papermario: src/battle/1A5830.c File Reference
1A5830.c File Reference
Functions
s32 has_enchanted_part (Actor *actor)
void dispatch_event_general (Actor *actor, s32 event)
void play_hit_sound (Actor *actor, f32 x, f32 y, f32 z, u32 hitSound)
void dispatch_event_actor (Actor *actor, s32 event)
HitResult calc_enemy_test_target (Actor *actor)
HitResult calc_enemy_damage_target (Actor *attacker)
s32 dispatch_damage_event_actor (Actor *actor, s32 damageAmount, s32 originalEvent, s32 stopMotion)
s32 dispatch_damage_event_actor_0 (Actor *actor, s32 damageAmount, s32 event)
s32 dispatch_damage_event_actor_1 (Actor *actor, s32 damageAmount, s32 event)
ApiStatus BindTakeTurn (Evt *script, s32 isInitialCall)
ApiStatus PauseTakeTurn (Evt *script, s32 isInitialCall)
ApiStatus ResumeTakeTurn (Evt *script, s32 isInitialCall)
ApiStatus BindIdle (Evt *script, s32 isInitialCall)
ApiStatus EnableIdleScript (Evt *script, s32 isInitialCall)
ApiStatus BindHandleEvent (Evt *script, s32 isInitialCall)
ApiStatus BindHandlePhase (Evt *script, s32 isInitialCall)
ApiStatus JumpToGoal (Evt *script, s32 isInitialCall)
ApiStatus IdleJumpToGoal (Evt *script, s32 isInitialCall)
ApiStatus JumpToGoalSimple2 (Evt *script, s32 isInitialCall)
ApiStatus JumpWithBounce (Evt *script, s32 isInitialCall)
ApiStatus LandJump (Evt *script, s32 isInitialCall)
ApiStatus FallToGoal (Evt *script, s32 isInitialCall)
ApiStatus RunToGoal (Evt *script, s32 isInitialCall)
ApiStatus IdleRunToGoal (Evt *script, s32 isInitialCall)
ApiStatus JumpPartTo (Evt *script, s32 isInitialCall)
ApiStatus FallPartTo (Evt *script, s32 isInitialCall)
ApiStatus LandJumpPart (Evt *script, s32 isInitialCall)
ApiStatus RunPartTo (Evt *script, s32 isInitialCall)
f32 update_lerp_battle (s32 easing, f32 start, f32 end, s32 elapsed, s32 duration)
ApiStatus FlyToGoal (Evt *script, s32 isInitialCall)
ApiStatus IdleFlyToGoal (Evt *script, s32 isInitialCall)
ApiStatus FlyPartTo (Evt *script, s32 isInitialCall)
ApiStatus GetLastEvent (Evt *script, s32 isInitialCall)
ApiStatus SetTargetActor (Evt *script, s32 isInitialCall)
ApiStatus SetEnemyHP (Evt *script, s32 isInitialCall)
ApiStatus GetActorHP (Evt *script, s32 isInitialCall)
ApiStatus GetEnemyMaxHP (Evt *script, s32 isInitialCall)
ApiStatus RemoveActor (Evt *script, s32 isInitialCall)
ApiStatus DropStarPoints (Evt *script, s32 isInitialCall)
ApiStatus SetDefenseTable (Evt *script, s32 isInitialCall)
ApiStatus SetStatusTable (Evt *script, s32 isInitialCall)
ApiStatus SetIdleAnimations (Evt *script, s32 isInitialCall)
ApiStatus func_8027CC10 (Evt *script, s32 isInitialCall)
ApiStatus EnemyDamageTarget (Evt *script, s32 isInitialCall)
ApiStatus EnemyFollowupAfflictTarget (Evt *script, s32 isInitialCall)
ApiStatus EnemyTestTarget (Evt *script, s32 isInitialCall)
ApiStatus DispatchDamageEvent (Evt *script, s32 isInitialCall)
ApiStatus DispatchEvent (Evt *script, s32 isInitialCall)
ApiStatus ShowHealthBar (Evt *script, s32 isInitialCall)
ApiStatus HideHealthBar (Evt *script, s32 isInitialCall)
ApiStatus SetTargetOffset (Evt *script, s32 isInitialCall)
ApiStatus func_8027D434 (Evt *script, s32 isInitialCall)
ApiStatus SetProjectileTargetOffset (Evt *script, s32 isInitialCall)
ApiStatus EnableActorBlur (Evt *script, s32 isInitialCall)
ApiStatus ForceDisableActorBlur (Evt *script, s32 isInitialCall)
ApiStatus AfflictActor (Evt *script, s32 isInitialCall)
ApiStatus GetInstigatorValue (Evt *script, s32 isInitialCall)
ApiStatus GetEncounterTrigger (Evt *script, s32 isInitialCall)
ApiStatus YieldTurn (Evt *script, s32 isInitialCall)
ApiStatus SetActorSize (Evt *script, s32 isInitialCall)
ApiStatus GetActorSize (Evt *script, s32 isInitialCall)
ApiStatus SetPartSize (Evt *script, s32 isInitialCall)
ApiStatus GetOriginalActorType (Evt *script, s32 isInitialCall)
ApiStatus GetCurrentActorType (Evt *script, s32 isInitialCall)
ApiStatus GetLastDamage (Evt *script, s32 isInitialCall)
ApiStatus EnableActorGlow (Evt *script, s32 isInitialCall)
ApiStatus WasStatusInflicted (Evt *script, s32 isInitialCall)
ApiStatus CopyStatusEffects (Evt *script, s32 isInitialCall)
ApiStatus ClearStatusEffects (Evt *script, s32 isInitialCall)
Variables
s32 D_802946E0 [] = { 100, 100, 100, 110, 130, 130, 130, 130, 130, 130, 130, 130, 130, 130, 130 }
Function Documentation
AfflictActor()
ApiStatus AfflictActor (Evt * script, s32 isInitialCall)
Bug
should be STATUS_TURN_MOD_FROZEN
BindHandleEvent()
ApiStatus BindHandleEvent (Evt * script, s32 isInitialCall)
BindHandlePhase()
ApiStatus BindHandlePhase (Evt * script, s32 isInitialCall)
BindIdle()
ApiStatus BindIdle (Evt * script, s32 isInitialCall)
BindTakeTurn()
ApiStatus BindTakeTurn (Evt * script, s32 isInitialCall)
calc_enemy_damage_target()
HitResult calc_enemy_damage_target (Actor * attacker)
Bug
? repeated paralyze and dizzy infliction
Referenced by EnemyDamageTarget(), and EnemyFollowupAfflictTarget().
calc_enemy_test_target()
HitResult calc_enemy_test_target (Actor * actor)
Referenced by EnemyTestTarget().
ClearStatusEffects()
ApiStatus ClearStatusEffects (Evt * script, s32 isInitialCall)
CopyStatusEffects()
ApiStatus CopyStatusEffects (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
dispatch_damage_event_actor()
s32 dispatch_damage_event_actor (Actor * actor, s32 damageAmount, s32 originalEvent, s32 stopMotion)
Referenced by dispatch_damage_event_actor_0(), and dispatch_damage_event_actor_1().
dispatch_damage_event_actor_0()
s32 dispatch_damage_event_actor_0 (Actor * actor, s32 damageAmount, s32 event)
Referenced by btl_state_update_9(), and DispatchDamageEvent().
dispatch_damage_event_actor_1()
s32 dispatch_damage_event_actor_1 (Actor * actor, s32 damageAmount, s32 event)
Referenced by calc_enemy_damage_target().
dispatch_event_actor()
void dispatch_event_actor (Actor * actor, s32 event)
Referenced by BoostAttack(), BoostDefense(), btl_state_update_9(), calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_partner_test_enemy(), calc_player_damage_enemy(), calc_player_test_enemy(), dispatch_damage_event_actor(), dispatch_event_general(), DispatchEvent(), ElectrifyActor(), HealActor(), and VanishActor().
dispatch_event_general()
void dispatch_event_general (Actor * actor, s32 event)
Referenced by calc_enemy_damage_target(), and calc_enemy_test_target().
DispatchDamageEvent()
ApiStatus DispatchDamageEvent (Evt * script, s32 isInitialCall)
DispatchEvent()
ApiStatus DispatchEvent (Evt * script, s32 isInitialCall)
DropStarPoints()
ApiStatus DropStarPoints (Evt * script, s32 isInitialCall)
EnableActorBlur()
ApiStatus EnableActorBlur (Evt * script, s32 isInitialCall)
EnableActorGlow()
ApiStatus EnableActorGlow (Evt * script, s32 isInitialCall)
EnableIdleScript()
ApiStatus EnableIdleScript (Evt * script, s32 isInitialCall)
EnemyDamageTarget()
ApiStatus EnemyDamageTarget (Evt * script, s32 isInitialCall)
EnemyFollowupAfflictTarget()
ApiStatus EnemyFollowupAfflictTarget (Evt * script, s32 isInitialCall)
EnemyTestTarget()
ApiStatus EnemyTestTarget (Evt * script, s32 isInitialCall)
FallPartTo()
ApiStatus FallPartTo (Evt * script, s32 isInitialCall)
FallToGoal()
ApiStatus FallToGoal (Evt * script, s32 isInitialCall)
FlyPartTo()
ApiStatus FlyPartTo (Evt * script, s32 isInitialCall)
FlyToGoal()
ApiStatus FlyToGoal (Evt * script, s32 isInitialCall)
ForceDisableActorBlur()
ApiStatus ForceDisableActorBlur (Evt * script, s32 isInitialCall)
func_8027CC10()
ApiStatus func_8027CC10 (Evt * script, s32 isInitialCall)
func_8027D434()
ApiStatus func_8027D434 (Evt * script, s32 isInitialCall)
GetActorHP()
ApiStatus GetActorHP (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
GetActorSize()
ApiStatus GetActorSize (Evt * script, s32 isInitialCall)
GetCurrentActorType()
ApiStatus GetCurrentActorType (Evt * script, s32 isInitialCall)
GetEncounterTrigger()
ApiStatus GetEncounterTrigger (Evt * script, s32 isInitialCall)
GetEnemyMaxHP()
ApiStatus GetEnemyMaxHP (Evt * script, s32 isInitialCall)
GetInstigatorValue()
ApiStatus GetInstigatorValue (Evt * script, s32 isInitialCall)
GetLastDamage()
ApiStatus GetLastDamage (Evt * script, s32 isInitialCall)
GetLastEvent()
ApiStatus GetLastEvent (Evt * script, s32 isInitialCall)
GetOriginalActorType()
ApiStatus GetOriginalActorType (Evt * script, s32 isInitialCall)
has_enchanted_part()
s32 has_enchanted_part (Actor * actor)
Referenced by calc_enemy_damage_target().
HideHealthBar()
ApiStatus HideHealthBar (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
IdleFlyToGoal()
ApiStatus IdleFlyToGoal (Evt * script, s32 isInitialCall)
IdleJumpToGoal()
ApiStatus IdleJumpToGoal (Evt * script, s32 isInitialCall)
IdleRunToGoal()
ApiStatus IdleRunToGoal (Evt * script, s32 isInitialCall)
JumpPartTo()
ApiStatus JumpPartTo (Evt * script, s32 isInitialCall)
JumpToGoal()
ApiStatus JumpToGoal (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
JumpToGoalSimple2()
ApiStatus JumpToGoalSimple2 (Evt * script, s32 isInitialCall)
JumpWithBounce()
ApiStatus JumpWithBounce (Evt * script, s32 isInitialCall)
LandJump()
ApiStatus LandJump (Evt * script, s32 isInitialCall)
LandJumpPart()
ApiStatus LandJumpPart (Evt * script, s32 isInitialCall)
PauseTakeTurn()
ApiStatus PauseTakeTurn (Evt * script, s32 isInitialCall)
play_hit_sound()
void play_hit_sound (Actor * actor, f32 x, f32 y, f32 z, u32 hitSound)
Referenced by calc_enemy_damage_target().
RemoveActor()
ApiStatus RemoveActor (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
ResumeTakeTurn()
ApiStatus ResumeTakeTurn (Evt * script, s32 isInitialCall)
RunPartTo()
ApiStatus RunPartTo (Evt * script, s32 isInitialCall)
RunToGoal()
ApiStatus RunToGoal (Evt * script, s32 isInitialCall)
Referenced by A().
SetActorSize()
ApiStatus SetActorSize (Evt * script, s32 isInitialCall)
SetDefenseTable()
ApiStatus SetDefenseTable (Evt * script, s32 isInitialCall)
SetEnemyHP()
ApiStatus SetEnemyHP (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetIdleAnimations()
ApiStatus SetIdleAnimations (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetPartSize()
ApiStatus SetPartSize (Evt * script, s32 isInitialCall)
SetProjectileTargetOffset()
ApiStatus SetProjectileTargetOffset (Evt * script, s32 isInitialCall)
SetStatusTable()
ApiStatus SetStatusTable (Evt * script, s32 isInitialCall)
SetTargetActor()
ApiStatus SetTargetActor (Evt * script, s32 isInitialCall)
SetTargetOffset()
ApiStatus SetTargetOffset (Evt * script, s32 isInitialCall)
ShowHealthBar()
ApiStatus ShowHealthBar (Evt * script, s32 isInitialCall)
update_lerp_battle()
f32 update_lerp_battle (s32 easing, f32 start, f32 end, s32 elapsed, s32 duration)
Referenced by FlyPartTo(), FlyToGoal(), and IdleFlyToGoal().
WasStatusInflicted()
ApiStatus WasStatusInflicted (Evt * script, s32 isInitialCall)
YieldTurn()
ApiStatus YieldTurn (Evt * script, s32 isInitialCall)
Variable Documentation
D_802946E0
s32 D_802946E0[] = { 100, 100, 100, 110, 130, 130, 130, 130, 130, 130, 130, 130, 130, 130, 130 }
Referenced by DropStarPoints().