papermario: src/23680.c File Reference
23680.c File Reference
Functions
void spawn_drops (Enemy *enemy)
s32 get_coin_drop_amount (Enemy *enemy)
void func_80048E34 (Enemy *enemy, s32 arg1, s32 arg2)
s32 func_80048F0C (void)
s32 is_point_within_region (s32 shape, f32 pointX, f32 pointY, f32 centerX, f32 centerY, f32 sizeX, f32 sizeZ)
s32 basic_ai_check_player_dist (EnemyDetectVolume *territory, Enemy *enemy, f32 radius, f32 fwdPosOffset, s8 useWorldYaw)
s32 ai_check_player_dist (Enemy *enemy, s32 chance, f32 radius, f32 moveSpeed)
void ai_enemy_play_sound (Npc *npc, s32 soundID, s32 upperSoundFlags)
void ai_try_set_state (Evt *script, s32 state)
void basic_ai_wander_init (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_wander (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void basic_ai_loiter_init (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void basic_ai_loiter (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void basic_ai_found_player_jump_init (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_found_player_jump (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_chase_init (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_chase (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void basic_ai_lose_player (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
ApiStatus BasicAI_Main (Evt *script, s32 isInitialCall)
Variables
s32 gLastRenderTaskCount
Function Documentation
ai_check_player_dist()
s32 ai_check_player_dist (Enemy * enemy, s32 chance, f32 radius, f32 moveSpeed)
Referenced by CleftAI_CanSeePlayer(), and ProjectileHitbox_GetUsableProjectileID().
ai_enemy_play_sound()
void ai_enemy_play_sound (Npc * npc, s32 soundID, s32 upperSoundFlags)
Referenced by basic_ai_chase(), basic_ai_found_player_jump_init(), basic_ai_loiter(), basic_ai_wander(), CleftAI_Hiding(), ClubbaNappingAI_Sleep(), FlyingAI_Loiter(), FlyingAI_Wander(), FlyingMagikoopaAI_11(), FlyingMagikoopaAI_21(), FlyingMagikoopaAI_23(), func_80045838(), GuardAI_Idle(), GuardAI_ReturnHome(), HoppingAI_ChaseInit(), HoppingAI_Hop(), HoppingAI_HopInit(), HoppingAI_Loiter(), LakituAI_Loiter(), LakituAI_Wander(), MagikoopaAI_21(), MagikoopaAI_23(), ParatroopaAI_Windup(), PatrolAI_Loiter(), PatrolAI_Move(), PiranhaPlantAI_01(), PiranhaPlantAI_10(), and SentinelAI_ReturnHome().
ai_try_set_state()
void ai_try_set_state (Evt * script, s32 state)
basic_ai_chase()
void basic_ai_chase (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by BasicAI_Main(), CleftAI_Main(), SpearGuyAI_Main(), and WanderMeleeAI_Main().
basic_ai_chase_init()
void basic_ai_chase_init (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
Referenced by BasicAI_Main(), CleftAI_Main(), HoppingAI_ChaseInit(), SpearGuyAI_Main(), StoneChompAI_ChaseInit(), and WanderMeleeAI_Main().
basic_ai_check_player_dist()
s32 basic_ai_check_player_dist (EnemyDetectVolume * territory, Enemy * enemy, f32 radius, f32 fwdPosOffset, s8 useWorldYaw)
Referenced by AvoidPlayerAI_Chase(), AvoidPlayerAI_ChaseInit(), basic_ai_chase(), basic_ai_loiter(), basic_ai_wander(), CleftAI_FindPlayer(), CleftAI_Hiding(), CleftAI_ReturnHome(), ClubbaNappingAI_Loiter(), ClubbaNappingAI_ReturnHome(), ClubbaNappingAI_Sleep(), FlyingAI_Loiter(), FlyingAI_Wander(), FlyingNoAttackAI_13(), GuardAI_Chase(), GuardAI_Idle(), GuardAI_ReturnHome(), HoppingAI_Chase(), HoppingAI_Hop(), HoppingAI_Loiter(), LakituAI_Loiter(), LakituAI_Wander(), MagikoopaAI_CanShootSpell(), PatrolAI_Chase(), PatrolAI_Loiter(), PatrolAI_Move(), PiranhaPlantAI_01(), PiranhaPlantAI_LosePlayer(), SentinelAI_Chase(), SentinelAI_Descend(), SentinelAI_ReturnHome(), and UnkNpcAIFunc48().
basic_ai_found_player_jump()
void basic_ai_found_player_jump (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
Referenced by BasicAI_Main(), SpearGuyAI_Main(), and WanderMeleeAI_Main().
basic_ai_found_player_jump_init()
void basic_ai_found_player_jump_init (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
Referenced by BasicAI_Main(), SpearGuyAI_Main(), and WanderMeleeAI_Main().
basic_ai_loiter()
void basic_ai_loiter (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by BasicAI_Main(), and WanderMeleeAI_Main().
basic_ai_loiter_init()
void basic_ai_loiter_init (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by BasicAI_Main(), and WanderMeleeAI_Main().
basic_ai_lose_player()
void basic_ai_lose_player (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
Referenced by BasicAI_Main(), SpearGuyAI_Main(), and WanderMeleeAI_Main().
basic_ai_wander()
void basic_ai_wander (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by BasicAI_Main(), SpearGuyAI_Main(), and WanderMeleeAI_Main().
basic_ai_wander_init()
void basic_ai_wander_init (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
Referenced by BasicAI_Main(), HoppingAI_HopInit(), SpearGuyAI_Main(), StoneChompAI_HopInit(), and WanderMeleeAI_Main().
BasicAI_Main()
ApiStatus BasicAI_Main (Evt * script, s32 isInitialCall)
func_80048E34()
void func_80048E34 (Enemy * enemy, s32 arg1, s32 arg2)
func_80048F0C()
s32 func_80048F0C (void)
get_coin_drop_amount()
s32 get_coin_drop_amount (Enemy * enemy)
Referenced by update_encounters_post_battle().
is_point_within_region()
s32 is_point_within_region (s32 shape, f32 pointX, f32 pointY, f32 centerX, f32 centerY, f32 sizeX, f32 sizeZ)
Referenced by basic_ai_check_player_dist(), basic_ai_wander(), CleftAI_Tackle(), FlyingAI_Wander(), FlyingAI_WanderInit(), FlyingMagikoopaAI_15(), HoppingAI_HopInit(), LakituAI_Wander(), and PiranhaPlantAI_10().
spawn_drops()
void spawn_drops (Enemy * enemy)
Referenced by OnDefeatEnemy().
Variable Documentation
gLastRenderTaskCount
s32 gLastRenderTaskCount extern
Referenced by execute_render_tasks(), and spawn_drops().