papermario: src/25AF0.c File Reference
25AF0.c File Reference
Functions
void ai_suspend_for_time (Evt *script)
void basic_ai_suspend (Evt *script)
b32 ai_check_fwd_collisions (Npc *npc, f32 time, f32 *outYaw, f32 *outDistFwd, f32 *outDistCW, f32 *outDistCCW)
Function Documentation
ai_check_fwd_collisions()
b32 ai_check_fwd_collisions (Npc * npc, f32 time, f32 * outYaw, f32 * outDistFwd, f32 * outDistCW, f32 * outDistCCW)
Referenced by basic_ai_wander(), ClubbaNappingAI_ReturnHome(), ShyGuyPatrolAI_15(), ShyGuyPatrolAI_16(), ShyGuyWanderAI_15(), and ShyGuyWanderAI_16().
ai_suspend_for_time()
void ai_suspend_for_time (Evt * script)
basic_ai_suspend()
void basic_ai_suspend (Evt * script)