papermario: src/audio/28910_len_5090.c File Reference
28910_len_5090.c File Reference
Macros
#define POST_BGM_READ()
Functions
void au_bgm_update_main (BGMPlayer *player)
BGMPlayer * au_bgm_get_player_with_song_name (s32 songString)
AuResult au_bgm_dispatch_player_event (SongUpdateEvent *event)
AuResult au_bgm_stop_song (s32 songName)
void au_bgm_stop_all (void)
AuResult au_bgm_is_song_playing (s32 songName)
s32 func_8004DB28 (BGMPlayer *player)
AuResult func_8004DB4C (SongUpdateEvent *s)
AuResult func_8004DC80 (s32 songName)
AuResult func_8004DCB8 (SongUpdateEvent *update, s32 clearChanged)
AuResult func_8004DE2C (SongUpdateEvent *update)
void func_8004DFD4 (AuGlobals *globals)
AuResult func_8004E0F4 (SongUpdateEvent *update)
void au_bgm_player_init (BGMPlayer *player, s32 priority, s32 busId, AuGlobals *globals)
void au_bgm_set_effect_indices (BGMPlayer *player, u8 *list)
void au_bgm_update_fade (BGMPlayer *player)
void func_8004E444 (BGMPlayer *arg0)
s32 au_bgm_player_update_main (BGMPlayer *player)
void au_bgm_player_initialize (BGMPlayer *player)
void func_8004E844 (BGMPlayer *player, s32 arg1)
void func_8004E880 (BGMPlayer *player, s32 sampleRate, s32 divisor)
void au_bgm_player_read_segment (BGMPlayer *player)
void au_bgm_end_segment_loop (BGMPlayer *player, u32 cmd)
void au_bgm_load_subsegment (BGMPlayer *player, u32 cmd)
void au_bgm_player_update_stop (BGMPlayer *player)
void au_bgm_player_update_playing (BGMPlayer *player)
void au_BGMCmd_E0_MasterTempo (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E1_MasterVolume (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E2_MasterPitchShift (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E3 (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E6_MasterEffect (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E4_MasterTempoFade (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E5_MasterVolumeFade (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E8_TrackOverridePatch (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E9_SubTrackVolume (BGMPlayer *arg0, BGMPlayerTrack *track)
void au_BGMCmd_F6_TrackVolumeFade (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EA_SubTrackPan (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EB_SubTrackReverb (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EC_SegTrackVolume (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_ED_SubTrackCoarseTune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EE_SubTrackFineTune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EF_SegTrackTune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F0_TrackTremolo (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F1_TrackTremoloSpeed (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F2_TrackTremoloTime (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F3_TrackTremoloStop (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F4 (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F5_TrackVoice (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F7_SubTrackReverbType (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FD_EventTrigger (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FE_Detour (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FC_Jump (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FF (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_NOP (BGMPlayer *player, BGMPlayerTrack *track)
void au_bgm_set_proximity_mix (s32 songName, u32 mix)
void au_bgm_set_playback_rate (BGMPlayer *player, f32 rate)
void au_bgm_player_set_detune (BGMPlayer *player, s32 detune)
void au_bgm_change_track_volume (BGMPlayer *player, s32 trackIdx, s16 time, u8 volume)
void au_bgm_set_track_volumes (BGMPlayer *player, u8 *trackVols, s32 mode)
void func_80050888 (BGMPlayer *player, BGMPlayerTrack *track, s32 target, s32 duration)
void func_80050900 (BGMPlayer *player)
AuResult func_80050970 (SongUpdateEvent *update)
Variables
BSS void(* CurrentSeqCmdHandler)(BGMPlayer *, BGMPlayerTrack *)
u8 EnvelopeReleaseDefaultFast []
u8 BgmDivisors [8]
u8 D_80078558 [40]
void(* SefCmdHandlers [])(SoundManager *, SoundPlayer *)
void(* SeqCmdHandlers [])(BGMPlayer *, BGMPlayerTrack *)
u8 SeqCmdArgCounts []
Macro Definition Documentation
POST_BGM_READ
#define POST_BGM_READ ()
Value:
if (track->detourLength != 0) {\
    track->detourLength--;\
    if (track->detourLength == 0) {\
        track->bgmReadPos = track->savedPos;\
    }\
}
Referenced by au_bgm_player_update_playing().
Function Documentation
au_bgm_change_track_volume()
void au_bgm_change_track_volume (BGMPlayer * player, s32 trackIdx, s16 time, u8 volume)
au_bgm_dispatch_player_event()
AuResult au_bgm_dispatch_player_event (SongUpdateEvent * event)
Referenced by au_song_start(), au_song_start_variation(), snd_set_song_fade(), and snd_set_song_variation_fade().
au_bgm_end_segment_loop()
void au_bgm_end_segment_loop (BGMPlayer * player, u32 cmd)
Referenced by au_bgm_player_read_segment().
au_bgm_get_player_with_song_name()
BGMPlayer * au_bgm_get_player_with_song_name (s32 songString)
Referenced by au_bgm_dispatch_player_event(), au_bgm_is_song_playing(), au_bgm_set_proximity_mix(), au_bgm_stop_song(), func_8004DB4C(), func_8004DCB8(), func_8004DE2C(), func_8004E0F4(), and func_80050970().
au_bgm_is_song_playing()
AuResult au_bgm_is_song_playing (s32 songName)
Referenced by au_song_is_playing().
au_bgm_load_subsegment()
void au_bgm_load_subsegment (BGMPlayer * player, u32 cmd)
Referenced by au_bgm_player_read_segment().
au_bgm_player_init()
void au_bgm_player_init (BGMPlayer * player, s32 priority, s32 busId, AuGlobals * globals)
Referenced by au_engine_init().
au_bgm_player_initialize()
void au_bgm_player_initialize (BGMPlayer * player)
Referenced by au_bgm_dispatch_player_event(), and au_bgm_player_update_main().
au_bgm_player_read_segment()
void au_bgm_player_read_segment (BGMPlayer * player)
Referenced by au_bgm_player_update_main().
au_bgm_player_set_detune()
void au_bgm_player_set_detune (BGMPlayer * player, s32 detune)
Referenced by snd_song_set_detune().
au_bgm_player_update_main()
s32 au_bgm_player_update_main (BGMPlayer * player)
Referenced by au_update_clients_2().
au_bgm_player_update_playing()
void au_bgm_player_update_playing (BGMPlayer * player)
Referenced by au_bgm_player_update_main().
au_bgm_player_update_stop()
void au_bgm_player_update_stop (BGMPlayer * player)
Referenced by au_bgm_player_update_main().
au_bgm_set_effect_indices()
void au_bgm_set_effect_indices (BGMPlayer * player, u8 * list)
Referenced by au_engine_init().
au_bgm_set_playback_rate()
void au_bgm_set_playback_rate (BGMPlayer * player, f32 rate)
Referenced by snd_song_set_playback_rate().
au_bgm_set_proximity_mix()
void au_bgm_set_proximity_mix (s32 songName, u32 mix)
Referenced by bgm_set_proximity_mix_far(), bgm_set_proximity_mix_full(), and bgm_set_proximity_mix_near().
au_bgm_set_track_volumes()
void au_bgm_set_track_volumes (BGMPlayer * player, u8 * trackVols, s32 mode)
Referenced by snd_song_clear_track_volumes(), and snd_song_set_track_volumes().
au_bgm_stop_all()
void au_bgm_stop_all (void)
Referenced by au_stop_songs().
au_bgm_stop_song()
AuResult au_bgm_stop_song (s32 songName)
Referenced by au_song_stop().
au_bgm_update_fade()
void au_bgm_update_fade (BGMPlayer * player)
Referenced by au_update_clients_2().
au_bgm_update_main()
void au_bgm_update_main (BGMPlayer * player)
Referenced by au_update_players_main().
au_BGMCmd_E0_MasterTempo()
void au_BGMCmd_E0_MasterTempo (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E1_MasterVolume()
void au_BGMCmd_E1_MasterVolume (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E2_MasterPitchShift()
void au_BGMCmd_E2_MasterPitchShift (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E3()
void au_BGMCmd_E3 (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E4_MasterTempoFade()
void au_BGMCmd_E4_MasterTempoFade (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E5_MasterVolumeFade()
void au_BGMCmd_E5_MasterVolumeFade (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E6_MasterEffect()
void au_BGMCmd_E6_MasterEffect (BGMPlayer * player, BGMPlayerTrack * track)
Referenced by func_8004DFD4().
au_BGMCmd_E8_TrackOverridePatch()
void au_BGMCmd_E8_TrackOverridePatch (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E9_SubTrackVolume()
void au_BGMCmd_E9_SubTrackVolume (BGMPlayer * arg0, BGMPlayerTrack * track)
Referenced by func_80050970().
au_BGMCmd_EA_SubTrackPan()
void au_BGMCmd_EA_SubTrackPan (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EB_SubTrackReverb()
void au_BGMCmd_EB_SubTrackReverb (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EC_SegTrackVolume()
void au_BGMCmd_EC_SegTrackVolume (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_ED_SubTrackCoarseTune()
void au_BGMCmd_ED_SubTrackCoarseTune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EE_SubTrackFineTune()
void au_BGMCmd_EE_SubTrackFineTune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EF_SegTrackTune()
void au_BGMCmd_EF_SegTrackTune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F0_TrackTremolo()
void au_BGMCmd_F0_TrackTremolo (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F1_TrackTremoloSpeed()
void au_BGMCmd_F1_TrackTremoloSpeed (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F2_TrackTremoloTime()
void au_BGMCmd_F2_TrackTremoloTime (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F3_TrackTremoloStop()
void au_BGMCmd_F3_TrackTremoloStop (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F4()
void au_BGMCmd_F4 (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F5_TrackVoice()
void au_BGMCmd_F5_TrackVoice (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F6_TrackVolumeFade()
void au_BGMCmd_F6_TrackVolumeFade (BGMPlayer * player, BGMPlayerTrack * track)
Referenced by au_bgm_change_track_volume(), au_bgm_player_update_playing(), and func_80050970().
au_BGMCmd_F7_SubTrackReverbType()
void au_BGMCmd_F7_SubTrackReverbType (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FC_Jump()
void au_BGMCmd_FC_Jump (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FD_EventTrigger()
void au_BGMCmd_FD_EventTrigger (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FE_Detour()
void au_BGMCmd_FE_Detour (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FF()
void au_BGMCmd_FF (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_NOP()
void au_BGMCmd_NOP (BGMPlayer * player, BGMPlayerTrack * track)
func_8004DB28()
s32 func_8004DB28 (BGMPlayer * player)
Referenced by au_load_song_files(), and func_8004DE2C().
func_8004DB4C()
AuResult func_8004DB4C (SongUpdateEvent * s)
Referenced by func_80055BB8(), and snd_set_song_variation_fade_time().
func_8004DC80()
AuResult func_8004DC80 (s32 songName)
Referenced by au_bgm_update_fade().
func_8004DCB8()
AuResult func_8004DCB8 (SongUpdateEvent * update, s32 clearChanged)
Referenced by func_8004DC80(), func_80055AF0(), func_80055B80(), and func_80055BF0().
func_8004DE2C()
AuResult func_8004DE2C (SongUpdateEvent * update)
Referenced by func_80055B28(), and func_80055C2C().
func_8004DFD4()
void func_8004DFD4 (AuGlobals * globals)
Referenced by au_update_clients_2().
func_8004E0F4()
AuResult func_8004E0F4 (SongUpdateEvent * update)
Referenced by func_80055C64(), and func_80055C94().
func_8004E444()
void func_8004E444 (BGMPlayer * arg0)
Referenced by au_bgm_update_fade(), and au_update_clients_2().
func_8004E844()
void func_8004E844 (BGMPlayer * player, s32 arg1)
Referenced by au_bgm_player_initialize(), and au_BGMCmd_FF().
func_8004E880()
void func_8004E880 (BGMPlayer * player, s32 sampleRate, s32 divisor)
Referenced by au_bgm_dispatch_player_event(), au_bgm_player_init(), and au_bgm_update_main().
func_80050888()
void func_80050888 (BGMPlayer * player, BGMPlayerTrack * track, s32 target, s32 duration)
Referenced by au_BGMCmd_FC_Jump(), and au_BGMCmd_FF().
func_80050900()
void func_80050900 (BGMPlayer * player)
Referenced by au_bgm_player_initialize(), au_bgm_player_update_stop(), and func_8004DCB8().
func_80050970()
AuResult func_80050970 (SongUpdateEvent * update)
Referenced by snd_set_song_variation().
Variable Documentation
BgmDivisors
u8 BgmDivisors[8] extern
Referenced by au_bgm_dispatch_player_event(), and au_bgm_update_main().
CurrentSeqCmdHandler
BSS void(* CurrentSeqCmdHandler) (BGMPlayer *, BGMPlayerTrack *) (BGMPlayer * , BGMPlayerTrack *)
Referenced by au_bgm_player_update_playing().
D_80078558
u8 D_80078558[40] extern
Referenced by au_BGMCmd_FF().
EnvelopeReleaseDefaultFast
u8 EnvelopeReleaseDefaultFast[] extern
Referenced by func_80050970().
SefCmdHandlers
void(* SefCmdHandlers[])(SoundManager *, SoundPlayer *) (SoundManager * , SoundPlayer *) extern
SeqCmdArgCounts
u8 SeqCmdArgCounts[] extern
Referenced by au_bgm_player_update_playing().
SeqCmdHandlers
void(* SeqCmdHandlers[])(BGMPlayer *, BGMPlayerTrack *) (BGMPlayer * , BGMPlayerTrack *) extern
Referenced by au_bgm_player_update_playing().