papermario: src/audio/2BF90.c File Reference
2BF90.c File Reference
Macros
#define TRACK_ID_DRUM 9
Enumerations
enum AmbientMode { AMB_MODE_NORMAL = 0 , AMB_MODE_RESUMING = 1 , AMB_MODE_STOPPED = 2 , AMB_MODE_PAUSING = 3 }
enum AmbientFadeState { AMB_FADE_IN = 0 , AMB_FADE_OUT = 1 , AMB_FADE_OUT_PAUSING = 2 }
enum AmbientPlayState { AMB_PLAYER_PLAYING = 0 , AMB_PLAYER_STOPPED = 1 , AMB_PLAYER_STOPPING = 2 }
enum MSEQCommand {
MSEQ_CMD_80_STOP_SOUND = 0x80 , MSEQ_CMD_90_PLAY_SOUND = 0x90 , MSEQ_CMD_A0_SET_VOLUME_PAN = 0xA0 , MSEQ_CMD_B0_MULTI = 0xB0 ,
MSEQ_CMD_C0_SET_INSTRUMENT = 0xC0 , MSEQ_CMD_E0_TUNING = 0xE0 , MSEQ_CMD_SUB_66_START_LOOP = 0x66 , MSEQ_CMD_SUB_67_END_LOOP = 0x67 ,
MSEQ_CMD_SUB_68_SET_REVERB = 0x68 , MSEQ_CMD_SUB_69_SET_RESUMABLE = 0x69
}
Functions
void au_amb_manager_init (AmbienceManager *manager, s8 priority, s8 busId, AuGlobals *globals)
AuResult au_amb_check_player_index (u32 index)
void au_amb_load_tracks_fade (s32 arg0, s32 arg1)
void au_amb_set_disabled (s32 index, s32 disable)
AuResult au_amb_start (s32 index, s32 time)
void au_amb_fade_setup (AmbiencePlayer *player)
void au_amb_pause (s32 index, s32 time)
void au_amb_resume (s32 index, s32 time)
void au_amb_stop_quick (s32 index)
void au_amb_stop_slow (s32 index, s32 time)
void au_amb_set_volume (s32 index, s32 time, s32 volume)
AuResult au_amb_is_stopped (s32 index)
void au_amb_play_sequence (AmbienceManager *manager, MSEQHeader *mseqFile, s32 index)
void au_amb_manager_update (AmbienceManager *manager)
void au_amb_load_track_fade_info (AmbienceManager *manager, AmbiencePlayer *player)
void au_amb_player_update (AmbienceManager *manager, AmbiencePlayer *player)
u8 au_amb_read_next (AmbiencePlayer *state)
void au_amb_player_stop (AmbienceManager *manager, AmbiencePlayer *player)
void au_amb_save_voices (AmbienceManager *arg0, AmbiencePlayer *player)
void au_amb_restore_voices (AmbienceManager *manager, AmbiencePlayer *player)
Variables
u8 BlankMseqData []
Macro Definition Documentation
TRACK_ID_DRUM
#define TRACK_ID_DRUM 9
Referenced by au_amb_player_update().
Enumeration Type Documentation
AmbientFadeState
enum AmbientFadeState
Enumerator
AMB_FADE_IN
AMB_FADE_OUT
AMB_FADE_OUT_PAUSING
AmbientMode
enum AmbientMode
Enumerator
AMB_MODE_NORMAL
AMB_MODE_RESUMING
AMB_MODE_STOPPED
AMB_MODE_PAUSING
AmbientPlayState
enum AmbientPlayState
Enumerator
AMB_PLAYER_PLAYING
AMB_PLAYER_STOPPED
AMB_PLAYER_STOPPING
MSEQCommand
enum MSEQCommand
Enumerator
MSEQ_CMD_80_STOP_SOUND
MSEQ_CMD_90_PLAY_SOUND
MSEQ_CMD_A0_SET_VOLUME_PAN
MSEQ_CMD_B0_MULTI
MSEQ_CMD_C0_SET_INSTRUMENT
MSEQ_CMD_E0_TUNING
MSEQ_CMD_SUB_66_START_LOOP
MSEQ_CMD_SUB_67_END_LOOP
MSEQ_CMD_SUB_68_SET_REVERB
MSEQ_CMD_SUB_69_SET_RESUMABLE
Function Documentation
au_amb_check_player_index()
AuResult au_amb_check_player_index (u32 index)
Referenced by snd_ambient_disable(), snd_ambient_enable(), snd_ambient_is_stopped(), snd_ambient_mute(), snd_ambient_pause(), snd_ambient_play(), snd_ambient_resume(), snd_ambient_set_volume(), snd_ambient_stop_quick(), and snd_ambient_stop_slow().
au_amb_fade_setup()
void au_amb_fade_setup (AmbiencePlayer * player)
Referenced by au_amb_manager_update(), and au_amb_start().
au_amb_is_stopped()
AuResult au_amb_is_stopped (s32 index)
Referenced by snd_ambient_is_stopped().
au_amb_load_track_fade_info()
void au_amb_load_track_fade_info (AmbienceManager * manager, AmbiencePlayer * player)
Referenced by au_amb_manager_update().
au_amb_load_tracks_fade()
void au_amb_load_tracks_fade (s32 arg0, s32 arg1)
Referenced by snd_ambient_mute().
au_amb_manager_init()
void au_amb_manager_init (AmbienceManager * manager, s8 priority, s8 busId, AuGlobals * globals)
Referenced by au_engine_init().
au_amb_manager_update()
void au_amb_manager_update (AmbienceManager * manager)
Referenced by au_update_clients_2().
au_amb_pause()
void au_amb_pause (s32 index, s32 time)
Referenced by snd_ambient_pause().
au_amb_play_sequence()
void au_amb_play_sequence (AmbienceManager * manager, MSEQHeader * mseqFile, s32 index)
Referenced by au_amb_start().
au_amb_player_stop()
void au_amb_player_stop (AmbienceManager * manager, AmbiencePlayer * player)
Referenced by au_amb_manager_update(), and au_amb_player_update().
au_amb_player_update()
void au_amb_player_update (AmbienceManager * manager, AmbiencePlayer * player)
Referenced by au_amb_manager_update().
au_amb_read_next()
u8 au_amb_read_next (AmbiencePlayer * state)
Referenced by au_amb_player_update().
au_amb_restore_voices()
void au_amb_restore_voices (AmbienceManager * manager, AmbiencePlayer * player)
Referenced by au_amb_manager_update().
au_amb_resume()
void au_amb_resume (s32 index, s32 time)
Referenced by snd_ambient_resume().
au_amb_save_voices()
void au_amb_save_voices (AmbienceManager * arg0, AmbiencePlayer * player)
Referenced by au_amb_manager_update().
au_amb_set_disabled()
void au_amb_set_disabled (s32 index, s32 disable)
Referenced by snd_ambient_disable(), and snd_ambient_enable().
au_amb_set_volume()
void au_amb_set_volume (s32 index, s32 time, s32 volume)
Referenced by snd_ambient_set_volume().
au_amb_start()
AuResult au_amb_start (s32 index, s32 time)
Referenced by snd_ambient_play().
au_amb_stop_quick()
void au_amb_stop_quick (s32 index)
Referenced by snd_ambient_stop_quick().
au_amb_stop_slow()
void au_amb_stop_slow (s32 index, s32 time)
Referenced by snd_ambient_stop_slow().
Variable Documentation
BlankMseqData
u8 BlankMseqData[] extern
Referenced by au_amb_player_update(), and au_amb_stop_quick().