papermario: src/audio/2d9a0_len_890.c File Reference
2d9a0_len_890.c File Reference
Functions
void au_update_stopped_voices (AuGlobals *globals)
void au_init_voices (AuGlobals *globals)
void au_update_voices (AuGlobals *globals)
void au_voice_after_volume_change (AuVoice *voice)
s32 au_voice_get_delta (s32 msecs)
void au_voice_start (AuVoice *voice, EnvelopeData *envData)
u8 au_voice_step (AuVoice *voice)
void au_voice_set_vol_changed (AuVoice *voice)
Function Documentation
au_init_voices()
void au_init_voices (AuGlobals * globals)
Referenced by au_engine_init().
au_update_stopped_voices()
void au_update_stopped_voices (AuGlobals * globals)
au_update_voices()
void au_update_voices (AuGlobals * globals)
Referenced by au_update_clients_2().
au_voice_after_volume_change()
void au_voice_after_volume_change (AuVoice * voice)
Referenced by au_update_voices().
au_voice_get_delta()
s32 au_voice_get_delta (s32 msecs)
Referenced by au_update_voices(), au_voice_after_volume_change(), and au_voice_start().
au_voice_set_vol_changed()
void au_voice_set_vol_changed (AuVoice * voice)
au_voice_start()
void au_voice_start (AuVoice * voice, EnvelopeData * envData)
Referenced by au_syn_update().
au_voice_step()
u8 au_voice_step (AuVoice * voice)
Referenced by au_update_voices(), and au_voice_start().