papermario: src/audio/2e230_len_2190.c File Reference
2e230_len_2190.c File Reference
Macros
#define SBN_ROM_OFFSET 0xF00000
#define TUNE_SCALING_ARR_AMPLIFY_FINE 0
#define TUNE_SCALING_ARR_AMPLIFY_COARSE 128
#define TUNE_SCALING_ARR_ATTENUATE_FINE 160
#define TUNE_SCALING_ARR_ATTENUATE_COARSE 288
#define SBN_LOOKUP(i, fmt, e) (au_fetch_SBN_file(globals->mseqFileList[AmbientSoundIDtoMSEQFileIndex[i]], fmt, &e))
#define AL_HEADER_SIG_BK 0x424B
#define AL_HEADER_SIG_CR 0x4352
#define AL_HEADER_SIG_DR 0x4452
#define AL_HEADER_SIG_SR 0x5352
Enumerations
enum BKParseState {
BK_READ_DONE = 0 , BK_READ_FETCH_HEADER = 11 , BK_READ_FETCH_DATA = 21 , BK_READ_SWIZZLE = 31 ,
BK_READ_PROCESS_CR = 101 , BK_READ_SWIZZLE_CR = 111 , BK_READ_PROCESS_DR = 201 , BK_READ_UNK_DR = 211 ,
BK_READ_PROCESS_SR = 301 , BK_READ_UNK_SR = 311
}
Functions
void func_80052E30 (u8 index)
void au_engine_init (s32 outputRate)
void au_update_clients_2 (void)
void au_update_players_main (void)
void au_syn_update (AuGlobals *globals)
void au_reset_nonfree_voice (AuVoice *voice, u8 index)
void au_reset_voice (AuVoice *voice, u8 voiceIdx)
f32 au_compute_pitch_ratio (s32 pitch)
void au_fade_init (Fade *fade, s32 time, s32 startValue, s32 endValue)
void au_fade_clear (Fade *fade)
void au_fade_update (Fade *fade)
void au_fade_set_volume (u8 busId, u16 volume, s32 busVolume)
void func_80053AC8 (Fade *fade)
void au_fade_set_vol_scale (Fade *fade, s16 value)
void func_80053B04 (Fade *fade, u32 arg1, s32 target)
void func_80053BA8 (Fade *fade)
Instrument * au_get_instrument (AuGlobals *globals, u32 bank, u32 patch, EnvelopeData *envData)
void au_get_bgm_player_and_file (u32 playerIndex, BGMHeader **outFile, BGMPlayer **outPlayer)
void au_get_bgm_player (u32 playerIndex, BGMPlayer **outPlayer)
AuResult au_load_song_files (u32 songID, BGMHeader *bgmFile, BGMPlayer *player)
AuResult func_80053E58 (s32 songID, BGMHeader *bgmFile)
BGMPlayer * func_80053F64 (s32 arg0)
AuResult au_ambient_load (u32 ambSoundID)
BGMPlayer * func_80054248 (u8 arg0)
void au_load_INIT (AuGlobals *arg0, s32 romAddr, ALHeap *heap)
AuResult au_fetch_SBN_file (u32 fileIdx, AuFileFormat format, SBNFileEntry *outEntry)
void au_load_PER (AuGlobals *globals, s32 romAddr)
void au_load_PRG (AuGlobals *arg0, s32 romAddr)
s32 snd_load_BGM (s32 arg0)
InstrumentGroup * au_get_BK_instruments (s32 bankGroup, u32 bankIndex)
SoundBank * au_load_BK_to_bank (s32 bkFileOffset, SoundBank *bank, s32 bankIndex, s32 bankGroup)
void au_swizzle_BK_instruments (s32 bkFileOffset, SoundBank *bank, InstrumentGroup instruments, u32 instrumentCount, u8 arg4)
s32 * func_80054AA0 (s32 *bkFileOffset, void *vaddr, s32 bankIndex, s32 bankGroup)
s32 snd_load_BK (s32 bkFileOffset, s32 bankIndex)
void func_80054C84 (s32 bankIndex, s32 bankGroup)
void func_80054CE0 (s32 arg0, u32 idx)
s32 func_80054D74 (s32 arg0, s32 arg1)
void func_80054DA8 (u32 bMonoSound)
void au_read_rom (s32 romAddr, void *buffer, u32 size)
void au_memset (void *dst, s32 size, u8 value)
void au_copy_bytes (s8 *src, s8 *dest, s32 size)
void au_copy_words (void *src, void *dst, s32 size)
Variables
AuCallback BeginSoundUpdateCallback
BGMPlayer * gBGMPlayerA
BGMPlayer * gBGMPlayerB
BGMPlayer * gBGMPlayerC
SoundManager * gSoundManager
AuGlobals * gSoundGlobals
AmbienceManager * gAuAmbienceManager
u16 D_80078530 [9]
u8 EnvelopePressDefault []
u8 EnvelopeReleaseDefault []
f32 AlTuneScaling []
Macro Definition Documentation
AL_HEADER_SIG_BK
#define AL_HEADER_SIG_BK 0x424B
Referenced by au_load_BK_to_bank(), and func_80054AA0().
AL_HEADER_SIG_CR
#define AL_HEADER_SIG_CR 0x4352
Referenced by au_load_BK_to_bank(), and func_80054AA0().
AL_HEADER_SIG_DR
#define AL_HEADER_SIG_DR 0x4452
Referenced by au_load_BK_to_bank().
AL_HEADER_SIG_SR
#define AL_HEADER_SIG_SR 0x5352
Referenced by au_load_BK_to_bank().
SBN_LOOKUP
#define SBN_LOOKUP (i, fmt, e) (au_fetch_SBN_file(globals->mseqFileList[AmbientSoundIDtoMSEQFileIndex[i]], fmt, &e))
Referenced by au_ambient_load().
SBN_ROM_OFFSET
#define SBN_ROM_OFFSET 0xF00000
Referenced by au_engine_init().
TUNE_SCALING_ARR_AMPLIFY_COARSE
#define TUNE_SCALING_ARR_AMPLIFY_COARSE 128
Referenced by au_compute_pitch_ratio().
TUNE_SCALING_ARR_AMPLIFY_FINE
#define TUNE_SCALING_ARR_AMPLIFY_FINE 0
Referenced by au_compute_pitch_ratio().
TUNE_SCALING_ARR_ATTENUATE_COARSE
#define TUNE_SCALING_ARR_ATTENUATE_COARSE 288
Referenced by au_compute_pitch_ratio().
TUNE_SCALING_ARR_ATTENUATE_FINE
#define TUNE_SCALING_ARR_ATTENUATE_FINE 160
Referenced by au_compute_pitch_ratio().
Enumeration Type Documentation
BKParseState
enum BKParseState
Enumerator
BK_READ_DONE
BK_READ_FETCH_HEADER
BK_READ_FETCH_DATA
BK_READ_SWIZZLE
BK_READ_PROCESS_CR
BK_READ_SWIZZLE_CR
BK_READ_PROCESS_DR
BK_READ_UNK_DR
BK_READ_PROCESS_SR
BK_READ_UNK_SR
Function Documentation
au_ambient_load()
AuResult au_ambient_load (u32 ambSoundID)
Referenced by snd_load_ambient().
au_compute_pitch_ratio()
f32 au_compute_pitch_ratio (s32 pitch)
Referenced by au_amb_player_update(), au_amb_restore_voices(), and au_bgm_player_update_playing().
au_copy_bytes()
void au_copy_bytes (s8 * src, s8 * dest, s32 size)
au_copy_words()
void au_copy_words (void * src, void * dst, s32 size)
Referenced by au_load_PER(), au_load_PRG(), func_8004DCB8(), and func_8004DFD4().
au_engine_init()
void au_engine_init (s32 outputRate)
Referenced by create_audio_system().
au_fade_clear()
void au_fade_clear (Fade * fade)
au_fade_init()
void au_fade_init (Fade * fade, s32 time, s32 startValue, s32 endValue)
Referenced by au_bgm_dispatch_player_event(), au_sfx_init(), and func_8004DFD4().
au_fade_set_vol_scale()
void au_fade_set_vol_scale (Fade * fade, s16 value)
Referenced by au_bgm_player_init().
au_fade_set_volume()
void au_fade_set_volume (u8 busId, u16 volume, s32 busVolume)
Referenced by au_sfx_init(), au_update_clients_2(), and func_8004E444().
au_fade_update()
void au_fade_update (Fade * fade)
Referenced by au_update_clients_2().
au_fetch_SBN_file()
AuResult au_fetch_SBN_file (u32 fileIdx, AuFileFormat format, SBNFileEntry * outEntry)
Referenced by au_engine_init(), au_load_BK_headers(), au_load_song_files(), and func_80053E58().
au_get_bgm_player()
void au_get_bgm_player (u32 playerIndex, BGMPlayer ** outPlayer)
au_get_bgm_player_and_file()
void au_get_bgm_player_and_file (u32 playerIndex, BGMHeader ** outFile, BGMPlayer ** outPlayer)
Referenced by au_song_load().
au_get_BK_instruments()
InstrumentGroup * au_get_BK_instruments (s32 bankGroup, u32 bankIndex)
Referenced by au_load_BK_to_bank(), func_80054AA0(), and func_80054C84().
au_get_instrument()
Instrument * au_get_instrument (AuGlobals * globals, u32 bank, u32 patch, EnvelopeData * envData)
Referenced by au_amb_player_update(), au_bgm_player_update_playing(), au_BGMCmd_E8_TrackOverridePatch(), and au_BGMCmd_F5_TrackVoice().
au_load_BK_to_bank()
SoundBank * au_load_BK_to_bank (s32 bkFileOffset, SoundBank * bank, s32 bankIndex, s32 bankGroup)
Referenced by au_load_BK_headers(), and snd_load_BK().
au_load_INIT()
void au_load_INIT (AuGlobals * arg0, s32 romAddr, ALHeap * heap)
Referenced by au_engine_init().
au_load_PER()
void au_load_PER (AuGlobals * globals, s32 romAddr)
Referenced by au_engine_init().
au_load_PRG()
void au_load_PRG (AuGlobals * arg0, s32 romAddr)
Referenced by au_engine_init().
au_load_song_files()
AuResult au_load_song_files (u32 songID, BGMHeader * bgmFile, BGMPlayer * player)
Referenced by au_song_load().
au_memset()
void au_memset (void * dst, s32 size, u8 value)
Referenced by au_amb_manager_init(), and au_amb_play_sequence().
au_read_rom()
void au_read_rom (s32 romAddr, void * buffer, u32 size)
Referenced by au_ambient_load(), au_engine_init(), au_load_BK_headers(), au_load_BK_to_bank(), au_load_INIT(), au_load_PER(), au_load_PRG(), au_load_song_files(), func_80053E58(), and func_80054AA0().
au_reset_nonfree_voice()
void au_reset_nonfree_voice (AuVoice * voice, u8 index)
au_reset_voice()
void au_reset_voice (AuVoice * voice, u8 voiceIdx)
Referenced by au_amb_player_stop(), au_amb_player_update(), au_amb_restore_voices(), au_bgm_player_update_playing(), au_BGMCmd_FC_Jump(), and func_80050900().
au_swizzle_BK_instruments()
void au_swizzle_BK_instruments (s32 bkFileOffset, SoundBank * bank, InstrumentGroup instruments, u32 instrumentCount, u8 arg4)
Referenced by au_load_BK_to_bank(), and func_80054AA0().
au_syn_update()
void au_syn_update (AuGlobals * globals)
Referenced by au_update_clients_2().
au_update_clients_2()
void au_update_clients_2 (void)
Referenced by alAudioFrame().
au_update_players_main()
void au_update_players_main (void)
Referenced by alAudioFrame().
func_80052E30()
void func_80052E30 (u8 index)
Referenced by au_pull_voice().
func_80053AC8()
void func_80053AC8 (Fade * fade)
Referenced by func_80054CE0().
func_80053B04()
void func_80053B04 (Fade * fade, u32 arg1, s32 target)
Referenced by func_8004E0F4().
func_80053BA8()
void func_80053BA8 (Fade * fade)
Referenced by au_update_clients_2().
func_80053E58()
AuResult func_80053E58 (s32 songID, BGMHeader * bgmFile)
Referenced by func_8004DE2C().
func_80053F64()
BGMPlayer * func_80053F64 (s32 arg0)
Referenced by func_8004DCB8(), and func_8004DE2C().
func_80054248()
BGMPlayer * func_80054248 (u8 arg0)
Referenced by func_8004DE2C().
func_80054AA0()
s32 * func_80054AA0 (s32 * bkFileOffset, void * vaddr, s32 bankIndex, s32 bankGroup)
func_80054C84()
void func_80054C84 (s32 bankIndex, s32 bankGroup)
func_80054CE0()
void func_80054CE0 (s32 arg0, u32 idx)
Referenced by func_800561A4(), and func_800561C4().
func_80054D74()
s32 func_80054D74 (s32 arg0, s32 arg1)
Referenced by func_800561E4().
func_80054DA8()
void func_80054DA8 (u32 bMonoSound)
Referenced by audio_set_mono(), and audio_set_stereo().
snd_load_BGM()
s32 snd_load_BGM (s32 arg0)
snd_load_BK()
s32 snd_load_BK (s32 bkFileOffset, s32 bankIndex)
Referenced by au_ambient_load(), au_load_song_files(), func_80053E58(), and snd_load_BGM().
Variable Documentation
AlTuneScaling
f32 AlTuneScaling[] extern
Referenced by au_compute_pitch_ratio().
BeginSoundUpdateCallback
AuCallback BeginSoundUpdateCallback
Referenced by au_update_players_main().
D_80078530
u16 D_80078530[9] extern
Referenced by func_80054CE0().
EnvelopePressDefault
u8 EnvelopePressDefault[] extern
Referenced by au_get_instrument().
EnvelopeReleaseDefault
u8 EnvelopeReleaseDefault[] extern
gAuAmbienceManager
AmbienceManager* gAuAmbienceManager
Referenced by au_ambient_load(), au_engine_init(), and au_update_clients_2().
gBGMPlayerA
BGMPlayer* gBGMPlayerA
Referenced by au_engine_init(), au_get_bgm_player(), au_get_bgm_player_and_file(), au_update_clients_2(), au_update_players_main(), func_80054248(), and func_80054CE0().
gBGMPlayerB
BGMPlayer* gBGMPlayerB
Referenced by au_engine_init(), au_get_bgm_player(), au_get_bgm_player_and_file(), au_update_clients_2(), au_update_players_main(), func_80054248(), and func_80054CE0().
gBGMPlayerC
BGMPlayer* gBGMPlayerC
Referenced by au_engine_init().
gSoundGlobals
AuGlobals* gSoundGlobals
Referenced by au_ambient_load(), au_engine_init(), au_fetch_SBN_file(), au_get_bgm_player_and_file(), au_get_BK_instruments(), au_load_song_files(), au_swizzle_BK_instruments(), au_update_clients_2(), au_update_players_main(), func_80052E30(), func_80053E58(), func_80053F64(), func_80054C84(), func_80054DA8(), snd_load_BGM(), and snd_load_BK().
gSoundManager
SoundManager* gSoundManager
Referenced by au_engine_init(), au_update_clients_2(), au_update_players_main(), func_80054248(), func_80054CE0(), and func_80054D74().