papermario: src/audio/30450.c File Reference
30450.c File Reference
Functions
void func_80055050 (ALHeap *heap)
void func_80055068 (u32 arg0)
void func_80055110 (BGMPlayer *player)
void func_8005513C (u32 arg0)
void snd_start_sound (s32 soundID, u8 volume, u8 pan)
void snd_start_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void snd_adjust_sound (s32 soundID, u8 volume, u8 pan)
void snd_adjust_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void snd_stop_sound (s32 soundID)
void snd_reset (void)
void snd_start_sound_raw (s32 soundID, s16 volume, s16 pitchShift, s32 pan)
AuResult snd_load_ambient (s32 ambSoundID)
AuResult snd_ambient_play (s32 index, s32 fadeInTime)
AuResult snd_ambient_stop_quick (s32 index)
AuResult snd_ambient_stop_slow (s32 index, s32 fadeOutTime)
AuResult snd_ambient_pause (s32 index, s32 fadeOutTime)
AuResult snd_ambient_resume (s32 index, s32 fadeInTime)
AuResult snd_ambient_is_stopped (s32 index)
AuResult snd_ambient_mute (s32 index, s32 arg1)
AuResult snd_ambient_set_volume (s32 index, s32 time, s32 volume)
AuResult snd_ambient_disable (s32 index)
AuResult snd_ambient_enable (s32 index)
void snd_ambient_80055760 (s32 index)
AuResult snd_ambient_stop_all (s32 time)
AuResult snd_ambient_play_only (s32 index)
AuResult au_song_load (s32 songID, s32 playerIndex)
AuResult au_song_start (s32 songName)
AuResult au_song_start_variation (s32 songName, s32 variation)
AuResult au_song_stop (s32 songName)
void au_stop_songs (void)
AuResult au_song_is_playing (s32 songName)
AuResult snd_set_song_variation_fade (s32 songName, s32 variation, s32 fadeInTime, s32 startVolume, s32 endVolume)
AuResult snd_set_song_fade (s32 songName, s32 fadeInTime, s32 startVolume, s32 endVolume)
AuResult snd_set_song_variation_fade_time (s32 songName, s32 fadeTime, s32 variation)
AuResult func_80055AF0 (s32 songName)
AuResult func_80055B28 (s32 songName)
AuResult func_80055B80 (s32 songName)
AuResult func_80055BB8 (s32 songName, s32 fadeTime)
AuResult func_80055BF0 (s32 songName)
AuResult func_80055C2C (s32 songName)
AuResult func_80055C64 (s32 songName)
AuResult func_80055C94 (s32 songName)
AuResult snd_set_song_variation (s32 songName, s32 variation)
AuResult snd_song_get_playing_info (s32 songName, BGMHeader **outFile, BGMPlayer **outPlayer)
AuResult snd_song_set_playback_rate (s32 songName, f32 rate)
AuResult snd_song_set_detune (s32 songName, s32 detune)
AuResult snd_song_set_track_volumes (s32 songName, MusicTrackVols trackVolSet)
AuResult snd_song_clear_track_volumes (s32 songName, MusicTrackVols trackVolSet)
AuResult snd_song_set_track_vol_mute (s32 songName, s32 trackIdx)
AuResult snd_song_set_track_vol_quiet (s32 songName, s32 trackIdx)
AuResult snd_song_set_track_vol_full (s32 songName, s32 trackIdx)
void bgm_set_proximity_mix_far (s32 songName, s32 mix)
void bgm_set_proximity_mix_near (s32 songName, s32 mix)
void bgm_set_proximity_mix_full (s32 songName, s32 mix)
void bgm_poll_music_events (MusicEventTrigger **musicEvents, s32 *count)
void bgm_flush_music_events (void)
void bgm_trigger_music_event (s32 playerID, s32 trackIndex, s32 eventInfo)
void bgm_clear_music_events (void)
void au_register_callback (AuCallback func, s32 index)
void audio_set_stereo (void)
void audio_set_mono (void)
void func_800561A4 (s32 arg0)
void func_800561C4 (s32 arg0)
void func_800561E4 (s32 arg0)
void enable_sounds (void)
void disable_sounds (void)
Variables
s32 PreventBGMPlayerUpdate = FALSE
u16 D_80078DB4 = 0
u16 AuAmbiencePlayOnlyIndex = 0
u8 D_80078DB8 []
u8 D_80078DC4 []
u8 D_80078DCC []
u8 D_80078DD0 []
u8 TrackVols_KPA_Outside []
u8 TrackVols_KPA_1 []
u8 TrackVols_KPA_2 []
u8 TrackVols_KPA_3 []
Function Documentation
au_register_callback()
void au_register_callback (AuCallback func, s32 index)
au_song_is_playing()
AuResult au_song_is_playing (s32 songName)
Referenced by bgm_update_music_settings(), and func_8014AD40().
au_song_load()
AuResult au_song_load (s32 songID, s32 playerIndex)
Referenced by bgm_update_music_settings(), and func_80055068().
au_song_start()
AuResult au_song_start (s32 songName)
au_song_start_variation()
AuResult au_song_start_variation (s32 songName, s32 variation)
Referenced by bgm_update_music_settings(), and func_80055068().
au_song_stop()
AuResult au_song_stop (s32 songName)
Referenced by _bgm_set_song(), bgm_update_music_settings(), and func_8014A964().
au_stop_songs()
void au_stop_songs (void)
audio_set_mono()
void audio_set_mono (void)
Referenced by filemenu_main_handle_input(), and state_step_startup().
audio_set_stereo()
void audio_set_stereo (void)
Referenced by filemenu_main_handle_input(), and state_step_startup().
bgm_clear_music_events()
void bgm_clear_music_events (void)
Referenced by au_engine_init(), and au_update_players_main().
bgm_flush_music_events()
void bgm_flush_music_events (void)
bgm_poll_music_events()
void bgm_poll_music_events (MusicEventTrigger ** musicEvents, s32 * count)
bgm_set_proximity_mix_far()
void bgm_set_proximity_mix_far (s32 songName, s32 mix)
Referenced by bgm_adjust_proximity().
bgm_set_proximity_mix_full()
void bgm_set_proximity_mix_full (s32 songName, s32 mix)
Referenced by bgm_adjust_proximity().
bgm_set_proximity_mix_near()
void bgm_set_proximity_mix_near (s32 songName, s32 mix)
Referenced by bgm_adjust_proximity().
bgm_trigger_music_event()
void bgm_trigger_music_event (s32 playerID, s32 trackIndex, s32 eventInfo)
Referenced by au_BGMCmd_FD_EventTrigger().
disable_sounds()
void disable_sounds (void)
Referenced by state_init_demo().
enable_sounds()
void enable_sounds (void)
Referenced by state_step_demo().
func_80055050()
void func_80055050 (ALHeap * heap)
Referenced by au_engine_init().
func_80055068()
void func_80055068 (u32 arg0)
func_80055110()
void func_80055110 (BGMPlayer * player)
Referenced by au_bgm_player_init().
func_8005513C()
void func_8005513C (u32 arg0)
func_80055AF0()
AuResult func_80055AF0 (s32 songName)
Referenced by bgm_update_music_settings().
func_80055B28()
AuResult func_80055B28 (s32 songName)
Referenced by bgm_update_music_settings().
func_80055B80()
AuResult func_80055B80 (s32 songName)
Referenced by _bgm_set_song().
func_80055BB8()
AuResult func_80055BB8 (s32 songName, s32 fadeTime)
Referenced by bgm_update_music_settings().
func_80055BF0()
AuResult func_80055BF0 (s32 songName)
func_80055C2C()
AuResult func_80055C2C (s32 songName)
func_80055C64()
AuResult func_80055C64 (s32 songName)
func_80055C94()
AuResult func_80055C94 (s32 songName)
func_800561A4()
void func_800561A4 (s32 arg0)
Referenced by bgm_reset_sequence_players(), and bgm_update_volume().
func_800561C4()
void func_800561C4 (s32 arg0)
func_800561E4()
void func_800561E4 (s32 arg0)
Referenced by sfx_set_reverb_mode().
snd_adjust_sound()
void snd_adjust_sound (s32 soundID, u8 volume, u8 pan)
snd_adjust_sound_with_shift()
void snd_adjust_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by sfx_adjust_env_sound_params(), and sfx_update_env_sound_params().
snd_ambient_80055760()
void snd_ambient_80055760 (s32 index)
snd_ambient_disable()
AuResult snd_ambient_disable (s32 index)
Referenced by snd_ambient_play_only().
snd_ambient_enable()
AuResult snd_ambient_enable (s32 index)
Referenced by snd_ambient_play_only().
snd_ambient_is_stopped()
AuResult snd_ambient_is_stopped (s32 index)
Referenced by update_ambient_sounds().
snd_ambient_mute()
AuResult snd_ambient_mute (s32 index, s32 arg1)
snd_ambient_pause()
AuResult snd_ambient_pause (s32 index, s32 fadeOutTime)
Referenced by bgm_push_battle_song().
snd_ambient_play()
AuResult snd_ambient_play (s32 index, s32 fadeInTime)
Referenced by snd_ambient_80055760(), and update_ambient_sounds().
snd_ambient_play_only()
AuResult snd_ambient_play_only (s32 index)
Referenced by snd_ambient_80055760().
snd_ambient_resume()
AuResult snd_ambient_resume (s32 index, s32 fadeInTime)
Referenced by bgm_pop_battle_song().
snd_ambient_set_volume()
AuResult snd_ambient_set_volume (s32 index, s32 time, s32 volume)
snd_ambient_stop_all()
AuResult snd_ambient_stop_all (s32 time)
snd_ambient_stop_quick()
AuResult snd_ambient_stop_quick (s32 index)
Referenced by play_ambient_sounds(), snd_ambient_stop_all(), and update_ambient_sounds().
snd_ambient_stop_slow()
AuResult snd_ambient_stop_slow (s32 index, s32 fadeOutTime)
Referenced by snd_ambient_stop_all(), and update_ambient_sounds().
snd_load_ambient()
AuResult snd_load_ambient (s32 ambSoundID)
Referenced by update_ambient_sounds().
snd_reset()
void snd_reset (void)
snd_set_song_fade()
AuResult snd_set_song_fade (s32 songName, s32 fadeInTime, s32 startVolume, s32 endVolume)
snd_set_song_variation()
AuResult snd_set_song_variation (s32 songName, s32 variation)
Referenced by bgm_set_variation().
snd_set_song_variation_fade()
AuResult snd_set_song_variation_fade (s32 songName, s32 variation, s32 fadeInTime, s32 startVolume, s32 endVolume)
Referenced by bgm_update_music_settings().
snd_set_song_variation_fade_time()
AuResult snd_set_song_variation_fade_time (s32 songName, s32 fadeTime, s32 variation)
Referenced by bgm_update_music_settings().
snd_song_clear_track_volumes()
AuResult snd_song_clear_track_volumes (s32 songName, MusicTrackVols trackVolSet)
Referenced by bgm_clear_track_volumes().
snd_song_get_playing_info()
AuResult snd_song_get_playing_info (s32 songName, BGMHeader ** outFile, BGMPlayer ** outPlayer)
Referenced by snd_song_clear_track_volumes(), snd_song_set_detune(), snd_song_set_playback_rate(), and snd_song_set_track_volumes().
snd_song_set_detune()
AuResult snd_song_set_detune (s32 songName, s32 detune)
snd_song_set_playback_rate()
AuResult snd_song_set_playback_rate (s32 songName, f32 rate)
Referenced by worker_update_phonograph_hud().
snd_song_set_track_vol_full()
AuResult snd_song_set_track_vol_full (s32 songName, s32 trackIdx)
snd_song_set_track_vol_mute()
AuResult snd_song_set_track_vol_mute (s32 songName, s32 trackIdx)
snd_song_set_track_vol_quiet()
AuResult snd_song_set_track_vol_quiet (s32 songName, s32 trackIdx)
snd_song_set_track_volumes()
AuResult snd_song_set_track_volumes (s32 songName, MusicTrackVols trackVolSet)
Referenced by bgm_set_track_volumes().
snd_start_sound()
void snd_start_sound (s32 soundID, u8 volume, u8 pan)
Referenced by animate_and_draw_record(), and appendGfx_records().
snd_start_sound_raw()
void snd_start_sound_raw (s32 soundID, s16 volume, s16 pitchShift, s32 pan)
snd_start_sound_with_shift()
void snd_start_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by func_80055068(), sfx_clear_env_sounds(), sfx_play_sound_looping(), and sfx_play_sound_with_params().
snd_stop_sound()
void snd_stop_sound (s32 soundID)
Referenced by action_update_sliding(), sfx_stop_env_sounds(), sfx_stop_sound(), and snd_stop_tracking_env_sound_pos().
Variable Documentation
AuAmbiencePlayOnlyIndex
u16 AuAmbiencePlayOnlyIndex = 0
Referenced by snd_ambient_80055760(), snd_ambient_play_only(), and snd_ambient_stop_all().
D_80078DB4
u16 D_80078DB4 = 0
Referenced by func_80055050(), and func_80055068().
D_80078DB8
u8 D_80078DB8[]
Initial value:
= {
    2, 94,
    3, 80,
    4, 100,
    5, 84,
    0
}
D_80078DC4
u8 D_80078DC4[]
Initial value:
= {
    2, 100,
    3, 110,
    4, 90,
    0
}
D_80078DCC
u8 D_80078DCC[]
Initial value:
= {
    2, 95,
    0
}
D_80078DD0
u8 D_80078DD0[]
Initial value:
= {
    5, 70,
    6, 90,
    7, 90,
    8, 100,
    0
}
PreventBGMPlayerUpdate
s32 PreventBGMPlayerUpdate = FALSE
Referenced by au_song_start(), au_song_start_variation(), au_update_clients_2(), func_80055050(), func_80055B28(), snd_set_song_fade(), and snd_set_song_variation_fade().
TrackVols_KPA_1
u8 TrackVols_KPA_1[]
Initial value:
= {
    5, 100,
    6, 102,
    7, 88,
    8, 110,
    9, 0,
    10, 0,
    11, 0,
    12, 0,
    13, 0,
    14, 0,
    15, 0,
    16, 0,
    0
}
TrackVols_KPA_2
u8 TrackVols_KPA_2[]
Initial value:
= {
    5, 100,
    6, 102,
    7, 88,
    8, 110,
    9, 126,
    10, 88,
    11, 100,
    12, 0,
    13, 0,
    14, 0,
    15, 0,
    16, 0,
    0
}
TrackVols_KPA_3
u8 TrackVols_KPA_3[]
Initial value:
= {
    5, 100,
    6, 102,
    7, 88,
    8, 110,
    9, 126,
    10, 88,
    11, 100,
    12, 100,
    13, 106,
    14, 100,
    15, 100,
    16, 110,
    0
}
TrackVols_KPA_Outside
u8 TrackVols_KPA_Outside[]
Initial value:
= {
    5, 0,
    6, 0,
    7, 0,
    8, 0,
    9, 0,
    10, 0,
    11, 0,
    12, 0,
    13, 0,
    14, 0,
    15, 0,
    16, 0,
    0
}