papermario: src/77480.c File Reference
77480.c File Reference
Macros
#define inspect_icon_VRAM (void*)0x802B7000
#define speech_bubble_VRAM (void*)0x802B7000
#define pulse_stone_VRAM (void*)0x802B7000
#define i_spy_VRAM (void*)0x802B7000
Functions
UNK_FUN_PTR (ISpyNotificationCallback)
UNK_FUN_PTR (PulseStoneNotificationCallback)
UNK_FUN_PTR (TalkNotificationCallback)
UNK_FUN_PTR (InteractNotificationCallback)
HitID player_raycast_down (f32 *, f32 *, f32 *, f32 *)
HitID player_raycast_up_corner (f32 *x, f32 *y, f32 *z, f32 *length)
HitID player_raycast_general (s32, f32, f32, f32, f32, f32, f32, f32 *, f32 *, f32 *, f32 *, f32 *, f32 *, f32 *)
void player_get_slip_vector (f32 *outX, f32 *outY, f32 x, f32 y, f32 nX, f32 nY)
void phys_update_standard (void)
void phys_update_lava_reset (void)
void update_player_blink (void)
void check_for_ispy (void)
void render_ispy_icon (void)
void check_for_pulse_stone (void)
void clear_ispy_icon (void)
void render_pulse_stone_icon (void)
void clear_pulse_stone_icon (void)
void check_for_conversation_prompt (void)
void render_conversation_prompt (void)
void clear_conversation_prompt (void)
void check_for_interactables (void)
void render_interact_prompt (void)
void clear_interact_prompt (void)
void update_partner_timers (void)
void player_update_sprite (void)
s32 get_player_back_anim (s32 arg0)
void appendGfx_player (void *data)
void appendGfx_player_spin (void *data)
Only used when speedy spinning.
void update_player_shadow (void)
s32 partner_use_ability (void)
HitID player_raycast_below (f32 yaw, f32 diameter, f32 *outX, f32 *outY, f32 *outZ, f32 *outLength, f32 *hitRx, f32 *hitRz, f32 *hitDirX, f32 *hitDirZ)
HitID player_raycast_below_cam_relative (PlayerStatus *playerStatus, f32 *outX, f32 *outY, f32 *outZ, f32 *outLength, f32 *hitRx, f32 *hitRz, f32 *hitDirX, f32 *hitDirZ)
HitID player_raycast_up_corners (PlayerStatus *player, f32 *posX, f32 *posY, f32 *posZ, f32 *hitDepth, f32 yaw)
HitID player_test_lateral_overlap (s32 mode, PlayerStatus *playerStatus, f32 *x, f32 *y, f32 *z, f32 length, f32 yaw)
HitID player_test_move_without_slipping (PlayerStatus *playerStatus, f32 *x, f32 *y, f32 *z, f32 length, f32 yaw, s32 *hasClimbableStep)
HitID player_test_move_with_slipping (PlayerStatus *playerStatus, f32 *x, f32 *y, f32 *z, f32 length, f32 yaw)
void update_player (void)
void check_input_use_partner (void)
void clear_player_status (void)
void player_reset_data (void)
b32 is_player_dismounted (void)
s32 get_overriding_player_anim (s32 anim)
void suggest_player_anim_allow_backward (AnimID anim)
void force_player_anim (AnimID anim)
void suggest_player_anim_always_forward (AnimID anim)
f32 get_xz_dist_to_player (f32 x, f32 z)
void enable_player_shadow (void)
void disable_player_shadow (void)
s32 disable_player_static_collisions (void)
s32 enable_player_static_collisions (void)
s32 disable_player_input (void)
s32 enable_player_input (void)
void func_800E01DC (void)
b32 check_player_action_debug (void)
void player_render_interact_prompts (void)
s32 has_valid_conversation_npc (void)
void func_800E06C0 (s32 arg0)
s32 func_800E06D8 (void)
void appendGfx_interact_prompt (void)
void render_player (void)
void render_player_model (void)
Variables
s32 D_8010C950
PlayerStatus gPlayerStatus
PlayerData gPlayerData
f32 D_800F7B48
s32 D_800F7B4C
s32 WorldTattleInteractionID
Macro Definition Documentation
i_spy_VRAM
#define i_spy_VRAM (void*)0x802B7000
inspect_icon_VRAM
#define inspect_icon_VRAM (void*)0x802B7000
pulse_stone_VRAM
#define pulse_stone_VRAM (void*)0x802B7000
speech_bubble_VRAM
#define speech_bubble_VRAM (void*)0x802B7000
Function Documentation
appendGfx_interact_prompt()
void appendGfx_interact_prompt (void)
Referenced by render_interact_prompt().
appendGfx_player()
void appendGfx_player (void * data)
Referenced by render_player_model().
appendGfx_player_spin()
void appendGfx_player_spin (void * data)
Only used when speedy spinning.
Referenced by render_player_model().
check_for_conversation_prompt()
void check_for_conversation_prompt (void)
Referenced by update_player().
check_for_interactables()
void check_for_interactables (void)
Referenced by update_player().
check_for_ispy()
void check_for_ispy (void)
Referenced by update_player().
check_for_pulse_stone()
void check_for_pulse_stone (void)
Referenced by update_player().
check_input_use_partner()
void check_input_use_partner (void)
Referenced by phys_update_standard().
check_player_action_debug()
b32 check_player_action_debug (void)
Referenced by phys_main_collision_below(), player_fall_distance(), and update_player().
clear_conversation_prompt()
void clear_conversation_prompt (void)
Referenced by player_reset_data().
clear_interact_prompt()
void clear_interact_prompt (void)
Referenced by player_reset_data().
clear_ispy_icon()
void clear_ispy_icon (void)
Referenced by player_reset_data().
clear_player_status()
void clear_player_status (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_demo(), state_step_intro(), and state_step_startup().
clear_pulse_stone_icon()
void clear_pulse_stone_icon (void)
Referenced by player_reset_data().
disable_player_input()
s32 disable_player_input (void)
Referenced by _use_partner_ability(), action_update_landing_on_switch(), action_update_spin_jump(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), check_input_open_menus(), entity_BlueWarpPipe_set_player_move_to_center(), entity_Chest_idle(), entity_CymbalPlant_idle(), entity_HeartBlock_show_tutorial_message(), entity_HeartBlockContent_anim_idle(), entity_SaveBlock_pause_game(), entity_SimpleSpring_idle(), entity_TriggerBlock_disable_player_input(), func_802BC0B8_E2E9E8(), phys_player_land(), post_battle(), post_battle(), SentinelAI_Descend(), start_battle(), state_init_file_select(), state_init_language_select(), state_init_pause(), state_step_change_map(), state_step_enter_world(), state_step_intro(), step_game_loop(), update_encounters_neutral(), and update_item_entity_pickup().
disable_player_shadow()
void disable_player_shadow (void)
Referenced by action_update_use_tweester(), entity_BlueWarpPipe_enter_pipe_init(), and func_802BC0B8_E2E9E8().
disable_player_static_collisions()
s32 disable_player_static_collisions (void)
Referenced by action_update_parasol(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), entity_BlueWarpPipe_set_player_move_to_center(), entity_HiddenPanel_flip_over(), entity_StarBoxLauncher_check_launch(), and post_battle().
enable_player_input()
s32 enable_player_input (void)
Referenced by _use_partner_ability(), action_update_spin_jump(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), check_input_open_menus(), end_outta_sight_cleanup(), entity_Chest_enable_player_input(), entity_CymbalPlant_idle(), entity_GiantChest_await_got_item(), entity_HeartBlock_wait_for_close_tutorial(), entity_HeartBlockContent__anim_heal(), entity_SaveBlock_resume_game(), entity_SimpleSpring_enable_player_input(), entity_TriggerBlock_enable_player_input(), func_802BC3A0_E2ECD0(), handle_jumping_land_on_switch(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), SentinelAI_GrabPlayer(), set_action_state(), state_step_change_map(), state_step_enter_world(), state_step_exit_language_select(), state_step_unpause(), update_encounters_conversation(), update_encounters_post_battle(), and update_item_entity_pickup().
enable_player_shadow()
void enable_player_shadow (void)
Referenced by func_802BC3A0_E2ECD0().
enable_player_static_collisions()
s32 enable_player_static_collisions (void)
Referenced by action_update_parasol(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), entity_HiddenPanel_flip_over(), entity_StarBoxLauncher_launch(), pre_battle(), pre_battle(), and pre_battle().
force_player_anim()
void force_player_anim (AnimID anim)
func_800E01DC()
void func_800E01DC (void)
func_800E06C0()
void func_800E06C0 (s32 arg0)
Referenced by update_triggers().
func_800E06D8()
s32 func_800E06D8 (void)
Referenced by should_continue_pulse_stone().
get_overriding_player_anim()
s32 get_overriding_player_anim (s32 anim)
Referenced by suggest_player_anim_allow_backward(), and suggest_player_anim_always_forward().
get_player_back_anim()
s32 get_player_back_anim (s32 arg0)
Referenced by player_update_sprite().
get_xz_dist_to_player()
f32 get_xz_dist_to_player (f32 x, f32 z)
Referenced by action_update_hit_fire(), action_update_hit_lava(), action_update_knockback(), entity_BlueWarpPipe_set_player_move_to_center(), and entity_HiddenPanel_idle().
has_valid_conversation_npc()
s32 has_valid_conversation_npc (void)
Referenced by check_for_conversation_prompt(), and should_continue_pulse_stone().
is_player_dismounted()
b32 is_player_dismounted (void)
Referenced by get_overriding_player_anim(), and update_item_entity_pickup().
partner_use_ability()
s32 partner_use_ability (void)
Referenced by check_input_use_partner(), post_battle(), post_battle(), post_battle(), post_battle(), and post_battle().
phys_update_lava_reset()
void phys_update_lava_reset (void)
Referenced by update_player().
phys_update_standard()
void phys_update_standard (void)
Referenced by update_player().
player_get_slip_vector()
void player_get_slip_vector (f32 * outX, f32 * outY, f32 x, f32 y, f32 nX, f32 nY)
Referenced by player_test_lateral_overlap(), player_test_move_with_slipping(), and player_test_move_without_slipping().
player_raycast_below()
HitID player_raycast_below (f32 yaw, f32 diameter, f32 * outX, f32 * outY, f32 * outZ, f32 * outLength, f32 * hitRx, f32 * hitRz, f32 * hitDirX, f32 * hitDirZ)
Referenced by player_raycast_below_cam_relative(), and update_player_shadow().
player_raycast_below_cam_relative()
HitID player_raycast_below_cam_relative (PlayerStatus * playerStatus, f32 * outX, f32 * outY, f32 * outZ, f32 * outLength, f32 * hitRx, f32 * hitRz, f32 * hitDirX, f32 * hitDirZ)
Referenced by action_update_sliding(), action_update_state_23(), action_update_step_down(), can_dismount(), phys_main_collision_below(), player_check_collision_below(), test_dismount_height(), test_mounting_height_adjustment(), update_current_floor(), and update_riding_physics().
player_raycast_down()
HitID player_raycast_down (f32 * x, f32 * y, f32 * z, f32 * length)
Referenced by player_raycast_below().
player_raycast_general()
HitID player_raycast_general (s32 mode, f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 * hitX, f32 * hitY, f32 * hitZ, f32 * hitDepth, f32 * hitNx, f32 * hitNy, f32 * hitNz)
Referenced by player_test_lateral_overlap(), player_test_move_with_slipping(), and player_test_move_without_slipping().
player_raycast_up_corner()
HitID player_raycast_up_corner (f32 * x, f32 * y, f32 * z, f32 * length)
Referenced by player_raycast_up_corners().
player_raycast_up_corners()
HitID player_raycast_up_corners (PlayerStatus * player, f32 * posX, f32 * posY, f32 * posZ, f32 * hitDepth, f32 yaw)
Referenced by collision_main_above().
player_render_interact_prompts()
void player_render_interact_prompts (void)
Referenced by gfx_draw_frame().
player_reset_data()
void player_reset_data (void)
Referenced by load_map_by_IDs().
player_test_lateral_overlap()
HitID player_test_lateral_overlap (s32 mode, PlayerStatus * playerStatus, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw)
Referenced by action_hammer_end_swing(), action_hammer_test_swing_collision(), check_for_treadmill_overlaps(), collision_check_player_intersecting_world(), collision_check_player_overlaps(), collision_lava_reset_check_additional_overlaps(), collision_main_lateral(), func_800E4404(), and peach_disguise_check_overlaps().
player_test_move_with_slipping()
HitID player_test_move_with_slipping (PlayerStatus * playerStatus, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw)
Referenced by action_update_sliding(), collision_main_lateral(), and phys_check_interactable_collision().
player_test_move_without_slipping()
HitID player_test_move_without_slipping (PlayerStatus * playerStatus, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, s32 * hasClimbableStep)
Referenced by collision_lateral_peach().
player_update_sprite()
void player_update_sprite (void)
Referenced by update_player().
render_conversation_prompt()
void render_conversation_prompt (void)
Referenced by player_render_interact_prompts().
render_interact_prompt()
void render_interact_prompt (void)
Referenced by player_render_interact_prompts().
render_ispy_icon()
void render_ispy_icon (void)
Referenced by player_render_interact_prompts().
render_player()
void render_player (void)
Referenced by render_frame().
render_player_model()
void render_player_model (void)
Referenced by render_player().
render_pulse_stone_icon()
void render_pulse_stone_icon (void)
Referenced by player_render_interact_prompts().
suggest_player_anim_allow_backward()
void suggest_player_anim_allow_backward (AnimID anim)
Referenced by action_update_falling(), action_update_hammer(), action_update_idle(), action_update_idle_peach(), action_update_jump(), action_update_land(), action_update_landing_on_switch(), action_update_parasol(), action_update_peach_falling(), action_update_peach_step_down(), action_update_pushing_block(), action_update_run(), action_update_sliding(), action_update_spin(), action_update_spin_jump(), action_update_step_up(), action_update_step_up_peach(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), action_update_walk(), entity_GiantChest_await_got_item(), entity_Padlock_push_player(), func_802B6198_E24768(), func_802B6550_E23C30(), handle_jumping_land_on_switch(), initialize_jump(), player_jump(), update_encounters_post_battle(), and update_player_carry_anim().
suggest_player_anim_always_forward()
void suggest_player_anim_always_forward (AnimID anim)
Referenced by action_update_first_strike(), action_update_hit_fire(), action_update_hit_lava(), action_update_knockback(), action_update_pushing_block(), action_update_raise_arms(), action_update_sliding(), action_update_spin(), action_update_talk(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), entity_GiantChest_open(), func_802BC2B4_E2EBE4(), update_item_entity_pickup(), and update_riding_physics().
UNK_FUN_PTR() [1/4]
UNK_FUN_PTR (InteractNotificationCallback)
UNK_FUN_PTR() [2/4]
UNK_FUN_PTR (ISpyNotificationCallback)
UNK_FUN_PTR() [3/4]
UNK_FUN_PTR (PulseStoneNotificationCallback)
UNK_FUN_PTR() [4/4]
UNK_FUN_PTR (TalkNotificationCallback)
update_partner_timers()
void update_partner_timers (void)
Referenced by update_player().
update_player()
void update_player (void)
Referenced by state_step_change_map(), state_step_enter_world(), state_step_exit_language_select(), state_step_game_over(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_unpause(), and state_step_world().
update_player_blink()
void update_player_blink (void)
Referenced by update_player().
update_player_shadow()
void update_player_shadow (void)
Referenced by update_player().
Variable Documentation
D_800F7B48
f32 D_800F7B48 extern
Referenced by player_update_sprite().
D_800F7B4C
s32 D_800F7B4C extern
Referenced by appendGfx_player().
D_8010C950
s32 D_8010C950
Referenced by func_800E06C0().
gPlayerData
PlayerData gPlayerData
Referenced by check_input_use_partner(), and update_partner_timers().
gPlayerStatus
PlayerStatus gPlayerStatus
Referenced by appendGfx_player(), appendGfx_player_spin(), check_for_conversation_prompt(), check_for_interactables(), check_for_ispy(), check_for_pulse_stone(), check_input_use_partner(), clear_player_status(), disable_player_input(), disable_player_shadow(), disable_player_static_collisions(), enable_player_input(), enable_player_shadow(), enable_player_static_collisions(), force_player_anim(), func_800E01DC(), func_800E06D8(), get_overriding_player_anim(), get_xz_dist_to_player(), has_valid_conversation_npc(), phys_update_standard(), player_reset_data(), player_update_sprite(), render_player_model(), suggest_player_anim_allow_backward(), suggest_player_anim_always_forward(), update_player(), update_player_blink(), and update_player_shadow().
WorldTattleInteractionID
s32 WorldTattleInteractionID extern
Referenced by check_input_use_partner().