papermario: src/7B440.c File Reference
7B440.c File Reference
Functions
void update_player_input (void)
void reset_player_status (void)
void get_packed_buttons (s32 *out)
void player_input_to_move_vector (f32 *outAngle, f32 *outMagnitude)
void game_input_to_move_vector (f32 *outAngle, f32 *outMagnitude)
void calculate_camera_yinterp_rate (void)
Variables
s32 PeachDisguiseNpcIndex
Entity * TweesterTouchingPartner
Entity * TweesterTouchingPlayer
s32 PrevPlayerDirection
s32 PlayerRunStateTime
f32 PlayerNormalYaw
f32 PlayerNormalPitch
PlayerSpinState gPlayerSpinState
BSS s32 PlayerYInterpUpdateDelay
Function Documentation
calculate_camera_yinterp_rate()
void calculate_camera_yinterp_rate (void)
Referenced by phys_peach_update(), and phys_update_action_state().
game_input_to_move_vector()
void game_input_to_move_vector (f32 * outAngle, f32 * outMagnitude)
Referenced by action_update_use_spinning_flower().
get_packed_buttons()
void get_packed_buttons (s32 * out)
player_input_to_move_vector()
void player_input_to_move_vector (f32 * outAngle, f32 * outMagnitude)
Referenced by action_update_idle(), action_update_idle_peach(), action_update_land(), action_update_peach_land(), action_update_peach_step_down_land(), action_update_pushing_block(), action_update_run(), action_update_spin(), action_update_step_down_land(), action_update_walk(), collision_main_above(), collision_main_lateral(), and phys_player_land().
reset_player_status()
void reset_player_status (void)
Referenced by player_reset_data().
update_player_input()
void update_player_input (void)
Referenced by update_player().
Variable Documentation
gPlayerSpinState
PlayerSpinState gPlayerSpinState
Referenced by reset_player_status().
PeachDisguiseNpcIndex
s32 PeachDisguiseNpcIndex
Referenced by reset_player_status().
PlayerNormalPitch
f32 PlayerNormalPitch
Referenced by reset_player_status().
PlayerNormalYaw
f32 PlayerNormalYaw
Referenced by reset_player_status().
PlayerRunStateTime
s32 PlayerRunStateTime
Referenced by reset_player_status().
PlayerYInterpUpdateDelay
BSS s32 PlayerYInterpUpdateDelay
Referenced by calculate_camera_yinterp_rate().
PrevPlayerDirection
s32 PrevPlayerDirection
Referenced by reset_player_status().
TweesterTouchingPartner
Entity* TweesterTouchingPartner
Referenced by reset_player_status().
TweesterTouchingPlayer
Entity* TweesterTouchingPlayer