papermario: src/7BB60.c File Reference
7BB60.c File Reference
Functions
HitID collision_check_player_intersecting_world (s32 mode, s32 arg1, f32 yaw)
HitID phys_check_interactable_collision (void)
void phys_save_ground_pos (void)
void record_jump_apex (void)
b32 can_trigger_loading_zone (void)
void move_player (s32 duration, f32 heading, f32 speed)
HitID collision_main_above (void)
void handle_jumping_land_on_switch (void)
void handle_jumping_launch (void)
void phys_update_jump (void)
void phys_init_integrator_for_current_state (void)
void gravity_use_fall_parms (void)
void phys_update_falling (void)
void player_handle_floor_collider_type (s32 colliderID)
void phys_player_land (void)
f32 integrate_gravity (void)
f32 player_fall_distance (void)
f32 player_check_collision_below (f32 offset, s32 *colliderID)
void collision_main_lateral (void)
HitID func_800E4404 (s32 mode, s32 offsetY, f32 arg2, f32 *outX, f32 *outY, f32 *outZ)
void collision_check_player_overlaps (void)
s32 phys_should_player_be_sliding (void)
s32 phys_is_on_sloped_ground (void)
void phys_main_collision_below (void)
void func_800E4AD8 (s32 mode)
void func_800E4B40 (s32 mode, f32 *outX, f32 *outY, f32 *outZ)
void collision_lava_reset_check_additional_overlaps (void)
void collision_lateral_peach (void)
void check_input_midair_jump (void)
s8 get_current_partner_id (void)
void try_player_footstep_sounds (s32 interval)
void phys_update_interact_collider (void)
s32 phys_can_player_interact (void)
f32 player_get_side_angle (void)
f32 player_get_camera_facing_angle (void)
Variables
CollisionStatus gCollisionStatus
f32 D_8010C928
f32 JumpedOnSwitchX
f32 JumpedOnSwitchZ
f32 StepUpLastYaw
f32 GravityParamsStartJump []
Function Documentation
can_trigger_loading_zone()
b32 can_trigger_loading_zone (void)
check_input_midair_jump()
void check_input_midair_jump (void)
Referenced by phys_update_standard().
collision_check_player_intersecting_world()
HitID collision_check_player_intersecting_world (s32 mode, s32 arg1, f32 yaw)
Referenced by collision_main_lateral(), and func_800E4AD8().
collision_check_player_overlaps()
void collision_check_player_overlaps (void)
Referenced by phys_update_standard().
collision_lateral_peach()
void collision_lateral_peach (void)
Referenced by collision_lava_reset_check_additional_overlaps(), and phys_update_standard().
collision_lava_reset_check_additional_overlaps()
void collision_lava_reset_check_additional_overlaps (void)
Referenced by action_update_use_spinning_flower(), and phys_update_lava_reset().
collision_main_above()
HitID collision_main_above (void)
Referenced by phys_update_standard().
collision_main_lateral()
void collision_main_lateral (void)
Referenced by phys_update_lava_reset(), phys_update_standard(), and update_player().
func_800E4404()
HitID func_800E4404 (s32 mode, s32 offsetY, f32 arg2, f32 * outX, f32 * outY, f32 * outZ)
Referenced by func_800E4B40().
func_800E4AD8()
void func_800E4AD8 (s32 mode)
func_800E4B40()
void func_800E4B40 (s32 mode, f32 * outX, f32 * outY, f32 * outZ)
get_current_partner_id()
s8 get_current_partner_id (void)
Referenced by collision_main_lateral(), and entity_try_partner_interaction_trigger().
gravity_use_fall_parms()
void gravity_use_fall_parms (void)
Referenced by action_update_state_23(), entity_TriggerBlock_disable_player_input(), handle_jumping_land_on_switch(), phys_main_collision_below(), and phys_update_jump().
handle_jumping_land_on_switch()
void handle_jumping_land_on_switch (void)
Referenced by phys_update_jump().
handle_jumping_launch()
void handle_jumping_launch (void)
Referenced by phys_update_jump().
integrate_gravity()
f32 integrate_gravity (void)
Referenced by action_update_hit_fire(), action_update_knockback(), action_update_spin_jump(), action_update_step_up(), action_update_tornado_jump(), handle_jumping_land_on_switch(), phys_update_jump(), and player_fall_distance().
move_player()
void move_player (s32 duration, f32 heading, f32 speed)
Referenced by entity_BlueWarpPipe_set_player_move_to_center().
phys_can_player_interact()
s32 phys_can_player_interact (void)
Referenced by check_for_interactables(), func_800E06D8(), should_collider_allow_interact(), should_continue_inspect(), and update_triggers().
phys_check_interactable_collision()
HitID phys_check_interactable_collision (void)
Referenced by phys_update_interact_collider().
phys_init_integrator_for_current_state()
void phys_init_integrator_for_current_state (void)
Referenced by initialize_jump().
phys_is_on_sloped_ground()
s32 phys_is_on_sloped_ground (void)
phys_main_collision_below()
void phys_main_collision_below (void)
Referenced by phys_update_standard().
phys_player_land()
void phys_player_land (void)
Referenced by action_update_tornado_jump(), handle_jumping_land_on_switch(), and player_handle_floor_collider_type().
phys_save_ground_pos()
void phys_save_ground_pos (void)
Referenced by phys_main_collision_below().
phys_should_player_be_sliding()
s32 phys_should_player_be_sliding (void)
Referenced by check_input_jump(), and phys_main_collision_below().
phys_update_falling()
void phys_update_falling (void)
Referenced by phys_update_standard().
phys_update_interact_collider()
void phys_update_interact_collider (void)
Referenced by action_update_idle(), action_update_idle_peach(), action_update_peach_step_down(), action_update_run(), action_update_spin(), action_update_step_down(), and action_update_walk().
phys_update_jump()
void phys_update_jump (void)
Referenced by phys_update_standard().
player_check_collision_below()
f32 player_check_collision_below (f32 offset, s32 * colliderID)
Referenced by action_update_hit_fire(), action_update_hit_lava(), action_update_knockback(), action_update_sliding(), action_update_spin_jump(), action_update_step_up(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), handle_jumping_land_on_switch(), phys_update_falling(), and player_jump().
player_fall_distance()
f32 player_fall_distance (void)
Referenced by action_update_hit_fire(), action_update_hit_lava(), action_update_knockback(), action_update_sliding(), action_update_spin_jump(), handle_jumping_land_on_switch(), and phys_update_falling().
player_get_camera_facing_angle()
f32 player_get_camera_facing_angle (void)
Referenced by entity_ItemBlock_spawn_item(), and entity_WoodenCrate_shatter().
player_get_side_angle()
f32 player_get_side_angle (void)
Referenced by action_hammer_end_swing(), action_hammer_play_hit_fx(), action_hammer_test_swing_collision(), entity_StarBoxLauncher_check_launch(), parasol_get_npc(), partner_flying_follow_player(), and partner_walking_follow_player().
player_handle_floor_collider_type()
void player_handle_floor_collider_type (s32 colliderID)
Referenced by handle_jumping_land_on_switch(), phys_update_falling(), and player_jump().
record_jump_apex()
void record_jump_apex (void)
Referenced by action_update_tornado_jump(), handle_jumping_land_on_switch(), handle_jumping_launch(), and phys_update_jump().
try_player_footstep_sounds()
void try_player_footstep_sounds (s32 interval)
Referenced by action_update_run(), action_update_step_up_peach(), and action_update_walk().
Variable Documentation
D_8010C928
f32 D_8010C928
Referenced by phys_main_collision_below().
gCollisionStatus
CollisionStatus gCollisionStatus
Referenced by collision_main_above(), collision_main_lateral(), phys_main_collision_below(), phys_player_land(), phys_update_interact_collider(), player_check_collision_below(), and try_player_footstep_sounds().
GravityParamsStartJump
f32 GravityParamsStartJump[] extern
Referenced by phys_init_integrator_for_current_state().
JumpedOnSwitchX
f32 JumpedOnSwitchX
Referenced by handle_jumping_land_on_switch().
JumpedOnSwitchZ
f32 JumpedOnSwitchZ
Referenced by handle_jumping_land_on_switch().
StepUpLastYaw
f32 StepUpLastYaw
Referenced by phys_main_collision_below().