papermario: src/7E9D0.c File Reference
7E9D0.c File Reference
Macros
#define PLAYER_ACTION_VRAM_DEF (void*) 0x802B6000
Functions
void func_800E5520 (void)
s32 phys_adjust_cam_on_landing (void)
void phys_clear_spin_history (void)
f32 phys_get_spin_history (s32 lag, s32 *x, s32 *y, s32 *z)
void phys_reset_spin_history (void)
void phys_update_action_state (void)
void phys_peach_update (void)
void set_action_state (s32 actionState)
void update_locomotion_state (void)
void start_falling (void)
void start_bounce_a (void)
void start_bounce_b (void)
b32 check_input_hammer (void)
b32 check_input_jump (void)
void check_input_spin (void)
void peach_set_disguise_anim (AnimID anim)
void peach_force_disguise_action (s32 useParasol)
void peach_check_for_parasol_input (void)
void peach_sync_disguise_npc (void)
Npc * peach_make_disguise_npc (s32 peachDisguise)
s32 peach_disguise_check_overlaps (void)
Variables
void * D_8010C924
s32 D_8010C92C
s32 D_8010C964
s32 gSpinHistoryBufferPos
s32 gSpinHistoryPosY [5]
s32 gSpinHistoryPosX [5]
s32 gSpinHistoryPosZ [5]
s16 gSpinHistoryPosAngle [5]
BSS s16 D_8010C9B0
Macro Definition Documentation
PLAYER_ACTION_VRAM_DEF
#define PLAYER_ACTION_VRAM_DEF (void*) 0x802B6000
Referenced by phys_peach_update(), and phys_update_action_state().
Function Documentation
check_input_hammer()
b32 check_input_hammer (void)
Referenced by action_update_idle(), action_update_run(), action_update_spin(), and action_update_walk().
check_input_jump()
b32 check_input_jump (void)
Bug
? collider flags not properly masked with COLLIDER_FLAG_SURFACE_TYPE
Referenced by action_update_idle(), action_update_land(), action_update_pushing_block(), action_update_run(), action_update_spin(), action_update_step_down(), action_update_step_down_land(), and action_update_walk().
check_input_spin()
void check_input_spin (void)
Referenced by phys_update_action_state().
func_800E5520()
void func_800E5520 (void)
Referenced by player_reset_data().
peach_check_for_parasol_input()
void peach_check_for_parasol_input (void)
Referenced by phys_peach_update().
peach_disguise_check_overlaps()
s32 peach_disguise_check_overlaps (void)
Referenced by action_update_parasol().
peach_force_disguise_action()
void peach_force_disguise_action (s32 useParasol)
Referenced by action_update_parasol().
peach_make_disguise_npc()
Npc * peach_make_disguise_npc (s32 peachDisguise)
Referenced by action_update_parasol(), and peach_check_for_parasol_input().
peach_set_disguise_anim()
void peach_set_disguise_anim (AnimID anim)
Referenced by action_update_idle_peach(), action_update_talk(), func_802B6198_E24768(), func_802B6550_E23C30(), and get_overriding_player_anim().
peach_sync_disguise_npc()
void peach_sync_disguise_npc (void)
Referenced by action_update_parasol(), and phys_peach_update().
phys_adjust_cam_on_landing()
s32 phys_adjust_cam_on_landing (void)
Referenced by action_update_hit_lava(), action_update_jump(), action_update_land(), action_update_peach_land(), action_update_peach_step_down_land(), action_update_step_down_land(), action_update_step_up(), action_update_use_spinning_flower(), entity_CymbalPlant_idle(), phys_main_collision_below(), and phys_player_land().
phys_clear_spin_history()
void phys_clear_spin_history (void)
Referenced by action_update_spin(), and action_update_tornado_jump().
phys_get_spin_history()
f32 phys_get_spin_history (s32 lag, s32 * x, s32 * y, s32 * z)
Referenced by appendGfx_player_spin(), and appendGfx_reflect_player_floor_fancy().
phys_peach_update()
void phys_peach_update (void)
Referenced by phys_update_action_state().
phys_reset_spin_history()
void phys_reset_spin_history (void)
Referenced by reset_player_status().
phys_update_action_state()
void phys_update_action_state (void)
Referenced by phys_update_lava_reset(), phys_update_standard(), and update_player().
set_action_state()
void set_action_state (s32 actionState)
Referenced by action_update_first_strike(), action_update_hit_fire(), action_update_hit_lava(), action_update_idle(), action_update_idle_peach(), action_update_knockback(), action_update_land(), action_update_launch(), action_update_parasol(), action_update_peach_land(), action_update_peach_step_down_land(), action_update_pushing_block(), action_update_raise_arms(), action_update_run(), action_update_sliding(), action_update_spin(), action_update_spin_jump(), action_update_state_23(), action_update_step_down(), action_update_step_up(), action_update_step_up_peach(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), action_update_walk(), check_input_hammer(), check_input_jump(), check_input_midair_jump(), check_input_open_menus(), check_input_spin(), check_player_action_debug(), collision_lateral_peach(), end_outta_sight_cleanup(), entity_CymbalPlant_idle(), entity_ScriptSpring_idle(), entity_SimpleSpring_set_jump_params(), entity_TriggerBlock_disable_player_input(), entity_Tweester_idle(), entity_WoodenCrate_idle(), func_802B6820_E256F0(), func_802BB000_E2D930(), func_802BC274_E2EBA4(), func_802BC3A0_E2ECD0(), handle_jumping_launch(), move_player(), peach_check_for_parasol_input(), peach_force_disguise_action(), phys_main_collision_below(), phys_peach_update(), phys_player_land(), phys_update_action_state(), phys_update_jump(), player_handle_floor_collider_type(), post_battle(), post_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), reset_player_status(), start_bounce_a(), start_bounce_b(), start_falling(), update_encounters_conversation(), update_encounters_neutral(), update_encounters_post_battle(), update_item_entity_pickup(), and update_locomotion_state().
start_bounce_a()
void start_bounce_a (void)
Referenced by update_encounters_neutral().
start_bounce_b()
void start_bounce_b (void)
start_falling()
void start_falling (void)
Referenced by action_update_use_spinning_flower().
update_locomotion_state()
void update_locomotion_state (void)
Referenced by action_update_land(), action_update_step_down_land(), action_update_step_up(), and phys_player_land().
Variable Documentation
D_8010C924
void* D_8010C924
Referenced by phys_peach_update(), phys_reset_spin_history(), and phys_update_action_state().
D_8010C92C
s32 D_8010C92C
Referenced by peach_check_for_parasol_input().
D_8010C964
s32 D_8010C964
Referenced by phys_reset_spin_history().
D_8010C9B0
BSS s16 D_8010C9B0
Referenced by func_800E5520(), and phys_adjust_cam_on_landing().
gSpinHistoryBufferPos
s32 gSpinHistoryBufferPos
Referenced by phys_clear_spin_history(), phys_get_spin_history(), and phys_reset_spin_history().
gSpinHistoryPosAngle
s16 gSpinHistoryPosAngle[5]
Referenced by phys_clear_spin_history(), phys_get_spin_history(), and phys_reset_spin_history().
gSpinHistoryPosX
s32 gSpinHistoryPosX[5]
Referenced by phys_get_spin_history(), and phys_reset_spin_history().
gSpinHistoryPosY
s32 gSpinHistoryPosY[5]
Referenced by phys_clear_spin_history(), phys_get_spin_history(), and phys_reset_spin_history().
gSpinHistoryPosZ
s32 gSpinHistoryPosZ[5]
Referenced by phys_get_spin_history(), and phys_reset_spin_history().