papermario: src/8a160_len_700.c File Reference
8a160_len_700.c File Reference
Data Structures
struct Unk8a160
struct Unk8a160Outer
Functions
INCLUDE_IMG ("A2960.png", D_801094B0)
void func_800F0CB0 (s32 arg0, f32 x, f32 y, f32 scale)
void func_800F0D5C (void)
void func_800F0D80 (void)
void func_800F102C (void)
Variables
Vp D_801096B0
u8 D_80109800 [32]
Vec2b D_80109820 [56]
BSS Unk8a160Outer D_8010D000 [1]
Data Structure Documentation
Unk8a160
struct Unk8a160
Data Fields
u8 alive
u8 lifetime
s8 lodVal
Color_RGBA8 rgba
f32 scale
s8 timeLeft
Vec2f vel
f32 x
f32 y
Unk8a160Outer
struct Unk8a160Outer
Data Fields
Unk8a160 subs[57]
Function Documentation
func_800F0CB0()
void func_800F0CB0 (s32 arg0, f32 x, f32 y, f32 scale)
Referenced by update_status_bar().
func_800F0D5C()
void func_800F0D5C (void)
Referenced by initialize_status_bar().
func_800F0D80()
void func_800F0D80 (void)
Referenced by update_status_bar().
func_800F102C()
void func_800F102C (void)
Referenced by update_status_bar().
INCLUDE_IMG()
INCLUDE_IMG ("A2960.png" , D_801094B0)
Variable Documentation
D_801096B0
Vp D_801096B0
Initial value:
= {
    .vp = {
        .vscale = { 640, 480, 511, 0 },
        .vtrans = { 640, 480, 511, 0 }
    }
}
Referenced by func_800F102C().
D_80109800
u8 D_80109800[32]
Initial value:
= {
    40, 90, 81, 72, 65, 59, 53, 47, 43, 38, 34, 31, 28, 25, 22, 20, 18, 16, 15, 13, 12, 10, 9, 8, 7, 7, 6, 5, 5, 4, 0, 0
}
Referenced by func_800F0D80().
D_80109820
Vec2b D_80109820[56]
Initial value:
= {
    { 247, 105 }, { 239, 87 }, { 17, 87 }, { 9, 105 }, { 0, 122 }, { 230, 69 }, { 26, 69 }, { 221, 52 }, { 35, 52 },
    { 202, 49 }, { 186, 255 }, { 200, 241 }, { 0, 200 }, { 56, 241 }, { 70, 255 }, { 54, 49 }, { 196, 222 },
    { 239, 191 }, { 17, 191 }, { 60, 222 }, { 85, 13 }, { 74, 46 }, { 99, 27 }, { 93, 43 }, { 12, 33 }, { 12, 22 },
    { 24, 22 }, { 24, 33 }, { 12, 10 }, { 24, 10 }, { 24, 45 }, { 232, 33 }, { 232, 22 }, { 232, 45 }, { 113, 40 },
    { 193, 203 }, { 190, 183 }, { 182, 46 }, { 163, 43 }, { 35, 182 }, { 52, 173 }, { 12, 45 }, { 244, 22 },
    { 244, 33 }, { 232, 10 }, { 244, 10 }, { 244, 45 }, { 204, 173 }, { 221, 182 }, { 186, 164 }, { 171, 13 },
    { 157, 27 }, { 143, 40 }, { 63, 203 }, { 66, 183 }, { 70, 164 }
}
Referenced by func_800F0D80().
D_8010D000
BSS Unk8a160Outer D_8010D000[1]
Referenced by func_800F0CB0(), func_800F0D5C(), func_800F0D80(), and func_800F102C().