papermario: src/battle/action_cmd.c File Reference
action_cmd.c File Reference
Macros
#define AC_TBL_ENTRY(name) action_cmd_ ## name ## _ROM_START, action_cmd_ ## name ## _ROM_END, action_cmd_ ## name ## _VRAM
Functions
s32 adjust_action_command_difficulty (s32 difficultyLevel)
void draw_mash_meter (s32 posX, s32 posY, s32 fillValue, s32 colorMode)
void draw_mash_meter_multicolor (s32 posX, s32 posY, s32 fillValue)
void draw_mash_meter_multicolor_with_divisor (s32 posX, s32 posY, s32 fillValue, s32 divisor)
void draw_mash_meter_mode (s32 posX, s32 posY, s32 fillValue, s32 colorMode)
void draw_mash_meter_mode_with_divisor (s32 posX, s32 posY, s32 fillValue, s32 divisor, s32 colorMode)
void draw_mash_meter_blink (s32 posX, s32 posY, s32 fillValue)
void draw_mash_meter_blink_with_divisor (s32 posX, s32 posY, s32 fillValue, s32 divisor)
void action_command_init_status (void)
void action_command_update (void)
void action_command_draw (void)
void action_command_free (void)
void create_action_command_ui_worker (void)
s32 check_block_input (s32 buttonMask)
void increment_action_command_attempt_count (void)
void increment_action_command_success_count (void)
Variables
u8 mashMeter_bgColors [15]
u8 mashMeter_fillColors [15]
u8 mashMeter_cutOffColors [15]
Difficulty1D actionCmdTableJump = { 7, 6, 5, 4, 3, 2, 1, 0 }
Difficulty1D actionCmdTableHammer = { 11, 10, 9, 8, 7, 6, 5, 4 }
Difficulty1D actionCmdTableFlee = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableBreakFree = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableWhirlwind = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableStopLeech = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTable07 = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableDizzyShell = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableFireShell = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTable0A = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableBomb = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableBodySlam = { 9, 8, 7, 6, 5, 4, 3, 2 }
Difficulty1D actionCmdTableAirLift = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableAirRaid = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableSquirt = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTablePowerShock = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableMegaShock = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableSmack = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableSpinySurge = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableHurricane = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty1D actionCmdTableSpook = { 130, 120, 110, 100, 90, 80, 70, 60 }
Difficulty2D actionCmdTableWaterBlock = { {6, 3}, {5, 3}, {4, 3}, {2, 3}, {1, 3}, {0, 3}, {0, 2}, {0, 1} }
Difficulty1D actionCmdTableTidalWave = { 130, 120, 110, 100, 90, 80, 70, 60 }
void * actionCommandDmaTable []
BSS s32 MashMeterSmoothDivisor
BSS s32 D_8029FBC4_pad [3]
BSS s32 IsGroupHeal
BSS s8 ApplyingBuff
BSS s32 D_8029FBD8_pad [2]
BSS ActionCommandStatus gActionCommandStatus
Macro Definition Documentation
AC_TBL_ENTRY
#define AC_TBL_ENTRY (name) action_cmd_ ## name ## _ROM_START, action_cmd_ ## name ## _ROM_END, action_cmd_ ## name ## _VRAM
Function Documentation
action_command_draw()
void action_command_draw (void)
Referenced by create_action_command_ui_worker().
action_command_free()
void action_command_free (void)
Referenced by action_command_update(), and update().
action_command_init_status()
void action_command_init_status (void)
action_command_update()
void action_command_update (void)
Referenced by create_action_command_ui_worker().
adjust_action_command_difficulty()
s32 adjust_action_command_difficulty (s32 difficultyLevel)
check_block_input()
s32 check_block_input (s32 buttonMask)
Referenced by calc_enemy_damage_target().
create_action_command_ui_worker()
void create_action_command_ui_worker (void)
Referenced by initialize_battle().
draw_mash_meter()
void draw_mash_meter (s32 posX, s32 posY, s32 fillValue, s32 colorMode)
Referenced by draw_mash_meter_blink(), draw_mash_meter_blink_with_divisor(), draw_mash_meter_mode(), draw_mash_meter_mode_with_divisor(), draw_mash_meter_multicolor(), and draw_mash_meter_multicolor_with_divisor().
draw_mash_meter_blink()
void draw_mash_meter_blink (s32 posX, s32 posY, s32 fillValue)
Referenced by draw().
draw_mash_meter_blink_with_divisor()
void draw_mash_meter_blink_with_divisor (s32 posX, s32 posY, s32 fillValue, s32 divisor)
Referenced by draw().
draw_mash_meter_mode()
void draw_mash_meter_mode (s32 posX, s32 posY, s32 fillValue, s32 colorMode)
draw_mash_meter_mode_with_divisor()
void draw_mash_meter_mode_with_divisor (s32 posX, s32 posY, s32 fillValue, s32 divisor, s32 colorMode)
Referenced by draw().
draw_mash_meter_multicolor()
void draw_mash_meter_multicolor (s32 posX, s32 posY, s32 fillValue)
Referenced by draw().
draw_mash_meter_multicolor_with_divisor()
void draw_mash_meter_multicolor_with_divisor (s32 posX, s32 posY, s32 fillValue, s32 divisor)
Referenced by draw().
increment_action_command_attempt_count()
void increment_action_command_attempt_count (void)
increment_action_command_success_count()
void increment_action_command_success_count (void)
Referenced by update().
Variable Documentation
actionCmdTable07
Difficulty1D actionCmdTable07 = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTable0A
Difficulty1D actionCmdTable0A = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableAirLift
Difficulty1D actionCmdTableAirLift = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableAirRaid
Difficulty1D actionCmdTableAirRaid = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableBodySlam
Difficulty1D actionCmdTableBodySlam = { 9, 8, 7, 6, 5, 4, 3, 2 }
actionCmdTableBomb
Difficulty1D actionCmdTableBomb = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableBreakFree
Difficulty1D actionCmdTableBreakFree = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableDizzyShell
Difficulty1D actionCmdTableDizzyShell = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableFireShell
Difficulty1D actionCmdTableFireShell = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableFlee
Difficulty1D actionCmdTableFlee = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableHammer
Difficulty1D actionCmdTableHammer = { 11, 10, 9, 8, 7, 6, 5, 4 }
actionCmdTableHurricane
Difficulty1D actionCmdTableHurricane = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableJump
Difficulty1D actionCmdTableJump = { 7, 6, 5, 4, 3, 2, 1, 0 }
actionCmdTableMegaShock
Difficulty1D actionCmdTableMegaShock = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTablePowerShock
Difficulty1D actionCmdTablePowerShock = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableSmack
Difficulty1D actionCmdTableSmack = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableSpinySurge
Difficulty1D actionCmdTableSpinySurge = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableSpook
Difficulty1D actionCmdTableSpook = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableSquirt
Difficulty1D actionCmdTableSquirt = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableStopLeech
Difficulty1D actionCmdTableStopLeech = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableTidalWave
Difficulty1D actionCmdTableTidalWave = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCmdTableWaterBlock
Difficulty2D actionCmdTableWaterBlock = { {6, 3}, {5, 3}, {4, 3}, {2, 3}, {1, 3}, {0, 3}, {0, 2}, {0, 1} }
actionCmdTableWhirlwind
Difficulty1D actionCmdTableWhirlwind = { 130, 120, 110, 100, 90, 80, 70, 60 }
actionCommandDmaTable
void* actionCommandDmaTable[]
Initial value:
= {
    NULL, NULL, NULL,
    action_cmd_jump_ROM_START, action_cmd_jump_ROM_END, action_cmd_jump_VRAM,
    action_cmd_hammer_ROM_START, action_cmd_hammer_ROM_END, action_cmd_hammer_VRAM,
    action_cmd_flee_ROM_START, action_cmd_flee_ROM_END, action_cmd_flee_VRAM,
    action_cmd_break_free_ROM_START, action_cmd_break_free_ROM_END, action_cmd_break_free_VRAM,
    action_cmd_whirlwind_ROM_START, action_cmd_whirlwind_ROM_END, action_cmd_whirlwind_VRAM,
    action_cmd_stop_leech_ROM_START, action_cmd_stop_leech_ROM_END, action_cmd_stop_leech_VRAM,
    action_cmd_unused_flee_ROM_START, action_cmd_unused_flee_ROM_END, action_cmd_unused_flee_VRAM,
    action_cmd_dizzy_shell_ROM_START, action_cmd_dizzy_shell_ROM_END, action_cmd_dizzy_shell_VRAM,
    action_cmd_fire_shell_ROM_START, action_cmd_fire_shell_ROM_END, action_cmd_fire_shell_VRAM,
    action_cmd_unused_mash_a_ROM_START, action_cmd_unused_mash_a_ROM_END, action_cmd_unused_mash_a_VRAM,
    action_cmd_bomb_ROM_START, action_cmd_bomb_ROM_END, action_cmd_bomb_VRAM,
    action_cmd_body_slam_ROM_START, action_cmd_body_slam_ROM_END, action_cmd_body_slam_VRAM,
    action_cmd_air_lift_ROM_START, action_cmd_air_lift_ROM_END, action_cmd_air_lift_VRAM,
    action_cmd_air_raid_ROM_START, action_cmd_air_raid_ROM_END, action_cmd_air_raid_VRAM,
    action_cmd_squirt_ROM_START, action_cmd_squirt_ROM_END, action_cmd_squirt_VRAM,
    action_cmd_power_shock_ROM_START, action_cmd_power_shock_ROM_END, action_cmd_power_shock_VRAM,
    action_cmd_mega_shock_ROM_START, action_cmd_mega_shock_ROM_END, action_cmd_mega_shock_VRAM,
    action_cmd_smack_ROM_START, action_cmd_smack_ROM_END, action_cmd_smack_VRAM,
    action_cmd_spiny_surge_ROM_START, action_cmd_spiny_surge_ROM_END, action_cmd_spiny_surge_VRAM,
    action_cmd_hurricane_ROM_START, action_cmd_hurricane_ROM_END, action_cmd_hurricane_VRAM,
    action_cmd_spook_ROM_START, action_cmd_spook_ROM_END, action_cmd_spook_VRAM,
    action_cmd_three_chances_ROM_START, action_cmd_three_chances_ROM_END, action_cmd_three_chances_VRAM,
    action_cmd_tidal_wave_ROM_START, action_cmd_tidal_wave_ROM_END, action_cmd_tidal_wave_VRAM,
}
ApplyingBuff
BSS s8 ApplyingBuff
D_8029FBC4_pad
BSS s32 D_8029FBC4_pad[3]
D_8029FBD8_pad
BSS s32 D_8029FBD8_pad[2]
gActionCommandStatus
BSS ActionCommandStatus gActionCommandStatus
Referenced by action_command_draw(), action_command_free(), action_command_init_status(), action_command_update(), check_block_input(), create_action_command_ui_worker(), draw(), draw_mash_meter(), free(), increment_action_command_attempt_count(), increment_action_command_success_count(), and update().
IsGroupHeal
BSS s32 IsGroupHeal
mashMeter_bgColors
u8 mashMeter_bgColors[15]
Initial value:
= {
     33,  33, 117,
     29,  35, 163,
     70,  12, 180,
    107,   0, 120,
    115,  13,  19,
}
Referenced by draw_mash_meter(), and DrawMashMeter().
mashMeter_cutOffColors
u8 mashMeter_cutOffColors[15]
Initial value:
= {
     45,  56, 210,
     84,  40, 209,
    125,  44, 181,
    161,  27,  85,
    255, 255, 255,
}
Referenced by draw_mash_meter(), and DrawMashMeter().
mashMeter_fillColors
u8 mashMeter_fillColors[15]
Initial value:
= {
      0, 228, 134,
     46, 180, 242,
    117, 112, 255,
    243,   4, 188,
    247,  13,   5,
}
Referenced by draw_mash_meter(), and DrawMashMeter().
MashMeterSmoothDivisor
BSS s32 MashMeterSmoothDivisor
Referenced by draw_mash_meter(), draw_mash_meter_blink(), draw_mash_meter_blink_with_divisor(), draw_mash_meter_mode(), draw_mash_meter_mode_with_divisor(), draw_mash_meter_multicolor(), and draw_mash_meter_multicolor_with_divisor().