papermario: src/battle/actor_api.c File Reference
actor_api.c File Reference
Functions
s32 count_targets (Actor *actor, s32 targetHomeIndex, s32 targetSelectionFlags)
s32 get_nearest_home_index (f32 x, f32 y, f32 z)
void set_goal_pos_to_part (ActorState *state, s32 actorID, s32 partID)
void set_part_goal_to_actor_part (ActorPartMovement *movement, s32 actorID, s32 partID)
void set_actor_current_position (s32 actorID, f32 x, f32 y, f32 z)
void set_part_absolute_position (s32 actorID, s32 partID, f32 x, f32 y, f32 z)
void set_actor_home_position (s32 actorID, f32 x, f32 y, f32 z)
Actor * get_actor (s32 actorID)
ApiStatus LoadBattleSection (Evt *script, s32 isInitialCall)
ApiStatus GetBattlePhase (Evt *script, s32 isInitialCall)
ApiStatus GetLastElement (Evt *script, s32 isInitialCall)
ApiStatus GetDamageSource (Evt *script, s32 isInitialCall)
ApiStatus SetDamageSource (Evt *script, s32 isInitialCall)
ApiStatus SetGoalToHome (Evt *script, s32 isInitialCall)
ApiStatus SetIdleGoalToHome (Evt *script, s32 isInitialCall)
ApiStatus SetGoalToIndex (Evt *script, s32 isInitialCall)
ApiStatus GetIndexFromPos (Evt *script, s32 isInitialCall)
ApiStatus GetIndexFromHome (Evt *script, s32 isInitialCall)
ApiStatus CountTargets (Evt *script, s32 isInitialCall)
ApiStatus ForceHomePos (Evt *script, s32 isInitialCall)
ApiStatus SetHomePos (Evt *script, s32 isInitialCall)
ApiStatus SetGoalToTarget (Evt *script, s32 isInitialCall)
ApiStatus SetPartGoalToTarget (Evt *script, s32 isInitialCall)
ApiStatus SetGoalToFirstTarget (Evt *script, s32 isInitialCall)
ApiStatus SetGoalPos (Evt *script, s32 isInitialCall)
ApiStatus SetIdleGoal (Evt *script, s32 isInitialCall)
ApiStatus AddGoalPos (Evt *script, s32 isInitialCall)
ApiStatus GetGoalPos (Evt *script, s32 isInitialCall)
ApiStatus GetIdleGoal (Evt *script, s32 isInitialCall)
ApiStatus GetPartTarget (Evt *script, s32 isInitialCall)
ApiStatus GetActorPos (Evt *script, s32 isInitialCall)
ApiStatus GetPartOffset (Evt *script, s32 isInitialCall)
ApiStatus GetPartPos (Evt *script, s32 isInitialCall)
ApiStatus GetHomePos (Evt *script, s32 isInitialCall)
ApiStatus SetActorPos (Evt *script, s32 isInitialCall)
ApiStatus SetPartPos (Evt *script, s32 isInitialCall)
ApiStatus SetEnemyTargetOffset (Evt *script, s32 isInitialCall)
ApiStatus SetAnimation (Evt *script, s32 isInitialCall)
ApiStatus GetAnimation (Evt *script, s32 isInitialCall)
ApiStatus SetAnimationRate (Evt *script, s32 isInitialCall)
ApiStatus SetActorYaw (Evt *script, s32 isInitialCall)
ApiStatus GetActorYaw (Evt *script, s32 isInitialCall)
ApiStatus SetPartYaw (Evt *script, s32 isInitialCall)
ApiStatus GetPartYaw (Evt *script, s32 isInitialCall)
ApiStatus SetActorJumpGravity (Evt *script, s32 isInitialCall)
ApiStatus SetActorIdleJumpGravity (Evt *script, s32 isInitialCall)
ApiStatus SetActorSpeed (Evt *script, s32 isInitialCall)
ApiStatus SetActorIdleSpeed (Evt *script, s32 isInitialCall)
ApiStatus SetPartJumpGravity (Evt *script, s32 isInitialCall)
ApiStatus SetPartMoveSpeed (Evt *script, s32 isInitialCall)
ApiStatus SetJumpAnimations (Evt *script, s32 isInitialCall)
ApiStatus AddActorPos (Evt *script, s32 isInitialCall)
ApiStatus SetActorDispOffset (Evt *script, s32 isInitialCall)
ApiStatus GetPartDispOffset (Evt *script, s32 isInitialCall)
ApiStatus SetPartDispOffset (Evt *script, s32 isInitialCall)
ApiStatus AddPartDispOffset (Evt *script, s32 isInitialCall)
ApiStatus FreezeBattleState (Evt *script, s32 isInitialCall)
ApiStatus GetActorVar (Evt *script, s32 isInitialCall)
ApiStatus SetActorVar (Evt *script, s32 isInitialCall)
ApiStatus AddActorVar (Evt *script, s32 isInitialCall)
ApiStatus GetPartMovementVar (Evt *script, s32 isInitialCall)
ApiStatus SetPartMovementVar (Evt *script, s32 isInitialCall)
ApiStatus AddPartMovementVar (Evt *script, s32 isInitialCall)
ApiStatus SetActorRotation (Evt *script, s32 isInitialCall)
ApiStatus SetActorRotationOffset (Evt *script, s32 isInitialCall)
ApiStatus GetActorRotation (Evt *script, s32 isInitialCall)
ApiStatus SetPartRotation (Evt *script, s32 isInitialCall)
ApiStatus SetPartRotationOffset (Evt *script, s32 isInitialCall)
ApiStatus GetPartRotation (Evt *script, s32 isInitialCall)
ApiStatus SetActorScale (Evt *script, s32 isInitialCall)
ApiStatus SetActorScaleModifier (Evt *script, s32 isInitialCall)
ApiStatus GetActorScale (Evt *script, s32 isInitialCall)
ApiStatus SetPartScale (Evt *script, s32 isInitialCall)
ApiStatus GetPartScale (Evt *script, s32 isInitialCall)
ApiStatus GetBattleFlags (Evt *script, s32 isInitialCall)
ApiStatus SetBattleFlagBits (Evt *script, s32 isInitialCall)
ApiStatus GetBattleFlags2 (Evt *script, s32 isInitialCall)
ApiStatus SetBattleFlagBits2 (Evt *script, s32 isInitialCall)
ApiStatus SetActorFlags (Evt *script, s32 isInitialCall)
ApiStatus SetActorFlagBits (Evt *script, s32 isInitialCall)
ApiStatus GetActorFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartFlagBits (Evt *script, s32 isInitialCall)
ApiStatus SetPartTargetFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartTargetFlagBits (Evt *script, s32 isInitialCall)
ApiStatus GetPartFlags (Evt *script, s32 isInitialCall)
ApiStatus GetPartTargetFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartEventFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartEventBits (Evt *script, s32 isInitialCall)
ApiStatus GetPartEventFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartImmunityFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartImmunityBits (Evt *script, s32 isInitialCall)
ApiStatus HPBarToHome (Evt *script, s32 isInitialCall)
ApiStatus HPBarToCurrent (Evt *script, s32 isInitialCall)
ApiStatus HideHPBar (Evt *script, s32 isInitialCall)
ApiStatus SetHPBarOffset (Evt *script, s32 isInitialCall)
ApiStatus SetActorStatusOffsets (Evt *script, s32 isInitialCall)
ApiStatus SummonEnemy (Evt *script, s32 isInitialCall)
ApiStatus GetOwnerID (Evt *script, s32 isInitialCall)
ApiStatus SetOwnerID (Evt *script, s32 isInitialCall)
ApiStatus ActorExists (Evt *script, s32 isInitialCall)
ApiStatus GetPartAnimInstanceID (Evt *script, s32 isInitialCall)
ApiStatus GetPartAnimNotify (Evt *script, s32 isInitialCall)
ApiStatus SetBattleMenuEnabledFlags (Evt *script, s32 isInitialCall)
ApiStatus SetEnabledStarPowers (Evt *script, s32 isInitialCall)
ApiStatus SetBattleInputMask (Evt *script, s32 isInitialCall)
ApiStatus SetBattleInputButtons (Evt *script, s32 isInitialCall)
ApiStatus CheckButtonPress (Evt *script, s32 isInitialCall)
ApiStatus CheckButtonHeld (Evt *script, s32 isInitialCall)
ApiStatus CheckButtonDown (Evt *script, s32 isInitialCall)
ApiStatus GetBattleState (Evt *script, s32 isInitialCall)
ApiStatus SetBattleState (Evt *script, s32 isInitialCall)
ApiStatus WaitForState (Evt *script, s32 isInitialCall)
ApiStatus CancelEnemyTurn (Evt *script, s32 isInitialCall)
ApiStatus func_8026E260 (Evt *script, s32 isInitialCall)
ApiStatus CreateCurrentPosTargetList (Evt *script, s32 isInitialCall)
ApiStatus CreateHomeTargetList (Evt *script, s32 isInitialCall)
ApiStatus InitTargetIterator (Evt *script, s32 isInitialCall)
ApiStatus SetOwnerTarget (Evt *script, s32 isInitialCall)
ApiStatus ChooseNextTarget (Evt *script, s32 isInitialCall)
s32 func_8026E558 (Evt *script, s32 isInitialCall)
ApiStatus GetTargetListLength (Evt *script, s32 isInitialCall)
ApiStatus GetOwnerTarget (Evt *script, s32 isInitialCall)
ApiStatus func_8026E914 (Evt *script, s32 isInitialCall)
ApiStatus GetPlayerActorID (Evt *script, s32 isInitialCall)
ApiStatus func_8026E9A0 (Evt *script, s32 isInitialCall)
ApiStatus GetDistanceToGoal (Evt *script, s32 isInitialCall)
ApiStatus SetActorPaletteEffect (Evt *script, s32 isInitialCall)
ApiStatus SetActorPaletteSwapTimes (Evt *script, s32 isInitialCall)
ApiStatus SetActorPaletteSwapParams (Evt *script, s32 isInitialCall)
ApiStatus EnableActorPaletteEffects (Evt *script, s32 isInitialCall)
ApiStatus func_8026EDE4 (Evt *script, s32 isInitialCall)
ApiStatus AddActorDecoration (Evt *script, s32 isInitialCall)
ApiStatus RemoveActorDecoration (Evt *script, s32 isInitialCall)
ApiStatus ModifyActorDecoration (Evt *script, s32 isInitialCall)
ApiStatus UseIdleAnimation (Evt *script, s32 isInitialCall)
ApiStatus func_8026F1A0 (Evt *script, s32 isInitialCall)
ApiStatus GetStatusFlags (Evt *script, s32 isInitialCall)
ApiStatus RemovePlayerBuffs (Evt *script, s32 isInitialCall)
ApiStatus SetPartAlpha (Evt *script, s32 isInitialCall)
ApiStatus CreatePartShadow (Evt *script, s32 isInitialCall)
ApiStatus RemovePartShadow (Evt *script, s32 isInitialCall)
ApiStatus SetEndBattleFadeOutRate (Evt *script, s32 isInitialCall)
ApiStatus SetBattleVar (Evt *script, s32 isInitialCall)
ApiStatus GetBattleVar (Evt *script, s32 isInitialCall)
ApiStatus ResetAllActorSounds (Evt *script, s32 isInitialCall)
s32 SetActorSounds (Evt *script, s32 isInitialCall)
ApiStatus ResetActorSounds (Evt *script, s32 isInitialCall)
ApiStatus SetPartSounds (Evt *script, s32 isInitialCall)
ApiStatus SetActorType (Evt *script, s32 isInitialCall)
ApiStatus ShowShockEffect (Evt *script, s32 isInitialCall)
ApiStatus GetActorAttackBoost (Evt *script, s32 isInitialCall)
ApiStatus GetActorDefenseBoost (Evt *script, s32 isInitialCall)
ApiStatus BoostAttack (Evt *script, s32 isInitialCall)
ApiStatus BoostDefense (Evt *script, s32 isInitialCall)
ApiStatus VanishActor (Evt *script, s32 isInitialCall)
ApiStatus ElectrifyActor (Evt *script, s32 isInitialCall)
ApiStatus HealActor (Evt *script, s32 isInitialCall)
ApiStatus WaitForBuffDone (Evt *script, s32 isInitialCall)
ApiStatus CopyBuffs (Evt *script, s32 isInitialCall)
Variables
s32 IsGroupHeal
s8 ApplyingBuff
Function Documentation
ActorExists()
ApiStatus ActorExists (Evt * script, s32 isInitialCall)
AddActorDecoration()
ApiStatus AddActorDecoration (Evt * script, s32 isInitialCall)
Referenced by A().
AddActorPos()
ApiStatus AddActorPos (Evt * script, s32 isInitialCall)
AddActorVar()
ApiStatus AddActorVar (Evt * script, s32 isInitialCall)
AddGoalPos()
ApiStatus AddGoalPos (Evt * script, s32 isInitialCall)
Referenced by A().
AddPartDispOffset()
ApiStatus AddPartDispOffset (Evt * script, s32 isInitialCall)
AddPartMovementVar()
ApiStatus AddPartMovementVar (Evt * script, s32 isInitialCall)
BoostAttack()
ApiStatus BoostAttack (Evt * script, s32 isInitialCall)
BoostDefense()
ApiStatus BoostDefense (Evt * script, s32 isInitialCall)
CancelEnemyTurn()
ApiStatus CancelEnemyTurn (Evt * script, s32 isInitialCall)
CheckButtonDown()
ApiStatus CheckButtonDown (Evt * script, s32 isInitialCall)
CheckButtonHeld()
ApiStatus CheckButtonHeld (Evt * script, s32 isInitialCall)
CheckButtonPress()
ApiStatus CheckButtonPress (Evt * script, s32 isInitialCall)
ChooseNextTarget()
ApiStatus ChooseNextTarget (Evt * script, s32 isInitialCall)
CopyBuffs()
ApiStatus CopyBuffs (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
count_targets()
s32 count_targets (Actor * actor, s32 targetHomeIndex, s32 targetSelectionFlags)
Referenced by CountTargets().
CountTargets()
ApiStatus CountTargets (Evt * script, s32 isInitialCall)
CreateCurrentPosTargetList()
ApiStatus CreateCurrentPosTargetList (Evt * script, s32 isInitialCall)
CreateHomeTargetList()
ApiStatus CreateHomeTargetList (Evt * script, s32 isInitialCall)
CreatePartShadow()
ApiStatus CreatePartShadow (Evt * script, s32 isInitialCall)
ElectrifyActor()
ApiStatus ElectrifyActor (Evt * script, s32 isInitialCall)
EnableActorPaletteEffects()
ApiStatus EnableActorPaletteEffects (Evt * script, s32 isInitialCall)
ForceHomePos()
ApiStatus ForceHomePos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
FreezeBattleState()
ApiStatus FreezeBattleState (Evt * script, s32 isInitialCall)
func_8026E260()
ApiStatus func_8026E260 (Evt * script, s32 isInitialCall)
func_8026E558()
s32 func_8026E558 (Evt * script, s32 isInitialCall)
func_8026E914()
ApiStatus func_8026E914 (Evt * script, s32 isInitialCall)
func_8026E9A0()
ApiStatus func_8026E9A0 (Evt * script, s32 isInitialCall)
func_8026EDE4()
ApiStatus func_8026EDE4 (Evt * script, s32 isInitialCall)
func_8026F1A0()
ApiStatus func_8026F1A0 (Evt * script, s32 isInitialCall)
get_actor()
Actor * get_actor (s32 actorID)
Referenced by ActorExists(), AddActorDecoration(), AddActorPos(), AddActorVar(), AddGoalPos(), AddPartDispOffset(), AddPartMovementVar(), AfflictActor(), BindHandleEvent(), BindHandlePhase(), BindIdle(), BindTakeTurn(), BoostAttack(), BoostDefense(), btl_state_draw_select_target(), btl_state_update_first_strike(), btl_state_update_next_enemy(), btl_state_update_partner_striking_first(), btl_state_update_select_target(), calc_enemy_damage_target(), calc_enemy_test_target(), calc_item_check_hit(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_partner_test_enemy(), calc_player_damage_enemy(), calc_player_test_enemy(), CamPresetUpdate_F(), CamPresetUpdate_G(), CamPresetUpdate_M(), ChooseNextTarget(), clear_part_flag_bits(), ClearStatusEffects(), CopyBuffs(), CopyStatusEffects(), CountTargets(), create_part_shadow(), create_target_list(), CreateCurrentPosTargetList(), CreateHomeTargetList(), DispatchDamageEvent(), DispatchEvent(), DropStarPoints(), ElectrifyActor(), EnableActorBlur(), EnableActorGlow(), EnableActorPaletteEffects(), EnableIdleScript(), EnemyDamageTarget(), EnemyFollowupAfflictTarget(), EnemyTestTarget(), FallPartTo(), FallToGoal(), FlyPartTo(), FlyToGoal(), ForceDisableActorBlur(), ForceHomePos(), func_8026E260(), func_8026E558(), func_8026EDE4(), func_8026F1A0(), func_8027CC10(), func_8027D434(), func_8027FC90(), func_8028070C(), GetActorAttackBoost(), GetActorDefenseBoost(), GetActorFlags(), GetActorHP(), GetActorLevel(), GetActorPos(), GetActorRotation(), GetActorScale(), GetActorSize(), GetActorVar(), GetActorYaw(), GetAnimation(), GetCurrentActorType(), GetDistanceToGoal(), GetEnemyMaxHP(), GetGoalPos(), GetHomePos(), GetIdleGoal(), GetIndexFromHome(), GetIndexFromPos(), GetInstigatorValue(), GetKoopaBrosWithState(), GetLastDamage(), GetLastEvent(), GetOriginalActorType(), GetOwnerTarget(), GetPartAnimInstanceID(), GetPartAnimNotify(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartOffset(), GetPartPos(), GetPartRotation(), GetPartScale(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), GetStatusFlags(), GetTargetListLength(), HealActor(), HideHealthBar(), HideHPBar(), HPBarToCurrent(), HPBarToHome(), IdleFlyToGoal(), IdleJumpToGoal(), IdleRunToGoal(), InitTargetIterator(), ItemAfflictEnemy(), ItemCheckHit(), ItemDamageEnemy(), ItemSpookEnemy(), JumpPartTo(), JumpToGoal(), JumpToGoalSimple2(), JumpWithBounce(), LandJump(), LandJumpPart(), MakeOwnerTargetIndex(), ModifyActorDecoration(), PartnerAfflictEnemy(), PartnerDamageEnemy(), PartnerPowerBounceEnemy(), PartnerTestEnemy(), PauseTakeTurn(), PlayerDamageEnemy(), PlayerPowerBounceEnemy(), PlayerTestEnemy(), remove_part_shadow(), RemoveActor(), RemoveActorDecoration(), ResetActorSounds(), ResetAllActorSounds(), ResumeTakeTurn(), RunPartTo(), RunToGoal(), set_actor_anim(), set_actor_anim_rate(), set_actor_current_position(), set_actor_home_position(), set_actor_yaw(), set_goal_pos_to_part(), set_part_absolute_position(), set_part_flag_bits(), set_part_goal_to_actor_part(), set_part_yaw(), SetActorDispOffset(), SetActorFlagBits(), SetActorFlags(), SetActorIdleJumpGravity(), SetActorIdleSpeed(), SetActorJumpGravity(), SetActorPaletteEffect(), SetActorPaletteSwapParams(), SetActorPaletteSwapTimes(), SetActorPos(), SetActorRotation(), SetActorRotationOffset(), SetActorScale(), SetActorScaleModifier(), SetActorSize(), SetActorSounds(), SetActorSpeed(), SetActorStatusOffsets(), SetActorType(), SetActorVar(), SetDefenseTable(), SetEnemyHP(), SetEnemyTargetOffset(), SetGoalPos(), SetGoalToFirstTarget(), SetGoalToHome(), SetGoalToIndex(), SetGoalToTarget(), SetHomePos(), SetHPBarOffset(), SetIdleAnimations(), SetIdleGoal(), SetIdleGoalToHome(), SetJumpAnimations(), SetOwnerTarget(), SetPartAlpha(), SetPartDispOffset(), SetPartEventBits(), SetPartEventFlags(), SetPartFlagBits(), SetPartFlags(), SetPartGoalToTarget(), SetPartImmunityBits(), SetPartImmunityFlags(), SetPartJumpGravity(), SetPartMovementVar(), SetPartMoveSpeed(), SetPartPos(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPartSize(), SetPartSounds(), SetPartTargetFlagBits(), SetPartTargetFlags(), SetProjectileTargetOffset(), SetStatusTable(), SetTargetActor(), SetTargetOffset(), ShowHealthBar(), ShowShockEffect(), UseIdleAnimation(), and VanishActor().
get_nearest_home_index()
s32 get_nearest_home_index (f32 x, f32 y, f32 z)
Referenced by CountTargets(), GetIndexFromHome(), and GetIndexFromPos().
GetActorAttackBoost()
ApiStatus GetActorAttackBoost (Evt * script, s32 isInitialCall)
GetActorDefenseBoost()
ApiStatus GetActorDefenseBoost (Evt * script, s32 isInitialCall)
GetActorFlags()
ApiStatus GetActorFlags (Evt * script, s32 isInitialCall)
GetActorPos()
ApiStatus GetActorPos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
GetActorRotation()
ApiStatus GetActorRotation (Evt * script, s32 isInitialCall)
GetActorScale()
ApiStatus GetActorScale (Evt * script, s32 isInitialCall)
GetActorVar()
ApiStatus GetActorVar (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
GetActorYaw()
ApiStatus GetActorYaw (Evt * script, s32 isInitialCall)
GetAnimation()
ApiStatus GetAnimation (Evt * script, s32 isInitialCall)
GetBattleFlags()
ApiStatus GetBattleFlags (Evt * script, s32 isInitialCall)
GetBattleFlags2()
ApiStatus GetBattleFlags2 (Evt * script, s32 isInitialCall)
GetBattlePhase()
ApiStatus GetBattlePhase (Evt * script, s32 isInitialCall)
GetBattleState()
ApiStatus GetBattleState (Evt * script, s32 isInitialCall)
GetBattleVar()
ApiStatus GetBattleVar (Evt * script, s32 isInitialCall)
GetDamageSource()
ApiStatus GetDamageSource (Evt * script, s32 isInitialCall)
GetDistanceToGoal()
ApiStatus GetDistanceToGoal (Evt * script, s32 isInitialCall)
GetGoalPos()
ApiStatus GetGoalPos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
GetHomePos()
ApiStatus GetHomePos (Evt * script, s32 isInitialCall)
GetIdleGoal()
ApiStatus GetIdleGoal (Evt * script, s32 isInitialCall)
GetIndexFromHome()
ApiStatus GetIndexFromHome (Evt * script, s32 isInitialCall)
GetIndexFromPos()
ApiStatus GetIndexFromPos (Evt * script, s32 isInitialCall)
GetLastElement()
ApiStatus GetLastElement (Evt * script, s32 isInitialCall)
GetOwnerID()
ApiStatus GetOwnerID (Evt * script, s32 isInitialCall)
GetOwnerTarget()
ApiStatus GetOwnerTarget (Evt * script, s32 isInitialCall)
GetPartAnimInstanceID()
ApiStatus GetPartAnimInstanceID (Evt * script, s32 isInitialCall)
GetPartAnimNotify()
ApiStatus GetPartAnimNotify (Evt * script, s32 isInitialCall)
GetPartDispOffset()
ApiStatus GetPartDispOffset (Evt * script, s32 isInitialCall)
GetPartEventFlags()
ApiStatus GetPartEventFlags (Evt * script, s32 isInitialCall)
GetPartFlags()
ApiStatus GetPartFlags (Evt * script, s32 isInitialCall)
GetPartMovementVar()
ApiStatus GetPartMovementVar (Evt * script, s32 isInitialCall)
GetPartOffset()
ApiStatus GetPartOffset (Evt * script, s32 isInitialCall)
GetPartPos()
ApiStatus GetPartPos (Evt * script, s32 isInitialCall)
GetPartRotation()
ApiStatus GetPartRotation (Evt * script, s32 isInitialCall)
GetPartScale()
ApiStatus GetPartScale (Evt * script, s32 isInitialCall)
GetPartTarget()
ApiStatus GetPartTarget (Evt * script, s32 isInitialCall)
GetPartTargetFlags()
ApiStatus GetPartTargetFlags (Evt * script, s32 isInitialCall)
GetPartYaw()
ApiStatus GetPartYaw (Evt * script, s32 isInitialCall)
GetPlayerActorID()
ApiStatus GetPlayerActorID (Evt * script, s32 isInitialCall)
GetStatusFlags()
ApiStatus GetStatusFlags (Evt * script, s32 isInitialCall)
GetTargetListLength()
ApiStatus GetTargetListLength (Evt * script, s32 isInitialCall)
HealActor()
ApiStatus HealActor (Evt * script, s32 isInitialCall)
HideHPBar()
ApiStatus HideHPBar (Evt * script, s32 isInitialCall)
HPBarToCurrent()
ApiStatus HPBarToCurrent (Evt * script, s32 isInitialCall)
HPBarToHome()
ApiStatus HPBarToHome (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
InitTargetIterator()
ApiStatus InitTargetIterator (Evt * script, s32 isInitialCall)
LoadBattleSection()
ApiStatus LoadBattleSection (Evt * script, s32 isInitialCall)
ModifyActorDecoration()
ApiStatus ModifyActorDecoration (Evt * script, s32 isInitialCall)
RemoveActorDecoration()
ApiStatus RemoveActorDecoration (Evt * script, s32 isInitialCall)
Referenced by A().
RemovePartShadow()
ApiStatus RemovePartShadow (Evt * script, s32 isInitialCall)
RemovePlayerBuffs()
ApiStatus RemovePlayerBuffs (Evt * script, s32 isInitialCall)
ResetActorSounds()
ApiStatus ResetActorSounds (Evt * script, s32 isInitialCall)
Referenced by A(), and A().
ResetAllActorSounds()
ApiStatus ResetAllActorSounds (Evt * script, s32 isInitialCall)
set_actor_current_position()
void set_actor_current_position (s32 actorID, f32 x, f32 y, f32 z)
set_actor_home_position()
void set_actor_home_position (s32 actorID, f32 x, f32 y, f32 z)
set_goal_pos_to_part()
void set_goal_pos_to_part (ActorState * state, s32 actorID, s32 partID)
Referenced by dispatch_damage_event_partner(), dispatch_damage_event_player(), SetGoalToFirstTarget(), and SetGoalToTarget().
set_part_absolute_position()
void set_part_absolute_position (s32 actorID, s32 partID, f32 x, f32 y, f32 z)
set_part_goal_to_actor_part()
void set_part_goal_to_actor_part (ActorPartMovement * movement, s32 actorID, s32 partID)
Referenced by SetPartGoalToTarget().
SetActorDispOffset()
ApiStatus SetActorDispOffset (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorFlagBits()
ApiStatus SetActorFlagBits (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorFlags()
ApiStatus SetActorFlags (Evt * script, s32 isInitialCall)
SetActorIdleJumpGravity()
ApiStatus SetActorIdleJumpGravity (Evt * script, s32 isInitialCall)
SetActorIdleSpeed()
ApiStatus SetActorIdleSpeed (Evt * script, s32 isInitialCall)
SetActorJumpGravity()
ApiStatus SetActorJumpGravity (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
SetActorPaletteEffect()
ApiStatus SetActorPaletteEffect (Evt * script, s32 isInitialCall)
SetActorPaletteSwapParams()
ApiStatus SetActorPaletteSwapParams (Evt * script, s32 isInitialCall)
SetActorPaletteSwapTimes()
ApiStatus SetActorPaletteSwapTimes (Evt * script, s32 isInitialCall)
SetActorPos()
ApiStatus SetActorPos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorRotation()
ApiStatus SetActorRotation (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorRotationOffset()
ApiStatus SetActorRotationOffset (Evt * script, s32 isInitialCall)
Referenced by A(), and A().
SetActorScale()
ApiStatus SetActorScale (Evt * script, s32 isInitialCall)
Referenced by A(), and A().
SetActorScaleModifier()
ApiStatus SetActorScaleModifier (Evt * script, s32 isInitialCall)
SetActorSounds()
s32 SetActorSounds (Evt * script, s32 isInitialCall)
Referenced by A(), and A().
SetActorSpeed()
ApiStatus SetActorSpeed (Evt * script, s32 isInitialCall)
Referenced by A().
SetActorStatusOffsets()
ApiStatus SetActorStatusOffsets (Evt * script, s32 isInitialCall)
SetActorType()
ApiStatus SetActorType (Evt * script, s32 isInitialCall)
SetActorVar()
ApiStatus SetActorVar (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorYaw()
ApiStatus SetActorYaw (Evt * script, s32 isInitialCall)
Referenced by A().
SetAnimation()
ApiStatus SetAnimation (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
SetAnimationRate()
ApiStatus SetAnimationRate (Evt * script, s32 isInitialCall)
SetBattleFlagBits()
ApiStatus SetBattleFlagBits (Evt * script, s32 isInitialCall)
SetBattleFlagBits2()
ApiStatus SetBattleFlagBits2 (Evt * script, s32 isInitialCall)
SetBattleInputButtons()
ApiStatus SetBattleInputButtons (Evt * script, s32 isInitialCall)
SetBattleInputMask()
ApiStatus SetBattleInputMask (Evt * script, s32 isInitialCall)
SetBattleMenuEnabledFlags()
ApiStatus SetBattleMenuEnabledFlags (Evt * script, s32 isInitialCall)
SetBattleState()
ApiStatus SetBattleState (Evt * script, s32 isInitialCall)
SetBattleVar()
ApiStatus SetBattleVar (Evt * script, s32 isInitialCall)
SetDamageSource()
ApiStatus SetDamageSource (Evt * script, s32 isInitialCall)
SetEnabledStarPowers()
ApiStatus SetEnabledStarPowers (Evt * script, s32 isInitialCall)
SetEndBattleFadeOutRate()
ApiStatus SetEndBattleFadeOutRate (Evt * script, s32 isInitialCall)
SetEnemyTargetOffset()
ApiStatus SetEnemyTargetOffset (Evt * script, s32 isInitialCall)
SetGoalPos()
ApiStatus SetGoalPos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
SetGoalToFirstTarget()
ApiStatus SetGoalToFirstTarget (Evt * script, s32 isInitialCall)
SetGoalToHome()
ApiStatus SetGoalToHome (Evt * script, s32 isInitialCall)
Referenced by A().
SetGoalToIndex()
ApiStatus SetGoalToIndex (Evt * script, s32 isInitialCall)
SetGoalToTarget()
ApiStatus SetGoalToTarget (Evt * script, s32 isInitialCall)
SetHomePos()
ApiStatus SetHomePos (Evt * script, s32 isInitialCall)
SetHPBarOffset()
ApiStatus SetHPBarOffset (Evt * script, s32 isInitialCall)
SetIdleGoal()
ApiStatus SetIdleGoal (Evt * script, s32 isInitialCall)
SetIdleGoalToHome()
ApiStatus SetIdleGoalToHome (Evt * script, s32 isInitialCall)
SetJumpAnimations()
ApiStatus SetJumpAnimations (Evt * script, s32 isInitialCall)
SetOwnerID()
ApiStatus SetOwnerID (Evt * script, s32 isInitialCall)
SetOwnerTarget()
ApiStatus SetOwnerTarget (Evt * script, s32 isInitialCall)
SetPartAlpha()
ApiStatus SetPartAlpha (Evt * script, s32 isInitialCall)
SetPartDispOffset()
ApiStatus SetPartDispOffset (Evt * script, s32 isInitialCall)
SetPartEventBits()
ApiStatus SetPartEventBits (Evt * script, s32 isInitialCall)
SetPartEventFlags()
ApiStatus SetPartEventFlags (Evt * script, s32 isInitialCall)
SetPartFlagBits()
ApiStatus SetPartFlagBits (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetPartFlags()
ApiStatus SetPartFlags (Evt * script, s32 isInitialCall)
SetPartGoalToTarget()
ApiStatus SetPartGoalToTarget (Evt * script, s32 isInitialCall)
SetPartImmunityBits()
ApiStatus SetPartImmunityBits (Evt * script, s32 isInitialCall)
SetPartImmunityFlags()
ApiStatus SetPartImmunityFlags (Evt * script, s32 isInitialCall)
SetPartJumpGravity()
ApiStatus SetPartJumpGravity (Evt * script, s32 isInitialCall)
SetPartMovementVar()
ApiStatus SetPartMovementVar (Evt * script, s32 isInitialCall)
SetPartMoveSpeed()
ApiStatus SetPartMoveSpeed (Evt * script, s32 isInitialCall)
SetPartPos()
ApiStatus SetPartPos (Evt * script, s32 isInitialCall)
SetPartRotation()
ApiStatus SetPartRotation (Evt * script, s32 isInitialCall)
SetPartRotationOffset()
ApiStatus SetPartRotationOffset (Evt * script, s32 isInitialCall)
SetPartScale()
ApiStatus SetPartScale (Evt * script, s32 isInitialCall)
SetPartSounds()
ApiStatus SetPartSounds (Evt * script, s32 isInitialCall)
SetPartTargetFlagBits()
ApiStatus SetPartTargetFlagBits (Evt * script, s32 isInitialCall)
SetPartTargetFlags()
ApiStatus SetPartTargetFlags (Evt * script, s32 isInitialCall)
SetPartYaw()
ApiStatus SetPartYaw (Evt * script, s32 isInitialCall)
ShowShockEffect()
ApiStatus ShowShockEffect (Evt * script, s32 isInitialCall)
SummonEnemy()
ApiStatus SummonEnemy (Evt * script, s32 isInitialCall)
UseIdleAnimation()
ApiStatus UseIdleAnimation (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
VanishActor()
ApiStatus VanishActor (Evt * script, s32 isInitialCall)
WaitForBuffDone()
ApiStatus WaitForBuffDone (Evt * script, s32 isInitialCall)
WaitForState()
ApiStatus WaitForState (Evt * script, s32 isInitialCall)
Variable Documentation
ApplyingBuff
s8 ApplyingBuff extern
Referenced by BoostAttack(), BoostDefense(), ElectrifyActor(), HealActor(), VanishActor(), and WaitForBuffDone().
IsGroupHeal
s32 IsGroupHeal extern
Referenced by HealActor().