papermario: src/battle/actor_rendering.c File Reference
actor_rendering.c File Reference
Macros
#define LERP_COMPONENT(a, b, alpha) ((a) * (255 - (alpha)) + (b) * (alpha)) / 255;
#define PAL_ANIM_END 0xFF
Enumerations
enum StandardPalettes { STANDARD_PAL_POISON = 1 , STANDARD_PAL_DIZZY = 2 , STANDARD_PAL_STATIC = 3 }
enum PalSwapState { PAL_SWAP_HOLD_A = 0 , PAL_SWAP_A_TO_B = 1 , PAL_SWAP_HOLD_B = 2 , PAL_SWAP_B_TO_A = 3 }
enum { STATIC_DEFAULT = 0 , STATIC_BRIGHT = 1 , STATIC_DARK = 2 }
enum { WATT_DEFAULT = 0 , WATT_BRIGHTEST = 1 , WATT_BRIGHTER = 2 }
Functions
void update_player_actor_shadow (void)
void appendGfx_npc_actor (s32 isPartner, s32 actorIndex)
void create_status_chill_out (s32 iconID)
void enable_status_static (s32 iconID)
void enable_status_chill_out (s32 iconID)
void enable_status_debuff (s16)
void enable_status_transparent (s16)
void enable_status_icon_boost_jump (s32 iconID)
void enable_status_icon_boost_hammer (s32 iconID)
s32 get_npc_anim_for_status (u32 *, s32)
void set_actor_pal_adjustment (Actor *actor, s32 arg1)
void create_status_icon_boost_hammer (s32 iconID)
void create_status_icon_boost_jump (s32 iconID)
void create_status_icon_peril (s32 iconID)
void create_status_icon_danger (s32 iconID)
void set_status_icons_offset (s32 iconID, s32 offsetY, s32 arg2)
void set_status_icons_properties (s32 iconID, f32 x, f32 y, f32 z, s32 arg, s32 arg2, s32 radius, s32 offsetY)
void appendGfx_npc_actor_reflection (s32, Actor *)
void make_flash_palettes (ActorPart *)
void func_unkA_draw_npc (ActorPart *, s32, Matrix4f)
void func_unkB_draw_npc (ActorPart *, s32, Matrix4f)
void func_unkA_draw_player (ActorPart *, s32, Matrix4f)
void func_unkB_draw_player (ActorPart *, s32, Matrix4f)
void part_glow_on (b32 arg0, ActorPart *part, s32 yaw, b32 arg3)
void part_flash_on (b32 arg0, ActorPart *part, s32 yaw, b32 arg3)
void add_part_decor_none (ActorPart *, s32)
void add_part_decor_golden_flames (ActorPart *, s32)
void add_part_decor_sweat (ActorPart *, s32)
void add_part_decor_seeing_stars (ActorPart *, s32)
void add_part_decor_red_flames (ActorPart *, s32)
void add_part_decor_smoky_trail (ActorPart *, s32)
void add_part_decor_fiery_trail (ActorPart *, s32)
void add_part_decor_whirlwind (ActorPart *, s32)
void add_part_decor_steam (ActorPart *, s32)
void add_part_decor_sparkles (ActorPart *, s32)
void add_part_decor_bowser_aura (ActorPart *, s32)
void add_part_decor_radiating_stars (ActorPart *, s32)
void render_without_adjusted_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void render_with_sleep_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void render_with_static_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void render_with_fear_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void render_with_poison_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void render_with_paralyze_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void render_with_berserk_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void render_with_watt_idle_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void render_with_watt_attack_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void render_with_player_debuff_palettes (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation, s32 isPoison)
void render_with_pal_blending (b32 arg0, ActorPart *part, s32 yaw, s32 arg3, Matrix4f mtx, s32 skipAnimation)
void render_with_palset_blending (b32 arg0, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
s32 update_part_glow (b32 isNpcSprite, ActorPart *part, s32 yaw, b32 isReflection)
s32 update_part_flash (b32 isNpcSprite, ActorPart *part, s32 yaw, b32 isReflection)
s32 get_player_anim_for_status (s32 animID)
void clear_part_flash_mode (ActorPart *part)
s32 get_flash_damage_intensity (ActorPart *part)
void mtx_mirror_y (Matrix4f mtx)
void enable_actor_blur (Actor *actor)
void disable_actor_blur (Actor *actor)
void reset_actor_blur (Actor *actor)
void force_disable_actor_blur (Actor *actor)
void enable_partner_blur (void)
void disable_partner_blur (void)
void reset_partner_blur (void)
void force_disable_partner_blur (void)
void enable_player_blur (void)
void disable_player_blur (void)
void reset_player_blur (void)
void force_disable_player_blur (void)
void force_disable_player_blur_immediately (void)
void update_player_actor_blur_history (Actor *actor)
void appendGfx_player_actor_blur (Actor *actor)
void update_nonplayer_actor_blur_history (b32 isPartner, Actor *actor)
void appendGfx_nonplayer_actor_blur (b32 isPartner, Actor *actor)
void update_enemy_actor_blur_history (Actor *actor)
void appendGfx_enemy_actor_blur (void *data)
void update_partner_actor_blur_history (Actor *actor)
void appendGfx_partner_actor_blur (void *data)
void update_nonplayer_actor_shadow (b32 isPartner, Actor *actor)
void update_enemy_shadows (void)
void update_hero_shadows (void)
void func_80255FD8 (void)
void appendGfx_enemy_actor (void *data)
void appendGfx_partner_actor (void *data)
void appendGfx_enemy_actor_reflection (void *data)
void appendGfx_partner_actor_reflection (void *data)
void appendGfx_player_actor (void *arg0)
void appendGfx_player_actor_reflection (void *arg0)
s32 render_with_adjusted_palettes (b32 isNpcSprite, ActorPart *part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
void part_glow_off (b32 isNpcSprite, ActorPart *part, s32 yaw, b32 isReflection)
void part_flash_off (b32 isNpcSprite, ActorPart *part, s32 yaw, b32 isReflection)
void _add_part_decoration (ActorPart *actorPart)
void _remove_part_decoration (ActorPart *part, s32 idx)
void remove_part_decor_none (ActorPart *part, s32 idx)
void remove_part_decor_golden_flames (ActorPart *part, s32 idx)
void remove_part_decor_sweat (ActorPart *part, s32 idx)
void remove_part_decor_seeing_stars (ActorPart *part, s32 idx)
void remove_part_decor_red_flames (ActorPart *part, s32 idx)
void remove_part_decor_smoky_trail (ActorPart *part, s32 idx)
void remove_part_decor_fiery_trail (ActorPart *part, s32 idx)
void remove_part_decor_whirlwind (ActorPart *part, s32 idx)
void remove_part_decor_steam (ActorPart *part, s32 idx)
void remove_part_decor_sparkles (ActorPart *part, s32 idx)
void remove_part_decor_bowser_aura (ActorPart *part, s32 idx)
void remove_part_decor_radiating_stars (ActorPart *part, s32 idx)
Variables
u8 StaticPalettesAnim []
s16 FearPaletteAnimXOffsets [] = { -2, 2, 0, 0, -2, 2, 0, 0, 0, 0, -2, 2, 0, 0, 0, 0, 0, 0, 0xFF }
s16 ParalyzePaletteAnimXOffsets [] = { -2, 2, 0, 0, -2, 2, 0, 0, 0, 0, -2, 2, 0, 0, 0, 0, 0, 0, 0xFF }
u8 bWattIdlePalettesAnim []
u8 WattAttackPalettesAnim []
s16 SparkleSpawnIntervals [] = { -1, 15, 10, 7, 5, 3, 2, 1 }
Macro Definition Documentation
LERP_COMPONENT
#define LERP_COMPONENT (a, b, alpha) ((a) * (255 - (alpha)) + (b) * (alpha)) / 255;
Referenced by render_with_pal_blending(), render_with_palset_blending(), and render_with_player_debuff_palettes().
PAL_ANIM_END
#define PAL_ANIM_END 0xFF
Referenced by render_with_fear_palettes(), render_with_paralyze_palettes(), render_with_static_palettes(), render_with_watt_attack_palettes(), and render_with_watt_idle_palettes().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STATIC_DEFAULT
STATIC_BRIGHT
STATIC_DARK
anonymous enum
anonymous enum
Enumerator
WATT_DEFAULT
WATT_BRIGHTEST
WATT_BRIGHTER
PalSwapState
enum PalSwapState
Enumerator
PAL_SWAP_HOLD_A
PAL_SWAP_A_TO_B
PAL_SWAP_HOLD_B
PAL_SWAP_B_TO_A
StandardPalettes
enum StandardPalettes
Enumerator
STANDARD_PAL_POISON
STANDARD_PAL_DIZZY
STANDARD_PAL_STATIC
Function Documentation
_add_part_decoration()
void _add_part_decoration (ActorPart * actorPart)
Referenced by add_part_decoration(), appendGfx_npc_actor(), and appendGfx_player_actor().
_remove_part_decoration()
void _remove_part_decoration (ActorPart * part, s32 idx)
Referenced by add_part_decoration(), and remove_part_decoration().
add_part_decor_bowser_aura()
void add_part_decor_bowser_aura (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
add_part_decor_fiery_trail()
void add_part_decor_fiery_trail (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
add_part_decor_golden_flames()
void add_part_decor_golden_flames (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
add_part_decor_none()
void add_part_decor_none (ActorPart * actorPart, s32 i)
Referenced by _add_part_decoration().
add_part_decor_radiating_stars()
void add_part_decor_radiating_stars (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
add_part_decor_red_flames()
void add_part_decor_red_flames (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
add_part_decor_seeing_stars()
void add_part_decor_seeing_stars (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
add_part_decor_smoky_trail()
void add_part_decor_smoky_trail (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
add_part_decor_sparkles()
void add_part_decor_sparkles (ActorPart * part, s32 idx)
Bug
this should be % 4
Referenced by _add_part_decoration().
add_part_decor_steam()
void add_part_decor_steam (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
add_part_decor_sweat()
void add_part_decor_sweat (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
add_part_decor_whirlwind()
void add_part_decor_whirlwind (ActorPart * part, s32 idx)
Referenced by _add_part_decoration().
appendGfx_enemy_actor()
void appendGfx_enemy_actor (void * data)
Referenced by btl_render_actors().
appendGfx_enemy_actor_blur()
void appendGfx_enemy_actor_blur (void * data)
Referenced by btl_render_actors().
appendGfx_enemy_actor_reflection()
void appendGfx_enemy_actor_reflection (void * data)
Referenced by btl_render_actors().
appendGfx_nonplayer_actor_blur()
void appendGfx_nonplayer_actor_blur (b32 isPartner, Actor * actor)
Referenced by appendGfx_enemy_actor_blur(), and appendGfx_partner_actor_blur().
appendGfx_npc_actor()
void appendGfx_npc_actor (s32 isPartner, s32 actorIndex)
Referenced by appendGfx_enemy_actor(), and appendGfx_partner_actor().
appendGfx_npc_actor_reflection()
void appendGfx_npc_actor_reflection (s32 flipYaw, Actor * actor)
Referenced by appendGfx_enemy_actor_reflection(), and appendGfx_partner_actor_reflection().
appendGfx_partner_actor()
void appendGfx_partner_actor (void * data)
Referenced by btl_render_actors().
appendGfx_partner_actor_blur()
void appendGfx_partner_actor_blur (void * data)
Referenced by btl_render_actors().
appendGfx_partner_actor_reflection()
void appendGfx_partner_actor_reflection (void * data)
Referenced by btl_render_actors().
appendGfx_player_actor()
void appendGfx_player_actor (void * arg0)
Referenced by btl_render_actors().
appendGfx_player_actor_blur()
void appendGfx_player_actor_blur (Actor * actor)
Referenced by btl_render_actors().
appendGfx_player_actor_reflection()
void appendGfx_player_actor_reflection (void * arg0)
Referenced by btl_render_actors().
clear_part_flash_mode()
void clear_part_flash_mode (ActorPart * part)
Referenced by part_flash_on().
create_status_chill_out()
void create_status_chill_out (s32 iconID)
Referenced by appendGfx_npc_actor().
create_status_icon_boost_hammer()
void create_status_icon_boost_hammer (s32 iconID)
Referenced by appendGfx_player_actor().
create_status_icon_boost_jump()
void create_status_icon_boost_jump (s32 iconID)
Referenced by appendGfx_player_actor().
create_status_icon_danger()
void create_status_icon_danger (s32 iconID)
Referenced by appendGfx_player_actor().
create_status_icon_peril()
void create_status_icon_peril (s32 iconID)
Referenced by appendGfx_player_actor().
disable_actor_blur()
void disable_actor_blur (Actor * actor)
Referenced by disable_partner_blur().
disable_partner_blur()
void disable_partner_blur (void)
disable_player_blur()
void disable_player_blur (void)
enable_actor_blur()
void enable_actor_blur (Actor * actor)
Referenced by enable_partner_blur().
enable_partner_blur()
void enable_partner_blur (void)
enable_player_blur()
void enable_player_blur (void)
enable_status_chill_out()
void enable_status_chill_out (s32 iconID)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
enable_status_debuff()
void enable_status_debuff (s16)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
enable_status_icon_boost_hammer()
void enable_status_icon_boost_hammer (s32 iconID)
Referenced by appendGfx_player_actor().
enable_status_icon_boost_jump()
void enable_status_icon_boost_jump (s32 iconID)
Referenced by appendGfx_player_actor().
enable_status_static()
void enable_status_static (s32 iconID)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
enable_status_transparent()
void enable_status_transparent (s16)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
force_disable_actor_blur()
void force_disable_actor_blur (Actor * actor)
Referenced by force_disable_partner_blur().
force_disable_partner_blur()
void force_disable_partner_blur (void)
force_disable_player_blur()
void force_disable_player_blur (void)
force_disable_player_blur_immediately()
void force_disable_player_blur_immediately (void)
func_80255FD8()
void func_80255FD8 (void)
Referenced by btl_render_actors().
func_unkA_draw_npc()
void func_unkA_draw_npc (ActorPart * part, s32 yaw, Matrix4f mtx)
Referenced by render_with_paralyze_palettes(), and render_without_adjusted_palettes().
func_unkA_draw_player()
void func_unkA_draw_player (ActorPart * part, s32 yaw, Matrix4f mtx)
Referenced by render_with_paralyze_palettes(), and render_without_adjusted_palettes().
func_unkB_draw_npc()
void func_unkB_draw_npc (ActorPart * part, s32 yaw, Matrix4f mtx)
Referenced by func_unkA_draw_npc(), render_with_berserk_palettes(), render_with_fear_palettes(), render_with_pal_blending(), render_with_palset_blending(), render_with_paralyze_palettes(), render_with_player_debuff_palettes(), render_with_poison_palettes(), render_with_sleep_palettes(), render_with_static_palettes(), render_with_watt_attack_palettes(), and render_with_watt_idle_palettes().
func_unkB_draw_player()
void func_unkB_draw_player (ActorPart * part, s32 yaw, Matrix4f mtx)
Referenced by func_unkA_draw_player(), render_with_berserk_palettes(), render_with_fear_palettes(), render_with_pal_blending(), render_with_palset_blending(), render_with_paralyze_palettes(), render_with_player_debuff_palettes(), render_with_poison_palettes(), render_with_sleep_palettes(), render_with_static_palettes(), render_with_watt_attack_palettes(), and render_with_watt_idle_palettes().
get_flash_damage_intensity()
s32 get_flash_damage_intensity (ActorPart * part)
Referenced by part_flash_on().
get_npc_anim_for_status()
s32 get_npc_anim_for_status (u32 * animations, s32 statusKey)
Referenced by appendGfx_npc_actor(), create_actor(), load_partner_actor(), and load_player_actor().
get_player_anim_for_status()
s32 get_player_anim_for_status (s32 animID)
Referenced by appendGfx_player_actor().
make_flash_palettes()
void make_flash_palettes (ActorPart * part)
Referenced by func_unkB_draw_npc(), and func_unkB_draw_player().
mtx_mirror_y()
void mtx_mirror_y (Matrix4f mtx)
Referenced by appendGfx_npc_actor_reflection(), and appendGfx_player_actor_reflection().
part_flash_off()
void part_flash_off (b32 isNpcSprite, ActorPart * part, s32 yaw, b32 isReflection)
Referenced by update_part_flash().
part_flash_on()
void part_flash_on (b32 arg0, ActorPart * part, s32 yaw, b32 arg3)
Referenced by update_part_flash().
part_glow_off()
void part_glow_off (b32 isNpcSprite, ActorPart * part, s32 yaw, b32 isReflection)
Referenced by update_part_glow().
part_glow_on()
void part_glow_on (b32 arg0, ActorPart * part, s32 yaw, b32 arg3)
Referenced by update_part_glow().
remove_part_decor_bowser_aura()
void remove_part_decor_bowser_aura (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_fiery_trail()
void remove_part_decor_fiery_trail (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_golden_flames()
void remove_part_decor_golden_flames (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_none()
void remove_part_decor_none (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_radiating_stars()
void remove_part_decor_radiating_stars (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_red_flames()
void remove_part_decor_red_flames (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_seeing_stars()
void remove_part_decor_seeing_stars (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_smoky_trail()
void remove_part_decor_smoky_trail (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_sparkles()
void remove_part_decor_sparkles (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_steam()
void remove_part_decor_steam (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_sweat()
void remove_part_decor_sweat (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_whirlwind()
void remove_part_decor_whirlwind (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
render_with_adjusted_palettes()
s32 render_with_adjusted_palettes (b32 isNpcSprite, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by appendGfx_npc_actor(), appendGfx_npc_actor_reflection(), appendGfx_player_actor(), appendGfx_player_actor_blur(), and appendGfx_player_actor_reflection().
render_with_berserk_palettes()
void render_with_berserk_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_with_fear_palettes()
void render_with_fear_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_with_pal_blending()
void render_with_pal_blending (b32 arg0, ActorPart * part, s32 yaw, s32 arg3, Matrix4f mtx, s32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_with_palset_blending()
void render_with_palset_blending (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_with_paralyze_palettes()
void render_with_paralyze_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_with_player_debuff_palettes()
void render_with_player_debuff_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation, s32 isPoison)
Referenced by render_with_adjusted_palettes().
render_with_poison_palettes()
void render_with_poison_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_with_sleep_palettes()
void render_with_sleep_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_with_static_palettes()
void render_with_static_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_with_watt_attack_palettes()
void render_with_watt_attack_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_with_watt_idle_palettes()
void render_with_watt_idle_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
render_without_adjusted_palettes()
void render_without_adjusted_palettes (b32 arg0, ActorPart * part, s32 yaw, Matrix4f mtx, b32 skipAnimation)
Referenced by render_with_adjusted_palettes().
reset_actor_blur()
void reset_actor_blur (Actor * actor)
Referenced by reset_partner_blur().
reset_partner_blur()
void reset_partner_blur (void)
reset_player_blur()
void reset_player_blur (void)
set_actor_pal_adjustment()
void set_actor_pal_adjustment (Actor * actor, s32 arg1)
Referenced by appendGfx_npc_actor(), appendGfx_player_actor(), and inflict_status().
set_status_icons_offset()
void set_status_icons_offset (s32 iconID, s32 offsetY, s32 arg2)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
set_status_icons_properties()
void set_status_icons_properties (s32 iconID, f32 x, f32 y, f32 z, s32 arg, s32 arg2, s32 radius, s32 offsetY)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
update_enemy_actor_blur_history()
void update_enemy_actor_blur_history (Actor * actor)
Referenced by update_nonplayer_actor_shadow().
update_enemy_shadows()
void update_enemy_shadows (void)
Referenced by update_nonplayer_actor_shadows().
update_hero_shadows()
void update_hero_shadows (void)
Referenced by update_nonplayer_actor_shadows().
update_nonplayer_actor_blur_history()
void update_nonplayer_actor_blur_history (b32 isPartner, Actor * actor)
Referenced by update_enemy_actor_blur_history(), and update_partner_actor_blur_history().
update_nonplayer_actor_shadow()
void update_nonplayer_actor_shadow (b32 isPartner, Actor * actor)
Referenced by update_enemy_shadows(), and update_hero_shadows().
update_part_flash()
s32 update_part_flash (b32 isNpcSprite, ActorPart * part, s32 yaw, b32 isReflection)
Referenced by appendGfx_npc_actor(), appendGfx_npc_actor_reflection(), appendGfx_player_actor(), and appendGfx_player_actor_reflection().
update_part_glow()
s32 update_part_glow (b32 isNpcSprite, ActorPart * part, s32 yaw, b32 isReflection)
Referenced by appendGfx_npc_actor(), appendGfx_npc_actor_reflection(), appendGfx_player_actor(), and appendGfx_player_actor_reflection().
update_partner_actor_blur_history()
void update_partner_actor_blur_history (Actor * actor)
Referenced by update_nonplayer_actor_shadow().
update_player_actor_blur_history()
void update_player_actor_blur_history (Actor * actor)
Referenced by update_player_actor_shadow().
update_player_actor_shadow()
void update_player_actor_shadow (void)
Referenced by update_hero_shadows().
Variable Documentation
bWattIdlePalettesAnim
u8 bWattIdlePalettesAnim[]
Initial value:
= {
    WATT_BRIGHTEST,   2,
    WATT_DEFAULT,    52,
    WATT_BRIGHTEST,   4,
    WATT_DEFAULT,    54,
    WATT_DEFAULT,    54,
    WATT_BRIGHTEST,   2,
    WATT_DEFAULT,    28,
    WATT_BRIGHTEST,   2,
    WATT_DEFAULT,     6,
    WATT_BRIGHTEST,   2,
    WATT_DEFAULT,    44,
    WATT_BRIGHTEST,   2,
    WATT_DEFAULT,    44,
     0xFF
}
Referenced by render_with_watt_idle_palettes().
FearPaletteAnimXOffsets
s16 FearPaletteAnimXOffsets[] = { -2, 2, 0, 0, -2, 2, 0, 0, 0, 0, -2, 2, 0, 0, 0, 0, 0, 0, 0xFF }
Referenced by render_with_fear_palettes().
ParalyzePaletteAnimXOffsets
s16 ParalyzePaletteAnimXOffsets[] = { -2, 2, 0, 0, -2, 2, 0, 0, 0, 0, -2, 2, 0, 0, 0, 0, 0, 0, 0xFF }
Referenced by render_with_paralyze_palettes().
SparkleSpawnIntervals
s16 SparkleSpawnIntervals[] = { -1, 15, 10, 7, 5, 3, 2, 1 }
Referenced by add_part_decor_sparkles().
StaticPalettesAnim
u8 StaticPalettesAnim[]
Initial value:
= {
    STATIC_DEFAULT,  32,
    STATIC_BRIGHT,    4,
    STATIC_DARK,      2,
    STATIC_DEFAULT,  16,
    STATIC_BRIGHT,    2,
    STATIC_DEFAULT,  64,
    STATIC_BRIGHT,    2,
    STATIC_DARK,      2,
    STATIC_DEFAULT,  28,
    STATIC_BRIGHT,    2,
    STATIC_DEFAULT,  18,
    STATIC_BRIGHT,    4,
    STATIC_DEFAULT,  16,
    STATIC_BRIGHT,    2,
    STATIC_DEFAULT,  80,
    STATIC_BRIGHT,    2,
    STATIC_DEFAULT,  16,
    STATIC_DARK,      2,
    STATIC_BRIGHT,    2,
    STATIC_DEFAULT,  32,
    STATIC_BRIGHT,    2,
    STATIC_DEFAULT,  14,
    STATIC_BRIGHT,    2,
    STATIC_DARK,      2,
     0xFF
}
Referenced by render_with_static_palettes().
WattAttackPalettesAnim
u8 WattAttackPalettesAnim[]
Initial value:
= {
    WATT_BRIGHTEST,   2,
    WATT_DEFAULT,    10,
    WATT_BRIGHTER,    4,
    WATT_DEFAULT,    14,
    WATT_BRIGHTEST,   2,
    WATT_DEFAULT,    10,
    WATT_BRIGHTER,    4,
    WATT_DEFAULT,     4,
     0xFF
}
Referenced by render_with_watt_attack_palettes().