papermario: src/animator.c File Reference
animator.c File Reference
Data Structures
struct DisplayListBufferHandle
Typedefs
typedef DisplayListBufferHandle AnimatedMeshVertexCopyList[0x60]
Functions
void appendGfx_animator_node (ModelAnimator *, AnimatorNode *, Matrix4f)
Vtx * animator_copy_vertices_to_buffer (ModelAnimator *animator, AnimatorNode *node, Vec3s *buffer, s32 vtxCount, s32 overhead, s32 startIdx)
void animator_make_mirrorZ (Matrix4f mtx)
void animator_make_mirrorY (Matrix4f mtx)
void animator_make_mirrorX (Matrix4f mtx)
void animator_make_identity (Matrix4f mtx)
AnimatorNode * get_animator_child_with_id (AnimatorNode *node, s32 id)
AnimatorNode * get_animator_child_for_model (AnimatorNode *node, s32 modelId)
void free_animator_nodes (AnimatorNode *root)
void clear_animator_list (void)
void reset_animator_list (void)
void delete_model_animator_node (AnimatorNode *node)
void delete_model_animator_nodes (ModelAnimator *animator)
void delete_model_animator (ModelAnimator *animator)
s32 create_model_animator (s16 *animPos)
s32 create_mesh_animator (s16 *animPos, s16 *animBuffer)
AnimatorNode * add_anim_node (ModelAnimator *animator, s32 parentNodeID, AnimatorNodeBlueprint *nodeBP)
void update_model_animator (s32 animatorID)
void update_model_animator_with_transform (s32 animatorID, Mtx *mtx)
s32 step_model_animator (ModelAnimator *animator)
void animator_update_model_transforms (ModelAnimator *animator, Mtx *rootTransform)
void animator_node_update_model_transform (ModelAnimator *animator, f32(*flipMtx)[4], AnimatorNode *node, Mtx *rootTransform)
void render_animated_model (s32 animatorID, Mtx *rootTransform)
void render_animated_model_with_vertices (s32 animatorID, Mtx *rootTransform, s32 segment, void *baseAddr)
void appendGfx_animator (ModelAnimator *animator)
AnimatorNode * get_animator_node_for_tree_index (ModelAnimator *animator, s32 arg1)
AnimatorNode * get_animator_node_with_id (ModelAnimator *animator, s32 id)
void set_animator_tree_to_node_map (ModelAnimator *animator, s32 *nodeIDs, s32 count)
ModelAnimator * get_animator_by_index (s32 animModelID)
ModelAnimator * set_animator_render_callback (s32 animModelID, void *callbackArg, void(*callbackFunc)(void *))
void enable_anim_model_fog (void)
void disable_anim_model_fog (void)
void set_anim_model_fog_dist (s32 start, s32 end)
void set_anim_model_fog_color (s32 r, s32 g, s32 b, s32 a)
s32 is_anim_model_fog_enabled (void)
void get_anim_model_fog_distance (s32 *start, s32 *end)
void get_anim_model_fog_color (s32 *r, s32 *g, s32 *b, s32 *a)
void set_animator_flags (s32 index, s32 bits)
void clear_animator_flags (s32 index, s32 bits)
void play_model_animation (s32 index, s16 *animPos)
void play_model_animation_starting_from (s32 index, s16 *animPos, s32 framesToSkip)
void load_model_animator_node (StaticAnimatorNode *node, ModelAnimator *animator, s32 parentNodeID, s32 *treeIndexToNodeIDs)
void load_model_animator_tree (s32 index, StaticAnimatorNode **tree)
void load_mesh_animator_node (StaticAnimatorNode *node, ModelAnimator *animator, s32 parentNodeID, s32 *treeIndexToNodeIDs)
void load_mesh_animator_tree (s32 index, StaticAnimatorNode **tree)
void reload_mesh_animator_node (StaticAnimatorNode *node, ModelAnimator *animator, s32 parentNodeID, s32 *treeIndexToNodeIDs)
void reload_mesh_animator_tree (ModelAnimator *animator)
s32 step_mesh_animator (ModelAnimator *animator)
Variables
s32 gAnimCount
BSS AnimatedMeshVertexCopyList D_801533C0
BSS AnimatedMeshVertexCopyList D_801536C0
BSS AnimatedMeshList D_801539C0
BSS AnimatedMeshList D_80153A00
BSS AnimatedMeshList * gCurrentAnimMeshListPtr
BSS s32 gAnimModelFogEnabled
BSS s32 gAnimModelFogR
BSS s32 gAnimModelFogG
BSS s32 gAnimModelFogB
BSS s32 gAnimModelFogA
BSS s32 gAnimModelFogStart
BSS s32 gAnimModelFogEnd
BSS s32 gAnimVtxSegment
BSS s32 D_80153A64
BSS Matrix4f gAnimRotMtx
BSS Matrix4f gAnimScaleMtx
BSS Matrix4f gAnimTranslateMtx
BSS Matrix4f gAnimRotScaleMtx
BSS StaticAnimatorNode ** gAnimTreeRoot
Gfx Gfx_RM1_SURFACE_OPA []
Gfx Gfx_RM1_DECAL_OPA []
Gfx Gfx_RM1_INTERSECTING_OPA []
Gfx Gfx_RM1_ALPHATEST []
Gfx Gfx_RM1_SURFACE_XLU []
Gfx Gfx_RM1_DECAL_XLU []
Gfx Gfx_RM1_INTERSECTING_XLU []
Gfx Gfx_RM3_SURFACE_OPA []
Gfx Gfx_RM3_DECAL_OPA []
Gfx Gfx_RM3_INTERSECTING_OPA []
Gfx Gfx_RM3_ALPHATEST []
Gfx Gfx_RM3_SURFACE_XLU []
Gfx Gfx_RM3_DECAL_XLU []
Gfx Gfx_RM3_INTERSECTING_XLU []
AnimScript gAnimScriptDefault
Data Structure Documentation
DisplayListBufferHandle
struct DisplayListBufferHandle
Data Fields
void * addr
s32 ttl
Typedef Documentation
AnimatedMeshVertexCopyList
typedef DisplayListBufferHandle AnimatedMeshVertexCopyList[0x60]
Function Documentation
add_anim_node()
AnimatorNode * add_anim_node (ModelAnimator * animator, s32 parentNodeID, AnimatorNodeBlueprint * nodeBP)
Referenced by load_model_animator_node(), and reload_mesh_animator_node().
animator_copy_vertices_to_buffer()
Vtx * animator_copy_vertices_to_buffer (ModelAnimator * animator, AnimatorNode * node, Vec3s * buffer, s32 vtxCount, s32 overhead, s32 startIdx)
Referenced by appendGfx_animator_node().
animator_make_identity()
void animator_make_identity (Matrix4f mtx)
Referenced by animator_update_model_transforms().
animator_make_mirrorX()
void animator_make_mirrorX (Matrix4f mtx)
Referenced by animator_update_model_transforms().
animator_make_mirrorY()
void animator_make_mirrorY (Matrix4f mtx)
Referenced by animator_update_model_transforms().
animator_make_mirrorZ()
void animator_make_mirrorZ (Matrix4f mtx)
Referenced by animator_update_model_transforms().
animator_node_update_model_transform()
void animator_node_update_model_transform (ModelAnimator * animator, f32(*) flipMtx[4], AnimatorNode * node, Mtx * rootTransform)
Referenced by animator_node_update_model_transform(), and animator_update_model_transforms().
animator_update_model_transforms()
void animator_update_model_transforms (ModelAnimator * animator, Mtx * rootTransform)
Referenced by update_model_animator(), and update_model_animator_with_transform().
appendGfx_animator()
void appendGfx_animator (ModelAnimator * animator)
Referenced by render_animated_model(), and render_animated_model_with_vertices().
appendGfx_animator_node()
void appendGfx_animator_node (ModelAnimator * animator, AnimatorNode * node, Matrix4f mtx)
Referenced by appendGfx_animator(), and appendGfx_animator_node().
clear_animator_flags()
void clear_animator_flags (s32 index, s32 bits)
clear_animator_list()
void clear_animator_list (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_title_screen().
create_mesh_animator()
s32 create_mesh_animator (s16 * animPos, s16 * animBuffer)
Referenced by load_split_entity_data().
create_model_animator()
s32 create_model_animator (s16 * animPos)
Referenced by create_shadow_from_data(), and load_split_entity_data().
delete_model_animator()
void delete_model_animator (ModelAnimator * animator)
Referenced by delete_entity(), and delete_entity_and_unload_data().
delete_model_animator_node()
void delete_model_animator_node (AnimatorNode * node)
Referenced by delete_model_animator(), delete_model_animator_node(), and delete_model_animator_nodes().
delete_model_animator_nodes()
void delete_model_animator_nodes (ModelAnimator * animator)
Referenced by reload_mesh_animator_tree().
disable_anim_model_fog()
void disable_anim_model_fog (void)
enable_anim_model_fog()
void enable_anim_model_fog (void)
free_animator_nodes()
void free_animator_nodes (AnimatorNode * root)
Referenced by free_animator_nodes().
get_anim_model_fog_color()
void get_anim_model_fog_color (s32 * r, s32 * g, s32 * b, s32 * a)
get_anim_model_fog_distance()
void get_anim_model_fog_distance (s32 * start, s32 * end)
get_animator_by_index()
ModelAnimator * get_animator_by_index (s32 animModelID)
Referenced by delete_entity(), delete_entity_and_unload_data(), entity_ItemlessBlock_init(), and entity_PinkFlower_init().
get_animator_child_for_model()
AnimatorNode * get_animator_child_for_model (AnimatorNode * node, s32 modelId)
Referenced by get_animator_child_for_model(), and get_animator_node_with_id().
get_animator_child_with_id()
AnimatorNode * get_animator_child_with_id (AnimatorNode * node, s32 id)
Referenced by add_anim_node(), get_animator_child_with_id(), get_animator_node_for_tree_index(), step_mesh_animator(), and step_model_animator().
get_animator_node_for_tree_index()
AnimatorNode * get_animator_node_for_tree_index (ModelAnimator * animator, s32 arg1)
get_animator_node_with_id()
AnimatorNode * get_animator_node_with_id (ModelAnimator * animator, s32 id)
is_anim_model_fog_enabled()
s32 is_anim_model_fog_enabled (void)
load_mesh_animator_node()
void load_mesh_animator_node (StaticAnimatorNode * node, ModelAnimator * animator, s32 parentNodeID, s32 * treeIndexToNodeIDs)
Referenced by load_mesh_animator_node(), and load_mesh_animator_tree().
load_mesh_animator_tree()
void load_mesh_animator_tree (s32 index, StaticAnimatorNode ** tree)
Referenced by load_split_entity_data().
load_model_animator_node()
void load_model_animator_node (StaticAnimatorNode * node, ModelAnimator * animator, s32 parentNodeID, s32 * treeIndexToNodeIDs)
Referenced by load_model_animator_node(), and load_model_animator_tree().
load_model_animator_tree()
void load_model_animator_tree (s32 index, StaticAnimatorNode ** tree)
Referenced by create_shadow_from_data(), load_mesh_animator_tree(), and load_split_entity_data().
play_model_animation()
void play_model_animation (s32 index, s16 * animPos)
Referenced by entity_BellbellPlant_idle(), entity_CymbalPlant_idle(), entity_HitItemBlock_play_anim(), entity_PinkFlower_idle(), entity_ScriptSpring_idle(), entity_SimpleSpring_idle(), entity_TrumpetPlant_idle(), and func_802BC0B8_E2E9E8().
play_model_animation_starting_from()
void play_model_animation_starting_from (s32 index, s16 * animPos, s32 framesToSkip)
reload_mesh_animator_node()
void reload_mesh_animator_node (StaticAnimatorNode * node, ModelAnimator * animator, s32 parentNodeID, s32 * treeIndexToNodeIDs)
Referenced by reload_mesh_animator_node(), and reload_mesh_animator_tree().
reload_mesh_animator_tree()
void reload_mesh_animator_tree (ModelAnimator * animator)
Referenced by step_mesh_animator(), update_model_animator(), and update_model_animator_with_transform().
render_animated_model()
void render_animated_model (s32 animatorID, Mtx * rootTransform)
Referenced by render_animated_models(), render_entities(), render_shadows(), and worker_render_animator().
render_animated_model_with_vertices()
void render_animated_model_with_vertices (s32 animatorID, Mtx * rootTransform, s32 segment, void * baseAddr)
Referenced by render_entities(), and render_shadows().
reset_animator_list()
void reset_animator_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
set_anim_model_fog_color()
void set_anim_model_fog_color (s32 r, s32 g, s32 b, s32 a)
set_anim_model_fog_dist()
void set_anim_model_fog_dist (s32 start, s32 end)
set_animator_flags()
void set_animator_flags (s32 index, s32 bits)
set_animator_render_callback()
ModelAnimator * set_animator_render_callback (s32 animModelID, void * callbackArg, void(*)(void *) callbackFunc)
Referenced by render_entities().
set_animator_tree_to_node_map()
void set_animator_tree_to_node_map (ModelAnimator * animator, s32 * nodeIDs, s32 count)
Referenced by load_model_animator_tree(), and reload_mesh_animator_tree().
step_mesh_animator()
s32 step_mesh_animator (ModelAnimator * animator)
Referenced by update_model_animator(), and update_model_animator_with_transform().
step_model_animator()
s32 step_model_animator (ModelAnimator * animator)
Referenced by update_model_animator(), and update_model_animator_with_transform().
update_model_animator()
void update_model_animator (s32 animatorID)
Referenced by load_split_entity_data(), play_model_animation_starting_from(), update_entities(), update_shadows(), and worker_update_animator().
update_model_animator_with_transform()
void update_model_animator_with_transform (s32 animatorID, Mtx * mtx)
Referenced by update_animated_models().
Variable Documentation
D_801533C0
BSS AnimatedMeshVertexCopyList D_801533C0
Referenced by animator_copy_vertices_to_buffer(), clear_animator_list(), update_model_animator(), and update_model_animator_with_transform().
D_801536C0
BSS AnimatedMeshVertexCopyList D_801536C0
Referenced by appendGfx_animator_node(), clear_animator_list(), update_model_animator(), and update_model_animator_with_transform().
D_801539C0
BSS AnimatedMeshList D_801539C0
Referenced by clear_animator_list(), and reset_animator_list().
D_80153A00
BSS AnimatedMeshList D_80153A00
Referenced by clear_animator_list(), and reset_animator_list().
D_80153A64
BSS s32 D_80153A64
gAnimCount
s32 gAnimCount
Referenced by clear_animator_list(), create_mesh_animator(), create_model_animator(), delete_model_animator(), and reset_animator_list().
gAnimModelFogA
BSS s32 gAnimModelFogA
Referenced by appendGfx_animator(), clear_animator_list(), get_anim_model_fog_color(), reset_animator_list(), and set_anim_model_fog_color().
gAnimModelFogB
BSS s32 gAnimModelFogB
Referenced by appendGfx_animator(), clear_animator_list(), get_anim_model_fog_color(), reset_animator_list(), and set_anim_model_fog_color().
gAnimModelFogEnabled
BSS s32 gAnimModelFogEnabled
Referenced by appendGfx_animator(), appendGfx_animator_node(), clear_animator_list(), disable_anim_model_fog(), enable_anim_model_fog(), is_anim_model_fog_enabled(), and reset_animator_list().
gAnimModelFogEnd
BSS s32 gAnimModelFogEnd
Referenced by appendGfx_animator(), clear_animator_list(), get_anim_model_fog_distance(), reset_animator_list(), and set_anim_model_fog_dist().
gAnimModelFogG
BSS s32 gAnimModelFogG
Referenced by appendGfx_animator(), clear_animator_list(), get_anim_model_fog_color(), reset_animator_list(), and set_anim_model_fog_color().
gAnimModelFogR
BSS s32 gAnimModelFogR
Referenced by appendGfx_animator(), clear_animator_list(), get_anim_model_fog_color(), reset_animator_list(), and set_anim_model_fog_color().
gAnimModelFogStart
BSS s32 gAnimModelFogStart
Referenced by appendGfx_animator(), clear_animator_list(), get_anim_model_fog_distance(), reset_animator_list(), and set_anim_model_fog_dist().
gAnimRotMtx
BSS Matrix4f gAnimRotMtx
Referenced by animator_node_update_model_transform().
gAnimRotScaleMtx
BSS Matrix4f gAnimRotScaleMtx
Referenced by animator_node_update_model_transform().
gAnimScaleMtx
BSS Matrix4f gAnimScaleMtx
Referenced by animator_node_update_model_transform().
gAnimScriptDefault
AnimScript gAnimScriptDefault
Initial value:
= {
    AS_WAIT,  60 ,
     AS_END,
}
Referenced by create_model_animator().
gAnimTranslateMtx
BSS Matrix4f gAnimTranslateMtx
Referenced by animator_node_update_model_transform().
gAnimTreeRoot
BSS StaticAnimatorNode** gAnimTreeRoot
Referenced by load_mesh_animator_tree(), load_model_animator_node(), load_model_animator_tree(), reload_mesh_animator_node(), and reload_mesh_animator_tree().
gAnimVtxSegment
BSS s32 gAnimVtxSegment
Referenced by appendGfx_animator(), and render_animated_model_with_vertices().
gCurrentAnimMeshListPtr
BSS AnimatedMeshList* gCurrentAnimMeshListPtr
Referenced by clear_animator_list(), create_mesh_animator(), create_model_animator(), delete_model_animator(), get_animator_by_index(), and reset_animator_list().
Gfx_RM1_ALPHATEST
Gfx Gfx_RM1_ALPHATEST extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_TEX_EDGE, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM1_DECAL_OPA
Gfx Gfx_RM1_DECAL_OPA extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_DECAL, G_RM_AA_ZB_OPA_DECAL2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD |
                          G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM1_DECAL_XLU
Gfx Gfx_RM1_DECAL_XLU extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_XLU_DECAL, G_RM_AA_ZB_XLU_DECAL2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM1_INTERSECTING_OPA
Gfx Gfx_RM1_INTERSECTING_OPA extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_INTER, G_RM_AA_ZB_OPA_INTER2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD |
                          G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM1_INTERSECTING_XLU
Gfx Gfx_RM1_INTERSECTING_XLU extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_XLU_INTER, G_RM_AA_ZB_XLU_INTER2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM1_SURFACE_OPA
Gfx Gfx_RM1_SURFACE_OPA extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD |
                          G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM1_SURFACE_XLU
Gfx Gfx_RM1_SURFACE_XLU extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_XLU_SURF, G_RM_AA_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM3_ALPHATEST
Gfx Gfx_RM3_ALPHATEST extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM3_DECAL_OPA
Gfx Gfx_RM3_DECAL_OPA extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM3_DECAL_XLU
Gfx Gfx_RM3_DECAL_XLU extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_XLU_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM3_INTERSECTING_OPA
Gfx Gfx_RM3_INTERSECTING_OPA extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_INTER2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM3_INTERSECTING_XLU
Gfx Gfx_RM3_INTERSECTING_XLU extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_XLU_INTER2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM3_SURFACE_OPA
Gfx Gfx_RM3_SURFACE_OPA extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().
Gfx_RM3_SURFACE_XLU
Gfx Gfx_RM3_SURFACE_XLU extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator().