papermario: src/world/area_hos/hos_05/intro.c File Reference
intro.c File Reference
Data Structures
struct StoryGraphicData
Macros
#define TAPE_OFFSET 0x2A440
#define STORY_IMG_SIZE (264 * 162 * G_IM_SIZ_8b_BYTES)
#define TAPE_IMG_SIZE (128 * 128 * G_IM_SIZ_8b_BYTES)
#define BOWSER_IMG_SIZE (128 * 128 * G_IM_SIZ_8b_BYTES)
#define PAL_256_SIZE (256 * 2)
#define BOWSER_APPEARS_TIME (268)
Enumerations
enum {
STORY_PAGE_BLANK = 0 , STORY_PAGE_STARRY_SKY = 1 , STORY_PAGE_SHRINE_EXT = 2 , STORY_PAGE_STAR_ROD = 3 ,
STORY_PAGE_SHRINE_INT = 4
}
enum {
STORY_PAGE_STATE_BEGIN = 0 , STORY_PAGE_STATE_WAIT = 1 , STORY_PAGE_STATE_NEXT = 2 , STORY_PAGE_STATE_BOWSER_BEGIN = 3 ,
STORY_PAGE_STATE_BOWSER_ANIM = 4 , STORY_PAGE_STATE_BOWSER_NEXT = 5 , STORY_PAGE_STATE_DONE = 6
}
Functions
void N adjust_cam_vfov (s32 camID, f32 fov)
void N appendGfx_image_strips (s32 baseX, s32 baseY, IMG_PTR img, PAL_PTR pal, s32 alpha, s32 width, s32 height, s32 lineHeight)
void N draw_foreground_bowser_silhouette (void)
void N draw_background_tape (void)
void N appendGfx_image_ci (s32 baseX, s32 baseY, IMG_PTR img, PAL_PTR pal)
void N worker_draw_story_graphics (void)
void N load_story_image (s32 loadBackImage, s32 imageIdx)
Variables
f32 IntroCamStateA_BoomLength = 130.4
f32 IntroCamStateA_BoomPitch = 12.4
f32 IntroCamStateA_ViewPitch = -16.8
f32 IntroCamStateA_Vfov = 62.0
f32 IntroCamStateB_BoomLength = 130.4
f32 IntroCamStateB_BoomPitch = 12.4
f32 IntroCamStateB_ViewPitch = -16.8
f32 IntroCamStateB_Vfov = 62.0
UnkHos05Path
Data Structure Documentation
StoryGraphicData
struct StoryGraphicData
Data Fields
s16 backImgPosX
s16 backImgPosY
s16 flipOrder
s16 frontImgPosX
s16 frontImgPosY
IMG_PTR imgBack
IMG_PTR imgBowser
IMG_PTR imgFront
IMG_PTR imgTape
PAL_PTR palBack
PAL_PTR palBowser
PAL_PTR palFront
u16 silhouettePosX
u16 silhouettePosY
s16 storyPageAlpha
s16 tapeAlpha
s16 tapePosX
s16 tapePosY
char unk_14[0x4]
char unk_24[0x18]
char unk_4C[0xC]
char unk_6E[0x2]
s32 workerID
Macro Definition Documentation
BOWSER_APPEARS_TIME
#define BOWSER_APPEARS_TIME (268)
BOWSER_IMG_SIZE
#define BOWSER_IMG_SIZE (128 * 128 * G_IM_SIZ_8b_BYTES)
PAL_256_SIZE
#define PAL_256_SIZE (256 * 2)
Referenced by load_story_image().
STORY_IMG_SIZE
#define STORY_IMG_SIZE (264 * 162 * G_IM_SIZ_8b_BYTES)
Referenced by load_story_image().
TAPE_IMG_SIZE
#define TAPE_IMG_SIZE (128 * 128 * G_IM_SIZ_8b_BYTES)
TAPE_OFFSET
#define TAPE_OFFSET 0x2A440
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STORY_PAGE_BLANK
STORY_PAGE_STARRY_SKY
STORY_PAGE_SHRINE_EXT
STORY_PAGE_STAR_ROD
STORY_PAGE_SHRINE_INT
anonymous enum
anonymous enum
Enumerator
STORY_PAGE_STATE_BEGIN
STORY_PAGE_STATE_WAIT
STORY_PAGE_STATE_NEXT
STORY_PAGE_STATE_BOWSER_BEGIN
STORY_PAGE_STATE_BOWSER_ANIM
STORY_PAGE_STATE_BOWSER_NEXT
STORY_PAGE_STATE_DONE
Function Documentation
adjust_cam_vfov()
void N adjust_cam_vfov (s32 camID, f32 fov)
appendGfx_image_ci()
void N appendGfx_image_ci (s32 baseX, s32 baseY, IMG_PTR img, PAL_PTR pal)
Referenced by worker_draw_story_graphics().
appendGfx_image_strips()
void N appendGfx_image_strips (s32 baseX, s32 baseY, IMG_PTR img, PAL_PTR pal, s32 alpha, s32 width, s32 height, s32 lineHeight)
Referenced by draw_background_tape(), and draw_foreground_bowser_silhouette().
draw_background_tape()
void N draw_background_tape (void)
Referenced by worker_draw_story_graphics().
draw_foreground_bowser_silhouette()
void N draw_foreground_bowser_silhouette (void)
Referenced by curtain_callback_narration().
load_story_image()
void N load_story_image (s32 loadBackImage, s32 imageIdx)
worker_draw_story_graphics()
void N worker_draw_story_graphics (void)
Variable Documentation
IntroCamStateA_BoomLength
f32 IntroCamStateA_BoomLength = 130.4
IntroCamStateA_BoomPitch
f32 IntroCamStateA_BoomPitch = 12.4
IntroCamStateA_Vfov
f32 IntroCamStateA_Vfov = 62.0
IntroCamStateA_ViewPitch
f32 IntroCamStateA_ViewPitch = -16.8
IntroCamStateB_BoomLength
f32 IntroCamStateB_BoomLength = 130.4
IntroCamStateB_BoomPitch
f32 IntroCamStateB_BoomPitch = 12.4
IntroCamStateB_Vfov
f32 IntroCamStateB_Vfov = 62.0
IntroCamStateB_ViewPitch
f32 IntroCamStateB_ViewPitch = -16.8
UnkHos05Path
UnkHos05Path