papermario: src/effects/attack_result_text.c File Reference
attack_result_text.c File Reference
Functions
void attack_result_text_init (EffectInstance *effect)
void attack_result_text_update (EffectInstance *effect)
void attack_result_text_render (EffectInstance *effect)
void func_E0090428 (EffectInstance *effect)
void func_E0090444 (EffectInstance *effect)
EffectInstance * attack_result_text_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 appearVel, s32 duration)
Variables
Gfx D_09001500_3918D0 []
Gfx D_090015A8_391978 []
Gfx D_09001610_3919E0 []
Gfx D_09001658_391A28 []
Gfx D_090016A0_391A70 []
Gfx D_090016E8_391AB8 []
Gfx D_09001730_391B00 []
Gfx D_090018B8_391C88 []
Gfx D_090018D8_391CA8 []
Gfx D_090018F8_391CC8 []
Gfx D_09001918_391CE8 []
Gfx D_09001938_391D08 []
Gfx * D_E0090A40 [5] = { D_09001658_391A28, D_09001610_3919E0, D_090016A0_391A70, D_090016E8_391AB8, D_09001730_391B00 }
Gfx * D_E0090A54 [5] = { D_090018D8_391CA8, D_090018B8_391C88, D_090018F8_391CC8, D_09001918_391CE8, D_09001938_391D08 }
u8 D_E0090A68 [8] = { 10, 40, 80, 120, 125, 100, 90, 100 }
u8 D_E0090A70 [8] = { 60, 80, 100, 110, 112, 95, 100, 0 }
s8 D_E0090A78 [5][6]
Function Documentation
attack_result_text_init()
void attack_result_text_init (EffectInstance * effect)
Referenced by attack_result_text_main().
attack_result_text_main()
EffectInstance * attack_result_text_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 appearVel, s32 duration)
attack_result_text_render()
void attack_result_text_render (EffectInstance * effect)
Referenced by attack_result_text_main().
attack_result_text_update()
void attack_result_text_update (EffectInstance * effect)
Referenced by attack_result_text_main().
func_E0090428()
void func_E0090428 (EffectInstance * effect)
Referenced by attack_result_text_main().
func_E0090444()
void func_E0090444 (EffectInstance * effect)
Referenced by func_E0090428().
Variable Documentation
D_09001500_3918D0
Gfx D_09001500_3918D0[] extern
Referenced by func_E0090444().
D_090015A8_391978
Gfx D_090015A8_391978[] extern
Referenced by func_E0090444().
D_09001610_3919E0
Gfx D_09001610_3919E0[] extern
D_09001658_391A28
Gfx D_09001658_391A28[] extern
D_090016A0_391A70
Gfx D_090016A0_391A70[] extern
D_090016E8_391AB8
Gfx D_090016E8_391AB8[] extern
D_09001730_391B00
Gfx D_09001730_391B00[] extern
D_090018B8_391C88
Gfx D_090018B8_391C88[] extern
D_090018D8_391CA8
Gfx D_090018D8_391CA8[] extern
D_090018F8_391CC8
Gfx D_090018F8_391CC8[] extern
D_09001918_391CE8
Gfx D_09001918_391CE8[] extern
D_09001938_391D08
Gfx D_09001938_391D08[] extern
D_E0090A40
Gfx* D_E0090A40[5] = { D_09001658_391A28, D_09001610_3919E0, D_090016A0_391A70, D_090016E8_391AB8, D_09001730_391B00 }
Referenced by func_E0090444().
D_E0090A54
Gfx* D_E0090A54[5] = { D_090018D8_391CA8, D_090018B8_391C88, D_090018F8_391CC8, D_09001918_391CE8, D_09001938_391D08 }
Referenced by func_E0090444().
D_E0090A68
u8 D_E0090A68[8] = { 10, 40, 80, 120, 125, 100, 90, 100 }
Referenced by attack_result_text_update().
D_E0090A70
u8 D_E0090A70[8] = { 60, 80, 100, 110, 112, 95, 100, 0 }
Referenced by attack_result_text_update().
D_E0090A78
s8 D_E0090A78[5][6]
Initial value:
= {
    { 255, 255, 255, 254, 159, 15 },
    { 215, 86, 0, 254, 207, 15 },
    { 254, 159, 15, 229, 21, 0 },
    { 0, 107, 42, 255, 217, 69 },
    { 0, 0, 215, 151, 255, 255 },
}
Referenced by func_E0090444().