papermario: src/effects/aura.c File Reference
aura.c File Reference
Functions
void aura_appendGfx (void *argEffect)
void aura_init (EffectInstance *effect)
void aura_update (EffectInstance *effect)
void aura_render (EffectInstance *effect)
void aura_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, EffectInstance **outEffect)
void func_E007684C (void)
void func_E0076854 (void)
Variables
Gfx D_09002000_379F80 []
Gfx D_090020E8_37A068 []
Gfx D_090021D0_37A150 []
Gfx D_090023B0_37A330 []
Gfx D_090023C8_37A348 []
Gfx D_090023E0_37A360 []
Gfx D_090023F8_37A378 []
Gfx D_09002410_37A390 []
Gfx D_09002428_37A3A8 []
Gfx D_09002440_37A3C0 []
Gfx D_09002458_37A3D8 []
Gfx * D_E0076E90 []
Gfx * D_E0076EA0 []
Gfx * D_E0076EB0 []
Gfx * D_E0076EC0 []
Gfx * D_E0076ED0 []
Function Documentation
aura_appendGfx()
void aura_appendGfx (void * argEffect)
Referenced by aura_render().
aura_init()
void aura_init (EffectInstance * effect)
Referenced by aura_main().
aura_main()
void aura_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, EffectInstance ** outEffect)
aura_render()
void aura_render (EffectInstance * effect)
Referenced by aura_main().
aura_update()
void aura_update (EffectInstance * effect)
Referenced by aura_main().
func_E007684C()
void func_E007684C (void)
func_E0076854()
void func_E0076854 (void)
Variable Documentation
D_09002000_379F80
Gfx D_09002000_379F80[] extern
D_090020E8_37A068
Gfx D_090020E8_37A068[] extern
D_090021D0_37A150
Gfx D_090021D0_37A150[] extern
D_090023B0_37A330
Gfx D_090023B0_37A330[] extern
D_090023C8_37A348
Gfx D_090023C8_37A348[] extern
D_090023E0_37A360
Gfx D_090023E0_37A360[] extern
D_090023F8_37A378
Gfx D_090023F8_37A378[] extern
D_09002410_37A390
Gfx D_09002410_37A390[] extern
D_09002428_37A3A8
Gfx D_09002428_37A3A8[] extern
D_09002440_37A3C0
Gfx D_09002440_37A3C0[] extern
D_09002458_37A3D8
Gfx D_09002458_37A3D8[] extern
D_E0076E90
Gfx* D_E0076E90[]
Initial value:
= {
    [FX_AURA_CAPTURE]   D_090023E0_37A360,
    [FX_AURA_RED]       D_090023E0_37A360,
    [FX_AURA_BLUE]      D_09002440_37A3C0,
    [FX_AURA_GOLD]      D_09002440_37A3C0
}
Referenced by aura_appendGfx().
D_E0076EA0
Gfx* D_E0076EA0[]
Initial value:
= {
    [FX_AURA_CAPTURE]   D_090023F8_37A378,
    [FX_AURA_RED]       D_090023F8_37A378,
    [FX_AURA_BLUE]      D_09002458_37A3D8,
    [FX_AURA_GOLD]      D_09002458_37A3D8
}
Referenced by aura_appendGfx().
D_E0076EB0
Gfx* D_E0076EB0[]
Initial value:
= {
    [FX_AURA_CAPTURE]   D_090023B0_37A330,
    [FX_AURA_RED]       D_090023B0_37A330,
    [FX_AURA_BLUE]      D_09002410_37A390,
    [FX_AURA_GOLD]      D_09002410_37A390
}
Referenced by aura_appendGfx().
D_E0076EC0
Gfx* D_E0076EC0[]
Initial value:
= {
    [FX_AURA_CAPTURE]   D_090023C8_37A348,
    [FX_AURA_RED]       D_090023C8_37A348,
    [FX_AURA_BLUE]      D_09002428_37A3A8,
    [FX_AURA_GOLD]      D_09002428_37A3A8
}
Referenced by aura_appendGfx().
D_E0076ED0
Gfx* D_E0076ED0[]
Initial value:
= {
    [FX_AURA_CAPTURE]   D_09002000_379F80,
    [FX_AURA_RED]       D_09002000_379F80,
    [FX_AURA_BLUE]      D_090020E8_37A068,
    [FX_AURA_GOLD]      D_090021D0_37A150
}
Referenced by aura_appendGfx().