papermario: src/background.c File Reference
background.c File Reference
Functions
void load_map_bg (char *optAssetName)
void reset_background_settings (void)
void set_background (BackgroundHeader *bg)
void set_background_size (s16 startX, s16 startY, s16 sizeX, s16 sizeY)
u16 blend_background_channel (u16 arg0, s32 arg1, s32 alpha)
void appendGfx_background_texture (void)
void enable_background_wave (void)
void disable_background_wave (void)
Variables
char gCloudyFlowerFieldsBg [] = "fla_bg"
char gSunnyFlowerFieldsBg [] = "flb_bg"
s8 gBackroundWaveEnabled = FALSE
s16 gBackroundTextureYOffset = 0
f32 gBackroundWavePhase = 0.0f
BSS PAL_BIN gBackgroundPalette [256]
BSS f32 gBackroundLastScrollValue
BSS s32 D_801595A4 [3]
BSS s32 D_801595AC
Function Documentation
appendGfx_background_texture()
void appendGfx_background_texture (void)
Bug
xh = 2 * bgXOffset + (bgMinX - 1) * 4
Bug
xh = 2 * bgXOffset + (bgMinX - 1) * 4
Referenced by gfx_draw_background().
blend_background_channel()
u16 blend_background_channel (u16 arg0, s32 arg1, s32 alpha)
Referenced by appendGfx_background_texture().
disable_background_wave()
void disable_background_wave (void)
enable_background_wave()
void enable_background_wave (void)
Referenced by EnableBackgroundWave().
load_map_bg()
void load_map_bg (char * optAssetName)
Referenced by btl_state_update_normal_start(), load_map_by_IDs(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
reset_background_settings()
void reset_background_settings (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
set_background()
void set_background (BackgroundHeader * bg)
Referenced by btl_state_update_normal_start(), load_map_by_IDs(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
set_background_size()
void set_background_size (s16 startX, s16 startY, s16 sizeX, s16 sizeY)
Referenced by load_map_by_IDs(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
Variable Documentation
D_801595A4
BSS s32 D_801595A4[3]
D_801595AC
BSS s32 D_801595AC
gBackgroundPalette
BSS PAL_BIN gBackgroundPalette[256]
Referenced by appendGfx_background_texture().
gBackroundLastScrollValue
BSS f32 gBackroundLastScrollValue
Referenced by appendGfx_background_texture(), and reset_background_settings().
gBackroundTextureYOffset
s16 gBackroundTextureYOffset = 0
Referenced by appendGfx_background_texture().
gBackroundWaveEnabled
s8 gBackroundWaveEnabled = FALSE
Referenced by appendGfx_background_texture(), disable_background_wave(), enable_background_wave(), and reset_background_settings().
gBackroundWavePhase
f32 gBackroundWavePhase = 0.0f
Referenced by appendGfx_background_texture().
gCloudyFlowerFieldsBg
char gCloudyFlowerFieldsBg[] = "fla_bg"
Referenced by load_map_bg().
gSunnyFlowerFieldsBg
char gSunnyFlowerFieldsBg[] = "flb_bg"
Referenced by load_map_bg().