papermario: src/battle/battle.c File Reference
battle.c File Reference
Macros
#define BTL_AREA(id, jpName)
#define BTL_AREA_DMA(id, jpName)
#define BTL_AREA_AUX(id, jpName)
Functions
void reset_battle_status (void)
void ALT_reset_battle_status (void)
void func_80072BCC (s32 arg0)
void load_battle_section (void)
void load_battle (s32 battleID)
void set_battle_stage (s32 stageID)
void set_battle_formation (Battle *battle)
void func_80072CEC (f32 arg0, f32 arg1, f32 arg2)
void func_80072CF4 (void)
void setup_demo_player (void)
void load_demo_battle (u32 index)
Variables
s32 D_800DC060
StageListRow * gCurrentStagePtr
s32 gBattleState
BattleStatus gBattleStatus
s32 gLastDrawBattleState
s32 D_800DC4D4
s32 gDefeatedBattleSubstate
s32 gBattleSubState
s32 D_800DC4E0
s32 gDefeatedBattleState
s32 gCurrentBattleID
s32 gCurrentStageID
s32 D_800DC4F0
Battle * gOverrideBattlePtr
s32 D_800DC4F8
Battle * gCurrentBattlePtr
BattleArea gBattleAreas []
Macro Definition Documentation
BTL_AREA
#define BTL_AREA (id, jpName)
Value:
    { \
    .dmaStart = battle_area_##id##_ROM_START, \
    .dmaEnd = battle_area_##id##_ROM_END, \
    .dmaDest = battle_area_##id##_VRAM, \
    .battles = &b_area_##id##_Formations, \
    .stages = &b_area_##id##_Stages, \
    .name = jpName, \
} \
BTL_AREA_AUX
#define BTL_AREA_AUX (id, jpName)
Value:
    { \
    .dmaStart = battle_area_##id##_ROM_START, \
    .dmaEnd = battle_area_##id##_ROM_END, \
    .dmaDest = battle_area_##id##_VRAM, \
    .name = jpName, \
} \
BTL_AREA_DMA
#define BTL_AREA_DMA (id, jpName)
Value:
    { \
    .dmaStart = battle_area_##id##_ROM_START, \
    .dmaEnd = battle_area_##id##_ROM_END, \
    .dmaDest = battle_area_##id##_VRAM, \
    .battles = &b_area_##id##_Formations, \
    .stages = &b_area_##id##_Stages, \
    .dmaTable = b_area_##id##_dmaTable, \
    .name = jpName, \
} \
Function Documentation
ALT_reset_battle_status()
void ALT_reset_battle_status (void)
func_80072BCC()
void func_80072BCC (s32 arg0)
func_80072CEC()
void func_80072CEC (f32 arg0, f32 arg1, f32 arg2)
Referenced by func_80072CF4().
func_80072CF4()
void func_80072CF4 (void)
load_battle()
void load_battle (s32 battleID)
Referenced by load_demo_battle(), and update_encounters_pre_battle().
load_battle_section()
void load_battle_section (void)
Referenced by state_step_battle().
load_demo_battle()
void load_demo_battle (u32 index)
Referenced by state_step_demo().
reset_battle_status()
void reset_battle_status (void)
Referenced by ALT_reset_battle_status(), load_demo_battle(), load_map_by_IDs(), state_step_demo(), state_step_intro(), and state_step_startup().
set_battle_formation()
void set_battle_formation (Battle * battle)
Referenced by update_encounters_pre_battle().
set_battle_stage()
void set_battle_stage (s32 stageID)
Referenced by load_demo_battle(), and update_encounters_pre_battle().
setup_demo_player()
void setup_demo_player (void)
Referenced by load_demo_battle().
Variable Documentation
D_800DC060
s32 D_800DC060 extern
Referenced by reset_battle_status().
D_800DC4D4
s32 D_800DC4D4 extern
Referenced by reset_battle_status().
D_800DC4E0
s32 D_800DC4E0 extern
Referenced by reset_battle_status().
D_800DC4F0
s32 D_800DC4F0 extern
Referenced by reset_battle_status().
D_800DC4F8
s32 D_800DC4F8 extern
Referenced by func_80072BCC(), and reset_battle_status().
gBattleAreas
BattleArea gBattleAreas[]
Referenced by load_battle_section().
gBattleState
s32 gBattleState extern
Referenced by load_battle(), and reset_battle_status().
gBattleStatus
BattleStatus gBattleStatus extern
gBattleSubState
s32 gBattleSubState extern
Referenced by load_battle(), and reset_battle_status().
gCurrentBattleID
s32 gCurrentBattleID extern
Referenced by load_battle(), load_battle_section(), and reset_battle_status().
gCurrentBattlePtr
Battle* gCurrentBattlePtr extern
Referenced by btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_normal_start(), load_battle_section(), and reset_battle_status().
gCurrentStageID
s32 gCurrentStageID extern
Referenced by load_battle_section(), reset_battle_status(), and set_battle_stage().
gCurrentStagePtr
StageListRow* gCurrentStagePtr extern
Referenced by load_battle_section(), and reset_battle_status().
gDefeatedBattleState
s32 gDefeatedBattleState extern
gDefeatedBattleSubstate
s32 gDefeatedBattleSubstate extern
gLastDrawBattleState
s32 gLastDrawBattleState extern
Referenced by load_battle(), load_battle_section(), and reset_battle_status().
gOverrideBattlePtr
Battle* gOverrideBattlePtr extern
Referenced by reset_battle_status(), and set_battle_formation().