papermario: src/battle_ui_gfx.c File Reference
battle_ui_gfx.c File Reference
Macros
#define ui_battle_menu_unused_disabled_png ui_battle_menu_unused_png
#define ui_battle_menu_flee_disabled_png ui_battle_menu_flee_png
#define ui_battle_menu_defend_disabled_png ui_battle_menu_defend_png
#define ui_battle_menu_strategies_disabled_png ui_battle_menu_strategies_png
#define ui_battle_menu_nothing_disabled_png ui_battle_menu_nothing_png
#define ui_battle_menu_pouch_disabled_png ui_battle_menu_pouch_png
Functions
INCLUDE_IMG ("ui/battle/menu/unused.png", ui_battle_menu_unused_png)
INCLUDE_PAL ("ui/battle/menu/unused.pal", ui_battle_menu_unused_pal)
INCLUDE_PAL ("ui/battle/menu/unused.disabled.pal", ui_battle_menu_unused_disabled_pal)
INCLUDE_IMG ("ui/battle/menu/flee.png", ui_battle_menu_flee_png)
INCLUDE_PAL ("ui/battle/menu/flee.pal", ui_battle_menu_flee_pal)
INCLUDE_PAL ("ui/battle/menu/flee.disabled.pal", ui_battle_menu_flee_disabled_pal)
INCLUDE_IMG ("ui/battle/menu/defend.png", ui_battle_menu_defend_png)
INCLUDE_PAL ("ui/battle/menu/defend.pal", ui_battle_menu_defend_pal)
INCLUDE_PAL ("ui/battle/menu/defend.disabled.pal", ui_battle_menu_defend_disabled_pal)
INCLUDE_IMG ("ui/battle/menu/strategies.png", ui_battle_menu_strategies_png)
INCLUDE_PAL ("ui/battle/menu/strategies.pal", ui_battle_menu_strategies_pal)
INCLUDE_PAL ("ui/battle/menu/strategies.disabled.pal", ui_battle_menu_strategies_disabled_pal)
INCLUDE_IMG ("ui/battle/menu/nothing.png", ui_battle_menu_nothing_png)
INCLUDE_PAL ("ui/battle/menu/nothing.pal", ui_battle_menu_nothing_pal)
INCLUDE_PAL ("ui/battle/menu/nothing.disabled.pal", ui_battle_menu_nothing_disabled_pal)
INCLUDE_IMG ("ui/battle/menu/pouch.png", ui_battle_menu_pouch_png)
INCLUDE_PAL ("ui/battle/menu/pouch.pal", ui_battle_menu_pouch_pal)
INCLUDE_PAL ("ui/battle/menu/pouch.disabled.pal", ui_battle_menu_pouch_disabled_pal)
INCLUDE_IMG ("ui/battle/swap_Z.png", ui_battle_swap_Z_png)
INCLUDE_PAL ("ui/battle/swap_Z.pal", ui_battle_swap_Z_pal)
INCLUDE_IMG ("ui/battle/swap_arrow_left.png", ui_battle_swap_arrow_left_png)
INCLUDE_PAL ("ui/battle/swap_arrow_left.pal", ui_battle_swap_arrow_left_pal)
INCLUDE_IMG ("ui/battle/swap_arrow_right.png", ui_battle_swap_arrow_right_png)
INCLUDE_PAL ("ui/battle/swap_arrow_right.pal", ui_battle_swap_arrow_right_pal)
INCLUDE_IMG ("ui/battle/menu/spirits.png", ui_battle_menu_spirits_png)
INCLUDE_PAL ("ui/battle/menu/spirits.pal", ui_battle_menu_spirits_pal)
INCLUDE_IMG ("ui/battle/yellow_arrow.png", ui_battle_yellow_arrow_png)
INCLUDE_PAL ("ui/battle/yellow_arrow.pal", ui_battle_yellow_arrow_pal)
INCLUDE_IMG ("ui/battle/hp_bar.png", ui_battle_hp_bar_png)
INCLUDE_PAL ("ui/battle/hp_bar.pal", ui_battle_hp_bar_pal)
INCLUDE_IMG ("ui/battle/hp_0.png", ui_battle_hp_0_png)
INCLUDE_PAL ("ui/battle/hp_0.pal", ui_battle_hp_0_pal)
INCLUDE_IMG ("ui/battle/hp_1.png", ui_battle_hp_1_png)
INCLUDE_PAL ("ui/battle/hp_1.pal", ui_battle_hp_1_pal)
INCLUDE_IMG ("ui/battle/hp_2.png", ui_battle_hp_2_png)
INCLUDE_PAL ("ui/battle/hp_2.pal", ui_battle_hp_2_pal)
INCLUDE_IMG ("ui/battle/hp_3.png", ui_battle_hp_3_png)
INCLUDE_PAL ("ui/battle/hp_3.pal", ui_battle_hp_3_pal)
INCLUDE_IMG ("ui/battle/hp_4.png", ui_battle_hp_4_png)
INCLUDE_PAL ("ui/battle/hp_4.pal", ui_battle_hp_4_pal)
INCLUDE_IMG ("ui/battle/hp_5.png", ui_battle_hp_5_png)
INCLUDE_PAL ("ui/battle/hp_5.pal", ui_battle_hp_5_pal)
INCLUDE_IMG ("ui/battle/hp_6.png", ui_battle_hp_6_png)
INCLUDE_PAL ("ui/battle/hp_6.pal", ui_battle_hp_6_pal)
INCLUDE_IMG ("ui/battle/hp_7.png", ui_battle_hp_7_png)
INCLUDE_PAL ("ui/battle/hp_7.pal", ui_battle_hp_7_pal)
INCLUDE_IMG ("ui/battle/hp_8.png", ui_battle_hp_8_png)
INCLUDE_PAL ("ui/battle/hp_8.pal", ui_battle_hp_8_pal)
INCLUDE_IMG ("ui/battle/hp_9.png", ui_battle_hp_9_png)
INCLUDE_PAL ("ui/battle/hp_9.pal", ui_battle_hp_9_pal)
INCLUDE_IMG ("ui/battle/cont/b_up.png", ui_battle_cont_b_up_png)
INCLUDE_PAL ("ui/battle/cont/b_up.pal", ui_battle_cont_b_up_pal)
INCLUDE_IMG ("ui/battle/cont/b_down.png", ui_battle_cont_b_down_png)
INCLUDE_PAL ("ui/battle/cont/b_down.pal", ui_battle_cont_b_down_pal)
INCLUDE_IMG ("ui/battle/cont/c_left_up.png", ui_battle_cont_c_left_up_png)
INCLUDE_PAL ("ui/battle/cont/c_left_up.pal", ui_battle_cont_c_left_up_pal)
INCLUDE_IMG ("ui/battle/cont/c_left_down.png", ui_battle_cont_c_left_down_png)
INCLUDE_PAL ("ui/battle/cont/c_left_down.pal", ui_battle_cont_c_left_down_pal)
INCLUDE_IMG ("ui/battle/cont/c_right_up.png", ui_battle_cont_c_right_up_png)
INCLUDE_PAL ("ui/battle/cont/c_right_up.pal", ui_battle_cont_c_right_up_pal)
INCLUDE_IMG ("ui/battle/cont/c_right_down.png", ui_battle_cont_c_right_down_png)
INCLUDE_PAL ("ui/battle/cont/c_right_down.pal", ui_battle_cont_c_right_down_pal)
INCLUDE_IMG ("ui/battle/cont/c_up_up.png", ui_battle_cont_c_up_up_png)
INCLUDE_PAL ("ui/battle/cont/c_up_up.pal", ui_battle_cont_c_up_up_pal)
INCLUDE_IMG ("ui/battle/cont/c_up_down.png", ui_battle_cont_c_up_down_png)
INCLUDE_PAL ("ui/battle/cont/c_up_down.pal", ui_battle_cont_c_up_down_pal)
INCLUDE_IMG ("ui/battle/cont/c_down_up.png", ui_battle_cont_c_down_up_png)
INCLUDE_PAL ("ui/battle/cont/c_down_up.pal", ui_battle_cont_c_down_up_pal)
INCLUDE_IMG ("ui/battle/cont/c_down_down.png", ui_battle_cont_c_down_down_png)
INCLUDE_PAL ("ui/battle/cont/c_down_down.pal", ui_battle_cont_c_down_down_pal)
INCLUDE_IMG ("ui/battle/cmd/timing_1_chance.png", ui_battle_cmd_timing_1_chance_png)
INCLUDE_PAL ("ui/battle/cmd/timing_1_chance.pal", ui_battle_cmd_timing_1_chance_pal)
INCLUDE_IMG ("ui/battle/cmd/timing_ready.png", ui_battle_cmd_timing_ready_png)
INCLUDE_PAL ("ui/battle/cmd/timing_ready.pal", ui_battle_cmd_timing_ready_pal)
INCLUDE_IMG ("ui/battle/cmd/timing_wait.png", ui_battle_cmd_timing_wait_png)
INCLUDE_PAL ("ui/battle/cmd/timing_wait.pal", ui_battle_cmd_timing_wait_pal)
INCLUDE_IMG ("ui/battle/cmd/charge_1.png", ui_battle_cmd_charge_1_png)
INCLUDE_PAL ("ui/battle/cmd/charge_1.pal", ui_battle_cmd_charge_1_pal)
INCLUDE_IMG ("ui/battle/cmd/charge_2.png", ui_battle_cmd_charge_2_png)
INCLUDE_PAL ("ui/battle/cmd/charge_2.pal", ui_battle_cmd_charge_2_pal)
INCLUDE_IMG ("ui/battle/cmd/charge_3.png", ui_battle_cmd_charge_3_png)
INCLUDE_PAL ("ui/battle/cmd/charge_3.pal", ui_battle_cmd_charge_3_pal)
INCLUDE_IMG ("ui/battle/cmd/charge_4.png", ui_battle_cmd_charge_4_png)
INCLUDE_PAL ("ui/battle/cmd/charge_4.pal", ui_battle_cmd_charge_4_pal)
INCLUDE_IMG ("ui/battle/cmd/timing_3_chances.png", ui_battle_cmd_timing_3_chances_png)
INCLUDE_PAL ("ui/battle/cmd/timing_3_chances.pal", ui_battle_cmd_timing_3_chances_pal)
INCLUDE_IMG ("ui/battle/cmd/gauge_result.png", ui_battle_cmd_gauge_result_png)
INCLUDE_PAL ("ui/battle/cmd/gauge_result.pal", ui_battle_cmd_gauge_result_pal)
INCLUDE_IMG ("ui/battle/cmd/timing_ok.png", ui_battle_cmd_timing_ok_png)
INCLUDE_PAL ("ui/battle/cmd/timing_ok.pal", ui_battle_cmd_timing_ok_pal)
INCLUDE_IMG ("ui/battle/cmd/timing_miss.png", ui_battle_cmd_timing_miss_png)
INCLUDE_PAL ("ui/battle/cmd/timing_miss.pal", ui_battle_cmd_timing_miss_pal)
INCLUDE_IMG ("ui/battle/cmd/flee_0.png", ui_battle_cmd_flee_0_png)
INCLUDE_PAL ("ui/battle/cmd/flee_0.pal", ui_battle_cmd_flee_0_pal)
INCLUDE_IMG ("ui/battle/cmd/flee_1.png", ui_battle_cmd_flee_1_png)
INCLUDE_PAL ("ui/battle/cmd/flee_1.pal", ui_battle_cmd_flee_1_pal)
INCLUDE_IMG ("ui/battle/cmd/flee_2.png", ui_battle_cmd_flee_2_png)
INCLUDE_PAL ("ui/battle/cmd/flee_2.pal", ui_battle_cmd_flee_2_pal)
INCLUDE_IMG ("ui/battle/cmd/100pct.png", ui_battle_cmd_100pct_png)
INCLUDE_PAL ("ui/battle/cmd/100pct.pal", ui_battle_cmd_100pct_pal)
INCLUDE_IMG ("ui/battle/cmd/right_on.png", ui_battle_cmd_right_on_png)
INCLUDE_PAL ("ui/battle/cmd/right_on.pal", ui_battle_cmd_right_on_pal)
INCLUDE_IMG ("ui/battle/cmd/fill_result.png", ui_battle_cmd_fill_result_png)
INCLUDE_PAL ("ui/battle/cmd/fill_result.pal", ui_battle_cmd_fill_result_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/marker_0.png", ui_battle_cmd_aim_marker_0_png)
INCLUDE_PAL ("ui/battle/cmd/aim/marker_0.pal", ui_battle_cmd_aim_marker_0_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/marker_1.png", ui_battle_cmd_aim_marker_1_png)
INCLUDE_PAL ("ui/battle/cmd/aim/marker_1.pal", ui_battle_cmd_aim_marker_1_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/marker_2.png", ui_battle_cmd_aim_marker_2_png)
INCLUDE_PAL ("ui/battle/cmd/aim/marker_2.pal", ui_battle_cmd_aim_marker_2_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/marker_3.png", ui_battle_cmd_aim_marker_3_png)
INCLUDE_PAL ("ui/battle/cmd/aim/marker_3.pal", ui_battle_cmd_aim_marker_3_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/marker_4.png", ui_battle_cmd_aim_marker_4_png)
INCLUDE_PAL ("ui/battle/cmd/aim/marker_4.pal", ui_battle_cmd_aim_marker_4_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/marker_5.png", ui_battle_cmd_aim_marker_5_png)
INCLUDE_PAL ("ui/battle/cmd/aim/marker_5.pal", ui_battle_cmd_aim_marker_5_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/marker_6.png", ui_battle_cmd_aim_marker_6_png)
INCLUDE_PAL ("ui/battle/cmd/aim/marker_6.pal", ui_battle_cmd_aim_marker_6_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/marker_7.png", ui_battle_cmd_aim_marker_7_png)
INCLUDE_PAL ("ui/battle/cmd/aim/marker_7.pal", ui_battle_cmd_aim_marker_7_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_0.png", ui_battle_cmd_aim_shimmer_0_png)
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_0.pal", ui_battle_cmd_aim_shimmer_0_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_1.png", ui_battle_cmd_aim_shimmer_1_png)
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_1.pal", ui_battle_cmd_aim_shimmer_1_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_2.png", ui_battle_cmd_aim_shimmer_2_png)
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_2.pal", ui_battle_cmd_aim_shimmer_2_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_3.png", ui_battle_cmd_aim_shimmer_3_png)
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_3.pal", ui_battle_cmd_aim_shimmer_3_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_4.png", ui_battle_cmd_aim_shimmer_4_png)
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_4.pal", ui_battle_cmd_aim_shimmer_4_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_5.png", ui_battle_cmd_aim_shimmer_5_png)
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_5.pal", ui_battle_cmd_aim_shimmer_5_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_6.png", ui_battle_cmd_aim_shimmer_6_png)
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_6.pal", ui_battle_cmd_aim_shimmer_6_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_7.png", ui_battle_cmd_aim_shimmer_7_png)
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_7.pal", ui_battle_cmd_aim_shimmer_7_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/reticle_0.png", ui_battle_cmd_aim_reticle_0_png)
INCLUDE_PAL ("ui/battle/cmd/aim/reticle_0.pal", ui_battle_cmd_aim_reticle_0_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/reticle_1.png", ui_battle_cmd_aim_reticle_1_png)
INCLUDE_PAL ("ui/battle/cmd/aim/reticle_1.pal", ui_battle_cmd_aim_reticle_1_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/target_0.png", ui_battle_cmd_aim_target_0_png)
INCLUDE_PAL ("ui/battle/cmd/aim/target_0.pal", ui_battle_cmd_aim_target_0_pal)
INCLUDE_IMG ("ui/battle/cmd/aim/target_1.png", ui_battle_cmd_aim_target_1_png)
INCLUDE_PAL ("ui/battle/cmd/aim/target_1.pal", ui_battle_cmd_aim_target_1_pal)
INCLUDE_IMG ("ui/battle/solid_star.png", ui_battle_solid_star_png)
INCLUDE_PAL ("ui/battle/solid_star.pal", ui_battle_solid_star_pal)
INCLUDE_IMG ("ui/battle/projector_spot.png", ui_battle_projector_spot_png)
INCLUDE_IMG ("ui/battle/projector_beam.png", ui_battle_projector_beam_png)
INCLUDE_IMG ("ui/battle/projector_reel.png", ui_battle_projector_reel_png)
INCLUDE_IMG ("ui/battle/swap_background.png", ui_battle_swap_background_png)
Variables
Gfx D_8028F860 []
Gfx D_8028FC68 []
Gfx D_80290C70 []
Gfx D_80291C78 []
HudScript HES_HPBar = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_bar_png, (s32) ui_battle_hp_bar_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_0_png, (s32) ui_battle_hp_0_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_1_png, (s32) ui_battle_hp_1_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_2_png, (s32) ui_battle_hp_2_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_3_png, (s32) ui_battle_hp_3_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_4_png, (s32) ui_battle_hp_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_5_png, (s32) ui_battle_hp_5_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_6_png, (s32) ui_battle_hp_6_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_7_png, (s32) ui_battle_hp_7_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_8_png, (s32) ui_battle_hp_8_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_HPDigit9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_9_png, (s32) ui_battle_hp_9_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_YellowArrow = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_16x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_yellow_arrow_png, (s32) ui_battle_yellow_arrow_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuFlee = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_flee_png, (s32) ui_battle_menu_flee_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuFleeDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_flee_png , (s32) ui_battle_menu_flee_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuDefend = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_defend_png, (s32) ui_battle_menu_defend_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuDefendDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_defend_png , (s32) ui_battle_menu_defend_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuStrategies = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_strategies_png, (s32) ui_battle_menu_strategies_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuStrategiesDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_strategies_png , (s32) ui_battle_menu_strategies_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuPouch = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_pouch_png, (s32) ui_battle_menu_pouch_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuPouchDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_pouch_png , (s32) ui_battle_menu_pouch_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuDoNothing = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_nothing_png, (s32) ui_battle_menu_nothing_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MenuDoNothingDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_nothing_png , (s32) ui_battle_menu_nothing_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingBar1Chance = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 72 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_1_chance_png, (s32) ui_battle_cmd_timing_1_chance_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_BButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 48 , 40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_b_up_png, (s32) ui_battle_cont_b_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_BButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 48 , 40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_b_down_png, (s32) ui_battle_cont_b_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MashBButton1
HudScript HES_PressBButton
HudScript HES_MashBButton2
HudScript HES_CLeftButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_left_up_png, (s32) ui_battle_cont_c_left_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_CLeftButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_left_down_png, (s32) ui_battle_cont_c_left_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MashCLeftButton
HudScript HES_CRightButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_right_up_png, (s32) ui_battle_cont_c_right_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_CRightButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_right_down_png, (s32) ui_battle_cont_c_right_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MashCRightButton1
HudScript HES_MashCRightButton2
HudScript HES_CUpButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_up_up_png, (s32) ui_battle_cont_c_up_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_CUpButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_up_down_png, (s32) ui_battle_cont_c_up_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MashCUpButton
HudScript HES_CDownButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_down_up_png, (s32) ui_battle_cont_c_down_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_CDownButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_down_down_png, (s32) ui_battle_cont_c_down_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_MashCDownButton1
HudScript HES_PressCDownButton
HudScript HES_MashCDownButton2
HudScript HES_TimingWait = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 16 , 16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_wait_png, (s32) ui_battle_cmd_timing_wait_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingReady = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 16 , 16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_ready_png, (s32) ui_battle_cmd_timing_ready_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingBlink
HudScript HES_TimingCharge4a = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_4_png, (s32) ui_battle_cmd_charge_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingCharge1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_1_png, (s32) ui_battle_cmd_charge_1_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingCharge4b = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_4_png, (s32) ui_battle_cmd_charge_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingCharge2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_2_png, (s32) ui_battle_cmd_charge_2_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingCharge4c = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_4_png, (s32) ui_battle_cmd_charge_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingCharge3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_3_png, (s32) ui_battle_cmd_charge_3_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_RunningAway
HudScript HES_100pct
HudScript HES_RightOn
HudScript HES_TimingBar3Chances = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 96 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_3_chances_png, (s32) ui_battle_cmd_timing_3_chances_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingGaugeResult = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_gauge_result_png, (s32) ui_battle_cmd_gauge_result_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingOK = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 24 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_ok_png, (s32) ui_battle_cmd_timing_ok_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_TimingMiss = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 24 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_miss_png, (s32) ui_battle_cmd_timing_miss_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_FillGaugeResult = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_fill_result_png, (s32) ui_battle_cmd_fill_result_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_ProjectorReel
HudScript HES_ProjectorSpot
HudScript HES_ProjectorBeam
HudScript HES_SwapZ = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 16 , 16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_swap_Z_png, (s32) ui_battle_swap_Z_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_SwapArrowLeft
HudScript HES_SwapArrowRight
HudScript HES_SwapBackground
HudScript HES_AimMarkerA
HudScript HES_AimMarkerB
HudScript HES_AimMarkerC
HudScript HES_AimMarkerD
HudScript HES_AimMarkerE
HudScript HES_AimMarkerF
HudScript HES_AimMarkerG
HudScript HES_AimMarkerH
HudScript HES_AimShimmerA
HudScript HES_AimShimmerB
HudScript HES_AimShimmerC
HudScript HES_AimShimmerD
HudScript HES_AimShimmerE
HudScript HES_AimShimmerF
HudScript HES_AimShimmerG
HudScript HES_AimShimmerH
HudScript HES_AimReticle
HudScript HES_AimTarget
HudScript HES_AimBlinkA
HudScript HES_AimBlinkB
HudScript HES_AimBlinkC
Macro Definition Documentation
ui_battle_menu_defend_disabled_png
#define ui_battle_menu_defend_disabled_png ui_battle_menu_defend_png
ui_battle_menu_flee_disabled_png
#define ui_battle_menu_flee_disabled_png ui_battle_menu_flee_png
ui_battle_menu_nothing_disabled_png
#define ui_battle_menu_nothing_disabled_png ui_battle_menu_nothing_png
ui_battle_menu_pouch_disabled_png
#define ui_battle_menu_pouch_disabled_png ui_battle_menu_pouch_png
ui_battle_menu_strategies_disabled_png
#define ui_battle_menu_strategies_disabled_png ui_battle_menu_strategies_png
ui_battle_menu_unused_disabled_png
#define ui_battle_menu_unused_disabled_png ui_battle_menu_unused_png
Function Documentation
INCLUDE_IMG() [1/74]
INCLUDE_IMG ("ui/battle/cmd/100pct.png" , ui_battle_cmd_100pct_png)
INCLUDE_IMG() [2/74]
INCLUDE_IMG ("ui/battle/cmd/aim/marker_0.png" , ui_battle_cmd_aim_marker_0_png)
INCLUDE_IMG() [3/74]
INCLUDE_IMG ("ui/battle/cmd/aim/marker_1.png" , ui_battle_cmd_aim_marker_1_png)
INCLUDE_IMG() [4/74]
INCLUDE_IMG ("ui/battle/cmd/aim/marker_2.png" , ui_battle_cmd_aim_marker_2_png)
INCLUDE_IMG() [5/74]
INCLUDE_IMG ("ui/battle/cmd/aim/marker_3.png" , ui_battle_cmd_aim_marker_3_png)
INCLUDE_IMG() [6/74]
INCLUDE_IMG ("ui/battle/cmd/aim/marker_4.png" , ui_battle_cmd_aim_marker_4_png)
INCLUDE_IMG() [7/74]
INCLUDE_IMG ("ui/battle/cmd/aim/marker_5.png" , ui_battle_cmd_aim_marker_5_png)
INCLUDE_IMG() [8/74]
INCLUDE_IMG ("ui/battle/cmd/aim/marker_6.png" , ui_battle_cmd_aim_marker_6_png)
INCLUDE_IMG() [9/74]
INCLUDE_IMG ("ui/battle/cmd/aim/marker_7.png" , ui_battle_cmd_aim_marker_7_png)
INCLUDE_IMG() [10/74]
INCLUDE_IMG ("ui/battle/cmd/aim/reticle_0.png" , ui_battle_cmd_aim_reticle_0_png)
INCLUDE_IMG() [11/74]
INCLUDE_IMG ("ui/battle/cmd/aim/reticle_1.png" , ui_battle_cmd_aim_reticle_1_png)
INCLUDE_IMG() [12/74]
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_0.png" , ui_battle_cmd_aim_shimmer_0_png)
INCLUDE_IMG() [13/74]
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_1.png" , ui_battle_cmd_aim_shimmer_1_png)
INCLUDE_IMG() [14/74]
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_2.png" , ui_battle_cmd_aim_shimmer_2_png)
INCLUDE_IMG() [15/74]
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_3.png" , ui_battle_cmd_aim_shimmer_3_png)
INCLUDE_IMG() [16/74]
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_4.png" , ui_battle_cmd_aim_shimmer_4_png)
INCLUDE_IMG() [17/74]
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_5.png" , ui_battle_cmd_aim_shimmer_5_png)
INCLUDE_IMG() [18/74]
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_6.png" , ui_battle_cmd_aim_shimmer_6_png)
INCLUDE_IMG() [19/74]
INCLUDE_IMG ("ui/battle/cmd/aim/shimmer_7.png" , ui_battle_cmd_aim_shimmer_7_png)
INCLUDE_IMG() [20/74]
INCLUDE_IMG ("ui/battle/cmd/aim/target_0.png" , ui_battle_cmd_aim_target_0_png)
INCLUDE_IMG() [21/74]
INCLUDE_IMG ("ui/battle/cmd/aim/target_1.png" , ui_battle_cmd_aim_target_1_png)
INCLUDE_IMG() [22/74]
INCLUDE_IMG ("ui/battle/cmd/charge_1.png" , ui_battle_cmd_charge_1_png)
INCLUDE_IMG() [23/74]
INCLUDE_IMG ("ui/battle/cmd/charge_2.png" , ui_battle_cmd_charge_2_png)
INCLUDE_IMG() [24/74]
INCLUDE_IMG ("ui/battle/cmd/charge_3.png" , ui_battle_cmd_charge_3_png)
INCLUDE_IMG() [25/74]
INCLUDE_IMG ("ui/battle/cmd/charge_4.png" , ui_battle_cmd_charge_4_png)
INCLUDE_IMG() [26/74]
INCLUDE_IMG ("ui/battle/cmd/fill_result.png" , ui_battle_cmd_fill_result_png)
INCLUDE_IMG() [27/74]
INCLUDE_IMG ("ui/battle/cmd/flee_0.png" , ui_battle_cmd_flee_0_png)
INCLUDE_IMG() [28/74]
INCLUDE_IMG ("ui/battle/cmd/flee_1.png" , ui_battle_cmd_flee_1_png)
INCLUDE_IMG() [29/74]
INCLUDE_IMG ("ui/battle/cmd/flee_2.png" , ui_battle_cmd_flee_2_png)
INCLUDE_IMG() [30/74]
INCLUDE_IMG ("ui/battle/cmd/gauge_result.png" , ui_battle_cmd_gauge_result_png)
INCLUDE_IMG() [31/74]
INCLUDE_IMG ("ui/battle/cmd/right_on.png" , ui_battle_cmd_right_on_png)
INCLUDE_IMG() [32/74]
INCLUDE_IMG ("ui/battle/cmd/timing_1_chance.png" , ui_battle_cmd_timing_1_chance_png)
INCLUDE_IMG() [33/74]
INCLUDE_IMG ("ui/battle/cmd/timing_3_chances.png" , ui_battle_cmd_timing_3_chances_png)
INCLUDE_IMG() [34/74]
INCLUDE_IMG ("ui/battle/cmd/timing_miss.png" , ui_battle_cmd_timing_miss_png)
INCLUDE_IMG() [35/74]
INCLUDE_IMG ("ui/battle/cmd/timing_ok.png" , ui_battle_cmd_timing_ok_png)
INCLUDE_IMG() [36/74]
INCLUDE_IMG ("ui/battle/cmd/timing_ready.png" , ui_battle_cmd_timing_ready_png)
INCLUDE_IMG() [37/74]
INCLUDE_IMG ("ui/battle/cmd/timing_wait.png" , ui_battle_cmd_timing_wait_png)
INCLUDE_IMG() [38/74]
INCLUDE_IMG ("ui/battle/cont/b_down.png" , ui_battle_cont_b_down_png)
INCLUDE_IMG() [39/74]
INCLUDE_IMG ("ui/battle/cont/b_up.png" , ui_battle_cont_b_up_png)
INCLUDE_IMG() [40/74]
INCLUDE_IMG ("ui/battle/cont/c_down_down.png" , ui_battle_cont_c_down_down_png)
INCLUDE_IMG() [41/74]
INCLUDE_IMG ("ui/battle/cont/c_down_up.png" , ui_battle_cont_c_down_up_png)
INCLUDE_IMG() [42/74]
INCLUDE_IMG ("ui/battle/cont/c_left_down.png" , ui_battle_cont_c_left_down_png)
INCLUDE_IMG() [43/74]
INCLUDE_IMG ("ui/battle/cont/c_left_up.png" , ui_battle_cont_c_left_up_png)
INCLUDE_IMG() [44/74]
INCLUDE_IMG ("ui/battle/cont/c_right_down.png" , ui_battle_cont_c_right_down_png)
INCLUDE_IMG() [45/74]
INCLUDE_IMG ("ui/battle/cont/c_right_up.png" , ui_battle_cont_c_right_up_png)
INCLUDE_IMG() [46/74]
INCLUDE_IMG ("ui/battle/cont/c_up_down.png" , ui_battle_cont_c_up_down_png)
INCLUDE_IMG() [47/74]
INCLUDE_IMG ("ui/battle/cont/c_up_up.png" , ui_battle_cont_c_up_up_png)
INCLUDE_IMG() [48/74]
INCLUDE_IMG ("ui/battle/hp_0.png" , ui_battle_hp_0_png)
INCLUDE_IMG() [49/74]
INCLUDE_IMG ("ui/battle/hp_1.png" , ui_battle_hp_1_png)
INCLUDE_IMG() [50/74]
INCLUDE_IMG ("ui/battle/hp_2.png" , ui_battle_hp_2_png)
INCLUDE_IMG() [51/74]
INCLUDE_IMG ("ui/battle/hp_3.png" , ui_battle_hp_3_png)
INCLUDE_IMG() [52/74]
INCLUDE_IMG ("ui/battle/hp_4.png" , ui_battle_hp_4_png)
INCLUDE_IMG() [53/74]
INCLUDE_IMG ("ui/battle/hp_5.png" , ui_battle_hp_5_png)
INCLUDE_IMG() [54/74]
INCLUDE_IMG ("ui/battle/hp_6.png" , ui_battle_hp_6_png)
INCLUDE_IMG() [55/74]
INCLUDE_IMG ("ui/battle/hp_7.png" , ui_battle_hp_7_png)
INCLUDE_IMG() [56/74]
INCLUDE_IMG ("ui/battle/hp_8.png" , ui_battle_hp_8_png)
INCLUDE_IMG() [57/74]
INCLUDE_IMG ("ui/battle/hp_9.png" , ui_battle_hp_9_png)
INCLUDE_IMG() [58/74]
INCLUDE_IMG ("ui/battle/hp_bar.png" , ui_battle_hp_bar_png)
INCLUDE_IMG() [59/74]
INCLUDE_IMG ("ui/battle/menu/defend.png" , ui_battle_menu_defend_png)
INCLUDE_IMG() [60/74]
INCLUDE_IMG ("ui/battle/menu/flee.png" , ui_battle_menu_flee_png)
INCLUDE_IMG() [61/74]
INCLUDE_IMG ("ui/battle/menu/nothing.png" , ui_battle_menu_nothing_png)
INCLUDE_IMG() [62/74]
INCLUDE_IMG ("ui/battle/menu/pouch.png" , ui_battle_menu_pouch_png)
INCLUDE_IMG() [63/74]
INCLUDE_IMG ("ui/battle/menu/spirits.png" , ui_battle_menu_spirits_png)
INCLUDE_IMG() [64/74]
INCLUDE_IMG ("ui/battle/menu/strategies.png" , ui_battle_menu_strategies_png)
INCLUDE_IMG() [65/74]
INCLUDE_IMG ("ui/battle/menu/unused.png" , ui_battle_menu_unused_png)
INCLUDE_IMG() [66/74]
INCLUDE_IMG ("ui/battle/projector_beam.png" , ui_battle_projector_beam_png)
INCLUDE_IMG() [67/74]
INCLUDE_IMG ("ui/battle/projector_reel.png" , ui_battle_projector_reel_png)
INCLUDE_IMG() [68/74]
INCLUDE_IMG ("ui/battle/projector_spot.png" , ui_battle_projector_spot_png)
INCLUDE_IMG() [69/74]
INCLUDE_IMG ("ui/battle/solid_star.png" , ui_battle_solid_star_png)
INCLUDE_IMG() [70/74]
INCLUDE_IMG ("ui/battle/swap_arrow_left.png" , ui_battle_swap_arrow_left_png)
INCLUDE_IMG() [71/74]
INCLUDE_IMG ("ui/battle/swap_arrow_right.png" , ui_battle_swap_arrow_right_png)
INCLUDE_IMG() [72/74]
INCLUDE_IMG ("ui/battle/swap_background.png" , ui_battle_swap_background_png)
INCLUDE_IMG() [73/74]
INCLUDE_IMG ("ui/battle/swap_Z.png" , ui_battle_swap_Z_png)
INCLUDE_IMG() [74/74]
INCLUDE_IMG ("ui/battle/yellow_arrow.png" , ui_battle_yellow_arrow_png)
INCLUDE_PAL() [1/76]
INCLUDE_PAL ("ui/battle/cmd/100pct.pal" , ui_battle_cmd_100pct_pal)
INCLUDE_PAL() [2/76]
INCLUDE_PAL ("ui/battle/cmd/aim/marker_0.pal" , ui_battle_cmd_aim_marker_0_pal)
INCLUDE_PAL() [3/76]
INCLUDE_PAL ("ui/battle/cmd/aim/marker_1.pal" , ui_battle_cmd_aim_marker_1_pal)
INCLUDE_PAL() [4/76]
INCLUDE_PAL ("ui/battle/cmd/aim/marker_2.pal" , ui_battle_cmd_aim_marker_2_pal)
INCLUDE_PAL() [5/76]
INCLUDE_PAL ("ui/battle/cmd/aim/marker_3.pal" , ui_battle_cmd_aim_marker_3_pal)
INCLUDE_PAL() [6/76]
INCLUDE_PAL ("ui/battle/cmd/aim/marker_4.pal" , ui_battle_cmd_aim_marker_4_pal)
INCLUDE_PAL() [7/76]
INCLUDE_PAL ("ui/battle/cmd/aim/marker_5.pal" , ui_battle_cmd_aim_marker_5_pal)
INCLUDE_PAL() [8/76]
INCLUDE_PAL ("ui/battle/cmd/aim/marker_6.pal" , ui_battle_cmd_aim_marker_6_pal)
INCLUDE_PAL() [9/76]
INCLUDE_PAL ("ui/battle/cmd/aim/marker_7.pal" , ui_battle_cmd_aim_marker_7_pal)
INCLUDE_PAL() [10/76]
INCLUDE_PAL ("ui/battle/cmd/aim/reticle_0.pal" , ui_battle_cmd_aim_reticle_0_pal)
INCLUDE_PAL() [11/76]
INCLUDE_PAL ("ui/battle/cmd/aim/reticle_1.pal" , ui_battle_cmd_aim_reticle_1_pal)
INCLUDE_PAL() [12/76]
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_0.pal" , ui_battle_cmd_aim_shimmer_0_pal)
INCLUDE_PAL() [13/76]
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_1.pal" , ui_battle_cmd_aim_shimmer_1_pal)
INCLUDE_PAL() [14/76]
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_2.pal" , ui_battle_cmd_aim_shimmer_2_pal)
INCLUDE_PAL() [15/76]
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_3.pal" , ui_battle_cmd_aim_shimmer_3_pal)
INCLUDE_PAL() [16/76]
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_4.pal" , ui_battle_cmd_aim_shimmer_4_pal)
INCLUDE_PAL() [17/76]
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_5.pal" , ui_battle_cmd_aim_shimmer_5_pal)
INCLUDE_PAL() [18/76]
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_6.pal" , ui_battle_cmd_aim_shimmer_6_pal)
INCLUDE_PAL() [19/76]
INCLUDE_PAL ("ui/battle/cmd/aim/shimmer_7.pal" , ui_battle_cmd_aim_shimmer_7_pal)
INCLUDE_PAL() [20/76]
INCLUDE_PAL ("ui/battle/cmd/aim/target_0.pal" , ui_battle_cmd_aim_target_0_pal)
INCLUDE_PAL() [21/76]
INCLUDE_PAL ("ui/battle/cmd/aim/target_1.pal" , ui_battle_cmd_aim_target_1_pal)
INCLUDE_PAL() [22/76]
INCLUDE_PAL ("ui/battle/cmd/charge_1.pal" , ui_battle_cmd_charge_1_pal)
INCLUDE_PAL() [23/76]
INCLUDE_PAL ("ui/battle/cmd/charge_2.pal" , ui_battle_cmd_charge_2_pal)
INCLUDE_PAL() [24/76]
INCLUDE_PAL ("ui/battle/cmd/charge_3.pal" , ui_battle_cmd_charge_3_pal)
INCLUDE_PAL() [25/76]
INCLUDE_PAL ("ui/battle/cmd/charge_4.pal" , ui_battle_cmd_charge_4_pal)
INCLUDE_PAL() [26/76]
INCLUDE_PAL ("ui/battle/cmd/fill_result.pal" , ui_battle_cmd_fill_result_pal)
INCLUDE_PAL() [27/76]
INCLUDE_PAL ("ui/battle/cmd/flee_0.pal" , ui_battle_cmd_flee_0_pal)
INCLUDE_PAL() [28/76]
INCLUDE_PAL ("ui/battle/cmd/flee_1.pal" , ui_battle_cmd_flee_1_pal)
INCLUDE_PAL() [29/76]
INCLUDE_PAL ("ui/battle/cmd/flee_2.pal" , ui_battle_cmd_flee_2_pal)
INCLUDE_PAL() [30/76]
INCLUDE_PAL ("ui/battle/cmd/gauge_result.pal" , ui_battle_cmd_gauge_result_pal)
INCLUDE_PAL() [31/76]
INCLUDE_PAL ("ui/battle/cmd/right_on.pal" , ui_battle_cmd_right_on_pal)
INCLUDE_PAL() [32/76]
INCLUDE_PAL ("ui/battle/cmd/timing_1_chance.pal" , ui_battle_cmd_timing_1_chance_pal)
INCLUDE_PAL() [33/76]
INCLUDE_PAL ("ui/battle/cmd/timing_3_chances.pal" , ui_battle_cmd_timing_3_chances_pal)
INCLUDE_PAL() [34/76]
INCLUDE_PAL ("ui/battle/cmd/timing_miss.pal" , ui_battle_cmd_timing_miss_pal)
INCLUDE_PAL() [35/76]
INCLUDE_PAL ("ui/battle/cmd/timing_ok.pal" , ui_battle_cmd_timing_ok_pal)
INCLUDE_PAL() [36/76]
INCLUDE_PAL ("ui/battle/cmd/timing_ready.pal" , ui_battle_cmd_timing_ready_pal)
INCLUDE_PAL() [37/76]
INCLUDE_PAL ("ui/battle/cmd/timing_wait.pal" , ui_battle_cmd_timing_wait_pal)
INCLUDE_PAL() [38/76]
INCLUDE_PAL ("ui/battle/cont/b_down.pal" , ui_battle_cont_b_down_pal)
INCLUDE_PAL() [39/76]
INCLUDE_PAL ("ui/battle/cont/b_up.pal" , ui_battle_cont_b_up_pal)
INCLUDE_PAL() [40/76]
INCLUDE_PAL ("ui/battle/cont/c_down_down.pal" , ui_battle_cont_c_down_down_pal)
INCLUDE_PAL() [41/76]
INCLUDE_PAL ("ui/battle/cont/c_down_up.pal" , ui_battle_cont_c_down_up_pal)
INCLUDE_PAL() [42/76]
INCLUDE_PAL ("ui/battle/cont/c_left_down.pal" , ui_battle_cont_c_left_down_pal)
INCLUDE_PAL() [43/76]
INCLUDE_PAL ("ui/battle/cont/c_left_up.pal" , ui_battle_cont_c_left_up_pal)
INCLUDE_PAL() [44/76]
INCLUDE_PAL ("ui/battle/cont/c_right_down.pal" , ui_battle_cont_c_right_down_pal)
INCLUDE_PAL() [45/76]
INCLUDE_PAL ("ui/battle/cont/c_right_up.pal" , ui_battle_cont_c_right_up_pal)
INCLUDE_PAL() [46/76]
INCLUDE_PAL ("ui/battle/cont/c_up_down.pal" , ui_battle_cont_c_up_down_pal)
INCLUDE_PAL() [47/76]
INCLUDE_PAL ("ui/battle/cont/c_up_up.pal" , ui_battle_cont_c_up_up_pal)
INCLUDE_PAL() [48/76]
INCLUDE_PAL ("ui/battle/hp_0.pal" , ui_battle_hp_0_pal)
INCLUDE_PAL() [49/76]
INCLUDE_PAL ("ui/battle/hp_1.pal" , ui_battle_hp_1_pal)
INCLUDE_PAL() [50/76]
INCLUDE_PAL ("ui/battle/hp_2.pal" , ui_battle_hp_2_pal)
INCLUDE_PAL() [51/76]
INCLUDE_PAL ("ui/battle/hp_3.pal" , ui_battle_hp_3_pal)
INCLUDE_PAL() [52/76]
INCLUDE_PAL ("ui/battle/hp_4.pal" , ui_battle_hp_4_pal)
INCLUDE_PAL() [53/76]
INCLUDE_PAL ("ui/battle/hp_5.pal" , ui_battle_hp_5_pal)
INCLUDE_PAL() [54/76]
INCLUDE_PAL ("ui/battle/hp_6.pal" , ui_battle_hp_6_pal)
INCLUDE_PAL() [55/76]
INCLUDE_PAL ("ui/battle/hp_7.pal" , ui_battle_hp_7_pal)
INCLUDE_PAL() [56/76]
INCLUDE_PAL ("ui/battle/hp_8.pal" , ui_battle_hp_8_pal)
INCLUDE_PAL() [57/76]
INCLUDE_PAL ("ui/battle/hp_9.pal" , ui_battle_hp_9_pal)
INCLUDE_PAL() [58/76]
INCLUDE_PAL ("ui/battle/hp_bar.pal" , ui_battle_hp_bar_pal)
INCLUDE_PAL() [59/76]
INCLUDE_PAL ("ui/battle/menu/defend.disabled.pal" , ui_battle_menu_defend_disabled_pal)
INCLUDE_PAL() [60/76]
INCLUDE_PAL ("ui/battle/menu/defend.pal" , ui_battle_menu_defend_pal)
INCLUDE_PAL() [61/76]
INCLUDE_PAL ("ui/battle/menu/flee.disabled.pal" , ui_battle_menu_flee_disabled_pal)
INCLUDE_PAL() [62/76]
INCLUDE_PAL ("ui/battle/menu/flee.pal" , ui_battle_menu_flee_pal)
INCLUDE_PAL() [63/76]
INCLUDE_PAL ("ui/battle/menu/nothing.disabled.pal" , ui_battle_menu_nothing_disabled_pal)
INCLUDE_PAL() [64/76]
INCLUDE_PAL ("ui/battle/menu/nothing.pal" , ui_battle_menu_nothing_pal)
INCLUDE_PAL() [65/76]
INCLUDE_PAL ("ui/battle/menu/pouch.disabled.pal" , ui_battle_menu_pouch_disabled_pal)
INCLUDE_PAL() [66/76]
INCLUDE_PAL ("ui/battle/menu/pouch.pal" , ui_battle_menu_pouch_pal)
INCLUDE_PAL() [67/76]
INCLUDE_PAL ("ui/battle/menu/spirits.pal" , ui_battle_menu_spirits_pal)
INCLUDE_PAL() [68/76]
INCLUDE_PAL ("ui/battle/menu/strategies.disabled.pal" , ui_battle_menu_strategies_disabled_pal)
INCLUDE_PAL() [69/76]
INCLUDE_PAL ("ui/battle/menu/strategies.pal" , ui_battle_menu_strategies_pal)
INCLUDE_PAL() [70/76]
INCLUDE_PAL ("ui/battle/menu/unused.disabled.pal" , ui_battle_menu_unused_disabled_pal)
INCLUDE_PAL() [71/76]
INCLUDE_PAL ("ui/battle/menu/unused.pal" , ui_battle_menu_unused_pal)
INCLUDE_PAL() [72/76]
INCLUDE_PAL ("ui/battle/solid_star.pal" , ui_battle_solid_star_pal)
INCLUDE_PAL() [73/76]
INCLUDE_PAL ("ui/battle/swap_arrow_left.pal" , ui_battle_swap_arrow_left_pal)
INCLUDE_PAL() [74/76]
INCLUDE_PAL ("ui/battle/swap_arrow_right.pal" , ui_battle_swap_arrow_right_pal)
INCLUDE_PAL() [75/76]
INCLUDE_PAL ("ui/battle/swap_Z.pal" , ui_battle_swap_Z_pal)
INCLUDE_PAL() [76/76]
INCLUDE_PAL ("ui/battle/yellow_arrow.pal" , ui_battle_yellow_arrow_pal)
Variable Documentation
D_8028F860
Gfx D_8028F860[]
Initial value:
= {
    gsSPEndDisplayList(),
}
D_8028FC68
Gfx D_8028FC68[]
Initial value:
= {
    gsSPEndDisplayList(),
}
D_80290C70
Gfx D_80290C70[]
Initial value:
= {
    gsSPEndDisplayList(),
}
D_80291C78
Gfx D_80291C78[]
Initial value:
= {
    gsSPEndDisplayList(),
}
HES_100pct
HudScript HES_100pct
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  64 ,  48 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetTexelOffset,  0 ,  -16 ,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.00  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_100pct_png, (s32) ui_battle_cmd_100pct_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.20  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_100pct_png, (s32) ui_battle_cmd_100pct_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.30  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_100pct_png, (s32) ui_battle_cmd_100pct_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.27  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_100pct_png, (s32) ui_battle_cmd_100pct_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.15  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_100pct_png, (s32) ui_battle_cmd_100pct_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.05  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_100pct_png, (s32) ui_battle_cmd_100pct_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimBlinkA
HudScript HES_AimBlinkA
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_ClearFlags,  HUD_ELEMENT_FLAG_200000 ,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetFlags,  HUD_ELEMENT_FLAG_200000 ,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimBlinkB
HudScript HES_AimBlinkB
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetFlags,  HUD_ELEMENT_FLAG_200000 ,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_ClearFlags,  HUD_ELEMENT_FLAG_200000 ,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetFlags,  HUD_ELEMENT_FLAG_200000 ,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimBlinkC
HudScript HES_AimBlinkC
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetFlags,  HUD_ELEMENT_FLAG_200000 ,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_ClearFlags,  HUD_ELEMENT_FLAG_200000 ,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimMarkerA
HudScript HES_AimMarkerA
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_1_png, (s32) ui_battle_cmd_aim_marker_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_2_png, (s32) ui_battle_cmd_aim_marker_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_3_png, (s32) ui_battle_cmd_aim_marker_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_4_png, (s32) ui_battle_cmd_aim_marker_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_5_png, (s32) ui_battle_cmd_aim_marker_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_6_png, (s32) ui_battle_cmd_aim_marker_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_7_png, (s32) ui_battle_cmd_aim_marker_7_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimMarkerB
HudScript HES_AimMarkerB
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_1_png, (s32) ui_battle_cmd_aim_marker_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_2_png, (s32) ui_battle_cmd_aim_marker_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_3_png, (s32) ui_battle_cmd_aim_marker_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_4_png, (s32) ui_battle_cmd_aim_marker_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_5_png, (s32) ui_battle_cmd_aim_marker_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_6_png, (s32) ui_battle_cmd_aim_marker_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_7_png, (s32) ui_battle_cmd_aim_marker_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimMarkerC
HudScript HES_AimMarkerC
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_2_png, (s32) ui_battle_cmd_aim_marker_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_3_png, (s32) ui_battle_cmd_aim_marker_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_4_png, (s32) ui_battle_cmd_aim_marker_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_5_png, (s32) ui_battle_cmd_aim_marker_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_6_png, (s32) ui_battle_cmd_aim_marker_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_7_png, (s32) ui_battle_cmd_aim_marker_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_1_png, (s32) ui_battle_cmd_aim_marker_1_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimMarkerD
HudScript HES_AimMarkerD
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_3_png, (s32) ui_battle_cmd_aim_marker_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_4_png, (s32) ui_battle_cmd_aim_marker_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_5_png, (s32) ui_battle_cmd_aim_marker_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_6_png, (s32) ui_battle_cmd_aim_marker_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_7_png, (s32) ui_battle_cmd_aim_marker_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_1_png, (s32) ui_battle_cmd_aim_marker_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_2_png, (s32) ui_battle_cmd_aim_marker_2_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimMarkerE
HudScript HES_AimMarkerE
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_4_png, (s32) ui_battle_cmd_aim_marker_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_5_png, (s32) ui_battle_cmd_aim_marker_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_6_png, (s32) ui_battle_cmd_aim_marker_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_7_png, (s32) ui_battle_cmd_aim_marker_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_1_png, (s32) ui_battle_cmd_aim_marker_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_2_png, (s32) ui_battle_cmd_aim_marker_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_3_png, (s32) ui_battle_cmd_aim_marker_3_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimMarkerF
HudScript HES_AimMarkerF
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_5_png, (s32) ui_battle_cmd_aim_marker_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_6_png, (s32) ui_battle_cmd_aim_marker_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_7_png, (s32) ui_battle_cmd_aim_marker_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_1_png, (s32) ui_battle_cmd_aim_marker_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_2_png, (s32) ui_battle_cmd_aim_marker_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_3_png, (s32) ui_battle_cmd_aim_marker_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_4_png, (s32) ui_battle_cmd_aim_marker_4_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimMarkerG
HudScript HES_AimMarkerG
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_6_png, (s32) ui_battle_cmd_aim_marker_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_7_png, (s32) ui_battle_cmd_aim_marker_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_1_png, (s32) ui_battle_cmd_aim_marker_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_2_png, (s32) ui_battle_cmd_aim_marker_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_3_png, (s32) ui_battle_cmd_aim_marker_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_4_png, (s32) ui_battle_cmd_aim_marker_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_5_png, (s32) ui_battle_cmd_aim_marker_5_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimMarkerH
HudScript HES_AimMarkerH
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_7_png, (s32) ui_battle_cmd_aim_marker_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_0_png, (s32) ui_battle_cmd_aim_marker_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_1_png, (s32) ui_battle_cmd_aim_marker_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_2_png, (s32) ui_battle_cmd_aim_marker_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_3_png, (s32) ui_battle_cmd_aim_marker_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_4_png, (s32) ui_battle_cmd_aim_marker_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_5_png, (s32) ui_battle_cmd_aim_marker_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_marker_6_png, (s32) ui_battle_cmd_aim_marker_6_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimReticle
HudScript HES_AimReticle
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_32x32 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  8 , (s32) ui_battle_cmd_aim_reticle_0_png, (s32) ui_battle_cmd_aim_reticle_0_pal,
        HUD_ELEMENT_OP_SetCI,  5 , (s32) ui_battle_cmd_aim_reticle_1_png, (s32) ui_battle_cmd_aim_reticle_1_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_AimShimmerA
HudScript HES_AimShimmerA
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_0_png, (s32) ui_battle_cmd_aim_shimmer_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_1_png, (s32) ui_battle_cmd_aim_shimmer_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_2_png, (s32) ui_battle_cmd_aim_shimmer_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_3_png, (s32) ui_battle_cmd_aim_shimmer_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_4_png, (s32) ui_battle_cmd_aim_shimmer_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_5_png, (s32) ui_battle_cmd_aim_shimmer_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_6_png, (s32) ui_battle_cmd_aim_shimmer_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_7_png, (s32) ui_battle_cmd_aim_shimmer_7_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimShimmerB
HudScript HES_AimShimmerB
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_1_png, (s32) ui_battle_cmd_aim_shimmer_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_2_png, (s32) ui_battle_cmd_aim_shimmer_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_3_png, (s32) ui_battle_cmd_aim_shimmer_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_4_png, (s32) ui_battle_cmd_aim_shimmer_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_5_png, (s32) ui_battle_cmd_aim_shimmer_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_6_png, (s32) ui_battle_cmd_aim_shimmer_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_7_png, (s32) ui_battle_cmd_aim_shimmer_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_0_png, (s32) ui_battle_cmd_aim_shimmer_0_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimShimmerC
HudScript HES_AimShimmerC
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_2_png, (s32) ui_battle_cmd_aim_shimmer_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_3_png, (s32) ui_battle_cmd_aim_shimmer_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_4_png, (s32) ui_battle_cmd_aim_shimmer_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_5_png, (s32) ui_battle_cmd_aim_shimmer_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_6_png, (s32) ui_battle_cmd_aim_shimmer_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_7_png, (s32) ui_battle_cmd_aim_shimmer_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_0_png, (s32) ui_battle_cmd_aim_shimmer_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_1_png, (s32) ui_battle_cmd_aim_shimmer_1_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimShimmerD
HudScript HES_AimShimmerD
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_3_png, (s32) ui_battle_cmd_aim_shimmer_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_4_png, (s32) ui_battle_cmd_aim_shimmer_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_5_png, (s32) ui_battle_cmd_aim_shimmer_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_6_png, (s32) ui_battle_cmd_aim_shimmer_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_7_png, (s32) ui_battle_cmd_aim_shimmer_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_0_png, (s32) ui_battle_cmd_aim_shimmer_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_1_png, (s32) ui_battle_cmd_aim_shimmer_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_2_png, (s32) ui_battle_cmd_aim_shimmer_2_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimShimmerE
HudScript HES_AimShimmerE
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_4_png, (s32) ui_battle_cmd_aim_shimmer_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_5_png, (s32) ui_battle_cmd_aim_shimmer_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_6_png, (s32) ui_battle_cmd_aim_shimmer_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_7_png, (s32) ui_battle_cmd_aim_shimmer_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_0_png, (s32) ui_battle_cmd_aim_shimmer_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_1_png, (s32) ui_battle_cmd_aim_shimmer_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_2_png, (s32) ui_battle_cmd_aim_shimmer_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_3_png, (s32) ui_battle_cmd_aim_shimmer_3_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimShimmerF
HudScript HES_AimShimmerF
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_5_png, (s32) ui_battle_cmd_aim_shimmer_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_6_png, (s32) ui_battle_cmd_aim_shimmer_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_7_png, (s32) ui_battle_cmd_aim_shimmer_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_0_png, (s32) ui_battle_cmd_aim_shimmer_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_1_png, (s32) ui_battle_cmd_aim_shimmer_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_2_png, (s32) ui_battle_cmd_aim_shimmer_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_3_png, (s32) ui_battle_cmd_aim_shimmer_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_4_png, (s32) ui_battle_cmd_aim_shimmer_4_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimShimmerG
HudScript HES_AimShimmerG
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_6_png, (s32) ui_battle_cmd_aim_shimmer_6_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_7_png, (s32) ui_battle_cmd_aim_shimmer_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_0_png, (s32) ui_battle_cmd_aim_shimmer_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_1_png, (s32) ui_battle_cmd_aim_shimmer_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_2_png, (s32) ui_battle_cmd_aim_shimmer_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_3_png, (s32) ui_battle_cmd_aim_shimmer_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_4_png, (s32) ui_battle_cmd_aim_shimmer_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_5_png, (s32) ui_battle_cmd_aim_shimmer_5_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimShimmerH
HudScript HES_AimShimmerH
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_16x16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_7_png, (s32) ui_battle_cmd_aim_shimmer_7_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_0_png, (s32) ui_battle_cmd_aim_shimmer_0_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_1_png, (s32) ui_battle_cmd_aim_shimmer_1_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_2_png, (s32) ui_battle_cmd_aim_shimmer_2_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_3_png, (s32) ui_battle_cmd_aim_shimmer_3_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_4_png, (s32) ui_battle_cmd_aim_shimmer_4_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_5_png, (s32) ui_battle_cmd_aim_shimmer_5_pal,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cmd_aim_shimmer_6_png, (s32) ui_battle_cmd_aim_shimmer_6_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_AimTarget
HudScript HES_AimTarget
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetTileSize,  HUD_ELEMENT_SIZE_24x24 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cmd_aim_target_0_png, (s32) ui_battle_cmd_aim_target_0_pal,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cmd_aim_target_1_png, (s32) ui_battle_cmd_aim_target_1_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_BButton
HudScript HES_BButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 48 , 40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_b_up_png, (s32) ui_battle_cont_b_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_update_message_popup().
HES_BButtonHeld
HudScript HES_BButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 48 , 40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_b_down_png, (s32) ui_battle_cont_b_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_CDownButton
HudScript HES_CDownButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_down_up_png, (s32) ui_battle_cont_c_down_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_update_message_popup().
HES_CDownButtonHeld
HudScript HES_CDownButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_down_down_png, (s32) ui_battle_cont_c_down_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_CLeftButton
HudScript HES_CLeftButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_left_up_png, (s32) ui_battle_cont_c_left_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_update_message_popup().
HES_CLeftButtonHeld
HudScript HES_CLeftButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_left_down_png, (s32) ui_battle_cont_c_left_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_CRightButton
HudScript HES_CRightButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_right_up_png, (s32) ui_battle_cont_c_right_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_update_message_popup().
HES_CRightButtonHeld
HudScript HES_CRightButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_right_down_png, (s32) ui_battle_cont_c_right_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_CUpButton
HudScript HES_CUpButton = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_up_up_png, (s32) ui_battle_cont_c_up_up_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_update_message_popup().
HES_CUpButtonHeld
HudScript HES_CUpButtonHeld = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 40 , 34 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cont_c_up_down_png, (s32) ui_battle_cont_c_up_down_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_FillGaugeResult
HudScript HES_FillGaugeResult = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_fill_result_png, (s32) ui_battle_cmd_fill_result_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPBar
HudScript HES_HPBar = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_bar_png, (s32) ui_battle_hp_bar_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_draw_enemy_health_bars(), and initialize_battle().
HES_HPDigit0
HudScript HES_HPDigit0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_0_png, (s32) ui_battle_hp_0_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPDigit1
HudScript HES_HPDigit1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_1_png, (s32) ui_battle_hp_1_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPDigit2
HudScript HES_HPDigit2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_2_png, (s32) ui_battle_hp_2_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPDigit3
HudScript HES_HPDigit3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_3_png, (s32) ui_battle_hp_3_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPDigit4
HudScript HES_HPDigit4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_4_png, (s32) ui_battle_hp_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPDigit5
HudScript HES_HPDigit5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_5_png, (s32) ui_battle_hp_5_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPDigit6
HudScript HES_HPDigit6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_6_png, (s32) ui_battle_hp_6_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPDigit7
HudScript HES_HPDigit7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_7_png, (s32) ui_battle_hp_7_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPDigit8
HudScript HES_HPDigit8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_8_png, (s32) ui_battle_hp_8_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_HPDigit9
HudScript HES_HPDigit9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_hp_9_png, (s32) ui_battle_hp_9_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MashBButton1
HudScript HES_MashBButton1
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  48 ,  40 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_b_up_png, (s32) ui_battle_cont_b_up_pal,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_b_down_png, (s32) ui_battle_cont_b_down_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup(), and update().
HES_MashBButton2
HudScript HES_MashBButton2
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  48 ,  40 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_b_down_png, (s32) ui_battle_cont_b_down_pal,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_b_up_png, (s32) ui_battle_cont_b_up_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_MashCDownButton1
HudScript HES_MashCDownButton1
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  40 ,  34 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_down_up_png, (s32) ui_battle_cont_c_down_up_pal,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_down_down_png, (s32) ui_battle_cont_c_down_down_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_MashCDownButton2
HudScript HES_MashCDownButton2
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  40 ,  34 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cont_c_down_up_png, (s32) ui_battle_cont_c_down_up_pal,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_down_down_png, (s32) ui_battle_cont_c_down_down_pal,
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cont_c_down_up_png, (s32) ui_battle_cont_c_down_up_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_MashCLeftButton
HudScript HES_MashCLeftButton
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  40 ,  34 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_left_up_png, (s32) ui_battle_cont_c_left_up_pal,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_left_down_png, (s32) ui_battle_cont_c_left_down_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_MashCRightButton1
HudScript HES_MashCRightButton1
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  40 ,  34 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_right_up_png, (s32) ui_battle_cont_c_right_up_pal,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_right_down_png, (s32) ui_battle_cont_c_right_down_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_MashCRightButton2
HudScript HES_MashCRightButton2
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  40 ,  34 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_right_down_png, (s32) ui_battle_cont_c_right_down_pal,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_right_up_png, (s32) ui_battle_cont_c_right_up_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_MashCUpButton
HudScript HES_MashCUpButton
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  40 ,  34 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_up_up_png, (s32) ui_battle_cont_c_up_up_pal,
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cont_c_up_down_png, (s32) ui_battle_cont_c_up_down_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_MenuDefend
HudScript HES_MenuDefend = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_defend_png, (s32) ui_battle_menu_defend_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MenuDefendDisabled
HudScript HES_MenuDefendDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_defend_png , (s32) ui_battle_menu_defend_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MenuDoNothing
HudScript HES_MenuDoNothing = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_nothing_png, (s32) ui_battle_menu_nothing_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MenuDoNothingDisabled
HudScript HES_MenuDoNothingDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_nothing_png , (s32) ui_battle_menu_nothing_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MenuFlee
HudScript HES_MenuFlee = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_flee_png, (s32) ui_battle_menu_flee_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MenuFleeDisabled
HudScript HES_MenuFleeDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_flee_png , (s32) ui_battle_menu_flee_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MenuPouch
HudScript HES_MenuPouch = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_pouch_png, (s32) ui_battle_menu_pouch_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MenuPouchDisabled
HudScript HES_MenuPouchDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_pouch_png , (s32) ui_battle_menu_pouch_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MenuStrategies
HudScript HES_MenuStrategies = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_strategies_png, (s32) ui_battle_menu_strategies_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_MenuStrategiesDisabled
HudScript HES_MenuStrategiesDisabled = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_32x32 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_menu_strategies_png , (s32) ui_battle_menu_strategies_disabled_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_PressBButton
HudScript HES_PressBButton
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  48 ,  40 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  3 , (s32) ui_battle_cont_b_down_png, (s32) ui_battle_cont_b_down_pal,
        HUD_ELEMENT_OP_SetCI,  10 , (s32) ui_battle_cont_b_up_png, (s32) ui_battle_cont_b_up_pal,
        HUD_ELEMENT_OP_SetCI,  7 , (s32) ui_battle_cont_b_down_png, (s32) ui_battle_cont_b_down_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_PressCDownButton
HudScript HES_PressCDownButton
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  40 ,  34 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  6 , (s32) ui_battle_cont_c_down_down_png, (s32) ui_battle_cont_c_down_down_pal,
        HUD_ELEMENT_OP_SetCI,  10 , (s32) ui_battle_cont_c_down_up_png, (s32) ui_battle_cont_c_down_up_pal,
        HUD_ELEMENT_OP_SetCI,  4 , (s32) ui_battle_cont_c_down_down_png, (s32) ui_battle_cont_c_down_down_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_ProjectorBeam
HudScript HES_ProjectorBeam
Initial value:
= {
     HUD_ELEMENT_OP_UseIA8,
    HUD_ELEMENT_OP_SetCustomSize,  64 ,  64 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetRGBA,  60 , (s32) ui_battle_projector_beam_png ,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_main_menu_update(), and btl_state_update_celebration().
HES_ProjectorReel
HudScript HES_ProjectorReel
Initial value:
= {
     HUD_ELEMENT_OP_UseIA8,
    HUD_ELEMENT_OP_SetCustomSize,  64 ,  64 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetRGBA,  60 , (s32) ui_battle_projector_reel_png ,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_main_menu_update().
HES_ProjectorSpot
HudScript HES_ProjectorSpot
Initial value:
= {
     HUD_ELEMENT_OP_UseIA8,
    HUD_ELEMENT_OP_SetCustomSize,  32 ,  32 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetRGBA,  60 , (s32) ui_battle_projector_spot_png ,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_main_menu_update().
HES_RightOn
HudScript HES_RightOn
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  56 ,  24 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetTexelOffset,  0 ,  -16 ,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.00  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_right_on_png, (s32) ui_battle_cmd_right_on_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.10  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_right_on_png, (s32) ui_battle_cmd_right_on_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.20  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_right_on_png, (s32) ui_battle_cmd_right_on_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.30  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cmd_right_on_png, (s32) ui_battle_cmd_right_on_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.27  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cmd_right_on_png, (s32) ui_battle_cmd_right_on_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.15  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cmd_right_on_png, (s32) ui_battle_cmd_right_on_pal,
        HUD_ELEMENT_OP_SetScale, (s32)( 1.05  * 65536.0f),
        HUD_ELEMENT_OP_SetCI,  2 , (s32) ui_battle_cmd_right_on_png, (s32) ui_battle_cmd_right_on_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_RunningAway
HudScript HES_RunningAway
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCustomSize,  16 ,  24 ,
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_flee_0_png, (s32) ui_battle_cmd_flee_0_pal,
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_flee_1_png, (s32) ui_battle_cmd_flee_1_pal,
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_flee_2_png, (s32) ui_battle_cmd_flee_2_pal,
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_flee_0_png, (s32) ui_battle_cmd_flee_0_pal,
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_flee_2_png, (s32) ui_battle_cmd_flee_2_pal,
        HUD_ELEMENT_OP_SetCI,  1 , (s32) ui_battle_cmd_flee_1_png, (s32) ui_battle_cmd_flee_1_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
HES_SwapArrowLeft
HudScript HES_SwapArrowLeft
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  8 ,  16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  12 , (s32) ui_battle_swap_arrow_left_png, (s32) ui_battle_swap_arrow_left_pal,
        HUD_ELEMENT_OP_SetCI,  8 , (s32) ui_battle_swap_arrow_left_png, (s32) ui_battle_swap_arrow_left_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_main_menu_update().
HES_SwapArrowRight
HudScript HES_SwapArrowRight
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  8 ,  16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  10 , (s32) ui_battle_swap_arrow_right_png, (s32) ui_battle_swap_arrow_right_pal,
        HUD_ELEMENT_OP_SetCI,  10 , (s32) ui_battle_swap_arrow_right_png, (s32) ui_battle_swap_arrow_right_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_main_menu_update().
HES_SwapBackground
HudScript HES_SwapBackground
Initial value:
= {
     HUD_ELEMENT_OP_UseIA8,
    HUD_ELEMENT_OP_SetCustomSize,  48 ,  16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetRGBA,  60 , (s32) ui_battle_swap_background_png ,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_main_menu_update().
HES_SwapZ
HudScript HES_SwapZ = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 16 , 16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_swap_Z_png, (s32) ui_battle_swap_Z_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_main_menu_update().
HES_TimingBar1Chance
HudScript HES_TimingBar1Chance = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 72 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_1_chance_png, (s32) ui_battle_cmd_timing_1_chance_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_TimingBar3Chances
HudScript HES_TimingBar3Chances = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 96 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_3_chances_png, (s32) ui_battle_cmd_timing_3_chances_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_TimingBlink
HudScript HES_TimingBlink
Initial value:
= {
     HUD_ELEMENT_OP_SetVisible,
    HUD_ELEMENT_OP_SetCustomSize,  16 ,  16 ,
     HUD_ELEMENT_OP_Loop,
        HUD_ELEMENT_OP_SetCI,  10 , (s32) ui_battle_cmd_timing_ready_png, (s32) ui_battle_cmd_timing_ready_pal,
        HUD_ELEMENT_OP_SetCI,  6 , (s32) ui_battle_cmd_timing_wait_png, (s32) ui_battle_cmd_timing_wait_pal,
     HUD_ELEMENT_OP_Restart,
     HUD_ELEMENT_OP_End,
}
Referenced by btl_update_message_popup().
HES_TimingCharge1
HudScript HES_TimingCharge1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_1_png, (s32) ui_battle_cmd_charge_1_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by update().
HES_TimingCharge2
HudScript HES_TimingCharge2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_2_png, (s32) ui_battle_cmd_charge_2_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by update().
HES_TimingCharge3
HudScript HES_TimingCharge3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_3_png, (s32) ui_battle_cmd_charge_3_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by update().
HES_TimingCharge4a
HudScript HES_TimingCharge4a = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_4_png, (s32) ui_battle_cmd_charge_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_TimingCharge4b
HudScript HES_TimingCharge4b = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_4_png, (s32) ui_battle_cmd_charge_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_TimingCharge4c
HudScript HES_TimingCharge4c = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 8 , 8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_charge_4_png, (s32) ui_battle_cmd_charge_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_TimingGaugeResult
HudScript HES_TimingGaugeResult = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_gauge_result_png, (s32) ui_battle_cmd_gauge_result_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_TimingMiss
HudScript HES_TimingMiss = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 24 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_miss_png, (s32) ui_battle_cmd_timing_miss_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by update().
HES_TimingOK
HudScript HES_TimingOK = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 24 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_ok_png, (s32) ui_battle_cmd_timing_ok_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by update().
HES_TimingReady
HudScript HES_TimingReady = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 16 , 16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_ready_png, (s32) ui_battle_cmd_timing_ready_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_update_message_popup(), and update().
HES_TimingWait
HudScript HES_TimingWait = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 16 , 16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_cmd_timing_wait_png, (s32) ui_battle_cmd_timing_wait_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_YellowArrow
HudScript HES_YellowArrow = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_16x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) ui_battle_yellow_arrow_png, (s32) ui_battle_yellow_arrow_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }