papermario: src/audio/bgm_player.c File Reference
bgm_player.c File Reference
Macros
#define POST_BGM_READ()
Functions
void au_bgm_begin_video_frame (BGMPlayer *player)
BGMPlayer * au_bgm_get_player_with_song_name (s32 songString)
AuResult au_bgm_process_init_song (SongStartRequest *request)
AuResult au_bgm_stop_song (s32 songName)
void au_bgm_stop_all (void)
AuResult au_bgm_is_song_playing (s32 songName)
b32 au_bgm_player_is_active (BGMPlayer *player)
AuResult au_bgm_process_fade_out (SongFadeOutRequest *request)
AuResult au_bgm_complete_push (s32 songName)
AuResult au_bgm_process_suspend (SongSuspendRequest *request, b32 skipStop)
AuResult au_bgm_process_resume (SongResumeRequest *request)
void au_bgm_restore_copied_player (AuGlobals *globals)
AuResult au_bgm_adjust_volume (SongStartRequest *request)
void au_bgm_player_init (BGMPlayer *player, s32 priority, s32 busID, AuGlobals *globals)
void au_bgm_set_effect_indices (BGMPlayer *player, u8 *list)
void au_bgm_update_fade (BGMPlayer *player)
void au_bgm_update_bus_volumes (BGMPlayer *player)
s32 au_bgm_player_audio_frame_update (BGMPlayer *player)
void au_bgm_player_initialize (BGMPlayer *player)
void au_bgm_clear_custom_note_press (BGMPlayer *player, s32 index)
void au_bgm_set_tick_resolution (BGMPlayer *player, s32 mBeatsPerMinute, u32 ticksPerBeat)
void au_bgm_player_read_composition (BGMPlayer *player)
void au_bgm_end_composition_loop (BGMPlayer *player, u32 cmd)
void au_bgm_load_phrase (BGMPlayer *player, u32 cmd)
void au_bgm_player_update_stop (BGMPlayer *player)
void au_bgm_player_update_playing (BGMPlayer *player)
play next tick
void au_BGMCmd_E0_MasterTempo (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E1_MasterVolume (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E2_MasterDetune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E3 (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E6_MasterEffect (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E4_MasterTempoFade (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E5_MasterVolumeFade (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E8_TrackOverridePatch (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E9_InstrumentVolume (BGMPlayer *arg0, BGMPlayerTrack *track)
void au_BGMCmd_F6_InstrumentVolumeLerp (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EA_InstrumentPan (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EB_InstrumentReverb (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EC_TrackVolume (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_ED_InstrumentCoarseTune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EE_InstrumentFineTune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EC_TrackDetune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F0_TrackTremolo (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F1_TrackTremoloRate (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F2_TrackTremoloDepth (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F3_TrackTremoloStop (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F4_SubTrackRandomPan (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F5_UseInstrument (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F7_ReverbType (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FD_EventTrigger (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FE_Detour (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FC_Branch (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FF_Special (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_NOP (BGMPlayer *player, BGMPlayerTrack *track)
void au_bgm_set_proximity_mix (s32 songName, u32 mix)
void au_bgm_set_playback_rate (BGMPlayer *player, f32 rate)
void au_bgm_player_set_detune (BGMPlayer *player, s32 detune)
void au_bgm_change_track_volume (BGMPlayer *player, s32 trackIdx, s16 time, u8 volume)
void au_bgm_set_track_volumes (BGMPlayer *player, u8 *trackVols, s32 mode)
void au_bgm_set_prox_mix_fade (BGMPlayer *player, BGMPlayerTrack *track, s32 target, s32 duration)
void au_bgm_reset_all_voices (BGMPlayer *player)
AuResult au_bgm_set_linked_tracks (SongSwapLinkedRequest *request)
Variables
BSS void(* CurrentSeqCmdHandler)(BGMPlayer *, BGMPlayerTrack *)
u8 EnvelopeReleaseDefaultFast []
u8 BgmTicksRates [8]
u8 BgmCustomEnvLookup [40]
void(* SefCmdHandlers [])(SoundManager *, SoundPlayer *)
void(* SeqCmdHandlers [])(BGMPlayer *, BGMPlayerTrack *)
u8 SeqCmdArgCounts []
Macro Definition Documentation
POST_BGM_READ
#define POST_BGM_READ ()
Value:
if (track->detourLength != 0) {\
    track->detourLength--;\
    if (track->detourLength == 0) {\
        track->bgmReadPos = track->savedPos;\
    }\
}
Referenced by au_bgm_player_update_playing().
Function Documentation
au_bgm_adjust_volume()
AuResult au_bgm_adjust_volume (SongStartRequest * request)
Referenced by snd_song_set_volume_full(), and snd_song_set_volume_quiet().
au_bgm_begin_video_frame()
void au_bgm_begin_video_frame (BGMPlayer * player)
Referenced by au_update_clients_for_video_frame().
au_bgm_change_track_volume()
void au_bgm_change_track_volume (BGMPlayer * player, s32 trackIdx, s16 time, u8 volume)
au_bgm_clear_custom_note_press()
void au_bgm_clear_custom_note_press (BGMPlayer * player, s32 index)
Referenced by au_bgm_player_initialize(), and au_BGMCmd_FF_Special().
au_bgm_complete_push()
AuResult au_bgm_complete_push (s32 songName)
Referenced by au_bgm_update_fade().
au_bgm_end_composition_loop()
void au_bgm_end_composition_loop (BGMPlayer * player, u32 cmd)
Referenced by au_bgm_player_read_composition().
au_bgm_get_player_with_song_name()
BGMPlayer * au_bgm_get_player_with_song_name (s32 songString)
Referenced by au_bgm_adjust_volume(), au_bgm_is_song_playing(), au_bgm_process_fade_out(), au_bgm_process_init_song(), au_bgm_process_resume(), au_bgm_process_suspend(), au_bgm_set_linked_tracks(), au_bgm_set_proximity_mix(), and au_bgm_stop_song().
au_bgm_is_song_playing()
AuResult au_bgm_is_song_playing (s32 songName)
Referenced by snd_song_is_playing().
au_bgm_load_phrase()
void au_bgm_load_phrase (BGMPlayer * player, u32 cmd)
Referenced by au_bgm_player_read_composition().
au_bgm_player_audio_frame_update()
s32 au_bgm_player_audio_frame_update (BGMPlayer * player)
Referenced by au_update_clients_for_audio_frame().
au_bgm_player_init()
void au_bgm_player_init (BGMPlayer * player, s32 priority, s32 busID, AuGlobals * globals)
Referenced by au_engine_init().
au_bgm_player_initialize()
void au_bgm_player_initialize (BGMPlayer * player)
Referenced by au_bgm_player_audio_frame_update(), and au_bgm_process_init_song().
au_bgm_player_is_active()
b32 au_bgm_player_is_active (BGMPlayer * player)
Referenced by au_bgm_process_resume(), and au_load_song_files().
au_bgm_player_read_composition()
void au_bgm_player_read_composition (BGMPlayer * player)
Referenced by au_bgm_player_audio_frame_update().
au_bgm_player_set_detune()
void au_bgm_player_set_detune (BGMPlayer * player, s32 detune)
Referenced by snd_song_set_detune().
au_bgm_player_update_playing()
void au_bgm_player_update_playing (BGMPlayer * player)
play next tick
Referenced by au_bgm_player_audio_frame_update().
au_bgm_player_update_stop()
void au_bgm_player_update_stop (BGMPlayer * player)
Referenced by au_bgm_player_audio_frame_update().
au_bgm_process_fade_out()
AuResult au_bgm_process_fade_out (SongFadeOutRequest * request)
Referenced by snd_song_request_fade_out(), and snd_song_request_push_fade_out().
au_bgm_process_init_song()
AuResult au_bgm_process_init_song (SongStartRequest * request)
Referenced by snd_song_request_fade_in(), snd_song_request_fade_in_default(), snd_song_request_play(), and snd_song_request_play_default().
au_bgm_process_resume()
AuResult au_bgm_process_resume (SongResumeRequest * request)
Referenced by snd_song_request_pop(), and snd_song_request_unpause().
au_bgm_process_suspend()
AuResult au_bgm_process_suspend (SongSuspendRequest * request, b32 skipStop)
Referenced by au_bgm_complete_push(), snd_song_push_stop(), snd_song_request_pause(), and snd_song_request_snapshot().
au_bgm_reset_all_voices()
void au_bgm_reset_all_voices (BGMPlayer * player)
Referenced by au_bgm_player_initialize(), au_bgm_player_update_stop(), and au_bgm_process_suspend().
au_bgm_restore_copied_player()
void au_bgm_restore_copied_player (AuGlobals * globals)
Referenced by au_update_clients_for_audio_frame().
au_bgm_set_effect_indices()
void au_bgm_set_effect_indices (BGMPlayer * player, u8 * list)
Referenced by au_engine_init().
au_bgm_set_linked_tracks()
AuResult au_bgm_set_linked_tracks (SongSwapLinkedRequest * request)
Referenced by snd_song_set_linked_mode().
au_bgm_set_playback_rate()
void au_bgm_set_playback_rate (BGMPlayer * player, f32 rate)
Referenced by snd_song_set_playback_rate().
au_bgm_set_prox_mix_fade()
void au_bgm_set_prox_mix_fade (BGMPlayer * player, BGMPlayerTrack * track, s32 target, s32 duration)
Referenced by au_BGMCmd_FC_Branch(), and au_BGMCmd_FF_Special().
au_bgm_set_proximity_mix()
void au_bgm_set_proximity_mix (s32 songName, u32 mix)
Referenced by snd_song_set_proximity_mix_far(), snd_song_set_proximity_mix_full(), and snd_song_set_proximity_mix_near().
au_bgm_set_tick_resolution()
void au_bgm_set_tick_resolution (BGMPlayer * player, s32 mBeatsPerMinute, u32 ticksPerBeat)
Referenced by au_bgm_begin_video_frame(), au_bgm_player_init(), and au_bgm_process_init_song().
au_bgm_set_track_volumes()
void au_bgm_set_track_volumes (BGMPlayer * player, u8 * trackVols, s32 mode)
Referenced by snd_song_clear_track_volumes(), and snd_song_set_track_volumes().
au_bgm_stop_all()
void au_bgm_stop_all (void)
Referenced by snd_song_stop_all().
au_bgm_stop_song()
AuResult au_bgm_stop_song (s32 songName)
Referenced by snd_song_stop().
au_bgm_update_bus_volumes()
void au_bgm_update_bus_volumes (BGMPlayer * player)
Referenced by au_bgm_update_fade(), and au_update_clients_for_audio_frame().
au_bgm_update_fade()
void au_bgm_update_fade (BGMPlayer * player)
Referenced by au_update_clients_for_audio_frame().
au_BGMCmd_E0_MasterTempo()
void au_BGMCmd_E0_MasterTempo (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E1_MasterVolume()
void au_BGMCmd_E1_MasterVolume (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E2_MasterDetune()
void au_BGMCmd_E2_MasterDetune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E3()
void au_BGMCmd_E3 (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E4_MasterTempoFade()
void au_BGMCmd_E4_MasterTempoFade (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E5_MasterVolumeFade()
void au_BGMCmd_E5_MasterVolumeFade (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E6_MasterEffect()
void au_BGMCmd_E6_MasterEffect (BGMPlayer * player, BGMPlayerTrack * track)
Referenced by au_bgm_restore_copied_player().
au_BGMCmd_E8_TrackOverridePatch()
void au_BGMCmd_E8_TrackOverridePatch (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E9_InstrumentVolume()
void au_BGMCmd_E9_InstrumentVolume (BGMPlayer * arg0, BGMPlayerTrack * track)
Referenced by au_bgm_set_linked_tracks().
au_BGMCmd_EA_InstrumentPan()
void au_BGMCmd_EA_InstrumentPan (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EB_InstrumentReverb()
void au_BGMCmd_EB_InstrumentReverb (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EC_TrackDetune()
void au_BGMCmd_EC_TrackDetune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EC_TrackVolume()
void au_BGMCmd_EC_TrackVolume (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_ED_InstrumentCoarseTune()
void au_BGMCmd_ED_InstrumentCoarseTune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EE_InstrumentFineTune()
void au_BGMCmd_EE_InstrumentFineTune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F0_TrackTremolo()
void au_BGMCmd_F0_TrackTremolo (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F1_TrackTremoloRate()
void au_BGMCmd_F1_TrackTremoloRate (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F2_TrackTremoloDepth()
void au_BGMCmd_F2_TrackTremoloDepth (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F3_TrackTremoloStop()
void au_BGMCmd_F3_TrackTremoloStop (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F4_SubTrackRandomPan()
void au_BGMCmd_F4_SubTrackRandomPan (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F5_UseInstrument()
void au_BGMCmd_F5_UseInstrument (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F6_InstrumentVolumeLerp()
void au_BGMCmd_F6_InstrumentVolumeLerp (BGMPlayer * player, BGMPlayerTrack * track)
Referenced by au_bgm_change_track_volume(), au_bgm_player_update_playing(), and au_bgm_set_linked_tracks().
au_BGMCmd_F7_ReverbType()
void au_BGMCmd_F7_ReverbType (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FC_Branch()
void au_BGMCmd_FC_Branch (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FD_EventTrigger()
void au_BGMCmd_FD_EventTrigger (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FE_Detour()
void au_BGMCmd_FE_Detour (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FF_Special()
void au_BGMCmd_FF_Special (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_NOP()
void au_BGMCmd_NOP (BGMPlayer * player, BGMPlayerTrack * track)
Variable Documentation
BgmCustomEnvLookup
u8 BgmCustomEnvLookup[40] extern
Referenced by au_BGMCmd_FF_Special().
BgmTicksRates
u8 BgmTicksRates[8] extern
Referenced by au_bgm_begin_video_frame(), and au_bgm_process_init_song().
CurrentSeqCmdHandler
BSS void(* CurrentSeqCmdHandler) (BGMPlayer *, BGMPlayerTrack *) (BGMPlayer * , BGMPlayerTrack *)
Referenced by au_bgm_player_update_playing().
EnvelopeReleaseDefaultFast
u8 EnvelopeReleaseDefaultFast[] extern
Referenced by au_bgm_set_linked_tracks().
SefCmdHandlers
void(* SefCmdHandlers[])(SoundManager *, SoundPlayer *) (SoundManager * , SoundPlayer *) extern
SeqCmdArgCounts
u8 SeqCmdArgCounts[] extern
Referenced by au_bgm_player_update_playing().
SeqCmdHandlers
void(* SeqCmdHandlers[])(BGMPlayer *, BGMPlayerTrack *) (BGMPlayer * , BGMPlayerTrack *) extern
Referenced by au_bgm_player_update_playing().