papermario: src/effects/big_smoke_puff.c File Reference
big_smoke_puff.c File Reference
Functions
void big_smoke_puff_init (EffectInstance *effect)
void big_smoke_puff_update (EffectInstance *effect)
void big_smoke_puff_render (EffectInstance *effect)
void big_smoke_puff_appendGfx (void *effect)
void big_smoke_puff_main (f32 x, f32 y, f32 z)
void func_E0002738 (EffectInstance *effect)
Variables
Gfx D_09000FA0_3273B0 []
Gfx D_09001060_327470 []
Gfx D_09001120_327530 []
Gfx D_090011E0_3275F0 []
Gfx D_090012A0_3276B0 []
Gfx D_09001360_327770 []
Gfx D_09001420_327830 []
Function Documentation
big_smoke_puff_appendGfx()
void big_smoke_puff_appendGfx (void * effect)
Referenced by big_smoke_puff_render().
big_smoke_puff_init()
void big_smoke_puff_init (EffectInstance * effect)
Referenced by big_smoke_puff_main().
big_smoke_puff_main()
void big_smoke_puff_main (f32 x, f32 y, f32 z)
big_smoke_puff_render()
void big_smoke_puff_render (EffectInstance * effect)
Referenced by big_smoke_puff_main().
big_smoke_puff_update()
void big_smoke_puff_update (EffectInstance * effect)
Referenced by big_smoke_puff_main().
func_E0002738()
void func_E0002738 (EffectInstance * effect)
Variable Documentation
D_09000FA0_3273B0
Gfx D_09000FA0_3273B0[] extern
D_09001060_327470
Gfx D_09001060_327470[] extern
D_09001120_327530
Gfx D_09001120_327530[] extern
D_090011E0_3275F0
Gfx D_090011E0_3275F0[] extern
D_090012A0_3276B0
Gfx D_090012A0_3276B0[] extern
D_09001360_327770
Gfx D_09001360_327770[] extern
D_09001420_327830
Gfx D_09001420_327830[] extern