papermario: src/effects/blast.c File Reference
blast.c File Reference
Functions
void blast_init (EffectInstance *effect)
void blast_update (EffectInstance *effect)
void blast_render (EffectInstance *effect)
void blast_appendGfx (void *effect)
void blast_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09001300_37ECD0 []
Gfx D_09001378_37ED48 []
Gfx D_090013F0_37EDC0 []
Gfx D_09001468_37EE38 []
Gfx D_090014E0_37EEB0 []
Gfx D_09001558_37EF28 []
Gfx D_090015D0_37EFA0 []
Gfx D_09001648_37F018 []
Gfx D_090016C0_37F090 []
Gfx D_09001738_37F108 []
Gfx D_090017B0_37F180 []
Gfx * D_E007C510 []
Function Documentation
blast_appendGfx()
void blast_appendGfx (void * effect)
Referenced by blast_render().
blast_init()
void blast_init (EffectInstance * effect)
Referenced by blast_main().
blast_main()
void blast_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
blast_render()
void blast_render (EffectInstance * effect)
Referenced by blast_main().
blast_update()
void blast_update (EffectInstance * effect)
Referenced by blast_main().
Variable Documentation
D_09001300_37ECD0
Gfx D_09001300_37ECD0[] extern
Referenced by blast_appendGfx().
D_09001378_37ED48
Gfx D_09001378_37ED48[] extern
D_090013F0_37EDC0
Gfx D_090013F0_37EDC0[] extern
D_09001468_37EE38
Gfx D_09001468_37EE38[] extern
D_090014E0_37EEB0
Gfx D_090014E0_37EEB0[] extern
D_09001558_37EF28
Gfx D_09001558_37EF28[] extern
D_090015D0_37EFA0
Gfx D_090015D0_37EFA0[] extern
D_09001648_37F018
Gfx D_09001648_37F018[] extern
D_090016C0_37F090
Gfx D_090016C0_37F090[] extern
D_09001738_37F108
Gfx D_09001738_37F108[] extern
D_090017B0_37F180
Gfx D_090017B0_37F180[] extern
Referenced by blast_appendGfx().
D_E007C510
Gfx* D_E007C510[]
Initial value:
= {
    D_09001378_37ED48, D_090013F0_37EDC0, D_09001468_37EE38,
    D_090014E0_37EEB0, D_09001558_37EF28, D_090015D0_37EFA0,
    D_09001648_37F018, D_090016C0_37F090, D_09001738_37F108
}
Referenced by blast_appendGfx().