papermario: src/entity/Block.c File Reference
Block.c File Reference
Macros
#define MULTICOIN_BLOCK_MAX_COINS 10
Functions
void entity_BrickBlock_idle (Entity *entity)
void entity_breakable_block_create_shattering_entity (Entity *entity)
void entity_MulticoinBlock_update_timer (Entity *entity)
void entity_base_block_setupGfx (s32 entityIndex)
void entity_base_block_play_vanish_effect (Entity *entity)
f32 entity_block_hit_init_scale (Entity *entity)
void entity_block_hit_animate_scale (Entity *entity)
void entity_base_block_update_slow_sinking (Entity *entity)
s32 entity_base_block_idle (Entity *entity)
void entity_base_block_init (Entity *entity)
void entity_inactive_block_hit_init (Entity *entity)
void entity_inactive_block_hit_anim (Entity *entity)
void entity_inactive_block_recoil_anim (Entity *entity)
void entity_MulticoinBlock_init (Entity *entity)
void entity_MulticoinBlock_spawn_coin (Entity *entity)
void entity_MulticoinBlock_idle (Entity *entity)
void entity_MulticoinBlock_check_if_inactive (Entity *entity)
s32 entity_block_handle_collision (Entity *entity)
void entity_init_Hammer1Block_normal (Entity *entity)
void entity_init_HammerBlock_small (Entity *entity)
Variables
Gfx Entity_InertYellowBlock_Render []
Gfx Entity_InertRedBlock_Render []
Gfx Entity_BrickBlock_Render []
Gfx Entity_Hammer1Block_Render []
Gfx Entity_Hammer2Block_Render []
Gfx Entity_Hammer3Block_Render []
Gfx Entity_PushBlock_Render []
Gfx Entity_PowBlock_Render []
EntityScript Entity_CreatedInertBlock_Script
EntityScript Entity_BreakingBlock_Script
EntityBlueprint Entity_ShatteringHammer1Block
EntityBlueprint Entity_ShatteringHammer2Block
EntityBlueprint Entity_ShatteringHammer3Block
EntityBlueprint Entity_ShatteringHammer1BlockTiny
EntityBlueprint Entity_ShatteringHammer2BlockTiny
EntityBlueprint Entity_ShatteringHammer3BlockTiny
EntityBlueprint Entity_ShatteringBrickBlock
EntityScript Entity_PowBlock_Script
EntityScript Entity_BaseBlock_Script
EntityScript D_802E9DEC
EntityScript Entity_InertBlock_Script
EntityScript Entity_BrickBlock_Script
EntityScript Entity_Hammer1Block_Script
EntityScript Entity_MulticoinBlock_Script
EntityModelScript Entity_InertYellowBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_InertYellowBlock_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_InertRedBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_InertRedBlock_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_MulticoinBrick_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_BrickBlock_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_Hammer1Block_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Hammer1Block_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_Hammer2Block_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Hammer2Block_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_Hammer3Block_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Hammer3Block_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_PushBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PushBlock_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_BrickBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_BrickBlock_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_PowBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PowBlock_Render, RENDER_MODE_SURFACE_OPA)
EntityBlueprint Entity_InertYellowBlock
EntityBlueprint Entity_InertRedBlock
EntityBlueprint Entity_BrickBlock
EntityBlueprint Entity_MulticoinBlock
EntityBlueprint Entity_Hammer1Block
EntityBlueprint Entity_Hammer1BlockWideX
EntityBlueprint Entity_Hammer1BlockWideZ
EntityBlueprint Entity_Hammer1BlockTiny
EntityBlueprint Entity_Hammer2Block
EntityBlueprint Entity_Hammer2BlockWideX
EntityBlueprint Entity_Hammer2BlockWideZ
EntityBlueprint Entity_Hammer2BlockTiny
EntityBlueprint Entity_Hammer3Block
EntityBlueprint Entity_Hammer3BlockWideX
EntityBlueprint Entity_Hammer3BlockWideZ
EntityBlueprint Entity_Hammer3BlockTiny
EntityBlueprint Entity_PushBlock
EntityBlueprint Entity_PowBlock
Macro Definition Documentation
MULTICOIN_BLOCK_MAX_COINS
#define MULTICOIN_BLOCK_MAX_COINS 10
Referenced by entity_MulticoinBlock_init(), entity_MulticoinBlock_spawn_coin(), and entity_MulticoinBlock_update_timer().
Function Documentation
entity_base_block_idle()
s32 entity_base_block_idle (Entity * entity)
Referenced by entity_block_hit_animate_scale(), entity_BrickBlock_idle(), entity_HeartBlock_idle(), entity_ItemBlock_idle(), entity_MulticoinBlock_idle(), entity_SaveBlock_idle(), and entity_upgrade_block_idle().
entity_base_block_init()
void entity_base_block_init (Entity * entity)
Referenced by entity_HeartBlock_create_child_entity(), entity_init_Hammer1Block_normal(), entity_ItemBlock_init(), entity_ItemlessBlock_init(), entity_MulticoinBlock_init(), entity_SaveBlock_init(), and entity_upgrade_block_init().
entity_base_block_play_vanish_effect()
void entity_base_block_play_vanish_effect (Entity * entity)
entity_base_block_setupGfx()
void entity_base_block_setupGfx (s32 entityIndex)
Referenced by entity_init_Hammer1Block_normal().
entity_base_block_update_slow_sinking()
void entity_base_block_update_slow_sinking (Entity * entity)
Referenced by entity_base_block_idle().
entity_block_handle_collision()
s32 entity_block_handle_collision (Entity * entity)
entity_block_hit_animate_scale()
void entity_block_hit_animate_scale (Entity * entity)
entity_block_hit_init_scale()
f32 entity_block_hit_init_scale (Entity * entity)
entity_breakable_block_create_shattering_entity()
void entity_breakable_block_create_shattering_entity (Entity * entity)
entity_BrickBlock_idle()
void entity_BrickBlock_idle (Entity * entity)
entity_inactive_block_hit_anim()
void entity_inactive_block_hit_anim (Entity * entity)
entity_inactive_block_hit_init()
void entity_inactive_block_hit_init (Entity * entity)
entity_inactive_block_recoil_anim()
void entity_inactive_block_recoil_anim (Entity * entity)
entity_init_Hammer1Block_normal()
void entity_init_Hammer1Block_normal (Entity * entity)
entity_init_HammerBlock_small()
void entity_init_HammerBlock_small (Entity * entity)
entity_MulticoinBlock_check_if_inactive()
void entity_MulticoinBlock_check_if_inactive (Entity * entity)
entity_MulticoinBlock_idle()
void entity_MulticoinBlock_idle (Entity * entity)
entity_MulticoinBlock_init()
void entity_MulticoinBlock_init (Entity * entity)
entity_MulticoinBlock_spawn_coin()
void entity_MulticoinBlock_spawn_coin (Entity * entity)
entity_MulticoinBlock_update_timer()
void entity_MulticoinBlock_update_timer (Entity * entity)
Referenced by entity_inactive_block_hit_anim(), entity_inactive_block_recoil_anim(), and entity_MulticoinBlock_idle().
Variable Documentation
D_802E9DEC
EntityScript D_802E9DEC
Initial value:
= {
    es_SetCallback(entity_base_block_idle, 0)
    es_PlaySound(SOUND_HIT_BLOCK)
    es_Restart
    es_End
}
Entity_BaseBlock_Script
EntityScript Entity_BaseBlock_Script
Initial value:
= {
    es_SetCallback(entity_base_block_idle, 0)
    es_Call(entity_start_script)
    es_Restart
    es_End
}
Entity_BreakingBlock_Script
EntityScript Entity_BreakingBlock_Script
Initial value:
= {
    es_RestartBoundScript
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetFlags(ENTITY_FLAG_DISABLE_COLLISION)
    es_Call(entity_breakable_block_create_shattering_entity)
    es_SetCallback(NULL, 1)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Referenced by entity_block_handle_collision().
Entity_BrickBlock
EntityBlueprint Entity_BrickBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_BrickBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_BrickBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(BrickBlock) },
    .entityType = ENTITY_TYPE_BRICK_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Referenced by MAP_RODATA_PAD().
Entity_BrickBlock_Render
Gfx Entity_BrickBlock_Render[] extern
Entity_BrickBlock_RenderScript
EntityModelScript Entity_BrickBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_BrickBlock_Render, RENDER_MODE_SURFACE_OPA)
Entity_BrickBlock_Script
EntityScript Entity_BrickBlock_Script
Initial value:
= {
    es_SetCallback(entity_BrickBlock_idle, 0)
    es_Call(entity_start_script)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetFlags(ENTITY_FLAG_DISABLE_COLLISION)
    es_Call(entity_breakable_block_create_shattering_entity)
    es_PlaySound(SOUND_HIT_BLOCK)
    es_SetCallback(NULL, 2)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_CreatedInertBlock_Script
EntityScript Entity_CreatedInertBlock_Script
Initial value:
= {
    es_Call(entity_inactive_block_hit_init)
    es_SetCallback(entity_inactive_block_hit_anim, 0)
    es_SetCallback(entity_inactive_block_recoil_anim, 0)
    es_Jump(Entity_InertBlock_Script)
    es_End
}
Referenced by entity_MulticoinBlock_spawn_coin().
Entity_Hammer1Block
EntityBlueprint Entity_Hammer1Block
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer1Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_Hammer1Block_normal,
    .updateEntityScript = Entity_Hammer1Block_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer1Block) },
    .entityType = ENTITY_TYPE_HAMMER1_BLOCK,
    .aabbSize = { 50, 50, 50 }
}
Entity_Hammer1Block_Render
Gfx Entity_Hammer1Block_Render[] extern
Entity_Hammer1Block_RenderScript
EntityModelScript Entity_Hammer1Block_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Hammer1Block_Render, RENDER_MODE_SURFACE_OPA)
Entity_Hammer1Block_Script
EntityScript Entity_Hammer1Block_Script
Initial value:
= {
    es_SetCallback(entity_base_block_idle, 0)
    es_PlaySound(SOUND_HIT_BLOCK)
    es_Call(entity_start_script)
    es_Restart
    es_End
}
Entity_Hammer1BlockTiny
EntityBlueprint Entity_Hammer1BlockTiny
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer1Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_HammerBlock_small,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer1Block) },
    .entityType = ENTITY_TYPE_HAMMER1_BLOCK_TINY,
    .aabbSize = { 25, 25, 25 }
}
Entity_Hammer1BlockWideX
EntityBlueprint Entity_Hammer1BlockWideX
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer1Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_Hammer1Block_normal,
    .updateEntityScript = Entity_Hammer1Block_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer1Block) },
    .entityType = ENTITY_TYPE_HAMMER1_BLOCK,
    .aabbSize = { 100, 50, 50 }
}
Entity_Hammer1BlockWideZ
EntityBlueprint Entity_Hammer1BlockWideZ
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer1Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_Hammer1Block_normal,
    .updateEntityScript = Entity_Hammer1Block_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer1Block) },
    .entityType = ENTITY_TYPE_HAMMER1_BLOCK,
    .aabbSize = { 50, 50, 100 }
}
Entity_Hammer2Block
EntityBlueprint Entity_Hammer2Block
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer2Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer2Block) },
    .entityType = ENTITY_TYPE_HAMMER2_BLOCK,
    .aabbSize = { 50, 50, 50 }
}
Entity_Hammer2Block_Render
Gfx Entity_Hammer2Block_Render[] extern
Entity_Hammer2Block_RenderScript
EntityModelScript Entity_Hammer2Block_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Hammer2Block_Render, RENDER_MODE_SURFACE_OPA)
Entity_Hammer2BlockTiny
EntityBlueprint Entity_Hammer2BlockTiny
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer2Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_HammerBlock_small,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer2Block) },
    .entityType = ENTITY_TYPE_HAMMER2_BLOCK_TINY,
    .aabbSize = { 25, 25, 25 }
}
Entity_Hammer2BlockWideX
EntityBlueprint Entity_Hammer2BlockWideX
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer2Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer2Block) },
    .entityType = ENTITY_TYPE_HAMMER2_BLOCK,
    .aabbSize = { 100, 50, 50 }
}
Entity_Hammer2BlockWideZ
EntityBlueprint Entity_Hammer2BlockWideZ
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer2Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer2Block) },
    .entityType = ENTITY_TYPE_HAMMER2_BLOCK,
    .aabbSize = { 50, 50, 100 }
}
Entity_Hammer3Block
EntityBlueprint Entity_Hammer3Block
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer3Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer3Block) },
    .entityType = ENTITY_TYPE_HAMMER3_BLOCK,
    .aabbSize = { 50, 50, 50 }
}
Entity_Hammer3Block_Render
Gfx Entity_Hammer3Block_Render[] extern
Entity_Hammer3Block_RenderScript
EntityModelScript Entity_Hammer3Block_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Hammer3Block_Render, RENDER_MODE_SURFACE_OPA)
Entity_Hammer3BlockTiny
EntityBlueprint Entity_Hammer3BlockTiny
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer3Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_HammerBlock_small,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer3Block) },
    .entityType = ENTITY_TYPE_HAMMER3_BLOCK_TINY,
    .aabbSize = { 25, 25, 25 }
}
Entity_Hammer3BlockWideX
EntityBlueprint Entity_Hammer3BlockWideX
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer3Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer3Block) },
    .entityType = ENTITY_TYPE_HAMMER3_BLOCK,
    .aabbSize = { 100, 50, 50 }
}
Entity_Hammer3BlockWideZ
EntityBlueprint Entity_Hammer3BlockWideZ
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_80,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_Hammer3Block_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(Hammer3Block) },
    .entityType = ENTITY_TYPE_HAMMER3_BLOCK,
    .aabbSize = { 50, 50, 100 }
}
Entity_InertBlock_Script
EntityScript Entity_InertBlock_Script
Initial value:
= {
    es_SetCallback(entity_base_block_idle, 0)
    es_PlaySound(SOUND_HIT_BLOCK)
    es_Call(entity_inactive_block_hit_init)
    es_Call(entity_start_script)
    es_SetCallback(entity_inactive_block_hit_anim, 0)
    es_SetCallback(entity_inactive_block_recoil_anim, 0)
    es_Restart
    es_End
}
Entity_InertRedBlock
EntityBlueprint Entity_InertRedBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_InertRedBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_Hammer1Block_normal,
    .updateEntityScript = Entity_InertBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(InertRedBlock) },
    .entityType = ENTITY_TYPE_INACTIVE_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Referenced by entity_ItemBlock_check_if_inactive(), and entity_ItemBlock_replace_with_inactive().
Entity_InertRedBlock_Render
Gfx Entity_InertRedBlock_Render[] extern
Entity_InertRedBlock_RenderScript
EntityModelScript Entity_InertRedBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_InertRedBlock_Render, RENDER_MODE_SURFACE_OPA)
Entity_InertYellowBlock
EntityBlueprint Entity_InertYellowBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_InertYellowBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_Hammer1Block_normal,
    .updateEntityScript = Entity_InertBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(InertYellowBlock) },
    .entityType = ENTITY_TYPE_MULTI_TRIGGER_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Referenced by entity_ItemBlock_check_if_inactive(), entity_ItemBlock_replace_with_inactive(), entity_MulticoinBlock_check_if_inactive(), entity_MulticoinBlock_idle(), and entity_MulticoinBlock_spawn_coin().
Entity_InertYellowBlock_Render
Gfx Entity_InertYellowBlock_Render[] extern
Entity_InertYellowBlock_RenderScript
EntityModelScript Entity_InertYellowBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_InertYellowBlock_Render, RENDER_MODE_SURFACE_OPA)
Entity_MulticoinBlock
EntityBlueprint Entity_MulticoinBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_MulticoinBrick_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_MulticoinBlock_init,
    .updateEntityScript = Entity_MulticoinBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(BrickBlock) },
    .entityType = ENTITY_TYPE_MULTI_COIN_BRICK,
    .aabbSize = { 25, 25, 25 }
}
Entity_MulticoinBlock_Script
EntityScript Entity_MulticoinBlock_Script
Initial value:
= {
    es_Call(entity_MulticoinBlock_check_if_inactive)
    es_Label(1)
        es_SetCallback(entity_MulticoinBlock_idle, 0)
        es_PlaySound(SOUND_HIT_BLOCK)
        es_Call(entity_MulticoinBlock_spawn_coin)
        es_Call(entity_inactive_block_hit_init)
        es_SetCallback(entity_inactive_block_hit_anim, 0)
        es_SetCallback(entity_inactive_block_recoil_anim, 0)
    es_Goto(1)
    es_End
}
Entity_MulticoinBrick_RenderScript
EntityModelScript Entity_MulticoinBrick_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_BrickBlock_Render, RENDER_MODE_SURFACE_OPA)
Entity_PowBlock
EntityBlueprint Entity_PowBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_PowBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_PowBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(PowBlock) },
    .entityType = ENTITY_TYPE_POW_BLOCK,
    .aabbSize = { 30, 25, 25 },
}
Entity_PowBlock_Render
Gfx Entity_PowBlock_Render[] extern
Entity_PowBlock_RenderScript
EntityModelScript Entity_PowBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PowBlock_Render, RENDER_MODE_SURFACE_OPA)
Entity_PowBlock_Script
EntityScript Entity_PowBlock_Script
Initial value:
= {
    es_SetCallback(entity_base_block_idle, 0)
    es_PlaySound(SOUND_HIT_BLOCK)
    es_Call(entity_block_hit_init_scale)
    es_SetCallback(entity_block_hit_animate_scale, 6)
    es_Call(entity_start_script)
    es_Restart
    es_End
}
Entity_PushBlock
EntityBlueprint Entity_PushBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_PushBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_BaseBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(PushBlock) },
    .entityType = ENTITY_TYPE_PUSH_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Entity_PushBlock_Render
Gfx Entity_PushBlock_Render[] extern
Entity_PushBlock_RenderScript
EntityModelScript Entity_PushBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PushBlock_Render, RENDER_MODE_SURFACE_OPA)
Entity_ShatteringBrickBlock
EntityBlueprint Entity_ShatteringBrickBlock extern
Referenced by entity_breakable_block_create_shattering_entity().
Entity_ShatteringHammer1Block
EntityBlueprint Entity_ShatteringHammer1Block extern
Referenced by entity_breakable_block_create_shattering_entity().
Entity_ShatteringHammer1BlockTiny
EntityBlueprint Entity_ShatteringHammer1BlockTiny extern
Referenced by entity_breakable_block_create_shattering_entity().
Entity_ShatteringHammer2Block
EntityBlueprint Entity_ShatteringHammer2Block extern
Referenced by entity_breakable_block_create_shattering_entity().
Entity_ShatteringHammer2BlockTiny
EntityBlueprint Entity_ShatteringHammer2BlockTiny extern
Referenced by entity_breakable_block_create_shattering_entity().
Entity_ShatteringHammer3Block
EntityBlueprint Entity_ShatteringHammer3Block extern
Referenced by entity_breakable_block_create_shattering_entity().
Entity_ShatteringHammer3BlockTiny
EntityBlueprint Entity_ShatteringHammer3BlockTiny extern
Referenced by entity_breakable_block_create_shattering_entity().