papermario: src/battle/action_cmd/body_slam.h File Reference
body_slam.h File Reference
Enumerations
enum { ACV_SLAM_BOMBETTE = 0 , ACV_SLAM_WATT = 1 }
Functions
void action_command_body_slam_update (void)
void action_command_body_slam_draw (void)
void action_command_body_slam_free (void)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ACV_SLAM_BOMBETTE
ACV_SLAM_WATT
Function Documentation
action_command_body_slam_draw()
void action_command_body_slam_draw (void)
Referenced by action_command_draw().
action_command_body_slam_free()
void action_command_body_slam_free (void)
Referenced by action_command_free().
action_command_body_slam_update()
void action_command_body_slam_update (void)
Referenced by action_command_update().