papermario: src/effects/bombette_breaking.c File Reference
bombette_breaking.c File Reference
Functions
void bombette_breaking_init (EffectInstance *effect)
void bombette_breaking_update (EffectInstance *effect)
void bombette_breaking_render (EffectInstance *effect)
void bombette_breaking_appendGfx (void *effect)
void bombette_breaking_get_model_center_and_size (s32 modelID, f32 *centerX, f32 *centerY, f32 *centerZ, f32 *sizeX, f32 *sizeY, f32 *sizeZ)
Model * bombette_breaking_get_model_from_list_index (s32 listIndex)
s32 bombette_breaking_get_model_list_index_from_tree_index (s32 listIndex)
EffectInstance * bombette_breaking_main (s32 type, s32 modelID, s32 treeIndex, f32 arg3, s32 arg4, s32 time)
Variables
Gfx D_090017D0_37F1A0 []
Gfx D_090018C0_37F290 []
Gfx D_09001C80_37F650 []
Gfx D_09001CC8_37F698 []
Gfx D_09001D00_37F6D0 []
Gfx * D_E0084E10 [] = { D_090018C0_37F290, D_090018C0_37F290, D_090018C0_37F290 }
Gfx * D_E0084E1C [] = { D_09001D00_37F6D0, D_09001CC8_37F698, D_09001C80_37F650 }
Gfx * D_E0084E28 [] = { D_090017D0_37F1A0, D_090017D0_37F1A0, D_090017D0_37F1A0 }
void(* D_E0084E34)(u16, f32 *, f32 *, f32 *, f32 *, f32 *, f32 *) = get_model_center_and_size
Model *(* D_E0084E38)(s32) = get_model_from_list_index
s32(* D_E0084E3C)(s32) = get_model_list_index_from_tree_index
Function Documentation
bombette_breaking_appendGfx()
void bombette_breaking_appendGfx (void * effect)
Referenced by bombette_breaking_render().
bombette_breaking_get_model_center_and_size()
void bombette_breaking_get_model_center_and_size (s32 modelID, f32 * centerX, f32 * centerY, f32 * centerZ, f32 * sizeX, f32 * sizeY, f32 * sizeZ)
Referenced by bombette_breaking_main().
bombette_breaking_get_model_from_list_index()
Model * bombette_breaking_get_model_from_list_index (s32 listIndex)
bombette_breaking_get_model_list_index_from_tree_index()
s32 bombette_breaking_get_model_list_index_from_tree_index (s32 listIndex)
bombette_breaking_init()
void bombette_breaking_init (EffectInstance * effect)
Referenced by bombette_breaking_main().
bombette_breaking_main()
EffectInstance * bombette_breaking_main (s32 type, s32 modelID, s32 treeIndex, f32 arg3, s32 arg4, s32 time)
bombette_breaking_render()
void bombette_breaking_render (EffectInstance * effect)
Referenced by bombette_breaking_main().
bombette_breaking_update()
void bombette_breaking_update (EffectInstance * effect)
Referenced by bombette_breaking_main().
Variable Documentation
D_090017D0_37F1A0
Gfx D_090017D0_37F1A0[] extern
D_090018C0_37F290
Gfx D_090018C0_37F290[] extern
D_09001C80_37F650
Gfx D_09001C80_37F650[] extern
D_09001CC8_37F698
Gfx D_09001CC8_37F698[] extern
D_09001D00_37F6D0
Gfx D_09001D00_37F6D0[] extern
D_E0084E10
Gfx* D_E0084E10[] = { D_090018C0_37F290, D_090018C0_37F290, D_090018C0_37F290 }
Referenced by bombette_breaking_appendGfx().
D_E0084E1C
Gfx* D_E0084E1C[] = { D_09001D00_37F6D0, D_09001CC8_37F698, D_09001C80_37F650 }
Referenced by bombette_breaking_appendGfx().
D_E0084E28
Gfx* D_E0084E28[] = { D_090017D0_37F1A0, D_090017D0_37F1A0, D_090017D0_37F1A0 }
Referenced by bombette_breaking_appendGfx().
D_E0084E34
void(* D_E0084E34) (u16, f32 *, f32 *, f32 *, f32 *, f32 *, f32 *) (u16 , f32 * , f32 * , f32 * , f32 * , f32 * , f32 *) = get_model_center_and_size
Referenced by bombette_breaking_get_model_center_and_size().
D_E0084E38
Model *(* D_E0084E38) (s32) (s32) = get_model_from_list_index
Referenced by bombette_breaking_get_model_from_list_index().
D_E0084E3C
s32(* D_E0084E3C) (s32) (s32) = get_model_list_index_from_tree_index
Referenced by bombette_breaking_get_model_list_index_from_tree_index().