papermario: src/battle/action_cmd/bomb.h File Reference
bomb.h File Reference
Functions
void action_command_bomb_update (void)
void action_command_bomb_draw (void)
void action_command_bomb_free (void)
Function Documentation
action_command_bomb_draw()
void action_command_bomb_draw (void)
Referenced by action_command_draw().
action_command_bomb_free()
void action_command_bomb_free (void)
Referenced by action_command_free().
action_command_bomb_update()
void action_command_bomb_update (void)
Referenced by action_command_update().