papermario: src/effects/breaking_junk.c File Reference
breaking_junk.c File Reference
Functions
void breaking_junk_init (EffectInstance *effect)
void breaking_junk_update (EffectInstance *effect)
void breaking_junk_render (EffectInstance *effect)
void breaking_junk_appendGfx (void *effect)
EffectInstance * breaking_junk_main (s32 arg0, f32 x, f32 y, f32 z, f32 scale, s32 time)
Variables
Gfx D_09000400_403FF0 []
Gfx D_090005A8_404198 []
Gfx D_090005C8_4041B8 []
Gfx D_090005E8_4041D8 []
Gfx D_09000608_4041F8 []
Gfx * D_E01187B0 [] = { D_090005A8_404198, D_090005C8_4041B8, D_090005E8_4041D8, D_09000608_4041F8 }
Gfx * D_E01187C0 [] = { D_09000400_403FF0 }
Function Documentation
breaking_junk_appendGfx()
void breaking_junk_appendGfx (void * effect)
Referenced by breaking_junk_render().
breaking_junk_init()
void breaking_junk_init (EffectInstance * effect)
Referenced by breaking_junk_main().
breaking_junk_main()
EffectInstance * breaking_junk_main (s32 arg0, f32 x, f32 y, f32 z, f32 scale, s32 time)
breaking_junk_render()
void breaking_junk_render (EffectInstance * effect)
Referenced by breaking_junk_main().
breaking_junk_update()
void breaking_junk_update (EffectInstance * effect)
Referenced by breaking_junk_main().
Variable Documentation
D_09000400_403FF0
Gfx D_09000400_403FF0[] extern
D_090005A8_404198
Gfx D_090005A8_404198[] extern
D_090005C8_4041B8
Gfx D_090005C8_4041B8[] extern
D_090005E8_4041D8
Gfx D_090005E8_4041D8[] extern
D_09000608_4041F8
Gfx D_09000608_4041F8[] extern
D_E01187B0
Gfx* D_E01187B0[] = { D_090005A8_404198, D_090005C8_4041B8, D_090005E8_4041D8, D_09000608_4041F8 }
Referenced by breaking_junk_appendGfx().
D_E01187C0
Gfx* D_E01187C0[] = { D_09000400_403FF0 }
Referenced by breaking_junk_appendGfx().