papermario: src/battle/action_cmd/break_free.h File Reference
break_free.h File Reference
Functions
void action_command_break_free_update (void)
void action_command_break_free_draw (void)
void action_command_break_free_free (void)
Function Documentation
action_command_break_free_draw()
void action_command_break_free_draw (void)
Referenced by action_command_draw().
action_command_break_free_free()
void action_command_break_free_free (void)
Referenced by action_command_free().
action_command_break_free_update()
void action_command_break_free_update (void)
Referenced by action_command_update().