papermario: src/battle/btl_states_actions.c File Reference
btl_states_actions.c File Reference
Functions
b32 dispatch_damage_tick_event_player (s32 damageAmount, s32 event)
void btl_merlee_on_start_turn (void)
void btl_merlee_on_first_strike (void)
void btl_set_state (s32 battleState)
void btl_state_update_normal_start (void)
void btl_state_draw_normal_start (void)
void btl_state_update_begin_turn (void)
void btl_state_draw_begin_turn (void)
void btl_state_update_begin_player_turn (void)
void btl_state_draw_begin_player_turn (void)
void btl_state_update_switch_to_player (void)
void btl_state_draw_switch_to_player (void)
void btl_state_update_begin_partner_turn (void)
void btl_state_draw_begin_partner_turn (void)
void btl_state_update_switch_to_partner (void)
void btl_state_draw_switch_to_partner (void)
void btl_state_update_9 (void)
void btl_state_draw_9 (void)
void btl_state_update_prepare_menu (void)
void btl_state_draw_prepare_menu (void)
void btl_state_update_end_turn (void)
void btl_state_draw_end_turn (void)
void btl_state_update_1C (void)
void btl_state_draw_1C (void)
void btl_state_update_victory (void)
void btl_state_draw_victory (void)
void btl_state_update_end_training_battle (void)
void btl_state_draw_end_training_battle (void)
void btl_state_update_end_battle (void)
void btl_state_draw_end_battle (void)
void btl_state_update_defend (void)
void btl_state_draw_defend (void)
void btl_state_update_run_away (void)
void btl_state_draw_run_away (void)
void btl_state_update_defeat (void)
void btl_state_draw_defeat (void)
void btl_state_update_change_partner (void)
void btl_state_draw_change_partner (void)
void btl_state_update_player_move (void)
void btl_state_draw_player_move (void)
void btl_state_update_end_player_turn (void)
void btl_state_draw_end_player_turn (void)
void btl_state_update_partner_move (void)
void btl_state_draw_partner_move (void)
void btl_state_update_end_partner_turn (void)
void btl_state_draw_end_partner_turn (void)
void btl_state_update_next_enemy (void)
void btl_state_draw_next_enemy (void)
void btl_state_update_enemy_move (void)
void btl_state_draw_enemy_move (void)
void btl_state_update_first_strike (void)
void btl_state_draw_first_stike (void)
void btl_state_update_partner_striking_first (void)
void btl_state_draw_partner_striking_first (void)
void btl_state_update_enemy_striking_first (void)
void btl_state_draw_enemy_striking_first (void)
void btl_state_update_end_demo_battle (void)
void btl_state_draw_end_demo_battle (void)
Variables
StageListRow * gCurrentStagePtr
s16 D_802809F6
s16 DemoBattleBeginDelay
s32 BattleScreenFadeAmt
EvtScript EVS_OnBattleInit
s32 bActorsIgnoreDuringCount []
EvtScript EVS_Mario_OnActorCreate
EvtScript EVS_Peach_OnActorCreate
BSS s32 BattleEnemiesCreated
BSS u8 D_8029F244
BSS s32 BattleSubStateDelay
BSS s32 D_8029F24C
BSS s32 RunAwayRewardStep
BSS b32 D_8029F254
BSS s32 D_8029F258
BSS s32 RunAwayRewardTotal
BSS s32 RunAwayRewardIncrement
BSS s32 D_8029F264
ShapeFile gMapShapeData
Function Documentation
btl_merlee_on_first_strike()
void btl_merlee_on_first_strike (void)
Referenced by btl_state_update_first_strike().
btl_merlee_on_start_turn()
void btl_merlee_on_start_turn (void)
Referenced by btl_state_update_begin_turn().
btl_set_state()
void btl_set_state (s32 battleState)
Referenced by btl_check_enemies_defeated(), btl_check_player_defeated(), btl_state_update_1C(), btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_begin_turn(), btl_state_update_celebration(), btl_state_update_change_partner(), btl_state_update_defeat(), btl_state_update_defend(), btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_end_partner_turn(), btl_state_update_end_player_turn(), btl_state_update_end_training_battle(), btl_state_update_end_turn(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_next_enemy(), btl_state_update_normal_start(), btl_state_update_partner_menu(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_peach_menu(), btl_state_update_player_menu(), btl_state_update_player_move(), btl_state_update_prepare_menu(), btl_state_update_run_away(), btl_state_update_select_target(), btl_state_update_switch_to_partner(), btl_state_update_switch_to_player(), btl_state_update_twink_menu(), btl_state_update_victory(), btl_update(), and load_battle_section().
btl_state_draw_1C()
void btl_state_draw_1C (void)
Referenced by btl_draw_ui().
btl_state_draw_9()
void btl_state_draw_9 (void)
Referenced by btl_draw_ui().
btl_state_draw_begin_partner_turn()
void btl_state_draw_begin_partner_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_begin_player_turn()
void btl_state_draw_begin_player_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_begin_turn()
void btl_state_draw_begin_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_change_partner()
void btl_state_draw_change_partner (void)
Referenced by btl_draw_ui().
btl_state_draw_defeat()
void btl_state_draw_defeat (void)
Referenced by btl_draw_ui().
btl_state_draw_defend()
void btl_state_draw_defend (void)
Referenced by btl_draw_ui().
btl_state_draw_end_battle()
void btl_state_draw_end_battle (void)
Referenced by btl_draw_ui().
btl_state_draw_end_demo_battle()
void btl_state_draw_end_demo_battle (void)
Referenced by btl_draw_ui().
btl_state_draw_end_partner_turn()
void btl_state_draw_end_partner_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_end_player_turn()
void btl_state_draw_end_player_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_end_training_battle()
void btl_state_draw_end_training_battle (void)
Referenced by btl_draw_ui().
btl_state_draw_end_turn()
void btl_state_draw_end_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_enemy_move()
void btl_state_draw_enemy_move (void)
Referenced by btl_draw_ui().
btl_state_draw_enemy_striking_first()
void btl_state_draw_enemy_striking_first (void)
Referenced by btl_draw_ui().
btl_state_draw_first_stike()
void btl_state_draw_first_stike (void)
Referenced by btl_draw_ui().
btl_state_draw_next_enemy()
void btl_state_draw_next_enemy (void)
Referenced by btl_draw_ui().
btl_state_draw_normal_start()
void btl_state_draw_normal_start (void)
Referenced by btl_draw_ui().
btl_state_draw_partner_move()
void btl_state_draw_partner_move (void)
Referenced by btl_draw_ui().
btl_state_draw_partner_striking_first()
void btl_state_draw_partner_striking_first (void)
Referenced by btl_draw_ui().
btl_state_draw_player_move()
void btl_state_draw_player_move (void)
Referenced by btl_draw_ui().
btl_state_draw_prepare_menu()
void btl_state_draw_prepare_menu (void)
Referenced by btl_draw_ui().
btl_state_draw_run_away()
void btl_state_draw_run_away (void)
Referenced by btl_draw_ui().
btl_state_draw_switch_to_partner()
void btl_state_draw_switch_to_partner (void)
Referenced by btl_draw_ui().
btl_state_draw_switch_to_player()
void btl_state_draw_switch_to_player (void)
Referenced by btl_draw_ui().
btl_state_draw_victory()
void btl_state_draw_victory (void)
Referenced by btl_draw_ui().
btl_state_update_1C()
void btl_state_update_1C (void)
Referenced by btl_update().
btl_state_update_9()
void btl_state_update_9 (void)
Referenced by btl_update().
btl_state_update_begin_partner_turn()
void btl_state_update_begin_partner_turn (void)
Referenced by btl_update().
btl_state_update_begin_player_turn()
void btl_state_update_begin_player_turn (void)
Referenced by btl_update().
btl_state_update_begin_turn()
void btl_state_update_begin_turn (void)
Referenced by btl_update().
btl_state_update_change_partner()
void btl_state_update_change_partner (void)
Referenced by btl_update().
btl_state_update_defeat()
void btl_state_update_defeat (void)
Referenced by btl_update().
btl_state_update_defend()
void btl_state_update_defend (void)
Referenced by btl_update().
btl_state_update_end_battle()
void btl_state_update_end_battle (void)
Referenced by btl_update().
btl_state_update_end_demo_battle()
void btl_state_update_end_demo_battle (void)
Referenced by btl_update().
btl_state_update_end_partner_turn()
void btl_state_update_end_partner_turn (void)
Referenced by btl_update().
btl_state_update_end_player_turn()
void btl_state_update_end_player_turn (void)
Referenced by btl_update().
btl_state_update_end_training_battle()
void btl_state_update_end_training_battle (void)
Referenced by btl_update().
btl_state_update_end_turn()
void btl_state_update_end_turn (void)
Referenced by btl_update().
btl_state_update_enemy_move()
void btl_state_update_enemy_move (void)
Referenced by btl_update().
btl_state_update_enemy_striking_first()
void btl_state_update_enemy_striking_first (void)
Referenced by btl_update().
btl_state_update_first_strike()
void btl_state_update_first_strike (void)
Referenced by btl_update().
btl_state_update_next_enemy()
void btl_state_update_next_enemy (void)
Referenced by btl_update().
btl_state_update_normal_start()
void btl_state_update_normal_start (void)
Referenced by btl_update().
btl_state_update_partner_move()
void btl_state_update_partner_move (void)
Referenced by btl_update().
btl_state_update_partner_striking_first()
void btl_state_update_partner_striking_first (void)
Referenced by btl_update().
btl_state_update_player_move()
void btl_state_update_player_move (void)
Referenced by btl_update().
btl_state_update_prepare_menu()
void btl_state_update_prepare_menu (void)
Referenced by btl_update().
btl_state_update_run_away()
void btl_state_update_run_away (void)
Referenced by btl_update().
btl_state_update_switch_to_partner()
void btl_state_update_switch_to_partner (void)
Referenced by btl_update().
btl_state_update_switch_to_player()
void btl_state_update_switch_to_player (void)
Referenced by btl_update().
btl_state_update_victory()
void btl_state_update_victory (void)
Referenced by btl_update().
dispatch_damage_tick_event_player()
b32 dispatch_damage_tick_event_player (s32 damageAmount, s32 event)
Referenced by btl_state_update_begin_player_turn().
Variable Documentation
bActorsIgnoreDuringCount
s32 bActorsIgnoreDuringCount[] extern
Referenced by btl_state_update_normal_start().
BattleEnemiesCreated
BSS s32 BattleEnemiesCreated
Referenced by btl_state_update_normal_start().
BattleScreenFadeAmt
s32 BattleScreenFadeAmt extern
Referenced by btl_state_draw_end_battle(), btl_state_draw_end_demo_battle(), btl_state_draw_enemy_striking_first(), btl_state_draw_first_stike(), btl_state_draw_normal_start(), btl_state_draw_partner_striking_first(), btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_normal_start(), and btl_state_update_run_away().
BattleSubStateDelay
BSS s32 BattleSubStateDelay
Referenced by btl_state_update_change_partner(), btl_state_update_end_training_battle(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_normal_start(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), btl_state_update_run_away(), and btl_state_update_victory().
D_802809F6
s16 D_802809F6 extern
Referenced by btl_state_draw_end_demo_battle(), btl_state_draw_first_stike(), btl_state_update_end_demo_battle(), and btl_update().
D_8029F244
BSS u8 D_8029F244
Referenced by btl_state_update_next_enemy().
D_8029F24C
BSS s32 D_8029F24C
Referenced by btl_state_update_run_away().
D_8029F254
BSS b32 D_8029F254
Referenced by btl_state_draw_enemy_striking_first(), btl_state_draw_first_stike(), btl_state_draw_partner_striking_first(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_partner_striking_first(), and btl_state_update_victory().
D_8029F258
BSS s32 D_8029F258
Referenced by btl_state_update_9(), btl_state_update_begin_partner_turn(), and btl_state_update_begin_player_turn().
D_8029F264
BSS s32 D_8029F264
Referenced by btl_state_update_run_away().
DemoBattleBeginDelay
s16 DemoBattleBeginDelay extern
Referenced by btl_state_update_end_demo_battle().
EVS_Mario_OnActorCreate
EvtScript EVS_Mario_OnActorCreate extern
Referenced by btl_state_update_normal_start().
EVS_OnBattleInit
EvtScript EVS_OnBattleInit extern
Referenced by btl_state_update_normal_start().
EVS_Peach_OnActorCreate
EvtScript EVS_Peach_OnActorCreate extern
Referenced by btl_state_update_normal_start().
gCurrentStagePtr
StageListRow* gCurrentStagePtr extern
Referenced by btl_state_update_end_battle(), btl_state_update_end_demo_battle(), and btl_state_update_normal_start().
gMapShapeData
ShapeFile gMapShapeData extern
Referenced by btl_state_update_normal_start().
RunAwayRewardIncrement
BSS s32 RunAwayRewardIncrement
Referenced by btl_state_update_run_away().
RunAwayRewardStep
BSS s32 RunAwayRewardStep
Referenced by btl_state_update_run_away().
RunAwayRewardTotal
BSS s32 RunAwayRewardTotal
Referenced by btl_state_update_run_away().