papermario: src/effects/bulb_glow.c File Reference
bulb_glow.c File Reference
Data Structures
struct UnkBulbGlow
Macros
#define TMEM_ADDR(x) (x / sizeof(u64))
Functions
void bulb_glow_init (EffectInstance *effect)
void bulb_glow_update (EffectInstance *effect)
void bulb_glow_render (EffectInstance *effect)
void bulb_glow_appendGfx (void *effect)
void bulb_glow_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, EffectInstance **outEffect)
void func_E0078274 (void)
Variables
Gfx D_09001400_37C1D0 []
Gfx D_090014B8_37C288 []
Gfx D_09001570_37C340 []
Gfx D_09001618_37C3E8 []
Gfx D_090016C0_37C490 []
Gfx * D_E0078900 []
UnkBulbGlow D_E0078918 []
s32 D_E00789A8 = 0
Color_RGB8 D_E00789AC []
Data Structure Documentation
UnkBulbGlow
struct UnkBulbGlow
Data Fields
s32 unk_00
s32 unk_04
f32 unk_08
f32 unk_0C
s32 unk_10
s32 unk_14
Macro Definition Documentation
TMEM_ADDR
#define TMEM_ADDR (x) (x / sizeof(u64))
Referenced by bulb_glow_appendGfx().
Function Documentation
bulb_glow_appendGfx()
void bulb_glow_appendGfx (void * effect)
Referenced by bulb_glow_render().
bulb_glow_init()
void bulb_glow_init (EffectInstance * effect)
Referenced by bulb_glow_main().
bulb_glow_main()
void bulb_glow_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, EffectInstance ** outEffect)
Referenced by lightning_main().
bulb_glow_render()
void bulb_glow_render (EffectInstance * effect)
Referenced by bulb_glow_main().
bulb_glow_update()
void bulb_glow_update (EffectInstance * effect)
Referenced by bulb_glow_main().
func_E0078274()
void func_E0078274 (void)
Variable Documentation
D_09001400_37C1D0
Gfx D_09001400_37C1D0[] extern
D_090014B8_37C288
Gfx D_090014B8_37C288[] extern
D_09001570_37C340
Gfx D_09001570_37C340[] extern
D_09001618_37C3E8
Gfx D_09001618_37C3E8[] extern
D_090016C0_37C490
Gfx D_090016C0_37C490[] extern
D_E0078900
Gfx* D_E0078900[]
Initial value:
= {
    D_09001400_37C1D0, D_090014B8_37C288, D_09001570_37C340, D_09001618_37C3E8, D_090016C0_37C490, D_09001570_37C340
}
Referenced by bulb_glow_appendGfx().
D_E0078918
UnkBulbGlow D_E0078918[]
Initial value:
= {
    { 0x00000080, 0x00000080, 0.5f, 0.5f, 0x00000040, 0x00000004 },
    { 0x00000040, 0x00000040, 2.0f, 2.0f, 0x00000020, 0x00000010 },
    { 0x00000040, 0x00000040, 1.0f, 1.0f, 0x00000040, 0x00000008 },
    { 0x00000040, 0x00000040, 2.0f, 2.0f, 0x00000010, 0x00000010 },
    { 0x00000040, 0x00000040, 1.0f, 1.0f, 0x00000020, 0x00000010 },
    { 0x00000040, 0x00000040, 1.0f, 1.0f, 0x00000040, 0x00000008 },
}
Referenced by bulb_glow_appendGfx().
D_E00789A8
s32 D_E00789A8 = 0
Referenced by bulb_glow_main().
D_E00789AC
Color_RGB8 D_E00789AC[]
Initial value:
= {
    { 255, 255, 255 },
    { 255, 255, 128 },
    { 255, 128, 255 },
    { 128, 255, 255 },
    { 255, 128, 128 },
    { 128, 255, 128 },
    { 128, 128, 255 },
}
Referenced by bulb_glow_appendGfx().