papermario: src/effects/butterflies.c File Reference
butterflies.c File Reference
Functions
void butterflies_init (EffectInstance *effect)
void butterflies_update (EffectInstance *effect)
void butterflies_render (EffectInstance *effect)
void butterflies_appendGfx (void *effect)
EffectInstance * butterflies_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Variables
Vtx D_09002D40_3ADD70 [][6]
Gfx D_09003880_3AE8B0 []
Gfx D_090038F8_3AE928 []
Gfx D_09003968_3AE998 []
Gfx D_090039D8_3AEA08 []
Gfx D_09003A48_3AEA78 []
Gfx D_09003AB8_3AEAE8 []
Gfx D_09003B28_3AEB58 []
Gfx D_09003B98_3AEBC8 []
Gfx D_09003C08_3AEC38 []
Gfx D_09003C78_3AECA8 []
Gfx D_09003CE8_3AED18 []
Gfx D_09003D58_3AED88 []
Gfx D_09003DC8_3AEDF8 []
Gfx * D_E00AA6C0 [11]
s8 D_E00AA6EC []
Function Documentation
butterflies_appendGfx()
void butterflies_appendGfx (void * effect)
Referenced by butterflies_render().
butterflies_init()
void butterflies_init (EffectInstance * effect)
Referenced by butterflies_main().
butterflies_main()
EffectInstance * butterflies_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
butterflies_render()
void butterflies_render (EffectInstance * effect)
Referenced by butterflies_main().
butterflies_update()
void butterflies_update (EffectInstance * effect)
Referenced by butterflies_main().
Variable Documentation
D_09002D40_3ADD70
Vtx D_09002D40_3ADD70[][6] extern
Referenced by butterflies_appendGfx().
D_09003880_3AE8B0
Gfx D_09003880_3AE8B0[] extern
Referenced by butterflies_appendGfx().
D_090038F8_3AE928
Gfx D_090038F8_3AE928[] extern
D_09003968_3AE998
Gfx D_09003968_3AE998[] extern
D_090039D8_3AEA08
Gfx D_090039D8_3AEA08[] extern
D_09003A48_3AEA78
Gfx D_09003A48_3AEA78[] extern
D_09003AB8_3AEAE8
Gfx D_09003AB8_3AEAE8[] extern
D_09003B28_3AEB58
Gfx D_09003B28_3AEB58[] extern
D_09003B98_3AEBC8
Gfx D_09003B98_3AEBC8[] extern
D_09003C08_3AEC38
Gfx D_09003C08_3AEC38[] extern
D_09003C78_3AECA8
Gfx D_09003C78_3AECA8[] extern
D_09003CE8_3AED18
Gfx D_09003CE8_3AED18[] extern
D_09003D58_3AED88
Gfx D_09003D58_3AED88[] extern
D_09003DC8_3AEDF8
Gfx D_09003DC8_3AEDF8[] extern
Referenced by butterflies_appendGfx().
D_E00AA6C0
Gfx* D_E00AA6C0[11]
Initial value:
= {
    D_090038F8_3AE928, D_09003968_3AE998, D_090039D8_3AEA08, D_09003A48_3AEA78, D_09003AB8_3AEAE8, D_09003B28_3AEB58, D_09003B98_3AEBC8, D_09003C08_3AEC38, D_09003C78_3AECA8, D_09003CE8_3AED18, D_09003D58_3AED88
}
Referenced by butterflies_appendGfx().
D_E00AA6EC
s8 D_E00AA6EC[]
Initial value:
= {
    -1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -17, -15, -13, -11, -9, -7, -5, -3, -1, 0, 0, 0, 0, 0, 0, 0, 0
}
Referenced by butterflies_appendGfx().