papermario: src/cam_mode_zone_interp.c File Reference
cam_mode_zone_interp.c File Reference
Enumerations
enum CameraSettingsPtrType { CAMERA_SETTINGS_PTR_MINUS_2 = -2 , CAMERA_SETTINGS_PTR_MINUS_1 = -1 , CAMERA_SETTINGS_PTR_NULL = 0 }
Functions
void interp_lookat_pos (Camera *camera, f32 arg1, f32 arg2, s16 arg3)
void update_unused_lead_amt (Camera *camera)
void func_80030450 (Camera *camera)
CameraControlSettings * test_ray_zone_aabb (f32 x, f32 y, f32 z)
void update_camera_from_controller (Camera *camera, CameraRig *oldConfiguration, CameraControlSettings **prevController, CameraRig *newConfiguration, CameraControlSettings **newController, f32 x1, f32 y1, f32 z1, f32 tX, f32 tY, f32 tZ, s32 changingMap, f32 *interpAlpha, s32 changingZone)
void update_camera_zone_interp (Camera *camera)
Variables
BSS CameraRig CurrentCamRig
BSS f32 D_800A08DC
BSS f32 D_800A08E0
BSS f32 D_800A08E4
BSS f32 D_800A08E8
BSS f32 D_800A08EC
Enumeration Type Documentation
CameraSettingsPtrType
enum CameraSettingsPtrType
Enumerator
CAMERA_SETTINGS_PTR_MINUS_2
CAMERA_SETTINGS_PTR_MINUS_1
CAMERA_SETTINGS_PTR_NULL
Function Documentation
func_80030450()
void func_80030450 (Camera * camera)
Referenced by update_camera_zone_interp().
interp_lookat_pos()
void interp_lookat_pos (Camera * camera, f32 arg1, f32 arg2, s16 arg3)
Referenced by update_camera_unused_leading().
test_ray_zone_aabb()
CameraControlSettings * test_ray_zone_aabb (f32 x, f32 y, f32 z)
Referenced by update_camera_zone_interp().
update_camera_from_controller()
void update_camera_from_controller (Camera * camera, CameraRig * oldConfiguration, CameraControlSettings ** prevController, CameraRig * newConfiguration, CameraControlSettings ** newController, f32 x1, f32 y1, f32 z1, f32 tX, f32 tY, f32 tZ, s32 changingMap, f32 * interpAlpha, s32 changingZone)
Referenced by update_camera_zone_interp().
update_camera_zone_interp()
void update_camera_zone_interp (Camera * camera)
Referenced by update_cameras().
update_unused_lead_amt()
void update_unused_lead_amt (Camera * camera)
Referenced by update_camera_unused_leading().
Variable Documentation
CurrentCamRig
BSS CameraRig CurrentCamRig
Referenced by update_camera_zone_interp().
D_800A08DC
BSS f32 D_800A08DC
Referenced by update_camera_zone_interp().
D_800A08E0
BSS f32 D_800A08E0
Referenced by update_camera_zone_interp().
D_800A08E4
BSS f32 D_800A08E4
Referenced by update_camera_from_controller().
D_800A08E8
BSS f32 D_800A08E8
Referenced by update_camera_from_controller().
D_800A08EC
BSS f32 D_800A08EC
Referenced by update_camera_from_controller().