papermario: src/cam_mode_5.c File Reference
cam_mode_5.c File Reference
Functions
void cam_interp_lookat_pos (Camera *camera, f32 arg1, f32 arg2, s16 arg3)
void func_8003034C (Camera *camera)
void update_camera_mode_5 (Camera *camera)
Function Documentation
cam_interp_lookat_pos()
void cam_interp_lookat_pos (Camera * camera, f32 arg1, f32 arg2, s16 arg3)
Referenced by update_camera_mode_5().
func_8003034C()
void func_8003034C (Camera * camera)
Referenced by update_camera_mode_5().
update_camera_mode_5()
void update_camera_mode_5 (Camera * camera)
Referenced by update_cameras().