papermario: src/evt/cam_api.c File Reference
cam_api.c File Reference
Functions
ApiStatus SetCamEnabled (Evt *script, s32 isInitialCall)
ApiStatus SetCamNoDraw (Evt *script, s32 isInitialCall)
ApiStatus SetCamPerspective (Evt *script, s32 isInitialCall)
ApiStatus func_802CA90C (Evt *script, s32 isInitialCall)
ApiStatus func_802CA988 (Evt *script, s32 isInitialCall)
ApiStatus SetCamViewport (Evt *script, s32 isInitialCall)
ApiStatus func_802CABE8 (Evt *script, s32 isInitialCall)
ApiStatus func_802CACC0 (Evt *script, s32 isInitialCall)
ApiStatus SetCamBGColor (Evt *script, s32 isInitialCall)
ApiStatus func_802CAE50 (Evt *script, s32 isInitialCall)
ApiStatus SetCamTarget (Evt *script, s32 isInitialCall)
ApiStatus InterpCamTargetPos (Evt *script, s32 isInitialCall)
ApiStatus ShakeCam (Evt *script, s32 isInitialCall)
void exec_ShakeCam1 (s32 camID, s32 mode, s32 duration)
void exec_ShakeCamX (s32 camID, s32 mode, s32 duration, f32 magnitude)
ApiStatus SetCamLeadPlayer (Evt *script, s32 isInitialCall)
ApiStatus func_802CB710 (Evt *script, s32 isInitialCall)
ApiStatus PanToTarget (Evt *script, s32 isInitialCall)
ApiStatus UseSettingsFrom (Evt *script, s32 isInitialCall)
ApiStatus LoadSettings (Evt *script, s32 isInitialCall)
ApiStatus SetCamType (Evt *script, s32 isInitialCall)
ApiStatus SetCamPitch (Evt *script, s32 isInitialCall)
ApiStatus SetCamDistance (Evt *script, s32 isInitialCall)
ApiStatus SetCamPosA (Evt *script, s32 isInitialCall)
ApiStatus SetCamPosB (Evt *script, s32 isInitialCall)
ApiStatus SetCamPosC (Evt *script, s32 isInitialCall)
ApiStatus SetPanTarget (Evt *script, s32 isInitialCall)
ApiStatus SetCamSpeed (Evt *script, s32 isInitialCall)
ApiStatus GetCamType (Evt *script, s32 isInitialCall)
ApiStatus GetCamPitch (Evt *script, s32 isInitialCall)
ApiStatus GetCamDistance (Evt *script, s32 isInitialCall)
ApiStatus GetCamPosA (Evt *script, s32 isInitialCall)
ApiStatus GetCamPosB (Evt *script, s32 isInitialCall)
ApiStatus GetCamPosC (Evt *script, s32 isInitialCall)
ApiStatus GetCamPosition (Evt *script, s32 isInitialCall)
ApiStatus WaitForCam (Evt *script, s32 isInitialCall)
ApiStatus SetCamProperties (Evt *script, s32 isInitialCall)
ApiStatus AdjustCam (Evt *script, s32 isInitialCall)
ApiStatus ResetCam (Evt *script, s32 isInitialCall)
Variables
EvtScript ShakeCam1
EvtScript ShakeCamX
Function Documentation
AdjustCam()
ApiStatus AdjustCam (Evt * script, s32 isInitialCall)
exec_ShakeCam1()
void exec_ShakeCam1 (s32 camID, s32 mode, s32 duration)
Referenced by action_update_spin_jump(), action_update_tornado_jump(), get_overriding_player_anim(), and SetPlayerAnimation().
exec_ShakeCamX()
void exec_ShakeCamX (s32 camID, s32 mode, s32 duration, f32 magnitude)
Referenced by action_hammer_play_hit_fx(), action_update_hit_lava(), and entity_HiddenPanel_flip_over().
func_802CA90C()
ApiStatus func_802CA90C (Evt * script, s32 isInitialCall)
func_802CA988()
ApiStatus func_802CA988 (Evt * script, s32 isInitialCall)
func_802CABE8()
ApiStatus func_802CABE8 (Evt * script, s32 isInitialCall)
func_802CACC0()
ApiStatus func_802CACC0 (Evt * script, s32 isInitialCall)
func_802CAE50()
ApiStatus func_802CAE50 (Evt * script, s32 isInitialCall)
func_802CB710()
ApiStatus func_802CB710 (Evt * script, s32 isInitialCall)
GetCamDistance()
ApiStatus GetCamDistance (Evt * script, s32 isInitialCall)
GetCamPitch()
ApiStatus GetCamPitch (Evt * script, s32 isInitialCall)
GetCamPosA()
ApiStatus GetCamPosA (Evt * script, s32 isInitialCall)
GetCamPosB()
ApiStatus GetCamPosB (Evt * script, s32 isInitialCall)
GetCamPosC()
ApiStatus GetCamPosC (Evt * script, s32 isInitialCall)
GetCamPosition()
ApiStatus GetCamPosition (Evt * script, s32 isInitialCall)
GetCamType()
ApiStatus GetCamType (Evt * script, s32 isInitialCall)
InterpCamTargetPos()
ApiStatus InterpCamTargetPos (Evt * script, s32 isInitialCall)
LoadSettings()
ApiStatus LoadSettings (Evt * script, s32 isInitialCall)
PanToTarget()
ApiStatus PanToTarget (Evt * script, s32 isInitialCall)
ResetCam()
ApiStatus ResetCam (Evt * script, s32 isInitialCall)
SetCamBGColor()
ApiStatus SetCamBGColor (Evt * script, s32 isInitialCall)
SetCamDistance()
ApiStatus SetCamDistance (Evt * script, s32 isInitialCall)
SetCamEnabled()
ApiStatus SetCamEnabled (Evt * script, s32 isInitialCall)
SetCamLeadPlayer()
ApiStatus SetCamLeadPlayer (Evt * script, s32 isInitialCall)
SetCamNoDraw()
ApiStatus SetCamNoDraw (Evt * script, s32 isInitialCall)
SetCamPerspective()
ApiStatus SetCamPerspective (Evt * script, s32 isInitialCall)
SetCamPitch()
ApiStatus SetCamPitch (Evt * script, s32 isInitialCall)
SetCamPosA()
ApiStatus SetCamPosA (Evt * script, s32 isInitialCall)
SetCamPosB()
ApiStatus SetCamPosB (Evt * script, s32 isInitialCall)
SetCamPosC()
ApiStatus SetCamPosC (Evt * script, s32 isInitialCall)
SetCamProperties()
ApiStatus SetCamProperties (Evt * script, s32 isInitialCall)
SetCamSpeed()
ApiStatus SetCamSpeed (Evt * script, s32 isInitialCall)
SetCamTarget()
ApiStatus SetCamTarget (Evt * script, s32 isInitialCall)
SetCamType()
ApiStatus SetCamType (Evt * script, s32 isInitialCall)
SetCamViewport()
ApiStatus SetCamViewport (Evt * script, s32 isInitialCall)
SetPanTarget()
ApiStatus SetPanTarget (Evt * script, s32 isInitialCall)
ShakeCam()
ApiStatus ShakeCam (Evt * script, s32 isInitialCall)
UseSettingsFrom()
ApiStatus UseSettingsFrom (Evt * script, s32 isInitialCall)
WaitForCam()
ApiStatus WaitForCam (Evt * script, s32 isInitialCall)
Variable Documentation
ShakeCam1
EvtScript ShakeCam1
Initial value:
= {
    EVT_RETURN
    EVT_END
}
Referenced by exec_ShakeCam1().
ShakeCamX
EvtScript ShakeCamX
Initial value:
= {
    EVT_RETURN
    EVT_END
}
Referenced by exec_ShakeCamX().