papermario: src/battle/camera.c File Reference
camera.c File Reference
Macros
#define LERP(a, b, alpha) ((a) * (alpha) + (b) * (1.0f-(alpha)))
#define CUBIC_SINE_INTERP(alpha) (1.0f - sin_rad(sin_rad(sin_rad((1.0f - alpha) * PI_S / 2) * PI_S / 2) * PI_S / 2))
Functions
s32 CamPresetUpdate_F (Evt *script, s32 isInitialCall)
s32 CamPresetUpdate_M (Evt *script, s32 isInitialCall)
s32 CamPresetUpdate_G (Evt *script, s32 isInitialCall)
s32 CamPresetUpdate_I (Evt *script, s32 isInitialCall)
s32 CamPresetUpdate_H (Evt *script, s32 isInitialCall)
void btl_cam_use_preset_impl (s32 id)
void btl_cam_use_preset_immediately (s32 preset)
void btl_cam_use_preset (s32 preset)
void btl_cam_target_actor (s32 actorID)
void btl_cam_target_actor_part (s32 actorID, s32 actorPartIndex)
void btl_cam_set_params (s16 arg0, s16 boomLength, s16 arg2, s16 boomPitch, s32 boomYaw, s32 boomZOffset, s32 arg6, s32 zoomPercent)
void btl_cam_move (s16 moveTime)
void btl_cam_set_target_pos (f32 x, f32 y, f32 z)
void btl_cam_set_pos (f32 x, f32 y, f32 z)
s32 btl_cam_is_moving_done (void)
void btl_cam_set_zoom (s16 zoom)
void btl_cam_add_zoom (s32 zoom)
void btl_cam_set_zoffset (s16 zOffset)
void btl_cam_unfreeze (void)
void func_8024E60C (void)
Variables
s8 BattleCam_IsFrozen = FALSE
s32 BattleCam_CurrentPresetID = -1
EvtScript CamPreset_B
EvtScript CamPreset_F
EvtScript CamPreset_M
EvtScript CamPreset_G
EvtScript CamPreset_I
EvtScript CamPreset_H
EvtScript CamPreset_N
EvtScript EVS_BattleCam_Default
EvtScript CamPreset_D
EvtScript CamPreset_E
EvtScript CamPreset_J
EvtScript CamPreset_K
EvtScript CamPreset_L
EvtScript CamPreset_A
EvtScript EVS_OnBattleInit
Macro Definition Documentation
CUBIC_SINE_INTERP
#define CUBIC_SINE_INTERP (alpha) (1.0f - sin_rad(sin_rad(sin_rad((1.0f - alpha) * PI_S / 2) * PI_S / 2) * PI_S / 2))
Referenced by CamPresetUpdate_F(), CamPresetUpdate_G(), CamPresetUpdate_H(), CamPresetUpdate_I(), and CamPresetUpdate_M().
LERP
#define LERP (a, b, alpha) ((a) * (alpha) + (b) * (1.0f-(alpha)))
Referenced by CamPresetUpdate_F(), CamPresetUpdate_G(), CamPresetUpdate_H(), CamPresetUpdate_I(), and CamPresetUpdate_M().
Function Documentation
btl_cam_add_zoom()
void btl_cam_add_zoom (s32 zoom)
btl_cam_is_moving_done()
s32 btl_cam_is_moving_done (void)
Referenced by btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), and btl_state_update_celebration().
btl_cam_move()
void btl_cam_move (s16 moveTime)
Referenced by btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_celebration(), btl_state_update_end_player_turn(), btl_state_update_enemy_move(), btl_state_update_partner_move(), btl_state_update_peach_menu(), btl_state_update_player_menu(), btl_state_update_player_move(), and btl_state_update_twink_menu().
btl_cam_set_params()
void btl_cam_set_params (s16 arg0, s16 boomLength, s16 arg2, s16 boomPitch, s32 boomYaw, s32 boomZOffset, s32 arg6, s32 zoomPercent)
Referenced by btl_state_update_celebration().
btl_cam_set_pos()
void btl_cam_set_pos (f32 x, f32 y, f32 z)
btl_cam_set_target_pos()
void btl_cam_set_target_pos (f32 x, f32 y, f32 z)
Referenced by btl_cam_use_preset_impl(), and btl_state_update_change_partner().
btl_cam_set_zoffset()
void btl_cam_set_zoffset (s16 zOffset)
Referenced by btl_state_update_change_partner().
btl_cam_set_zoom()
void btl_cam_set_zoom (s16 zoom)
Referenced by btl_state_update_change_partner().
btl_cam_target_actor()
void btl_cam_target_actor (s32 actorID)
Referenced by btl_state_update_defeat(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), and btl_state_update_run_away().
btl_cam_target_actor_part()
void btl_cam_target_actor_part (s32 actorID, s32 actorPartIndex)
btl_cam_unfreeze()
void btl_cam_unfreeze (void)
Referenced by btl_state_update_end_battle().
btl_cam_use_preset()
void btl_cam_use_preset (s32 preset)
Referenced by btl_state_update_1C(), btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_celebration(), btl_state_update_change_partner(), btl_state_update_defeat(), btl_state_update_end_battle(), btl_state_update_end_player_turn(), btl_state_update_end_training_battle(), btl_state_update_end_turn(), btl_state_update_enemy_move(), btl_state_update_first_strike(), btl_state_update_normal_start(), btl_state_update_partner_menu(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_peach_menu(), btl_state_update_player_menu(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_twink_menu(), btl_state_update_victory(), and CamPresetUpdate_I().
btl_cam_use_preset_immediately()
void btl_cam_use_preset_immediately (s32 preset)
btl_cam_use_preset_impl()
void btl_cam_use_preset_impl (s32 id)
Referenced by btl_cam_use_preset(), and btl_cam_use_preset_immediately().
CamPresetUpdate_F()
s32 CamPresetUpdate_F (Evt * script, s32 isInitialCall)
CamPresetUpdate_G()
s32 CamPresetUpdate_G (Evt * script, s32 isInitialCall)
CamPresetUpdate_H()
s32 CamPresetUpdate_H (Evt * script, s32 isInitialCall)
CamPresetUpdate_I()
s32 CamPresetUpdate_I (Evt * script, s32 isInitialCall)
CamPresetUpdate_M()
s32 CamPresetUpdate_M (Evt * script, s32 isInitialCall)
func_8024E60C()
void func_8024E60C (void)
Variable Documentation
BattleCam_CurrentPresetID
s32 BattleCam_CurrentPresetID = -1
Referenced by btl_cam_use_preset_impl().
BattleCam_IsFrozen
s8 BattleCam_IsFrozen = FALSE
Referenced by btl_cam_add_zoom(), btl_cam_move(), btl_cam_set_params(), btl_cam_set_pos(), btl_cam_set_target_pos(), btl_cam_set_zoffset(), btl_cam_set_zoom(), btl_cam_target_actor(), btl_cam_target_actor_part(), btl_cam_unfreeze(), btl_cam_use_preset(), btl_cam_use_preset_immediately(), and btl_cam_use_preset_impl().
CamPreset_A
EvtScript CamPreset_A
Initial value:
= {
    Call(SetBattleCamPos, 0, 15, 0)
    Call(SetBattleCamParam, AUX_CAM_BOOM_LENGTH, 550)
    Call(SetBattleCamParam, AUX_CAM_PARAM_3, 100)
    Call(SetBattleCamParam, AUX_CAM_BOOM_PITCH, 8)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_B
EvtScript CamPreset_B
Initial value:
= {
    Call(CamPresetUpdate_B)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_D
EvtScript CamPreset_D
Initial value:
= {
    Call(CamPresetUpdate_D)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_E
EvtScript CamPreset_E
Initial value:
= {
    Call(CamPresetUpdate_E)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_F
EvtScript CamPreset_F
Initial value:
= {
    Call(CamPresetUpdate_F)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_G
EvtScript CamPreset_G
Initial value:
= {
    Call(CamPresetUpdate_G)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_H
EvtScript CamPreset_H
Initial value:
= {
    Call(CamPresetUpdate_H)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_I
EvtScript CamPreset_I
Initial value:
= {
    Call(CamPresetUpdate_I)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_J
EvtScript CamPreset_J
Initial value:
= {
    Call(CamPresetUpdate_J)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_K
EvtScript CamPreset_K
Initial value:
= {
    Call(CamPresetUpdate_K)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_L
EvtScript CamPreset_L
Initial value:
= {
    Call(CamPresetUpdate_L)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_M
EvtScript CamPreset_M
Initial value:
= {
    Call(CamPresetUpdate_M)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
CamPreset_N
EvtScript CamPreset_N
Initial value:
= {
    Call(CamPresetUpdate_N)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
EVS_BattleCam_Default
EvtScript EVS_BattleCam_Default
Initial value:
= {
    Call(BattleCamImpl_Default)
    Return
    End
}
Referenced by btl_cam_use_preset_impl().
EVS_OnBattleInit
EvtScript EVS_OnBattleInit
Initial value:
= {
    Call(SetCamPerspective, CAM_BATTLE, CAM_UPDATE_MODE_6, 25, 16, 1024)
    Call(SetCamViewport, CAM_BATTLE, 12, 20, 296, 200)
    Call(SetCamBGColor, CAM_BATTLE, 0, 0, 0)
    Call(SetCamEnabled, CAM_BATTLE, TRUE)
    Wait(1)
    Call(InitVirtualEntityList)
    Call(InitAnimatedModels)
    Call(func_802CABE8, CAM_BATTLE, 0, 240, 100, 8)
    Call(func_802CAE50, CAM_BATTLE, -75, 35, 0)
    Call(BattleCamTargetActor, 0)
    Call(func_8024CE9C)
    Return
    End
}
Referenced by btl_state_update_normal_start().