papermario: include/camera.h File Reference
camera.h File Reference
Functions
void update_camera_minimal (Camera *)
void update_camera_unused_radial (Camera *)
void update_camera_interp_pos (Camera *)
void update_camera_unused_confined (Camera *)
void update_camera_unused_leading (Camera *)
void update_camera_no_interp (Camera *)
void create_camera_leadplayer_matrix (Camera *)
void update_camera_zone_interp (Camera *camera)
Camera * initialize_next_camera (CameraInitData *data)
Variables
f32 CamLengthScale
Function Documentation
create_camera_leadplayer_matrix()
void create_camera_leadplayer_matrix (Camera * camera)
Referenced by update_cameras().
initialize_next_camera()
Camera * initialize_next_camera (CameraInitData * data)
Referenced by create_cameras(), and create_cameras_unused().
update_camera_interp_pos()
void update_camera_interp_pos (Camera * camera)
Referenced by update_cameras().
update_camera_minimal()
void update_camera_minimal (Camera * camera)
Referenced by update_cameras().
update_camera_no_interp()
void update_camera_no_interp (Camera * camera)
Referenced by update_cameras().
update_camera_unused_confined()
void update_camera_unused_confined (Camera * camera)
Referenced by update_cameras().
update_camera_unused_leading()
void update_camera_unused_leading (Camera * camera)
Referenced by update_cameras().
update_camera_unused_radial()
void update_camera_unused_radial (Camera * camera)
Referenced by update_cameras().
update_camera_zone_interp()
void update_camera_zone_interp (Camera * camera)
Referenced by update_cameras().
Variable Documentation
CamLengthScale
f32 CamLengthScale extern
Referenced by create_cameras(), update_camera_interp_pos(), update_camera_minimal(), update_camera_unused_confined(), and update_camera_unused_radial().