papermario: src/effects/chapter_change.c File Reference
chapter_change.c File Reference
Data Structures
struct UnkStruct
Macros
#define X_VAR 128
#define Y_VAR -33
Functions
void chapter_change_init (EffectInstance *effect)
void chapter_change_update (EffectInstance *effect)
void chapter_change_render (EffectInstance *effect)
void chapter_change_appendGfx (void *effect)
void func_E010E000 (ChapterChangeFXData *data, s32 arg1, UnkStruct *arg2)
EffectInstance * chapter_change_main (s32 arg0, f32 posX, f32 posY, f32 arg3, f32 arg4, s32 duration)
Variables
Gfx D_0900BE40_3F7CA0 []
Gfx D_0900BE88_3F7CE8 []
Gfx D_0900BED0_3F7D30 []
Gfx D_0900BF18_3F7D78 []
Gfx D_0900BF60_3F7DC0 []
Gfx D_0900BFA8_3F7E08 []
Gfx D_0900BFF0_3F7E50 []
Gfx D_0900C038_3F7E98 []
Gfx D_0900C080_3F7EE0 []
Gfx D_0900C168_3F7FC8 []
Gfx D_0900C1B0_3F8010 []
Gfx D_0900C1F8_3F8058 []
Gfx D_0900C240_3F80A0 []
Gfx D_0900C328_3F8188 []
Gfx D_0900C370_3F81D0 []
Gfx D_0900C458_3F82B8 []
Gfx D_0900C540_3F83A0 []
s32 D_E010E750 []
UnkStruct D_E010E79C []
UnkStruct D_E010E7D8 []
UnkStruct D_E010E7FC []
UnkStruct D_E010E838 []
UnkStruct D_E010E868 []
Data Structure Documentation
UnkStruct
struct UnkStruct
Data Fields
Gfx * displayList
s16 height
u8 sizeScale
s32 unk_00
u8 unk_00
s8 unk_00
u8 unk_01
s8 unk_01
u8 unk_02
s16 unk_02
u8 unk_03
s32 unk_04
Gfx * unk_04
s16 unk_04
s16 unk_06
f32 unk_08
Gfx * unk_08
s32 unk_08
char unk_09[1]
f32 unk_0C
s32 unk_10
s32 unk_14
s16 width
s16 x
s16 y
Macro Definition Documentation
X_VAR
#define X_VAR 128
Y_VAR
#define Y_VAR -33
Function Documentation
chapter_change_appendGfx()
void chapter_change_appendGfx (void * effect)
Referenced by chapter_change_render().
chapter_change_init()
void chapter_change_init (EffectInstance * effect)
Referenced by chapter_change_main().
chapter_change_main()
EffectInstance * chapter_change_main (s32 arg0, f32 posX, f32 posY, f32 arg3, f32 arg4, s32 duration)
chapter_change_render()
void chapter_change_render (EffectInstance * effect)
Referenced by chapter_change_main().
chapter_change_update()
void chapter_change_update (EffectInstance * effect)
Referenced by chapter_change_main().
func_E010E000()
void func_E010E000 (ChapterChangeFXData * data, s32 arg1, UnkStruct * arg2)
Referenced by chapter_change_appendGfx().
Variable Documentation
D_0900BE40_3F7CA0
Gfx D_0900BE40_3F7CA0[] extern
D_0900BE88_3F7CE8
Gfx D_0900BE88_3F7CE8[] extern
D_0900BED0_3F7D30
Gfx D_0900BED0_3F7D30[] extern
D_0900BF18_3F7D78
Gfx D_0900BF18_3F7D78[] extern
D_0900BF60_3F7DC0
Gfx D_0900BF60_3F7DC0[] extern
D_0900BFA8_3F7E08
Gfx D_0900BFA8_3F7E08[] extern
D_0900BFF0_3F7E50
Gfx D_0900BFF0_3F7E50[] extern
D_0900C038_3F7E98
Gfx D_0900C038_3F7E98[] extern
D_0900C080_3F7EE0
Gfx D_0900C080_3F7EE0[] extern
D_0900C168_3F7FC8
Gfx D_0900C168_3F7FC8[] extern
D_0900C1B0_3F8010
Gfx D_0900C1B0_3F8010[] extern
D_0900C1F8_3F8058
Gfx D_0900C1F8_3F8058[] extern
D_0900C240_3F80A0
Gfx D_0900C240_3F80A0[] extern
D_0900C328_3F8188
Gfx D_0900C328_3F8188[] extern
D_0900C370_3F81D0
Gfx D_0900C370_3F81D0[] extern
D_0900C458_3F82B8
Gfx D_0900C458_3F82B8[] extern
D_0900C540_3F83A0
Gfx D_0900C540_3F83A0[] extern
D_E010E750
s32 D_E010E750[]
Initial value:
= {
    -1,
    MSG_Menus_019D, MSG_Menus_019E, MSG_Menus_019F,
    MSG_Menus_01A0, MSG_Menus_01A1, MSG_Menus_01A2,
    MSG_Menus_01A3, MSG_Menus_01A4, MSG_Menus_019C,
    -1, -1, -1, -1, -1, -1, -1, -1, -1
}
Referenced by chapter_change_main().
D_E010E79C
UnkStruct D_E010E79C[]
Initial value:
= {
    { D_0900C080_3F7EE0, 104,  0, 128, 10 },
    { D_0900C168_3F7FC8, 104, 10, 128, 10 },
    { D_0900C1B0_3F8010, 104, 20, 128, 10 },
    { D_0900C1F8_3F8058, 104, 30, 128, 10 },
    {              NULL,   0,  0,   0,  0 }
}
Referenced by chapter_change_appendGfx().
D_E010E7D8
UnkStruct D_E010E7D8[]
Initial value:
= {
    { D_0900C458_3F82B8, -16, -6, 144, 20 },
    { D_0900C540_3F83A0, -16, 14, 144, 20 },
    {              NULL,   0,  0,   0,  0 }
}
Referenced by chapter_change_appendGfx().
D_E010E7FC
UnkStruct D_E010E7FC[]
Initial value:
= {
    { D_0900C080_3F7EE0, 0, -6, 128, 10 },
    { D_0900C168_3F7FC8, 0,  4, 128, 10 },
    { D_0900C1B0_3F8010, 0, 14, 128, 10 },
    { D_0900C1F8_3F8058, 0, 24, 128, 10 },
    {              NULL, 0,  0,   0,  0 }
}
Referenced by chapter_change_appendGfx().
D_E010E838
UnkStruct D_E010E838[]
Initial value:
= {
    { D_0900C240_3F80A0,   0,  0, 104, 20 },
    { D_0900C328_3F8188,   0, 20, 104, 20 },
    { D_0900C370_3F81D0, 232,  0,  16, 40 },
    {              NULL,   0,  0,   0,  0 }
}
Referenced by chapter_change_appendGfx().
D_E010E868
UnkStruct D_E010E868[]
Initial value:
= {
    { D_0900BE40_3F7CA0,  128 ,  -33 , 64, 64 },
    {              NULL,     0,     0,  0,  0 },
    { D_0900BE88_3F7CE8,  128 ,  -33 , 64, 64 },
    {              NULL,     0,     0,  0,  0 },
    { D_0900BED0_3F7D30,  128 ,  -33 , 64, 64 },
    {              NULL,     0,     0,  0,  0 },
    { D_0900BF18_3F7D78,  128 ,  -33 , 64, 64 },
    {              NULL,     0,     0,  0,  0 },
    { D_0900BF60_3F7DC0,  128 ,  -33 , 64, 64 },
    {              NULL,     0,     0,  0,  0 },
    { D_0900BFA8_3F7E08,  128 ,  -33 , 64, 64 },
    {              NULL,     0,     0,  0,  0 },
    { D_0900BFF0_3F7E50,  128 ,  -33 , 64, 64 },
    {              NULL,     0,     0,  0,  0 },
    { D_0900C038_3F7E98,  128 ,  -33 , 64, 64 },
    {              NULL,     0,     0,  0,  0 }
}
Referenced by chapter_change_appendGfx().