papermario: src/entity/Chest.c File Reference
Chest.c File Reference
Functions
void entity_Chest_adjust_camera (Entity *entity)
void entity_Chest_reset_camera (Entity *entity)
void entity_Chest_setupGfx (s32 entityIndex)
void entity_Chest_check_opened (Entity *entity)
void entity_Chest_idle (Entity *entity)
void entity_Chest_begin_opening (Entity *entity)
void entity_Chest_open (Entity *entity)
void entity_Chest_close (Entity *entity)
void entity_GiantChest_hide_effect (Entity *entity)
void entity_GiantChest_open (Entity *entity)
void entity_GiantChest_give_equipment (Entity *entity)
void entity_Chest_start_bound_script (Entity *entity)
void entity_Chest_enable_player_input (Entity *entity)
void entity_GiantChest_await_got_item (Entity *entity)
void entity_Chest_clear_item_id (Entity *entity)
void entity_Chest_readargs (Entity *entity)
void entity_GiantChest_init (Entity *entity)
void entity_Chest_init (Entity *entity)
Variables
EntityScript Entity_Chest_ScriptOpened
Gfx Entity_Chest_RenderBox []
Gfx Entity_Chest_RenderLid []
Mtx Entity_Chest_LidMtx
EvtScript Entity_Chest_AdjustCam_ISK
EvtScript Entity_Chest_ResetCam_ISK
EvtScript Entity_Chest_AdjustCam_TIK
EvtScript Entity_Chest_AdjustCam_KZN
EvtScript Entity_Chest_ResetCam_Default
EntityScript Entity_GiantChest_Script
EntityScript Entity_Chest_Script
EntityModelScript Entity_Chest_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Chest_RenderBox, RENDER_MODE_SURFACE_OPA)
EntityBlueprint Entity_GiantChest
EntityBlueprint Entity_Chest
Function Documentation
entity_Chest_adjust_camera()
void entity_Chest_adjust_camera (Entity * entity)
entity_Chest_begin_opening()
void entity_Chest_begin_opening (Entity * entity)
entity_Chest_check_opened()
void entity_Chest_check_opened (Entity * entity)
entity_Chest_clear_item_id()
void entity_Chest_clear_item_id (Entity * entity)
entity_Chest_close()
void entity_Chest_close (Entity * entity)
entity_Chest_enable_player_input()
void entity_Chest_enable_player_input (Entity * entity)
entity_Chest_idle()
void entity_Chest_idle (Entity * entity)
entity_Chest_init()
void entity_Chest_init (Entity * entity)
entity_Chest_open()
void entity_Chest_open (Entity * entity)
Referenced by entity_GiantChest_open().
entity_Chest_readargs()
void entity_Chest_readargs (Entity * entity)
Referenced by entity_Chest_init(), and entity_GiantChest_init().
entity_Chest_reset_camera()
void entity_Chest_reset_camera (Entity * entity)
entity_Chest_setupGfx()
void entity_Chest_setupGfx (s32 entityIndex)
Referenced by entity_Chest_init(), and entity_GiantChest_init().
entity_Chest_start_bound_script()
void entity_Chest_start_bound_script (Entity * entity)
entity_GiantChest_await_got_item()
void entity_GiantChest_await_got_item (Entity * entity)
entity_GiantChest_give_equipment()
void entity_GiantChest_give_equipment (Entity * entity)
entity_GiantChest_hide_effect()
void entity_GiantChest_hide_effect (Entity * entity)
entity_GiantChest_init()
void entity_GiantChest_init (Entity * entity)
entity_GiantChest_open()
void entity_GiantChest_open (Entity * entity)
Variable Documentation
Entity_Chest
EntityBlueprint Entity_Chest
Initial value:
= {
    .flags = ENTITY_FLAG_8000 | ENTITY_FLAG_4000,
    .typeDataSize = sizeof(ChestData),
    .renderCommandList = Entity_Chest_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_Chest_init,
    .updateEntityScript = Entity_Chest_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(Chest) },
    .entityType = ENTITY_TYPE_CHEST,
    .aabbSize = { 28, 26, 23 }
}
Entity_Chest_AdjustCam_ISK
EvtScript Entity_Chest_AdjustCam_ISK
Initial value:
= {
    Thread
        Call(GetPlayerPos, LVar0, LVar1, LVar2)
        Call(UseSettingsFrom, 0, -195, -358, -555)
        Call(SetPanTarget, 0, LVar0, LVar1, LVar2)
        Call(SetCamDistance, 0, Float(290.0))
        Call(SetCamPitch, 0, Float(20.0), Float(-10.0))
        Call(SetCamSpeed, 0, Float(8.0))
        Call(PanToTarget, 0, 0, 1)
        Call(WaitForCam, 0, Float(1.0))
    EndThread
    Return
    End
}
Referenced by entity_Chest_adjust_camera().
Entity_Chest_AdjustCam_KZN
EvtScript Entity_Chest_AdjustCam_KZN
Initial value:
= {
    Thread
        Call(AdjustCam, 0, Float(8.0), 0, Float(210.0), Float(21.0), Float(-16.0))
    EndThread
    Return
    End
}
Referenced by entity_Chest_adjust_camera().
Entity_Chest_AdjustCam_TIK
EvtScript Entity_Chest_AdjustCam_TIK
Initial value:
= {
    Thread
        Call(AdjustCam, 0, Float(8.0), 0, Float(300.0), Float(17.5), Float(-9.5))
    EndThread
    Return
    End
}
Referenced by entity_Chest_adjust_camera().
Entity_Chest_LidMtx
Mtx Entity_Chest_LidMtx extern
Referenced by entity_Chest_setupGfx().
Entity_Chest_RenderBox
Gfx Entity_Chest_RenderBox[] extern
Entity_Chest_RenderLid
Gfx Entity_Chest_RenderLid[] extern
Referenced by entity_Chest_setupGfx().
Entity_Chest_RenderScript
EntityModelScript Entity_Chest_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Chest_RenderBox, RENDER_MODE_SURFACE_OPA)
Entity_Chest_ResetCam_Default
EvtScript Entity_Chest_ResetCam_Default
Initial value:
= {
    Thread
        Call(ResetCam, 0, 3)
    EndThread
    Return
    End
}
Referenced by entity_Chest_reset_camera().
Entity_Chest_ResetCam_ISK
EvtScript Entity_Chest_ResetCam_ISK
Initial value:
= {
    Thread
        Call(ResetCam, 0, 3)
    EndThread
    Return
    End
}
Referenced by entity_Chest_reset_camera().
Entity_Chest_Script
EntityScript Entity_Chest_Script
Initial value:
= {
    es_Call(entity_Chest_check_opened)
    es_SetCallback(entity_Chest_idle, 0)
    es_Call(entity_Chest_begin_opening)
    es_Call(entity_Chest_start_bound_script)
    es_Call(entity_Chest_clear_item_id)
    es_SetCallback(entity_Chest_open, 0)
    es_Call(entity_Chest_enable_player_input)
    es_SetCallback(entity_Chest_close, 0)
    es_SetCallback(NULL, 0)
    es_Restart
    es_End
}
Entity_Chest_ScriptOpened
EntityScript Entity_Chest_ScriptOpened
Initial value:
= {
    es_SetCallback(NULL, 0)
    es_End
}
Referenced by entity_Chest_check_opened().
Entity_GiantChest
EntityBlueprint Entity_GiantChest
Initial value:
= {
    .flags = ENTITY_FLAG_4000,
    .typeDataSize = sizeof(ChestData),
    .renderCommandList = Entity_Chest_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_GiantChest_init,
    .updateEntityScript = Entity_GiantChest_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(Chest) },
    .entityType = ENTITY_TYPE_CHEST,
    .aabbSize = { 50, 45, 46 }
}
Entity_GiantChest_Script
EntityScript Entity_GiantChest_Script
Initial value:
= {
    es_Call(entity_Chest_check_opened)
    es_SetCallback(entity_Chest_idle, 0)
    es_Call(entity_Chest_adjust_camera)
    es_Call(entity_GiantChest_give_equipment)
    es_Call(entity_Chest_begin_opening)
    es_SetCallback(entity_GiantChest_open, 0)
    es_Call(entity_Chest_start_bound_script)
    es_SetCallback(entity_GiantChest_await_got_item, 0)
    es_Call(entity_GiantChest_hide_effect)
    es_Call(entity_Chest_reset_camera)
    es_SetCallback(entity_Chest_close, 0)
    es_SetCallback(NULL, 0)
    es_Restart
    es_End
}