papermario: src/effects/chomp_drop.c File Reference
chomp_drop.c File Reference
Functions
void chomp_drop_init (EffectInstance *effect)
void chomp_drop_update (EffectInstance *effect)
void chomp_drop_render (EffectInstance *effect)
void chomp_drop_appendGfx (void *effect)
EffectInstance * chomp_drop_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5, f32 arg6, s32 arg7, f32 arg8, s32 arg9)
EFFECT_DEF_DUST (dust_main)
Variables
Gfx D_09001040_398080 []
Gfx D_090010E8_398128 []
Gfx D_09001190_3981D0 []
Function Documentation
chomp_drop_appendGfx()
void chomp_drop_appendGfx (void * effect)
Referenced by chomp_drop_render().
chomp_drop_init()
void chomp_drop_init (EffectInstance * effect)
Referenced by chomp_drop_main().
chomp_drop_main()
EffectInstance * chomp_drop_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5, f32 arg6, s32 arg7, f32 arg8, s32 arg9)
chomp_drop_render()
void chomp_drop_render (EffectInstance * effect)
Referenced by chomp_drop_main().
chomp_drop_update()
void chomp_drop_update (EffectInstance * effect)
Referenced by chomp_drop_main().
EFFECT_DEF_DUST()
EFFECT_DEF_DUST (dust_main)
Variable Documentation
D_09001040_398080
Gfx D_09001040_398080[] extern
Referenced by chomp_drop_appendGfx().
D_090010E8_398128
Gfx D_090010E8_398128[] extern
Referenced by chomp_drop_appendGfx().
D_09001190_3981D0
Gfx D_09001190_3981D0[] extern
Referenced by chomp_drop_appendGfx().