papermario: src/effects/cloud_puff.c File Reference
cloud_puff.c File Reference
Functions
void cloud_puff_init (EffectInstance *effect)
void cloud_puff_update (EffectInstance *effect)
void cloud_puff_render (EffectInstance *effect)
void cloud_puff_appendGfx (void *effect)
void cloud_puff_main (f32 arg0, f32 arg1, f32 arg2, f32 arg3)
Variables
Gfx D_090000E0_32ED30 []
Gfx D_090001B8_32EE08 []
Function Documentation
cloud_puff_appendGfx()
void cloud_puff_appendGfx (void * effect)
Referenced by cloud_puff_render().
cloud_puff_init()
void cloud_puff_init (EffectInstance * effect)
Referenced by cloud_puff_main().
cloud_puff_main()
void cloud_puff_main (f32 arg0, f32 arg1, f32 arg2, f32 arg3)
cloud_puff_render()
void cloud_puff_render (EffectInstance * effect)
Referenced by cloud_puff_main().
cloud_puff_update()
void cloud_puff_update (EffectInstance * effect)
Referenced by cloud_puff_main().
Variable Documentation
D_090000E0_32ED30
Gfx D_090000E0_32ED30[] extern
Referenced by cloud_puff_appendGfx().
D_090001B8_32EE08
Gfx D_090001B8_32EE08[] extern
Referenced by cloud_puff_appendGfx().