papermario: src/effects/cloud_trail.c File Reference
cloud_trail.c File Reference
Functions
void cloud_trail_init (EffectInstance *effect)
void cloud_trail_update (EffectInstance *effect)
void cloud_trail_render (EffectInstance *effect)
void cloud_trail_appendGfx (void *effect)
void cloud_trail_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Variables
Gfx D_090000E0_32ED30 []
Gfx D_090001B8_32EE08 []
Function Documentation
cloud_trail_appendGfx()
void cloud_trail_appendGfx (void * effect)
Referenced by cloud_trail_render().
cloud_trail_init()
void cloud_trail_init (EffectInstance * effect)
Referenced by cloud_trail_main().
cloud_trail_main()
void cloud_trail_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
cloud_trail_render()
void cloud_trail_render (EffectInstance * effect)
Referenced by cloud_trail_main().
cloud_trail_update()
void cloud_trail_update (EffectInstance * effect)
Referenced by cloud_trail_main().
Variable Documentation
D_090000E0_32ED30
Gfx D_090000E0_32ED30[] extern
Referenced by cloud_trail_appendGfx().
D_090001B8_32EE08
Gfx D_090001B8_32EE08[] extern
Referenced by cloud_trail_appendGfx().