papermario: src/effects/cold_breath.c File Reference
cold_breath.c File Reference
Functions
void cold_breath_init (EffectInstance *effect)
void cold_breath_update (EffectInstance *effect)
void cold_breath_render (EffectInstance *effect)
void cold_breath_appendGfx (void *effect)
EffectInstance * cold_breath_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, s32 duration)
Variables
Gfx D_09002000_3DB100 []
Gfx D_09002200_3DB300 []
Gfx D_09002220_3DB320 []
Gfx D_09002240_3DB340 []
Gfx D_09002260_3DB360 []
Gfx D_09002280_3DB380 []
Gfx D_090022A0_3DB3A0 []
Gfx * D_E00DE810 [][5]
Gfx * D_E00DE84C []
s8 D_E00DE858 []
u8 D_E00DE8B4 []
u8 D_E00DE910 []
u8 D_E00DE96C []
Function Documentation
cold_breath_appendGfx()
void cold_breath_appendGfx (void * effect)
Referenced by cold_breath_render().
cold_breath_init()
void cold_breath_init (EffectInstance * effect)
Referenced by cold_breath_main().
cold_breath_main()
EffectInstance * cold_breath_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, s32 duration)
Referenced by ice_pillar_update(), and snowman_doll_update().
cold_breath_render()
void cold_breath_render (EffectInstance * effect)
Referenced by cold_breath_main().
cold_breath_update()
void cold_breath_update (EffectInstance * effect)
Referenced by cold_breath_main().
Variable Documentation
D_09002000_3DB100
Gfx D_09002000_3DB100[] extern
D_09002200_3DB300
Gfx D_09002200_3DB300[] extern
D_09002220_3DB320
Gfx D_09002220_3DB320[] extern
D_09002240_3DB340
Gfx D_09002240_3DB340[] extern
D_09002260_3DB360
Gfx D_09002260_3DB360[] extern
D_09002280_3DB380
Gfx D_09002280_3DB380[] extern
D_090022A0_3DB3A0
Gfx D_090022A0_3DB3A0[] extern
D_E00DE810
Gfx* D_E00DE810[][5]
Initial value:
= {
    { D_09002200_3DB300, D_09002220_3DB320, D_09002240_3DB340, D_09002260_3DB360, D_09002280_3DB380 },
    { D_09002200_3DB300, D_09002220_3DB320, D_09002240_3DB340, D_09002260_3DB360, D_09002280_3DB380 },
    { D_09002200_3DB300, D_09002220_3DB320, D_09002240_3DB340, D_09002260_3DB360, D_09002280_3DB380 }
}
Referenced by cold_breath_appendGfx().
D_E00DE84C
Gfx* D_E00DE84C[]
Initial value:
= {
    D_09002000_3DB100, D_090022A0_3DB3A0, D_09002000_3DB100
}
Referenced by cold_breath_appendGfx().
D_E00DE858
s8 D_E00DE858[]
Initial value:
= {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xF8, 0xF1, 0xEB, 0xE6, 0xE2, 0xDE, 0xDB, 0xD9, 0xD8, 0xD7,
    0xD6, 0xD5, 0xD4, 0xD3, 0xD2, 0xD1, 0xD0, 0xCF, 0xCE, 0xCD,
    0xCC, 0xCB, 0xCA, 0xC9, 0xC8, 0xC7, 0xC6, 0xC5, 0xC4, 0xC3,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00
}
Referenced by cold_breath_appendGfx().
D_E00DE8B4
u8 D_E00DE8B4[]
Initial value:
= {
    0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F, 0x30, 0x31,
    0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x3B,
    0x3C, 0x3D, 0x3E, 0x3F, 0x40, 0x41, 0x42, 0x43, 0x44, 0x45,
    0x32, 0x32, 0x32, 0x32, 0x32, 0x32, 0x32, 0x32, 0x32, 0x32,
    0x34, 0x37, 0x39, 0x3C, 0x3E, 0x41, 0x43, 0x46, 0x48, 0x4B,
    0x4D, 0x50, 0x52, 0x55, 0x57, 0x5A, 0x5C, 0x5F, 0x61, 0x64,
    0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F, 0x30, 0x31,
    0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x3B,
    0x3C, 0x3D, 0x3E, 0x3F, 0x40, 0x41, 0x42, 0x43, 0x44, 0x45,
    0x00, 0x00
}
Referenced by cold_breath_appendGfx().
D_E00DE910
u8 D_E00DE910[]
Initial value:
= {
    0x00, 0x14, 0x28, 0x3C, 0x50, 0x64, 0x78, 0x8C, 0xA0, 0xB4,
    0xBE, 0xC3, 0xD2, 0xD0, 0xD3, 0xD6, 0xD9, 0xDC, 0xDF, 0xE2,
    0xE5, 0xE8, 0xEB, 0xEE, 0xF1, 0xF4, 0xF7, 0xFA, 0xFD, 0xFF,
    0x00, 0x14, 0x28, 0x3C, 0x50, 0x64, 0x78, 0x8C, 0xA0, 0xB4,
    0xBE, 0xC3, 0xD2, 0xD0, 0xD3, 0xD6, 0xD9, 0xDC, 0xDF, 0xE2,
    0xE5, 0xE8, 0xEB, 0xEE, 0xF1, 0xF4, 0xF7, 0xFA, 0xFD, 0xFF,
    0x00, 0x14, 0x28, 0x3C, 0x50, 0x64, 0x78, 0x8C, 0xA0, 0xB4,
    0xBE, 0xC3, 0xD2, 0xD0, 0xD3, 0xD6, 0xD9, 0xDC, 0xDF, 0xE2,
    0xE5, 0xE8, 0xEB, 0xEE, 0xF1, 0xF4, 0xF7, 0xFA, 0xFD, 0xFF,
    0x00, 0x00
}
Referenced by cold_breath_appendGfx().
D_E00DE96C
u8 D_E00DE96C[]
Initial value:
= {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09,
    0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13,
    0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D,
    0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4,
    0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4,
    0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4, 0xB4,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
Referenced by cold_breath_appendGfx().