papermario: src/collision.c File Reference
collision.c File Reference
Data Structures
struct HitFile
struct ColliderBackupEntry
struct HitFileHeader
struct HitAssetCollider
Functions
s32 collision_heap_create (void)
void * collision_heap_malloc (s32 size)
void collision_heap_free (void *)
void load_hit_data (s32 idx, HitFile *hit)
void _add_hit_vert_to_buffer (Vec3f **buf, Vec3f *vert, s32 *bufSize)
s32 _get_hit_vert_index_from_buffer (Vec3f **buffer, Vec3f *vert, s32 *bufferSize)
void backup_map_collision_data (void)
void func_8005AF84 (void)
void func_8005AF8C (void)
void initialize_collision (void)
void load_map_hit_asset (void)
void restore_map_collision_data (void)
void load_battle_hit_asset (const char *hitName)
void parent_collider_to_model (s16 colliderID, s16 modelIndex)
void update_collider_transform (s16 colliderID)
s32 get_collider_flags (s32 colliderID)
void get_flat_collider_normal (s32 colliderID, f32 *x, f32 *y, f32 *z)
void get_collider_center (s32 colliderID, f32 *x, f32 *y, f32 *z)
s32 test_ray_triangle_general (ColliderTriangle *triangle, Vec3f *vertices)
s32 test_ray_triangle_down (ColliderTriangle *triangle, Vec3f *vertices)
s32 test_ray_triangle_horizontal (ColliderTriangle *triangle, Vec3f *vertices)
s32 test_ray_colliders (s32 ignoreFlags, f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 *hitX, f32 *hitY, f32 *hitZ, f32 *hitDepth, f32 *hitNx, f32 *hitNy, f32 *hitNz)
s32 test_ray_zones (f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 *hitX, f32 *hitY, f32 *hitZ, f32 *hitDepth, f32 *hitNx, f32 *hitNy, f32 *hitNz)
f32 test_ray_collider_horizontal (s32 ignoreFlags, s32 colliderID, f32 x, f32 y, f32 z, f32 length, f32 yaw)
s32 test_ray_entities (f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 *hitX, f32 *hitY, f32 *hitZ, f32 *hitDepth, f32 *hitNx, f32 *hitNy, f32 *hitNz)
Test a general ray from a given starting position and direction against all entities.
Variables
CollisionData gCollisionData
CollisionData gZoneCollisionData
BSS f32 gCollisionRayStartX
BSS f32 gCollisionRayStartY
BSS f32 gCollisionRayStartZ
BSS f32 gCollisionRayDirX
BSS f32 gCollisionRayDirY
BSS f32 gCollisionRayDirZ
BSS f32 gCollisionPointX
BSS f32 gCollisionPointY
BSS f32 gCollisionPointZ
BSS f32 gCollisionRayLength
BSS f32 gCollisionNormalX
BSS f32 gCollisionNormalY
BSS f32 gCollisionNormalZ
BSS ColliderBackupEntry * gCollisionDataBackup
BSS ColliderBackupEntry * gCollisionDataZoneBackup
Vec3s gEntityColliderFaces []
Vec3f gEntityColliderNormals []
Data Structure Documentation
HitFile
struct HitFile
Data Fields
u32 collisionOffset
u32 zoneOffset
ColliderBackupEntry
struct ColliderBackupEntry
Data Fields
s32 flags
char pad_06[2]
s16 parentModelIndex
HitFileHeader
struct HitFileHeader
Data Fields
s16 boundingBoxesDataSize
s32 boundingBoxesOffset
s32 collidersOffset
s16 numColliders
s16 numVertices
char pad_02[2]
char pad_0A[2]
char pad_12[2]
s32 verticesOffset
HitAssetCollider
struct HitAssetCollider
Data Fields
s16 boundingBoxOffset
s16 firstChild
s16 nextSibling
s16 numTriangles
s32 trianglesOffset
Function Documentation
_add_hit_vert_to_buffer()
void _add_hit_vert_to_buffer (Vec3f ** buf, Vec3f * vert, s32 * bufSize)
Referenced by parent_collider_to_model().
_get_hit_vert_index_from_buffer()
s32 _get_hit_vert_index_from_buffer (Vec3f ** buffer, Vec3f * vert, s32 * bufferSize)
Referenced by parent_collider_to_model().
backup_map_collision_data()
void backup_map_collision_data (void)
Referenced by state_step_battle(), state_step_language_select(), and state_step_pause().
collision_heap_create()
s32 collision_heap_create (void)
Referenced by initialize_collision().
collision_heap_free()
void collision_heap_free (void * data)
Referenced by parent_collider_to_model().
collision_heap_malloc()
void * collision_heap_malloc (s32 size)
Referenced by load_hit_data(), and parent_collider_to_model().
func_8005AF84()
void func_8005AF84 (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
func_8005AF8C()
void func_8005AF8C (void)
get_collider_center()
void get_collider_center (s32 colliderID, f32 * x, f32 * y, f32 * z)
get_collider_flags()
s32 get_collider_flags (s32 colliderID)
Referenced by action_update_hit_fire(), action_update_knockback(), action_update_sliding(), action_update_spin_jump(), action_update_step_down(), action_update_tornado_jump(), can_dismount(), check_input_jump(), func_80262130(), handle_floor_behavior(), partner_get_out(), partner_walking_follow_player(), phys_adjust_cam_on_landing(), phys_main_collision_below(), player_handle_floor_collider_type(), spawn_surface_effects(), try_player_footstep_sounds(), update_current_floor(), update_riding_physics(), and update_riding_physics().
get_flat_collider_normal()
void get_flat_collider_normal (s32 colliderID, f32 * x, f32 * y, f32 * z)
initialize_collision()
void initialize_collision (void)
Referenced by load_map_by_IDs(), state_step_demo(), state_step_end_battle(), state_step_exit_language_select(), state_step_intro(), state_step_startup(), and state_step_unpause().
load_battle_hit_asset()
void load_battle_hit_asset (const char * hitName)
Referenced by btl_state_update_normal_start().
load_hit_data()
void load_hit_data (s32 idx, HitFile * hit)
Referenced by load_battle_hit_asset(), and load_map_hit_asset().
load_map_hit_asset()
void load_map_hit_asset (void)
Referenced by load_map_by_IDs(), and restore_map_collision_data().
parent_collider_to_model()
void parent_collider_to_model (s16 colliderID, s16 modelIndex)
Referenced by restore_map_collision_data().
restore_map_collision_data()
void restore_map_collision_data (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
test_ray_collider_horizontal()
f32 test_ray_collider_horizontal (s32 ignoreFlags, s32 colliderID, f32 x, f32 y, f32 z, f32 length, f32 yaw)
test_ray_colliders()
s32 test_ray_colliders (s32 ignoreFlags, f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 * hitX, f32 * hitY, f32 * hitZ, f32 * hitDepth, f32 * hitNx, f32 * hitNy, f32 * hitNz)
Referenced by entity_raycast_down(), npc_raycast_down(), npc_raycast_general(), npc_raycast_up(), npc_raycast_up_corner(), player_raycast_down(), player_raycast_general(), player_raycast_up_corner(), and test_ray_to_wall_center().
test_ray_entities()
s32 test_ray_entities (f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 * hitX, f32 * hitY, f32 * hitZ, f32 * hitDepth, f32 * hitNx, f32 * hitNy, f32 * hitNz)
Test a general ray from a given starting position and direction against all entities.
If one is hit, returns the position and normal of the hit and the length along the ray on the output params. All output params are invalid when a value of NO_COLLIDER is returned.
Parameters
startX origin x position of the ray
startY origin y position of the ray
startZ origin z position of the ray
dirX normalized x direction of the ray
dirY normalized y direction of the ray
dirZ normalized z direction of the ray
[out] hitX normalized x position of the hit
[out] hitY normalized y position of the hit
[out] hitZ normalized z position of the hit
[in,out] hitDepth as input, maximum length of the ray; as output, distance along the ray of the hit
[out] hitNx x normal direction of the hit
[out] hitNy y normal direction of the hit
[out] hitNz z normal direction of the hit
Returns
entity index or NO_COLLIDER is none is hit
Referenced by entity_raycast_down(), npc_raycast_down(), npc_raycast_general(), npc_raycast_up(), npc_raycast_up_corner(), player_raycast_down(), player_raycast_general(), and player_raycast_up_corner().
test_ray_triangle_down()
s32 test_ray_triangle_down (ColliderTriangle * triangle, Vec3f * vertices)
Referenced by test_ray_colliders(), and test_ray_zones().
test_ray_triangle_general()
s32 test_ray_triangle_general (ColliderTriangle * triangle, Vec3f * vertices)
Referenced by test_ray_colliders(), and test_ray_entities().
test_ray_triangle_horizontal()
s32 test_ray_triangle_horizontal (ColliderTriangle * triangle, Vec3f * vertices)
Referenced by test_ray_collider_horizontal(), and test_ray_colliders().
test_ray_zones()
s32 test_ray_zones (f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 * hitX, f32 * hitY, f32 * hitZ, f32 * hitDepth, f32 * hitNx, f32 * hitNy, f32 * hitNz)
Referenced by test_ray_zone(), and test_ray_zone_aabb().
update_collider_transform()
void update_collider_transform (s16 colliderID)
Referenced by restore_map_collision_data().
Variable Documentation
gCollisionData
CollisionData gCollisionData
Referenced by backup_map_collision_data(), get_collider_center(), get_collider_flags(), get_flat_collider_normal(), initialize_collision(), load_battle_hit_asset(), load_hit_data(), modify_collider_family_flags(), parent_collider_to_model(), restore_map_collision_data(), test_ray_collider_horizontal(), test_ray_colliders(), and update_collider_transform().
gCollisionDataBackup
BSS ColliderBackupEntry* gCollisionDataBackup
Referenced by backup_map_collision_data(), and restore_map_collision_data().
gCollisionDataZoneBackup
BSS ColliderBackupEntry* gCollisionDataZoneBackup
Referenced by backup_map_collision_data(), and restore_map_collision_data().
gCollisionNormalX
BSS f32 gCollisionNormalX
Referenced by test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionNormalY
BSS f32 gCollisionNormalY
Referenced by test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionNormalZ
BSS f32 gCollisionNormalZ
Referenced by test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionPointX
BSS f32 gCollisionPointX
Referenced by test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionPointY
BSS f32 gCollisionPointY
Referenced by test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionPointZ
BSS f32 gCollisionPointZ
Referenced by test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionRayDirX
BSS f32 gCollisionRayDirX
Referenced by test_ray_collider_horizontal(), test_ray_colliders(), test_ray_entities(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionRayDirY
BSS f32 gCollisionRayDirY
Referenced by test_ray_collider_horizontal(), test_ray_colliders(), test_ray_entities(), test_ray_triangle_general(), and test_ray_zones().
gCollisionRayDirZ
BSS f32 gCollisionRayDirZ
Referenced by test_ray_collider_horizontal(), test_ray_colliders(), test_ray_entities(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionRayLength
BSS f32 gCollisionRayLength
Referenced by test_ray_collider_horizontal(), test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionRayStartX
BSS f32 gCollisionRayStartX
Referenced by test_ray_collider_horizontal(), test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionRayStartY
BSS f32 gCollisionRayStartY
Referenced by test_ray_collider_horizontal(), test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gCollisionRayStartZ
BSS f32 gCollisionRayStartZ
Referenced by test_ray_collider_horizontal(), test_ray_colliders(), test_ray_entities(), test_ray_triangle_down(), test_ray_triangle_general(), test_ray_triangle_horizontal(), and test_ray_zones().
gEntityColliderFaces
Vec3s gEntityColliderFaces[] extern
Referenced by test_ray_entities().
gEntityColliderNormals
Vec3f gEntityColliderNormals[] extern
Referenced by test_ray_entities().
gZoneCollisionData
CollisionData gZoneCollisionData
Referenced by backup_map_collision_data(), initialize_collision(), load_hit_data(), restore_map_collision_data(), set_zone_enabled(), test_ray_zone(), test_ray_zone_aabb(), and test_ray_zones().