papermario: src/effects/confetti.c File Reference
confetti.c File Reference
Functions
void confetti_init (EffectInstance *effect)
void confetti_update (EffectInstance *effect)
void confetti_render (EffectInstance *effect)
void confetti_appendGfx (void *effect)
void func_E0088000 (ConfettiFXData *part)
EffectInstance * confetti_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_090009E8_38C588 []
Gfx D_09000A00_38C5A0 []
Gfx D_09000940_38C4E0 []
Gfx * D_E0088CC0 []
Color_RGB8 D_E0088CDC []
u8 D_E0088D00 [] = { 0, 1, 2, 3, 2, 1, 0, 0 }
u8 D_E0088D08 [] = { 0, 45, 0, 60 }
Function Documentation
confetti_appendGfx()
void confetti_appendGfx (void * effect)
Referenced by confetti_render().
confetti_init()
void confetti_init (EffectInstance * effect)
Referenced by confetti_main().
confetti_main()
EffectInstance * confetti_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Referenced by explosion_update().
confetti_render()
void confetti_render (EffectInstance * effect)
Referenced by confetti_main().
confetti_update()
void confetti_update (EffectInstance * effect)
Referenced by confetti_main().
func_E0088000()
void func_E0088000 (ConfettiFXData * part)
Referenced by confetti_main(), and confetti_update().
Variable Documentation
D_09000940_38C4E0
Gfx D_09000940_38C4E0[] extern
Referenced by confetti_appendGfx().
D_090009E8_38C588
Gfx D_090009E8_38C588[] extern
D_09000A00_38C5A0
Gfx D_09000A00_38C5A0[] extern
D_E0088CC0
Gfx* D_E0088CC0[]
Initial value:
= {
    D_090009E8_38C588, D_090009E8_38C588, D_090009E8_38C588, D_09000A00_38C5A0,
    D_090009E8_38C588, D_090009E8_38C588, D_090009E8_38C588
}
Referenced by confetti_appendGfx().
D_E0088CDC
Color_RGB8 D_E0088CDC[]
Initial value:
= {
    { 232, 160, 168 },
    { 168,  80,  88 },
    { 160, 168, 232 },
    {  72,  72, 232 },
    { 160, 232, 160 },
    {  96, 176, 120 },
    { 224, 224,  88 },
    { 176, 160,  56 },
    { 232, 160, 232 },
    { 176,  64, 160 },
    { 160, 216, 216 },
    {  88, 168, 168 },
}
Referenced by confetti_appendGfx().
D_E0088D00
u8 D_E0088D00[] = { 0, 1, 2, 3, 2, 1, 0, 0 }
Referenced by confetti_appendGfx().
D_E0088D08
u8 D_E0088D08[] = { 0, 45, 0, 60 }
Referenced by confetti_main().