papermario: src/world/area_end/common/Credits.inc.c File Reference
Credits.inc.c File Reference
Macros
#define CREDITS_MESSAGE_BUFFER_COUNT (23)
Enumerations
enum { CREDITS_LINE_FLAG_1 = 1 , CREDITS_LINE_FLAG_2 = 2 }
enum { CREDITS_LINE_APPEARING = 0 , CREDITS_LINE_HOLDING = 1 , CREDITS_LINE_VANISHING = 2 }
Functions
s32 msg_get_print_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u8 flags)
void msg_get_glyph (s32 font, s32 variation, s32 charIndex, s32 palette, MesasgeFontGlyphData *out)
void dma_load_msg (u32 msgID, void *dest)
void CharAnim_FadeIn_0 (CreditsLine *line, CreditsChar *chr)
void CharAnim_FadeIn_1 (CreditsLine *line, CreditsChar *chr)
void CharAnim_FadeIn_2 (CreditsLine *line, CreditsChar *chr)
void CharAnim_FadeIn_3 (CreditsLine *line, CreditsChar *chr)
void CharAnim_FadeIn_4 (CreditsLine *line, CreditsChar *chr)
void CharAnim_FadeIn_5 (CreditsLine *line, CreditsChar *chr)
void CharAnim_HoldClearImgFX (CreditsLine *line, CreditsChar *chr)
void CharAnim_Hold (CreditsLine *line, CreditsChar *chr)
void CharAnim_FadeOut_0 (CreditsLine *line, CreditsChar *chr)
void CharAnim_FadeOut_1 (CreditsLine *line, CreditsChar *chr)
void CharAnim_FadeOut_2 (CreditsLine *line, CreditsChar *chr)
void CharAnim_FadeOut_3 (CreditsLine *line, CreditsChar *chr)
void credits_update_line (CreditsLine *line)
void credits_worker_render (void)
void credits_load_message (CreditsEntry *entry)
void init_credits (void)
Variables
BSS CreditsData CreditsData
BSS CreditsData * CreditsDataPtr
BSS s32 BSS_PAD_1 [2]
BSS u8 CreditsMessageBuffers [CREDITS_MESSAGE_BUFFER_COUNT][256]
BSS Mtx CreditsProjMatrices [2]
CreditsPairOffset Font4Patterns []
CreditsPairOffset Font3Patterns []
Vp CreditsViewport
s32 CreditsBufferIndex = 0
Macro Definition Documentation
CREDITS_MESSAGE_BUFFER_COUNT
#define CREDITS_MESSAGE_BUFFER_COUNT (23)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CREDITS_LINE_FLAG_1
CREDITS_LINE_FLAG_2
anonymous enum
anonymous enum
Enumerator
CREDITS_LINE_APPEARING
CREDITS_LINE_HOLDING
CREDITS_LINE_VANISHING
Function Documentation
CharAnim_FadeIn_0()
void CharAnim_FadeIn_0 (CreditsLine * line, CreditsChar * chr)
CharAnim_FadeIn_1()
void CharAnim_FadeIn_1 (CreditsLine * line, CreditsChar * chr)
Referenced by credits_update_line().
CharAnim_FadeIn_2()
void CharAnim_FadeIn_2 (CreditsLine * line, CreditsChar * chr)
Referenced by credits_update_line().
CharAnim_FadeIn_3()
void CharAnim_FadeIn_3 (CreditsLine * line, CreditsChar * chr)
Referenced by credits_update_line().
CharAnim_FadeIn_4()
void CharAnim_FadeIn_4 (CreditsLine * line, CreditsChar * chr)
Referenced by credits_update_line().
CharAnim_FadeIn_5()
void CharAnim_FadeIn_5 (CreditsLine * line, CreditsChar * chr)
Referenced by credits_update_line().
CharAnim_FadeOut_0()
void CharAnim_FadeOut_0 (CreditsLine * line, CreditsChar * chr)
CharAnim_FadeOut_1()
void CharAnim_FadeOut_1 (CreditsLine * line, CreditsChar * chr)
Referenced by credits_update_line().
CharAnim_FadeOut_2()
void CharAnim_FadeOut_2 (CreditsLine * line, CreditsChar * chr)
Referenced by credits_update_line().
CharAnim_FadeOut_3()
void CharAnim_FadeOut_3 (CreditsLine * line, CreditsChar * chr)
Referenced by credits_update_line().
CharAnim_Hold()
void CharAnim_Hold (CreditsLine * line, CreditsChar * chr)
Referenced by credits_update_line().
CharAnim_HoldClearImgFX()
void CharAnim_HoldClearImgFX (CreditsLine * line, CreditsChar * chr)
credits_load_message()
void credits_load_message (CreditsEntry * entry)
credits_update_line()
void credits_update_line (CreditsLine * line)
Referenced by credits_worker_render().
credits_worker_render()
void credits_worker_render (void)
Referenced by init_credits().
dma_load_msg()
void dma_load_msg (u32 msgID, void * dest)
Referenced by credits_load_message(), draw_msg(), get_msg_properties(), load_message_to_buffer(), and set_message_text_var().
init_credits()
void init_credits (void)
msg_get_glyph()
void msg_get_glyph (s32 font, s32 variation, s32 charIndex, s32 palette, MesasgeFontGlyphData * out)
Referenced by CharAnim_FadeIn_0(), CharAnim_FadeIn_1(), CharAnim_FadeIn_2(), CharAnim_FadeIn_3(), CharAnim_FadeIn_4(), CharAnim_FadeIn_5(), CharAnim_FadeOut_0(), CharAnim_FadeOut_1(), CharAnim_FadeOut_2(), CharAnim_FadeOut_3(), CharAnim_Hold(), and CharAnim_HoldClearImgFX().
msg_get_print_char_width()
s32 msg_get_print_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u8 flags)
Referenced by credits_update_line(), and get_msg_properties().
Variable Documentation
BSS_PAD_1
BSS s32 BSS_PAD_1[2]
CreditsBufferIndex
s32 CreditsBufferIndex = 0
Referenced by credits_load_message().
CreditsData
BSS CreditsData CreditsData
CreditsDataPtr
BSS CreditsData* CreditsDataPtr
Referenced by credits_load_message(), credits_worker_render(), and init_credits().
CreditsMessageBuffers
BSS u8 CreditsMessageBuffers[CREDITS_MESSAGE_BUFFER_COUNT][256]
Referenced by credits_load_message().
CreditsProjMatrices
BSS Mtx CreditsProjMatrices[2]
Referenced by credits_worker_render().
CreditsViewport
Vp CreditsViewport
Initial value:
= {
    .vp = {
        .vscale = { 640, 480, 511, 0 },
        .vtrans = { 640, 480, 511, 0 }
    }
}
Referenced by credits_worker_render().
Font3Patterns
CreditsPairOffset Font3Patterns[]
Referenced by credits_update_line().
Font4Patterns
CreditsPairOffset Font4Patterns[]
Initial value:
= {
    { .firstChar = 0x02, .secondChar = 0x07, .offset = 1 },
    { .firstChar = 0x02, .secondChar = 0x0A, .offset = 1 },
    { .firstChar = 0x03, .secondChar = 0x04, .offset = 1 },
    { .firstChar = 0x07, .secondChar = 0x0D, .offset = 1 },
    { .firstChar = 0x09, .secondChar = 0x04, .offset = 1 },
    { .firstChar = 0x0C, .secondChar = 0x04, .offset = 1 },
    { .firstChar = 0x0C, .secondChar = 0x0C, .offset = 1 },
    { .firstChar = 0x0C, .secondChar = 0x14, .offset = 1 },
    { .firstChar = 0x0D, .secondChar = 0x03, .offset = 1 },
    { .firstChar = 0x0D, .secondChar = 0x04, .offset = 1 },
    { .firstChar = 0x0D, .secondChar = 0x0A, .offset = 1 },
    { .firstChar = 0x0D, .secondChar = 0x14, .offset = 1 },
    { .firstChar = 0x0E, .secondChar = 0x0D, .offset = 1 },
    { .firstChar = 0x0E, .secondChar = 0x11, .offset = 1 },
    { .firstChar = 0x11, .secondChar = 0x04, .offset = 1 },
    { .firstChar = 0x11, .secondChar = 0x0F, .offset = 1 },
    { .firstChar = 0x14, .secondChar = 0x02, .offset = 1 },
    { .firstChar = 0x14, .secondChar = 0x0D, .offset = 1 },
    { .firstChar = 0x14, .secondChar = 0x0F, .offset = 1 },
    { .firstChar = 0x14, .secondChar = 0x12, .offset = 1 },
    { .firstChar = 0x12, .secondChar = 0x02, .offset = 1 },
    { .firstChar = 0x12, .secondChar = 0x07, .offset = 1 },
    { .firstChar = 0x12, .secondChar = 0x0F, .offset = 1 },
    { .firstChar = 0x15, .secondChar = 0x04, .offset = 1 },
    { .firstChar = 0x16, .secondChar = 0x11, .offset = 1 },
    {}
}
Referenced by credits_update_line().