papermario: src/effects/damage_stars.c File Reference
damage_stars.c File Reference
Functions
void damage_stars_init (EffectInstance *effect)
void damage_stars_update (EffectInstance *effect)
void damage_stars_render (EffectInstance *effect)
void damage_stars_appendGfx (void *effect)
void damage_stars_main (s32 type, f32 x, f32 y, f32 z, f32 rotAxisX, f32 rotAxisY, f32 rotAxisZ, s32 number)
Variables
Gfx D_090004C0_343500 []
Gfx D_090005E0_343620 []
u8 D_E0030E90 []
f32 D_E0030EB4 = 0.0f
Function Documentation
damage_stars_appendGfx()
void damage_stars_appendGfx (void * effect)
Referenced by damage_stars_render().
damage_stars_init()
void damage_stars_init (EffectInstance * effect)
Referenced by damage_stars_main().
damage_stars_main()
void damage_stars_main (s32 type, f32 x, f32 y, f32 z, f32 rotAxisX, f32 rotAxisY, f32 rotAxisZ, s32 number)
damage_stars_render()
void damage_stars_render (EffectInstance * effect)
Referenced by damage_stars_main().
damage_stars_update()
void damage_stars_update (EffectInstance * effect)
Referenced by damage_stars_main().
Variable Documentation
D_090004C0_343500
Gfx D_090004C0_343500[] extern
Referenced by damage_stars_appendGfx().
D_090005E0_343620
Gfx D_090005E0_343620[] extern
Referenced by damage_stars_appendGfx().
D_E0030E90
u8 D_E0030E90[]
Initial value:
= {
    254, 172, 172,
    254, 172, 213,
    254, 180, 154,
    213, 180, 254,
    180, 180, 254,
    180, 221, 254,
    180, 254, 254,
    180, 254, 213,
    180, 254, 180,
    213, 254, 180,
    254, 254, 180,
    254, 213, 172
}
Referenced by damage_stars_appendGfx().
D_E0030EB4
f32 D_E0030EB4 = 0.0f
Referenced by damage_stars_main().