papermario: src/entity/default/Padlock.c File Reference
Padlock.c File Reference
Functions
void entity_Padlock_setupGfx (s32 entityIndex)
void entity_Padlock_push_player (Entity *entity)
void entity_Padlock_idle (Entity *entity)
void entity_Padlock_init (Entity *entity)
void entity_PadlockRedFrame_init (Entity *entity)
void entity_PadlockRedFace_init (Entity *entity)
void entity_PadlockBlueFace_init (Entity *entity)
Variables
Gfx Entity_Padlock_Render []
Gfx Entity_Padlock_RenderShackle []
Mtx Entity_Padlock_mtxShackle
Gfx Entity_PadlockRedFrame_Render []
Gfx Entity_PadlockRedFrame_RenderShackle []
Mtx Entity_PadlockRedFrame_mtxShackle
Gfx Entity_PadlockRedFace_Render []
Gfx Entity_PadlockRedFace_RenderShackle []
Mtx Entity_PadlockRedFace_mtxShackle
Gfx Entity_PadlockBlueFace_Render []
Gfx Entity_PadlockBlueFace_RenderShackle []
Mtx Entity_PadlockBlueFace_mtxShackle
EntityScript Entity_Padlock_Script
EntityModelScript Entity_Padlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Padlock_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_PadlockRedFrame_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PadlockRedFrame_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_PadlockRedFace_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PadlockRedFace_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_PadlockBlueFace_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PadlockBlueFace_Render, RENDER_MODE_SURFACE_OPA)
EntityBlueprint Entity_Padlock
EntityBlueprint Entity_PadlockRedFrame
EntityBlueprint Entity_PadlockRedFace
EntityBlueprint Entity_PadlockBlueFace
Function Documentation
entity_Padlock_idle()
void entity_Padlock_idle (Entity * entity)
entity_Padlock_init()
void entity_Padlock_init (Entity * entity)
entity_Padlock_push_player()
void entity_Padlock_push_player (Entity * entity)
Referenced by entity_Padlock_idle().
entity_Padlock_setupGfx()
void entity_Padlock_setupGfx (s32 entityIndex)
Referenced by entity_Padlock_init(), entity_PadlockBlueFace_init(), entity_PadlockRedFace_init(), and entity_PadlockRedFrame_init().
entity_PadlockBlueFace_init()
void entity_PadlockBlueFace_init (Entity * entity)
entity_PadlockRedFace_init()
void entity_PadlockRedFace_init (Entity * entity)
entity_PadlockRedFrame_init()
void entity_PadlockRedFrame_init (Entity * entity)
Variable Documentation
Entity_Padlock
EntityBlueprint Entity_Padlock
Initial value:
= {
    .flags = ENTITY_FLAG_SHOWS_INSPECT_PROMPT | ENTITY_FLAG_400 | ENTITY_FLAG_HAS_SHADOW,
    .typeDataSize = sizeof(PadlockData),
    .renderCommandList = Entity_Padlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_Padlock_init,
    .updateEntityScript = Entity_Padlock_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(Padlock) },
    .entityType = ENTITY_TYPE_PADLOCK,
    .aabbSize = { 30, 175, 10 }
}
Entity_Padlock_mtxShackle
Mtx Entity_Padlock_mtxShackle extern
Referenced by entity_Padlock_init().
Entity_Padlock_Render
Gfx Entity_Padlock_Render[] extern
Entity_Padlock_RenderScript
EntityModelScript Entity_Padlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Padlock_Render, RENDER_MODE_SURFACE_OPA)
Entity_Padlock_RenderShackle
Gfx Entity_Padlock_RenderShackle[] extern
Referenced by entity_Padlock_init().
Entity_Padlock_Script
EntityScript Entity_Padlock_Script
Initial value:
= {
    es_SetCallback(entity_Padlock_idle, 0)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_PadlockBlueFace
EntityBlueprint Entity_PadlockBlueFace
Initial value:
= {
    .flags = ENTITY_FLAG_SHOWS_INSPECT_PROMPT | ENTITY_FLAG_400 | ENTITY_FLAG_HAS_SHADOW,
    .typeDataSize = sizeof(PadlockData),
    .renderCommandList = Entity_PadlockBlueFace_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_PadlockBlueFace_init,
    .updateEntityScript = Entity_Padlock_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(PadlockBlueFace) },
    .entityType = ENTITY_TYPE_PADLOCK_BLUE_FACE,
    .aabbSize = { 30, 175, 10 }
}
Entity_PadlockBlueFace_mtxShackle
Mtx Entity_PadlockBlueFace_mtxShackle extern
Referenced by entity_PadlockBlueFace_init().
Entity_PadlockBlueFace_Render
Gfx Entity_PadlockBlueFace_Render[] extern
Entity_PadlockBlueFace_RenderScript
EntityModelScript Entity_PadlockBlueFace_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PadlockBlueFace_Render, RENDER_MODE_SURFACE_OPA)
Entity_PadlockBlueFace_RenderShackle
Gfx Entity_PadlockBlueFace_RenderShackle[] extern
Referenced by entity_PadlockBlueFace_init().
Entity_PadlockRedFace
EntityBlueprint Entity_PadlockRedFace
Initial value:
= {
    .flags = ENTITY_FLAG_SHOWS_INSPECT_PROMPT | ENTITY_FLAG_400 | ENTITY_FLAG_HAS_SHADOW,
    .typeDataSize = sizeof(PadlockData),
    .renderCommandList = Entity_PadlockRedFace_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_PadlockRedFace_init,
    .updateEntityScript = Entity_Padlock_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(PadlockRedFace) },
    .entityType = ENTITY_TYPE_PADLOCK_RED_FACE,
    .aabbSize = { 30, 175, 10 }
 }
Entity_PadlockRedFace_mtxShackle
Mtx Entity_PadlockRedFace_mtxShackle extern
Referenced by entity_PadlockRedFace_init().
Entity_PadlockRedFace_Render
Gfx Entity_PadlockRedFace_Render[] extern
Entity_PadlockRedFace_RenderScript
EntityModelScript Entity_PadlockRedFace_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PadlockRedFace_Render, RENDER_MODE_SURFACE_OPA)
Entity_PadlockRedFace_RenderShackle
Gfx Entity_PadlockRedFace_RenderShackle[] extern
Referenced by entity_PadlockRedFace_init().
Entity_PadlockRedFrame
EntityBlueprint Entity_PadlockRedFrame
Initial value:
= {
    .flags = ENTITY_FLAG_SHOWS_INSPECT_PROMPT | ENTITY_FLAG_400 | ENTITY_FLAG_HAS_SHADOW,
    .typeDataSize = sizeof(PadlockData),
    .renderCommandList = Entity_PadlockRedFrame_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_PadlockRedFrame_init,
    .updateEntityScript = Entity_Padlock_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(PadlockRedFrame) },
    .entityType = ENTITY_TYPE_PADLOCK_RED_FRAME,
    .aabbSize = { 30, 175, 10 }
}
Entity_PadlockRedFrame_mtxShackle
Mtx Entity_PadlockRedFrame_mtxShackle extern
Referenced by entity_PadlockRedFrame_init().
Entity_PadlockRedFrame_Render
Gfx Entity_PadlockRedFrame_Render[] extern
Entity_PadlockRedFrame_RenderScript
EntityModelScript Entity_PadlockRedFrame_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_PadlockRedFrame_Render, RENDER_MODE_SURFACE_OPA)
Entity_PadlockRedFrame_RenderShackle
Gfx Entity_PadlockRedFrame_RenderShackle[] extern
Referenced by entity_PadlockRedFrame_init().