papermario: src/entity/default/BoardedFloor.c File Reference
BoardedFloor.c File Reference
Functions
void Entity_BoardedFloor_setupGfx (s32)
void Entity_BoardedFloor_init_fragments (Entity *entity, Gfx **dlists, Mtx *matrices)
void Entity_BoardedFloor_init (Entity *entity)
void Entity_BoardedFloor_update_fragments (Entity *entity)
void Entity_BoardedFloor_idle (Entity *entity)
void Entity_BoardedFloor_shatter (Entity *entity)
Variables
Gfx Entity_RenderNone []
Gfx * Entity_BoardedFloor_FragmentsRender []
Mtx Entity_BoardedFloor_FragmentMatrices []
EntityModelScript Entity_BoardedFloor_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_BoardedFloor_RenderScriptShattered = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_XLU_LAYER1)
EntityModelScript Entity_BoardedFloor_Script
EntityBlueprint Entity_BoardedFloor
Function Documentation
Entity_BoardedFloor_idle()
void Entity_BoardedFloor_idle (Entity * entity)
Entity_BoardedFloor_init()
void Entity_BoardedFloor_init (Entity * entity)
Entity_BoardedFloor_init_fragments()
void Entity_BoardedFloor_init_fragments (Entity * entity, Gfx ** dlists, Mtx * matrices)
Referenced by Entity_BoardedFloor_init().
Entity_BoardedFloor_setupGfx()
void Entity_BoardedFloor_setupGfx (s32 entityIndex)
Referenced by Entity_BoardedFloor_init_fragments().
Entity_BoardedFloor_shatter()
void Entity_BoardedFloor_shatter (Entity * entity)
Entity_BoardedFloor_update_fragments()
void Entity_BoardedFloor_update_fragments (Entity * entity)
Variable Documentation
Entity_BoardedFloor
EntityBlueprint Entity_BoardedFloor
Initial value:
= {
    .flags = 0,
    .typeDataSize = sizeof(BoardedFloorData),
    .renderCommandList = Entity_BoardedFloor_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = Entity_BoardedFloor_init,
    .updateEntityScript = Entity_BoardedFloor_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(BoardedFloor) },
    .entityType = ENTITY_TYPE_BOARDED_FLOOR,
    .aabbSize = { 60, 5, 60 }
}
Entity_BoardedFloor_FragmentMatrices
Mtx Entity_BoardedFloor_FragmentMatrices[] extern
Referenced by Entity_BoardedFloor_init().
Entity_BoardedFloor_FragmentsRender
Gfx* Entity_BoardedFloor_FragmentsRender[] extern
Referenced by Entity_BoardedFloor_init().
Entity_BoardedFloor_RenderScript
EntityModelScript Entity_BoardedFloor_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_OPA)
Entity_BoardedFloor_RenderScriptShattered
EntityModelScript Entity_BoardedFloor_RenderScriptShattered = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_XLU_LAYER1)
Referenced by Entity_BoardedFloor_shatter().
Entity_BoardedFloor_Script
EntityModelScript Entity_BoardedFloor_Script
Initial value:
= {
    es_ClearFlags(ENTITY_FLAG_DISABLE_COLLISION)
    es_SetCallback(Entity_BoardedFloor_idle, 0)
    es_PlaySound(SOUND_BREAK_FLOOR)
    es_SetFlags(ENTITY_FLAG_DISABLE_COLLISION)
    es_Call(Entity_BoardedFloor_shatter)
    es_SetCallback(Entity_BoardedFloor_update_fragments, 0)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_RenderNone
Gfx Entity_RenderNone[] extern