var dir_eb8c049ce469dc9bce8b56fe1e771e33 =
[
    [ "AvoidPlayerAI.inc.c", "AvoidPlayerAI_8inc_8c.html", "AvoidPlayerAI_8inc_8c" ],
    [ "BulletBillAI.inc.c", "BulletBillAI_8inc_8c.html", "BulletBillAI_8inc_8c" ],
    [ "CleftAI.inc.c", "CleftAI_8inc_8c.html", "CleftAI_8inc_8c" ],
    [ "ClubbaNappingAI.inc.c", "ClubbaNappingAI_8inc_8c.html", "ClubbaNappingAI_8inc_8c" ],
    [ "ClubbaPatrolAI.inc.c", "ClubbaPatrolAI_8inc_8c.html", null ],
    [ "FireBarAI.inc.c", "FireBarAI_8inc_8c.html", "FireBarAI_8inc_8c" ],
    [ "FlyingAI.inc.c", "FlyingAI_8inc_8c.html", "FlyingAI_8inc_8c" ],
    [ "FlyingMagikoopaAI.inc.c", "FlyingMagikoopaAI_8inc_8c.html", "FlyingMagikoopaAI_8inc_8c" ],
    [ "FlyingNoAttackAI.inc.c", "FlyingNoAttackAI_8inc_8c.html", "FlyingNoAttackAI_8inc_8c" ],
    [ "GenericHitboxDefeat.inc.c", "GenericHitboxDefeat_8inc_8c.html", "GenericHitboxDefeat_8inc_8c" ],
    [ "GrooveGuyAI.inc.c", "GrooveGuyAI_8inc_8c.html", "GrooveGuyAI_8inc_8c" ],
    [ "GuardAI.inc.c", "GuardAI_8inc_8c.html", "GuardAI_8inc_8c" ],
    [ "HoppingAI.inc.c", "HoppingAI_8inc_8c.html", "HoppingAI_8inc_8c" ],
    [ "KoopaPatrolAI.inc.c", "KoopaPatrolAI_8inc_8c.html", null ],
    [ "LakituAI.inc.c", "LakituAI_8inc_8c.html", "LakituAI_8inc_8c" ],
    [ "MagikoopaAI.inc.c", "MagikoopaAI_8inc_8c.html", "MagikoopaAI_8inc_8c" ],
    [ "MagikoopaSpellAI.inc.c", "MagikoopaSpellAI_8inc_8c.html", "MagikoopaSpellAI_8inc_8c" ],
    [ "MeleeHitbox.inc.c", "MeleeHitbox_8inc_8c.html", "MeleeHitbox_8inc_8c" ],
    [ "MontyMoleAI.inc.c", "MontyMoleAI_8inc_8c.html", "MontyMoleAI_8inc_8c" ],
    [ "ParatroopaAI.inc.c", "ParatroopaAI_8inc_8c.html", "ParatroopaAI_8inc_8c" ],
    [ "PatrolNoAttackAI.inc.c", "PatrolNoAttackAI_8inc_8c.html", "PatrolNoAttackAI_8inc_8c" ],
    [ "PiranhaPlantAI.inc.c", "PiranhaPlantAI_8inc_8c.html", "PiranhaPlantAI_8inc_8c" ],
    [ "ProjectileHitbox.inc.c", "ProjectileHitbox_8inc_8c.html", "ProjectileHitbox_8inc_8c" ],
    [ "RangedAttackAI.inc.c", "RangedAttackAI_8inc_8c.html", null ],
    [ "SentinelAI.inc.c", "SentinelAI_8inc_8c.html", "SentinelAI_8inc_8c" ],
    [ "ShyGuyPatrolAI.inc.c", "ShyGuyPatrolAI_8inc_8c.html", "ShyGuyPatrolAI_8inc_8c" ],
    [ "ShyGuyWanderAI.inc.c", "ShyGuyWanderAI_8inc_8c.html", "ShyGuyWanderAI_8inc_8c" ],
    [ "SpearGuyAI.inc.c", "SpearGuyAI_8inc_8c.html", "SpearGuyAI_8inc_8c" ],
    [ "SpinyAI.inc.c", "SpinyAI_8inc_8c.html", null ],
    [ "States_PatrolAI.inc.c", "States__PatrolAI_8inc_8c.html", "States__PatrolAI_8inc_8c" ],
    [ "States_TackleAI.inc.c", "States__TackleAI_8inc_8c.html", "States__TackleAI_8inc_8c" ],
    [ "StoneChompAI.inc.c", "StoneChompAI_8inc_8c.html", "StoneChompAI_8inc_8c" ],
    [ "SwooperAI.inc.c", "SwooperAI_8inc_8c.html", null ],
    [ "TackleAI.inc.c", "TackleAI_8inc_8c.html", "TackleAI_8inc_8c" ],
    [ "WanderMeleeAI.inc.c", "WanderMeleeAI_8inc_8c.html", "WanderMeleeAI_8inc_8c" ]
];