var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "mapfs", "dir_c76295d25f2ede10a4d3448270e62bc1.html", "dir_c76295d25f2ede10a4d3448270e62bc1" ],
    [ "script_api", "dir_a1f35c589ed3ca78b7671f08df5b6174.html", "dir_a1f35c589ed3ca78b7671f08df5b6174" ],
    [ "camera.h", "camera_8h.html", "camera_8h" ],
    [ "common.h", "common_8h.html", null ],
    [ "common_structs.h", "common__structs_8h.html", "common__structs_8h" ],
    [ "effect_shims.h", "effect__shims_8h.html", "effect__shims_8h" ],
    [ "effects.h", "effects_8h.html", "effects_8h" ],
    [ "effects_internal.h", "effects__internal_8h.html", "effects__internal_8h" ],
    [ "entity.h", "entity_8h.html", "entity_8h" ],
    [ "enums.h", "enums_8h.html", "enums_8h" ],
    [ "evt.h", "evt_8h.html", "evt_8h" ],
    [ "filemenu.h", "filemenu_8h.html", "filemenu_8h" ],
    [ "functions.h", "functions_8h.html", "functions_8h" ],
    [ "gbi_custom.h", "gbi__custom_8h.html", "gbi__custom_8h" ],
    [ "imgfx.h", "imgfx_8h.html", "imgfx_8h" ],
    [ "include_asm.h", "include__asm_8h.html", "include__asm_8h" ],
    [ "include_asset.h", "include__asset_8h.html", "include__asset_8h" ],
    [ "item_entity.h", "item__entity_8h.html", "item__entity_8h" ],
    [ "macro.inc", "macro_8inc.html", null ],
    [ "macros.h", "macros_8h.html", "macros_8h" ],
    [ "map.h", "map_8h.html", "map_8h" ],
    [ "messages.h", "messages_8h.html", "messages_8h" ],
    [ "mips.h", "mips_8h.html", "mips_8h" ],
    [ "model.h", "model_8h.html", "model_8h" ],
    [ "move_addu.inc", "move__addu_8inc.html", null ],
    [ "npc.h", "npc_8h.html", "npc_8h" ],
    [ "overlay.h", "overlay_8h.html", "overlay_8h" ],
    [ "rumble.h", "rumble_8h.html", "rumble_8h" ],
    [ "saved_byte_names.h", "saved__byte__names_8h.html", "saved__byte__names_8h" ],
    [ "saved_flag_names.h", "saved__flag__names_8h.html", "saved__flag__names_8h" ],
    [ "sparkle_script.h", "sparkle__script_8h.html", "sparkle__script_8h" ],
    [ "types.h", "types_8h.html", "types_8h" ],
    [ "ultra64.h", "ultra64_8h.html", null ],
    [ "variables.h", "variables_8h.html", "variables_8h" ]
];