papermario: src/effects/disable_x.c File Reference
disable_x.c File Reference
Functions
void disable_x_init (EffectInstance *effect)
void disable_x_update (EffectInstance *effect)
void disable_x_render (EffectInstance *effect)
void func_E0082528 (EffectInstance *effect)
void func_E00828B4 (EffectInstance *effect)
void func_E0082A84 (EffectInstance *effect)
EffectInstance * disable_x_main (s32 type, f32 x, f32 y, f32 z, s32 arg4)
void func_E0082580 (DisableXFXData *data)
void func_E00826C4 (DisableXFXData *data)
Variables
Gfx D_09002100_3884B0 []
Gfx D_09002198_388548 []
Gfx D_09002230_3885E0 []
Gfx D_09002250_388600 []
Gfx D_09002270_388620 []
Gfx D_09002290_388640 []
Gfx D_090022B0_388660 []
Gfx D_09002320_3886D0 []
Gfx D_09002360_388710 []
Gfx D_090023A0_388750 []
Gfx D_090023E0_388790 []
Gfx D_09002420_3887D0 []
Gfx D_09002460_388810 []
Gfx D_090024A0_388850 []
Gfx D_090024E0_388890 []
Gfx D_09002520_3888D0 []
Gfx D_09002560_388910 []
Gfx D_090025A0_388950 []
Gfx D_090025E0_388990 []
Gfx * D_E0082D00 []
Function Documentation
disable_x_init()
void disable_x_init (EffectInstance * effect)
Referenced by disable_x_main().
disable_x_main()
EffectInstance * disable_x_main (s32 type, f32 x, f32 y, f32 z, s32 arg4)
Referenced by disable_x_update().
disable_x_render()
void disable_x_render (EffectInstance * effect)
Referenced by disable_x_main().
disable_x_update()
void disable_x_update (EffectInstance * effect)
Referenced by disable_x_main().
func_E0082528()
void func_E0082528 (EffectInstance * effect)
Referenced by disable_x_main().
func_E0082580()
void func_E0082580 (DisableXFXData * data)
Referenced by func_E00828B4(), and func_E0082A84().
func_E00826C4()
void func_E00826C4 (DisableXFXData * data)
Referenced by func_E00828B4(), and func_E0082A84().
func_E00828B4()
void func_E00828B4 (EffectInstance * effect)
Referenced by func_E0082528().
func_E0082A84()
void func_E0082A84 (EffectInstance * effect)
Referenced by func_E0082528().
Variable Documentation
D_09002100_3884B0
Gfx D_09002100_3884B0[] extern
Referenced by func_E00828B4().
D_09002198_388548
Gfx D_09002198_388548[] extern
Referenced by func_E00828B4().
D_09002230_3885E0
Gfx D_09002230_3885E0[] extern
Referenced by func_E00828B4().
D_09002250_388600
Gfx D_09002250_388600[] extern
Referenced by func_E0082A84().
D_09002270_388620
Gfx D_09002270_388620[] extern
Referenced by func_E0082A84().
D_09002290_388640
Gfx D_09002290_388640[] extern
Referenced by func_E0082A84().
D_090022B0_388660
Gfx D_090022B0_388660[] extern
Referenced by func_E0082A84().
D_09002320_3886D0
Gfx D_09002320_3886D0[] extern
D_09002360_388710
Gfx D_09002360_388710[] extern
D_090023A0_388750
Gfx D_090023A0_388750[] extern
D_090023E0_388790
Gfx D_090023E0_388790[] extern
D_09002420_3887D0
Gfx D_09002420_3887D0[] extern
D_09002460_388810
Gfx D_09002460_388810[] extern
D_090024A0_388850
Gfx D_090024A0_388850[] extern
D_090024E0_388890
Gfx D_090024E0_388890[] extern
D_09002520_3888D0
Gfx D_09002520_3888D0[] extern
D_09002560_388910
Gfx D_09002560_388910[] extern
D_090025A0_388950
Gfx D_090025A0_388950[] extern
D_090025E0_388990
Gfx D_090025E0_388990[] extern
D_E0082D00
Gfx* D_E0082D00[]
Initial value:
= {
    D_09002320_3886D0, D_09002360_388710, D_090023A0_388750, D_090023E0_388790, D_09002420_3887D0, D_09002460_388810,
    D_090024A0_388850, D_090024E0_388890, D_09002520_3888D0, D_09002560_388910, D_090025A0_388950, D_090025E0_388990
}
Referenced by func_E0082A84().