papermario: src/battle/dmg_partner.c File Reference
dmg_partner.c File Reference
Macros
#define INFLICT_STATUS(STATUS_TYPE)
Functions
s32 dispatch_damage_event_partner_1 (s32, s32)
void dispatch_event_partner (s32 lastEventType)
void dispatch_event_partner_continue_turn (s8 lastEventType)
HitResult calc_partner_test_enemy (void)
HitResult calc_partner_damage_enemy (void)
s32 dispatch_damage_event_partner (s32 damageAmount, s32 event, s32 stopMotion)
s32 dispatch_damage_event_partner_0 (s32 damageAmount, s32 event, s32 stopMotion)
ApiStatus MakeOwnerTargetIndex (Evt *script, s32 isInitialCall)
ApiStatus func_8027FC90 (Evt *script, s32 isInitialCall)
ApiStatus GetActorLevel (Evt *script, s32 isInitialCall)
ApiStatus PartnerDamageEnemy (Evt *script, s32 isInitialCall)
ApiStatus PartnerAfflictEnemy (Evt *script, s32 isInitialCall)
ApiStatus PartnerPowerBounceEnemy (Evt *script, s32 isInitialCall)
ApiStatus PartnerTestEnemy (Evt *script, s32 isInitialCall)
ApiStatus func_8028070C (Evt *script, s32 isInitialCall)
ApiStatus DeletePartner (Evt *script, s32 isInitialCall)
ApiStatus GetPartnerActionSuccess (Evt *script, s32 isInitialCall)
ApiStatus PartnerYieldTurn (Evt *script, s32 isInitialCall)
Seems to be the same functionality as YieldTurn in 1A5830.c.
Macro Definition Documentation
INFLICT_STATUS
#define INFLICT_STATUS (STATUS_TYPE)
Value:
                    if ((battleStatus->curAttackStatus & STATUS_FLAG_##STATUS_TYPE) && \
                        try_inflict_status(target, STATUS_KEY_##STATUS_TYPE, STATUS_TURN_MOD_##STATUS_TYPE)) { \
                        wasSpecialHit = TRUE; \
                        wasStatusInflicted = TRUE; \
                    } \
Function Documentation
calc_partner_damage_enemy()
HitResult calc_partner_damage_enemy (void)
Referenced by func_8027FC90(), PartnerAfflictEnemy(), PartnerDamageEnemy(), and PartnerPowerBounceEnemy().
calc_partner_test_enemy()
HitResult calc_partner_test_enemy (void)
Referenced by PartnerTestEnemy().
DeletePartner()
ApiStatus DeletePartner (Evt * script, s32 isInitialCall)
dispatch_damage_event_partner()
s32 dispatch_damage_event_partner (s32 damageAmount, s32 event, s32 stopMotion)
Referenced by dispatch_damage_event_partner_0(), and dispatch_damage_event_partner_1().
dispatch_damage_event_partner_0()
s32 dispatch_damage_event_partner_0 (s32 damageAmount, s32 event, s32 stopMotion)
Referenced by func_8028070C().
dispatch_damage_event_partner_1()
s32 dispatch_damage_event_partner_1 (s32 damageAmount, s32 event)
Referenced by calc_partner_damage_enemy(), and calc_partner_test_enemy().
dispatch_event_partner()
void dispatch_event_partner (s32 lastEventType)
Referenced by btl_state_update_begin_partner_turn(), btl_state_update_end_training_battle(), btl_state_update_victory(), calc_enemy_damage_target(), dispatch_damage_event_partner(), and dispatch_event_general().
dispatch_event_partner_continue_turn()
void dispatch_event_partner_continue_turn (s8 lastEventType)
func_8027FC90()
ApiStatus func_8027FC90 (Evt * script, s32 isInitialCall)
func_8028070C()
ApiStatus func_8028070C (Evt * script, s32 isInitialCall)
GetActorLevel()
ApiStatus GetActorLevel (Evt * script, s32 isInitialCall)
GetPartnerActionSuccess()
ApiStatus GetPartnerActionSuccess (Evt * script, s32 isInitialCall)
MakeOwnerTargetIndex()
ApiStatus MakeOwnerTargetIndex (Evt * script, s32 isInitialCall)
PartnerAfflictEnemy()
ApiStatus PartnerAfflictEnemy (Evt * script, s32 isInitialCall)
PartnerDamageEnemy()
ApiStatus PartnerDamageEnemy (Evt * script, s32 isInitialCall)
PartnerPowerBounceEnemy()
ApiStatus PartnerPowerBounceEnemy (Evt * script, s32 isInitialCall)
PartnerTestEnemy()
ApiStatus PartnerTestEnemy (Evt * script, s32 isInitialCall)
PartnerYieldTurn()
ApiStatus PartnerYieldTurn (Evt * script, s32 isInitialCall)
Seems to be the same functionality as YieldTurn in 1A5830.c.
YieldTurn copy.