papermario: src/battle/dmg_player.c File Reference
dmg_player.c File Reference
Macros
#define INFLICT_STATUS(STATUS_TYPE)
Functions
b32 dispatch_damage_event_player (s32 damageAmount, s32 event, b32 noHitSound)
b32 dispatch_hazard_event_player (s32 damageAmount, s32 event)
ApiStatus PlaySleepHitFX (Evt *script, s32 isInitialCall)
ApiStatus PlayDizzyHitFX (Evt *script, s32 isInitialCall)
ApiStatus PlayParalyzeHitFX (Evt *script, s32 isInitialCall)
ApiStatus PlayPoisonHitFX (Evt *script, s32 isInitialCall)
ApiStatus PlayStopHitFX (Evt *script, s32 isInitialCall)
ApiStatus PlayFreezeHitSnowflakeFX (Evt *script, s32 isInitialCall)
ApiStatus PlayFreezeHitParticleFX (Evt *script, s32 isInitialCall)
ApiStatus PlayShrinkHitFX (Evt *script, s32 isInitialCall)
void dispatch_event_player (s32 eventType)
void dispatch_event_player_continue_turn (s32 eventType)
HitResult calc_player_test_enemy (void)
HitResult calc_player_damage_enemy (void)
b32 dispatch_damage_tick_event_player (s32 damageAmount, s32 event)
ApiStatus GetMenuSelection (Evt *script, s32 isInitialCall)
ApiStatus func_80273444 (Evt *script, s32 isInitialCall)
ApiStatus PlayerFallToGoal (Evt *script, s32 isInitialCall)
ApiStatus PlayerLandJump (Evt *script, s32 isInitialCall)
ApiStatus PlayerRunToGoal (Evt *script, s32 isInitialCall)
ApiStatus CancelablePlayerRunToGoal (Evt *script, s32 isInitialCall)
ApiStatus GetPlayerHP (Evt *script, s32 isInitialCall)
ApiStatus PlayerDamageEnemy (Evt *script, s32 isInitialCall)
ApiStatus PlayerPowerBounceEnemy (Evt *script, s32 isInitialCall)
ApiStatus PlayerTestEnemy (Evt *script, s32 isInitialCall)
ApiStatus DispatchDamagePlayerEvent (Evt *script, s32 isInitialCall)
ApiStatus EnablePlayerBlur (Evt *script, s32 isInitialCall)
ApiStatus ForceDisablePlayerBlur (Evt *script, s32 isInitialCall)
ApiStatus ForceDisablePlayerBlurImmediately (Evt *script, s32 isInitialCall)
ApiStatus func_80274A18 (Evt *script, s32 isInitialCall)
ApiStatus func_802752AC (Evt *script, s32 isInitialCall)
ApiStatus func_80275F00 (Evt *script, s32 isInitialCall)
ApiStatus GetPlayerActionSuccess (Evt *script, s32 isInitialCall)
ApiStatus PlayerYieldTurn (Evt *script, s32 isInitialCall)
ApiStatus DispatchEventPlayer (Evt *script, s32 isInitialCall)
Variables
EvtScript EVS_PlaySleepHitFX
EvtScript EVS_PlayDizzyHitFX
EvtScript EVS_PlayParalyzeHitFX
EvtScript EVS_PlayPoisonHitFX
EvtScript EVS_PlayStopHitFX
EvtScript EVS_PlayFreezeHitFX
EvtScript EVS_PlayShrinkHitFX
Macro Definition Documentation
INFLICT_STATUS
#define INFLICT_STATUS (STATUS_TYPE)
Value:
                if ((battleStatus->curAttackStatus & STATUS_FLAG_##STATUS_TYPE) && \
                    try_inflict_status(target, STATUS_KEY_##STATUS_TYPE, STATUS_TURN_MOD_##STATUS_TYPE)) { \
                    wasSpecialHit = TRUE; \
                    wasStatusInflicted = TRUE; \
                } \
Function Documentation
calc_player_damage_enemy()
HitResult calc_player_damage_enemy (void)
Referenced by PlayerDamageEnemy(), and PlayerPowerBounceEnemy().
calc_player_test_enemy()
HitResult calc_player_test_enemy (void)
Referenced by PlayerTestEnemy().
CancelablePlayerRunToGoal()
ApiStatus CancelablePlayerRunToGoal (Evt * script, s32 isInitialCall)
dispatch_damage_event_player()
b32 dispatch_damage_event_player (s32 damageAmount, s32 event, b32 noHitSound)
Referenced by dispatch_damage_tick_event_player(), and dispatch_hazard_event_player().
dispatch_damage_tick_event_player()
b32 dispatch_damage_tick_event_player (s32 damageAmount, s32 event)
Referenced by btl_state_update_begin_player_turn(), and DispatchDamagePlayerEvent().
dispatch_event_player()
void dispatch_event_player (s32 eventType)
Referenced by btl_state_update_begin_player_turn(), btl_state_update_end_training_battle(), btl_state_update_victory(), calc_enemy_damage_target(), dispatch_damage_event_player(), dispatch_event_general(), and DispatchEventPlayer().
dispatch_event_player_continue_turn()
void dispatch_event_player_continue_turn (s32 eventType)
dispatch_hazard_event_player()
b32 dispatch_hazard_event_player (s32 damageAmount, s32 event)
Referenced by calc_player_damage_enemy(), and calc_player_test_enemy().
DispatchDamagePlayerEvent()
ApiStatus DispatchDamagePlayerEvent (Evt * script, s32 isInitialCall)
DispatchEventPlayer()
ApiStatus DispatchEventPlayer (Evt * script, s32 isInitialCall)
EnablePlayerBlur()
ApiStatus EnablePlayerBlur (Evt * script, s32 isInitialCall)
ForceDisablePlayerBlur()
ApiStatus ForceDisablePlayerBlur (Evt * script, s32 isInitialCall)
ForceDisablePlayerBlurImmediately()
ApiStatus ForceDisablePlayerBlurImmediately (Evt * script, s32 isInitialCall)
func_80273444()
ApiStatus func_80273444 (Evt * script, s32 isInitialCall)
func_80274A18()
ApiStatus func_80274A18 (Evt * script, s32 isInitialCall)
func_802752AC()
ApiStatus func_802752AC (Evt * script, s32 isInitialCall)
func_80275F00()
ApiStatus func_80275F00 (Evt * script, s32 isInitialCall)
GetMenuSelection()
ApiStatus GetMenuSelection (Evt * script, s32 isInitialCall)
GetPlayerActionSuccess()
ApiStatus GetPlayerActionSuccess (Evt * script, s32 isInitialCall)
GetPlayerHP()
ApiStatus GetPlayerHP (Evt * script, s32 isInitialCall)
PlayDizzyHitFX()
ApiStatus PlayDizzyHitFX (Evt * script, s32 isInitialCall)
PlayerDamageEnemy()
ApiStatus PlayerDamageEnemy (Evt * script, s32 isInitialCall)
PlayerFallToGoal()
ApiStatus PlayerFallToGoal (Evt * script, s32 isInitialCall)
PlayerLandJump()
ApiStatus PlayerLandJump (Evt * script, s32 isInitialCall)
PlayerPowerBounceEnemy()
ApiStatus PlayerPowerBounceEnemy (Evt * script, s32 isInitialCall)
PlayerRunToGoal()
ApiStatus PlayerRunToGoal (Evt * script, s32 isInitialCall)
PlayerTestEnemy()
ApiStatus PlayerTestEnemy (Evt * script, s32 isInitialCall)
PlayerYieldTurn()
ApiStatus PlayerYieldTurn (Evt * script, s32 isInitialCall)
PlayFreezeHitParticleFX()
ApiStatus PlayFreezeHitParticleFX (Evt * script, s32 isInitialCall)
PlayFreezeHitSnowflakeFX()
ApiStatus PlayFreezeHitSnowflakeFX (Evt * script, s32 isInitialCall)
PlayParalyzeHitFX()
ApiStatus PlayParalyzeHitFX (Evt * script, s32 isInitialCall)
PlayPoisonHitFX()
ApiStatus PlayPoisonHitFX (Evt * script, s32 isInitialCall)
PlayShrinkHitFX()
ApiStatus PlayShrinkHitFX (Evt * script, s32 isInitialCall)
PlaySleepHitFX()
ApiStatus PlaySleepHitFX (Evt * script, s32 isInitialCall)
PlayStopHitFX()
ApiStatus PlayStopHitFX (Evt * script, s32 isInitialCall)
Variable Documentation
EVS_PlayDizzyHitFX
EvtScript EVS_PlayDizzyHitFX
Initial value:
= {
    EVT_RETURN
    EVT_END
}
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayFreezeHitFX
EvtScript EVS_PlayFreezeHitFX
Initial value:
= {
    EVT_RETURN
    EVT_END
}
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayParalyzeHitFX
EvtScript EVS_PlayParalyzeHitFX
Initial value:
= {
    EVT_RETURN
    EVT_END
}
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayPoisonHitFX
EvtScript EVS_PlayPoisonHitFX
Initial value:
= {
    EVT_RETURN
    EVT_END
}
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayShrinkHitFX
EvtScript EVS_PlayShrinkHitFX
Initial value:
= {
    EVT_RETURN
    EVT_END
}
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlaySleepHitFX
EvtScript EVS_PlaySleepHitFX
Initial value:
= {
    EVT_RETURN
    EVT_END
}
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayStopHitFX
EvtScript EVS_PlayStopHitFX
Initial value:
= {
    EVT_RETURN
    EVT_END
}
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().