papermario: src/draw_img_util.c File Reference
draw_img_util.c File Reference
Data Structures
struct Rect2b
Functions
s32 draw_image_with_clipping (IMG_PTR raster, u32 width, u32 height, s32 fmt, s32 bitDepth, s16 posX, s16 posY, u16 clipX, u16 clipY, u16 clipWidth, u16 clipHeight)
s32 draw_ci_image_with_clipping (IMG_PTR raster, s32 width, s32 height, s32 fmt, s32 bitDepth, PAL_PTR palette, s16 posX, s16 posY, u16 clipULx, u16 clipULy, u16 clipLRx, u16 clipRLy, u8 opacity)
s32 draw_tiled_image (IMG_PTR raster, u32 width, u32 height, u8 fmt, u8 bitDepth, s16 posX, s16 posY, u16 clipX, u16 clipY, u16 clipWidth, u16 clipHeight, f32 scaleX, f32 scaleY)
s32 integer_log (s32 number, u32 base)
s32 draw_adjustable_tiled_image (IMG_PTR raster, u32 width, u32 height, u8 fmt, u8 bitDepth, s16 posX, s16 posY, u16 clipX, u16 clipY, u16 clipWidth, u16 clipHeight, f32 scaleX, f32 scaleY)
Data Structure Documentation
Rect2b
struct Rect2b
Data Fields
s16 lrx
s16 lry
s16 ulx
s16 uly
Function Documentation
draw_adjustable_tiled_image()
s32 draw_adjustable_tiled_image (IMG_PTR raster, u32 width, u32 height, u8 fmt, u8 bitDepth, s16 posX, s16 posY, u16 clipX, u16 clipY, u16 clipWidth, u16 clipHeight, f32 scaleX, f32 scaleY)
draw_ci_image_with_clipping()
s32 draw_ci_image_with_clipping (IMG_PTR raster, s32 width, s32 height, s32 fmt, s32 bitDepth, PAL_PTR palette, s16 posX, s16 posY, u16 clipULx, u16 clipULy, u16 clipLRx, u16 clipRLy, u8 opacity)
draw_image_with_clipping()
s32 draw_image_with_clipping (IMG_PTR raster, u32 width, u32 height, s32 fmt, s32 bitDepth, s16 posX, s16 posY, u16 clipX, u16 clipY, u16 clipWidth, u16 clipHeight)
Referenced by draw_ci_image_with_clipping().
draw_tiled_image()
s32 draw_tiled_image (IMG_PTR raster, u32 width, u32 height, u8 fmt, u8 bitDepth, s16 posX, s16 posY, u16 clipX, u16 clipY, u16 clipWidth, u16 clipHeight, f32 scaleX, f32 scaleY)
integer_log()
s32 integer_log (s32 number, u32 base)
Referenced by draw_adjustable_tiled_image(), and imgfx_appendGfx_mesh_strip().