papermario: src/effects/dust.c File Reference
dust.c File Reference
Functions
void dust_init (EffectInstance *effect)
void dust_render (EffectInstance *effect)
void dust_update (EffectInstance *effect)
void dust_appendGfx (void *effect)
EffectInstance * dust_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4)
Variables
Gfx D_09000CC0_33FCC0 []
Gfx D_09000D68_33FD68 []
Gfx D_09000E18_33FE18 []
Gfx D_09000E38_33FE38 []
Gfx D_09000E58_33FE58 []
Function Documentation
dust_appendGfx()
void dust_appendGfx (void * effect)
Referenced by dust_render().
dust_init()
void dust_init (EffectInstance * effect)
Referenced by dust_main().
dust_main()
EffectInstance * dust_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4)
Referenced by chomp_drop_update(), and floating_rock_update().
dust_render()
void dust_render (EffectInstance * effect)
Referenced by dust_main().
dust_update()
void dust_update (EffectInstance * effect)
Referenced by dust_main().
Variable Documentation
D_09000CC0_33FCC0
Gfx D_09000CC0_33FCC0[] extern
Referenced by dust_appendGfx().
D_09000D68_33FD68
Gfx D_09000D68_33FD68[] extern
Referenced by dust_appendGfx().
D_09000E18_33FE18
Gfx D_09000E18_33FE18[] extern
Referenced by dust_appendGfx().
D_09000E38_33FE38
Gfx D_09000E38_33FE38[] extern
Referenced by dust_appendGfx().
D_09000E58_33FE58
Gfx D_09000E58_33FE58[] extern
Referenced by dust_appendGfx().