papermario: src/audio/e0b30_len_b80.c File Reference
e0b30_len_b80.c File Reference
Functions
void bgm_update_volume (void)
void bgm_set_target_volume (s16 volume)
s32 bgm_get_map_default_variation (s32 songID)
If the given song ID is present in SongsUsingVariationFlag, returns the current map's songVariation & 1 value.
void bgm_reset_sequence_players (void)
void bgm_reset_volume (void)
void bgm_update_music_settings (void)
s32 _bgm_set_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
s32 bgm_set_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
s32 func_8014A964 (s32 playerIndex, s32 songID, s32 variation, s32 fadeInTime, s16 fadeStartVolume, s16 fadeEndVolume)
s32 bgm_adjust_proximity (s32 playerIndex, s32 mix, s16 state)
AuResult bgm_set_track_volumes (s32 playerIndex, s16 trackVolSet)
AuResult bgm_clear_track_volumes (s32 playerIndex, s16 trackVolSet)
AuResult bgm_set_variation (s32 playerIndex, s16 arg1)
s32 bgm_init_music_players (void)
void bgm_quiet_max_volume (void)
void bgm_reset_max_volume (void)
s32 func_8014AD40 (void)
void bgm_pop_song (void)
void bgm_push_song (s32 songID, s32 variation)
void bgm_pop_battle_song (void)
void bgm_push_battle_song (void)
void bgm_set_battle_song (s32 songID, s32 variation)
void func_8014AFA0 (void)
Variables
BSS s16 MusicDefaultVolume
BSS s16 MusicTargetVolume
BSS s16 MusicMaxVolume
BSS s16 MusicCurrentVolume
MusicSettings gMusicSettings [2]
MusicSettings BlankMusicSettings
s32 SongsUsingVariationFlag []
Lists the songs that are forced to use the variation determined by map.songVariation & 1.
s16 NextVolumeUpdateTimer = 0
Function Documentation
_bgm_set_song()
s32 _bgm_set_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
Referenced by bgm_pop_battle_song(), bgm_pop_song(), and bgm_set_song().
bgm_adjust_proximity()
s32 bgm_adjust_proximity (s32 playerIndex, s32 mix, s16 state)
bgm_clear_track_volumes()
AuResult bgm_clear_track_volumes (s32 playerIndex, s16 trackVolSet)
bgm_get_map_default_variation()
s32 bgm_get_map_default_variation (s32 songID)
If the given song ID is present in SongsUsingVariationFlag, returns the current map's songVariation & 1 value.
Otherwise, returns -1.
See also
SongsUsingVariationFlag
Returns
-1: no override; 0: override to variation 0; 1 override to variation 1
Referenced by _bgm_set_song(), and func_8014A964().
bgm_init_music_players()
s32 bgm_init_music_players (void)
Referenced by state_step_startup().
bgm_pop_battle_song()
void bgm_pop_battle_song (void)
Referenced by update_encounters_post_battle().
bgm_pop_song()
void bgm_pop_song (void)
bgm_push_battle_song()
void bgm_push_battle_song (void)
Referenced by update_encounters_pre_battle().
bgm_push_song()
void bgm_push_song (s32 songID, s32 variation)
bgm_quiet_max_volume()
void bgm_quiet_max_volume (void)
Referenced by state_step_pause().
bgm_reset_max_volume()
void bgm_reset_max_volume (void)
Referenced by state_step_unpause().
bgm_reset_sequence_players()
void bgm_reset_sequence_players (void)
Referenced by load_engine_data().
bgm_reset_volume()
void bgm_reset_volume (void)
Referenced by state_step_startup().
bgm_set_battle_song()
void bgm_set_battle_song (s32 songID, s32 variation)
Referenced by update_encounters_pre_battle().
bgm_set_song()
s32 bgm_set_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
Referenced by bgm_init_music_players(), bgm_push_battle_song(), bgm_push_song(), btl_state_update_celebration(), btl_state_update_defeat(), btl_state_update_end_training_battle(), btl_state_update_run_away(), btl_state_update_victory(), state_init_exit_file_select(), state_init_title_screen(), and state_step_title_screen().
bgm_set_target_volume()
void bgm_set_target_volume (s16 volume)
Referenced by _bgm_set_song(), and bgm_update_music_settings().
bgm_set_track_volumes()
AuResult bgm_set_track_volumes (s32 playerIndex, s16 trackVolSet)
bgm_set_variation()
AuResult bgm_set_variation (s32 playerIndex, s16 arg1)
bgm_update_music_settings()
void bgm_update_music_settings (void)
Referenced by step_game_loop().
bgm_update_volume()
void bgm_update_volume (void)
Referenced by bgm_update_music_settings().
func_8014A964()
s32 func_8014A964 (s32 playerIndex, s32 songID, s32 variation, s32 fadeInTime, s16 fadeStartVolume, s16 fadeEndVolume)
func_8014AD40()
s32 func_8014AD40 (void)
func_8014AFA0()
void func_8014AFA0 (void)
Variable Documentation
BlankMusicSettings
MusicSettings BlankMusicSettings
Initial value:
= {
    .flags = 0,
    .state = 0,
    .fadeOutTime = -1,
    .fadeInTime = 0,
    .fadeStartVolume = 0,
    .fadeEndVolume = 0,
    .songID = -1,
    .variation = -1,
    .songName = -1,
    .battleSongID = 0,
    .battleVariation = 0,
    .savedSongID = 0,
    .savedVariation = 0,
    .savedSongName = 0
}
Referenced by bgm_reset_sequence_players().
gMusicSettings
MusicSettings gMusicSettings[2]
Referenced by _bgm_set_song(), bgm_adjust_proximity(), bgm_clear_track_volumes(), bgm_pop_battle_song(), bgm_pop_song(), bgm_push_battle_song(), bgm_push_song(), bgm_reset_sequence_players(), bgm_set_battle_song(), bgm_set_song(), bgm_set_track_volumes(), bgm_set_variation(), bgm_update_music_settings(), func_8014A964(), and func_8014AD40().
MusicCurrentVolume
BSS s16 MusicCurrentVolume
Referenced by bgm_reset_sequence_players(), and bgm_update_volume().
MusicDefaultVolume
BSS s16 MusicDefaultVolume
Referenced by _bgm_set_song(), and bgm_update_music_settings().
MusicMaxVolume
BSS s16 MusicMaxVolume
Referenced by bgm_quiet_max_volume(), bgm_reset_max_volume(), bgm_reset_sequence_players(), bgm_reset_volume(), and bgm_update_volume().
MusicTargetVolume
BSS s16 MusicTargetVolume
Referenced by bgm_reset_sequence_players(), bgm_reset_volume(), bgm_set_target_volume(), and bgm_update_volume().
NextVolumeUpdateTimer
s16 NextVolumeUpdateTimer = 0
Referenced by bgm_update_volume().
SongsUsingVariationFlag
s32 SongsUsingVariationFlag[]
Initial value:
= {
    SONG_SPECIAL_BATTLE,
    SONG_TUBBA_BLUBBA_BATTLE,
    SONG_JR_TROOPA_BATTLE,
    SONG_YOSHI_KIDS_FOUND,
    SONG_ITEM_UPGRADE,
    SONG_NEW_PARTNER,
}
Lists the songs that are forced to use the variation determined by map.songVariation & 1.
See also
bgm_get_map_default_variation
Referenced by bgm_get_map_default_variation().