papermario: src/effects/effect_46.c File Reference
effect_46.c File Reference
Functions
void effect_46_init (EffectInstance *effect)
void effect_46_update (EffectInstance *effect)
void effect_46_render (EffectInstance *effect)
void effect_46_appendGfx (void *effect)
EffectInstance * effect_46_main (s32 type, PlayerStatus *player, f32 scale, s32 duration)
Variables
Gfx D_090003A0_38ED30 []
Gfx D_09000420_38EDB0 []
s32 D_E008CAF0 []
u8 ColorsR [] = { 255, 255, 64 }
u8 ColorsG [] = { 255, 64, 64 }
u8 ColorsB [] = { 255, 64, 255 }
Function Documentation
effect_46_appendGfx()
void effect_46_appendGfx (void * effect)
Referenced by effect_46_render().
effect_46_init()
void effect_46_init (EffectInstance * effect)
Referenced by effect_46_main().
effect_46_main()
EffectInstance * effect_46_main (s32 type, PlayerStatus * player, f32 scale, s32 duration)
effect_46_render()
void effect_46_render (EffectInstance * effect)
Referenced by effect_46_main().
effect_46_update()
void effect_46_update (EffectInstance * effect)
Referenced by effect_46_main().
Variable Documentation
ColorsB
u8 ColorsB[] = { 255, 64, 255 }
Referenced by effect_46_main().
ColorsG
u8 ColorsG[] = { 255, 64, 64 }
Referenced by effect_46_main().
ColorsR
u8 ColorsR[] = { 255, 255, 64 }
Referenced by effect_46_main().
D_090003A0_38ED30
Gfx D_090003A0_38ED30[] extern
Referenced by effect_46_appendGfx().
D_09000420_38EDB0
Gfx D_09000420_38EDB0[] extern
Referenced by effect_46_appendGfx().
D_E008CAF0
s32 D_E008CAF0[]
Initial value:
= {
    0xFEACACFE, 0xACD5FEB4, 0x9AD5B4FE,
    0xB4B4FEB4, 0xDDFEB4FE, 0xFEB4FED5,
    0xB4FEB4D5, 0xFEB4FEFE, 0xB4FED5AC
}