papermario: src/effects/effect_75.c File Reference
effect_75.c File Reference
Functions
void effect_75_init (EffectInstance *effect)
void effect_75_update (EffectInstance *effect)
void effect_75_render (EffectInstance *effect)
void effect_75_appendGfx (void *effect)
EffectInstance * effect_75_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 scale, s32 arg5)
void func_E00EA664 (void)
Variables
Gfx D_09001910_3E4270 []
Gfx D_09001A00_3E4360 []
Gfx D_09001A20_3E4380 []
Gfx * D_E00EAA50 [2] = { D_09001A00_3E4360, D_09001A20_3E4380 }
Gfx * D_E00EAA58 [2] = { D_09001910_3E4270, NULL }
Function Documentation
effect_75_appendGfx()
void effect_75_appendGfx (void * effect)
Referenced by effect_75_render().
effect_75_init()
void effect_75_init (EffectInstance * effect)
Referenced by effect_75_main().
effect_75_main()
EffectInstance * effect_75_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 scale, s32 arg5)
effect_75_render()
void effect_75_render (EffectInstance * effect)
Referenced by effect_75_main().
effect_75_update()
void effect_75_update (EffectInstance * effect)
Referenced by effect_75_main().
func_E00EA664()
void func_E00EA664 (void)
Variable Documentation
D_09001910_3E4270
Gfx D_09001910_3E4270[] extern
D_09001A00_3E4360
Gfx D_09001A00_3E4360[] extern
D_09001A20_3E4380
Gfx D_09001A20_3E4380[] extern
D_E00EAA50
Gfx* D_E00EAA50[2] = { D_09001A00_3E4360, D_09001A20_3E4380 }
Referenced by effect_75_appendGfx().
D_E00EAA58
Gfx* D_E00EAA58[2] = { D_09001910_3E4270, NULL }
Referenced by effect_75_appendGfx().