papermario: src/effects/whirlwind.c File Reference
whirlwind.c File Reference
Functions
void whirlwind_init (EffectInstance *effect)
void whirlwind_update (EffectInstance *effect)
void whirlwind_render (EffectInstance *effect)
void whirlwind_appendGfx (void *effect)
EffectInstance * whirlwind_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00CE470 (void)
Variables
Gfx D_09000400_3D3D30 []
Function Documentation
func_E00CE470()
void func_E00CE470 (void)
whirlwind_appendGfx()
void whirlwind_appendGfx (void * effect)
Referenced by whirlwind_render().
whirlwind_init()
void whirlwind_init (EffectInstance * effect)
Referenced by whirlwind_main().
whirlwind_main()
EffectInstance * whirlwind_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
whirlwind_render()
void whirlwind_render (EffectInstance * effect)
Referenced by whirlwind_main().
whirlwind_update()
void whirlwind_update (EffectInstance * effect)
Referenced by whirlwind_main().
Variable Documentation
D_09000400_3D3D30
Gfx D_09000400_3D3D30[] extern
Referenced by whirlwind_appendGfx().