papermario: src/effects/stop_watch.c File Reference
stop_watch.c File Reference
Data Structures
struct UnkStruct
Functions
void stop_watch_init (EffectInstance *effect)
void stop_watch_update (EffectInstance *effect)
void stop_watch_render (EffectInstance *effect)
void stop_watch_appendGfx (void *effect)
EffectInstance * stop_watch_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00C4300 (void)
Variables
Gfx D_09001000_3CC890 []
u8 D_E00C49D0 [] = { 120, 80, 40, 60 }
u8 D_E00C49D4 []
u8 D_E00C49E8 []
u8 D_E00C49FC []
UnkStruct D_E00C4A10 []
Data Structure Documentation
UnkStruct
struct UnkStruct
Data Fields
Gfx * displayList
s16 height
u8 sizeScale
s32 unk_00
u8 unk_00
s8 unk_00
u8 unk_01
s8 unk_01
u8 unk_02
s16 unk_02
u8 unk_03
s32 unk_04
Gfx * unk_04
s16 unk_04
s16 unk_06
f32 unk_08
Gfx * unk_08
s32 unk_08
char unk_09[1]
f32 unk_0C
s32 unk_10
s32 unk_14
s16 width
s16 x
s16 y
Function Documentation
func_E00C4300()
void func_E00C4300 (void)
stop_watch_appendGfx()
void stop_watch_appendGfx (void * effect)
Referenced by stop_watch_render().
stop_watch_init()
void stop_watch_init (EffectInstance * effect)
Referenced by stop_watch_main().
stop_watch_main()
EffectInstance * stop_watch_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
stop_watch_render()
void stop_watch_render (EffectInstance * effect)
Referenced by stop_watch_main().
stop_watch_update()
void stop_watch_update (EffectInstance * effect)
Referenced by stop_watch_main().
Variable Documentation
D_09001000_3CC890
Gfx D_09001000_3CC890[] extern
Referenced by stop_watch_appendGfx().
D_E00C49D0
u8 D_E00C49D0[] = { 120, 80, 40, 60 }
Referenced by stop_watch_appendGfx().
D_E00C49D4
u8 D_E00C49D4[]
Initial value:
= {
    255, 255, 255, 198, 138, 130, 130, 130, 130, 130,
    175, 215, 250, 255, 255, 255, 255
}
Referenced by stop_watch_appendGfx().
D_E00C49E8
u8 D_E00C49E8[]
Initial value:
= {
    130, 130, 130, 130, 130, 165, 213, 255, 255, 255,
    255, 255, 255, 225, 198, 159, 130
}
Referenced by stop_watch_appendGfx().
D_E00C49FC
u8 D_E00C49FC[]
Initial value:
= {
    130, 196, 255, 255, 255, 255, 255, 255, 202, 144,
    130, 130, 130, 130, 130, 130, 130
}
Referenced by stop_watch_appendGfx().
D_E00C4A10
UnkStruct D_E00C4A10[]
Initial value:
= {
    { -50, -70,  5 },
    {  80, -90, 20 },
    {  20, -50, 45 },
    { -80,  30, 10 },
    {  30,   0, 35 },
    { 120, -30, 50 },
    {  10,  50, 30 },
    { 100,  30, 15 },
    {  40, 100, 40 },
    { 140,  90, 25 }
}
Referenced by stop_watch_main().