papermario: src/effects/snowman_doll.c File Reference
snowman_doll.c File Reference
Functions
void snowman_doll_init (EffectInstance *effect)
void snowman_doll_update (EffectInstance *effect)
void snowman_doll_render (EffectInstance *effect)
void snowman_doll_appendGfx (void *effect)
EffectInstance * snowman_doll_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
EFFECT_DEF_COLD_BREATH (cold_breath_main)
EFFECT_DEF_MISC_PARTICLES (misc_particles_main)
void func_E00C0758 (void)
Variables
Gfx D_090037A8_3C1148 []
Gfx D_09003818_3C11B8 []
s8 D_E00C0A10 []
s8 D_E00C0A21 = 110
u8 D_E00C0A24 []
u8 D_E00C0A40 []
s8 D_E00C0A8C []
Function Documentation
EFFECT_DEF_COLD_BREATH()
EFFECT_DEF_COLD_BREATH (cold_breath_main)
EFFECT_DEF_MISC_PARTICLES()
EFFECT_DEF_MISC_PARTICLES (misc_particles_main)
func_E00C0758()
void func_E00C0758 (void)
snowman_doll_appendGfx()
void snowman_doll_appendGfx (void * effect)
Referenced by snowman_doll_render().
snowman_doll_init()
void snowman_doll_init (EffectInstance * effect)
Referenced by snowman_doll_main().
snowman_doll_main()
EffectInstance * snowman_doll_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
snowman_doll_render()
void snowman_doll_render (EffectInstance * effect)
Referenced by snowman_doll_main().
snowman_doll_update()
void snowman_doll_update (EffectInstance * effect)
Referenced by snowman_doll_main().
Variable Documentation
D_090037A8_3C1148
Gfx D_090037A8_3C1148[] extern
Referenced by snowman_doll_appendGfx().
D_09003818_3C11B8
Gfx D_09003818_3C11B8[] extern
Referenced by snowman_doll_appendGfx().
D_E00C0A10
s8 D_E00C0A10[]
Initial value:
= {
    100,  90,  82,  76,  72,  70,  74, 89, 103, 116,
    118, 120, 120, 120, 120, 118, 114
}
Referenced by snowman_doll_update().
D_E00C0A21
s8 D_E00C0A21 = 110
Referenced by snowman_doll_update().
D_E00C0A24
u8 D_E00C0A24[]
Initial value:
= {
    100,  90,  82,  76,  72,  70,  74,  89, 100, 108,
    110, 108, 102,  96,  95,  96,  99, 101, 100, 100,
    100, 100, 100, 100, 100, 100, 100
}
Referenced by snowman_doll_update().
D_E00C0A40
u8 D_E00C0A40[]
Initial value:
= {
    100,  90,  82,  76,  72,  70,  70,  70,  70,  70,
     70,  70,  70,  70,  70,  70,  70,  70,  70,  70,
     70,  70,  70,  70,  70,  70,  70,  70,  70,  70,
     70,  70,  70,  70,  70,  70,  70,  70,  70,  70,
     70,  70,  70,  70,  70,  70,  70,  70,  70,  70,
     70,  70,  70,  70,  70,  70,  70,  70,  70,  70,
     70,  70,  74,  89, 103, 116, 118, 120, 120, 120,
    120, 118, 114, 110
}
Referenced by snowman_doll_update().
D_E00C0A8C
s8 D_E00C0A8C[]
Initial value:
= {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x05, 0x0A, 0x10, 0x16, 0x1C, 0x21, 0x26, 0x28, 0x29,
    0x29, 0x28, 0x26, 0x21, 0x1C, 0x16, 0x10, 0x0A, 0x05, 0x01, 0x01, 0x05, 0x0A, 0x10, 0x16,
    0x1C, 0x21, 0x26, 0x28, 0x29, 0x29, 0x28, 0x26, 0x21, 0x1C, 0x16, 0x10, 0x0A, 0x05, 0x01,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0xFF, 0x38, 0x00, 0xC8, 0x1E, 0x64, 0x64, 0x00, 0xFF, 0x4C, 0x00, 0xB4, 0x1E, 0x64,
    0x64, 0x00, 0xFF, 0x60, 0x00, 0xA0, 0x1E, 0x64, 0x64, 0x00, 0xFF, 0x74, 0x00, 0x8C, 0x1E,
    0x64, 0x64, 0x00, 0xFF, 0x88, 0x00, 0x78, 0x1E, 0x64, 0x64, 0x00, 0xFF, 0x9C, 0x00, 0x64,
    0x1E, 0x64, 0x64, 0x00, 0xFF, 0xB0, 0x00, 0x50, 0x1E, 0x64, 0x64, 0x00, 0xFF, 0xC4, 0x00,
    0x3C, 0x1E, 0x64, 0x64, 0x00, 0xFF, 0xD8, 0x00, 0x28, 0x1E, 0x64, 0x64, 0x00, 0xFF, 0xEC,
    0x00, 0x14, 0x1E, 0x64, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1E, 0x64, 0x64, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x1E, 0x78, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x82, 0x46, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x05, 0x87, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x8A, 0x3E,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8C, 0x3C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x8C,
    0x3C, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x8C, 0x3C, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF,
    0x8C, 0x3C, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFE, 0x8A, 0x3E, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xFE, 0x87, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFD, 0x82, 0x46, 0x00, 0x00, 0x00, 0x00,
    0x00, 0xFC, 0x78, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFA, 0x64, 0x64, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xFA, 0x64, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF8, 0x64, 0x64, 0x00, 0x00,
    0x00, 0x00, 0x01, 0xF4, 0x64, 0x64, 0x00, 0x00, 0x00, 0x00, 0x03, 0xEE, 0x64, 0x64, 0x00,
    0x00, 0x00, 0x00, 0x05, 0xE6, 0x64, 0x64, 0x00, 0x00, 0x00, 0x00, 0x0A, 0xDC, 0x64, 0x64,
    0x00, 0x00, 0x00, 0x00, 0x0F, 0xD0, 0x64, 0x64, 0x00, 0x00, 0x00, 0x00, 0x14, 0xC2, 0x64,
    0x64, 0x00, 0x00, 0x00, 0x00, 0x1C, 0xB2, 0x64, 0x64, 0x00, 0x00, 0x05, 0x00, 0x1E, 0xA0,
    0x64, 0x64, 0x00, 0x00, 0x08, 0x00, 0x1E, 0xA0, 0x64, 0x64, 0x00, 0x00, 0x0A, 0x00, 0x1E,
    0xA0, 0x64, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
Referenced by snowman_doll_update().