papermario: src/effects/fright_jar.c File Reference
fright_jar.c File Reference
Functions
void fright_jar_init (EffectInstance *effect)
void fright_jar_update (EffectInstance *effect)
void fright_jar_render (EffectInstance *effect)
void fright_jar_appendGfx (void *effect)
EffectInstance * fright_jar_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00C2214 (void)
Variables
s32 D_09000000_3C1BA0
s32 D_09002020_3C3BC0
Vtx D_09004040_3C5BE0 [][22]
Gfx D_09008BE0_3CA780 []
u8 D_E00C2990 []
Function Documentation
fright_jar_appendGfx()
void fright_jar_appendGfx (void * effect)
Referenced by fright_jar_render().
fright_jar_init()
void fright_jar_init (EffectInstance * effect)
Referenced by fright_jar_main().
fright_jar_main()
EffectInstance * fright_jar_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
fright_jar_render()
void fright_jar_render (EffectInstance * effect)
Referenced by fright_jar_main().
fright_jar_update()
void fright_jar_update (EffectInstance * effect)
Referenced by fright_jar_main().
func_E00C2214()
void func_E00C2214 (void)
Variable Documentation
D_09000000_3C1BA0
s32 D_09000000_3C1BA0 extern
Referenced by fright_jar_appendGfx().
D_09002020_3C3BC0
s32 D_09002020_3C3BC0 extern
Referenced by fright_jar_appendGfx().
D_09004040_3C5BE0
Vtx D_09004040_3C5BE0[][22] extern
Referenced by fright_jar_appendGfx().
D_09008BE0_3CA780
Gfx D_09008BE0_3CA780[] extern
Referenced by fright_jar_appendGfx().
D_E00C2990
u8 D_E00C2990[]
Initial value:
= {
    0xFF, 0xFF, 0xDC, 0xBE, 0xA0, 0x78, 0x50, 0x28,
    0x00, 0x00, 0x28, 0x50, 0x78, 0xA0, 0xBE, 0xDC
}
Referenced by fright_jar_appendGfx().