papermario: src/effects/squirt.c File Reference
squirt.c File Reference
Functions
void squirt_init (EffectInstance *effect)
void squirt_update (EffectInstance *effect)
void squirt_render (EffectInstance *effect)
void squirt_appendGfx (void *effect)
EffectInstance * squirt_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, s32 arg8)
void func_E00B24A8 (void)
Variables
u8 D_E00B2BA0 [] = { 255, 255, 255, 255, 255, 255, 255, 255, 255, 200, 128, 32, 0, 0, 0, 0 }
Gfx D_09000800_3B5B40 []
Gfx D_090008A8_3B5BE8 []
Function Documentation
func_E00B24A8()
void func_E00B24A8 (void)
squirt_appendGfx()
void squirt_appendGfx (void * effect)
Referenced by squirt_render().
squirt_init()
void squirt_init (EffectInstance * effect)
Referenced by squirt_main().
squirt_main()
EffectInstance * squirt_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, s32 arg8)
squirt_render()
void squirt_render (EffectInstance * effect)
Referenced by squirt_main().
squirt_update()
void squirt_update (EffectInstance * effect)
Referenced by squirt_main().
Variable Documentation
D_09000800_3B5B40
Gfx D_09000800_3B5B40[] extern
Referenced by squirt_appendGfx().
D_090008A8_3B5BE8
Gfx D_090008A8_3B5BE8[] extern
Referenced by squirt_appendGfx().
D_E00B2BA0
u8 D_E00B2BA0[] = { 255, 255, 255, 255, 255, 255, 255, 255, 255, 200, 128, 32, 0, 0, 0, 0 }
Referenced by squirt_appendGfx().