papermario: src/effects.c File Reference
effects.c File Reference
Macros
#define EFFECT_GLOBALS_TLB_IDX 0x10
#define FX_ENTRY(name, gfx_name)
Typedefs
typedef s8 TlbEntry[0x1000]
typedef TlbEntry TlbMappablePage[15]
Functions
void stub_effect_delegate (EffectInstance *effect)
Used for unbound function points in effect structs.
void set_effect_pos_offset (EffectInstance *effect, f32 x, f32 y, f32 z)
void clear_effect_data (void)
void func_80059D48 (void)
void update_effects (void)
void render_effects_scene (void)
void render_effects_UI (void)
EffectInstance * create_effect_instance (EffectBlueprint *effectBp)
void remove_effect (EffectInstance *effectInstance)
void remove_all_effects (void)
s32 load_effect (s32 effectIndex)
Variables
BSS EffectSharedData gEffectSharedData [15]
EffectInstance * gEffectInstances [96]
TlbMappablePage gEffectDataBuffer
Addr gEffectGlobals
s32 D_8007FEB8 [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 5, 3, 4, 13, 60, 0, 512, 0, 0, 3, 0 }
Macro Definition Documentation
EFFECT_GLOBALS_TLB_IDX
#define EFFECT_GLOBALS_TLB_IDX 0x10
Referenced by clear_effect_data().
FX_ENTRY
#define FX_ENTRY (name, gfx_name)
Value:
    { \
    .entryPoint = name##_main, \
    .dmaStart = effect_##name##_ROM_START, \
    .dmaEnd = effect_##name##_ROM_END, \
    .dmaDest = effect_##name##_VRAM, \
    .graphicsDmaStart = gfx_name##_ROM_START, \
    .graphicsDmaEnd = gfx_name##_ROM_END, \
}
Typedef Documentation
TlbEntry
typedef s8 TlbEntry[0x1000]
TlbMappablePage
typedef TlbEntry TlbMappablePage[15]
Function Documentation
clear_effect_data()
void clear_effect_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_demo(), state_step_intro(), and state_step_startup().
create_effect_instance()
EffectInstance * create_effect_instance (EffectBlueprint * effectBp)
Bug
? null check for renderUI instead of renderWorld
func_80059D48()
void func_80059D48 (void)
load_effect()
s32 load_effect (s32 effectIndex)
remove_all_effects()
void remove_all_effects (void)
Referenced by btl_state_update_end_battle(), and btl_state_update_end_demo_battle().
remove_effect()
void remove_effect (EffectInstance * effectInstance)
render_effects_scene()
void render_effects_scene (void)
Referenced by render_frame().
render_effects_UI()
void render_effects_UI (void)
Referenced by gfx_draw_frame().
set_effect_pos_offset()
void set_effect_pos_offset (EffectInstance * effect, f32 x, f32 y, f32 z)
stub_effect_delegate()
void stub_effect_delegate (EffectInstance * effect)
Used for unbound function points in effect structs.
Referenced by create_effect_instance(), and render_effects_UI().
update_effects()
void update_effects (void)
Referenced by state_step_battle(), state_step_change_map(), state_step_enter_world(), state_step_exit_language_select(), state_step_game_over(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_unpause(), and state_step_world().
Variable Documentation
D_8007FEB8
s32 D_8007FEB8[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 5, 3, 4, 13, 60, 0, 512, 0, 0, 3, 0 }
gEffectDataBuffer
TlbMappablePage gEffectDataBuffer extern
Referenced by load_effect().
gEffectGlobals
BSS u8 gEffectGlobals extern
Referenced by clear_effect_data().
gEffectInstances
EffectInstance* gEffectInstances[96]
Referenced by clear_effect_data(), create_effect_instance(), remove_all_effects(), remove_effect(), render_effects_scene(), render_effects_UI(), and update_effects().
gEffectSharedData
BSS EffectSharedData gEffectSharedData[15]
Referenced by clear_effect_data(), create_effect_instance(), load_effect(), and update_effects().