papermario: src/effects/effect_3D.c File Reference
effect_3D.c File Reference
Functions
void effect_3D_init (EffectInstance *effect)
void effect_3D_update (EffectInstance *effect)
void effect_3D_render (EffectInstance *effect)
void effect_3D_appendGfx (void *effect)
void effect_3D_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, s32 arg7, EffectInstance **outEffect)
void func_E007A884 (void)
Variables
Gfx D_09000240_37D3C0 []
Gfx D_090002E8_37D468 []
Function Documentation
effect_3D_appendGfx()
void effect_3D_appendGfx (void * effect)
Referenced by effect_3D_render().
effect_3D_init()
void effect_3D_init (EffectInstance * effect)
Referenced by effect_3D_main().
effect_3D_main()
void effect_3D_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, s32 arg7, EffectInstance ** outEffect)
effect_3D_render()
void effect_3D_render (EffectInstance * effect)
Referenced by effect_3D_main().
effect_3D_update()
void effect_3D_update (EffectInstance * effect)
Referenced by effect_3D_main().
func_E007A884()
void func_E007A884 (void)
Variable Documentation
D_09000240_37D3C0
Gfx D_09000240_37D3C0[] extern
Referenced by effect_3D_appendGfx().
D_090002E8_37D468
Gfx D_090002E8_37D468[] extern
Referenced by effect_3D_appendGfx().