papermario: src/effects/effect_86.c File Reference
effect_86.c File Reference
Functions
void effect_86_init (EffectInstance *effect)
void effect_86_update (EffectInstance *effect)
void effect_86_render (EffectInstance *effect)
void effect_86_appendGfx (void *effect)
EffectInstance * effect_86_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09000800_415860 []
Gfx D_09000BA8_415C08 []
Gfx D_09000BC8_415C28 []
Gfx D_09000BE8_415C48 []
Gfx D_09000C08_415C68 []
Gfx D_09000C28_415C88 []
Gfx D_09000C48_415CA8 []
Gfx D_09000C68_415CC8 []
Gfx D_09000C88_415CE8 []
Gfx D_09000CA8_415D08 []
Gfx D_09000CC8_415D28 []
Gfx D_09000CE8_415D48 []
Gfx D_09000D08_415D68 []
Gfx * D_E0128480 [12]
Gfx * D_E01284B0 [] = { D_09000800_415860 }
Function Documentation
effect_86_appendGfx()
void effect_86_appendGfx (void * effect)
Referenced by effect_86_render().
effect_86_init()
void effect_86_init (EffectInstance * effect)
Referenced by effect_86_main().
effect_86_main()
EffectInstance * effect_86_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
effect_86_render()
void effect_86_render (EffectInstance * effect)
Referenced by effect_86_main().
effect_86_update()
void effect_86_update (EffectInstance * effect)
Referenced by effect_86_main().
Variable Documentation
D_09000800_415860
Gfx D_09000800_415860[] extern
D_09000BA8_415C08
Gfx D_09000BA8_415C08[] extern
D_09000BC8_415C28
Gfx D_09000BC8_415C28[] extern
D_09000BE8_415C48
Gfx D_09000BE8_415C48[] extern
D_09000C08_415C68
Gfx D_09000C08_415C68[] extern
D_09000C28_415C88
Gfx D_09000C28_415C88[] extern
D_09000C48_415CA8
Gfx D_09000C48_415CA8[] extern
D_09000C68_415CC8
Gfx D_09000C68_415CC8[] extern
D_09000C88_415CE8
Gfx D_09000C88_415CE8[] extern
D_09000CA8_415D08
Gfx D_09000CA8_415D08[] extern
D_09000CC8_415D28
Gfx D_09000CC8_415D28[] extern
D_09000CE8_415D48
Gfx D_09000CE8_415D48[] extern
D_09000D08_415D68
Gfx D_09000D08_415D68[] extern
D_E0128480
Gfx* D_E0128480[12]
Initial value:
= {
    D_09000BA8_415C08, D_09000BC8_415C28, D_09000BE8_415C48, D_09000C08_415C68,
    D_09000C28_415C88, D_09000C48_415CA8, D_09000C68_415CC8, D_09000C88_415CE8,
    D_09000CA8_415D08, D_09000CC8_415D28, D_09000CE8_415D48, D_09000D08_415D68
}
Referenced by effect_86_appendGfx().
D_E01284B0
Gfx* D_E01284B0[] = { D_09000800_415860 }
Referenced by effect_86_appendGfx().