papermario: src/effects/effect_63.c File Reference
effect_63.c File Reference
Functions
void effect_63_init (EffectInstance *effect)
void effect_63_update (EffectInstance *effect)
void effect_63_render (EffectInstance *effect)
void effect_63_appendGfx (void *effect)
EffectInstance * effect_63_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, s32 arg8, s32 arg9)
Variables
Gfx D_09001B70_3CF250 []
Gfx D_09001C98_3CF378 []
Gfx * D_E00C6C90 []
Gfx * D_E00C6C9C []
Function Documentation
effect_63_appendGfx()
void effect_63_appendGfx (void * effect)
Referenced by effect_63_render().
effect_63_init()
void effect_63_init (EffectInstance * effect)
Referenced by effect_63_main().
effect_63_main()
EffectInstance * effect_63_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, s32 arg8, s32 arg9)
Referenced by effect_63_update().
effect_63_render()
void effect_63_render (EffectInstance * effect)
Referenced by effect_63_main().
effect_63_update()
void effect_63_update (EffectInstance * effect)
Referenced by effect_63_main().
Variable Documentation
D_09001B70_3CF250
Gfx D_09001B70_3CF250[] extern
D_09001C98_3CF378
Gfx D_09001C98_3CF378[] extern
D_E00C6C90
Gfx* D_E00C6C90[]
Initial value:
= {
    D_09001C98_3CF378, D_09001C98_3CF378, D_09001C98_3CF378
}
Referenced by effect_63_appendGfx().
D_E00C6C9C
Gfx* D_E00C6C9C[]
Initial value:
= {
    D_09001B70_3CF250, D_09001B70_3CF250, D_09001B70_3CF250, NULL, NULL
}
Referenced by effect_63_appendGfx().