papermario: src/effects/effect_65.c File Reference
effect_65.c File Reference
Macros
#define MAX_POINTS 30
#define VTX_BUF_SIZE 2 * MAX_POINTS * sizeof(Vtx) / sizeof(Gfx)
Functions
void effect_65_init (EffectInstance *effect)
void effect_65_update (EffectInstance *effect)
void effect_65_render (EffectInstance *effect)
void effect_65_appendGfx (void *effect)
EffectInstance * effect_65_main (s32 variation, f32 posX, f32 posY, f32 posZ, f32 scale, s32 duration)
Variables
Gfx D_09000400_3D15E0 []
Gfx * D_E00CACB0 [] = { D_09000400_3D15E0, D_09000400_3D15E0, D_09000400_3D15E0, D_09000400_3D15E0 }
Macro Definition Documentation
MAX_POINTS
#define MAX_POINTS 30
Referenced by effect_65_appendGfx(), effect_65_main(), and effect_65_update().
VTX_BUF_SIZE
#define VTX_BUF_SIZE 2 * MAX_POINTS * sizeof(Vtx) / sizeof(Gfx)
Referenced by effect_65_appendGfx().
Function Documentation
effect_65_appendGfx()
void effect_65_appendGfx (void * effect)
Referenced by effect_65_render().
effect_65_init()
void effect_65_init (EffectInstance * effect)
Referenced by effect_65_main().
effect_65_main()
EffectInstance * effect_65_main (s32 variation, f32 posX, f32 posY, f32 posZ, f32 scale, s32 duration)
effect_65_render()
void effect_65_render (EffectInstance * effect)
Referenced by effect_65_main().
effect_65_update()
void effect_65_update (EffectInstance * effect)
Referenced by effect_65_main().
Variable Documentation
D_09000400_3D15E0
Gfx D_09000400_3D15E0[] extern
D_E00CACB0
Gfx* D_E00CACB0[] = { D_09000400_3D15E0, D_09000400_3D15E0, D_09000400_3D15E0, D_09000400_3D15E0 }
Referenced by effect_65_appendGfx().