papermario: src/effects/fire_flower.c File Reference
fire_flower.c File Reference
Functions
void fire_flower_appendGfx (void *effect)
void fire_flower_init (EffectInstance *effect)
void fire_flower_update (EffectInstance *effect)
void fire_flower_render (EffectInstance *effect)
EffectInstance * fire_flower_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4)
EFFECT_DEF_STARS_SPREAD (stars_spread_main)
Variables
char D_09000000_3803A0 [][0x200]
Gfx D_09000D40_3810E0 []
Gfx D_09000DE0_381180 []
Gfx D_09000EB8_381258 []
Gfx D_09000ED8_381278 []
Gfx D_09000EF8_381298 []
s8 D_E007EC30 [] = { 50, 60, 70, 80, 90, 100, 105, 100 }
Function Documentation
EFFECT_DEF_STARS_SPREAD()
EFFECT_DEF_STARS_SPREAD (stars_spread_main)
fire_flower_appendGfx()
void fire_flower_appendGfx (void * effect)
Referenced by fire_flower_render().
fire_flower_init()
void fire_flower_init (EffectInstance * effect)
Referenced by fire_flower_main().
fire_flower_main()
EffectInstance * fire_flower_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4)
fire_flower_render()
void fire_flower_render (EffectInstance * effect)
Referenced by fire_flower_main().
fire_flower_update()
void fire_flower_update (EffectInstance * effect)
Referenced by fire_flower_main().
Variable Documentation
D_09000000_3803A0
char D_09000000_3803A0[][0x200] extern
Referenced by fire_flower_appendGfx().
D_09000D40_3810E0
Gfx D_09000D40_3810E0[] extern
Referenced by fire_flower_appendGfx().
D_09000DE0_381180
Gfx D_09000DE0_381180[] extern
Referenced by fire_flower_appendGfx().
D_09000EB8_381258
Gfx D_09000EB8_381258[] extern
Referenced by fire_flower_appendGfx().
D_09000ED8_381278
Gfx D_09000ED8_381278[] extern
Referenced by fire_flower_appendGfx().
D_09000EF8_381298
Gfx D_09000EF8_381298[] extern
Referenced by fire_flower_appendGfx().
D_E007EC30
s8 D_E007EC30[] = { 50, 60, 70, 80, 90, 100, 105, 100 }
Referenced by fire_flower_update().