papermario: src/effects/embers.c File Reference
embers.c File Reference
Functions
void embers_init (EffectInstance *effect)
void embers_update (EffectInstance *effect)
void embers_render (EffectInstance *effect)
void embers_appendGfx (void *effect)
EffectInstance * embers_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, s32 arg7, s32 arg8, f32 arg9, f32 argA)
void func_E00E05F8 (void)
Variables
Gfx D_09000280_3DC1C0 []
Gfx D_090003B0_3DC2F0 []
Gfx * D_E00E0A40 [] = { D_090003B0_3DC2F0, D_09000280_3DC1C0 }
f32 D_E00E0A48 []
Function Documentation
embers_appendGfx()
void embers_appendGfx (void * effect)
Referenced by embers_render().
embers_init()
void embers_init (EffectInstance * effect)
Referenced by embers_main().
embers_main()
EffectInstance * embers_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, s32 arg7, s32 arg8, f32 arg9, f32 argA)
embers_render()
void embers_render (EffectInstance * effect)
Referenced by embers_main().
embers_update()
void embers_update (EffectInstance * effect)
Referenced by embers_main().
func_E00E05F8()
void func_E00E05F8 (void)
Variable Documentation
D_09000280_3DC1C0
Gfx D_09000280_3DC1C0[] extern
D_090003B0_3DC2F0
Gfx D_090003B0_3DC2F0[] extern
D_E00E0A40
Gfx* D_E00E0A40[] = { D_090003B0_3DC2F0, D_09000280_3DC1C0 }
Referenced by embers_appendGfx().
D_E00E0A48
f32 D_E00E0A48[]
Initial value:
= {
    0.01f, 0.05f,  0.1f,  0.2f, 0.35f,  0.5f,
    0.65f,  0.8f, 0.95f,  1.0f,  1.0f,  1.0f,
     1.0f,  1.0f,  1.0f,  1.0f,  1.0f,  1.0f,
     1.0f,  1.0f,  1.0f, 0.95f,  0.8f, 0.65f,
     0.5f, 0.35f,  0.2f,  0.1f, 0.05f, 0.01f
}
Referenced by embers_update().