papermario: src/effects/emote.c File Reference
emote.c File Reference
Functions
void emote_init (EffectInstance *effect)
void emote_update (EffectInstance *effect)
void emote_render (EffectInstance *effect)
void emote_appendGfx (void *effect)
void func_E0020000 (EmoteFXData *part, s32 arg1)
void emote_main (s32 arg0, Npc *arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, s32 arg7, EffectInstance **arg8)
Variables
Gfx D_09002170_336DE0 []
Gfx D_09002238_336EA8 []
Gfx D_090022E0_336F50 []
Gfx D_09002308_336F78 []
Gfx D_090023B0_337020 []
Gfx D_090023D8_337048 []
Gfx D_09002480_3370F0 []
Gfx D_090024A8_337118 []
Gfx D_09002550_3371C0 []
Gfx D_09002578_3371E8 []
Gfx * D_E0020C90 [] = { D_090022E0_336F50, NULL, D_090023B0_337020, D_09002480_3370F0, D_09002550_3371C0 }
Gfx * D_E0020CA4 [] = { D_09002238_336EA8, NULL, D_09002308_336F78, D_090023D8_337048, D_090024A8_337118 }
s8 D_E0020CB8 [40]
s8 D_E0020CE0 [28]
s8 D_E0020CFC [40]
s8 D_E0020D24 [12] = { 0, 0, 1, 1, 2, 2, 3, 3, -13, 0, 0, 0 }
s8 D_E0020D30 [80]
s8 * D_E0020D80 [5] = { D_E0020CB8, D_E0020CE0, D_E0020CFC, D_E0020D24, D_E0020D30 }
u8 D_E0020D94 []
Function Documentation
emote_appendGfx()
void emote_appendGfx (void * effect)
Referenced by emote_render().
emote_init()
void emote_init (EffectInstance * effect)
Referenced by emote_main().
emote_main()
void emote_main (s32 arg0, Npc * arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, s32 arg7, EffectInstance ** arg8)
emote_render()
void emote_render (EffectInstance * effect)
Referenced by emote_main().
emote_update()
void emote_update (EffectInstance * effect)
Referenced by emote_main().
func_E0020000()
void func_E0020000 (EmoteFXData * part, s32 arg1)
Referenced by emote_main(), and emote_update().
Variable Documentation
D_09002170_336DE0
Gfx D_09002170_336DE0[] extern
Referenced by emote_appendGfx().
D_09002238_336EA8
Gfx D_09002238_336EA8[] extern
D_090022E0_336F50
Gfx D_090022E0_336F50[] extern
D_09002308_336F78
Gfx D_09002308_336F78[] extern
D_090023B0_337020
Gfx D_090023B0_337020[] extern
D_090023D8_337048
Gfx D_090023D8_337048[] extern
D_09002480_3370F0
Gfx D_09002480_3370F0[] extern
D_090024A8_337118
Gfx D_090024A8_337118[] extern
D_09002550_3371C0
Gfx D_09002550_3371C0[] extern
D_09002578_3371E8
Gfx D_09002578_3371E8[] extern
Referenced by emote_appendGfx().
D_E0020C90
Gfx* D_E0020C90[] = { D_090022E0_336F50, NULL, D_090023B0_337020, D_09002480_3370F0, D_09002550_3371C0 }
Referenced by emote_appendGfx().
D_E0020CA4
Gfx* D_E0020CA4[] = { D_09002238_336EA8, NULL, D_09002308_336F78, D_090023D8_337048, D_090024A8_337118 }
Referenced by emote_appendGfx().
D_E0020CB8
s8 D_E0020CB8[40]
Initial value:
= {
    0, 0, 1, 2, 3, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    -1, 0
}
D_E0020CE0
s8 D_E0020CE0[28]
Initial value:
= {
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, -1, 0, 0, 0
}
D_E0020CFC
s8 D_E0020CFC[40]
Initial value:
= {
    0, 0, 2, 1, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, -1,
    0, 0
}
D_E0020D24
s8 D_E0020D24[12] = { 0, 0, 1, 1, 2, 2, 3, 3, -13, 0, 0, 0 }
D_E0020D30
s8 D_E0020D30[80]
Initial value:
= {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, -1, 0
}
D_E0020D80
s8* D_E0020D80[5] = { D_E0020CB8, D_E0020CE0, D_E0020CFC, D_E0020D24, D_E0020D30 }
Referenced by emote_update().
D_E0020D94
u8 D_E0020D94[]
Initial value:
= {
    64,  0,  0,
    32,  0, 32,
     0,  0, 64,
     0, 32, 32,
     0, 64,  0,
    32, 32,  0,
     0,  0,  0
}
Referenced by emote_appendGfx().