papermario: src/effects/ending_decals.c File Reference
ending_decals.c File Reference
Functions
void ending_decals_init (EffectInstance *effect)
void ending_decals_update (EffectInstance *effect)
void ending_decals_render (EffectInstance *effect)
void ending_decals_appendGfx (void *effect)
void ending_decals_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 arg4, EffectInstance **outEffect)
Variables
Gfx D_09001E40_36CD20 []
Gfx D_09001EA8_36CD88 []
Gfx D_09001F10_36CDF0 []
Gfx D_09001F78_36CE58 []
Gfx D_09002058_36CF38 []
Gfx D_09002078_36CF58 []
Gfx * D_E00685B0 []
Gfx * D_E00685BC []
Gfx * D_E00685F4 []
Function Documentation
ending_decals_appendGfx()
void ending_decals_appendGfx (void * effect)
Referenced by ending_decals_render().
ending_decals_init()
void ending_decals_init (EffectInstance * effect)
Referenced by ending_decals_main().
ending_decals_main()
void ending_decals_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 arg4, EffectInstance ** outEffect)
ending_decals_render()
void ending_decals_render (EffectInstance * effect)
Referenced by ending_decals_main().
ending_decals_update()
void ending_decals_update (EffectInstance * effect)
Referenced by ending_decals_main().
Variable Documentation
D_09001E40_36CD20
Gfx D_09001E40_36CD20[] extern
Referenced by ending_decals_appendGfx().
D_09001EA8_36CD88
Gfx D_09001EA8_36CD88[] extern
D_09001F10_36CDF0
Gfx D_09001F10_36CDF0[] extern
D_09001F78_36CE58
Gfx D_09001F78_36CE58[] extern
D_09002058_36CF38
Gfx D_09002058_36CF38[] extern
D_09002078_36CF58
Gfx D_09002078_36CF58[] extern
D_E00685B0
Gfx* D_E00685B0[]
Initial value:
= {
    D_09001E40_36CD20, D_09001E40_36CD20, D_09002058_36CF38
}
Referenced by ending_decals_appendGfx().
D_E00685BC
Gfx* D_E00685BC[]
Initial value:
= {
    D_09001E40_36CD20, D_09001E40_36CD20, D_09001E40_36CD20, D_09001E40_36CD20,
    D_09001E40_36CD20, D_09001EA8_36CD88, D_09001EA8_36CD88, D_09001F10_36CDF0,
    D_09001F10_36CDF0, D_09001F10_36CDF0, D_09001F10_36CDF0, D_09001F10_36CDF0,
    D_09001EA8_36CD88, D_09001EA8_36CD88
}
Referenced by ending_decals_appendGfx().
D_E00685F4
Gfx* D_E00685F4[]
Initial value:
= {
    D_09001F78_36CE58, D_09001F78_36CE58, D_09002078_36CF58
}
Referenced by ending_decals_appendGfx().