papermario: src/effects/energy_shockwave.c File Reference
energy_shockwave.c File Reference
Functions
void energy_shockwave_init (EffectInstance *effect)
void energy_shockwave_update (EffectInstance *effect)
void energy_shockwave_render (EffectInstance *effect)
void energy_shockwave_appendGfx (void *effect)
void energy_shockwave_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
EFFECT_DEF_SHIMMER_WAVE (shimmer_wave_main)
Variables
Gfx D_09000DC0_3762D0 []
Gfx D_09000E60_376370 []
Function Documentation
EFFECT_DEF_SHIMMER_WAVE()
EFFECT_DEF_SHIMMER_WAVE (shimmer_wave_main)
energy_shockwave_appendGfx()
void energy_shockwave_appendGfx (void * effect)
Referenced by energy_shockwave_render().
energy_shockwave_init()
void energy_shockwave_init (EffectInstance * effect)
Referenced by energy_shockwave_main().
energy_shockwave_main()
void energy_shockwave_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
energy_shockwave_render()
void energy_shockwave_render (EffectInstance * effect)
Referenced by energy_shockwave_main().
energy_shockwave_update()
void energy_shockwave_update (EffectInstance * effect)
Referenced by energy_shockwave_main().
Variable Documentation
D_09000DC0_3762D0
Gfx D_09000DC0_3762D0[] extern
Referenced by energy_shockwave_appendGfx().
D_09000E60_376370
Gfx D_09000E60_376370[] extern
Referenced by energy_shockwave_appendGfx().