papermario: src/effects/energy_in_out.c File Reference
energy_in_out.c File Reference
Functions
void energy_in_out_init (EffectInstance *effect)
void energy_in_out_update (EffectInstance *effect)
void energy_in_out_render (EffectInstance *effect)
void energy_in_out_appendGfx (void *effect)
EffectInstance * energy_in_out_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00D6978 (void)
Variables
Gfx D_09000200_3D6130 []
Gfx D_090003A8_3D62D8 []
Gfx D_090003C8_3D62F8 []
Gfx D_090003E8_3D6318 []
Gfx D_09000528_3D6458 []
Gfx D_09000540_3D6470 []
Gfx D_09000558_3D6488 []
Gfx D_09000688_3D65B8 []
Gfx D_09000808_3D6738 []
Gfx * D_E00D6E40 []
u8 D_E00D6E74 []
u8 D_E00D6E84 []
Function Documentation
energy_in_out_appendGfx()
void energy_in_out_appendGfx (void * effect)
Referenced by energy_in_out_render().
energy_in_out_init()
void energy_in_out_init (EffectInstance * effect)
Referenced by energy_in_out_main().
energy_in_out_main()
EffectInstance * energy_in_out_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
energy_in_out_render()
void energy_in_out_render (EffectInstance * effect)
Referenced by energy_in_out_main().
energy_in_out_update()
void energy_in_out_update (EffectInstance * effect)
Referenced by energy_in_out_main().
func_E00D6978()
void func_E00D6978 (void)
Variable Documentation
D_09000200_3D6130
Gfx D_09000200_3D6130[] extern
Referenced by energy_in_out_appendGfx().
D_090003A8_3D62D8
Gfx D_090003A8_3D62D8[] extern
D_090003C8_3D62F8
Gfx D_090003C8_3D62F8[] extern
D_090003E8_3D6318
Gfx D_090003E8_3D6318[] extern
D_09000528_3D6458
Gfx D_09000528_3D6458[] extern
D_09000540_3D6470
Gfx D_09000540_3D6470[] extern
D_09000558_3D6488
Gfx D_09000558_3D6488[] extern
D_09000688_3D65B8
Gfx D_09000688_3D65B8[] extern
Referenced by energy_in_out_appendGfx().
D_09000808_3D6738
Gfx D_09000808_3D6738[] extern
Referenced by energy_in_out_appendGfx().
D_E00D6E40
Gfx* D_E00D6E40[]
Initial value:
= {
    D_090003A8_3D62D8, D_090003C8_3D62F8, D_090003E8_3D6318, D_09000528_3D6458,
    D_09000540_3D6470, D_09000558_3D6488, D_09000688_3D65B8, D_09000688_3D65B8,
    D_09000688_3D65B8, D_09000558_3D6488, D_09000808_3D6738, D_09000688_3D65B8,
    D_09000558_3D6488
}
Referenced by energy_in_out_appendGfx().
D_E00D6E74
u8 D_E00D6E74[]
Initial value:
= {
    0x0B, 0x0B, 0x0B, 0x0B, 0x11, 0x0B, 0x0B, 0x15, 0x15, 0x15, 0x15, 0x15, 0x15, 0x00, 0x00, 0x00
}
Referenced by energy_in_out_main().
D_E00D6E84
u8 D_E00D6E84[]
Initial value:
= {
    0x14, 0x05, 0x14, 0x14, 0x0A, 0x14, 0x14, 0x08, 0x08, 0x08, 0x01, 0x01, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
Referenced by energy_in_out_main().