papermario: src/effects/energy_orb_wave.c File Reference
energy_orb_wave.c File Reference
Functions
void energy_orb_wave_init (EffectInstance *effect)
void energy_orb_wave_update (EffectInstance *effect)
void energy_orb_wave_render (EffectInstance *effect)
void energy_orb_wave_appendGfx (void *effect)
EffectInstance * energy_orb_wave_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00A4648 (void)
Variables
Gfx D_09001000_3A5320 []
Gfx D_090010A8_3A53C8 []
Gfx D_090011D0_3A54F0 []
Gfx D_090011F0_3A5510 []
Gfx D_09001210_3A5530 []
Function Documentation
energy_orb_wave_appendGfx()
void energy_orb_wave_appendGfx (void * effect)
Referenced by energy_orb_wave_render().
energy_orb_wave_init()
void energy_orb_wave_init (EffectInstance * effect)
Referenced by energy_orb_wave_main().
energy_orb_wave_main()
EffectInstance * energy_orb_wave_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
energy_orb_wave_render()
void energy_orb_wave_render (EffectInstance * effect)
Referenced by energy_orb_wave_main().
energy_orb_wave_update()
void energy_orb_wave_update (EffectInstance * effect)
Referenced by energy_orb_wave_main().
func_E00A4648()
void func_E00A4648 (void)
Variable Documentation
D_09001000_3A5320
Gfx D_09001000_3A5320[] extern
Referenced by energy_orb_wave_appendGfx().
D_090010A8_3A53C8
Gfx D_090010A8_3A53C8[] extern
Referenced by energy_orb_wave_appendGfx().
D_090011D0_3A54F0
Gfx D_090011D0_3A54F0[] extern
Referenced by energy_orb_wave_appendGfx().
D_090011F0_3A5510
Gfx D_090011F0_3A5510[] extern
Referenced by energy_orb_wave_appendGfx().
D_09001210_3A5530
Gfx D_09001210_3A5530[] extern
Referenced by energy_orb_wave_appendGfx().