papermario: src/entity.c File Reference
entity.c File Reference
Macros
#define WORLD_ENTITY_HEAP_BOTTOM 0x80250000
#define WORLD_ENTITY_HEAP_BASE 0x80267FF0
#define entity_jan_iwa_VRAM (void*) 0x802BAE00
#define entity_sbk_omo_VRAM (void*) 0x802BAE00
#define entity_default_VRAM (void*) 0x802BAE00
Functions
void update_shadows (void)
s32 step_entity_commandlist (Entity *entity)
void entity_swizzle_anim_pointers (EntityBlueprint *entityData, void *baseAnim, void *baseGfx)
void render_shadows (void)
void update_entity_transform_matrix (Entity *entity)
void update_shadow_transform_matrix (Shadow *shadow)
void update_entity_inverse_rotation_matrix (Entity *entity)
void delete_entity (s32 entityIndex)
void delete_entity_and_unload_data (s32 entityIndex)
void _delete_shadow (s32 shadowIndex)
void reload_world_entity_data (void)
s32 entity_get_collision_flags (Entity *entity)
void entity_free_static_data (EntityBlueprint *data)
s32 create_entity_shadow (Entity *entity, f32 x, f32 y, f32 z)
void update_entity_shadow_position (Entity *entity)
void update_entities (void)
void set_entity_commandlist (Entity *entity, s32 *entityScript)
void exec_entity_commandlist (Entity *entity)
void func_8010FD98 (void *arg0, s32 alpha)
void func_8010FE44 (void *arg0)
void entity_model_set_shadow_color (void *data)
void render_entities (void)
Entity * get_entity_by_index (s32 index)
Shadow * get_shadow_by_index (s32 index)
EntityList * get_entity_list (void)
ShadowList * get_shadow_list (void)
s32 entity_start_script (Entity *entity)
u32 get_entity_type (s32 index)
s32 entity_try_partner_interaction_trigger (s32 entityIdx)
s32 test_player_entity_aabb (Entity *entity)
s32 is_player_action_state (s8 actionState)
void entity_set_render_script (Entity *entity, EntityModelScript *cmdList)
void entity_reset_collision (Entity *entity)
void load_area_specific_entity_data (void)
void clear_entity_data (b32 arg0)
void init_entity_data (void)
s32 is_entity_data_loaded (Entity *entity, EntityBlueprint *blueprint, s32 *loadedStart, s32 *loadedEnd)
void load_simple_entity_data (Entity *entity, EntityBlueprint *bp, s32 listIndex)
void load_split_entity_data (Entity *entity, EntityBlueprint *entityData, s32 listIndex)
s32 func_80111790 (EntityBlueprint *data)
s32 create_entity (EntityBlueprint *bp,...)
s32 create_shadow_from_data (ShadowBlueprint *bp, f32 x, f32 y, f32 z)
s32 create_shadow_type (s32 type, f32 x, f32 y, f32 z)
void delete_shadow (s32 shadowIndex)
s32 entity_raycast_down (f32 *x, f32 *y, f32 *z, f32 *hitYaw, f32 *hitPitch, f32 *hitLength)
void set_standard_shadow_scale (Shadow *shadow, f32 height)
void set_npc_shadow_scale (Shadow *shadow, f32 height, f32 npcRadius)
void set_peach_shadow_scale (Shadow *shadow, f32 scale)
s32 is_block_on_ground (Entity *block)
Variables
s32 D_8014AFB0 = 255
s32 CreateEntityVarArgBuffer [4]
HiddenPanelsData gCurrentHiddenPanels
s32 gEntityHideMode
s32 D_801512BC
s32 D_80151304
s32 D_80151344
s32 entity_numEntities
s32 gEntityHeapBase
s32 gLastCreatedEntityIndex
s32 gEntityHeapBottom
s32 entity_numShadows
s32 isAreaSpecificEntityDataLoaded
s32 entity_updateCounter
BSS EntityList gWorldEntityList
BSS EntityList gBattleEntityList
BSS EntityList * gCurrentEntityListPtr
BSS s32 D_80151474
BSS ShadowList gWorldShadowList
BSS ShadowList gBattleShadowList
BSS ShadowList * gCurrentShadowListPtr
BSS s32 wEntityDataLoadedSize
BSS s32 bEntityDataLoadedSize
BSS s32 D_80151664
BSS EntityBlueprint * wEntityBlueprint [MAX_ENTITIES+2]
BSS EntityBlueprint * bEntityBlueprint [4]
BSS s32 D_801516F8
BSS s32 D_801516FC
Addr BattleEntityHeapBottom
Macro Definition Documentation
entity_default_VRAM
#define entity_default_VRAM (void*) 0x802BAE00
entity_jan_iwa_VRAM
#define entity_jan_iwa_VRAM (void*) 0x802BAE00
entity_sbk_omo_VRAM
#define entity_sbk_omo_VRAM (void*) 0x802BAE00
WORLD_ENTITY_HEAP_BASE
#define WORLD_ENTITY_HEAP_BASE 0x80267FF0
Referenced by clear_entity_data(), and init_entity_data().
WORLD_ENTITY_HEAP_BOTTOM
#define WORLD_ENTITY_HEAP_BOTTOM 0x80250000
Referenced by clear_entity_data(), and init_entity_data().
Function Documentation
_delete_shadow()
void _delete_shadow (s32 shadowIndex)
Referenced by delete_shadow(), and update_shadows().
clear_entity_data()
void clear_entity_data (b32 arg0)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_title_screen().
create_entity()
s32 create_entity (EntityBlueprint * bp, ...)
Referenced by entity_breakable_block_create_shattering_entity(), entity_HeartBlock_create_child_entity(), entity_ItemBlock_check_if_inactive(), entity_ItemBlock_replace_with_inactive(), entity_MulticoinBlock_check_if_inactive(), entity_MulticoinBlock_idle(), entity_MulticoinBlock_spawn_coin(), entity_Munchlesia_create_child(), entity_PinkFlower_init(), and entity_upgrade_block_check_if_inactive().
create_entity_shadow()
s32 create_entity_shadow (Entity * entity, f32 x, f32 y, f32 z)
Referenced by create_entity().
create_shadow_from_data()
s32 create_shadow_from_data (ShadowBlueprint * bp, f32 x, f32 y, f32 z)
Referenced by create_shadow_type().
create_shadow_type()
s32 create_shadow_type (s32 type, f32 x, f32 y, f32 z)
Referenced by create_actor(), create_entity_shadow(), create_npc_impl(), create_part_shadow(), create_part_shadow_by_ref(), load_partner_actor(), load_player_actor(), make_item_entity(), make_item_entity_at_player(), and player_reset_data().
delete_entity()
void delete_entity (s32 entityIndex)
Referenced by update_entities().
delete_entity_and_unload_data()
void delete_entity_and_unload_data (s32 entityIndex)
Referenced by update_entities().
delete_shadow()
void delete_shadow (s32 shadowIndex)
Referenced by btl_delete_actor(), btl_delete_player_actor(), free_npc(), free_npc_by_index(), remove_item_entity_by_index(), remove_item_entity_by_reference(), and remove_part_shadow().
entity_free_static_data()
void entity_free_static_data (EntityBlueprint * data)
Referenced by delete_entity_and_unload_data().
entity_get_collision_flags()
s32 entity_get_collision_flags (Entity * entity)
Referenced by update_entities().
entity_model_set_shadow_color()
void entity_model_set_shadow_color (void * data)
Referenced by render_shadows().
entity_raycast_down()
s32 entity_raycast_down (f32 * x, f32 * y, f32 * z, f32 * hitYaw, f32 * hitPitch, f32 * hitLength)
Referenced by entity_switch_fall_down(), is_block_on_ground(), update_entity_shadow_position(), and update_npcs().
entity_reset_collision()
void entity_reset_collision (Entity * entity)
entity_set_render_script()
void entity_set_render_script (Entity * entity, EntityModelScript * cmdList)
Referenced by Entity_BoardedFloor_shatter(), entity_HeartBlock_change_render_script(), entity_HeartBlockContent__anim_heal(), entity_HeartBlockContent_reset(), entity_HiddenPanel_init(), and entity_WoodenCrate_idle().
entity_start_script()
s32 entity_start_script (Entity * entity)
Referenced by action_update_use_tweester(), entity_ArrowSign_handle_collision(), entity_base_switch_start_bound_script(), entity_block_handle_collision(), entity_BlueWarpPipe_start_bound_script(), Entity_BoardedFloor_idle(), entity_BombableRock_idle(), entity_Chest_start_bound_script(), entity_GreenStompSwitch_retract(), entity_Padlock_idle(), entity_ScriptSpring_idle(), entity_Signpost_idle(), entity_SimpleSpring_idle(), entity_StarBoxLauncher_start_script(), entity_TriggerBlock_start_bound_script_2(), and entity_WoodenCrate_idle().
entity_swizzle_anim_pointers()
void entity_swizzle_anim_pointers (EntityBlueprint * entityData, void * baseAnim, void * baseGfx)
Referenced by load_split_entity_data(), and reload_world_entity_data().
entity_try_partner_interaction_trigger()
s32 entity_try_partner_interaction_trigger (s32 entityIdx)
Referenced by blast_affect_entities(), lateral_hit_interactable_entity(), and vertical_hit_interactable_entity().
exec_entity_commandlist()
void exec_entity_commandlist (Entity * entity)
Referenced by action_update_use_spinning_flower(), entity_base_switch_animate_scale(), entity_BellbellPlant_idle(), entity_block_handle_collision(), entity_BlueWarpPipe_check_if_active(), entity_BlueWarpPipe_enter_pipe_update(), entity_BlueWarpPipe_idle(), entity_BlueWarpPipe_rise_up(), entity_BlueWarpPipe_wait_for_player_to_get_off(), entity_BlueWarpPipe_wait_player_move_to_center(), Entity_BoardedFloor_idle(), Entity_BoardedFloor_update_fragments(), entity_BombableRock_idle(), entity_BombableRock_update_fragments(), entity_Chest_idle(), entity_Chest_open(), entity_GiantChest_await_got_item(), entity_GiantChest_open(), entity_GreenStompSwitch_extend(), entity_GreenStompSwitch_idle(), entity_GreenStompSwitch_retract(), entity_HeartBlock_show_tutorial_message(), entity_HeartBlock_wait_for_close_tutorial(), entity_HeartBlockContent__anim_heal(), entity_HeartBlockContent_anim_idle(), entity_HiddenPanel_flip_over(), entity_HiddenPanel_idle(), entity_HugeBlueSwitch_idle(), entity_inactive_block_hit_anim(), entity_inactive_block_recoil_anim(), entity_ItemBlock_check_if_inactive(), entity_MulticoinBlock_idle(), entity_Padlock_idle(), entity_PinkFlower_idle(), entity_RedSwitch_animate_scale(), entity_RedSwitch_wait_and_reset(), entity_SaveBlock_show_tutorial_message(), entity_SaveBlock_wait_for_close_choice(), entity_SaveBlock_wait_for_close_result(), entity_SaveBlock_wait_for_close_tutorial(), entity_ScriptSpring_idle(), entity_shattering_idle(), entity_SimpleSpring_idle(), entity_small_switch_idle(), entity_StarBoxLauncher_check_launch(), entity_StarBoxLauncher_launch(), entity_TrumpetPlant_idle(), entity_WoodenCrate_idle(), entity_WoodenCrate_update_fragments(), func_802BB0A0_E2D9D0(), func_802BC050_E2E980(), and func_802BC99C_E312EC().
func_8010FD98()
void func_8010FD98 (void * arg0, s32 alpha)
Referenced by func_8010FE44().
func_8010FE44()
void func_8010FE44 (void * arg0)
Referenced by render_entities().
func_80111790()
s32 func_80111790 (EntityBlueprint * data)
Referenced by entity_free_static_data().
get_entity_by_index()
Entity * get_entity_by_index (s32 index)
Referenced by action_hammer_end_swing(), action_update_landing_on_switch(), action_update_spin_jump(), action_update_tornado_jump(), action_update_use_spinning_flower(), check_for_interactables(), check_input_jump(), delete_entity(), delete_entity_and_unload_data(), entity_ArrowSign_setupGfx(), entity_base_block_setupGfx(), entity_BlueWarpPipe_setupGfx(), Entity_BoardedFloor_setupGfx(), entity_BombableRock_setupGfx(), entity_Chest_setupGfx(), entity_HeartBlock_create_child_entity(), entity_HeartBlockContent__reset(), entity_HeartBlockContent__setupGfx(), entity_HeartBlockContent_anim_idle(), entity_HeartBlockContent_set_initial_pos(), entity_HiddenPanel_setupGfx(), entity_HitItemBlock_show_inactive(), entity_ItemBlock_replace_with_inactive(), entity_ItemBlock_setupGfx(), entity_MulticoinBlock_spawn_coin(), entity_Padlock_setupGfx(), entity_PinkFlower_idle(), entity_PinkFlower_init(), entity_PinkFlowerLight_idle(), entity_PinkFlowerLight_setupGfx(), entity_SaveBlock_setupGfx(), entity_shattering_setupGfx(), entity_SpinningFlower_setupGfx(), entity_StarBoxLauncher_setupGfx(), entity_SuperBlockContent_attach_to_parent(), entity_SuperBlockContent_setupGfx(), entity_try_partner_interaction_trigger(), entity_Tweester_render_face(), entity_Tweester_render_inner_whirl(), entity_Tweester_render_outer_whirl(), entity_Tweester_setupGfx(), entity_upgrade_block_check_if_inactive(), entity_upgrade_block_hide_content(), entity_WoodenCrate_setupGfx(), func_802BC050_E2E980(), get_entity_type(), interact_inspect_update(), npc_find_standing_on_entity(), phys_player_land(), player_raycast_down(), player_raycast_general(), player_raycast_up_corner(), render_entities(), test_ray_entities(), and update_entities().
get_entity_list()
EntityList * get_entity_list (void)
Referenced by clear_entity_data(), and init_entity_data().
get_entity_type()
u32 get_entity_type (s32 index)
Referenced by action_hammer_test_swing_collision(), action_update_spin_jump(), action_update_tornado_jump(), can_dismount(), check_for_interactables(), collision_main_above(), entity_block_handle_collision(), entity_block_hit_animate_scale(), entity_block_hit_init_scale(), entity_breakable_block_create_shattering_entity(), entity_HitItemBlock_play_anim(), entity_ItemBlock_check_if_inactive(), entity_ItemBlock_replace_with_inactive(), entity_raycast_down(), entity_shattering_block_init(), entity_StarBoxLauncher_check_launch(), entity_try_partner_interaction_trigger(), func_800E06D8(), func_800EA4B0(), load_simple_entity_data(), load_split_entity_data(), phys_main_collision_below(), phys_player_land(), and should_continue_inspect().
get_shadow_by_index()
Shadow * get_shadow_by_index (s32 index)
Referenced by _delete_shadow(), calculate_camera_yinterp_rate(), create_entity_shadow(), create_shadow_type(), delete_entity(), delete_entity_and_unload_data(), disable_npc_shadow(), disable_player_shadow(), enable_npc_shadow(), enable_player_shadow(), end_outta_sight_cleanup(), entity_base_block_update_slow_sinking(), entity_HitItemBlock_hide(), entity_HitItemBlock_show_inactive(), entity_ItemBlock_replace_with_inactive(), hide_item_entity(), make_item_entity(), make_item_entity_at_player(), npc_get_collider_below(), phys_is_on_sloped_ground(), phys_should_player_be_sliding(), render_shadows(), reveal_item_entity(), spawn_drops(), test_reflection_worker_render_floor(), test_reflection_worker_render_wall(), update_entity_shadow_position(), update_item_entities(), update_nonplayer_actor_shadow(), update_npcs(), update_player_actor_shadow(), update_player_shadow(), update_shadows(), worker_reflect_player_floor(), worker_reflect_player_wall(), and worker_render_player_reflection().
get_shadow_list()
ShadowList * get_shadow_list (void)
Referenced by clear_entity_data(), and init_entity_data().
init_entity_data()
void init_entity_data (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
is_block_on_ground()
s32 is_block_on_ground (Entity * block)
Referenced by entity_base_block_idle(), entity_ItemBlock_replace_with_inactive(), and entity_shattering_init_pieces().
is_entity_data_loaded()
s32 is_entity_data_loaded (Entity * entity, EntityBlueprint * blueprint, s32 * loadedStart, s32 * loadedEnd)
Referenced by load_simple_entity_data(), and load_split_entity_data().
is_player_action_state()
s32 is_player_action_state (s8 actionState)
load_area_specific_entity_data()
void load_area_specific_entity_data (void)
Referenced by create_entity().
load_simple_entity_data()
void load_simple_entity_data (Entity * entity, EntityBlueprint * bp, s32 listIndex)
Referenced by create_entity().
load_split_entity_data()
void load_split_entity_data (Entity * entity, EntityBlueprint * entityData, s32 listIndex)
Referenced by create_entity().
reload_world_entity_data()
void reload_world_entity_data (void)
Referenced by init_entity_data().
render_entities()
void render_entities (void)
Referenced by render_frame().
render_shadows()
void render_shadows (void)
Referenced by render_entities().
set_entity_commandlist()
void set_entity_commandlist (Entity * entity, s32 * entityScript)
Referenced by entity_block_handle_collision(), entity_Chest_check_opened(), entity_ItemBlock_check_if_inactive(), entity_MulticoinBlock_spawn_coin(), and entity_SaveBlock_wait_for_close_choice().
set_npc_shadow_scale()
void set_npc_shadow_scale (Shadow * shadow, f32 height, f32 npcRadius)
Referenced by update_npcs().
set_peach_shadow_scale()
void set_peach_shadow_scale (Shadow * shadow, f32 scale)
Referenced by update_player_shadow().
set_standard_shadow_scale()
void set_standard_shadow_scale (Shadow * shadow, f32 height)
Referenced by make_item_entity(), make_item_entity_at_player(), update_item_entities(), update_nonplayer_actor_shadow(), update_player_actor_shadow(), and update_player_shadow().
step_entity_commandlist()
s32 step_entity_commandlist (Entity * entity)
Referenced by exec_entity_commandlist(), and update_entities().
test_player_entity_aabb()
s32 test_player_entity_aabb (Entity * entity)
update_entities()
void update_entities (void)
Referenced by step_game_loop().
update_entity_inverse_rotation_matrix()
void update_entity_inverse_rotation_matrix (Entity * entity)
Referenced by update_entities().
update_entity_shadow_position()
void update_entity_shadow_position (Entity * entity)
Referenced by update_entities().
update_entity_transform_matrix()
void update_entity_transform_matrix (Entity * entity)
Referenced by create_entity(), and update_entities().
update_shadow_transform_matrix()
void update_shadow_transform_matrix (Shadow * shadow)
Referenced by create_shadow_from_data(), and update_shadows().
update_shadows()
void update_shadows (void)
Referenced by update_entities().
Variable Documentation
BattleEntityHeapBottom
BSS u8 BattleEntityHeapBottom extern
Referenced by clear_entity_data(), and init_entity_data().
bEntityBlueprint
BSS EntityBlueprint* bEntityBlueprint[4]
Referenced by clear_entity_data(), init_entity_data(), and is_entity_data_loaded().
bEntityDataLoadedSize
BSS s32 bEntityDataLoadedSize
Referenced by clear_entity_data(), load_simple_entity_data(), and load_split_entity_data().
CreateEntityVarArgBuffer
s32 CreateEntityVarArgBuffer[4]
Referenced by create_entity(), entity_ArrowSign_init(), entity_BlueSwitch_init(), entity_Chest_readargs(), entity_HeartBlock_create_child_entity(), entity_HiddenPanel_init(), entity_init_BlueWarpPipe(), entity_ItemBlock_init(), entity_SimpleSpring_init(), entity_SpinningFlower_init(), entity_Tweester_init(), and entity_WoodenCrate_init().
D_8014AFB0
s32 D_8014AFB0 = 255
Referenced by clear_entity_data(), func_8010FE44(), and render_entities().
D_801512BC
s32 D_801512BC
Referenced by update_entities().
D_80151304
s32 D_80151304
Referenced by clear_entity_data().
D_80151344
s32 D_80151344
Referenced by clear_entity_data().
D_80151474
BSS s32 D_80151474
D_80151664
BSS s32 D_80151664
D_801516F8
BSS s32 D_801516F8
D_801516FC
BSS s32 D_801516FC
Referenced by clear_entity_data().
entity_numEntities
s32 entity_numEntities
Referenced by clear_entity_data(), init_entity_data(), and update_entities().
entity_numShadows
s32 entity_numShadows
Referenced by clear_entity_data(), init_entity_data(), and update_shadows().
entity_updateCounter
s32 entity_updateCounter
Referenced by clear_entity_data(), and update_entities().
gBattleEntityList
BSS EntityList gBattleEntityList
Referenced by get_entity_list().
gBattleShadowList
BSS ShadowList gBattleShadowList
Referenced by get_shadow_list().
gCurrentEntityListPtr
BSS EntityList* gCurrentEntityListPtr
Referenced by clear_entity_data(), create_entity(), delete_entity(), delete_entity_and_unload_data(), func_80111790(), get_entity_by_index(), and init_entity_data().
gCurrentHiddenPanels
HiddenPanelsData gCurrentHiddenPanels
Referenced by action_hammer_end_swing(), action_update_spin_jump(), action_update_tornado_jump(), check_for_ispy(), clear_entity_data(), entity_HiddenPanel_idle(), entity_HiddenPanel_init(), entity_HiddenPanel_set_ispy_notification(), ispy_notification_update(), and update_entities().
gCurrentShadowListPtr
BSS ShadowList* gCurrentShadowListPtr
Referenced by _delete_shadow(), clear_entity_data(), create_shadow_from_data(), get_shadow_by_index(), and init_entity_data().
gEntityHeapBase
s32 gEntityHeapBase
Referenced by clear_entity_data(), init_entity_data(), load_simple_entity_data(), load_split_entity_data(), and reload_world_entity_data().
gEntityHeapBottom
s32 gEntityHeapBottom
Referenced by clear_entity_data(), init_entity_data(), load_split_entity_data(), and reload_world_entity_data().
gEntityHideMode
s32 gEntityHideMode
Referenced by clear_entity_data(), and render_entities().
gLastCreatedEntityIndex
s32 gLastCreatedEntityIndex
gWorldEntityList
BSS EntityList gWorldEntityList
Referenced by get_entity_list().
gWorldShadowList
BSS ShadowList gWorldShadowList
Referenced by get_shadow_list().
isAreaSpecificEntityDataLoaded
s32 isAreaSpecificEntityDataLoaded
Referenced by clear_entity_data(), and load_area_specific_entity_data().
wEntityBlueprint
BSS EntityBlueprint* wEntityBlueprint[MAX_ENTITIES+2]
Referenced by clear_entity_data(), entity_free_static_data(), is_entity_data_loaded(), and reload_world_entity_data().
wEntityDataLoadedSize
BSS s32 wEntityDataLoadedSize
Referenced by clear_entity_data(), entity_free_static_data(), load_simple_entity_data(), and load_split_entity_data().