papermario: src/entity_model.c File Reference
entity_model.c File Reference
Functions
s32 step_entity_model_commandlist (EntityModel *entityModel)
void free_entity_model_by_ref (EntityModel *entityModel)
void clear_entity_models (void)
void init_entity_models (void)
s32 load_entity_model (EntityModelScript *cmdList)
s32 ALT_load_entity_model (EntityModelScript *cmdList)
void exec_entity_model_commandlist (s32 idx)
void make_entity_model_mtx_flipZ (Matrix4f mtx)
void appendGfx_entity_model (EntityModel *model)
void draw_entity_model_A (s32 modelIdx, Mtx *transformMtx)
void draw_entity_model_B (s32 modelIdx, Mtx *transformMtx, s32 vertexSegment, Vec3s *vertexArray)
void draw_entity_model_C (s32 modelIdx, Mtx *transformMtx)
void draw_entity_model_D (s32 modelIdx, Mtx *transformMtx, s32 arg2, Vec3s *vertexArray)
void draw_entity_model_E (s32 modelIdx, Mtx *transformMtx)
void set_entity_model_render_command_list (s32 idx, EntityModelScript *cmdList)
EntityModel * get_entity_model (s32 listIndex)
void free_entity_model_by_index (s32 idx)
void set_entity_model_flags (s32 idx, s32 newFlags)
void clear_entity_model_flags (s32 idx, s32 newFlags)
void bind_entity_model_setupGfx (s32 idx, void *setupGfxCallbackArg0, void(*fpSetupGfxCallback)(void *))
void func_80122F8C (s32 idx, s32 newFlags)
void func_80122FB8 (s32 idx, s32 newFlags)
void enable_entity_fog (void)
void disable_entity_fog (void)
void set_entity_fog_dist (s32 min, s32 max)
void set_entity_fog_color (s32 r, s32 g, s32 b, s32 a)
s32 is_entity_fog_enabled (void)
void get_entity_fog_distance (s32 *start, s32 *end)
void get_entity_fog_color (s32 *r, s32 *g, s32 *b, s32 *a)
Variables
EntityModelScript D_8014C260
Lights1 D_8014C268 = gdSPDefLights1(255, 255, 255, 0, 0, 0, 0, 0, 0)
s32 gEntityModelCount
BSS EntityModelList gWorldEntityModelList
BSS EntityModelList gBattleEntityModelList
BSS EntityModelList * gCurrentEntityModelList
BSS s32 D_80154374
BSS s32 entity_fog_enabled
BSS s32 entity_fog_red
BSS s32 entity_fog_green
BSS s32 entity_fog_blue
BSS s32 entity_fog_alpha
BSS s32 entity_fog_dist_min
BSS s32 entity_fog_dist_max
Gfx Gfx_RM1_SURFACE_OPA []
Gfx Gfx_RM1_DECAL_OPA []
Gfx Gfx_RM1_INTERSECTING_OPA []
Gfx Gfx_RM1_ALPHATEST []
Gfx Gfx_RM1_SURFACE_XLU []
Gfx Gfx_RM1_DECAL_XLU []
Gfx Gfx_RM1_INTERSECTING_XLU []
Gfx Gfx_RM1_ALPHATEST_ONESIDED []
Gfx Gfx_RM1_SURFACE_XLU_NO_AA []
Gfx Gfx_RM1_DECAL_XLU_NO_AA []
Gfx Gfx_RM1_PASS_THROUGH []
Gfx Gfx_RM1_SURFACE_OPA_NO_ZB []
Gfx Gfx_RM1_ALPHATEST_NO_ZB []
Gfx Gfx_RM1_SURFACE_XLU_NO_ZB []
Gfx Gfx_RM1_CLOUD_NO_ZCMP []
Gfx Gfx_RM3_SURFACE_OPA []
Gfx Gfx_RM3_DECAL_OPA []
Gfx Gfx_RM3_INTERSECTING_OPA []
Gfx Gfx_RM3_ALPHATEST []
Gfx Gfx_RM3_SURFACE_XLU []
Gfx Gfx_RM3_DECAL_XLU []
Gfx Gfx_RM3_INTERSECTING_XLU []
Function Documentation
ALT_load_entity_model()
s32 ALT_load_entity_model (EntityModelScript * cmdList)
Referenced by ALT_virtual_entity_create().
appendGfx_entity_model()
void appendGfx_entity_model (EntityModel * model)
Referenced by draw_entity_model_A(), draw_entity_model_B(), draw_entity_model_C(), and draw_entity_model_D().
bind_entity_model_setupGfx()
void bind_entity_model_setupGfx (s32 idx, void * setupGfxCallbackArg0, void(*)(void *) fpSetupGfxCallback)
Referenced by render_entities(), render_shadows(), and show_immune_bonk().
clear_entity_model_flags()
void clear_entity_model_flags (s32 idx, s32 newFlags)
Referenced by btl_bonk_update().
clear_entity_models()
void clear_entity_models (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_title_screen().
disable_entity_fog()
void disable_entity_fog (void)
draw_entity_model_A()
void draw_entity_model_A (s32 modelIdx, Mtx * transformMtx)
Referenced by btl_bonk_render(), render_entities(), render_shadows(), and virtual_entity_list_render_world().
draw_entity_model_B()
void draw_entity_model_B (s32 modelIdx, Mtx * transformMtx, s32 vertexSegment, Vec3s * vertexArray)
Referenced by render_entities(), and render_shadows().
draw_entity_model_C()
void draw_entity_model_C (s32 modelIdx, Mtx * transformMtx)
draw_entity_model_D()
void draw_entity_model_D (s32 modelIdx, Mtx * transformMtx, s32 arg2, Vec3s * vertexArray)
draw_entity_model_E()
void draw_entity_model_E (s32 modelIdx, Mtx * transformMtx)
Referenced by virtual_entity_list_render_UI().
enable_entity_fog()
void enable_entity_fog (void)
exec_entity_model_commandlist()
void exec_entity_model_commandlist (s32 idx)
Referenced by ALT_virtual_entity_create(), btl_bonk_update(), create_entity(), update_entities(), update_shadows(), virtual_entity_create(), virtual_entity_create_at_index(), and virtual_entity_list_update().
free_entity_model_by_index()
void free_entity_model_by_index (s32 idx)
Referenced by _delete_shadow(), btl_bonk_update(), delete_entity(), delete_entity_and_unload_data(), free_entity_model_by_ref(), and virtual_entity_delete_by_index().
free_entity_model_by_ref()
void free_entity_model_by_ref (EntityModel * entityModel)
Referenced by step_entity_model_commandlist().
func_80122F8C()
void func_80122F8C (s32 idx, s32 newFlags)
func_80122FB8()
void func_80122FB8 (s32 idx, s32 newFlags)
get_entity_fog_color()
void get_entity_fog_color (s32 * r, s32 * g, s32 * b, s32 * a)
get_entity_fog_distance()
void get_entity_fog_distance (s32 * start, s32 * end)
get_entity_model()
EntityModel * get_entity_model (s32 listIndex)
Referenced by render_entities(), test_reflection_worker_render_floor(), test_reflection_worker_render_wall(), update_npcs(), virtual_entity_list_render_UI(), virtual_entity_list_render_world(), worker_reflect_player_floor(), worker_reflect_player_wall(), and worker_render_player_reflection().
init_entity_models()
void init_entity_models (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
is_entity_fog_enabled()
s32 is_entity_fog_enabled (void)
load_entity_model()
s32 load_entity_model (EntityModelScript * cmdList)
Referenced by create_entity(), create_shadow_from_data(), show_immune_bonk(), virtual_entity_create(), and virtual_entity_create_at_index().
make_entity_model_mtx_flipZ()
void make_entity_model_mtx_flipZ (Matrix4f mtx)
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
set_entity_fog_color()
void set_entity_fog_color (s32 r, s32 g, s32 b, s32 a)
set_entity_fog_dist()
void set_entity_fog_dist (s32 min, s32 max)
set_entity_model_flags()
void set_entity_model_flags (s32 idx, s32 newFlags)
Referenced by show_immune_bonk().
set_entity_model_render_command_list()
void set_entity_model_render_command_list (s32 idx, EntityModelScript * cmdList)
Referenced by entity_set_render_script().
step_entity_model_commandlist()
s32 step_entity_model_commandlist (EntityModel * entityModel)
Referenced by exec_entity_model_commandlist().
Variable Documentation
D_8014C260
EntityModelScript D_8014C260
Initial value:
= {
    ems_End
    ems_End
}
Referenced by ALT_load_entity_model(), load_entity_model(), and set_entity_model_render_command_list().
D_8014C268
Lights1 D_8014C268 = gdSPDefLights1(255, 255, 255, 0, 0, 0, 0, 0, 0)
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
D_80154374
BSS s32 D_80154374
Referenced by appendGfx_entity_model(), draw_entity_model_B(), draw_entity_model_D(), and draw_entity_model_E().
entity_fog_alpha
BSS s32 entity_fog_alpha
Referenced by appendGfx_entity_model(), clear_entity_models(), draw_entity_model_E(), get_entity_fog_color(), init_entity_models(), and set_entity_fog_color().
entity_fog_blue
BSS s32 entity_fog_blue
Referenced by appendGfx_entity_model(), clear_entity_models(), draw_entity_model_E(), get_entity_fog_color(), init_entity_models(), and set_entity_fog_color().
entity_fog_dist_max
BSS s32 entity_fog_dist_max
Referenced by appendGfx_entity_model(), clear_entity_models(), draw_entity_model_E(), get_entity_fog_distance(), init_entity_models(), and set_entity_fog_dist().
entity_fog_dist_min
BSS s32 entity_fog_dist_min
Referenced by appendGfx_entity_model(), clear_entity_models(), draw_entity_model_E(), get_entity_fog_distance(), init_entity_models(), and set_entity_fog_dist().
entity_fog_enabled
BSS s32 entity_fog_enabled
Referenced by appendGfx_entity_model(), clear_entity_models(), disable_entity_fog(), draw_entity_model_E(), enable_entity_fog(), init_entity_models(), and is_entity_fog_enabled().
entity_fog_green
BSS s32 entity_fog_green
Referenced by appendGfx_entity_model(), clear_entity_models(), draw_entity_model_E(), get_entity_fog_color(), init_entity_models(), and set_entity_fog_color().
entity_fog_red
BSS s32 entity_fog_red
Referenced by appendGfx_entity_model(), clear_entity_models(), draw_entity_model_E(), get_entity_fog_color(), init_entity_models(), and set_entity_fog_color().
gBattleEntityModelList
BSS EntityModelList gBattleEntityModelList
Referenced by clear_entity_models(), and init_entity_models().
gCurrentEntityModelList
BSS EntityModelList* gCurrentEntityModelList
Referenced by ALT_load_entity_model(), clear_entity_models(), free_entity_model_by_index(), free_entity_model_by_ref(), get_entity_model(), init_entity_models(), and load_entity_model().
gEntityModelCount
s32 gEntityModelCount
Referenced by ALT_load_entity_model(), clear_entity_models(), free_entity_model_by_index(), init_entity_models(), and load_entity_model().
Gfx_RM1_ALPHATEST
Gfx Gfx_RM1_ALPHATEST[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_ALPHATEST_NO_ZB
Gfx Gfx_RM1_ALPHATEST_NO_ZB extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_TEX_EDGE, G_RM_AA_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_ALPHATEST_ONESIDED
Gfx Gfx_RM1_ALPHATEST_ONESIDED extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_TEX_EDGE, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_CLOUD_NO_ZCMP
Gfx Gfx_RM1_CLOUD_NO_ZCMP extern
Initial value:
= {
    gsDPSetRenderMode(IM_RD | CVG_DST_SAVE | ZMODE_XLU | FORCE_BL |
                      GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA),
                      IM_RD | CVG_DST_SAVE | ZMODE_XLU | FORCE_BL |
                      GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_DECAL_OPA
Gfx Gfx_RM1_DECAL_OPA[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_DECAL_XLU
Gfx Gfx_RM1_DECAL_XLU[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_DECAL_XLU_NO_AA
Gfx Gfx_RM1_DECAL_XLU_NO_AA extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_ZB_OVL_SURF, G_RM_ZB_OVL_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_INTERSECTING_OPA
Gfx Gfx_RM1_INTERSECTING_OPA[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_INTERSECTING_XLU
Gfx Gfx_RM1_INTERSECTING_XLU[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_PASS_THROUGH
Gfx Gfx_RM1_PASS_THROUGH extern
Initial value:
= {
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_OPA
Gfx Gfx_RM1_SURFACE_OPA[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_OPA_NO_ZB
Gfx Gfx_RM1_SURFACE_OPA_NO_ZB extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_OPA_SURF, G_RM_AA_OPA_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_XLU
Gfx Gfx_RM1_SURFACE_XLU[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_XLU_NO_AA
Gfx Gfx_RM1_SURFACE_XLU_NO_AA extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_ZB_XLU_SURF, G_RM_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_XLU_NO_ZB
Gfx Gfx_RM1_SURFACE_XLU_NO_ZB extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_XLU_SURF, G_RM_AA_XLU_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_ALPHATEST
Gfx Gfx_RM3_ALPHATEST[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_DECAL_OPA
Gfx Gfx_RM3_DECAL_OPA[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_DECAL_XLU
Gfx Gfx_RM3_DECAL_XLU[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_INTERSECTING_OPA
Gfx Gfx_RM3_INTERSECTING_OPA[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_INTERSECTING_XLU
Gfx Gfx_RM3_INTERSECTING_XLU[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_SURFACE_OPA
Gfx Gfx_RM3_SURFACE_OPA[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_SURFACE_XLU
Gfx Gfx_RM3_SURFACE_XLU[] extern
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
gWorldEntityModelList
BSS EntityModelList gWorldEntityModelList
Referenced by clear_entity_models(), and init_entity_models().