papermario: src/evt/evt.c File Reference
evt.c File Reference
Functions
Bytecode * evt_find_label (Evt *script, s32 arg1)
Bytecode * evt_skip_if (Evt *script)
Bytecode * evt_skip_else (Evt *script)
Bytecode * evt_goto_end_case (Evt *script)
Bytecode * evt_goto_next_case (Evt *script)
Bytecode * evt_goto_end_loop (Evt *script)
f32 evt_fixed_var_to_float (Bytecode scriptVar)
Bytecode evt_float_to_fixed_var (f32 value)
ApiStatus evt_handle_return (Evt *script)
ApiStatus evt_handle_label (Evt *script)
ApiStatus evt_handle_goto (Evt *script)
ApiStatus evt_handle_loop (Evt *script)
ApiStatus evt_handle_end_loop (Evt *script)
ApiStatus evt_handle_break_loop (Evt *script)
ApiStatus evt_handle_wait (Evt *script)
ApiStatus evt_handle_wait_seconds (Evt *script)
ApiStatus evt_handle_if_equal (Evt *script)
ApiStatus evt_handle_if_not_equal (Evt *script)
ApiStatus evt_handle_if_less (Evt *script)
ApiStatus evt_handle_if_greater (Evt *script)
ApiStatus evt_handle_if_less_equal (Evt *script)
ApiStatus evt_handle_if_greater_equal (Evt *script)
ApiStatus evt_handle_if_AND (Evt *script)
ApiStatus evt_handle_if_not_AND (Evt *script)
ApiStatus evt_handle_else (Evt *script)
ApiStatus evt_handle_end_if (Evt *script)
ApiStatus evt_handle_switch (Evt *script)
ApiStatus evt_handle_switch_const (Evt *script)
ApiStatus evt_handle_case_equal (Evt *script)
ApiStatus evt_handle_case_not_equal (Evt *script)
ApiStatus evt_handle_case_less (Evt *script)
ApiStatus evt_handle_case_less_equal (Evt *script)
ApiStatus evt_handle_case_greater (Evt *script)
ApiStatus evt_handle_case_greater_equal (Evt *script)
ApiStatus evt_handle_case_range (Evt *script)
ApiStatus evt_handle_case_default (Evt *script)
ApiStatus evt_handle_case_AND (Evt *script)
ApiStatus evt_handle_case_equal_OR (Evt *script)
ApiStatus evt_handle_case_equal_AND (Evt *script)
ApiStatus evt_handle_end_case_group (Evt *script)
ApiStatus evt_handle_break_case (Evt *script)
ApiStatus evt_handle_end_switch (Evt *script)
ApiStatus evt_handle_set_var (Evt *script)
ApiStatus evt_handle_set_const (Evt *script)
ApiStatus evt_handle_set_float (Evt *script)
ApiStatus evt_handle_add (Evt *script)
ApiStatus evt_handle_subtract (Evt *script)
ApiStatus evt_handle_multiply (Evt *script)
ApiStatus evt_handle_divide (Evt *script)
ApiStatus evt_handle_mod (Evt *script)
ApiStatus evt_handle_addF (Evt *script)
ApiStatus evt_handle_subtractF (Evt *script)
ApiStatus evt_handle_multiplyF (Evt *script)
ApiStatus evt_handle_divideF (Evt *script)
ApiStatus evt_handle_set_int_buffer_ptr (Evt *script)
ApiStatus evt_handle_set_float_buffer_ptr (Evt *script)
ApiStatus evt_handle_get_1_word (Evt *script)
ApiStatus evt_handle_get_2_word (Evt *script)
ApiStatus evt_handle_get_3_word (Evt *script)
ApiStatus evt_handle_get_4_word (Evt *script)
ApiStatus evt_handle_get_Nth_word (Evt *script)
ApiStatus evt_handle_get_1_float (Evt *script)
ApiStatus evt_handle_get_2_float (Evt *script)
ApiStatus evt_handle_get_3_float (Evt *script)
ApiStatus evt_handle_get_4_float (Evt *script)
ApiStatus evt_handle_get_Nth_float (Evt *script)
ApiStatus evt_handle_set_array (Evt *script)
ApiStatus evt_handle_set_flag_array (Evt *script)
ApiStatus evt_handle_allocate_array (Evt *script)
ApiStatus evt_handle_AND (Evt *script)
ApiStatus evt_handle_AND_const (Evt *script)
ApiStatus evt_handle_OR (Evt *script)
ApiStatus evt_handle_OR_const (Evt *script)
ApiStatus evt_handle_call (Evt *script)
ApiStatus evt_handle_exec1 (Evt *script)
ApiStatus evt_handle_exec1_get_id (Evt *script)
ApiStatus evt_handle_exec_wait (Evt *script)
ApiStatus evt_handle_jump (Evt *script)
s32 evt_trigger_on_activate_exec_script (Trigger *trigger)
ApiStatus evt_handle_bind (Evt *script)
ApiStatus DeleteTrigger (Evt *script, s32 isInitialCall)
Removes a trigger previously bound with EVT_BIND_TRIGGER.
ApiStatus evt_handle_unbind (Evt *script)
ApiStatus evt_handle_kill (Evt *script)
ApiStatus evt_handle_set_priority (Evt *script)
ApiStatus evt_handle_set_timescale (Evt *script)
ApiStatus evt_handle_set_group (Evt *script)
ApiStatus evt_handle_suspend_all (Evt *script)
ApiStatus evt_handle_resume_all (Evt *script)
ApiStatus evt_handle_suspend_others (Evt *script)
ApiStatus evt_handle_resume_others (Evt *script)
ApiStatus evt_handle_suspend (Evt *script)
ApiStatus evt_handle_resume (Evt *script)
ApiStatus evt_handle_does_script_exist (Evt *script)
s32 evt_trigger_on_activate_lock (Trigger *trigger)
ApiStatus evt_handle_bind_lock (Evt *script)
ApiStatus evt_handle_thread (Evt *script)
ApiStatus evt_handle_end_thread (Evt *script)
ApiStatus evt_handle_child_thread (Evt *script)
ApiStatus evt_handle_end_child_thread (Evt *script)
ApiStatus evt_handle_debug_log (Evt *script)
ApiStatus evt_handle_print_debug_var (Evt *script)
ApiStatus func_802C739C (Evt *script)
ApiStatus func_802C73B0 (Evt *script)
ApiStatus func_802C73B8 (Evt *script)
s32 evt_execute_next_command (Evt *script)
s32 evt_get_variable (Evt *script, Bytecode var)
s32 evt_get_variable_index (Evt *script, s32 var)
s32 evt_get_variable_index_alt (s32 var)
s32 evt_set_variable (Evt *script, Bytecode var, s32 value)
f32 evt_get_float_variable (Evt *script, Bytecode var)
f32 evt_set_float_variable (Evt *script, Bytecode var, f32 value)
Variables
u32 * gMapFlags
s32 * gMapVars
char evtDebugPrintBuffer [0x100]
Function Documentation
DeleteTrigger()
ApiStatus DeleteTrigger (Evt * script, s32 isInitialCall)
Removes a trigger previously bound with EVT_BIND_TRIGGER.
Parameters
triggerPtr
evt_execute_next_command()
s32 evt_execute_next_command (Evt * script)
Referenced by update_scripts().
evt_find_label()
Bytecode * evt_find_label (Evt * script, s32 arg1)
Referenced by evt_handle_goto().
evt_fixed_var_to_float()
f32 evt_fixed_var_to_float (Bytecode scriptVar)
Referenced by evt_get_float_variable(), evt_get_variable(), evt_handle_print_debug_var(), evt_set_float_variable(), and evt_set_variable().
evt_float_to_fixed_var()
Bytecode evt_float_to_fixed_var (f32 value)
Referenced by evt_set_float_variable().
evt_get_float_variable()
f32 evt_get_float_variable (Evt * script, Bytecode var)
Referenced by AddActorPos(), AddAnimatedModelRootPosition(), AddGoalPos(), AddPartDispOffset(), AddVectorPolar(), AdjustCam(), appendGfx_shrunk_player(), ClampAngleFloat(), CreateWhaleGeyser(), DemoJoystickRadial(), DemoJoystickXY(), evt_handle_addF(), evt_handle_divideF(), evt_handle_get_1_float(), evt_handle_get_2_float(), evt_handle_get_3_float(), evt_handle_get_4_float(), evt_handle_multiplyF(), evt_handle_set_float(), evt_handle_set_timescale(), evt_handle_subtractF(), evt_handle_wait_seconds(), FacePlayerTowardPoint(), func_8005DB00(), func_802D1270(), func_802D4D14(), func_802D7690(), GetDist2D(), InterpPlayerYaw(), JumpWithBounce(), make_vine_interpolation(), NpcFlyTo(), PanToTarget(), PlayEffect(), PlaySoundAtF(), ResetCam(), RotateGroup(), RotateModel(), ScaleGroup(), ScaleModel(), SetActorDispOffset(), SetActorIdleJumpGravity(), SetActorIdleSpeed(), SetActorJumpGravity(), SetActorRotation(), SetActorRotationOffset(), SetActorScale(), SetActorScaleModifier(), SetActorSpeed(), SetAnimatedModelRenderMode(), SetAnimatedModelRootPosition(), SetAnimatedModelRootRotation(), SetAnimatedModelRootScale(), SetAnimationRate(), SetCamDistance(), SetCamPerspective(), SetCamPitch(), SetCamPosA(), SetCamPosB(), SetCamPosC(), SetCamProperties(), SetCamSpeed(), SetNpcAnimationSpeed(), SetNpcJumpscale(), SetNpcRotation(), SetNpcRotationPivot(), SetNpcScale(), SetNpcSpeed(), SetPanTarget(), SetPartDispOffset(), SetPartJumpGravity(), SetPartMoveSpeed(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPlayerAnimationSpeed(), SetPlayerJumpscale(), SetPlayerSpeed(), SetVirtualEntityJumpGravity(), SetVirtualEntityMoveSpeed(), SetVirtualEntityPosition(), SetVirtualEntityRotation(), SetVirtualEntityScale(), ShakeCam(), ShowEmote(), ShowRecoveryShimmer(), ShowSleepBubble(), ShowStartRecoveryShimmer(), ShowSweat(), TranslateGroup(), TranslateModel(), UseSettingsFrom(), and WaitForCam().
evt_get_variable()
s32 evt_get_variable (Evt * script, Bytecode var)
Referenced by _npc_jump_to(), _show_message(), ActorExists(), AddActorDecoration(), AddActorPos(), AddActorVar(), AddAnimatedModelRootPosition(), AddBadge(), AddBattleCamOffsetZ(), AddBattleCamZoom(), AddCoin(), AddGoalPos(), AddItem(), AddKeyItem(), AddPartDispOffset(), AddPartMovementVar(), AddStarPieces(), AddStarPoints(), AdjustCam(), AdjustMusicProximityMix(), AfflictActor(), animate_and_draw_record(), appendGfx_piranha_vines(), appendGfx_records(), appendGfx_ritual_card(), appendGfx_sticker(), apply_transform_to_children(), ApproachPlayer100Units(), AssignScript(), AssignSwitchFlag(), AwaitPlayerApproach(), AwaitPlayerLeave(), BasicAI_Main(), BattleCamTargetActor(), BattleCamTargetActorPart(), BindHandleEvent(), BindHandlePhase(), BindIdle(), BindNpcAI(), BindNpcAux(), BindNpcDefeat(), BindNpcHit(), BindNpcIdle(), BindNpcInteract(), BindTakeTurn(), BoostAttack(), BoostDefense(), BringPartnerOut(), calculate_records(), CancelablePlayerRunToGoal(), CancelEnemyTurn(), card_worker_render(), card_worker_update(), ChangeModelAnimation(), check_input_open_menus(), check_input_status_bar(), ChooseNextTarget(), ClampAngleInt(), ClearAmbientSounds(), ClearPartnerMoveHistory(), ClearStatusEffects(), CleftAI_Main(), CloneModel(), CopyBuffs(), CopyStatusEffects(), CountTargets(), CreateNpc(), CreatePartShadow(), CreateVirtualEntity(), CreateVirtualEntity_ALT(), CreateVirtualEntityAt(), CreateWhaleGeyser(), DeleteAnimatedModel(), DeleteNpc(), DeleteTrigger(), DeleteVirtualEntity(), DemoPressButton(), DemoSetButtons(), Disable8bitMario(), DisablePartner(), DisablePartnerAI(), DisablePlayerInput(), DisablePlayerPhysics(), DisablePulseStone(), DismissEffect(), DismissItemOutline(), DispatchDamageEvent(), DispatchDamagePlayerEvent(), DispatchEvent(), DispatchEventPlayer(), DisposeWhaleGeyser(), DropItemEntity(), DropResizableItemEntity(), DropStarPoints(), ElectrifyActor(), EnableActorBlur(), EnableActorGlow(), EnableActorPaletteEffects(), EnableGroup(), EnableIdleScript(), EnableModel(), EnableMusicProximityMix(), EnableNpcAI(), EnableNpcAux(), EnableNpcBlur(), EnableNpcShadow(), EnablePartner(), EnablePlayerBlur(), EnableSpriteShading(), EnableTexPanning(), EnableWorldStatusBar(), EnemyDamageTarget(), EnemyFollowupAfflictTarget(), EnemyTestTarget(), evt_handle_add(), evt_handle_allocate_array(), evt_handle_AND(), evt_handle_AND_const(), evt_handle_bind(), evt_handle_bind_lock(), evt_handle_call(), evt_handle_case_equal(), evt_handle_case_equal_AND(), evt_handle_case_equal_OR(), evt_handle_case_greater(), evt_handle_case_greater_equal(), evt_handle_case_less(), evt_handle_case_less_equal(), evt_handle_case_not_equal(), evt_handle_case_range(), evt_handle_divide(), evt_handle_does_script_exist(), evt_handle_end_loop(), evt_handle_exec1(), evt_handle_exec1_get_id(), evt_handle_exec_wait(), evt_handle_get_Nth_float(), evt_handle_get_Nth_word(), evt_handle_goto(), evt_handle_if_AND(), evt_handle_if_equal(), evt_handle_if_greater(), evt_handle_if_greater_equal(), evt_handle_if_less(), evt_handle_if_less_equal(), evt_handle_if_not_AND(), evt_handle_if_not_equal(), evt_handle_jump(), evt_handle_kill(), evt_handle_mod(), evt_handle_multiply(), evt_handle_OR(), evt_handle_OR_const(), evt_handle_resume(), evt_handle_resume_all(), evt_handle_resume_others(), evt_handle_set_array(), evt_handle_set_flag_array(), evt_handle_set_float_buffer_ptr(), evt_handle_set_group(), evt_handle_set_int_buffer_ptr(), evt_handle_set_priority(), evt_handle_set_var(), evt_handle_subtract(), evt_handle_suspend(), evt_handle_suspend_all(), evt_handle_suspend_others(), evt_handle_switch(), evt_handle_wait(), FacePlayerTowardPoint(), FadeInMusic(), FadeOutMusic(), FallPartTo(), FallToGoal(), FindItem(), FindKeyItem(), FlyPartTo(), FlyToGoal(), ForceDisableActorBlur(), ForceHomePos(), FreezeBattleCam(), FreezeBattleState(), func_80044238(), func_80045798(), func_80045838(), func_8005DB00(), func_80240DA4_9087D4(), func_80241610_990DF0(), func_80244F5C_8057DC(), func_8024ECF8(), func_8026E260(), func_8026E558(), func_8026E9A0(), func_8026EDE4(), func_8026F1A0(), func_80273444(), func_80274A18(), func_802752AC(), func_80275F00(), func_8027CC10(), func_8027D434(), func_8027FC90(), func_8028070C(), func_802CA90C(), func_802CA988(), func_802CABE8(), func_802CACC0(), func_802CAE50(), func_802CB710(), func_802CF56C(), func_802D0C94(), func_802D1270(), func_802D1380(), func_802D2C14(), func_802D4CC4(), func_802D7690(), func_802D7B74(), get_spirits_rescued(), get_tattle(), GetActorAttackBoost(), GetActorDefenseBoost(), GetActorFlags(), GetActorHP(), GetActorLevel(), GetActorPos(), GetActorRotation(), GetActorScale(), GetActorSize(), GetActorVar(), GetActorYaw(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), GetAnimatedModelRootPosition(), GetAnimatedNodePosition(), GetAnimatedNodeRotation(), GetAnimatedPositionByTreeIndex(), GetAnimatedRotationByTreeIndex(), GetAnimation(), GetBattleVar(), GetCamDistance(), GetCamPitch(), GetCamPosA(), GetCamPosB(), GetCamPosC(), GetCamPosition(), GetCamType(), GetCardOrientation(), GetColliderCenter(), GetCurrentActorType(), GetDistanceToGoal(), GetEnemyMaxHP(), GetGoalPos(), GetHomePos(), GetIdleGoal(), GetIndexFromHome(), GetIndexFromPos(), GetInstigatorValue(), GetItemPower(), GetLastDamage(), GetLastEvent(), GetModelCenter(), GetModelIndex(), GetNpcAnimation(), GetNpcPointer(), GetNpcPos(), GetNpcVar(), GetNpcYaw(), GetOriginalActorType(), GetPartAnimInstanceID(), GetPartAnimNotify(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartOffset(), GetPartPos(), GetPartRotation(), GetPartScale(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), GetPhonographData(), GetSelfAnimationFromTable(), GetSelfVar(), GetStatusFlags(), GetTransformGroup(), GetValueByRef(), GetVirtualEntityPosition(), gfx_build_bubble_flower(), gfx_build_knocked_down_player(), gfx_build_rowf_rug_with_ripples(), gfx_build_splashes(), goto_map(), HasKeyItem(), HealActor(), HideHealthBar(), HideHPBar(), HidePlayerShadow(), HPBarToCurrent(), HPBarToHome(), IdleFlyToGoal(), IdleJumpToGoal(), IdleRunToGoal(), InterpCamTargetPos(), InterpNpcYaw(), InterpPlayerYaw(), InvalidateModelTransform(), IsPlayerWithin(), ItemAfflictEnemy(), ItemCheckHit(), ItemDamageEnemy(), ItemSpookEnemy(), JumpPartTo(), JumpToGoal(), JumpToGoalSimple2(), JumpWithBounce(), KnockdownCreate(), LandJump(), LandJumpPart(), load_map_bg(), LoadAnimatedMesh(), LoadAnimatedModel(), LoadBattleSection(), LoadDemoBattle(), LoadPath(), LoadSettings(), MakeEntity(), MakeItemEntity(), MakeLerp(), MakeLocalVertexCopy(), MakeNpcs(), MakeOwnerTargetIndex(), MakeTransformGroup(), map_init(), ModifyActorDecoration(), ModifyColliderFlags(), ModifyGlobalOverrideFlags(), MoveBattleCamOver(), NpcFaceNpc(), NpcFacePlayer(), NpcFlyTo(), NpcMoveTo(), NpcSetHomePosToCurrent(), OnPlayerFled(), PanToTarget(), ParentColliderToModel(), PartnerAfflictEnemy(), PartnerDamageEnemy(), PartnerPowerBounceEnemy(), PartnerTestEnemy(), pause_cleanup(), pause_handle_input(), pause_init(), pause_map_draw_contents(), pause_map_handle_input(), pause_map_init(), pause_map_update(), pause_stats_handle_input(), pause_tutorial_draw_contents(), PauseTakeTurn(), phys_adjust_cam_on_landing(), PiranhaPlantAI_Main(), PlayAmbientSounds(), PlayEffect(), player_jump(), PlayerDamageEnemy(), PlayerFaceNpc(), PlayerFallToGoal(), PlayerMoveTo(), PlayerPowerBounceEnemy(), PlayerRunToGoal(), PlayerTestEnemy(), PlayMerleeGatherFX(), PlayMerleeOrbFX(), PlayModelAnimation(), PlayModelAnimationStartingFrom(), PlaySound(), PlaySoundAt(), PlaySoundAtCollider(), PlaySoundAtF(), PlaySoundAtModel(), PlaySoundAtNpc(), PlaySoundAtPlayer(), PlaySoundWithVolume(), ProjectileHitbox_GetUsableProjectileID(), PushSong(), Quizmo_CreateReactionEffect(), RandInt(), RegisterMusicEvents(), RemoveActor(), RemoveActorDecoration(), RemoveBadge(), RemoveEffect(), RemoveEncounter(), RemoveFortressKeys(), RemoveItem(), RemoveItemAt(), RemoveItemEntity(), RemoveKeyItemAt(), RemoveNpc(), RemovePartShadow(), ResetActorSounds(), ResetAllActorSounds(), ResetCam(), ResetFromLava(), RestartNpcAI(), RestartNpcAux(), ResumeTakeTurn(), RotateGroup(), RotateModel(), RunPartTo(), RunToGoal(), ScaleGroup(), ScaleModel(), SelfEnemyOverrideSyncPos(), SetActorDispOffset(), SetActorFlagBits(), SetActorFlags(), SetActorIdleJumpGravity(), SetActorIdleSpeed(), SetActorJumpGravity(), SetActorPaletteEffect(), SetActorPaletteSwapParams(), SetActorPaletteSwapTimes(), SetActorPos(), SetActorRotation(), SetActorRotationOffset(), SetActorScale(), SetActorScaleModifier(), SetActorSize(), SetActorSounds(), SetActorSpeed(), SetActorStatusOffsets(), SetActorType(), SetActorVar(), SetActorYaw(), SetAnimatedModelRenderMode(), SetAnimatedModelRootPosition(), SetAnimatedModelRootRotation(), SetAnimatedModelRootScale(), SetAnimatedNodeFlags(), SetAnimation(), SetAnimationRate(), SetAnimatorFlags(), SetBattleCamOffsetZ(), SetBattleCamParam(), SetBattleCamParams(), SetBattleCamPos(), SetBattleCamTarget(), SetBattleCamYaw(), SetBattleCamZoom(), SetBattleFlagBits(), SetBattleFlagBits2(), SetBattleMusic(), SetBattleSong(), SetBattleState(), SetBattleVar(), SetCamBGColor(), SetCamDistance(), SetCamEnabled(), SetCamLeadPlayer(), SetCamNoDraw(), SetCamPerspective(), SetCamPitch(), SetCamPosA(), SetCamPosB(), SetCamPosC(), SetCamProperties(), SetCamSpeed(), SetCamTarget(), SetCamType(), SetCamViewport(), SetCustomGfx(), SetCustomGfxBuilders(), SetCustomGfxEnabled(), SetDefenseTable(), SetEncounterStatusFlags(), SetEndBattleFadeOutRate(), SetEnemyFlagBits(), SetEnemyHP(), SetEnemyTargetOffset(), SetEntityCullMode(), SetGameMode(), SetGoalPos(), SetGoalToFirstTarget(), SetGoalToHome(), SetGoalToIndex(), SetGoalToTarget(), SetGroupVisibility(), SetHomePos(), SetHPBarOffset(), SetIdleAnimations(), SetIdleGoal(), SetIdleGoalToHome(), SetItemAlpha(), SetItemFlags(), SetItemPos(), SetJumpAnimations(), SetMessageBoxDuration(), SetMessageText(), SetMessageValue(), SetModelCustomGfx(), SetModelFlags(), SetModelTexVariant(), SetMotionBlurParams(), SetMusicTrack(), SetMusicTrackVolumes(), SetNpcAnimation(), SetNpcAnimationSpeed(), SetNpcAux(), SetNpcCollisionChannel(), SetNpcCollisionSize(), SetNpcDecoration(), SetNpcFlagBits(), SetNpcImgFXFlags(), SetNpcImgFXParams(), SetNpcJumpscale(), SetNpcPaletteSwapLower(), SetNpcPaletteSwapMode(), SetNpcPaletteSwapping(), SetNpcPos(), SetNpcRenderMode(), SetNpcRotation(), SetNpcRotationPivot(), SetNpcScale(), SetNpcSpeed(), SetNpcSprite(), SetNpcVar(), SetNpcYaw(), SetOwnerID(), SetOwnerInstigatorValue(), SetOwnerTarget(), SetPanTarget(), SetPartAlpha(), SetPartDispOffset(), SetPartEventBits(), SetPartEventFlags(), SetPartFlagBits(), SetPartFlags(), SetPartGoalToTarget(), SetPartImmunityBits(), SetPartImmunityFlags(), SetPartJumpGravity(), SetPartMovementVar(), SetPartMoveSpeed(), SetPartPos(), SetPartRotation(), SetPartRotationOffset(), SetPartScale(), SetPartSize(), SetPartSounds(), SetPartTargetFlagBits(), SetPartTargetFlags(), SetPartYaw(), SetPlayerActionState(), SetPlayerAnimation(), SetPlayerCollisionSize(), SetPlayerFlagBits(), SetPlayerPos(), SetPlayerPushVelocity(), SetProjectileTargetOffset(), SetRenderMode(), SetSelfEnemyFlagBits(), SetSelfRotation(), SetSelfVar(), SetSleepBubbleTimeLeft(), SetSpriteShading(), SetStatusTable(), SetTargetActor(), SetTargetOffset(), SetTattleMessage(), SetTexPanner(), SetTexPanOffset(), SetTimeFreezeMode(), SetTransformGroupEnabled(), setup_gfx_bridge(), SetValueByRef(), SetVirtualEntityFlagBits(), SetVirtualEntityFlags(), SetVirtualEntityJumpGravity(), SetVirtualEntityMoveSpeed(), SetVirtualEntityPosition(), SetVirtualEntityRenderCommands(), SetVirtualEntityRenderMode(), SetVirtualEntityRotation(), SetVirtualEntityScale(), SetZoneEnabled(), ShakeCam(), ShowChoice(), ShowCoinCounter(), ShowEmote(), ShowGotItem(), ShowHealthBar(), ShowImmuneBonk(), ShowMessageAtScreenPos(), ShowMessageAtWorldPos(), ShowMessageBox(), ShowRecoveryShimmer(), ShowShockEffect(), ShowSleepBubble(), ShowStartRecoveryShimmer(), ShowSweat(), ShowVariableMessageBox(), ShowWorldStatusBar(), SpearGuyAI_Main(), StartBattleWith(), StartBossBattle(), StopSound(), StopTrackingSoundPos(), SummonEnemy(), SwitchMessage(), TranslateGroup(), TranslateModel(), update_item_entity_pickup(), update_status_bar(), UpdateColliderTransform(), UpdatePlayerImgFX(), UseBattleCamPreset(), UseBattleCamPresetImmediately(), UseBattleCamPresetWait(), UseDoorSounds(), UseDynamicShadow(), UseEntryHeading(), UseExitHeading(), UseIdleAnimation(), UseRoomDoorSounds(), UseSettingsFrom(), VanishActor(), VirtualEntityJumpTo(), VirtualEntityLandJump(), VirtualEntityMoveTo(), WaitForCam(), WaitForState(), WanderMeleeAI_Main(), WasStatusInflicted(), WorldItem_GetItemProperties(), WorldItem_RestoreFP(), WorldItem_RestoreHP(), WorldItem_ShowFPGain(), WorldItem_ShowHPGain(), and WorldItem_ShowUseSparkles().
evt_get_variable_index()
s32 evt_get_variable_index (Evt * script, s32 var)
Referenced by AssignBlockFlag(), AssignChestFlag(), AssignCrateFlag(), AssignPanelFlag(), DropResizableItemEntity(), evt_handle_bind(), evt_handle_bind_lock(), and MakeItemEntity().
evt_get_variable_index_alt()
s32 evt_get_variable_index_alt (s32 var)
evt_goto_end_case()
Bytecode * evt_goto_end_case (Evt * script)
Referenced by evt_handle_break_case(), evt_handle_case_AND(), evt_handle_case_default(), evt_handle_case_equal(), evt_handle_case_equal_AND(), evt_handle_case_equal_OR(), evt_handle_case_greater(), evt_handle_case_greater_equal(), evt_handle_case_less(), evt_handle_case_less_equal(), evt_handle_case_not_equal(), evt_handle_case_range(), and evt_handle_end_case_group().
evt_goto_end_loop()
Bytecode * evt_goto_end_loop (Evt * script)
Referenced by evt_handle_break_loop().
evt_goto_next_case()
Bytecode * evt_goto_next_case (Evt * script)
Referenced by evt_handle_case_AND(), evt_handle_case_equal(), evt_handle_case_equal_AND(), evt_handle_case_equal_OR(), evt_handle_case_greater(), evt_handle_case_greater_equal(), evt_handle_case_less(), evt_handle_case_less_equal(), evt_handle_case_not_equal(), evt_handle_case_range(), and evt_handle_end_case_group().
evt_handle_add()
ApiStatus evt_handle_add (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_addF()
ApiStatus evt_handle_addF (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_allocate_array()
ApiStatus evt_handle_allocate_array (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_AND()
ApiStatus evt_handle_AND (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_AND_const()
ApiStatus evt_handle_AND_const (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_bind()
ApiStatus evt_handle_bind (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_bind_lock()
ApiStatus evt_handle_bind_lock (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_break_case()
ApiStatus evt_handle_break_case (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_break_loop()
ApiStatus evt_handle_break_loop (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_call()
ApiStatus evt_handle_call (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_AND()
ApiStatus evt_handle_case_AND (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_default()
ApiStatus evt_handle_case_default (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_equal()
ApiStatus evt_handle_case_equal (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_equal_AND()
ApiStatus evt_handle_case_equal_AND (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_equal_OR()
ApiStatus evt_handle_case_equal_OR (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_greater()
ApiStatus evt_handle_case_greater (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_greater_equal()
ApiStatus evt_handle_case_greater_equal (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_less()
ApiStatus evt_handle_case_less (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_less_equal()
ApiStatus evt_handle_case_less_equal (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_not_equal()
ApiStatus evt_handle_case_not_equal (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_case_range()
ApiStatus evt_handle_case_range (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_child_thread()
ApiStatus evt_handle_child_thread (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_debug_log()
ApiStatus evt_handle_debug_log (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_divide()
ApiStatus evt_handle_divide (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_divideF()
ApiStatus evt_handle_divideF (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_does_script_exist()
ApiStatus evt_handle_does_script_exist (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_else()
ApiStatus evt_handle_else (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_end_case_group()
ApiStatus evt_handle_end_case_group (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_end_child_thread()
ApiStatus evt_handle_end_child_thread (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_end_if()
ApiStatus evt_handle_end_if (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_end_loop()
ApiStatus evt_handle_end_loop (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_end_switch()
ApiStatus evt_handle_end_switch (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_end_thread()
ApiStatus evt_handle_end_thread (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_exec1()
ApiStatus evt_handle_exec1 (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_exec1_get_id()
ApiStatus evt_handle_exec1_get_id (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_exec_wait()
ApiStatus evt_handle_exec_wait (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_1_float()
ApiStatus evt_handle_get_1_float (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_1_word()
ApiStatus evt_handle_get_1_word (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_2_float()
ApiStatus evt_handle_get_2_float (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_2_word()
ApiStatus evt_handle_get_2_word (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_3_float()
ApiStatus evt_handle_get_3_float (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_3_word()
ApiStatus evt_handle_get_3_word (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_4_float()
ApiStatus evt_handle_get_4_float (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_4_word()
ApiStatus evt_handle_get_4_word (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_Nth_float()
ApiStatus evt_handle_get_Nth_float (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_get_Nth_word()
ApiStatus evt_handle_get_Nth_word (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_goto()
ApiStatus evt_handle_goto (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_if_AND()
ApiStatus evt_handle_if_AND (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_if_equal()
ApiStatus evt_handle_if_equal (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_if_greater()
ApiStatus evt_handle_if_greater (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_if_greater_equal()
ApiStatus evt_handle_if_greater_equal (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_if_less()
ApiStatus evt_handle_if_less (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_if_less_equal()
ApiStatus evt_handle_if_less_equal (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_if_not_AND()
ApiStatus evt_handle_if_not_AND (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_if_not_equal()
ApiStatus evt_handle_if_not_equal (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_jump()
ApiStatus evt_handle_jump (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_kill()
ApiStatus evt_handle_kill (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_label()
ApiStatus evt_handle_label (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_loop()
ApiStatus evt_handle_loop (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_mod()
ApiStatus evt_handle_mod (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_multiply()
ApiStatus evt_handle_multiply (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_multiplyF()
ApiStatus evt_handle_multiplyF (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_OR()
ApiStatus evt_handle_OR (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_OR_const()
ApiStatus evt_handle_OR_const (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_print_debug_var()
s32 evt_handle_print_debug_var (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_resume()
ApiStatus evt_handle_resume (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_resume_all()
ApiStatus evt_handle_resume_all (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_resume_others()
ApiStatus evt_handle_resume_others (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_return()
ApiStatus evt_handle_return (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_array()
ApiStatus evt_handle_set_array (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_const()
ApiStatus evt_handle_set_const (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_flag_array()
ApiStatus evt_handle_set_flag_array (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_float()
ApiStatus evt_handle_set_float (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_float_buffer_ptr()
ApiStatus evt_handle_set_float_buffer_ptr (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_group()
ApiStatus evt_handle_set_group (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_int_buffer_ptr()
ApiStatus evt_handle_set_int_buffer_ptr (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_priority()
ApiStatus evt_handle_set_priority (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_timescale()
ApiStatus evt_handle_set_timescale (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_set_var()
ApiStatus evt_handle_set_var (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_subtract()
ApiStatus evt_handle_subtract (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_subtractF()
ApiStatus evt_handle_subtractF (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_suspend()
ApiStatus evt_handle_suspend (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_suspend_all()
ApiStatus evt_handle_suspend_all (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_suspend_others()
ApiStatus evt_handle_suspend_others (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_switch()
ApiStatus evt_handle_switch (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_switch_const()
ApiStatus evt_handle_switch_const (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_thread()
ApiStatus evt_handle_thread (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_unbind()
ApiStatus evt_handle_unbind (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_wait()
ApiStatus evt_handle_wait (Evt * script)
Referenced by evt_execute_next_command().
evt_handle_wait_seconds()
ApiStatus evt_handle_wait_seconds (Evt * script)
Referenced by evt_execute_next_command().
evt_set_float_variable()
f32 evt_set_float_variable (Evt * script, Bytecode var, f32 value)
Referenced by AddVectorPolar(), ClampAngleFloat(), evt_handle_addF(), evt_handle_divideF(), evt_handle_get_1_float(), evt_handle_get_2_float(), evt_handle_get_3_float(), evt_handle_get_4_float(), evt_handle_get_Nth_float(), evt_handle_multiplyF(), evt_handle_set_float(), evt_handle_subtractF(), exec_ShakeCamX(), GetActorScale(), GetAnimatedModelRootPosition(), GetCamDistance(), GetCamPitch(), GetCamPosA(), GetCamPosB(), GetCamPosC(), GetCamPosition(), GetDist2D(), GetPartRotation(), and GetPartScale().
evt_set_variable()
s32 evt_set_variable (Evt * script, Bytecode var, s32 value)
Referenced by ActorExists(), AddBadge(), AddItem(), ApproachPlayer100Units(), CancelablePlayerRunToGoal(), card_worker_render(), card_worker_update(), CheckButtonDown(), CheckButtonHeld(), CheckButtonPress(), ChooseNextTarget(), ClampAngleInt(), ClearVariable(), CountFortessKeys(), CountTargets(), CreateVirtualEntity(), CreateVirtualEntity_ALT(), EnemyDamageTarget(), EnemyFollowupAfflictTarget(), EnemyTestTarget(), evt_handle_add(), evt_handle_allocate_array(), evt_handle_AND(), evt_handle_AND_const(), evt_handle_bind(), evt_handle_divide(), evt_handle_does_script_exist(), evt_handle_end_loop(), evt_handle_exec1_get_id(), evt_handle_get_1_word(), evt_handle_get_2_word(), evt_handle_get_3_word(), evt_handle_get_4_word(), evt_handle_get_Nth_word(), evt_handle_mod(), evt_handle_multiply(), evt_handle_OR(), evt_handle_OR_const(), evt_handle_set_const(), evt_handle_set_var(), evt_handle_subtract(), exec_ShakeCamX(), filemenu_yesno_handle_input(), FindItem(), FindKeyItem(), func_800445A8(), func_800445D4(), func_800458CC(), func_8026E558(), func_8026E914(), func_8027FC90(), func_802CA988(), GetActorAttackBoost(), GetActorDefenseBoost(), GetActorFlags(), GetActorHP(), GetActorLevel(), GetActorPos(), GetActorRotation(), GetActorSize(), GetActorVar(), GetActorYaw(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), GetAnimatedNodePosition(), GetAnimatedNodeRotation(), GetAnimatedPositionByTreeIndex(), GetAnimatedRotationByTreeIndex(), GetAnimation(), GetBattleFlags(), GetBattleFlags2(), GetBattleOutcome(), GetBattlePhase(), GetBattleState(), GetBattleVar(), GetCamType(), GetCurrentActorType(), GetCurrentPartnerID(), GetDamageSource(), GetDemoState(), GetDistanceToGoal(), GetEncounterTrigger(), GetEncounterTriggerHitTier(), GetEnemyMaxHP(), GetEntryID(), GetGoalPos(), GetHomePos(), GetIdleGoal(), GetIndexFromHome(), GetIndexFromPos(), GetInstigatorValue(), GetItemPower(), GetLastDamage(), GetLastElement(), GetLastEvent(), GetLoadType(), GetMapID(), GetMenuSelection(), GetModelIndex(), GetNpcAnimation(), GetNpcPointer(), GetNpcPos(), GetNpcVar(), GetNpcYaw(), GetOriginalActorType(), GetOwnerEncounterTrigger(), GetOwnerID(), GetOwnerTarget(), GetPartAnimInstanceID(), GetPartAnimNotify(), GetPartDispOffset(), GetPartEventFlags(), GetPartFlags(), GetPartMovementVar(), GetPartnerActionSuccess(), GetPartnerInUse(), GetPartnerPos(), GetPartOffset(), GetPartPos(), GetPartTarget(), GetPartTargetFlags(), GetPartYaw(), GetPlayerActionState(), GetPlayerActionSuccess(), GetPlayerActorID(), GetPlayerAnimation(), GetPlayerHP(), GetPlayerPos(), GetPlayerTargetYaw(), GetSelfAnimationFromTable(), GetSelfNpcID(), GetSelfVar(), GetStatusFlags(), GetTargetListLength(), GetTransformGroup(), GetValueByRef(), GetVirtualEntityPosition(), HasKeyItem(), init_enter_world_shared(), IsMessageBoxDisplayed(), IsPlayerOnValidFloor(), IsPlayerWithin(), IsStartingConversation(), ItemAfflictEnemy(), ItemCheckHit(), ItemDamageEnemy(), ItemSpookEnemy(), KnockdownCreate(), load_demo_battle(), MakeOwnerTargetIndex(), PartnerAfflictEnemy(), PartnerCanUseAbility(), PartnerDamageEnemy(), PartnerIsFlying(), PartnerPowerBounceEnemy(), PartnerTestEnemy(), PlayEffect(), PlayerDamageEnemy(), PlayerPowerBounceEnemy(), PlayerTestEnemy(), RandInt(), RemoveItem(), SetValueByRef(), ShowSleepBubble(), state_step_demo(), update_item_entity_pickup(), WasStatusInflicted(), and worker_update_phonograph_hud().
evt_skip_else()
Bytecode * evt_skip_else (Evt * script)
Referenced by evt_handle_else().
evt_skip_if()
Bytecode * evt_skip_if (Evt * script)
Referenced by evt_handle_if_AND(), evt_handle_if_equal(), evt_handle_if_greater(), evt_handle_if_greater_equal(), evt_handle_if_less(), evt_handle_if_less_equal(), evt_handle_if_not_AND(), and evt_handle_if_not_equal().
evt_trigger_on_activate_exec_script()
s32 evt_trigger_on_activate_exec_script (Trigger * trigger)
Referenced by bind_trigger(), and evt_handle_bind().
evt_trigger_on_activate_lock()
s32 evt_trigger_on_activate_lock (Trigger * trigger)
Referenced by evt_handle_bind_lock().
func_802C739C()
ApiStatus func_802C739C (Evt * script)
Referenced by evt_execute_next_command().
func_802C73B0()
ApiStatus func_802C73B0 (Evt * script)
Referenced by evt_execute_next_command().
func_802C73B8()
ApiStatus func_802C73B8 (Evt * script)
Referenced by evt_execute_next_command().
Variable Documentation
evtDebugPrintBuffer
char evtDebugPrintBuffer[0x100] extern
Referenced by evt_handle_print_debug_var().
gMapFlags
u32* gMapFlags extern
Referenced by clear_script_list(), evt_get_float_variable(), evt_get_variable(), evt_handle_print_debug_var(), evt_set_float_variable(), evt_set_variable(), and init_script_list().
gMapVars
s32* gMapVars extern
Referenced by clear_script_list(), evt_get_float_variable(), evt_get_variable(), evt_handle_print_debug_var(), evt_set_float_variable(), evt_set_variable(), and init_script_list().