papermario: src/effects/explosion.c File Reference
explosion.c File Reference
Functions
void explosion_init (EffectInstance *effect)
void explosion_update (EffectInstance *effect)
void explosion_render (EffectInstance *effect)
void explosion_appendGfx (void *effect)
void explosion_main (s32 type, f32 x, f32 y, f32 z)
EFFECT_DEF_SMOKE_RING (smoke_ring_main)
EFFECT_DEF_CONFETTI (confetti_main)
Variables
Gfx D_09000840_3447B0 []
Gfx D_090008F0_344860 []
Gfx D_09000910_344880 []
Gfx D_09000978_3448E8 []
Gfx D_090009D8_344948 []
Gfx D_09000A38_3449A8 []
Gfx * D_E00328B0 [] = { D_09000978_3448E8, D_090009D8_344948, D_09000A38_3449A8 }
Function Documentation
EFFECT_DEF_CONFETTI()
EFFECT_DEF_CONFETTI (confetti_main)
EFFECT_DEF_SMOKE_RING()
EFFECT_DEF_SMOKE_RING (smoke_ring_main)
explosion_appendGfx()
void explosion_appendGfx (void * effect)
Referenced by explosion_render().
explosion_init()
void explosion_init (EffectInstance * effect)
Referenced by explosion_main().
explosion_main()
void explosion_main (s32 type, f32 x, f32 y, f32 z)
explosion_render()
void explosion_render (EffectInstance * effect)
Referenced by explosion_main().
explosion_update()
void explosion_update (EffectInstance * effect)
Referenced by explosion_main().
Variable Documentation
D_09000840_3447B0
Gfx D_09000840_3447B0[] extern
Referenced by explosion_appendGfx().
D_090008F0_344860
Gfx D_090008F0_344860[] extern
Referenced by explosion_appendGfx().
D_09000910_344880
Gfx D_09000910_344880[] extern
Referenced by explosion_appendGfx().
D_09000978_3448E8
Gfx D_09000978_3448E8[] extern
D_090009D8_344948
Gfx D_090009D8_344948[] extern
D_09000A38_3449A8
Gfx D_09000A38_3449A8[] extern
D_E00328B0
Gfx* D_E00328B0[] = { D_09000978_3448E8, D_090009D8_344948, D_09000A38_3449A8 }
Referenced by explosion_appendGfx().