papermario: src/evt/f8f60_len_1560.c File Reference
f8f60_len_1560.c File Reference
Functions
ApiStatus MakeLerp (Evt *script, s32 isInitialCall)
ApiStatus UpdateLerp (Evt *script, s32 isInitialCall)
ApiStatus RandInt (Evt *script, s32 isInitialCall)
ApiStatus GetAngleBetweenNPCs (Evt *script, s32 isInitialCall)
ApiStatus GetAngleToNPC (Evt *script, s32 isInitialCall)
ApiStatus GetAngleToPlayer (Evt *script, s32 isInitialCall)
ApiStatus AwaitPlayerApproach (Evt *script, s32 isInitialCall)
ApiStatus IsPlayerWithin (Evt *script, s32 isInitialCall)
ApiStatus AwaitPlayerLeave (Evt *script, s32 isInitialCall)
ApiStatus AddVectorPolar (Evt *script, s32 isInitialCall)
ApiStatus func_802D4BDC (Evt *script, s32 isInitialCall)
ApiStatus func_802D4C4C (Evt *script, s32 isInitialCall)
ApiStatus func_802D4CC4 (Evt *script, s32 isInitialCall)
ApiStatus func_802D4D14 (Evt *script, s32 isInitialCall)
ApiStatus func_802D4D88 (Evt *script, s32 isInitialCall)
void load_path_data (s32 num, f32 *normalizedLengths, Vec3f *pathPositions, Vec3f *outVectors)
void get_path_position (f32 alpha, Vec3f *outPos, s32 numVectors, f32 *normalizedLengths, Vec3f *pathPoints, Vec3f *vectors)
ApiStatus LoadPath (Evt *script, s32 isInitialCall)
ApiStatus GetNextPathPos (Evt *script, s32 isInitialCall)
ApiStatus GetDist2D (Evt *script, s32 isInitialCall)
ApiStatus SetTimeFreezeMode (Evt *script, s32 initialCall)
ApiStatus ModifyGlobalOverrideFlags (Evt *script, s32 initialCall)
ApiStatus SetValueByRef (Evt *script, s32 isInitialCall)
ApiStatus GetValueByRef (Evt *script, s32 isInitialCall)
ApiStatus EnableWorldStatusBar (Evt *script, s32 isInitialCall)
ApiStatus ShowWorldStatusBar (Evt *script, s32 isInitialCall)
ApiStatus SetGameMode (Evt *script, s32 isInitialCall)
ApiStatus ClampAngleInt (Evt *script, s32 isInitialCall)
ApiStatus ClampAngleFloat (Evt *script, s32 isInitialCall)
Function Documentation
AddVectorPolar()
ApiStatus AddVectorPolar (Evt * script, s32 isInitialCall)
AwaitPlayerApproach()
ApiStatus AwaitPlayerApproach (Evt * script, s32 isInitialCall)
AwaitPlayerLeave()
ApiStatus AwaitPlayerLeave (Evt * script, s32 isInitialCall)
ClampAngleFloat()
ApiStatus ClampAngleFloat (Evt * script, s32 isInitialCall)
ClampAngleInt()
ApiStatus ClampAngleInt (Evt * script, s32 isInitialCall)
EnableWorldStatusBar()
ApiStatus EnableWorldStatusBar (Evt * script, s32 isInitialCall)
func_802D4BDC()
ApiStatus func_802D4BDC (Evt * script, s32 isInitialCall)
func_802D4C4C()
ApiStatus func_802D4C4C (Evt * script, s32 isInitialCall)
func_802D4CC4()
ApiStatus func_802D4CC4 (Evt * script, s32 isInitialCall)
func_802D4D14()
ApiStatus func_802D4D14 (Evt * script, s32 isInitialCall)
func_802D4D88()
ApiStatus func_802D4D88 (Evt * script, s32 isInitialCall)
get_path_position()
void get_path_position (f32 alpha, Vec3f * outPos, s32 numVectors, f32 * normalizedLengths, Vec3f * pathPoints, Vec3f * vectors)
Referenced by GetNextPathPos().
GetAngleBetweenNPCs()
ApiStatus GetAngleBetweenNPCs (Evt * script, s32 isInitialCall)
GetAngleToNPC()
ApiStatus GetAngleToNPC (Evt * script, s32 isInitialCall)
GetAngleToPlayer()
ApiStatus GetAngleToPlayer (Evt * script, s32 isInitialCall)
GetDist2D()
ApiStatus GetDist2D (Evt * script, s32 isInitialCall)
GetNextPathPos()
ApiStatus GetNextPathPos (Evt * script, s32 isInitialCall)
See also
LoadPath
Referenced by make_vine_interpolation().
GetValueByRef()
ApiStatus GetValueByRef (Evt * script, s32 isInitialCall)
IsPlayerWithin()
ApiStatus IsPlayerWithin (Evt * script, s32 isInitialCall)
load_path_data()
void load_path_data (s32 num, f32 * normalizedLengths, Vec3f * pathPositions, Vec3f * outVectors)
Referenced by LoadPath().
LoadPath()
ApiStatus LoadPath (Evt * script, s32 isInitialCall)
See also
GetNextPathPos
Referenced by make_vine_interpolation().
MakeLerp()
ApiStatus MakeLerp (Evt * script, s32 isInitialCall)
ModifyGlobalOverrideFlags()
ApiStatus ModifyGlobalOverrideFlags (Evt * script, s32 initialCall)
RandInt()
ApiStatus RandInt (Evt * script, s32 isInitialCall)
SetGameMode()
ApiStatus SetGameMode (Evt * script, s32 isInitialCall)
SetTimeFreezeMode()
ApiStatus SetTimeFreezeMode (Evt * script, s32 initialCall)
SetValueByRef()
ApiStatus SetValueByRef (Evt * script, s32 isInitialCall)
ShowWorldStatusBar()
ApiStatus ShowWorldStatusBar (Evt * script, s32 isInitialCall)
UpdateLerp()
ApiStatus UpdateLerp (Evt * script, s32 isInitialCall)