papermario: src/effects/falling_leaves.c File Reference
falling_leaves.c File Reference
Functions
void falling_leaves_init (EffectInstance *effect)
void falling_leaves_render (EffectInstance *effect)
void falling_leaves_update (EffectInstance *effect)
void falling_leaves_appendGfx (void *effect)
void falling_leaves_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Variables
Gfx D_09001100_3601E0 []
Gfx D_090011B0_360290 []
Function Documentation
falling_leaves_appendGfx()
void falling_leaves_appendGfx (void * effect)
Referenced by falling_leaves_render().
falling_leaves_init()
void falling_leaves_init (EffectInstance * effect)
Referenced by falling_leaves_main().
falling_leaves_main()
void falling_leaves_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
falling_leaves_render()
void falling_leaves_render (EffectInstance * effect)
Referenced by falling_leaves_main().
falling_leaves_update()
void falling_leaves_update (EffectInstance * effect)
Referenced by falling_leaves_main().
Variable Documentation
D_09001100_3601E0
Gfx D_09001100_3601E0[] extern
Referenced by falling_leaves_appendGfx().
D_090011B0_360290
Gfx D_090011B0_360290[] extern
Referenced by falling_leaves_appendGfx().