papermario: include/filemenu.h File Reference
filemenu.h File Reference
Macros
#define WINDOW_UPDATE_FUNC(name)
Enumerations
enum {
PAGE_0 , PAGE_1 , PAGE_2 , PAGE_3 ,
PAGE_4
}
Functions
void filemenu_update_show_name_input (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_show_options_left (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_show_options_right (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_show_options_bottom (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_show_with_rotation (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_hidden_name_input (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_hidden_options_left (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_hidden_options_right (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_hidden_title (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_hidden_options_bottom (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_hidden_with_rotation (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_select_file (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_deselect_file (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_show_name_confirm (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_hidden_name_confirm (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void main_menu_window_update (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_update_show_title (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_draw_file_name (u8 *, s32, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_title (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_stereo (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_mono (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_option_left (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_option_center (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_option_right (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_file_0_info (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_file_0_title (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_file_1_info (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_file_1_title (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_file_2_info (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_file_2_title (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_file_3_info (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_file_3_title (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_yesno_draw_options_contents (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_yesno_draw_prompt_contents (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_info_draw_message_contents (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_file_create_header (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_choose_name (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_cursor (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_draw_contents_copy_arrow (MenuPanel *, s32, s32, s32, s32, s32, s32)
void filemenu_main_init (MenuPanel *)
void filemenu_main_handle_input (MenuPanel *)
void filemenu_main_update (MenuPanel *)
void filemenu_main_cleanup (MenuPanel *)
void filemenu_yesno_init (MenuPanel *)
void filemenu_yesno_handle_input (MenuPanel *)
void filemenu_yesno_update (MenuPanel *)
void filemenu_yesno_cleanup (MenuPanel *)
void filemenu_info_init (MenuPanel *)
void filemenu_info_handle_input (MenuPanel *)
void filemenu_info_update (MenuPanel *)
void filemenu_info_cleanup (MenuPanel *)
void filemenu_choose_name_init (MenuPanel *)
void filemenu_choose_name_handle_input (MenuPanel *)
void filemenu_choose_name_update (MenuPanel *)
void filemenu_choose_name_cleanup (MenuPanel *)
void filemenu_draw_message (u8 *, s32, s32, s32, s32, u32)
void filemenu_draw_rect (s32 ulx, s32 uly, s32 lrx, s32 lry, s32 tileIdx, s32 uls, s32 ult, s32 dsdx, s32 dtdy)
Variables
MenuPanel * filemenu_menus []
s32 filemenu_iterFileIdx
s32 filemenu_pressedButtons
s32 filemenu_cursorHudElem
s32 filemenu_heldButtons
s8 filemenu_filename_pos
s32 filemenu_loadedFileIdx
s8 filemenu_currentMenu
s32 filemenu_8024C09C
s32 filemenu_cursorHudElemID [1]
s32 filemenu_8024C0A4 [3]
s32 filemenu_hudElemIDs [20]
s32 filemenu_createfile_hudElems [4]
u8 filemenu_filename [8]
WindowStyleCustom filemenu_windowStyles []
u8 filemenu_createfile_gridData []
Macro Definition Documentation
WINDOW_UPDATE_FUNC
#define WINDOW_UPDATE_FUNC (name)
Value:
    void (name)( \
    s32 windowIdx,\
    s32* flags,\
    s32* posX, s32* posY, s32* posZ,\
    f32* scaleX, f32* scaleY,\
    f32* rotX, f32* rotY, f32* rotZ,\
    s32* darkening,\
    s32* opacity);\
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PAGE_0
PAGE_1
PAGE_2
PAGE_3
PAGE_4
Function Documentation
filemenu_choose_name_cleanup()
void filemenu_choose_name_cleanup (MenuPanel * menu)
filemenu_choose_name_handle_input()
void filemenu_choose_name_handle_input (MenuPanel * menu)
filemenu_choose_name_init()
void filemenu_choose_name_init (MenuPanel * menu)
filemenu_choose_name_update()
void filemenu_choose_name_update (MenuPanel * menu)
filemenu_draw_contents_choose_name()
void filemenu_draw_contents_choose_name (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_copy_arrow()
void filemenu_draw_contents_copy_arrow (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_0_info()
void filemenu_draw_contents_file_0_info (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_0_title()
void filemenu_draw_contents_file_0_title (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_1_info()
void filemenu_draw_contents_file_1_info (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_1_title()
void filemenu_draw_contents_file_1_title (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_2_info()
void filemenu_draw_contents_file_2_info (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_2_title()
void filemenu_draw_contents_file_2_title (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_3_info()
void filemenu_draw_contents_file_3_info (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_3_title()
void filemenu_draw_contents_file_3_title (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_create_header()
void filemenu_draw_contents_file_create_header (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_mono()
void filemenu_draw_contents_mono (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_option_center()
void filemenu_draw_contents_option_center (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_option_left()
void filemenu_draw_contents_option_left (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_option_right()
void filemenu_draw_contents_option_right (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_stereo()
void filemenu_draw_contents_stereo (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_title()
void filemenu_draw_contents_title (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_cursor()
void filemenu_draw_cursor (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_file_name()
void filemenu_draw_file_name (u8 * filename, s32 length, s32 x, s32 y, s32 alpha, s32 arg5, s32 arg6, s32 charWidth)
Referenced by filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_title(), and filemenu_yesno_draw_prompt_contents().
filemenu_draw_message()
void filemenu_draw_message (u8 * message, s32 x, s32 y, s32 alpha, s32 color, u32 flags)
Referenced by filemenu_draw_contents_choose_name(), filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), filemenu_draw_contents_file_title(), filemenu_draw_contents_option_center(), filemenu_draw_contents_option_left(), filemenu_draw_contents_option_right(), filemenu_draw_contents_title(), filemenu_draw_file_name(), filemenu_info_draw_message_contents(), filemenu_yesno_draw_options_contents(), and filemenu_yesno_draw_prompt_contents().
filemenu_draw_rect()
void filemenu_draw_rect (s32 ulx, s32 uly, s32 lrx, s32 lry, s32 tileIdx, s32 uls, s32 ult, s32 dsdx, s32 dtdy)
Referenced by filemenu_draw_char(), filemenu_update_hidden_name_confirm(), and filemenu_update_show_name_confirm().
filemenu_info_cleanup()
void filemenu_info_cleanup (MenuPanel * menu)
filemenu_info_draw_message_contents()
void filemenu_info_draw_message_contents (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_info_handle_input()
void filemenu_info_handle_input (MenuPanel * menu)
filemenu_info_init()
void filemenu_info_init (MenuPanel * tab)
filemenu_info_update()
void filemenu_info_update (MenuPanel * menu)
filemenu_main_cleanup()
void filemenu_main_cleanup (MenuPanel * menu)
filemenu_main_handle_input()
void filemenu_main_handle_input (MenuPanel * menu)
filemenu_main_init()
void filemenu_main_init (MenuPanel * menu)
filemenu_main_update()
void filemenu_main_update (MenuPanel * menu)
filemenu_update_deselect_file()
void filemenu_update_deselect_file (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_yesno_handle_input().
filemenu_update_hidden_name_confirm()
void filemenu_update_hidden_name_confirm (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_yesno_handle_input().
filemenu_update_hidden_name_input()
void filemenu_update_hidden_name_input (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_choose_name_handle_input(), and filemenu_yesno_handle_input().
filemenu_update_hidden_options_bottom()
void filemenu_update_hidden_options_bottom (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_main_handle_input().
filemenu_update_hidden_options_left()
void filemenu_update_hidden_options_left (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_main_handle_input().
filemenu_update_hidden_options_right()
void filemenu_update_hidden_options_right (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_main_handle_input().
filemenu_update_hidden_title()
void filemenu_update_hidden_title (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_main_handle_input(), and filemenu_selectlanguage_handle_input().
filemenu_update_hidden_with_rotation()
void filemenu_update_hidden_with_rotation (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_main_handle_input().
filemenu_update_select_file()
void filemenu_update_select_file (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_main_handle_input().
filemenu_update_show_name_confirm()
void filemenu_update_show_name_confirm (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_choose_name_handle_input(), and filemenu_main_handle_input().
filemenu_update_show_name_input()
void filemenu_update_show_name_input (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_main_handle_input().
filemenu_update_show_options_bottom()
void filemenu_update_show_options_bottom (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_info_handle_input(), and filemenu_main_handle_input().
filemenu_update_show_options_left()
void filemenu_update_show_options_left (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_info_handle_input(), and filemenu_main_handle_input().
filemenu_update_show_options_right()
void filemenu_update_show_options_right (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_info_handle_input(), and filemenu_main_handle_input().
filemenu_update_show_title()
void filemenu_update_show_title (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
filemenu_update_show_with_rotation()
void filemenu_update_show_with_rotation (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_choose_name_handle_input(), and filemenu_yesno_handle_input().
filemenu_yesno_cleanup()
void filemenu_yesno_cleanup (MenuPanel * menu)
filemenu_yesno_draw_options_contents()
void filemenu_yesno_draw_options_contents (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_yesno_draw_prompt_contents()
void filemenu_yesno_draw_prompt_contents (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_yesno_handle_input()
void filemenu_yesno_handle_input (MenuPanel * menu)
filemenu_yesno_init()
void filemenu_yesno_init (MenuPanel * tab)
filemenu_yesno_update()
void filemenu_yesno_update (MenuPanel * menu)
main_menu_window_update()
void main_menu_window_update (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_main_handle_input().
Variable Documentation
filemenu_8024C09C
s32 filemenu_8024C09C extern
filemenu_8024C0A4
s32 filemenu_8024C0A4[3] extern
filemenu_createfile_gridData
u8 filemenu_createfile_gridData[] extern
filemenu_createfile_hudElems
s32 filemenu_createfile_hudElems[4] extern
Referenced by filemenu_choose_name_cleanup(), filemenu_choose_name_init(), filemenu_draw_contents_choose_name(), and filemenu_draw_contents_file_create_header().
filemenu_currentMenu
s8 filemenu_currentMenu extern
Referenced by filemenu_choose_name_handle_input(), filemenu_draw_contents_choose_name(), filemenu_draw_contents_copy_arrow(), filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_title(), filemenu_info_handle_input(), filemenu_init(), filemenu_main_handle_input(), filemenu_update(), filemenu_yesno_draw_options_contents(), filemenu_yesno_handle_input(), func_80244BC4(), and func_filemenu_8024D710().
filemenu_cursorHudElem
s32 filemenu_cursorHudElem extern
Referenced by filemenu_init().
filemenu_cursorHudElemID
s32 filemenu_cursorHudElemID[1] extern
Referenced by filemenu_cleanup(), filemenu_draw_cursor(), and filemenu_init().
filemenu_filename
u8 filemenu_filename[8] extern
Referenced by filemenu_choose_name_handle_input(), filemenu_draw_contents_file_create_header(), filemenu_main_handle_input(), filemenu_yesno_draw_prompt_contents(), and filemenu_yesno_handle_input().
filemenu_filename_pos
s8 filemenu_filename_pos extern
Referenced by filemenu_choose_name_handle_input(), filemenu_draw_contents_file_create_header(), and filemenu_main_handle_input().
filemenu_heldButtons
s32 filemenu_heldButtons extern
Referenced by filemenu_choose_name_handle_input(), filemenu_draw_contents_choose_name(), filemenu_main_handle_input(), filemenu_selectlanguage_handle_input(), filemenu_update(), and filemenu_yesno_handle_input().
filemenu_hudElemIDs
s32 filemenu_hudElemIDs[20] extern
Referenced by filemenu_draw_contents_file_info(), filemenu_draw_contents_mono(), filemenu_draw_contents_stereo(), filemenu_main_cleanup(), and filemenu_main_init().
filemenu_iterFileIdx
s32 filemenu_iterFileIdx extern
Referenced by filemenu_info_draw_message_contents(), filemenu_main_handle_input(), and filemenu_yesno_handle_input().
filemenu_loadedFileIdx
s32 filemenu_loadedFileIdx extern
Referenced by filemenu_draw_contents_copy_arrow(), filemenu_info_draw_message_contents(), filemenu_main_handle_input(), filemenu_main_update(), and filemenu_yesno_handle_input().
filemenu_menus
MenuPanel* filemenu_menus[] extern
Referenced by filemenu_choose_name_handle_input(), filemenu_cleanup(), filemenu_draw_contents_copy_arrow(), filemenu_info_draw_message_contents(), filemenu_info_handle_input(), filemenu_init(), filemenu_main_handle_input(), filemenu_main_update(), filemenu_update(), filemenu_yesno_draw_prompt_contents(), filemenu_yesno_handle_input(), and func_80244BC4().
filemenu_pressedButtons
s32 filemenu_pressedButtons extern
Referenced by filemenu_choose_name_handle_input(), filemenu_info_handle_input(), filemenu_main_handle_input(), filemenu_selectlanguage_handle_input(), filemenu_update(), and filemenu_yesno_handle_input().
filemenu_windowStyles
WindowStyleCustom filemenu_windowStyles[] extern
Referenced by filemenu_main_update(), and filemenu_selectlanguage_update().