papermario: src/filemenu/filemenu_createfile.c File Reference
filemenu_createfile.c File Reference
Macros
#define WINDOW_1_Y (10)
#define WINDOW_2_Y (67)
#define WINDOW_2_HEIGHT (113)
#define ROWS (6)
#define INPUT_FINAL_PAGE (2)
#define FILEMENU_ROW_AMT (17)
#define FILEMENU_C9_OFFSET (5)
Functions
void filemenu_update_change_layout (s32 windowIdx, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void filemenu_draw_contents_file_create_header (MenuPanel *menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
s32 msg_get_print_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u8 flags)
void filemenu_draw_contents_choose_name (MenuPanel *menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
void filemenu_choose_name_init (MenuPanel *menu)
void filemenu_choose_name_handle_input (MenuPanel *menu)
void filemenu_choose_name_update (MenuPanel *menu)
void filemenu_choose_name_cleanup (MenuPanel *menu)
Variables
HudScript HES_FilenameCaret
HudScript HES_FilenameSpace
HudScript HES_134F60_135120
HudScript * filemenu_createfile_hudElemScripts []
s32 D_8024A18C = -4
MenuWindowBP filemenu_createfile_windowBPs []
MenuPanel filemenu_createfile_menuBP
Macro Definition Documentation
FILEMENU_C9_OFFSET
#define FILEMENU_C9_OFFSET (5)
Referenced by filemenu_draw_contents_choose_name().
FILEMENU_ROW_AMT
#define FILEMENU_ROW_AMT (17)
Referenced by filemenu_draw_contents_choose_name().
INPUT_FINAL_PAGE
#define INPUT_FINAL_PAGE (2)
Referenced by filemenu_choose_name_handle_input().
ROWS
#define ROWS (6)
WINDOW_1_Y
#define WINDOW_1_Y (10)
WINDOW_2_HEIGHT
#define WINDOW_2_HEIGHT (113)
WINDOW_2_Y
#define WINDOW_2_Y (67)
Function Documentation
filemenu_choose_name_cleanup()
void filemenu_choose_name_cleanup (MenuPanel * menu)
filemenu_choose_name_handle_input()
void filemenu_choose_name_handle_input (MenuPanel * menu)
filemenu_choose_name_init()
void filemenu_choose_name_init (MenuPanel * menu)
filemenu_choose_name_update()
void filemenu_choose_name_update (MenuPanel * menu)
filemenu_draw_contents_choose_name()
void filemenu_draw_contents_choose_name (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_draw_contents_file_create_header()
void filemenu_draw_contents_file_create_header (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
filemenu_update_change_layout()
void filemenu_update_change_layout (s32 windowIdx, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_choose_name_handle_input(), and filemenu_draw_contents_choose_name().
msg_get_print_char_width()
s32 msg_get_print_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u8 flags)
Referenced by filemenu_draw_contents_choose_name().
Variable Documentation
D_8024A18C
s32 D_8024A18C = -4
Referenced by filemenu_draw_contents_choose_name().
filemenu_createfile_hudElemScripts
HudScript* filemenu_createfile_hudElemScripts[]
Initial value:
= {
    &HES_FilenameCaret, &HES_FilenameSpace, &HES_134F60_135120
}
Referenced by filemenu_choose_name_init().
filemenu_createfile_menuBP
MenuPanel filemenu_createfile_menuBP
Initial value:
= {
    .initialized = FALSE,
    .col = 0,
    .row = 0,
    .selected = 0,
    .page = 0,
    .numCols = 13,
    .numRows =  (6) ,
    .numPages = 0,
    .gridData = filemenu_createfile_gridData,
    .fpInit = &filemenu_choose_name_init,
    .fpHandleInput = &filemenu_choose_name_handle_input,
    .fpUpdate = &filemenu_choose_name_update,
    .fpCleanup = &filemenu_choose_name_cleanup
}
filemenu_createfile_windowBPs
MenuWindowBP filemenu_createfile_windowBPs[]
Initial value:
= {
    {
        .windowID = WINDOW_ID_FILEMENU_CREATEFILE_HEADER,
        .unk_01 = 0,
        .pos = { .x = 68, .y =  (10)  },
        .width = 164,
        .height = 46,
        .priority = WINDOW_PRIORITY_64,
        .fpDrawContents = &filemenu_draw_contents_file_create_header,
        .tab = NULL,
        .parentID = WINDOW_ID_FILEMENU_MAIN,
        .fpUpdate = { WINDOW_UPDATE_HIDE },
        .extraFlags = 0,
        .style = { .customStyle = &filemenu_windowStyles[21] }
    },
    {
        .windowID = WINDOW_ID_FILEMENU_KEYBOARD,
        .unk_01 = 0,
        .pos = { .x = 12, .y =  (67)  },
        .width = 262,
        .height =  (113) ,
        .priority = WINDOW_PRIORITY_64,
        .fpDrawContents = &filemenu_draw_contents_choose_name,
        .tab = NULL,
        .parentID = WINDOW_ID_FILEMENU_MAIN,
        .fpUpdate = { WINDOW_UPDATE_HIDE },
        .extraFlags = 0,
        .style = { .customStyle = &filemenu_windowStyles[22] }
    },
}
Referenced by filemenu_choose_name_init().
HES_134F60_135120
HudScript HES_134F60_135120 extern
HES_FilenameCaret
HudScript HES_FilenameCaret extern
HES_FilenameSpace
HudScript HES_FilenameSpace extern