papermario: src/filemenu/filemenu_msg.c File Reference
filemenu_msg.c File Reference
Functions
s32 msg_get_print_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u8 flags)
s32 filemenu_draw_char (s32 c, s32 x, s32 y, s32 flag1, s32 color, s32 flag2)
void filemenu_draw_message (u8 *message, s32 x, s32 y, s32 alpha, s32 color, u32 flags)
u8 * filemenu_get_menu_message (s32 idx)
void filemenu_draw_file_name (u8 *filename, s32 length, s32 x, s32 y, s32 alpha, s32 arg5, s32 arg6, s32 charWidth)
Variables
MessageCharset * MsgCharsets [5]
PAL_BIN D_802F4560 [80][8]
u8 filemenu_glyphBuffer [20][0x80]
u8 filemenu_msg_C6 [] = { 0x33, 0x30, 0x21, 0x23, 0x25, 0xFD }
u8 filemenu_msg_C7 [] = { 0xFD }
u8 filemenu_msg_C8 [] = { 0xFD }
u8 filemenu_msg_C9 [] = { 0x22, 0x21, 0x23, 0x2B, 0xFD }
u8 filemenu_msg_CA [] = { 0x25, 0x2E, 0x24, 0xFD }
s32 filemenu_specialSymbols [] = { (s32)filemenu_msg_C6, (s32)filemenu_msg_C7, (s32)filemenu_msg_C8, (s32)filemenu_msg_C9, (s32)filemenu_msg_CA }
Gfx filemenu_dl_draw_char_init []
Gfx * filemenu_savedGfxPos = NULL
s32 filemenu_charset = 0
s32 filemenu_charset_raster_id = 0
s32 filemenu_char_color = -1
u8 filemenu_msg_01 []
u8 filemenu_msg_02 []
u8 filemenu_msg_03 []
u8 filemenu_msg_04 []
u8 filemenu_msg_05 []
u8 filemenu_msg_06 [] = { 0x2E, 0x25, 0x37, 0xFD }
u8 filemenu_msg_07 [] = { 0x2C, 0x45, 0x56, 0x45, 0x4C, 0xFD }
u8 filemenu_msg_08 [] = { 0x30, 0x4C, 0x41, 0x59, 0xF7, 0x34, 0x49, 0x4D, 0x45, 0xFD }
u8 filemenu_msg_09 [] = { 0x24, 0x45, 0x4C, 0x45, 0x54, 0x45, 0xF7, 0x26, 0x49, 0x4C, 0x45, 0xFD }
u8 filemenu_msg_10 [] = { 0x23, 0x41, 0x4E, 0x43, 0x45, 0x4C, 0xFD }
u8 filemenu_msg_11 [] = { 0x23, 0x4F, 0x50, 0x59, 0xF7, 0x26, 0x49, 0x4C, 0x45, 0xFD }
u8 filemenu_msg_12 [] = { 0x26, 0x49, 0x52, 0x53, 0x54, 0xF7, 0x30, 0x4C, 0x41, 0x59, 0xFD }
u8 filemenu_msg_13 [] = { 0x0E, 0xFD }
u8 filemenu_msg_14 [] = { 0x39, 0x45, 0x53, 0xFD }
u8 filemenu_msg_15 [] = { 0x2E, 0x4F, 0xFD }
u8 filemenu_msg_16 [] = { 0x24, 0x45, 0x4C, 0x45, 0x54, 0x45, 0xFD }
u8 filemenu_msg_17 []
u8 filemenu_msg_18 [] = { 0x33, 0x41, 0x56, 0x45, 0xF7, 0x2F, 0x2B, 0x1F, 0xFD }
u8 filemenu_msg_19 [] = { 0x26, 0x49, 0x4C, 0x45, 0xF7, 0x4E, 0x41, 0x4D, 0x45, 0xF7, 0x49, 0x53, 0xF7, 0x1A, 0xFD }
u8 filemenu_msg_20 [] = { 0x0E, 0xFD }
u8 filemenu_msg_21 [] = { 0x2F, 0x2B, 0x1F, 0xFD }
u8 filemenu_msg_22 [] = { 0x26, 0x49, 0x4C, 0x45, 0xFD }
u8 filemenu_msg_23 []
u8 filemenu_msg_24 []
u8 filemenu_msg_25 [] = { 0x33, 0x54, 0x41, 0x52, 0x54, 0xF7, 0x47, 0x41, 0x4D, 0x45, 0xF7, 0x57, 0x49, 0x54, 0x48, 0xFD }
u8 filemenu_msg_26 [] = { 0x26, 0x49, 0x4C, 0x45, 0xFD }
u8 filemenu_msg_27 []
u8 filemenu_msg_28 [] = { 0xFD }
u8 filemenu_msg_29 [] = { 0x23, 0x4F, 0x50, 0x59, 0xF7, 0x46, 0x52, 0x4F, 0x4D, 0xFD }
u8 filemenu_msg_30 [] = { 0x54, 0x4F, 0xFD }
u8 filemenu_msg_31 []
u8 filemenu_msg_32 []
u8 filemenu_createfile_gridData []
u8 filemenu_msg_33 [] = { 0x1F, 0xFD }
u8 filemenu_msg_34 [] = { 0x0E, 0xFD }
u8 * gFileMenuMessages []
Function Documentation
filemenu_draw_char()
s32 filemenu_draw_char (s32 c, s32 x, s32 y, s32 flag1, s32 color, s32 flag2)
Referenced by filemenu_draw_message().
filemenu_draw_file_name()
void filemenu_draw_file_name (u8 * filename, s32 length, s32 x, s32 y, s32 alpha, s32 arg5, s32 arg6, s32 charWidth)
Referenced by filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_title(), and filemenu_yesno_draw_prompt_contents().
filemenu_draw_message()
void filemenu_draw_message (u8 * message, s32 x, s32 y, s32 alpha, s32 color, u32 flags)
Referenced by filemenu_draw_contents_choose_name(), filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), filemenu_draw_contents_file_title(), filemenu_draw_contents_option_center(), filemenu_draw_contents_option_left(), filemenu_draw_contents_option_right(), filemenu_draw_contents_title(), filemenu_draw_file_name(), filemenu_info_draw_message_contents(), filemenu_yesno_draw_options_contents(), and filemenu_yesno_draw_prompt_contents().
filemenu_get_menu_message()
u8 * filemenu_get_menu_message (s32 idx)
Referenced by filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), filemenu_draw_contents_file_title(), filemenu_draw_contents_option_center(), filemenu_draw_contents_option_left(), filemenu_draw_contents_option_right(), filemenu_draw_contents_title(), filemenu_info_draw_message_contents(), filemenu_yesno_draw_options_contents(), and filemenu_yesno_draw_prompt_contents().
msg_get_print_char_width()
s32 msg_get_print_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u8 flags)
Referenced by filemenu_draw_file_name().
Variable Documentation
D_802F4560
PAL_BIN D_802F4560[80][8] extern
Referenced by filemenu_draw_char().
filemenu_char_color
s32 filemenu_char_color = -1
Referenced by filemenu_draw_char().
filemenu_charset
s32 filemenu_charset = 0
Referenced by filemenu_draw_char().
filemenu_charset_raster_id
s32 filemenu_charset_raster_id = 0
Referenced by filemenu_draw_char().
filemenu_createfile_gridData
u8 filemenu_createfile_gridData[]
Initial value:
= { 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D,
                                  0x2E, 0x2F, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A,
                                  0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x4B, 0x4C, 0x4D,
                                  0x4E, 0x4F, 0x50, 0x51, 0x52, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A,
                                  0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x10, 0x0E, 0x0D, 0xF7,
                                  0x00, 0x90, 0x91, 0x20, 0xC6, 0xF7, 0xF7, 0xC9, 0xF7, 0xF7, 0xCA, 0xF7, 0xF7
}
filemenu_dl_draw_char_init
Gfx filemenu_dl_draw_char_init[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetRenderMode(G_RM_TEX_EDGE, G_RM_TEX_EDGE2),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsDPSetPrimColor(0, 0, 40, 40, 40, 72),
    gsSPEndDisplayList(),
}
Referenced by filemenu_draw_char().
filemenu_glyphBuffer
u8 filemenu_glyphBuffer[20][0x80] extern
Referenced by filemenu_draw_char().
filemenu_msg_01
u8 filemenu_msg_01[]
Initial value:
= { 0x33, 0x45, 0x4C, 0x45, 0x43, 0x54, 0xF7, 0x46, 0x49, 0x4C, 0x45, 0xF7, 0x54, 0x4F, 0xF7, 0x53,
                    0x54, 0x41, 0x52, 0x54, 0x1A, 0xFD }
filemenu_msg_02
u8 filemenu_msg_02[]
Initial value:
= { 0x33, 0x45, 0x4C, 0x45, 0x43, 0x54, 0xF7, 0x46, 0x49, 0x4C, 0x45, 0xF7, 0x54, 0x4F, 0xF7, 0x44,
                    0x45, 0x4C, 0x45, 0x54, 0x45, 0x1A, 0xFD }
filemenu_msg_03
u8 filemenu_msg_03[]
Initial value:
= { 0x33, 0x45, 0x4C, 0x45, 0x43, 0x54, 0xF7, 0x46, 0x49, 0x4C, 0x45, 0xF7, 0x54, 0x4F, 0xF7, 0x53,
                    0x41, 0x56, 0x45, 0xFD }
filemenu_msg_04
u8 filemenu_msg_04[]
Initial value:
= { 0x23, 0x4F, 0x50, 0x59, 0xF7, 0x57, 0x48, 0x49, 0x43, 0x48, 0xF7, 0x46, 0x49, 0x4C, 0x45, 0x1F,
                    0xFD }
filemenu_msg_05
u8 filemenu_msg_05[]
Initial value:
= { 0x23, 0x4F, 0x50, 0x59, 0xF7, 0x54, 0x4F, 0xF7, 0x57, 0x48, 0x49, 0x43, 0x48, 0xF7, 0x46, 0x49,
                    0x4C, 0x45, 0x1F, 0xFD }
filemenu_msg_06
u8 filemenu_msg_06[] = { 0x2E, 0x25, 0x37, 0xFD }
filemenu_msg_07
u8 filemenu_msg_07[] = { 0x2C, 0x45, 0x56, 0x45, 0x4C, 0xFD }
filemenu_msg_08
u8 filemenu_msg_08[] = { 0x30, 0x4C, 0x41, 0x59, 0xF7, 0x34, 0x49, 0x4D, 0x45, 0xFD }
filemenu_msg_09
u8 filemenu_msg_09[] = { 0x24, 0x45, 0x4C, 0x45, 0x54, 0x45, 0xF7, 0x26, 0x49, 0x4C, 0x45, 0xFD }
filemenu_msg_10
u8 filemenu_msg_10[] = { 0x23, 0x41, 0x4E, 0x43, 0x45, 0x4C, 0xFD }
filemenu_msg_11
u8 filemenu_msg_11[] = { 0x23, 0x4F, 0x50, 0x59, 0xF7, 0x26, 0x49, 0x4C, 0x45, 0xFD }
filemenu_msg_12
u8 filemenu_msg_12[] = { 0x26, 0x49, 0x52, 0x53, 0x54, 0xF7, 0x30, 0x4C, 0x41, 0x59, 0xFD }
filemenu_msg_13
u8 filemenu_msg_13[] = { 0x0E, 0xFD }
filemenu_msg_14
u8 filemenu_msg_14[] = { 0x39, 0x45, 0x53, 0xFD }
filemenu_msg_15
u8 filemenu_msg_15[] = { 0x2E, 0x4F, 0xFD }
filemenu_msg_16
u8 filemenu_msg_16[] = { 0x24, 0x45, 0x4C, 0x45, 0x54, 0x45, 0xFD }
filemenu_msg_17
u8 filemenu_msg_17[]
Initial value:
= { 0x2F, 0x56, 0x45, 0x52, 0x52, 0x49, 0x44, 0x45, 0xF7, 0x54, 0x4F, 0xF7, 0x2E, 0x45, 0x57, 0xF7,
                    0x24, 0x41, 0x54, 0x41, 0xFD }
filemenu_msg_18
u8 filemenu_msg_18[] = { 0x33, 0x41, 0x56, 0x45, 0xF7, 0x2F, 0x2B, 0x1F, 0xFD }
filemenu_msg_19
u8 filemenu_msg_19[] = { 0x26, 0x49, 0x4C, 0x45, 0xF7, 0x4E, 0x41, 0x4D, 0x45, 0xF7, 0x49, 0x53, 0xF7, 0x1A, 0xFD }
filemenu_msg_20
u8 filemenu_msg_20[] = { 0x0E, 0xFD }
filemenu_msg_21
u8 filemenu_msg_21[] = { 0x2F, 0x2B, 0x1F, 0xFD }
filemenu_msg_22
u8 filemenu_msg_22[] = { 0x26, 0x49, 0x4C, 0x45, 0xFD }
filemenu_msg_23
u8 filemenu_msg_23[]
Initial value:
= { 0x57, 0x49, 0x4C, 0x4C, 0xF7, 0x42, 0x45, 0xF7, 0x44, 0x45, 0x4C, 0x45, 0x54, 0x45, 0x44, 0x0E,
                    0xFD }
filemenu_msg_24
u8 filemenu_msg_24[]
Initial value:
= { 0x2F, 0x2B, 0xF7, 0x54, 0x4F, 0xF7, 0x43, 0x4F, 0x50, 0x59, 0xF7, 0x54, 0x4F, 0xF7, 0x54, 0x48,
                    0x49, 0x53, 0xF7, 0x46, 0x49, 0x4C, 0x45, 0x1F, 0xFD }
filemenu_msg_25
u8 filemenu_msg_25[] = { 0x33, 0x54, 0x41, 0x52, 0x54, 0xF7, 0x47, 0x41, 0x4D, 0x45, 0xF7, 0x57, 0x49, 0x54, 0x48, 0xFD }
filemenu_msg_26
u8 filemenu_msg_26[] = { 0x26, 0x49, 0x4C, 0x45, 0xFD }
filemenu_msg_27
u8 filemenu_msg_27[]
Initial value:
= { 0x48, 0x41, 0x53, 0xF7, 0x42, 0x45, 0x45, 0x4E, 0xF7, 0x44, 0x45, 0x4C, 0x45, 0x54, 0x45, 0x44,
                    0x0E, 0xFD }
filemenu_msg_28
u8 filemenu_msg_28[] = { 0xFD }
filemenu_msg_29
u8 filemenu_msg_29[] = { 0x23, 0x4F, 0x50, 0x59, 0xF7, 0x46, 0x52, 0x4F, 0x4D, 0xFD }
filemenu_msg_30
u8 filemenu_msg_30[] = { 0x54, 0x4F, 0xFD }
filemenu_msg_31
u8 filemenu_msg_31[]
Initial value:
= { 0x48, 0x41, 0x53, 0xF7, 0x42, 0x45, 0x45, 0x4E, 0xF7, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44,
                    0x0E, 0xFD }
filemenu_msg_32
u8 filemenu_msg_32[]
Initial value:
= { 0x25, 0x4E, 0x54, 0x45, 0x52, 0xF7, 0x41, 0xF7, 0x46, 0x49, 0x4C, 0x45, 0xF7, 0x4E, 0x41, 0x4D,
                    0x45, 0x01, 0xFD }
filemenu_msg_33
u8 filemenu_msg_33[] = { 0x1F, 0xFD }
filemenu_msg_34
u8 filemenu_msg_34[] = { 0x0E, 0xFD }
filemenu_msg_C6
u8 filemenu_msg_C6[] = { 0x33, 0x30, 0x21, 0x23, 0x25, 0xFD }
filemenu_msg_C7
u8 filemenu_msg_C7[] = { 0xFD }
filemenu_msg_C8
u8 filemenu_msg_C8[] = { 0xFD }
filemenu_msg_C9
u8 filemenu_msg_C9[] = { 0x22, 0x21, 0x23, 0x2B, 0xFD }
filemenu_msg_CA
u8 filemenu_msg_CA[] = { 0x25, 0x2E, 0x24, 0xFD }
filemenu_savedGfxPos
Gfx* filemenu_savedGfxPos = NULL
Referenced by filemenu_draw_char().
filemenu_specialSymbols
s32 filemenu_specialSymbols[] = { (s32)filemenu_msg_C6, (s32)filemenu_msg_C7, (s32)filemenu_msg_C8, (s32)filemenu_msg_C9, (s32)filemenu_msg_CA }
Referenced by filemenu_draw_message().
gFileMenuMessages
u8* gFileMenuMessages[]
Referenced by filemenu_get_menu_message().
MsgCharsets
MessageCharset* MsgCharsets[5] extern
Referenced by filemenu_draw_char().