papermario: src/fio.h File Reference
fio.h File Reference
Functions
b32 fio_load_globals (void)
b32 fio_save_globals (void)
b32 fio_load_game (s32 saveSlot)
void fio_save_game (s32 saveSlot)
void fio_erase_game (s32 saveSlot)
Variables
SaveMetadata gSaveSlotMetadata [4]
u8 gSaveSlotHasData [4]
SaveGlobals gSaveGlobals
Function Documentation
fio_erase_game()
void fio_erase_game (s32 saveSlot)
Referenced by filemenu_yesno_handle_input().
fio_load_game()
b32 fio_load_game (s32 saveSlot)
Referenced by filemenu_init(), filemenu_main_handle_input(), and filemenu_yesno_handle_input().
fio_load_globals()
b32 fio_load_globals (void)
Referenced by filemenu_init(), and state_step_startup().
fio_save_game()
void fio_save_game (s32 saveSlot)
Referenced by entity_SaveBlock_save_data(), filemenu_main_handle_input(), and filemenu_yesno_handle_input().
fio_save_globals()
b32 fio_save_globals (void)
Referenced by filemenu_yesno_handle_input().
Variable Documentation
gSaveGlobals
SaveGlobals gSaveGlobals extern
Referenced by filemenu_init(), filemenu_yesno_handle_input(), fio_calc_globals_checksum(), fio_load_globals(), fio_save_globals(), fio_validate_globals_checksums(), and state_step_startup().
gSaveSlotHasData
u8 gSaveSlotHasData[4] extern
Referenced by filemenu_draw_contents_file_info(), filemenu_draw_contents_file_title(), filemenu_init(), filemenu_main_handle_input(), and filemenu_yesno_handle_input().
gSaveSlotMetadata
SaveMetadata gSaveSlotMetadata[4] extern
Referenced by filemenu_draw_contents_file_info(), filemenu_draw_contents_file_title(), filemenu_init(), filemenu_main_handle_input(), filemenu_yesno_handle_input(), fio_deserialize_state(), and fio_serialize_state().