papermario: src/fio.c File Reference
fio.c File Reference
Data Structures
struct SaveInfo
Macros
#define GLOBALS_PAGE_1 6
#define GLOBALS_PAGE_2 7
Functions
void fio_deserialize_state (void)
void fio_serialize_state (void)
b32 fio_read_flash (s32 pageNum, void *readBuffer, u32 numBytes)
b32 fio_write_flash (s32 pageNum, s8 *readBuffer, u32 numBytes)
s32 fio_erase_flash (s32 pageNum)
s32 get_spirits_rescued (void)
s32 fio_calc_globals_checksum (void)
b32 fio_validate_globals_checksums (void)
b32 fio_load_globals (void)
b32 fio_save_globals (void)
s32 fio_calc_file_checksum (SaveData *saveData)
b32 fio_validate_file_checksum (SaveData *saveData)
b32 fio_fetch_saved_file_info (void)
b32 fio_load_game (s32 saveSlot)
void fio_save_game (s32 saveSlot)
void fio_erase_game (s32 saveSlot)
void func_8002B608 (void)
void fio_init_flash (void)
Variables
BSS SaveData FetchSaveBuffer
BSS SaveInfo LogicalSaveInfo [4]
BSS SaveInfo PhysicalSaveInfo [6]
BSS s32 NextAvailablePhysicalSave
SaveGlobals gSaveGlobals
SaveData gCurrentSaveFile
char MagicSaveString [] = "Mario Story 006"
Data Structure Documentation
SaveInfo
struct SaveInfo
Data Fields
s32 count
s32 slot
Macro Definition Documentation
GLOBALS_PAGE_1
#define GLOBALS_PAGE_1 6
Referenced by fio_load_globals(), and fio_save_globals().
GLOBALS_PAGE_2
#define GLOBALS_PAGE_2 7
Referenced by fio_load_globals(), and fio_save_globals().
Function Documentation
fio_calc_file_checksum()
s32 fio_calc_file_checksum (SaveData * saveData)
Referenced by fio_save_game(), and fio_validate_file_checksum().
fio_calc_globals_checksum()
s32 fio_calc_globals_checksum (void)
Referenced by fio_save_globals(), and fio_validate_globals_checksums().
fio_deserialize_state()
void fio_deserialize_state (void)
Referenced by fio_load_game(), and load_map_by_IDs().
fio_erase_flash()
s32 fio_erase_flash (s32 pageNum)
Referenced by fio_erase_game(), fio_save_game(), and fio_save_globals().
fio_erase_game()
void fio_erase_game (s32 saveSlot)
Referenced by filemenu_yesno_handle_input().
fio_fetch_saved_file_info()
b32 fio_fetch_saved_file_info (void)
Referenced by fio_erase_game(), fio_load_game(), and fio_save_game().
fio_init_flash()
void fio_init_flash (void)
Referenced by load_engine_data().
fio_load_game()
b32 fio_load_game (s32 saveSlot)
Referenced by filemenu_init(), filemenu_main_handle_input(), and filemenu_yesno_handle_input().
fio_load_globals()
b32 fio_load_globals (void)
Referenced by filemenu_init(), and state_step_startup().
fio_read_flash()
b32 fio_read_flash (s32 pageNum, void * readBuffer, u32 numBytes)
Referenced by fio_fetch_saved_file_info(), fio_load_game(), fio_load_globals(), and fio_save_game().
fio_save_game()
void fio_save_game (s32 saveSlot)
Referenced by entity_SaveBlock_save_data(), filemenu_main_handle_input(), and filemenu_yesno_handle_input().
fio_save_globals()
b32 fio_save_globals (void)
Referenced by filemenu_yesno_handle_input().
fio_serialize_state()
void fio_serialize_state (void)
Referenced by fio_save_game(), and func_8002B608().
fio_validate_file_checksum()
b32 fio_validate_file_checksum (SaveData * saveData)
Referenced by fio_fetch_saved_file_info(), and fio_load_game().
fio_validate_globals_checksums()
b32 fio_validate_globals_checksums (void)
Referenced by fio_load_globals().
fio_write_flash()
b32 fio_write_flash (s32 pageNum, s8 * readBuffer, u32 numBytes)
Referenced by fio_save_game(), and fio_save_globals().
func_8002B608()
void func_8002B608 (void)
get_spirits_rescued()
s32 get_spirits_rescued (void)
Referenced by fio_serialize_state().
Variable Documentation
FetchSaveBuffer
BSS SaveData FetchSaveBuffer
Referenced by fio_fetch_saved_file_info(), and fio_save_game().
gCurrentSaveFile
SaveData gCurrentSaveFile
Referenced by clear_area_flag(), clear_area_flags(), clear_global_flag(), clear_saved_variables(), filemenu_init(), fio_deserialize_state(), fio_load_game(), fio_save_game(), fio_serialize_state(), get_area_byte(), get_area_flag(), get_global_byte(), get_global_flag(), set_area_byte(), set_area_flag(), set_global_byte(), and set_global_flag().
gSaveGlobals
SaveGlobals gSaveGlobals
Referenced by fio_calc_globals_checksum(), fio_load_globals(), fio_save_globals(), and fio_validate_globals_checksums().
LogicalSaveInfo
BSS SaveInfo LogicalSaveInfo[4]
Referenced by fio_fetch_saved_file_info(), and fio_load_game().
MagicSaveString
char MagicSaveString[] = "Mario Story 006"
Referenced by fio_load_game(), fio_save_game(), fio_save_globals(), fio_validate_file_checksum(), and fio_validate_globals_checksums().
NextAvailablePhysicalSave
BSS s32 NextAvailablePhysicalSave
Referenced by fio_fetch_saved_file_info(), and fio_save_game().
PhysicalSaveInfo
BSS SaveInfo PhysicalSaveInfo[6]
Referenced by fio_erase_game(), and fio_fetch_saved_file_info().