papermario: src/effects/fire_breath.c File Reference
fire_breath.c File Reference
Functions
void fire_breath_init (EffectInstance *effect)
void fire_breath_update (EffectInstance *effect)
void fire_breath_render (EffectInstance *effect)
void fire_breath_appendGfx (void *effect)
EffectInstance * fire_breath_main (s32 type, f32 startX, f32 startY, f32 startZ, f32 endX, f32 endY, f32 endZ, s32 numExtra, s32 spawnDelay, s32 duration)
Variables
Gfx D_09000A00_373DE0 []
Gfx D_09000B88_373F68 []
Gfx D_09000C00_373FE0 []
Gfx D_09000C20_374000 []
Gfx * D_E006EC00 [] = { D_09000B88_373F68, D_09000B88_373F68, D_09000B88_373F68 }
Gfx * D_E006EC0C [] = { D_09000A00_373DE0, D_09000A00_373DE0, D_09000A00_373DE0 }
Function Documentation
fire_breath_appendGfx()
void fire_breath_appendGfx (void * effect)
Referenced by fire_breath_render().
fire_breath_init()
void fire_breath_init (EffectInstance * effect)
Referenced by fire_breath_main().
fire_breath_main()
EffectInstance * fire_breath_main (s32 type, f32 startX, f32 startY, f32 startZ, f32 endX, f32 endY, f32 endZ, s32 numExtra, s32 spawnDelay, s32 duration)
Referenced by fire_breath_update().
fire_breath_render()
void fire_breath_render (EffectInstance * effect)
Referenced by fire_breath_main().
fire_breath_update()
void fire_breath_update (EffectInstance * effect)
Referenced by fire_breath_main().
Variable Documentation
D_09000A00_373DE0
Gfx D_09000A00_373DE0[] extern
D_09000B88_373F68
Gfx D_09000B88_373F68[] extern
D_09000C00_373FE0
Gfx D_09000C00_373FE0[] extern
Referenced by fire_breath_appendGfx().
D_09000C20_374000
Gfx D_09000C20_374000[] extern
Referenced by fire_breath_appendGfx().
D_E006EC00
Gfx* D_E006EC00[] = { D_09000B88_373F68, D_09000B88_373F68, D_09000B88_373F68 }
Referenced by fire_breath_appendGfx().
D_E006EC0C
Gfx* D_E006EC0C[] = { D_09000A00_373DE0, D_09000A00_373DE0, D_09000A00_373DE0 }
Referenced by fire_breath_appendGfx().