papermario: src/effects/firework.c File Reference
firework.c File Reference
Functions
void firework_init (EffectInstance *effect)
void firework_update (EffectInstance *effect)
void firework_render (EffectInstance *effect)
void func_E0086398 (EffectInstance *effect)
void func_E00863B4 (EffectInstance *effect)
EffectInstance * firework_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09000940_38AC90 []
Gfx D_09000A00_38AD50 []
Gfx D_09000A20_38AD70 []
Gfx D_09000A40_38AD90 []
Gfx D_09000A60_38ADB0 []
Gfx D_09000A80_38ADD0 []
Gfx * D_E0086AA0 []
Gfx * D_E0086AB4 [] = { D_09000940_38AC90, D_09000940_38AC90, D_09000940_38AC90 }
u8 D_E0086AC0 [] = { 0x0D, 0x0D, 0x0D, 0x00 }
u8 D_E0086AC4 []
u8 D_E0086AD4 []
u8 D_E0086AE4 []
Function Documentation
firework_init()
void firework_init (EffectInstance * effect)
Referenced by firework_main().
firework_main()
EffectInstance * firework_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
firework_render()
void firework_render (EffectInstance * effect)
Referenced by firework_main().
firework_update()
void firework_update (EffectInstance * effect)
Referenced by firework_main().
func_E0086398()
void func_E0086398 (EffectInstance * effect)
Referenced by firework_main().
func_E00863B4()
void func_E00863B4 (EffectInstance * effect)
Referenced by func_E0086398().
Variable Documentation
D_09000940_38AC90
Gfx D_09000940_38AC90[] extern
D_09000A00_38AD50
Gfx D_09000A00_38AD50[] extern
D_09000A20_38AD70
Gfx D_09000A20_38AD70[] extern
D_09000A40_38AD90
Gfx D_09000A40_38AD90[] extern
D_09000A60_38ADB0
Gfx D_09000A60_38ADB0[] extern
D_09000A80_38ADD0
Gfx D_09000A80_38ADD0[] extern
D_E0086AA0
Gfx* D_E0086AA0[]
Initial value:
= {
    D_09000A00_38AD50, D_09000A20_38AD70, D_09000A40_38AD90,
    D_09000A60_38ADB0, D_09000A80_38ADD0
}
Referenced by func_E00863B4().
D_E0086AB4
Gfx* D_E0086AB4[] = { D_09000940_38AC90, D_09000940_38AC90, D_09000940_38AC90 }
Referenced by func_E00863B4().
D_E0086AC0
u8 D_E0086AC0[] = { 0x0D, 0x0D, 0x0D, 0x00 }
Referenced by firework_main(), and firework_update().
D_E0086AC4
u8 D_E0086AC4[]
Initial value:
= {
    0x40, 0x68, 0x90, 0xA4, 0xB8, 0xC0, 0xD0, 0xD8,
    0xE0, 0xE8, 0xF0, 0xF8, 0xFF, 0x00, 0x00, 0x00
}
Referenced by firework_update().
D_E0086AD4
u8 D_E0086AD4[]
Initial value:
= {
    0x0A, 0x14, 0x1C, 0x23, 0x2A, 0x30, 0x35, 0x39,
    0x3C, 0x3E, 0x3F, 0x40, 0x41, 0x00, 0x00, 0x00
}
Referenced by firework_update().
D_E0086AE4
u8 D_E0086AE4[]
Initial value:
= {
    0xFF, 0xFF, 0xC8, 0x82, 0x3C, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00
}
Referenced by func_E00863B4().