papermario: src/effects/flame.c File Reference
flame.c File Reference
Data Structures
struct FlamePreset
Functions
void flame_init (EffectInstance *effect)
void flame_update (EffectInstance *effect)
void flame_render (EffectInstance *effect)
void flame_appendGfx (void *effect)
void flame_main (s32 type, f32 arg1, f32 arg2, f32 arg3, f32 arg4, EffectInstance **outEffect)
Variables
Gfx D_09000800_3543B0 []
Gfx D_090008F8_3544A8 []
Gfx D_09000918_3544C8 []
Gfx D_090009E0_354590 []
FlamePreset FlamePresets []
s32 LastFlameRenderFrame = 0
Data Structure Documentation
FlamePreset
struct FlamePreset
Data Fields
Color_RGB8 colorScale
Gfx * dlist
Color_RGB8 envColor
s8 keyCenter
s8 primIntensity
u8 sizeScale
Function Documentation
flame_appendGfx()
void flame_appendGfx (void * effect)
Referenced by flame_render().
flame_init()
void flame_init (EffectInstance * effect)
Referenced by flame_main().
flame_main()
void flame_main (s32 type, f32 arg1, f32 arg2, f32 arg3, f32 arg4, EffectInstance ** outEffect)
flame_render()
void flame_render (EffectInstance * effect)
Referenced by flame_main().
flame_update()
void flame_update (EffectInstance * effect)
Referenced by flame_main().
Variable Documentation
D_09000800_3543B0
Gfx D_09000800_3543B0[] extern
D_090008F8_3544A8
Gfx D_090008F8_3544A8[] extern
Referenced by flame_appendGfx().
D_09000918_3544C8
Gfx D_09000918_3544C8[] extern
Referenced by flame_appendGfx().
D_090009E0_354590
Gfx D_090009E0_354590[] extern
Referenced by flame_appendGfx().
FlamePresets
FlamePreset FlamePresets[]
Referenced by flame_appendGfx(), and flame_main().
LastFlameRenderFrame
s32 LastFlameRenderFrame = 0
Referenced by flame_appendGfx().