papermario: src/effects/flashing_box_shockwave.c File Reference
flashing_box_shockwave.c File Reference
Functions
void flashing_box_shockwave_init (EffectInstance *effect)
void flashing_box_shockwave_update (EffectInstance *effect)
void flashing_box_shockwave_render (EffectInstance *effect)
void flashing_box_shockwave_appendGfx (void *effect)
EffectInstance * flashing_box_shockwave_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 sizeX, f32 sizeY)
Variables
Gfx D_09000600_3936A0 []
Gfx D_090008E8_393988 []
Gfx D_09000950_3939F0 []
Gfx D_09000FF8_394098 []
Function Documentation
flashing_box_shockwave_appendGfx()
void flashing_box_shockwave_appendGfx (void * effect)
Referenced by flashing_box_shockwave_render().
flashing_box_shockwave_init()
void flashing_box_shockwave_init (EffectInstance * effect)
Referenced by flashing_box_shockwave_main().
flashing_box_shockwave_main()
EffectInstance * flashing_box_shockwave_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 sizeX, f32 sizeY)
Referenced by lightning_main().
flashing_box_shockwave_render()
void flashing_box_shockwave_render (EffectInstance * effect)
Referenced by flashing_box_shockwave_main().
flashing_box_shockwave_update()
void flashing_box_shockwave_update (EffectInstance * effect)
Referenced by flashing_box_shockwave_main().
Variable Documentation
D_09000600_3936A0
Gfx D_09000600_3936A0[] extern
Referenced by flashing_box_shockwave_appendGfx().
D_090008E8_393988
Gfx D_090008E8_393988[] extern
Referenced by flashing_box_shockwave_appendGfx().
D_09000950_3939F0
Gfx D_09000950_3939F0[] extern
Referenced by flashing_box_shockwave_appendGfx().
D_09000FF8_394098
Gfx D_09000FF8_394098[] extern
Referenced by flashing_box_shockwave_appendGfx().