papermario: src/battle/action_cmd/flee.h File Reference
flee.h File Reference
Functions
void action_command_flee_update (void)
void action_command_flee_draw (void)
void action_command_flee_free (void)
Function Documentation
action_command_flee_draw()
void action_command_flee_draw (void)
Referenced by action_command_draw().
action_command_flee_free()
void action_command_flee_free (void)
Referenced by action_command_free().
action_command_flee_update()
void action_command_flee_update (void)
Referenced by action_command_update().