papermario: src/effects/floating_flower.c File Reference
floating_flower.c File Reference
Functions
void floating_flower_init (EffectInstance *effect)
void floating_flower_update (EffectInstance *effect)
void floating_flower_render (EffectInstance *effect)
void floating_flower_appendGfx (void *effect)
void floating_flower_main (s32 type, f32 posX, f32 posY, f32 posZ, s32 duration)
Variables
s32 D_E001A610 = 0
Gfx D_090002F0_330750 []
Function Documentation
floating_flower_appendGfx()
void floating_flower_appendGfx (void * effect)
Referenced by floating_flower_render().
floating_flower_init()
void floating_flower_init (EffectInstance * effect)
Referenced by floating_flower_main().
floating_flower_main()
void floating_flower_main (s32 type, f32 posX, f32 posY, f32 posZ, s32 duration)
floating_flower_render()
void floating_flower_render (EffectInstance * effect)
Referenced by floating_flower_main().
floating_flower_update()
void floating_flower_update (EffectInstance * effect)
Referenced by floating_flower_main().
Variable Documentation
D_090002F0_330750
Gfx D_090002F0_330750[] extern
Referenced by floating_flower_appendGfx().
D_E001A610
s32 D_E001A610 = 0
Referenced by floating_flower_main().