papermario: src/effects/floating_rock.c File Reference
floating_rock.c File Reference
Functions
void floating_rock_init (EffectInstance *effect)
void floating_rock_update (EffectInstance *effect)
void floating_rock_render (EffectInstance *effect)
void floating_rock_appendGfx (void *effect)
EffectInstance * floating_rock_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 floorY, f32 fallVelocity, f32 fallAccel, f32 scale, s32 duration)
EFFECT_DEF_DUST (dust_main)
Variables
Gfx D_090003A0_396490 []
Gfx D_090003E0_3964D0 []
Gfx D_09000410_396500 []
Gfx D_09000450_396540 []
Gfx * D_E0098510 []
Function Documentation
EFFECT_DEF_DUST()
EFFECT_DEF_DUST (dust_main)
floating_rock_appendGfx()
void floating_rock_appendGfx (void * effect)
Referenced by floating_rock_render().
floating_rock_init()
void floating_rock_init (EffectInstance * effect)
Referenced by floating_rock_main().
floating_rock_main()
EffectInstance * floating_rock_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 floorY, f32 fallVelocity, f32 fallAccel, f32 scale, s32 duration)
floating_rock_render()
void floating_rock_render (EffectInstance * effect)
Referenced by floating_rock_main().
floating_rock_update()
void floating_rock_update (EffectInstance * effect)
Referenced by floating_rock_main().
Variable Documentation
D_090003A0_396490
Gfx D_090003A0_396490[] extern
D_090003E0_3964D0
Gfx D_090003E0_3964D0[] extern
D_09000410_396500
Gfx D_09000410_396500[] extern
D_09000450_396540
Gfx D_09000450_396540[] extern
Referenced by floating_rock_appendGfx().
D_E0098510
Gfx* D_E0098510[]
Initial value:
= {
    D_090003A0_396490, D_090003E0_3964D0, D_09000410_396500,
    D_090003A0_396490, D_090003E0_3964D0, D_09000410_396500
}
Referenced by floating_rock_appendGfx().