papermario: src/effects/floating_cloud_puff.c File Reference
floating_cloud_puff.c File Reference
Functions
void floating_cloud_puff_init (EffectInstance *effect)
void floating_cloud_puff_update (EffectInstance *effect)
void floating_cloud_puff_render (EffectInstance *effect)
void floating_cloud_puff_appendGfx (void *effect)
EffectInstance * floating_cloud_puff_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00D227C (void)
Variables
Gfx D_09000080_3D4F10 []
Gfx D_09000168_3D4FF8 []
u8 D_E00D2500 [] = { 0x00, 0x1E, 0x50, 0x78, 0x70, 0x68, 0x64, 0x00 }
u8 D_E00D2508 [] = { 0x5E, 0x5C, 0x64, 0x69, 0x6B, 0x69, 0x64, 0x00 }
Function Documentation
floating_cloud_puff_appendGfx()
void floating_cloud_puff_appendGfx (void * effect)
Referenced by floating_cloud_puff_render().
floating_cloud_puff_init()
void floating_cloud_puff_init (EffectInstance * effect)
Referenced by floating_cloud_puff_main().
floating_cloud_puff_main()
EffectInstance * floating_cloud_puff_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Referenced by tubba_heart_attack_update().
floating_cloud_puff_render()
void floating_cloud_puff_render (EffectInstance * effect)
Referenced by floating_cloud_puff_main().
floating_cloud_puff_update()
void floating_cloud_puff_update (EffectInstance * effect)
Referenced by floating_cloud_puff_main().
func_E00D227C()
void func_E00D227C (void)
Variable Documentation
D_09000080_3D4F10
Gfx D_09000080_3D4F10[] extern
Referenced by floating_cloud_puff_appendGfx().
D_09000168_3D4FF8
Gfx D_09000168_3D4FF8[] extern
Referenced by floating_cloud_puff_appendGfx().
D_E00D2500
u8 D_E00D2500[] = { 0x00, 0x1E, 0x50, 0x78, 0x70, 0x68, 0x64, 0x00 }
Referenced by floating_cloud_puff_update().
D_E00D2508
u8 D_E00D2508[] = { 0x5E, 0x5C, 0x64, 0x69, 0x6B, 0x69, 0x64, 0x00 }
Referenced by floating_cloud_puff_update().