papermario: src/effects/flower_trail.c File Reference
flower_trail.c File Reference
Functions
void flower_trail_init (EffectInstance *effect)
void flower_trail_update (EffectInstance *effect)
void flower_trail_render (EffectInstance *effect)
void flower_trail_appendGfx (void *effect)
void flower_trail_update_part_transform (FlowerFXData *effect)
void flower_trail_update_part (FlowerFXData *effect)
void flower_trail_main (s32 triggeredByNpc, f32 posX, f32 posY, f32 posZ, f32 angle, f32 direction)
void flower_trail_dispose (EffectInstance *effect)
Variables
Gfx D_09000E20_32DCE0 []
Gfx D_09000E38_32DCF8 []
Function Documentation
flower_trail_appendGfx()
void flower_trail_appendGfx (void * effect)
Referenced by flower_trail_render().
flower_trail_dispose()
void flower_trail_dispose (EffectInstance * effect)
flower_trail_init()
void flower_trail_init (EffectInstance * effect)
Referenced by flower_trail_main().
flower_trail_main()
void flower_trail_main (s32 triggeredByNpc, f32 posX, f32 posY, f32 posZ, f32 angle, f32 direction)
flower_trail_render()
void flower_trail_render (EffectInstance * effect)
Referenced by flower_trail_main().
flower_trail_update()
void flower_trail_update (EffectInstance * effect)
Referenced by flower_trail_main().
flower_trail_update_part()
void flower_trail_update_part (FlowerFXData * effect)
Referenced by flower_trail_update().
flower_trail_update_part_transform()
void flower_trail_update_part_transform (FlowerFXData * effect)
Referenced by flower_trail_update().
Variable Documentation
D_09000E20_32DCE0
Gfx D_09000E20_32DCE0[] extern
Referenced by flower_trail_appendGfx().
D_09000E38_32DCF8
Gfx D_09000E38_32DCF8[] extern
Referenced by flower_trail_appendGfx().