papermario: src/effects/flower_splash.c File Reference
flower_splash.c File Reference
Functions
void flower_splash_init (EffectInstance *effect)
void flower_splash_update (EffectInstance *effect)
void flower_splash_render (EffectInstance *effect)
void flower_splash_appendGfx (void *effect)
void flower_splash_update_part_transform (FlowerFXData *effect)
void flower_splash_update_part (FlowerFXData *effect)
void flower_splash_main (f32 posX, f32 posY, f32 posZ, f32 angle)
void flower_splash_dispose (EffectInstance *effect)
Variables
Gfx D_09000E08_32DCC8 []
Function Documentation
flower_splash_appendGfx()
void flower_splash_appendGfx (void * effect)
Referenced by flower_splash_render().
flower_splash_dispose()
void flower_splash_dispose (EffectInstance * effect)
flower_splash_init()
void flower_splash_init (EffectInstance * effect)
Referenced by flower_splash_main().
flower_splash_main()
void flower_splash_main (f32 posX, f32 posY, f32 posZ, f32 angle)
flower_splash_render()
void flower_splash_render (EffectInstance * effect)
Referenced by flower_splash_main().
flower_splash_update()
void flower_splash_update (EffectInstance * effect)
Referenced by flower_splash_main().
flower_splash_update_part()
void flower_splash_update_part (FlowerFXData * effect)
Referenced by flower_splash_update().
flower_splash_update_part_transform()
void flower_splash_update_part_transform (FlowerFXData * effect)
Referenced by flower_splash_update().
Variable Documentation
D_09000E08_32DCC8
Gfx D_09000E08_32DCC8[] extern
Referenced by flower_splash_appendGfx().