papermario: src/effects/footprint.c File Reference
footprint.c File Reference
Functions
void func_E0018000 (FootprintFXData *part)
void footprint_init (EffectInstance *effect)
void footprint_update (EffectInstance *effect)
void footprint_render (EffectInstance *effect)
void footprint_appendGfx (void *effect)
void footprint_main (f32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
void func_E00183BC (EffectInstance *effect)
Variables
Gfx D_09000240_32FD90 []
Function Documentation
footprint_appendGfx()
void footprint_appendGfx (void * effect)
Referenced by footprint_render().
footprint_init()
void footprint_init (EffectInstance * effect)
Referenced by footprint_main().
footprint_main()
void footprint_main (f32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
footprint_render()
void footprint_render (EffectInstance * effect)
Referenced by footprint_main().
footprint_update()
void footprint_update (EffectInstance * effect)
Referenced by footprint_main().
func_E0018000()
void func_E0018000 (FootprintFXData * part)
Referenced by footprint_update().
func_E00183BC()
void func_E00183BC (EffectInstance * effect)
Variable Documentation
D_09000240_32FD90
Gfx D_09000240_32FD90[] extern
Referenced by footprint_appendGfx().