papermario: include/functions.h File Reference
functions.h File Reference
Functions
f32 fabsf (f32 f)
f64 fabs (f64 f)
f32 cosine (s16 arg0)
void nuBoot (void)
void boot_idle (void *data)
void boot_main (void *data)
void is_debug_init (void)
void is_debug_panic (const char *message, char *file, s32 line)
f32 signF (f32 val)
s32 func_8002ACDC (void)
void load_obfuscation_shims (void)
void * heap_malloc (s32 size)
void * _heap_malloc (HeapNode *head, u32 size)
void * _heap_malloc_tail (HeapNode *head, u32 size)
u32 _heap_free (HeapNode *heapNodeList, void *addrToFree)
void * _heap_realloc (HeapNode *heapNodeList, void *addr, u32 newSize)
HeapNode * _heap_create (HeapNode *addr, u32 size)
u32 dma_copy (Addr romStart, Addr romEnd, void *vramDest)
f32 rand_float (void)
void copy_matrix (Matrix4f src, Matrix4f dest)
s8 set_global_byte (s32 index, s32 value)
s32 get_global_byte (s32 index)
s32 set_global_flag (s32 index)
s32 clear_global_flag (s32 index)
s32 get_global_flag (s32 index)
s8 set_area_byte (s32 index, s32 value)
s32 get_area_byte (s32 index)
s32 set_area_flag (s32 index)
s32 clear_area_flag (s32 index)
s32 get_area_flag (s32 index)
Shadow * get_shadow_by_index (s32 index)
s32 get_time_freeze_mode (void)
void render_player_model (void)
s16 get_game_mode (void)
s32 is_picking_up_item (void)
f32 integrate_gravity (void)
void gravity_use_fall_parms (void)
f32 get_clamped_angle_diff (f32, f32)
b32 startup_fade_screen_in (s16 subtractAlpha)
b32 startup_fade_screen_out (s16 addAlpha)
void startup_fade_screen_update (void)
u32 get_entity_type (s32 arg0)
Entity * get_entity_by_index (s32 index)
s32 create_entity (EntityBlueprint *bp,...)
void entity_shattering_idle (Entity *entity)
void show_damage_fx (Actor *actor, f32 x, f32 y, f32 z, s32 damage)
s32 entity_raycast_down (f32 *, f32 *, f32 *, f32 *, f32 *, f32 *)
void step_game_loop (void)
s32 resume_all_group (s32 groupFlags)
f32 length2D (f32 x, f32 y)
void player_input_to_move_vector (f32 *angle, f32 *magnitude)
void game_input_to_move_vector (f32 *x, f32 *y)
void exec_ShakeCamX (s32 arg0, s32 arg1, s32 arg2, f32 arg3)
void exec_ShakeCam1 (s32 arg0, s32 arg1, s32 arg2)
f32 player_get_side_angle (void)
void draw_number (s32 value, s32 x, s32 y, s32 variableWidthChars, s32 palette, s32 opacity, u16 style)
void set_entity_model_flags (s32 idx, s32 newFlags)
void clear_entity_model_flags (s32 idx, s32 newFlags)
void exec_entity_model_commandlist (s32 idx)
RenderTask * queue_render_task (RenderTask *task)
s32 create_mesh_animator (s16 *animPos, s16 *animBuffer)
void load_mesh_animator_tree (s32 index, StaticAnimatorNode **tree)
void setup_pause_menu_tab (MenuWindowBP *bpArray, s32 arraySize)
s32 draw_ci_image_with_clipping (u8 *raster, s32 width, s32 height, s32 fmt, s32 bitDepth, u16 *palette, s16 posX, s16 posY, u16 clipULx, u16 clipULy, u16 clipLRx, u16 clipRLy, u8 opacity)
void render_frame (s32 flag)
void clear_windows (void)
void update_window_hierarchy (s32 windowIndex, u8 arg1)
void get_msg_properties (s32 msgID, s32 *height, s32 *width, s32 *maxLineChars, s32 *numLines, s32 *maxLinesPerPage, s32 *arg6, u16 charset)
void replace_window_update (s32 idx, s8 arg1, WindowUpdateFunc pendingFunc)
void decode_yay0 (void *src, void *dst)
s32 ai_check_player_dist (Enemy *enemy, s32 arg1, f32 arg2, f32 arg3)
void pause_init (void)
void pause_handle_input (s32 buttonsPressed, s32 buttonsHeld)
void pause_cleanup (void)
void filemenu_init (s32 mode)
void filemenu_cleanup (void)
void filemenu_update (void)
s32 filemenu_get_exit_mode (void)
void filemenu_set_selected (MenuPanel *menu, s32 col, s32 row)
void filemenu_set_cursor_alpha (s32 arg0)
void filemenu_set_cursor_goal_pos (s32 windowIndex, s32 posX, s32 posY)
u8 * filemenu_get_menu_message (s32 idx)
void gfx_task_background (void)
void update_enemy_shadows (void)
void update_hero_shadows (void)
void appendGfx_background_texture (void)
void appendGfx_enemy_actor (void *)
void appendGfx_enemy_actor_blur (void *)
void appendGfx_enemy_actor_reflection (void *)
void appendGfx_partner_actor (void *)
void appendGfx_partner_actor_blur (void *)
void appendGfx_partner_actor_reflection (void *)
void appendGfx_player_actor (void *)
void appendGfx_player_actor_blur (Actor *)
void appendGfx_player_actor_reflection (void *)
void force_disable_actor_blur (Actor *)
void player_handle_floor_collider_type (s32 colliderID)
f32 player_fall_distance (void)
void func_800E4AD8 (s32 arg0)
f32 player_check_collision_below (f32, s32 *colliderID)
b32 can_trigger_loading_zone (void)
void update_damage_popups (void)
void show_action_rating (s32, Actor *, f32, f32, f32)
s32 render_with_adjusted_palettes (s32, ActorPart *, s32, Matrix4f, s32)
HeapNode * general_heap_create (void)
void * general_heap_malloc (s32 size)
s32 general_heap_free (void *data)
s32 integer_log (s32 number, u32 base)
void set_battle_stage (s32)
void load_battle (s32)
void entity_Shadow_init (Shadow *entity)
void entity_SaveBlock_idle (Entity *entity)
void entity_SaveBlock_pause_game (void)
void entity_SaveBlock_resume_game (void)
void entity_SaveBlock_save_data (void)
void entity_SaveBlock_show_tutorial_message (Entity *entity)
void entity_SaveBlock_wait_for_close_tutorial (Entity *entity)
void entity_SaveBlock_show_choice_message (void)
void entity_SaveBlock_show_result_message (void)
void entity_SaveBlock_wait_for_close_result (Entity *entity)
void entity_SaveBlock_wait_for_close_choice (Entity *entity)
void entity_SaveBlock_init (Entity *entity)
void entity_GreenStompSwitch_idle (Entity *entity)
void entity_GreenStompSwitch_retract (Entity *entity)
void entity_GreenStompSwitch_extend (Entity *entity)
void entity_HugeBlueSwitch_idle (Entity *entity)
void entity_small_switch_idle (Entity *entity)
void entity_RedSwitch_wait_and_reset (Entity *entity)
void entity_base_switch_anim_init (Entity *entity)
s32 entity_RedSwitch_animate_scale (Entity *entity)
void entity_base_switch_start_bound_script (Entity *entity)
void entity_base_switch_animate_scale (Entity *entity)
void entity_base_switch_init (Entity *entity)
f32 entity_block_hit_init_scale (Entity *entity)
void entity_block_hit_animate_scale (Entity *entity)
s32 entity_block_handle_collision (Entity *entity)
void entity_BlueSwitch_init (Entity *entity)
void entity_HugeBlueSwitch_init (Entity *entity)
s32 dispatch_damage_event_actor_0 (Actor *actor, s32 damageAmount, s32 event)
MessagePrintState * msg_get_printer_for_msg (s32 msgID, s32 *a1)
s32 msg_printer_load_msg (s32 msgID, MessagePrintState *printer)
void msg_printer_set_origin_pos (MessagePrintState *msgPrintState, s32 x, s32 y)
void get_screen_coords (s32 camID, f32 x, f32 y, f32 z, s32 *screenX, s32 *screenY, s32 *screenZ)
void parent_collider_to_model (s16 colliderID, s16 modelIndex)
void clone_model (u16 srcModelID, u16 newModelID)
struct Model * get_model_from_list_index (s32 listIndex)
s32 create_model_animator (s16 *animPos)
s32 get_model_list_index_from_tree_index (s32 treeIndex)
s32 get_transform_group_index (s32)
void get_model_center_and_size (u16 modelID, f32 *centerX, f32 *centerY, f32 *centerZ, f32 *sizeX, f32 *sizeY, f32 *sizeZ)
HitID collision_main_above (void)
void collision_lava_reset_check_additional_overlaps (void)
s32 player_test_lateral_overlap (s32, PlayerStatus *, f32 *, f32 *, f32 *, f32, f32)
Npc * peach_make_disguise_npc (s32 peachDisguise)
void peach_set_disguise_anim (AnimID)
s32 draw_box (s32 flags, WindowStyle windowStyle, s32 posX, s32 posY, s32 posZ, s32 width, s32 height, u8 opacity, u8 darkening, f32 scaleX, f32 scaleY, f32 rotX, f32 rotY, f32 rotZ, void(*fpDrawContents)(s32, s32, s32, s32, s32, s32, s32), void *drawContentsArg0, Matrix4f rotScaleMtx, s32 translateX, s32 translateY, Matrix4f outMtx)
s32 get_msg_width (s32 msgID, u16 charset)
s32 partner_can_open_world_menus (void)
s32 disable_player_static_collisions (void)
s32 disable_player_input (void)
void func_80027088 (s32)
void set_time_freeze_mode (s32)
Time freeze modes: 0: none 1: NPCs move, can't be interacted with 2: NPCs don't move, no partner ability, can't interact, can't use exits 3: NPCs don't more or animate 4: NPCs can move, animations don't update, can use exits.
s32 get_map_IDs_by_name (const char *mapName, s16 *areaID, s16 *mapID)
void transform_point (Matrix4f mtx, f32 inX, f32 inY, f32 inZ, f32 inS, f32 *outX, f32 *outY, f32 *outZ, f32 *outW)
void try_player_footstep_sounds (s32 arg0)
void phys_update_interact_collider (void)
void phys_reset_spin_history (void)
s32 phys_adjust_cam_on_landing (void)
s32 phys_should_player_be_sliding (void)
void phys_init_integrator_for_current_state (void)
void phys_player_land (void)
void phys_main_collision_below (void)
void phys_peach_update (void)
void check_input_spin (void)
b32 npc_test_move_simple_without_slipping (s32, f32 *, f32 *, f32 *, f32, f32, f32, f32)
void update_collider_transform (s16 colliderID)
void get_collider_center (s32 colliderID, f32 *x, f32 *y, f32 *z)
s32 is_another_trigger_bound (Trigger *, EvtScript *script)
Trigger * create_trigger (TriggerBlueprint *def)
s32 evt_trigger_on_activate_exec_script (Trigger *trigger)
Trigger * get_trigger_by_id (s32 triggerID)
Actor * get_actor (s32 actorID)
ActorPart * get_actor_part (Actor *actor, s32 partID)
s32 add_coins (s32 amt)
s32 is_partner_ability_active (s32)
s32 count_power_plus (s32)
s32 phys_can_player_interact (void)
void ai_enemy_play_sound (Npc *npc, s32 arg1, s32 arg2)
HitID player_test_move_without_slipping (PlayerStatus *, f32 *, f32 *, f32 *, f32, f32, s32 *)
HitID player_test_move_with_slipping (PlayerStatus *playerStatus, f32 *posX, f32 *posY, f32 *posZ, f32 speed, f32 heading)
s32 evt_get_variable (Evt *script, Bytecode var)
s32 evt_set_variable (Evt *script, Bytecode var, s32 value)
f32 evt_get_float_variable (Evt *script, Bytecode var)
f32 evt_set_float_variable (Evt *script, Bytecode var, f32 value)
s32 evt_get_variable_index (Evt *script, s32 var)
void set_script_timescale (Evt *script, f32 timescale)
f32 sin_deg (f32 x)
f32 cos_deg (f32 x)
f32 sin_rad (f32 x)
f32 cos_rad (f32 x)
s32 round (f32)
f32 atan2 (f32 startX, f32 startZ, f32 endX, f32 endZ)
f32 clamp_angle (f32 theta)
s32 sign (s32 value)
b32 check_player_action_debug (void)
s32 battle_heap_create (void)
s32 test_ray_zones (f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 *hitX, f32 *hitY, f32 *hitZ, f32 *hitDepth, f32 *nx, f32 *ny, f32 *nz)
s32 test_ray_colliders (s32 ignoreFlags, f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 *hitX, f32 *hitY, f32 *hitZ, f32 *hitDepth, f32 *hitNx, f32 *hitNy, f32 *hitNz)
s32 test_ray_entities (f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 *hitX, f32 *hitY, f32 *hitZ, f32 *hitDepth, f32 *hitNx, f32 *hitNy, f32 *hitNz)
Test a general ray from a given starting position and direction against all entities.
void mem_clear (void *data, s32 numBytes)
void startup_set_fade_screen_color (s16 color)
void startup_set_fade_screen_alpha (s16 alpha)
f32 get_xz_dist_to_player (f32, f32)
void func_800E06C0 (s32)
void close_status_bar (void)
Evt * func_802C39F8 (Evt *parentScript, Bytecode *nextLine, s32 newState)
Evt * start_child_script (Evt *parentScript, EvtScript *source, s32 initialState)
Evt * restart_script (Evt *script)
void clear_virtual_entity_list (void)
void reset_model_animators (void)
void init_virtual_entity_list (void)
void init_model_animators (void)
void play_model_animation (s32, s16 *)
s32 heap_free (void *ptr)
void load_battle_hit_asset (const char *hitName)
void load_data_for_models (struct ModelNode *model, s32 romOffset, s32 size)
void load_player_actor (void)
void btl_state_update_normal_start (void)
void btl_state_draw_normal_start (void)
void btl_state_update_begin_turn (void)
void btl_state_draw_begin_turn (void)
void btl_state_update_begin_player_turn (void)
void btl_state_draw_begin_player_turn (void)
void btl_state_update_switch_to_player (void)
void btl_state_draw_switch_to_player (void)
void btl_state_update_begin_partner_turn (void)
void btl_state_draw_begin_partner_turn (void)
void btl_state_update_switch_to_partner (void)
void btl_state_draw_switch_to_partner (void)
void btl_state_update_9 (void)
void btl_state_draw_9 (void)
void btl_state_update_prepare_menu (void)
void btl_state_draw_prepare_menu (void)
void btl_state_update_end_turn (void)
void btl_state_draw_end_turn (void)
void btl_state_update_1C (void)
void btl_state_draw_1C (void)
void btl_state_update_victory (void)
void btl_state_draw_victory (void)
void btl_state_update_end_training_battle (void)
void btl_state_draw_end_training_battle (void)
void btl_state_update_end_battle (void)
void btl_state_draw_end_battle (void)
void btl_state_update_defend (void)
void btl_state_draw_defend (void)
void btl_state_update_run_away (void)
void btl_state_draw_run_away (void)
void btl_state_update_defeat (void)
void btl_state_draw_defeat (void)
void btl_state_update_change_partner (void)
void btl_state_draw_change_partner (void)
void btl_state_update_player_move (void)
void btl_state_draw_player_move (void)
void btl_state_update_end_player_turn (void)
void btl_state_update_partner_move (void)
void btl_state_draw_end_player_turn (void)
void btl_state_draw_partner_move (void)
void btl_state_update_end_partner_turn (void)
void btl_state_draw_end_partner_turn (void)
void btl_state_update_next_enemy (void)
void btl_state_draw_next_enemy (void)
void btl_state_update_enemy_move (void)
void btl_state_draw_enemy_move (void)
void btl_state_update_first_strike (void)
void btl_state_draw_first_stike (void)
void btl_state_update_partner_striking_first (void)
void btl_state_draw_partner_striking_first (void)
void btl_state_update_enemy_striking_first (void)
void btl_state_draw_enemy_striking_first (void)
void btl_state_update_end_demo_battle (void)
void btl_state_draw_end_demo_battle (void)
void btl_state_update_player_menu (void)
void btl_state_draw_player_menu (void)
void btl_state_update_partner_menu (void)
void btl_state_draw_partner_menu (void)
void btl_state_update_peach_menu (void)
void btl_state_draw_peach_menu (void)
void btl_state_update_twink_menu (void)
void btl_state_draw_twink_menu (void)
void btl_state_update_select_target (void)
void btl_state_draw_select_target (void)
void btl_state_update_22 (void)
void btl_state_draw_22 (void)
void btl_state_update_celebration (void)
void btl_draw_upgrade_windows (s32)
void btl_state_draw_celebration (void)
void btl_bonk_cleanup (void)
void set_actor_anim_by_ref (Actor *, ActorPart *, AnimID)
void update_action_ratings (void)
void update_health_bars (void)
s32 btl_cam_is_moving_done (void)
void btl_popup_messages_update (void)
void btl_popup_messages_draw_world_geometry (void)
void func_80255FD8 (void)
void set_actor_glow_pal (Actor *actor, s32 arg1)
void btl_set_popup_duration (s32 duration)
void switch_to_partner (s32 arg0)
s8 get_current_partner_id (void)
void delete_trigger (Trigger *toDelete)
void kill_script_by_ID (s32 id)
void set_script_priority (Evt *script, s32 priority)
void set_script_group (Evt *script, s32 groupFlags)
void suspend_group_others (Evt *script, s32 groupFlags)
void resume_group_others (Evt *script, s32 groupFlags)
s32 suspend_all_script (s32 id)
s32 resume_all_script (s32 id)
s32 create_shadow_type (s32 type, f32 x, f32 y, f32 z)
b32 is_point_outside_territory (s32 shape, f32 pointX, f32 pointY, f32 centerX, f32 centerY, f32 sizeX, f32 sizeZ)
PlayerData * get_player_data (void)
b32 npc_raycast_down_around (s32, f32 *, f32 *, f32 *, f32 *, f32, f32)
b32 npc_raycast_down_sides (s32 ignoreFlags, f32 *posX, f32 *posY, f32 *posZ, f32 *hitDepth)
b32 npc_raycast_up (s32, f32 *, f32 *, f32 *, f32 *)
HitID npc_raycast_up_corners (s32 ignoreFlags, f32 *posX, f32 *posY, f32 *posZ, f32 *hitDepth, f32 yaw, f32 radius)
HitID player_raycast_up_corners (PlayerStatus *, f32 *, f32 *, f32 *, f32 *, f32)
HitID player_raycast_below_cam_relative (PlayerStatus *playerStatus, f32 *outX, f32 *outY, f32 *outZ, f32 *outLength, f32 *hitRx, f32 *hitRz, f32 *hitDirX, f32 *hitDirZ)
b32 npc_test_move_taller_with_slipping (s32, f32 *, f32 *, f32 *, f32, f32, f32, f32)
b32 npc_test_move_simple_with_slipping (s32, f32 *, f32 *, f32 *, f32, f32, f32, f32)
s32 npc_test_move_complex_with_slipping (s32, f32 *, f32 *, f32 *, f32, f32, f32, f32)
EvtScript * partner_get_enter_map_script (void)
void partner_handle_before_battle (void)
void partner_walking_update_player_tracking (Npc *partner)
void partner_walking_update_motion (Npc *partner)
void enable_partner_ai (void)
void partner_walking_enable (Npc *partner, s32 val)
void partner_flying_enable (Npc *partner, s32 val)
void partner_flying_update_player_tracking (Npc *partner)
s32 partner_is_flying (void)
void partner_flying_update_motion (Npc *partner)
void partner_clear_player_tracking (Npc *partner)
void partner_set_tether_distance (f32)
void btl_delete_player_actor (Actor *player)
s32 cancel_message (MessagePrintState *msgPrintState)
void set_message_images (MessageImageData *images)
void kill_all_scripts (void)
s32 does_script_exist (s32 id)
s32 does_script_exist_by_ref (Evt *script)
Evt * start_script (EvtScript *source, s32 priority, s32 initialState)
Evt * start_script_in_group (EvtScript *source, u8 priority, u8 initialState, u8 groupFlags)
f32 get_player_normal_yaw (void)
void set_standard_shadow_scale (Shadow *shadow, f32 scale)
void set_npc_shadow_scale (Shadow *shadow, f32 height, f32 npcRadius)
void set_npc_animation (Npc *npc, u32 animID)
void set_peach_shadow_scale (Shadow *shadow, f32 scale)
s32 is_block_on_ground (Entity *block)
void set_actor_anim (s32 actorID, s32 partID, AnimID animID)
void set_actor_anim_rate (s32 actorID, s32 partID, f32 rate)
void mdl_group_set_visibility (u16, s32, s32)
void init_enter_world_shared (void)
s16 update_enter_map_screen_overlay (s16 *progress)
s16 update_exit_map_screen_overlay (s16 *progress)
void set_screen_overlay_params_front (u8, f32)
void set_screen_overlay_params_back (u8, f32)
void set_screen_overlay_alpha (s32, f32)
void get_screen_overlay_params (s32, u8 *type, f32 *zoom)
void set_screen_overlay_color (s32, u8, u8, u8)
void set_screen_overlay_center (s32, s32, s32, s32)
s32 rand_int (s32)
void sort_items (void)
Bubbles up player inventory items such that all ITEM_NONE values are at the bottom.
s32 is_ability_active (s32 arg0)
s32 is_starting_conversation (void)
f32 update_lerp (s32 easing, f32 start, f32 end, s32 elapsed, s32 duration)
void sin_cos_deg (f32 rad, f32 *outSinTheta, f32 *outCosTheta)
void set_main_pan_u (s32 texPannerID, s32 value)
void set_main_pan_v (s32 texPannerID, s32 value)
void set_aux_pan_u (s32 texPannerID, s32 value)
void set_aux_pan_v (s32 texPannerID, s32 value)
void enable_world_fog (void)
void set_world_fog_dist (s32 start, s32 end)
void set_world_fog_color (s32 r, s32 g, s32 b, s32 a)
s32 is_world_fog_enabled (void)
void get_world_fog_color (s32 *r, s32 *g, s32 *b, s32 *a)
void enable_entity_fog (void)
void set_entity_fog_dist (s32 start, s32 end)
void set_entity_fog_color (s32 r, s32 g, s32 b, s32 a)
struct ModelTransformGroup * get_transform_group (s32 index)
void mdl_make_transform_group (u16 modelID)
void enable_transform_group (u16 modelID)
void disable_transform_group (u16 modelID)
void set_map_transition_effect (ScreenTransition)
void set_tex_panner (struct Model *model, s32 texPannerID)
void set_custom_gfx (s32 customGfxIndex, Gfx *pre, Gfx *post)
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 angle, s32 pickupVar)
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
ItemEntity * get_item_entity (s32 itemEntityIndex)
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupVar)
void set_item_entity_flags (s32 itemEntityIndex, s32 flag)
void clear_item_entity_flags (s32 index, s32 flags)
s32 create_worker_frontUI (void(*updateFunc)(void), void(*drawFunc)(void))
Worker * get_worker (s32 idx)
Trigger * bind_trigger_1 (EvtScript *script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority)
void set_cam_viewport (s16 id, s16 x, s16 y, s16 width, s16 height)
void disable_player_shadow (void)
void move_player (s32 duration, f32 heading, f32 speed)
s32 enable_player_input (void)
s32 enable_player_static_collisions (void)
b32 check_input_jump (void)
b32 check_input_hammer (void)
Npc * resolve_npc (Evt *script, s32 npcIdOrPtr)
void enable_npc_blur (Npc *npc)
void disable_npc_blur (Npc *npc)
void enable_partner_blur (void)
void disable_partner_blur (void)
void partner_initialize_data (void)
f32 dist2D (f32 ax, f32 ay, f32 bx, f32 by)
f32 dist3D (f32 ax, f32 ay, f32 az, f32 bx, f32 by, f32 bz)
void add_vec2D_polar (f32 *x, f32 *y, f32 r, f32 theta)
enum AuResult bgm_set_track_volumes (s32 playerIndex, s16 trackVolSet)
enum AuResult bgm_clear_track_volumes (s32 playerIndex, s16 trackVolSet)
enum AuResult bgm_set_variation (s32 playerIndex, s16 arg1)
void bgm_quiet_max_volume (void)
void bgm_reset_max_volume (void)
void bgm_reset_volume (void)
s32 bgm_init_music_players (void)
s32 bgm_set_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
void bgm_set_battle_song (s32, s32)
void bgm_push_battle_song (void)
s32 bgm_adjust_proximity (s32 playerIndex, s32 arg1, s16 arg2)
void func_801491E4 (Matrix4f mtx, s32, s32, s32, s32, s32 alpha)
s32 func_8014A964 (s32 playerIndex, s32 songID, s32 variation, s32 fadeInTime, s16 arg4, s16 arg5)
void basic_window_update (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void basic_hidden_window_update (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void create_current_pos_target_list (Actor *actor)
void create_home_target_list (Actor *actor)
void set_actor_yaw (s32 actorID, s32 yaw)
void set_part_yaw (s32 actorID, s32 partID, s32 value)
void add_part_decoration (ActorPart *part, s32 decorationIndex, s32 decorationType)
void add_actor_decoration (Actor *actor, s32 decorationIndex, s32 decorationType)
void remove_part_decoration (ActorPart *part, s32 decorationIndex)
void remove_actor_decoration (Actor *actor, s32 decorationIndex)
s32 player_team_is_ability_active (Actor *actor, s32 ability)
void create_part_shadow (s32 actorID, s32 partID)
void remove_part_shadow (s32 actorID, s32 partID)
void create_part_shadow_by_ref (s32 arg0, ActorPart *part)
void spawn_drops (Enemy *enemy)
void set_part_pal_adjustment (ActorPart *, s32)
char * int_to_string (s32, char *, s32)
Evt * get_script_by_index (s32 index)
Evt * get_script_by_id (s32 id)
s32 partner_test_enemy_collision (Npc *enemy)
s32 get_lava_reset_pos (f32 *x, f32 *y, f32 *z)
void start_rumble (s32, s32)
void update_locomotion_state (void)
void start_rumble_type (u32)
void start_falling (void)
void start_bounce_a (void)
void start_bounce_b (void)
void update_input (void)
void update_max_rumble_duration (void)
void mdl_reset_transform_flags (void)
void update_workers (void)
void update_triggers (void)
void update_scripts (void)
void update_messages (void)
void update_entities (void)
void func_80138198 (void)
void bgm_update_music_settings (void)
s32 func_8014AD40 (void)
void update_ambient_sounds (void)
void update_windows (void)
void player_render_interact_prompts (void)
void func_802C3EE4 (void)
void render_screen_overlay_backUI (void)
void render_workers_backUI (void)
void render_effects_UI (void)
void render_window_root (void)
void render_messages (void)
void render_workers_frontUI (void)
void render_screen_overlay_frontUI (void)
void render_curtains (void)
void fio_init_flash (void)
void func_80028838 (void)
void clear_screen_overlays (void)
void bgm_reset_sequence_players (void)
void reset_ambient_sounds (void)
void poll_rumble (void)
void bgm_pop_song (void)
void bgm_push_song (s32 songID, s32 variation)
void bgm_pop_battle_song (void)
s32 play_ambient_sounds (s32 fadeInTime, s32 fadeOutTime)
s32 get_fortress_key_count (void)
s32 subtract_fortress_keys (s32 amt)
s32 add_star_points (s32 amt)
s32 add_star_pieces (s32 amt)
s32 make_item_entity_at_player (s32 itemID, s32 arg1, s32 pickupMsgFlags)
void set_action_state (s32 actionState)
s32 get_collider_flags (s32 colliderID)
void suggest_player_anim_always_forward (AnimID anim)
void suggest_player_anim_allow_backward (AnimID anim)
void subtract_hp (s32 amt)
void draw_status_ui (void)
void open_status_bar_slowly (void)
void suspend_all_group (s32 groupFlags)
void kill_script (Evt *instanceToKill)
void exec_entity_commandlist (Entity *entity)
void show_start_recovery_shimmer (f32 x, f32 y, f32 z, s32 arg3)
void show_recovery_shimmer (f32 x, f32 y, f32 z, s32 arg3)
void show_next_damage_popup (f32 x, f32 y, f32 z, s32 damageAmount, s32)
void add_xz_vec3f (Vec3f *vector, f32 speed, f32 angleDeg)
void add_xz_vec3f_copy1 (Vec3f *vector, f32 speed, f32 angleDeg)
void add_xz_vec3f_copy2 (Vec3f *vector, f32 speed, f32 angleDeg)
void play_movement_dust_effects (s32 var0, f32 xPos, f32 yPos, f32 zPos, f32 angleDeg)
void draw_prev_frame_buffer_at_screen_pos (s32, s32, s32, s32, f32)
void func_8013A4D0 (void)
void btl_draw_ui (void)
void btl_restore_world_cameras (void)
void btl_popup_messages_draw_ui (void)
void btl_cam_set_target_pos (f32, f32, f32)
void btl_cam_unfreeze (void)
void deduct_current_move_fp (void)
void load_partner_actor (void)
void dispatch_event_partner (s32)
void dispatch_event_player (s32)
s32 btl_are_all_enemies_defeated (void)
s32 btl_check_enemies_defeated (void)
s32 btl_check_player_defeated (void)
void btl_show_battle_message (s32 messageIndex, s32 duration)
void btl_update_ko_status (void)
void reset_actor_turn_info (void)
void startup_draw_prim_rect (s16 left, s16 top, s16 right, s16 bottom, u16 r, u16 g, u16 b, u16 a)
void startup_draw_prim_rect_COPY (s16 left, s16 top, s16 right, s16 bottom, u16 r, u16 g, u16 b, u16 a)
void btl_draw_prim_quad (u8 r, u8 g, u8 b, u8 a, u16 left, u16 top, u16 arg6, u16 arg7)
void reset_all_actor_sounds (Actor *)
void decrement_status_bar_disabled (void)
void increment_status_bar_disabled (void)
void btl_delete_actor (Actor *actor)
void create_status_debuff (s32, s32)
void create_status_static (s32, s32)
void create_status_transparent (s32, s32)
void remove_status_chill_out (s32)
void remove_status_debuff (s32)
void remove_status_icon_boost_hammer (s32)
void remove_status_icon_boost_jump (s32)
void remove_status_icon_boost_partner (s32)
void remove_status_icon_danger (s32)
void remove_status_icon_peril (s32)
void remove_status_icon_surprise (s32)
void remove_status_static (s32)
void remove_status_transparent (s32)
void remove_all_status_icons (s32)
s32 create_status_icon_set (void)
s32 find_item (s32)
void enable_background_wave (void)
void set_map_change_fade_rate (s16)
void load_map_by_IDs (s16 areaID, s16 mapID, s16 loadType)
void state_init_startup (void)
void state_step_startup (void)
void state_drawUI_startup (void)
void state_init_logos (void)
void state_step_logos (void)
void state_drawUI_logos (void)
void state_init_title_screen (void)
void state_step_title_screen (void)
void state_drawUI_title_screen (void)
void state_init_enter_demo (void)
void state_step_enter_world (void)
void state_init_change_map (void)
void state_step_change_map (void)
void state_drawUI_change_map (void)
void state_init_game_over (void)
void state_step_game_over (void)
void state_drawUI_game_over (void)
void state_init_enter_world (void)
void state_drawUI_enter_world (void)
void state_init_world (void)
void state_step_world (void)
void state_drawUI_world (void)
void state_init_battle (void)
void state_step_battle (void)
void state_drawUI_battle (void)
void state_init_end_battle (void)
void state_step_end_battle (void)
void state_drawUI_end_battle (void)
void state_init_pause (void)
void state_step_pause (void)
void state_drawUI_pause (void)
void state_init_unpause (void)
void state_step_unpause (void)
void state_drawUI_unpause (void)
void state_init_language_select (void)
void state_step_language_select (void)
void state_drawUI_language_select (void)
void state_init_exit_language_select (void)
void state_step_exit_language_select (void)
void state_drawUI_exit_language_select (void)
void state_init_file_select (void)
void state_step_file_select (void)
void state_drawUI_file_select (void)
void state_init_exit_file_select (void)
void state_step_exit_file_select (void)
void state_drawUI_exit_file_select (void)
void state_init_intro (void)
void state_step_intro (void)
void state_drawUI_intro (void)
void state_init_demo (void)
void state_step_demo (void)
void state_drawUI_demo (void)
void btl_set_player_idle_anims (void)
void shim_create_audio_system_obfuscated (void)
void shim_load_engine_data_obfuscated (void)
void shim_general_heap_create_obfuscated (void)
void shim_battle_heap_create_obfuscated (void)
void appendGfx_ispy_icon (void)
void interact_inspect_setup (void)
void interact_speech_setup (void)
void pulse_stone_notification_setup (void)
void appendGfx_speech_bubble (void)
void appendGfx_pulse_stone_icon (void)
void ispy_notification_setup (void)
void initialize_curtains (void)
void update_curtains (void)
void set_curtain_scale_goal (f32 scale)
void set_curtain_scale (f32 scale)
void set_curtain_draw_callback (void(*callback)(void))
void set_curtain_fade_goal (f32 fade)
void set_curtain_fade (f32 fade)
void crash_screen_init (void)
void crash_screen_set_draw_info (u16 *frameBufPtr, s16 width, s16 height)
void basic_ai_wander_init (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_wander (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_loiter (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_found_player_jump_init (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_found_player_jump (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_chase_init (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_chase (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_lose_player (Evt *script, MobileAISettings *npcAISettings, EnemyDetectVolume *territory)
void basic_ai_suspend (Evt *script)
s32 create_worker_scene (void(*updateFunc)(void), void(*renderFunc)(void))
void init_entity_models (void)
f32 phys_get_spin_history (s32 lag, s32 *x, s32 *y, s32 *z)
void imgfx_update (u32, ImgFXType, s32, s32, s32, s32, s32)
s32 imgfx_appendGfx_component (s32, ImgFXTexture *, u32, Matrix4f)
void imgfx_update_cache (void)
s32 imgfx_get_free_instances (s32)
void free_worker (s32)
b32 ai_check_fwd_collisions (Npc *npc, f32 time, f32 *outYaw, f32 *outDistFwd, f32 *outDistCW, f32 *outDistCCW)
void basic_ai_loiter_init (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void PatrolAI_LoiterInit (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
s32 func_80263230 (Actor *, Actor *)
void set_part_glow_pal (ActorPart *, s32)
void clear_actor_static_pal_adjustments (Actor *)
void set_actor_flash_mode (Actor *actor, s32 arg1)
void remove_player_buffs (s32)
s32 is_actor_health_bar_visible (Actor *)
void sin_cos_rad (f32 rad, f32 *outSinTheta, f32 *outCosTheta)
void load_font (s32 font)
void load_font_data (Addr offset, u16 size, void *dest)
void * load_asset_by_name (const char *assetName, u32 *decompressedSize)
Gfx * mdl_get_copied_gfx (s32 copyIndex)
void mdl_get_copied_vertices (s32 copyIndex, Vtx **firstVertex, Vtx **copiedVertices, s32 *numCopied)
void mdl_draw_hidden_panel_surface (Gfx **arg0, u16 treeIndex)
b32 is_point_visible (f32 x, f32 y, f32 z, s32 depthQueryID, f32 *screenX, f32 *screenY)
void set_screen_overlay_center_worldpos (s32 idx, s32 posIdx, s32 x, s32 y, s32 z)
void * mdl_get_next_texture_address (s32)
s32 cancel_current_message (void)
void draw_msg (s32 msgID, s32 posX, s32 posY, s32 opacity, s32 palette, u8 style)
void mdl_get_shroud_tint_params (u8 *r, u8 *g, u8 *b, u8 *a)
s32 entity_base_block_idle (Entity *entity)
void add_star_power (s32 amt)
s32 recover_hp (s32 amt)
s32 recover_fp (s32 amt)
s32 entity_can_collide_with_jumping_player (Entity *entity)
void entity_base_block_init (Entity *entity)
s32 entity_start_script (Entity *entity)
void init_item_entity_list (void)
void init_script_list (void)
void init_entity_data (void)
void init_trigger_list (void)
void partner_init_after_battle (s32 arg0)
void load_map_script_lib (void)
void remove_item_entity_by_index (s32 index)
void set_entity_commandlist (Entity *entity, s32 *entityScript)
s32 is_player_dismounted (void)
void func_800EF300 (void)
void func_800EF314 (void)
void func_800EF43C (void)
void func_800EF3E4 (void)
void enable_player_shadow (void)
s32 get_msg_lines (s32 messageID)
void set_window_properties (s32 panelID, s32 posX, s32 posY, s32 width, s32 height, u8, void *drawContents, void *drawContentsArg, s8 parent)
void set_window_update (s32 panelID, s32)
void set_windows_visible (s32 groupIdx)
void partner_disable_input (void)
void partner_set_goal_pos (s32 x, s32 z)
void close_message (MessagePrintState *msgPrintState)
void show_foreground_models_unchecked (void)
void hide_foreground_models_unchecked (void)
void show_foreground_models (void)
void hide_foreground_models (void)
void btl_set_state (s32 battleState)
void draw_entity_model_A (s32, Mtx *)
void draw_entity_model_B (s32, Mtx *, s32, Vec3s *)
void draw_entity_model_C (s32, Mtx *)
void draw_entity_model_D (s32, Mtx *, s32, Vec3s *)
void draw_entity_model_E (s32, Mtx *)
void free_entity_model_by_index (s32 idx)
void btl_cam_use_preset (s32)
void btl_cam_set_params (b16, s16, s16, s16, s32, s32, s32, s32)
void btl_cam_set_zoffset (s16)
void btl_cam_target_actor (s32)
void btl_cam_set_zoom (s16)
void btl_cam_move (s16)
void btl_cam_disable_clamp_x (void)
void initialize_battle (void)
void dispatch_event_actor (Actor *, s32)
s32 dispatch_damage_event_actor_1 (Actor *actor, s32 damageAmount, s32 event)
void reset_battle_status (void)
void btl_show_variable_battle_message (s32, s32, s32)
s32 btl_is_popup_displayed (void)
void btl_cam_use_preset_immediately (s32)
s32 inflict_status (Actor *, s32, s32)
s32 try_inflict_status (Actor *, s32, s32)
s32 inflict_status_set_duration (Actor *actor, s32 statusTypeKey, s32 statusDurationKey, s32 duration)
void mdl_set_all_tint_type (s32)
void load_model_animator_tree (s32, StaticAnimatorNode **)
s32 inflict_partner_ko (Actor *target, s32 statusTypeKey, s32 duration)
s32 get_defense (Actor *actor, s32 *defenseTable, s32 elementFlags)
void btl_popup_messages_init (void)
void remove_all_effects (void)
void update_effects (void)
void update_cameras (void)
void clear_render_tasks (void)
void clear_worker_list (void)
void clear_printers (void)
void clear_item_entity_data (void)
void clear_player_data (void)
void phys_update_jump (void)
void phys_update_falling (void)
void check_input_midair_jump (void)
void collision_check_player_overlaps (void)
void update_player_input (void)
void phys_update_action_state (void)
void collision_main_lateral (void)
void handle_floor_behavior (void)
void check_input_open_menus (void)
void check_input_status_bar (void)
void update_player (void)
void enforce_hpfp_limits (void)
s32 should_collider_allow_interact (s32)
void show_coin_counter (void)
s32 add_item (s32 itemID)
s32 add_badge (s32 itemID)
void hide_coin_counter_immediately (void)
void hide_popup_menu (void)
void destroy_popup_menu (void)
void reset_player_status (void)
void player_reset_data (void)
void partner_reset_data (void)
s32 has_valid_conversation_npc (void)
s32 func_800E06D8 (void)
void func_800E01DC (void)
void collision_lateral_peach (void)
void func_800E5520 (void)
void clear_world_menus (void)
void setup_status_bar_for_battle (void)
void enable_status_bar_input (void)
void disable_status_bar_input (void)
b32 can_control_status_bar (void)
void status_bar_respond_to_changes (void)
void status_bar_always_show_on (void)
void status_bar_always_show_off (void)
void func_800F0C9C (void)
void star_power_shimmer_start (s32, f32, f32, f32)
void star_power_shimmer_init (void)
void star_power_shimmer_update (void)
void star_power_shimmer_draw (void)
s32 get_item_count (void)
s32 get_stored_empty_count (void)
s32 get_stored_count (void)
s32 get_item_empty_count (void)
void shop_open_item_select_popup (s32 mode)
void hide_coin_counter (void)
void set_message_text_var (s32 msgID, s32 index)
void set_message_int_var (s32 value, s32 index)
s32 store_item (s32 itemID)
void open_status_bar_quickly (void)
void show_immune_bonk (f32 x, f32 y, f32 z, s32, s32, s32)
void show_primary_damage_popup (f32 x, f32 y, f32 z, s32 attack, s32 a)
s32 dispatch_damage_event_partner (s32 damageAmount, s32 event, s32 stopMotion)
void disable_actor_blur (Actor *)
void reset_actor_blur (Actor *)
void enable_actor_blur (Actor *)
void apply_shock_effect (Actor *)
void part_glow_off (s32, ActorPart *, s32 yaw, b32 arg3)
void part_flash_off (b32 isNpcSprite, ActorPart *part, s32 yaw, b32 isReflection)
void part_flash_on (b32 isNpcSprite, ActorPart *part, s32 yaw, b32 isReflection)
void _add_part_decoration (ActorPart *)
void _remove_part_decoration (ActorPart *part, s32 decorationIndex)
void remove_part_decor_none (ActorPart *, s32)
void remove_part_decor_golden_flames (ActorPart *, s32)
void remove_part_decor_sweat (ActorPart *, s32)
void remove_part_decor_seeing_stars (ActorPart *, s32)
void remove_part_decor_red_flames (ActorPart *, s32)
void remove_part_decor_smoky_trail (ActorPart *, s32)
void remove_part_decor_fiery_trail (ActorPart *, s32)
void remove_part_decor_whirlwind (ActorPart *, s32)
void remove_part_decor_steam (ActorPart *, s32)
void remove_part_decor_sparkles (ActorPart *, s32)
void remove_part_decor_bowser_aura (ActorPart *, s32)
void remove_part_decor_radiating_stars (ActorPart *, s32)
void status_bar_ignore_changes (void)
void imgfx_release_instance (u32)
void set_script_flags (Evt *script, s32 flags)
void clear_script_flags (Evt *script, s32 flags)
void disable_player_blur (void)
void enable_player_blur (void)
void reset_player_blur (void)
void force_disable_player_blur (void)
void force_disable_player_blur_immediately (void)
void func_8023E104 (void)
void func_8023E11C (void)
void set_goal_pos_to_part (ActorState *state, s32 actorID, s32 partID)
void init_encounters_ui (void)
void initialize_collision (void)
void render_entities (void)
void render_player (void)
void render_workers_scene (void)
void render_effects_scene (void)
s32 get_asset_offset (char *, s32 *)
void initialize_status_bar (void)
void status_bar_start_blinking_fp (void)
s32 is_status_bar_visible (void)
void status_bar_start_blinking_starpoints (void)
void status_bar_stop_blinking_starpoints (void)
void status_bar_start_blinking_hp (void)
void status_bar_start_blinking_sp (void)
void status_bar_stop_blinking_fp (void)
void status_bar_stop_blinking_hp (void)
void status_bar_stop_blinking_sp (void)
void status_bar_start_blinking_sp_bars (s32 numBarsToBlink)
void status_bar_draw_number (s32 iconID, s32 x, s32 y, s32 value, s32 numDigits)
void status_bar_draw_stat (s32 id, s32 x, s32 y, s32, s32)
void set_background_size (s16, s16, s16, s16)
void set_background (BackgroundHeader *)
void set_max_star_power (s8)
void sync_status_bar (void)
void create_cameras (void)
void func_80045AC0 (void)
void func_8005AF84 (void)
void npc_follow_init (Npc *, s32, FollowAnims *, f32, f32, s32, s32)
void npc_update_npc_tracking (Npc *)
void npc_follow_npc (Npc *)
void create_encounters (void)
void update_encounters_neutral (void)
void update_encounters_pre_battle (void)
void update_encounters_conversation (void)
void update_encounters_post_battle (void)
void load_map_bg (char *optAssetName)
void reset_background_settings (void)
void func_80138188 (void)
void func_80266970 (Actor *)
void show_actor_health_bar (Actor *)
void hide_actor_health_bar (Actor *)
void clear_part_pal_adjustment (ActorPart *)
void calculate_camera_yinterp_rate (void)
void load_tattle_flags (s32)
s32 use_consumable (s32 invSlot)
void remove_consumable (void)
void delete_shadow (s32)
void partner_reset_tether_distance (void)
void save_tattle_flags (s32)
void update_merlee_messages (void)
void draw_merlee_messages (void)
void show_merlee_message (s16, s16)
s32 is_merlee_message_done (void)
void close_action_command_instruction_popup (void)
void draw_encounters_conversation (void)
void draw_encounters_post_battle (void)
void draw_encounters_pre_battle (void)
void draw_encounters_neutral (void)
void show_first_strike_message (void)
void entity_upgrade_block_hide_content (s32)
s32 lookup_defense (s32 *, s32)
s32 lookup_status_chance (s32 *, s32)
void peach_check_for_parasol_input (void)
void peach_sync_disguise_npc (void)
b32 check_conversation_trigger (void)
void clear_player_status (void)
void clear_entity_models (void)
void bind_entity_model_setupGfx (s32 idx, void *setupGfxCallbackArg0, void(*fpSetupGfxCallback)(void *))
void clear_animator_list (void)
void clear_model_data (void)
void init_sprite_shading_data (void)
void clear_sprite_shading_data (void)
void clear_character_set (void)
void clear_trigger_data (void)
void clear_script_list (void)
void clear_entity_data (b32)
void clear_effect_data (void)
void clear_saved_variables (void)
void clear_area_flags (void)
f32 get_player_normal_pitch (void)
void partner_kill_ability_script (void)
void func_800EF3D4 (s32)
void mdl_update_transform_matrices (void)
void mdl_group_set_custom_gfx (u16, s32, s32, b32)
void backup_map_collision_data (void)
void reset_status_bar (void)
void btl_save_world_cameras (void)
void load_battle_section (void)
void btl_update (void)
void update_item_entities (void)
void iterate_models (void)
void restore_map_collision_data (void)
void mdl_load_all_textures (struct ModelNode *model, s32 romOffset, s32 size)
void mdl_calculate_model_sizes (void)
Function Documentation
_add_part_decoration()
void _add_part_decoration (ActorPart * actorPart)
Referenced by add_part_decoration(), appendGfx_npc_actor(), and appendGfx_player_actor().
_heap_create()
HeapNode * _heap_create (HeapNode * addr, u32 size)
Referenced by battle_heap_create(), battle_heap_create_obfuscated(), collision_heap_create(), general_heap_create(), and spr_init_sprites().
_heap_free()
u32 _heap_free (HeapNode * heapNodeList, void * addrToFree)
Referenced by _heap_realloc(), collision_heap_free(), general_heap_free(), heap_free(), and spr_free_sprite().
_heap_malloc()
void * _heap_malloc (HeapNode * head, u32 size)
Referenced by _heap_realloc(), collision_heap_malloc(), general_heap_malloc(), heap_malloc(), imgfx_init(), spr_allocate_components(), spr_init_player_raster_cache(), spr_init_quad_cache(), and spr_load_sprite().
_heap_malloc_tail()
void * _heap_malloc_tail (HeapNode * head, u32 size)
Referenced by general_heap_malloc_tail(), and spr_load_sprite().
_heap_realloc()
void * _heap_realloc (HeapNode * heapNodeList, void * addr, u32 newSize)
Referenced by spr_load_npc_extra_anims().
_remove_part_decoration()
void _remove_part_decoration (ActorPart * part, s32 decorationIndex)
Referenced by add_part_decoration(), and remove_part_decoration().
add_actor_decoration()
void add_actor_decoration (Actor * actor, s32 decorationIndex, s32 decorationType)
add_badge()
s32 add_badge (s32 itemID)
add_coins()
s32 add_coins (s32 amt)
add_item()
s32 add_item (s32 itemID)
Referenced by add_badge(), and update_item_entity_pickup().
add_part_decoration()
void add_part_decoration (ActorPart * part, s32 decorationIndex, s32 decorationType)
Referenced by add_actor_decoration().
add_star_pieces()
s32 add_star_pieces (s32 amt)
add_star_points()
s32 add_star_points (s32 amt)
add_star_power()
void add_star_power (s32 amt)
add_vec2D_polar()
void add_vec2D_polar (f32 * x, f32 * y, f32 r, f32 theta)
Referenced by action_update_use_munchlesia(), ai_check_player_dist(), basic_ai_check_player_dist(), btl_main_menu_draw(), btl_main_menu_update(), can_dismount(), check_for_treadmill_overlaps(), ClubbaNappingAI_Sleep(), collision_main_lateral(), draw_all_status_icons(), entity_StarBoxLauncher_check_launch(), FlyingMagikoopaAI_15(), FlyingMagikoopaAI_21(), func_802BB98C_E2E2BC(), func_802BC17C_E2EAAC(), handle_jumping_land_on_switch(), MagikoopaAI_21(), offset_player_from_camera(), partner_do_player_collision(), partner_flying_follow_player(), partner_get_out(), partner_move_to_goal(), partner_walking_follow_player(), PiranhaPlantAI_10(), pre_battle(), sync_player_position(), test_item_player_collision(), update_encounters_neutral(), and update_riding_physics().
add_xz_vec3f()
void add_xz_vec3f (Vec3f * vector, f32 speed, f32 angleDeg)
add_xz_vec3f_copy1()
void add_xz_vec3f_copy1 (Vec3f * vector, f32 speed, f32 angleDeg)
add_xz_vec3f_copy2()
void add_xz_vec3f_copy2 (Vec3f * vector, f32 speed, f32 angleDeg)
ai_check_fwd_collisions()
b32 ai_check_fwd_collisions (Npc * npc, f32 time, f32 * outYaw, f32 * outDistFwd, f32 * outDistCW, f32 * outDistCCW)
Referenced by basic_ai_wander(), ClubbaNappingAI_ReturnHome(), ShyGuyPatrolAI_15(), ShyGuyPatrolAI_16(), ShyGuyWanderAI_15(), and ShyGuyWanderAI_16().
ai_check_player_dist()
s32 ai_check_player_dist (Enemy * enemy, s32 arg1, f32 arg2, f32 arg3)
Referenced by CleftAI_CanSeePlayer(), and ProjectileHitbox_GetUsableProjectileID().
ai_enemy_play_sound()
void ai_enemy_play_sound (Npc * npc, s32 arg1, s32 arg2)
Referenced by basic_ai_chase(), basic_ai_found_player_jump_init(), basic_ai_loiter(), basic_ai_wander(), CleftAI_Hiding(), ClubbaNappingAI_Sleep(), FlyingAI_Loiter(), FlyingAI_Wander(), FlyingMagikoopaAI_11(), FlyingMagikoopaAI_21(), FlyingMagikoopaAI_23(), GuardAI_Idle(), GuardAI_ReturnHome(), HoppingAI_ChaseInit(), HoppingAI_Hop(), HoppingAI_HopInit(), HoppingAI_Loiter(), LakituAI_Loiter(), LakituAI_Wander(), MagikoopaAI_21(), MagikoopaAI_23(), ParatroopaAI_Windup(), PatrolAI_Loiter(), PatrolAI_Move(), PiranhaPlantAI_01(), PiranhaPlantAI_10(), and SentinelAI_ReturnHome().
appendGfx_background_texture()
void appendGfx_background_texture (void)
Bug
xh = 2 * bgXOffset + (bgMinX - 1) * 4
Bug
xh = 2 * bgXOffset + (bgMinX - 1) * 4
Referenced by gfx_draw_background().
appendGfx_enemy_actor()
void appendGfx_enemy_actor (void * data)
Referenced by btl_render_actors().
appendGfx_enemy_actor_blur()
void appendGfx_enemy_actor_blur (void * data)
Referenced by btl_render_actors().
appendGfx_enemy_actor_reflection()
void appendGfx_enemy_actor_reflection (void * data)
Referenced by btl_render_actors().
appendGfx_ispy_icon()
void appendGfx_ispy_icon (void)
Referenced by render_ispy_icon().
appendGfx_partner_actor()
void appendGfx_partner_actor (void * data)
Referenced by btl_render_actors().
appendGfx_partner_actor_blur()
void appendGfx_partner_actor_blur (void * data)
Referenced by btl_render_actors().
appendGfx_partner_actor_reflection()
void appendGfx_partner_actor_reflection (void * data)
Referenced by btl_render_actors().
appendGfx_player_actor()
void appendGfx_player_actor (void * arg0)
Referenced by btl_render_actors().
appendGfx_player_actor_blur()
void appendGfx_player_actor_blur (Actor * actor)
Referenced by btl_render_actors().
appendGfx_player_actor_reflection()
void appendGfx_player_actor_reflection (void * arg0)
Referenced by btl_render_actors().
appendGfx_pulse_stone_icon()
void appendGfx_pulse_stone_icon (void)
Referenced by render_pulse_stone_icon().
appendGfx_speech_bubble()
void appendGfx_speech_bubble (void)
Referenced by render_conversation_prompt().
apply_shock_effect()
void apply_shock_effect (Actor * actor)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_partner_test_enemy(), calc_player_damage_enemy(), and show_damage_fx().
atan2()
f32 atan2 (f32 startX, f32 startZ, f32 endX, f32 endZ)
backup_map_collision_data()
void backup_map_collision_data (void)
Referenced by state_step_battle(), state_step_language_select(), and state_step_pause().
basic_ai_chase()
void basic_ai_chase (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
basic_ai_chase_init()
void basic_ai_chase_init (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
Referenced by HoppingAI_ChaseInit(), and StoneChompAI_ChaseInit().
basic_ai_found_player_jump()
void basic_ai_found_player_jump (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
basic_ai_found_player_jump_init()
void basic_ai_found_player_jump_init (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
basic_ai_loiter()
void basic_ai_loiter (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
basic_ai_loiter_init()
void basic_ai_loiter_init (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
basic_ai_lose_player()
void basic_ai_lose_player (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
basic_ai_suspend()
void basic_ai_suspend (Evt * script)
basic_ai_wander()
void basic_ai_wander (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
basic_ai_wander_init()
void basic_ai_wander_init (Evt * script, MobileAISettings * npcAISettings, EnemyDetectVolume * territory)
Referenced by HoppingAI_HopInit(), and StoneChompAI_HopInit().
basic_hidden_window_update()
void basic_hidden_window_update (s32 windowIndex, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by draw_shop_items(), hide_popup_menu(), update_coin_counter(), update_item_entity_pickup(), and worker_update_ingredient_windows().
basic_window_update()
void basic_window_update (s32 windowIndex, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by draw_shop_items(), func_800F16CC(), pause_tabs_update(), popup_menu_update(), show_coin_counter(), update_item_entity_pickup(), and worker_update_ingredient_windows().
battle_heap_create()
s32 battle_heap_create (void)
Referenced by battle_heap_create_obfuscated(), state_step_end_battle(), state_step_file_select(), state_step_language_select(), and state_step_pause().
bgm_adjust_proximity()
s32 bgm_adjust_proximity (s32 playerIndex, s32 arg1, s16 arg2)
bgm_clear_track_volumes()
enum AuResult bgm_clear_track_volumes (s32 playerIndex, s16 trackVolSet)
bgm_init_music_players()
s32 bgm_init_music_players (void)
Referenced by state_step_startup().
bgm_pop_battle_song()
void bgm_pop_battle_song (void)
Referenced by update_encounters_post_battle().
bgm_pop_song()
void bgm_pop_song (void)
bgm_push_battle_song()
void bgm_push_battle_song (void)
Referenced by update_encounters_pre_battle().
bgm_push_song()
void bgm_push_song (s32 songID, s32 variation)
bgm_quiet_max_volume()
void bgm_quiet_max_volume (void)
Referenced by state_step_pause().
bgm_reset_max_volume()
void bgm_reset_max_volume (void)
Referenced by state_step_unpause().
bgm_reset_sequence_players()
void bgm_reset_sequence_players (void)
Referenced by load_engine_data().
bgm_reset_volume()
void bgm_reset_volume (void)
Referenced by state_step_startup().
bgm_set_battle_song()
void bgm_set_battle_song (s32 songID, s32 variation)
Referenced by update_encounters_pre_battle().
bgm_set_song()
s32 bgm_set_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
Referenced by bgm_init_music_players(), bgm_push_battle_song(), bgm_push_song(), btl_state_update_celebration(), btl_state_update_defeat(), btl_state_update_end_training_battle(), btl_state_update_run_away(), btl_state_update_victory(), state_init_exit_file_select(), state_init_title_screen(), and state_step_title_screen().
bgm_set_track_volumes()
enum AuResult bgm_set_track_volumes (s32 playerIndex, s16 trackVolSet)
bgm_set_variation()
enum AuResult bgm_set_variation (s32 playerIndex, s16 arg1)
bgm_update_music_settings()
void bgm_update_music_settings (void)
Referenced by step_game_loop().
bind_entity_model_setupGfx()
void bind_entity_model_setupGfx (s32 idx, void * setupGfxCallbackArg0, void(*)(void *) fpSetupGfxCallback)
Referenced by render_entities(), render_shadows(), and show_immune_bonk().
bind_trigger_1()
Trigger * bind_trigger_1 (EvtScript * script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority)
boot_idle()
void boot_idle (void * data)
boot_main()
void boot_main (void * data)
btl_are_all_enemies_defeated()
s32 btl_are_all_enemies_defeated (void)
Referenced by btl_check_enemies_defeated(), and btl_state_update_partner_move().
btl_bonk_cleanup()
void btl_bonk_cleanup (void)
Referenced by btl_update().
btl_cam_disable_clamp_x()
void btl_cam_disable_clamp_x (void)
btl_cam_is_moving_done()
s32 btl_cam_is_moving_done (void)
Referenced by btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), and btl_state_update_celebration().
btl_cam_move()
void btl_cam_move (s16 moveTime)
Referenced by btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_celebration(), btl_state_update_end_player_turn(), btl_state_update_enemy_move(), btl_state_update_partner_move(), btl_state_update_peach_menu(), btl_state_update_player_menu(), btl_state_update_player_move(), and btl_state_update_twink_menu().
btl_cam_set_params()
void btl_cam_set_params (b16 skipRecalc, s16 dist, s16 fovScale, s16 pitch, s32 yaw, s32 offsetY, s32 unkParam7, s32 zoomPercent)
Referenced by btl_state_update_celebration().
btl_cam_set_target_pos()
void btl_cam_set_target_pos (f32 x, f32 y, f32 z)
Referenced by btl_cam_use_preset_impl(), and btl_state_update_change_partner().
btl_cam_set_zoffset()
void btl_cam_set_zoffset (s16 zOffset)
Referenced by btl_state_update_change_partner().
btl_cam_set_zoom()
void btl_cam_set_zoom (s16 zoom)
Referenced by btl_state_update_change_partner().
btl_cam_target_actor()
void btl_cam_target_actor (s32 actorID)
Referenced by btl_state_update_defeat(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), and btl_state_update_run_away().
btl_cam_unfreeze()
void btl_cam_unfreeze (void)
Referenced by btl_state_update_end_battle().
btl_cam_use_preset()
void btl_cam_use_preset (s32 preset)
Referenced by btl_state_update_1C(), btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_celebration(), btl_state_update_change_partner(), btl_state_update_defeat(), btl_state_update_end_battle(), btl_state_update_end_player_turn(), btl_state_update_end_training_battle(), btl_state_update_end_turn(), btl_state_update_enemy_move(), btl_state_update_first_strike(), btl_state_update_normal_start(), btl_state_update_partner_menu(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_peach_menu(), btl_state_update_player_menu(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_twink_menu(), and btl_state_update_victory().
btl_cam_use_preset_immediately()
void btl_cam_use_preset_immediately (s32 preset)
btl_check_enemies_defeated()
s32 btl_check_enemies_defeated (void)
Referenced by btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_begin_turn(), btl_state_update_end_partner_turn(), btl_state_update_end_player_turn(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), and btl_state_update_partner_striking_first().
btl_check_player_defeated()
s32 btl_check_player_defeated (void)
Referenced by btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), and btl_state_update_player_move().
btl_delete_actor()
void btl_delete_actor (Actor * actor)
Referenced by btl_state_update_change_partner(), btl_state_update_end_battle(), and btl_state_update_end_demo_battle().
btl_delete_player_actor()
void btl_delete_player_actor (Actor * player)
Referenced by btl_state_update_end_battle(), and btl_state_update_end_demo_battle().
btl_draw_prim_quad()
void btl_draw_prim_quad (u8 r, u8 g, u8 b, u8 a, u16 left, u16 top, u16 arg6, u16 arg7)
Referenced by btl_draw_enemy_health_bars(), and btl_main_menu_draw().
btl_draw_ui()
void btl_draw_ui (void)
Referenced by state_drawUI_battle().
btl_draw_upgrade_windows()
void btl_draw_upgrade_windows (s32 phase)
Referenced by btl_state_draw_celebration().
btl_is_popup_displayed()
s32 btl_is_popup_displayed (void)
Referenced by btl_main_menu_update(), btl_state_update_begin_player_turn(), btl_state_update_enemy_move(), btl_state_update_partner_menu(), btl_state_update_partner_move(), btl_state_update_peach_menu(), btl_state_update_player_menu(), btl_state_update_player_move(), and btl_state_update_twink_menu().
btl_popup_messages_draw_ui()
void btl_popup_messages_draw_ui (void)
Referenced by btl_draw_ui().
btl_popup_messages_draw_world_geometry()
void btl_popup_messages_draw_world_geometry (void)
Referenced by btl_render_actors().
btl_popup_messages_init()
void btl_popup_messages_init (void)
Referenced by initialize_battle().
btl_popup_messages_update()
void btl_popup_messages_update (void)
Referenced by btl_update().
btl_restore_world_cameras()
void btl_restore_world_cameras (void)
Referenced by state_step_end_battle().
btl_save_world_cameras()
void btl_save_world_cameras (void)
Referenced by state_step_battle().
btl_set_player_idle_anims()
void btl_set_player_idle_anims (void)
Referenced by btl_state_update_end_turn().
btl_set_popup_duration()
void btl_set_popup_duration (s32 duration)
Referenced by action_command_free(), and update().
btl_set_state()
void btl_set_state (s32 battleState)
Referenced by btl_check_enemies_defeated(), btl_check_player_defeated(), btl_state_update_1C(), btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_begin_turn(), btl_state_update_celebration(), btl_state_update_change_partner(), btl_state_update_defeat(), btl_state_update_defend(), btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_end_partner_turn(), btl_state_update_end_player_turn(), btl_state_update_end_training_battle(), btl_state_update_end_turn(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_next_enemy(), btl_state_update_normal_start(), btl_state_update_partner_menu(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_peach_menu(), btl_state_update_player_menu(), btl_state_update_player_move(), btl_state_update_prepare_menu(), btl_state_update_run_away(), btl_state_update_select_target(), btl_state_update_switch_to_partner(), btl_state_update_switch_to_player(), btl_state_update_twink_menu(), btl_state_update_victory(), btl_update(), and load_battle_section().
btl_show_battle_message()
void btl_show_battle_message (s32 messageIndex, s32 duration)
Referenced by btl_main_menu_update(), btl_state_update_begin_player_turn(), btl_state_update_enemy_move(), btl_state_update_partner_move(), btl_state_update_player_move(), and btl_state_update_select_target().
btl_show_variable_battle_message()
void btl_show_variable_battle_message (s32 messageIndex, s32 duration, s32 varValue)
Referenced by btl_state_update_partner_menu(), btl_state_update_peach_menu(), btl_state_update_player_menu(), and btl_state_update_twink_menu().
btl_state_draw_1C()
void btl_state_draw_1C (void)
Referenced by btl_draw_ui().
btl_state_draw_22()
void btl_state_draw_22 (void)
Referenced by btl_draw_ui().
btl_state_draw_9()
void btl_state_draw_9 (void)
Referenced by btl_draw_ui().
btl_state_draw_begin_partner_turn()
void btl_state_draw_begin_partner_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_begin_player_turn()
void btl_state_draw_begin_player_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_begin_turn()
void btl_state_draw_begin_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_celebration()
void btl_state_draw_celebration (void)
Referenced by btl_draw_ui().
btl_state_draw_change_partner()
void btl_state_draw_change_partner (void)
Referenced by btl_draw_ui().
btl_state_draw_defeat()
void btl_state_draw_defeat (void)
Referenced by btl_draw_ui().
btl_state_draw_defend()
void btl_state_draw_defend (void)
Referenced by btl_draw_ui().
btl_state_draw_end_battle()
void btl_state_draw_end_battle (void)
Referenced by btl_draw_ui().
btl_state_draw_end_demo_battle()
void btl_state_draw_end_demo_battle (void)
Referenced by btl_draw_ui().
btl_state_draw_end_partner_turn()
void btl_state_draw_end_partner_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_end_player_turn()
void btl_state_draw_end_player_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_end_training_battle()
void btl_state_draw_end_training_battle (void)
Referenced by btl_draw_ui().
btl_state_draw_end_turn()
void btl_state_draw_end_turn (void)
Referenced by btl_draw_ui().
btl_state_draw_enemy_move()
void btl_state_draw_enemy_move (void)
Referenced by btl_draw_ui().
btl_state_draw_enemy_striking_first()
void btl_state_draw_enemy_striking_first (void)
Referenced by btl_draw_ui().
btl_state_draw_first_stike()
void btl_state_draw_first_stike (void)
Referenced by btl_draw_ui().
btl_state_draw_next_enemy()
void btl_state_draw_next_enemy (void)
Referenced by btl_draw_ui().
btl_state_draw_normal_start()
void btl_state_draw_normal_start (void)
Referenced by btl_draw_ui().
btl_state_draw_partner_menu()
void btl_state_draw_partner_menu (void)
Referenced by btl_draw_ui().
btl_state_draw_partner_move()
void btl_state_draw_partner_move (void)
Referenced by btl_draw_ui().
btl_state_draw_partner_striking_first()
void btl_state_draw_partner_striking_first (void)
Referenced by btl_draw_ui().
btl_state_draw_peach_menu()
void btl_state_draw_peach_menu (void)
Referenced by btl_draw_ui().
btl_state_draw_player_menu()
void btl_state_draw_player_menu (void)
Referenced by btl_draw_ui().
btl_state_draw_player_move()
void btl_state_draw_player_move (void)
Referenced by btl_draw_ui().
btl_state_draw_prepare_menu()
void btl_state_draw_prepare_menu (void)
Referenced by btl_draw_ui().
btl_state_draw_run_away()
void btl_state_draw_run_away (void)
Referenced by btl_draw_ui().
btl_state_draw_select_target()
void btl_state_draw_select_target (void)
Referenced by btl_draw_ui().
btl_state_draw_switch_to_partner()
void btl_state_draw_switch_to_partner (void)
Referenced by btl_draw_ui().
btl_state_draw_switch_to_player()
void btl_state_draw_switch_to_player (void)
Referenced by btl_draw_ui().
btl_state_draw_twink_menu()
void btl_state_draw_twink_menu (void)
Referenced by btl_draw_ui().
btl_state_draw_victory()
void btl_state_draw_victory (void)
Referenced by btl_draw_ui().
btl_state_update_1C()
void btl_state_update_1C (void)
Referenced by btl_update().
btl_state_update_22()
void btl_state_update_22 (void)
Referenced by btl_update().
btl_state_update_9()
void btl_state_update_9 (void)
Referenced by btl_update().
btl_state_update_begin_partner_turn()
void btl_state_update_begin_partner_turn (void)
Referenced by btl_update().
btl_state_update_begin_player_turn()
void btl_state_update_begin_player_turn (void)
Referenced by btl_update().
btl_state_update_begin_turn()
void btl_state_update_begin_turn (void)
Referenced by btl_update().
btl_state_update_celebration()
void btl_state_update_celebration (void)
Referenced by btl_update().
btl_state_update_change_partner()
void btl_state_update_change_partner (void)
Referenced by btl_update().
btl_state_update_defeat()
void btl_state_update_defeat (void)
Referenced by btl_update().
btl_state_update_defend()
void btl_state_update_defend (void)
Referenced by btl_update().
btl_state_update_end_battle()
void btl_state_update_end_battle (void)
Referenced by btl_update().
btl_state_update_end_demo_battle()
void btl_state_update_end_demo_battle (void)
Referenced by btl_update().
btl_state_update_end_partner_turn()
void btl_state_update_end_partner_turn (void)
Referenced by btl_update().
btl_state_update_end_player_turn()
void btl_state_update_end_player_turn (void)
Referenced by btl_update().
btl_state_update_end_training_battle()
void btl_state_update_end_training_battle (void)
Referenced by btl_update().
btl_state_update_end_turn()
void btl_state_update_end_turn (void)
Referenced by btl_update().
btl_state_update_enemy_move()
void btl_state_update_enemy_move (void)
Referenced by btl_update().
btl_state_update_enemy_striking_first()
void btl_state_update_enemy_striking_first (void)
Referenced by btl_update().
btl_state_update_first_strike()
void btl_state_update_first_strike (void)
Referenced by btl_update().
btl_state_update_next_enemy()
void btl_state_update_next_enemy (void)
Referenced by btl_update().
btl_state_update_normal_start()
void btl_state_update_normal_start (void)
Referenced by btl_update().
btl_state_update_partner_menu()
void btl_state_update_partner_menu (void)
Referenced by btl_state_update_partner_menu(), btl_state_update_select_target(), and btl_update().
btl_state_update_partner_move()
void btl_state_update_partner_move (void)
Referenced by btl_update().
btl_state_update_partner_striking_first()
void btl_state_update_partner_striking_first (void)
Referenced by btl_update().
btl_state_update_peach_menu()
void btl_state_update_peach_menu (void)
Referenced by btl_state_update_peach_menu(), btl_state_update_select_target(), and btl_update().
btl_state_update_player_menu()
void btl_state_update_player_menu (void)
Bug
?
Referenced by btl_state_update_player_menu(), btl_state_update_select_target(), and btl_update().
btl_state_update_player_move()
void btl_state_update_player_move (void)
Referenced by btl_update().
btl_state_update_prepare_menu()
void btl_state_update_prepare_menu (void)
Referenced by btl_update().
btl_state_update_run_away()
void btl_state_update_run_away (void)
Referenced by btl_update().
btl_state_update_select_target()
void btl_state_update_select_target (void)
Referenced by btl_update().
btl_state_update_switch_to_partner()
void btl_state_update_switch_to_partner (void)
Referenced by btl_update().
btl_state_update_switch_to_player()
void btl_state_update_switch_to_player (void)
Referenced by btl_update().
btl_state_update_twink_menu()
void btl_state_update_twink_menu (void)
Referenced by btl_state_update_select_target(), btl_state_update_twink_menu(), and btl_update().
btl_state_update_victory()
void btl_state_update_victory (void)
Referenced by btl_update().
btl_update()
void btl_update (void)
Referenced by state_step_battle().
btl_update_ko_status()
void btl_update_ko_status (void)
Referenced by btl_state_update_enemy_move(), btl_state_update_partner_move(), and btl_state_update_player_move().
calculate_camera_yinterp_rate()
void calculate_camera_yinterp_rate (void)
Referenced by phys_peach_update(), and phys_update_action_state().
can_control_status_bar()
b32 can_control_status_bar (void)
Referenced by check_input_status_bar().
can_trigger_loading_zone()
b32 can_trigger_loading_zone (void)
cancel_current_message()
s32 cancel_current_message (void)
Referenced by pre_battle().
cancel_message()
s32 cancel_message (MessagePrintState * msgPrintState)
Referenced by cancel_current_message().
check_conversation_trigger()
b32 check_conversation_trigger (void)
Referenced by phys_peach_update(), and phys_update_action_state().
check_input_hammer()
b32 check_input_hammer (void)
Referenced by action_update_idle(), action_update_run(), action_update_spin(), and action_update_walk().
check_input_jump()
b32 check_input_jump (void)
Bug
? collider flags not properly masked with COLLIDER_FLAG_SURFACE_TYPE
Referenced by action_update_idle(), action_update_land(), action_update_pushing_block(), action_update_run(), action_update_spin(), action_update_step_down(), action_update_step_down_land(), and action_update_walk().
check_input_midair_jump()
void check_input_midair_jump (void)
Referenced by phys_update_standard().
check_input_open_menus()
void check_input_open_menus (void)
Referenced by update_player().
check_input_spin()
void check_input_spin (void)
Referenced by phys_update_action_state().
check_input_status_bar()
void check_input_status_bar (void)
Referenced by update_player().
check_player_action_debug()
b32 check_player_action_debug (void)
Referenced by phys_main_collision_below(), player_fall_distance(), and update_player().
clamp_angle()
f32 clamp_angle (f32 theta)
clear_actor_static_pal_adjustments()
void clear_actor_static_pal_adjustments (Actor * actor)
clear_animator_list()
void clear_animator_list (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_title_screen().
clear_area_flag()
s32 clear_area_flag (s32 index)
Referenced by evt_set_variable().
clear_area_flags()
void clear_area_flags (void)
Referenced by load_map_by_IDs().
clear_character_set()
void clear_character_set (void)
Referenced by load_engine_data().
clear_effect_data()
void clear_effect_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_demo(), state_step_intro(), and state_step_startup().
clear_entity_data()
void clear_entity_data (b32 arg0)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_title_screen().
clear_entity_model_flags()
void clear_entity_model_flags (s32 idx, s32 newFlags)
Referenced by btl_bonk_update().
clear_entity_models()
void clear_entity_models (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_title_screen().
clear_global_flag()
s32 clear_global_flag (s32 index)
Referenced by evt_set_variable().
clear_item_entity_data()
void clear_item_entity_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
clear_item_entity_flags()
void clear_item_entity_flags (s32 index, s32 flags)
clear_model_data()
void clear_model_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
clear_part_pal_adjustment()
void clear_part_pal_adjustment (ActorPart * part)
Referenced by calc_enemy_damage_target(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
clear_player_data()
void clear_player_data (void)
Referenced by filemenu_yesno_handle_input(), load_demo_battle(), load_engine_data(), state_init_title_screen(), state_step_demo(), state_step_intro(), and state_step_startup().
clear_player_status()
void clear_player_status (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_demo(), state_step_intro(), and state_step_startup().
clear_printers()
void clear_printers (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_title_screen(), state_step_demo(), state_step_intro(), and state_step_startup().
clear_render_tasks()
void clear_render_tasks (void)
Referenced by load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_demo(), state_step_intro(), state_step_startup(), and state_step_title_screen().
clear_saved_variables()
void clear_saved_variables (void)
Referenced by filemenu_yesno_handle_input(), load_engine_data(), state_init_demo(), state_step_demo(), state_step_intro(), and state_step_startup().
clear_screen_overlays()
void clear_screen_overlays (void)
Referenced by load_engine_data(), state_step_demo(), state_step_intro(), and state_step_startup().
clear_script_flags()
void clear_script_flags (Evt * script, s32 flags)
Referenced by clear_script_flags(), and update_encounters_neutral().
clear_script_list()
void clear_script_list (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_demo(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
clear_sprite_shading_data()
void clear_sprite_shading_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
clear_trigger_data()
void clear_trigger_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
clear_virtual_entity_list()
void clear_virtual_entity_list (void)
Referenced by clear_script_list().
clear_windows()
void clear_windows (void)
Referenced by load_engine_data(), state_step_startup(), and state_step_title_screen().
clear_worker_list()
void clear_worker_list (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
clear_world_menus()
void clear_world_menus (void)
Referenced by player_reset_data().
clone_model()
void clone_model (u16 srcModelID, u16 newModelID)
close_action_command_instruction_popup()
void close_action_command_instruction_popup (void)
Referenced by action_command_free(), and btl_state_update_player_move().
close_message()
void close_message (MessagePrintState * msgPrintState)
Referenced by _show_message(), and entity_SaveBlock_wait_for_close_choice().
close_status_bar()
void close_status_bar (void)
Referenced by check_conversation_trigger(), check_input_status_bar(), destroy_popup_menu(), initialize_status_bar(), and shop_close_item_select_popup().
collision_check_player_overlaps()
void collision_check_player_overlaps (void)
Referenced by phys_update_standard().
collision_lateral_peach()
void collision_lateral_peach (void)
Referenced by collision_lava_reset_check_additional_overlaps(), and phys_update_standard().
collision_lava_reset_check_additional_overlaps()
void collision_lava_reset_check_additional_overlaps (void)
Referenced by action_update_use_spinning_flower(), and phys_update_lava_reset().
collision_main_above()
HitID collision_main_above (void)
Referenced by phys_update_standard().
collision_main_lateral()
void collision_main_lateral (void)
Referenced by phys_update_lava_reset(), phys_update_standard(), and update_player().
copy_matrix()
void copy_matrix (Matrix4f src, Matrix4f dest)
Referenced by animator_node_update_model_transform(), and update_collider_transform().
cos_deg()
f32 cos_deg (f32 x)
cos_rad()
f32 cos_rad (f32 x)
Referenced by action_hammer_play_hit_fx(), action_update_hit_lava(), action_update_parasol(), action_update_spin(), add_part_decor_steam(), add_xz_vec3f(), add_xz_vec3f_copy1(), add_xz_vec3f_copy2(), apply_constraints_to_lead_amount(), build_gfx_floor(), build_gfx_thread(), ChompChainAddPolarPos(), ChompChainGetPolarX(), create_camera_leadplayer_matrix(), Entity_BoardedFloor_update_fragments(), entity_BombableRock_update_fragments(), entity_GiantChest_give_equipment(), entity_GiantChest_open(), entity_HeartBlockContent__anim_heal(), entity_Padlock_push_player(), entity_StarBoxLauncher_launch(), entity_TrumpetPlant_create_effect(), entity_TrumpetPlant_spawn_coin(), entity_Tweester_move(), entity_WoodenCrate_update_fragments(), interp_lookat_pos(), npc_do_other_npc_collision(), npc_do_player_collision(), npc_move_heading(), npc_raycast_down_around(), npc_raycast_down_sides(), npc_raycast_up_corners(), play_movement_dust_effects(), player_raycast_up_corners(), spawn_cloud_surface_effects(), spawn_flower_surface_effects(), spawn_hedge_surface_effects(), spawn_snow_surface_effects(), spawn_water_surface_effects(), sync_held_position(), unkVtxFunc001(), update_camera_interp_pos(), update_camera_no_interp(), update_camera_unused_ahead(), update_camera_unused_confined(), update_camera_unused_radial(), update_camera_zone_interp(), update_item_entity_collectable(), update_lerp(), update_lerp_battle(), and virtual_entity_move_polar().
cosine()
f32 cosine (s16 arg0)
Referenced by appendGfx_message(), imgfx_appendGfx_mesh(), msg_draw_choice_pointer(), msg_draw_speech_arrow(), msg_update_rewind_arrow(), npc_update_decoration_charged(), part_glow_on(), and SentinelAI_Descend().
count_power_plus()
s32 count_power_plus (s32 damageType)
Referenced by calc_player_damage_enemy().
crash_screen_init()
void crash_screen_init (void)
Referenced by boot_main().
crash_screen_set_draw_info()
void crash_screen_set_draw_info (u16 * frameBufPtr, s16 width, s16 height)
Referenced by gfx_draw_frame().
create_cameras()
void create_cameras (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_demo(), state_step_intro(), state_step_startup(), and state_step_title_screen().
create_current_pos_target_list()
void create_current_pos_target_list (Actor * actor)
Referenced by btl_init_menu_boots(), btl_init_menu_hammer(), btl_init_menu_partner(), btl_state_update_partner_striking_first(), btl_state_update_player_menu(), btl_state_update_select_target(), count_targets(), and func_80263300().
create_encounters()
void create_encounters (void)
Referenced by update_encounters().
create_entity()
s32 create_entity (EntityBlueprint * bp, ...)
Referenced by entity_breakable_block_create_shattering_entity(), entity_HeartBlock_create_child_entity(), entity_ItemBlock_check_if_inactive(), entity_ItemBlock_replace_with_inactive(), entity_MulticoinBlock_check_if_inactive(), entity_MulticoinBlock_idle(), entity_MulticoinBlock_spawn_coin(), entity_Munchlesia_create_child(), entity_PinkFlower_init(), and entity_upgrade_block_check_if_inactive().
create_home_target_list()
void create_home_target_list (Actor * actor)
create_mesh_animator()
s32 create_mesh_animator (s16 * animPos, s16 * animBuffer)
Referenced by load_split_entity_data().
create_model_animator()
s32 create_model_animator (s16 * animPos)
Referenced by create_shadow_from_data(), and load_split_entity_data().
create_part_shadow()
void create_part_shadow (s32 actorID, s32 partID)
create_part_shadow_by_ref()
void create_part_shadow_by_ref (s32 arg0, ActorPart * part)
create_shadow_type()
s32 create_shadow_type (s32 type, f32 x, f32 y, f32 z)
Referenced by create_actor(), create_entity_shadow(), create_npc_impl(), create_part_shadow(), create_part_shadow_by_ref(), load_partner_actor(), load_player_actor(), make_item_entity(), make_item_entity_at_player(), and player_reset_data().
create_status_debuff()
void create_status_debuff (s32 iconID, s32 statusID)
Referenced by appendGfx_npc_actor(), appendGfx_player_actor(), and inflict_status().
create_status_icon_set()
s32 create_status_icon_set (void)
Referenced by create_actor(), load_partner_actor(), and load_player_actor().
create_status_static()
void create_status_static (s32 iconID, s32 statusID)
Referenced by appendGfx_npc_actor(), appendGfx_player_actor(), and inflict_status().
create_status_transparent()
void create_status_transparent (s32 iconID, s32 statusID)
Referenced by appendGfx_npc_actor(), appendGfx_player_actor(), and inflict_status().
create_trigger()
Trigger * create_trigger (TriggerBlueprint * def)
Referenced by bind_trigger(), evt_handle_bind(), and evt_handle_bind_lock().
create_worker_frontUI()
s32 create_worker_frontUI (void(*)(void) updateFunc, void(*)(void) drawFunc)
Referenced by clear_item_entity_data(), create_action_command_ui_worker(), create_battle_popup_menu(), create_shop_popup_menu(), create_standard_popup_menu(), init_credits(), and partner_reset_data().
create_worker_scene()
s32 create_worker_scene (void(*)(void) updateFunc, void(*)(void) renderFunc)
Referenced by clear_encounter_status(), clear_item_entity_data(), clear_virtual_entity_list(), func_80045AC0(), init_encounter_status(), initialize_battle(), and reset_model_animators().
decode_yay0()
void decode_yay0 (void * src, void * dst)
Referenced by btl_state_update_normal_start(), load_battle_hit_asset(), load_map_bg(), load_map_by_IDs(), load_map_hit_asset(), pause_partners_load_portrait(), spr_load_sprite(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
decrement_status_bar_disabled()
void decrement_status_bar_disabled (void)
Referenced by btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_first_strike(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), and update_item_entity_pickup().
deduct_current_move_fp()
void deduct_current_move_fp (void)
Referenced by btl_state_update_change_partner(), and btl_state_update_partner_move().
delete_shadow()
void delete_shadow (s32 shadowIndex)
Referenced by btl_delete_actor(), btl_delete_player_actor(), free_npc(), free_npc_by_index(), remove_item_entity_by_index(), remove_item_entity_by_reference(), and remove_part_shadow().
delete_trigger()
void delete_trigger (Trigger * toDelete)
Referenced by evt_handle_unbind().
destroy_popup_menu()
void destroy_popup_menu (void)
Referenced by btl_state_update_partner_menu(), btl_state_update_player_menu(), check_input_open_menus(), popup_menu_update(), shop_close_item_select_popup(), and update_item_entity_pickup().
disable_actor_blur()
void disable_actor_blur (Actor * actor)
Referenced by disable_partner_blur().
disable_npc_blur()
void disable_npc_blur (Npc * npc)
Referenced by free_npc(), free_npc_by_index(), partner_put_away(), pre_battle(), pre_battle(), and pre_battle().
disable_partner_blur()
void disable_partner_blur (void)
disable_player_blur()
void disable_player_blur (void)
disable_player_input()
s32 disable_player_input (void)
Referenced by _use_partner_ability(), action_update_landing_on_switch(), action_update_spin_jump(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), check_input_open_menus(), entity_BlueWarpPipe_set_player_move_to_center(), entity_Chest_idle(), entity_CymbalPlant_idle(), entity_HeartBlock_show_tutorial_message(), entity_HeartBlockContent_anim_idle(), entity_SaveBlock_pause_game(), entity_SimpleSpring_idle(), entity_TriggerBlock_disable_player_input(), func_802BC0B8_E2E9E8(), phys_player_land(), post_battle(), post_battle(), SentinelAI_Descend(), start_battle(), state_init_file_select(), state_init_language_select(), state_init_pause(), state_step_change_map(), state_step_enter_world(), state_step_intro(), step_game_loop(), update_encounters_neutral(), and update_item_entity_pickup().
disable_player_shadow()
void disable_player_shadow (void)
Referenced by action_update_use_tweester(), entity_BlueWarpPipe_enter_pipe_init(), and func_802BC0B8_E2E9E8().
disable_player_static_collisions()
s32 disable_player_static_collisions (void)
Referenced by action_update_parasol(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), entity_BlueWarpPipe_set_player_move_to_center(), entity_HiddenPanel_flip_over(), entity_StarBoxLauncher_check_launch(), and post_battle().
disable_status_bar_input()
void disable_status_bar_input (void)
disable_transform_group()
void disable_transform_group (u16 modelID)
dispatch_damage_event_actor_0()
s32 dispatch_damage_event_actor_0 (Actor * actor, s32 damageAmount, s32 event)
Referenced by btl_state_update_9().
dispatch_damage_event_actor_1()
s32 dispatch_damage_event_actor_1 (Actor * actor, s32 damageAmount, s32 event)
Referenced by calc_enemy_damage_target().
dispatch_damage_event_partner()
s32 dispatch_damage_event_partner (s32 damageAmount, s32 event, s32 stopMotion)
Referenced by dispatch_damage_event_partner_0(), and dispatch_damage_event_partner_1().
dispatch_event_actor()
void dispatch_event_actor (Actor * actor, s32 event)
Referenced by btl_state_update_9(), calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_partner_test_enemy(), calc_player_damage_enemy(), calc_player_test_enemy(), dispatch_damage_event_actor(), and dispatch_event_general().
dispatch_event_partner()
void dispatch_event_partner (s32 lastEventType)
Referenced by btl_state_update_begin_partner_turn(), btl_state_update_end_training_battle(), btl_state_update_victory(), calc_enemy_damage_target(), dispatch_damage_event_partner(), and dispatch_event_general().
dispatch_event_player()
void dispatch_event_player (s32 eventType)
Referenced by btl_state_update_begin_player_turn(), btl_state_update_end_training_battle(), btl_state_update_victory(), calc_enemy_damage_target(), dispatch_damage_event_player(), and dispatch_event_general().
dist2D()
f32 dist2D (f32 ax, f32 ay, f32 bx, f32 by)
Referenced by _npc_jump_to(), action_update_use_spinning_flower(), action_update_use_tweester(), ai_check_fwd_collisions(), ai_check_player_dist(), AvoidPlayerAI_ChaseInit(), basic_ai_chase(), basic_ai_chase_init(), basic_ai_check_player_dist(), basic_ai_wander(), BooPatrolAI_Move(), CleftAI_ReturnHome(), CleftAI_RevUp(), ClubbaNappingAI_ReturnHome(), ClubbaNappingAI_Sleep(), entity_HiddenPanel_idle(), entity_Tweester_idle(), FlyingAI_Wander(), FlyingMagikoopaAI_15(), func_802BB0A0_E2D9D0(), func_802BB8D4_E2E204(), func_802BC0F0_E2EA20(), game_input_to_move_vector(), get_movement_from_input(), get_stick_input_radial(), get_xz_dist_to_player(), GuardAI_ReturnHome(), handle_jumping_land_on_switch(), is_point_outside_territory(), MagikoopaAI_10(), MeleeHitbox_CanSeePlayer(), msg_draw_speech_arrow(), npc_find_closest(), npc_find_closest_simple(), npc_follow_npc(), npc_update_npc_tracking(), ParatroopaAI_Windup(), partner_flying_follow_player(), partner_get_out(), partner_move_to_goal(), partner_put_away(), partner_walking_follow_player(), PatrolAI_Move(), PatrolAI_MoveInit(), PiranhaPlantAI_10(), player_input_to_move_vector(), player_jump(), render_entities(), SentinelAI_Chase(), SentinelAI_ReturnHome(), test_first_strike(), test_first_strike(), UnkDistFunc(), update_camera_unused_radial(), update_camera_zone_interp(), and update_player_shadow().
dist3D()
f32 dist3D (f32 ax, f32 ay, f32 az, f32 bx, f32 by, f32 bz)
Referenced by update_triggers().
dma_copy()
u32 dma_copy (Addr romStart, Addr romEnd, void * vramDest)
Referenced by btl_state_update_celebration(), create_partner_npc(), dma_load_msg(), filemenu_selectlanguage_init(), filemenu_selectlanguage_update(), get_asset_offset(), imgfx_load_anim(), imgfx_mesh_anim_update(), load_asset_by_name(), load_battle_section(), load_effect(), load_font_data(), load_map_by_IDs(), load_obfuscation_shims(), load_simple_entity_data(), load_split_entity_data(), load_story_image(), load_texture_by_name(), load_texture_impl(), load_texture_variants(), msg_copy_to_print_buffer(), phys_peach_update(), phys_update_action_state(), reload_world_entity_data(), render_curtains(), state_init_logos(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), state_step_unpause(), and use_consumable().
does_script_exist()
s32 does_script_exist (s32 id)
Referenced by _use_partner_ability(), btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_begin_turn(), btl_state_update_celebration(), btl_state_update_change_partner(), btl_state_update_defeat(), btl_state_update_defend(), btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_end_player_turn(), btl_state_update_end_training_battle(), btl_state_update_end_turn(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_next_enemy(), btl_state_update_normal_start(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_victory(), create_encounters(), evt_handle_does_script_exist(), evt_trigger_on_activate_exec_script(), evt_trigger_on_activate_lock(), partner_handle_after_battle(), partner_handle_before_battle(), partner_kill_ability_script(), partner_resume_ability_script(), partner_suspend_ability_script(), state_step_change_map(), state_step_enter_world(), state_step_game_over(), state_step_intro(), update_encounters_conversation(), update_encounters_post_battle(), update_entities(), and update_item_entity_collectable().
does_script_exist_by_ref()
s32 does_script_exist_by_ref (Evt * script)
draw_box()
s32 draw_box (s32 flags, WindowStyle windowStyle, s32 posX, s32 posY, s32 posZ, s32 width, s32 height, u8 opacity, u8 darkening, f32 scaleX, f32 scaleY, f32 rotX, f32 rotY, f32 rotZ, void(*)(s32, s32, s32, s32, s32, s32, s32) fpDrawContents, void * drawContentsArg0, Matrix4f rotScaleMtx, s32 translateX, s32 translateY, Matrix4f outMtx)
draw_ci_image_with_clipping()
s32 draw_ci_image_with_clipping (u8 * raster, s32 width, s32 height, s32 fmt, s32 bitDepth, u16 * palette, s16 posX, s16 posY, u16 clipULx, u16 clipULy, u16 clipLRx, u16 clipRLy, u8 opacity)
Referenced by appendGfx_message(), appendGfx_score_display(), CharAnim_FadeIn_5(), CharAnim_FadeOut_3(), CharAnim_Hold(), msg_draw_choice_pointer(), and msg_draw_rewind_arrow().
draw_encounters_conversation()
void draw_encounters_conversation (void)
Referenced by draw_encounter_ui().
draw_encounters_neutral()
void draw_encounters_neutral (void)
Referenced by draw_encounter_ui().
draw_encounters_post_battle()
void draw_encounters_post_battle (void)
Referenced by draw_encounter_ui().
draw_encounters_pre_battle()
void draw_encounters_pre_battle (void)
Referenced by draw_encounter_ui().
draw_entity_model_A()
void draw_entity_model_A (s32 modelIdx, Mtx * transformMtx)
Referenced by btl_bonk_render(), render_entities(), render_shadows(), and virtual_entity_list_render_world().
draw_entity_model_B()
void draw_entity_model_B (s32 modelIdx, Mtx * transformMtx, s32 vertexSegment, Vec3s * vertexArray)
Referenced by render_entities(), and render_shadows().
draw_entity_model_C()
void draw_entity_model_C (s32 modelIdx, Mtx * transformMtx)
draw_entity_model_D()
void draw_entity_model_D (s32 modelIdx, Mtx * transformMtx, s32 arg2, Vec3s * vertexArray)
draw_entity_model_E()
void draw_entity_model_E (s32 modelIdx, Mtx * transformMtx)
Referenced by virtual_entity_list_render_UI().
draw_merlee_messages()
void draw_merlee_messages (void)
Referenced by draw_encounter_ui().
draw_msg()
void draw_msg (s32 msgID, s32 posX, s32 posY, s32 opacity, s32 palette, u8 style)
draw_number()
void draw_number (s32 value, s32 x, s32 y, s32 variableWidthChars, s32 palette, s32 opacity, u16 style)
Referenced by appendGfx_records_impl(), appendGfx_score_display(), btl_menu_moves_draw_content(), coin_counter_draw_content(), draw_record_display(), draw_shop_items(), filemenu_draw_contents_file_info(), filemenu_draw_contents_file_title(), filemenu_info_draw_message_contents(), filemenu_yesno_draw_prompt_contents(), func_800F4D28(), pause_badges_draw_contents(), pause_partners_draw_movelist(), pause_stats_draw_contents(), popup_menu_draw_menu_contents(), and popup_menu_draw_title_contents().
draw_prev_frame_buffer_at_screen_pos()
void draw_prev_frame_buffer_at_screen_pos (s32 x1, s32 y1, s32 x2, s32 y2, f32 alpha)
draw_status_ui()
void draw_status_ui (void)
Referenced by btl_draw_ui(), state_drawUI_change_map(), state_drawUI_enter_world(), and state_drawUI_world().
enable_actor_blur()
void enable_actor_blur (Actor * actor)
Referenced by enable_partner_blur().
enable_background_wave()
void enable_background_wave (void)
Referenced by EnableBackgroundWave().
enable_entity_fog()
void enable_entity_fog (void)
enable_npc_blur()
void enable_npc_blur (Npc * npc)
Referenced by partner_put_away().
enable_partner_ai()
void enable_partner_ai (void)
Referenced by action_update_use_spinning_flower(), entity_CymbalPlant_idle(), and func_802BC32C_E2EC5C().
enable_partner_blur()
void enable_partner_blur (void)
enable_player_blur()
void enable_player_blur (void)
enable_player_input()
s32 enable_player_input (void)
Referenced by _use_partner_ability(), action_update_spin_jump(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), check_input_open_menus(), end_outta_sight_cleanup(), entity_Chest_enable_player_input(), entity_CymbalPlant_idle(), entity_GiantChest_await_got_item(), entity_HeartBlock_wait_for_close_tutorial(), entity_HeartBlockContent__anim_heal(), entity_SaveBlock_resume_game(), entity_SimpleSpring_enable_player_input(), entity_TriggerBlock_enable_player_input(), func_802BC3A0_E2ECD0(), handle_jumping_land_on_switch(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), SentinelAI_GrabPlayer(), set_action_state(), state_step_change_map(), state_step_enter_world(), state_step_exit_language_select(), state_step_unpause(), update_encounters_conversation(), update_encounters_post_battle(), and update_item_entity_pickup().
enable_player_shadow()
void enable_player_shadow (void)
Referenced by func_802BC3A0_E2ECD0().
enable_player_static_collisions()
s32 enable_player_static_collisions (void)
Referenced by action_update_parasol(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), entity_HiddenPanel_flip_over(), entity_StarBoxLauncher_launch(), pre_battle(), pre_battle(), and pre_battle().
enable_status_bar_input()
void enable_status_bar_input (void)
enable_transform_group()
void enable_transform_group (u16 modelID)
Referenced by mdl_make_transform_group().
enable_world_fog()
void enable_world_fog (void)
enforce_hpfp_limits()
void enforce_hpfp_limits (void)
Referenced by pause_badges_handle_input(), and pause_handle_input().
entity_base_block_idle()
s32 entity_base_block_idle (Entity * entity)
Referenced by entity_block_hit_animate_scale(), entity_BrickBlock_idle(), entity_HeartBlock_idle(), entity_ItemBlock_idle(), entity_MulticoinBlock_idle(), entity_SaveBlock_idle(), and entity_upgrade_block_idle().
entity_base_block_init()
void entity_base_block_init (Entity * entity)
Referenced by entity_HeartBlock_create_child_entity(), entity_init_Hammer1Block_normal(), entity_ItemBlock_init(), entity_ItemlessBlock_init(), entity_MulticoinBlock_init(), entity_SaveBlock_init(), and entity_upgrade_block_init().
entity_base_switch_anim_init()
void entity_base_switch_anim_init (Entity * entity)
entity_base_switch_animate_scale()
void entity_base_switch_animate_scale (Entity * entity)
entity_base_switch_init()
void entity_base_switch_init (Entity * entity)
Referenced by entity_BlueSwitch_init(), and entity_HugeBlueSwitch_init().
entity_base_switch_start_bound_script()
void entity_base_switch_start_bound_script (Entity * entity)
entity_block_handle_collision()
s32 entity_block_handle_collision (Entity * entity)
entity_block_hit_animate_scale()
void entity_block_hit_animate_scale (Entity * entity)
entity_block_hit_init_scale()
f32 entity_block_hit_init_scale (Entity * entity)
entity_BlueSwitch_init()
void entity_BlueSwitch_init (Entity * entity)
entity_can_collide_with_jumping_player()
s32 entity_can_collide_with_jumping_player (Entity * entity)
Referenced by entity_HeartBlockContent_anim_idle().
entity_GreenStompSwitch_extend()
void entity_GreenStompSwitch_extend (Entity * entity)
entity_GreenStompSwitch_idle()
void entity_GreenStompSwitch_idle (Entity * entity)
entity_GreenStompSwitch_retract()
void entity_GreenStompSwitch_retract (Entity * entity)
entity_HugeBlueSwitch_idle()
void entity_HugeBlueSwitch_idle (Entity * entity)
entity_HugeBlueSwitch_init()
void entity_HugeBlueSwitch_init (Entity * entity)
entity_raycast_down()
s32 entity_raycast_down (f32 * x, f32 * y, f32 * z, f32 * hitYaw, f32 * hitPitch, f32 * hitLength)
Referenced by entity_switch_fall_down(), is_block_on_ground(), update_entity_shadow_position(), and update_npcs().
entity_RedSwitch_animate_scale()
s32 entity_RedSwitch_animate_scale (Entity * entity)
entity_RedSwitch_wait_and_reset()
void entity_RedSwitch_wait_and_reset (Entity * entity)
entity_SaveBlock_idle()
void entity_SaveBlock_idle (Entity * entity)
entity_SaveBlock_init()
void entity_SaveBlock_init (Entity * entity)
entity_SaveBlock_pause_game()
void entity_SaveBlock_pause_game (void)
entity_SaveBlock_resume_game()
void entity_SaveBlock_resume_game (void)
entity_SaveBlock_save_data()
void entity_SaveBlock_save_data (void)
entity_SaveBlock_show_choice_message()
void entity_SaveBlock_show_choice_message (void)
entity_SaveBlock_show_result_message()
void entity_SaveBlock_show_result_message (void)
entity_SaveBlock_show_tutorial_message()
void entity_SaveBlock_show_tutorial_message (Entity * entity)
entity_SaveBlock_wait_for_close_choice()
void entity_SaveBlock_wait_for_close_choice (Entity * entity)
entity_SaveBlock_wait_for_close_result()
void entity_SaveBlock_wait_for_close_result (Entity * entity)
entity_SaveBlock_wait_for_close_tutorial()
void entity_SaveBlock_wait_for_close_tutorial (Entity * entity)
entity_Shadow_init()
void entity_Shadow_init (Shadow * entity)
entity_shattering_idle()
void entity_shattering_idle (Entity * entity)
entity_small_switch_idle()
void entity_small_switch_idle (Entity * entity)
entity_start_script()
s32 entity_start_script (Entity * entity)
Referenced by action_update_use_tweester(), entity_ArrowSign_handle_collision(), entity_base_switch_start_bound_script(), entity_block_handle_collision(), entity_BlueWarpPipe_start_bound_script(), Entity_BoardedFloor_idle(), entity_BombableRock_idle(), entity_Chest_start_bound_script(), entity_GreenStompSwitch_retract(), entity_Padlock_idle(), entity_ScriptSpring_idle(), entity_Signpost_idle(), entity_SimpleSpring_idle(), entity_StarBoxLauncher_start_script(), entity_TriggerBlock_start_bound_script_2(), and entity_WoodenCrate_idle().
entity_upgrade_block_hide_content()
void entity_upgrade_block_hide_content (s32 entityIndex)
evt_get_float_variable()
f32 evt_get_float_variable (Evt * script, Bytecode var)
Referenced by appendGfx_shrunk_player(), evt_handle_addF(), evt_handle_divideF(), evt_handle_get_1_float(), evt_handle_get_2_float(), evt_handle_get_3_float(), evt_handle_get_4_float(), evt_handle_multiplyF(), evt_handle_set_float(), evt_handle_set_timescale(), evt_handle_subtractF(), evt_handle_wait_seconds(), and make_vine_interpolation().
evt_get_variable()
s32 evt_get_variable (Evt * script, Bytecode var)
Referenced by _npc_jump_to(), _show_message(), animate_and_draw_record(), appendGfx_piranha_vines(), appendGfx_records(), appendGfx_ritual_card(), appendGfx_sticker(), apply_transform_to_children(), calculate_records(), card_worker_render(), card_worker_update(), check_input_open_menus(), check_input_status_bar(), evt_handle_add(), evt_handle_allocate_array(), evt_handle_AND(), evt_handle_AND_const(), evt_handle_bind(), evt_handle_bind_lock(), evt_handle_call(), evt_handle_case_equal(), evt_handle_case_equal_AND(), evt_handle_case_equal_OR(), evt_handle_case_greater(), evt_handle_case_greater_equal(), evt_handle_case_less(), evt_handle_case_less_equal(), evt_handle_case_not_equal(), evt_handle_case_range(), evt_handle_divide(), evt_handle_does_script_exist(), evt_handle_end_loop(), evt_handle_exec1(), evt_handle_exec1_get_id(), evt_handle_exec_wait(), evt_handle_get_Nth_float(), evt_handle_get_Nth_word(), evt_handle_goto(), evt_handle_if_AND(), evt_handle_if_equal(), evt_handle_if_greater(), evt_handle_if_greater_equal(), evt_handle_if_less(), evt_handle_if_less_equal(), evt_handle_if_not_AND(), evt_handle_if_not_equal(), evt_handle_jump(), evt_handle_kill(), evt_handle_mod(), evt_handle_multiply(), evt_handle_OR(), evt_handle_OR_const(), evt_handle_resume(), evt_handle_resume_all(), evt_handle_resume_others(), evt_handle_set_array(), evt_handle_set_flag_array(), evt_handle_set_float_buffer_ptr(), evt_handle_set_group(), evt_handle_set_int_buffer_ptr(), evt_handle_set_priority(), evt_handle_set_var(), evt_handle_subtract(), evt_handle_suspend(), evt_handle_suspend_all(), evt_handle_suspend_others(), evt_handle_switch(), evt_handle_wait(), func_80240DA4_9087D4(), func_80241610_990DF0(), func_80244F5C_8057DC(), get_spirits_rescued(), get_tattle(), GetCardOrientation(), GetPhonographData(), gfx_build_bubble_flower(), gfx_build_knocked_down_player(), gfx_build_rowf_rug_with_ripples(), gfx_build_splashes(), goto_map(), load_map_bg(), map_init(), pause_cleanup(), pause_handle_input(), pause_init(), pause_map_draw_contents(), pause_map_handle_input(), pause_map_init(), pause_map_update(), pause_stats_handle_input(), pause_tutorial_draw_contents(), phys_adjust_cam_on_landing(), player_jump(), ProjectileHitbox_GetUsableProjectileID(), Quizmo_CreateReactionEffect(), setup_gfx_bridge(), update_item_entity_pickup(), and update_status_bar().
evt_get_variable_index()
s32 evt_get_variable_index (Evt * script, s32 var)
Referenced by evt_handle_bind(), and evt_handle_bind_lock().
evt_set_float_variable()
f32 evt_set_float_variable (Evt * script, Bytecode var, f32 value)
Referenced by evt_handle_addF(), evt_handle_divideF(), evt_handle_get_1_float(), evt_handle_get_2_float(), evt_handle_get_3_float(), evt_handle_get_4_float(), evt_handle_get_Nth_float(), evt_handle_multiplyF(), evt_handle_set_float(), evt_handle_subtractF(), and exec_ShakeCamX().
evt_set_variable()
s32 evt_set_variable (Evt * script, Bytecode var, s32 value)
Referenced by card_worker_render(), card_worker_update(), evt_handle_add(), evt_handle_allocate_array(), evt_handle_AND(), evt_handle_AND_const(), evt_handle_bind(), evt_handle_divide(), evt_handle_does_script_exist(), evt_handle_end_loop(), evt_handle_exec1_get_id(), evt_handle_get_1_word(), evt_handle_get_2_word(), evt_handle_get_3_word(), evt_handle_get_4_word(), evt_handle_get_Nth_word(), evt_handle_mod(), evt_handle_multiply(), evt_handle_OR(), evt_handle_OR_const(), evt_handle_set_const(), evt_handle_set_var(), evt_handle_subtract(), exec_ShakeCamX(), filemenu_yesno_handle_input(), init_enter_world_shared(), load_demo_battle(), state_step_demo(), update_item_entity_pickup(), and worker_update_phonograph_hud().
evt_trigger_on_activate_exec_script()
s32 evt_trigger_on_activate_exec_script (Trigger * trigger)
Referenced by bind_trigger(), and evt_handle_bind().
exec_entity_commandlist()
void exec_entity_commandlist (Entity * entity)
Referenced by action_update_use_spinning_flower(), entity_base_switch_animate_scale(), entity_BellbellPlant_idle(), entity_block_handle_collision(), entity_BlueWarpPipe_check_if_active(), entity_BlueWarpPipe_enter_pipe_update(), entity_BlueWarpPipe_idle(), entity_BlueWarpPipe_rise_up(), entity_BlueWarpPipe_wait_for_player_to_get_off(), entity_BlueWarpPipe_wait_player_move_to_center(), Entity_BoardedFloor_idle(), Entity_BoardedFloor_update_fragments(), entity_BombableRock_idle(), entity_BombableRock_update_fragments(), entity_Chest_idle(), entity_Chest_open(), entity_GiantChest_await_got_item(), entity_GiantChest_open(), entity_GreenStompSwitch_extend(), entity_GreenStompSwitch_idle(), entity_GreenStompSwitch_retract(), entity_HeartBlock_show_tutorial_message(), entity_HeartBlock_wait_for_close_tutorial(), entity_HeartBlockContent__anim_heal(), entity_HeartBlockContent_anim_idle(), entity_HiddenPanel_flip_over(), entity_HiddenPanel_idle(), entity_HugeBlueSwitch_idle(), entity_inactive_block_hit_anim(), entity_inactive_block_recoil_anim(), entity_ItemBlock_check_if_inactive(), entity_MulticoinBlock_idle(), entity_Padlock_idle(), entity_PinkFlower_idle(), entity_RedSwitch_animate_scale(), entity_RedSwitch_wait_and_reset(), entity_SaveBlock_show_tutorial_message(), entity_SaveBlock_wait_for_close_choice(), entity_SaveBlock_wait_for_close_result(), entity_SaveBlock_wait_for_close_tutorial(), entity_ScriptSpring_idle(), entity_shattering_idle(), entity_SimpleSpring_idle(), entity_small_switch_idle(), entity_StarBoxLauncher_check_launch(), entity_StarBoxLauncher_launch(), entity_TrumpetPlant_idle(), entity_WoodenCrate_idle(), entity_WoodenCrate_update_fragments(), func_802BB0A0_E2D9D0(), func_802BC050_E2E980(), and func_802BC99C_E312EC().
exec_entity_model_commandlist()
void exec_entity_model_commandlist (s32 idx)
Referenced by ALT_virtual_entity_create(), btl_bonk_update(), create_entity(), update_entities(), update_shadows(), virtual_entity_create(), virtual_entity_create_at_index(), and virtual_entity_list_update().
exec_ShakeCam1()
void exec_ShakeCam1 (s32 arg0, s32 arg1, s32 arg2)
Referenced by action_update_spin_jump(), action_update_tornado_jump(), and get_overriding_player_anim().
exec_ShakeCamX()
void exec_ShakeCamX (s32 arg0, s32 arg1, s32 arg2, f32 arg3)
Referenced by action_hammer_play_hit_fx(), action_update_hit_lava(), and entity_HiddenPanel_flip_over().
fabs()
f64 fabs (f64 f)
Referenced by action_update_sliding(), action_update_state_23(), entity_HiddenPanel_idle(), entity_HiddenPanel_is_item_on_top(), entity_Padlock_push_player(), entity_Tweester_idle(), func_802BB0A0_E2D9D0(), func_802BB8D4_E2E204(), func_802BC0F0_E2EA20(), parasol_get_npc(), partner_flying_follow_player(), partner_move_to_goal(), player_raycast_general(), sfx_compute_spatialized_sound_params_ignore_depth(), test_mounting_height_adjustment(), and update_riding_physics().
fabsf()
f32 fabsf (f32 f)
Referenced by action_update_run(), action_update_sliding(), action_update_use_spinning_flower(), action_update_use_tweester(), action_update_walk(), appendGfx_background_texture(), ArcsinDeg(), atan2(), AvoidPlayerAI_ChaseInit(), basic_ai_chase_init(), basic_ai_check_player_dist(), btl_main_menu_draw(), calculate_line_segment_intersection(), calculate_segment_intersection(), check_conversation_trigger(), clamp_angle(), CleftAI_CanSeePlayer(), collision_main_above(), collision_main_lateral(), create_shading_palette(), Entity_BoardedFloor_update_fragments(), entity_BombableRock_update_fragments(), entity_Chest_idle(), entity_shattering_idle(), entity_Signpost_idle(), entity_Tweester_has_reached_target(), entity_WoodenCrate_update_fragments(), FlyingAI_LosePlayer(), FlyingAI_Wander(), FlyingNoAttackAI_12(), get_clamped_angle_diff(), GuardAI_ChaseInit(), HoppingAI_Chase(), HoppingAI_Hop(), MagikoopaAI_CanShootSpell(), MeleeHitbox_CanSeePlayer(), npc_do_player_collision(), npc_find_closest(), npc_find_closest_simple(), npc_follow_npc(), npc_get_render_yaw(), npc_raycast_down(), npc_raycast_down_around(), npc_raycast_down_sides(), npc_test_move_complex_with_slipping(), npc_test_move_simple_with_slipping(), npc_test_move_simple_without_slipping(), npc_test_move_taller_with_slipping(), npc_try_apply_gravity(), npc_try_snap_to_ground(), partner_do_player_collision(), partner_flying_follow_player(), partner_flying_update_motion(), partner_get_out(), partner_move_to_goal(), partner_walking_follow_player(), partner_walking_update_motion(), PatrolAI_ChaseInit(), phys_is_on_sloped_ground(), phys_should_player_be_sliding(), player_check_collision_below(), player_raycast_below(), player_update_sprite(), ProjectileHitbox_GetUsableProjectileID(), red_tree_orbit_listener(), SentinelAI_ChaseInit(), SentinelAI_Descend(), sfx_compute_spatialized_sound_params_with_depth(), test_player_entity_aabb(), update_camera_from_controller(), update_camera_interp_pos(), update_encounters_neutral(), and update_unused_lead_amt().
filemenu_cleanup()
void filemenu_cleanup (void)
Referenced by state_step_exit_file_select(), and state_step_exit_language_select().
filemenu_get_exit_mode()
s32 filemenu_get_exit_mode (void)
Referenced by filemenu_cleanup(), state_init_exit_file_select(), state_step_exit_file_select(), and state_step_exit_language_select().
filemenu_get_menu_message()
u8 * filemenu_get_menu_message (s32 idx)
Referenced by filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), filemenu_draw_contents_file_title(), filemenu_draw_contents_option_center(), filemenu_draw_contents_option_left(), filemenu_draw_contents_option_right(), filemenu_draw_contents_title(), filemenu_info_draw_message_contents(), filemenu_yesno_draw_options_contents(), and filemenu_yesno_draw_prompt_contents().
filemenu_init()
void filemenu_init (s32 mode)
Referenced by state_step_file_select(), and state_step_language_select().
filemenu_set_cursor_alpha()
void filemenu_set_cursor_alpha (s32 arg0)
Referenced by filemenu_info_draw_message_contents().
filemenu_set_cursor_goal_pos()
void filemenu_set_cursor_goal_pos (s32 windowIndex, s32 posX, s32 posY)
Referenced by filemenu_draw_contents_choose_name(), filemenu_draw_contents_file_title(), filemenu_draw_contents_option_center(), filemenu_draw_contents_option_left(), filemenu_draw_contents_option_right(), filemenu_yesno_draw_options_contents(), and func_filemenu_8024D710().
filemenu_set_selected()
void filemenu_set_selected (MenuPanel * menu, s32 col, s32 row)
Referenced by filemenu_choose_name_handle_input(), filemenu_info_handle_input(), filemenu_init(), filemenu_main_handle_input(), and filemenu_yesno_handle_input().
filemenu_update()
void filemenu_update (void)
Referenced by state_step_file_select(), and state_step_language_select().
find_item()
s32 find_item (s32 itemID)
Returns
the index of the given item in the player's inventory, or -1 if not found
Referenced by btl_state_update_defeat().
fio_init_flash()
void fio_init_flash (void)
Referenced by load_engine_data().
force_disable_actor_blur()
void force_disable_actor_blur (Actor * actor)
Referenced by force_disable_partner_blur().
force_disable_player_blur()
void force_disable_player_blur (void)
force_disable_player_blur_immediately()
void force_disable_player_blur_immediately (void)
free_entity_model_by_index()
void free_entity_model_by_index (s32 idx)
Referenced by _delete_shadow(), btl_bonk_update(), delete_entity(), delete_entity_and_unload_data(), free_entity_model_by_ref(), and virtual_entity_delete_by_index().
free_worker()
void free_worker (s32 idx)
Referenced by popup_menu_update().
func_80027088()
void func_80027088 (s32)
func_80028838()
void func_80028838 (void)
Referenced by load_engine_data().
func_8002ACDC()
s32 func_8002ACDC (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
func_80045AC0()
void func_80045AC0 (void)
Referenced by clear_encounter_status(), and init_encounter_status().
func_8005AF84()
void func_8005AF84 (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
func_800E01DC()
void func_800E01DC (void)
func_800E06C0()
void func_800E06C0 (s32 arg0)
Referenced by update_triggers().
func_800E06D8()
s32 func_800E06D8 (void)
Referenced by should_continue_pulse_stone().
func_800E4AD8()
void func_800E4AD8 (s32 arg0)
func_800E5520()
void func_800E5520 (void)
Referenced by player_reset_data().
func_800EF300()
void func_800EF300 (void)
Referenced by action_update_use_spinning_flower(), entity_CymbalPlant_idle(), and func_802BC050_E2E980().
func_800EF314()
void func_800EF314 (void)
func_800EF3D4()
void func_800EF3D4 (s32 arg0)
Referenced by check_for_interactables(), entity_HiddenPanel_idle(), interact_inspect_dismiss(), update_encounters_conversation(), and update_encounters_neutral().
func_800EF3E4()
void func_800EF3E4 (void)
Referenced by entity_Chest_idle().
func_800EF43C()
void func_800EF43C (void)
func_800F0C9C()
void func_800F0C9C (void)
Referenced by render_player_model().
func_80138188()
void func_80138188 (void)
Referenced by load_demo_battle(), and load_map_by_IDs().
func_80138198()
void func_80138198 (void)
Referenced by step_game_loop().
func_8013A4D0()
void func_8013A4D0 (void)
Referenced by spr_update_player_raster_cache().
func_801491E4()
void func_801491E4 (Matrix4f mtx, s32 arg1, s32 arg2, s32 arg3, s32 arg4, s32 alpha)
Referenced by appendGfx_item_entity(), and render_item_entities().
func_8014A964()
s32 func_8014A964 (s32 playerIndex, s32 songID, s32 variation, s32 fadeInTime, s16 arg4, s16 arg5)
func_8014AD40()
s32 func_8014AD40 (void)
func_8023E104()
void func_8023E104 (void)
Referenced by btl_state_update_run_away().
func_8023E11C()
void func_8023E11C (void)
Referenced by btl_state_update_run_away().
func_80255FD8()
void func_80255FD8 (void)
Referenced by btl_render_actors().
func_80263230()
s32 func_80263230 (Actor * actor, Actor * targetActor)
Referenced by btl_state_update_first_strike(), and dispatch_damage_event_actor().
func_80266970()
void func_80266970 (Actor * target)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
func_802C39F8()
Evt * func_802C39F8 (Evt * parentScript, Bytecode * nextLine, s32 newState)
Referenced by evt_handle_child_thread().
func_802C3EE4()
void func_802C3EE4 (void)
Referenced by gfx_draw_frame().
game_input_to_move_vector()
void game_input_to_move_vector (f32 * x, f32 * y)
Referenced by action_update_use_spinning_flower().
general_heap_create()
HeapNode * general_heap_create (void)
Referenced by general_heap_create_obfuscated(), load_demo_battle(), load_engine_data(), state_init_file_select(), state_init_language_select(), state_init_logos(), state_init_title_screen(), state_step_demo(), state_step_intro(), state_step_startup(), and state_step_title_screen().
general_heap_free()
s32 general_heap_free (void * data)
Referenced by _update_message(), btl_state_update_normal_start(), draw_msg(), func_8013A4D0(), get_msg_properties(), heap_free(), imgfx_update_cache_impl(), init_hud_element_list(), load_battle_hit_asset(), load_map_bg(), load_map_by_IDs(), load_map_hit_asset(), pause_partners_load_portrait(), remove_all_effects(), remove_effect(), restore_map_collision_data(), set_message_text_var(), spr_load_sprite(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), state_step_unpause(), update_effects(), update_model_animator(), and update_model_animator_with_transform().
general_heap_malloc()
void * general_heap_malloc (s32 size)
get_actor()
Actor * get_actor (s32 actorID)
Referenced by btl_state_draw_select_target(), btl_state_update_first_strike(), btl_state_update_next_enemy(), btl_state_update_partner_striking_first(), btl_state_update_select_target(), calc_enemy_damage_target(), calc_enemy_test_target(), calc_item_check_hit(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_partner_test_enemy(), calc_player_damage_enemy(), calc_player_test_enemy(), clear_part_flag_bits(), create_part_shadow(), create_target_list(), GetKoopaBrosWithState(), remove_part_shadow(), set_actor_anim(), set_actor_anim_rate(), set_actor_current_position(), set_actor_home_position(), set_actor_yaw(), set_goal_pos_to_part(), set_part_absolute_position(), set_part_flag_bits(), set_part_goal_to_actor_part(), and set_part_yaw().
get_actor_part()
ActorPart * get_actor_part (Actor * actor, s32 partID)
Referenced by btl_state_draw_select_target(), btl_state_update_select_target(), calc_enemy_damage_target(), calc_enemy_test_target(), calc_item_check_hit(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_partner_test_enemy(), calc_player_damage_enemy(), calc_player_test_enemy(), clear_part_flag_bits(), create_part_shadow(), create_target_list(), remove_part_shadow(), set_actor_anim(), set_actor_anim_rate(), set_goal_pos_to_part(), set_part_absolute_position(), set_part_flag_bits(), set_part_goal_to_actor_part(), and set_part_yaw().
get_area_byte()
s32 get_area_byte (s32 index)
Referenced by evt_get_float_variable(), evt_get_variable(), evt_handle_print_debug_var(), and evt_set_variable().
get_area_flag()
s32 get_area_flag (s32 index)
Referenced by evt_get_variable(), evt_handle_print_debug_var(), evt_set_variable(), and update_triggers().
get_asset_offset()
s32 get_asset_offset (char * assetName, s32 * compressedSize)
Referenced by btl_state_update_normal_start(), load_map_by_IDs(), and state_step_end_battle().
get_clamped_angle_diff()
f32 get_clamped_angle_diff (f32 a, f32 b)
Referenced by AvoidPlayerAI_ChaseInit(), basic_ai_chase_init(), check_conversation_trigger(), CleftAI_CanSeePlayer(), FlyingAI_LosePlayer(), FlyingNoAttackAI_12(), GuardAI_ChaseInit(), MagikoopaAI_CanShootSpell(), MeleeHitbox_CanSeePlayer(), npc_do_player_collision(), npc_follow_npc(), npc_get_render_yaw(), partner_flying_follow_player(), partner_force_player_flip_done(), partner_walking_follow_player(), PatrolAI_ChaseInit(), player_get_side_angle(), player_update_sprite(), ProjectileHitbox_GetUsableProjectileID(), red_tree_orbit_listener(), SentinelAI_ChaseInit(), set_npc_yaw(), test_item_player_collision(), update_camera_unused_radial(), update_encounters_neutral(), and update_unused_lead_amt().
get_collider_center()
void get_collider_center (s32 colliderID, f32 * x, f32 * y, f32 * z)
get_collider_flags()
s32 get_collider_flags (s32 colliderID)
Referenced by action_update_hit_fire(), action_update_knockback(), action_update_sliding(), action_update_spin_jump(), action_update_step_down(), action_update_tornado_jump(), can_dismount(), check_input_jump(), func_80262130(), handle_floor_behavior(), partner_get_out(), partner_walking_follow_player(), phys_adjust_cam_on_landing(), phys_main_collision_below(), player_handle_floor_collider_type(), spawn_surface_effects(), try_player_footstep_sounds(), update_current_floor(), update_riding_physics(), and update_riding_physics().
get_current_partner_id()
s8 get_current_partner_id (void)
Referenced by collision_main_lateral(), and entity_try_partner_interaction_trigger().
get_defense()
s32 get_defense (Actor * actor, s32 * defenseTable, s32 elementFlags)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
get_entity_by_index()
Entity * get_entity_by_index (s32 index)
Referenced by action_hammer_end_swing(), action_update_landing_on_switch(), action_update_spin_jump(), action_update_tornado_jump(), action_update_use_spinning_flower(), check_for_interactables(), check_input_jump(), delete_entity(), delete_entity_and_unload_data(), entity_ArrowSign_setupGfx(), entity_base_block_setupGfx(), entity_BlueWarpPipe_setupGfx(), Entity_BoardedFloor_setupGfx(), entity_BombableRock_setupGfx(), entity_Chest_setupGfx(), entity_HeartBlock_create_child_entity(), entity_HeartBlockContent__reset(), entity_HeartBlockContent__setupGfx(), entity_HeartBlockContent_anim_idle(), entity_HeartBlockContent_set_initial_pos(), entity_HiddenPanel_setupGfx(), entity_HitItemBlock_show_inactive(), entity_ItemBlock_replace_with_inactive(), entity_ItemBlock_setupGfx(), entity_MulticoinBlock_spawn_coin(), entity_Padlock_setupGfx(), entity_PinkFlower_idle(), entity_PinkFlower_init(), entity_PinkFlowerLight_idle(), entity_PinkFlowerLight_setupGfx(), entity_SaveBlock_setupGfx(), entity_shattering_setupGfx(), entity_SpinningFlower_setupGfx(), entity_StarBoxLauncher_setupGfx(), entity_SuperBlockContent_attach_to_parent(), entity_SuperBlockContent_setupGfx(), entity_try_partner_interaction_trigger(), entity_Tweester_render_face(), entity_Tweester_render_inner_whirl(), entity_Tweester_render_outer_whirl(), entity_Tweester_setupGfx(), entity_upgrade_block_check_if_inactive(), entity_upgrade_block_hide_content(), entity_WoodenCrate_setupGfx(), func_802BC050_E2E980(), get_entity_type(), interact_inspect_update(), npc_find_standing_on_entity(), phys_player_land(), player_raycast_down(), player_raycast_general(), player_raycast_up_corner(), render_entities(), test_ray_entities(), and update_entities().
get_entity_type()
u32 get_entity_type (s32 arg0)
Referenced by action_hammer_test_swing_collision(), action_update_spin_jump(), action_update_tornado_jump(), can_dismount(), check_for_interactables(), collision_main_above(), entity_block_handle_collision(), entity_block_hit_animate_scale(), entity_block_hit_init_scale(), entity_breakable_block_create_shattering_entity(), entity_HitItemBlock_play_anim(), entity_ItemBlock_check_if_inactive(), entity_ItemBlock_replace_with_inactive(), entity_raycast_down(), entity_shattering_block_init(), entity_StarBoxLauncher_check_launch(), entity_try_partner_interaction_trigger(), func_800E06D8(), func_800EA4B0(), load_simple_entity_data(), load_split_entity_data(), phys_main_collision_below(), phys_player_land(), and should_continue_inspect().
get_fortress_key_count()
s32 get_fortress_key_count (void)
get_game_mode()
s16 get_game_mode (void)
Referenced by filemenu_set_cursor_goal_pos(), pause_set_cursor_pos(), pause_set_cursor_pos_immediate(), and render_curtains().
get_global_byte()
s32 get_global_byte (s32 index)
Referenced by evt_get_float_variable(), evt_get_variable(), evt_handle_print_debug_var(), evt_set_variable(), is_actor_health_bar_visible(), is_actortype_health_bar_visible(), load_tattle_flags(), and save_tattle_flags().
get_global_flag()
s32 get_global_flag (s32 index)
Referenced by entity_BlueWarpPipe_check_if_active(), entity_Chest_check_opened(), entity_HeartBlock_show_tutorial_message(), entity_HiddenPanel_set_ispy_notification(), entity_init_BlueWarpPipe(), entity_ItemBlock_check_if_inactive(), entity_MulticoinBlock_check_if_inactive(), entity_SaveBlock_show_tutorial_message(), entity_upgrade_block_check_if_inactive(), entity_WoodenCrate_shatter(), evt_get_variable(), evt_handle_print_debug_var(), evt_set_variable(), make_item_entity(), spawn_drops(), and update_triggers().
get_item_count()
s32 get_item_count (void)
Referenced by get_item_empty_count().
get_item_empty_count()
s32 get_item_empty_count (void)
get_item_entity()
ItemEntity * get_item_entity (s32 itemEntityIndex)
Referenced by draw_shop_items(), entity_base_block_idle(), entity_HiddenPanel_flip_over(), entity_HiddenPanel_is_item_on_top(), and update_item_entity_pickup().
get_lava_reset_pos()
s32 get_lava_reset_pos (f32 * x, f32 * y, f32 * z)
Referenced by action_update_hit_lava().
get_map_IDs_by_name()
s32 get_map_IDs_by_name (const char * mapName, s16 * areaID, s16 * mapID)
Referenced by btl_state_update_end_battle(), goto_map(), and state_step_demo().
get_model_center_and_size()
void get_model_center_and_size (u16 modelID, f32 * centerX, f32 * centerY, f32 * centerZ, f32 * sizeX, f32 * sizeY, f32 * sizeZ)
get_model_from_list_index()
struct Model * get_model_from_list_index (s32 listIndex)
Referenced by animator_node_update_model_transform(), clone_model(), disable_transform_group(), enable_transform_group(), get_model_center_and_size(), get_model_list_index_from_tree_index(), gfx_build_inside_crystal_ball(), gfx_build_water(), hide_foreground_models(), hide_foreground_models_unchecked(), is_model_center_visible(), mdl_draw_hidden_panel_surface(), mdl_make_local_vertex_copy(), mdl_project_tex_coords(), render_transform_group_node(), set_spotlight_pos_scale(), show_foreground_models(), show_foreground_models_unchecked(), UnkModelFunc001(), and update_collider_transform().
get_model_list_index_from_tree_index()
s32 get_model_list_index_from_tree_index (s32 treeIndex)
Referenced by animator_node_update_model_transform(), clone_model(), get_model_center_and_size(), gfx_build_inside_crystal_ball(), gfx_build_water(), hide_foreground_models(), hide_foreground_models_unchecked(), is_model_center_visible(), mdl_draw_hidden_panel_surface(), mdl_make_local_vertex_copy(), mdl_make_transform_group(), mdl_project_tex_coords(), set_spotlight_pos_scale(), show_foreground_models(), show_foreground_models_unchecked(), and UnkModelFunc001().
get_msg_lines()
s32 get_msg_lines (s32 messageID)
Referenced by btl_menu_moves_show_error(), btl_menu_strats_show_error(), btl_message_popup_draw_content(), btl_show_message_popup(), btl_state_update_celebration(), btl_submenu_moves_update(), btl_update_strats_menu(), draw_content_cant_increase_popup(), draw_content_pickup_item_header(), draw_merlee_message(), draw_merlee_message_string(), func_800F4C1C(), func_801363A0(), popup_menu_update(), and UpdateIntroMessages().
get_msg_properties()
void get_msg_properties (s32 msgID, s32 * height, s32 * width, s32 * maxLineChars, s32 * numLines, s32 * maxLinesPerPage, s32 * arg6, u16 charset)
Referenced by _msg_get_printer_for_msg(), credits_load_message(), credits_update_line(), draw_msg(), get_msg_lines(), get_msg_width(), pause_handle_input(), and pause_tutorial_draw_contents().
get_msg_width()
s32 get_msg_width (s32 msgID, u16 charset)
get_player_data()
PlayerData * get_player_data (void)
Referenced by ClubbaNappingAI_Sleep(), pause_partners_draw_movelist(), pause_partners_draw_title(), pause_partners_handle_input(), pause_partners_init(), pause_spirits_draw_contents(), pause_spirits_draw_title(), pause_spirits_handle_input(), pause_spirits_init(), and pause_spirits_update().
get_player_normal_pitch()
f32 get_player_normal_pitch (void)
Referenced by phys_main_collision_below(), player_raycast_down(), and update_riding_physics().
get_player_normal_yaw()
f32 get_player_normal_yaw (void)
Referenced by player_raycast_down(), and update_player_shadow().
get_screen_coords()
void get_screen_coords (s32 camID, f32 x, f32 y, f32 z, s32 * screenX, s32 * screenY, s32 * screenZ)
Referenced by _show_message(), btl_draw_enemy_health_bars(), btl_state_draw_select_target(), draw_all_status_icons(), draw_encounters_pre_battle(), render_player_model(), render_shrunk_player(), sfx_compute_spatialized_sound_params_full(), sfx_compute_spatialized_sound_params_ignore_depth(), sfx_compute_spatialized_sound_params_with_depth(), test_reflection_worker_render_floor(), test_reflection_worker_render_wall(), update_cameras(), update_encounters_neutral(), worker_draw_example_player(), worker_draw_fake_player(), worker_reflect_player_floor(), worker_reflect_player_wall(), and worker_render_player_reflection().
get_screen_overlay_params()
void get_screen_overlay_params (s32 layer, u8 * type, f32 * zoom)
Referenced by appendGfx_image_strips(), btl_update(), create_target_list(), UpdateIntroMessages(), and worker_draw_story_graphics().
get_script_by_id()
Evt * get_script_by_id (s32 id)
Referenced by update_encounters_neutral(), and worker_update_phonograph_hud().
get_script_by_index()
Evt * get_script_by_index (s32 index)
Referenced by dispatch_event_actor(), and func_802C73B8().
get_shadow_by_index()
Shadow * get_shadow_by_index (s32 index)
Referenced by _delete_shadow(), calculate_camera_yinterp_rate(), create_entity_shadow(), create_shadow_type(), delete_entity(), delete_entity_and_unload_data(), disable_npc_shadow(), disable_player_shadow(), enable_npc_shadow(), enable_player_shadow(), end_outta_sight_cleanup(), entity_base_block_update_slow_sinking(), entity_HitItemBlock_hide(), entity_HitItemBlock_show_inactive(), entity_ItemBlock_replace_with_inactive(), hide_item_entity(), make_item_entity(), make_item_entity_at_player(), npc_get_collider_below(), phys_is_on_sloped_ground(), phys_should_player_be_sliding(), render_shadows(), reveal_item_entity(), spawn_drops(), test_reflection_worker_render_floor(), test_reflection_worker_render_wall(), update_entity_shadow_position(), update_item_entities(), update_nonplayer_actor_shadow(), update_npcs(), update_player_actor_shadow(), update_player_shadow(), update_shadows(), worker_reflect_player_floor(), worker_reflect_player_wall(), and worker_render_player_reflection().
get_stored_count()
s32 get_stored_count (void)
Referenced by get_stored_empty_count().
get_stored_empty_count()
s32 get_stored_empty_count (void)
get_time_freeze_mode()
s32 get_time_freeze_mode (void)
Referenced by entity_Tweester_idle(), state_step_battle(), test_item_entity_position(), and test_item_player_collision().
get_transform_group()
struct ModelTransformGroup * get_transform_group (s32 index)
Referenced by disable_transform_group(), enable_transform_group(), and get_transform_group_index().
get_transform_group_index()
s32 get_transform_group_index (s32 modelID)
Referenced by disable_transform_group(), and enable_transform_group().
get_trigger_by_id()
Trigger * get_trigger_by_id (s32 triggerID)
Referenced by get_trigger_tattle().
get_worker()
Worker * get_worker (s32 idx)
Referenced by partner_reset_data().
get_world_fog_color()
void get_world_fog_color (s32 * r, s32 * g, s32 * b, s32 * a)
Referenced by appendGfx_background_texture(), and tattle_cam_pre_render().
get_xz_dist_to_player()
f32 get_xz_dist_to_player (f32 x, f32 z)
Referenced by action_update_hit_fire(), action_update_hit_lava(), action_update_knockback(), entity_BlueWarpPipe_set_player_move_to_center(), and entity_HiddenPanel_idle().
gfx_task_background()
void gfx_task_background (void)
Referenced by gfxRetrace_Callback().
gravity_use_fall_parms()
void gravity_use_fall_parms (void)
Referenced by action_update_state_23(), entity_TriggerBlock_disable_player_input(), handle_jumping_land_on_switch(), phys_main_collision_below(), and phys_update_jump().
handle_floor_behavior()
void handle_floor_behavior (void)
Referenced by player_jump(), and update_player().
has_valid_conversation_npc()
s32 has_valid_conversation_npc (void)
Referenced by check_for_conversation_prompt(), and should_continue_pulse_stone().
heap_free()
s32 heap_free (void * ptr)
Referenced by _delete_shadow(), ALT_clear_hud_element_cache(), btl_bonk_update(), btl_delete_actor(), btl_delete_player_actor(), btl_popup_messages_delete(), delete_entity(), delete_entity_and_unload_data(), delete_model_animator(), delete_model_animator_node(), delete_trigger(), disable_npc_blur(), dispose_merlee_message(), free_animator_nodes(), free_entity_model_by_index(), free_npc(), free_npc_by_index(), free_popup(), free_worker(), func_80045B10(), func_802C3C10(), get_asset_offset(), hud_element_free(), hud_element_free_transform(), imgfx_mesh_anim_update(), imgfx_update(), imgfx_update_cache_impl(), kill_enemy(), kill_script(), load_asset_by_name(), load_battle_hit_asset(), load_map_hit_asset(), load_path_data(), remove_item_entity_by_index(), remove_item_entity_by_reference(), and state_step_logos().
heap_malloc()
void * heap_malloc (s32 size)
Referenced by add_anim_node(), ALT_clear_hud_element_cache(), ALT_load_entity_model(), clear_virtual_entity_list(), clone_model(), create_actor(), create_encounters(), create_entity(), create_mesh_animator(), create_model_animator(), create_npc_impl(), create_shadow_from_data(), create_trigger(), create_worker_backUI(), create_worker_frontUI(), create_worker_scene(), enable_npc_blur(), evt_handle_allocate_array(), func_802C39F8(), get_asset_offset(), hud_element_create(), imgfx_load_anim(), imgfx_mesh_anim_update(), imgfx_update(), load_asset_by_name(), load_battle_hit_asset(), load_entity_model(), load_map_hit_asset(), load_partner_actor(), load_path_data(), load_player_actor(), make_item_entity(), make_item_entity_at_player(), mdl_create_model(), mdl_make_local_vertex_copy(), mdl_make_transform_group(), msg_copy_to_print_buffer(), npc_follow_init(), reset_model_animators(), show_immune_bonk(), start_child_script(), start_script(), start_script_in_group(), state_init_logos(), state_init_title_screen(), and update_item_entity_collectable().
hide_actor_health_bar()
void hide_actor_health_bar (Actor * target)
hide_coin_counter()
void hide_coin_counter (void)
hide_coin_counter_immediately()
void hide_coin_counter_immediately (void)
hide_foreground_models()
void hide_foreground_models (void)
hide_foreground_models_unchecked()
void hide_foreground_models_unchecked (void)
Referenced by tattle_cam_pre_render().
hide_popup_menu()
void hide_popup_menu (void)
Referenced by btl_state_update_partner_menu(), btl_state_update_player_menu(), check_input_open_menus(), shop_update_item_select_popup(), and update_item_entity_pickup().
imgfx_appendGfx_component()
s32 imgfx_appendGfx_component (s32 idx, ImgFXTexture * ifxImg, u32 flagBits, Matrix4f mtx)
Referenced by appendGfx_entity_model(), appendGfx_FallingSprite(), appendGfx_interact_prompt(), appendGfx_ispy_icon(), appendGfx_pulse_stone_icon(), appendGfx_ritual_card(), appendGfx_speech_bubble(), appendGfx_sticker(), CharAnim_FadeIn_0(), CharAnim_FadeIn_1(), CharAnim_FadeIn_2(), CharAnim_FadeIn_3(), CharAnim_FadeIn_4(), CharAnim_FadeOut_0(), CharAnim_FadeOut_1(), CharAnim_FadeOut_2(), CharAnim_HoldClearImgFX(), draw_coin_sparkles(), draw_entity_model_E(), func_80241610_97F0E0(), func_80241610_990DF0(), func_80241610_993D40(), gfx_build_knocked_down_player(), render_hud_element(), and spr_appendGfx_component().
imgfx_get_free_instances()
s32 imgfx_get_free_instances (s32 count)
Referenced by hud_element_create_transform_A(), spr_load_npc_sprite(), and spr_update_player_sprite().
imgfx_release_instance()
void imgfx_release_instance (u32 idx)
Referenced by hud_element_free_transform(), imgfx_release_instance_chain(), and spr_free_sprite().
imgfx_update()
void imgfx_update (u32 idx, ImgFXType type, s32 imgfxArg1, s32 imgfxArg2, s32 imgfxArg3, s32 imgfxArg4, s32 flags)
Referenced by appendGfx_interact_prompt(), appendGfx_ispy_icon(), appendGfx_speech_bubble(), appendGfx_sticker(), CharAnim_FadeIn_0(), CharAnim_FadeIn_1(), CharAnim_FadeIn_2(), CharAnim_FadeIn_3(), CharAnim_FadeIn_4(), CharAnim_FadeOut_0(), CharAnim_FadeOut_1(), CharAnim_FadeOut_2(), CharAnim_HoldClearImgFX(), func_80241610_97F0E0(), func_80241610_990DF0(), render_hud_element(), set_npc_imgfx_comp(), and set_player_imgfx_comp().
imgfx_update_cache()
void imgfx_update_cache (void)
Referenced by state_drawUI_world().
increment_status_bar_disabled()
void increment_status_bar_disabled (void)
Referenced by btl_state_update_first_strike(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), initialize_battle(), and update_item_entity_pickup().
inflict_partner_ko()
s32 inflict_partner_ko (Actor * target, s32 statusTypeKey, s32 duration)
Referenced by calc_enemy_damage_target().
inflict_status()
s32 inflict_status (Actor * target, s32 statusTypeKey, s32 duration)
Referenced by calc_item_damage_enemy(), dispatch_damage_event_partner(), inflict_partner_ko(), inflict_status_set_duration(), and try_inflict_status().
inflict_status_set_duration()
s32 inflict_status_set_duration (Actor * actor, s32 statusTypeKey, s32 statusDurationKey, s32 duration)
Referenced by btl_state_update_normal_start(), and try_inflict_status().
init_encounters_ui()
void init_encounters_ui (void)
Referenced by draw_encounter_ui().
init_enter_world_shared()
void init_enter_world_shared (void)
Referenced by state_init_enter_demo(), and state_init_enter_world().
init_entity_data()
void init_entity_data (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
init_entity_models()
void init_entity_models (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
init_item_entity_list()
void init_item_entity_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
init_model_animators()
void init_model_animators (void)
Referenced by init_script_list().
init_script_list()
void init_script_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
init_sprite_shading_data()
void init_sprite_shading_data (void)
Referenced by clear_sprite_shading_data(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
init_trigger_list()
void init_trigger_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
init_virtual_entity_list()
void init_virtual_entity_list (void)
Referenced by init_script_list().
initialize_battle()
void initialize_battle (void)
Bug
? why just 16
Referenced by state_step_battle().
initialize_collision()
void initialize_collision (void)
Referenced by load_map_by_IDs(), state_step_demo(), state_step_end_battle(), state_step_exit_language_select(), state_step_intro(), state_step_startup(), and state_step_unpause().
initialize_curtains()
void initialize_curtains (void)
Referenced by load_engine_data(), and state_step_startup().
initialize_status_bar()
void initialize_status_bar (void)
Referenced by load_demo_battle(), and load_map_by_IDs().
int_to_string()
char * int_to_string (s32 integer, char * dest, s32 base)
Referenced by draw_number(), and set_message_int_var().
integer_log()
s32 integer_log (s32 number, u32 base)
Referenced by draw_adjustable_tiled_image(), and imgfx_appendGfx_mesh_strip().
integrate_gravity()
f32 integrate_gravity (void)
Referenced by action_update_hit_fire(), action_update_knockback(), action_update_spin_jump(), action_update_step_up(), action_update_tornado_jump(), handle_jumping_land_on_switch(), phys_update_jump(), and player_fall_distance().
interact_inspect_setup()
void interact_inspect_setup (void)
Referenced by check_for_interactables().
interact_speech_setup()
void interact_speech_setup (void)
Referenced by check_for_conversation_prompt().
is_ability_active()
s32 is_ability_active (s32 arg0)
Referenced by action_command_init_status(), action_hammer_play_hit_fx(), action_update_run(), action_update_spin(), action_update_walk(), adjust_action_command_difficulty(), appendGfx_player_actor(), btl_menu_strats_draw_content(), btl_state_update_begin_player_turn(), btl_state_update_begin_turn(), btl_state_update_celebration(), btl_state_update_end_player_turn(), btl_state_update_first_strike(), btl_state_update_normal_start(), btl_state_update_partner_menu(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_select_target(), calc_enemy_damage_target(), calc_player_damage_enemy(), check_block_input(), check_input_spin(), enforce_hpfp_limits(), entity_HiddenPanel_set_ispy_notification(), get_coin_drop_amount(), inflict_status(), is_actor_health_bar_visible(), is_actortype_health_bar_visible(), load_player_actor(), player_team_is_ability_active(), show_first_strike_message(), spawn_drops(), update_encounters_neutral(), update_encounters_pre_battle(), and update_locomotion_state().
is_actor_health_bar_visible()
s32 is_actor_health_bar_visible (Actor * actor)
Referenced by btl_draw_enemy_health_bars().
is_another_trigger_bound()
s32 is_another_trigger_bound (Trigger * trigger, EvtScript * script)
Referenced by evt_trigger_on_activate_exec_script().
is_block_on_ground()
s32 is_block_on_ground (Entity * block)
Referenced by entity_base_block_idle(), entity_ItemBlock_replace_with_inactive(), and entity_shattering_init_pieces().
is_debug_init()
void is_debug_init (void)
Referenced by boot_main().
is_debug_panic()
void is_debug_panic (const char * message, char * file, s32 line)
is_merlee_message_done()
s32 is_merlee_message_done (void)
is_partner_ability_active()
s32 is_partner_ability_active (s32 ability)
Referenced by player_team_is_ability_active().
is_picking_up_item()
s32 is_picking_up_item (void)
Returns
TRUE when "you got X" popup is on-screen
Referenced by can_open_world_menu(), check_conversation_trigger(), check_input_open_menus(), check_input_status_bar(), entity_Tweester_idle(), func_802BB000_E2D930(), and update_encounters_neutral().
is_player_dismounted()
s32 is_player_dismounted (void)
Referenced by get_overriding_player_anim(), and update_item_entity_pickup().
is_point_outside_territory()
b32 is_point_outside_territory (s32 shape, f32 pointX, f32 pointY, f32 centerX, f32 centerY, f32 sizeX, f32 sizeZ)
Referenced by basic_ai_check_player_dist(), basic_ai_wander(), CleftAI_Tackle(), FlyingAI_Wander(), FlyingAI_WanderInit(), FlyingMagikoopaAI_15(), HoppingAI_HopInit(), LakituAI_Wander(), and PiranhaPlantAI_10().
is_point_visible()
b32 is_point_visible (f32 x, f32 y, f32 z, s32 depthQueryID, f32 * screenX, f32 * screenY)
is_starting_conversation()
s32 is_starting_conversation (void)
Referenced by partner_use_ability(), phys_update_jump(), should_continue_pulse_stone(), and test_item_entity_position().
is_status_bar_visible()
s32 is_status_bar_visible (void)
Referenced by check_input_status_bar().
is_world_fog_enabled()
s32 is_world_fog_enabled (void)
Referenced by appendGfx_background_texture(), and tattle_cam_pre_render().
ispy_notification_setup()
void ispy_notification_setup (void)
Referenced by check_for_ispy().
iterate_models()
void iterate_models (void)
Referenced by state_step_battle(), and state_step_world().
kill_all_scripts()
void kill_all_scripts (void)
Referenced by btl_state_update_end_battle(), and btl_state_update_end_demo_battle().
kill_script()
void kill_script (Evt * instanceToKill)
Referenced by evt_handle_end_child_thread(), evt_handle_end_thread(), evt_handle_return(), func_802C3C10(), kill_all_scripts(), kill_script(), and kill_script_by_ID().
kill_script_by_ID()
void kill_script_by_ID (s32 id)
Referenced by _use_partner_ability(), bind_enemy_ai(), bind_enemy_aux(), bind_enemy_interact(), btl_cam_use_preset_impl(), btl_delete_actor(), btl_delete_player_actor(), btl_state_update_celebration(), dispatch_event_actor(), dispatch_event_partner(), dispatch_event_partner_continue_turn(), dispatch_event_player(), dispatch_event_player_continue_turn(), evt_handle_kill(), func_80048E34(), kill_enemy(), partner_handle_after_battle(), partner_handle_before_battle(), partner_kill_ability_script(), start_rumble_type(), and update_encounters_pre_battle().
length2D()
f32 length2D (f32 x, f32 y)
Referenced by ArcsinDeg().
load_asset_by_name()
void * load_asset_by_name (const char * assetName, u32 * decompressedSize)
Referenced by btl_state_update_normal_start(), load_battle_hit_asset(), load_map_bg(), load_map_by_IDs(), load_map_hit_asset(), pause_partners_load_portrait(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
load_battle()
void load_battle (s32 battleID)
Referenced by load_demo_battle(), and update_encounters_pre_battle().
load_battle_hit_asset()
void load_battle_hit_asset (const char * hitName)
Referenced by btl_state_update_normal_start().
load_battle_section()
void load_battle_section (void)
Referenced by state_step_battle().
load_data_for_models()
void load_data_for_models (struct ModelNode * model, s32 romOffset, s32 size)
Referenced by btl_state_update_normal_start(), and load_map_by_IDs().
load_font()
void load_font (s32 font)
Referenced by clear_printers().
load_font_data()
void load_font_data (Addr offset, u16 size, void * dest)
Referenced by filemenu_draw_char(), load_font(), and msg_draw_char().
load_map_bg()
void load_map_bg (char * optAssetName)
Referenced by btl_state_update_normal_start(), load_map_by_IDs(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
load_map_by_IDs()
void load_map_by_IDs (s16 areaID, s16 mapID, s16 loadType)
Referenced by state_step_change_map(), state_step_enter_world(), state_step_game_over(), and state_step_intro().
load_map_script_lib()
void load_map_script_lib (void)
Referenced by load_map_by_IDs(), state_step_end_battle(), and state_step_unpause().
load_mesh_animator_tree()
void load_mesh_animator_tree (s32 index, StaticAnimatorNode ** tree)
Referenced by load_split_entity_data().
load_model_animator_tree()
void load_model_animator_tree (s32 index, StaticAnimatorNode ** tree)
Referenced by create_shadow_from_data(), load_mesh_animator_tree(), and load_split_entity_data().
load_obfuscation_shims()
void load_obfuscation_shims (void)
Referenced by boot_main(), load_map_by_IDs(), and state_step_battle().
load_partner_actor()
void load_partner_actor (void)
Referenced by btl_state_update_change_partner(), and btl_state_update_normal_start().
load_player_actor()
void load_player_actor (void)
Referenced by btl_state_update_normal_start().
load_tattle_flags()
void load_tattle_flags (s32 actorType)
lookup_defense()
s32 lookup_defense (s32 * defenseTable, s32 elementKey)
Referenced by get_defense().
lookup_status_chance()
s32 lookup_status_chance (s32 * statusTable, s32 statusKey)
Referenced by inflict_status_set_duration(), and try_inflict_status().
make_item_entity()
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 angle, s32 pickupVar)
Referenced by entity_ItemBlock_spawn_item(), entity_TrumpetPlant_spawn_coin(), entity_WoodenCrate_shatter(), make_item_entity_delayed(), make_item_entity_nodelay(), and spawn_drops().
make_item_entity_at_player()
s32 make_item_entity_at_player (s32 itemID, s32 arg1, s32 pickupMsgFlags)
make_item_entity_delayed()
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
Referenced by update_item_entity_pickup().
make_item_entity_nodelay()
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupVar)
Referenced by entity_GiantChest_give_equipment(), entity_HiddenPanel_flip_over(), entity_MulticoinBlock_spawn_coin(), entity_Munchlesia_init(), and musical_hill_orbit_listener().
mdl_calculate_model_sizes()
void mdl_calculate_model_sizes (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
mdl_draw_hidden_panel_surface()
void mdl_draw_hidden_panel_surface (Gfx ** arg0, u16 treeIndex)
mdl_get_copied_gfx()
Gfx * mdl_get_copied_gfx (s32 copyIndex)
Referenced by build_gfx_aurora(), build_gfx_blue_stars(), build_gfx_blue_stars(), build_gfx_green_stars(), build_gfx_green_stars(), build_gfx_pink_stars(), build_gfx_pink_stars(), build_gfx_star(), build_gfx_yellow_stars(), build_gfx_yellow_stars(), func_8024033C_A1B43C(), func_8024060C_A1B70C(), gfx_build_bubble_flower(), gfx_build_club_64(), gfx_build_rowf_rug_with_ripples(), make_tongue_gfx(), setup_gfx_bridge(), unkAngleFunc002(), and unkAngleFunc003().
mdl_get_copied_vertices()
void mdl_get_copied_vertices (s32 copyIndex, Vtx ** firstVertex, Vtx ** copiedVertices, s32 * numCopied)
Referenced by build_gfx_aurora(), build_gfx_blue_stars(), build_gfx_blue_stars(), build_gfx_green_stars(), build_gfx_green_stars(), build_gfx_pink_stars(), build_gfx_pink_stars(), build_gfx_star(), build_gfx_yellow_stars(), build_gfx_yellow_stars(), func_8024033C_A1B43C(), func_8024060C_A1B70C(), gfx_build_bubble_flower(), gfx_build_club_64(), gfx_build_rowf_rug_with_ripples(), make_tongue_gfx(), setup_gfx_bridge(), unkAngleFunc002(), and unkAngleFunc003().
mdl_get_next_texture_address()
void * mdl_get_next_texture_address (s32 size)
Referenced by draw_box().
mdl_get_shroud_tint_params()
void mdl_get_shroud_tint_params (u8 * r, u8 * g, u8 * b, u8 * a)
mdl_group_set_custom_gfx()
void mdl_group_set_custom_gfx (u16 groupModelID, s32 customGfxIndex, s32 tintType, b32 invertSelection)
mdl_group_set_visibility()
void mdl_group_set_visibility (u16 treeIndex, s32 flags, s32 mode)
mdl_load_all_textures()
void mdl_load_all_textures (struct ModelNode * model, s32 romOffset, s32 size)
Referenced by load_data_for_models(), state_init_file_select(), state_init_language_select(), and state_step_end_battle().
mdl_make_transform_group()
void mdl_make_transform_group (u16 modelID)
mdl_reset_transform_flags()
void mdl_reset_transform_flags (void)
Referenced by step_game_loop().
mdl_set_all_tint_type()
void mdl_set_all_tint_type (s32 tintType)
Referenced by btl_state_update_celebration().
mdl_update_transform_matrices()
void mdl_update_transform_matrices (void)
Referenced by render_frame().
mem_clear()
void mem_clear (void * data, s32 numBytes)
move_player()
void move_player (s32 duration, f32 heading, f32 speed)
Referenced by entity_BlueWarpPipe_set_player_move_to_center().
msg_get_printer_for_msg()
MessagePrintState * msg_get_printer_for_msg (s32 msgID, s32 * a1)
Referenced by _show_message(), entity_HeartBlock_show_tutorial_message(), entity_SaveBlock_show_choice_message(), entity_SaveBlock_show_tutorial_message(), popup_menu_update(), and update_item_entity_pickup().
msg_printer_load_msg()
s32 msg_printer_load_msg (s32 msgID, MessagePrintState * printer)
Referenced by _show_message(), and entity_SaveBlock_show_result_message().
msg_printer_set_origin_pos()
void msg_printer_set_origin_pos (MessagePrintState * msgPrintState, s32 x, s32 y)
Referenced by _show_message(), popup_menu_update(), and update_item_entity_pickup().
npc_follow_init()
void npc_follow_init (Npc * npc, s32 targetNpcID, FollowAnims * anims, f32 walkSpeed, f32 runSpeed, s32 idleRadius, s32 walkRadius)
npc_follow_npc()
void npc_follow_npc (Npc * npc)
npc_raycast_down_around()
b32 npc_raycast_down_around (s32 ignoreFlags, f32 * posX, f32 * posY, f32 * posZ, f32 * hitDepth, f32 yaw, f32 radius)
Referenced by func_80262130(), npc_try_apply_gravity(), npc_try_snap_to_ground(), partner_flying_follow_player(), partner_flying_update_motion(), partner_get_out(), partner_move_to_goal(), partner_walking_follow_player(), test_for_water_level(), update_item_entity_collectable(), and update_riding_physics().
npc_raycast_down_sides()
b32 npc_raycast_down_sides (s32 ignoreFlags, f32 * posX, f32 * posY, f32 * posZ, f32 * hitDepth)
npc_raycast_up()
b32 npc_raycast_up (s32 ignoreFlags, f32 * startX, f32 * startY, f32 * startZ, f32 * hitDepth)
Referenced by partner_flying_update_motion(), and update_item_entity_collectable().
npc_raycast_up_corners()
HitID npc_raycast_up_corners (s32 ignoreFlags, f32 * posX, f32 * posY, f32 * posZ, f32 * hitDepth, f32 yaw, f32 radius)
Referenced by update_riding_physics().
npc_test_move_complex_with_slipping()
s32 npc_test_move_complex_with_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 height, f32 radius)
Referenced by apply_riding_static_collisions(), npc_do_world_collision(), update_item_entity_collectable(), and update_riding_physics().
npc_test_move_simple_with_slipping()
b32 npc_test_move_simple_with_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 height, f32 radius)
Referenced by ai_check_fwd_collisions(), apply_riding_static_collisions(), basic_ai_chase(), basic_ai_check_player_dist(), basic_ai_loiter(), basic_ai_wander(), CleftAI_Tackle(), HoppingAI_Chase(), HoppingAI_Hop(), HoppingAI_HopInit(), npc_do_world_collision(), PiranhaPlantAI_10(), UnkNpcAIFunc12(), and update_item_entity_collectable().
npc_test_move_simple_without_slipping()
b32 npc_test_move_simple_without_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 height, f32 radius)
Referenced by AvoidPlayerAI_ChaseInit().
npc_test_move_taller_with_slipping()
b32 npc_test_move_taller_with_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 height, f32 radius)
Referenced by apply_riding_static_collisions(), blast_affect_entities(), check_conversation_trigger(), Entity_BoardedFloor_update_fragments(), entity_BombableRock_update_fragments(), entity_shattering_idle(), entity_WoodenCrate_update_fragments(), FlyingMagikoopaAI_15(), npc_do_world_collision(), partner_flying_follow_player(), test_first_strike(), test_first_strike(), update_encounters_neutral(), update_riding_physics(), and update_riding_physics().
npc_update_npc_tracking()
void npc_update_npc_tracking (Npc * npc)
nuBoot()
void nuBoot (void)
open_status_bar_quickly()
void open_status_bar_quickly (void)
Referenced by create_standard_popup_menu(), and shop_open_item_select_popup().
open_status_bar_slowly()
void open_status_bar_slowly (void)
Referenced by action_update_hit_fire(), action_update_hit_lava(), and check_input_status_bar().
parent_collider_to_model()
void parent_collider_to_model (s16 colliderID, s16 modelIndex)
Referenced by restore_map_collision_data().
part_flash_off()
void part_flash_off (b32 isNpcSprite, ActorPart * part, s32 yaw, b32 isReflection)
Referenced by update_part_flash().
part_flash_on()
void part_flash_on (b32 isNpcSprite, ActorPart * part, s32 yaw, b32 isReflection)
Referenced by update_part_flash().
part_glow_off()
void part_glow_off (s32 isNpcSprite, ActorPart * part, s32 yaw, b32 arg3)
Referenced by update_part_glow().
partner_can_open_world_menus()
s32 partner_can_open_world_menus (void)
Referenced by can_open_world_menu(), and should_cancel_open_world_menu().
partner_clear_player_tracking()
void partner_clear_player_tracking (Npc * partner)
Referenced by enable_partner_ai(), end_outta_sight_cleanup(), partner_flying_follow_player(), partner_get_out(), partner_walking_follow_player(), post_battle(), post_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), try_cancel_tweester(), try_cancel_tweester(), try_cancel_tweester(), try_cancel_tweester(), try_cancel_tweester(), try_cancel_tweester(), try_cancel_tweester(), try_cancel_tweester(), and try_cancel_tweester().
partner_disable_input()
void partner_disable_input (void)
Referenced by check_input_open_menus(), SentinelAI_Descend(), start_battle(), update_encounters_neutral(), and update_item_entity_pickup().
partner_flying_enable()
void partner_flying_enable (Npc * partner, s32 val)
Referenced by enable_partner_ai().
partner_flying_update_motion()
void partner_flying_update_motion (Npc * partner)
partner_flying_update_player_tracking()
void partner_flying_update_player_tracking (Npc * partner)
partner_get_enter_map_script()
EvtScript * partner_get_enter_map_script (void)
partner_handle_before_battle()
void partner_handle_before_battle (void)
Referenced by update_encounters_pre_battle().
partner_init_after_battle()
void partner_init_after_battle (s32 arg0)
Referenced by state_step_end_battle().
partner_initialize_data()
void partner_initialize_data (void)
Referenced by state_step_startup().
partner_is_flying()
s32 partner_is_flying (void)
partner_kill_ability_script()
void partner_kill_ability_script (void)
partner_reset_data()
void partner_reset_data (void)
Referenced by load_map_by_IDs().
partner_reset_tether_distance()
void partner_reset_tether_distance (void)
Referenced by check_for_interactables(), and interact_inspect_dismiss().
partner_set_goal_pos()
void partner_set_goal_pos (s32 x, s32 z)
Referenced by func_800EF414().
partner_set_tether_distance()
void partner_set_tether_distance (f32 dist)
partner_test_enemy_collision()
s32 partner_test_enemy_collision (Npc * enemy)
Referenced by update_encounters_neutral().
partner_walking_enable()
void partner_walking_enable (Npc * partner, s32 val)
Referenced by enable_partner_ai().
partner_walking_update_motion()
void partner_walking_update_motion (Npc * partner)
partner_walking_update_player_tracking()
void partner_walking_update_player_tracking (Npc * partner)
PatrolAI_LoiterInit()
void PatrolAI_LoiterInit (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
pause_cleanup()
void pause_cleanup (void)
Referenced by state_step_unpause().
pause_handle_input()
void pause_handle_input (s32 buttonsPressed, s32 buttonsHeld)
Referenced by state_step_pause().
pause_init()
void pause_init (void)
Referenced by state_step_pause().
peach_check_for_parasol_input()
void peach_check_for_parasol_input (void)
Referenced by phys_peach_update().
peach_make_disguise_npc()
Npc * peach_make_disguise_npc (s32 peachDisguise)
Referenced by action_update_parasol(), and peach_check_for_parasol_input().
peach_set_disguise_anim()
void peach_set_disguise_anim (AnimID anim)
Referenced by action_update_idle_peach(), action_update_talk(), func_802B6198_E24768(), func_802B6550_E23C30(), and get_overriding_player_anim().
peach_sync_disguise_npc()
void peach_sync_disguise_npc (void)
Referenced by action_update_parasol(), and phys_peach_update().
phys_adjust_cam_on_landing()
s32 phys_adjust_cam_on_landing (void)
Referenced by action_update_hit_lava(), action_update_jump(), action_update_land(), action_update_peach_land(), action_update_peach_step_down_land(), action_update_step_down_land(), action_update_step_up(), action_update_use_spinning_flower(), entity_CymbalPlant_idle(), phys_main_collision_below(), and phys_player_land().
phys_can_player_interact()
s32 phys_can_player_interact (void)
Referenced by check_for_interactables(), func_800E06D8(), should_collider_allow_interact(), should_continue_inspect(), and update_triggers().
phys_get_spin_history()
f32 phys_get_spin_history (s32 lag, s32 * x, s32 * y, s32 * z)
Referenced by appendGfx_player_spin(), and appendGfx_reflect_player_floor_fancy().
phys_init_integrator_for_current_state()
void phys_init_integrator_for_current_state (void)
Referenced by initialize_jump().
phys_main_collision_below()
void phys_main_collision_below (void)
Referenced by phys_update_standard().
phys_peach_update()
void phys_peach_update (void)
Referenced by phys_update_action_state().
phys_player_land()
void phys_player_land (void)
Referenced by action_update_tornado_jump(), handle_jumping_land_on_switch(), and player_handle_floor_collider_type().
phys_reset_spin_history()
void phys_reset_spin_history (void)
Referenced by reset_player_status().
phys_should_player_be_sliding()
s32 phys_should_player_be_sliding (void)
Referenced by check_input_jump(), and phys_main_collision_below().
phys_update_action_state()
void phys_update_action_state (void)
Referenced by phys_update_lava_reset(), phys_update_standard(), and update_player().
phys_update_falling()
void phys_update_falling (void)
Referenced by phys_update_standard().
phys_update_interact_collider()
void phys_update_interact_collider (void)
Referenced by action_update_idle(), action_update_idle_peach(), action_update_peach_step_down(), action_update_run(), action_update_spin(), action_update_step_down(), and action_update_walk().
phys_update_jump()
void phys_update_jump (void)
Referenced by phys_update_standard().
play_ambient_sounds()
s32 play_ambient_sounds (s32 fadeInTime, s32 fadeOutTime)
play_model_animation()
void play_model_animation (s32 index, s16 * animPos)
Referenced by entity_BellbellPlant_idle(), entity_CymbalPlant_idle(), entity_HitItemBlock_play_anim(), entity_PinkFlower_idle(), entity_ScriptSpring_idle(), entity_SimpleSpring_idle(), entity_TrumpetPlant_idle(), and func_802BC0B8_E2E9E8().
play_movement_dust_effects()
void play_movement_dust_effects (s32 var0, f32 xPos, f32 yPos, f32 zPos, f32 angleDeg)
player_check_collision_below()
f32 player_check_collision_below (f32 offset, s32 * colliderID)
Referenced by action_update_hit_fire(), action_update_hit_lava(), action_update_knockback(), action_update_sliding(), action_update_spin_jump(), action_update_step_up(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), handle_jumping_land_on_switch(), phys_update_falling(), and player_jump().
player_fall_distance()
f32 player_fall_distance (void)
Referenced by action_update_hit_fire(), action_update_hit_lava(), action_update_knockback(), action_update_sliding(), action_update_spin_jump(), handle_jumping_land_on_switch(), and phys_update_falling().
player_get_side_angle()
f32 player_get_side_angle (void)
Referenced by action_hammer_end_swing(), action_hammer_play_hit_fx(), action_hammer_test_swing_collision(), entity_StarBoxLauncher_check_launch(), parasol_get_npc(), partner_flying_follow_player(), and partner_walking_follow_player().
player_handle_floor_collider_type()
void player_handle_floor_collider_type (s32 colliderID)
Referenced by handle_jumping_land_on_switch(), phys_update_falling(), and player_jump().
player_input_to_move_vector()
void player_input_to_move_vector (f32 * angle, f32 * magnitude)
Referenced by action_update_idle(), action_update_idle_peach(), action_update_land(), action_update_peach_land(), action_update_peach_step_down_land(), action_update_pushing_block(), action_update_run(), action_update_spin(), action_update_step_down_land(), action_update_walk(), collision_main_above(), collision_main_lateral(), and phys_player_land().
player_raycast_below_cam_relative()
HitID player_raycast_below_cam_relative (PlayerStatus * playerStatus, f32 * outX, f32 * outY, f32 * outZ, f32 * outLength, f32 * hitRx, f32 * hitRz, f32 * hitDirX, f32 * hitDirZ)
Referenced by action_update_sliding(), action_update_state_23(), action_update_step_down(), can_dismount(), phys_main_collision_below(), player_check_collision_below(), test_dismount_height(), test_mounting_height_adjustment(), update_current_floor(), and update_riding_physics().
player_raycast_up_corners()
HitID player_raycast_up_corners (PlayerStatus * player, f32 * posX, f32 * posY, f32 * posZ, f32 * hitDepth, f32 yaw)
Referenced by collision_main_above().
player_render_interact_prompts()
void player_render_interact_prompts (void)
Referenced by gfx_draw_frame().
player_reset_data()
void player_reset_data (void)
Referenced by load_map_by_IDs().
player_team_is_ability_active()
s32 player_team_is_ability_active (Actor * actor, s32 ability)
Referenced by appendGfx_player_actor(), btl_init_menu_boots(), btl_init_menu_hammer(), btl_init_menu_partner(), btl_state_update_change_partner(), btl_state_update_partner_menu(), btl_state_update_player_menu(), calc_enemy_damage_target(), calc_enemy_test_target(), calc_partner_test_enemy(), calc_player_damage_enemy(), calc_player_test_enemy(), and deduct_current_move_fp().
player_test_lateral_overlap()
s32 player_test_lateral_overlap (s32 mode, PlayerStatus * playerStatus, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw)
Referenced by action_hammer_end_swing(), action_hammer_test_swing_collision(), check_for_treadmill_overlaps(), collision_check_player_intersecting_world(), collision_check_player_overlaps(), collision_lava_reset_check_additional_overlaps(), collision_main_lateral(), func_800E4404(), and peach_disguise_check_overlaps().
player_test_move_with_slipping()
HitID player_test_move_with_slipping (PlayerStatus * playerStatus, f32 * posX, f32 * posY, f32 * posZ, f32 speed, f32 heading)
Referenced by action_update_sliding(), collision_main_lateral(), and phys_check_interactable_collision().
player_test_move_without_slipping()
HitID player_test_move_without_slipping (PlayerStatus * playerStatus, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, s32 * hasClimbableStep)
Referenced by collision_lateral_peach().
poll_rumble()
void poll_rumble (void)
Referenced by load_engine_data().
pulse_stone_notification_setup()
void pulse_stone_notification_setup (void)
Referenced by check_for_pulse_stone().
queue_render_task()
RenderTask * queue_render_task (RenderTask * task)
rand_float()
f32 rand_float (void)
Referenced by entity_shattering_init_pieces().
rand_int()
s32 rand_int (s32 max)
recover_fp()
s32 recover_fp (s32 amt)
Referenced by entity_HeartBlockContent__anim_heal().
recover_hp()
s32 recover_hp (s32 amt)
Referenced by entity_HeartBlockContent__anim_heal().
remove_actor_decoration()
void remove_actor_decoration (Actor * actor, s32 decorationIndex)
Referenced by btl_delete_actor(), and btl_delete_player_actor().
remove_all_effects()
void remove_all_effects (void)
Referenced by btl_state_update_end_battle(), and btl_state_update_end_demo_battle().
remove_all_status_icons()
void remove_all_status_icons (s32 iconID)
Referenced by btl_delete_actor(), and btl_delete_player_actor().
remove_consumable()
void remove_consumable (void)
remove_item_entity_by_index()
void remove_item_entity_by_index (s32 index)
Referenced by entity_GiantChest_await_got_item().
remove_part_decor_bowser_aura()
void remove_part_decor_bowser_aura (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_fiery_trail()
void remove_part_decor_fiery_trail (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_golden_flames()
void remove_part_decor_golden_flames (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_none()
void remove_part_decor_none (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_radiating_stars()
void remove_part_decor_radiating_stars (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_red_flames()
void remove_part_decor_red_flames (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_seeing_stars()
void remove_part_decor_seeing_stars (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_smoky_trail()
void remove_part_decor_smoky_trail (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_sparkles()
void remove_part_decor_sparkles (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_steam()
void remove_part_decor_steam (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_sweat()
void remove_part_decor_sweat (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decor_whirlwind()
void remove_part_decor_whirlwind (ActorPart * part, s32 idx)
Referenced by _remove_part_decoration().
remove_part_decoration()
void remove_part_decoration (ActorPart * part, s32 decorationIndex)
Referenced by remove_actor_decoration().
remove_part_shadow()
void remove_part_shadow (s32 actorID, s32 partID)
remove_player_buffs()
void remove_player_buffs (s32 buffs)
remove_status_chill_out()
void remove_status_chill_out (s32 iconID)
Referenced by btl_state_update_begin_player_turn(), and remove_all_status_icons().
remove_status_debuff()
void remove_status_debuff (s32 iconID)
Referenced by btl_state_update_9(), btl_state_update_begin_player_turn(), btl_state_update_defeat(), create_status_debuff(), and remove_all_status_icons().
remove_status_icon_boost_hammer()
void remove_status_icon_boost_hammer (s32 iconID)
Referenced by appendGfx_player_actor(), and remove_all_status_icons().
remove_status_icon_boost_jump()
void remove_status_icon_boost_jump (s32 iconID)
Referenced by appendGfx_player_actor(), and remove_all_status_icons().
remove_status_icon_boost_partner()
void remove_status_icon_boost_partner (s32 iconID)
Referenced by remove_all_status_icons().
remove_status_icon_danger()
void remove_status_icon_danger (s32 iconID)
Referenced by appendGfx_player_actor(), and remove_all_status_icons().
remove_status_icon_peril()
void remove_status_icon_peril (s32 iconID)
Referenced by appendGfx_player_actor(), and remove_all_status_icons().
remove_status_icon_surprise()
void remove_status_icon_surprise (s32 iconID)
Referenced by remove_all_status_icons().
remove_status_static()
void remove_status_static (s32 iconID)
Referenced by btl_state_update_9(), btl_state_update_begin_player_turn(), calc_item_damage_enemy(), create_status_static(), remove_all_status_icons(), and remove_player_buffs().
remove_status_transparent()
void remove_status_transparent (s32 iconID)
Referenced by btl_state_update_9(), btl_state_update_begin_player_turn(), calc_item_damage_enemy(), create_status_transparent(), remove_all_status_icons(), and remove_player_buffs().
render_curtains()
void render_curtains (void)
Referenced by gfx_draw_frame().
render_effects_scene()
void render_effects_scene (void)
Referenced by render_frame().
render_effects_UI()
void render_effects_UI (void)
Referenced by gfx_draw_frame().
render_entities()
void render_entities (void)
Referenced by render_frame().
render_frame()
void render_frame (s32 flag)
Referenced by appendGfx_title_screen(), and gfx_draw_frame().
render_messages()
void render_messages (void)
Referenced by gfx_draw_frame().
render_player()
void render_player (void)
Referenced by render_frame().
render_player_model()
void render_player_model (void)
Referenced by render_player().
render_screen_overlay_backUI()
void render_screen_overlay_backUI (void)
Referenced by gfx_draw_frame().
render_screen_overlay_frontUI()
void render_screen_overlay_frontUI (void)
Referenced by gfx_draw_frame().
render_window_root()
void render_window_root (void)
Referenced by gfx_draw_frame().
render_with_adjusted_palettes()
s32 render_with_adjusted_palettes (s32 isNpcSprite, ActorPart * part, s32 yaw, Matrix4f mtx, s32 skipAnimation)
Referenced by appendGfx_npc_actor(), appendGfx_npc_actor_reflection(), appendGfx_player_actor(), appendGfx_player_actor_blur(), and appendGfx_player_actor_reflection().
render_workers_backUI()
void render_workers_backUI (void)
Referenced by gfx_draw_frame().
render_workers_frontUI()
void render_workers_frontUI (void)
Referenced by gfx_draw_frame().
render_workers_scene()
void render_workers_scene (void)
Referenced by render_frame().
replace_window_update()
void replace_window_update (s32 idx, s8 arg1, WindowUpdateFunc pendingFunc)
Referenced by pause_tabs_handle_input().
reset_actor_blur()
void reset_actor_blur (Actor * actor)
Referenced by reset_partner_blur().
reset_actor_turn_info()
void reset_actor_turn_info (void)
Referenced by btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), btl_state_update_switch_to_partner(), and btl_state_update_switch_to_player().
reset_all_actor_sounds()
void reset_all_actor_sounds (Actor * actor)
Referenced by btl_state_update_enemy_move(), btl_state_update_partner_move(), and btl_state_update_player_move().
reset_ambient_sounds()
void reset_ambient_sounds (void)
Referenced by load_engine_data().
reset_background_settings()
void reset_background_settings (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
reset_battle_status()
void reset_battle_status (void)
Referenced by ALT_reset_battle_status(), load_demo_battle(), load_map_by_IDs(), state_step_demo(), state_step_intro(), and state_step_startup().
reset_model_animators()
void reset_model_animators (void)
Referenced by clear_script_list().
reset_player_blur()
void reset_player_blur (void)
reset_player_status()
void reset_player_status (void)
Referenced by player_reset_data().
reset_status_bar()
void reset_status_bar (void)
Referenced by state_step_battle(), state_step_language_select(), and state_step_pause().
resolve_npc()
Npc * resolve_npc (Evt * script, s32 npcIdOrPtr)
Referenced by _npc_jump_to(), and _show_message().
restart_script()
Evt * restart_script (Evt * script)
Referenced by btl_cam_move(), and evt_handle_jump().
restore_map_collision_data()
void restore_map_collision_data (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
resume_all_group()
s32 resume_all_group (s32 groupFlags)
Referenced by create_encounters(), evt_handle_resume_all(), set_time_freeze_mode(), start_battle(), update_encounters_conversation(), update_encounters_post_battle(), and update_item_entity_collectable().
resume_all_script()
s32 resume_all_script (s32 id)
Referenced by evt_handle_resume(), partner_resume_ability_script(), update_encounters_conversation(), and update_encounters_post_battle().
resume_group_others()
void resume_group_others (Evt * script, s32 groupFlags)
Referenced by evt_handle_resume_others().
round()
s32 round (f32 x)
Referenced by atan2().
save_tattle_flags()
void save_tattle_flags (s32 actorType)
set_action_state()
void set_action_state (s32 actionState)
Referenced by action_hammer_end_swing(), action_update_first_strike(), action_update_hit_fire(), action_update_hit_lava(), action_update_idle(), action_update_idle_peach(), action_update_knockback(), action_update_land(), action_update_launch(), action_update_parasol(), action_update_peach_land(), action_update_peach_step_down_land(), action_update_pushing_block(), action_update_raise_arms(), action_update_run(), action_update_sliding(), action_update_spin(), action_update_spin_jump(), action_update_state_23(), action_update_step_down(), action_update_step_up(), action_update_step_up_peach(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), action_update_walk(), check_input_hammer(), check_input_jump(), check_input_midair_jump(), check_input_open_menus(), check_input_spin(), check_player_action_debug(), collision_lateral_peach(), end_outta_sight_cleanup(), entity_CymbalPlant_idle(), entity_ScriptSpring_idle(), entity_SimpleSpring_set_jump_params(), entity_TriggerBlock_disable_player_input(), entity_Tweester_idle(), entity_WoodenCrate_idle(), func_802BB000_E2D930(), func_802BC274_E2EBA4(), func_802BC3A0_E2ECD0(), handle_jumping_launch(), move_player(), peach_check_for_parasol_input(), peach_force_disguise_action(), phys_main_collision_below(), phys_peach_update(), phys_player_land(), phys_update_action_state(), phys_update_jump(), player_handle_floor_collider_type(), post_battle(), post_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), pre_battle(), reset_player_status(), start_bounce_a(), start_bounce_b(), start_falling(), update_encounters_conversation(), update_encounters_neutral(), update_encounters_post_battle(), update_item_entity_pickup(), and update_locomotion_state().
set_actor_anim()
void set_actor_anim (s32 actorID, s32 partID, AnimID animID)
Referenced by btl_set_player_idle_anims(), btl_state_update_celebration(), btl_state_update_partner_menu(), btl_state_update_peach_menu(), btl_state_update_player_menu(), and btl_state_update_twink_menu().
set_actor_anim_by_ref()
void set_actor_anim_by_ref (Actor * actor, ActorPart * part, AnimID anim)
set_actor_anim_rate()
void set_actor_anim_rate (s32 actorID, s32 partID, f32 rate)
set_actor_flash_mode()
void set_actor_flash_mode (Actor * actor, s32 arg1)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_player_damage_enemy(), dispatch_damage_event_actor(), dispatch_damage_event_partner(), and dispatch_damage_event_player().
set_actor_glow_pal()
void set_actor_glow_pal (Actor * actor, s32 arg1)
Referenced by appendGfx_npc_actor(), appendGfx_player_actor(), and btl_delete_actor().
set_actor_yaw()
void set_actor_yaw (s32 actorID, s32 yaw)
set_area_byte()
s8 set_area_byte (s32 index, s32 value)
Referenced by evt_set_variable().
set_area_flag()
s32 set_area_flag (s32 index)
Referenced by entity_base_switch_start_bound_script(), and evt_set_variable().
set_aux_pan_u()
void set_aux_pan_u (s32 texPannerID, s32 value)
set_aux_pan_v()
void set_aux_pan_v (s32 texPannerID, s32 value)
set_background()
void set_background (BackgroundHeader * bg)
Referenced by btl_state_update_normal_start(), load_map_by_IDs(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
set_background_size()
void set_background_size (s16 startX, s16 startY, s16 sizeX, s16 sizeY)
Referenced by load_map_by_IDs(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
set_battle_stage()
void set_battle_stage (s32 stageID)
Referenced by load_demo_battle(), and update_encounters_pre_battle().
set_cam_viewport()
void set_cam_viewport (s16 id, s16 x, s16 y, s16 width, s16 height)
Referenced by hud_element_setup_cam(), initialize_next_camera(), load_map_by_IDs(), state_init_file_select(), state_init_language_select(), state_init_logos(), state_init_title_screen(), and state_step_demo().
set_curtain_draw_callback()
void set_curtain_draw_callback (void(*)(void) callback)
Referenced by state_step_intro(), and state_step_logos().
set_curtain_fade()
void set_curtain_fade (f32 fade)
Referenced by state_step_logos(), and state_step_title_screen().
set_curtain_fade_goal()
void set_curtain_fade_goal (f32 fade)
Referenced by state_init_intro(), state_step_intro(), and state_step_logos().
set_curtain_scale()
void set_curtain_scale (f32 scale)
Referenced by state_step_logos(), and state_step_title_screen().
set_curtain_scale_goal()
void set_curtain_scale_goal (f32 scale)
Referenced by btl_state_update_normal_start(), state_init_intro(), state_step_exit_file_select(), and state_step_logos().
set_custom_gfx()
void set_custom_gfx (s32 customGfxIndex, Gfx * pre, Gfx * post)
set_entity_commandlist()
void set_entity_commandlist (Entity * entity, s32 * entityScript)
Referenced by entity_block_handle_collision(), entity_Chest_check_opened(), entity_ItemBlock_check_if_inactive(), entity_MulticoinBlock_spawn_coin(), and entity_SaveBlock_wait_for_close_choice().
set_entity_fog_color()
void set_entity_fog_color (s32 r, s32 g, s32 b, s32 a)
set_entity_fog_dist()
void set_entity_fog_dist (s32 start, s32 end)
set_entity_model_flags()
void set_entity_model_flags (s32 idx, s32 newFlags)
Referenced by show_immune_bonk().
set_global_byte()
s8 set_global_byte (s32 index, s32 value)
Referenced by evt_set_variable(), and save_tattle_flags().
set_global_flag()
s32 set_global_flag (s32 index)
Referenced by entity_GiantChest_give_equipment(), entity_HeartBlock_show_tutorial_message(), entity_SaveBlock_show_tutorial_message(), evt_set_variable(), spawn_drops(), update_item_entity_collectable(), and update_item_entity_pickup().
set_goal_pos_to_part()
void set_goal_pos_to_part (ActorState * state, s32 actorID, s32 partID)
Referenced by dispatch_damage_event_partner(), and dispatch_damage_event_player().
set_item_entity_flags()
void set_item_entity_flags (s32 itemEntityIndex, s32 flag)
Referenced by check_for_item_collision().
set_item_entity_position()
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
Referenced by entity_GiantChest_open().
set_main_pan_u()
void set_main_pan_u (s32 texPannerID, s32 value)
set_main_pan_v()
void set_main_pan_v (s32 texPannerID, s32 value)
set_map_change_fade_rate()
void set_map_change_fade_rate (s16 fadeRate)
set_map_transition_effect()
void set_map_transition_effect (ScreenTransition transition)
Referenced by goto_map(), state_init_demo(), state_init_enter_world(), state_init_exit_file_select(), state_init_exit_language_select(), and state_step_demo().
set_max_star_power()
void set_max_star_power (s8 newMax)
set_message_images()
void set_message_images (MessageImageData * images)
set_message_int_var()
void set_message_int_var (s32 value, s32 index)
Referenced by btl_message_popup_draw_content(), btl_show_message_popup(), popup_menu_draw_menu_contents(), shop_owner_buy_dialog(), and shop_owner_continue_speech_with_quantity().
set_message_text_var()
void set_message_text_var (s32 msgID, s32 index)
Referenced by btl_message_popup_draw_content(), btl_show_message_popup(), draw_content_pickup_item_header(), func_801363A0(), shop_owner_buy_dialog(), and shop_owner_continue_speech_with_quantity().
set_npc_animation()
void set_npc_animation (Npc * npc, u32 animID)
Referenced by _show_message().
set_npc_shadow_scale()
void set_npc_shadow_scale (Shadow * shadow, f32 height, f32 npcRadius)
Referenced by update_npcs().
set_part_glow_pal()
void set_part_glow_pal (ActorPart * part, s32 glowState)
Referenced by set_actor_glow_pal().
set_part_pal_adjustment()
void set_part_pal_adjustment (ActorPart * part, s32 palAdjust)
Referenced by set_actor_pal_adjustment().
set_part_yaw()
void set_part_yaw (s32 actorID, s32 partID, s32 value)
set_peach_shadow_scale()
void set_peach_shadow_scale (Shadow * shadow, f32 scale)
Referenced by update_player_shadow().
set_screen_overlay_alpha()
void set_screen_overlay_alpha (s32 layer, f32 alpha)
Referenced by draw_encounters_pre_battle(), and update_exit_map_screen_overlay().
set_screen_overlay_center()
void set_screen_overlay_center (s32 layer, s32 arg1, s32 screenPosX, s32 screenPosY)
Referenced by btl_state_update_end_battle(), draw_encounters_pre_battle(), update_enter_map_screen_overlay(), and update_exit_map_screen_overlay().
set_screen_overlay_center_worldpos()
void set_screen_overlay_center_worldpos (s32 idx, s32 posIdx, s32 x, s32 y, s32 z)
set_screen_overlay_color()
void set_screen_overlay_color (s32 layer, u8 r, u8 g, u8 b)
Referenced by btl_state_draw_end_demo_battle(), btl_state_draw_normal_start(), btl_state_update_end_battle(), btl_state_update_normal_start(), btl_update(), draw_encounters_post_battle(), draw_encounters_pre_battle(), startup_fade_screen_update(), state_init_intro(), state_step_intro(), update_enter_map_screen_overlay(), and update_exit_map_screen_overlay().
set_screen_overlay_params_back()
void set_screen_overlay_params_back (u8 type, f32 zoom)
Referenced by btl_state_update_normal_start(), btl_update(), draw_encounters_pre_battle(), state_init_intro(), state_step_intro(), and update_exit_map_screen_overlay().
set_screen_overlay_params_front()
void set_screen_overlay_params_front (u8 type, f32 zoom)
Referenced by btl_state_draw_celebration(), btl_state_draw_end_battle(), btl_state_draw_end_demo_battle(), btl_state_draw_enemy_striking_first(), btl_state_draw_first_stike(), btl_state_draw_normal_start(), btl_state_draw_partner_striking_first(), btl_state_update_normal_start(), btl_update(), draw_encounters_post_battle(), draw_encounters_pre_battle(), load_demo_battle(), startup_fade_screen_update(), state_init_demo(), state_init_exit_language_select(), state_init_language_select(), state_step_change_map(), state_step_enter_world(), state_step_exit_language_select(), state_step_game_over(), state_step_intro(), state_step_language_select(), update_encounters_post_battle(), update_encounters_pre_battle(), update_enter_map_screen_overlay(), and update_exit_map_screen_overlay().
set_script_flags()
void set_script_flags (Evt * script, s32 flags)
Referenced by set_script_flags(), and update_encounters_neutral().
set_script_group()
void set_script_group (Evt * script, s32 groupFlags)
Referenced by evt_handle_set_group().
set_script_priority()
void set_script_priority (Evt * script, s32 priority)
Referenced by evt_handle_set_priority().
set_script_timescale()
void set_script_timescale (Evt * script, f32 timescale)
Referenced by evt_handle_set_timescale(), and worker_update_phonograph_hud().
set_standard_shadow_scale()
void set_standard_shadow_scale (Shadow * shadow, f32 scale)
Referenced by make_item_entity(), make_item_entity_at_player(), update_item_entities(), update_nonplayer_actor_shadow(), update_player_actor_shadow(), and update_player_shadow().
set_tex_panner()
void set_tex_panner (struct Model * model, s32 texPannerID)
set_time_freeze_mode()
void set_time_freeze_mode (s32 mode)
Time freeze modes: 0: none 1: NPCs move, can't be interacted with 2: NPCs don't move, no partner ability, can't interact, can't use exits 3: NPCs don't more or animate 4: NPCs can move, animations don't update, can use exits.
Referenced by _use_partner_ability(), action_update_parasol(), check_input_open_menus(), entity_HeartBlock_show_tutorial_message(), entity_HeartBlock_wait_for_close_tutorial(), entity_HeartBlockContent__anim_heal(), entity_HeartBlockContent_anim_idle(), entity_HiddenPanel_flip_over(), entity_SaveBlock_pause_game(), entity_SaveBlock_resume_game(), pre_battle(), state_init_file_select(), state_init_language_select(), state_init_pause(), state_step_battle(), state_step_change_map(), state_step_end_battle(), state_step_enter_world(), state_step_exit_file_select(), state_step_exit_language_select(), state_step_unpause(), and update_item_entity_pickup().
set_window_properties()
void set_window_properties (s32 panelID, s32 posX, s32 posY, s32 width, s32 height, u8 priority, void * drawContents, void * drawContentsArg, s8 parent)
Referenced by btl_show_message_popup(), btl_state_update_celebration(), btl_submenu_moves_update(), btl_update_strats_menu(), draw_merlee_message(), func_801363A0(), popup_menu_update(), setup_pause_menu_tab(), and show_coin_counter().
set_window_update()
void set_window_update (s32 panelID, s32 func)
Referenced by btl_show_message_popup(), btl_state_update_celebration(), btl_state_update_partner_menu(), btl_state_update_player_menu(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_strats_menu(), draw_merlee_message(), draw_shop_items(), filemenu_choose_name_handle_input(), filemenu_cleanup(), filemenu_info_handle_input(), filemenu_main_handle_input(), filemenu_main_init(), filemenu_selectlanguage_handle_input(), filemenu_update_change_layout(), filemenu_yesno_handle_input(), func_800F16CC(), func_802A27E4(), func_802A2910(), func_802A2AB8(), func_802A2C58(), func_802A472C(), func_802A47E0(), func_802A48FC(), func_802A4A10(), hide_popup_menu(), pause_cleanup(), pause_init(), pause_partners_handle_input(), pause_partners_init(), pause_tabs_update(), popup_menu_update(), setup_pause_menu_tab(), show_coin_counter(), update_coin_counter(), update_item_entity_pickup(), update_merlee_message(), and worker_update_ingredient_windows().
set_windows_visible()
void set_windows_visible (s32 groupIdx)
Referenced by btl_state_update_end_battle(), btl_state_update_end_demo_battle(), initialize_battle(), state_init_pause(), state_step_exit_file_select(), state_step_exit_language_select(), state_step_file_select(), state_step_language_select(), and state_step_unpause().
set_world_fog_color()
void set_world_fog_color (s32 r, s32 g, s32 b, s32 a)
set_world_fog_dist()
void set_world_fog_dist (s32 start, s32 end)
setup_pause_menu_tab()
void setup_pause_menu_tab (MenuWindowBP * bpArray, s32 arraySize)
Referenced by filemenu_choose_name_init(), filemenu_info_init(), filemenu_init(), filemenu_main_init(), filemenu_selectlanguage_init(), filemenu_yesno_init(), pause_badges_init(), pause_init(), pause_items_init(), pause_map_init(), pause_partners_init(), pause_spirits_init(), pause_stats_init(), and pause_tabs_init().
setup_status_bar_for_battle()
void setup_status_bar_for_battle (void)
Referenced by btl_state_update_normal_start().
shim_battle_heap_create_obfuscated()
void shim_battle_heap_create_obfuscated (void)
Referenced by state_step_battle().
shim_create_audio_system_obfuscated()
void shim_create_audio_system_obfuscated (void)
Referenced by boot_main().
shim_general_heap_create_obfuscated()
void shim_general_heap_create_obfuscated (void)
Referenced by load_map_by_IDs().
shim_load_engine_data_obfuscated()
void shim_load_engine_data_obfuscated (void)
Referenced by boot_main().
shop_open_item_select_popup()
void shop_open_item_select_popup (s32 mode)
should_collider_allow_interact()
s32 should_collider_allow_interact (s32 colliderID)
Returns
TRUE if colliderID is bound to an interaction trigger (press A) and the player can use it.
Referenced by check_for_interactables(), func_800E06D8(), and should_continue_inspect().
show_action_rating()
void show_action_rating (s32 rating, Actor * actor, f32 x, f32 y, f32 z)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
show_actor_health_bar()
void show_actor_health_bar (Actor * target)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
show_coin_counter()
void show_coin_counter (void)
show_damage_fx()
void show_damage_fx (Actor * actor, f32 x, f32 y, f32 z, s32 damage)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_player_damage_enemy(), dispatch_damage_event_actor(), dispatch_damage_event_partner(), and dispatch_damage_event_player().
show_first_strike_message()
void show_first_strike_message (void)
Referenced by draw_first_strike_ui().
show_foreground_models()
void show_foreground_models (void)
show_foreground_models_unchecked()
void show_foreground_models_unchecked (void)
Referenced by tattle_cam_post_render().
show_immune_bonk()
void show_immune_bonk (f32 x, f32 y, f32 z, s32 numStars, s32 arg4, s32 arg5)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
show_merlee_message()
void show_merlee_message (s16 messageIndex, s16 duration)
show_next_damage_popup()
void show_next_damage_popup (f32 x, f32 y, f32 z, s32 damageAmount, s32 angle)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_player_damage_enemy(), dispatch_damage_event_actor(), dispatch_damage_event_partner(), and dispatch_damage_event_player().
show_primary_damage_popup()
void show_primary_damage_popup (f32 x, f32 y, f32 z, s32 attack, s32 a)
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
show_recovery_shimmer()
void show_recovery_shimmer (f32 x, f32 y, f32 z, s32 arg3)
show_start_recovery_shimmer()
void show_start_recovery_shimmer (f32 x, f32 y, f32 z, s32 arg3)
sign()
s32 sign (s32 value)
Referenced by imgfx_mesh_make_wavy(), pause_interp_text_scroll(), pause_interp_vertical_scroll(), pause_partners_update(), pause_tabs_update(), show_immune_bonk(), sign(), and signF().
signF()
f32 signF (f32 val)
Referenced by FireBarAI_Callback().
sin_cos_deg()
void sin_cos_deg (f32 rad, f32 * outSinTheta, f32 * outCosTheta)
sin_cos_rad()
void sin_cos_rad (f32 rad, f32 * outSinTheta, f32 * outCosTheta)
Referenced by action_hammer_end_swing(), action_hammer_test_swing_collision(), action_update_hit_fire(), action_update_hit_lava(), action_update_knockback(), action_update_sliding(), action_update_state_23(), action_update_step_up(), action_update_use_spinning_flower(), action_update_use_tweester(), add_vec2D_polar(), collision_main_lateral(), entity_GiantChest_open(), entity_PinkFlowerLight_setupGfx(), entity_shattering_idle(), npc_test_move_with_slipping(), npc_test_move_without_slipping(), peach_disguise_check_overlaps(), player_raycast_below(), player_test_lateral_overlap(), player_test_move_with_slipping(), player_test_move_without_slipping(), spawn_default_surface_effects(), surface_cloud_behavior(), surface_flowers_behavior(), surface_hedges_behavior(), surface_snow_behavior(), surface_standard_behavior(), surface_water_behavior(), test_ray_collider_horizontal(), test_ray_to_wall_center(), update_riding_physics(), and update_riding_physics().
sin_deg()
f32 sin_deg (f32 x)
sin_rad()
f32 sin_rad (f32 x)
Referenced by action_hammer_play_hit_fx(), action_update_hit_lava(), action_update_parasol(), action_update_spin(), action_update_use_spinning_flower(), action_update_use_tweester(), add_part_decor_steam(), add_tongue_deformation(), add_xz_vec3f(), add_xz_vec3f_copy1(), add_xz_vec3f_copy2(), appendGfx_background_texture(), apply_constraints_to_lead_amount(), btl_state_update_9(), btl_state_update_end_player_turn(), btl_state_update_end_turn(), btl_state_update_partner_menu(), btl_state_update_peach_menu(), btl_state_update_player_menu(), btl_state_update_twink_menu(), btl_state_update_victory(), build_gfx_floor(), build_gfx_thread(), ChompChainAddPolarPos(), ChompChainGetPolarX(), create_camera_leadplayer_matrix(), Entity_BoardedFloor_update_fragments(), entity_BombableRock_update_fragments(), entity_Chest_close(), entity_Chest_open(), entity_GiantChest_give_equipment(), entity_GiantChest_open(), entity_HeartBlockContent__anim_heal(), entity_HiddenPanel_flip_over(), entity_inactive_block_hit_anim(), entity_inactive_block_recoil_anim(), entity_Padlock_push_player(), entity_StarBoxLauncher_launch(), entity_TrumpetPlant_create_effect(), entity_TrumpetPlant_spawn_coin(), entity_Tweester_move(), entity_WoodenCrate_update_fragments(), func_802BC3E4_E2ED14(), gfx_build_bubble_flower(), imgfx_mesh_make_wavy(), interp_lookat_pos(), npc_do_other_npc_collision(), npc_do_player_collision(), npc_move_heading(), npc_raycast_down_around(), npc_raycast_down_sides(), npc_raycast_up_corners(), play_movement_dust_effects(), player_raycast_up_corners(), setup_gfx_fountain_stars(), setup_gfx_fountain_water(), setup_gfx_geyser(), sfx_compute_spatialized_sound_params_ignore_depth(), spawn_cloud_surface_effects(), spawn_flower_surface_effects(), spawn_hedge_surface_effects(), spawn_snow_surface_effects(), spawn_water_surface_effects(), sync_held_position(), unkVtxFunc001(), update_camera_interp_pos(), update_camera_no_interp(), update_camera_unused_ahead(), update_camera_unused_confined(), update_camera_unused_radial(), update_item_entity_collectable(), update_lerp(), update_lerp_battle(), virtual_entity_move_polar(), and worker_update_phonograph_hud().
sort_items()
void sort_items (void)
Bubbles up player inventory items such that all ITEM_NONE values are at the bottom.
Referenced by add_item(), remove_consumable(), and update_item_entity_pickup().
spawn_drops()
void spawn_drops (Enemy * enemy)
star_power_shimmer_draw()
void star_power_shimmer_draw (void)
Referenced by update_status_bar().
star_power_shimmer_init()
void star_power_shimmer_init (void)
Referenced by initialize_status_bar().
star_power_shimmer_start()
void star_power_shimmer_start (s32 emitterIdx, f32 x, f32 y, f32 scale)
Referenced by update_status_bar().
star_power_shimmer_update()
void star_power_shimmer_update (void)
Referenced by update_status_bar().
start_bounce_a()
void start_bounce_a (void)
Referenced by update_encounters_neutral().
start_bounce_b()
void start_bounce_b (void)
start_child_script()
Evt * start_child_script (Evt * parentScript, EvtScript * source, s32 initialState)
Referenced by evt_handle_exec_wait().
start_falling()
void start_falling (void)
Referenced by action_update_use_spinning_flower().
start_rumble()
void start_rumble (s32 freq, s32 nframes)
Referenced by action_hammer_play_hit_fx(), action_update_hit_lava(), action_update_spin_jump(), action_update_tornado_jump(), and entity_CymbalPlant_idle().
start_rumble_type()
void start_rumble_type (u32 type)
start_script()
Evt * start_script (EvtScript * source, s32 priority, s32 initialState)
Referenced by _use_partner_ability(), bind_enemy_ai(), bind_enemy_aux(), bind_enemy_interact(), btl_cam_use_preset_impl(), btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_begin_turn(), btl_state_update_celebration(), btl_state_update_change_partner(), btl_state_update_defeat(), btl_state_update_defend(), btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_end_player_turn(), btl_state_update_end_training_battle(), btl_state_update_end_turn(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_next_enemy(), btl_state_update_normal_start(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_victory(), calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_player_damage_enemy(), create_actor(), create_encounters(), dispatch_event_actor(), dispatch_event_partner(), dispatch_event_partner_continue_turn(), dispatch_event_player(), dispatch_event_player_continue_turn(), entity_Chest_adjust_camera(), entity_Chest_reset_camera(), evt_trigger_on_activate_exec_script(), evt_trigger_on_activate_lock(), FireBarAI_Callback(), func_80048E34(), load_partner_actor(), musical_hill_orbit_listener(), partner_handle_after_battle(), red_tree_orbit_listener(), shake_battle_cam_pitch(), shop_owner_begin_speech(), shop_owner_buy_dialog(), shop_owner_continue_speech(), shop_owner_continue_speech_with_quantity(), shop_owner_end_speech(), shop_owner_reset_speech(), start_battle(), start_rumble_type(), update_encounters_neutral(), update_encounters_post_battle(), update_entities(), and use_consumable().
start_script_in_group()
Evt * start_script_in_group (EvtScript * source, u8 priority, u8 initialState, u8 groupFlags)
Referenced by evt_handle_exec1(), evt_handle_exec1_get_id(), evt_handle_thread(), exec_ShakeCam1(), exec_ShakeCamX(), load_map_by_IDs(), and update_encounters_post_battle().
startup_draw_prim_rect()
void startup_draw_prim_rect (s16 left, s16 top, s16 right, s16 bottom, u16 r, u16 g, u16 b, u16 a)
Referenced by state_drawUI_startup().
startup_draw_prim_rect_COPY()
void startup_draw_prim_rect_COPY (s16 left, s16 top, s16 right, s16 bottom, u16 r, u16 g, u16 b, u16 a)
Referenced by appendGfx_score_display(), draw_mash_meter(), and DrawMashMeter().
startup_fade_screen_in()
b32 startup_fade_screen_in (s16 subtractAlpha)
Referenced by state_step_logos(), and state_step_title_screen().
startup_fade_screen_out()
b32 startup_fade_screen_out (s16 addAlpha)
Referenced by state_step_intro(), state_step_logos(), and state_step_title_screen().
startup_fade_screen_update()
void startup_fade_screen_update (void)
Referenced by state_init_intro(), state_init_logos(), state_init_title_screen(), state_step_demo(), state_step_intro(), state_step_logos(), and state_step_title_screen().
startup_set_fade_screen_alpha()
void startup_set_fade_screen_alpha (s16 alpha)
Referenced by btl_update(), state_init_intro(), state_init_logos(), state_step_demo(), and state_step_logos().
startup_set_fade_screen_color()
void startup_set_fade_screen_color (s16 color)
Referenced by btl_update(), state_init_intro(), state_init_logos(), state_step_demo(), state_step_logos(), and state_step_title_screen().
state_drawUI_battle()
void state_drawUI_battle (void)
state_drawUI_change_map()
void state_drawUI_change_map (void)
state_drawUI_demo()
void state_drawUI_demo (void)
state_drawUI_end_battle()
void state_drawUI_end_battle (void)
state_drawUI_enter_world()
void state_drawUI_enter_world (void)
state_drawUI_exit_file_select()
void state_drawUI_exit_file_select (void)
state_drawUI_exit_language_select()
void state_drawUI_exit_language_select (void)
state_drawUI_file_select()
void state_drawUI_file_select (void)
state_drawUI_game_over()
void state_drawUI_game_over (void)
state_drawUI_intro()
void state_drawUI_intro (void)
state_drawUI_language_select()
void state_drawUI_language_select (void)
state_drawUI_logos()
void state_drawUI_logos (void)
state_drawUI_pause()
void state_drawUI_pause (void)
state_drawUI_startup()
void state_drawUI_startup (void)
state_drawUI_title_screen()
void state_drawUI_title_screen (void)
state_drawUI_unpause()
void state_drawUI_unpause (void)
state_drawUI_world()
void state_drawUI_world (void)
state_init_battle()
void state_init_battle (void)
state_init_change_map()
void state_init_change_map (void)
state_init_demo()
void state_init_demo (void)
state_init_end_battle()
void state_init_end_battle (void)
state_init_enter_demo()
void state_init_enter_demo (void)
state_init_enter_world()
void state_init_enter_world (void)
state_init_exit_file_select()
void state_init_exit_file_select (void)
state_init_exit_language_select()
void state_init_exit_language_select (void)
state_init_file_select()
void state_init_file_select (void)
state_init_game_over()
void state_init_game_over (void)
state_init_intro()
void state_init_intro (void)
Referenced by state_step_intro().
state_init_language_select()
void state_init_language_select (void)
state_init_logos()
void state_init_logos (void)
state_init_pause()
void state_init_pause (void)
state_init_startup()
void state_init_startup (void)
state_init_title_screen()
void state_init_title_screen (void)
state_init_unpause()
void state_init_unpause (void)
state_init_world()
void state_init_world (void)
state_step_battle()
void state_step_battle (void)
state_step_change_map()
void state_step_change_map (void)
state_step_demo()
void state_step_demo (void)
state_step_end_battle()
void state_step_end_battle (void)
state_step_enter_world()
void state_step_enter_world (void)
state_step_exit_file_select()
void state_step_exit_file_select (void)
state_step_exit_language_select()
void state_step_exit_language_select (void)
state_step_file_select()
void state_step_file_select (void)
state_step_game_over()
void state_step_game_over (void)
state_step_intro()
void state_step_intro (void)
state_step_language_select()
void state_step_language_select (void)
state_step_logos()
void state_step_logos (void)
state_step_pause()
void state_step_pause (void)
state_step_startup()
void state_step_startup (void)
state_step_title_screen()
void state_step_title_screen (void)
state_step_unpause()
void state_step_unpause (void)
state_step_world()
void state_step_world (void)
status_bar_always_show_off()
void status_bar_always_show_off (void)
Referenced by draw_shop_items(), and shop_close_item_select_popup().
status_bar_always_show_on()
void status_bar_always_show_on (void)
Referenced by shop_open_item_select_popup().
status_bar_draw_number()
void status_bar_draw_number (s32 iconID, s32 x, s32 y, s32 value, s32 numDigits)
Referenced by update_status_bar().
status_bar_draw_stat()
void status_bar_draw_stat (s32 id, s32 x, s32 y, s32 currentValue, s32 maxValue)
Referenced by update_status_bar().
status_bar_ignore_changes()
void status_bar_ignore_changes (void)
Referenced by create_standard_popup_menu(), and shop_open_item_select_popup().
status_bar_respond_to_changes()
void status_bar_respond_to_changes (void)
Referenced by destroy_popup_menu(), shop_close_item_select_popup(), state_step_exit_language_select(), and state_step_unpause().
status_bar_start_blinking_fp()
void status_bar_start_blinking_fp (void)
Referenced by btl_menu_moves_draw_content(), and update_status_bar().
status_bar_start_blinking_hp()
void status_bar_start_blinking_hp (void)
Referenced by update_status_bar().
status_bar_start_blinking_sp()
void status_bar_start_blinking_sp (void)
status_bar_start_blinking_sp_bars()
void status_bar_start_blinking_sp_bars (s32 numBarsToBlink)
Referenced by btl_menu_moves_draw_content().
status_bar_start_blinking_starpoints()
void status_bar_start_blinking_starpoints (void)
Referenced by btl_state_update_run_away().
status_bar_stop_blinking_fp()
void status_bar_stop_blinking_fp (void)
Referenced by btl_menu_moves_draw_content(), btl_submenu_moves_update(), and update_status_bar().
status_bar_stop_blinking_hp()
void status_bar_stop_blinking_hp (void)
Referenced by update_status_bar().
status_bar_stop_blinking_sp()
void status_bar_stop_blinking_sp (void)
Referenced by btl_menu_moves_draw_content(), and btl_submenu_moves_update().
status_bar_stop_blinking_starpoints()
void status_bar_stop_blinking_starpoints (void)
Referenced by btl_state_update_run_away().
step_game_loop()
void step_game_loop (void)
Referenced by gfxRetrace_Callback().
store_item()
s32 store_item (s32 itemID)
subtract_fortress_keys()
s32 subtract_fortress_keys (s32 amt)
subtract_hp()
void subtract_hp (s32 amt)
Referenced by action_update_hit_fire(), action_update_hit_lava(), and func_802BC274_E2EBA4().
suggest_player_anim_allow_backward()
void suggest_player_anim_allow_backward (AnimID anim)
Referenced by action_update_falling(), action_update_hammer(), action_update_idle(), action_update_idle_peach(), action_update_jump(), action_update_land(), action_update_landing_on_switch(), action_update_parasol(), action_update_peach_falling(), action_update_peach_step_down(), action_update_pushing_block(), action_update_run(), action_update_sliding(), action_update_spin(), action_update_spin_jump(), action_update_step_up(), action_update_step_up_peach(), action_update_use_munchlesia(), action_update_use_spinning_flower(), action_update_use_tweester(), action_update_walk(), entity_GiantChest_await_got_item(), entity_Padlock_push_player(), func_802B6198_E24768(), func_802B6550_E23C30(), handle_jumping_land_on_switch(), initialize_jump(), player_jump(), update_encounters_post_battle(), and update_player_carry_anim().
suggest_player_anim_always_forward()
void suggest_player_anim_always_forward (AnimID anim)
Referenced by action_update_first_strike(), action_update_hit_fire(), action_update_hit_lava(), action_update_knockback(), action_update_pushing_block(), action_update_raise_arms(), action_update_sliding(), action_update_spin(), action_update_talk(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_spinning_flower(), entity_GiantChest_open(), func_802BC2B4_E2EBE4(), update_item_entity_pickup(), and update_riding_physics().
suspend_all_group()
void suspend_all_group (s32 groupFlags)
Referenced by evt_handle_suspend_all(), set_time_freeze_mode(), suspend_frozen_scripts(), update_encounters_neutral(), and update_encounters_pre_battle().
suspend_all_script()
s32 suspend_all_script (s32 id)
Referenced by evt_handle_suspend(), partner_suspend_ability_script(), start_battle(), update_encounters_neutral(), and update_encounters_pre_battle().
suspend_group_others()
void suspend_group_others (Evt * script, s32 groupFlags)
Referenced by evt_handle_suspend_others().
switch_to_partner()
void switch_to_partner (s32 arg0)
Referenced by check_input_open_menus().
sync_status_bar()
void sync_status_bar (void)
test_ray_colliders()
s32 test_ray_colliders (s32 ignoreFlags, f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 * hitX, f32 * hitY, f32 * hitZ, f32 * hitDepth, f32 * hitNx, f32 * hitNy, f32 * hitNz)
Referenced by entity_raycast_down(), npc_raycast_down(), npc_raycast_general(), npc_raycast_up(), npc_raycast_up_corner(), player_raycast_down(), player_raycast_general(), player_raycast_up_corner(), and test_ray_to_wall_center().
test_ray_entities()
s32 test_ray_entities (f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 * hitX, f32 * hitY, f32 * hitZ, f32 * hitDepth, f32 * hitNx, f32 * hitNy, f32 * hitNz)
Test a general ray from a given starting position and direction against all entities.
If one is hit, returns the position and normal of the hit and the length along the ray on the output params. All output params are invalid when a value of NO_COLLIDER is returned.
Parameters
startX origin x position of the ray
startY origin y position of the ray
startZ origin z position of the ray
dirX normalized x direction of the ray
dirY normalized y direction of the ray
dirZ normalized z direction of the ray
[out] hitX normalized x position of the hit
[out] hitY normalized y position of the hit
[out] hitZ normalized z position of the hit
[in,out] hitDepth as input, maximum length of the ray; as output, distance along the ray of the hit
[out] hitNx x normal direction of the hit
[out] hitNy y normal direction of the hit
[out] hitNz z normal direction of the hit
Returns
entity index or NO_COLLIDER is none is hit
Referenced by entity_raycast_down(), npc_raycast_down(), npc_raycast_general(), npc_raycast_up(), npc_raycast_up_corner(), player_raycast_down(), player_raycast_general(), and player_raycast_up_corner().
test_ray_zones()
s32 test_ray_zones (f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 * hitX, f32 * hitY, f32 * hitZ, f32 * hitDepth, f32 * nx, f32 * ny, f32 * nz)
Referenced by test_ray_zone(), and test_ray_zone_aabb().
transform_point()
void transform_point (Matrix4f mtx, f32 inX, f32 inY, f32 inZ, f32 inS, f32 * outX, f32 * outY, f32 * outZ, f32 * outW)
try_inflict_status()
s32 try_inflict_status (Actor * actor, s32 statusTypeKey, s32 statusKey)
Referenced by calc_enemy_damage_target().
try_player_footstep_sounds()
void try_player_footstep_sounds (s32 arg0)
Referenced by action_update_run(), action_update_step_up_peach(), and action_update_walk().
update_action_ratings()
void update_action_ratings (void)
Referenced by btl_update().
update_ambient_sounds()
void update_ambient_sounds (void)
Referenced by step_game_loop().
update_cameras()
void update_cameras (void)
Referenced by state_step_battle(), state_step_change_map(), state_step_enter_world(), state_step_game_over(), state_step_intro(), state_step_logos(), state_step_title_screen(), and state_step_world().
update_collider_transform()
void update_collider_transform (s16 colliderID)
Referenced by restore_map_collision_data().
update_curtains()
void update_curtains (void)
Referenced by step_game_loop().
update_damage_popups()
void update_damage_popups (void)
Referenced by btl_update().
update_effects()
void update_effects (void)
Referenced by state_step_battle(), state_step_change_map(), state_step_enter_world(), state_step_exit_language_select(), state_step_game_over(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_unpause(), and state_step_world().
update_encounters_conversation()
void update_encounters_conversation (void)
Referenced by update_encounters().
update_encounters_neutral()
void update_encounters_neutral (void)
Referenced by update_encounters().
update_encounters_post_battle()
void update_encounters_post_battle (void)
Referenced by update_encounters().
update_encounters_pre_battle()
void update_encounters_pre_battle (void)
Referenced by update_encounters().
update_enemy_shadows()
void update_enemy_shadows (void)
Referenced by update_nonplayer_actor_shadows().
update_enter_map_screen_overlay()
s16 update_enter_map_screen_overlay (s16 * progress)
Referenced by state_step_change_map(), and state_step_enter_world().
update_entities()
void update_entities (void)
Referenced by step_game_loop().
update_exit_map_screen_overlay()
s16 update_exit_map_screen_overlay (s16 * progress)
Referenced by init_enter_world_shared(), state_step_change_map(), and state_step_exit_file_select().
update_health_bars()
void update_health_bars (void)
Referenced by btl_update().
update_hero_shadows()
void update_hero_shadows (void)
Referenced by update_nonplayer_actor_shadows().
update_input()
void update_input (void)
Referenced by step_game_loop().
update_item_entities()
void update_item_entities (void)
Referenced by state_step_battle(), and state_step_world().
update_lerp()
f32 update_lerp (s32 easing, f32 start, f32 end, s32 elapsed, s32 duration)
Referenced by animate_and_draw_record(), appendGfx_message(), appendGfx_records(), CharAnim_FadeIn_0(), CharAnim_FadeIn_1(), CharAnim_FadeIn_2(), CharAnim_FadeIn_3(), CharAnim_FadeIn_4(), CharAnim_FadeIn_5(), CharAnim_FadeOut_0(), CharAnim_FadeOut_1(), CharAnim_FadeOut_2(), CharAnim_FadeOut_3(), FlyingMagikoopaAI_17(), msg_update_rewind_arrow(), setup_gfx_background_shade(), sfx_compute_spatialized_sound_params_full(), and update_riding_physics().
update_locomotion_state()
void update_locomotion_state (void)
Referenced by action_update_land(), action_update_step_down_land(), action_update_step_up(), and phys_player_land().
update_max_rumble_duration()
void update_max_rumble_duration (void)
Referenced by step_game_loop().
update_merlee_messages()
void update_merlee_messages (void)
Referenced by update_encounters().
update_messages()
void update_messages (void)
Referenced by step_game_loop().
update_player()
void update_player (void)
Referenced by state_step_change_map(), state_step_enter_world(), state_step_exit_language_select(), state_step_game_over(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_unpause(), and state_step_world().
update_player_input()
void update_player_input (void)
Referenced by update_player().
update_scripts()
void update_scripts (void)
Referenced by step_game_loop().
update_triggers()
void update_triggers (void)
Referenced by step_game_loop().
update_window_hierarchy()
void update_window_hierarchy (s32 windowIndex, u8 arg1)
Referenced by filemenu_init(), pause_init(), pause_update_tab_active(), pause_update_tab_inactive(), render_windows(), and set_window_properties().
update_windows()
void update_windows (void)
Referenced by step_game_loop().
update_workers()
void update_workers (void)
Referenced by step_game_loop().
use_consumable()
s32 use_consumable (s32 invSlot)
Referenced by check_input_open_menus().