papermario: src/game_states.c File Reference
game_states.c File Reference
Functions
void mode_default_nop (void)
void clear_game_modes (void)
GameMode * set_next_game_mode (GameMode *mode)
GameMode * set_game_mode_slot (s32 i, GameMode *mode)
void game_mode_set_fpDrawAuxUI (s32 i, void(*fn)(void))
void set_game_mode_flag_4 (s32 i)
void set_game_mode_flag_8 (s32 i)
void clear_game_mode_unk_flags (s32 i)
void set_game_mode_flag_10 (s32 i)
void step_current_game_mode (void)
void state_do_unk (void)
void state_render_backUI (void)
void state_render_frontUI (void)
Variables
BSS GameMode gMainGameMode [2]
BSS s32 D_80151730 [4]
Function Documentation
clear_game_mode_unk_flags()
void clear_game_mode_unk_flags (s32 i)
clear_game_modes()
void clear_game_modes (void)
Referenced by load_engine_data().
game_mode_set_fpDrawAuxUI()
void game_mode_set_fpDrawAuxUI (s32 i, void(*)(void) fn)
Referenced by state_init_title_screen(), and state_init_world().
mode_default_nop()
void mode_default_nop (void)
Referenced by game_mode_set_fpDrawAuxUI(), set_game_mode_slot(), and set_next_game_mode().
set_game_mode_flag_10()
void set_game_mode_flag_10 (s32 i)
set_game_mode_flag_4()
void set_game_mode_flag_4 (s32 i)
set_game_mode_flag_8()
void set_game_mode_flag_8 (s32 i)
set_game_mode_slot()
GameMode * set_game_mode_slot (s32 i, GameMode * mode)
Referenced by set_game_mode().
set_next_game_mode()
GameMode * set_next_game_mode (GameMode * mode)
state_do_unk()
void state_do_unk (void)
state_render_backUI()
void state_render_backUI (void)
Referenced by gfx_draw_frame().
state_render_frontUI()
void state_render_frontUI (void)
Referenced by gfx_draw_frame().
step_current_game_mode()
void step_current_game_mode (void)
Referenced by step_game_loop().
Variable Documentation
D_80151730
BSS s32 D_80151730[4]
gMainGameMode
BSS GameMode gMainGameMode[2]
Referenced by clear_game_mode_unk_flags(), clear_game_modes(), game_mode_set_fpDrawAuxUI(), set_game_mode_flag_10(), set_game_mode_flag_4(), set_game_mode_flag_8(), set_game_mode_slot(), set_next_game_mode(), state_do_unk(), state_render_backUI(), state_render_frontUI(), and step_current_game_mode().