papermario: src/game_modes.h File Reference
game_modes.h File Reference
Data Structures
struct GameMode
Enumerations
enum GameModeFlags {
MODE_FLAG_NONE = 0 , MODE_FLAG_INITIALIZED = (1 << 0) , MODE_FLAG_STEP_NOT_DONE = (1 << 1) , MODE_FLAG_4 = (1 << 2) ,
MODE_FLAG_8 = (1 << 3) , MODE_FLAG_10 = (1 << 4) , MODE_FLAG_RENDER_AUX_SET = (1 << 5)
}
enum GameModeIDs {
GAME_MODE_STARTUP = 0 , GAME_MODE_LOGOS = 1 , GAME_MODE_TITLE_SCREEN = 2 , GAME_MODE_ENTER_DEMO_WORLD = 3 ,
GAME_MODE_WORLD = 4 , GAME_MODE_CHANGE_MAP = 5 , GAME_MODE_GAME_OVER = 6 , GAME_MODE_ENTER_WORLD = 7 ,
GAME_MODE_BATTLE = 8 , GAME_MODE_END_BATTLE = 9 , GAME_MODE_PAUSE = 10 , GAME_MODE_UNPAUSE = 11 ,
GAME_MODE_LANGUAGE_SELECT = 12 , GAME_MODE_END_LANGUAGE_SELECT = 13 , GAME_MODE_FILE_SELECT = 14 , GAME_MODE_END_FILE_SELECT = 15 ,
GAME_MODE_INTRO = 16 , GAME_MODE_DEMO = 17
}
Functions
void set_game_mode (s16 mode)
void clear_game_modes (void)
GameMode * set_game_mode_slot (s32 i, GameMode *mode)
void game_mode_set_fpDrawAuxUI (s32 i, void(*fn)(void))
void step_current_game_mode (void)
void state_render_backUI (void)
void state_render_frontUI (void)
Enumeration Type Documentation
GameModeFlags
enum GameModeFlags
Enumerator
MODE_FLAG_NONE
MODE_FLAG_INITIALIZED
MODE_FLAG_STEP_NOT_DONE
MODE_FLAG_4
MODE_FLAG_8
MODE_FLAG_10
MODE_FLAG_RENDER_AUX_SET
GameModeIDs
enum GameModeIDs
Enumerator
GAME_MODE_STARTUP
GAME_MODE_LOGOS
GAME_MODE_TITLE_SCREEN
GAME_MODE_ENTER_DEMO_WORLD
GAME_MODE_WORLD
GAME_MODE_CHANGE_MAP
GAME_MODE_GAME_OVER
GAME_MODE_ENTER_WORLD
GAME_MODE_BATTLE
GAME_MODE_END_BATTLE
GAME_MODE_PAUSE
GAME_MODE_UNPAUSE
GAME_MODE_LANGUAGE_SELECT
GAME_MODE_END_LANGUAGE_SELECT
GAME_MODE_FILE_SELECT
GAME_MODE_END_FILE_SELECT
GAME_MODE_INTRO
GAME_MODE_DEMO
Function Documentation
clear_game_modes()
void clear_game_modes (void)
Referenced by load_engine_data().
game_mode_set_fpDrawAuxUI()
void game_mode_set_fpDrawAuxUI (s32 i, void(*)(void) fn)
Referenced by state_init_title_screen(), and state_init_world().
set_game_mode()
void set_game_mode (s16 mode)
Referenced by btl_state_update_end_battle(), btl_state_update_end_demo_battle(), check_input_open_menus(), filemenu_main_handle_input(), filemenu_selectlanguage_handle_input(), filemenu_yesno_handle_input(), goto_map(), load_battle(), load_engine_data(), pause_handle_input(), state_step_change_map(), state_step_demo(), state_step_end_battle(), state_step_enter_world(), state_step_exit_file_select(), state_step_exit_language_select(), state_step_game_over(), state_step_intro(), state_step_logos(), state_step_startup(), state_step_title_screen(), state_step_unpause(), and step_game_loop().
set_game_mode_slot()
GameMode * set_game_mode_slot (s32 i, GameMode * mode)
Referenced by set_game_mode().
state_render_backUI()
void state_render_backUI (void)
Referenced by gfx_draw_frame().
state_render_frontUI()
void state_render_frontUI (void)
Referenced by gfx_draw_frame().
step_current_game_mode()
void step_current_game_mode (void)
Referenced by step_game_loop().