papermario: src/effects/gather_magic.c File Reference
gather_magic.c File Reference
Functions
void gather_magic_appendGfx (void *effect)
void gather_magic_init (EffectInstance *effect)
void gather_magic_update (EffectInstance *effect)
void gather_magic_render (EffectInstance *effect)
EffectInstance * gather_magic_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09000080_38F790 []
Gfx D_090001A8_38F8B8 []
Gfx D_090001C8_38F8D8 []
Gfx * D_E008E890 [] = { D_090001A8_38F8B8, D_090001C8_38F8D8 }
Function Documentation
gather_magic_appendGfx()
void gather_magic_appendGfx (void * effect)
Referenced by gather_magic_render().
gather_magic_init()
void gather_magic_init (EffectInstance * effect)
Referenced by gather_magic_main().
gather_magic_main()
EffectInstance * gather_magic_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Referenced by lightning_main().
gather_magic_render()
void gather_magic_render (EffectInstance * effect)
Referenced by gather_magic_main().
gather_magic_update()
void gather_magic_update (EffectInstance * effect)
Referenced by gather_magic_main().
Variable Documentation
D_09000080_38F790
Gfx D_09000080_38F790[] extern
Referenced by gather_magic_appendGfx().
D_090001A8_38F8B8
Gfx D_090001A8_38F8B8[] extern
D_090001C8_38F8D8
Gfx D_090001C8_38F8D8[] extern
D_E008E890
Gfx* D_E008E890[] = { D_090001A8_38F8B8, D_090001C8_38F8D8 }
Referenced by gather_magic_appendGfx().