papermario: src/effects/gather_energy_pink.c File Reference
gather_energy_pink.c File Reference
Functions
void gather_energy_pink_init (EffectInstance *effect)
void gather_energy_pink_update (EffectInstance *effect)
void gather_energy_pink_render (EffectInstance *effect)
void gather_energy_pink_appendGfx (void *effect)
void gather_energy_pink_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, s32 duration)
Variables
Gfx D_09000DA0_33C970 []
Gfx D_09000E28_33C9F8 []
Gfx D_090010B0_33CC80 []
Gfx D_09001138_33CD08 []
Gfx * D_E00269F0 [] = { D_090010B0_33CC80, D_09000DA0_33C970 }
Gfx * D_E00269F8 [] = { D_09001138_33CD08, D_09000E28_33C9F8 }
u8 D_E0026A00 []
Function Documentation
gather_energy_pink_appendGfx()
void gather_energy_pink_appendGfx (void * effect)
Referenced by gather_energy_pink_render().
gather_energy_pink_init()
void gather_energy_pink_init (EffectInstance * effect)
Referenced by gather_energy_pink_main().
gather_energy_pink_main()
void gather_energy_pink_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, s32 duration)
gather_energy_pink_render()
void gather_energy_pink_render (EffectInstance * effect)
Referenced by gather_energy_pink_main().
gather_energy_pink_update()
void gather_energy_pink_update (EffectInstance * effect)
Referenced by gather_energy_pink_main().
Variable Documentation
D_09000DA0_33C970
Gfx D_09000DA0_33C970[] extern
D_09000E28_33C9F8
Gfx D_09000E28_33C9F8[] extern
D_090010B0_33CC80
Gfx D_090010B0_33CC80[] extern
D_09001138_33CD08
Gfx D_09001138_33CD08[] extern
D_E00269F0
Gfx* D_E00269F0[] = { D_090010B0_33CC80, D_09000DA0_33C970 }
Referenced by gather_energy_pink_appendGfx().
D_E00269F8
Gfx* D_E00269F8[] = { D_09001138_33CD08, D_09000E28_33C9F8 }
Referenced by gather_energy_pink_appendGfx().
D_E0026A00
u8 D_E0026A00[]
Initial value:
= {
    0xFF, 0xC5, 0x9C, 0xFF, 0x9C, 0xFF, 0xFF, 0x73, 0xD6, 0xFF, 0x9C, 0xFF, 0xFF, 0xC5, 0x7B, 0xFF,
    0xB4, 0xFF, 0xDE, 0x73, 0xFF, 0xFF, 0x94, 0x9C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
Referenced by gather_energy_pink_appendGfx().