papermario: src/effects/got_item_outline.c File Reference
got_item_outline.c File Reference
Functions
void got_item_outline_init (EffectInstance *effect)
void got_item_outline_update (EffectInstance *effect)
void got_item_outline_render (EffectInstance *effect)
void got_item_outline_appendGfx (void *effect)
void got_item_outline_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 arg4, EffectInstance **outEffect)
void func_E003621C (void)
Variables
IMG_BIN D_09000000_345B40 [][0x1000]
IMG_BIN D_09004000_349B40 [][0x1000]
Gfx D_09008100_34DC40 []
Gfx D_09008170_34DCB0 []
Gfx D_09008190_34DCD0 []
Gfx D_090081A8_34DCE8 []
Gfx D_090081C0_34DD00 []
Gfx * D_E0036630 []
u8 AnimScaleIn [] = { 60, 120, 140, 147, 149, 150 }
u8 AnimScaleOut [] = { 150, 150, 150, 150, 150, 150 }
Function Documentation
func_E003621C()
void func_E003621C (void)
got_item_outline_appendGfx()
void got_item_outline_appendGfx (void * effect)
Referenced by got_item_outline_render().
got_item_outline_init()
void got_item_outline_init (EffectInstance * effect)
Referenced by got_item_outline_main().
got_item_outline_main()
void got_item_outline_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 arg4, EffectInstance ** outEffect)
got_item_outline_render()
void got_item_outline_render (EffectInstance * effect)
Referenced by got_item_outline_main().
got_item_outline_update()
void got_item_outline_update (EffectInstance * effect)
Referenced by got_item_outline_main().
Variable Documentation
AnimScaleIn
u8 AnimScaleIn[] = { 60, 120, 140, 147, 149, 150 }
Referenced by got_item_outline_update().
AnimScaleOut
u8 AnimScaleOut[] = { 150, 150, 150, 150, 150, 150 }
Referenced by got_item_outline_update().
D_09000000_345B40
IMG_BIN D_09000000_345B40[][0x1000] extern
Referenced by got_item_outline_appendGfx().
D_09004000_349B40
IMG_BIN D_09004000_349B40[][0x1000] extern
Referenced by got_item_outline_appendGfx().
D_09008100_34DC40
Gfx D_09008100_34DC40[] extern
Referenced by got_item_outline_appendGfx().
D_09008170_34DCB0
Gfx D_09008170_34DCB0[] extern
D_09008190_34DCD0
Gfx D_09008190_34DCD0[] extern
D_090081A8_34DCE8
Gfx D_090081A8_34DCE8[] extern
D_090081C0_34DD00
Gfx D_090081C0_34DD00[] extern
D_E0036630
Gfx* D_E0036630[]
Initial value:
= {
    D_09008170_34DCB0, D_09008190_34DCD0, D_090081A8_34DCE8, D_090081C0_34DD00
}
Referenced by got_item_outline_appendGfx().