papermario: src/effects/green_impact.c File Reference
green_impact.c File Reference
Functions
void green_impact_init (EffectInstance *effect)
void green_impact_update (EffectInstance *effect)
void green_impact_render (EffectInstance *effect)
void green_impact_appendGfx (void *effect)
EffectInstance * green_impact_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
Variables
Gfx D_09000540_365EF0 []
Gfx D_090005A0_365F50 []
Gfx * D_E0064A60 [] = { D_090005A0_365F50, D_090005A0_365F50 }
Function Documentation
green_impact_appendGfx()
void green_impact_appendGfx (void * effect)
Referenced by green_impact_render().
green_impact_init()
void green_impact_init (EffectInstance * effect)
Referenced by green_impact_main().
green_impact_main()
EffectInstance * green_impact_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
green_impact_render()
void green_impact_render (EffectInstance * effect)
Referenced by green_impact_main().
green_impact_update()
void green_impact_update (EffectInstance * effect)
Referenced by green_impact_main().
Variable Documentation
D_09000540_365EF0
Gfx D_09000540_365EF0[] extern
Referenced by green_impact_appendGfx().
D_090005A0_365F50
Gfx D_090005A0_365F50[] extern
D_E0064A60
Gfx* D_E0064A60[] = { D_090005A0_365F50, D_090005A0_365F50 }
Referenced by green_impact_appendGfx().