papermario: src/heap.c File Reference
heap.c File Reference
Functions
HeapNode * general_heap_create (void)
void * general_heap_malloc (s32 size)
void * general_heap_malloc_tail (s32 size)
s32 general_heap_free (void *data)
s32 battle_heap_create (void)
s32 func_8002ACDC (void)
void * heap_malloc (s32 size)
s32 heap_free (void *data)
s32 collision_heap_create (void)
void * collision_heap_malloc (s32 size)
s32 collision_heap_free (void *data)
Variables
HeapNode heap_generalHead
HeapNode heap_collisionHead
Function Documentation
battle_heap_create()
s32 battle_heap_create (void)
Referenced by battle_heap_create_obfuscated(), state_step_end_battle(), state_step_file_select(), state_step_language_select(), and state_step_pause().
collision_heap_create()
s32 collision_heap_create (void)
Referenced by initialize_collision().
collision_heap_free()
s32 collision_heap_free (void * data)
Referenced by parent_collider_to_model().
collision_heap_malloc()
void * collision_heap_malloc (s32 size)
Referenced by load_hit_data(), and parent_collider_to_model().
func_8002ACDC()
s32 func_8002ACDC (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
general_heap_create()
HeapNode * general_heap_create (void)
Referenced by general_heap_create_obfuscated(), load_demo_battle(), load_engine_data(), state_init_file_select(), state_init_language_select(), state_init_logos(), state_init_title_screen(), state_step_demo(), state_step_intro(), state_step_startup(), and state_step_title_screen().
general_heap_free()
s32 general_heap_free (void * data)
Referenced by _update_message(), btl_state_update_normal_start(), draw_msg(), func_8013A4D0(), get_msg_properties(), heap_free(), imgfx_update_cache_impl(), init_hud_element_list(), load_battle_hit_asset(), load_map_bg(), load_map_by_IDs(), load_map_hit_asset(), pause_partners_load_portrait(), remove_all_effects(), remove_effect(), restore_map_collision_data(), set_message_text_var(), spr_load_sprite(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), state_step_unpause(), update_effects(), update_model_animator(), and update_model_animator_with_transform().
general_heap_malloc()
void * general_heap_malloc (s32 size)
general_heap_malloc_tail()
void * general_heap_malloc_tail (s32 size)
heap_free()
s32 heap_free (void * data)
Referenced by _delete_shadow(), ALT_clear_hud_element_cache(), btl_bonk_update(), btl_delete_actor(), btl_delete_player_actor(), btl_popup_messages_delete(), delete_entity(), delete_entity_and_unload_data(), delete_model_animator(), delete_model_animator_node(), delete_trigger(), disable_npc_blur(), dispose_merlee_message(), free_animator_nodes(), free_entity_model_by_index(), free_npc(), free_npc_by_index(), free_popup(), free_worker(), func_80045B10(), func_802C3C10(), get_asset_offset(), hud_element_free(), hud_element_free_transform(), imgfx_mesh_anim_update(), imgfx_update(), imgfx_update_cache_impl(), kill_enemy(), kill_script(), load_asset_by_name(), load_battle_hit_asset(), load_map_hit_asset(), load_path_data(), remove_item_entity_by_index(), remove_item_entity_by_reference(), and state_step_logos().
heap_malloc()
void * heap_malloc (s32 size)
Referenced by add_anim_node(), ALT_clear_hud_element_cache(), ALT_load_entity_model(), clear_virtual_entity_list(), clone_model(), create_actor(), create_encounters(), create_entity(), create_mesh_animator(), create_model_animator(), create_npc_impl(), create_shadow_from_data(), create_trigger(), create_worker_backUI(), create_worker_frontUI(), create_worker_scene(), enable_npc_blur(), evt_handle_allocate_array(), func_802C39F8(), get_asset_offset(), hud_element_create(), imgfx_load_anim(), imgfx_mesh_anim_update(), imgfx_update(), load_asset_by_name(), load_battle_hit_asset(), load_entity_model(), load_map_hit_asset(), load_partner_actor(), load_path_data(), load_player_actor(), make_item_entity(), make_item_entity_at_player(), mdl_create_model(), mdl_make_local_vertex_copy(), mdl_make_transform_group(), msg_copy_to_print_buffer(), npc_follow_init(), reset_model_animators(), show_immune_bonk(), start_child_script(), start_script(), start_script_in_group(), state_init_logos(), state_init_title_screen(), and update_item_entity_collectable().
Variable Documentation
heap_collisionHead
HeapNode heap_collisionHead extern
Referenced by collision_heap_create(), collision_heap_free(), and collision_heap_malloc().
heap_generalHead
HeapNode heap_generalHead extern
Referenced by general_heap_create(), general_heap_free(), general_heap_malloc(), and general_heap_malloc_tail().