papermario: src/entity/HeartBlock.c File Reference
HeartBlock.c File Reference
Functions
f32 entity_HeartBlockContent_get_previous_yaw (HeartBlockContentData *data, s32 lagTime)
void entity_HeartBlockContent__setupGfx (s32 entityIndex, Gfx *arg1)
void entity_HeartBlockContent_setupGfx (s32 entityIndex)
void entity_HeartBlockContent_set_initial_pos (Entity *entity)
void entity_HeartBlockContent__reset (Entity *entity)
void entity_HeartBlockContent_anim_idle (Entity *entity, s32 arg1)
void entity_HeartBlockContent_reset_data (Entity *entity)
void entity_HeartBlockContent__anim_heal (Entity *entity, s32 arg1)
void entity_HeartBlock_idle (Entity *entity)
void entity_HeartBlockContent_anim_beating (Entity *entity)
void entity_HeartBlockContent_init (Entity *entity)
void entity_HeartBlockContent_reset (Entity *entity)
void entity_HeartBlockContent_idle (Entity *entity)
void entity_HeartBlockContent_anim_heal (Entity *entity)
void entity_HeartBlock_change_render_script (Entity *entity)
void entity_HeartBlock_show_tutorial_message (Entity *entity)
void entity_HeartBlock_wait_for_close_tutorial (Entity *entity)
s8 entity_HeartBlock_create_child_entity (Entity *entity, EntityBlueprint *bp)
void entity_HeartBlock_init (Entity *entity)
Variables
EntityModelScript Entity_HeartBlockContent_RenderScriptIdle = STANDARD_ENTITY_MODEL_SCRIPT(Entity_HeartBlockContent_RenderHeartSleeping, RENDER_MODE_ALPHATEST)
EntityModelScript Entity_HeartBlockContent_RenderScriptAfterHit = STANDARD_ENTITY_MODEL_SCRIPT(Entity_HeartBlockContent_RenderHeartHappy, RENDER_MODE_SURFACE_XLU_LAYER2)
EntityModelScript Entity_HeartBlockContent_RenderScriptHit = STANDARD_ENTITY_MODEL_SCRIPT(Entity_HeartBlockContent_RenderHeartAwake, RENDER_MODE_SURFACE_XLU_LAYER2)
EntityBlueprint Entity_HeartBlockContent
Gfx Entity_HeartBlock_Render []
Gfx Entity_HeartBlockContent_RenderHeartSleeping []
Gfx Entity_HeartBlockContent_RenderHeartAwake []
Gfx Entity_HeartBlockContent_RenderHeartHappy []
BSS u32 HeartBlockPrinterClosed
EntityScript Entity_InertBlock_Script
EntityScript Entity_HeartBlockContent_Script
EntityScript Entity_HeartBlock_Script
EntityModelScript Entity_HeartBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_HeartBlock_Render, RENDER_MODE_SURFACE_XLU_LAYER3)
EntityBlueprint Entity_HeartBlockFrame
EntityBlueprint Entity_HeartBlock
Function Documentation
entity_HeartBlock_change_render_script()
void entity_HeartBlock_change_render_script (Entity * entity)
entity_HeartBlock_create_child_entity()
s8 entity_HeartBlock_create_child_entity (Entity * entity, EntityBlueprint * bp)
Referenced by entity_HeartBlock_init().
entity_HeartBlock_idle()
void entity_HeartBlock_idle (Entity * entity)
entity_HeartBlock_init()
void entity_HeartBlock_init (Entity * entity)
entity_HeartBlock_show_tutorial_message()
void entity_HeartBlock_show_tutorial_message (Entity * entity)
entity_HeartBlock_wait_for_close_tutorial()
void entity_HeartBlock_wait_for_close_tutorial (Entity * entity)
entity_HeartBlockContent__anim_heal()
void entity_HeartBlockContent__anim_heal (Entity * entity, s32 arg1)
Referenced by entity_HeartBlockContent_anim_heal().
entity_HeartBlockContent__reset()
void entity_HeartBlockContent__reset (Entity * entity)
Referenced by entity_HeartBlockContent_reset().
entity_HeartBlockContent__setupGfx()
void entity_HeartBlockContent__setupGfx (s32 entityIndex, Gfx * arg1)
Referenced by entity_HeartBlockContent_setupGfx().
entity_HeartBlockContent_anim_beating()
void entity_HeartBlockContent_anim_beating (Entity * entity)
Referenced by entity_HeartBlockContent_idle().
entity_HeartBlockContent_anim_heal()
void entity_HeartBlockContent_anim_heal (Entity * entity)
entity_HeartBlockContent_anim_idle()
void entity_HeartBlockContent_anim_idle (Entity * entity, s32 arg1)
Referenced by entity_HeartBlockContent_idle().
entity_HeartBlockContent_get_previous_yaw()
f32 entity_HeartBlockContent_get_previous_yaw (HeartBlockContentData * data, s32 lagTime)
Referenced by entity_HeartBlockContent__setupGfx().
entity_HeartBlockContent_idle()
void entity_HeartBlockContent_idle (Entity * entity)
entity_HeartBlockContent_init()
void entity_HeartBlockContent_init (Entity * entity)
entity_HeartBlockContent_reset()
void entity_HeartBlockContent_reset (Entity * entity)
entity_HeartBlockContent_reset_data()
void entity_HeartBlockContent_reset_data (Entity * entity)
entity_HeartBlockContent_set_initial_pos()
void entity_HeartBlockContent_set_initial_pos (Entity * entity)
Referenced by entity_HeartBlockContent__reset(), entity_HeartBlockContent_anim_beating(), entity_HeartBlockContent_anim_idle(), and entity_HeartBlockContent_init().
entity_HeartBlockContent_setupGfx()
void entity_HeartBlockContent_setupGfx (s32 entityIndex)
Referenced by entity_HeartBlockContent__anim_heal(), and entity_HeartBlockContent__reset().
Variable Documentation
Entity_HeartBlock
EntityBlueprint Entity_HeartBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_HeartBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_HeartBlock_init,
    .updateEntityScript = Entity_HeartBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(HeartBlock) },
    .entityType = ENTITY_TYPE_HEALING_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Entity_HeartBlock_Render
Gfx Entity_HeartBlock_Render[] extern
Entity_HeartBlock_RenderScript
EntityModelScript Entity_HeartBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_HeartBlock_Render, RENDER_MODE_SURFACE_XLU_LAYER3)
Entity_HeartBlock_Script
EntityScript Entity_HeartBlock_Script
Initial value:
= {
    es_SetCallback(entity_HeartBlock_idle, 0)
    es_PlaySound(SOUND_HIT_BLOCK)
    es_Call(entity_start_script)
    es_Call(entity_block_hit_init_scale)
    es_SetCallback(entity_block_hit_animate_scale, 6)
    es_Restart
    es_End
}
Entity_HeartBlockContent
EntityBlueprint Entity_HeartBlockContent
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION,
    .typeDataSize = sizeof(HeartBlockContentData),
    .renderCommandList = Entity_HeartBlockContent_RenderScriptIdle,
    .modelAnimationNodes = 0,
    .fpInit = entity_HeartBlockContent_init,
    .updateEntityScript = Entity_HeartBlockContent_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(HeartBlockContent) },
    .entityType = ENTITY_TYPE_HEALING_BLOCK_CONTENT,
    .aabbSize = { 18, 6, 18 }
}
Referenced by entity_HeartBlock_init().
Entity_HeartBlockContent_RenderHeartAwake
Gfx Entity_HeartBlockContent_RenderHeartAwake[] extern
Entity_HeartBlockContent_RenderHeartHappy
Gfx Entity_HeartBlockContent_RenderHeartHappy[] extern
Referenced by entity_HeartBlockContent_setupGfx().
Entity_HeartBlockContent_RenderHeartSleeping
Gfx Entity_HeartBlockContent_RenderHeartSleeping[] extern
Entity_HeartBlockContent_RenderScriptAfterHit
EntityModelScript Entity_HeartBlockContent_RenderScriptAfterHit = STANDARD_ENTITY_MODEL_SCRIPT(Entity_HeartBlockContent_RenderHeartHappy, RENDER_MODE_SURFACE_XLU_LAYER2)
Referenced by entity_HeartBlock_change_render_script().
Entity_HeartBlockContent_RenderScriptHit
EntityModelScript Entity_HeartBlockContent_RenderScriptHit = STANDARD_ENTITY_MODEL_SCRIPT(Entity_HeartBlockContent_RenderHeartAwake, RENDER_MODE_SURFACE_XLU_LAYER2)
Referenced by entity_HeartBlockContent__anim_heal().
Entity_HeartBlockContent_RenderScriptIdle
EntityModelScript Entity_HeartBlockContent_RenderScriptIdle = STANDARD_ENTITY_MODEL_SCRIPT(Entity_HeartBlockContent_RenderHeartSleeping, RENDER_MODE_ALPHATEST)
Referenced by entity_HeartBlockContent_reset().
Entity_HeartBlockContent_Script
EntityScript Entity_HeartBlockContent_Script
Initial value:
= {
    es_Call(entity_HeartBlockContent_reset)
    es_SetCallback(entity_HeartBlockContent_idle, 0)
    es_Call(entity_HeartBlockContent_reset_data)
    es_Call(entity_HeartBlock_change_render_script)
    es_SetCallback(entity_HeartBlockContent_anim_heal, 0)
    es_Call(entity_HeartBlock_show_tutorial_message)
    es_SetCallback(entity_HeartBlock_wait_for_close_tutorial, 0)
    es_SetCallback(NULL, 60)
    es_Restart
    es_End
}
Entity_HeartBlockFrame
EntityBlueprint Entity_HeartBlockFrame
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_HeartBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_block_init,
    .updateEntityScript = Entity_InertBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(HeartBlock) },
    .entityType = ENTITY_TYPE_HEALING_BLOCK_FRAME,
    .aabbSize = { 25, 25, 25 }
}
Entity_InertBlock_Script
EntityScript Entity_InertBlock_Script extern
HeartBlockPrinterClosed
BSS u32 HeartBlockPrinterClosed
Referenced by entity_HeartBlock_show_tutorial_message(), and entity_HeartBlock_wait_for_close_tutorial().