papermario: src/entity/HiddenPanel.c File Reference
HiddenPanel.c File Reference
Functions
s32 entity_HiddenPanel_is_item_on_top (Entity *)
void entity_HiddenPanel_flip_over (Entity *)
void mdl_project_tex_coords (s32 modelID, Gfx *destGfx, Matrix4f destMtx, void *destVertices)
s32 npc_find_standing_on_entity (s32 entityIndex)
void entity_HiddenPanel_setupGfx (s32 entityIndex)
void entity_HiddenPanel_set_ispy_notification (Entity *entity)
void entity_HiddenPanel_hide (Entity *entity)
void entity_HiddenPanel_idle (Entity *entity)
void entity_HiddenPanel_init (Entity *entity)
Variables
s32 ERS_AltHiddenPanel []
Gfx Gfx_HiddenPanel_RenderTop []
Gfx Gfx_AltHiddenPanel_RenderTop []
Gfx Gfx_HiddenPanel_RenderHole []
Gfx Gfx_HiddenPanel_Render []
Gfx Gfx_HiddenPanel_Render2 []
EntityScript Entity_HiddenPanel_Script
EntityModelScript ERS_HiddenPanel
EntityBlueprint Entity_HiddenPanel
Function Documentation
entity_HiddenPanel_flip_over()
void entity_HiddenPanel_flip_over (Entity * entity)
entity_HiddenPanel_hide()
void entity_HiddenPanel_hide (Entity * entity)
entity_HiddenPanel_idle()
void entity_HiddenPanel_idle (Entity * entity)
entity_HiddenPanel_init()
void entity_HiddenPanel_init (Entity * entity)
entity_HiddenPanel_is_item_on_top()
s32 entity_HiddenPanel_is_item_on_top (Entity * entity)
Referenced by entity_HiddenPanel_idle().
entity_HiddenPanel_set_ispy_notification()
void entity_HiddenPanel_set_ispy_notification (Entity * entity)
entity_HiddenPanel_setupGfx()
void entity_HiddenPanel_setupGfx (s32 entityIndex)
Referenced by entity_HiddenPanel_init().
mdl_project_tex_coords()
void mdl_project_tex_coords (s32 modelID, Gfx * destGfx, Matrix4f destMtx, void * destVertices)
Referenced by entity_HiddenPanel_init(), and entity_HiddenPanel_setupGfx().
npc_find_standing_on_entity()
s32 npc_find_standing_on_entity (s32 entityIndex)
Referenced by entity_HiddenPanel_idle().
Variable Documentation
Entity_HiddenPanel
EntityBlueprint Entity_HiddenPanel
Initial value:
= {
    .flags = ENTITY_FLAG_HIDDEN,
    .typeDataSize = sizeof(HiddenPanelData),
    .renderCommandList = ERS_HiddenPanel,
    .modelAnimationNodes = 0,
    .fpInit = entity_HiddenPanel_init,
    .updateEntityScript = Entity_HiddenPanel_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(HiddenPanel) },
    .entityType = ENTITY_TYPE_HIDDEN_PANEL,
    .aabbSize = { 60, 0, 60 }
}
Entity_HiddenPanel_Script
EntityScript Entity_HiddenPanel_Script
Initial value:
= {
    es_Call(entity_HiddenPanel_set_ispy_notification)
    es_Label(1)
        es_Call(entity_HiddenPanel_hide)
        es_SetCallback(entity_HiddenPanel_idle, 0)
        es_SetCallback(entity_HiddenPanel_flip_over, 0)
    es_Goto(1)
    es_End
}
ERS_AltHiddenPanel
EntityModelScript ERS_AltHiddenPanel
Initial value:
= {
    ems_SetRenderMode(RENDER_MODE_SURFACE_OPA)
    ems_SetFlags(ENTITY_MODEL_FLAG_10000)
    ems_Draw(Gfx_HiddenPanel_Render2, 60)
    ems_Restart
    ems_End
}
Referenced by entity_HiddenPanel_init().
ERS_HiddenPanel
EntityModelScript ERS_HiddenPanel
Initial value:
= {
    ems_SetRenderMode(RENDER_MODE_SURFACE_OPA)
    ems_SetFlags(ENTITY_MODEL_FLAG_10000)
    ems_Draw(Gfx_HiddenPanel_Render, 60)
    ems_Restart
    ems_End
}
Gfx_AltHiddenPanel_RenderTop
Gfx Gfx_AltHiddenPanel_RenderTop[] extern
Referenced by entity_HiddenPanel_init().
Gfx_HiddenPanel_Render
Gfx Gfx_HiddenPanel_Render[] extern
Gfx_HiddenPanel_Render2
Gfx Gfx_HiddenPanel_Render2[] extern
Gfx_HiddenPanel_RenderHole
Gfx Gfx_HiddenPanel_RenderHole[] extern
Referenced by entity_HiddenPanel_setupGfx().
Gfx_HiddenPanel_RenderTop
Gfx Gfx_HiddenPanel_RenderTop[] extern
Referenced by entity_HiddenPanel_init().