papermario: src/effects/hieroglyphs.c File Reference
hieroglyphs.c File Reference
Functions
void hieroglyphs_init (EffectInstance *effect)
void hieroglyphs_update (EffectInstance *effect)
void hieroglyphs_render (EffectInstance *effect)
void hieroglyphs_appendGfx (void *effect)
EffectInstance * hieroglyphs_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 timeLeft)
void func_E00E2210 (void)
Variables
Gfx D_09001000_3DDD50 []
Vtx_t D_090010A8_3DDDF8 []
Gfx * D_E00E29F0 [] = { D_09001000_3DDD50 }
u8 D_E00E29F4 []
u8 D_E00E2A08 []
u8 D_E00E2A1C []
Function Documentation
func_E00E2210()
void func_E00E2210 (void)
hieroglyphs_appendGfx()
void hieroglyphs_appendGfx (void * effect)
Referenced by hieroglyphs_render().
hieroglyphs_init()
void hieroglyphs_init (EffectInstance * effect)
Referenced by hieroglyphs_main().
hieroglyphs_main()
EffectInstance * hieroglyphs_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 timeLeft)
hieroglyphs_render()
void hieroglyphs_render (EffectInstance * effect)
Referenced by hieroglyphs_main().
hieroglyphs_update()
void hieroglyphs_update (EffectInstance * effect)
Referenced by hieroglyphs_main().
Variable Documentation
D_09001000_3DDD50
Gfx D_09001000_3DDD50[] extern
D_090010A8_3DDDF8
Vtx_t D_090010A8_3DDDF8[] extern
Referenced by hieroglyphs_appendGfx().
D_E00E29F0
Gfx* D_E00E29F0[] = { D_09001000_3DDD50 }
Referenced by hieroglyphs_appendGfx().
D_E00E29F4
u8 D_E00E29F4[]
Initial value:
= {
    120, 130, 140, 150, 160, 170, 180, 190, 200, 200,
    190, 180, 170, 160, 150, 140, 130
}
Referenced by hieroglyphs_appendGfx().
D_E00E2A08
u8 D_E00E2A08[]
Initial value:
= {
    170, 160, 150, 140, 130, 120, 130, 140, 150, 160,
    170, 180, 190, 200, 200, 190, 180
}
Referenced by hieroglyphs_appendGfx().
D_E00E2A1C
u8 D_E00E2A1C[]
Initial value:
= {
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255
}
Referenced by hieroglyphs_appendGfx().