papermario: src/world/area_hos/hos_05/hos_05_5_intro.c File Reference
hos_05_5_intro.c File Reference
Data Structures
struct StoryGraphicData
struct UnkHos05Path
Macros
#define TAPE_OFFSET 0x2A440
#define STORY_IMG_SIZE (264 * 162 * G_IM_SIZ_8b_BYTES)
#define TAPE_IMG_SIZE (128 * 128 * G_IM_SIZ_8b_BYTES)
#define BOWSER_IMG_SIZE (128 * 128 * G_IM_SIZ_8b_BYTES)
#define PAL_256_SIZE (256 * 2)
#define BOWSER_APPEARS_TIME (268)
Enumerations
enum {
STORY_PAGE_BLANK = 0 , STORY_PAGE_STARRY_SKY = 1 , STORY_PAGE_SHRINE_EXT = 2 , STORY_PAGE_STAR_ROD = 3 ,
STORY_PAGE_SHRINE_INT = 4
}
enum {
STORY_PAGE_STATE_BEGIN = 0 , STORY_PAGE_STATE_WAIT = 1 , STORY_PAGE_STATE_NEXT = 2 , STORY_PAGE_STATE_BOWSER_BEGIN = 3 ,
STORY_PAGE_STATE_BOWSER_ANIM = 4 , STORY_PAGE_STATE_BOWSER_NEXT = 5 , STORY_PAGE_STATE_DONE = 6
}
Functions
void adjust_cam_vfov (s32 camID, f32 fov)
void appendGfx_image_strips (s32 baseX, s32 baseY, IMG_PTR img, PAL_PTR pal, s32 alpha, s32 width, s32 height, s32 lineHeight)
void draw_foreground_bowser_silhouette (void)
void draw_background_tape (void)
void appendGfx_image_ci (s32 baseX, s32 baseY, IMG_PTR img, PAL_PTR pal)
void worker_draw_story_graphics (void)
void load_story_image (s32 loadBackImage, s32 imageIdx)
Variables
s32 missing_802494FC_94FC []
s32 D_802495DC_A3381C = 0
s32 D_802495E0_A33820 = 0
CameraControlSettings IntroCamSettings0
CameraControlSettings IntroCamSettings1
CameraControlSettings IntroCamSettings2
CameraControlSettings IntroCamSettings3
CameraControlSettings IntroCamSettings4
CameraControlSettings IntroCamSettings5
CameraControlSettings IntroCamSettings6
CameraControlSettings IntroCamSettings7
CameraControlSettings IntroCamSettings8
CameraControlSettings IntroCamSettings9
CameraControlSettings IntroCamSettings10
CameraControlSettings IntroCamSettings11
CameraControlSettings IntroCamSettings12
CameraControlSettings IntroCamSettings13
CameraControlSettings IntroCamSettings14
CameraControlSettings IntroCamSettings15
CameraControlSettings IntroCamSettings16
f32 StoryCameraAngle = 240.0
u16 * ColorBufPtr = NULL
f32 IntroCamStateA_BoomLength = 130.4
f32 IntroCamStateA_BoomPitch = 12.4
f32 IntroCamStateA_ViewPitch = -16.8
f32 IntroCamStateA_Vfov = 62.0
f32 IntroCamStateB_BoomLength = 130.4
f32 IntroCamStateB_BoomPitch = 12.4
f32 IntroCamStateB_ViewPitch = -16.8
f32 IntroCamStateB_Vfov = 62.0
s32 D_802498F8_A33B38 = 0
s32 D_802498FC_A33B3C = 0
s32 StoryCameraShake1Angle = 0
f32 StoryCameraShake1Scale = 1.0
s32 StoryCameraShake2Angle = 0
f32 StoryCameraShake2Scale = 12.0
s32 UnusedBowserLeapTime = 0
s16 UnusedBowserHoverOffsets []
s16 UnusedBowserLeapPath []
BSS f32 UnusedBowserLeapBaseY
s32 BowserHoverTime = 0
s16 BowserHoverOffsets []
BSS f32 BowserHoverBaseY
f32 UnusedStoryCameraZoomAmt = 30.0
s32 UnusedKammyMoveTime = 0
s16 UnusedKammyHoverOffset []
Vec2s UnusedKammyMovePath []
BSS f32 UnusedKammyMoveBaseY
s32 KammyHoverTime = 0
s16 KammyHoverOffsets []
BSS f32 KammyHoverBaseY
f32 BoomLengthInhale = 121.6
s32 CamMoveInhaleTime = 0
f32 BoomLengthExhale = 90.0
s32 CamMoveExhaleTime = 0
s32 FlyToStarRodTime = 0
BSS f32 FlyToStarRodStartX
BSS f32 FlyToStarRodStartZ
s32 HoldStarRodTime = 0
BSS f32 HoldStarRodFov
BSS f32 HoldStarRodBoomLength
BSS f32 HoldStarRodCamX
BSS f32 HoldStarRodCamY
BSS f32 HoldStarRodCamZ
BSS f32 FlyToBowserStartX
BSS f32 FlyToBowserStartZ
BSS f32 D_8024F2FC
BSS f32 D_8024F300
BSS f32 D_8024F304
BSS f32 D_8024F308
BSS f32 D_8024F30C
BSS f32 D_8024F310
BSS char D_8024F314 [0x4]
BSS f32 StarSpiritsPosX [7]
BSS char D_8024F334 [0x4]
BSS f32 StarSpiritsPosY [7]
BSS char D_8024F354 [0x4]
BSS f32 StarSpiritsPosZ [7]
BSS f32 AnimBowser_FlyOff_InitialY
BSS f32 AnimKammy_FlyOff_InitialY
BSS char D_8024F37C [0x4]
BSS s32 D_8024F380
BSS char D_8024F384 [0x74]
BSS UnkHos05Path D_8024F3F8 [7]
BSS StoryGraphicData StoryGraphics
f32 PanAcrossRoomCamX = 40.0
f32 PanAcrossRoomCamZ = -40.0
f32 PanAcrossRoomAngle = 45.0
s32 PanAcrossRoomTime = 0
f32 OrbitKammyFov = 50.0
f32 OrbitKammyBoomLength = 246.1
f32 OrbitKammyCamY = 200.0
f32 OrbitKammyAngle = 25.0
s32 OrbitKammyTime = 0
EvtScript EVS_UpdateWorldFogParams
EvtScript EVS_CaptureSpirits
f32 FinalCamMoveBoomLength = 130.0
s32 FlyToBowserTime = 0
s32 StarSpiritLeapBackScalars []
StoryGraphicData * StoryGraphicsPtr = & StoryGraphics
Gfx gfx_setup_story_viewport []
s32 StoryPageState = STORY_PAGE_STATE_BEGIN
s32 CurrentStoryPageIdx = 0
s32 CurrentStoryPageTime = 0
u32 BowserSilhouetteTime = 0
s32 StoryPageDuration []
s32 NextPageAnimOffsetsX []
u8 BowserSilhouetteShakeY []
u16 BowserSilhouetteLeapX []
u16 BowserSilhouetteLeapY []
s32 FadeAwayTapeTime = 30
s32 D_8024ACBC_A34EFC = 0x00010019
EvtScript EVS_Scene_IntroStory
EvtScript EVS_Intro_Main
f32 AnimBowser_FlyOff_Time = 0.0
f32 AnimKammy_FlyOff_Time = 0.0
Data Structure Documentation
StoryGraphicData
struct StoryGraphicData
Data Fields
s16 backImgPosX
s16 backImgPosY
s16 flipOrder
s16 frontImgPosX
s16 frontImgPosY
IMG_PTR imgBack
IMG_PTR imgBowser
IMG_PTR imgFront
IMG_PTR imgTape
PAL_PTR palBack
PAL_PTR palBowser
PAL_PTR palFront
u16 silhouettePosX
u16 silhouettePosY
s16 storyPageAlpha
s16 tapeAlpha
s16 tapePosX
s16 tapePosY
char unk_14[0x4]
char unk_24[0x18]
char unk_4C[0xC]
char unk_6E[0x2]
s32 workerID
UnkHos05Path
struct UnkHos05Path
Data Fields
Vec3f endPoint
Vec3f midPoint
Vec3f startPoint
char unk_24[4]
Macro Definition Documentation
BOWSER_APPEARS_TIME
#define BOWSER_APPEARS_TIME (268)
BOWSER_IMG_SIZE
#define BOWSER_IMG_SIZE (128 * 128 * G_IM_SIZ_8b_BYTES)
PAL_256_SIZE
#define PAL_256_SIZE (256 * 2)
Referenced by load_story_image().
STORY_IMG_SIZE
#define STORY_IMG_SIZE (264 * 162 * G_IM_SIZ_8b_BYTES)
Referenced by load_story_image().
TAPE_IMG_SIZE
#define TAPE_IMG_SIZE (128 * 128 * G_IM_SIZ_8b_BYTES)
TAPE_OFFSET
#define TAPE_OFFSET 0x2A440
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
STORY_PAGE_BLANK
STORY_PAGE_STARRY_SKY
STORY_PAGE_SHRINE_EXT
STORY_PAGE_STAR_ROD
STORY_PAGE_SHRINE_INT
anonymous enum
anonymous enum
Enumerator
STORY_PAGE_STATE_BEGIN
STORY_PAGE_STATE_WAIT
STORY_PAGE_STATE_NEXT
STORY_PAGE_STATE_BOWSER_BEGIN
STORY_PAGE_STATE_BOWSER_ANIM
STORY_PAGE_STATE_BOWSER_NEXT
STORY_PAGE_STATE_DONE
Function Documentation
adjust_cam_vfov()
void adjust_cam_vfov (s32 camID, f32 fov)
appendGfx_image_ci()
void appendGfx_image_ci (s32 baseX, s32 baseY, IMG_PTR img, PAL_PTR pal)
Referenced by worker_draw_story_graphics().
appendGfx_image_strips()
void appendGfx_image_strips (s32 baseX, s32 baseY, IMG_PTR img, PAL_PTR pal, s32 alpha, s32 width, s32 height, s32 lineHeight)
Referenced by draw_background_tape(), and draw_foreground_bowser_silhouette().
draw_background_tape()
void draw_background_tape (void)
Referenced by worker_draw_story_graphics().
draw_foreground_bowser_silhouette()
void draw_foreground_bowser_silhouette (void)
Referenced by curtain_callback_narration().
load_story_image()
void load_story_image (s32 loadBackImage, s32 imageIdx)
worker_draw_story_graphics()
void worker_draw_story_graphics (void)
Variable Documentation
AnimBowser_FlyOff_InitialY
BSS f32 AnimBowser_FlyOff_InitialY
AnimBowser_FlyOff_Time
f32 AnimBowser_FlyOff_Time = 0.0
AnimKammy_FlyOff_InitialY
BSS f32 AnimKammy_FlyOff_InitialY
AnimKammy_FlyOff_Time
f32 AnimKammy_FlyOff_Time = 0.0
BoomLengthExhale
f32 BoomLengthExhale = 90.0
BoomLengthInhale
f32 BoomLengthInhale = 121.6
BowserHoverBaseY
BSS f32 BowserHoverBaseY
BowserHoverOffsets
s16 BowserHoverOffsets[]
Initial value:
= {
    -3, -2, -1,  0,  1,  2,  3,  4,
     3,  2,  1,  0, -1, -2, -3, -4,
}
BowserHoverTime
s32 BowserHoverTime = 0
BowserSilhouetteLeapX
u16 BowserSilhouetteLeapX[]
Initial value:
= {
    100, 110, 121, 136, 155, 175, 195, 214, 232, 249, 265, 280, 294, 307, 319
}
BowserSilhouetteLeapY
u16 BowserSilhouetteLeapY[]
Initial value:
= {
    3, 2, -6, -21, -40, -63, -90, -120, -160, -200, -240, -280, -320
}
BowserSilhouetteShakeY
u8 BowserSilhouetteShakeY[]
BowserSilhouetteTime
u32 BowserSilhouetteTime = 0
CamMoveExhaleTime
s32 CamMoveExhaleTime = 0
CamMoveInhaleTime
s32 CamMoveInhaleTime = 0
ColorBufPtr
u16* ColorBufPtr = NULL
CurrentStoryPageIdx
s32 CurrentStoryPageIdx = 0
CurrentStoryPageTime
s32 CurrentStoryPageTime = 0
D_802495DC_A3381C
s32 D_802495DC_A3381C = 0
D_802495E0_A33820
s32 D_802495E0_A33820 = 0
D_802498F8_A33B38
s32 D_802498F8_A33B38 = 0
D_802498FC_A33B3C
s32 D_802498FC_A33B3C = 0
D_8024ACBC_A34EFC
s32 D_8024ACBC_A34EFC = 0x00010019
D_8024F2FC
BSS f32 D_8024F2FC
D_8024F300
BSS f32 D_8024F300
D_8024F304
BSS f32 D_8024F304
D_8024F308
BSS f32 D_8024F308
D_8024F30C
BSS f32 D_8024F30C
D_8024F310
BSS f32 D_8024F310
D_8024F314
BSS char D_8024F314[0x4]
D_8024F334
BSS char D_8024F334[0x4]
D_8024F354
BSS char D_8024F354[0x4]
D_8024F37C
BSS char D_8024F37C[0x4]
D_8024F380
BSS s32 D_8024F380
D_8024F384
BSS char D_8024F384[0x74]
D_8024F3F8
BSS UnkHos05Path D_8024F3F8[7]
EVS_CaptureSpirits
EvtScript EVS_CaptureSpirits
EVS_Intro_Main
EvtScript EVS_Intro_Main
Initial value:
= {
    EVT_USE_ARRAY(EVT_PTR( D_8024F380 ))
    EVT_CALL(LoadSettings, CAM_DEFAULT, EVT_PTR( IntroCamSettings1 ))
    EVT_THREAD
    EVT_END_THREAD
    EVT_RETURN
    EVT_END
}
EVS_Scene_IntroStory
EvtScript EVS_Scene_IntroStory
EVS_UpdateWorldFogParams
EvtScript EVS_UpdateWorldFogParams
Initial value:
= {
    EVT_END_LOOP
    EVT_RETURN
    EVT_END
}
FadeAwayTapeTime
s32 FadeAwayTapeTime = 30
FinalCamMoveBoomLength
f32 FinalCamMoveBoomLength = 130.0
FlyToBowserStartX
BSS f32 FlyToBowserStartX
FlyToBowserStartZ
BSS f32 FlyToBowserStartZ
FlyToBowserTime
s32 FlyToBowserTime = 0
FlyToStarRodStartX
BSS f32 FlyToStarRodStartX
FlyToStarRodStartZ
BSS f32 FlyToStarRodStartZ
FlyToStarRodTime
s32 FlyToStarRodTime = 0
gfx_setup_story_viewport
Gfx gfx_setup_story_viewport[]
Initial value:
= {
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetCombineMode(PM_CC_10, PM_CC_10),
    gsDPSetScissor(G_SC_NON_INTERLACE, 29, 28, 291, 190),
    gsDPSetColorDither(G_CD_DISABLE),
    gsDPSetAlphaDither(G_AD_PATTERN),
    gsDPSetRenderMode(CVG_DST_FULL | ZMODE_OPA | FORCE_BL | G_RM_PASS, CVG_DST_FULL | ZMODE_OPA | FORCE_BL | GBL_c2(G_BL_CLR_IN, G_BL_0, G_BL_CLR_IN, G_BL_1)),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH | G_CLIPPING | 0x0040F9FA),
    gsSPSetGeometryMode(G_SHADE | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_image_strips(), and worker_draw_story_graphics().
HoldStarRodBoomLength
BSS f32 HoldStarRodBoomLength
HoldStarRodCamX
BSS f32 HoldStarRodCamX
HoldStarRodCamY
BSS f32 HoldStarRodCamY
HoldStarRodCamZ
BSS f32 HoldStarRodCamZ
HoldStarRodFov
BSS f32 HoldStarRodFov
HoldStarRodTime
s32 HoldStarRodTime = 0
IntroCamSettings0
CameraControlSettings IntroCamSettings0
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 130.4,
    .boomPitch = 12.4,
    .points = { .two = {  0.0, -1.0, 0.0, 0.0, -1.0, -500.0 }},
    .viewPitch = -16.8,
    .flag = FALSE,
}
IntroCamSettings1
CameraControlSettings IntroCamSettings1
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 130.4,
    .boomPitch = 12.4,
    .points = { .two = {  0.0, -1.0, 0.0, -433.0127, -1.0, -250.0 }},
    .viewPitch = -16.8,
    .flag = FALSE,
}
IntroCamSettings10
CameraControlSettings IntroCamSettings10
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 225.7,
    .boomPitch = 9.7,
    .points = { .two = {  0.0, -1.0, 0.0, 6.9, -1.0, 168.8 }},
    .viewPitch = -3.0,
    .flag = FALSE,
}
IntroCamSettings11
CameraControlSettings IntroCamSettings11
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 130.0,
    .boomPitch = 9.8,
    .points = { .two = {  0.0, -1.0, 0.0, 40.0, -1.0, 168.8 }},
    .viewPitch = -9.3,
    .flag = FALSE,
}
IntroCamSettings12
CameraControlSettings IntroCamSettings12
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 270.0,
    .boomPitch = 9.8,
    .points = { .two = {  0.0, -1.0, 0.0, 40.0, -1.0, 168.8 }},
    .viewPitch = -9.3,
    .flag = FALSE,
}
IntroCamSettings13
CameraControlSettings IntroCamSettings13
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 246.1,
    .boomPitch = -1.3,
    .points = { .two = {  0.0, -1.0, 0.0, 500.0, -1.0, 500.0 }},
    .viewPitch = 0.5,
    .flag = FALSE,
}
IntroCamSettings14
CameraControlSettings IntroCamSettings14
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 180.0,
    .boomPitch = -1.3,
    .points = { .two = {  0.0, -1.0, 0.0, 0.0, -1.0, -500.0 }},
    .viewPitch = 0.5,
    .flag = FALSE,
}
IntroCamSettings15
CameraControlSettings IntroCamSettings15
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 90.0,
    .boomPitch = 5.4,
    .points = { .two = {  0.0, -1.0, 0.0, 0.0, -1.0, 500.0 }},
    .viewPitch = -6.9,
    .flag = FALSE,
}
IntroCamSettings16
CameraControlSettings IntroCamSettings16
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 445.8,
    .boomPitch = 5.4,
    .points = { .two = {  0.0, -1.0, 0.0, 0.0, -1.0, 500.0 }},
    .viewPitch = -6.9,
    .flag = FALSE,
}
IntroCamSettings2
CameraControlSettings IntroCamSettings2
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 400.0,
    .boomPitch = 2.7,
    .points = { .two = {  0.0, -1.0, 0.0, 0.0, -1.0, -500.0 }},
    .viewPitch = -7.4,
    .flag = FALSE,
}
IntroCamSettings3
CameraControlSettings IntroCamSettings3
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 274.4,
    .boomPitch = -9.3,
    .points = { .two = {  0.0, -1.0, 0.0, 114.3, -1.0, 500.0 }},
    .viewPitch = 0.7,
    .flag = FALSE,
}
IntroCamSettings4
CameraControlSettings IntroCamSettings4
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 274.4,
    .boomPitch = -9.3,
    .points = { .two = {  0.0, -1.0, 0.0, 114.3, -1.0, 500.0 }},
    .viewPitch = 0.7,
    .flag = FALSE,
}
IntroCamSettings5
CameraControlSettings IntroCamSettings5
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 243.3,
    .boomPitch = 16.0,
    .points = { .two = {  0.0, -1.0, 0.0, 56.1, -1.0, -1.1 }},
    .viewPitch = -3.0,
    .flag = FALSE,
}
IntroCamSettings6
CameraControlSettings IntroCamSettings6
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 192.5,
    .boomPitch = 12.4,
    .points = { .two = {  0.0, -1.0, 0.0, 0.0, -1.0, 500.0 }},
    .viewPitch = -10.7,
    .flag = FALSE,
}
IntroCamSettings7
CameraControlSettings IntroCamSettings7
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 467.0,
    .boomPitch = 21.0,
    .points = { .two = {  0.0, -1.0, 0.0, 71.3, -1.0, 154.3 }},
    .viewPitch = -3.0,
    .flag = FALSE,
}
IntroCamSettings8
CameraControlSettings IntroCamSettings8
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 121.6,
    .boomPitch = 0.0,
    .points = { .two = {  0.0, -1.0, 0.0, 24.4, -1.0, 154.3 }},
    .viewPitch = 0.0,
    .flag = FALSE,
}
IntroCamSettings9
CameraControlSettings IntroCamSettings9
Initial value:
= {
    .type = CAM_CONTROL_FIXED_ORIENTATION,
    .boomLength = 474.7,
    .boomPitch = 0.0,
    .points = { .two = {  0.0, -1.0, 0.0, 24.4, -1.0, 154.3 }},
    .viewPitch = 0.0,
    .flag = FALSE,
}
IntroCamStateA_BoomLength
f32 IntroCamStateA_BoomLength = 130.4
IntroCamStateA_BoomPitch
f32 IntroCamStateA_BoomPitch = 12.4
IntroCamStateA_Vfov
f32 IntroCamStateA_Vfov = 62.0
IntroCamStateA_ViewPitch
f32 IntroCamStateA_ViewPitch = -16.8
IntroCamStateB_BoomLength
f32 IntroCamStateB_BoomLength = 130.4
IntroCamStateB_BoomPitch
f32 IntroCamStateB_BoomPitch = 12.4
IntroCamStateB_Vfov
f32 IntroCamStateB_Vfov = 62.0
IntroCamStateB_ViewPitch
f32 IntroCamStateB_ViewPitch = -16.8
KammyHoverBaseY
BSS f32 KammyHoverBaseY
KammyHoverOffsets
s16 KammyHoverOffsets[]
Initial value:
= {
    -3, -2, -1,  0,  1,  2,  3,  4,
     3,  2,  1,  0, -1, -2, -3, -4,
}
KammyHoverTime
s32 KammyHoverTime = 0
missing_802494FC_94FC
s32 missing_802494FC_94FC[]
Initial value:
= {
    0x64, 0x63, 0x62, 0x60, 0x5E, 0x5C, 0x59, 0x57,
    0x54, 0x51, 0x4F, 0x4E, 0x4D, 0x4D, 0x4C, 0x4C,
    0x4C, 0x4C, 0x4D, 0x4D, 0x4E, 0x4E, 0x4F, 0x4F,
    0x50, 0x50, 0x51, 0x51, 0x52, 0x52, 0x53, 0x53,
    0x54, 0x54, 0x55, 0x55, 0x56, 0x56, 0x57, 0x57,
    0x58, 0x58, 0x59, 0x59, 0x5A, 0x5B, 0x5C, 0x5D,
    0x5E, 0x5F, 0x60, 0x61, 0x62, 0x63, 0x64,
}
NextPageAnimOffsetsX
s32 NextPageAnimOffsetsX[]
Initial value:
= {
    0, 0, 0, -1, -2, -3, -4, -9, -15, -22,
    -30, -39, -49, -60, -72, -85, -99, -114, -130, -147,
    -165, -184, -204, -225, -247, -270,
}
OrbitKammyAngle
f32 OrbitKammyAngle = 25.0
OrbitKammyBoomLength
f32 OrbitKammyBoomLength = 246.1
OrbitKammyCamY
f32 OrbitKammyCamY = 200.0
OrbitKammyFov
f32 OrbitKammyFov = 50.0
OrbitKammyTime
s32 OrbitKammyTime = 0
PanAcrossRoomAngle
f32 PanAcrossRoomAngle = 45.0
PanAcrossRoomCamX
f32 PanAcrossRoomCamX = 40.0
PanAcrossRoomCamZ
f32 PanAcrossRoomCamZ = -40.0
PanAcrossRoomTime
s32 PanAcrossRoomTime = 0
StarSpiritLeapBackScalars
s32 StarSpiritLeapBackScalars[]
Initial value:
= {
    EVT_FLOAT(0.93),  EVT_FLOAT(0.9),
    EVT_FLOAT(0.938), EVT_FLOAT(0.91),
    EVT_FLOAT(0.955), EVT_FLOAT(0.93),
    EVT_FLOAT(0.968), EVT_FLOAT(0.95),
    EVT_FLOAT(0.979), EVT_FLOAT(0.97),
    EVT_FLOAT(0.985), EVT_FLOAT(0.985),
    EVT_FLOAT(0.995), EVT_FLOAT(0.995),
    EVT_FLOAT(0.998), EVT_FLOAT(0.998),
    EVT_FLOAT(0.999), EVT_FLOAT(0.999),
    EVT_FLOAT(1.0),   EVT_FLOAT(1.0),
}
StarSpiritsPosX
BSS f32 StarSpiritsPosX[7]
StarSpiritsPosY
BSS f32 StarSpiritsPosY[7]
StarSpiritsPosZ
BSS f32 StarSpiritsPosZ[7]
StoryCameraAngle
f32 StoryCameraAngle = 240.0
StoryCameraShake1Angle
s32 StoryCameraShake1Angle = 0
StoryCameraShake1Scale
f32 StoryCameraShake1Scale = 1.0
StoryCameraShake2Angle
s32 StoryCameraShake2Angle = 0
StoryCameraShake2Scale
f32 StoryCameraShake2Scale = 12.0
StoryGraphics
BSS StoryGraphicData StoryGraphics
StoryGraphicsPtr
StoryGraphicData* StoryGraphicsPtr = & StoryGraphics
Referenced by draw_background_tape(), draw_foreground_bowser_silhouette(), load_story_image(), and worker_draw_story_graphics().
StoryPageDuration
s32 StoryPageDuration[]
Initial value:
= {
    [STORY_PAGE_BLANK]          222 * DT,
    [STORY_PAGE_STARRY_SKY]     338 * DT,
    [STORY_PAGE_SHRINE_EXT]     338 * DT,
    [STORY_PAGE_STAR_ROD]       338 * DT,
    [STORY_PAGE_SHRINE_INT]     622 * DT,
}
StoryPageState
s32 StoryPageState = STORY_PAGE_STATE_BEGIN
UnusedBowserHoverOffsets
s16 UnusedBowserHoverOffsets[]
Initial value:
= {
    -3, -2, -1,  0,  1,  2,  3,  4,
     3,  2,  1,  0, -1, -2, -3, -4,
}
UnusedBowserLeapBaseY
BSS f32 UnusedBowserLeapBaseY
UnusedBowserLeapPath
s16 UnusedBowserLeapPath[]
Initial value:
= {
    360, 345, 330, 315, 300, 285, 270, 255,
    240, 225, 215, 203, 191, 180, 170, 161, 153, 146, 140, 135
}
UnusedBowserLeapTime
s32 UnusedBowserLeapTime = 0
UnusedKammyHoverOffset
s16 UnusedKammyHoverOffset[]
Initial value:
= {
    -3, -2, -1,  0,  1,  2,  3,  4,
     3,  2,  1,  0, -1, -2, -3, -4,
}
UnusedKammyMoveBaseY
BSS f32 UnusedKammyMoveBaseY
UnusedKammyMovePath
Vec2s UnusedKammyMovePath[]
UnusedKammyMoveTime
s32 UnusedKammyMoveTime = 0
UnusedStoryCameraZoomAmt
f32 UnusedStoryCameraZoomAmt = 30.0