papermario: src/hud_element.c File Reference
hud_element.c File Reference
Data Structures
struct HudElementSize
Macros
#define MAX_HUD_CACHE_ENTRIES 192
Functions
void hud_element_setup_cam (void)
void hud_element_load_script (HudElement *hudElement, HudScript *anim)
void hud_element_draw_rect (HudElement *hudElement, s16 texSizeX, s16 texSizeY, s16 drawSizeX, s16 drawSizeY, s16 offsetX, s16 offsetY, s32 clamp, s32 dropShadow)
void hud_element_clear_cache (void)
void init_hud_element_list (void)
s32 hud_element_create (HudScript *anim)
Creates a new HUD element and returns its ID.
void update_hud_elements (void)
s32 hud_element_update (HudElement *hudElement)
void render_hud_elements_backUI (void)
void render_hud_elements_frontUI (void)
void render_hud_element (HudElement *hudElement)
void render_transformed_hud_elements (void)
void func_80143C48 (s32 elemID, s32 arg1, s32 camID)
void func_80144218 (s32 id)
void func_80144238 (s32 id)
void func_80144258 (s32 id)
void func_80144278 (s32 id)
void draw_hud_element_internal (s32 id, s32 clipMode)
void hud_element_draw_clipped (s32 id)
void hud_element_draw_next (s32 id)
void hud_element_draw_without_clipping (s32 id)
void hud_element_set_script (s32 id, HudScript *anim)
HudScript * hud_element_get_script (s32 id)
HudElement * get_hud_element (s32 id)
void hud_element_free (s32 id)
void hud_element_set_render_pos (s32 id, s32 x, s32 y)
void hud_element_get_render_pos (s32 id, s32 *x, s32 *y)
void hud_element_set_render_depth (s32 id, s32 z)
void hud_element_set_flags (s32 id, s32 flags)
Turns on the given flags.
void hud_element_clear_flags (s32 id, s32 flags)
Turns off the given flags.
void ALT_clear_hud_element_cache (void)
void hud_element_set_scale (s32 index, f32 scale)
void hud_element_use_preset_size (s32 id, s8 sizePreset)
s32 func_80144E4C (s32 id)
void func_80144E74 (s32 id, s32 arg1)
void hud_element_set_alpha (s32 id, s32 opacity)
void hud_element_set_tint (s32 id, s32 r, s32 g, s32 b)
void hud_element_create_transform_A (s32 id)
void hud_element_create_transform_B (s32 id)
void hud_element_create_transform_C (s32 id)
void hud_element_free_transform (s32 id)
void hud_element_set_transform_pos (s32 id, f32 x, f32 y, f32 z)
void hud_element_set_transform_scale (s32 id, f32 x, f32 y, f32 z)
void hud_element_set_transform_rotation (s32 id, f32 x, f32 y, f32 z)
void hud_element_set_transform_rotation_pivot (s32 id, s32 dx, s32 dy)
void copy_world_hud_element_ref_to_battle (s32 worldID, s32 battleID)
void hud_element_set_aux_cache (void *base, s32 size)
Variables
u8 * gHudElementAuxCache = NULL
s32 gHudElementCacheCapacity = 0x11000
HudScript HES_Empty
HudElementSize gHudElementSizes []
s16 D_8014F068 [] = { 34, 32, 0, 40, 40, 968, 0, 0 }
Gfx gHudElementsDLBackUI []
Gfx gHudElementsDLFrontUI []
Vtx D_8014F0C8 []
Lights1 HudElementLights = gdSPDefLights1(255, 255, 255, 0, 0, 0, 0, 0, 0)
s32 gHudElementsNumber
HudCacheEntry * gHudElementCacheTableRaster
HudCacheEntry * gHudElementCacheTablePalette
s32 * gHudElementCacheSize
u8 * gHudElementCacheBuffer
BSS HudElementList gHudElementsWorld
BSS HudElementList gHudElementsBattle
BSS HudElementList * gHudElements
BSS u8 * gHudElementCacheBufferWorld
BSS s32 gHudElementCacheSizeWorld
BSS s32 D_8015796C
BSS HudCacheEntry gHudElementCacheTableRasterWorld [192]
BSS HudCacheEntry gHudElementCacheTablePaletteWorld [192]
BSS u8 * gHudElementCacheBufferBattle
BSS s32 gHudElementCacheSizeBattle
BSS s32 D_80158578 [2]
BSS HudCacheEntry gHudElementCacheTableRasterBattle [192]
BSS HudCacheEntry gHudElementCacheTablePaletteBattle [192]
BSS s32 D_80159180
Data Structure Documentation
HudElementSize
struct HudElementSize
Data Fields
s16 height
s16 size
s16 width
Macro Definition Documentation
MAX_HUD_CACHE_ENTRIES
#define MAX_HUD_CACHE_ENTRIES 192
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_load_script(), and hud_element_update().
Function Documentation
ALT_clear_hud_element_cache()
void ALT_clear_hud_element_cache (void)
See also
hud_element_clear_cache
copy_world_hud_element_ref_to_battle()
void copy_world_hud_element_ref_to_battle (s32 worldID, s32 battleID)
Referenced by reset_status_bar().
draw_hud_element_internal()
void draw_hud_element_internal (s32 id, s32 clipMode)
Referenced by hud_element_draw_clipped(), hud_element_draw_next(), and hud_element_draw_without_clipping().
func_80143C48()
void func_80143C48 (s32 elemID, s32 arg1, s32 camID)
Referenced by func_80144218(), func_80144238(), func_80144258(), and func_80144278().
func_80144218()
void func_80144218 (s32 id)
Referenced by btl_main_menu_draw(), btl_message_popup_draw_content(), and btl_state_draw_celebration().
func_80144238()
void func_80144238 (s32 id)
Referenced by btl_main_menu_draw(), and btl_state_draw_celebration().
func_80144258()
void func_80144258 (s32 id)
func_80144278()
void func_80144278 (s32 id)
func_80144E4C()
s32 func_80144E4C (s32 id)
func_80144E74()
void func_80144E74 (s32 id, s32 arg1)
get_hud_element()
HudElement * get_hud_element (s32 id)
Referenced by update_all_status_icons().
hud_element_clear_cache()
void hud_element_clear_cache (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_file_select(), state_init_language_select(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_title_screen().
hud_element_clear_flags()
void hud_element_clear_flags (s32 id, s32 flags)
Turns off the given flags.
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_state_update_celebration(), btl_update_starpoints_display(), draw_all_status_icons(), initialize_status_bar(), pause_badges_draw_contents(), pause_items_draw_contents(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), pause_textbox_draw_contents(), status_bar_draw_number(), status_bar_draw_stat(), update(), and worker_update_phonograph_hud().
hud_element_create()
s32 hud_element_create (HudScript * anim)
Creates a new HUD element and returns its ID.
Referenced by btl_main_menu_update(), btl_state_update_celebration(), btl_state_update_select_target(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_strats_menu(), create_status_icon_boost_hammer(), create_status_icon_boost_jump(), create_status_icon_boost_partner(), create_status_icon_danger(), create_status_icon_peril(), create_status_icon_surprise(), filemenu_choose_name_init(), filemenu_init(), filemenu_main_init(), filemenu_selectlanguage_init(), initialize_battle(), initialize_status_bar(), pause_badges_init(), pause_init(), pause_items_init(), pause_map_init(), pause_partners_init(), pause_stats_init(), pause_tabs_init(), popup_menu_update(), show_coin_counter(), update_all_status_icons(), and update_item_entity_pickup().
hud_element_create_transform_A()
void hud_element_create_transform_A (s32 id)
hud_element_create_transform_B()
void hud_element_create_transform_B (s32 id)
Referenced by btl_main_menu_update(), btl_state_update_celebration(), and btl_update_message_popup().
hud_element_create_transform_C()
void hud_element_create_transform_C (s32 id)
hud_element_draw_clipped()
void hud_element_draw_clipped (s32 id)
Referenced by appendGfx_score_display(), btl_draw_enemy_health_bars(), btl_main_menu_draw(), btl_menu_moves_draw_content(), btl_menu_moves_show_icon(), btl_menu_strats_draw_content(), btl_message_popup_draw_content(), btl_state_draw_celebration(), btl_update_starpoints_display(), coin_counter_draw_content(), draw(), draw_shop_items(), func_800F4D28(), popup_draw_cost_icon(), worker_draw_mixing_game_ui(), and worker_draw_phonograph_hud().
hud_element_draw_next()
void hud_element_draw_next (s32 id)
Referenced by btl_draw_enemy_health_bars(), draw_all_status_icons(), draw_content_pickup_item_header(), filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), pause_badges_draw_contents(), pause_items_draw_contents(), pause_stats_draw_contents(), popup_menu_draw_menu_contents(), status_bar_draw_number(), status_bar_draw_stat(), and update_status_bar().
hud_element_draw_rect()
void hud_element_draw_rect (HudElement * hudElement, s16 texSizeX, s16 texSizeY, s16 drawSizeX, s16 drawSizeY, s16 offsetX, s16 offsetY, s32 clamp, s32 dropShadow)
Parameters
clamp 0 = repeat; 1 = clamp
dropShadow Whether to render a drop shadow or not
Referenced by draw_hud_element_internal(), render_hud_elements_backUI(), and render_hud_elements_frontUI().
hud_element_draw_without_clipping()
void hud_element_draw_without_clipping (s32 id)
Referenced by btl_menu_moves_draw_content(), btl_menu_strats_draw_content(), filemenu_draw_contents_choose_name(), filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), filemenu_draw_contents_mono(), filemenu_draw_contents_stereo(), filemenu_draw_cursor(), pause_badges_draw_contents(), pause_draw_cursor(), pause_items_draw_contents(), pause_map_draw_contents(), pause_partners_draw_movelist(), pause_partners_draw_movelist_flower(), pause_partners_draw_title(), pause_stats_draw_contents(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), pause_textbox_draw_contents(), pause_tutorial_draw_contents(), and popup_menu_draw_menu_contents().
hud_element_free()
void hud_element_free (s32 id)
Referenced by btl_main_menu_destroy(), btl_state_update_celebration(), btl_state_update_select_target(), btl_update_message_popup(), destroy_popup_menu(), filemenu_choose_name_cleanup(), filemenu_cleanup(), filemenu_main_cleanup(), filemenu_selectlanguage_cleanup(), free(), func_802A27E4(), func_802A472C(), pause_badges_cleanup(), pause_cleanup(), pause_items_cleanup(), pause_map_cleanup(), pause_partners_cleanup(), pause_stats_cleanup(), pause_tabs_cleanup(), remove_status_icon_boost_partner(), remove_status_icon_danger(), remove_status_icon_peril(), remove_status_icon_surprise(), show_coin_counter(), update_all_status_icons(), update_coin_counter(), update_hud_elements(), and update_item_entity_pickup().
hud_element_free_transform()
void hud_element_free_transform (s32 id)
Referenced by hud_element_free().
hud_element_get_render_pos()
void hud_element_get_render_pos (s32 id, s32 * x, s32 * y)
Referenced by btl_draw_upgrade_windows(), btl_state_update_celebration(), draw(), and worker_draw_phonograph_hud().
hud_element_get_script()
HudScript * hud_element_get_script (s32 id)
Referenced by btl_state_draw_celebration(), btl_state_draw_select_target(), btl_update_starpoints_display(), draw(), and update().
hud_element_load_script()
void hud_element_load_script (HudElement * hudElement, HudScript * anim)
Referenced by hud_element_create(), hud_element_set_script(), and hud_element_update().
hud_element_set_alpha()
void hud_element_set_alpha (s32 id, s32 opacity)
Parameters
opacity 0 = invisible; 255 = opaque
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_menu_moves_draw_content(), btl_menu_moves_show_icon(), btl_menu_strats_draw_content(), btl_message_popup_draw_content(), btl_state_draw_select_target(), btl_state_update_celebration(), filemenu_draw_cursor(), func_800F4D28(), pause_draw_cursor(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), popup_draw_cost_icon(), popup_menu_draw_menu_contents(), update(), and worker_update_phonograph_hud().
hud_element_set_aux_cache()
void hud_element_set_aux_cache (void * base, s32 size)
Referenced by state_init_file_select(), state_init_language_select(), state_step_battle(), state_step_end_battle(), state_step_exit_language_select(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_unpause().
hud_element_set_flags()
void hud_element_set_flags (s32 id, s32 flags)
Turns on the given flags.
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_state_update_celebration(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_starpoints_display(), btl_update_strats_menu(), create_status_icon_boost_hammer(), create_status_icon_boost_jump(), create_status_icon_boost_partner(), create_status_icon_danger(), create_status_icon_peril(), create_status_icon_surprise(), draw_all_status_icons(), filemenu_choose_name_init(), filemenu_init(), filemenu_main_init(), filemenu_selectlanguage_init(), initialize_battle(), initialize_status_bar(), pause_badges_draw_contents(), pause_badges_init(), pause_init(), pause_items_draw_contents(), pause_items_init(), pause_map_init(), pause_partners_init(), pause_stats_init(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), pause_tabs_init(), pause_textbox_draw_contents(), pause_tutorial_draw_contents(), popup_menu_update(), show_coin_counter(), update(), update_all_status_icons(), and update_item_entity_pickup().
hud_element_set_render_depth()
void hud_element_set_render_depth (s32 id, s32 z)
Referenced by btl_draw_enemy_health_bars(), btl_main_menu_update(), btl_state_update_select_target(), and initialize_battle().
hud_element_set_render_pos()
void hud_element_set_render_pos (s32 id, s32 x, s32 y)
Referenced by appendGfx_score_display(), btl_draw_enemy_health_bars(), btl_main_menu_draw(), btl_main_menu_update(), btl_menu_moves_draw_content(), btl_menu_moves_show_icon(), btl_menu_strats_draw_content(), btl_message_popup_draw_content(), btl_state_draw_celebration(), btl_state_draw_select_target(), btl_state_update_celebration(), btl_state_update_select_target(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_starpoints_display(), btl_update_strats_menu(), coin_counter_draw_content(), draw(), draw_all_status_icons(), draw_content_pickup_item_header(), draw_shop_items(), filemenu_draw_contents_choose_name(), filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), filemenu_draw_contents_mono(), filemenu_draw_contents_stereo(), filemenu_draw_cursor(), func_800F4D28(), pause_badges_draw_contents(), pause_draw_cursor(), pause_items_draw_contents(), pause_map_draw_contents(), pause_partners_draw_movelist(), pause_partners_draw_movelist_flower(), pause_partners_draw_title(), pause_stats_draw_contents(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), pause_textbox_draw_contents(), pause_tutorial_draw_contents(), popup_draw_cost_icon(), popup_menu_draw_menu_contents(), status_bar_draw_number(), status_bar_draw_stat(), update(), update_item_entity_pickup(), update_status_bar(), and worker_update_phonograph_hud().
hud_element_set_scale()
void hud_element_set_scale (s32 index, f32 scale)
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_message_popup_draw_content(), btl_state_update_celebration(), btl_submenu_moves_update(), btl_update_strats_menu(), draw_shop_items(), pause_badges_draw_contents(), pause_items_draw_contents(), pause_partners_draw_movelist(), pause_textbox_draw_contents(), pause_tutorial_draw_contents(), popup_menu_draw_menu_contents(), popup_menu_update(), and update().
hud_element_set_script()
void hud_element_set_script (s32 id, HudScript * anim)
Referenced by btl_draw_enemy_health_bars(), btl_menu_moves_draw_content(), btl_state_draw_celebration(), btl_state_draw_select_target(), btl_state_update_celebration(), btl_state_update_select_target(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_starpoints_display(), btl_update_strats_menu(), draw(), func_800F16CC(), func_802A2910(), func_802A2AB8(), func_802A47E0(), func_802A48FC(), pause_badges_draw_contents(), pause_items_draw_contents(), pause_stats_draw_contents(), pause_textbox_draw_contents(), popup_menu_draw_menu_contents(), popup_menu_update(), remove_status_icon_boost_hammer(), remove_status_icon_boost_jump(), status_bar_draw_number(), status_bar_draw_stat(), update(), update_all_status_icons(), update_item_entity_pickup(), update_status_bar(), and worker_update_phonograph_hud().
hud_element_set_tint()
void hud_element_set_tint (s32 id, s32 r, s32 g, s32 b)
Referenced by btl_main_menu_update(), btl_state_draw_celebration(), btl_state_update_celebration(), btl_submenu_moves_update(), btl_update_strats_menu(), func_800F16CC(), func_802A2910(), func_802A2AB8(), func_802A47E0(), func_802A48FC(), popup_menu_update(), and show_coin_counter().
hud_element_set_transform_pos()
void hud_element_set_transform_pos (s32 id, f32 x, f32 y, f32 z)
Referenced by btl_main_menu_draw().
hud_element_set_transform_rotation()
void hud_element_set_transform_rotation (s32 id, f32 x, f32 y, f32 z)
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_state_draw_celebration(), and btl_state_update_celebration().
hud_element_set_transform_rotation_pivot()
void hud_element_set_transform_rotation_pivot (s32 id, s32 dx, s32 dy)
Referenced by btl_main_menu_draw(), btl_main_menu_update(), and btl_state_update_celebration().
hud_element_set_transform_scale()
void hud_element_set_transform_scale (s32 id, f32 x, f32 y, f32 z)
Referenced by btl_main_menu_draw(), and btl_state_update_celebration().
hud_element_setup_cam()
void hud_element_setup_cam (void)
Referenced by hud_element_clear_cache(), hud_element_create_transform_A(), hud_element_create_transform_B(), and hud_element_create_transform_C().
hud_element_update()
s32 hud_element_update (HudElement * hudElement)
Returns
0 if frame is completed
Referenced by hud_element_create(), hud_element_set_script(), and update_hud_elements().
hud_element_use_preset_size()
void hud_element_use_preset_size (s32 id, s8 sizePreset)
init_hud_element_list()
void init_hud_element_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
render_hud_element()
void render_hud_element (HudElement * hudElement)
Referenced by func_80143C48(), and render_transformed_hud_elements().
render_hud_elements_backUI()
void render_hud_elements_backUI (void)
Referenced by gfx_draw_frame().
render_hud_elements_frontUI()
void render_hud_elements_frontUI (void)
Referenced by gfx_draw_frame().
render_transformed_hud_elements()
void render_transformed_hud_elements (void)
Referenced by render_frame().
update_hud_elements()
void update_hud_elements (void)
Referenced by step_game_loop().
Variable Documentation
D_8014F068
s16 D_8014F068[] = { 34, 32, 0, 40, 40, 968, 0, 0 }
D_8014F0C8
Vtx D_8014F0C8[]
Referenced by render_hud_element().
D_8015796C
BSS s32 D_8015796C
D_80158578
BSS s32 D_80158578[2]
D_80159180
BSS s32 D_80159180
Referenced by hud_element_clear_cache(), init_hud_element_list(), render_hud_element(), and render_hud_elements_backUI().
gHudElementAuxCache
u8* gHudElementAuxCache = NULL
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), and hud_element_set_aux_cache().
gHudElementCacheBuffer
u8* gHudElementCacheBuffer
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_load_script(), init_hud_element_list(), and item_entity_load().
gHudElementCacheBufferBattle
BSS u8* gHudElementCacheBufferBattle
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), and init_hud_element_list().
gHudElementCacheBufferWorld
BSS u8* gHudElementCacheBufferWorld
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), and init_hud_element_list().
gHudElementCacheCapacity
s32 gHudElementCacheCapacity = 0x11000
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_load_script(), and hud_element_set_aux_cache().
gHudElementCacheSize
s32* gHudElementCacheSize
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_load_script(), init_hud_element_list(), and item_entity_load().
gHudElementCacheSizeBattle
BSS s32 gHudElementCacheSizeBattle
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), and init_hud_element_list().
gHudElementCacheSizeWorld
BSS s32 gHudElementCacheSizeWorld
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), and init_hud_element_list().
gHudElementCacheTablePalette
HudCacheEntry* gHudElementCacheTablePalette
Referenced by ALT_clear_hud_element_cache(), appendGfx_item_entity(), hud_element_clear_cache(), hud_element_load_script(), init_hud_element_list(), item_entity_load(), and render_item_entities().
gHudElementCacheTablePaletteBattle
BSS HudCacheEntry gHudElementCacheTablePaletteBattle[192]
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_update(), and init_hud_element_list().
gHudElementCacheTablePaletteWorld
BSS HudCacheEntry gHudElementCacheTablePaletteWorld[192]
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_update(), and init_hud_element_list().
gHudElementCacheTableRaster
HudCacheEntry* gHudElementCacheTableRaster
Referenced by ALT_clear_hud_element_cache(), appendGfx_item_entity(), hud_element_clear_cache(), hud_element_load_script(), init_hud_element_list(), item_entity_load(), and render_item_entities().
gHudElementCacheTableRasterBattle
BSS HudCacheEntry gHudElementCacheTableRasterBattle[192]
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_update(), and init_hud_element_list().
gHudElementCacheTableRasterWorld
BSS HudCacheEntry gHudElementCacheTableRasterWorld[192]
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_update(), and init_hud_element_list().
gHudElements
BSS HudElementList* gHudElements
Referenced by func_80144E4C(), get_hud_element(), hud_element_clear_cache(), hud_element_create(), hud_element_free(), hud_element_get_script(), init_hud_element_list(), render_hud_elements_backUI(), render_hud_elements_frontUI(), render_transformed_hud_elements(), and update_hud_elements().
gHudElementsBattle
BSS HudElementList gHudElementsBattle
Referenced by copy_world_hud_element_ref_to_battle(), hud_element_clear_cache(), and init_hud_element_list().
gHudElementsDLBackUI
Gfx gHudElementsDLBackUI[]
Initial value:
= {
    gsDPSetScissor(G_SC_NON_INTERLACE, 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT),
    gsDPPipeSync(),
    gsSPSetOtherMode(G_SETOTHERMODE_H, G_MDSFT_ALPHADITHER, 18, G_AD_DISABLE | G_CD_DISABLE | G_CK_NONE | G_TC_FILT | G_TF_BILERP | G_TT_NONE | G_TL_TILE | G_TD_CLAMP | G_TP_NONE | G_CYC_1CYCLE),
    gsDPSetAlphaCompare(G_AC_NONE),
    gsSPEndDisplayList()
}
Referenced by render_hud_elements_backUI().
gHudElementsDLFrontUI
Gfx gHudElementsDLFrontUI[]
Initial value:
= {
    gsDPSetScissor(G_SC_NON_INTERLACE, 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT),
    gsDPPipeSync(),
    gsSPSetOtherMode(G_SETOTHERMODE_H, G_MDSFT_ALPHADITHER, 18, G_AD_DISABLE | G_CD_DISABLE | G_CK_NONE | G_TC_FILT | G_TF_BILERP | G_TT_NONE | G_TL_TILE | G_TD_CLAMP | G_TP_NONE | G_CYC_1CYCLE),
    gsDPSetAlphaCompare(G_AC_NONE),
    gsSPEndDisplayList()
}
Referenced by render_hud_elements_frontUI().
gHudElementSizes
HudElementSize gHudElementSizes[]
Initial value:
= {
    { 8, 8, 32 },
    { 16, 16, 128 },
    { 24, 24, 288 },
    { 32, 32, 512 },
    { 48, 48, 1152 },
    { 64, 64, 2048 },
    { 8, 16, 64 },
    { 16, 8, 64 },
    { 16, 24, 192 },
    { 16, 32, 256 },
    { 64, 32, 1024 },
    { 32, 16, 256 },
    { 12, 12, 72 },
    { 48, 24, 576 },
    { 32, 8, 128 },
    { 24, 8, 96 },
    { 64, 16, 512 },
    { 16, 64, 512 },
    { 192, 32, 3072 },
    { 40, 40, 800 },
    { 24, 16, 192 },
    { 32, 40, 640 },
    { 40, 16, 320 },
    { 40, 24, 480 },
    { 32, 24, 384 },
    { 20, 32, 0 }
}
Referenced by draw_hud_element_internal(), hud_element_load_script(), hud_element_set_scale(), hud_element_update(), render_hud_element(), render_hud_elements_backUI(), and render_hud_elements_frontUI().
gHudElementsNumber
s32 gHudElementsNumber
Referenced by hud_element_clear_cache(), hud_element_create(), hud_element_free(), and init_hud_element_list().
gHudElementsWorld
BSS HudElementList gHudElementsWorld
Referenced by copy_world_hud_element_ref_to_battle(), hud_element_clear_cache(), and init_hud_element_list().
HES_Empty
HudScript HES_Empty
Initial value:
= {
     HUD_ELEMENT_OP_End,
}
Referenced by hud_element_create(), and hud_element_set_script().
HudElementLights
Lights1 HudElementLights = gdSPDefLights1(255, 255, 255, 0, 0, 0, 0, 0, 0)
Referenced by func_80143C48(), and render_transformed_hud_elements().