papermario: src/hud_element.h File Reference
hud_element.h File Reference
Data Structures
struct HudCacheEntry
struct PopupMenu
struct Shop
struct IconHudScriptPair
struct VtxRect
struct HudTransform
struct HudElement
struct PartnerPopupProperties
Macros
#define HUD_ELEMENT_BATTLE_ID_MASK 0x800
#define HS_PTR(sym) (s32)&sym
#define hs_End HUD_ELEMENT_OP_End,
#define hs_SetRGBA(time, image) HUD_ELEMENT_OP_SetRGBA, time, (s32)image,
#define hs_SetCI(time, name) HUD_ELEMENT_OP_SetCI, time, (s32)name##_png, (s32)name##_pal,
#define hs_SetCI_Explicit(time, raster, palette) HUD_ELEMENT_OP_SetCI, time, (s32)raster##_png, (s32)palette##_pal,
#define hs_Restart HUD_ELEMENT_OP_Restart,
#define hs_Loop HUD_ELEMENT_OP_Loop,
#define hs_SetTileSize(size) HUD_ELEMENT_OP_SetTileSize, size,
#define hs_SetSizesAutoScale(size1, size2) HUD_ELEMENT_OP_SetSizesAutoScale, size1, size2,
#define hs_SetSizesFixedScale(size1, size2) HUD_ELEMENT_OP_SetSizesFixedScale, size1, size2,
#define hs_SetVisible HUD_ELEMENT_OP_SetVisible,
#define hs_SetHidden HUD_ELEMENT_OP_SetHidden,
#define hs_AddTexelOffsetX(x) HUD_ELEMENT_OP_AddTexelOffsetX, x,
#define hs_AddTexelOffsetY(y) HUD_ELEMENT_OP_AddTexelOffsetY, y,
#define hs_SetTexelOffset(x, y) HUD_ELEMENT_OP_SetTexelOffset, x, y,
#define hs_SetIcon(time, icon) HUD_ELEMENT_OP_SetImage, time, ICON_##icon##_raster, ICON_##icon##_palette, 0, 0,
#define hs_SetScale(scale) HUD_ELEMENT_OP_SetScale, (s32)(scale * 65536.0f),
#define hs_SetAlpha(alpha) HUD_ELEMENT_OP_SetAlpha, alpha,
#define hs_RandomDelay(arg0, arg1) HUD_ELEMENT_OP_RandomDelay, arg0, arg1,
#define hs_Delete HUD_ELEMENT_OP_Delete,
#define hs_UseIA8 HUD_ELEMENT_OP_UseIA8,
#define hs_SetCustomSize(arg0, arg1) HUD_ELEMENT_OP_SetCustomSize, arg0, arg1,
#define hs_RandomRestart(max, cutoff) HUD_ELEMENT_OP_RandomRestart, max, cutoff,
Restarts the loop if cutoff < rand_int(max)
#define hs_op_15(arg0) HUD_ELEMENT_OP_op_15, arg0,
#define hs_RandomBranch(args...) HUD_ELEMENT_OP_RandomBranch, (sizeof((s32[]){args})/sizeof(s32)), args,
#define hs_SetFlags(arg0) HUD_ELEMENT_OP_SetFlags, arg0,
#define hs_ClearFlags(arg0) HUD_ELEMENT_OP_ClearFlags, arg0,
#define hs_PlaySound(arg0) HUD_ELEMENT_OP_PlaySound, arg0,
#define hs_SetPivot(arg0, arg1) HUD_ELEMENT_OP_SetPivot, arg0, arg1,
#define HES_TEMPLATE_CI_ENUM_SIZE(name, sizeX, sizeY)
Basic HudScript used for static CI images, setting size with hs_SetTileSize.
#define HES_TEMPLATE_CI_CUSTOM_SIZE(name, sizeX, sizeY)
Basic HudScript used for static CI images, setting size with hs_SetCustomSize.
#define HES_TEMPLATE_STANDARD_ITEM(icon)
#define HES_TEMPLATE_HEART_PIECE()
#define HES_TEMPLATE_HEART()
#define HES_TEMPLATE_STAR_POINT()
#define HES_TEMPLATE_SMALL_STAR_POINT()
#define HES_TEMPLATE_HEART_POINT()
#define HES_TEMPLATE_FLOWER_POINT()
#define HES_TEMPLATE_STAR_PIECE()
#define HES_TEMPLATE_COIN()
#define HES_COIN_SPARKLE(dx, dy)
#define HES_TEMPLATE_COIN_SPARKLE()
Typedefs
typedef s32 HudScript[]
typedef HudElement * HudElementList[320]
Enumerations
enum {
HUD_ELEMENT_OP_End , HUD_ELEMENT_OP_SetRGBA , HUD_ELEMENT_OP_SetCI , HUD_ELEMENT_OP_Restart ,
HUD_ELEMENT_OP_Loop , HUD_ELEMENT_OP_SetTileSize , HUD_ELEMENT_OP_SetSizesAutoScale , HUD_ELEMENT_OP_SetSizesFixedScale ,
HUD_ELEMENT_OP_SetVisible , HUD_ELEMENT_OP_SetHidden , HUD_ELEMENT_OP_AddTexelOffsetX , HUD_ELEMENT_OP_AddTexelOffsetY ,
HUD_ELEMENT_OP_SetTexelOffset , HUD_ELEMENT_OP_SetImage , HUD_ELEMENT_OP_SetScale , HUD_ELEMENT_OP_SetAlpha ,
HUD_ELEMENT_OP_RandomDelay , HUD_ELEMENT_OP_Delete , HUD_ELEMENT_OP_UseIA8 , HUD_ELEMENT_OP_SetCustomSize ,
HUD_ELEMENT_OP_RandomRestart , HUD_ELEMENT_OP_op_15 , HUD_ELEMENT_OP_op_16 , HUD_ELEMENT_OP_RandomBranch ,
HUD_ELEMENT_OP_SetFlags , HUD_ELEMENT_OP_ClearFlags , HUD_ELEMENT_OP_PlaySound , HUD_ELEMENT_OP_SetPivot
}
enum {
HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_SIZE_16x16 , HUD_ELEMENT_SIZE_24x24 , HUD_ELEMENT_SIZE_32x32 ,
HUD_ELEMENT_SIZE_48x48 , HUD_ELEMENT_SIZE_64x64 , HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_SIZE_16x8 ,
HUD_ELEMENT_SIZE_16x24 , HUD_ELEMENT_SIZE_16x32 , HUD_ELEMENT_SIZE_64x32 , HUD_ELEMENT_SIZE_32x16 ,
HUD_ELEMENT_SIZE_12x12 , HUD_ELEMENT_SIZE_48x24 , HUD_ELEMENT_SIZE_32x8 , HUD_ELEMENT_SIZE_24x8 ,
HUD_ELEMENT_SIZE_64x16 , HUD_ELEMENT_SIZE_16x64 , HUD_ELEMENT_SIZE_192x32 , HUD_ELEMENT_SIZE_40x40 ,
HUD_ELEMENT_SIZE_24x16 , HUD_ELEMENT_SIZE_32x40 , HUD_ELEMENT_SIZE_40x16 , HUD_ELEMENT_SIZE_40x24 ,
HUD_ELEMENT_SIZE_32x24
}
enum HudElementFlags {
HUD_ELEMENT_FLAG_INITIALIZED = 0x00000001 , HUD_ELEMENT_FLAG_DISABLED = 0x00000002 , HUD_ELEMENT_FLAG_ANIMATION_FINISHED = 0x00000004 , HUD_ELEMENT_FLAG_8 = 0x00000008 ,
HUD_ELEMENT_FLAG_SCALED = 0x00000010 , HUD_ELEMENT_FLAG_TRANSPARENT = 0x00000020 , HUD_ELEMENT_FLAG_FRONTUI = 0x00000040 , HUD_ELEMENT_FLAG_80 = 0x00000080 ,
HUD_ELEMENT_FLAG_FIXEDSCALE = 0x00000100 , HUD_ELEMENT_FLAG_200 = 0x00000200 , HUD_ELEMENT_FLAG_BATTLE = 0x00000400 , HUD_ELEMENT_FLAG_REPEATED = 0x00000800 ,
HUD_ELEMENT_FLAG_FLIPX = 0x00001000 , HUD_ELEMENT_FLAG_FLIPY = 0x00002000 , HUD_ELEMENT_FLAG_FMT_CI4 = 0x00004000 , HUD_ELEMENT_FLAG_FILTER_TEX = 0x00008000 ,
HUD_ELEMENT_FLAG_TRANSFORM = 0x00010000 , HUD_ELEMENT_FLAG_NO_FOLD = 0x00020000 , HUD_ELEMENT_FLAG_DELETE = 0x00040000 , HUD_ELEMENT_FLAG_FMT_IA8 = 0x00080000 ,
HUD_ELEMENT_FLAG_CUSTOM_SIZE = 0x00100000 , HUD_ELEMENT_FLAG_200000 = 0x00200000 , HUD_ELEMENT_FLAG_MEMOFFSET = 0x00400000 , HUD_ELEMENT_FLAG_ANTIALIASING = 0x00800000 ,
HUD_ELEMENT_FLAG_1000000 = 0x01000000 , HUD_ELEMENT_FLAG_2000000 = 0x02000000 , HUD_ELEMENT_FLAG_4000000 = 0x04000000 , HUD_ELEMENT_FLAG_8000000 = 0x08000000 ,
HUD_ELEMENT_FLAG_10000000 = 0x10000000 , HUD_ELEMENT_FLAG_DROP_SHADOW = 0x20000000 , HUD_ELEMENT_FLAG_40000000 = 0x40000000 , HUD_ELEMENT_FLAG_80000000 = 0x80000000
}
enum { HUD_ELEMENT_DRAW_FIRST_WITH_CLIPPING = 0 , HUD_ELEMENT_DRAW_NEXT = 1 , HUD_ELEMENT_DRAW_FIRST_WITHOUT_CLIPPING = 2 }
Functions
void hud_element_load_script (HudElement *hudElement, HudScript *anim)
void hud_element_draw_rect (HudElement *hudElement, s16 texSizeX, s16 texSizeY, s16 drawSizeX, s16 drawSizeY, s16 offsetX, s16 offsetY, s32 clamp, s32 dropShadow)
void hud_element_clear_cache (void)
void init_hud_element_list (void)
s32 hud_element_create (HudScript *anim)
Creates a new HUD element and returns its ID.
void update_hud_elements (void)
s32 hud_element_update (HudElement *hudElement)
void render_hud_elements_backUI (void)
void render_hud_elements_frontUI (void)
void render_hud_element (HudElement *hudElement)
void render_transformed_hud_elements (void)
void func_80143C48 (s32 arg0, s32 arg1, s32 camID)
void func_80144218 (s32 arg0)
void func_80144238 (s32 arg0)
void func_80144258 (s32 arg0)
void func_80144278 (s32 arg0)
void draw_hud_element_internal (s32 id, s32 clipMode)
void hud_element_draw_clipped (s32 id)
void hud_element_draw_next (s32 id)
void hud_element_draw_without_clipping (s32 id)
void hud_element_set_script (s32 id, HudScript *anim)
HudScript * hud_element_get_script (s32 id)
HudElement * get_hud_element (s32 id)
void hud_element_free (s32 id)
void hud_element_set_render_pos (s32 id, s32 x, s32 y)
void hud_element_get_render_pos (s32 id, s32 *x, s32 *y)
void hud_element_set_render_depth (s32 id, s32 z)
void hud_element_set_flags (s32 id, s32 flags)
Turns on the given flags.
void hud_element_clear_flags (s32 id, s32 flags)
Turns off the given flags.
void ALT_clear_hud_element_cache (void)
void hud_element_set_scale (s32 index, f32 scale)
void hud_element_use_preset_size (s32 id, s8 size)
s32 func_80144E4C (s32 id)
void func_80144E74 (s32 id, s32 arg1)
void hud_element_set_alpha (s32 id, s32 opacity)
void hud_element_set_tint (s32 id, s32 r, s32 g, s32 b)
void hud_element_create_transform_A (s32 id)
void hud_element_create_transform_B (s32 id)
void hud_element_create_transform_C (s32 id)
void hud_element_free_transform (s32 id)
void hud_element_set_transform_pos (s32 id, f32 x, f32 y, f32 z)
void hud_element_set_transform_scale (s32 id, f32 x, f32 y, f32 z)
void hud_element_set_transform_rotation (s32 id, f32 x, f32 y, f32 z)
void hud_element_set_transform_rotation_pivot (s32 id, s32 dx, s32 dy)
void copy_world_hud_element_ref_to_battle (s32 worldID, s32 battleID)
void hud_element_set_aux_cache (void *base, s32 size)
void create_standard_popup_menu (PopupMenu *)
Variables
HudScript HES_AnimatedHandPointer
HudScript HES_StatusCoin
HudScript HES_Refund
HudScript HES_MenuTimes
PartnerPopupProperties gPartnerPopupProperties [13]
HudScript * wDisabledPartnerHudScripts []
HudScript * wPartnerHudScripts []
Data Structure Documentation
HudCacheEntry
struct HudCacheEntry
Data Fields
u8 * data
s32 id
PopupMenu
struct PopupMenu
Data Fields
s32 descMsg[32]
s32 dipMode
b32 enabled[32]
s32 initialPos
s32 nameMsg[32]
s32 numEntries
s32 popupType
HudScript * ptrIcon[32]
s16 result
s32 titleNumber
char unk_104[0x4]
char unk_188[0x4]
char unk_20C[0x4]
char unk_290[0x4]
char unk_314[0x4]
char unk_32E[0x2]
char unk_80[0x4]
s32 userIndex[32]
s32 value[32]
Shop
struct Shop
Data Fields
HudElemID costHID
s32 curItemSlot
s16 flags
s32 inventoryItemFlags
ShopItemLocation * itemDataPositions
PopupMenu itemSelectMenu
s16 numItems
s16 numSpecialPrices
ShopOwner * owner
s32 selectedStoreItemSlot
ShopItemData * staticInventory
ShopSellPriceData * staticPriceList
char unk_06[0x2]
s32 unk_358
IconHudScriptPair
struct IconHudScriptPair
Data Fields
HudScript * disabled
HudScript * enabled
VtxRect
struct VtxRect
Data Fields
Vtx vtx[4]
HudTransform
struct HudTransform
Data Fields
s32 imgfxIdx
Vec2s pivot
Vec3f pos
Vec3f rot
Vec3f scale
VtxRect unk_30[3]
HudElement
struct HudElement
Data Fields
HudScript * anim
Vec2bu customDrawSize
Vec2bu customImageSize
f32 deltaSizeX
f32 deltaSizeY
s8 drawSizePreset
u32 flags
s32 heightScale X10.
HudTransform * hudTransform
u8 * imageAddr
HudScript * loopStartPos
s32 memOffset
u8 opacity
u8 * paletteAddr
HudScript * readPos
s16 renderPosX
s16 renderPosY
Vec2b screenPosOffset
u8 sizeX
u8 sizeY
s8 tileSizePreset
Color_RGB8 tint
f32 uniformScale
f32 unkImgScale[2]
s8 updateTimer
s32 widthScale X10.
Vec3b worldPosOffset
PartnerPopupProperties
struct PartnerPopupProperties
Data Fields
s32 battleDescMsg
s32 nameMsg
s32 unk_04
s32 worldDescMsg
Macro Definition Documentation
HES_COIN_SPARKLE
#define HES_COIN_SPARKLE (dx, dy)
Value:
    { \
        hs_SetTexelOffset(dx, dy) \
        hs_SetIcon(1, anim_shimmer_0) \
        hs_SetIcon(1, anim_shimmer_1) \
        hs_SetIcon(1, anim_shimmer_2) \
        hs_SetIcon(2, anim_shimmer_6) \
        hs_SetIcon(1, anim_shimmer_2) \
        hs_SetIcon(1, anim_shimmer_3) \
        hs_SetIcon(1, anim_shimmer_6) \
        hs_SetIcon(1, anim_shimmer_4) \
        hs_SetIcon(1, anim_shimmer_6) \
        hs_SetIcon(1, anim_shimmer_5) \
        hs_SetIcon(16, anim_shimmer_6) \
        hs_End \
    }
HES_TEMPLATE_CI_CUSTOM_SIZE
#define HES_TEMPLATE_CI_CUSTOM_SIZE (name, sizeX, sizeY)
Value:
    { \
        hs_SetVisible \
        hs_SetCustomSize(sizeX, sizeY) \
        hs_Loop \
            hs_SetCI(60, name) \
        hs_Restart \
        hs_End \
    }
Basic HudScript used for static CI images, setting size with hs_SetCustomSize.
HES_TEMPLATE_CI_ENUM_SIZE
#define HES_TEMPLATE_CI_ENUM_SIZE (name, sizeX, sizeY)
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_##sizeX##x##sizeY) \
        hs_Loop \
            hs_SetCI(60, name) \
        hs_Restart \
        hs_End \
    }
Basic HudScript used for static CI images, setting size with hs_SetTileSize.
HES_TEMPLATE_COIN
#define HES_TEMPLATE_COIN ()
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_24x24) \
        hs_Loop \
            hs_op_15(0) \
            hs_SetIcon(3, anim_coin_0) \
            hs_SetIcon(3, anim_coin_1) \
            hs_SetIcon(3, anim_coin_4) \
            hs_SetIcon(3, anim_coin_5) \
            hs_SetIcon(3, anim_coin_6) \
            hs_SetIcon(3, anim_coin_7) \
            hs_SetIcon(3, anim_coin_8) \
            hs_SetIcon(3, anim_coin_9) \
            hs_RandomRestart(100, 70) \
            hs_op_15(1) \
            hs_SetIcon(3, anim_coin_0) \
            hs_SetIcon(2, anim_coin_1) \
            hs_SetIcon(1, anim_coin_2) \
            hs_SetIcon(1, anim_coin_3) \
            hs_SetIcon(2, anim_coin_4) \
            hs_SetIcon(3, anim_coin_5) \
            hs_SetIcon(3, anim_coin_6) \
            hs_SetIcon(3, anim_coin_7) \
            hs_SetIcon(3, anim_coin_8) \
            hs_SetIcon(3, anim_coin_9) \
        hs_Restart \
        hs_End \
    }
HES_TEMPLATE_COIN_SPARKLE
#define HES_TEMPLATE_COIN_SPARKLE ()
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_8x8) \
        hs_RandomBranch( \
            HS_PTR(HES_Item_CoinSparkleA), \
            HS_PTR(HES_Item_CoinSparkleB), \
            HS_PTR(HES_Item_CoinSparkleC), \
            HS_PTR(HES_Item_CoinSparkleD), \
            HS_PTR(HES_Item_CoinSparkleE)) \
        hs_End \
    }
HES_TEMPLATE_FLOWER_POINT
#define HES_TEMPLATE_FLOWER_POINT ()
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_32x32) \
        hs_Loop \
            hs_SetIcon(8, anim_fp_0) \
            hs_SetIcon(5, anim_fp_1) \
            hs_SetIcon(8, anim_fp_2) \
        hs_Restart \
        hs_End \
    }
HES_TEMPLATE_HEART
#define HES_TEMPLATE_HEART ()
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_24x24) \
        hs_Loop \
            hs_SetIcon(10, anim_heart_0) \
            hs_SetIcon(6, anim_heart_1) \
        hs_Restart \
        hs_End \
    }
HES_TEMPLATE_HEART_PIECE
#define HES_TEMPLATE_HEART_PIECE ()
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_24x24) \
        hs_Loop \
            hs_SetIcon(60, anim_heart_piece) \
        hs_Restart \
        hs_End \
    }
HES_TEMPLATE_HEART_POINT
#define HES_TEMPLATE_HEART_POINT ()
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_32x32) \
        hs_Loop \
            hs_SetIcon(8, anim_hp_0) \
            hs_SetIcon(5, anim_hp_1) \
            hs_SetIcon(8, anim_hp_2) \
        hs_Restart \
        hs_End \
    }
HES_TEMPLATE_SMALL_STAR_POINT
#define HES_TEMPLATE_SMALL_STAR_POINT ()
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_8x8) \
        hs_Loop \
            hs_SetIcon(2, anim_sp_small_0) \
            hs_SetIcon(2, anim_sp_small_1) \
            hs_SetIcon(2, anim_sp_small_2) \
            hs_SetIcon(2, anim_sp_small_3) \
            hs_SetIcon(2, anim_sp_small_4) \
            hs_SetIcon(2, anim_sp_small_5) \
            hs_SetIcon(2, anim_sp_small_6) \
            hs_SetIcon(2, anim_sp_small_7) \
        hs_Restart \
        hs_End \
    }
HES_TEMPLATE_STANDARD_ITEM
#define HES_TEMPLATE_STANDARD_ITEM (icon)
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_32x32) \
        hs_Loop \
            hs_SetIcon(60, icon) \
        hs_Restart \
        hs_End \
    }
HES_TEMPLATE_STAR_PIECE
#define HES_TEMPLATE_STAR_PIECE ()
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_32x32) \
        hs_Loop \
            hs_SetIcon(12, anim_star_piece_0) \
            hs_SetIcon(4, anim_star_piece_1) \
            hs_SetIcon(12, anim_star_piece_2) \
            hs_SetIcon(4, anim_star_piece_1) \
        hs_Restart \
        hs_End \
    }
HES_TEMPLATE_STAR_POINT
#define HES_TEMPLATE_STAR_POINT ()
Value:
    { \
        hs_SetVisible \
        hs_SetTileSize(HUD_ELEMENT_SIZE_24x24) \
        hs_Loop \
            hs_SetIcon(2, anim_sp_0) \
            hs_SetIcon(2, anim_sp_1) \
            hs_SetIcon(2, anim_sp_2) \
            hs_SetIcon(2, anim_sp_3) \
            hs_SetIcon(2, anim_sp_4) \
            hs_SetIcon(2, anim_sp_5) \
            hs_SetIcon(2, anim_sp_6) \
            hs_SetIcon(2, anim_sp_7) \
        hs_Restart \
        hs_End \
    }
hs_AddTexelOffsetX
#define hs_AddTexelOffsetX (x) HUD_ELEMENT_OP_AddTexelOffsetX, x,
hs_AddTexelOffsetY
#define hs_AddTexelOffsetY (y) HUD_ELEMENT_OP_AddTexelOffsetY, y,
hs_ClearFlags
#define hs_ClearFlags (arg0) HUD_ELEMENT_OP_ClearFlags, arg0,
hs_Delete
#define hs_Delete HUD_ELEMENT_OP_Delete,
hs_End
#define hs_End HUD_ELEMENT_OP_End,
hs_Loop
#define hs_Loop HUD_ELEMENT_OP_Loop,
hs_op_15
#define hs_op_15 (arg0) HUD_ELEMENT_OP_op_15, arg0,
hs_PlaySound
#define hs_PlaySound (arg0) HUD_ELEMENT_OP_PlaySound, arg0,
HS_PTR
#define HS_PTR (sym) (s32)&sym
hs_RandomBranch
#define hs_RandomBranch (args...) HUD_ELEMENT_OP_RandomBranch, (sizeof((s32[]){args})/sizeof(s32)), args,
hs_RandomDelay
#define hs_RandomDelay (arg0, arg1) HUD_ELEMENT_OP_RandomDelay, arg0, arg1,
hs_RandomRestart
#define hs_RandomRestart (max, cutoff) HUD_ELEMENT_OP_RandomRestart, max, cutoff,
Restarts the loop if cutoff < rand_int(max)
hs_Restart
#define hs_Restart HUD_ELEMENT_OP_Restart,
hs_SetAlpha
#define hs_SetAlpha (alpha) HUD_ELEMENT_OP_SetAlpha, alpha,
hs_SetCI
#define hs_SetCI (time, name) HUD_ELEMENT_OP_SetCI, time, (s32)name##_png, (s32)name##_pal,
hs_SetCI_Explicit
#define hs_SetCI_Explicit (time, raster, palette) HUD_ELEMENT_OP_SetCI, time, (s32)raster##_png, (s32)palette##_pal,
hs_SetCustomSize
#define hs_SetCustomSize (arg0, arg1) HUD_ELEMENT_OP_SetCustomSize, arg0, arg1,
hs_SetFlags
#define hs_SetFlags (arg0) HUD_ELEMENT_OP_SetFlags, arg0,
hs_SetHidden
#define hs_SetHidden HUD_ELEMENT_OP_SetHidden,
hs_SetIcon
#define hs_SetIcon (time, icon) HUD_ELEMENT_OP_SetImage, time, ICON_##icon##_raster, ICON_##icon##_palette, 0, 0,
hs_SetPivot
#define hs_SetPivot (arg0, arg1) HUD_ELEMENT_OP_SetPivot, arg0, arg1,
hs_SetRGBA
#define hs_SetRGBA (time, image) HUD_ELEMENT_OP_SetRGBA, time, (s32)image,
hs_SetScale
#define hs_SetScale (scale) HUD_ELEMENT_OP_SetScale, (s32)(scale * 65536.0f),
hs_SetSizesAutoScale
#define hs_SetSizesAutoScale (size1, size2) HUD_ELEMENT_OP_SetSizesAutoScale, size1, size2,
hs_SetSizesFixedScale
#define hs_SetSizesFixedScale (size1, size2) HUD_ELEMENT_OP_SetSizesFixedScale, size1, size2,
hs_SetTexelOffset
#define hs_SetTexelOffset (x, y) HUD_ELEMENT_OP_SetTexelOffset, x, y,
hs_SetTileSize
#define hs_SetTileSize (size) HUD_ELEMENT_OP_SetTileSize, size,
hs_SetVisible
#define hs_SetVisible HUD_ELEMENT_OP_SetVisible,
hs_UseIA8
#define hs_UseIA8 HUD_ELEMENT_OP_UseIA8,
HUD_ELEMENT_BATTLE_ID_MASK
#define HUD_ELEMENT_BATTLE_ID_MASK 0x800
Referenced by func_80144E4C(), hud_element_create(), and hud_element_free().
Typedef Documentation
HudElementList
typedef HudElement* HudElementList[320]
HudScript
typedef s32 HudScript[]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HUD_ELEMENT_OP_End
HUD_ELEMENT_OP_SetRGBA
HUD_ELEMENT_OP_SetCI
HUD_ELEMENT_OP_Restart
HUD_ELEMENT_OP_Loop
HUD_ELEMENT_OP_SetTileSize
HUD_ELEMENT_OP_SetSizesAutoScale
HUD_ELEMENT_OP_SetSizesFixedScale
HUD_ELEMENT_OP_SetVisible
HUD_ELEMENT_OP_SetHidden
HUD_ELEMENT_OP_AddTexelOffsetX
HUD_ELEMENT_OP_AddTexelOffsetY
HUD_ELEMENT_OP_SetTexelOffset
HUD_ELEMENT_OP_SetImage
HUD_ELEMENT_OP_SetScale
HUD_ELEMENT_OP_SetAlpha
HUD_ELEMENT_OP_RandomDelay
HUD_ELEMENT_OP_Delete
HUD_ELEMENT_OP_UseIA8
HUD_ELEMENT_OP_SetCustomSize
HUD_ELEMENT_OP_RandomRestart
HUD_ELEMENT_OP_op_15
HUD_ELEMENT_OP_op_16
HUD_ELEMENT_OP_RandomBranch
HUD_ELEMENT_OP_SetFlags
HUD_ELEMENT_OP_ClearFlags
HUD_ELEMENT_OP_PlaySound
HUD_ELEMENT_OP_SetPivot
anonymous enum
anonymous enum
Enumerator
HUD_ELEMENT_SIZE_8x8
HUD_ELEMENT_SIZE_16x16
HUD_ELEMENT_SIZE_24x24
HUD_ELEMENT_SIZE_32x32
HUD_ELEMENT_SIZE_48x48
HUD_ELEMENT_SIZE_64x64
HUD_ELEMENT_SIZE_8x16
HUD_ELEMENT_SIZE_16x8
HUD_ELEMENT_SIZE_16x24
HUD_ELEMENT_SIZE_16x32
HUD_ELEMENT_SIZE_64x32
HUD_ELEMENT_SIZE_32x16
HUD_ELEMENT_SIZE_12x12
HUD_ELEMENT_SIZE_48x24
HUD_ELEMENT_SIZE_32x8
HUD_ELEMENT_SIZE_24x8
HUD_ELEMENT_SIZE_64x16
HUD_ELEMENT_SIZE_16x64
HUD_ELEMENT_SIZE_192x32
HUD_ELEMENT_SIZE_40x40
HUD_ELEMENT_SIZE_24x16
HUD_ELEMENT_SIZE_32x40
HUD_ELEMENT_SIZE_40x16
HUD_ELEMENT_SIZE_40x24
HUD_ELEMENT_SIZE_32x24
anonymous enum
anonymous enum
Enumerator
HUD_ELEMENT_DRAW_FIRST_WITH_CLIPPING
HUD_ELEMENT_DRAW_NEXT
HUD_ELEMENT_DRAW_FIRST_WITHOUT_CLIPPING
HudElementFlags
enum HudElementFlags
Enumerator
HUD_ELEMENT_FLAG_INITIALIZED
HUD_ELEMENT_FLAG_DISABLED
HUD_ELEMENT_FLAG_ANIMATION_FINISHED
HUD_ELEMENT_FLAG_8
HUD_ELEMENT_FLAG_SCALED
HUD_ELEMENT_FLAG_TRANSPARENT
HUD_ELEMENT_FLAG_FRONTUI
HUD_ELEMENT_FLAG_80
HUD_ELEMENT_FLAG_FIXEDSCALE
HUD_ELEMENT_FLAG_200
HUD_ELEMENT_FLAG_BATTLE
HUD_ELEMENT_FLAG_REPEATED
HUD_ELEMENT_FLAG_FLIPX
HUD_ELEMENT_FLAG_FLIPY
HUD_ELEMENT_FLAG_FMT_CI4
HUD_ELEMENT_FLAG_FILTER_TEX
HUD_ELEMENT_FLAG_TRANSFORM
HUD_ELEMENT_FLAG_NO_FOLD
HUD_ELEMENT_FLAG_DELETE
HUD_ELEMENT_FLAG_FMT_IA8
HUD_ELEMENT_FLAG_CUSTOM_SIZE
HUD_ELEMENT_FLAG_200000
HUD_ELEMENT_FLAG_MEMOFFSET
HUD_ELEMENT_FLAG_ANTIALIASING
HUD_ELEMENT_FLAG_1000000
HUD_ELEMENT_FLAG_2000000
HUD_ELEMENT_FLAG_4000000
HUD_ELEMENT_FLAG_8000000
HUD_ELEMENT_FLAG_10000000
HUD_ELEMENT_FLAG_DROP_SHADOW
HUD_ELEMENT_FLAG_40000000
HUD_ELEMENT_FLAG_80000000
Function Documentation
ALT_clear_hud_element_cache()
void ALT_clear_hud_element_cache (void)
See also
hud_element_clear_cache
copy_world_hud_element_ref_to_battle()
void copy_world_hud_element_ref_to_battle (s32 worldID, s32 battleID)
Referenced by reset_status_bar().
create_standard_popup_menu()
void create_standard_popup_menu (PopupMenu * popup)
Referenced by check_input_open_menus(), and update_item_entity_pickup().
draw_hud_element_internal()
void draw_hud_element_internal (s32 id, s32 clipMode)
Referenced by hud_element_draw_clipped(), hud_element_draw_next(), and hud_element_draw_without_clipping().
func_80143C48()
void func_80143C48 (s32 arg0, s32 arg1, s32 camID)
Referenced by func_80144218(), func_80144238(), func_80144258(), and func_80144278().
func_80144218()
void func_80144218 (s32 arg0)
Referenced by btl_main_menu_draw(), btl_message_popup_draw_content(), and btl_state_draw_celebration().
func_80144238()
void func_80144238 (s32 arg0)
Referenced by btl_main_menu_draw(), and btl_state_draw_celebration().
func_80144258()
void func_80144258 (s32 arg0)
func_80144278()
void func_80144278 (s32 arg0)
func_80144E4C()
s32 func_80144E4C (s32 id)
func_80144E74()
void func_80144E74 (s32 id, s32 arg1)
get_hud_element()
HudElement * get_hud_element (s32 id)
Referenced by update_all_status_icons().
hud_element_clear_cache()
void hud_element_clear_cache (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_file_select(), state_init_language_select(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_title_screen().
hud_element_clear_flags()
void hud_element_clear_flags (s32 id, s32 flags)
Turns off the given flags.
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_state_update_celebration(), btl_update_starpoints_display(), draw_all_status_icons(), initialize_status_bar(), pause_badges_draw_contents(), pause_items_draw_contents(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), pause_textbox_draw_contents(), status_bar_draw_number(), status_bar_draw_stat(), update(), and worker_update_phonograph_hud().
hud_element_create()
s32 hud_element_create (HudScript * anim)
Creates a new HUD element and returns its ID.
Referenced by btl_main_menu_update(), btl_state_update_celebration(), btl_state_update_select_target(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_strats_menu(), create_status_icon_boost_hammer(), create_status_icon_boost_jump(), create_status_icon_boost_partner(), create_status_icon_danger(), create_status_icon_peril(), create_status_icon_surprise(), filemenu_choose_name_init(), filemenu_init(), filemenu_main_init(), filemenu_selectlanguage_init(), initialize_battle(), initialize_status_bar(), pause_badges_init(), pause_init(), pause_items_init(), pause_map_init(), pause_partners_init(), pause_stats_init(), pause_tabs_init(), popup_menu_update(), show_coin_counter(), update_all_status_icons(), and update_item_entity_pickup().
hud_element_create_transform_A()
void hud_element_create_transform_A (s32 id)
hud_element_create_transform_B()
void hud_element_create_transform_B (s32 id)
Referenced by btl_main_menu_update(), btl_state_update_celebration(), and btl_update_message_popup().
hud_element_create_transform_C()
void hud_element_create_transform_C (s32 id)
hud_element_draw_clipped()
void hud_element_draw_clipped (s32 id)
Referenced by appendGfx_score_display(), btl_draw_enemy_health_bars(), btl_main_menu_draw(), btl_menu_moves_draw_content(), btl_menu_moves_show_icon(), btl_menu_strats_draw_content(), btl_message_popup_draw_content(), btl_state_draw_celebration(), btl_update_starpoints_display(), coin_counter_draw_content(), draw(), draw_shop_items(), func_800F4D28(), popup_draw_cost_icon(), worker_draw_mixing_game_ui(), and worker_draw_phonograph_hud().
hud_element_draw_next()
void hud_element_draw_next (s32 id)
Referenced by btl_draw_enemy_health_bars(), draw_all_status_icons(), draw_content_pickup_item_header(), filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), pause_badges_draw_contents(), pause_items_draw_contents(), pause_stats_draw_contents(), popup_menu_draw_menu_contents(), status_bar_draw_number(), status_bar_draw_stat(), and update_status_bar().
hud_element_draw_rect()
void hud_element_draw_rect (HudElement * hudElement, s16 texSizeX, s16 texSizeY, s16 drawSizeX, s16 drawSizeY, s16 offsetX, s16 offsetY, s32 clamp, s32 dropShadow)
Parameters
clamp 0 = repeat; 1 = clamp
dropShadow Whether to render a drop shadow or not
Referenced by draw_hud_element_internal(), render_hud_elements_backUI(), and render_hud_elements_frontUI().
hud_element_draw_without_clipping()
void hud_element_draw_without_clipping (s32 id)
Referenced by btl_menu_moves_draw_content(), btl_menu_strats_draw_content(), filemenu_draw_contents_choose_name(), filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), filemenu_draw_contents_mono(), filemenu_draw_contents_stereo(), filemenu_draw_cursor(), pause_badges_draw_contents(), pause_draw_cursor(), pause_items_draw_contents(), pause_map_draw_contents(), pause_partners_draw_movelist(), pause_partners_draw_movelist_flower(), pause_partners_draw_title(), pause_stats_draw_contents(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), pause_textbox_draw_contents(), pause_tutorial_draw_contents(), and popup_menu_draw_menu_contents().
hud_element_free()
void hud_element_free (s32 id)
Referenced by btl_main_menu_destroy(), btl_state_update_celebration(), btl_state_update_select_target(), btl_update_message_popup(), destroy_popup_menu(), filemenu_choose_name_cleanup(), filemenu_cleanup(), filemenu_main_cleanup(), filemenu_selectlanguage_cleanup(), free(), func_802A27E4(), func_802A472C(), pause_badges_cleanup(), pause_cleanup(), pause_items_cleanup(), pause_map_cleanup(), pause_partners_cleanup(), pause_stats_cleanup(), pause_tabs_cleanup(), remove_status_icon_boost_partner(), remove_status_icon_danger(), remove_status_icon_peril(), remove_status_icon_surprise(), show_coin_counter(), update_all_status_icons(), update_coin_counter(), update_hud_elements(), and update_item_entity_pickup().
hud_element_free_transform()
void hud_element_free_transform (s32 id)
Referenced by hud_element_free().
hud_element_get_render_pos()
void hud_element_get_render_pos (s32 id, s32 * x, s32 * y)
Referenced by btl_draw_upgrade_windows(), btl_state_update_celebration(), draw(), and worker_draw_phonograph_hud().
hud_element_get_script()
HudScript * hud_element_get_script (s32 id)
Referenced by btl_state_draw_celebration(), btl_state_draw_select_target(), btl_update_starpoints_display(), draw(), and update().
hud_element_load_script()
void hud_element_load_script (HudElement * hudElement, HudScript * anim)
Referenced by hud_element_create(), hud_element_set_script(), and hud_element_update().
hud_element_set_alpha()
void hud_element_set_alpha (s32 id, s32 opacity)
Parameters
opacity 0 = invisible; 255 = opaque
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_menu_moves_draw_content(), btl_menu_moves_show_icon(), btl_menu_strats_draw_content(), btl_message_popup_draw_content(), btl_state_draw_select_target(), btl_state_update_celebration(), filemenu_draw_cursor(), func_800F4D28(), pause_draw_cursor(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), popup_draw_cost_icon(), popup_menu_draw_menu_contents(), update(), and worker_update_phonograph_hud().
hud_element_set_aux_cache()
void hud_element_set_aux_cache (void * base, s32 size)
Referenced by state_init_file_select(), state_init_language_select(), state_step_battle(), state_step_end_battle(), state_step_exit_language_select(), state_step_language_select(), state_step_pause(), state_step_startup(), and state_step_unpause().
hud_element_set_flags()
void hud_element_set_flags (s32 id, s32 flags)
Turns on the given flags.
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_state_update_celebration(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_starpoints_display(), btl_update_strats_menu(), create_status_icon_boost_hammer(), create_status_icon_boost_jump(), create_status_icon_boost_partner(), create_status_icon_danger(), create_status_icon_peril(), create_status_icon_surprise(), draw_all_status_icons(), filemenu_choose_name_init(), filemenu_init(), filemenu_main_init(), filemenu_selectlanguage_init(), initialize_battle(), initialize_status_bar(), pause_badges_draw_contents(), pause_badges_init(), pause_init(), pause_items_draw_contents(), pause_items_init(), pause_map_init(), pause_partners_init(), pause_stats_init(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), pause_tabs_init(), pause_textbox_draw_contents(), pause_tutorial_draw_contents(), popup_menu_update(), show_coin_counter(), update(), update_all_status_icons(), and update_item_entity_pickup().
hud_element_set_render_depth()
void hud_element_set_render_depth (s32 id, s32 z)
Referenced by btl_draw_enemy_health_bars(), btl_main_menu_update(), btl_state_update_select_target(), and initialize_battle().
hud_element_set_render_pos()
void hud_element_set_render_pos (s32 id, s32 x, s32 y)
Referenced by appendGfx_score_display(), btl_draw_enemy_health_bars(), btl_main_menu_draw(), btl_main_menu_update(), btl_menu_moves_draw_content(), btl_menu_moves_show_icon(), btl_menu_strats_draw_content(), btl_message_popup_draw_content(), btl_state_draw_celebration(), btl_state_draw_select_target(), btl_state_update_celebration(), btl_state_update_select_target(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_starpoints_display(), btl_update_strats_menu(), coin_counter_draw_content(), draw(), draw_all_status_icons(), draw_content_pickup_item_header(), draw_shop_items(), filemenu_draw_contents_choose_name(), filemenu_draw_contents_file_create_header(), filemenu_draw_contents_file_info(), filemenu_draw_contents_mono(), filemenu_draw_contents_stereo(), filemenu_draw_cursor(), func_800F4D28(), pause_badges_draw_contents(), pause_draw_cursor(), pause_items_draw_contents(), pause_map_draw_contents(), pause_partners_draw_movelist(), pause_partners_draw_movelist_flower(), pause_partners_draw_title(), pause_stats_draw_contents(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), pause_textbox_draw_contents(), pause_tutorial_draw_contents(), popup_draw_cost_icon(), popup_menu_draw_menu_contents(), status_bar_draw_number(), status_bar_draw_stat(), update(), update_item_entity_pickup(), update_status_bar(), and worker_update_phonograph_hud().
hud_element_set_scale()
void hud_element_set_scale (s32 index, f32 scale)
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_message_popup_draw_content(), btl_state_update_celebration(), btl_submenu_moves_update(), btl_update_strats_menu(), draw_shop_items(), pause_badges_draw_contents(), pause_items_draw_contents(), pause_partners_draw_movelist(), pause_textbox_draw_contents(), pause_tutorial_draw_contents(), popup_menu_draw_menu_contents(), popup_menu_update(), and update().
hud_element_set_script()
void hud_element_set_script (s32 id, HudScript * anim)
Referenced by btl_draw_enemy_health_bars(), btl_menu_moves_draw_content(), btl_state_draw_celebration(), btl_state_draw_select_target(), btl_state_update_celebration(), btl_state_update_select_target(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_starpoints_display(), btl_update_strats_menu(), draw(), func_800F16CC(), func_802A2910(), func_802A2AB8(), func_802A47E0(), func_802A48FC(), pause_badges_draw_contents(), pause_items_draw_contents(), pause_stats_draw_contents(), pause_textbox_draw_contents(), popup_menu_draw_menu_contents(), popup_menu_update(), remove_status_icon_boost_hammer(), remove_status_icon_boost_jump(), status_bar_draw_number(), status_bar_draw_stat(), update(), update_all_status_icons(), update_item_entity_pickup(), update_status_bar(), and worker_update_phonograph_hud().
hud_element_set_tint()
void hud_element_set_tint (s32 id, s32 r, s32 g, s32 b)
Referenced by btl_main_menu_update(), btl_state_draw_celebration(), btl_state_update_celebration(), btl_submenu_moves_update(), btl_update_strats_menu(), func_800F16CC(), func_802A2910(), func_802A2AB8(), func_802A47E0(), func_802A48FC(), popup_menu_update(), and show_coin_counter().
hud_element_set_transform_pos()
void hud_element_set_transform_pos (s32 id, f32 x, f32 y, f32 z)
Referenced by btl_main_menu_draw().
hud_element_set_transform_rotation()
void hud_element_set_transform_rotation (s32 id, f32 x, f32 y, f32 z)
Referenced by btl_main_menu_draw(), btl_main_menu_update(), btl_state_draw_celebration(), and btl_state_update_celebration().
hud_element_set_transform_rotation_pivot()
void hud_element_set_transform_rotation_pivot (s32 id, s32 dx, s32 dy)
Referenced by btl_main_menu_draw(), btl_main_menu_update(), and btl_state_update_celebration().
hud_element_set_transform_scale()
void hud_element_set_transform_scale (s32 id, f32 x, f32 y, f32 z)
Referenced by btl_main_menu_draw(), and btl_state_update_celebration().
hud_element_update()
s32 hud_element_update (HudElement * hudElement)
Returns
0 if frame is completed
Referenced by hud_element_create(), hud_element_set_script(), and update_hud_elements().
hud_element_use_preset_size()
void hud_element_use_preset_size (s32 id, s8 size)
init_hud_element_list()
void init_hud_element_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
render_hud_element()
void render_hud_element (HudElement * hudElement)
Referenced by func_80143C48(), and render_transformed_hud_elements().
render_hud_elements_backUI()
void render_hud_elements_backUI (void)
Referenced by gfx_draw_frame().
render_hud_elements_frontUI()
void render_hud_elements_frontUI (void)
Referenced by gfx_draw_frame().
render_transformed_hud_elements()
void render_transformed_hud_elements (void)
Referenced by render_frame().
update_hud_elements()
void update_hud_elements (void)
Referenced by step_game_loop().
Variable Documentation
gPartnerPopupProperties
PartnerPopupProperties gPartnerPopupProperties[13] extern
Referenced by btl_state_update_partner_menu(), btl_state_update_player_menu(), pause_partners_draw_title(), and setup_partner_popup().
HES_AnimatedHandPointer
HudScript HES_AnimatedHandPointer extern
Referenced by btl_submenu_moves_update(), btl_update_strats_menu(), func_800F16CC(), func_802A2910(), func_802A2AB8(), func_802A47E0(), func_802A48FC(), and popup_menu_update().
HES_MenuTimes
HudScript HES_MenuTimes extern
Referenced by popup_menu_update(), and show_coin_counter().
HES_Refund
HudScript HES_Refund extern
HES_StatusCoin
HudScript HES_StatusCoin extern
Referenced by initialize_status_bar(), popup_menu_update(), and show_coin_counter().
wDisabledPartnerHudScripts
HudScript* wDisabledPartnerHudScripts[] extern
Referenced by setup_partner_popup().
wPartnerHudScripts
HudScript* wPartnerHudScripts[] extern
Referenced by setup_partner_popup().