papermario: src/effects/huff_puff_breath.c File Reference
huff_puff_breath.c File Reference
Functions
void huff_puff_breath_init (EffectInstance *effect)
void huff_puff_breath_update (EffectInstance *effect)
void huff_puff_breath_render (EffectInstance *effect)
void huff_puff_breath_appendGfx (void *effect)
EffectInstance * huff_puff_breath_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 angle, f32 speed, f32 scale, s32 timeLeft)
void func_E00DC2FC (void)
Variables
Gfx D_09000400_3D84C0 []
Gfx D_090005E8_3D86A8 []
Gfx D_09000628_3D86E8 []
Gfx * D_E00DC640 [] = { D_09000628_3D86E8, D_090005E8_3D86A8 }
Gfx * D_E00DC648 [] = { D_09000400_3D84C0, D_09000400_3D84C0 }
Function Documentation
func_E00DC2FC()
void func_E00DC2FC (void)
huff_puff_breath_appendGfx()
void huff_puff_breath_appendGfx (void * effect)
Referenced by huff_puff_breath_render().
huff_puff_breath_init()
void huff_puff_breath_init (EffectInstance * effect)
Referenced by huff_puff_breath_main().
huff_puff_breath_main()
EffectInstance * huff_puff_breath_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 angle, f32 speed, f32 scale, s32 timeLeft)
huff_puff_breath_render()
void huff_puff_breath_render (EffectInstance * effect)
Referenced by huff_puff_breath_main().
huff_puff_breath_update()
void huff_puff_breath_update (EffectInstance * effect)
Referenced by huff_puff_breath_main().
Variable Documentation
D_09000400_3D84C0
Gfx D_09000400_3D84C0[] extern
D_090005E8_3D86A8
Gfx D_090005E8_3D86A8[] extern
D_09000628_3D86E8
Gfx D_09000628_3D86E8[] extern
D_E00DC640
Gfx* D_E00DC640[] = { D_09000628_3D86E8, D_090005E8_3D86A8 }
Referenced by huff_puff_breath_appendGfx().
D_E00DC648
Gfx* D_E00DC648[] = { D_09000400_3D84C0, D_09000400_3D84C0 }
Referenced by huff_puff_breath_appendGfx().