papermario: src/i_spy.c File Reference
i_spy.c File Reference
Data Structures
struct ISpyNotification
Enumerations
enum { I_SPY_DELAY = 0 , I_SPY_APPEAR = 1 , I_SPY_OVERSHOOT = 2 , I_SPY_ANIMATE = 3 }
Functions
INCLUDE_IMG ("ispy_icon.png", ispy_icon_img)
INCLUDE_PAL ("ispy_icon.pal", ispy_icon_1_pal)
INCLUDE_PAL ("ispy_icon.2.pal", ispy_icon_2_pal)
INCLUDE_PAL ("ispy_icon.3.pal", ispy_icon_3_pal)
void ispy_notification_update (void)
void appendGfx_ispy_icon (void)
void ispy_notification_setup (void)
Variables
BSS ISpyNotification ISpyData
ISpyNotification * ISpyPtr = &ISpyData
Data Structure Documentation
ISpyNotification
struct ISpyNotification
Data Fields
s32 alpha
s32 flashCount
Vec3f pos
f32 scale
s32 state
s32 time
char unk_10[8]
char unk_1C[4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
I_SPY_DELAY
I_SPY_APPEAR
I_SPY_OVERSHOOT
I_SPY_ANIMATE
Function Documentation
appendGfx_ispy_icon()
void appendGfx_ispy_icon (void)
Referenced by render_ispy_icon().
INCLUDE_IMG()
INCLUDE_IMG ("ispy_icon.png" , ispy_icon_img)
INCLUDE_PAL() [1/3]
INCLUDE_PAL ("ispy_icon.2.pal" , ispy_icon_2_pal)
INCLUDE_PAL() [2/3]
INCLUDE_PAL ("ispy_icon.3.pal" , ispy_icon_3_pal)
INCLUDE_PAL() [3/3]
INCLUDE_PAL ("ispy_icon.pal" , ispy_icon_1_pal)
ispy_notification_setup()
void ispy_notification_setup (void)
Referenced by check_for_ispy().
ispy_notification_update()
void ispy_notification_update (void)
Referenced by ispy_notification_setup().
Variable Documentation
ISpyData
BSS ISpyNotification ISpyData
ISpyPtr
ISpyNotification* ISpyPtr = &ISpyData
Referenced by appendGfx_ispy_icon(), ispy_notification_setup(), and ispy_notification_update().