papermario: src/effects/ice_pillar.c File Reference
ice_pillar.c File Reference
Functions
void ice_pillar_init (EffectInstance *effect)
void ice_pillar_update (EffectInstance *effect)
void ice_pillar_render (EffectInstance *effect)
void ice_pillar_appendGfx (void *effect)
EFFECT_DEF_MISC_PARTICLES (misc_particles_main)
EFFECT_DEF_ICE_SHARD (ice_shard_main)
EFFECT_DEF_COLD_BREATH (cold_breath_main)
EffectInstance * ice_pillar_main (s32 arg0, f32 x, f32 y, f32 z, f32 scale, s32 arg5)
Variables
Gfx D_09001000_40B1C0 []
Gfx D_090011A8_40B368 []
Gfx D_090011C8_40B388 []
Gfx D_090011E8_40B3A8 []
Gfx D_09001208_40B3C8 []
Gfx * D_E011E7F0 [] = { D_090011A8_40B368, D_090011C8_40B388, D_090011E8_40B3A8, D_09001208_40B3C8 }
Gfx * D_E011E800 [] = { D_09001000_40B1C0 }
Function Documentation
EFFECT_DEF_COLD_BREATH()
EFFECT_DEF_COLD_BREATH (cold_breath_main)
EFFECT_DEF_ICE_SHARD()
EFFECT_DEF_ICE_SHARD (ice_shard_main)
EFFECT_DEF_MISC_PARTICLES()
EFFECT_DEF_MISC_PARTICLES (misc_particles_main)
ice_pillar_appendGfx()
void ice_pillar_appendGfx (void * effect)
Referenced by ice_pillar_render().
ice_pillar_init()
void ice_pillar_init (EffectInstance * effect)
Referenced by ice_pillar_main().
ice_pillar_main()
EffectInstance * ice_pillar_main (s32 arg0, f32 x, f32 y, f32 z, f32 scale, s32 arg5)
ice_pillar_render()
void ice_pillar_render (EffectInstance * effect)
Referenced by ice_pillar_main().
ice_pillar_update()
void ice_pillar_update (EffectInstance * effect)
Referenced by ice_pillar_main().
Variable Documentation
D_09001000_40B1C0
Gfx D_09001000_40B1C0[] extern
D_090011A8_40B368
Gfx D_090011A8_40B368[] extern
D_090011C8_40B388
Gfx D_090011C8_40B388[] extern
D_090011E8_40B3A8
Gfx D_090011E8_40B3A8[] extern
D_09001208_40B3C8
Gfx D_09001208_40B3C8[] extern
D_E011E7F0
Gfx* D_E011E7F0[] = { D_090011A8_40B368, D_090011C8_40B388, D_090011E8_40B3A8, D_09001208_40B3C8 }
Referenced by ice_pillar_appendGfx().
D_E011E800
Gfx* D_E011E800[] = { D_09001000_40B1C0 }
Referenced by ice_pillar_appendGfx().