papermario: src/imgfx.c File Reference
imgfx.c File Reference
Data Structures
union ImgFXIntVars
union ImgFXFloatVars
struct ImgFXState
struct ImgFXCacheEntry
struct ImgFXRenderMode
struct ImgFXIntVars.args
struct ImgFXIntVars.anim
struct ImgFXIntVars.wavy
struct ImgFXIntVars.color
struct ImgFXIntVars.hologram
struct ImgFXIntVars.overlay
struct ImgFXFloatVars.anim
struct ImgFXFloatVars.wavy
struct ImgFXFloatVars.overlay
Typedefs
typedef ImgFXState ImgFXInstanceList[MAX_IMGFX_INSTANCES]
Enumerations
enum ImgFXAnimFlags { IMGFX_ANIM_FLAG_ABSOLUTE_COORDS = 1 }
Functions
void imgfx_cache_instance_data (ImgFXState *state)
void imgfx_clear_instance_data (ImgFXState *state)
void imgfx_init_instance (ImgFXState *state)
void imgfx_make_mesh (ImgFXState *state)
void imgfx_appendGfx_mesh (ImgFXState *state, Matrix4f mtx)
void imgfx_mesh_make_strip (ImgFXState *state)
void imgfx_mesh_make_grid (ImgFXState *state)
void imgfx_mesh_anim_update (ImgFXState *state)
void imgfx_appendGfx_mesh_basic (ImgFXState *, Matrix4f mtx)
void imgfx_appendGfx_mesh_grid (ImgFXState *, Matrix4f mtx)
void imgfx_appendGfx_mesh_anim (ImgFXState *, Matrix4f mtx)
void imgfx_appendGfx_mesh_strip (ImgFXState *, Matrix4f mtx)
void imgfx_wavy_init (ImgFXState *state)
void imgfx_mesh_make_wavy (ImgFXState *state)
void imgfx_mesh_load_colors (ImgFXState *state)
void imgfx_set_vtx_buf_capacity (s16 arg0)
void imgfx_init (void)
void func_8013A4D0 (void)
void imgfx_add_to_cache (void *data, s8 usingContextualHeap)
void imgfx_update_cache_impl (void)
void imgfx_update_cache (void)
s32 imgfx_get_free_instances (s32 count)
void imgfx_release_instance (u32 idx)
void imgfx_release_instance_chain (u32 idx)
s32 imgfx_get_next_instance (s32 idx)
ImgFXState * imgfx_get_instance (s32 idx)
void imgfx_update (u32 idx, ImgFXType type, s32 imgfxArg1, s32 imgfxArg2, s32 imgfxArg3, s32 imgfxArg4, s32 flags)
void imgfx_set_state_flags (s32 idx, u16 flagBits, s32 mode)
s32 imgfx_appendGfx_component (s32 idx, ImgFXTexture *ifxImg, u32 flagBits, Matrix4f mtx)
ImgFXAnimHeader * imgfx_load_anim (ImgFXState *state)
Variables
HeapNode heap_spriteHead
BSS ImgFXWorkingTexture ImgFXCurrentTexture
BSS Vtx * ImgFXVtxBuffers [2]
BSS Vtx * imgfx_vtxBuf
BSS ImgFXInstanceList * ImgFXInstances
BSS s8 D_80156958 [2]
BSS s32 D_8015695C
BSS s32 D_80156960 [2]
BSS s32 D_80156968 [2]
BSS s8 D_80156970
BSS s32 D_80156974 [3]
BSS ImgFXAnimHeader ImgFXAnimHeaders [MAX_IMGFX_INSTANCES]
BSS ImgFXCacheEntry ImgFXDataCache [8]
ImgFXWorkingTexture * ImgFXCurrentTexturePtr = &ImgFXCurrentTexture
u16 imgfx_vtxCount = 0
Lights2 ImgFXLights = gdSPDefLights2(144, 144, 144, 255, 255, 255, 0, 0, 120, 255, 255, 255, 0, 0, 136)
Vp D_8014EE40
Vp D_8014EE50
u16 ImgFXVtxBufferCapacity = 300
Gfx DefaultImgFXSetupGfx []
ImgFXRenderMode ImgFXRenderModes []
Addr shock_header
Addr shiver_header
Addr vertical_pipe_curl_header
Addr horizontal_pipe_curl_header
Addr startle_header
Addr flutter_down_header
Addr unfurl_header
Addr get_in_bed_header
Addr spirit_capture_header
Addr unused_1_header
Addr unused_2_header
Addr unused_3_header
Addr tutankoopa_gather_header
Addr tutankoopa_swirl_2_header
Addr tutankoopa_swirl_1_header
Addr shuffle_cards_header
Addr flip_card_1_header
Addr flip_card_2_header
Addr flip_card_3_header
Addr cymbal_crush_header
u8 * ImgFXAnimOffsets []
Data Structure Documentation
ImgFXIntVars
union ImgFXIntVars
Data Fields
struct ImgFXIntVars.anim anim
struct ImgFXIntVars.args args
struct ImgFXIntVars.color color
struct ImgFXIntVars.hologram hologram
struct ImgFXIntVars.overlay overlay
s32 raw[2][4]
struct ImgFXIntVars.wavy wavy
ImgFXFloatVars
union ImgFXFloatVars
Data Fields
struct ImgFXFloatVars.anim anim
struct ImgFXFloatVars.overlay overlay
f32 raw[2][4]
struct ImgFXFloatVars.wavy wavy
ImgFXState
struct ImgFXState
Data Fields
u8 arrayIdx
Color_RGBA8 * colorBuf
u16 colorBufCount
u8 * curAnimOffset
u16 firstVtxIdx
s32 flags
ImgFXFloatVars floats
Gfx * gfxBufs[2]
ImgFXIntVars ints
s8 lastAnimCmd
s8 lastColorCmd
u16 lastVtxIdx
u8 meshType
s16 nextIdx
s32 otherModeL
u8 renderType
u8 subdivX
u8 subdivY
char unk_07[0x1]
u16 unk_0C
s16 unk_0E
char unk_18[0x4]
char unk_62[0x2]
Vtx * vtxBufs[2]
ImgFXCacheEntry
struct ImgFXCacheEntry
Data Fields
s32 * data
u8 staleCooldownTimer
char unk_06[0x2]
u8 usingContextualHeap
ImgFXRenderMode
struct ImgFXRenderMode
Data Fields
u8 flags
s32 mode1
s32 mode2
ImgFXIntVars.args
struct ImgFXIntVars.args
Data Fields
s32 anim[4]
s32 color[4]
ImgFXIntVars.anim
struct ImgFXIntVars.anim
Data Fields
s32 interval
s32 step
s32 type
ImgFXIntVars.wavy
struct ImgFXIntVars.wavy
Data Fields
Vec3i mag
ImgFXIntVars.color
struct ImgFXIntVars.color
Data Fields
s32 a
s32 b
s32 g
s32 r
char unk_00[0x10]
ImgFXIntVars.hologram
struct ImgFXIntVars.hologram
Data Fields
s32 alphaAmt
s32 mode
s32 noiseAmt
char unk_00[0x10]
char unk_18[4]
ImgFXIntVars.overlay
struct ImgFXIntVars.overlay
Data Fields
s32 alpha
ImgFXOverlayTexture * pattern
char unk_00[0x10]
ImgFXFloatVars.anim
struct ImgFXFloatVars.anim
Data Fields
f32 curFrame
f32 curIdx
ImgFXFloatVars.wavy
struct ImgFXFloatVars.wavy
Data Fields
f32 phase1
f32 phase2
f32 phase3
ImgFXFloatVars.overlay
struct ImgFXFloatVars.overlay
Data Fields
f32 posX
f32 posY
char unk_00[0x10]
Typedef Documentation
ImgFXInstanceList
typedef ImgFXState ImgFXInstanceList[MAX_IMGFX_INSTANCES]
Enumeration Type Documentation
ImgFXAnimFlags
enum ImgFXAnimFlags
Enumerator
IMGFX_ANIM_FLAG_ABSOLUTE_COORDS
Function Documentation
func_8013A4D0()
void func_8013A4D0 (void)
Referenced by spr_update_player_raster_cache().
imgfx_add_to_cache()
void imgfx_add_to_cache (void * data, s8 usingContextualHeap)
Referenced by imgfx_cache_instance_data(), and imgfx_load_anim().
imgfx_appendGfx_component()
s32 imgfx_appendGfx_component (s32 idx, ImgFXTexture * ifxImg, u32 flagBits, Matrix4f mtx)
Referenced by appendGfx_entity_model(), appendGfx_FallingSprite(), appendGfx_interact_prompt(), appendGfx_ispy_icon(), appendGfx_pulse_stone_icon(), appendGfx_ritual_card(), appendGfx_speech_bubble(), appendGfx_sticker(), CharAnim_FadeIn_0(), CharAnim_FadeIn_1(), CharAnim_FadeIn_2(), CharAnim_FadeIn_3(), CharAnim_FadeIn_4(), CharAnim_FadeOut_0(), CharAnim_FadeOut_1(), CharAnim_FadeOut_2(), CharAnim_HoldClearImgFX(), draw_coin_sparkles(), draw_entity_model_E(), func_80241610_97F0E0(), func_80241610_990DF0(), func_80241610_993D40(), gfx_build_knocked_down_player(), render_hud_element(), and spr_appendGfx_component().
imgfx_appendGfx_mesh()
void imgfx_appendGfx_mesh (ImgFXState * state, Matrix4f mtx)
Referenced by imgfx_appendGfx_component().
imgfx_appendGfx_mesh_anim()
void imgfx_appendGfx_mesh_anim (ImgFXState * state, Matrix4f mtx)
Referenced by imgfx_appendGfx_mesh().
imgfx_appendGfx_mesh_basic()
void imgfx_appendGfx_mesh_basic (ImgFXState * state, Matrix4f mtx)
Referenced by imgfx_appendGfx_mesh().
imgfx_appendGfx_mesh_grid()
void imgfx_appendGfx_mesh_grid (ImgFXState * state, Matrix4f mtx)
Referenced by imgfx_appendGfx_mesh().
imgfx_appendGfx_mesh_strip()
void imgfx_appendGfx_mesh_strip (ImgFXState * state, Matrix4f mtx)
Referenced by imgfx_appendGfx_mesh().
imgfx_cache_instance_data()
void imgfx_cache_instance_data (ImgFXState * state)
Referenced by func_8013A4D0(), imgfx_appendGfx_component(), and imgfx_update().
imgfx_clear_instance_data()
void imgfx_clear_instance_data (ImgFXState * state)
Referenced by imgfx_init().
imgfx_get_free_instances()
s32 imgfx_get_free_instances (s32 count)
Referenced by hud_element_create_transform_A(), spr_load_npc_sprite(), and spr_update_player_sprite().
imgfx_get_instance()
ImgFXState * imgfx_get_instance (s32 idx)
imgfx_get_next_instance()
s32 imgfx_get_next_instance (s32 idx)
imgfx_init()
void imgfx_init (void)
Referenced by spr_init_sprites().
imgfx_init_instance()
void imgfx_init_instance (ImgFXState * state)
Referenced by func_8013A4D0(), imgfx_get_free_instances(), imgfx_init(), and imgfx_update().
imgfx_load_anim()
ImgFXAnimHeader * imgfx_load_anim (ImgFXState * state)
Referenced by imgfx_mesh_anim_update().
imgfx_make_mesh()
void imgfx_make_mesh (ImgFXState * state)
Referenced by imgfx_appendGfx_component().
imgfx_mesh_anim_update()
void imgfx_mesh_anim_update (ImgFXState * state)
Referenced by imgfx_make_mesh().
imgfx_mesh_load_colors()
void imgfx_mesh_load_colors (ImgFXState * state)
Referenced by imgfx_make_mesh().
imgfx_mesh_make_grid()
void imgfx_mesh_make_grid (ImgFXState * state)
Referenced by imgfx_make_mesh().
imgfx_mesh_make_strip()
void imgfx_mesh_make_strip (ImgFXState * state)
Referenced by imgfx_make_mesh().
imgfx_mesh_make_wavy()
void imgfx_mesh_make_wavy (ImgFXState * state)
Bug
? should be sin_deg?
Referenced by imgfx_make_mesh().
imgfx_release_instance()
void imgfx_release_instance (u32 idx)
Referenced by hud_element_free_transform(), imgfx_release_instance_chain(), and spr_free_sprite().
imgfx_release_instance_chain()
void imgfx_release_instance_chain (u32 idx)
imgfx_set_state_flags()
void imgfx_set_state_flags (s32 idx, u16 flagBits, s32 mode)
imgfx_set_vtx_buf_capacity()
void imgfx_set_vtx_buf_capacity (s16 arg0)
imgfx_update()
void imgfx_update (u32 idx, ImgFXType type, s32 imgfxArg1, s32 imgfxArg2, s32 imgfxArg3, s32 imgfxArg4, s32 flags)
Referenced by appendGfx_interact_prompt(), appendGfx_ispy_icon(), appendGfx_speech_bubble(), appendGfx_sticker(), CharAnim_FadeIn_0(), CharAnim_FadeIn_1(), CharAnim_FadeIn_2(), CharAnim_FadeIn_3(), CharAnim_FadeIn_4(), CharAnim_FadeOut_0(), CharAnim_FadeOut_1(), CharAnim_FadeOut_2(), CharAnim_HoldClearImgFX(), func_80241610_97F0E0(), func_80241610_990DF0(), render_hud_element(), set_npc_imgfx_comp(), and set_player_imgfx_comp().
imgfx_update_cache()
void imgfx_update_cache (void)
Referenced by state_drawUI_world().
imgfx_update_cache_impl()
void imgfx_update_cache_impl (void)
Referenced by imgfx_update_cache().
imgfx_wavy_init()
void imgfx_wavy_init (ImgFXState * state)
Referenced by imgfx_update().
Variable Documentation
cymbal_crush_header
Addr cymbal_crush_header extern
D_8014EE40
Vp D_8014EE40
Initial value:
= {
    .vp = {
        .vscale = { 640, 480, 511, 0 },
        .vtrans = { 640, 480, 511, 0 },
    }
}
Referenced by imgfx_appendGfx_mesh_basic().
D_8014EE50
Vp D_8014EE50
Initial value:
= {
    .vp = {
        .vscale = { 640, 480, 511, 0 },
        .vtrans = { 640, 480, 512, 0 },
    }
}
Referenced by imgfx_appendGfx_mesh_basic().
D_80156958
BSS s8 D_80156958[2]
Referenced by imgfx_init().
D_8015695C
BSS s32 D_8015695C
D_80156960
BSS s32 D_80156960[2]
Referenced by imgfx_init().
D_80156968
BSS s32 D_80156968[2]
Referenced by imgfx_init().
D_80156970
BSS s8 D_80156970
Referenced by imgfx_init().
D_80156974
BSS s32 D_80156974[3]
DefaultImgFXSetupGfx
Gfx DefaultImgFXSetupGfx[]
Initial value:
= {
    gsSPClearGeometryMode(G_CULL_BOTH | G_LIGHTING),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_SHADING_SMOOTH),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetAlphaCompare(G_AC_NONE),
    gsSPSetOtherMode(G_SETOTHERMODE_H, G_MDSFT_ALPHADITHER, 18,
                     G_AD_DISABLE | G_CD_DISABLE | G_TC_FILT | G_TF_BILERP | G_TP_PERSP),
    gsSPEndDisplayList(),
}
Referenced by imgfx_appendGfx_mesh().
flip_card_1_header
Addr flip_card_1_header extern
flip_card_2_header
Addr flip_card_2_header extern
flip_card_3_header
Addr flip_card_3_header extern
flutter_down_header
Addr flutter_down_header extern
get_in_bed_header
Addr get_in_bed_header extern
heap_spriteHead
HeapNode heap_spriteHead extern
Referenced by imgfx_init().
horizontal_pipe_curl_header
Addr horizontal_pipe_curl_header extern
imgfx_vtxBuf
BSS Vtx* imgfx_vtxBuf
Referenced by func_8013A4D0(), imgfx_appendGfx_mesh_basic(), imgfx_appendGfx_mesh_grid(), imgfx_init(), imgfx_mesh_load_colors(), imgfx_mesh_make_grid(), imgfx_mesh_make_strip(), and imgfx_mesh_make_wavy().
imgfx_vtxCount
u16 imgfx_vtxCount = 0
Referenced by func_8013A4D0(), imgfx_init(), imgfx_mesh_make_grid(), and imgfx_mesh_make_strip().
ImgFXAnimHeaders
BSS ImgFXAnimHeader ImgFXAnimHeaders[MAX_IMGFX_INSTANCES]
Referenced by imgfx_load_anim().
ImgFXAnimOffsets
u8* ImgFXAnimOffsets[]
Initial value:
= {
    [IMGFX_ANIM_SHOCK]                 shock_header,
    [IMGFX_ANIM_SHIVER]                shiver_header,
    [IMGFX_ANIM_VERTICAL_PIPE_CURL]    vertical_pipe_curl_header,
    [IMGFX_ANIM_HORIZONTAL_PIPE_CURL]  horizontal_pipe_curl_header,
    [IMGFX_ANIM_STARTLE]               startle_header,
    [IMGFX_ANIM_FLUTTER_DOWN]          flutter_down_header,
    [IMGFX_ANIM_UNFURL]                unfurl_header,
    [IMGFX_ANIM_GET_IN_BED]            get_in_bed_header,
    [IMGFX_ANIM_SPIRIT_CAPTURE]        spirit_capture_header,
    [IMGFX_ANIM_UNUSED_1]              unused_1_header,
    [IMGFX_ANIM_UNUSED_2]              unused_2_header,
    [IMGFX_ANIM_UNUSED_3]              unused_3_header,
    [IMGFX_ANIM_TUTANKOOPA_GATHER]     tutankoopa_gather_header,
    [IMGFX_ANIM_TUTANKOOPA_SWIRL_2]    tutankoopa_swirl_2_header,
    [IMGFX_ANIM_TUTANKOOPA_SWIRL_1]    tutankoopa_swirl_1_header,
    [IMGFX_ANIM_SHUFFLE_CARDS]         shuffle_cards_header,
    [IMGFX_ANIM_FLIP_CARD_1]           flip_card_1_header,
    [IMGFX_ANIM_FLIP_CARD_2]           flip_card_2_header,
    [IMGFX_ANIM_FLIP_CARD_3]           flip_card_3_header,
    [IMGFX_ANIM_CYMBAL_CRUSH]          cymbal_crush_header,
}
Referenced by imgfx_load_anim().
ImgFXCurrentTexture
BSS ImgFXWorkingTexture ImgFXCurrentTexture
ImgFXCurrentTexturePtr
ImgFXWorkingTexture* ImgFXCurrentTexturePtr = &ImgFXCurrentTexture
Referenced by imgfx_appendGfx_component(), imgfx_appendGfx_mesh(), imgfx_appendGfx_mesh_anim(), imgfx_appendGfx_mesh_basic(), imgfx_appendGfx_mesh_grid(), imgfx_appendGfx_mesh_strip(), imgfx_mesh_anim_update(), imgfx_mesh_load_colors(), imgfx_mesh_make_grid(), and imgfx_mesh_make_strip().
ImgFXDataCache
BSS ImgFXCacheEntry ImgFXDataCache[8]
Referenced by imgfx_add_to_cache(), imgfx_init(), and imgfx_update_cache_impl().
ImgFXInstances
BSS ImgFXInstanceList* ImgFXInstances
Referenced by func_8013A4D0(), imgfx_appendGfx_mesh_basic(), imgfx_get_free_instances(), imgfx_get_next_instance(), imgfx_init(), and imgfx_set_state_flags().
ImgFXLights
Lights2 ImgFXLights = gdSPDefLights2(144, 144, 144, 255, 255, 255, 0, 0, 120, 255, 255, 255, 0, 0, 136)
Referenced by imgfx_appendGfx_mesh().
ImgFXRenderModes
ImgFXRenderMode ImgFXRenderModes[]
Initial value:
= {
    [IMGFX_RENDER_DEFAULT]               { 0x00441208, 0x00111208, 0 },
    [IMGFX_RENDER_MULTIPLY_RGB]          { 0x00441208, 0x00111208, 0 },
    [IMGFX_RENDER_MULTIPLY_ALPHA]        { 0x00404B40, 0x00104B40, IMGFX_RENDER_NO_OVERRIDE },
    [IMGFX_RENDER_MULTIPLY_RGBA]         { 0x00404B40, 0x00104B40, IMGFX_RENDER_NO_OVERRIDE },
    [IMGFX_RENDER_MODULATE_PRIM_RGB]     { 0x00441208, 0x00111208, 0 },
    [IMGFX_RENDER_MODULATE_PRIM_RGBA]    { 0x00404B40, 0x00104B40, IMGFX_RENDER_NO_OVERRIDE },
    [IMGFX_RENDER_MULTIPLY_SHADE_RGB]    { 0x00441208, 0x00111208, 0 },
    [IMGFX_RENDER_MULTIPLY_SHADE_ALPHA]  { 0x00404B40, 0x00104B40, IMGFX_RENDER_NO_OVERRIDE },
    [IMGFX_RENDER_MULTIPLY_SHADE_RGBA]   { 0x00404B40, 0x00104B40, IMGFX_RENDER_NO_OVERRIDE },
    [IMGFX_RENDER_MODULATE_SHADE_RGB]    { 0x00441208, 0x00111208, 0 },
    [IMGFX_RENDER_MODULATE_SHADE_RGBA]   { 0x00404B40, 0x00104B40, IMGFX_RENDER_NO_OVERRIDE },
    [IMGFX_RENDER_ANIM]                  { 0x00441208, 0x00111208, 0 },
    [IMGFX_RENDER_HOLOGRAM]              { 0x00404B40, 0x00104B40, IMGFX_RENDER_NO_OVERRIDE },
    [IMGFX_RENDER_COLOR_FILL]            { 0x00441208, 0x00111208, 0 },
    [IMGFX_RENDER_OVERLAY_RGB]           { 0x00441208, 0x00111208, 0 },
    [IMGFX_RENDER_OVERLAY_RGBA]          { 0x00404B40, 0x00104B40, IMGFX_RENDER_NO_OVERRIDE },
    [IMGFX_RENDER_UNUSED]                { 0x00441208, 0x00111208, 0 },
}
Referenced by imgfx_appendGfx_mesh().
ImgFXVtxBufferCapacity
u16 ImgFXVtxBufferCapacity = 300
Referenced by imgfx_init(), and imgfx_set_vtx_buf_capacity().
ImgFXVtxBuffers
BSS Vtx* ImgFXVtxBuffers[2]
Referenced by func_8013A4D0(), and imgfx_init().
shiver_header
Addr shiver_header extern
shock_header
Addr shock_header extern
shuffle_cards_header
Addr shuffle_cards_header extern
spirit_capture_header
Addr spirit_capture_header extern
startle_header
Addr startle_header extern
tutankoopa_gather_header
Addr tutankoopa_gather_header extern
tutankoopa_swirl_1_header
Addr tutankoopa_swirl_1_header extern
tutankoopa_swirl_2_header
Addr tutankoopa_swirl_2_header extern
unfurl_header
Addr unfurl_header extern
unused_1_header
Addr unused_1_header extern
unused_2_header
Addr unused_2_header extern
unused_3_header
Addr unused_3_header extern
vertical_pipe_curl_header
Addr vertical_pipe_curl_header extern