papermario: include/script_api/battle.h File Reference
battle.h File Reference
Functions
ApiStatus EnablePartnerBlur (Evt *script, s32 isInitialCall)
ApiStatus DisablePartnerBlur (Evt *script, s32 isInitialCall)
ApiStatus UseBattleCamPreset (Evt *script, s32 isInitialCall)
ApiStatus SetBattleCamTarget (Evt *script, s32 isInitialCall)
ApiStatus SetBattleCamOffsetZ (Evt *script, s32 isInitialCall)
ApiStatus AddBattleCamOffsetZ (Evt *script, s32 isInitialCall)
ApiStatus SetBattleCamYaw (Evt *script, s32 isInitialCall)
ApiStatus BattleCamTargetActor (Evt *script, s32 isInitialCall)
ApiStatus MoveBattleCamOver (Evt *script, s32 isInitialCall)
ApiStatus SetBattleCamZoom (Evt *script, s32 isInitialCall)
ApiStatus AddBattleCamZoom (Evt *script, s32 isInitialCall)
ApiStatus FreezeBattleCam (Evt *script, s32 isInitialCall)
ApiStatus func_8024EDA4 (Evt *script, s32 isInitialCall)
ApiStatus ShowMessageBox (Evt *script, s32 isInitialCall)
ApiStatus ShowVariableMessageBox (Evt *script, s32 isInitialCall)
ApiStatus IsMessageBoxDisplayed (Evt *script, s32 isInitialCall)
ApiStatus WaitForMessageBoxDone (Evt *script, s32 isInitialCall)
ApiStatus ForceCloseMessageBox (Evt *script, s32 isInitialCall)
ApiStatus SetMessageBoxDuration (Evt *script, s32 isInitialCall)
ApiStatus ItemDamageEnemy (Evt *script, s32 isInitialCall)
ApiStatus ItemAfflictEnemy (Evt *script, s32 isInitialCall)
ApiStatus ItemSpookEnemy (Evt *script, s32 isInitialCall)
ApiStatus ItemCheckHit (Evt *script, s32 isInitialCall)
ApiStatus ActorSpeak (Evt *script, s32 isInitialCall)
ApiStatus EndActorSpeech (Evt *script, s32 isInitialCall)
ApiStatus ShowBattleChoice (Evt *script, s32 isInitialCall)
ApiStatus OverrideBattleDmaDest (Evt *script, s32 isInitialCall)
ApiStatus LoadBattleDmaData (Evt *script, s32 isInitialCall)
ApiStatus EnableBattleFloorReflections (Evt *script, s32 isInitialCall)
ApiStatus SetDarknessMode (Evt *script, s32 isInitialCall)
ApiStatus PlaySoundAtActor (Evt *script, s32 isInitialCall)
ApiStatus PlaySoundAtPart (Evt *script, s32 isInitialCall)
ApiStatus SetForegroundModelsVisibleUnchecked (Evt *script, s32 isInitialCall)
ApiStatus SetForegroundModelsVisible (Evt *script, s32 isInitialCall)
ApiStatus MakeStatusField (Evt *script, s32 isInitialCall)
ApiStatus MultiplyByActorScale (Evt *script, s32 isInitialCall)
ApiStatus MultiplyVec2ByActorScale (Evt *script, s32 isInitialCall)
ApiStatus MultiplyVec3ByActorScale (Evt *script, s32 isInitialCall)
ApiStatus ApplyShrinkFromOwner (Evt *script, s32 isInitialCall)
ApiStatus StartRumble (Evt *script, s32 isInitialCall)
ApiStatus HasMerleeCastsLeft (Evt *script, s32 isInitialCall)
ApiStatus SpawnRecoverHeartFX (Evt *script, s32 isInitialCall)
ApiStatus SpawnRecoverFlowerFX (Evt *script, s32 isInitialCall)
ApiStatus IncrementPlayerHP (Evt *script, s32 isInitialCall)
ApiStatus IncrementPlayerFP (Evt *script, s32 isInitialCall)
ApiStatus StartRumbleWithParams (Evt *script, s32 isInitialCall)
ApiStatus LoadItemScript (Evt *script, s32 isInitialCall)
ApiStatus LoadMoveScript (Evt *script, s32 isInitialCall)
ApiStatus LoadBattleSection (Evt *script, s32 isInitialCall)
ApiStatus GetBattlePhase (Evt *script, s32 isInitialCall)
ApiStatus GetLastElement (Evt *script, s32 isInitialCall)
ApiStatus SetDamageSource (Evt *script, s32 isInitialCall)
ApiStatus GetDamageSource (Evt *script, s32 isInitialCall)
ApiStatus SetGoalToHome (Evt *script, s32 isInitialCall)
ApiStatus SetIdleGoalToHome (Evt *script, s32 isInitialCall)
ApiStatus SetGoalToIndex (Evt *script, s32 isInitialCall)
ApiStatus GetIndexFromPos (Evt *script, s32 isInitialCall)
ApiStatus GetIndexFromHome (Evt *script, s32 isInitialCall)
ApiStatus CountTargets (Evt *script, s32 isInitialCall)
ApiStatus ForceHomePos (Evt *script, s32 isInitialCall)
ApiStatus SetHomePos (Evt *script, s32 isInitialCall)
ApiStatus SetGoalToTarget (Evt *script, s32 isInitialCall)
ApiStatus SetPartGoalToTarget (Evt *script, s32 isInitialCall)
ApiStatus SetGoalToFirstTarget (Evt *script, s32 isInitialCall)
ApiStatus SetGoalPos (Evt *script, s32 isInitialCall)
ApiStatus SetIdleGoal (Evt *script, s32 isInitialCall)
ApiStatus AddGoalPos (Evt *script, s32 isInitialCall)
ApiStatus GetGoalPos (Evt *script, s32 isInitialCall)
ApiStatus GetIdleGoal (Evt *script, s32 isInitialCall)
ApiStatus GetPartTarget (Evt *script, s32 isInitialCall)
ApiStatus GetActorPos (Evt *script, s32 isInitialCall)
ApiStatus GetPartOffset (Evt *script, s32 isInitialCall)
ApiStatus GetPartPos (Evt *script, s32 isInitialCall)
ApiStatus GetHomePos (Evt *script, s32 isInitialCall)
ApiStatus SetActorPos (Evt *script, s32 isInitialCall)
ApiStatus SetPartPos (Evt *script, s32 isInitialCall)
ApiStatus SetEnemyTargetOffset (Evt *script, s32 isInitialCall)
ApiStatus SetAnimation (Evt *script, s32 isInitialCall)
ApiStatus GetAnimation (Evt *script, s32 isInitialCall)
ApiStatus SetAnimationRate (Evt *script, s32 isInitialCall)
ApiStatus SetActorYaw (Evt *script, s32 isInitialCall)
ApiStatus GetActorYaw (Evt *script, s32 isInitialCall)
ApiStatus SetPartYaw (Evt *script, s32 isInitialCall)
ApiStatus GetPartYaw (Evt *script, s32 isInitialCall)
ApiStatus SetActorJumpGravity (Evt *script, s32 isInitialCall)
ApiStatus SetActorIdleJumpGravity (Evt *script, s32 isInitialCall)
ApiStatus SetActorSpeed (Evt *script, s32 isInitialCall)
ApiStatus SetActorIdleSpeed (Evt *script, s32 isInitialCall)
ApiStatus SetPartJumpGravity (Evt *script, s32 isInitialCall)
ApiStatus SetPartMoveSpeed (Evt *script, s32 isInitialCall)
ApiStatus SetJumpAnimations (Evt *script, s32 isInitialCall)
ApiStatus AddActorPos (Evt *script, s32 isInitialCall)
ApiStatus SetActorDispOffset (Evt *script, s32 isInitialCall)
ApiStatus GetPartDispOffset (Evt *script, s32 isInitialCall)
ApiStatus SetPartDispOffset (Evt *script, s32 isInitialCall)
ApiStatus AddPartDispOffset (Evt *script, s32 isInitialCall)
ApiStatus FreezeBattleState (Evt *script, s32 isInitialCall)
ApiStatus GetActorVar (Evt *script, s32 isInitialCall)
ApiStatus SetActorVar (Evt *script, s32 isInitialCall)
ApiStatus AddActorVar (Evt *script, s32 isInitialCall)
ApiStatus GetPartMovementVar (Evt *script, s32 isInitialCall)
ApiStatus SetPartMovementVar (Evt *script, s32 isInitialCall)
ApiStatus AddPartMovementVar (Evt *script, s32 isInitialCall)
ApiStatus SetActorRotation (Evt *script, s32 isInitialCall)
ApiStatus SetActorRotationOffset (Evt *script, s32 isInitialCall)
ApiStatus GetActorRotation (Evt *script, s32 isInitialCall)
ApiStatus SetPartRotation (Evt *script, s32 isInitialCall)
ApiStatus SetPartRotationOffset (Evt *script, s32 isInitialCall)
ApiStatus GetPartRotation (Evt *script, s32 isInitialCall)
ApiStatus SetActorScale (Evt *script, s32 isInitialCall)
ApiStatus SetActorScaleModifier (Evt *script, s32 isInitialCall)
ApiStatus GetActorScale (Evt *script, s32 isInitialCall)
ApiStatus SetPartScale (Evt *script, s32 isInitialCall)
ApiStatus GetPartScale (Evt *script, s32 isInitialCall)
ApiStatus GetBattleFlags (Evt *script, s32 isInitialCall)
ApiStatus SetBattleFlagBits (Evt *script, s32 isInitialCall)
ApiStatus GetBattleFlags2 (Evt *script, s32 isInitialCall)
ApiStatus SetBattleFlagBits2 (Evt *script, s32 isInitialCall)
ApiStatus SetActorFlags (Evt *script, s32 isInitialCall)
ApiStatus SetActorFlagBits (Evt *script, s32 isInitialCall)
ApiStatus GetActorFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartFlagBits (Evt *script, s32 isInitialCall)
ApiStatus SetPartTargetFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartTargetFlagBits (Evt *script, s32 isInitialCall)
ApiStatus GetPartFlags (Evt *script, s32 isInitialCall)
ApiStatus GetPartTargetFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartEventFlags (Evt *script, s32 isInitialCall)
ApiStatus SetPartEventBits (Evt *script, s32 isInitialCall)
ApiStatus GetPartEventFlags (Evt *script, s32 isInitialCall)
ApiStatus HPBarToHome (Evt *script, s32 isInitialCall)
ApiStatus HPBarToCurrent (Evt *script, s32 isInitialCall)
ApiStatus SetHPBarOffset (Evt *script, s32 isInitialCall)
ApiStatus SetActorStatusOffsets (Evt *script, s32 isInitialCall)
ApiStatus SummonEnemy (Evt *script, s32 isInitialCall)
ApiStatus GetOwnerID (Evt *script, s32 isInitialCall)
ApiStatus SetOwnerID (Evt *script, s32 isInitialCall)
ApiStatus ActorExists (Evt *script, s32 isInitialCall)
ApiStatus SetEnabledStarPowers (Evt *script, s32 isInitialCall)
ApiStatus SetBattleInputMask (Evt *script, s32 isInitialCall)
ApiStatus SetBattleInputButtons (Evt *script, s32 isInitialCall)
ApiStatus CheckButtonPress (Evt *script, s32 isInitialCall)
ApiStatus CheckButtonHeld (Evt *script, s32 isInitialCall)
ApiStatus CheckButtonDown (Evt *script, s32 isInitialCall)
ApiStatus GetBattleState (Evt *script, s32 isInitialCall)
ApiStatus CreateCurrentPosTargetList (Evt *script, s32 isInitialCall)
ApiStatus CreateHomeTargetList (Evt *script, s32 isInitialCall)
ApiStatus InitTargetIterator (Evt *script, s32 isInitialCall)
ApiStatus SetOwnerTarget (Evt *script, s32 isInitialCall)
ApiStatus ChooseNextTarget (Evt *script, s32 isInitialCall)
ApiStatus GetTargetListLength (Evt *script, s32 isInitialCall)
ApiStatus GetOwnerTarget (Evt *script, s32 isInitialCall)
ApiStatus func_8026E914 (Evt *script, s32 isInitialCall)
ApiStatus GetPlayerActorID (Evt *script, s32 isInitialCall)
ApiStatus GetDistanceToGoal (Evt *script, s32 isInitialCall)
ApiStatus SetActorPaletteEffect (Evt *script, s32 isInitialCall)
ApiStatus AddActorDecoration (Evt *script, s32 isInitialCall)
ApiStatus RemoveActorDecoration (Evt *script, s32 isInitialCall)
ApiStatus ModifyActorDecoration (Evt *script, s32 isInitialCall)
ApiStatus UseIdleAnimation (Evt *script, s32 isInitialCall)
ApiStatus GetStatusFlags (Evt *script, s32 isInitialCall)
ApiStatus RemovePlayerBuffs (Evt *script, s32 isInitialCall)
ApiStatus SetPartAlpha (Evt *script, s32 isInitialCall)
ApiStatus CreatePartShadow (Evt *script, s32 isInitialCall)
ApiStatus RemovePartShadow (Evt *script, s32 isInitialCall)
ApiStatus SetEndBattleFadeOutRate (Evt *script, s32 isInitialCall)
ApiStatus SetBattleVar (Evt *script, s32 isInitialCall)
ApiStatus GetBattleVar (Evt *script, s32 isInitialCall)
ApiStatus ResetAllActorSounds (Evt *script, s32 isInitialCall)
ApiStatus SetActorSounds (Evt *script, s32 isInitialCall)
ApiStatus ResetActorSounds (Evt *script, s32 isInitialCall)
ApiStatus SetPartSounds (Evt *script, s32 isInitialCall)
ApiStatus SetActorType (Evt *script, s32 isInitialCall)
ApiStatus ShowShockEffect (Evt *script, s32 isInitialCall)
ApiStatus GetActorAttackBoost (Evt *script, s32 isInitialCall)
ApiStatus GetActorDefenseBoost (Evt *script, s32 isInitialCall)
ApiStatus BoostAttack (Evt *script, s32 isInitialCall)
ApiStatus BoostDefense (Evt *script, s32 isInitialCall)
ApiStatus VanishActor (Evt *script, s32 isInitialCall)
ApiStatus ElectrifyActor (Evt *script, s32 isInitialCall)
ApiStatus HealActor (Evt *script, s32 isInitialCall)
ApiStatus WaitForBuffDone (Evt *script, s32 isInitialCall)
ApiStatus CopyBuffs (Evt *script, s32 isInitialCall)
ApiStatus GetMenuSelection (Evt *script, s32 isInitialCall)
ApiStatus PlayerFallToGoal (Evt *script, s32 isInitialCall)
ApiStatus PlayerLandJump (Evt *script, s32 isInitialCall)
ApiStatus PlayerRunToGoal (Evt *script, s32 isInitialCall)
ApiStatus CancelablePlayerRunToGoal (Evt *script, s32 isInitialCall)
ApiStatus GetPlayerHP (Evt *script, s32 isInitialCall)
ApiStatus PlayerDamageEnemy (Evt *script, s32 isInitialCall)
ApiStatus PlayerPowerBounceEnemy (Evt *script, s32 isInitialCall)
ApiStatus PlayerTestEnemy (Evt *script, s32 isInitialCall)
ApiStatus DispatchDamagePlayerEvent (Evt *script, s32 isInitialCall)
ApiStatus EnablePlayerBlur (Evt *script, s32 isInitialCall)
ApiStatus func_80274A18 (Evt *script, s32 isInitialCall)
ApiStatus func_802752AC (Evt *script, s32 isInitialCall)
ApiStatus func_80275F00 (Evt *script, s32 isInitialCall)
ApiStatus GetPlayerActionSuccess (Evt *script, s32 isInitialCall)
ApiStatus BindTakeTurn (Evt *script, s32 isInitialCall)
ApiStatus PauseTakeTurn (Evt *script, s32 isInitialCall)
ApiStatus ResumeTakeTurn (Evt *script, s32 isInitialCall)
ApiStatus BindIdle (Evt *script, s32 isInitialCall)
ApiStatus EnableIdleScript (Evt *script, s32 isInitialCall)
ApiStatus BindHandleEvent (Evt *script, s32 isInitialCall)
ApiStatus BindHandlePhase (Evt *script, s32 isInitialCall)
ApiStatus JumpToGoal (Evt *script, s32 isInitialCall)
ApiStatus IdleJumpToGoal (Evt *script, s32 isInitialCall)
ApiStatus JumpWithBounce (Evt *script, s32 isInitialCall)
ApiStatus LandJump (Evt *script, s32 isInitialCall)
ApiStatus FallToGoal (Evt *script, s32 isInitialCall)
ApiStatus RunToGoal (Evt *script, s32 isInitialCall)
ApiStatus IdleRunToGoal (Evt *script, s32 isInitialCall)
ApiStatus JumpPartTo (Evt *script, s32 isInitialCall)
ApiStatus FallPartTo (Evt *script, s32 isInitialCall)
ApiStatus LandJumpPart (Evt *script, s32 isInitialCall)
ApiStatus RunPartTo (Evt *script, s32 isInitialCall)
ApiStatus FlyToGoal (Evt *script, s32 isInitialCall)
ApiStatus IdleFlyToGoal (Evt *script, s32 isInitialCall)
ApiStatus FlyPartTo (Evt *script, s32 isInitialCall)
ApiStatus GetLastEvent (Evt *script, s32 isInitialCall)
ApiStatus SetTargetActor (Evt *script, s32 isInitialCall)
ApiStatus SetEnemyHP (Evt *script, s32 isInitialCall)
ApiStatus GetActorHP (Evt *script, s32 isInitialCall)
ApiStatus GetEnemyMaxHP (Evt *script, s32 isInitialCall)
ApiStatus RemoveActor (Evt *script, s32 isInitialCall)
ApiStatus DropStarPoints (Evt *script, s32 isInitialCall)
ApiStatus SetDefenseTable (Evt *script, s32 isInitialCall)
ApiStatus SetStatusTable (Evt *script, s32 isInitialCall)
ApiStatus SetIdleAnimations (Evt *script, s32 isInitialCall)
ApiStatus EnemyDamageTarget (Evt *script, s32 isInitialCall)
ApiStatus EnemyFollowupAfflictTarget (Evt *script, s32 isInitialCall)
ApiStatus EnemyTestTarget (Evt *script, s32 isInitialCall)
ApiStatus DispatchDamageEvent (Evt *script, s32 isInitialCall)
ApiStatus DispatchEvent (Evt *script, s32 isInitialCall)
ApiStatus ShowHealthBar (Evt *script, s32 isInitialCall)
ApiStatus SetTargetOffset (Evt *script, s32 isInitialCall)
ApiStatus SetProjectileTargetOffset (Evt *script, s32 isInitialCall)
ApiStatus EnableActorBlur (Evt *script, s32 isInitialCall)
ApiStatus AfflictActor (Evt *script, s32 isInitialCall)
ApiStatus GetInstigatorValue (Evt *script, s32 isInitialCall)
ApiStatus GetEncounterTrigger (Evt *script, s32 isInitialCall)
ApiStatus YieldTurn (Evt *script, s32 isInitialCall)
ApiStatus SetActorSize (Evt *script, s32 isInitialCall)
ApiStatus GetActorSize (Evt *script, s32 isInitialCall)
ApiStatus SetPartSize (Evt *script, s32 isInitialCall)
ApiStatus GetOriginalActorType (Evt *script, s32 isInitialCall)
ApiStatus GetCurrentActorType (Evt *script, s32 isInitialCall)
ApiStatus GetLastDamage (Evt *script, s32 isInitialCall)
ApiStatus EnableActorGlow (Evt *script, s32 isInitialCall)
ApiStatus WasStatusInflicted (Evt *script, s32 isInitialCall)
ApiStatus CopyStatusEffects (Evt *script, s32 isInitialCall)
ApiStatus ClearStatusEffects (Evt *script, s32 isInitialCall)
ApiStatus MakeOwnerTargetIndex (Evt *script, s32 isInitialCall)
ApiStatus GetActorLevel (Evt *script, s32 isInitialCall)
ApiStatus PartnerDamageEnemy (Evt *script, s32 isInitialCall)
ApiStatus PartnerAfflictEnemy (Evt *script, s32 isInitialCall)
ApiStatus PartnerPowerBounceEnemy (Evt *script, s32 isInitialCall)
ApiStatus PartnerTestEnemy (Evt *script, s32 isInitialCall)
ApiStatus DeletePartner (Evt *script, s32 isInitialCall)
ApiStatus GetDamageIntensity (Evt *script, s32 isInitialCall)
ApiStatus AddEffectOffset (Evt *script, s32 isInitialCall)
ApiStatus LoadStarPowerScript (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_B (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_F (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_M (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_G (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_I (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_H (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_N (Evt *script, s32 isInitialCall)
ApiStatus BattleCamImpl_Default (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_D (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_E (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_J (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_K (Evt *script, s32 isInitialCall)
ApiStatus CamPresetUpdate_L (Evt *script, s32 isInitialCall)
ApiStatus SetBattleCamPos (Evt *script, s32 isInitialCall)
ApiStatus SetBattleCamParam (Evt *script, s32 isInitialCall)
ApiStatus GetPartAnimNotify (Evt *script, s32 isInitialCall)
ApiStatus InitAnimatedModels (Evt *script, s32 isInitialCall)
ApiStatus func_8024CE9C (Evt *script, s32 isInitialCall)
ApiStatus func_802CAE50 (Evt *script, s32 isInitialCall)
ApiStatus func_802807D0 (Evt *script, s32 isInitialCall)
ApiStatus PartnerYieldTurn (Evt *script, s32 isInitialCall)
YieldTurn copy.
ApiStatus func_8024ECF8 (Evt *script, s32 isInitialCall)
ApiStatus UseBattleCamPresetImmediately (Evt *script, s32 isInitialCall)
ApiStatus UseBattleCamPresetWait (Evt *script, s32 isInitialCall)
ApiStatus HideHealthBar (Evt *script, s32 isInitialCall)
ApiStatus GetPartnerActionSuccess (Evt *script, s32 isInitialCall)
ApiStatus CreateNpc (Evt *script, s32 isInitialCall)
ApiStatus EnableBattleStatusBar (Evt *script, s32 isInitialCall)
ApiStatus PlayerYieldTurn (Evt *script, s32 isInitialCall)
ApiStatus ShowStartRecoveryShimmer (Evt *script, s32 isInitialCall)
ApiStatus ShowRecoveryShimmer (Evt *script, s32 isInitialCall)
ApiStatus func_80273444 (Evt *script, s32 isInitialCall)
ApiStatus WaitForState (Evt *script, s32 isInitialCall)
ApiStatus SetBattleMenuEnabledFlags (Evt *script, s32 isInitialCall)
ApiStatus SetBattleState (Evt *script, s32 isInitialCall)
ApiStatus func_8027D434 (Evt *script, s32 isInitialCall)
ApiStatus func_8026F1A0 (Evt *script, s32 isInitialCall)
ApiStatus PlayLoopingSoundAtActor (Evt *script, s32 isInitialCall)
ApiStatus StopLoopingSoundAtActor (Evt *script, s32 isInitialCall)
ApiStatus EnableActorPaletteEffects (Evt *script, s32 isInitialCall)
ApiStatus SetActorPaletteSwapParams (Evt *script, s32 isInitialCall)
ApiStatus BattleCamTargetActorPart (Evt *script, s32 isInitialCall)
ApiStatus GetDarknessStatus (Evt *script, s32 isInitialCall)
ApiStatus CancelEnemyTurn (Evt *script, s32 isInitialCall)
ApiStatus GetAnimatedNodeRotation (Evt *script, s32 isInitialCall)
ApiStatus GetAnimatedNodePosition (Evt *script, s32 isInitialCall)
ApiStatus DispatchEventPlayer (Evt *script, s32 isInitialCall)
Variables
EvtScript EVS_Mario_HandlePhase
EvtScript EVS_Peach_HandlePhase
EvtScript EVS_ExecuteMarioAction
EvtScript EVS_ExecutePeachAction
EvtScript EVS_Player_HandleEvent
EvtScript BtlPutPartnerAway
EvtScript BtlBringPartnerOut
EvtScript EVS_MarioEnterStage
EvtScript EVS_PeachEnterStage
EvtScript EVS_PlayerFirstStrike
EvtScript EVS_StartDefend
EvtScript EVS_RunAwayStart
EvtScript EVS_RunAwayFail
EvtScript EVS_PlayerDies
EvtScript EVS_PlayEatFX
EvtScript EVS_PlayDrinkFX
EvtScript EVS_UseLifeShroom
EvtScript EVS_MerleeRunOut
EvtScript EVS_MerleeAttackBonus
EvtScript EVS_MerleeDefenseBonus
EvtScript EVS_MerleeExpBonus
EvtScript EVS_PlayerHappy
EvtScript EVS_ApplyDizzyAttack
EvtScript EVS_PlayerRegainAbility
EvtScript EVS_UseMystery
EvtScript EVS_PlaySleepHitFX
EvtScript EVS_PlayDizzyHitFX
EvtScript EVS_PlayParalyzeHitFX
EvtScript EVS_PlayPoisonHitFX
EvtScript EVS_PlayStopHitFX
EvtScript EVS_PlayFreezeHitFX
EvtScript EVS_PlayShrinkHitFX
EvtScript EVS_ForceNextTarget
EvtScript EVS_Enemy_Hit
EvtScript EVS_Partner_RunAway
EvtScript EVS_Partner_SpikeContact
EvtScript EVS_Partner_BombetteSpikeContact
EvtScript EVS_Partner_BurnContact
EvtScript EVS_Partner_Recover
EvtScript EVS_Partner_ShockHit
EvtScript EVS_Partner_BurnHit
EvtScript EVS_Partner_Hit
EvtScript EVS_Partner_Drop
EvtScript EVS_Partner_NoDamageHit
EvtScript EVS_Partner_LakilesterHit
EvtScript EVS_Enemy_HopToPos
EvtScript EVS_Enemy_BurnHit
EvtScript EVS_Enemy_ShockHit
EvtScript EVS_Enemy_ShockHit_Impl
EvtScript EVS_Partner_Celebrate
EvtScript EVS_Enemy_NoDamageHit
EvtScript EVS_Enemy_Death
EvtScript EVS_Enemy_DeathWithoutRemove
EvtScript EVS_Enemy_ScareAway
EvtScript EVS_Enemy_SpinSmashHit
EvtScript EVS_Enemy_FlipBackUp
EvtScript EVS_Enemy_Knockback
EvtScript EVS_Enemy_ReturnHome
EvtScript EVS_Enemy_Recover
EvtScript EVS_Enemy_HopHome
EvtScript EVS_Enemy_AirLift
EvtScript EVS_Enemy_BlowAway
EvtScript Rumble_1
EvtScript Rumble_2
EvtScript Rumble_3
EvtScript Rumble_4
EvtScript Rumble_5
EvtScript Rumble_6
EvtScript Rumble_7
EvtScript Rumble_Unused_1
EvtScript Rumble_Unused_2
EvtScript Rumble_Unused_3
EvtScript Rumble_Unused_4
EvtScript CamPreset_A
EvtScript CamPreset_B
EvtScript EVS_BattleCam_Default
EvtScript CamPreset_D
EvtScript CamPreset_E
EvtScript CamPreset_F
EvtScript CamPreset_G
EvtScript CamPreset_H
EvtScript CamPreset_I
EvtScript CamPreset_J
EvtScript CamPreset_K
EvtScript CamPreset_L
EvtScript CamPreset_M
EvtScript CamPreset_N
Function Documentation
ActorExists()
ApiStatus ActorExists (Evt * script, s32 isInitialCall)
ActorSpeak()
ApiStatus ActorSpeak (Evt * script, s32 isInitialCall)
AddActorDecoration()
ApiStatus AddActorDecoration (Evt * script, s32 isInitialCall)
Referenced by A().
AddActorPos()
ApiStatus AddActorPos (Evt * script, s32 isInitialCall)
AddActorVar()
ApiStatus AddActorVar (Evt * script, s32 isInitialCall)
AddBattleCamOffsetZ()
ApiStatus AddBattleCamOffsetZ (Evt * script, s32 isInitialCall)
AddBattleCamZoom()
ApiStatus AddBattleCamZoom (Evt * script, s32 isInitialCall)
AddEffectOffset()
ApiStatus AddEffectOffset (Evt * script, s32 isInitialCall)
AddGoalPos()
ApiStatus AddGoalPos (Evt * script, s32 isInitialCall)
Referenced by A().
AddPartDispOffset()
ApiStatus AddPartDispOffset (Evt * script, s32 isInitialCall)
AddPartMovementVar()
ApiStatus AddPartMovementVar (Evt * script, s32 isInitialCall)
AfflictActor()
ApiStatus AfflictActor (Evt * script, s32 isInitialCall)
Bug
should be STATUS_TURN_MOD_FROZEN
ApplyShrinkFromOwner()
ApiStatus ApplyShrinkFromOwner (Evt * script, s32 isInitialCall)
BattleCamImpl_Default()
ApiStatus BattleCamImpl_Default (Evt * script, s32 isInitialCall)
BattleCamTargetActor()
ApiStatus BattleCamTargetActor (Evt * script, s32 isInitialCall)
BattleCamTargetActorPart()
ApiStatus BattleCamTargetActorPart (Evt * script, s32 isInitialCall)
BindHandleEvent()
ApiStatus BindHandleEvent (Evt * script, s32 isInitialCall)
BindHandlePhase()
ApiStatus BindHandlePhase (Evt * script, s32 isInitialCall)
BindIdle()
ApiStatus BindIdle (Evt * script, s32 isInitialCall)
BindTakeTurn()
ApiStatus BindTakeTurn (Evt * script, s32 isInitialCall)
BoostAttack()
ApiStatus BoostAttack (Evt * script, s32 isInitialCall)
BoostDefense()
ApiStatus BoostDefense (Evt * script, s32 isInitialCall)
CamPresetUpdate_B()
ApiStatus CamPresetUpdate_B (Evt * script, s32 isInitialCall)
CamPresetUpdate_D()
ApiStatus CamPresetUpdate_D (Evt * script, s32 isInitialCall)
CamPresetUpdate_E()
ApiStatus CamPresetUpdate_E (Evt * script, s32 isInitialCall)
CamPresetUpdate_F()
ApiStatus CamPresetUpdate_F (Evt * script, s32 isInitialCall)
CamPresetUpdate_G()
ApiStatus CamPresetUpdate_G (Evt * script, s32 isInitialCall)
CamPresetUpdate_H()
ApiStatus CamPresetUpdate_H (Evt * script, s32 isInitialCall)
CamPresetUpdate_I()
ApiStatus CamPresetUpdate_I (Evt * script, s32 isInitialCall)
CamPresetUpdate_J()
ApiStatus CamPresetUpdate_J (Evt * script, s32 isInitialCall)
CamPresetUpdate_K()
ApiStatus CamPresetUpdate_K (Evt * script, s32 isInitialCall)
CamPresetUpdate_L()
ApiStatus CamPresetUpdate_L (Evt * script, s32 isInitialCall)
CamPresetUpdate_M()
ApiStatus CamPresetUpdate_M (Evt * script, s32 isInitialCall)
CamPresetUpdate_N()
ApiStatus CamPresetUpdate_N (Evt * script, s32 isInitialCall)
CancelablePlayerRunToGoal()
ApiStatus CancelablePlayerRunToGoal (Evt * script, s32 isInitialCall)
CancelEnemyTurn()
ApiStatus CancelEnemyTurn (Evt * script, s32 isInitialCall)
CheckButtonDown()
ApiStatus CheckButtonDown (Evt * script, s32 isInitialCall)
CheckButtonHeld()
ApiStatus CheckButtonHeld (Evt * script, s32 isInitialCall)
CheckButtonPress()
ApiStatus CheckButtonPress (Evt * script, s32 isInitialCall)
ChooseNextTarget()
ApiStatus ChooseNextTarget (Evt * script, s32 isInitialCall)
ClearStatusEffects()
ApiStatus ClearStatusEffects (Evt * script, s32 isInitialCall)
CopyBuffs()
ApiStatus CopyBuffs (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
CopyStatusEffects()
ApiStatus CopyStatusEffects (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
CountTargets()
ApiStatus CountTargets (Evt * script, s32 isInitialCall)
CreateCurrentPosTargetList()
ApiStatus CreateCurrentPosTargetList (Evt * script, s32 isInitialCall)
CreateHomeTargetList()
ApiStatus CreateHomeTargetList (Evt * script, s32 isInitialCall)
CreateNpc()
ApiStatus CreateNpc (Evt * script, s32 isInitialCall)
CreatePartShadow()
ApiStatus CreatePartShadow (Evt * script, s32 isInitialCall)
DeletePartner()
ApiStatus DeletePartner (Evt * script, s32 isInitialCall)
DisablePartnerBlur()
ApiStatus DisablePartnerBlur (Evt * script, s32 isInitialCall)
DispatchDamageEvent()
ApiStatus DispatchDamageEvent (Evt * script, s32 isInitialCall)
DispatchDamagePlayerEvent()
ApiStatus DispatchDamagePlayerEvent (Evt * script, s32 isInitialCall)
DispatchEvent()
ApiStatus DispatchEvent (Evt * script, s32 isInitialCall)
DispatchEventPlayer()
ApiStatus DispatchEventPlayer (Evt * script, s32 isInitialCall)
DropStarPoints()
ApiStatus DropStarPoints (Evt * script, s32 isInitialCall)
ElectrifyActor()
ApiStatus ElectrifyActor (Evt * script, s32 isInitialCall)
EnableActorBlur()
ApiStatus EnableActorBlur (Evt * script, s32 isInitialCall)
EnableActorGlow()
ApiStatus EnableActorGlow (Evt * script, s32 isInitialCall)
EnableActorPaletteEffects()
ApiStatus EnableActorPaletteEffects (Evt * script, s32 isInitialCall)
EnableBattleFloorReflections()
ApiStatus EnableBattleFloorReflections (Evt * script, s32 isInitialCall)
EnableBattleStatusBar()
ApiStatus EnableBattleStatusBar (Evt * script, s32 isInitialCall)
EnableIdleScript()
ApiStatus EnableIdleScript (Evt * script, s32 isInitialCall)
EnablePartnerBlur()
ApiStatus EnablePartnerBlur (Evt * script, s32 isInitialCall)
EnablePlayerBlur()
ApiStatus EnablePlayerBlur (Evt * script, s32 isInitialCall)
EndActorSpeech()
ApiStatus EndActorSpeech (Evt * script, s32 isInitialCall)
EnemyDamageTarget()
ApiStatus EnemyDamageTarget (Evt * script, s32 isInitialCall)
EnemyFollowupAfflictTarget()
ApiStatus EnemyFollowupAfflictTarget (Evt * script, s32 isInitialCall)
EnemyTestTarget()
ApiStatus EnemyTestTarget (Evt * script, s32 isInitialCall)
FallPartTo()
ApiStatus FallPartTo (Evt * script, s32 isInitialCall)
FallToGoal()
ApiStatus FallToGoal (Evt * script, s32 isInitialCall)
FlyPartTo()
ApiStatus FlyPartTo (Evt * script, s32 isInitialCall)
FlyToGoal()
ApiStatus FlyToGoal (Evt * script, s32 isInitialCall)
ForceCloseMessageBox()
ApiStatus ForceCloseMessageBox (Evt * script, s32 isInitialCall)
ForceHomePos()
ApiStatus ForceHomePos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
FreezeBattleCam()
ApiStatus FreezeBattleCam (Evt * script, s32 isInitialCall)
FreezeBattleState()
ApiStatus FreezeBattleState (Evt * script, s32 isInitialCall)
func_8024CE9C()
ApiStatus func_8024CE9C (Evt * script, s32 isInitialCall)
func_8024ECF8()
ApiStatus func_8024ECF8 (Evt * script, s32 isInitialCall)
func_8024EDA4()
ApiStatus func_8024EDA4 (Evt * script, s32 isInitialCall)
func_8026E914()
ApiStatus func_8026E914 (Evt * script, s32 isInitialCall)
func_8026F1A0()
ApiStatus func_8026F1A0 (Evt * script, s32 isInitialCall)
func_80273444()
ApiStatus func_80273444 (Evt * script, s32 isInitialCall)
func_80274A18()
ApiStatus func_80274A18 (Evt * script, s32 isInitialCall)
func_802752AC()
ApiStatus func_802752AC (Evt * script, s32 isInitialCall)
func_80275F00()
ApiStatus func_80275F00 (Evt * script, s32 isInitialCall)
func_8027D434()
ApiStatus func_8027D434 (Evt * script, s32 isInitialCall)
func_802807D0()
ApiStatus func_802807D0 (Evt * script, s32 isInitialCall)
func_802CAE50()
ApiStatus func_802CAE50 (Evt * script, s32 isInitialCall)
GetActorAttackBoost()
ApiStatus GetActorAttackBoost (Evt * script, s32 isInitialCall)
GetActorDefenseBoost()
ApiStatus GetActorDefenseBoost (Evt * script, s32 isInitialCall)
GetActorFlags()
ApiStatus GetActorFlags (Evt * script, s32 isInitialCall)
GetActorHP()
ApiStatus GetActorHP (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
GetActorLevel()
ApiStatus GetActorLevel (Evt * script, s32 isInitialCall)
GetActorPos()
ApiStatus GetActorPos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
GetActorRotation()
ApiStatus GetActorRotation (Evt * script, s32 isInitialCall)
GetActorScale()
ApiStatus GetActorScale (Evt * script, s32 isInitialCall)
GetActorSize()
ApiStatus GetActorSize (Evt * script, s32 isInitialCall)
GetActorVar()
ApiStatus GetActorVar (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
GetActorYaw()
ApiStatus GetActorYaw (Evt * script, s32 isInitialCall)
GetAnimatedNodePosition()
ApiStatus GetAnimatedNodePosition (Evt * script, s32 isInitialCall)
GetAnimatedNodeRotation()
ApiStatus GetAnimatedNodeRotation (Evt * script, s32 isInitialCall)
GetAnimation()
ApiStatus GetAnimation (Evt * script, s32 isInitialCall)
GetBattleFlags()
ApiStatus GetBattleFlags (Evt * script, s32 isInitialCall)
GetBattleFlags2()
ApiStatus GetBattleFlags2 (Evt * script, s32 isInitialCall)
GetBattlePhase()
ApiStatus GetBattlePhase (Evt * script, s32 isInitialCall)
GetBattleState()
ApiStatus GetBattleState (Evt * script, s32 isInitialCall)
GetBattleVar()
ApiStatus GetBattleVar (Evt * script, s32 isInitialCall)
GetCurrentActorType()
ApiStatus GetCurrentActorType (Evt * script, s32 isInitialCall)
GetDamageIntensity()
ApiStatus GetDamageIntensity (Evt * script, s32 isInitialCall)
GetDamageSource()
ApiStatus GetDamageSource (Evt * script, s32 isInitialCall)
GetDarknessStatus()
ApiStatus GetDarknessStatus (Evt * script, s32 isInitialCall)
GetDistanceToGoal()
ApiStatus GetDistanceToGoal (Evt * script, s32 isInitialCall)
GetEncounterTrigger()
ApiStatus GetEncounterTrigger (Evt * script, s32 isInitialCall)
GetEnemyMaxHP()
ApiStatus GetEnemyMaxHP (Evt * script, s32 isInitialCall)
GetGoalPos()
ApiStatus GetGoalPos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
GetHomePos()
ApiStatus GetHomePos (Evt * script, s32 isInitialCall)
GetIdleGoal()
ApiStatus GetIdleGoal (Evt * script, s32 isInitialCall)
GetIndexFromHome()
ApiStatus GetIndexFromHome (Evt * script, s32 isInitialCall)
GetIndexFromPos()
ApiStatus GetIndexFromPos (Evt * script, s32 isInitialCall)
GetInstigatorValue()
ApiStatus GetInstigatorValue (Evt * script, s32 isInitialCall)
GetLastDamage()
ApiStatus GetLastDamage (Evt * script, s32 isInitialCall)
GetLastElement()
ApiStatus GetLastElement (Evt * script, s32 isInitialCall)
GetLastEvent()
ApiStatus GetLastEvent (Evt * script, s32 isInitialCall)
GetMenuSelection()
ApiStatus GetMenuSelection (Evt * script, s32 isInitialCall)
GetOriginalActorType()
ApiStatus GetOriginalActorType (Evt * script, s32 isInitialCall)
GetOwnerID()
ApiStatus GetOwnerID (Evt * script, s32 isInitialCall)
GetOwnerTarget()
ApiStatus GetOwnerTarget (Evt * script, s32 isInitialCall)
GetPartAnimNotify()
ApiStatus GetPartAnimNotify (Evt * script, s32 isInitialCall)
GetPartDispOffset()
ApiStatus GetPartDispOffset (Evt * script, s32 isInitialCall)
GetPartEventFlags()
ApiStatus GetPartEventFlags (Evt * script, s32 isInitialCall)
GetPartFlags()
ApiStatus GetPartFlags (Evt * script, s32 isInitialCall)
GetPartMovementVar()
ApiStatus GetPartMovementVar (Evt * script, s32 isInitialCall)
GetPartnerActionSuccess()
ApiStatus GetPartnerActionSuccess (Evt * script, s32 isInitialCall)
GetPartOffset()
ApiStatus GetPartOffset (Evt * script, s32 isInitialCall)
GetPartPos()
ApiStatus GetPartPos (Evt * script, s32 isInitialCall)
GetPartRotation()
ApiStatus GetPartRotation (Evt * script, s32 isInitialCall)
GetPartScale()
ApiStatus GetPartScale (Evt * script, s32 isInitialCall)
GetPartTarget()
ApiStatus GetPartTarget (Evt * script, s32 isInitialCall)
GetPartTargetFlags()
ApiStatus GetPartTargetFlags (Evt * script, s32 isInitialCall)
GetPartYaw()
ApiStatus GetPartYaw (Evt * script, s32 isInitialCall)
GetPlayerActionSuccess()
ApiStatus GetPlayerActionSuccess (Evt * script, s32 isInitialCall)
GetPlayerActorID()
ApiStatus GetPlayerActorID (Evt * script, s32 isInitialCall)
GetPlayerHP()
ApiStatus GetPlayerHP (Evt * script, s32 isInitialCall)
GetStatusFlags()
ApiStatus GetStatusFlags (Evt * script, s32 isInitialCall)
GetTargetListLength()
ApiStatus GetTargetListLength (Evt * script, s32 isInitialCall)
HasMerleeCastsLeft()
ApiStatus HasMerleeCastsLeft (Evt * script, s32 isInitialCall)
HealActor()
ApiStatus HealActor (Evt * script, s32 isInitialCall)
HideHealthBar()
ApiStatus HideHealthBar (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
HPBarToCurrent()
ApiStatus HPBarToCurrent (Evt * script, s32 isInitialCall)
HPBarToHome()
ApiStatus HPBarToHome (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
IdleFlyToGoal()
ApiStatus IdleFlyToGoal (Evt * script, s32 isInitialCall)
IdleJumpToGoal()
ApiStatus IdleJumpToGoal (Evt * script, s32 isInitialCall)
IdleRunToGoal()
ApiStatus IdleRunToGoal (Evt * script, s32 isInitialCall)
IncrementPlayerFP()
ApiStatus IncrementPlayerFP (Evt * script, s32 isInitialCall)
IncrementPlayerHP()
ApiStatus IncrementPlayerHP (Evt * script, s32 isInitialCall)
InitAnimatedModels()
ApiStatus InitAnimatedModels (Evt * script, s32 isInitialCall)
InitTargetIterator()
ApiStatus InitTargetIterator (Evt * script, s32 isInitialCall)
IsMessageBoxDisplayed()
ApiStatus IsMessageBoxDisplayed (Evt * script, s32 isInitialCall)
ItemAfflictEnemy()
ApiStatus ItemAfflictEnemy (Evt * script, s32 isInitialCall)
ItemCheckHit()
ApiStatus ItemCheckHit (Evt * script, s32 isInitialCall)
ItemDamageEnemy()
ApiStatus ItemDamageEnemy (Evt * script, s32 isInitialCall)
ItemSpookEnemy()
ApiStatus ItemSpookEnemy (Evt * script, s32 isInitialCall)
JumpPartTo()
ApiStatus JumpPartTo (Evt * script, s32 isInitialCall)
JumpToGoal()
ApiStatus JumpToGoal (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
JumpWithBounce()
ApiStatus JumpWithBounce (Evt * script, s32 isInitialCall)
LandJump()
ApiStatus LandJump (Evt * script, s32 isInitialCall)
LandJumpPart()
ApiStatus LandJumpPart (Evt * script, s32 isInitialCall)
LoadBattleDmaData()
ApiStatus LoadBattleDmaData (Evt * script, s32 isInitialCall)
LoadBattleSection()
ApiStatus LoadBattleSection (Evt * script, s32 isInitialCall)
LoadItemScript()
ApiStatus LoadItemScript (Evt * script, s32 isInitialCall)
LoadMoveScript()
ApiStatus LoadMoveScript (Evt * script, s32 isInitialCall)
LoadStarPowerScript()
ApiStatus LoadStarPowerScript (Evt * script, s32 isInitialCall)
MakeOwnerTargetIndex()
ApiStatus MakeOwnerTargetIndex (Evt * script, s32 isInitialCall)
MakeStatusField()
ApiStatus MakeStatusField (Evt * script, s32 isInitialCall)
ModifyActorDecoration()
ApiStatus ModifyActorDecoration (Evt * script, s32 isInitialCall)
MoveBattleCamOver()
ApiStatus MoveBattleCamOver (Evt * script, s32 isInitialCall)
MultiplyByActorScale()
ApiStatus MultiplyByActorScale (Evt * script, s32 isInitialCall)
MultiplyVec2ByActorScale()
ApiStatus MultiplyVec2ByActorScale (Evt * script, s32 isInitialCall)
MultiplyVec3ByActorScale()
ApiStatus MultiplyVec3ByActorScale (Evt * script, s32 isInitialCall)
OverrideBattleDmaDest()
ApiStatus OverrideBattleDmaDest (Evt * script, s32 isInitialCall)
PartnerAfflictEnemy()
ApiStatus PartnerAfflictEnemy (Evt * script, s32 isInitialCall)
PartnerDamageEnemy()
ApiStatus PartnerDamageEnemy (Evt * script, s32 isInitialCall)
PartnerPowerBounceEnemy()
ApiStatus PartnerPowerBounceEnemy (Evt * script, s32 isInitialCall)
PartnerTestEnemy()
ApiStatus PartnerTestEnemy (Evt * script, s32 isInitialCall)
PartnerYieldTurn()
ApiStatus PartnerYieldTurn (Evt * script, s32 isInitialCall)
YieldTurn copy.
YieldTurn copy.
PauseTakeTurn()
ApiStatus PauseTakeTurn (Evt * script, s32 isInitialCall)
PlayerDamageEnemy()
ApiStatus PlayerDamageEnemy (Evt * script, s32 isInitialCall)
PlayerFallToGoal()
ApiStatus PlayerFallToGoal (Evt * script, s32 isInitialCall)
PlayerLandJump()
ApiStatus PlayerLandJump (Evt * script, s32 isInitialCall)
PlayerPowerBounceEnemy()
ApiStatus PlayerPowerBounceEnemy (Evt * script, s32 isInitialCall)
PlayerRunToGoal()
ApiStatus PlayerRunToGoal (Evt * script, s32 isInitialCall)
PlayerTestEnemy()
ApiStatus PlayerTestEnemy (Evt * script, s32 isInitialCall)
PlayerYieldTurn()
ApiStatus PlayerYieldTurn (Evt * script, s32 isInitialCall)
PlayLoopingSoundAtActor()
ApiStatus PlayLoopingSoundAtActor (Evt * script, s32 isInitialCall)
PlaySoundAtActor()
ApiStatus PlaySoundAtActor (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), and A().
PlaySoundAtPart()
ApiStatus PlaySoundAtPart (Evt * script, s32 isInitialCall)
RemoveActor()
ApiStatus RemoveActor (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
RemoveActorDecoration()
ApiStatus RemoveActorDecoration (Evt * script, s32 isInitialCall)
Referenced by A().
RemovePartShadow()
ApiStatus RemovePartShadow (Evt * script, s32 isInitialCall)
RemovePlayerBuffs()
ApiStatus RemovePlayerBuffs (Evt * script, s32 isInitialCall)
ResetActorSounds()
ApiStatus ResetActorSounds (Evt * script, s32 isInitialCall)
Referenced by A(), and A().
ResetAllActorSounds()
ApiStatus ResetAllActorSounds (Evt * script, s32 isInitialCall)
ResumeTakeTurn()
ApiStatus ResumeTakeTurn (Evt * script, s32 isInitialCall)
RunPartTo()
ApiStatus RunPartTo (Evt * script, s32 isInitialCall)
RunToGoal()
ApiStatus RunToGoal (Evt * script, s32 isInitialCall)
Referenced by A().
SetActorDispOffset()
ApiStatus SetActorDispOffset (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorFlagBits()
ApiStatus SetActorFlagBits (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorFlags()
ApiStatus SetActorFlags (Evt * script, s32 isInitialCall)
SetActorIdleJumpGravity()
ApiStatus SetActorIdleJumpGravity (Evt * script, s32 isInitialCall)
SetActorIdleSpeed()
ApiStatus SetActorIdleSpeed (Evt * script, s32 isInitialCall)
SetActorJumpGravity()
ApiStatus SetActorJumpGravity (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
SetActorPaletteEffect()
ApiStatus SetActorPaletteEffect (Evt * script, s32 isInitialCall)
SetActorPaletteSwapParams()
ApiStatus SetActorPaletteSwapParams (Evt * script, s32 isInitialCall)
SetActorPos()
ApiStatus SetActorPos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorRotation()
ApiStatus SetActorRotation (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorRotationOffset()
ApiStatus SetActorRotationOffset (Evt * script, s32 isInitialCall)
Referenced by A(), and A().
SetActorScale()
ApiStatus SetActorScale (Evt * script, s32 isInitialCall)
Referenced by A(), and A().
SetActorScaleModifier()
ApiStatus SetActorScaleModifier (Evt * script, s32 isInitialCall)
SetActorSize()
ApiStatus SetActorSize (Evt * script, s32 isInitialCall)
SetActorSounds()
ApiStatus SetActorSounds (Evt * script, s32 isInitialCall)
Referenced by A(), and A().
SetActorSpeed()
ApiStatus SetActorSpeed (Evt * script, s32 isInitialCall)
Referenced by A().
SetActorStatusOffsets()
ApiStatus SetActorStatusOffsets (Evt * script, s32 isInitialCall)
SetActorType()
ApiStatus SetActorType (Evt * script, s32 isInitialCall)
SetActorVar()
ApiStatus SetActorVar (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetActorYaw()
ApiStatus SetActorYaw (Evt * script, s32 isInitialCall)
Referenced by A().
SetAnimation()
ApiStatus SetAnimation (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
SetAnimationRate()
ApiStatus SetAnimationRate (Evt * script, s32 isInitialCall)
SetBattleCamOffsetZ()
ApiStatus SetBattleCamOffsetZ (Evt * script, s32 isInitialCall)
SetBattleCamParam()
ApiStatus SetBattleCamParam (Evt * script, s32 isInitialCall)
SetBattleCamPos()
ApiStatus SetBattleCamPos (Evt * script, s32 isInitialCall)
SetBattleCamTarget()
ApiStatus SetBattleCamTarget (Evt * script, s32 isInitialCall)
SetBattleCamYaw()
ApiStatus SetBattleCamYaw (Evt * script, s32 isInitialCall)
SetBattleCamZoom()
ApiStatus SetBattleCamZoom (Evt * script, s32 isInitialCall)
SetBattleFlagBits()
ApiStatus SetBattleFlagBits (Evt * script, s32 isInitialCall)
SetBattleFlagBits2()
ApiStatus SetBattleFlagBits2 (Evt * script, s32 isInitialCall)
SetBattleInputButtons()
ApiStatus SetBattleInputButtons (Evt * script, s32 isInitialCall)
SetBattleInputMask()
ApiStatus SetBattleInputMask (Evt * script, s32 isInitialCall)
SetBattleMenuEnabledFlags()
ApiStatus SetBattleMenuEnabledFlags (Evt * script, s32 isInitialCall)
SetBattleState()
ApiStatus SetBattleState (Evt * script, s32 isInitialCall)
SetBattleVar()
ApiStatus SetBattleVar (Evt * script, s32 isInitialCall)
SetDamageSource()
ApiStatus SetDamageSource (Evt * script, s32 isInitialCall)
SetDarknessMode()
ApiStatus SetDarknessMode (Evt * script, s32 isInitialCall)
SetDefenseTable()
ApiStatus SetDefenseTable (Evt * script, s32 isInitialCall)
SetEnabledStarPowers()
ApiStatus SetEnabledStarPowers (Evt * script, s32 isInitialCall)
SetEndBattleFadeOutRate()
ApiStatus SetEndBattleFadeOutRate (Evt * script, s32 isInitialCall)
SetEnemyHP()
ApiStatus SetEnemyHP (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetEnemyTargetOffset()
ApiStatus SetEnemyTargetOffset (Evt * script, s32 isInitialCall)
SetForegroundModelsVisible()
ApiStatus SetForegroundModelsVisible (Evt * script, s32 isInitialCall)
SetForegroundModelsVisibleUnchecked()
ApiStatus SetForegroundModelsVisibleUnchecked (Evt * script, s32 isInitialCall)
SetGoalPos()
ApiStatus SetGoalPos (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
SetGoalToFirstTarget()
ApiStatus SetGoalToFirstTarget (Evt * script, s32 isInitialCall)
SetGoalToHome()
ApiStatus SetGoalToHome (Evt * script, s32 isInitialCall)
Referenced by A().
SetGoalToIndex()
ApiStatus SetGoalToIndex (Evt * script, s32 isInitialCall)
SetGoalToTarget()
ApiStatus SetGoalToTarget (Evt * script, s32 isInitialCall)
SetHomePos()
ApiStatus SetHomePos (Evt * script, s32 isInitialCall)
SetHPBarOffset()
ApiStatus SetHPBarOffset (Evt * script, s32 isInitialCall)
SetIdleAnimations()
ApiStatus SetIdleAnimations (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetIdleGoal()
ApiStatus SetIdleGoal (Evt * script, s32 isInitialCall)
SetIdleGoalToHome()
ApiStatus SetIdleGoalToHome (Evt * script, s32 isInitialCall)
SetJumpAnimations()
ApiStatus SetJumpAnimations (Evt * script, s32 isInitialCall)
SetMessageBoxDuration()
ApiStatus SetMessageBoxDuration (Evt * script, s32 isInitialCall)
SetOwnerID()
ApiStatus SetOwnerID (Evt * script, s32 isInitialCall)
SetOwnerTarget()
ApiStatus SetOwnerTarget (Evt * script, s32 isInitialCall)
SetPartAlpha()
ApiStatus SetPartAlpha (Evt * script, s32 isInitialCall)
SetPartDispOffset()
ApiStatus SetPartDispOffset (Evt * script, s32 isInitialCall)
SetPartEventBits()
ApiStatus SetPartEventBits (Evt * script, s32 isInitialCall)
SetPartEventFlags()
ApiStatus SetPartEventFlags (Evt * script, s32 isInitialCall)
SetPartFlagBits()
ApiStatus SetPartFlagBits (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
SetPartFlags()
ApiStatus SetPartFlags (Evt * script, s32 isInitialCall)
SetPartGoalToTarget()
ApiStatus SetPartGoalToTarget (Evt * script, s32 isInitialCall)
SetPartJumpGravity()
ApiStatus SetPartJumpGravity (Evt * script, s32 isInitialCall)
SetPartMovementVar()
ApiStatus SetPartMovementVar (Evt * script, s32 isInitialCall)
SetPartMoveSpeed()
ApiStatus SetPartMoveSpeed (Evt * script, s32 isInitialCall)
SetPartPos()
ApiStatus SetPartPos (Evt * script, s32 isInitialCall)
SetPartRotation()
ApiStatus SetPartRotation (Evt * script, s32 isInitialCall)
SetPartRotationOffset()
ApiStatus SetPartRotationOffset (Evt * script, s32 isInitialCall)
SetPartScale()
ApiStatus SetPartScale (Evt * script, s32 isInitialCall)
SetPartSize()
ApiStatus SetPartSize (Evt * script, s32 isInitialCall)
SetPartSounds()
ApiStatus SetPartSounds (Evt * script, s32 isInitialCall)
SetPartTargetFlagBits()
ApiStatus SetPartTargetFlagBits (Evt * script, s32 isInitialCall)
SetPartTargetFlags()
ApiStatus SetPartTargetFlags (Evt * script, s32 isInitialCall)
SetPartYaw()
ApiStatus SetPartYaw (Evt * script, s32 isInitialCall)
SetProjectileTargetOffset()
ApiStatus SetProjectileTargetOffset (Evt * script, s32 isInitialCall)
SetStatusTable()
ApiStatus SetStatusTable (Evt * script, s32 isInitialCall)
SetTargetActor()
ApiStatus SetTargetActor (Evt * script, s32 isInitialCall)
SetTargetOffset()
ApiStatus SetTargetOffset (Evt * script, s32 isInitialCall)
ShowBattleChoice()
ApiStatus ShowBattleChoice (Evt * script, s32 isInitialCall)
ShowHealthBar()
ApiStatus ShowHealthBar (Evt * script, s32 isInitialCall)
ShowMessageBox()
ApiStatus ShowMessageBox (Evt * script, s32 isInitialCall)
ShowRecoveryShimmer()
ApiStatus ShowRecoveryShimmer (Evt * script, s32 isInitialCall)
ShowShockEffect()
ApiStatus ShowShockEffect (Evt * script, s32 isInitialCall)
ShowStartRecoveryShimmer()
ApiStatus ShowStartRecoveryShimmer (Evt * script, s32 isInitialCall)
ShowVariableMessageBox()
ApiStatus ShowVariableMessageBox (Evt * script, s32 isInitialCall)
SpawnRecoverFlowerFX()
ApiStatus SpawnRecoverFlowerFX (Evt * script, s32 isInitialCall)
SpawnRecoverHeartFX()
ApiStatus SpawnRecoverHeartFX (Evt * script, s32 isInitialCall)
StartRumble()
ApiStatus StartRumble (Evt * script, s32 isInitialCall)
StartRumbleWithParams()
ApiStatus StartRumbleWithParams (Evt * script, s32 isInitialCall)
StopLoopingSoundAtActor()
ApiStatus StopLoopingSoundAtActor (Evt * script, s32 isInitialCall)
SummonEnemy()
ApiStatus SummonEnemy (Evt * script, s32 isInitialCall)
UseBattleCamPreset()
ApiStatus UseBattleCamPreset (Evt * script, s32 isInitialCall)
Referenced by A(), A(), A(), A(), and A().
UseBattleCamPresetImmediately()
ApiStatus UseBattleCamPresetImmediately (Evt * script, s32 isInitialCall)
UseBattleCamPresetWait()
ApiStatus UseBattleCamPresetWait (Evt * script, s32 isInitialCall)
UseIdleAnimation()
ApiStatus UseIdleAnimation (Evt * script, s32 isInitialCall)
Referenced by A(), A(), and A().
VanishActor()
ApiStatus VanishActor (Evt * script, s32 isInitialCall)
WaitForBuffDone()
ApiStatus WaitForBuffDone (Evt * script, s32 isInitialCall)
WaitForMessageBoxDone()
ApiStatus WaitForMessageBoxDone (Evt * script, s32 isInitialCall)
WaitForState()
ApiStatus WaitForState (Evt * script, s32 isInitialCall)
WasStatusInflicted()
ApiStatus WasStatusInflicted (Evt * script, s32 isInitialCall)
YieldTurn()
ApiStatus YieldTurn (Evt * script, s32 isInitialCall)
Variable Documentation
BtlBringPartnerOut
EvtScript BtlBringPartnerOut extern
Referenced by btl_state_update_change_partner().
BtlPutPartnerAway
EvtScript BtlPutPartnerAway extern
Referenced by btl_state_update_change_partner().
CamPreset_A
EvtScript CamPreset_A extern
Referenced by btl_cam_use_preset_impl().
CamPreset_B
EvtScript CamPreset_B extern
Referenced by btl_cam_use_preset_impl().
CamPreset_D
EvtScript CamPreset_D extern
Referenced by btl_cam_use_preset_impl().
CamPreset_E
EvtScript CamPreset_E extern
Referenced by btl_cam_use_preset_impl().
CamPreset_F
EvtScript CamPreset_F extern
Referenced by btl_cam_use_preset_impl().
CamPreset_G
EvtScript CamPreset_G extern
Referenced by btl_cam_use_preset_impl().
CamPreset_H
EvtScript CamPreset_H extern
Referenced by btl_cam_use_preset_impl().
CamPreset_I
EvtScript CamPreset_I extern
Referenced by btl_cam_use_preset_impl().
CamPreset_J
EvtScript CamPreset_J extern
Referenced by btl_cam_use_preset_impl().
CamPreset_K
EvtScript CamPreset_K extern
Referenced by btl_cam_use_preset_impl().
CamPreset_L
EvtScript CamPreset_L extern
Referenced by btl_cam_use_preset_impl().
CamPreset_M
EvtScript CamPreset_M extern
Referenced by btl_cam_use_preset_impl().
CamPreset_N
EvtScript CamPreset_N extern
Referenced by btl_cam_use_preset_impl().
EVS_ApplyDizzyAttack
EvtScript EVS_ApplyDizzyAttack extern
Referenced by btl_state_update_normal_start().
EVS_BattleCam_Default
EvtScript EVS_BattleCam_Default extern
Referenced by btl_cam_use_preset_impl().
EVS_Enemy_AirLift
EvtScript EVS_Enemy_AirLift extern
EVS_Enemy_BlowAway
EvtScript EVS_Enemy_BlowAway extern
EVS_Enemy_BurnHit
EvtScript EVS_Enemy_BurnHit extern
EVS_Enemy_Death
EvtScript EVS_Enemy_Death extern
EVS_Enemy_DeathWithoutRemove
EvtScript EVS_Enemy_DeathWithoutRemove extern
EVS_Enemy_FlipBackUp
EvtScript EVS_Enemy_FlipBackUp extern
EVS_Enemy_Hit
EvtScript EVS_Enemy_Hit extern
EVS_Enemy_HopHome
EvtScript EVS_Enemy_HopHome extern
EVS_Enemy_HopToPos
EvtScript EVS_Enemy_HopToPos extern
EVS_Enemy_Knockback
EvtScript EVS_Enemy_Knockback extern
EVS_Enemy_NoDamageHit
EvtScript EVS_Enemy_NoDamageHit extern
EVS_Enemy_Recover
EvtScript EVS_Enemy_Recover extern
EVS_Enemy_ReturnHome
EvtScript EVS_Enemy_ReturnHome extern
EVS_Enemy_ScareAway
EvtScript EVS_Enemy_ScareAway extern
EVS_Enemy_ShockHit
EvtScript EVS_Enemy_ShockHit extern
Referenced by A(), A(), and A().
EVS_Enemy_ShockHit_Impl
EvtScript EVS_Enemy_ShockHit_Impl extern
EVS_Enemy_SpinSmashHit
EvtScript EVS_Enemy_SpinSmashHit extern
EVS_ExecuteMarioAction
EvtScript EVS_ExecuteMarioAction extern
EVS_ExecutePeachAction
EvtScript EVS_ExecutePeachAction extern
EVS_ForceNextTarget
EvtScript EVS_ForceNextTarget extern
EVS_Mario_HandlePhase
EvtScript EVS_Mario_HandlePhase extern
Referenced by btl_state_update_9(), btl_state_update_celebration(), btl_state_update_defeat(), btl_state_update_defend(), btl_state_update_end_player_turn(), btl_state_update_first_strike(), btl_state_update_player_move(), btl_state_update_run_away(), and btl_state_update_victory().
EVS_MarioEnterStage
EvtScript EVS_MarioEnterStage extern
Referenced by btl_state_update_normal_start().
EVS_MerleeAttackBonus
EvtScript EVS_MerleeAttackBonus extern
EVS_MerleeDefenseBonus
EvtScript EVS_MerleeDefenseBonus extern
EVS_MerleeExpBonus
EvtScript EVS_MerleeExpBonus extern
EVS_MerleeRunOut
EvtScript EVS_MerleeRunOut extern
EVS_Partner_BombetteSpikeContact
EvtScript EVS_Partner_BombetteSpikeContact extern
EVS_Partner_BurnContact
EvtScript EVS_Partner_BurnContact extern
EVS_Partner_BurnHit
EvtScript EVS_Partner_BurnHit extern
EVS_Partner_Celebrate
EvtScript EVS_Partner_Celebrate extern
EVS_Partner_Drop
EvtScript EVS_Partner_Drop extern
EVS_Partner_Hit
EvtScript EVS_Partner_Hit extern
EVS_Partner_LakilesterHit
EvtScript EVS_Partner_LakilesterHit extern
EVS_Partner_NoDamageHit
EvtScript EVS_Partner_NoDamageHit extern
EVS_Partner_Recover
EvtScript EVS_Partner_Recover extern
EVS_Partner_RunAway
EvtScript EVS_Partner_RunAway extern
EVS_Partner_ShockHit
EvtScript EVS_Partner_ShockHit extern
EVS_Partner_SpikeContact
EvtScript EVS_Partner_SpikeContact extern
EVS_Peach_HandlePhase
EvtScript EVS_Peach_HandlePhase extern
Referenced by btl_state_update_player_move().
EVS_PeachEnterStage
EvtScript EVS_PeachEnterStage extern
Referenced by btl_state_update_normal_start().
EVS_PlayDizzyHitFX
EvtScript EVS_PlayDizzyHitFX extern
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayDrinkFX
EvtScript EVS_PlayDrinkFX extern
EVS_PlayEatFX
EvtScript EVS_PlayEatFX extern
EVS_Player_HandleEvent
EvtScript EVS_Player_HandleEvent extern
Referenced by dispatch_event_player(), and dispatch_event_player_continue_turn().
EVS_PlayerDies
EvtScript EVS_PlayerDies extern
EVS_PlayerFirstStrike
EvtScript EVS_PlayerFirstStrike extern
EVS_PlayerHappy
EvtScript EVS_PlayerHappy extern
EVS_PlayerRegainAbility
EvtScript EVS_PlayerRegainAbility extern
Referenced by btl_state_update_begin_player_turn().
EVS_PlayFreezeHitFX
EvtScript EVS_PlayFreezeHitFX extern
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayParalyzeHitFX
EvtScript EVS_PlayParalyzeHitFX extern
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayPoisonHitFX
EvtScript EVS_PlayPoisonHitFX extern
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayShrinkHitFX
EvtScript EVS_PlayShrinkHitFX extern
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlaySleepHitFX
EvtScript EVS_PlaySleepHitFX extern
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_PlayStopHitFX
EvtScript EVS_PlayStopHitFX extern
Referenced by calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), and calc_player_damage_enemy().
EVS_RunAwayFail
EvtScript EVS_RunAwayFail extern
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_RunAwayStart
EvtScript EVS_RunAwayStart extern
EVS_StartDefend
EvtScript EVS_StartDefend extern
EVS_UseLifeShroom
EvtScript EVS_UseLifeShroom extern
EVS_UseMystery
EvtScript EVS_UseMystery extern
Rumble_1
EvtScript Rumble_1 extern
Rumble_2
EvtScript Rumble_2 extern
Rumble_3
EvtScript Rumble_3 extern
Rumble_4
EvtScript Rumble_4 extern
Rumble_5
EvtScript Rumble_5 extern
Rumble_6
EvtScript Rumble_6 extern
Rumble_7
EvtScript Rumble_7 extern
Rumble_Unused_1
EvtScript Rumble_Unused_1 extern
Rumble_Unused_2
EvtScript Rumble_Unused_2 extern
Rumble_Unused_3
EvtScript Rumble_Unused_3 extern
Rumble_Unused_4
EvtScript Rumble_Unused_4 extern