papermario: src/inspect_icon.c File Reference
inspect_icon.c File Reference
Data Structures
struct InspectIconData
Macros
#define NAMESPACE inspect_icon
Enumerations
enum { INSPECT_ICON_APPEAR = 0 , INSPECT_ICON_HOLD = 1 , INSPECT_ICON_IDLE = 2 , INSPECT_ICON_VANISH = 3 }
Functions
INCLUDE_IMG ("inspect_icon.png", inspect_icon_img)
INCLUDE_PAL ("inspect_icon.pal", inspect_icon_pal)
void interact_inspect_update (void)
void interact_inspect_dismiss (void)
void interact_inspect_setup (void)
void appendGfx_interact_prompt (void)
s32 should_continue_inspect (void)
void update_inspect_icon_pos (void)
MATCHING_BSS (0x30)
Variables
BSS InspectIconData InspectIcon
InspectIconData * InspectIconPtr = &InspectIcon
Data Structure Documentation
InspectIconData
struct InspectIconData
Data Fields
s32 alpha
u8 brightness
s32 holdTime
s8 iconBounceDir
s8 iconBounceVel
Vec3f pos
f32 scale
u8 state
char unk_18[0x4]
char unk_20[0x1]
char unk_25[0x3]
f32 yaw
Macro Definition Documentation
NAMESPACE
#define NAMESPACE inspect_icon
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
INSPECT_ICON_APPEAR
INSPECT_ICON_HOLD
INSPECT_ICON_IDLE
INSPECT_ICON_VANISH
Function Documentation
appendGfx_interact_prompt()
void appendGfx_interact_prompt (void)
Referenced by render_interact_prompt().
INCLUDE_IMG()
INCLUDE_IMG ("inspect_icon.png" , inspect_icon_img)
INCLUDE_PAL()
INCLUDE_PAL ("inspect_icon.pal" , inspect_icon_pal)
interact_inspect_dismiss()
void interact_inspect_dismiss (void)
Referenced by interact_inspect_update().
interact_inspect_setup()
void interact_inspect_setup (void)
Referenced by check_for_interactables().
interact_inspect_update()
void interact_inspect_update (void)
Referenced by interact_inspect_setup().
MATCHING_BSS()
MATCHING_BSS (0x30)
should_continue_inspect()
s32 should_continue_inspect (void)
Referenced by interact_inspect_update().
update_inspect_icon_pos()
void update_inspect_icon_pos (void)
Referenced by interact_inspect_dismiss(), and interact_inspect_update().
Variable Documentation
InspectIcon
BSS InspectIconData InspectIcon
InspectIconPtr
InspectIconData* InspectIconPtr = &InspectIcon
Referenced by appendGfx_interact_prompt(), interact_inspect_setup(), interact_inspect_update(), and update_inspect_icon_pos().