papermario: src/inventory.c File Reference
inventory.c File Reference
Macros
#define FULLY_EXTENDED_Y 18
#define FULLY_RETRACTED_Y -100
Enumerations
enum BlinkModes { BLINK_OFF = 0 , BLINK_ON = 1 }
enum ShimmerStates { STATUS_SHIMMER_OFF = 0 , STATUS_SHIMMER_BEGIN = 1 , STATUS_SHIMMER_ON = 2 }
Functions
void status_bar_start_blinking_coins (void)
void status_bar_stop_blinking_coins (void)
void clear_player_data (void)
PlayerData * get_player_data (void)
s32 add_item (s32 itemID)
s32 get_item_count (void)
s32 get_item_empty_count (void)
s32 find_item (s32 itemID)
void sort_items (void)
Bubbles up player inventory items such that all ITEM_NONE values are at the bottom.
s32 add_badge (s32 itemID)
s32 store_item (s32 itemID)
s32 get_stored_count (void)
s32 get_stored_empty_count (void)
void enforce_hpfp_limits (void)
void initialize_status_bar (void)
void status_bar_draw_number (s32 iconID, s32 startX, s32 startY, s32 value, s32 numDigits)
void status_bar_draw_stat (s32 id, s32 startX, s32 startY, s32 currentValue, s32 maxValue)
void update_status_bar (void)
void coin_counter_draw_content (UNK_TYPE arg0, s32 posX, s32 posY)
void update_coin_counter (void)
void show_coin_counter (void)
void hide_coin_counter (void)
void hide_coin_counter_immediately (void)
void draw_status_ui (void)
void open_status_bar_slowly (void)
void open_status_bar_quickly (void)
void close_status_bar (void)
void setup_status_bar_for_world (void)
void setup_status_bar_for_battle (void)
void enable_status_bar_input (void)
void disable_status_bar_input (void)
b32 can_control_status_bar (void)
void status_bar_ignore_changes (void)
void status_bar_show_and_ignore_changes (void)
void status_bar_respond_to_changes (void)
s32 status_bar_is_ignoring_changes (void)
void status_bar_always_show_on (void)
void status_bar_always_show_off (void)
s32 is_status_bar_visible (void)
void status_bar_start_blinking_hp (void)
void status_bar_stop_blinking_hp (void)
void status_bar_start_blinking_fp (void)
void status_bar_stop_blinking_fp (void)
void status_bar_start_blinking_sp (void)
void status_bar_stop_blinking_sp (void)
void status_bar_start_blinking_sp_bars (s32 numBarsToBlink)
void status_bar_start_blinking_starpoints (void)
void status_bar_stop_blinking_starpoints (void)
void decrement_status_bar_disabled (void)
void increment_status_bar_disabled (void)
void sync_status_bar (void)
void reset_status_bar (void)
s32 is_ability_active (s32 ability)
s32 is_partner_ability_active (s32 ability)
s32 add_coins (s32 amt)
s32 add_star_points (s32 amt)
s32 add_star_pieces (s32 amt)
void increment_max_star_power (void)
void set_max_star_power (s8 newMax)
void add_star_power (s32 amt)
s32 recover_fp (s32 amt)
s32 recover_hp (s32 amt)
void subtract_hp (s32 amt)
s8 has_full_hp (void)
s8 has_full_fp (void)
s8 add_fortress_keys (s32 amt)
s32 subtract_fortress_keys (s32 amt)
s32 get_fortress_key_count (void)
Variables
BSS b16 ShowingCoinCounter
BSS b16 HidingCoinCounter
StatusBar gStatusBar
HudScript * TimesHudScript
HudScript * SPIncrementHudScripts []
HudScript * SPStarHudScripts []
s32 StatusBarSPIncrementOffsets []
HudScript * DigitHudScripts [10]
HudScript HES_StatusHP
HudScript HES_StatusHP_de
HudScript HES_StatusHP_fr
HudScript HES_StatusHP_es
HudScript HES_StatusHeart
HudScript HES_StatusFP
HudScript HES_StatusFP_de
HudScript HES_StatusFP_fr
HudScript HES_StatusFP_es
HudScript HES_StatusFlower
HudScript HES_Item_CoinSparkleRandom
HudScript HES_StatusStarPoint
HudScript HES_StatusStar1
HudScript HES_StatusTimes
HudScript HES_StatusSPShine
HudScript HES_StatusSPEmptyIncrement
HudScript HES_StatusStarEmpty
HudScript * SlashHudScript
Macro Definition Documentation
FULLY_EXTENDED_Y
#define FULLY_EXTENDED_Y 18
Referenced by status_bar_show_and_ignore_changes(), and update_status_bar().
FULLY_RETRACTED_Y
#define FULLY_RETRACTED_Y -100
Referenced by initialize_status_bar(), reset_status_bar(), setup_status_bar_for_world(), and update_status_bar().
Enumeration Type Documentation
BlinkModes
enum BlinkModes
Enumerator
BLINK_OFF
BLINK_ON
ShimmerStates
enum ShimmerStates
Enumerator
STATUS_SHIMMER_OFF
STATUS_SHIMMER_BEGIN
STATUS_SHIMMER_ON
Function Documentation
add_badge()
s32 add_badge (s32 itemID)
add_coins()
s32 add_coins (s32 amt)
add_fortress_keys()
s8 add_fortress_keys (s32 amt)
add_item()
s32 add_item (s32 itemID)
Referenced by add_badge(), and update_item_entity_pickup().
add_star_pieces()
s32 add_star_pieces (s32 amt)
add_star_points()
s32 add_star_points (s32 amt)
add_star_power()
void add_star_power (s32 amt)
can_control_status_bar()
b32 can_control_status_bar (void)
Referenced by check_input_status_bar().
clear_player_data()
void clear_player_data (void)
Referenced by filemenu_yesno_handle_input(), load_demo_battle(), load_engine_data(), state_init_title_screen(), state_step_demo(), state_step_intro(), and state_step_startup().
close_status_bar()
void close_status_bar (void)
Referenced by check_conversation_trigger(), check_input_status_bar(), destroy_popup_menu(), initialize_status_bar(), and shop_close_item_select_popup().
coin_counter_draw_content()
void coin_counter_draw_content (UNK_TYPE arg0, s32 posX, s32 posY)
Referenced by show_coin_counter().
decrement_status_bar_disabled()
void decrement_status_bar_disabled (void)
Referenced by btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_first_strike(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), and update_item_entity_pickup().
disable_status_bar_input()
void disable_status_bar_input (void)
draw_status_ui()
void draw_status_ui (void)
Referenced by btl_draw_ui(), state_drawUI_change_map(), state_drawUI_enter_world(), and state_drawUI_world().
enable_status_bar_input()
void enable_status_bar_input (void)
enforce_hpfp_limits()
void enforce_hpfp_limits (void)
Referenced by pause_badges_handle_input(), and pause_handle_input().
find_item()
s32 find_item (s32 itemID)
Returns
the index of the given item in the player's inventory, or -1 if not found
Referenced by btl_state_update_defeat().
get_fortress_key_count()
s32 get_fortress_key_count (void)
get_item_count()
s32 get_item_count (void)
Referenced by get_item_empty_count().
get_item_empty_count()
s32 get_item_empty_count (void)
get_player_data()
PlayerData * get_player_data (void)
Referenced by ClubbaNappingAI_Sleep(), pause_partners_draw_movelist(), pause_partners_draw_title(), pause_partners_handle_input(), pause_partners_init(), pause_spirits_draw_contents(), pause_spirits_draw_title(), pause_spirits_handle_input(), pause_spirits_init(), and pause_spirits_update().
get_stored_count()
s32 get_stored_count (void)
Referenced by get_stored_empty_count().
get_stored_empty_count()
s32 get_stored_empty_count (void)
has_full_fp()
s8 has_full_fp (void)
has_full_hp()
s8 has_full_hp (void)
hide_coin_counter()
void hide_coin_counter (void)
hide_coin_counter_immediately()
void hide_coin_counter_immediately (void)
increment_max_star_power()
void increment_max_star_power (void)
increment_status_bar_disabled()
void increment_status_bar_disabled (void)
Referenced by btl_state_update_first_strike(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), initialize_battle(), and update_item_entity_pickup().
initialize_status_bar()
void initialize_status_bar (void)
Referenced by load_demo_battle(), and load_map_by_IDs().
is_ability_active()
s32 is_ability_active (s32 ability)
Referenced by action_command_init_status(), action_hammer_play_hit_fx(), action_update_run(), action_update_spin(), action_update_walk(), adjust_action_command_difficulty(), appendGfx_player_actor(), btl_menu_strats_draw_content(), btl_state_update_begin_player_turn(), btl_state_update_begin_turn(), btl_state_update_celebration(), btl_state_update_end_player_turn(), btl_state_update_first_strike(), btl_state_update_normal_start(), btl_state_update_partner_menu(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_select_target(), calc_enemy_damage_target(), calc_player_damage_enemy(), check_block_input(), check_input_spin(), enforce_hpfp_limits(), entity_HiddenPanel_set_ispy_notification(), get_coin_drop_amount(), inflict_status(), is_actor_health_bar_visible(), is_actortype_health_bar_visible(), load_player_actor(), player_team_is_ability_active(), show_first_strike_message(), spawn_drops(), update_encounters_neutral(), update_encounters_pre_battle(), and update_locomotion_state().
is_partner_ability_active()
s32 is_partner_ability_active (s32 ability)
Referenced by player_team_is_ability_active().
is_status_bar_visible()
s32 is_status_bar_visible (void)
Referenced by check_input_status_bar().
open_status_bar_quickly()
void open_status_bar_quickly (void)
Referenced by create_standard_popup_menu(), and shop_open_item_select_popup().
open_status_bar_slowly()
void open_status_bar_slowly (void)
Referenced by action_update_hit_fire(), action_update_hit_lava(), and check_input_status_bar().
recover_fp()
s32 recover_fp (s32 amt)
Referenced by entity_HeartBlockContent__anim_heal().
recover_hp()
s32 recover_hp (s32 amt)
Referenced by entity_HeartBlockContent__anim_heal().
reset_status_bar()
void reset_status_bar (void)
Referenced by state_step_battle(), state_step_language_select(), and state_step_pause().
set_max_star_power()
void set_max_star_power (s8 newMax)
setup_status_bar_for_battle()
void setup_status_bar_for_battle (void)
Referenced by btl_state_update_normal_start().
setup_status_bar_for_world()
void setup_status_bar_for_world (void)
Referenced by update_encounters_post_battle().
show_coin_counter()
void show_coin_counter (void)
sort_items()
void sort_items (void)
Bubbles up player inventory items such that all ITEM_NONE values are at the bottom.
Referenced by add_item(), remove_consumable(), and update_item_entity_pickup().
status_bar_always_show_off()
void status_bar_always_show_off (void)
Referenced by draw_shop_items(), and shop_close_item_select_popup().
status_bar_always_show_on()
void status_bar_always_show_on (void)
Referenced by shop_open_item_select_popup().
status_bar_draw_number()
void status_bar_draw_number (s32 iconID, s32 startX, s32 startY, s32 value, s32 numDigits)
Referenced by update_status_bar().
status_bar_draw_stat()
void status_bar_draw_stat (s32 id, s32 startX, s32 startY, s32 currentValue, s32 maxValue)
Referenced by update_status_bar().
status_bar_ignore_changes()
void status_bar_ignore_changes (void)
Referenced by create_standard_popup_menu(), and shop_open_item_select_popup().
status_bar_is_ignoring_changes()
s32 status_bar_is_ignoring_changes (void)
Referenced by create_battle_popup_menu(), create_shop_popup_menu(), and create_standard_popup_menu().
status_bar_respond_to_changes()
void status_bar_respond_to_changes (void)
Referenced by destroy_popup_menu(), shop_close_item_select_popup(), state_step_exit_language_select(), and state_step_unpause().
status_bar_show_and_ignore_changes()
void status_bar_show_and_ignore_changes (void)
status_bar_start_blinking_coins()
void status_bar_start_blinking_coins (void)
Referenced by update_status_bar().
status_bar_start_blinking_fp()
void status_bar_start_blinking_fp (void)
Referenced by btl_menu_moves_draw_content(), and update_status_bar().
status_bar_start_blinking_hp()
void status_bar_start_blinking_hp (void)
Referenced by update_status_bar().
status_bar_start_blinking_sp()
void status_bar_start_blinking_sp (void)
status_bar_start_blinking_sp_bars()
void status_bar_start_blinking_sp_bars (s32 numBarsToBlink)
Referenced by btl_menu_moves_draw_content().
status_bar_start_blinking_starpoints()
void status_bar_start_blinking_starpoints (void)
Referenced by btl_state_update_run_away().
status_bar_stop_blinking_coins()
void status_bar_stop_blinking_coins (void)
Referenced by update_status_bar().
status_bar_stop_blinking_fp()
void status_bar_stop_blinking_fp (void)
Referenced by btl_menu_moves_draw_content(), btl_submenu_moves_update(), and update_status_bar().
status_bar_stop_blinking_hp()
void status_bar_stop_blinking_hp (void)
Referenced by update_status_bar().
status_bar_stop_blinking_sp()
void status_bar_stop_blinking_sp (void)
Referenced by btl_menu_moves_draw_content(), and btl_submenu_moves_update().
status_bar_stop_blinking_starpoints()
void status_bar_stop_blinking_starpoints (void)
Referenced by btl_state_update_run_away().
store_item()
s32 store_item (s32 itemID)
subtract_fortress_keys()
s32 subtract_fortress_keys (s32 amt)
subtract_hp()
void subtract_hp (s32 amt)
Referenced by action_update_hit_fire(), action_update_hit_lava(), and func_802BC274_E2EBA4().
sync_status_bar()
void sync_status_bar (void)
update_coin_counter()
void update_coin_counter (void)
Referenced by draw_status_ui().
update_status_bar()
void update_status_bar (void)
Referenced by draw_status_ui().
Variable Documentation
DigitHudScripts
HudScript* DigitHudScripts[10] extern
Referenced by status_bar_draw_number(), and status_bar_draw_stat().
gStatusBar
StatusBar gStatusBar
Referenced by add_star_power(), btl_state_update_normal_start(), can_control_status_bar(), close_status_bar(), coin_counter_draw_content(), decrement_status_bar_disabled(), disable_status_bar_input(), enable_status_bar_input(), hide_coin_counter(), hide_coin_counter_immediately(), increment_status_bar_disabled(), initialize_status_bar(), is_status_bar_visible(), open_status_bar_quickly(), open_status_bar_slowly(), reset_status_bar(), setup_status_bar_for_battle(), setup_status_bar_for_world(), show_coin_counter(), status_bar_always_show_off(), status_bar_always_show_on(), status_bar_ignore_changes(), status_bar_is_ignoring_changes(), status_bar_respond_to_changes(), status_bar_show_and_ignore_changes(), status_bar_start_blinking_coins(), status_bar_start_blinking_fp(), status_bar_start_blinking_hp(), status_bar_start_blinking_sp(), status_bar_start_blinking_sp_bars(), status_bar_start_blinking_starpoints(), status_bar_stop_blinking_coins(), status_bar_stop_blinking_fp(), status_bar_stop_blinking_hp(), status_bar_stop_blinking_sp(), status_bar_stop_blinking_starpoints(), sync_status_bar(), update_coin_counter(), and update_status_bar().
HES_Item_CoinSparkleRandom
HudScript HES_Item_CoinSparkleRandom extern
Referenced by initialize_status_bar().
HES_StatusFlower
HudScript HES_StatusFlower extern
Referenced by initialize_status_bar().
HES_StatusFP
HudScript HES_StatusFP extern
Referenced by initialize_status_bar().
HES_StatusFP_de
HudScript HES_StatusFP_de extern
Referenced by initialize_status_bar().
HES_StatusFP_es
HudScript HES_StatusFP_es extern
Referenced by initialize_status_bar().
HES_StatusFP_fr
HudScript HES_StatusFP_fr extern
Referenced by initialize_status_bar().
HES_StatusHeart
HudScript HES_StatusHeart extern
Referenced by initialize_status_bar().
HES_StatusHP
HudScript HES_StatusHP extern
Referenced by initialize_status_bar().
HES_StatusHP_de
HudScript HES_StatusHP_de extern
Referenced by initialize_status_bar().
HES_StatusHP_es
HudScript HES_StatusHP_es extern
Referenced by initialize_status_bar().
HES_StatusHP_fr
HudScript HES_StatusHP_fr extern
Referenced by initialize_status_bar().
HES_StatusSPEmptyIncrement
HudScript HES_StatusSPEmptyIncrement extern
Referenced by update_status_bar().
HES_StatusSPShine
HudScript HES_StatusSPShine extern
Referenced by initialize_status_bar().
HES_StatusStar1
HudScript HES_StatusStar1 extern
Referenced by initialize_status_bar().
HES_StatusStarEmpty
HudScript HES_StatusStarEmpty extern
Referenced by update_status_bar().
HES_StatusStarPoint
HudScript HES_StatusStarPoint extern
Referenced by initialize_status_bar().
HES_StatusTimes
HudScript HES_StatusTimes extern
Referenced by initialize_status_bar().
HidingCoinCounter
BSS b16 HidingCoinCounter
Referenced by clear_player_data(), initialize_status_bar(), show_coin_counter(), and update_coin_counter().
ShowingCoinCounter
BSS b16 ShowingCoinCounter
Referenced by clear_player_data(), hide_coin_counter(), hide_coin_counter_immediately(), initialize_status_bar(), show_coin_counter(), and update_coin_counter().
SlashHudScript
HudScript* SlashHudScript extern
Referenced by status_bar_draw_stat().
SPIncrementHudScripts
HudScript* SPIncrementHudScripts[] extern
Referenced by update_status_bar().
SPStarHudScripts
HudScript* SPStarHudScripts[] extern
Referenced by update_status_bar().
StatusBarSPIncrementOffsets
s32 StatusBarSPIncrementOffsets[] extern
Referenced by update_status_bar().
TimesHudScript
HudScript* TimesHudScript extern
Referenced by status_bar_draw_number().