papermario: src/is_debug.c File Reference
is_debug.c File Reference
Data Structures
struct ISVDbg
Macros
#define gISVDbgPrnAdrs ((ISVDbg*) 0xb3ff0000)
Functions
char * is_debug_print (char *arg0, const char *str, size_t count)
void is_debug_init (void)
void printf (const char *fmt,...)
void osSyncPrintf (const char *fmt,...)
void rmonPrintf (const char *fmt,...)
void is_debug_panic (const char *message, char *file, s32 line)
Data Structure Documentation
ISVDbg
struct ISVDbg
Data Fields
char data[0x10000-0x20]
u32 get
u32 magic
u32 put
char unk_08[0x14-0x08]
char unk_18[0x20-0x18]
Macro Definition Documentation
gISVDbgPrnAdrs
#define gISVDbgPrnAdrs ((ISVDbg*) 0xb3ff0000)
Referenced by is_debug_init(), and is_debug_print().
Function Documentation
is_debug_init()
void is_debug_init (void)
Referenced by boot_main().
is_debug_panic()
void is_debug_panic (const char * message, char * file, s32 line)
is_debug_print()
char * is_debug_print (char * arg0, const char * str, size_t count)
Referenced by osSyncPrintf(), printf(), and rmonPrintf().
osSyncPrintf()
void osSyncPrintf (const char * fmt, ...)
Referenced by is_debug_panic(), UnkModelFunc000(), and UnkModelFunc001().
printf()
void printf (const char * fmt, ...)
rmonPrintf()
void rmonPrintf (const char * fmt, ...)