papermario: src/item_entity.c File Reference
item_entity.c File Reference
Macros
#define MAX_ITEM_ENTITIES 256
#define WD_VAR1 54
#define WD_VAR2 30
#define WD_VAR3 30
#define X_VAR1 20
#define HT_VAR1 height
#define WD_VAR4 280
#define X_PICKUP_ITEM_1 15
#define X_PICKUP_ITEM_2 40
#define X_PICKUP_THREW 40
#define Y_PICKUP_ITEM_1 offsetY
#define Y_PICKUP_ITEM_2 offsetY
#define Y_PICKUP_THREW 4
Functions
void item_entity_update (ItemEntity *)
void appendGfx_item_entity (void *)
void draw_item_entities (void)
void draw_ui_item_entities (void)
s32 test_item_player_collision (ItemEntity *)
void update_item_entity_collectable (ItemEntity *)
void draw_ui_item_entity_collectable (ItemEntity *)
void update_item_entity_stationary (ItemEntity *)
void draw_ui_item_entity_stationary (ItemEntity *)
void update_item_entity_no_pickup (ItemEntity *)
void draw_ui_item_entity_no_pickup (ItemEntity *)
void func_801363A0 (ItemEntity *)
void update_item_entity_pickup (ItemEntity *)
void draw_content_pickup_item_header (ItemEntity *item, s32 posX, s32 posY)
void draw_content_cant_carry_more (ItemEntity *item, s32 posX, s32 posY)
void draw_content_pickup_item_desc (ItemEntity *item, s32 posX, s32 posY)
void sparkle_script_init (ItemEntity *item, SparkleScript *script)
s32 sparkle_script_step (ItemEntity *item)
void sparkle_script_update (ItemEntity *item)
void draw_coin_sparkles (ItemEntity *item)
ItemEntity * get_item_entity (s32 itemEntityIndex)
void hide_item_entity (ItemEntity *item)
void reveal_item_entity (ItemEntity *item)
void clear_item_entity_data (void)
void init_item_entity_list (void)
void item_entity_load (ItemEntity *item)
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 angle, s32 pickupFlagIndex)
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupVar)
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
s32 make_item_entity_at_player (s32 itemID, s32 category, s32 pickupMsgFlags)
void update_item_entities (void)
void render_item_entities (void)
void remove_item_entity_by_reference (ItemEntity *entity)
void remove_item_entity_by_index (s32 index)
void func_80133A94 (s32 idx, s32 itemID)
s32 test_item_entity_position (f32 x, f32 y, f32 z, f32 dist)
void set_item_entity_flags (s32 index, s32 flags)
void clear_item_entity_flags (s32 index, s32 flags)
void auto_collect_item_entity (s32 index)
b32 is_picking_up_item (void)
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
void set_current_item_entity_render_group (s32 group)
s32 get_current_item_entity_render_group (void)
Variables
SparkleScript SparkleScript_Coin
Gfx Gfx_RM1_ALPHATEST []
Gfx Gfx_RM2_ALPHATEST []
Lights1 ItemEntityLights = gdSPDefLights1(255, 255, 255, 0, 0, 0, 0, 0, 0)
HudCacheEntry * gHudElementCacheTableRaster
HudCacheEntry * gHudElementCacheTablePalette
u8 * gHudElementCacheBuffer
s32 * gHudElementCacheSize
s32 ItemEntitiesCreated
BSS s32 UnusedItemPhysicsScriptID
BSS s32 ItemEntityAlternatingSpawn
BSS s32 ItemEntityRenderGroup
BSS s16 CoinSparkleCenterX
BSS s16 CoinSparkleCenterY
BSS s16 CoinSparkleCenterZ
BSS s32 pad_ItemEntity [3]
BSS ItemEntity * WorldItemEntities [256]
BSS ItemEntity * BattleItemEntities [256]
BSS ItemEntity ** gCurrentItemEntities
BSS s16 isPickingUpItem
BSS s16 ItemSpawnWithinPlayerPickupDelay
BSS s16 D_801565A8
BSS s32 D_801565AC
BSS PopupMenu ItemPickupMenu
BSS s32 ItemPickupIconID
BSS s32 ItemPickupStateDelay
BSS s32 ThrowAwayMenuIdx
BSS s32 ThrowAwayItemID
BSS EffectInstance * ItemPickupGotOutline
BSS MessagePrintState * GotItemTutorialPrinter
BSS b32 GotItemTutorialClosed
Vtx D_8014C5A0 [4]
Vtx D_8014C5E0 [4]
Gfx D_8014C620 []
Gfx D_8014C678 []
Gfx D_8014C6A0 []
s16 PickupHeaderWindowHeight [] = { 32, 40 }
s16 PickupMessageWindowYOffsets [] = { 8, 4 }
s32 * gItemEntityScripts []
Macro Definition Documentation
HT_VAR1
#define HT_VAR1 height
Referenced by func_801363A0().
MAX_ITEM_ENTITIES
#define MAX_ITEM_ENTITIES 256
Referenced by clear_item_entity_data(), draw_item_entities(), draw_ui_item_entities(), item_entity_load(), make_item_entity(), make_item_entity_at_player(), remove_item_entity_by_reference(), render_item_entities(), test_item_entity_position(), and update_item_entities().
WD_VAR1
#define WD_VAR1 54
Referenced by func_801363A0().
WD_VAR2
#define WD_VAR2 30
Referenced by func_801363A0().
WD_VAR3
#define WD_VAR3 30
Referenced by func_801363A0().
WD_VAR4
#define WD_VAR4 280
Referenced by func_801363A0().
X_PICKUP_ITEM_1
#define X_PICKUP_ITEM_1 15
Referenced by draw_content_pickup_item_header().
X_PICKUP_ITEM_2
#define X_PICKUP_ITEM_2 40
Referenced by draw_content_pickup_item_header().
X_PICKUP_THREW
#define X_PICKUP_THREW 40
Referenced by draw_content_pickup_item_header().
X_VAR1
#define X_VAR1 20
Referenced by func_801363A0().
Y_PICKUP_ITEM_1
#define Y_PICKUP_ITEM_1 offsetY
Referenced by draw_content_pickup_item_header().
Y_PICKUP_ITEM_2
#define Y_PICKUP_ITEM_2 offsetY
Referenced by draw_content_pickup_item_header().
Y_PICKUP_THREW
#define Y_PICKUP_THREW 4
Referenced by draw_content_pickup_item_header().
Function Documentation
appendGfx_item_entity()
void appendGfx_item_entity (void * data)
Referenced by draw_item_entities().
auto_collect_item_entity()
void auto_collect_item_entity (s32 index)
clear_item_entity_data()
void clear_item_entity_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
clear_item_entity_flags()
void clear_item_entity_flags (s32 index, s32 flags)
draw_coin_sparkles()
void draw_coin_sparkles (ItemEntity * item)
Referenced by appendGfx_item_entity().
draw_content_cant_carry_more()
void draw_content_cant_carry_more (ItemEntity * item, s32 posX, s32 posY)
Referenced by func_801363A0().
draw_content_pickup_item_desc()
void draw_content_pickup_item_desc (ItemEntity * item, s32 posX, s32 posY)
Referenced by func_801363A0().
draw_content_pickup_item_header()
void draw_content_pickup_item_header (ItemEntity * item, s32 posX, s32 posY)
Referenced by func_801363A0().
draw_item_entities()
void draw_item_entities (void)
Referenced by clear_item_entity_data().
draw_ui_item_entities()
void draw_ui_item_entities (void)
Referenced by clear_item_entity_data().
draw_ui_item_entity_collectable()
void draw_ui_item_entity_collectable (ItemEntity * item)
Referenced by draw_ui_item_entities().
draw_ui_item_entity_no_pickup()
void draw_ui_item_entity_no_pickup (ItemEntity * item)
Referenced by draw_ui_item_entities().
draw_ui_item_entity_stationary()
void draw_ui_item_entity_stationary (ItemEntity * item)
Referenced by draw_ui_item_entities().
func_80133A94()
void func_80133A94 (s32 idx, s32 itemID)
func_801363A0()
void func_801363A0 (ItemEntity * item)
Referenced by update_item_entity_pickup().
get_current_item_entity_render_group()
s32 get_current_item_entity_render_group (void)
get_item_entity()
ItemEntity * get_item_entity (s32 itemEntityIndex)
Referenced by draw_shop_items(), entity_base_block_idle(), entity_HiddenPanel_flip_over(), entity_HiddenPanel_is_item_on_top(), and update_item_entity_pickup().
hide_item_entity()
void hide_item_entity (ItemEntity * item)
Referenced by make_item_entity(), and update_item_entity_pickup().
init_item_entity_list()
void init_item_entity_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
is_picking_up_item()
b32 is_picking_up_item (void)
Returns
TRUE when "you got X" popup is on-screen
Referenced by can_open_world_menu(), check_conversation_trigger(), check_input_open_menus(), check_input_status_bar(), entity_Tweester_idle(), func_802BB000_E2D930(), and update_encounters_neutral().
item_entity_load()
void item_entity_load (ItemEntity * item)
Referenced by func_80133A94(), make_item_entity(), and make_item_entity_at_player().
item_entity_update()
void item_entity_update (ItemEntity * entity)
Referenced by item_entity_load(), and update_item_entities().
make_item_entity()
s32 make_item_entity (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 angle, s32 pickupFlagIndex)
Referenced by entity_ItemBlock_spawn_item(), entity_TrumpetPlant_spawn_coin(), entity_WoodenCrate_shatter(), make_item_entity_delayed(), make_item_entity_nodelay(), and spawn_drops().
make_item_entity_at_player()
s32 make_item_entity_at_player (s32 itemID, s32 category, s32 pickupMsgFlags)
make_item_entity_delayed()
s32 make_item_entity_delayed (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupDelay, s32 pickupVar)
Referenced by update_item_entity_pickup().
make_item_entity_nodelay()
s32 make_item_entity_nodelay (s32 itemID, f32 x, f32 y, f32 z, s32 itemSpawnMode, s32 pickupVar)
Referenced by entity_GiantChest_give_equipment(), entity_HiddenPanel_flip_over(), entity_MulticoinBlock_spawn_coin(), entity_Munchlesia_init(), and musical_hill_orbit_listener().
remove_item_entity_by_index()
void remove_item_entity_by_index (s32 index)
Referenced by entity_GiantChest_await_got_item().
remove_item_entity_by_reference()
void remove_item_entity_by_reference (ItemEntity * entity)
Referenced by update_item_entity_collectable(), and update_item_entity_pickup().
render_item_entities()
void render_item_entities (void)
Referenced by render_frame().
reveal_item_entity()
void reveal_item_entity (ItemEntity * item)
Referenced by update_item_entity_collectable().
set_current_item_entity_render_group()
void set_current_item_entity_render_group (s32 group)
set_item_entity_flags()
void set_item_entity_flags (s32 index, s32 flags)
Referenced by check_for_item_collision().
set_item_entity_position()
void set_item_entity_position (s32 itemEntityIndex, f32 x, f32 y, f32 z)
Referenced by entity_GiantChest_open().
sparkle_script_init()
void sparkle_script_init (ItemEntity * item, SparkleScript * script)
Referenced by make_item_entity(), make_item_entity_at_player(), and update_item_entities().
sparkle_script_step()
s32 sparkle_script_step (ItemEntity * item)
Referenced by sparkle_script_update().
sparkle_script_update()
void sparkle_script_update (ItemEntity * item)
Referenced by make_item_entity(), make_item_entity_at_player(), and update_item_entities().
test_item_entity_position()
s32 test_item_entity_position (f32 x, f32 y, f32 z, f32 dist)
Referenced by check_for_item_collision().
test_item_player_collision()
b32 test_item_player_collision (ItemEntity * item)
Referenced by update_item_entity_collectable(), and update_item_entity_stationary().
update_item_entities()
void update_item_entities (void)
Referenced by state_step_battle(), and state_step_world().
update_item_entity_collectable()
void update_item_entity_collectable (ItemEntity * item)
Referenced by update_item_entities().
update_item_entity_no_pickup()
void update_item_entity_no_pickup (ItemEntity * item)
Referenced by update_item_entities().
update_item_entity_pickup()
void update_item_entity_pickup (ItemEntity * item)
Referenced by update_item_entities().
update_item_entity_stationary()
void update_item_entity_stationary (ItemEntity * item)
Referenced by update_item_entities().
Variable Documentation
BattleItemEntities
BSS ItemEntity* BattleItemEntities[256]
Referenced by clear_item_entity_data(), and init_item_entity_list().
CoinSparkleCenterX
BSS s16 CoinSparkleCenterX
Referenced by clear_item_entity_data(), draw_coin_sparkles(), and update_item_entities().
CoinSparkleCenterY
BSS s16 CoinSparkleCenterY
Referenced by clear_item_entity_data(), draw_coin_sparkles(), and update_item_entities().
CoinSparkleCenterZ
BSS s16 CoinSparkleCenterZ
Referenced by clear_item_entity_data(), draw_coin_sparkles(), and update_item_entities().
D_8014C5A0
Vtx D_8014C5A0[4]
Initial value:
= {
    {{{ -12,  0, 0 }, 0, { 0x2300, 0x2300 }, { 0, 0, 0, 255 }}},
    {{{  11,  0, 0 }, 0, { 0x2000, 0x2300 }, { 0, 0, 0, 255 }}},
    {{{  11, 23, 0 }, 0, { 0x2000, 0x2000 }, { 0, 0, 0, 255 }}},
    {{{ -12, 23, 0 }, 0, { 0x2300, 0x2000 }, { 0, 0, 0, 255 }}},
}
D_8014C5E0
Vtx D_8014C5E0[4]
Initial value:
= {
    {{{ -16,  0, 0 }, 0, { 0x2400, 0x2400 }, { 0, 0, 0, 255 }}},
    {{{  15,  0, 0 }, 0, { 0x2000, 0x2400 }, { 0, 0, 0, 255 }}},
    {{{  15, 31, 0 }, 0, { 0x2000, 0x2000 }, { 0, 0, 0, 255 }}},
    {{{ -16, 31, 0 }, 0, { 0x2400, 0x2000 }, { 0, 0, 0, 255 }}},
}
D_8014C620
Gfx D_8014C620[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsDPSetTexturePersp(G_TP_PERSP),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_item_entity(), and render_item_entities().
D_8014C678
Gfx D_8014C678[]
Initial value:
= {
    gsSPClearGeometryMode(G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPVertex(D_8014C5A0, 4, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsDPPipeSync(),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_item_entity(), and render_item_entities().
D_8014C6A0
Gfx D_8014C6A0[]
Initial value:
= {
    gsSPClearGeometryMode(G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPVertex(D_8014C5E0, 4, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsDPPipeSync(),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_item_entity(), and render_item_entities().
D_801565A8
BSS s16 D_801565A8
Referenced by clear_item_entity_data(), init_item_entity_list(), is_picking_up_item(), set_item_entity_flags(), update_item_entity_collectable(), and update_item_entity_stationary().
D_801565AC
BSS s32 D_801565AC
gCurrentItemEntities
BSS ItemEntity** gCurrentItemEntities
Referenced by auto_collect_item_entity(), clear_item_entity_data(), clear_item_entity_flags(), draw_item_entities(), draw_ui_item_entities(), func_80133A94(), get_item_entity(), init_item_entity_list(), make_item_entity(), make_item_entity_at_player(), remove_item_entity_by_index(), remove_item_entity_by_reference(), render_item_entities(), set_item_entity_flags(), set_item_entity_position(), test_item_entity_position(), and update_item_entities().
Gfx_RM1_ALPHATEST
Gfx Gfx_RM1_ALPHATEST[] extern
Referenced by appendGfx_item_entity(), and render_item_entities().
Gfx_RM2_ALPHATEST
Gfx Gfx_RM2_ALPHATEST extern
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_item_entity(), and render_item_entities().
gHudElementCacheBuffer
u8* gHudElementCacheBuffer extern
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_load_script(), init_hud_element_list(), and item_entity_load().
gHudElementCacheSize
s32* gHudElementCacheSize extern
Referenced by ALT_clear_hud_element_cache(), hud_element_clear_cache(), hud_element_load_script(), init_hud_element_list(), and item_entity_load().
gHudElementCacheTablePalette
HudCacheEntry* gHudElementCacheTablePalette extern
Referenced by ALT_clear_hud_element_cache(), appendGfx_item_entity(), hud_element_clear_cache(), hud_element_load_script(), init_hud_element_list(), item_entity_load(), and render_item_entities().
gHudElementCacheTableRaster
HudCacheEntry* gHudElementCacheTableRaster extern
Referenced by ALT_clear_hud_element_cache(), appendGfx_item_entity(), hud_element_clear_cache(), hud_element_load_script(), init_hud_element_list(), item_entity_load(), and render_item_entities().
gItemEntityScripts
s32* gItemEntityScripts[] extern
Referenced by item_entity_load().
GotItemTutorialClosed
BSS b32 GotItemTutorialClosed
Referenced by update_item_entity_pickup().
GotItemTutorialPrinter
BSS MessagePrintState* GotItemTutorialPrinter
Referenced by update_item_entity_pickup().
isPickingUpItem
BSS s16 isPickingUpItem
Referenced by clear_item_entity_data(), init_item_entity_list(), is_picking_up_item(), remove_item_entity_by_index(), remove_item_entity_by_reference(), test_item_entity_position(), test_item_player_collision(), update_item_entity_collectable(), update_item_entity_pickup(), and update_item_entity_stationary().
ItemEntitiesCreated
s32 ItemEntitiesCreated
Referenced by clear_item_entity_data(), init_item_entity_list(), make_item_entity(), and make_item_entity_at_player().
ItemEntityAlternatingSpawn
BSS s32 ItemEntityAlternatingSpawn
Referenced by clear_item_entity_data(), init_item_entity_list(), make_item_entity(), and make_item_entity_at_player().
ItemEntityLights
Lights1 ItemEntityLights = gdSPDefLights1(255, 255, 255, 0, 0, 0, 0, 0, 0)
Referenced by draw_coin_sparkles().
ItemEntityRenderGroup
BSS s32 ItemEntityRenderGroup
Referenced by clear_item_entity_data(), draw_item_entities(), get_current_item_entity_render_group(), and set_current_item_entity_render_group().
ItemPickupGotOutline
BSS EffectInstance* ItemPickupGotOutline
Referenced by update_item_entity_pickup().
ItemPickupIconID
BSS s32 ItemPickupIconID
Referenced by draw_content_pickup_item_header(), and update_item_entity_pickup().
ItemPickupMenu
BSS PopupMenu ItemPickupMenu
Referenced by update_item_entity_pickup().
ItemPickupStateDelay
BSS s32 ItemPickupStateDelay
Referenced by update_item_entity_pickup().
ItemSpawnWithinPlayerPickupDelay
BSS s16 ItemSpawnWithinPlayerPickupDelay
Referenced by make_item_entity(), and test_item_player_collision().
pad_ItemEntity
BSS s32 pad_ItemEntity[3]
PickupHeaderWindowHeight
s16 PickupHeaderWindowHeight[] = { 32, 40 }
Referenced by func_801363A0().
PickupMessageWindowYOffsets
s16 PickupMessageWindowYOffsets[] = { 8, 4 }
Referenced by draw_content_pickup_item_header().
SparkleScript_Coin
SparkleScript SparkleScript_Coin extern
Referenced by make_item_entity(), make_item_entity_at_player(), and update_item_entities().
ThrowAwayItemID
BSS s32 ThrowAwayItemID
Referenced by draw_content_pickup_item_header(), func_801363A0(), and update_item_entity_pickup().
ThrowAwayMenuIdx
BSS s32 ThrowAwayMenuIdx
Referenced by update_item_entity_pickup().
UnusedItemPhysicsScriptID
BSS s32 UnusedItemPhysicsScriptID
Referenced by update_item_entity_collectable().
WorldItemEntities
BSS ItemEntity* WorldItemEntities[256]
Referenced by clear_item_entity_data(), and init_item_entity_list().