papermario: src/entity/ItemBlock.c File Reference
ItemBlock.c File Reference
Functions
f32 player_get_camera_facing_angle (void)
void entity_inactive_block_hit_init (Entity *)
void entity_inactive_block_hit_anim (Entity *)
void entity_inactive_block_recoil_anim (Entity *)
void entity_ItemBlock_idle (Entity *entity)
void entity_HiddenItemBlock_idle (Entity *entity)
void entity_HitItemBlock_appear (Entity *entity)
void entity_ItemBlock_spawn_item (Entity *entity)
void entity_TriggerBlock_start_bound_script_2 (Entity *entity)
void entity_TriggerBlock_play_vanish_effect (Entity *entity)
void entity_HitItemBlock_play_anim (Entity *entity)
void entity_HitItemBlock_show_inactive (Entity *entity)
void entity_ItemBlock_check_if_inactive (Entity *entity)
void entity_ItemBlock_replace_with_inactive (Entity *entity)
void entity_HitItemBlock_hide (Entity *entity)
s32 entity_TriggerBlock_start_bound_script (Entity *entity)
void entity_TriggerBlock_disable_player_input (void)
void entity_TriggerBlock_enable_player_input (void)
void entity_ItemBlock_setupGfx (s32 entityIndex)
void entity_ItemBlock_init (Entity *entity)
void entity_HiddenItemBlock_init (Entity *entity)
void entity_ItemlessBlock_init (Entity *entity)
Variables
Gfx Entity_YellowBlock_Render []
Gfx Entity_RedBlock_Render []
AnimScript Entity_HitYellowBlock_AnimationHit
AnimScript Entity_HitYellowBlock_AnimationIdle
StaticAnimatorNode * Entity_HitYellowBlock_Mesh []
AnimScript Entity_HitFloatingYellowBlock_AnimationIdle
StaticAnimatorNode * Entity_HitFloatingYellowBlock_Mesh []
AnimScript Entity_HitRedBlock_AnimationHit
StaticAnimatorNode * Entity_HitRedBlock_Mesh []
s32 D_802EA310 []
EntityBlueprint Entity_HitGroundedYellowBlock
EntityBlueprint Entity_HitFloatingYellowBlock
EntityBlueprint Entity_HitRedBlock
BSS EffectInstance * TriggerBlockVanishEffect
EntityScript Entity_ItemBlock_Script
EntityScript Entity_HiddenItemBlock_Script
EntityScript Entity_HitBlock_Script
EntityScript Entity_TriggerBlock_Script
DmaEntry Entity_HitYellowBlock_dma [] = { ENTITY_ROM(HitYellowBlock_gfx), ENTITY_ROM(HitYellowBlock_anim) }
DmaEntry Entity_HitFloatinYellowBlock_dma [] = { ENTITY_ROM(HitFloatingYellowBlock_gfx), ENTITY_ROM(HitFloatingYellowBlock_anim) }
DmaEntry Entity_HitRedBlock_dma [] = { ENTITY_ROM(HitRedBlock_gfx), ENTITY_ROM(HitRedBlock_anim) }
EntityModelScript Entity_YellowBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_YellowBlock_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_HiddenYellowBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_YellowBlock_Render, RENDER_MODE_SURFACE_XLU_LAYER2)
EntityModelScript Entity_RedBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RedBlock_Render, RENDER_MODE_SURFACE_OPA)
EntityModelScript Entity_HiddenRedBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RedBlock_Render, RENDER_MODE_SURFACE_XLU_LAYER2)
EntityBlueprint Entity_YellowBlock
EntityBlueprint Entity_HiddenYellowBlock
EntityBlueprint Entity_RedBlock
EntityBlueprint Entity_HiddenRedBlock
EntityBlueprint Entity_TriggerBlock
Function Documentation
entity_HiddenItemBlock_idle()
void entity_HiddenItemBlock_idle (Entity * entity)
entity_HiddenItemBlock_init()
void entity_HiddenItemBlock_init (Entity * entity)
entity_HitItemBlock_appear()
void entity_HitItemBlock_appear (Entity * entity)
entity_HitItemBlock_hide()
void entity_HitItemBlock_hide (Entity * entity)
entity_HitItemBlock_play_anim()
void entity_HitItemBlock_play_anim (Entity * entity)
entity_HitItemBlock_show_inactive()
void entity_HitItemBlock_show_inactive (Entity * entity)
entity_inactive_block_hit_anim()
void entity_inactive_block_hit_anim (Entity * entity)
entity_inactive_block_hit_init()
void entity_inactive_block_hit_init (Entity * entity)
entity_inactive_block_recoil_anim()
void entity_inactive_block_recoil_anim (Entity * entity)
entity_ItemBlock_check_if_inactive()
void entity_ItemBlock_check_if_inactive (Entity * entity)
entity_ItemBlock_idle()
void entity_ItemBlock_idle (Entity * entity)
entity_ItemBlock_init()
void entity_ItemBlock_init (Entity * entity)
Referenced by entity_HiddenItemBlock_init().
entity_ItemBlock_replace_with_inactive()
void entity_ItemBlock_replace_with_inactive (Entity * entity)
entity_ItemBlock_setupGfx()
void entity_ItemBlock_setupGfx (s32 entityIndex)
Referenced by entity_ItemBlock_init(), and entity_ItemlessBlock_init().
entity_ItemBlock_spawn_item()
void entity_ItemBlock_spawn_item (Entity * entity)
entity_ItemlessBlock_init()
void entity_ItemlessBlock_init (Entity * entity)
entity_TriggerBlock_disable_player_input()
void entity_TriggerBlock_disable_player_input (void)
entity_TriggerBlock_enable_player_input()
void entity_TriggerBlock_enable_player_input (void)
entity_TriggerBlock_play_vanish_effect()
void entity_TriggerBlock_play_vanish_effect (Entity * entity)
entity_TriggerBlock_start_bound_script()
s32 entity_TriggerBlock_start_bound_script (Entity * entity)
entity_TriggerBlock_start_bound_script_2()
void entity_TriggerBlock_start_bound_script_2 (Entity * entity)
player_get_camera_facing_angle()
f32 player_get_camera_facing_angle (void)
Referenced by entity_ItemBlock_spawn_item().
Variable Documentation
D_802EA310
EntityScript D_802EA310
Initial value:
= {
    es_SetCallback(NULL, 2)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Referenced by entity_ItemBlock_check_if_inactive().
Entity_HiddenItemBlock_Script
EntityScript Entity_HiddenItemBlock_Script
Initial value:
= {
    es_Call(entity_ItemBlock_check_if_inactive)
    es_SetCallback(NULL, 0)
    es_SetCallback(entity_HiddenItemBlock_idle, 0)
    es_PlaySound(SOUND_HIT_BLOCK)
    es_Call(entity_ItemBlock_spawn_item)
    es_Call(entity_ItemBlock_replace_with_inactive)
    es_SetCallback(NULL, 1)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 2)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_HiddenRedBlock
EntityBlueprint Entity_HiddenRedBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_HiddenRedBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_HiddenItemBlock_init,
    .updateEntityScript = Entity_HiddenItemBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(RedBlock) },
    .entityType = ENTITY_TYPE_HIDDEN_RED_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Entity_HiddenRedBlock_RenderScript
EntityModelScript Entity_HiddenRedBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RedBlock_Render, RENDER_MODE_SURFACE_XLU_LAYER2)
Entity_HiddenYellowBlock
EntityBlueprint Entity_HiddenYellowBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_HiddenYellowBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_HiddenItemBlock_init,
    .updateEntityScript = Entity_HiddenItemBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(YellowBlock) },
    .entityType = ENTITY_TYPE_HIDDEN_YELLOW_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Entity_HiddenYellowBlock_RenderScript
EntityModelScript Entity_HiddenYellowBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_YellowBlock_Render, RENDER_MODE_SURFACE_XLU_LAYER2)
Entity_HitBlock_Script
EntityScript Entity_HitBlock_Script
Initial value:
= {
    es_SetCallback(NULL, 1)
    es_Call(entity_HitItemBlock_play_anim)
    es_SetCallback(entity_HitItemBlock_appear, 10)
    es_Call(entity_HitItemBlock_hide)
    es_Call(entity_HitItemBlock_show_inactive)
    es_SetCallback(NULL, 1)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetFlags(ENTITY_FLAG_PENDING_FULL_DELETE)
    es_End
}
Entity_HitFloatingYellowBlock
EntityBlueprint Entity_HitFloatingYellowBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_HitFloatingYellowBlock_AnimationIdle,
    .modelAnimationNodes = Entity_HitFloatingYellowBlock_Mesh,
    .fpInit = entity_ItemlessBlock_init,
    .updateEntityScript = Entity_HitBlock_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_HitFloatinYellowBlock_dma },
    .entityType = ENTITY_TYPE_YELLOW_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Referenced by entity_ItemBlock_replace_with_inactive().
Entity_HitFloatingYellowBlock_AnimationIdle
AnimScript Entity_HitFloatingYellowBlock_AnimationIdle extern
Entity_HitFloatingYellowBlock_Mesh
StaticAnimatorNode* Entity_HitFloatingYellowBlock_Mesh[] extern
Entity_HitFloatinYellowBlock_dma
DmaEntry Entity_HitFloatinYellowBlock_dma[] = { ENTITY_ROM(HitFloatingYellowBlock_gfx), ENTITY_ROM(HitFloatingYellowBlock_anim) }
Entity_HitGroundedYellowBlock
EntityBlueprint Entity_HitGroundedYellowBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_HitYellowBlock_AnimationIdle,
    .modelAnimationNodes = Entity_HitYellowBlock_Mesh,
    .fpInit = entity_ItemlessBlock_init,
    .updateEntityScript = Entity_HitBlock_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_HitYellowBlock_dma },
    .entityType = ENTITY_TYPE_YELLOW_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Referenced by entity_ItemBlock_replace_with_inactive().
Entity_HitRedBlock
EntityBlueprint Entity_HitRedBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_HitRedBlock_AnimationHit,
    .modelAnimationNodes = Entity_HitRedBlock_Mesh,
    .fpInit = entity_ItemlessBlock_init,
    .updateEntityScript = Entity_HitBlock_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_HitRedBlock_dma },
    .entityType = ENTITY_TYPE_RED_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Referenced by entity_ItemBlock_replace_with_inactive().
Entity_HitRedBlock_AnimationHit
AnimScript Entity_HitRedBlock_AnimationHit extern
Referenced by entity_HitItemBlock_play_anim().
Entity_HitRedBlock_dma
DmaEntry Entity_HitRedBlock_dma[] = { ENTITY_ROM(HitRedBlock_gfx), ENTITY_ROM(HitRedBlock_anim) }
Entity_HitRedBlock_Mesh
StaticAnimatorNode* Entity_HitRedBlock_Mesh[] extern
Entity_HitYellowBlock_AnimationHit
AnimScript Entity_HitYellowBlock_AnimationHit extern
Referenced by entity_HitItemBlock_play_anim().
Entity_HitYellowBlock_AnimationIdle
AnimScript Entity_HitYellowBlock_AnimationIdle extern
Entity_HitYellowBlock_dma
DmaEntry Entity_HitYellowBlock_dma[] = { ENTITY_ROM(HitYellowBlock_gfx), ENTITY_ROM(HitYellowBlock_anim) }
Entity_HitYellowBlock_Mesh
StaticAnimatorNode* Entity_HitYellowBlock_Mesh[] extern
Entity_ItemBlock_Script
EntityScript Entity_ItemBlock_Script
Initial value:
= {
    es_Call(entity_ItemBlock_check_if_inactive)
    es_SetCallback(NULL, 0)
    es_SetCallback(entity_ItemBlock_idle, 0)
    es_PlaySound(SOUND_HIT_BLOCK)
    es_Call(entity_ItemBlock_spawn_item)
    es_Call(entity_ItemBlock_replace_with_inactive)
    es_SetCallback(NULL, 1)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 2)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_RedBlock
EntityBlueprint Entity_RedBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_RedBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_ItemBlock_init,
    .updateEntityScript = Entity_ItemBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(RedBlock) },
    .entityType = ENTITY_TYPE_RED_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Entity_RedBlock_Render
Gfx Entity_RedBlock_Render[] extern
Entity_RedBlock_RenderScript
EntityModelScript Entity_RedBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RedBlock_Render, RENDER_MODE_SURFACE_OPA)
Entity_TriggerBlock
EntityBlueprint Entity_TriggerBlock
Initial value:
= {
    .flags = ENTITY_FLAG_8000 | ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_HitYellowBlock_AnimationIdle,
    .modelAnimationNodes = Entity_HitYellowBlock_Mesh,
    .fpInit = entity_ItemlessBlock_init,
    .updateEntityScript = Entity_TriggerBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dmaList = Entity_HitYellowBlock_dma },
    .entityType = ENTITY_TYPE_SINGLE_TRIGGER_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Entity_TriggerBlock_Script
EntityScript Entity_TriggerBlock_Script
Initial value:
= {
    es_SetCallback(entity_ItemBlock_idle, 0)
    es_Call(entity_TriggerBlock_disable_player_input)
    es_PlaySound(SOUND_HIT_BLOCK)
    es_Call(entity_TriggerBlock_play_vanish_effect)
    es_Call(entity_inactive_block_hit_init)
    es_SetCallback(entity_inactive_block_hit_anim, 0)
    es_SetCallback(entity_inactive_block_recoil_anim, 0)
    es_Call(entity_TriggerBlock_start_bound_script)
    es_Call(entity_TriggerBlock_enable_player_input)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetFlags(ENTITY_FLAG_DISABLE_COLLISION)
    es_Call(entity_TriggerBlock_start_bound_script_2)
    es_SetCallback(NULL, 2)
    es_SetFlags(ENTITY_FLAG_PENDING_FULL_DELETE)
    es_End
}
Entity_YellowBlock
EntityBlueprint Entity_YellowBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_YellowBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_ItemBlock_init,
    .updateEntityScript = Entity_ItemBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(YellowBlock) },
    .entityType = ENTITY_TYPE_YELLOW_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Entity_YellowBlock_Render
Gfx Entity_YellowBlock_Render[] extern
Entity_YellowBlock_RenderScript
EntityModelScript Entity_YellowBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_YellowBlock_Render, RENDER_MODE_SURFACE_OPA)
TriggerBlockVanishEffect
BSS EffectInstance* TriggerBlockVanishEffect
Referenced by entity_TriggerBlock_play_vanish_effect().