papermario: src/effects/landing_dust.c File Reference
landing_dust.c File Reference
Functions
void landing_dust_init (EffectInstance *effect)
void landing_dust_update (EffectInstance *effect)
void landing_dust_render (EffectInstance *effect)
void landing_dust_appendGfx (void *effect)
void func_E000C000 (LandingDustFXData *part)
void func_E000C094 (LandingDustFXData *part)
void func_E000C0C8 (LandingDustFXData *part)
void landing_dust_main (s32 type, f32 x, f32 y, f32 z, f32 arg4)
Variables
Gfx D_09002780_32B620 []
Gfx D_09002868_32B708 []
Gfx D_09002950_32B7F0 []
Gfx D_09002A38_32B8D8 []
Gfx D_09002B20_32B9C0 []
Gfx D_09002B40_32B9E0 []
Gfx D_09002B60_32BA00 []
Function Documentation
func_E000C000()
void func_E000C000 (LandingDustFXData * part)
Referenced by landing_dust_update().
func_E000C094()
void func_E000C094 (LandingDustFXData * part)
Referenced by landing_dust_update().
func_E000C0C8()
void func_E000C0C8 (LandingDustFXData * part)
Referenced by landing_dust_update().
landing_dust_appendGfx()
void landing_dust_appendGfx (void * effect)
Referenced by landing_dust_render().
landing_dust_init()
void landing_dust_init (EffectInstance * effect)
Referenced by landing_dust_main().
landing_dust_main()
void landing_dust_main (s32 type, f32 x, f32 y, f32 z, f32 arg4)
Referenced by star_update().
landing_dust_render()
void landing_dust_render (EffectInstance * effect)
Referenced by landing_dust_main().
landing_dust_update()
void landing_dust_update (EffectInstance * effect)
Referenced by landing_dust_main().
Variable Documentation
D_09002780_32B620
Gfx D_09002780_32B620[] extern
D_09002868_32B708
Gfx D_09002868_32B708[] extern
D_09002950_32B7F0
Gfx D_09002950_32B7F0[] extern
D_09002A38_32B8D8
Gfx D_09002A38_32B8D8[] extern
D_09002B20_32B9C0
Gfx D_09002B20_32B9C0[] extern
D_09002B40_32B9E0
Gfx D_09002B40_32B9E0[] extern
D_09002B60_32BA00
Gfx D_09002B60_32BA00[] extern