papermario: src/effects/lens_flare.c File Reference
lens_flare.c File Reference
Functions
void lens_flare_init (EffectInstance *effect)
void lens_flare_update (EffectInstance *effect)
void lens_flare_render (EffectInstance *effect)
void lens_flare_appendGfx (void *effect)
void lens_flare_main (s32 type, f32 posX, f32 posY, f32 posZ, s32 duration)
Variables
Gfx D_09000240_345420 []
Gfx D_090002E0_3454C0 []
Gfx * D_E0034780 [] = { D_090002E0_3454C0, D_090002E0_3454C0 }
Gfx * D_E0034788 [] = { D_09000240_345420, D_09000240_345420 }
u8 D_E0034790 []
Function Documentation
lens_flare_appendGfx()
void lens_flare_appendGfx (void * effect)
Referenced by lens_flare_render().
lens_flare_init()
void lens_flare_init (EffectInstance * effect)
Referenced by lens_flare_main().
lens_flare_main()
void lens_flare_main (s32 type, f32 posX, f32 posY, f32 posZ, s32 duration)
lens_flare_render()
void lens_flare_render (EffectInstance * effect)
Referenced by lens_flare_main().
lens_flare_update()
void lens_flare_update (EffectInstance * effect)
Referenced by lens_flare_main().
Variable Documentation
D_09000240_345420
Gfx D_09000240_345420[] extern
D_090002E0_3454C0
Gfx D_090002E0_3454C0[] extern
D_E0034780
Gfx* D_E0034780[] = { D_090002E0_3454C0, D_090002E0_3454C0 }
Referenced by lens_flare_appendGfx().
D_E0034788
Gfx* D_E0034788[] = { D_09000240_345420, D_09000240_345420 }
Referenced by lens_flare_appendGfx().
D_E0034790
u8 D_E0034790[]
Initial value:
= {
    255, 255,  82,
    255, 255,  82,
    181, 148,   0,
    181, 148,   0,
    255, 255, 214,
    255, 255, 214,
    181, 148,   0,
    181, 148,   0
}
Referenced by lens_flare_appendGfx().