papermario: src/level_up.c File Reference
level_up.c File Reference
Macros
#define level_up_digit_0_red_png level_up_digit_0_png
#define level_up_digit_1_red_png level_up_digit_1_png
#define level_up_digit_2_red_png level_up_digit_2_png
#define level_up_digit_3_red_png level_up_digit_3_png
#define level_up_digit_4_red_png level_up_digit_4_png
#define level_up_digit_5_red_png level_up_digit_5_png
#define level_up_digit_6_red_png level_up_digit_6_png
#define level_up_digit_7_red_png level_up_digit_7_png
#define level_up_digit_8_red_png level_up_digit_8_png
#define level_up_digit_9_red_png level_up_digit_9_png
#define level_up_small_digit_0_red_png level_up_small_digit_0_png
#define level_up_small_digit_1_red_png level_up_small_digit_1_png
#define level_up_small_digit_2_red_png level_up_small_digit_2_png
#define level_up_small_digit_3_red_png level_up_small_digit_3_png
#define level_up_small_digit_4_red_png level_up_small_digit_4_png
#define level_up_small_digit_5_red_png level_up_small_digit_5_png
#define level_up_small_digit_6_red_png level_up_small_digit_6_png
#define level_up_small_digit_7_red_png level_up_small_digit_7_png
#define level_up_small_digit_8_red_png level_up_small_digit_8_png
#define level_up_small_digit_9_red_png level_up_small_digit_9_png
#define level_up_small_arrow_red_png level_up_small_arrow_png
#define level_up_digit_0_blue_png level_up_digit_0_png
#define level_up_digit_1_blue_png level_up_digit_1_png
#define level_up_digit_2_blue_png level_up_digit_2_png
#define level_up_digit_3_blue_png level_up_digit_3_png
#define level_up_digit_4_blue_png level_up_digit_4_png
#define level_up_digit_5_blue_png level_up_digit_5_png
#define level_up_digit_6_blue_png level_up_digit_6_png
#define level_up_digit_7_blue_png level_up_digit_7_png
#define level_up_digit_8_blue_png level_up_digit_8_png
#define level_up_digit_9_blue_png level_up_digit_9_png
#define level_up_small_digit_0_blue_png level_up_small_digit_0_png
#define level_up_small_digit_1_blue_png level_up_small_digit_1_png
#define level_up_small_digit_2_blue_png level_up_small_digit_2_png
#define level_up_small_digit_3_blue_png level_up_small_digit_3_png
#define level_up_small_digit_4_blue_png level_up_small_digit_4_png
#define level_up_small_digit_5_blue_png level_up_small_digit_5_png
#define level_up_small_digit_6_blue_png level_up_small_digit_6_png
#define level_up_small_digit_7_blue_png level_up_small_digit_7_png
#define level_up_small_digit_8_blue_png level_up_small_digit_8_png
#define level_up_small_digit_9_blue_png level_up_small_digit_9_png
#define level_up_small_arrow_blue_png level_up_small_arrow_png
Functions
INCLUDE_IMG ("level_up/big_V.png", D_802A1418_79F358)
INCLUDE_IMG ("level_up/big_P.png", D_802A2490_7A03D0)
INCLUDE_IMG ("level_up/big_exclamation_mark.png", D_802A3508_7A1448)
INCLUDE_IMG ("level_up/big_U.png", D_802A4580_7A24C0)
INCLUDE_IMG ("level_up/big_L.png", D_802A55F8_7A3538)
INCLUDE_IMG ("level_up/big_E.png", D_802A6670_7A45B0)
INCLUDE_IMG ("level_up/heart.png", level_up_heart_png)
INCLUDE_PAL ("level_up/heart.pal", level_up_heart_pal)
INCLUDE_IMG ("level_up/flower.png", level_up_flower_png)
INCLUDE_PAL ("level_up/flower.pal", level_up_flower_pal)
INCLUDE_IMG ("level_up/leaves.png", level_up_leaves_png)
INCLUDE_PAL ("level_up/leaves.pal", level_up_leaves_pal)
INCLUDE_IMG ("level_up/badge.png", level_up_badge_png)
INCLUDE_PAL ("level_up/badge.pal", level_up_badge_pal)
INCLUDE_IMG ("level_up/FP.png", level_up_FP_png)
INCLUDE_PAL ("level_up/FP.pal", level_up_FP_pal)
INCLUDE_IMG ("level_up/BP.png", level_up_BP_png)
INCLUDE_PAL ("level_up/BP.pal", level_up_BP_pal)
INCLUDE_IMG ("level_up/HP.png", level_up_HP_png)
INCLUDE_PAL ("level_up/HP.pal", level_up_HP_pal)
INCLUDE_IMG ("level_up/digit_0.png", level_up_digit_0_png)
INCLUDE_PAL ("level_up/digit_0.pal", level_up_digit_0_pal)
INCLUDE_IMG ("level_up/digit_1.png", level_up_digit_1_png)
INCLUDE_PAL ("level_up/digit_1.pal", level_up_digit_1_pal)
INCLUDE_IMG ("level_up/digit_2.png", level_up_digit_2_png)
INCLUDE_PAL ("level_up/digit_2.pal", level_up_digit_2_pal)
INCLUDE_IMG ("level_up/digit_3.png", level_up_digit_3_png)
INCLUDE_PAL ("level_up/digit_3.pal", level_up_digit_3_pal)
INCLUDE_IMG ("level_up/digit_4.png", level_up_digit_4_png)
INCLUDE_PAL ("level_up/digit_4.pal", level_up_digit_4_pal)
INCLUDE_IMG ("level_up/digit_5.png", level_up_digit_5_png)
INCLUDE_PAL ("level_up/digit_5.pal", level_up_digit_5_pal)
INCLUDE_IMG ("level_up/digit_6.png", level_up_digit_6_png)
INCLUDE_PAL ("level_up/digit_6.pal", level_up_digit_6_pal)
INCLUDE_IMG ("level_up/digit_7.png", level_up_digit_7_png)
INCLUDE_PAL ("level_up/digit_7.pal", level_up_digit_7_pal)
INCLUDE_IMG ("level_up/digit_8.png", level_up_digit_8_png)
INCLUDE_PAL ("level_up/digit_8.pal", level_up_digit_8_pal)
INCLUDE_IMG ("level_up/digit_9.png", level_up_digit_9_png)
INCLUDE_PAL ("level_up/digit_9.pal", level_up_digit_9_pal)
INCLUDE_IMG ("level_up/small_digit_0.png", level_up_small_digit_0_png)
INCLUDE_PAL ("level_up/small_digit_0.pal", level_up_small_digit_0_pal)
INCLUDE_IMG ("level_up/small_digit_1.png", level_up_small_digit_1_png)
INCLUDE_PAL ("level_up/small_digit_1.pal", level_up_small_digit_1_pal)
INCLUDE_IMG ("level_up/small_digit_2.png", level_up_small_digit_2_png)
INCLUDE_PAL ("level_up/small_digit_2.pal", level_up_small_digit_2_pal)
INCLUDE_IMG ("level_up/small_digit_3.png", level_up_small_digit_3_png)
INCLUDE_PAL ("level_up/small_digit_3.pal", level_up_small_digit_3_pal)
INCLUDE_IMG ("level_up/small_digit_4.png", level_up_small_digit_4_png)
INCLUDE_PAL ("level_up/small_digit_4.pal", level_up_small_digit_4_pal)
INCLUDE_IMG ("level_up/small_digit_5.png", level_up_small_digit_5_png)
INCLUDE_PAL ("level_up/small_digit_5.pal", level_up_small_digit_5_pal)
INCLUDE_IMG ("level_up/small_digit_6.png", level_up_small_digit_6_png)
INCLUDE_PAL ("level_up/small_digit_6.pal", level_up_small_digit_6_pal)
INCLUDE_IMG ("level_up/small_digit_7.png", level_up_small_digit_7_png)
INCLUDE_PAL ("level_up/small_digit_7.pal", level_up_small_digit_7_pal)
INCLUDE_IMG ("level_up/small_digit_8.png", level_up_small_digit_8_png)
INCLUDE_PAL ("level_up/small_digit_8.pal", level_up_small_digit_8_pal)
INCLUDE_IMG ("level_up/small_digit_9.png", level_up_small_digit_9_png)
INCLUDE_PAL ("level_up/small_digit_9.pal", level_up_small_digit_9_pal)
INCLUDE_IMG ("level_up/small_arrow.png", level_up_small_arrow_png)
INCLUDE_PAL ("level_up/small_arrow.pal", level_up_small_arrow_pal)
INCLUDE_PAL ("level_up/digit_0.red.pal", level_up_digit_0_red_pal)
INCLUDE_PAL ("level_up/digit_1.red.pal", level_up_digit_1_red_pal)
INCLUDE_PAL ("level_up/digit_2.red.pal", level_up_digit_2_red_pal)
INCLUDE_PAL ("level_up/digit_3.red.pal", level_up_digit_3_red_pal)
INCLUDE_PAL ("level_up/digit_4.red.pal", level_up_digit_4_red_pal)
INCLUDE_PAL ("level_up/digit_5.red.pal", level_up_digit_5_red_pal)
INCLUDE_PAL ("level_up/digit_6.red.pal", level_up_digit_6_red_pal)
INCLUDE_PAL ("level_up/digit_7.red.pal", level_up_digit_7_red_pal)
INCLUDE_PAL ("level_up/digit_8.red.pal", level_up_digit_8_red_pal)
INCLUDE_PAL ("level_up/digit_9.red.pal", level_up_digit_9_red_pal)
INCLUDE_PAL ("level_up/small_digit_0.red.pal", level_up_small_digit_0_red_pal)
INCLUDE_PAL ("level_up/small_digit_1.red.pal", level_up_small_digit_1_red_pal)
INCLUDE_PAL ("level_up/small_digit_2.red.pal", level_up_small_digit_2_red_pal)
INCLUDE_PAL ("level_up/small_digit_3.red.pal", level_up_small_digit_3_red_pal)
INCLUDE_PAL ("level_up/small_digit_4.red.pal", level_up_small_digit_4_red_pal)
INCLUDE_PAL ("level_up/small_digit_5.red.pal", level_up_small_digit_5_red_pal)
INCLUDE_PAL ("level_up/small_digit_6.red.pal", level_up_small_digit_6_red_pal)
INCLUDE_PAL ("level_up/small_digit_7.red.pal", level_up_small_digit_7_red_pal)
INCLUDE_PAL ("level_up/small_digit_8.red.pal", level_up_small_digit_8_red_pal)
INCLUDE_PAL ("level_up/small_digit_9.red.pal", level_up_small_digit_9_red_pal)
INCLUDE_PAL ("level_up/small_arrow.red.pal", level_up_small_arrow_red_pal)
INCLUDE_PAL ("level_up/digit_0.blue.pal", level_up_digit_0_blue_pal)
INCLUDE_PAL ("level_up/digit_1.blue.pal", level_up_digit_1_blue_pal)
INCLUDE_PAL ("level_up/digit_2.blue.pal", level_up_digit_2_blue_pal)
INCLUDE_PAL ("level_up/digit_3.blue.pal", level_up_digit_3_blue_pal)
INCLUDE_PAL ("level_up/digit_4.blue.pal", level_up_digit_4_blue_pal)
INCLUDE_PAL ("level_up/digit_5.blue.pal", level_up_digit_5_blue_pal)
INCLUDE_PAL ("level_up/digit_6.blue.pal", level_up_digit_6_blue_pal)
INCLUDE_PAL ("level_up/digit_7.blue.pal", level_up_digit_7_blue_pal)
INCLUDE_PAL ("level_up/digit_8.blue.pal", level_up_digit_8_blue_pal)
INCLUDE_PAL ("level_up/digit_9.blue.pal", level_up_digit_9_blue_pal)
INCLUDE_PAL ("level_up/small_digit_0.blue.pal", level_up_small_digit_0_blue_pal)
INCLUDE_PAL ("level_up/small_digit_1.blue.pal", level_up_small_digit_1_blue_pal)
INCLUDE_PAL ("level_up/small_digit_2.blue.pal", level_up_small_digit_2_blue_pal)
INCLUDE_PAL ("level_up/small_digit_3.blue.pal", level_up_small_digit_3_blue_pal)
INCLUDE_PAL ("level_up/small_digit_4.blue.pal", level_up_small_digit_4_blue_pal)
INCLUDE_PAL ("level_up/small_digit_5.blue.pal", level_up_small_digit_5_blue_pal)
INCLUDE_PAL ("level_up/small_digit_6.blue.pal", level_up_small_digit_6_blue_pal)
INCLUDE_PAL ("level_up/small_digit_7.blue.pal", level_up_small_digit_7_blue_pal)
INCLUDE_PAL ("level_up/small_digit_8.blue.pal", level_up_small_digit_8_blue_pal)
INCLUDE_PAL ("level_up/small_digit_9.blue.pal", level_up_small_digit_9_blue_pal)
INCLUDE_PAL ("level_up/small_arrow.blue.pal", level_up_small_arrow_blue_pal)
INCLUDE_IMG ("level_up/select_one_to_upgrade.png", level_up_select_one_to_upgrade_png)
INCLUDE_PAL ("level_up/select_one_to_upgrade.pal", level_up_select_one_to_upgrade_pal)
Variables
Lights1 level_up_lights = gdSPDefLights1(0, 0, 0, 0, 0, 0, 0, 0, 0)
Gfx D_802A76E8_7A5628 []
Gfx D_802A7750_7A5690 []
Gfx D_802A77B8_7A56F8 []
Gfx D_802A7820_7A5760 []
Gfx D_802A7888_7A57C8 []
Gfx D_802A78F0_7A5830 []
Gfx D_802A7958_7A5898 []
Gfx D_802A79C0_7A5900 []
Gfx D_802A7A28_7A5968 []
Gfx D_802A7A88_7A59C8 []
EntityModelScript EMS_level_up = STANDARD_ENTITY_MODEL_SCRIPT(D_802A7A88_7A59C8, RENDER_MODE_CLOUD_NO_ZCMP)
HudScript HES_level_up_heart = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_heart_png, (s32) level_up_heart_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_heart_copy = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_heart_png, (s32) level_up_heart_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_flower = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_flower_png, (s32) level_up_flower_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_leaves = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_leaves_png, (s32) level_up_leaves_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_badge = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_badge_png, (s32) level_up_badge_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_FP = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_FP_png, (s32) level_up_FP_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_0_png, (s32) level_up_digit_0_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_1_png, (s32) level_up_digit_1_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_2_png, (s32) level_up_digit_2_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_3_png, (s32) level_up_digit_3_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_4_png, (s32) level_up_digit_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_5_png, (s32) level_up_digit_5_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_6_png, (s32) level_up_digit_6_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_7_png, (s32) level_up_digit_7_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_8_png, (s32) level_up_digit_8_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_green_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_9_png, (s32) level_up_digit_9_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_0_png, (s32) level_up_small_digit_0_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_1_png, (s32) level_up_small_digit_1_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_2_png, (s32) level_up_small_digit_2_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_3_png, (s32) level_up_small_digit_3_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_4_png, (s32) level_up_small_digit_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_5_png, (s32) level_up_small_digit_5_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_6_png, (s32) level_up_small_digit_6_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_7_png, (s32) level_up_small_digit_7_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_8_png, (s32) level_up_small_digit_8_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_9_png, (s32) level_up_small_digit_9_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_green_arrow = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_arrow_png, (s32) level_up_small_arrow_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_HP = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_HP_png, (s32) level_up_HP_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_0_png , (s32) level_up_digit_0_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_1_png , (s32) level_up_digit_1_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_2_png , (s32) level_up_digit_2_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_3_png , (s32) level_up_digit_3_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_4_png , (s32) level_up_digit_4_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_5_png , (s32) level_up_digit_5_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_6_png , (s32) level_up_digit_6_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_7_png , (s32) level_up_digit_7_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_8_png , (s32) level_up_digit_8_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_red_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_9_png , (s32) level_up_digit_9_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_0_png , (s32) level_up_small_digit_0_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_1_png , (s32) level_up_small_digit_1_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_2_png , (s32) level_up_small_digit_2_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_3_png , (s32) level_up_small_digit_3_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_4_png , (s32) level_up_small_digit_4_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_5_png , (s32) level_up_small_digit_5_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_6_png , (s32) level_up_small_digit_6_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_7_png , (s32) level_up_small_digit_7_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_8_png , (s32) level_up_small_digit_8_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_9_png , (s32) level_up_small_digit_9_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_red_arrow = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_arrow_png , (s32) level_up_small_arrow_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_BP = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_BP_png, (s32) level_up_BP_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_0_png , (s32) level_up_digit_0_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_1_png , (s32) level_up_digit_1_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_2_png , (s32) level_up_digit_2_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_3_png , (s32) level_up_digit_3_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_4_png , (s32) level_up_digit_4_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_5_png , (s32) level_up_digit_5_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_6_png , (s32) level_up_digit_6_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_7_png , (s32) level_up_digit_7_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_8_png , (s32) level_up_digit_8_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_blue_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_9_png , (s32) level_up_digit_9_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_0_png , (s32) level_up_small_digit_0_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_1_png , (s32) level_up_small_digit_1_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_2_png , (s32) level_up_small_digit_2_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_3_png , (s32) level_up_small_digit_3_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_4_png , (s32) level_up_small_digit_4_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_5_png , (s32) level_up_small_digit_5_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_6_png , (s32) level_up_small_digit_6_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_7_png , (s32) level_up_small_digit_7_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_8_png , (s32) level_up_small_digit_8_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_9_png , (s32) level_up_small_digit_9_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_small_blue_arrow = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_arrow_png , (s32) level_up_small_arrow_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HudScript HES_level_up_select_one_to_upgrade = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 208 , 16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_select_one_to_upgrade_png, (s32) level_up_select_one_to_upgrade_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Macro Definition Documentation
level_up_digit_0_blue_png
#define level_up_digit_0_blue_png level_up_digit_0_png
level_up_digit_0_red_png
#define level_up_digit_0_red_png level_up_digit_0_png
level_up_digit_1_blue_png
#define level_up_digit_1_blue_png level_up_digit_1_png
level_up_digit_1_red_png
#define level_up_digit_1_red_png level_up_digit_1_png
level_up_digit_2_blue_png
#define level_up_digit_2_blue_png level_up_digit_2_png
level_up_digit_2_red_png
#define level_up_digit_2_red_png level_up_digit_2_png
level_up_digit_3_blue_png
#define level_up_digit_3_blue_png level_up_digit_3_png
level_up_digit_3_red_png
#define level_up_digit_3_red_png level_up_digit_3_png
level_up_digit_4_blue_png
#define level_up_digit_4_blue_png level_up_digit_4_png
level_up_digit_4_red_png
#define level_up_digit_4_red_png level_up_digit_4_png
level_up_digit_5_blue_png
#define level_up_digit_5_blue_png level_up_digit_5_png
level_up_digit_5_red_png
#define level_up_digit_5_red_png level_up_digit_5_png
level_up_digit_6_blue_png
#define level_up_digit_6_blue_png level_up_digit_6_png
level_up_digit_6_red_png
#define level_up_digit_6_red_png level_up_digit_6_png
level_up_digit_7_blue_png
#define level_up_digit_7_blue_png level_up_digit_7_png
level_up_digit_7_red_png
#define level_up_digit_7_red_png level_up_digit_7_png
level_up_digit_8_blue_png
#define level_up_digit_8_blue_png level_up_digit_8_png
level_up_digit_8_red_png
#define level_up_digit_8_red_png level_up_digit_8_png
level_up_digit_9_blue_png
#define level_up_digit_9_blue_png level_up_digit_9_png
level_up_digit_9_red_png
#define level_up_digit_9_red_png level_up_digit_9_png
level_up_small_arrow_blue_png
#define level_up_small_arrow_blue_png level_up_small_arrow_png
level_up_small_arrow_red_png
#define level_up_small_arrow_red_png level_up_small_arrow_png
level_up_small_digit_0_blue_png
#define level_up_small_digit_0_blue_png level_up_small_digit_0_png
level_up_small_digit_0_red_png
#define level_up_small_digit_0_red_png level_up_small_digit_0_png
level_up_small_digit_1_blue_png
#define level_up_small_digit_1_blue_png level_up_small_digit_1_png
level_up_small_digit_1_red_png
#define level_up_small_digit_1_red_png level_up_small_digit_1_png
level_up_small_digit_2_blue_png
#define level_up_small_digit_2_blue_png level_up_small_digit_2_png
level_up_small_digit_2_red_png
#define level_up_small_digit_2_red_png level_up_small_digit_2_png
level_up_small_digit_3_blue_png
#define level_up_small_digit_3_blue_png level_up_small_digit_3_png
level_up_small_digit_3_red_png
#define level_up_small_digit_3_red_png level_up_small_digit_3_png
level_up_small_digit_4_blue_png
#define level_up_small_digit_4_blue_png level_up_small_digit_4_png
level_up_small_digit_4_red_png
#define level_up_small_digit_4_red_png level_up_small_digit_4_png
level_up_small_digit_5_blue_png
#define level_up_small_digit_5_blue_png level_up_small_digit_5_png
level_up_small_digit_5_red_png
#define level_up_small_digit_5_red_png level_up_small_digit_5_png
level_up_small_digit_6_blue_png
#define level_up_small_digit_6_blue_png level_up_small_digit_6_png
level_up_small_digit_6_red_png
#define level_up_small_digit_6_red_png level_up_small_digit_6_png
level_up_small_digit_7_blue_png
#define level_up_small_digit_7_blue_png level_up_small_digit_7_png
level_up_small_digit_7_red_png
#define level_up_small_digit_7_red_png level_up_small_digit_7_png
level_up_small_digit_8_blue_png
#define level_up_small_digit_8_blue_png level_up_small_digit_8_png
level_up_small_digit_8_red_png
#define level_up_small_digit_8_red_png level_up_small_digit_8_png
level_up_small_digit_9_blue_png
#define level_up_small_digit_9_blue_png level_up_small_digit_9_png
level_up_small_digit_9_red_png
#define level_up_small_digit_9_red_png level_up_small_digit_9_png
Function Documentation
INCLUDE_IMG() [1/35]
INCLUDE_IMG ("level_up/badge.png" , level_up_badge_png)
INCLUDE_IMG() [2/35]
INCLUDE_IMG ("level_up/big_E.png" , D_802A6670_7A45B0)
INCLUDE_IMG() [3/35]
INCLUDE_IMG ("level_up/big_exclamation_mark.png" , D_802A3508_7A1448)
INCLUDE_IMG() [4/35]
INCLUDE_IMG ("level_up/big_L.png" , D_802A55F8_7A3538)
INCLUDE_IMG() [5/35]
INCLUDE_IMG ("level_up/big_P.png" , D_802A2490_7A03D0)
INCLUDE_IMG() [6/35]
INCLUDE_IMG ("level_up/big_U.png" , D_802A4580_7A24C0)
INCLUDE_IMG() [7/35]
INCLUDE_IMG ("level_up/big_V.png" , D_802A1418_79F358)
INCLUDE_IMG() [8/35]
INCLUDE_IMG ("level_up/BP.png" , level_up_BP_png)
INCLUDE_IMG() [9/35]
INCLUDE_IMG ("level_up/digit_0.png" , level_up_digit_0_png)
INCLUDE_IMG() [10/35]
INCLUDE_IMG ("level_up/digit_1.png" , level_up_digit_1_png)
INCLUDE_IMG() [11/35]
INCLUDE_IMG ("level_up/digit_2.png" , level_up_digit_2_png)
INCLUDE_IMG() [12/35]
INCLUDE_IMG ("level_up/digit_3.png" , level_up_digit_3_png)
INCLUDE_IMG() [13/35]
INCLUDE_IMG ("level_up/digit_4.png" , level_up_digit_4_png)
INCLUDE_IMG() [14/35]
INCLUDE_IMG ("level_up/digit_5.png" , level_up_digit_5_png)
INCLUDE_IMG() [15/35]
INCLUDE_IMG ("level_up/digit_6.png" , level_up_digit_6_png)
INCLUDE_IMG() [16/35]
INCLUDE_IMG ("level_up/digit_7.png" , level_up_digit_7_png)
INCLUDE_IMG() [17/35]
INCLUDE_IMG ("level_up/digit_8.png" , level_up_digit_8_png)
INCLUDE_IMG() [18/35]
INCLUDE_IMG ("level_up/digit_9.png" , level_up_digit_9_png)
INCLUDE_IMG() [19/35]
INCLUDE_IMG ("level_up/flower.png" , level_up_flower_png)
INCLUDE_IMG() [20/35]
INCLUDE_IMG ("level_up/FP.png" , level_up_FP_png)
INCLUDE_IMG() [21/35]
INCLUDE_IMG ("level_up/heart.png" , level_up_heart_png)
INCLUDE_IMG() [22/35]
INCLUDE_IMG ("level_up/HP.png" , level_up_HP_png)
INCLUDE_IMG() [23/35]
INCLUDE_IMG ("level_up/leaves.png" , level_up_leaves_png)
INCLUDE_IMG() [24/35]
INCLUDE_IMG ("level_up/select_one_to_upgrade.png" , level_up_select_one_to_upgrade_png)
INCLUDE_IMG() [25/35]
INCLUDE_IMG ("level_up/small_arrow.png" , level_up_small_arrow_png)
INCLUDE_IMG() [26/35]
INCLUDE_IMG ("level_up/small_digit_0.png" , level_up_small_digit_0_png)
INCLUDE_IMG() [27/35]
INCLUDE_IMG ("level_up/small_digit_1.png" , level_up_small_digit_1_png)
INCLUDE_IMG() [28/35]
INCLUDE_IMG ("level_up/small_digit_2.png" , level_up_small_digit_2_png)
INCLUDE_IMG() [29/35]
INCLUDE_IMG ("level_up/small_digit_3.png" , level_up_small_digit_3_png)
INCLUDE_IMG() [30/35]
INCLUDE_IMG ("level_up/small_digit_4.png" , level_up_small_digit_4_png)
INCLUDE_IMG() [31/35]
INCLUDE_IMG ("level_up/small_digit_5.png" , level_up_small_digit_5_png)
INCLUDE_IMG() [32/35]
INCLUDE_IMG ("level_up/small_digit_6.png" , level_up_small_digit_6_png)
INCLUDE_IMG() [33/35]
INCLUDE_IMG ("level_up/small_digit_7.png" , level_up_small_digit_7_png)
INCLUDE_IMG() [34/35]
INCLUDE_IMG ("level_up/small_digit_8.png" , level_up_small_digit_8_png)
INCLUDE_IMG() [35/35]
INCLUDE_IMG ("level_up/small_digit_9.png" , level_up_small_digit_9_png)
INCLUDE_PAL() [1/71]
INCLUDE_PAL ("level_up/badge.pal" , level_up_badge_pal)
INCLUDE_PAL() [2/71]
INCLUDE_PAL ("level_up/BP.pal" , level_up_BP_pal)
INCLUDE_PAL() [3/71]
INCLUDE_PAL ("level_up/digit_0.blue.pal" , level_up_digit_0_blue_pal)
INCLUDE_PAL() [4/71]
INCLUDE_PAL ("level_up/digit_0.pal" , level_up_digit_0_pal)
INCLUDE_PAL() [5/71]
INCLUDE_PAL ("level_up/digit_0.red.pal" , level_up_digit_0_red_pal)
INCLUDE_PAL() [6/71]
INCLUDE_PAL ("level_up/digit_1.blue.pal" , level_up_digit_1_blue_pal)
INCLUDE_PAL() [7/71]
INCLUDE_PAL ("level_up/digit_1.pal" , level_up_digit_1_pal)
INCLUDE_PAL() [8/71]
INCLUDE_PAL ("level_up/digit_1.red.pal" , level_up_digit_1_red_pal)
INCLUDE_PAL() [9/71]
INCLUDE_PAL ("level_up/digit_2.blue.pal" , level_up_digit_2_blue_pal)
INCLUDE_PAL() [10/71]
INCLUDE_PAL ("level_up/digit_2.pal" , level_up_digit_2_pal)
INCLUDE_PAL() [11/71]
INCLUDE_PAL ("level_up/digit_2.red.pal" , level_up_digit_2_red_pal)
INCLUDE_PAL() [12/71]
INCLUDE_PAL ("level_up/digit_3.blue.pal" , level_up_digit_3_blue_pal)
INCLUDE_PAL() [13/71]
INCLUDE_PAL ("level_up/digit_3.pal" , level_up_digit_3_pal)
INCLUDE_PAL() [14/71]
INCLUDE_PAL ("level_up/digit_3.red.pal" , level_up_digit_3_red_pal)
INCLUDE_PAL() [15/71]
INCLUDE_PAL ("level_up/digit_4.blue.pal" , level_up_digit_4_blue_pal)
INCLUDE_PAL() [16/71]
INCLUDE_PAL ("level_up/digit_4.pal" , level_up_digit_4_pal)
INCLUDE_PAL() [17/71]
INCLUDE_PAL ("level_up/digit_4.red.pal" , level_up_digit_4_red_pal)
INCLUDE_PAL() [18/71]
INCLUDE_PAL ("level_up/digit_5.blue.pal" , level_up_digit_5_blue_pal)
INCLUDE_PAL() [19/71]
INCLUDE_PAL ("level_up/digit_5.pal" , level_up_digit_5_pal)
INCLUDE_PAL() [20/71]
INCLUDE_PAL ("level_up/digit_5.red.pal" , level_up_digit_5_red_pal)
INCLUDE_PAL() [21/71]
INCLUDE_PAL ("level_up/digit_6.blue.pal" , level_up_digit_6_blue_pal)
INCLUDE_PAL() [22/71]
INCLUDE_PAL ("level_up/digit_6.pal" , level_up_digit_6_pal)
INCLUDE_PAL() [23/71]
INCLUDE_PAL ("level_up/digit_6.red.pal" , level_up_digit_6_red_pal)
INCLUDE_PAL() [24/71]
INCLUDE_PAL ("level_up/digit_7.blue.pal" , level_up_digit_7_blue_pal)
INCLUDE_PAL() [25/71]
INCLUDE_PAL ("level_up/digit_7.pal" , level_up_digit_7_pal)
INCLUDE_PAL() [26/71]
INCLUDE_PAL ("level_up/digit_7.red.pal" , level_up_digit_7_red_pal)
INCLUDE_PAL() [27/71]
INCLUDE_PAL ("level_up/digit_8.blue.pal" , level_up_digit_8_blue_pal)
INCLUDE_PAL() [28/71]
INCLUDE_PAL ("level_up/digit_8.pal" , level_up_digit_8_pal)
INCLUDE_PAL() [29/71]
INCLUDE_PAL ("level_up/digit_8.red.pal" , level_up_digit_8_red_pal)
INCLUDE_PAL() [30/71]
INCLUDE_PAL ("level_up/digit_9.blue.pal" , level_up_digit_9_blue_pal)
INCLUDE_PAL() [31/71]
INCLUDE_PAL ("level_up/digit_9.pal" , level_up_digit_9_pal)
INCLUDE_PAL() [32/71]
INCLUDE_PAL ("level_up/digit_9.red.pal" , level_up_digit_9_red_pal)
INCLUDE_PAL() [33/71]
INCLUDE_PAL ("level_up/flower.pal" , level_up_flower_pal)
INCLUDE_PAL() [34/71]
INCLUDE_PAL ("level_up/FP.pal" , level_up_FP_pal)
INCLUDE_PAL() [35/71]
INCLUDE_PAL ("level_up/heart.pal" , level_up_heart_pal)
INCLUDE_PAL() [36/71]
INCLUDE_PAL ("level_up/HP.pal" , level_up_HP_pal)
INCLUDE_PAL() [37/71]
INCLUDE_PAL ("level_up/leaves.pal" , level_up_leaves_pal)
INCLUDE_PAL() [38/71]
INCLUDE_PAL ("level_up/select_one_to_upgrade.pal" , level_up_select_one_to_upgrade_pal)
INCLUDE_PAL() [39/71]
INCLUDE_PAL ("level_up/small_arrow.blue.pal" , level_up_small_arrow_blue_pal)
INCLUDE_PAL() [40/71]
INCLUDE_PAL ("level_up/small_arrow.pal" , level_up_small_arrow_pal)
INCLUDE_PAL() [41/71]
INCLUDE_PAL ("level_up/small_arrow.red.pal" , level_up_small_arrow_red_pal)
INCLUDE_PAL() [42/71]
INCLUDE_PAL ("level_up/small_digit_0.blue.pal" , level_up_small_digit_0_blue_pal)
INCLUDE_PAL() [43/71]
INCLUDE_PAL ("level_up/small_digit_0.pal" , level_up_small_digit_0_pal)
INCLUDE_PAL() [44/71]
INCLUDE_PAL ("level_up/small_digit_0.red.pal" , level_up_small_digit_0_red_pal)
INCLUDE_PAL() [45/71]
INCLUDE_PAL ("level_up/small_digit_1.blue.pal" , level_up_small_digit_1_blue_pal)
INCLUDE_PAL() [46/71]
INCLUDE_PAL ("level_up/small_digit_1.pal" , level_up_small_digit_1_pal)
INCLUDE_PAL() [47/71]
INCLUDE_PAL ("level_up/small_digit_1.red.pal" , level_up_small_digit_1_red_pal)
INCLUDE_PAL() [48/71]
INCLUDE_PAL ("level_up/small_digit_2.blue.pal" , level_up_small_digit_2_blue_pal)
INCLUDE_PAL() [49/71]
INCLUDE_PAL ("level_up/small_digit_2.pal" , level_up_small_digit_2_pal)
INCLUDE_PAL() [50/71]
INCLUDE_PAL ("level_up/small_digit_2.red.pal" , level_up_small_digit_2_red_pal)
INCLUDE_PAL() [51/71]
INCLUDE_PAL ("level_up/small_digit_3.blue.pal" , level_up_small_digit_3_blue_pal)
INCLUDE_PAL() [52/71]
INCLUDE_PAL ("level_up/small_digit_3.pal" , level_up_small_digit_3_pal)
INCLUDE_PAL() [53/71]
INCLUDE_PAL ("level_up/small_digit_3.red.pal" , level_up_small_digit_3_red_pal)
INCLUDE_PAL() [54/71]
INCLUDE_PAL ("level_up/small_digit_4.blue.pal" , level_up_small_digit_4_blue_pal)
INCLUDE_PAL() [55/71]
INCLUDE_PAL ("level_up/small_digit_4.pal" , level_up_small_digit_4_pal)
INCLUDE_PAL() [56/71]
INCLUDE_PAL ("level_up/small_digit_4.red.pal" , level_up_small_digit_4_red_pal)
INCLUDE_PAL() [57/71]
INCLUDE_PAL ("level_up/small_digit_5.blue.pal" , level_up_small_digit_5_blue_pal)
INCLUDE_PAL() [58/71]
INCLUDE_PAL ("level_up/small_digit_5.pal" , level_up_small_digit_5_pal)
INCLUDE_PAL() [59/71]
INCLUDE_PAL ("level_up/small_digit_5.red.pal" , level_up_small_digit_5_red_pal)
INCLUDE_PAL() [60/71]
INCLUDE_PAL ("level_up/small_digit_6.blue.pal" , level_up_small_digit_6_blue_pal)
INCLUDE_PAL() [61/71]
INCLUDE_PAL ("level_up/small_digit_6.pal" , level_up_small_digit_6_pal)
INCLUDE_PAL() [62/71]
INCLUDE_PAL ("level_up/small_digit_6.red.pal" , level_up_small_digit_6_red_pal)
INCLUDE_PAL() [63/71]
INCLUDE_PAL ("level_up/small_digit_7.blue.pal" , level_up_small_digit_7_blue_pal)
INCLUDE_PAL() [64/71]
INCLUDE_PAL ("level_up/small_digit_7.pal" , level_up_small_digit_7_pal)
INCLUDE_PAL() [65/71]
INCLUDE_PAL ("level_up/small_digit_7.red.pal" , level_up_small_digit_7_red_pal)
INCLUDE_PAL() [66/71]
INCLUDE_PAL ("level_up/small_digit_8.blue.pal" , level_up_small_digit_8_blue_pal)
INCLUDE_PAL() [67/71]
INCLUDE_PAL ("level_up/small_digit_8.pal" , level_up_small_digit_8_pal)
INCLUDE_PAL() [68/71]
INCLUDE_PAL ("level_up/small_digit_8.red.pal" , level_up_small_digit_8_red_pal)
INCLUDE_PAL() [69/71]
INCLUDE_PAL ("level_up/small_digit_9.blue.pal" , level_up_small_digit_9_blue_pal)
INCLUDE_PAL() [70/71]
INCLUDE_PAL ("level_up/small_digit_9.pal" , level_up_small_digit_9_pal)
INCLUDE_PAL() [71/71]
INCLUDE_PAL ("level_up/small_digit_9.red.pal" , level_up_small_digit_9_red_pal)
Variable Documentation
D_802A76E8_7A5628
Gfx D_802A76E8_7A5628[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_XLU_SURF, G_RM_XLU_SURF2),
    gsSPDisplayList(D_802A4508_7A2448),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPVertex(&D_802A1398_79F2D8[0], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 6, 7, 0),
    gsSPEndDisplayList(),
}
D_802A7750_7A5690
Gfx D_802A7750_7A5690[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_XLU_SURF, G_RM_XLU_SURF2),
    gsSPDisplayList(D_802A5580_7A34C0),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPVertex(&D_802A1318_79F258[0], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 6, 7, 0),
    gsSPEndDisplayList(),
}
D_802A77B8_7A56F8
Gfx D_802A77B8_7A56F8[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_XLU_SURF, G_RM_XLU_SURF2),
    gsSPDisplayList(D_802A3490_7A13D0),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPVertex(&D_802A1298_79F1D8[0], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 6, 7, 0),
    gsSPEndDisplayList(),
}
D_802A7820_7A5760
Gfx D_802A7820_7A5760[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_XLU_SURF, G_RM_XLU_SURF2),
    gsSPDisplayList(D_802A65F8_7A4538),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPVertex(&D_802A1218_79F158[0], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 6, 7, 0),
    gsSPEndDisplayList(),
}
D_802A7888_7A57C8
Gfx D_802A7888_7A57C8[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_XLU_SURF, G_RM_XLU_SURF2),
    gsSPDisplayList(D_802A65F8_7A4538),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPVertex(&D_802A1198_79F0D8[0], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 6, 7, 0),
    gsSPEndDisplayList(),
}
D_802A78F0_7A5830
Gfx D_802A78F0_7A5830[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_XLU_SURF, G_RM_XLU_SURF2),
    gsSPDisplayList(D_802A7670_7A55B0),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPVertex(&D_802A1118_79F058[0], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 6, 7, 0),
    gsSPEndDisplayList(),
}
D_802A7958_7A5898
Gfx D_802A7958_7A5898[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_XLU_SURF, G_RM_XLU_SURF2),
    gsSPDisplayList(D_802A2418_7A0358),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPVertex(&D_802A1098_79EFD8[0], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 6, 7, 0),
    gsSPEndDisplayList(),
}
D_802A79C0_7A5900
Gfx D_802A79C0_7A5900[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_XLU_SURF, G_RM_XLU_SURF2),
    gsSPDisplayList(D_802A7670_7A55B0),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPVertex(&D_802A1018_79EF58[0], 8, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSP2Triangles(4, 5, 6, 0, 4, 6, 7, 0),
    gsSPEndDisplayList(),
}
D_802A7A28_7A5968
Gfx D_802A7A28_7A5968[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsSPDisplayList(D_802A79C0_7A5900),
    gsSPDisplayList(D_802A7958_7A5898),
    gsSPDisplayList(D_802A78F0_7A5830),
    gsSPDisplayList(D_802A7888_7A57C8),
    gsSPDisplayList(D_802A7820_7A5760),
    gsSPDisplayList(D_802A77B8_7A56F8),
    gsSPDisplayList(D_802A7750_7A5690),
    gsSPDisplayList(D_802A76E8_7A5628),
    gsSPEndDisplayList(),
}
D_802A7A88_7A59C8
Gfx D_802A7A88_7A59C8[]
Initial value:
= {
    gsSPSetLights1(level_up_lights),
    gsSPDisplayList(D_802A7A28_7A5968),
    gsSPEndDisplayList(),
}
EMS_level_up
EntityModelScript EMS_level_up = STANDARD_ENTITY_MODEL_SCRIPT(D_802A7A88_7A59C8, RENDER_MODE_CLOUD_NO_ZCMP)
HES_level_up_badge
HudScript HES_level_up_badge = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_badge_png, (s32) level_up_badge_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_state_draw_celebration(), and btl_state_update_celebration().
HES_level_up_blue_digit_0
HudScript HES_level_up_blue_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_0_png , (s32) level_up_digit_0_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_blue_digit_1
HudScript HES_level_up_blue_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_1_png , (s32) level_up_digit_1_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_blue_digit_2
HudScript HES_level_up_blue_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_2_png , (s32) level_up_digit_2_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_blue_digit_3
HudScript HES_level_up_blue_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_3_png , (s32) level_up_digit_3_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_blue_digit_4
HudScript HES_level_up_blue_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_4_png , (s32) level_up_digit_4_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_blue_digit_5
HudScript HES_level_up_blue_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_5_png , (s32) level_up_digit_5_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_blue_digit_6
HudScript HES_level_up_blue_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_6_png , (s32) level_up_digit_6_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_blue_digit_7
HudScript HES_level_up_blue_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_7_png , (s32) level_up_digit_7_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_blue_digit_8
HudScript HES_level_up_blue_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_8_png , (s32) level_up_digit_8_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_blue_digit_9
HudScript HES_level_up_blue_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_9_png , (s32) level_up_digit_9_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_BP
HudScript HES_level_up_BP = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_BP_png, (s32) level_up_BP_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_flower
HudScript HES_level_up_flower = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_flower_png, (s32) level_up_flower_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_state_draw_celebration(), and btl_state_update_celebration().
HES_level_up_FP
HudScript HES_level_up_FP = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_FP_png, (s32) level_up_FP_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_0
HudScript HES_level_up_green_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_0_png, (s32) level_up_digit_0_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_1
HudScript HES_level_up_green_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_1_png, (s32) level_up_digit_1_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_2
HudScript HES_level_up_green_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_2_png, (s32) level_up_digit_2_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_3
HudScript HES_level_up_green_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_3_png, (s32) level_up_digit_3_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_4
HudScript HES_level_up_green_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_4_png, (s32) level_up_digit_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_5
HudScript HES_level_up_green_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_5_png, (s32) level_up_digit_5_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_6
HudScript HES_level_up_green_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_6_png, (s32) level_up_digit_6_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_7
HudScript HES_level_up_green_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_7_png, (s32) level_up_digit_7_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_8
HudScript HES_level_up_green_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_8_png, (s32) level_up_digit_8_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_green_digit_9
HudScript HES_level_up_green_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_9_png, (s32) level_up_digit_9_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_heart
HudScript HES_level_up_heart = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_heart_png, (s32) level_up_heart_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_state_update_celebration().
HES_level_up_heart_copy
HudScript HES_level_up_heart_copy = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_heart_png, (s32) level_up_heart_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_state_draw_celebration().
HES_level_up_HP
HudScript HES_level_up_HP = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 32 , 24 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_HP_png, (s32) level_up_HP_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_leaves
HudScript HES_level_up_leaves = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_40x40 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_leaves_png, (s32) level_up_leaves_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_state_draw_celebration(), and btl_state_update_celebration().
HES_level_up_red_digit_0
HudScript HES_level_up_red_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_0_png , (s32) level_up_digit_0_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_red_digit_1
HudScript HES_level_up_red_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_1_png , (s32) level_up_digit_1_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_red_digit_2
HudScript HES_level_up_red_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_2_png , (s32) level_up_digit_2_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_red_digit_3
HudScript HES_level_up_red_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_3_png , (s32) level_up_digit_3_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_red_digit_4
HudScript HES_level_up_red_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_4_png , (s32) level_up_digit_4_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_red_digit_5
HudScript HES_level_up_red_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_5_png , (s32) level_up_digit_5_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_red_digit_6
HudScript HES_level_up_red_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_6_png , (s32) level_up_digit_6_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_red_digit_7
HudScript HES_level_up_red_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_7_png , (s32) level_up_digit_7_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_red_digit_8
HudScript HES_level_up_red_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_8_png , (s32) level_up_digit_8_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_red_digit_9
HudScript HES_level_up_red_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_digit_9_png , (s32) level_up_digit_9_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_select_one_to_upgrade
HudScript HES_level_up_select_one_to_upgrade = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetCustomSize, 208 , 16 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_select_one_to_upgrade_png, (s32) level_up_select_one_to_upgrade_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_state_update_celebration().
HES_level_up_small_blue_arrow
HudScript HES_level_up_small_blue_arrow = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_arrow_png , (s32) level_up_small_arrow_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_state_update_celebration().
HES_level_up_small_blue_digit_0
HudScript HES_level_up_small_blue_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_0_png , (s32) level_up_small_digit_0_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_blue_digit_1
HudScript HES_level_up_small_blue_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_1_png , (s32) level_up_small_digit_1_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_blue_digit_2
HudScript HES_level_up_small_blue_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_2_png , (s32) level_up_small_digit_2_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_blue_digit_3
HudScript HES_level_up_small_blue_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_3_png , (s32) level_up_small_digit_3_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_blue_digit_4
HudScript HES_level_up_small_blue_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_4_png , (s32) level_up_small_digit_4_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_blue_digit_5
HudScript HES_level_up_small_blue_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_5_png , (s32) level_up_small_digit_5_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_blue_digit_6
HudScript HES_level_up_small_blue_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_6_png , (s32) level_up_small_digit_6_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_blue_digit_7
HudScript HES_level_up_small_blue_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_7_png , (s32) level_up_small_digit_7_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_blue_digit_8
HudScript HES_level_up_small_blue_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_8_png , (s32) level_up_small_digit_8_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_blue_digit_9
HudScript HES_level_up_small_blue_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_9_png , (s32) level_up_small_digit_9_blue_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_arrow
HudScript HES_level_up_small_green_arrow = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_arrow_png, (s32) level_up_small_arrow_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_state_update_celebration().
HES_level_up_small_green_digit_0
HudScript HES_level_up_small_green_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_0_png, (s32) level_up_small_digit_0_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_digit_1
HudScript HES_level_up_small_green_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_1_png, (s32) level_up_small_digit_1_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_digit_2
HudScript HES_level_up_small_green_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_2_png, (s32) level_up_small_digit_2_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_digit_3
HudScript HES_level_up_small_green_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_3_png, (s32) level_up_small_digit_3_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_digit_4
HudScript HES_level_up_small_green_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_4_png, (s32) level_up_small_digit_4_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_digit_5
HudScript HES_level_up_small_green_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_5_png, (s32) level_up_small_digit_5_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_digit_6
HudScript HES_level_up_small_green_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_6_png, (s32) level_up_small_digit_6_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_digit_7
HudScript HES_level_up_small_green_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_7_png, (s32) level_up_small_digit_7_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_digit_8
HudScript HES_level_up_small_green_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_8_png, (s32) level_up_small_digit_8_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_green_digit_9
HudScript HES_level_up_small_green_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_9_png, (s32) level_up_small_digit_9_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_arrow
HudScript HES_level_up_small_red_arrow = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_arrow_png , (s32) level_up_small_arrow_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
Referenced by btl_state_update_celebration().
HES_level_up_small_red_digit_0
HudScript HES_level_up_small_red_digit_0 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_0_png , (s32) level_up_small_digit_0_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_digit_1
HudScript HES_level_up_small_red_digit_1 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_1_png , (s32) level_up_small_digit_1_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_digit_2
HudScript HES_level_up_small_red_digit_2 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_2_png , (s32) level_up_small_digit_2_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_digit_3
HudScript HES_level_up_small_red_digit_3 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_3_png , (s32) level_up_small_digit_3_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_digit_4
HudScript HES_level_up_small_red_digit_4 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_4_png , (s32) level_up_small_digit_4_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_digit_5
HudScript HES_level_up_small_red_digit_5 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_5_png , (s32) level_up_small_digit_5_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_digit_6
HudScript HES_level_up_small_red_digit_6 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_6_png , (s32) level_up_small_digit_6_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_digit_7
HudScript HES_level_up_small_red_digit_7 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_7_png , (s32) level_up_small_digit_7_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_digit_8
HudScript HES_level_up_small_red_digit_8 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_8_png , (s32) level_up_small_digit_8_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
HES_level_up_small_red_digit_9
HudScript HES_level_up_small_red_digit_9 = { HUD_ELEMENT_OP_SetVisible, HUD_ELEMENT_OP_SetTileSize, HUD_ELEMENT_SIZE_8x8 , HUD_ELEMENT_OP_Loop, HUD_ELEMENT_OP_SetCI, 60 , (s32) level_up_small_digit_9_png , (s32) level_up_small_digit_9_red_pal, HUD_ELEMENT_OP_Restart, HUD_ELEMENT_OP_End, }
level_up_lights
Lights1 level_up_lights = gdSPDefLights1(0, 0, 0, 0, 0, 0, 0, 0, 0)