papermario: src/effects/lightning.c File Reference
lightning.c File Reference
Functions
void lightning_init (EffectInstance *effect)
void lightning_update (EffectInstance *effect)
void lightning_render (EffectInstance *effect)
void lightning_appendGfx (void *effect)
EFFECT_DEF_GATHER_MAGIC (gather_magic_main)
EFFECT_DEF_BULB_GLOW (bulb_glow_main)
EFFECT_DEF_SNAKING_STATIC (snaking_static_main)
EFFECT_DEF_FLASHING_BOX_SHOCKWAVE (flashing_box_shockwave_main)
EffectInstance * lightning_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
Variables
Gfx D_09003280_371FE0 []
Gfx D_090032F8_372058 []
Gfx D_09003378_3720D8 []
Gfx D_090033E0_372140 []
Gfx D_09003580_3722E0 []
Gfx D_09003778_3724D8 []
Gfx D_09003888_3725E8 []
Gfx D_09003948_3726A8 []
Gfx * D_E006CB60 []
Gfx * D_E006CB78 []
Function Documentation
EFFECT_DEF_BULB_GLOW()
EFFECT_DEF_BULB_GLOW (bulb_glow_main)
EFFECT_DEF_FLASHING_BOX_SHOCKWAVE()
EFFECT_DEF_FLASHING_BOX_SHOCKWAVE (flashing_box_shockwave_main)
EFFECT_DEF_GATHER_MAGIC()
EFFECT_DEF_GATHER_MAGIC (gather_magic_main)
EFFECT_DEF_SNAKING_STATIC()
EFFECT_DEF_SNAKING_STATIC (snaking_static_main)
lightning_appendGfx()
void lightning_appendGfx (void * effect)
Referenced by lightning_render().
lightning_init()
void lightning_init (EffectInstance * effect)
Referenced by lightning_main().
lightning_main()
EffectInstance * lightning_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
lightning_render()
void lightning_render (EffectInstance * effect)
Referenced by lightning_main().
lightning_update()
void lightning_update (EffectInstance * effect)
Referenced by lightning_main().
Variable Documentation
D_09003280_371FE0
Gfx D_09003280_371FE0[] extern
D_090032F8_372058
Gfx D_090032F8_372058[] extern
D_09003378_3720D8
Gfx D_09003378_3720D8[] extern
D_090033E0_372140
Gfx D_090033E0_372140[] extern
D_09003580_3722E0
Gfx D_09003580_3722E0[] extern
D_09003778_3724D8
Gfx D_09003778_3724D8[] extern
D_09003888_3725E8
Gfx D_09003888_3725E8[] extern
D_09003948_3726A8
Gfx D_09003948_3726A8[] extern
D_E006CB60
Gfx* D_E006CB60[]
Initial value:
= {
    D_09003778_3724D8, D_09003580_3722E0, D_090033E0_372140,
    D_09003378_3720D8, D_090032F8_372058, D_09003280_371FE0
}
Referenced by lightning_appendGfx().
D_E006CB78
Gfx* D_E006CB78[]
Initial value:
= {
    D_09003888_3725E8, D_09003888_3725E8, D_09003888_3725E8,
    D_09003948_3726A8, D_09003948_3726A8, D_09003948_3726A8
}
Referenced by lightning_appendGfx().