papermario: src/effects/light_rays.c File Reference
light_rays.c File Reference
Functions
void light_rays_init (EffectInstance *effect)
void light_rays_update (EffectInstance *effect)
void light_rays_render (EffectInstance *effect)
void light_rays_appendGfx (void *effect)
void func_E006A000 (LightRaysFXData *part, s32 beamIdx)
void func_E006A0BC (LightRaysFXData *part, s32 beamIdx)
void light_rays_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, EffectInstance **outEffect)
void func_E006A464 (LightRaysFXData *part)
void func_E006A85C (LightRaysFXData *part)
Variables
Gfx D_090000B0_36E040 []
Gfx D_09000110_36E0A0 []
Gfx D_09000130_36E0C0 []
Gfx D_090001D8_36E168 []
Gfx * D_E006ADF0 []
Gfx * D_E006AE00 []
s32 D_E006AE10 []
Function Documentation
func_E006A000()
void func_E006A000 (LightRaysFXData * part, s32 beamIdx)
Referenced by light_rays_main(), and light_rays_update().
func_E006A0BC()
void func_E006A0BC (LightRaysFXData * part, s32 beamIdx)
Referenced by light_rays_main(), and light_rays_update().
func_E006A464()
void func_E006A464 (LightRaysFXData * part)
Referenced by light_rays_update().
func_E006A85C()
void func_E006A85C (LightRaysFXData * part)
Referenced by light_rays_appendGfx().
light_rays_appendGfx()
void light_rays_appendGfx (void * effect)
Referenced by light_rays_render().
light_rays_init()
void light_rays_init (EffectInstance * effect)
Referenced by light_rays_main().
light_rays_main()
void light_rays_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, EffectInstance ** outEffect)
light_rays_render()
void light_rays_render (EffectInstance * effect)
Referenced by light_rays_main().
light_rays_update()
void light_rays_update (EffectInstance * effect)
Referenced by light_rays_main().
Variable Documentation
D_090000B0_36E040
Gfx D_090000B0_36E040[] extern
D_09000110_36E0A0
Gfx D_09000110_36E0A0[] extern
D_09000130_36E0C0
Gfx D_09000130_36E0C0[] extern
D_090001D8_36E168
Gfx D_090001D8_36E168[] extern
D_E006ADF0
Gfx* D_E006ADF0[]
Initial value:
= {
    D_09000110_36E0A0, D_09000110_36E0A0, D_090000B0_36E040, D_090000B0_36E040
}
Referenced by light_rays_appendGfx().
D_E006AE00
Gfx* D_E006AE00[]
Initial value:
= {
    D_09000130_36E0C0, D_09000130_36E0C0, D_090001D8_36E168, D_090001D8_36E168
}
Referenced by light_rays_appendGfx().
D_E006AE10
s32 D_E006AE10[]
Initial value:
= {
      0,  -20,    0,   1,  18,
    -10,  -60,   45,  -1,   4,
    -20,  -20,   90,   1,   1,
    -10,  -60,  135,   1,  -4,
      0,  -20,  180,  -8,   1,
    -10,  -60,  225,  -1,  -1,
    -20,  -20,  270,   1,  -9,
    -10,  -60,  315,   4,   4,
      0,   10,   22,   4,   1,
    -10,   20,   67,   1,  -1,
    -20,   10,  112,  -1,  -1,
    -10,   20,  157,  -8,   1,
      0,   10,  202,   1,  -4,
    -10,   20,  247,   1, -18,
    -20,   10,  292,  -1,   9,
    -10,   20,  337,   1,   1
}
Referenced by func_E006A0BC().