papermario: src/effects/lightning_bolt.c File Reference
lightning_bolt.c File Reference
Data Structures
struct LightningPreset
Functions
void lightning_bolt_init (EffectInstance *effect)
void lightning_bolt_update (EffectInstance *effect)
void lightning_bolt_render (EffectInstance *effect)
void lightning_bolt_appendGfx (void *effect)
EffectInstance * lightning_bolt_main (s32 type, f32 startX, f32 startY, f32 startZ, f32 endX, f32 endY, f32 endZ, f32 scale, s32 duration)
f32 lightning_bolt_get_rand_symmetric (f32 interval)
void func_E00BC36C (void)
Variables
LightningPreset D_E00BCC30 []
LightningPreset D_E00BCD38 []
LightningPreset * D_E00BCE40 [] = { D_E00BCC30, D_E00BCD38 }
Gfx D_09001000_3BBEA0 []
Data Structure Documentation
LightningPreset
struct LightningPreset
Data Fields
u8 offset[12]
u8 width[12]
Function Documentation
func_E00BC36C()
void func_E00BC36C (void)
lightning_bolt_appendGfx()
void lightning_bolt_appendGfx (void * effect)
Referenced by lightning_bolt_render().
lightning_bolt_get_rand_symmetric()
f32 lightning_bolt_get_rand_symmetric (f32 interval)
lightning_bolt_init()
void lightning_bolt_init (EffectInstance * effect)
Referenced by lightning_bolt_main().
lightning_bolt_main()
EffectInstance * lightning_bolt_main (s32 type, f32 startX, f32 startY, f32 startZ, f32 endX, f32 endY, f32 endZ, f32 scale, s32 duration)
lightning_bolt_render()
void lightning_bolt_render (EffectInstance * effect)
Referenced by lightning_bolt_main().
lightning_bolt_update()
void lightning_bolt_update (EffectInstance * effect)
Referenced by lightning_bolt_main().
Variable Documentation
D_09001000_3BBEA0
Gfx D_09001000_3BBEA0[] extern
Referenced by lightning_bolt_appendGfx().
D_E00BCC30
LightningPreset D_E00BCC30[]
Initial value:
= {
    {{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5}, {10, 9, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5}, {8, 7, 6, 5, 4, 3, 2, 1, 0, 0, 0, 0}},
    {{35, 5, 25, 5, 0, 25, 35, 5, 15, 0, 0, 0}, {10, 13, 15, 12, 11, 13, 10, 12, 5, 1, 0, 0}},
    {{45, 15, 35, 15, 0, 35, 45, 55, 25, 5, 2, 0}, {13, 10, 12, 10, 13, 10, 13, 10, 12, 9, 5, 1}},
    {{15, 15, 15, 15, 15, 15, 0, 15, 15, 5, 2, 0}, {14, 10, 15, 10, 13, 30, 32, 30, 24, 50, 40, 60}},
    {{1, 5, 15, 15, 35, 45, 40, 35, 25, 5, 2, 0}, {4, 6, 10, 5, 8, 14, 6, 10, 14, 35, 50, 50}},
    {{1, 15, 25, 15, 25, 35, 45, 40, 35, 15, 5, 0}, {2, 2, 23, 12, 8, 15, 15, 5, 6, 18, 38, 60}},
    {{30, 25, 15, 5, 15, 15, 25, 30, 35, 25, 5, 0}, {3, 3, 3, 11, 3, 12, 4, 5, 2, 12, 42, 50}},
    {{33, 33, 20, 12, 25, 17, 15, 20, 22, 20, 5, 0}, {3, 3, 3, 2, 10, 2, 2, 12, 2, 2, 2, 20}},
    {{30, 30, 25, 25, 35, 20, 15, 10, 15, 15, 5, 0}, {2, 2, 2, 2, 2, 2, 6, 2, 2, 2, 6, 5}},
    {{27, 27, 22, 22, 32, 17, 12, 7, 12, 12, 2, 0}, {2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0}},
}
D_E00BCD38
LightningPreset D_E00BCD38[]
Initial value:
= {
    {{25, 25, 25, 5, 25, 5, 25, 25, 5, 25, 25, 25}, {4, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0}},
    {{15, 15, 15, 25, 15, 15, 5, 25, 25, 15, 25, 25}, {4, 4, 4, 4, 4, 3, 2, 1, 0, 0, 0, 0}},
    {{25, 25, 25, 5, 15, 25, 5, 5, 15, 5, 5, 0}, {4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 0, 0}},
    {{25, 25, 25, 5, 25, 5, 25, 25, 5, 15, 5, 0}, {4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 6, 5}},
    {{15, 15, 15, 45, 35, 45, 35, 35, 25, 35, 15, 0}, {4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 6, 5}},
    {{45, 55, 35, 25, 55, 15, 45, 25, 45, 35, 15, 0}, {4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 6, 5}},
    {{85, 25, 15, 75, 25, 65, 35, 45, 75, 85, 15, 0}, {4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 6, 5}},
    {{85, 15, 35, 55, 65, 45, 25, 75, 35, 45, 35, 40}, {4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 6, 5}},
    {{85, 15, 35, 55, 65, 45, 25, 75, 35, 45, 35, 40}, {4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 6, 5}},
    {{85, 15, 35, 55, 65, 45, 25, 75, 35, 45, 35, 40}, {4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 6, 5}},
    {{30, 30, 25, 25, 35, 20, 15, 10, 15, 15, 5, 0}, {4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 0}},
}
D_E00BCE40
LightningPreset* D_E00BCE40[] = { D_E00BCC30, D_E00BCD38 }
Referenced by lightning_bolt_appendGfx().