papermario: src/effects/lil_oink.c File Reference
lil_oink.c File Reference
Functions
void lil_oink_appendGfx (void *effect)
void lil_oink_init (EffectInstance *effect)
void lil_oink_update (EffectInstance *effect)
void lil_oink_render (EffectInstance *effect)
EffectInstance * lil_oink_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09002D70_401FC0 []
Gfx D_09002DD8_402028 []
Gfx D_09002E70_4020C0 []
Gfx D_09002E98_4020E8 []
Gfx D_09002F30_402180 []
Gfx D_09002FC8_402218 []
Gfx D_09003060_4022B0 []
Gfx D_090030F8_402348 []
Gfx D_09003190_4023E0 []
Gfx D_09003228_402478 []
Gfx D_090032C0_402510 []
Gfx D_09003358_4025A8 []
Gfx D_09003370_4025C0 []
Gfx D_09003388_4025D8 []
Gfx * lil_oink_FramesGfx [][3]
Gfx * D_E0114718 []
s8 lil_oink_AnimateGfxSelect [] = { 1, 2, 1, 0 }
Function Documentation
lil_oink_appendGfx()
void lil_oink_appendGfx (void * effect)
Referenced by lil_oink_render().
lil_oink_init()
void lil_oink_init (EffectInstance * effect)
Referenced by lil_oink_main().
lil_oink_main()
EffectInstance * lil_oink_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
lil_oink_render()
void lil_oink_render (EffectInstance * effect)
Referenced by lil_oink_main().
lil_oink_update()
void lil_oink_update (EffectInstance * effect)
Referenced by lil_oink_main().
Variable Documentation
D_09002D70_401FC0
Gfx D_09002D70_401FC0[] extern
Referenced by lil_oink_appendGfx().
D_09002DD8_402028
Gfx D_09002DD8_402028[] extern
D_09002E70_4020C0
Gfx D_09002E70_4020C0[] extern
D_09002E98_4020E8
Gfx D_09002E98_4020E8[] extern
D_09002F30_402180
Gfx D_09002F30_402180[] extern
D_09002FC8_402218
Gfx D_09002FC8_402218[] extern
D_09003060_4022B0
Gfx D_09003060_4022B0[] extern
D_090030F8_402348
Gfx D_090030F8_402348[] extern
D_09003190_4023E0
Gfx D_09003190_4023E0[] extern
D_09003228_402478
Gfx D_09003228_402478[] extern
D_090032C0_402510
Gfx D_090032C0_402510[] extern
D_09003358_4025A8
Gfx D_09003358_4025A8[] extern
D_09003370_4025C0
Gfx D_09003370_4025C0[] extern
D_09003388_4025D8
Gfx D_09003388_4025D8[] extern
D_E0114718
Gfx* D_E0114718[]
Initial value:
= {
    [LIL_OINK_TYPE_BLACK]       D_09002DD8_402028,
    [LIL_OINK_TYPE_WHITE]       D_09002E70_4020C0,
    [LIL_OINK_TYPE_PINK]        D_09002E98_4020E8,
    [LIL_OINK_TYPE_PIKACHU]     D_09002F30_402180,
    [LIL_OINK_TYPE_SHROOM]      D_09002FC8_402218,
    [LIL_OINK_TYPE_FLOWER]      D_09003060_4022B0,
    [LIL_OINK_TYPE_STAR]        D_090030F8_402348,
    [LIL_OINK_TYPE_QUESTION]    D_09003190_4023E0,
    [LIL_OINK_TYPE_SILVER]      D_09003228_402478,
    [LIL_OINK_TYPE_GOLD]        D_090032C0_402510
}
Referenced by lil_oink_appendGfx().
lil_oink_AnimateGfxSelect
s8 lil_oink_AnimateGfxSelect[] = { 1, 2, 1, 0 }
Referenced by lil_oink_update().
lil_oink_FramesGfx
Gfx* lil_oink_FramesGfx[][3]
Initial value:
= {
    [LIL_OINK_TYPE_BLACK]       { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
    [LIL_OINK_TYPE_WHITE]       { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
    [LIL_OINK_TYPE_PINK]        { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
    [LIL_OINK_TYPE_PIKACHU]     { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
    [LIL_OINK_TYPE_SHROOM]      { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
    [LIL_OINK_TYPE_FLOWER]      { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
    [LIL_OINK_TYPE_STAR]        { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
    [LIL_OINK_TYPE_QUESTION]    { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
    [LIL_OINK_TYPE_SILVER]      { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
    [LIL_OINK_TYPE_GOLD]        { D_09003358_4025A8, D_09003370_4025C0, D_09003388_4025D8 },
}
Referenced by lil_oink_appendGfx().