papermario: src/load_obfuscation_shims.c File Reference
load_obfuscation_shims.c File Reference
Functions
void load_obfuscation_shims (void)
Variables
s8 obfuscated_obfuscation_shims_ROM_START []
s8 obfuscated_obfuscation_shims_VRAM []
Function Documentation
load_obfuscation_shims()
void load_obfuscation_shims (void)
Referenced by boot_main(), load_map_by_IDs(), and state_step_battle().
Variable Documentation
obfuscated_obfuscation_shims_ROM_START
s8 obfuscated_obfuscation_shims_ROM_START[] extern
Referenced by load_obfuscation_shims().
obfuscated_obfuscation_shims_VRAM
s8 obfuscated_obfuscation_shims_VRAM[] extern
Referenced by load_obfuscation_shims().