papermario: src/main.c File Reference
main.c File Reference
Enumerations
enum { RESET_STATE_NONE = 0 , RESET_STATE_INIT = 1 , RESET_STATE_FADE = 2 }
Functions
u8 nuBootStack[0x2000] ALIGNED (8)
unsigned char D_800B32E0[0x800] ALIGNED (16)
void gfxRetrace_Callback (s32)
void gfxPreNMI_Callback (void)
void appendGfx_reset_tile_pattern (void)
void gfx_draw_frame (void)
void gfx_init_state (void)
void create_audio_system (void)
void load_engine_data (void)
void boot_main (void *data)
Variables
u8 nuYieldBuf [NU_GFX_YIELD_BUF_SIZE]
OSThread __osThreadSave
s16 D_80074010 = 8
s32 ResetGameState
u16 * ResetSavedFrameImg
s16 D_80073E08
s16 D_80073E0A
IMG_BIN ResetTilesImg []
u16 * ResetFrameBufferArray
u16 * nuGfxZBuffer
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RESET_STATE_NONE
RESET_STATE_INIT
RESET_STATE_FADE
Function Documentation
ALIGNED() [1/2]
unsigned char D_800B32E0[0x800] ALIGNED (16)
ALIGNED() [2/2]
u8 nuBootStack[0x2000] ALIGNED (8)
appendGfx_reset_tile_pattern()
void appendGfx_reset_tile_pattern (void)
Referenced by gfxRetrace_Callback().
boot_main()
void boot_main (void * data)
create_audio_system()
void create_audio_system (void)
Referenced by create_audio_system_obfuscated().
gfx_draw_frame()
void gfx_draw_frame (void)
Referenced by gfxRetrace_Callback().
gfx_init_state()
void gfx_init_state (void)
Referenced by appendGfx_reset_tile_pattern().
gfxPreNMI_Callback()
void gfxPreNMI_Callback (void)
Referenced by boot_main().
gfxRetrace_Callback()
void gfxRetrace_Callback (s32 gfxTaskNum)
Referenced by boot_main().
load_engine_data()
void load_engine_data (void)
Referenced by load_engine_data_obfuscated().
Variable Documentation
__osThreadSave
OSThread __osThreadSave
D_80073E08
s16 D_80073E08 extern
Referenced by gfxRetrace_Callback().
D_80073E0A
s16 D_80073E0A extern
Referenced by gfxRetrace_Callback().
D_80074010
s16 D_80074010 = 8
Referenced by appendGfx_reset_tile_pattern().
nuGfxZBuffer
u16* nuGfxZBuffer
Referenced by appendGfx_reset_tile_pattern().
nuYieldBuf
u8 nuYieldBuf[NU_GFX_YIELD_BUF_SIZE]
ResetFrameBufferArray
u16* ResetFrameBufferArray
Referenced by gfxRetrace_Callback().
ResetGameState
s32 ResetGameState extern
Referenced by gfxPreNMI_Callback(), and gfxRetrace_Callback().
ResetSavedFrameImg
u16* ResetSavedFrameImg extern
Referenced by appendGfx_reset_tile_pattern(), and gfxRetrace_Callback().
ResetTilesImg
IMG_BIN ResetTilesImg[] extern
Referenced by appendGfx_reset_tile_pattern().