papermario: include/map.h File Reference
map.h File Reference
Data Structures
struct MapSettings
Fields other than main, entryList, entryCount, background, and tattle are initialised when the map loads.
struct MapConfig
struct AreaConfig
union MapSettings.tattle
Macros
#define EVS_MakeEntities EVS_MakeEntities
#define EVS_SetupMusic EVS_SetupMusic
#define EVS_SetupRooms EVS_SetupRooms
#define EVS_SetupFoliage EVS_SetupFoliage
#define EVS_BindExitTriggers EVS_BindExitTriggers
#define EVS_EnterMap EVS_EnterMap
#define CLONED_MODEL(idx) (10000+(idx))
#define ENTRY_COUNT(entryList) (sizeof(entryList) / sizeof(Vec4f))
#define MAP_ID_MAX_LEN 7
"xxx_yyy" excluding null terminator.
Typedefs
typedef Vec4f EntryList[]
typedef s32(* MapInit) (void)
Functions
MapSettings * get_current_map_settings (void)
Variables
AreaConfig gAreas [29]
Zero-terminated.
EvtScript EVS_NpcHitRecoil
EvtScript EVS_800936C0
Data Structure Documentation
MapSettings
struct MapSettings
Data Fields
BackgroundHeader * background
char ** colliderNameList
s32 entryCount
EntryList * entryList
s32 hitAssetCollisionOffset
s32 hitAssetZoneOffset
EvtScript * main
char ** modelNameList
struct ModelNode * modelTreeRoot
union MapSettings.tattle tattle
char unk_0C[4]
char unk_1C[12]
char unk_34[4]
char ** zoneNameList
MapConfig
struct MapConfig
Data Fields
char * bgName
void * dmaDest
void * dmaEnd
void * dmaStart
char * id
See also
MAP_ID_MAX_LEN
MapInit init Return TRUE to skip normal asset (shape/hit/bg/tex) loading.
MapSettings * settings
s8 sfxReverb
s8 songVariation 0 or 1.
See also
bgm_get_map_default_variation
char unk_1C[0x2]
AreaConfig
struct AreaConfig
Data Fields
char * id "area_xxx"
s32 mapCount
MapConfig * maps
char * name JP debug name.
Macro Definition Documentation
CLONED_MODEL
#define CLONED_MODEL (idx) (10000+(idx))
ENTRY_COUNT
#define ENTRY_COUNT (entryList) (sizeof(entryList) / sizeof(Vec4f))
EVS_BindExitTriggers
#define EVS_BindExitTriggers EVS_BindExitTriggers
Referenced by MAP_RODATA_PAD().
EVS_EnterMap
#define EVS_EnterMap EVS_EnterMap
Referenced by MAP_RODATA_PAD().
EVS_MakeEntities
#define EVS_MakeEntities EVS_MakeEntities
Referenced by MAP_RODATA_PAD().
EVS_SetupFoliage
#define EVS_SetupFoliage EVS_SetupFoliage
Referenced by MAP_RODATA_PAD().
EVS_SetupMusic
#define EVS_SetupMusic EVS_SetupMusic
Referenced by MAP_RODATA_PAD().
EVS_SetupRooms
#define EVS_SetupRooms EVS_SetupRooms
MAP_ID_MAX_LEN
#define MAP_ID_MAX_LEN 7
"xxx_yyy" excluding null terminator.
Typedef Documentation
EntryList
typedef Vec4f EntryList[]
MapInit
typedef s32(* MapInit) (void)
Function Documentation
get_current_map_settings()
MapSettings * get_current_map_settings (void)
Referenced by entity_BlueWarpPipe_set_player_move_to_center(), get_lava_reset_pos(), load_battle_hit_asset(), load_hit_data(), load_map_hit_asset(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
Variable Documentation
EVS_800936C0
EvtScript EVS_800936C0 extern
EVS_NpcHitRecoil
EvtScript EVS_NpcHitRecoil extern
gAreas
AreaConfig gAreas[29] extern
Zero-terminated.
Referenced by bgm_get_map_default_variation(), get_map_IDs_by_name(), load_map_by_IDs(), reset_player_status(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().