papermario: src/evt/map_api.c File Reference
map_api.c File Reference
Functions
ApiStatus TranslateModel (Evt *script, s32 isInitialCall)
ApiStatus RotateModel (Evt *script, s32 isInitialCall)
ApiStatus ScaleModel (Evt *script, s32 isInitialCall)
ApiStatus GetModelIndex (Evt *script, s32 isInitialCall)
ApiStatus InvalidateModelTransform (Evt *script, s32 isInitialCall)
ApiStatus CloneModel (Evt *script, s32 isInitialCall)
ApiStatus GetModelCenter (Evt *script, s32 isInitialCall)
ApiStatus SetTexPanner (Evt *script, s32 isInitialCall)
ApiStatus SetCustomGfxEnabled (Evt *script, s32 isInitialCall)
ApiStatus SetModelCustomGfx (Evt *script, s32 isInitialCall)
ApiStatus SetModelTexVariant (Evt *script, s32 isInitialCall)
ApiStatus EnableTexPanning (Evt *script, s32 isInitialCall)
ApiStatus EnableModel (Evt *script, s32 isInitialCall)
ApiStatus SetGroupVisibility (Evt *script, s32 isInitialCall)
ApiStatus SetTexPanOffset (Evt *script, s32 isInitialCall)
ApiStatus SetCustomGfx (Evt *script, s32 isInitialCall)
ApiStatus SetCustomGfxBuilders (Evt *script, s32 isInitialCall)
ApiStatus SetModelFlags (Evt *script, s32 isInitialCall)
void apply_transform_to_children (ApiStatus(*apiFunc)(Evt *, s32), Evt *script)
ApiStatus MakeTransformGroup (Evt *script, s32 isInitialCall)
ApiStatus SetTransformGroupEnabled (Evt *script, s32 isInitialCall)
ApiStatus TranslateGroup (Evt *script, s32 isInitialCall)
ApiStatus RotateGroup (Evt *script, s32 isInitialCall)
ApiStatus ScaleGroup (Evt *script, s32 isInitialCall)
ApiStatus GetTransformGroup (Evt *script, s32 isInitialCall)
ApiStatus EnableGroup (Evt *script, s32 isInitialCall)
ApiStatus MakeLocalVertexCopy (Evt *script, s32 isInitialCall)
void modify_collider_family_flags (s32 index, s32 flags, s32 mode)
ApiStatus ModifyColliderFlags (Evt *script, s32 isInitialCall)
ApiStatus ResetFromLava (Evt *script, s32 isInitialCall)
s32 get_lava_reset_pos (f32 *outX, f32 *outY, f32 *outZ)
ApiStatus GetColliderCenter (Evt *script, s32 isInitialCall)
ApiStatus ParentColliderToModel (Evt *script, s32 isInitialCall)
ApiStatus UpdateColliderTransform (Evt *script, s32 isInitialCall)
void set_zone_enabled (s32 zoneID, s32 enabled)
ApiStatus SetZoneEnabled (Evt *script, s32 isInitialCall)
void goto_map (Evt *script, s32 mode)
ApiStatus GotoMap (Evt *script, s32 isInitialCall)
ApiStatus GotoMapSpecial (Evt *script, s32 isInitialCall)
ApiStatus GotoMapByID (Evt *script, s32 isInitialCall)
ApiStatus GetEntryID (Evt *script, s32 isInitialCall)
ApiStatus GetMapID (Evt *script, s32 isInitialCall)
ApiStatus GetLoadType (Evt *script, s32 isInitialCall)
ApiStatus SetRenderMode (Evt *script, s32 isInitialCall)
ApiStatus PlaySoundAtModel (Evt *script, s32 isInitialCall)
ApiStatus PlaySoundAtCollider (Evt *script, s32 isInitialCall)
Variables
LavaReset * gLavaResetList
s32 LastSafeFloor
ModelTreeInfoList * gCurrentModelTreeNodeInfo
Function Documentation
apply_transform_to_children()
void apply_transform_to_children (ApiStatus(*)(Evt *, s32) apiFunc, Evt * script)
Referenced by EnableGroup(), RotateGroup(), ScaleGroup(), and TranslateGroup().
CloneModel()
ApiStatus CloneModel (Evt * script, s32 isInitialCall)
EnableGroup()
ApiStatus EnableGroup (Evt * script, s32 isInitialCall)
EnableModel()
ApiStatus EnableModel (Evt * script, s32 isInitialCall)
Referenced by EnableGroup().
EnableTexPanning()
ApiStatus EnableTexPanning (Evt * script, s32 isInitialCall)
get_lava_reset_pos()
s32 get_lava_reset_pos (f32 * outX, f32 * outY, f32 * outZ)
Referenced by action_update_hit_lava().
GetColliderCenter()
ApiStatus GetColliderCenter (Evt * script, s32 isInitialCall)
GetEntryID()
ApiStatus GetEntryID (Evt * script, s32 isInitialCall)
GetLoadType()
ApiStatus GetLoadType (Evt * script, s32 isInitialCall)
GetMapID()
ApiStatus GetMapID (Evt * script, s32 isInitialCall)
GetModelCenter()
ApiStatus GetModelCenter (Evt * script, s32 isInitialCall)
GetModelIndex()
ApiStatus GetModelIndex (Evt * script, s32 isInitialCall)
GetTransformGroup()
ApiStatus GetTransformGroup (Evt * script, s32 isInitialCall)
goto_map()
void goto_map (Evt * script, s32 mode)
Referenced by GotoMap(), GotoMapByID(), and GotoMapSpecial().
GotoMap()
ApiStatus GotoMap (Evt * script, s32 isInitialCall)
GotoMapByID()
ApiStatus GotoMapByID (Evt * script, s32 isInitialCall)
GotoMapSpecial()
ApiStatus GotoMapSpecial (Evt * script, s32 isInitialCall)
InvalidateModelTransform()
ApiStatus InvalidateModelTransform (Evt * script, s32 isInitialCall)
MakeLocalVertexCopy()
ApiStatus MakeLocalVertexCopy (Evt * script, s32 isInitialCall)
MakeTransformGroup()
ApiStatus MakeTransformGroup (Evt * script, s32 isInitialCall)
modify_collider_family_flags()
void modify_collider_family_flags (s32 index, s32 flags, s32 mode)
Referenced by modify_collider_family_flags(), ModifyColliderFlags(), and ResetFromLava().
ModifyColliderFlags()
ApiStatus ModifyColliderFlags (Evt * script, s32 isInitialCall)
ParentColliderToModel()
ApiStatus ParentColliderToModel (Evt * script, s32 isInitialCall)
PlaySoundAtCollider()
ApiStatus PlaySoundAtCollider (Evt * script, s32 isInitialCall)
PlaySoundAtModel()
ApiStatus PlaySoundAtModel (Evt * script, s32 isInitialCall)
ResetFromLava()
ApiStatus ResetFromLava (Evt * script, s32 isInitialCall)
RotateGroup()
ApiStatus RotateGroup (Evt * script, s32 isInitialCall)
RotateModel()
ApiStatus RotateModel (Evt * script, s32 isInitialCall)
Referenced by RotateGroup().
ScaleGroup()
ApiStatus ScaleGroup (Evt * script, s32 isInitialCall)
ScaleModel()
ApiStatus ScaleModel (Evt * script, s32 isInitialCall)
Referenced by ScaleGroup().
set_zone_enabled()
void set_zone_enabled (s32 zoneID, s32 enabled)
Referenced by set_zone_enabled(), and SetZoneEnabled().
SetCustomGfx()
ApiStatus SetCustomGfx (Evt * script, s32 isInitialCall)
SetCustomGfxBuilders()
ApiStatus SetCustomGfxBuilders (Evt * script, s32 isInitialCall)
SetCustomGfxEnabled()
ApiStatus SetCustomGfxEnabled (Evt * script, s32 isInitialCall)
SetGroupVisibility()
ApiStatus SetGroupVisibility (Evt * script, s32 isInitialCall)
SetModelCustomGfx()
ApiStatus SetModelCustomGfx (Evt * script, s32 isInitialCall)
SetModelFlags()
ApiStatus SetModelFlags (Evt * script, s32 isInitialCall)
SetModelTexVariant()
ApiStatus SetModelTexVariant (Evt * script, s32 isInitialCall)
SetRenderMode()
ApiStatus SetRenderMode (Evt * script, s32 isInitialCall)
SetTexPanner()
ApiStatus SetTexPanner (Evt * script, s32 isInitialCall)
SetTexPanOffset()
ApiStatus SetTexPanOffset (Evt * script, s32 isInitialCall)
SetTransformGroupEnabled()
ApiStatus SetTransformGroupEnabled (Evt * script, s32 isInitialCall)
SetZoneEnabled()
ApiStatus SetZoneEnabled (Evt * script, s32 isInitialCall)
TranslateGroup()
ApiStatus TranslateGroup (Evt * script, s32 isInitialCall)
TranslateModel()
ApiStatus TranslateModel (Evt * script, s32 isInitialCall)
Referenced by TranslateGroup().
UpdateColliderTransform()
ApiStatus UpdateColliderTransform (Evt * script, s32 isInitialCall)
Variable Documentation
gCurrentModelTreeNodeInfo
ModelTreeInfoList* gCurrentModelTreeNodeInfo extern
Referenced by appendGfx_model_group(), clear_model_data(), init_model_data(), load_texture_by_name(), mdl_group_set_custom_gfx(), and mdl_group_set_visibility().
gLavaResetList
LavaReset* gLavaResetList extern
Referenced by get_lava_reset_pos(), and ResetFromLava().
LastSafeFloor
s32 LastSafeFloor extern
Referenced by get_lava_reset_pos(), and ResetFromLava().