papermario: src/world/common/enemy/ai/MeleeHitbox.inc.c File Reference
MeleeHitbox.inc.c File Reference
Macros
#define _AI_MELEE_HITBOX_INC_ 0
Functions
void MeleeHitbox_30 (Evt *script)
void MeleeHitbox_31 (Evt *script)
void MeleeHitbox_32 (Evt *script)
void MeleeHitbox_33 (Evt *script)
s32 MeleeHitbox_CanSeePlayer (Evt *script)
Macro Definition Documentation
_AI_MELEE_HITBOX_INC_
#define _AI_MELEE_HITBOX_INC_ 0
Function Documentation
MeleeHitbox_30()
void MeleeHitbox_30 (Evt * script)
Referenced by SpearGuyAI_Main(), and WanderMeleeAI_Main().
MeleeHitbox_31()
void MeleeHitbox_31 (Evt * script)
Referenced by SpearGuyAI_Main(), and WanderMeleeAI_Main().
MeleeHitbox_32()
void MeleeHitbox_32 (Evt * script)
Referenced by SpearGuyAI_Main(), and WanderMeleeAI_Main().
MeleeHitbox_33()
void MeleeHitbox_33 (Evt * script)
Referenced by SpearGuyAI_Main(), and WanderMeleeAI_Main().
MeleeHitbox_CanSeePlayer()
s32 MeleeHitbox_CanSeePlayer (Evt * script)
Referenced by SpearGuyAI_Main(), and WanderMeleeAI_Main().