papermario: src/world/menus.c File Reference
menus.c File Reference
Enumerations
enum WorldMenuStates {
WORLD_MENU_STATE_NONE = 0 , WORLD_MENU_STATE_DELAY = 1 , WORLD_MENU_STATE_OPEN = 2 , WORLD_MENU_STATE_HOLD = 3 ,
WORLD_MENU_STATE_CLOSE = 4 , WORLD_MENU_STATE_UNPAUSE = 10
}
enum WorldMenuTypes { WORLD_MENU_CHANGE_PARTNER = 0 , WORLD_MENU_USE_ITEM = 1 , WORLD_MENU_PAUSE = 2 }
Functions
void reset_outta_sight_alpha_on_menu_close (void)
b32 should_cancel_open_world_menu (void)
b32 can_open_world_menu (s32 currentButtons, s32 pressedButtons)
void clear_world_menus (void)
s32 setup_partner_popup (PopupMenu *menu)
s32 setup_item_popup (PopupMenu *menu)
void check_input_open_menus (void)
void check_input_status_bar (void)
Variables
BSS s32 D_8010C9C4
BSS PopupMenu WorldPopupMenu
BSS s16 WorldMenuType
BSS s16 WorldMenuDelay
BSS s16 WorldPopupResult
BSS s16 OpenMenuDisableCount
BSS s16 WorldMenuState
s32 MenuIndexFromPartnerID []
Enumeration Type Documentation
WorldMenuStates
enum WorldMenuStates
Enumerator
WORLD_MENU_STATE_NONE
WORLD_MENU_STATE_DELAY
WORLD_MENU_STATE_OPEN
WORLD_MENU_STATE_HOLD
WORLD_MENU_STATE_CLOSE
WORLD_MENU_STATE_UNPAUSE
WorldMenuTypes
enum WorldMenuTypes
Enumerator
WORLD_MENU_CHANGE_PARTNER
WORLD_MENU_USE_ITEM
WORLD_MENU_PAUSE
Function Documentation
can_open_world_menu()
b32 can_open_world_menu (s32 currentButtons, s32 pressedButtons)
Referenced by check_input_open_menus().
check_input_open_menus()
void check_input_open_menus (void)
Referenced by update_player().
check_input_status_bar()
void check_input_status_bar (void)
Referenced by update_player().
clear_world_menus()
void clear_world_menus (void)
Referenced by player_reset_data().
reset_outta_sight_alpha_on_menu_close()
void reset_outta_sight_alpha_on_menu_close (void)
Referenced by check_input_open_menus().
setup_item_popup()
s32 setup_item_popup (PopupMenu * menu)
Referenced by check_input_open_menus().
setup_partner_popup()
s32 setup_partner_popup (PopupMenu * menu)
Referenced by check_input_open_menus().
should_cancel_open_world_menu()
b32 should_cancel_open_world_menu (void)
Referenced by check_input_open_menus().
Variable Documentation
D_8010C9C4
BSS s32 D_8010C9C4
MenuIndexFromPartnerID
s32 MenuIndexFromPartnerID[] extern
Referenced by check_input_open_menus().
OpenMenuDisableCount
BSS s16 OpenMenuDisableCount
Referenced by check_input_open_menus().
WorldMenuDelay
BSS s16 WorldMenuDelay
Referenced by check_input_open_menus().
WorldMenuState
BSS s16 WorldMenuState
Referenced by check_input_open_menus(), and clear_world_menus().
WorldMenuType
BSS s16 WorldMenuType
Referenced by check_input_open_menus().
WorldPopupMenu
BSS PopupMenu WorldPopupMenu
Referenced by check_input_open_menus().
WorldPopupResult
BSS s16 WorldPopupResult
Referenced by check_input_open_menus().