papermario: src/effects/merlin_house_stars.c File Reference
merlin_house_stars.c File Reference
Macros
#define PM_CC1_MERLIN_STARS 0, 0, 0, 1, TEXEL1, 0, PRIMITIVE, TEXEL0
#define PM_CC2_MERLIN_STARS 0, 0, 0, COMBINED, COMBINED, 0, ENVIRONMENT, 0
Functions
void merlin_house_stars_init (EffectInstance *effect)
void merlin_house_stars_update (EffectInstance *effect)
void merlin_house_stars_render (EffectInstance *effect)
void merlin_house_stars_appendGfx (void *effect)
EffectInstance * merlin_house_stars_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
void func_E00A639C (void)
Variables
Gfx D_09001000_3A6BE0 []
Gfx D_09001418_3A6FF8 []
Macro Definition Documentation
PM_CC1_MERLIN_STARS
#define PM_CC1_MERLIN_STARS 0, 0, 0, 1, TEXEL1, 0, PRIMITIVE, TEXEL0
Referenced by merlin_house_stars_appendGfx().
PM_CC2_MERLIN_STARS
#define PM_CC2_MERLIN_STARS 0, 0, 0, COMBINED, COMBINED, 0, ENVIRONMENT, 0
Referenced by merlin_house_stars_appendGfx().
Function Documentation
func_E00A639C()
void func_E00A639C (void)
merlin_house_stars_appendGfx()
void merlin_house_stars_appendGfx (void * effect)
Referenced by merlin_house_stars_render().
merlin_house_stars_init()
void merlin_house_stars_init (EffectInstance * effect)
Referenced by merlin_house_stars_main().
merlin_house_stars_main()
EffectInstance * merlin_house_stars_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
merlin_house_stars_render()
void merlin_house_stars_render (EffectInstance * effect)
Referenced by merlin_house_stars_main().
merlin_house_stars_update()
void merlin_house_stars_update (EffectInstance * effect)
Referenced by merlin_house_stars_main().
Variable Documentation
D_09001000_3A6BE0
Gfx D_09001000_3A6BE0[] extern
Referenced by merlin_house_stars_appendGfx().
D_09001418_3A6FF8
Gfx D_09001418_3A6FF8[] extern
Referenced by merlin_house_stars_appendGfx().