papermario: src/world/area_mgm/mgm_00/mgm_00.h File Reference
mgm_00.h File Reference
Minigame - Playroom Lobby.
Macros
#define NAMESPACE mgm_00
Enumerations
enum { NPC_RedToad = 0 , NPC_GreenToad = 1 , NPC_BlueToad = 2 }
enum { MV_RecordDisplayData = MapVar(10) }
Functions
void msg_draw_frame (s32 posX, s32 posY, s32 sizeX, s32 sizeY, s32 style, s32 palette, s32 fading, s32 bgAlpha, s32 frameAlpha)
Variables
EvtScript EVS_Main
EvtScript D_80243C40_E123E0
EvtScript EVS_BindInteractTriggers
EvtScript EVS_OnEnterPipe_JumpAttack
EvtScript EVS_OnEnterPipe_SmashAttack
NpcGroupList DefaultNPCs
Macro Definition Documentation
NAMESPACE
#define NAMESPACE mgm_00
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NPC_RedToad
NPC_GreenToad
NPC_BlueToad
anonymous enum
anonymous enum
Enumerator
MV_RecordDisplayData
Function Documentation
msg_draw_frame()
void msg_draw_frame (s32 posX, s32 posY, s32 sizeX, s32 sizeY, s32 style, s32 palette, s32 fading, s32 bgAlpha, s32 frameAlpha)
Referenced by appendGfx_message(), appendGfx_records_impl(), and draw_record_display().
Variable Documentation
D_80243C40_E123E0
EvtScript D_80243C40_E123E0 extern
DefaultNPCs
NpcGroupList DefaultNPCs extern
EVS_BindInteractTriggers
EvtScript EVS_BindInteractTriggers extern
EVS_Main
EvtScript EVS_Main extern
EVS_OnEnterPipe_JumpAttack
EvtScript EVS_OnEnterPipe_JumpAttack extern
EVS_OnEnterPipe_SmashAttack
EvtScript EVS_OnEnterPipe_SmashAttack extern