papermario: src/world/area_mgm/mgm_02/mgm_02_2_npc.c File Reference
mgm_02_2_npc.c File Reference
Data Structures
struct SmashGameBoxData
struct SmashGameData
Macros
#define SCOREKEEPER_ENEMY_IDX 0
#define SMASH_DATA_VAR_IDX 0
#define PLAY_COST 10
#define PLAY_TIME ((s32)(900 * DT))
#define FRAME_RATE ((s32)(30 * DT))
#define NUM_BOXES 35
#define NUM_PANELS 10
#define SMASH_DATA_VAR_IDX 0
#define SMASH_DATA_VAR_IDX 0
#define FUZZY_NPC_ID_BASE NPC_Fuzzy_01
#define BOBOMB_NPC_ID_BASE NPC_Bobomb_01
#define LUIGI_NPC_ID_BASE NPC_Luigi_01
#define TEXT_POS_Y 28
#define COUNT_POS_Y 43
Enumerations
enum SmashGameBoxCotent { BOX_CONTENT_FUZZY = 0 , BOX_CONTENT_BOMB = 1 , BOX_CONTENT_PEACH = 2 , BOX_CONTENT_EMPTY = 3 }
enum SmashGameStunFlags { STUN_FLAG_STUNNED = 1 , STUN_FLAG_CHANGED = 2 , STUN_FLAG_GRABBED = 4 }
enum SmashGameBoxState {
BOX_STATE_FUZZY_INIT = 10 , BOX_STATE_FUZZY_IDLE = 11 , BOX_STATE_FUZZY_POPUP = 12 , BOX_STATE_FUZZY_HIT = 13 ,
BOX_STATE_FUZZY_ATTACH = 14 , BOX_STATE_FUZZY_GRAB = 15 , BOX_STATE_FUZZY_DETACH = 16 , BOX_STATE_FUZZY_DONE = 17 ,
BOX_STATE_FUZZY_END = 18 , BOX_STATE_BOMB_INIT = 30 , BOX_STATE_BOMB_IDLE = 31 , BOX_STATE_BOMB_POPUP = 32 ,
BOX_STATE_BOMB_HIT = 33 , BOX_STATE_BOMB_ATTACK = 34 , BOX_STATE_BOMB_STUN = 35 , BOX_STATE_BOMB_DONE = 36 ,
BOX_STATE_BOMB_END = 37 , BOX_STATE_EMPTY_INIT = 50 , BOX_STATE_EMPTY_IDLE = 51 , BOX_STATE_EMPTY_HIT = 52 ,
BOX_STATE_PEACH_INIT = 70 , BOX_STATE_PEACH_IDLE = 71 , BOX_STATE_PEACH_POPUP = 72 , BOX_STATE_PEACH_HIT = 73 ,
BOX_STATE_PEACH_EMERGE = 74 , BOX_STATE_PEACH_DONE = 75
}
Functions
void delete_entity (s32)
void partner_enable_input (void)
void appendGfx_score_display (void *renderData)
void worker_draw_score (void)
Variables
HudScript HES_BlueMeter
HudScript HES_AButton
HudScript HES_MashAButton
s32 InitialConfigurations [3][NUM_BOXES]
s32 BoxModelIDs [NUM_BOXES]
s32 BoxColliderIDs [NUM_BOXES]
s32 PanelModelIDs [NUM_PANELS]
BSS s32 D_80248600 [NUM_PANELS]
IMG_BIN panel_peach_img
PAL_BIN panel_peach_pal
EvtScript read_sign_instructions
EvtScript EVS_Dummy
EvtScript EVS_CreateScoreDisplay
EvtScript EVS_ShowBox
EvtScript EVS_MakeBoxAppear
EvtScript EVS_HideBox
EvtScript EVS_HideBoxWithSmoke
EvtScript EVS_HideAllBoxes
EvtScript EVS_HideAllBoxesWithSmoke
EvtScript EVS_MakeAllBoxesAppear
EvtScript EVS_HidePeachPanels
EvtScript EVS_OnHitBox
EvtScript D_802441E4_E19F64
EvtScript EVS_SetBoxContents
EvtScript EVS_CleanupGame
EvtScript EVS_Toad_GovernGame
EvtScript EVS_InitializeMinigame
EvtScript EVS_DestroyMinigame
EvtScript EVS_NpcInteract_Toad
EvtScript EVS_NpcInit_Toad
NpcData NpcData_GuideToad
EvtScript EVS_NpcInit_Fuzzy
EvtScript EVS_NpcInit_Bobomb
EvtScript EVS_NpcInit_Luigi
NpcData NpcData_Fuzzy_01
NpcData NpcData_Fuzzy_02
NpcData NpcData_Fuzzy_03
NpcData NpcData_Fuzzy_04
NpcData NpcData_Fuzzy_05
NpcData NpcData_Bobomb_01
NpcData NpcData_Bobomb_02
NpcData NpcData_Bobomb_03
NpcData NpcData_Bobomb_04
NpcData NpcData_Bobomb_05
NpcData NpcData_Luigis []
NpcGroupList DefaultNPCs
Data Structure Documentation
SmashGameBoxData
struct SmashGameBoxData
Data Fields
s32 colliderID
s32 content
s32 modelID
s32 npcID
s32 peachPanelModelID
SmashGameBoxState state
s32 stateTimer
SmashGameData
struct SmashGameData
Data Fields
SmashGameBoxData box[NUM_BOXES]
s32 curScore
s32 found
s32 hudElemID_AButton
s32 hudElemID_Meter
s32 mashProgress
s32 signpostEntity
SmashGameStunFlags stunFlags
s32 timeLeft
s32 windowA_posX
s32 windowB_posX
s32 workerID
Macro Definition Documentation
BOBOMB_NPC_ID_BASE
#define BOBOMB_NPC_ID_BASE NPC_Bobomb_01
COUNT_POS_Y
#define COUNT_POS_Y 43
Referenced by appendGfx_score_display().
FRAME_RATE
#define FRAME_RATE ((s32)(30 * DT))
Referenced by appendGfx_score_display().
FUZZY_NPC_ID_BASE
#define FUZZY_NPC_ID_BASE NPC_Fuzzy_01
LUIGI_NPC_ID_BASE
#define LUIGI_NPC_ID_BASE NPC_Luigi_01
NUM_BOXES
#define NUM_BOXES 35
NUM_PANELS
#define NUM_PANELS 10
Referenced by appendGfx_score_display().
PLAY_COST
#define PLAY_COST 10
PLAY_TIME
#define PLAY_TIME ((s32)(900 * DT))
Referenced by appendGfx_score_display().
SCOREKEEPER_ENEMY_IDX
#define SCOREKEEPER_ENEMY_IDX 0
Referenced by appendGfx_score_display().
SMASH_DATA_VAR_IDX [1/3]
#define SMASH_DATA_VAR_IDX 0
Referenced by appendGfx_score_display().
SMASH_DATA_VAR_IDX [2/3]
#define SMASH_DATA_VAR_IDX 0
SMASH_DATA_VAR_IDX [3/3]
#define SMASH_DATA_VAR_IDX 0
TEXT_POS_Y
#define TEXT_POS_Y 28
Referenced by appendGfx_score_display().
Enumeration Type Documentation
SmashGameBoxCotent
enum SmashGameBoxCotent
Enumerator
BOX_CONTENT_FUZZY
BOX_CONTENT_BOMB
BOX_CONTENT_PEACH
BOX_CONTENT_EMPTY
SmashGameBoxState
enum SmashGameBoxState
Enumerator
BOX_STATE_FUZZY_INIT
BOX_STATE_FUZZY_IDLE
BOX_STATE_FUZZY_POPUP
BOX_STATE_FUZZY_HIT
BOX_STATE_FUZZY_ATTACH
BOX_STATE_FUZZY_GRAB
BOX_STATE_FUZZY_DETACH
BOX_STATE_FUZZY_DONE
BOX_STATE_FUZZY_END
BOX_STATE_BOMB_INIT
BOX_STATE_BOMB_IDLE
BOX_STATE_BOMB_POPUP
BOX_STATE_BOMB_HIT
BOX_STATE_BOMB_ATTACK
BOX_STATE_BOMB_STUN
BOX_STATE_BOMB_DONE
BOX_STATE_BOMB_END
BOX_STATE_EMPTY_INIT
BOX_STATE_EMPTY_IDLE
BOX_STATE_EMPTY_HIT
BOX_STATE_PEACH_INIT
BOX_STATE_PEACH_IDLE
BOX_STATE_PEACH_POPUP
BOX_STATE_PEACH_HIT
BOX_STATE_PEACH_EMERGE
BOX_STATE_PEACH_DONE
SmashGameStunFlags
enum SmashGameStunFlags
Enumerator
STUN_FLAG_STUNNED
STUN_FLAG_CHANGED
STUN_FLAG_GRABBED
Function Documentation
appendGfx_score_display()
void appendGfx_score_display (void * renderData)
Referenced by worker_draw_score().
delete_entity()
void delete_entity (s32 entityIndex)
Referenced by update_entities().
partner_enable_input()
void partner_enable_input (void)
Referenced by check_input_open_menus(), CloseChoicePopup(), DisablePlayerInput(), SentinelAI_GrabPlayer(), update_encounters_conversation(), update_encounters_post_battle(), and update_item_entity_pickup().
worker_draw_score()
void worker_draw_score (void)
Variable Documentation
BoxColliderIDs
s32 BoxColliderIDs
Initial value:
= {
    COLLIDER_a1, COLLIDER_b1, COLLIDER_c1, COLLIDER_d1, COLLIDER_e1, COLLIDER_f1, COLLIDER_g1,
    COLLIDER_a2, COLLIDER_b2, COLLIDER_c2, COLLIDER_d2, COLLIDER_e2, COLLIDER_f2, COLLIDER_g2,
    COLLIDER_a3, COLLIDER_b3, COLLIDER_c3, COLLIDER_d3, COLLIDER_e3, COLLIDER_f3, COLLIDER_g3,
    COLLIDER_a4, COLLIDER_b4, COLLIDER_c4, COLLIDER_d4, COLLIDER_e4, COLLIDER_f4, COLLIDER_g4,
    COLLIDER_a5, COLLIDER_b5, COLLIDER_c5, COLLIDER_d5, COLLIDER_e5, COLLIDER_f5, COLLIDER_g5,
}
BoxModelIDs
s32 BoxModelIDs
Initial value:
= {
    MODEL_a1, MODEL_b1, MODEL_c1, MODEL_d1, MODEL_e1, MODEL_f1, MODEL_g1,
    MODEL_a2, MODEL_b2, MODEL_c2, MODEL_d2, MODEL_e2, MODEL_f2, MODEL_g2,
    MODEL_a3, MODEL_b3, MODEL_c3, MODEL_d3, MODEL_e3, MODEL_f3, MODEL_g3,
    MODEL_a4, MODEL_b4, MODEL_c4, MODEL_d4, MODEL_e4, MODEL_f4, MODEL_g4,
    MODEL_a5, MODEL_b5, MODEL_c5, MODEL_d5, MODEL_e5, MODEL_f5, MODEL_g5,
}
D_802441E4_E19F64
EvtScript D_802441E4_E19F64
D_80248600
BSS s32 D_80248600[NUM_PANELS]
DefaultNPCs
NpcGroupList DefaultNPCs
Initial value:
= {
    NPC_GROUP( NpcData_GuideToad ),
    NPC_GROUP( NpcData_Fuzzy_01 ),
    NPC_GROUP( NpcData_Fuzzy_02 ),
    NPC_GROUP( NpcData_Fuzzy_03 ),
    NPC_GROUP( NpcData_Fuzzy_04 ),
    NPC_GROUP( NpcData_Fuzzy_05 ),
    NPC_GROUP( NpcData_Bobomb_01 ),
    NPC_GROUP( NpcData_Bobomb_02 ),
    NPC_GROUP( NpcData_Bobomb_03 ),
    NPC_GROUP( NpcData_Bobomb_04 ),
    NPC_GROUP( NpcData_Bobomb_05 ),
    NPC_GROUP( NpcData_Luigis ),
    {}
}
EVS_CleanupGame
EvtScript EVS_CleanupGame
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_CreateScoreDisplay
EvtScript EVS_CreateScoreDisplay
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_DestroyMinigame
EvtScript EVS_DestroyMinigame
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_Dummy
EvtScript EVS_Dummy
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_HideAllBoxes
EvtScript EVS_HideAllBoxes
EVS_HideAllBoxesWithSmoke
EvtScript EVS_HideAllBoxesWithSmoke
EVS_HideBox
EvtScript EVS_HideBox
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_HideBoxWithSmoke
EvtScript EVS_HideBoxWithSmoke
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_HidePeachPanels
EvtScript EVS_HidePeachPanels
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_InitializeMinigame
EvtScript EVS_InitializeMinigame
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_MakeAllBoxesAppear
EvtScript EVS_MakeAllBoxesAppear
EVS_MakeBoxAppear
EvtScript EVS_MakeBoxAppear
Initial value:
= {
    EVT_END_LOOP
    EVT_RETURN
    EVT_END
}
EVS_NpcInit_Bobomb
EvtScript EVS_NpcInit_Bobomb
Initial value:
= {
        EVT_CASE_DEFAULT
    EVT_END_SWITCH
    EVT_ELSE
    EVT_END_IF
    EVT_RETURN
    EVT_END
}
EVS_NpcInit_Fuzzy
EvtScript EVS_NpcInit_Fuzzy
Initial value:
= {
        EVT_CASE_DEFAULT
    EVT_END_SWITCH
    EVT_ELSE
    EVT_END_IF
    EVT_RETURN
    EVT_END
}
EVS_NpcInit_Luigi
EvtScript EVS_NpcInit_Luigi
Initial value:
= {
    EVT_ELSE
    EVT_END_IF
    EVT_RETURN
    EVT_END
}
EVS_NpcInit_Toad
EvtScript EVS_NpcInit_Toad
Initial value:
= {
    EVT_CALL(BindNpcInteract, NPC_SELF, EVT_PTR( EVS_NpcInteract_Toad ))
    EVT_RETURN
    EVT_END
}
EVS_NpcInteract_Toad
EvtScript EVS_NpcInteract_Toad
EVS_OnHitBox
EvtScript EVS_OnHitBox
EVS_SetBoxContents
EvtScript EVS_SetBoxContents
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_ShowBox
EvtScript EVS_ShowBox
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_Toad_GovernGame
EvtScript EVS_Toad_GovernGame
HES_AButton
HudScript HES_AButton extern
HES_BlueMeter
HudScript HES_BlueMeter extern
HES_MashAButton
HudScript HES_MashAButton extern
InitialConfigurations
s32 InitialConfigurations[3][NUM_BOXES]
Initial value:
= {
    { 2, 0, 2, 0, 2, 3, 3, 3, 3, 3, 2, 3, 2, 1, 3, 3, 2, 3, 0, 3, 3, 2, 3, 3, 1, 2, 3, 3, 2, 3, 3, 1, 3, 3, 2 },
    { 2, 0, 2, 1, 2, 3, 2, 3, 3, 3, 3, 1, 3, 2, 3, 0, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 1, 0, 3, 2, 3, 3, 2, 3, 2 },
    { 3, 3, 0, 3, 3, 1, 0, 1, 2, 3, 3, 3, 2, 3, 0, 3, 2, 2, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 3, 3, 2, 3, 1, 3, 3 },
}
NpcData_Bobomb_01
NpcData NpcData_Bobomb_01
Initial value:
= {
    .id = NPC_Bobomb_01,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Bobomb ,
    .settings = & NpcSettings_Bobomb ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = BOBOMB_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Bobomb_02
NpcData NpcData_Bobomb_02
Initial value:
= {
    .id = NPC_Bobomb_02,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Bobomb ,
    .settings = & NpcSettings_Bobomb ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = BOBOMB_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Bobomb_03
NpcData NpcData_Bobomb_03
Initial value:
= {
    .id = NPC_Bobomb_03,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Bobomb ,
    .settings = & NpcSettings_Bobomb ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = BOBOMB_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Bobomb_04
NpcData NpcData_Bobomb_04
Initial value:
= {
    .id = NPC_Bobomb_04,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Bobomb ,
    .settings = & NpcSettings_Bobomb ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = BOBOMB_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Bobomb_05
NpcData NpcData_Bobomb_05
Initial value:
= {
    .id = NPC_Bobomb_05,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Bobomb ,
    .settings = & NpcSettings_Bobomb ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = BOBOMB_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Fuzzy_01
NpcData NpcData_Fuzzy_01
Initial value:
= {
    .id = NPC_Fuzzy_01,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Fuzzy ,
    .settings = & NpcSettings_Fuzzy ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = FUZZY_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Fuzzy_02
NpcData NpcData_Fuzzy_02
Initial value:
= {
    .id = NPC_Fuzzy_02,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Fuzzy ,
    .settings = & NpcSettings_Fuzzy ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = FUZZY_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Fuzzy_03
NpcData NpcData_Fuzzy_03
Initial value:
= {
    .id = NPC_Fuzzy_03,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Fuzzy ,
    .settings = & NpcSettings_Fuzzy ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = FUZZY_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Fuzzy_04
NpcData NpcData_Fuzzy_04
Initial value:
= {
    .id = NPC_Fuzzy_04,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Fuzzy ,
    .settings = & NpcSettings_Fuzzy ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = FUZZY_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Fuzzy_05
NpcData NpcData_Fuzzy_05
Initial value:
= {
    .id = NPC_Fuzzy_05,
    .pos = { NPC_DISPOSE_LOCATION },
    .yaw = 0,
    .init = & EVS_NpcInit_Fuzzy ,
    .settings = & NpcSettings_Fuzzy ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_PLAYER_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_ACTIVE_WHILE_OFFSCREEN | ENEMY_FLAG_IGNORE_TOUCH | ENEMY_FLAG_IGNORE_JUMP | ENEMY_FLAG_IGNORE_HAMMER | ENEMY_FLAG_CANT_INTERACT | ENEMY_FLAG_IGNORE_PARTNER | ENEMY_FLAG_IGNORE_SPIN,
    .drops = NO_DROPS,
    .animations = FUZZY_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_GuideToad
NpcData NpcData_GuideToad
Initial value:
= {
    .id = NPC_Toad,
    .pos = { 353.0f, -20.0f, 185.0f },
    .yaw = 270,
    .init = & EVS_NpcInit_Toad ,
    .settings = & NpcSettings_Toad_Stationary ,
    .flags = ENEMY_FLAG_PASSIVE | ENEMY_FLAG_IGNORE_WORLD_COLLISION | ENEMY_FLAG_IGNORE_ENTITY_COLLISION | ENEMY_FLAG_FLYING | ENEMY_FLAG_NO_SHADOW_RAYCAST,
    .drops = NO_DROPS,
    .animations = TOAD_RED_ANIMS,
    .tattle = MSG_NpcTattle_MGM_SmashAttackGuide,
}
NpcData_Luigis
NpcData NpcData_Luigis[]
panel_peach_img
IMG_BIN panel_peach_img extern
Referenced by appendGfx_score_display().
panel_peach_pal
PAL_BIN panel_peach_pal extern
Referenced by appendGfx_score_display().
PanelModelIDs
s32 PanelModelIDs[NUM_PANELS]
Initial value:
= {
    MODEL_o50, MODEL_o51, MODEL_o52, MODEL_o53, MODEL_o54,
    MODEL_o55, MODEL_o56, MODEL_o57, MODEL_o58, MODEL_o59
}
read_sign_instructions
EvtScript read_sign_instructions
Initial value:
= {
    EVT_RETURN
    EVT_END
}