papermario: src/effects/misc_particles.c File Reference
misc_particles.c File Reference
Functions
void misc_particles_init (EffectInstance *effect)
void misc_particles_update (EffectInstance *effect)
void misc_particles_render (EffectInstance *effect)
void misc_particles_appendGfx (void *effect)
EffectInstance * misc_particles_main (s32 variation, f32 posX, f32 posY, f32 posZ, f32 scaleX, f32 scaleY, f32 arg6, s32 numParticles, s32 duration)
void func_E00E4954 (void)
Variables
Gfx D_09001580_3E03E0 []
Gfx D_09001670_3E04D0 []
Gfx D_09001768_3E05C8 []
Gfx D_09001818_3E0678 []
Gfx D_09001A20_3E0880 []
Gfx D_09001A40_3E08A0 []
Gfx D_09001A60_3E08C0 []
Gfx D_09001A80_3E08E0 []
Gfx * D_E00E4D90 []
Gfx * D_E00E4DA8 []
u8 D_E00E4DC0 []
u8 D_E00E4DE0 []
u8 D_E00E4E00 []
Function Documentation
func_E00E4954()
void func_E00E4954 (void)
misc_particles_appendGfx()
void misc_particles_appendGfx (void * effect)
Referenced by misc_particles_render().
misc_particles_init()
void misc_particles_init (EffectInstance * effect)
Referenced by misc_particles_main().
misc_particles_main()
EffectInstance * misc_particles_main (s32 variation, f32 posX, f32 posY, f32 posZ, f32 scaleX, f32 scaleY, f32 arg6, s32 numParticles, s32 duration)
Referenced by ice_pillar_main(), snowman_doll_update(), and spirit_card_main().
misc_particles_render()
void misc_particles_render (EffectInstance * effect)
Referenced by misc_particles_main().
misc_particles_update()
void misc_particles_update (EffectInstance * effect)
Referenced by misc_particles_main().
Variable Documentation
D_09001580_3E03E0
Gfx D_09001580_3E03E0[] extern
D_09001670_3E04D0
Gfx D_09001670_3E04D0[] extern
D_09001768_3E05C8
Gfx D_09001768_3E05C8[] extern
D_09001818_3E0678
Gfx D_09001818_3E0678[] extern
D_09001A20_3E0880
Gfx D_09001A20_3E0880[] extern
D_09001A40_3E08A0
Gfx D_09001A40_3E08A0[] extern
D_09001A60_3E08C0
Gfx D_09001A60_3E08C0[] extern
D_09001A80_3E08E0
Gfx D_09001A80_3E08E0[] extern
D_E00E4D90
Gfx* D_E00E4D90[]
Initial value:
= {
    D_09001A20_3E0880, D_09001A40_3E08A0, D_09001A60_3E08C0,
    D_09001A60_3E08C0, D_09001A80_3E08E0, D_09001A80_3E08E0
}
Referenced by misc_particles_appendGfx().
D_E00E4DA8
Gfx* D_E00E4DA8[]
Initial value:
= {
    D_09001580_3E03E0, D_09001670_3E04D0, D_09001768_3E05C8,
    D_09001768_3E05C8, D_09001818_3E0678, D_09001818_3E0678
}
Referenced by misc_particles_appendGfx().
D_E00E4DC0
u8 D_E00E4DC0[]
Initial value:
= {
    0x02, 0x04, 0x08, 0x0D, 0x0F, 0x0D, 0x09, 0x06, 0x04, 0x03,
    0x02, 0x04, 0x08, 0x0D, 0x0F, 0x0D, 0x09, 0x06, 0x04, 0x03,
    0x02, 0x04, 0x08, 0x0D, 0x0F, 0x0D, 0x09, 0x06, 0x04, 0x03
}
Referenced by misc_particles_update().
D_E00E4DE0
u8 D_E00E4DE0[]
Initial value:
= {
    0x28, 0x5A, 0x51, 0x48, 0x41, 0x3B, 0x35, 0x2F, 0x2B, 0x26,
    0x22, 0x1F, 0x1C, 0x19, 0x16, 0x14, 0x12, 0x10, 0x0F, 0x0D,
    0x0C, 0x0A, 0x09, 0x08, 0x07, 0x07, 0x06, 0x05, 0x05, 0x04
}
Referenced by misc_particles_update().
D_E00E4E00
u8 D_E00E4E00[]
Initial value:
= {
    0xC8, 0xFA, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFA, 0xC8
}
Referenced by misc_particles_update().