papermario: src/evt/model_api.c File Reference
model_api.c File Reference
Functions
void update_animated_models (void)
void render_animated_models (void)
void reset_model_animators (void)
void init_model_animators (void)
Variables
AnimatedModelList gBattleMeshAnimationList
AnimatedModelList gWorldMeshAnimationList
AnimatedModelList * gCurrentMeshAnimationListPtr
Function Documentation
init_model_animators()
void init_model_animators (void)
Referenced by init_script_list().
render_animated_models()
void render_animated_models (void)
Referenced by reset_model_animators().
reset_model_animators()
void reset_model_animators (void)
Referenced by clear_script_list().
update_animated_models()
void update_animated_models (void)
Referenced by reset_model_animators().
Variable Documentation
gBattleMeshAnimationList
AnimatedModelList gBattleMeshAnimationList extern
Referenced by init_model_animators(), and reset_model_animators().
gCurrentMeshAnimationListPtr
AnimatedModelList* gCurrentMeshAnimationListPtr extern
Referenced by init_model_animators(), and reset_model_animators().
gWorldMeshAnimationList
AnimatedModelList gWorldMeshAnimationList extern
Referenced by init_model_animators(), and reset_model_animators().