papermario: src/model.c File Reference
model.c File Reference
Data Structures
struct FogSettings
struct DepthFloatFactors
Macros
#define WORLD_TEXTURE_MEMORY_SIZE 0x20000
#define BATTLE_TEXTURE_MEMORY_SIZE 0x8000
#define DEPTH_EXPONENT_MASK 0xE000
#define DEPTH_MANTISSA_MASK 0x1FFC
#define DEPTH_DZ_MASK 0x0003
#define DEPTH_EXPONENT_SHIFT 13
#define DEPTH_MANTISSA_SHIFT 2
#define DEPTH_DZ_SHIFT 0
#define MAX_VIEWPORT_DEPTH (2 * 32 * ((G_MAXZ / 2)))
#define TEST_POINT_VISIBILITY
Enumerations
enum {
AUX_COMBINE_0 = 0 , AUX_COMBINE_1 = 1 , AUX_COMBINE_2 = 2 , AUX_COMBINE_3 = 3 ,
AUX_COMBINE_4 = 4 , AUX_COMBINE_5 = 5 , AUX_COMBINE_6 = 6 , AUX_COMBINE_7 = 7 ,
AUX_COMBINE_8 = 8 , AUX_COMBINE_9 = 9 , AUX_COMBINE_A = 10
}
enum { AUX_COMBINE_SUB_0 = 0 , AUX_COMBINE_SUB_1 = 1 , AUX_COMBINE_SUB_2 = 2 , AUX_COMBINE_SUB_COUNT = 3 }
enum {
TEX_COMBINE_NOTEX = 0 , TEX_COMBINE_MAIN_ONLY_0 = 1 , TEX_COMBINE_MAIN_ONLY_1 = 2 , TEX_COMBINE_MAIN_ONLY_2 = 3 ,
TEX_COMBINE_MIPMAPS_0 = 4 , TEX_COMBINE_MIPMAPS_1 = 5 , TEX_COMBINE_MIPMAPS_2 = 6 , TEX_COMBINE_AUX_SHARED_0 = 7 ,
TEX_COMBINE_AUX_SHARED_1 = 8 , TEX_COMBINE_AUX_SHARED_2 = 9 , TEX_COMBINE_AUX_IND_0 = 10 , TEX_COMBINE_AUX_IND_1 = 11 ,
TEX_COMBINE_AUX_IND_2 = 12 , TEX_COMBINE_3 = 13 , TEX_COMBINE_4 = 14 , TEX_COMBINE_5 = 15 ,
TEX_COMBINE_6 = 16 , TEX_COMBINE_7 = 17 , TEX_COMBINE_8 = 18 , TEX_COMBINE_9 = 19 ,
TEX_COMBINE_A = 20
}
enum {
TINT_COMBINE_NONE = 0 , TINT_COMBINE_FOG = 1 , TINT_COMBINE_SHROUD = 2 , TINT_COMBINE_DEPTH = 3 ,
TINT_COMBINE_REMAP = 4
}
enum {
RENDER_CLASS_1CYC = 1 , RENDER_CLASS_2CYC = 2 , RENDER_CLASS_FOG = 3 , RENDER_CLASS_1CYC_SHROUD = 4 ,
RENDER_CLASS_2CYC_SHROUD = 5 , RENDER_CLASS_FOG_SHROUD = 6 , RENDER_CLASS_1CYC_DEPTH = 10 , RENDER_CLASS_2CYC_DEPTH = 11
}
Functions
BSS TextureHeader gCurrentTextureHeader ALIGNED (16)
void func_80117D00 (Model *model)
void appendGfx_model_group (void *model)
void render_transform_group_node (ModelNode *node)
void render_transform_group (void *group)
void make_texture_gfx (TextureHeader *, Gfx **, IMG_PTR raster, PAL_PTR palette, IMG_PTR auxRaster, PAL_PTR auxPalette, u8, u8, u16, u16)
void load_model_transforms (ModelNode *model, ModelNode *parent, Matrix4f mdlTxMtx, s32 treeDepth)
s32 is_identity_fixed_mtx (Mtx *mtx)
void build_custom_gfx (void)
void appendGfx_model (void *data)
void load_texture_impl (u32 romOffset, TextureHandle *handle, TextureHeader *header, s32 mainSize, s32 mainPalSize, s32 auxSize, s32 auxPalSize)
void load_texture_by_name (ModelNodeProperty *propertyName, s32 romOffset, s32 size)
void load_texture_variants (u32 romOffset, s32 textureID, s32 baseOffset, s32 size)
ModelNodeProperty * get_model_property (ModelNode *node, ModelPropertyKeys key)
void load_next_model_textures (ModelNode *model, s32 romOffset, s32 texSize)
void mdl_load_all_textures (ModelNode *rootModel, s32 romOffset, s32 size)
s32 mdl_get_child_count (ModelNode *model)
void clear_model_data (void)
void init_model_data (void)
void mdl_calculate_model_sizes (void)
void mdl_create_model (ModelBlueprint *bp, s32 unused)
void iterate_models (void)
void mdl_update_transform_matrices (void)
void render_models (void)
Model * get_model_from_list_index (s32 listIndex)
void load_data_for_models (ModelNode *rootModel, s32 texturesOffset, s32 size)
s32 get_model_list_index_from_tree_index (s32 treeIndex)
s32 get_transform_group_index (s32 modelID)
void get_model_center_and_size (u16 modelID, f32 *centerX, f32 *centerY, f32 *centerZ, f32 *sizeX, f32 *sizeY, f32 *sizeZ)
ModelTransformGroup * get_transform_group (s32 index)
void func_8011B1D8 (ModelNode *node)
void mdl_make_transform_group (u16 modelID)
void enable_transform_group (u16 modelID)
void disable_transform_group (u16 modelID)
void clone_model (u16 srcModelID, u16 newModelID)
void mdl_group_set_visibility (u16 treeIndex, s32 flags, s32 mode)
void mdl_group_set_custom_gfx (u16 groupModelID, s32 customGfxIndex, s32 tintType, b32 invertSelection)
void mdl_reset_transform_flags (void)
void enable_world_fog (void)
void disable_world_fog (void)
void set_world_fog_dist (s32 start, s32 end)
void set_world_fog_color (s32 r, s32 g, s32 b, s32 a)
s32 is_world_fog_enabled (void)
void get_world_fog_distance (s32 *start, s32 *end)
void get_world_fog_color (s32 *r, s32 *g, s32 *b, s32 *a)
void set_tex_panner (Model *model, s32 texPannerID)
void set_main_pan_u (s32 texPannerID, s32 value)
void set_main_pan_v (s32 texPannerID, s32 value)
void set_aux_pan_u (s32 texPannerID, s32 value)
void set_aux_pan_v (s32 texPannerID, s32 value)
void set_mdl_custom_gfx_set (Model *model, s32 customGfxIndex, u32 tintType)
void set_custom_gfx (s32 customGfxIndex, Gfx *pre, Gfx *post)
void set_custom_gfx_builders (s32 customGfxIndex, ModelCustomGfxBuilderFunc pre, ModelCustomGfxBuilderFunc post)
void mdl_set_shroud_tint_params (u8 r, u8 g, u8 b, u8 a)
void mdl_get_shroud_tint_params (u8 *r, u8 *g, u8 *b, u8 *a)
void mdl_set_depth_tint_params (u8 primR, u8 primG, u8 primB, u8 primA, u8 fogR, u8 fogG, u8 fogB, s32 fogStart, s32 fogEnd)
void mdl_get_depth_tint_params (u8 *primR, u8 *primG, u8 *primB, u8 *primA, u8 *fogR, u8 *fogG, u8 *fogB, s32 *fogStart, s32 *fogEnd)
void mdl_set_remap_tint_params (u8 maxR, u8 maxG, u8 maxB, u8 minR, u8 minG, u8 minB)
void mdl_get_remap_tint_params (u8 *primR, u8 *primG, u8 *primB, u8 *envR, u8 *envG, u8 *envB)
void mdl_get_vertex_count (Gfx *gfx, s32 *numVertices, Vtx **baseVtx, s32 *gfxCount, Vtx *baseAddr)
void mdl_local_gfx_update_vtx_pointers (Gfx *nodeDlist, Vtx *baseVtx, Gfx *arg2, Vtx *arg3)
void mdl_local_gfx_copy_vertices (Vtx *src, s32 num, Vtx *dest)
void mdl_make_local_vertex_copy (s32 copyIndex, u16 modelID, s32 isMakingCopy)
void mdl_get_copied_vertices (s32 copyIndex, Vtx **firstVertex, Vtx **copiedVertices, s32 *numCopied)
Gfx * mdl_get_copied_gfx (s32 copyIndex)
void mdl_project_tex_coords (s32 modelID, Gfx *outGfx, Matrix4f arg2, Vtx *arg3)
s32 is_model_center_visible (u16 modelID, s32 depthQueryID, f32 *screenX, f32 *screenY)
b32 is_point_visible (f32 x, f32 y, f32 z, s32 depthQueryID, f32 *screenX, f32 *screenY)
void mdl_draw_hidden_panel_surface (Gfx **arg0, u16 treeIndex)
void * mdl_get_next_texture_address (s32 size)
void mdl_set_all_tint_type (s32 tintType)
void clear_render_tasks (void)
void clear_render_tasks_alt (void)
RenderTask * queue_render_task (RenderTask *task)
void execute_render_tasks (void)
Variables
u8 * gBackgroundTintModePtr
ModelList * gCurrentModels
ModelTreeInfoList * gCurrentModelTreeNodeInfo
Addr TextureHeap
Gfx Gfx_RM1_SURFACE_OPA []
Gfx Gfx_RM1_DECAL_OPA []
Gfx Gfx_RM1_INTERSECTING_OPA []
Gfx Gfx_RM1_ALPHATEST []
Gfx Gfx_RM1_SURFACE_XLU []
Gfx Gfx_RM1_DECAL_XLU []
Gfx Gfx_RM1_INTERSECTING_XLU []
Gfx Gfx_RM1_SURFACE_OPA_NO_AA []
Gfx Gfx_RM1_DECAL_OPA_NO_AA []
Gfx Gfx_RM1_INTERSECTING_OPA_NO_AA []
Gfx Gfx_RM1_ALPHATEST_ONESIDED []
Gfx Gfx_RM1_SURFACE_XLU_NO_AA []
Gfx Gfx_RM1_DECAL_XLU_NO_AA []
Gfx Gfx_RM1_PASS_THROUGH []
Gfx Gfx_RM1_SURFACE_XLU_AA_ZB_ZUPD []
Gfx Gfx_RM1_SURFACE_OPA_NO_ZB []
Gfx Gfx_RM1_ALPHATEST_NO_ZB []
Gfx Gfx_RM1_SURFACE_XLU_NO_ZB []
Gfx Gfx_RM1_SURFACE_XLU_ZB_ZUPD []
Gfx Gfx_RM1_CLOUD_NO_ZCMP []
Gfx Gfx_RM1_CLOUD []
Gfx Gfx_RM1_CLOUD_NO_ZB []
Gfx Gfx_RM2_SURFACE_OPA []
Gfx Gfx_RM2_DECAL_OPA []
Gfx Gfx_RM2_INTERSECTING_OPA []
Gfx Gfx_RM2_ALPHATEST []
Gfx Gfx_RM2_SURFACE_XLU []
Gfx Gfx_RM2_DECAL_XLU []
Gfx Gfx_RM2_INTERSECTING_XLU []
Gfx Gfx_RM2_SURFACE_OPA_NO_AA []
Gfx Gfx_RM2_DECAL_OPA_NO_AA []
Gfx Gfx_RM2_INTERSECTING_OPA_NO_AA []
Gfx Gfx_RM2_ALPHATEST_ONESIDED []
Gfx Gfx_RM2_SURFACE_XLU_NO_AA []
Gfx Gfx_RM2_DECAL_XLU_NO_AA []
Gfx Gfx_RM2_PASS_THROUGH []
Gfx Gfx_RM2_SURFACE_XLU_AA_ZB_ZUPD []
Gfx Gfx_RM2_SURFACE_OPA_NO_ZB []
Gfx Gfx_RM2_ALPHATEST_NO_ZB []
Gfx Gfx_RM2_SURFACE_XLU_NO_ZB []
Gfx Gfx_RM2_CLOUD []
Gfx Gfx_RM2_CLOUD_NO_ZB []
Gfx Gfx_RM3_SURFACE_OPA []
Gfx Gfx_RM3_DECAL_OPA []
Gfx Gfx_RM3_INTERSECTING_OPA []
Gfx Gfx_RM3_ALPHATEST []
Gfx Gfx_RM3_SURFACE_XLU []
Gfx Gfx_RM3_DECAL_XLU []
Gfx Gfx_RM3_INTERSECTING_XLU []
Gfx Gfx_RM3_SURFACE_OPA_NO_AA []
Gfx Gfx_RM3_DECAL_OPA_NO_AA []
Gfx Gfx_RM3_INTERSECTING_OPA_NO_AA []
Gfx Gfx_RM3_ALPHATEST_ONESIDED []
Gfx Gfx_RM3_SURFACE_XLU_NO_AA []
Gfx Gfx_RM3_DECAL_XLU_NO_AA []
Gfx Gfx_RM3_PASS_THROUGH []
Gfx Gfx_RM3_SURFACE_XLU_AA_ZB_ZUPD []
Gfx Gfx_RM3_SURFACE_OPA_NO_ZB []
Gfx Gfx_RM3_ALPHATEST_NO_ZB []
Gfx Gfx_RM3_SURFACE_XLU_NO_ZB []
Gfx Gfx_RM3_CLOUD []
Gfx Gfx_RM3_CLOUD_NO_ZB []
Gfx * ModelRenderModes []
Gfx SolidCombineModes [][5]
Gfx AlphaTestCombineModes [][5]
void * TextureHeapBase = (void*) &TextureHeap
u8 ShroudTintAmt = 0
u8 ShroudTintR = 0
u8 ShroudTintG = 0
u8 ShroudTintB = 0
u8 DepthTintBaseR = 0
u8 DepthTintBaseG = 0
u8 DepthTintBaseB = 0
u8 DepthTintBaseA = 0
u8 DepthTintColR = 0
u8 DepthTintColG = 0
u8 DepthTintColB = 0
u8 DepthTintColA = 0
s32 DepthTintStart = 950
s32 DepthTintEnd = 1000
u8 RemapTintMaxR = 255
u8 RemapTintMaxG = 255
u8 RemapTintMaxB = 255
u8 RemapTintMinR = 0
u8 RemapTintMinG = 0
u8 RemapTintMinB = 0
Mtx ReferenceIdentityMtx
DepthFloatFactors DepthFloatLookupTable []
s32 gLastRenderTaskCount = 0
s32 RenderTaskBasePriorities []
s8 D_8014C248 = FALSE
ModelCustomGfxBuilderList * gCurrentCustomModelGfxBuildersPtr
ModelNode ** gCurrentModelTreeRoot
ModelTransformGroupList * gCurrentTransformGroups
ModelCustomGfxList * gCurrentCustomModelGfxPtr
BSS ModelList wModelList
BSS ModelList bModelList
BSS ModelTransformGroupList wTransformGroups
BSS ModelTransformGroupList bTransformGroups
BSS ModelCustomGfxList wCustomModelGfx
BSS ModelCustomGfxList bCustomModelGfx
BSS ModelCustomGfxBuilderList wCustomModelGfxBuilders
BSS ModelCustomGfxBuilderList bCustomModelGfxBuilders
BSS ModelLocalVertexCopyList wModelLocalVtxBuffers
BSS ModelLocalVertexCopyList bModelLocalVtxBuffers
BSS ModelLocalVertexCopyList * gCurrentModelLocalVtxBuffers
BSS ModelNode * wModelTreeRoot
BSS ModelNode * bModelTreeRoot
BSS s32 D_8015221C
BSS ModelTreeInfoList wModelTreeNodeInfo
BSS ModelTreeInfoList bModelTreeNodeInfo
BSS s8 wBackgroundTintMode
BSS s8 bBackgroundTintMode
BSS s8 D_80153222
BSS s8 D_80153223
BSS s32 TreeIterPos
BSS FogSettings wFogSettings
BSS s32 D_80153244
BSS FogSettings bFogSettings
BSS FogSettings * gFogSettings
BSS s32 texPannerMainU [MAX_TEX_PANNERS]
BSS s32 texPannerMainV [MAX_TEX_PANNERS]
BSS s32 texPannerAuxU [MAX_TEX_PANNERS]
BSS s32 texPannerAuxV [MAX_TEX_PANNERS]
BSS void * TextureHeapPos
BSS u16 mtg_IterIdx
BSS u16 mtg_SearchModelID
BSS ModelNode * mtg_FoundModelNode
BSS u16 mtg_MinChild
BSS u16 mtg_MaxChild
BSS s32 D_80153378 [2]
BSS u16 DepthCopyBuffer [16]
BSS RenderTask * RenderTaskLists [3]
BSS s32 RenderTaskListIdx
BSS s32 RenderTaskCount
TextureHandle TextureHandles [128]
Addr BattleEntityHeapBottom
Data Structure Documentation
FogSettings
struct FogSettings
Data Fields
Color4i color
s32 enabled
s32 endDistance
s32 startDistance
DepthFloatFactors
struct DepthFloatFactors
Data Fields
s32 bias
s32 shift
Macro Definition Documentation
BATTLE_TEXTURE_MEMORY_SIZE
#define BATTLE_TEXTURE_MEMORY_SIZE 0x8000
Referenced by mdl_get_next_texture_address().
DEPTH_DZ_MASK
#define DEPTH_DZ_MASK 0x0003
Referenced by is_model_center_visible(), and is_point_visible().
DEPTH_DZ_SHIFT
#define DEPTH_DZ_SHIFT 0
DEPTH_EXPONENT_MASK
#define DEPTH_EXPONENT_MASK 0xE000
DEPTH_EXPONENT_SHIFT
#define DEPTH_EXPONENT_SHIFT 13
Referenced by is_model_center_visible(), and is_point_visible().
DEPTH_MANTISSA_MASK
#define DEPTH_MANTISSA_MASK 0x1FFC
Referenced by is_model_center_visible(), and is_point_visible().
DEPTH_MANTISSA_SHIFT
#define DEPTH_MANTISSA_SHIFT 2
Referenced by is_model_center_visible(), and is_point_visible().
MAX_VIEWPORT_DEPTH
#define MAX_VIEWPORT_DEPTH (2 * 32 * ((G_MAXZ / 2)))
Referenced by is_model_center_visible(), and is_point_visible().
TEST_POINT_VISIBILITY
#define TEST_POINT_VISIBILITY
Value:
    outX = (m00 * xComp) + (m10 * yComp) + (m20 * zComp) + m30; \
    outY = (m01 * xComp) + (m11 * yComp) + (m21 * zComp) + m31; \
    outZ = (m02 * xComp) + (m12 * yComp) + (m22 * zComp) + m32; \
    outW = (m03 * xComp) + (m13 * yComp) + (m23 * zComp) + m33; \
    if (outW == 0.0f) { \
        break; \
    } \
    /* Perspective divide */ \
    outW = 1.0f / outW; \
    xComp = outX * outW; \
    yComp = outY * outW; \
    zComp = outZ * outW; \
    if (zComp > -1.0f && xComp >= -1.0f && xComp <= 1.0f && yComp >= -1.0f && yComp <= 1.0f) { \
        break; \
    }
WORLD_TEXTURE_MEMORY_SIZE
#define WORLD_TEXTURE_MEMORY_SIZE 0x20000
Referenced by mdl_get_next_texture_address(), and mdl_load_all_textures().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
AUX_COMBINE_0
AUX_COMBINE_1
AUX_COMBINE_2
AUX_COMBINE_3
AUX_COMBINE_4
AUX_COMBINE_5
AUX_COMBINE_6
AUX_COMBINE_7
AUX_COMBINE_8
AUX_COMBINE_9
AUX_COMBINE_A
anonymous enum
anonymous enum
Enumerator
AUX_COMBINE_SUB_0
AUX_COMBINE_SUB_1
AUX_COMBINE_SUB_2
AUX_COMBINE_SUB_COUNT
anonymous enum
anonymous enum
Enumerator
TEX_COMBINE_NOTEX
TEX_COMBINE_MAIN_ONLY_0
TEX_COMBINE_MAIN_ONLY_1
TEX_COMBINE_MAIN_ONLY_2
TEX_COMBINE_MIPMAPS_0
TEX_COMBINE_MIPMAPS_1
TEX_COMBINE_MIPMAPS_2
TEX_COMBINE_AUX_SHARED_0
TEX_COMBINE_AUX_SHARED_1
TEX_COMBINE_AUX_SHARED_2
TEX_COMBINE_AUX_IND_0
TEX_COMBINE_AUX_IND_1
TEX_COMBINE_AUX_IND_2
TEX_COMBINE_3
TEX_COMBINE_4
TEX_COMBINE_5
TEX_COMBINE_6
TEX_COMBINE_7
TEX_COMBINE_8
TEX_COMBINE_9
TEX_COMBINE_A
anonymous enum
anonymous enum
Enumerator
TINT_COMBINE_NONE
TINT_COMBINE_FOG
TINT_COMBINE_SHROUD
TINT_COMBINE_DEPTH
TINT_COMBINE_REMAP
anonymous enum
anonymous enum
Enumerator
RENDER_CLASS_1CYC
RENDER_CLASS_2CYC
RENDER_CLASS_FOG
RENDER_CLASS_1CYC_SHROUD
RENDER_CLASS_2CYC_SHROUD
RENDER_CLASS_FOG_SHROUD
RENDER_CLASS_1CYC_DEPTH
RENDER_CLASS_2CYC_DEPTH
Function Documentation
ALIGNED()
BSS TextureHeader gCurrentTextureHeader ALIGNED (16)
appendGfx_model()
void appendGfx_model (void * data)
Referenced by func_80117D00(), mdl_draw_hidden_panel_surface(), render_models(), and render_transform_group_node().
appendGfx_model_group()
void appendGfx_model_group (void * model)
Referenced by render_models(), and render_transform_group_node().
build_custom_gfx()
void build_custom_gfx (void)
Referenced by mdl_update_transform_matrices().
clear_model_data()
void clear_model_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
clear_render_tasks()
void clear_render_tasks (void)
Referenced by load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_demo(), state_step_intro(), state_step_startup(), and state_step_title_screen().
clear_render_tasks_alt()
void clear_render_tasks_alt (void)
clone_model()
void clone_model (u16 srcModelID, u16 newModelID)
disable_transform_group()
void disable_transform_group (u16 modelID)
disable_world_fog()
void disable_world_fog (void)
enable_transform_group()
void enable_transform_group (u16 modelID)
Referenced by mdl_make_transform_group().
enable_world_fog()
void enable_world_fog (void)
execute_render_tasks()
void execute_render_tasks (void)
Referenced by render_frame().
func_80117D00()
void func_80117D00 (Model * model)
Referenced by appendGfx_model_group(), and func_80117D00().
func_8011B1D8()
void func_8011B1D8 (ModelNode * node)
Referenced by func_8011B1D8(), and mdl_make_transform_group().
get_model_center_and_size()
void get_model_center_and_size (u16 modelID, f32 * centerX, f32 * centerY, f32 * centerZ, f32 * sizeX, f32 * sizeY, f32 * sizeZ)
get_model_from_list_index()
Model * get_model_from_list_index (s32 listIndex)
Referenced by animator_node_update_model_transform(), clone_model(), disable_transform_group(), enable_transform_group(), get_model_center_and_size(), get_model_list_index_from_tree_index(), gfx_build_inside_crystal_ball(), gfx_build_water(), hide_foreground_models(), hide_foreground_models_unchecked(), is_model_center_visible(), mdl_draw_hidden_panel_surface(), mdl_make_local_vertex_copy(), mdl_project_tex_coords(), render_transform_group_node(), set_spotlight_pos_scale(), show_foreground_models(), show_foreground_models_unchecked(), UnkModelFunc001(), and update_collider_transform().
get_model_list_index_from_tree_index()
s32 get_model_list_index_from_tree_index (s32 treeIndex)
Referenced by animator_node_update_model_transform(), clone_model(), get_model_center_and_size(), gfx_build_inside_crystal_ball(), gfx_build_water(), hide_foreground_models(), hide_foreground_models_unchecked(), is_model_center_visible(), mdl_draw_hidden_panel_surface(), mdl_make_local_vertex_copy(), mdl_make_transform_group(), mdl_project_tex_coords(), set_spotlight_pos_scale(), show_foreground_models(), show_foreground_models_unchecked(), and UnkModelFunc001().
get_model_property()
ModelNodeProperty * get_model_property (ModelNode * node, ModelPropertyKeys key)
Referenced by appendGfx_model(), func_80117D00(), func_8011B1D8(), get_model_center_and_size(), load_model_transforms(), load_next_model_textures(), mdl_calculate_model_sizes(), mdl_create_model(), mdl_make_transform_group(), mdl_update_transform_matrices(), and render_transform_group_node().
get_transform_group()
ModelTransformGroup * get_transform_group (s32 index)
Referenced by disable_transform_group(), enable_transform_group(), and get_transform_group_index().
get_transform_group_index()
s32 get_transform_group_index (s32 modelID)
Referenced by disable_transform_group(), and enable_transform_group().
get_world_fog_color()
void get_world_fog_color (s32 * r, s32 * g, s32 * b, s32 * a)
Referenced by appendGfx_background_texture(), and tattle_cam_pre_render().
get_world_fog_distance()
void get_world_fog_distance (s32 * start, s32 * end)
init_model_data()
void init_model_data (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
is_identity_fixed_mtx()
s32 is_identity_fixed_mtx (Mtx * mtx)
Returns
TRUE if mtx is NULL or identity.
Referenced by mdl_create_model().
is_model_center_visible()
s32 is_model_center_visible (u16 modelID, s32 depthQueryID, f32 * screenX, f32 * screenY)
is_point_visible()
b32 is_point_visible (f32 x, f32 y, f32 z, s32 depthQueryID, f32 * screenX, f32 * screenY)
is_world_fog_enabled()
s32 is_world_fog_enabled (void)
Referenced by appendGfx_background_texture(), and tattle_cam_pre_render().
iterate_models()
void iterate_models (void)
Referenced by state_step_battle(), and state_step_world().
load_data_for_models()
void load_data_for_models (ModelNode * rootModel, s32 texturesOffset, s32 size)
Referenced by btl_state_update_normal_start(), and load_map_by_IDs().
load_model_transforms()
void load_model_transforms (ModelNode * model, ModelNode * parent, Matrix4f mdlTxMtx, s32 treeDepth)
Referenced by load_data_for_models(), and load_model_transforms().
load_next_model_textures()
void load_next_model_textures (ModelNode * model, s32 romOffset, s32 texSize)
Referenced by load_next_model_textures(), and mdl_load_all_textures().
load_texture_by_name()
void load_texture_by_name (ModelNodeProperty * propertyName, s32 romOffset, s32 size)
Referenced by load_next_model_textures().
load_texture_impl()
void load_texture_impl (u32 romOffset, TextureHandle * handle, TextureHeader * header, s32 mainSize, s32 mainPalSize, s32 auxSize, s32 auxPalSize)
Referenced by load_texture_by_name(), and load_texture_variants().
load_texture_variants()
void load_texture_variants (u32 romOffset, s32 textureID, s32 baseOffset, s32 size)
Referenced by load_texture_by_name().
make_texture_gfx()
void make_texture_gfx (TextureHeader * header, Gfx ** gfxPos, IMG_PTR raster, PAL_PTR palette, IMG_PTR auxRaster, PAL_PTR auxPalette, u8 auxShiftS, u8 auxShiftT, u16 auxOffsetS, u16 auxOffsetT)
Referenced by appendGfx_model(), and load_texture_impl().
mdl_calculate_model_sizes()
void mdl_calculate_model_sizes (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
mdl_create_model()
void mdl_create_model (ModelBlueprint * bp, s32 unused)
Referenced by load_model_transforms().
mdl_draw_hidden_panel_surface()
void mdl_draw_hidden_panel_surface (Gfx ** arg0, u16 treeIndex)
mdl_get_child_count()
s32 mdl_get_child_count (ModelNode * model)
Referenced by func_8011B1D8(), load_model_transforms(), and mdl_get_child_count().
mdl_get_copied_gfx()
Gfx * mdl_get_copied_gfx (s32 copyIndex)
Referenced by build_gfx_aurora(), build_gfx_blue_stars(), build_gfx_blue_stars(), build_gfx_green_stars(), build_gfx_green_stars(), build_gfx_pink_stars(), build_gfx_pink_stars(), build_gfx_star(), build_gfx_yellow_stars(), build_gfx_yellow_stars(), func_8024033C_A1B43C(), func_8024060C_A1B70C(), gfx_build_bubble_flower(), gfx_build_club_64(), gfx_build_rowf_rug_with_ripples(), make_tongue_gfx(), setup_gfx_bridge(), unkAngleFunc002(), and unkAngleFunc003().
mdl_get_copied_vertices()
void mdl_get_copied_vertices (s32 copyIndex, Vtx ** firstVertex, Vtx ** copiedVertices, s32 * numCopied)
Referenced by build_gfx_aurora(), build_gfx_blue_stars(), build_gfx_blue_stars(), build_gfx_green_stars(), build_gfx_green_stars(), build_gfx_pink_stars(), build_gfx_pink_stars(), build_gfx_star(), build_gfx_yellow_stars(), build_gfx_yellow_stars(), func_8024033C_A1B43C(), func_8024060C_A1B70C(), gfx_build_bubble_flower(), gfx_build_club_64(), gfx_build_rowf_rug_with_ripples(), make_tongue_gfx(), setup_gfx_bridge(), unkAngleFunc002(), and unkAngleFunc003().
mdl_get_depth_tint_params()
void mdl_get_depth_tint_params (u8 * primR, u8 * primG, u8 * primB, u8 * primA, u8 * fogR, u8 * fogG, u8 * fogB, s32 * fogStart, s32 * fogEnd)
mdl_get_next_texture_address()
void * mdl_get_next_texture_address (s32 size)
Referenced by draw_box().
mdl_get_remap_tint_params()
void mdl_get_remap_tint_params (u8 * primR, u8 * primG, u8 * primB, u8 * envR, u8 * envG, u8 * envB)
Referenced by appendGfx_background_texture().
mdl_get_shroud_tint_params()
void mdl_get_shroud_tint_params (u8 * r, u8 * g, u8 * b, u8 * a)
mdl_get_vertex_count()
void mdl_get_vertex_count (Gfx * gfx, s32 * numVertices, Vtx ** baseVtx, s32 * gfxCount, Vtx * baseAddr)
Referenced by mdl_make_local_vertex_copy(), and mdl_project_tex_coords().
mdl_group_set_custom_gfx()
void mdl_group_set_custom_gfx (u16 groupModelID, s32 customGfxIndex, s32 tintType, b32 invertSelection)
mdl_group_set_visibility()
void mdl_group_set_visibility (u16 treeIndex, s32 flags, s32 mode)
mdl_load_all_textures()
void mdl_load_all_textures (ModelNode * rootModel, s32 romOffset, s32 size)
Referenced by load_data_for_models(), state_init_file_select(), state_init_language_select(), and state_step_end_battle().
mdl_local_gfx_copy_vertices()
void mdl_local_gfx_copy_vertices (Vtx * src, s32 num, Vtx * dest)
Referenced by mdl_make_local_vertex_copy().
mdl_local_gfx_update_vtx_pointers()
void mdl_local_gfx_update_vtx_pointers (Gfx * nodeDlist, Vtx * baseVtx, Gfx * arg2, Vtx * arg3)
Referenced by mdl_make_local_vertex_copy().
mdl_make_local_vertex_copy()
void mdl_make_local_vertex_copy (s32 copyIndex, u16 modelID, s32 isMakingCopy)
mdl_make_transform_group()
void mdl_make_transform_group (u16 modelID)
mdl_project_tex_coords()
void mdl_project_tex_coords (s32 modelID, Gfx * outGfx, Matrix4f arg2, Vtx * arg3)
mdl_reset_transform_flags()
void mdl_reset_transform_flags (void)
Referenced by step_game_loop().
mdl_set_all_tint_type()
void mdl_set_all_tint_type (s32 tintType)
Referenced by btl_state_update_celebration().
mdl_set_depth_tint_params()
void mdl_set_depth_tint_params (u8 primR, u8 primG, u8 primB, u8 primA, u8 fogR, u8 fogG, u8 fogB, s32 fogStart, s32 fogEnd)
mdl_set_remap_tint_params()
void mdl_set_remap_tint_params (u8 maxR, u8 maxG, u8 maxB, u8 minR, u8 minG, u8 minB)
mdl_set_shroud_tint_params()
void mdl_set_shroud_tint_params (u8 r, u8 g, u8 b, u8 a)
Referenced by btl_state_update_celebration().
mdl_update_transform_matrices()
void mdl_update_transform_matrices (void)
Referenced by render_frame().
queue_render_task()
RenderTask * queue_render_task (RenderTask * task)
render_models()
void render_models (void)
Referenced by render_frame().
render_transform_group()
void render_transform_group (void * group)
Referenced by render_models().
render_transform_group_node()
void render_transform_group_node (ModelNode * node)
Referenced by render_transform_group(), and render_transform_group_node().
set_aux_pan_u()
void set_aux_pan_u (s32 texPannerID, s32 value)
set_aux_pan_v()
void set_aux_pan_v (s32 texPannerID, s32 value)
set_custom_gfx()
void set_custom_gfx (s32 customGfxIndex, Gfx * pre, Gfx * post)
set_custom_gfx_builders()
void set_custom_gfx_builders (s32 customGfxIndex, ModelCustomGfxBuilderFunc pre, ModelCustomGfxBuilderFunc post)
set_main_pan_u()
void set_main_pan_u (s32 texPannerID, s32 value)
set_main_pan_v()
void set_main_pan_v (s32 texPannerID, s32 value)
set_mdl_custom_gfx_set()
void set_mdl_custom_gfx_set (Model * model, s32 customGfxIndex, u32 tintType)
Referenced by mdl_set_all_tint_type().
set_tex_panner()
void set_tex_panner (Model * model, s32 texPannerID)
set_world_fog_color()
void set_world_fog_color (s32 r, s32 g, s32 b, s32 a)
set_world_fog_dist()
void set_world_fog_dist (s32 start, s32 end)
Variable Documentation
AlphaTestCombineModes
Gfx AlphaTestCombineModes[][5]
Referenced by appendGfx_model().
BattleEntityHeapBottom
Addr BattleEntityHeapBottom extern
bBackgroundTintMode
BSS s8 bBackgroundTintMode
Referenced by clear_model_data(), and init_model_data().
bCustomModelGfx
BSS ModelCustomGfxList bCustomModelGfx
Referenced by clear_model_data(), and init_model_data().
bCustomModelGfxBuilders
BSS ModelCustomGfxBuilderList bCustomModelGfxBuilders
Referenced by clear_model_data(), and init_model_data().
bFogSettings
BSS FogSettings bFogSettings
Referenced by clear_model_data(), and init_model_data().
bModelList
BSS ModelList bModelList
Referenced by clear_model_data(), and init_model_data().
bModelLocalVtxBuffers
BSS ModelLocalVertexCopyList bModelLocalVtxBuffers
Referenced by clear_model_data(), and init_model_data().
bModelTreeNodeInfo
BSS ModelTreeInfoList bModelTreeNodeInfo
Referenced by clear_model_data(), and init_model_data().
bModelTreeRoot
BSS ModelNode* bModelTreeRoot
Referenced by clear_model_data(), and init_model_data().
bTransformGroups
BSS ModelTransformGroupList bTransformGroups
Referenced by clear_model_data(), and init_model_data().
D_8014C248
s8 D_8014C248 = FALSE
Referenced by state_init_title_screen().
D_8015221C
BSS s32 D_8015221C
D_80153222
BSS s8 D_80153222
D_80153223
BSS s8 D_80153223
D_80153244
BSS s32 D_80153244
D_80153378
BSS s32 D_80153378[2]
DepthCopyBuffer
BSS u16 DepthCopyBuffer[16]
Referenced by is_model_center_visible(), and is_point_visible().
DepthFloatLookupTable
DepthFloatFactors DepthFloatLookupTable[]
Initial value:
= {
    { 6, 0x00000 },
    { 5, 0x20000 },
    { 4, 0x30000 },
    { 3, 0x38000 },
    { 2, 0x3C000 },
    { 1, 0x3E000 },
    { 0, 0x3F000 },
    { 0, 0x3F800 },
    { 0, 0x00000 },
}
Referenced by is_model_center_visible(), and is_point_visible().
DepthTintBaseA
u8 DepthTintBaseA = 0
Referenced by appendGfx_model(), mdl_get_depth_tint_params(), and mdl_set_depth_tint_params().
DepthTintBaseB
u8 DepthTintBaseB = 0
Referenced by appendGfx_model(), mdl_get_depth_tint_params(), and mdl_set_depth_tint_params().
DepthTintBaseG
u8 DepthTintBaseG = 0
Referenced by appendGfx_model(), mdl_get_depth_tint_params(), and mdl_set_depth_tint_params().
DepthTintBaseR
u8 DepthTintBaseR = 0
Referenced by appendGfx_model(), mdl_get_depth_tint_params(), and mdl_set_depth_tint_params().
DepthTintColA
u8 DepthTintColA = 0
DepthTintColB
u8 DepthTintColB = 0
Referenced by appendGfx_model(), mdl_get_depth_tint_params(), and mdl_set_depth_tint_params().
DepthTintColG
u8 DepthTintColG = 0
Referenced by appendGfx_model(), mdl_get_depth_tint_params(), and mdl_set_depth_tint_params().
DepthTintColR
u8 DepthTintColR = 0
Referenced by appendGfx_model(), mdl_get_depth_tint_params(), and mdl_set_depth_tint_params().
DepthTintEnd
s32 DepthTintEnd = 1000
Referenced by appendGfx_model(), mdl_get_depth_tint_params(), and mdl_set_depth_tint_params().
DepthTintStart
s32 DepthTintStart = 950
Referenced by appendGfx_model(), mdl_get_depth_tint_params(), and mdl_set_depth_tint_params().
gBackgroundTintModePtr
u8* gBackgroundTintModePtr
Referenced by appendGfx_background_texture(), btl_state_update_celebration(), clear_model_data(), floating_flower_appendGfx(), init_model_data(), and snowfall_appendGfx().
gCurrentCustomModelGfxBuildersPtr
ModelCustomGfxBuilderList* gCurrentCustomModelGfxBuildersPtr
Referenced by clear_model_data(), and init_model_data().
gCurrentCustomModelGfxPtr
ModelCustomGfxList* gCurrentCustomModelGfxPtr
Referenced by appendGfx_model(), build_custom_gfx(), clear_model_data(), and init_model_data().
gCurrentModelLocalVtxBuffers
BSS ModelLocalVertexCopyList* gCurrentModelLocalVtxBuffers
Referenced by clear_model_data(), and init_model_data().
gCurrentModels
ModelList* gCurrentModels
Referenced by clear_model_data(), clone_model(), get_model_from_list_index(), init_model_data(), iterate_models(), mdl_calculate_model_sizes(), mdl_create_model(), mdl_reset_transform_flags(), mdl_set_all_tint_type(), mdl_update_transform_matrices(), and render_models().
gCurrentModelTreeNodeInfo
ModelTreeInfoList* gCurrentModelTreeNodeInfo
Referenced by appendGfx_model_group(), clear_model_data(), init_model_data(), load_texture_by_name(), mdl_group_set_custom_gfx(), and mdl_group_set_visibility().
gCurrentModelTreeRoot
ModelNode** gCurrentModelTreeRoot
Referenced by clear_model_data(), init_model_data(), load_data_for_models(), and mdl_make_transform_group().
gCurrentTransformGroups
ModelTransformGroupList* gCurrentTransformGroups
Referenced by clear_model_data(), get_transform_group(), init_model_data(), mdl_make_transform_group(), mdl_reset_transform_flags(), mdl_update_transform_matrices(), and render_models().
gFogSettings
BSS FogSettings* gFogSettings
Referenced by appendGfx_model(), clear_model_data(), disable_world_fog(), enable_world_fog(), get_world_fog_color(), get_world_fog_distance(), init_model_data(), is_world_fog_enabled(), set_world_fog_color(), and set_world_fog_dist().
Gfx_RM1_ALPHATEST
Gfx Gfx_RM1_ALPHATEST[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_TEX_EDGE, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), appendGfx_item_entity(), draw_entity_model_E(), and render_item_entities().
Gfx_RM1_ALPHATEST_NO_ZB
Gfx Gfx_RM1_ALPHATEST_NO_ZB[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_TEX_EDGE, G_RM_AA_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_ALPHATEST_ONESIDED
Gfx Gfx_RM1_ALPHATEST_ONESIDED[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_TEX_EDGE, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_CLOUD
Gfx Gfx_RM1_CLOUD
Initial value:
= {
    gsDPSetRenderMode(G_RM_ZB_CLD_SURF, G_RM_ZB_CLD_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM1_CLOUD_NO_ZB
Gfx Gfx_RM1_CLOUD_NO_ZB
Initial value:
= {
    gsDPSetRenderMode(G_RM_CLD_SURF, G_RM_CLD_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM1_CLOUD_NO_ZCMP
Gfx Gfx_RM1_CLOUD_NO_ZCMP[]
Initial value:
= {
    gsDPSetRenderMode(IM_RD | CVG_DST_SAVE | ZMODE_XLU | FORCE_BL |
                      GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA),
                      IM_RD | CVG_DST_SAVE | ZMODE_XLU | FORCE_BL |
                      GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_DECAL_OPA
Gfx Gfx_RM1_DECAL_OPA[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_DECAL, G_RM_AA_ZB_OPA_DECAL2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD |
                          G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_DECAL_OPA_NO_AA
Gfx Gfx_RM1_DECAL_OPA_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_ZB_OPA_DECAL, G_RM_ZB_OPA_DECAL2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM1_DECAL_XLU
Gfx Gfx_RM1_DECAL_XLU[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_XLU_DECAL, G_RM_AA_ZB_XLU_DECAL2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_DECAL_XLU_NO_AA
Gfx Gfx_RM1_DECAL_XLU_NO_AA[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_ZB_OVL_SURF, G_RM_ZB_OVL_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_INTERSECTING_OPA
Gfx Gfx_RM1_INTERSECTING_OPA[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_INTER, G_RM_AA_ZB_OPA_INTER2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD |
                          G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_INTERSECTING_OPA_NO_AA
Gfx Gfx_RM1_INTERSECTING_OPA_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_INTER, G_RM_AA_ZB_OPA_INTER2),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsDPSetCombineMode(G_CC_SHADE, G_CC_SHADE),
    gsSPEndDisplayList(),
}
Gfx_RM1_INTERSECTING_XLU
Gfx Gfx_RM1_INTERSECTING_XLU[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_XLU_INTER, G_RM_AA_ZB_XLU_INTER2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_PASS_THROUGH
Gfx Gfx_RM1_PASS_THROUGH[]
Initial value:
= {
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_OPA
Gfx Gfx_RM1_SURFACE_OPA[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD |
                          G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_OPA_NO_AA
Gfx Gfx_RM1_SURFACE_OPA_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_ZB_OPA_SURF, G_RM_ZB_OPA_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM1_SURFACE_OPA_NO_ZB
Gfx Gfx_RM1_SURFACE_OPA_NO_ZB[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_OPA_SURF, G_RM_AA_OPA_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_XLU
Gfx Gfx_RM1_SURFACE_XLU[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_ZB_XLU_SURF, G_RM_AA_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_XLU_AA_ZB_ZUPD
Gfx Gfx_RM1_SURFACE_XLU_AA_ZB_ZUPD
Initial value:
= {
    gsDPSetRenderMode(AA_EN | Z_CMP | Z_UPD | IM_RD | CLR_ON_CVG | CVG_DST_WRAP | ZMODE_XLU | FORCE_BL |
                      GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA), AA_EN | Z_CMP | Z_UPD | IM_RD |
                      CLR_ON_CVG | CVG_DST_WRAP | ZMODE_XLU | FORCE_BL |
                      GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM1_SURFACE_XLU_NO_AA
Gfx Gfx_RM1_SURFACE_XLU_NO_AA[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_ZB_XLU_SURF, G_RM_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_XLU_NO_ZB
Gfx Gfx_RM1_SURFACE_XLU_NO_ZB[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_AA_XLU_SURF, G_RM_AA_XLU_SURF2),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM1_SURFACE_XLU_ZB_ZUPD
Gfx Gfx_RM1_SURFACE_XLU_ZB_ZUPD
Initial value:
= {
    gsDPSetRenderMode(AA_EN | IM_RD | CVG_DST_WRAP | CLR_ON_CVG | FORCE_BL | Z_CMP | Z_UPD |
                      GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA),
                      AA_EN | IM_RD | CVG_DST_WRAP | CLR_ON_CVG | FORCE_BL | Z_CMP | Z_UPD  | ZMODE_XLU |
                      GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_ALPHATEST
Gfx Gfx_RM2_ALPHATEST[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_item_entity(), and render_item_entities().
Gfx_RM2_ALPHATEST_NO_ZB
Gfx Gfx_RM2_ALPHATEST_NO_ZB
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_ALPHATEST_ONESIDED
Gfx Gfx_RM2_ALPHATEST_ONESIDED
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_CLOUD
Gfx Gfx_RM2_CLOUD
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_ZB_CLD_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_CLOUD_NO_ZB
Gfx Gfx_RM2_CLOUD_NO_ZB
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_CLD_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_DECAL_OPA
Gfx Gfx_RM2_DECAL_OPA
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_OPA_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_DECAL_OPA_NO_AA
Gfx Gfx_RM2_DECAL_OPA_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_ZB_OPA_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_DECAL_XLU
Gfx Gfx_RM2_DECAL_XLU
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_XLU_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_DECAL_XLU_NO_AA
Gfx Gfx_RM2_DECAL_XLU_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_ZB_XLU_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_INTERSECTING_OPA
Gfx Gfx_RM2_INTERSECTING_OPA
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_OPA_INTER2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_INTERSECTING_OPA_NO_AA
Gfx Gfx_RM2_INTERSECTING_OPA_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_OPA_INTER2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsDPSetCombineMode(G_CC_SHADE, G_CC_SHADE),
    gsSPEndDisplayList(),
}
Gfx_RM2_INTERSECTING_XLU
Gfx Gfx_RM2_INTERSECTING_XLU
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_XLU_INTER2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_PASS_THROUGH
Gfx Gfx_RM2_PASS_THROUGH
Initial value:
= {
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_SURFACE_OPA
Gfx Gfx_RM2_SURFACE_OPA
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_SURFACE_OPA_NO_AA
Gfx Gfx_RM2_SURFACE_OPA_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_ZB_OPA_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_SURFACE_OPA_NO_ZB
Gfx Gfx_RM2_SURFACE_OPA_NO_ZB
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_OPA_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_SURFACE_XLU
Gfx Gfx_RM2_SURFACE_XLU
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_SURFACE_XLU_AA_ZB_ZUPD
Gfx Gfx_RM2_SURFACE_XLU_AA_ZB_ZUPD
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_SURFACE_XLU_NO_AA
Gfx Gfx_RM2_SURFACE_XLU_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM2_SURFACE_XLU_NO_ZB
Gfx Gfx_RM2_SURFACE_XLU_NO_ZB
Initial value:
= {
    gsDPSetRenderMode(G_RM_PASS, G_RM_AA_XLU_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_ALPHATEST
Gfx Gfx_RM3_ALPHATEST[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_ALPHATEST_NO_ZB
Gfx Gfx_RM3_ALPHATEST_NO_ZB
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_ALPHATEST_ONESIDED
Gfx Gfx_RM3_ALPHATEST_ONESIDED
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_TEX_EDGE2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_CLOUD
Gfx Gfx_RM3_CLOUD
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_ZB_CLD_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_CLOUD_NO_ZB
Gfx Gfx_RM3_CLOUD_NO_ZB
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_CLD_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_DECAL_OPA
Gfx Gfx_RM3_DECAL_OPA[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_DECAL_OPA_NO_AA
Gfx Gfx_RM3_DECAL_OPA_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_ZB_OPA_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_DECAL_XLU
Gfx Gfx_RM3_DECAL_XLU[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_XLU_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_DECAL_XLU_NO_AA
Gfx Gfx_RM3_DECAL_XLU_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_ZB_XLU_DECAL2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_INTERSECTING_OPA
Gfx Gfx_RM3_INTERSECTING_OPA[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_INTER2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_INTERSECTING_OPA_NO_AA
Gfx Gfx_RM3_INTERSECTING_OPA_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_INTER2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_INTERSECTING_XLU
Gfx Gfx_RM3_INTERSECTING_XLU[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_XLU_INTER2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_PASS_THROUGH
Gfx Gfx_RM3_PASS_THROUGH
Initial value:
= {
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_SURFACE_OPA
Gfx Gfx_RM3_SURFACE_OPA[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_SURFACE_OPA_NO_AA
Gfx Gfx_RM3_SURFACE_OPA_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_ZB_OPA_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_SURFACE_OPA_NO_ZB
Gfx Gfx_RM3_SURFACE_OPA_NO_ZB
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_OPA_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_SURFACE_XLU
Gfx Gfx_RM3_SURFACE_XLU[]
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_animator(), appendGfx_entity_model(), and draw_entity_model_E().
Gfx_RM3_SURFACE_XLU_AA_ZB_ZUPD
Gfx Gfx_RM3_SURFACE_XLU_AA_ZB_ZUPD
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_SURFACE_XLU_NO_AA
Gfx Gfx_RM3_SURFACE_XLU_NO_AA
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_ZB_XLU_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Gfx_RM3_SURFACE_XLU_NO_ZB
Gfx Gfx_RM3_SURFACE_XLU_NO_ZB
Initial value:
= {
    gsDPSetRenderMode(G_RM_FOG_SHADE_A, G_RM_AA_XLU_SURF2),
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_SHADE | G_FOG | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
gLastRenderTaskCount
s32 gLastRenderTaskCount = 0
Referenced by execute_render_tasks(), and spawn_drops().
ModelRenderModes
Gfx* ModelRenderModes[]
Referenced by appendGfx_model().
mtg_FoundModelNode
BSS ModelNode* mtg_FoundModelNode
Referenced by func_8011B1D8(), and mdl_make_transform_group().
mtg_IterIdx
BSS u16 mtg_IterIdx
Referenced by render_transform_group(), and render_transform_group_node().
mtg_MaxChild
BSS u16 mtg_MaxChild
Referenced by func_8011B1D8(), and mdl_make_transform_group().
mtg_MinChild
BSS u16 mtg_MinChild
Referenced by func_8011B1D8(), and mdl_make_transform_group().
mtg_SearchModelID
BSS u16 mtg_SearchModelID
Referenced by func_8011B1D8(), and mdl_make_transform_group().
ReferenceIdentityMtx
Mtx ReferenceIdentityMtx
Initial value:
= RDP_MATRIX(
    1.000000, 0.000000, 0.000000, 0.000000,
    0.000000, 1.000000, 0.000000, 0.000000,
    0.000000, 0.000000, 1.000000, 0.000000,
    0.000000, 0.000000, 0.000000, 1.000000
)
Referenced by is_identity_fixed_mtx().
RemapTintMaxB
u8 RemapTintMaxB = 255
Referenced by appendGfx_model(), mdl_get_remap_tint_params(), and mdl_set_remap_tint_params().
RemapTintMaxG
u8 RemapTintMaxG = 255
Referenced by appendGfx_model(), mdl_get_remap_tint_params(), and mdl_set_remap_tint_params().
RemapTintMaxR
u8 RemapTintMaxR = 255
Referenced by appendGfx_model(), mdl_get_remap_tint_params(), and mdl_set_remap_tint_params().
RemapTintMinB
u8 RemapTintMinB = 0
Referenced by appendGfx_model(), mdl_get_remap_tint_params(), and mdl_set_remap_tint_params().
RemapTintMinG
u8 RemapTintMinG = 0
Referenced by appendGfx_model(), mdl_get_remap_tint_params(), and mdl_set_remap_tint_params().
RemapTintMinR
u8 RemapTintMinR = 0
Referenced by appendGfx_model(), mdl_get_remap_tint_params(), and mdl_set_remap_tint_params().
RenderTaskBasePriorities
s32 RenderTaskBasePriorities[]
Referenced by queue_render_task().
RenderTaskCount
BSS s32 RenderTaskCount
Referenced by clear_render_tasks(), clear_render_tasks_alt(), execute_render_tasks(), and queue_render_task().
RenderTaskListIdx
BSS s32 RenderTaskListIdx
Referenced by clear_render_tasks(), clear_render_tasks_alt(), execute_render_tasks(), and queue_render_task().
RenderTaskLists
BSS RenderTask* RenderTaskLists[3]
Referenced by clear_render_tasks(), clear_render_tasks_alt(), execute_render_tasks(), and queue_render_task().
ShroudTintAmt
u8 ShroudTintAmt = 0
Referenced by appendGfx_model(), clear_model_data(), mdl_get_shroud_tint_params(), and mdl_set_shroud_tint_params().
ShroudTintB
u8 ShroudTintB = 0
Referenced by appendGfx_model(), clear_model_data(), mdl_get_shroud_tint_params(), and mdl_set_shroud_tint_params().
ShroudTintG
u8 ShroudTintG = 0
Referenced by appendGfx_model(), clear_model_data(), mdl_get_shroud_tint_params(), and mdl_set_shroud_tint_params().
ShroudTintR
u8 ShroudTintR = 0
Referenced by appendGfx_model(), clear_model_data(), mdl_get_shroud_tint_params(), and mdl_set_shroud_tint_params().
SolidCombineModes
Gfx SolidCombineModes[][5]
Referenced by appendGfx_model(), and make_texture_gfx().
texPannerAuxU
BSS s32 texPannerAuxU[MAX_TEX_PANNERS]
Referenced by appendGfx_model(), clear_model_data(), and set_aux_pan_u().
texPannerAuxV
BSS s32 texPannerAuxV[MAX_TEX_PANNERS]
Referenced by appendGfx_model(), clear_model_data(), and set_aux_pan_v().
texPannerMainU
BSS s32 texPannerMainU[MAX_TEX_PANNERS]
Referenced by appendGfx_model(), clear_model_data(), and set_main_pan_u().
texPannerMainV
BSS s32 texPannerMainV[MAX_TEX_PANNERS]
Referenced by appendGfx_model(), clear_model_data(), and set_main_pan_v().
TextureHandles
TextureHandle TextureHandles[128]
Referenced by appendGfx_model(), load_texture_by_name(), load_texture_variants(), and mdl_load_all_textures().
TextureHeap
Addr TextureHeap extern
TextureHeapBase
void* TextureHeapBase = (void*) &TextureHeap
Referenced by mdl_get_next_texture_address(), and mdl_load_all_textures().
TextureHeapPos
BSS void* TextureHeapPos
Referenced by load_texture_impl(), mdl_get_next_texture_address(), and mdl_load_all_textures().
TreeIterPos
BSS s32 TreeIterPos
Referenced by appendGfx_model_group(), func_80117D00(), func_8011B1D8(), load_data_for_models(), load_model_transforms(), load_next_model_textures(), load_texture_by_name(), mdl_create_model(), mdl_load_all_textures(), and mdl_make_transform_group().
wBackgroundTintMode
BSS s8 wBackgroundTintMode
Referenced by clear_model_data(), and init_model_data().
wCustomModelGfx
BSS ModelCustomGfxList wCustomModelGfx
Referenced by clear_model_data(), and init_model_data().
wCustomModelGfxBuilders
BSS ModelCustomGfxBuilderList wCustomModelGfxBuilders
Referenced by clear_model_data(), and init_model_data().
wFogSettings
BSS FogSettings wFogSettings
Referenced by clear_model_data(), and init_model_data().
wModelList
BSS ModelList wModelList
Referenced by clear_model_data(), and init_model_data().
wModelLocalVtxBuffers
BSS ModelLocalVertexCopyList wModelLocalVtxBuffers
Referenced by clear_model_data(), and init_model_data().
wModelTreeNodeInfo
BSS ModelTreeInfoList wModelTreeNodeInfo
Referenced by clear_model_data(), and init_model_data().
wModelTreeRoot
BSS ModelNode* wModelTreeRoot
Referenced by clear_model_data(), and init_model_data().
wTransformGroups
BSS ModelTransformGroupList wTransformGroups
Referenced by clear_model_data(), and init_model_data().