papermario: src/effects/motion_blur_flame.c File Reference
motion_blur_flame.c File Reference
Data Structures
struct UnkStruct
Functions
void motion_blur_flame_init (EffectInstance *effect)
void motion_blur_flame_update (EffectInstance *effect)
void motion_blur_flame_render (EffectInstance *effect)
void motion_blur_flame_appendGfx (void *effect)
EffectInstance * motion_blur_flame_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00A2234 (void)
Variables
Gfx D_09000200_3A35D0 []
Gfx D_090002A8_3A3678 []
Gfx D_09000358_3A3728 []
Gfx * D_E00A29D0 [] = { D_09000200_3A35D0, D_090002A8_3A3678, D_09000358_3A3728 }
UnkStruct D_E00A29DC []
s32 D_E00A2A24 [] = { 100, 60, 30, 10, 0, 0, 0 }
Data Structure Documentation
UnkStruct
struct UnkStruct
Data Fields
Gfx * displayList
s16 height
u8 sizeScale
s32 unk_00
u8 unk_00
s8 unk_00
u8 unk_01
s8 unk_01
u8 unk_02
s16 unk_02
u8 unk_03
s32 unk_04
Gfx * unk_04
s16 unk_04
s16 unk_06
f32 unk_08
Gfx * unk_08
s32 unk_08
char unk_09[1]
f32 unk_0C
s32 unk_10
s32 unk_14
s16 width
s16 x
s16 y
Function Documentation
func_E00A2234()
void func_E00A2234 (void)
motion_blur_flame_appendGfx()
void motion_blur_flame_appendGfx (void * effect)
Referenced by motion_blur_flame_render().
motion_blur_flame_init()
void motion_blur_flame_init (EffectInstance * effect)
Referenced by motion_blur_flame_main().
motion_blur_flame_main()
EffectInstance * motion_blur_flame_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
motion_blur_flame_render()
void motion_blur_flame_render (EffectInstance * effect)
Referenced by motion_blur_flame_main().
motion_blur_flame_update()
void motion_blur_flame_update (EffectInstance * effect)
Referenced by motion_blur_flame_main().
Variable Documentation
D_09000200_3A35D0
Gfx D_09000200_3A35D0[] extern
D_090002A8_3A3678
Gfx D_090002A8_3A3678[] extern
D_09000358_3A3728
Gfx D_09000358_3A3728[] extern
D_E00A29D0
Gfx* D_E00A29D0[] = { D_09000200_3A35D0, D_090002A8_3A3678, D_09000358_3A3728 }
Referenced by motion_blur_flame_appendGfx().
D_E00A29DC
UnkStruct D_E00A29DC[]
Initial value:
= {
    { 16, 16, 1.0f, 1.0f, 8, 8 },
    { 16, 16, 1.0f, 1.0f, 8, 8 },
    { 16, 16, 1.0f, 1.0f, 8, 8 },
}
Referenced by motion_blur_flame_appendGfx().
D_E00A2A24
s32 D_E00A2A24[] = { 100, 60, 30, 10, 0, 0, 0 }
Referenced by motion_blur_flame_appendGfx().