papermario: src/effects/moving_cloud.c File Reference
moving_cloud.c File Reference
Functions
void moving_cloud_init (EffectInstance *effect)
void moving_cloud_update (EffectInstance *effect)
void moving_cloud_render (EffectInstance *effect)
void moving_cloud_appendGfx (void *effect)
EffectInstance * moving_cloud_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, f32 arg8)
Variables
Gfx D_09000100_3E1DD0 []
Gfx D_090001E8_3E1EB8 []
Gfx * D_E00E8630 [] = { D_090001E8_3E1EB8 }
Gfx * D_E00E8634 [] = { D_09000100_3E1DD0 }
Function Documentation
moving_cloud_appendGfx()
void moving_cloud_appendGfx (void * effect)
Referenced by moving_cloud_render().
moving_cloud_init()
void moving_cloud_init (EffectInstance * effect)
Referenced by moving_cloud_main().
moving_cloud_main()
EffectInstance * moving_cloud_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, f32 arg8)
moving_cloud_render()
void moving_cloud_render (EffectInstance * effect)
Referenced by moving_cloud_main().
moving_cloud_update()
void moving_cloud_update (EffectInstance * effect)
Referenced by moving_cloud_main().
Variable Documentation
D_09000100_3E1DD0
Gfx D_09000100_3E1DD0[] extern
D_090001E8_3E1EB8
Gfx D_090001E8_3E1EB8[] extern
D_E00E8630
Gfx* D_E00E8630[] = { D_090001E8_3E1EB8 }
Referenced by moving_cloud_appendGfx().
D_E00E8634
Gfx* D_E00E8634[] = { D_09000100_3E1DD0 }
Referenced by moving_cloud_appendGfx().