papermario: src/audio/mseq_player.c File Reference
mseq_player.c File Reference
Macros
#define TRACK_ID_DRUM 9
Enumerations
enum MseqMode { MSEQ_MODE_PLAYING = 0 , MSEQ_MODE_RESUMING = 1 , MSEQ_MODE_STOPPED = 2 , MSEQ_MODE_PAUSING = 3 }
enum MseqFadeState { MSEQ_FADE_IN = 0 , MSEQ_FADE_OUT = 1 , MSEQ_FADE_OUT_PAUSING = 2 }
enum MseqPlayState { MSEQ_PLAYER_PLAYING = 0 , MSEQ_PLAYER_STOPPED = 1 , MSEQ_PLAYER_STOPPING = 2 }
enum MseqTrackFlags { MSEQ_TRACK_RESUMABLE = 1 }
enum MseqCommand {
MSEQ_CMD_80_STOP_SOUND = 0x80 , MSEQ_CMD_90_PLAY_SOUND = 0x90 , MSEQ_CMD_A0_SET_VOLUME_PAN = 0xA0 , MSEQ_CMD_B0_MULTI = 0xB0 ,
MSEQ_CMD_C0_SET_INSTRUMENT = 0xC0 , MSEQ_CMD_E0_TUNING = 0xE0 , MSEQ_CMD_SUB_66_START_LOOP = 0x66 , MSEQ_CMD_SUB_67_END_LOOP = 0x67 ,
MSEQ_CMD_SUB_68_SET_REVERB = 0x68 , MSEQ_CMD_SUB_69_SET_RESUMABLE = 0x69
}
Functions
void au_mseq_manager_init (AmbienceManager *manager, s8 priority, s8 busID, AuGlobals *globals)
AuResult au_mseq_check_player_index (u32 index)
void au_mseq_load_tracks_fade (s32 arg0, s32 arg1)
void au_mseq_set_disabled (s32 index, s32 disable)
AuResult au_mseq_start (s32 index, s32 time)
void au_mseq_fade_setup (AmbiencePlayer *player)
void au_mseq_pause (s32 index, s32 time)
void au_mseq_resume (s32 index, s32 time)
void au_mseq_stop_quick (s32 index)
void au_mseq_stop_slow (s32 index, s32 time)
void au_mseq_set_volume (s32 index, s32 time, s32 volume)
AuResult au_mseq_check_stopped (s32 index)
void au_mseq_play_sequence (AmbienceManager *manager, MSEQHeader *mseqFile, s32 index)
void au_mseq_manager_audio_frame_update (AmbienceManager *manager)
void au_mseq_load_track_fade_info (AmbienceManager *manager, AmbiencePlayer *player)
void au_mseq_player_update (AmbienceManager *manager, AmbiencePlayer *player)
u8 au_mseq_read_next (AmbiencePlayer *state)
void au_mseq_player_stop (AmbienceManager *manager, AmbiencePlayer *player)
void au_mseq_save_voices (AmbienceManager *manager, AmbiencePlayer *player)
void au_mseq_restore_voices (AmbienceManager *manager, AmbiencePlayer *player)
Variables
u8 BlankMseqData []
Macro Definition Documentation
TRACK_ID_DRUM
#define TRACK_ID_DRUM 9
Referenced by au_mseq_player_update().
Enumeration Type Documentation
MseqCommand
enum MseqCommand
Enumerator
MSEQ_CMD_80_STOP_SOUND
MSEQ_CMD_90_PLAY_SOUND
MSEQ_CMD_A0_SET_VOLUME_PAN
MSEQ_CMD_B0_MULTI
MSEQ_CMD_C0_SET_INSTRUMENT
MSEQ_CMD_E0_TUNING
MSEQ_CMD_SUB_66_START_LOOP
MSEQ_CMD_SUB_67_END_LOOP
MSEQ_CMD_SUB_68_SET_REVERB
MSEQ_CMD_SUB_69_SET_RESUMABLE
MseqFadeState
enum MseqFadeState
Enumerator
MSEQ_FADE_IN
MSEQ_FADE_OUT
MSEQ_FADE_OUT_PAUSING
MseqMode
enum MseqMode
Enumerator
MSEQ_MODE_PLAYING
MSEQ_MODE_RESUMING
MSEQ_MODE_STOPPED
MSEQ_MODE_PAUSING
MseqPlayState
enum MseqPlayState
Enumerator
MSEQ_PLAYER_PLAYING
MSEQ_PLAYER_STOPPED
MSEQ_PLAYER_STOPPING
MseqTrackFlags
enum MseqTrackFlags
Enumerator
MSEQ_TRACK_RESUMABLE
Function Documentation
au_mseq_check_player_index()
AuResult au_mseq_check_player_index (u32 index)
Referenced by snd_ambient_disable(), snd_ambient_enable(), snd_ambient_fade_out(), snd_ambient_is_stopped(), snd_ambient_pause(), snd_ambient_play(), snd_ambient_resume(), snd_ambient_set_volume(), snd_ambient_stop_quick(), and snd_ambient_stop_slow().
au_mseq_check_stopped()
AuResult au_mseq_check_stopped (s32 index)
Referenced by snd_ambient_is_stopped().
au_mseq_fade_setup()
void au_mseq_fade_setup (AmbiencePlayer * player)
Referenced by au_mseq_manager_audio_frame_update(), and au_mseq_start().
au_mseq_load_track_fade_info()
void au_mseq_load_track_fade_info (AmbienceManager * manager, AmbiencePlayer * player)
Referenced by au_mseq_manager_audio_frame_update().
au_mseq_load_tracks_fade()
void au_mseq_load_tracks_fade (s32 arg0, s32 arg1)
Referenced by snd_ambient_fade_out().
au_mseq_manager_audio_frame_update()
void au_mseq_manager_audio_frame_update (AmbienceManager * manager)
Referenced by au_update_clients_for_audio_frame().
au_mseq_manager_init()
void au_mseq_manager_init (AmbienceManager * manager, s8 priority, s8 busID, AuGlobals * globals)
Referenced by au_engine_init().
au_mseq_pause()
void au_mseq_pause (s32 index, s32 time)
Referenced by snd_ambient_pause().
au_mseq_play_sequence()
void au_mseq_play_sequence (AmbienceManager * manager, MSEQHeader * mseqFile, s32 index)
Referenced by au_mseq_start().
au_mseq_player_stop()
void au_mseq_player_stop (AmbienceManager * manager, AmbiencePlayer * player)
Referenced by au_mseq_manager_audio_frame_update(), and au_mseq_player_update().
au_mseq_player_update()
void au_mseq_player_update (AmbienceManager * manager, AmbiencePlayer * player)
Referenced by au_mseq_manager_audio_frame_update().
au_mseq_read_next()
u8 au_mseq_read_next (AmbiencePlayer * state)
Referenced by au_mseq_player_update().
au_mseq_restore_voices()
void au_mseq_restore_voices (AmbienceManager * manager, AmbiencePlayer * player)
Referenced by au_mseq_manager_audio_frame_update().
au_mseq_resume()
void au_mseq_resume (s32 index, s32 time)
Referenced by snd_ambient_resume().
au_mseq_save_voices()
void au_mseq_save_voices (AmbienceManager * manager, AmbiencePlayer * player)
Referenced by au_mseq_manager_audio_frame_update().
au_mseq_set_disabled()
void au_mseq_set_disabled (s32 index, s32 disable)
Referenced by snd_ambient_disable(), and snd_ambient_enable().
au_mseq_set_volume()
void au_mseq_set_volume (s32 index, s32 time, s32 volume)
Referenced by snd_ambient_set_volume().
au_mseq_start()
AuResult au_mseq_start (s32 index, s32 time)
Referenced by snd_ambient_play().
au_mseq_stop_quick()
void au_mseq_stop_quick (s32 index)
Referenced by snd_ambient_stop_quick().
au_mseq_stop_slow()
void au_mseq_stop_slow (s32 index, s32 time)
Referenced by snd_ambient_stop_slow().
Variable Documentation
BlankMseqData
u8 BlankMseqData[] extern
Referenced by au_mseq_player_update(), and au_mseq_stop_quick().