papermario: src/msg.c File Reference
msg.c File Reference
Macros
#define MSG_ROM_START 0x1B83000
#define CHOICE_POINTER_MOVE_RATE 6.0
#define CHAR_SPACE_MULTIPLIER 0.6
Typedefs
typedef MessageImageData * MessageImageDataList[1]
Enumerations
enum RewindArrowStates {
REWIND_ARROW_STATE_INIT = 0 , REWIND_ARROW_STATE_GROW = 1 , REWIND_ARROW_STATE_NEUTRAL = 2 , REWIND_ARROW_STATE_CHANGE_COLOR = 3 ,
REWIND_ARROW_STATE_CHANGE_COLOR_BACK = 4
}
Functions
ALIGNED (8)
s32 draw_image_with_clipping (IMG_PTR raster, s32 width, s32 height, s32 fmt, s32 bitDepth, s16 posX, s16 posY, u16 clipULx, u16 clipULy, u16 clipLRx, u16 clipRLy)
s32 _update_message (MessagePrintState *printer)
void msg_copy_to_print_buffer (MessagePrintState *printer, s32 arg1, s32 arg2)
void initialize_printer (MessagePrintState *printer, s32 arg1, s32 arg2)
MessagePrintState * _msg_get_printer_for_msg (s32 msgID, s32 *donePrintingWriteback, s32 arg2)
void msg_update_rewind_arrow (s32)
void msg_draw_rewind_arrow (s32)
void msg_draw_choice_pointer (MessagePrintState *printer)
void draw_message_window (MessagePrintState *printer)
void appendGfx_message (MessagePrintState *, s16, s16, u16, u16, u16, u8)
void appendGfx_msg_prim_rect (u8 r, u8 g, u8 b, u8 a, u16 ulX, u16 ulY, u16 lrX, u16 lrY)
void msg_reset_gfx_state (void)
void msg_draw_char (MessagePrintState *printer, MessageDrawState *drawState, s32 charIndex, s32 palette, s32 posX, s32 posY)
void msg_draw_prim_rect (u8 r, u8 g, u8 b, u8 a, u16 posX, u16 posY, u16 sizeX, u16 sizeY)
void msg_draw_speech_arrow (MessagePrintState *printer)
void msg_draw_frame (s32 posX, s32 posY, s32 sizeX, s32 sizeY, s32 style, s32 palette, s32 fading, s32 bgAlpha, s32 frameAlpha)
void msg_draw_speech_bubble (MessagePrintState *printer, s16 posX, s16 posY, s16 straightWidth, s16 curveWidth, s16 height, f32 scaleX, f32 scaleY, u8 opacity, s32 arg9)
void clear_character_set (void)
void clear_printers (void)
void load_font_data (Addr offset, u16 size, void *dest)
void load_font (s32 font)
void update_messages (void)
void render_messages (void)
void msg_play_speech_sound (MessagePrintState *printer, u8 character)
void dma_load_msg (u32 msgID, void *dest)
s8 * load_message_to_buffer (s32 msgID)
MessagePrintState * msg_get_printer_for_msg (s32 msgID, s32 *donePrintingWriteback)
s32 msg_printer_load_msg (s32 msgID, MessagePrintState *printer)
void msg_printer_set_origin_pos (MessagePrintState *msgPrintState, s32 x, s32 y)
s32 cancel_message (MessagePrintState *msgPrintState)
void set_message_images (MessageImageData *images)
void set_message_text_var (s32 msgID, s32 index)
void set_message_int_var (s32 value, s32 index)
void close_message (MessagePrintState *msgPrintState)
s32 msg_get_print_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u8 flags)
s32 msg_get_draw_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u16 flags)
void get_msg_properties (s32 msgID, s32 *height, s32 *width, s32 *maxLineChars, s32 *numLines, s32 *maxLinesPerPage, s32 *numSpaces, u16 charset)
s32 get_msg_width (s32 msgID, u16 charset)
s32 get_msg_lines (s32 msgID)
void draw_msg (s32 msgID, s32 posX, s32 posY, s32 opacity, s32 palette, u8 style)
void draw_digit (IMG_PTR img, s32 charset, s32 posX, s32 posY)
void draw_number (s32 value, s32 x, s32 y, s32 charset, s32 palette, s32 opacity, u16 style)
Variables
s32 D_8014C280 [] = { 0x028001E0, 0x01FF0000, 0x028001E0, 0x01FF0000 }
u8 MessagePlural [] = { MSG_CHAR_LOWER_S, MSG_CHAR_READ_END }
u8 MessageSingular [] = { MSG_CHAR_READ_ENDL, MSG_CHAR_READ_END }
s16 gNextMessageBuffer = 0
Gfx D_8014C2D8 []
SHIFT_BSS s32 gMsgBGScrollAmtX
SHIFT_BSS u16 gMsgGlobalWaveCounter
SHIFT_BSS MessageImageDataList gMsgVarImages
SHIFT_BSS s32 gMsgBGScrollAmtY
SHIFT_BSS u8 * D_8015131C
SHIFT_BSS Gfx * D_80151338
SHIFT_BSS char gMessageBuffers [2][1024]
SHIFT_BSS u8 gMessageMsgVars [3][32]
SHIFT_BSS s16 D_80155C98
SHIFT_BSS Mtx gMessageWindowProjMatrix [2]
SHIFT_BSS MessageDrawState D_80155D20
SHIFT_BSS MessageDrawState * msg_drawState
SHIFT_BSS IMG_BIN D_80159B50 [0x200]
SHIFT_BSS PAL_BIN D_8015C7E0 [0x10]
SHIFT_BSS MessagePrintState gMessagePrinters [3]
s16 MsgStyleVerticalLineOffsets []
IMG_BIN ui_msg_bubble_left_png []
IMG_BIN ui_msg_bubble_mid_png []
IMG_BIN ui_msg_bubble_right_png []
IMG_BIN ui_msg_arrow_png []
unsigned char ui_msg_palettes [16][32]
IMG_BIN ui_msg_sign_corner_topleft_png []
IMG_BIN ui_msg_sign_corner_topright_png []
IMG_BIN ui_msg_sign_corner_bottomleft_png []
IMG_BIN ui_msg_sign_corner_bottomright_png []
IMG_BIN ui_msg_lamppost_corner_bottomright_png []
IMG_BIN ui_msg_sign_side_top_png []
IMG_BIN ui_msg_sign_side_left_png []
IMG_BIN ui_msg_sign_side_right_png []
IMG_BIN ui_msg_sign_side_bottom_png []
IMG_BIN ui_msg_sign_fill_png []
PAL_BIN ui_msg_sign_pal []
PAL_BIN ui_msg_lamppost_pal []
IMG_BIN ui_msg_background_png []
IMG_BIN ui_msg_rewind_arrow_png []
PAL_BIN ui_msg_rewind_arrow_pal []
IMG_BIN ui_msg_star_png []
IMG_BIN ui_msg_star_silhouette_png []
IMG_BIN D_802ED550 []
PAL_BIN D_802ED670 []
IMG_BIN MsgCharImgTitle []
IMG_BIN MsgCharImgNormal []
MessageCharset * MsgCharsets [5]
IMG_BIN MsgCharImgSubtitle []
PAL_BIN D_802F4560 [80][8]
s32 gMessageBoxFrameParts [2][16]
IMG_BIN ui_point_right_png []
PAL_BIN ui_point_right_pal []
MessageNumber gMsgNumbers []
Gfx gMsgDlistInitDrawNumber []
s32 gItemIconRasterOffsets []
s32 gItemIconPaletteOffsets []
s32 MsgLetterRasterOffsets []
s32 MsgLetterPaletteOffsets []
MsgVoice MsgVoices []
Macro Definition Documentation
CHAR_SPACE_MULTIPLIER
#define CHAR_SPACE_MULTIPLIER 0.6
Referenced by msg_get_draw_char_width(), and msg_get_print_char_width().
CHOICE_POINTER_MOVE_RATE
#define CHOICE_POINTER_MOVE_RATE 6.0
Referenced by msg_draw_choice_pointer().
MSG_ROM_START
#define MSG_ROM_START 0x1B83000
Referenced by dma_load_msg().
Typedef Documentation
MessageImageDataList
typedef MessageImageData* MessageImageDataList[1]
Enumeration Type Documentation
RewindArrowStates
enum RewindArrowStates
Enumerator
REWIND_ARROW_STATE_INIT
REWIND_ARROW_STATE_GROW
REWIND_ARROW_STATE_NEUTRAL
REWIND_ARROW_STATE_CHANGE_COLOR
REWIND_ARROW_STATE_CHANGE_COLOR_BACK
Function Documentation
_msg_get_printer_for_msg()
MessagePrintState * _msg_get_printer_for_msg (s32 msgID, s32 * donePrintingWriteback, s32 arg2)
Referenced by msg_get_printer_for_msg().
_update_message()
s32 _update_message (MessagePrintState * printer)
Referenced by update_messages().
ALIGNED()
ALIGNED (8)
appendGfx_message()
void appendGfx_message (MessagePrintState * printer, s16 posX, s16 posY, u16 additionalOffsetX, u16 additionalOffsetY, u16 flag, u8 alpha)
Referenced by draw_message_window(), draw_msg(), and drawbox_message_delegate().
appendGfx_msg_prim_rect()
void appendGfx_msg_prim_rect (u8 r, u8 g, u8 b, u8 a, u16 ulX, u16 ulY, u16 lrX, u16 lrY)
Referenced by msg_draw_prim_rect().
cancel_message()
s32 cancel_message (MessagePrintState * msgPrintState)
Referenced by cancel_current_message().
clear_character_set()
void clear_character_set (void)
Referenced by load_engine_data().
clear_printers()
void clear_printers (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_title_screen(), state_step_demo(), state_step_intro(), and state_step_startup().
close_message()
void close_message (MessagePrintState * msgPrintState)
Referenced by _show_message(), and entity_SaveBlock_wait_for_close_choice().
dma_load_msg()
void dma_load_msg (u32 msgID, void * dest)
Referenced by credits_load_message(), draw_msg(), get_msg_properties(), load_message_to_buffer(), and set_message_text_var().
draw_digit()
void draw_digit (IMG_PTR img, s32 charset, s32 posX, s32 posY)
Referenced by draw_number().
draw_image_with_clipping()
s32 draw_image_with_clipping (IMG_PTR raster, s32 width, s32 height, s32 fmt, s32 bitDepth, s16 posX, s16 posY, u16 clipULx, u16 clipULy, u16 clipLRx, u16 clipRLy)
Referenced by msg_draw_choice_pointer().
draw_message_window()
void draw_message_window (MessagePrintState * printer)
Referenced by render_messages().
draw_msg()
void draw_msg (s32 msgID, s32 posX, s32 posY, s32 opacity, s32 palette, u8 style)
draw_number()
void draw_number (s32 value, s32 x, s32 y, s32 charset, s32 palette, s32 opacity, u16 style)
Referenced by appendGfx_records_impl(), appendGfx_score_display(), coin_counter_draw_content(), draw_record_display(), draw_shop_items(), filemenu_draw_contents_file_info(), filemenu_draw_contents_file_title(), filemenu_info_draw_message_contents(), filemenu_yesno_draw_prompt_contents(), func_800F4D28(), func_802A3C98(), pause_badges_draw_contents(), pause_partners_draw_movelist(), pause_stats_draw_contents(), popup_menu_draw_menu_contents(), and popup_menu_draw_title_contents().
get_msg_lines()
s32 get_msg_lines (s32 msgID)
Referenced by btl_message_popup_draw_content(), btl_show_message_popup(), btl_submenu_moves_update(), draw_content_pickup_item_header(), draw_merlee_message(), draw_merlee_message_string(), func_800F4C1C(), func_801363A0(), func_802A4534(), popup_menu_update(), and UpdateIntroMessages().
get_msg_properties()
void get_msg_properties (s32 msgID, s32 * height, s32 * width, s32 * maxLineChars, s32 * numLines, s32 * maxLinesPerPage, s32 * numSpaces, u16 charset)
Referenced by _msg_get_printer_for_msg(), credits_load_message(), credits_update_line(), draw_msg(), get_msg_lines(), get_msg_width(), pause_handle_input(), and pause_tutorial_draw_contents().
get_msg_width()
s32 get_msg_width (s32 msgID, u16 charset)
initialize_printer()
void initialize_printer (MessagePrintState * printer, s32 arg1, s32 arg2)
Referenced by _msg_get_printer_for_msg(), clear_printers(), and draw_msg().
load_font()
void load_font (s32 font)
Referenced by clear_printers().
load_font_data()
void load_font_data (Addr offset, u16 size, void * dest)
Referenced by filemenu_draw_char(), load_font(), and msg_draw_char().
load_message_to_buffer()
s8 * load_message_to_buffer (s32 msgID)
Referenced by _msg_get_printer_for_msg(), and msg_printer_load_msg().
msg_copy_to_print_buffer()
void msg_copy_to_print_buffer (MessagePrintState * printer, s32 arg1, s32 arg2)
Referenced by _update_message(), and draw_msg().
msg_draw_char()
void msg_draw_char (MessagePrintState * printer, MessageDrawState * drawState, s32 charIndex, s32 palette, s32 posX, s32 posY)
Referenced by appendGfx_message().
msg_draw_choice_pointer()
void msg_draw_choice_pointer (MessagePrintState * printer)
Referenced by render_messages().
msg_draw_frame()
void msg_draw_frame (s32 posX, s32 posY, s32 sizeX, s32 sizeY, s32 style, s32 palette, s32 fading, s32 bgAlpha, s32 frameAlpha)
Referenced by appendGfx_records_impl(), and draw_record_display().
msg_draw_prim_rect()
void msg_draw_prim_rect (u8 r, u8 g, u8 b, u8 a, u16 posX, u16 posY, u16 sizeX, u16 sizeY)
Referenced by appendGfx_message(), and msg_draw_speech_bubble().
msg_draw_rewind_arrow()
void msg_draw_rewind_arrow (s32 printerIndex)
Referenced by render_messages().
msg_draw_speech_arrow()
void msg_draw_speech_arrow (MessagePrintState * printer)
Referenced by appendGfx_message().
msg_draw_speech_bubble()
void msg_draw_speech_bubble (MessagePrintState * printer, s16 posX, s16 posY, s16 straightWidth, s16 curveWidth, s16 height, f32 scaleX, f32 scaleY, u8 opacity, s32 arg9)
Referenced by appendGfx_message().
msg_get_draw_char_width()
s32 msg_get_draw_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u16 flags)
Referenced by appendGfx_message(), and msg_get_glyph().
msg_get_print_char_width()
s32 msg_get_print_char_width (s32 character, s32 charset, s32 variation, f32 msgScale, s32 overrideCharWidth, u8 flags)
Referenced by credits_update_line(), filemenu_draw_contents_choose_name(), filemenu_draw_file_name(), and get_msg_properties().
msg_get_printer_for_msg()
MessagePrintState * msg_get_printer_for_msg (s32 msgID, s32 * donePrintingWriteback)
Referenced by _show_message(), entity_HeartBlock_show_tutorial_message(), entity_SaveBlock_show_choice_message(), entity_SaveBlock_show_tutorial_message(), popup_menu_update(), and update_item_entity_pickup().
msg_play_speech_sound()
void msg_play_speech_sound (MessagePrintState * printer, u8 character)
Referenced by msg_copy_to_print_buffer().
msg_printer_load_msg()
s32 msg_printer_load_msg (s32 msgID, MessagePrintState * printer)
Referenced by _show_message(), and entity_SaveBlock_show_result_message().
msg_printer_set_origin_pos()
void msg_printer_set_origin_pos (MessagePrintState * msgPrintState, s32 x, s32 y)
Referenced by _show_message(), popup_menu_update(), and update_item_entity_pickup().
msg_reset_gfx_state()
void msg_reset_gfx_state (void)
Referenced by appendGfx_message().
msg_update_rewind_arrow()
void msg_update_rewind_arrow (s32 printerIndex)
Referenced by render_messages().
render_messages()
void render_messages (void)
Referenced by gfx_draw_frame().
set_message_images()
void set_message_images (MessageImageData * images)
set_message_int_var()
void set_message_int_var (s32 value, s32 index)
Referenced by btl_message_popup_draw_content(), btl_show_message_popup(), popup_menu_draw_menu_contents(), shop_owner_buy_dialog(), and shop_owner_continue_speech_with_quantity().
set_message_text_var()
void set_message_text_var (s32 msgID, s32 index)
Referenced by btl_message_popup_draw_content(), btl_show_message_popup(), draw_content_pickup_item_header(), func_801363A0(), shop_owner_buy_dialog(), and shop_owner_continue_speech_with_quantity().
update_messages()
void update_messages (void)
Referenced by step_game_loop().
Variable Documentation
D_8014C280
s32 D_8014C280[] = { 0x028001E0, 0x01FF0000, 0x028001E0, 0x01FF0000 }
Referenced by render_messages().
D_8014C2D8
Gfx D_8014C2D8[]
Initial value:
= {
    gsDPSetCycleType(G_CYC_2CYCLE),
    gsSPClearGeometryMode(G_CULL_BOTH | G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_SHADING_SMOOTH),
    gsDPSetColorDither(G_CD_DISABLE),
    gsDPSetAlphaDither(G_AD_DISABLE),
    gsDPSetAlphaCompare(G_AC_NONE),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetTexturePersp(G_TP_PERSP),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetTextureFilter(G_TF_AVERAGE),
    gsDPSetRenderMode(IM_RD | CVG_DST_SAVE | ZMODE_XLU | FORCE_BL | G_RM_PASS, IM_RD | CVG_DST_SAVE | ZMODE_XLU |
                      FORCE_BL | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)),
    gsDPSetCombineMode(PM_CC_MSG_UP_ARROW, G_CC_PASS2),
    gsSPEndDisplayList(),
}
Referenced by msg_update_rewind_arrow().
D_8015131C
SHIFT_BSS u8* D_8015131C
Referenced by appendGfx_message(), and msg_copy_to_print_buffer().
D_80151338
SHIFT_BSS Gfx* D_80151338
Referenced by appendGfx_message(), and clear_printers().
D_80155C98
SHIFT_BSS s16 D_80155C98
Referenced by clear_character_set(), and load_font().
D_80155D20
SHIFT_BSS MessageDrawState D_80155D20
Referenced by appendGfx_message().
D_80159B50
SHIFT_BSS IMG_BIN D_80159B50[0x200]
Referenced by appendGfx_message(), and msg_copy_to_print_buffer().
D_8015C7E0
SHIFT_BSS PAL_BIN D_8015C7E0[0x10]
Referenced by appendGfx_message(), and msg_copy_to_print_buffer().
D_802ED550
IMG_BIN D_802ED550[] extern
D_802ED670
PAL_BIN D_802ED670[] extern
D_802F4560
PAL_BIN D_802F4560[80][8] extern
Referenced by draw_number(), and load_font().
gItemIconPaletteOffsets
s32 gItemIconPaletteOffsets[] extern
Referenced by msg_copy_to_print_buffer().
gItemIconRasterOffsets
s32 gItemIconRasterOffsets[] extern
Referenced by msg_copy_to_print_buffer().
gMessageBoxFrameParts
s32 gMessageBoxFrameParts[2][16] extern
gMessageBuffers
SHIFT_BSS char gMessageBuffers[2][1024]
Referenced by load_message_to_buffer().
gMessageMsgVars
SHIFT_BSS u8 gMessageMsgVars[3][32]
Referenced by clear_printers(), get_msg_properties(), msg_copy_to_print_buffer(), set_message_int_var(), and set_message_text_var().
gMessagePrinters
SHIFT_BSS MessagePrintState gMessagePrinters[3]
Referenced by _msg_get_printer_for_msg(), clear_printers(), msg_draw_rewind_arrow(), msg_update_rewind_arrow(), render_messages(), and update_messages().
gMessageWindowProjMatrix
SHIFT_BSS Mtx gMessageWindowProjMatrix[2]
Referenced by render_messages().
gMsgBGScrollAmtX
SHIFT_BSS s32 gMsgBGScrollAmtX
Referenced by clear_printers(), msg_draw_frame(), and update_messages().
gMsgBGScrollAmtY
SHIFT_BSS s32 gMsgBGScrollAmtY
Referenced by clear_printers(), msg_draw_frame(), and update_messages().
gMsgDlistInitDrawNumber
Gfx gMsgDlistInitDrawNumber[]
Initial value:
= {
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetColorDither(G_CD_DISABLE),
    gsDPSetAlphaDither(G_AD_DISABLE),
    gsDPSetCombineKey(G_CK_NONE),
    gsDPSetAlphaCompare(G_AC_NONE),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsSPEndDisplayList(),
}
Referenced by draw_number().
gMsgGlobalWaveCounter
SHIFT_BSS u16 gMsgGlobalWaveCounter
Referenced by appendGfx_message(), clear_printers(), and update_messages().
gMsgNumbers
MessageNumber gMsgNumbers[]
Referenced by draw_digit(), and draw_number().
gMsgVarImages
SHIFT_BSS MessageImageDataList gMsgVarImages
Referenced by set_message_images().
gNextMessageBuffer
s16 gNextMessageBuffer = 0
Referenced by load_message_to_buffer().
MessagePlural
u8 MessagePlural[] = { MSG_CHAR_LOWER_S, MSG_CHAR_READ_END }
Referenced by shop_owner_buy_dialog(), and shop_owner_continue_speech_with_quantity().
MessageSingular
u8 MessageSingular[] = { MSG_CHAR_READ_ENDL, MSG_CHAR_READ_END }
Referenced by shop_owner_buy_dialog(), and shop_owner_continue_speech_with_quantity().
msg_drawState
SHIFT_BSS MessageDrawState* msg_drawState
Referenced by appendGfx_message(), appendGfx_msg_prim_rect(), and msg_draw_speech_bubble().
MsgCharImgNormal
IMG_BIN MsgCharImgNormal[] extern
Referenced by load_font().
MsgCharImgSubtitle
IMG_BIN MsgCharImgSubtitle[] extern
Referenced by load_font().
MsgCharImgTitle
IMG_BIN MsgCharImgTitle[] extern
Referenced by load_font().
MsgCharsets
MessageCharset* MsgCharsets[5] extern
Referenced by get_msg_properties(), msg_copy_to_print_buffer(), msg_get_draw_char_width(), and msg_get_print_char_width().
MsgLetterPaletteOffsets
s32 MsgLetterPaletteOffsets[] extern
Referenced by msg_copy_to_print_buffer().
MsgLetterRasterOffsets
s32 MsgLetterRasterOffsets[] extern
Referenced by msg_copy_to_print_buffer().
MsgStyleVerticalLineOffsets
s16 MsgStyleVerticalLineOffsets[] extern
Referenced by msg_copy_to_print_buffer().
MsgVoices
MsgVoice MsgVoices[] extern
ui_msg_arrow_png
IMG_BIN ui_msg_arrow_png[] extern
ui_msg_background_png
IMG_BIN ui_msg_background_png[] extern
ui_msg_bubble_left_png
IMG_BIN ui_msg_bubble_left_png[] extern
ui_msg_bubble_mid_png
IMG_BIN ui_msg_bubble_mid_png[] extern
ui_msg_bubble_right_png
IMG_BIN ui_msg_bubble_right_png[] extern
ui_msg_lamppost_corner_bottomright_png
IMG_BIN ui_msg_lamppost_corner_bottomright_png[] extern
ui_msg_lamppost_pal
PAL_BIN ui_msg_lamppost_pal[] extern
ui_msg_palettes
unsigned char ui_msg_palettes[16][32] extern
ui_msg_rewind_arrow_pal
PAL_BIN ui_msg_rewind_arrow_pal[] extern
Referenced by msg_draw_rewind_arrow().
ui_msg_rewind_arrow_png
IMG_BIN ui_msg_rewind_arrow_png[] extern
Referenced by msg_draw_rewind_arrow().
ui_msg_sign_corner_bottomleft_png
IMG_BIN ui_msg_sign_corner_bottomleft_png[] extern
ui_msg_sign_corner_bottomright_png
IMG_BIN ui_msg_sign_corner_bottomright_png[] extern
ui_msg_sign_corner_topleft_png
IMG_BIN ui_msg_sign_corner_topleft_png[] extern
ui_msg_sign_corner_topright_png
IMG_BIN ui_msg_sign_corner_topright_png[] extern
ui_msg_sign_fill_png
IMG_BIN ui_msg_sign_fill_png[] extern
ui_msg_sign_pal
PAL_BIN ui_msg_sign_pal[] extern
ui_msg_sign_side_bottom_png
IMG_BIN ui_msg_sign_side_bottom_png[] extern
ui_msg_sign_side_left_png
IMG_BIN ui_msg_sign_side_left_png[] extern
ui_msg_sign_side_right_png
IMG_BIN ui_msg_sign_side_right_png[] extern
ui_msg_sign_side_top_png
IMG_BIN ui_msg_sign_side_top_png[] extern
ui_msg_star_png
IMG_BIN ui_msg_star_png[] extern
Referenced by msg_update_rewind_arrow().
ui_msg_star_silhouette_png
IMG_BIN ui_msg_star_silhouette_png[] extern
Referenced by msg_update_rewind_arrow().
ui_point_right_pal
PAL_BIN ui_point_right_pal[] extern
Referenced by msg_draw_choice_pointer().
ui_point_right_png
IMG_BIN ui_point_right_png[] extern
Referenced by msg_draw_choice_pointer().