papermario: src/evt/npc_api.c File Reference
npc_api.c File Reference
Functions
Npc * resolve_npc (Evt *script, s32 npcIdOrPtr)
void set_npc_animation (Npc *npc, u32 animID)
ApiStatus CreateNpc (Evt *script, s32 isInitialCall)
ApiStatus DeleteNpc (Evt *script, s32 isInitialCall)
ApiStatus GetNpcPointer (Evt *script, s32 isInitialCall)
ApiStatus SetNpcPos (Evt *script, s32 isInitialCall)
ApiStatus SetNpcRotation (Evt *script, s32 isInitialCall)
ApiStatus SetNpcRotationPivot (Evt *script, s32 isInitialCall)
ApiStatus SetNpcScale (Evt *script, s32 isInitialCall)
ApiStatus SetNpcCollisionSize (Evt *script, s32 isInitialCall)
ApiStatus SetNpcSpeed (Evt *script, s32 isInitialCall)
ApiStatus SetNpcJumpscale (Evt *script, s32 isInitialCall)
ApiStatus SetNpcAnimation (Evt *script, s32 isInitialCall)
ApiStatus GetNpcAnimation (Evt *script, s32 isInitialCall)
ApiStatus SetNpcAnimationSpeed (Evt *script, s32 isInitialCall)
ApiStatus NpcMoveTo (Evt *script, s32 isInitialCall)
ApiStatus _npc_jump_to (Evt *script, s32 isInitialCall, s32 snapYaw)
ApiStatus NpcJump0 (Evt *script, s32 isInitialCall)
ApiStatus NpcJump1 (Evt *script, s32 isInitialCall)
ApiStatus NpcFlyTo (Evt *script, s32 isInitialCall)
ApiStatus GetNpcYaw (Evt *script, s32 isInitialCall)
ApiStatus SetNpcYaw (Evt *script, s32 isInitialCall)
ApiStatus InterpNpcYaw (Evt *script, s32 isInitialCall)
ApiStatus NpcFacePlayer (Evt *script, s32 isInitialCall)
ApiStatus NpcFaceNpc (Evt *script, s32 isInitialCall)
ApiStatus SetNpcFlagBits (Evt *script, s32 isInitialCall)
ApiStatus GetNpcPos (Evt *script, s32 isInitialCall)
ApiStatus SetNpcCollisionChannel (Evt *script, s32 isInitialCall)
ApiStatus SetNpcSprite (Evt *script, s32 isInitialCall)
ApiStatus EnableNpcShadow (Evt *script, s32 isInitialCall)
ApiStatus EnableNpcBlur (Evt *script, s32 isInitialCall)
ApiStatus ClearPartnerMoveHistory (Evt *script, s32 isInitialCall)
ApiStatus NpcSetHomePosToCurrent (Evt *script, s32 isInitialCall)
ApiStatus GetPartnerPos (Evt *script, s32 isInitialCall)
ApiStatus DisablePartnerAI (Evt *script, s32 isInitialCall)
ApiStatus EnablePartnerAI (Evt *script, s32 isInitialCall)
ApiStatus func_802CF54C (Evt *script, s32 isInitialCall)
ApiStatus func_802CF56C (Evt *script, s32 isInitialCall)
ApiStatus BringPartnerOut (Evt *script, s32 isInitialCall)
ApiStatus PutPartnerAway (Evt *script, s32 isInitialCall)
ApiStatus GetCurrentPartnerID (Evt *script, s32 isInitialCall)
ApiStatus PartnerCanUseAbility (Evt *script, s32 isInitialCall)
ApiStatus PartnerIsFlying (Evt *script, s32 isInitialCall)
ApiStatus SetNpcImgFXParams (Evt *script, s32 isInitialCall)
ApiStatus SetNpcImgFXFlags (Evt *script, s32 isInitialCall)
ApiStatus SetNpcPaletteSwapMode (Evt *script, s32 isInitialCall)
ApiStatus SetNpcPaletteSwapLower (Evt *script, s32 isInitialCall)
ApiStatus SetNpcPaletteSwapping (Evt *script, s32 isInitialCall)
ApiStatus SetNpcDecoration (Evt *script, s32 isInitialCall)
ApiStatus PlaySoundAtNpc (Evt *script, s32 isInitialCall)
ApiStatus SetNpcRenderMode (Evt *script, s32 isInitialCall)
Variables
s32 wExtraPartnerID
s32 wExtraPartnerNpcID
Function Documentation
_npc_jump_to()
ApiStatus _npc_jump_to (Evt * script, s32 isInitialCall, s32 snapYaw)
Referenced by NpcJump0(), and NpcJump1().
BringPartnerOut()
ApiStatus BringPartnerOut (Evt * script, s32 isInitialCall)
ClearPartnerMoveHistory()
ApiStatus ClearPartnerMoveHistory (Evt * script, s32 isInitialCall)
CreateNpc()
ApiStatus CreateNpc (Evt * script, s32 isInitialCall)
DeleteNpc()
ApiStatus DeleteNpc (Evt * script, s32 isInitialCall)
DisablePartnerAI()
ApiStatus DisablePartnerAI (Evt * script, s32 isInitialCall)
EnableNpcBlur()
ApiStatus EnableNpcBlur (Evt * script, s32 isInitialCall)
EnableNpcShadow()
ApiStatus EnableNpcShadow (Evt * script, s32 isInitialCall)
EnablePartnerAI()
ApiStatus EnablePartnerAI (Evt * script, s32 isInitialCall)
func_802CF54C()
ApiStatus func_802CF54C (Evt * script, s32 isInitialCall)
func_802CF56C()
ApiStatus func_802CF56C (Evt * script, s32 isInitialCall)
GetCurrentPartnerID()
ApiStatus GetCurrentPartnerID (Evt * script, s32 isInitialCall)
GetNpcAnimation()
ApiStatus GetNpcAnimation (Evt * script, s32 isInitialCall)
GetNpcPointer()
ApiStatus GetNpcPointer (Evt * script, s32 isInitialCall)
GetNpcPos()
ApiStatus GetNpcPos (Evt * script, s32 isInitialCall)
GetNpcYaw()
ApiStatus GetNpcYaw (Evt * script, s32 isInitialCall)
GetPartnerPos()
ApiStatus GetPartnerPos (Evt * script, s32 isInitialCall)
InterpNpcYaw()
ApiStatus InterpNpcYaw (Evt * script, s32 isInitialCall)
NpcFaceNpc()
ApiStatus NpcFaceNpc (Evt * script, s32 isInitialCall)
NpcFacePlayer()
ApiStatus NpcFacePlayer (Evt * script, s32 isInitialCall)
NpcFlyTo()
ApiStatus NpcFlyTo (Evt * script, s32 isInitialCall)
NpcJump0()
ApiStatus NpcJump0 (Evt * script, s32 isInitialCall)
NpcJump1()
ApiStatus NpcJump1 (Evt * script, s32 isInitialCall)
NpcMoveTo()
ApiStatus NpcMoveTo (Evt * script, s32 isInitialCall)
NpcSetHomePosToCurrent()
ApiStatus NpcSetHomePosToCurrent (Evt * script, s32 isInitialCall)
PartnerCanUseAbility()
ApiStatus PartnerCanUseAbility (Evt * script, s32 isInitialCall)
PartnerIsFlying()
ApiStatus PartnerIsFlying (Evt * script, s32 isInitialCall)
PlaySoundAtNpc()
ApiStatus PlaySoundAtNpc (Evt * script, s32 isInitialCall)
PutPartnerAway()
ApiStatus PutPartnerAway (Evt * script, s32 isInitialCall)
resolve_npc()
Npc * resolve_npc (Evt * script, s32 npcIdOrPtr)
Referenced by _npc_jump_to(), ClearPartnerMoveHistory(), EnableNpcBlur(), EnableNpcShadow(), GetNpcAnimation(), GetNpcPos(), GetNpcYaw(), InterpNpcYaw(), NpcFaceNpc(), NpcFacePlayer(), NpcFlyTo(), NpcMoveTo(), NpcSetHomePosToCurrent(), PlaySoundAtNpc(), SetNpcAnimation(), SetNpcAnimationSpeed(), SetNpcCollisionChannel(), SetNpcCollisionSize(), SetNpcDecoration(), SetNpcFlagBits(), SetNpcImgFXFlags(), SetNpcImgFXParams(), SetNpcJumpscale(), SetNpcPaletteSwapLower(), SetNpcPaletteSwapMode(), SetNpcPaletteSwapping(), SetNpcPos(), SetNpcRenderMode(), SetNpcRotation(), SetNpcRotationPivot(), SetNpcScale(), SetNpcSpeed(), SetNpcSprite(), and SetNpcYaw().
set_npc_animation()
void set_npc_animation (Npc * npc, u32 animID)
Referenced by _show_message(), and SetNpcAnimation().
SetNpcAnimation()
ApiStatus SetNpcAnimation (Evt * script, s32 isInitialCall)
SetNpcAnimationSpeed()
ApiStatus SetNpcAnimationSpeed (Evt * script, s32 isInitialCall)
SetNpcCollisionChannel()
ApiStatus SetNpcCollisionChannel (Evt * script, s32 isInitialCall)
SetNpcCollisionSize()
ApiStatus SetNpcCollisionSize (Evt * script, s32 isInitialCall)
SetNpcDecoration()
ApiStatus SetNpcDecoration (Evt * script, s32 isInitialCall)
SetNpcFlagBits()
ApiStatus SetNpcFlagBits (Evt * script, s32 isInitialCall)
SetNpcImgFXFlags()
ApiStatus SetNpcImgFXFlags (Evt * script, s32 isInitialCall)
SetNpcImgFXParams()
ApiStatus SetNpcImgFXParams (Evt * script, s32 isInitialCall)
SetNpcJumpscale()
ApiStatus SetNpcJumpscale (Evt * script, s32 isInitialCall)
SetNpcPaletteSwapLower()
ApiStatus SetNpcPaletteSwapLower (Evt * script, s32 isInitialCall)
SetNpcPaletteSwapMode()
ApiStatus SetNpcPaletteSwapMode (Evt * script, s32 isInitialCall)
SetNpcPaletteSwapping()
ApiStatus SetNpcPaletteSwapping (Evt * script, s32 isInitialCall)
SetNpcPos()
ApiStatus SetNpcPos (Evt * script, s32 isInitialCall)
SetNpcRenderMode()
ApiStatus SetNpcRenderMode (Evt * script, s32 isInitialCall)
SetNpcRotation()
ApiStatus SetNpcRotation (Evt * script, s32 isInitialCall)
SetNpcRotationPivot()
ApiStatus SetNpcRotationPivot (Evt * script, s32 isInitialCall)
SetNpcScale()
ApiStatus SetNpcScale (Evt * script, s32 isInitialCall)
SetNpcSpeed()
ApiStatus SetNpcSpeed (Evt * script, s32 isInitialCall)
SetNpcSprite()
ApiStatus SetNpcSprite (Evt * script, s32 isInitialCall)
SetNpcYaw()
ApiStatus SetNpcYaw (Evt * script, s32 isInitialCall)
Variable Documentation
wExtraPartnerID
s32 wExtraPartnerID extern
Referenced by BringPartnerOut(), and PutPartnerAway().
wExtraPartnerNpcID
s32 wExtraPartnerNpcID extern
Referenced by BringPartnerOut(), and PutPartnerAway().