papermario: src/npc_collision.c File Reference
npc_collision.c File Reference
Functions
HitID npc_raycast_down (s32 ignoreFlags, f32 *startX, f32 *startY, f32 *startZ, f32 *hitDepth)
b32 npc_raycast_down_around (s32 ignoreFlags, f32 *posX, f32 *posY, f32 *posZ, f32 *hitDepth, f32 yaw, f32 radius)
b32 npc_raycast_down_sides (s32 ignoreFlags, f32 *posX, f32 *posY, f32 *posZ, f32 *hitDepth)
s32 npc_raycast_up (s32 ignoreFlags, f32 *startX, f32 *startY, f32 *startZ, f32 *hitDepth)
s32 npc_raycast_up_corner (s32 ignoreFlags, f32 *x, f32 *y, f32 *z, f32 *length)
HitID npc_raycast_up_corners (s32 ignoreFlags, f32 *posX, f32 *posY, f32 *posZ, f32 *hitDepth, f32 yaw, f32 radius)
s32 npc_raycast_general (s32 flags, f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 *hitX, f32 *hitY, f32 *hitZ, f32 *outDepth, f32 *hitNx, f32 *hitNy, f32 *hitNz)
void npc_get_slip_vector (f32 *outX, f32 *outZ, f32 aX, f32 aZ, f32 bX, f32 bZ)
HitID npc_test_move_with_slipping (s32 ignoreFlags, f32 *x, f32 *y, f32 *z, f32 length, f32 yaw, f32 radius)
s32 npc_test_move_without_slipping (s32 ignoreFlags, f32 *x, f32 *y, f32 *z, f32 length, f32 yaw, f32 radius)
b32 npc_test_move_taller_with_slipping (s32 ignoreFlags, f32 *x, f32 *y, f32 *z, f32 length, f32 yaw, f32 height, f32 radius)
b32 npc_test_move_simple_with_slipping (s32 ignoreFlags, f32 *x, f32 *y, f32 *z, f32 length, f32 yaw, f32 height, f32 radius)
b32 npc_test_move_simple_without_slipping (s32 ignoreFlags, f32 *x, f32 *y, f32 *z, f32 length, f32 yaw, f32 height, f32 radius)
s32 npc_test_move_complex_with_slipping (s32 ignoreFlags, f32 *x, f32 *y, f32 *z, f32 length, f32 yaw, f32 height, f32 radius)
Variables
s32 NpcHitQueryBehindRightY
s32 NpcHitQueryBehindCollider
s32 NpcHitQueryAheadCollider
s32 NpcHitQueryAheadY
s32 NpcHitQueryBehindLeftY
s32 NpcHitQueryColliderID
PlayerStatus * gPlayerStatusPtr = &gPlayerStatus
Function Documentation
npc_get_slip_vector()
void npc_get_slip_vector (f32 * outX, f32 * outZ, f32 aX, f32 aZ, f32 bX, f32 bZ)
Referenced by npc_test_move_with_slipping().
npc_raycast_down()
HitID npc_raycast_down (s32 ignoreFlags, f32 * startX, f32 * startY, f32 * startZ, f32 * hitDepth)
Referenced by npc_raycast_down_around(), and npc_raycast_down_sides().
npc_raycast_down_around()
b32 npc_raycast_down_around (s32 ignoreFlags, f32 * posX, f32 * posY, f32 * posZ, f32 * hitDepth, f32 yaw, f32 radius)
Referenced by func_80262130(), npc_try_apply_gravity(), npc_try_snap_to_ground(), partner_flying_follow_player(), partner_flying_update_motion(), partner_get_out(), partner_move_to_goal(), partner_walking_follow_player(), test_for_water_level(), update_item_entity_collectable(), and update_riding_physics().
npc_raycast_down_sides()
b32 npc_raycast_down_sides (s32 ignoreFlags, f32 * posX, f32 * posY, f32 * posZ, f32 * hitDepth)
npc_raycast_general()
s32 npc_raycast_general (s32 flags, f32 startX, f32 startY, f32 startZ, f32 dirX, f32 dirY, f32 dirZ, f32 * hitX, f32 * hitY, f32 * hitZ, f32 * outDepth, f32 * hitNx, f32 * hitNy, f32 * hitNz)
Referenced by npc_test_move_with_slipping(), and npc_test_move_without_slipping().
npc_raycast_up()
s32 npc_raycast_up (s32 ignoreFlags, f32 * startX, f32 * startY, f32 * startZ, f32 * hitDepth)
Referenced by partner_flying_update_motion(), and update_item_entity_collectable().
npc_raycast_up_corner()
s32 npc_raycast_up_corner (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 * length)
Referenced by npc_raycast_up_corners().
npc_raycast_up_corners()
HitID npc_raycast_up_corners (s32 ignoreFlags, f32 * posX, f32 * posY, f32 * posZ, f32 * hitDepth, f32 yaw, f32 radius)
Referenced by update_riding_physics().
npc_test_move_complex_with_slipping()
s32 npc_test_move_complex_with_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 height, f32 radius)
Referenced by apply_riding_static_collisions(), npc_do_world_collision(), update_item_entity_collectable(), and update_riding_physics().
npc_test_move_simple_with_slipping()
b32 npc_test_move_simple_with_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 height, f32 radius)
Referenced by ai_check_fwd_collisions(), apply_riding_static_collisions(), basic_ai_chase(), basic_ai_check_player_dist(), basic_ai_loiter(), basic_ai_wander(), CleftAI_Tackle(), HoppingAI_Chase(), HoppingAI_Hop(), HoppingAI_HopInit(), npc_do_world_collision(), PiranhaPlantAI_10(), UnkNpcAIFunc12(), and update_item_entity_collectable().
npc_test_move_simple_without_slipping()
b32 npc_test_move_simple_without_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 height, f32 radius)
Referenced by AvoidPlayerAI_ChaseInit().
npc_test_move_taller_with_slipping()
b32 npc_test_move_taller_with_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 height, f32 radius)
Referenced by apply_riding_static_collisions(), blast_affect_entities(), check_conversation_trigger(), Entity_BoardedFloor_update_fragments(), entity_BombableRock_update_fragments(), entity_shattering_idle(), entity_WoodenCrate_update_fragments(), FlyingMagikoopaAI_15(), npc_do_world_collision(), partner_flying_follow_player(), test_first_strike(), test_first_strike(), update_encounters_neutral(), update_riding_physics(), and update_riding_physics().
npc_test_move_with_slipping()
HitID npc_test_move_with_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 radius)
Referenced by npc_test_move_complex_with_slipping(), npc_test_move_simple_with_slipping(), and npc_test_move_taller_with_slipping().
npc_test_move_without_slipping()
s32 npc_test_move_without_slipping (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 length, f32 yaw, f32 radius)
Referenced by npc_test_move_simple_without_slipping().
Variable Documentation
gPlayerStatusPtr
PlayerStatus* gPlayerStatusPtr = &gPlayerStatus
Referenced by AvoidPlayerAI_ChaseInit(), basic_ai_chase(), basic_ai_chase_init(), basic_ai_loiter(), basic_ai_wander(), can_trigger_loading_zone(), clear_conversation_prompt(), clear_interact_prompt(), clear_ispy_icon(), clear_pulse_stone_icon(), CleftAI_Ambush(), CleftAI_CanSeePlayer(), CleftAI_FindPlayer(), CleftAI_PreAmbush(), CleftAI_ReturnHome(), CleftAI_RevUp(), ClubbaNappingAI_Loiter(), ClubbaNappingAI_ReturnHome(), ClubbaNappingAI_Sleep(), collision_check_player_intersecting_world(), entity_get_collision_flags(), entity_HiddenPanel_flip_over(), entity_SaveBlock_pause_game(), entity_SaveBlock_save_data(), FlyingAI_ChaseInit(), FlyingAI_JumpInit(), FlyingAI_Loiter(), FlyingAI_LosePlayer(), FlyingAI_Wander(), FlyingMagikoopaAI_15(), FlyingMagikoopaAI_17(), FlyingNoAttackAI_12(), FlyingNoAttackAI_13(), func_800E4404(), func_802400D0_BC7F30(), func_80240920_BD4190(), GuardAI_ChaseInit(), GuardAI_Idle(), GuardAI_ReturnHome(), HoppingAI_ChaseInit(), HoppingAI_Hop(), HoppingAI_Loiter(), interact_inspect_dismiss(), MagikoopaAI_10(), MagikoopaAI_CanShootSpell(), MeleeHitbox_CanSeePlayer(), ParatroopaAI_Windup(), partner_handle_after_battle(), PatrolAI_ChaseInit(), PatrolAI_Loiter(), phys_update_lava_reset(), PiranhaPlantAI_10(), ProjectileHitbox_GetUsableProjectileID(), render_conversation_prompt(), render_entities(), render_interact_prompt(), render_ispy_icon(), render_pulse_stone_icon(), SentinelAI_Chase(), SentinelAI_ChaseInit(), SentinelAI_Descend(), SentinelAI_DescendInit(), set_script_owner_npc_anim(), state_step_battle(), sync_held_position(), UnkDistFunc(), update_camera_lead_amount(), update_player_shadow(), worker_draw_example_player(), and worker_draw_fake_player().
NpcHitQueryAheadCollider
s32 NpcHitQueryAheadCollider
Referenced by func_80262130(), npc_raycast_down_around(), and npc_raycast_down_sides().
NpcHitQueryAheadY
s32 NpcHitQueryAheadY
Referenced by npc_raycast_down_around(), and npc_raycast_down_sides().
NpcHitQueryBehindCollider
s32 NpcHitQueryBehindCollider
Referenced by func_80262130(), npc_raycast_down_around(), and npc_raycast_down_sides().
NpcHitQueryBehindLeftY
s32 NpcHitQueryBehindLeftY
Referenced by npc_raycast_down_around(), and npc_raycast_down_sides().
NpcHitQueryBehindRightY
s32 NpcHitQueryBehindRightY
Referenced by npc_raycast_down_around(), and npc_raycast_down_sides().
NpcHitQueryColliderID
s32 NpcHitQueryColliderID
Referenced by apply_riding_static_collisions(), blast_affect_entities(), entity_StarBoxLauncher_check_launch(), lateral_hit_interactable_entity(), npc_do_world_collision(), npc_get_collider_below(), npc_raycast_down_around(), npc_raycast_down_sides(), npc_raycast_up(), npc_test_move_with_slipping(), npc_test_move_without_slipping(), npc_try_apply_gravity(), npc_try_snap_to_ground(), partner_get_out(), partner_walking_follow_player(), test_for_water_level(), update_riding_physics(), update_riding_physics(), and vertical_hit_interactable_entity().