papermario: src/obfuscation_shims.c File Reference
obfuscation_shims.c File Reference
Functions
void create_audio_system_obfuscated (void)
void load_engine_data_obfuscated (void)
void general_heap_create_obfuscated (void)
void battle_heap_create_obfuscated (void)
void shim_create_audio_system_obfuscated (void)
void shim_load_engine_data_obfuscated (void)
void shim_general_heap_create_obfuscated (void)
void shim_battle_heap_create_obfuscated (void)
Function Documentation
battle_heap_create_obfuscated()
void battle_heap_create_obfuscated (void)
Referenced by shim_battle_heap_create_obfuscated().
create_audio_system_obfuscated()
void create_audio_system_obfuscated (void)
Referenced by shim_create_audio_system_obfuscated().
general_heap_create_obfuscated()
void general_heap_create_obfuscated (void)
Referenced by shim_general_heap_create_obfuscated().
load_engine_data_obfuscated()
void load_engine_data_obfuscated (void)
Referenced by shim_load_engine_data_obfuscated().
shim_battle_heap_create_obfuscated()
void shim_battle_heap_create_obfuscated (void)
Referenced by state_step_battle().
shim_create_audio_system_obfuscated()
void shim_create_audio_system_obfuscated (void)
Referenced by boot_main().
shim_general_heap_create_obfuscated()
void shim_general_heap_create_obfuscated (void)
Referenced by load_map_by_IDs().
shim_load_engine_data_obfuscated()
void shim_load_engine_data_obfuscated (void)
Referenced by boot_main().