papermario: src/world/area_obk/obk_07/obk_07_6_phonograph.c File Reference
obk_07_6_phonograph.c File Reference
Data Structures
struct PhonographData
Enumerations
enum {
PHONOGRAPH_HUD_STATE_DESTROYED = -1 , PHONOGRAPH_HUD_STATE_INIT = 0 , PHONOGRAPH_HUD_STATE_APPEAR = 1 , PHONOGRAPH_HUD_STATE_MASHING = 10 ,
PHONOGRAPH_HUD_STATE_FINAL = 11
}
Functions
PhonographData * GetPhonographData (void)
void DrawMashMeter (s32 posX, s32 posY, s32 fillValue)
void DrawMashMeterWithDivisor (s32 baseX, s32 baseY, s32 fillValue, s32 smoothDivisor)
void worker_update_phonograph_hud (void)
void worker_draw_phonograph_hud (void)
Variables
HudScript HES_SlowlyMashAButton
EvtScript EVS_UpdateGuardBoo
EvtScript EVS_DummyUpdateGuardBoo
EvtScript EVS_GuardBoo_ReturnToPost
EvtScript EVS_NpcAI_GuardBoo_Wary
s32 ItemList_Records []
s32 SongList []
u8 mashMeter_bgColors []
u8 mashMeter_fillColors []
u8 mashMeter_cutOffColors []
EvtScript EVS_UpdatePhonographScale
EvtScript EVS_UpdateCrankRotation
EvtScript EVS_UpdateRecordRotation
EvtScript EVS_SetPhonographScale
EvtScript EVS_SetCrankRotation
EvtScript EVS_SetRecordRotation
EvtScript EVS_WindDownPhonograph
EvtScript EVS_PlayPhonograph
EvtScript EVS_Inspect_Phonograph
EvtScript EVS_NpcAI_GuardBoo_DoNothing
EvtScript EVS_NpcAI_GuardBoo_Dancing
EvtScript EVS_GuardBooVanish
EvtScript EVS_NpcInteract_GuardBoo
EvtScript EVS_Scene_PlayerGotChestItem
EvtScript EVS_SetupGuardBoo
EvtScript EVS_SetupPhonograph
Data Structure Documentation
PhonographData
struct PhonographData
Data Fields
s32 barFillWidth
f32 crankRotation
s32 fillValue
s32 hudBaseX
s32 hudBaseY
s32 hudElemAButton
s32 hudElemBlueMeter
s32 hudElemOK
s32 hudWorker
s32 inputBuffer[90]
s32 inputBufferPos
s32 mashMeterDividers[6]
s32 mashMeterIntervals
s32 mashMeterSmoothDivisor
s32 meterFillAmount
f32 modelScale
f32 recordRotation
s32 songName
s32 state
f32 timeScale
s32 unk_1D8
s8 unk_1DC
char unk_1DD[0x3]
char unk_48[0x4]
s32 updateCrankScriptID
s32 updateRecordScriptID
s32 updateScaleScriptID
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PHONOGRAPH_HUD_STATE_DESTROYED
PHONOGRAPH_HUD_STATE_INIT
PHONOGRAPH_HUD_STATE_APPEAR
PHONOGRAPH_HUD_STATE_MASHING
PHONOGRAPH_HUD_STATE_FINAL
Function Documentation
DrawMashMeter()
void DrawMashMeter (s32 posX, s32 posY, s32 fillValue)
Referenced by DrawMashMeterWithDivisor().
DrawMashMeterWithDivisor()
void DrawMashMeterWithDivisor (s32 baseX, s32 baseY, s32 fillValue, s32 smoothDivisor)
Referenced by worker_draw_phonograph_hud().
GetPhonographData()
PhonographData * GetPhonographData (void)
Referenced by DrawMashMeter(), DrawMashMeterWithDivisor(), worker_draw_phonograph_hud(), and worker_update_phonograph_hud().
worker_draw_phonograph_hud()
void worker_draw_phonograph_hud (void)
worker_update_phonograph_hud()
void worker_update_phonograph_hud (void)
Variable Documentation
EVS_DummyUpdateGuardBoo
EvtScript EVS_DummyUpdateGuardBoo
Initial value:
= {
    EVT_END_LOOP
    EVT_RETURN
    EVT_END
}
EVS_GuardBoo_ReturnToPost
EvtScript EVS_GuardBoo_ReturnToPost
EVS_GuardBooVanish
EvtScript EVS_GuardBooVanish
Initial value:
= {
    EVT_THREAD
    EVT_END_THREAD
        EVT_END_IF
    EVT_RETURN
    EVT_END
}
EVS_Inspect_Phonograph
EvtScript EVS_Inspect_Phonograph
EVS_NpcAI_GuardBoo_Dancing
EvtScript EVS_NpcAI_GuardBoo_Dancing
EVS_NpcAI_GuardBoo_DoNothing
EvtScript EVS_NpcAI_GuardBoo_DoNothing
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_NpcAI_GuardBoo_Wary
EvtScript EVS_NpcAI_GuardBoo_Wary
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_NpcInteract_GuardBoo
EvtScript EVS_NpcInteract_GuardBoo
Initial value:
= {
            EVT_ELSE
            EVT_END_IF
            EVT_ELSE
            EVT_END_IF
    EVT_END_SWITCH
    EVT_RETURN
    EVT_END
}
EVS_PlayPhonograph
EvtScript EVS_PlayPhonograph
EVS_Scene_PlayerGotChestItem
EvtScript EVS_Scene_PlayerGotChestItem
Initial value:
= {
    EVT_CALL(BindNpcAI, NPC_GuardBoo, EVT_PTR( EVS_NpcAI_GuardBoo_DoNothing ))
    EVT_RETURN
    EVT_END
}
EVS_SetCrankRotation
EvtScript EVS_SetCrankRotation
Initial value:
= {
                EVT_BREAK_LOOP
            EVT_END_IF
        EVT_END_IF
    EVT_END_LOOP
    EVT_RETURN
    EVT_END
}
EVS_SetPhonographScale
EvtScript EVS_SetPhonographScale
Initial value:
= {
                EVT_BREAK_LOOP
            EVT_END_IF
        EVT_END_IF
    EVT_END_LOOP
    EVT_RETURN
    EVT_END
}
EVS_SetRecordRotation
EvtScript EVS_SetRecordRotation
Initial value:
= {
                EVT_BREAK_LOOP
            EVT_END_IF
        EVT_END_IF
    EVT_END_LOOP
    EVT_RETURN
    EVT_END
}
EVS_SetupGuardBoo
EvtScript EVS_SetupGuardBoo
Initial value:
= {
    EVT_CALL(SetNpcScale, NPC_GuardBoo, EVT_FLOAT(1.0), EVT_FLOAT(1.0), EVT_FLOAT(1.0))
    EVT_CALL(BindNpcInteract, NPC_SELF, EVT_PTR( EVS_NpcInteract_GuardBoo ))
    EVT_CALL(BindNpcIdle, NPC_SELF, EVT_PTR( EVS_NpcAI_GuardBoo_Wary ))
    EVT_RETURN
    EVT_END
}
EVS_SetupPhonograph
EvtScript EVS_SetupPhonograph
Initial value:
= {
    EVT_END_IF
    EVT_BIND_PADLOCK(EVT_PTR( EVS_Inspect_Phonograph ), TRIGGER_WALL_PRESS_A, COLLIDER_o344, EVT_PTR( ItemList_Records ), 0, 1)
    EVT_RETURN
    EVT_END
}
EVS_UpdateCrankRotation
EvtScript EVS_UpdateCrankRotation
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_UpdateGuardBoo
EvtScript EVS_UpdateGuardBoo
EVS_UpdatePhonographScale
EvtScript EVS_UpdatePhonographScale
Initial value:
= {
            EVT_END_IF
            EVT_END_IF
    EVT_RETURN
    EVT_END
}
EVS_UpdateRecordRotation
EvtScript EVS_UpdateRecordRotation
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_WindDownPhonograph
EvtScript EVS_WindDownPhonograph
HES_SlowlyMashAButton
HudScript HES_SlowlyMashAButton extern
Referenced by worker_update_phonograph_hud().
ItemList_Records
s32 ItemList_Records[]
Initial value:
= {
    ITEM_BOO_RECORD,
    ITEM_NONE
}
mashMeter_bgColors
u8 mashMeter_bgColors[]
Initial value:
= {
     33,  33, 117,
     29,  35, 163,
     70,  12, 180,
    107,   0, 120,
    115,  13,  19,
}
Referenced by DrawMashMeter().
mashMeter_cutOffColors
u8 mashMeter_cutOffColors[]
Initial value:
= {
     45,  56, 210,
     84,  40, 209,
    125,  44, 181,
    161,  27,  85,
    255, 255, 255,
}
Referenced by DrawMashMeter().
mashMeter_fillColors
u8 mashMeter_fillColors[]
Initial value:
= {
      0, 228, 134,
     46, 180, 242,
    117, 112, 255,
    243,   4, 188,
    247,  13,   5,
}
Referenced by DrawMashMeter().
SongList
s32 SongList[]
Initial value:
= {
    SONG_PHONOGRAPH_MUSIC,
    SONG_TOAD_TOWN,
}