papermario: include/overlay.h File Reference
overlay.h File Reference
Data Structures
struct ScreenOverlay
Functions
void _render_transition_stencil (u8, f32, ScreenOverlay *)
void appendGfx_screen_transition_stencil (s32, s32, f32, s32, s32, s32, s32, s32)
void appendGfx_darkness_stencil (s32, s32, s32, f32, f32)
Data Structure Documentation
ScreenOverlay
struct ScreenOverlay
Data Fields
f32 alpha
Color_RGB8 color
s32 screenPos[2][2]
char unk_03
Function Documentation
_render_transition_stencil()
void _render_transition_stencil (u8 stencilType, f32 progress, ScreenOverlay * overlay)
Referenced by gfx_draw_frame(), render_screen_overlay_backUI(), and render_screen_overlay_frontUI().
appendGfx_darkness_stencil()
void appendGfx_darkness_stencil (s32 isWorld, s32 posX, s32 posY, f32 alpha, f32 progress)
Referenced by _render_transition_stencil().
appendGfx_screen_transition_stencil()
void appendGfx_screen_transition_stencil (s32 arg0, s32 arg1, f32 progress, s32 primR, s32 primG, s32 primB, s32 primA, s32 camID)
Referenced by _render_transition_stencil().