papermario: src/effects/partner_buff.c File Reference
partner_buff.c File Reference
Enumerations
enum {
BUFF_STATE_IDLE = 0 , BUFF_STATE_DECREMENT_TURNS_INIT = 1 , BUFF_STATE_DECREMENT_TURNS = 10 , BUFF_STATE_SET_TURNS_INIT = 2 ,
BUFF_STATE_SET_TURNS = 20 , BUFF_STATE_FADE_OUT = 3 , BUFF_STATE_FADE_IN_INIT = 4 , BUFF_STATE_FADE_IN = 40
}
Functions
void partner_buff_init (EffectInstance *effect)
void partner_buff_update (EffectInstance *effect)
void partner_buff_render (EffectInstance *effect)
void func_E011A3A0 (EffectInstance *effect)
void func_E011A700 (EffectInstance *effect)
EffectInstance * partner_buff_main (s32 useRandomValues, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 duration)
void func_E011A3BC (s16 alpha)
void func_E011A48C (s32 posX, s32 posY, s32 tile, f32 scale)
Variables
Gfx D_09001800_406740 []
Gfx D_090019A0_4068E0 []
Gfx D_09001A18_406958 []
Gfx D_09001A90_4069D0 []
Gfx D_09001B08_406A48 []
Gfx D_09001B80_406AC0 []
Gfx * D_E011AC20 [] = { D_09001800_406740 }
Gfx * D_E011AC24 []
s8 D_E011AC4C [] = { 15, 15, 15, 15, 15, 35, 75, 100, 100, 100, 100, 0 }
s8 D_E011AC58 [] = { 100, 100, 100, 100, 100, 90, 10, 10, 10, 10, 10, 0 }
s8 D_E011AC64 [] = { 0, -1, -3, -4, -4, 4, 32, 32, 32, 32, 32, 0 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BUFF_STATE_IDLE
BUFF_STATE_DECREMENT_TURNS_INIT
BUFF_STATE_DECREMENT_TURNS
BUFF_STATE_SET_TURNS_INIT
BUFF_STATE_SET_TURNS
BUFF_STATE_FADE_OUT
BUFF_STATE_FADE_IN_INIT
BUFF_STATE_FADE_IN
Function Documentation
func_E011A3A0()
void func_E011A3A0 (EffectInstance * effect)
Referenced by partner_buff_main().
func_E011A3BC()
void func_E011A3BC (s16 alpha)
Referenced by func_E011A700().
func_E011A48C()
void func_E011A48C (s32 posX, s32 posY, s32 tile, f32 scale)
Referenced by func_E011A700().
func_E011A700()
void func_E011A700 (EffectInstance * effect)
Referenced by func_E011A3A0().
partner_buff_init()
void partner_buff_init (EffectInstance * effect)
Referenced by partner_buff_main().
partner_buff_main()
EffectInstance * partner_buff_main (s32 useRandomValues, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 duration)
partner_buff_render()
void partner_buff_render (EffectInstance * effect)
Referenced by partner_buff_main().
partner_buff_update()
void partner_buff_update (EffectInstance * effect)
Referenced by partner_buff_main().
Variable Documentation
D_09001800_406740
Gfx D_09001800_406740[] extern
D_090019A0_4068E0
Gfx D_090019A0_4068E0[] extern
D_09001A18_406958
Gfx D_09001A18_406958[] extern
D_09001A90_4069D0
Gfx D_09001A90_4069D0[] extern
D_09001B08_406A48
Gfx D_09001B08_406A48[] extern
D_09001B80_406AC0
Gfx D_09001B80_406AC0[] extern
D_E011AC20
Gfx* D_E011AC20[] = { D_09001800_406740 }
Referenced by func_E011A700().
D_E011AC24
Gfx* D_E011AC24[]
Initial value:
= {
    D_090019A0_4068E0, D_09001A18_406958, D_09001A90_4069D0, D_09001B08_406A48, D_09001B80_406AC0,
    NULL, NULL, NULL, NULL, NULL
}
Referenced by func_E011A700().
D_E011AC4C
s8 D_E011AC4C[] = { 15, 15, 15, 15, 15, 35, 75, 100, 100, 100, 100, 0 }
Referenced by func_E011A700().
D_E011AC58
s8 D_E011AC58[] = { 100, 100, 100, 100, 100, 90, 10, 10, 10, 10, 10, 0 }
Referenced by func_E011A700().
D_E011AC64
s8 D_E011AC64[] = { 0, -1, -3, -4, -4, 4, 32, 32, 32, 32, 32, 0 }
Referenced by func_E011A700().