papermario: src/world/common/lava_piranha/part2.inc.c File Reference
part2.inc.c File Reference
Macros
#define PIRANHA_DMA_ENTRY(name)
Functions
MAP_STATIC_PAD (1, unk_static_pad)
void N make_vine_interpolation (LavaPiranhaVine *vine)
void N appendGfx_piranha_vines (void *data)
void N worker_render_piranha_vines (void)
Macro Definition Documentation
PIRANHA_DMA_ENTRY
#define PIRANHA_DMA_ENTRY (name)
Value:
    (s32) world_model_anim_kzn_##name##_ROM_START,\
    (s32) world_model_anim_kzn_##name##_ROM_END,\
    (s32) world_model_anim_kzn_##name##_VRAM
Function Documentation
appendGfx_piranha_vines()
void N appendGfx_piranha_vines (void * data)
Referenced by worker_render_piranha_vines().
make_vine_interpolation()
void N make_vine_interpolation (LavaPiranhaVine * vine)
Referenced by appendGfx_piranha_vines(), and appendGfx_vines().
MAP_STATIC_PAD()
MAP_STATIC_PAD (1 , unk_static_pad)
worker_render_piranha_vines()
void N worker_render_piranha_vines (void)