papermario: src/pause/pause_common.h File Reference
pause_common.h File Reference
Enumerations
enum PauseMenuLabels {
PAUSE_LBL_HP = 0 , PAUSE_LBL_FP = 1 , PAUSE_LBL_BP = 2 , PAUSE_LBL_BOOTS = 3 ,
PAUSE_LBL_HAMMER = 4 , PAUSE_LBL_ENERGY = 5 , PAUSE_LBL_STATS = 6 , PAUSE_LBL_AVAILABLE = 7 ,
PAUSE_LBL_ABILITIES = 8
}
enum PauseMenuMessages {
PAUSE_MSG_NONE , PAUSE_MSG_TUT_NAME_BADGES , PAUSE_MSG_TUT_UNUSED_1 , PAUSE_MSG_TUT_UNUSED_2 ,
PAUSE_MSG_TUT_UNUSED_3 , PAUSE_MSG_TUT_UNUSED_4 , PAUSE_MSG_TUT_UNUSED_5 , PAUSE_MSG_TUT_UNUSED_6 ,
PAUSE_MSG_TUT_UNUSED_7 , PAUSE_MSG_TUT_DESC_1 , PAUSE_MSG_TUT_DESC_2 , PAUSE_MSG_TUT_DESC_3 ,
PAUSE_MSG_TUT_DESC_4 , PAUSE_MSG_TUT_DESC_5 , PAUSE_MSG_TUT_DESC_6 , PAUSE_MSG_TUT_DESC_7 ,
PAUSE_MSG_TUT_CMD_1 , PAUSE_MSG_TUT_CMD_2 , PAUSE_MSG_TUT_CMD_3 , PAUSE_MSG_TUT_CMD_4 ,
PAUSE_MSG_TUT_CMD_5 , PAUSE_MSG_TUT_CMD_6 , PAUSE_MSG_TUT_CMD_7 , PAUSE_MSG_17 ,
PAUSE_MSG_18 , PAUSE_MSG_19 , PAUSE_MSG_1A , PAUSE_MSG_TAB_STATS ,
PAUSE_MSG_TAB_BADGES , PAUSE_MSG_TAB_ITEMS , PAUSE_MSG_TAB_PARTY , PAUSE_MSG_TAB_SPIRITS ,
PAUSE_MSG_TAB_MAP , PAUSE_MSG_TIP_CONTROLS , PAUSE_MSG_TIP_HP , PAUSE_MSG_TIP_FP ,
PAUSE_MSG_TIP_BP , PAUSE_MSG_TIP_BOOTS_1 , PAUSE_MSG_TIP_BOOTS_2 , PAUSE_MSG_TIP_BOOTS_3 ,
PAUSE_MSG_TIP_HAMMER_0 , PAUSE_MSG_TIP_HAMMER_1 , PAUSE_MSG_TIP_HAMMER_2 , PAUSE_MSG_TIP_HAMMER_3 ,
PAUSE_MSG_TIP_STAR_POWER , PAUSE_MSG_TIP_STAR_POINTS , PAUSE_MSG_TIP_COINS , PAUSE_MSG_TIP_SECRETS ,
PAUSE_MSG_TIP_STAR_PIECES , PAUSE_MSG_TIP_TIME , PAUSE_MSG_LBL_COINS , PAUSE_MSG_LBL_STAR_POINTS ,
PAUSE_MSG_LBL_STAR_PIECES , PAUSE_MSG_LBL_TIME , PAUSE_MSG_LBL_HP , PAUSE_MSG_LBL_FP ,
PAUSE_MSG_LBL_BP , PAUSE_MSG_SLASH , PAUSE_MSG_DOT , PAUSE_MSG_3B ,
PAUSE_MSG_3C , PAUSE_MSG_3D , PAUSE_MSG_3E , PAUSE_MSG_3F ,
PAUSE_MSG_40 , PAUSE_MSG_41 , PAUSE_MSG_42 , PAUSE_MSG_MARIO ,
PAUSE_MSG_LEVEL , PAUSE_MSG_NO_BADGE , PAUSE_MSG_BADGE_BP , PAUSE_MSG_ALL_BADGES ,
PAUSE_MSG_ACTIVE , PAUSE_MSG_BADGES , PAUSE_MSG_NOT_ENOUGH_BP , PAUSE_MSG_DONT_WEAR_MORE ,
PAUSE_MSG_BAGDE_DESC_ALL , PAUSE_MSG_BAGDE_DESC_ACTIVE , PAUSE_MSG_BAGDE_DESC_NONE , PAUSE_MSG_KEY_ITEMS ,
PAUSE_MSG_CONSUMABLES , PAUSE_MSG_DESC_CONSUMABLES , PAUSE_MSG_DESC_KEY_ITEMS , PAUSE_MSG_PARTNER_HP ,
PAUSE_MSG_PARTNER_FP , PAUSE_MSG_PARTNER_ABILITIES , PAUSE_MSG_UNKNOWN_SPIRIT
}
Functions
void pause_update_tab_default (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void pause_update_tab_active (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void pause_update_tab_inactive (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void pause_update_page_active_1 (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void pause_update_page_inactive_1 (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void pause_update_page_active_2 (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void pause_update_page_inactive_2 (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void pause_set_cursor_pos (s32 windowID, s32 posX, s32 posY)
void pause_set_cursor_pos_immediate (s32 windowID, s32 posX, s32 posY)
void pause_set_cursor_opacity (s32 val)
void pause_draw_menu_label (s32 index, s32 x, s32 y)
s32 pause_get_total_equipped_bp_cost (void)
void pause_draw_rect (s32 ulx, s32 uly, s32 lrx, s32 lry, s32 tileIdx, s32 uls, s32 ult, s32 dsdx, s32 dtdy)
s32 pause_get_menu_msg (s32 index)
s32 pause_interp_vertical_scroll (s32 deltaBefore)
void pause_sort_item_list (s16 *arr, s32 len, s32(*compare)(s16 *, s16 *))
Variables
HudScript HES_PressAButton
HudScript HES_PressStartButton
HudScript HES_StartButtonText
HudScript HES_StickTapRight
HudScript HES_UnusedBadge
HudScript HES_AnimatedCursorHand
HudScript HES_DescMsgPrev
HudScript HES_DescMsgNext
HudScript HES_HeaderStats
HudScript HES_HeaderBadges
HudScript HES_HeaderItems
HudScript HES_HeaderParty
HudScript HES_HeaderSpirits
HudScript HES_HeaderMap
HudScript HES_MarioHeadSmall
HudScript HES_StatBoots0
HudScript HES_StatBoots1
HudScript HES_StatBoots2
HudScript HES_StatBoots3
HudScript HES_StatHammer0
HudScript HES_StatHammer1
HudScript HES_StatHammer2
HudScript HES_StatHammer3
HudScript HES_StatusStarPoint
HudScript HES_StatStarPiece_1
HudScript HES_Clock
HudScript HES_StatusHeart
HudScript HES_StatFp_1
HudScript HES_StatBp
HudScript HES_StatusStar1
HudScript HES_StatusStar2
HudScript HES_StatusStar3
HudScript HES_StatusStar4
HudScript HES_StatusStar5
HudScript HES_StatusStar6
HudScript HES_StatusStar7
HudScript HES_StatusStarEmpty
HudScript HES_StatTimes
HudScript HES_ListPrevPage
HudScript HES_ListNextPage
HudScript HES_Dash
HudScript HES_LabelBpNeeded
HudScript HES_FPCost
HudScript HES_PartnerRank
HudScript HES_MoveDiamond
HudScript HES_MoveBlueOrb
HudScript HES_MoveGreenOrb
HudScript HES_MoveRedOrb
HudScript HES_MapWalk0
HudScript HES_StatusSPIncrement1
HudScript HES_StatusSPIncrement2
HudScript HES_StatusSPIncrement3
HudScript HES_StatusSPIncrement4
HudScript HES_StatusSPIncrement5
HudScript HES_StatusSPIncrement6
HudScript HES_StatusSPIncrement7
HudScript HES_StatusSPEmptyIncrement
IconHudScriptPair gItemHudScripts []
WindowStyleCustom gPauseWS_0
WindowStyleCustom gPauseWS_1
WindowStyleCustom gPauseWS_2
WindowStyleCustom gPauseWS_3
WindowStyleCustom gPauseWS_4
WindowStyleCustom gPauseWS_5
WindowStyleCustom gPauseWS_6
WindowStyleCustom gPauseWS_7
WindowStyleCustom gPauseWS_8
WindowStyleCustom gPauseWS_9
WindowStyleCustom gPauseWS_10
WindowStyleCustom gPauseWS_11
WindowStyleCustom gPauseWS_12
WindowStyleCustom gPauseWS_13
WindowStyleCustom gPauseWS_14
WindowStyleCustom gPauseWS_15
WindowStyleCustom gPauseWS_16
WindowStyleCustom gPauseWS_17
WindowStyleCustom gPauseWS_18
WindowStyleCustom gPauseWS_19
WindowStyleCustom gPauseWS_20
WindowStyleCustom gPauseWS_21
WindowStyleCustom gPauseWS_22
WindowStyleCustom gPauseWS_23
WindowStyleCustom gPauseWS_24
WindowStyleCustom gPauseWS_25
WindowStyleCustom gPauseWS_26
WindowStyleCustom gPauseWS_27
WindowStyleCustom gPauseWS_28
s32 gPauseHeldButtons
s32 gPausePressedButtons
s32 gPauseCurrentDescMsg
HudScript * gPauseCurrentDescIconScript
s32 gPauseCursorIconID
s8 gPauseMenuCurrentTab
Enumeration Type Documentation
PauseMenuLabels
enum PauseMenuLabels
Enumerator
PAUSE_LBL_HP
PAUSE_LBL_FP
PAUSE_LBL_BP
PAUSE_LBL_BOOTS
PAUSE_LBL_HAMMER
PAUSE_LBL_ENERGY
PAUSE_LBL_STATS
PAUSE_LBL_AVAILABLE
PAUSE_LBL_ABILITIES
PauseMenuMessages
enum PauseMenuMessages
Enumerator
PAUSE_MSG_NONE
PAUSE_MSG_TUT_NAME_BADGES
PAUSE_MSG_TUT_UNUSED_1
PAUSE_MSG_TUT_UNUSED_2
PAUSE_MSG_TUT_UNUSED_3
PAUSE_MSG_TUT_UNUSED_4
PAUSE_MSG_TUT_UNUSED_5
PAUSE_MSG_TUT_UNUSED_6
PAUSE_MSG_TUT_UNUSED_7
PAUSE_MSG_TUT_DESC_1
PAUSE_MSG_TUT_DESC_2
PAUSE_MSG_TUT_DESC_3
PAUSE_MSG_TUT_DESC_4
PAUSE_MSG_TUT_DESC_5
PAUSE_MSG_TUT_DESC_6
PAUSE_MSG_TUT_DESC_7
PAUSE_MSG_TUT_CMD_1
PAUSE_MSG_TUT_CMD_2
PAUSE_MSG_TUT_CMD_3
PAUSE_MSG_TUT_CMD_4
PAUSE_MSG_TUT_CMD_5
PAUSE_MSG_TUT_CMD_6
PAUSE_MSG_TUT_CMD_7
PAUSE_MSG_17
PAUSE_MSG_18
PAUSE_MSG_19
PAUSE_MSG_1A
PAUSE_MSG_TAB_STATS
PAUSE_MSG_TAB_BADGES
PAUSE_MSG_TAB_ITEMS
PAUSE_MSG_TAB_PARTY
PAUSE_MSG_TAB_SPIRITS
PAUSE_MSG_TAB_MAP
PAUSE_MSG_TIP_CONTROLS
PAUSE_MSG_TIP_HP
PAUSE_MSG_TIP_FP
PAUSE_MSG_TIP_BP
PAUSE_MSG_TIP_BOOTS_1
PAUSE_MSG_TIP_BOOTS_2
PAUSE_MSG_TIP_BOOTS_3
PAUSE_MSG_TIP_HAMMER_0
PAUSE_MSG_TIP_HAMMER_1
PAUSE_MSG_TIP_HAMMER_2
PAUSE_MSG_TIP_HAMMER_3
PAUSE_MSG_TIP_STAR_POWER
PAUSE_MSG_TIP_STAR_POINTS
PAUSE_MSG_TIP_COINS
PAUSE_MSG_TIP_SECRETS
PAUSE_MSG_TIP_STAR_PIECES
PAUSE_MSG_TIP_TIME
PAUSE_MSG_LBL_COINS
PAUSE_MSG_LBL_STAR_POINTS
PAUSE_MSG_LBL_STAR_PIECES
PAUSE_MSG_LBL_TIME
PAUSE_MSG_LBL_HP
PAUSE_MSG_LBL_FP
PAUSE_MSG_LBL_BP
PAUSE_MSG_SLASH
PAUSE_MSG_DOT
PAUSE_MSG_3B
PAUSE_MSG_3C
PAUSE_MSG_3D
PAUSE_MSG_3E
PAUSE_MSG_3F
PAUSE_MSG_40
PAUSE_MSG_41
PAUSE_MSG_42
PAUSE_MSG_MARIO
PAUSE_MSG_LEVEL
PAUSE_MSG_NO_BADGE
PAUSE_MSG_BADGE_BP
PAUSE_MSG_ALL_BADGES
PAUSE_MSG_ACTIVE
PAUSE_MSG_BADGES
PAUSE_MSG_NOT_ENOUGH_BP
PAUSE_MSG_DONT_WEAR_MORE
PAUSE_MSG_BAGDE_DESC_ALL
PAUSE_MSG_BAGDE_DESC_ACTIVE
PAUSE_MSG_BAGDE_DESC_NONE
PAUSE_MSG_KEY_ITEMS
PAUSE_MSG_CONSUMABLES
PAUSE_MSG_DESC_CONSUMABLES
PAUSE_MSG_DESC_KEY_ITEMS
PAUSE_MSG_PARTNER_HP
PAUSE_MSG_PARTNER_FP
PAUSE_MSG_PARTNER_ABILITIES
PAUSE_MSG_UNKNOWN_SPIRIT
Function Documentation
pause_draw_menu_label()
void pause_draw_menu_label (s32 index, s32 x, s32 y)
Referenced by pause_badges_draw_contents(), pause_partners_draw_contents(), and pause_stats_draw_contents().
pause_draw_rect()
void pause_draw_rect (s32 ulx, s32 uly, s32 lrx, s32 lry, s32 tileIdx, s32 uls, s32 ult, s32 dsdx, s32 dtdy)
Referenced by pause_badges_draw_bp_orbs(), pause_draw_menu_label(), pause_map_draw_border_arrows(), pause_map_draw_contents(), pause_partners_draw_contents(), pause_spirits_draw_contents(), and pause_tutorial_draw_contents().
pause_get_menu_msg()
s32 pause_get_menu_msg (s32 index)
Referenced by pause_badges_draw_contents(), pause_badges_handle_input(), pause_items_draw_contents(), pause_items_handle_input(), pause_partners_draw_movelist_title(), pause_spirits_draw_title(), pause_spirits_handle_input(), pause_stats_draw_contents(), pause_stats_handle_input(), pause_tabs_handle_input(), and pause_tutorial_draw_contents().
pause_get_total_equipped_bp_cost()
s32 pause_get_total_equipped_bp_cost (void)
Referenced by pause_badges_draw_contents(), and pause_badges_try_equip().
pause_interp_vertical_scroll()
s32 pause_interp_vertical_scroll (s32 deltaBefore)
Referenced by pause_badges_update(), and pause_items_update().
pause_set_cursor_opacity()
void pause_set_cursor_opacity (s32 val)
Referenced by pause_badges_draw_contents().
pause_set_cursor_pos()
void pause_set_cursor_pos (s32 windowID, s32 posX, s32 posY)
Referenced by pause_badges_draw_contents(), pause_items_draw_contents(), pause_map_draw_contents(), pause_partners_draw_contents(), pause_partners_draw_movelist(), pause_spirits_draw_contents(), pause_stats_draw_contents(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), and pause_tabs_draw_stats().
pause_set_cursor_pos_immediate()
void pause_set_cursor_pos_immediate (s32 windowID, s32 posX, s32 posY)
Referenced by pause_badges_draw_contents(), and pause_items_draw_contents().
pause_sort_item_list()
void pause_sort_item_list (s16 * arr, s32 len, s32(*)(s16 *, s16 *) compare)
Referenced by pause_badges_count_all(), pause_badges_count_equipped(), and pause_items_load_items().
pause_update_page_active_1()
void pause_update_page_active_1 (s32 windowIndex, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by pause_tabs_update().
pause_update_page_active_2()
void pause_update_page_active_2 (s32 windowIndex, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by pause_tabs_update().
pause_update_page_inactive_1()
void pause_update_page_inactive_1 (s32 windowIndex, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by pause_tabs_update().
pause_update_page_inactive_2()
void pause_update_page_inactive_2 (s32 windowIndex, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by pause_tabs_update().
pause_update_tab_active()
void pause_update_tab_active (s32 windowIndex, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by pause_tabs_handle_input().
pause_update_tab_default()
void pause_update_tab_default (s32 windowIndex, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
pause_update_tab_inactive()
void pause_update_tab_inactive (s32 windowIndex, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by pause_tabs_handle_input().
Variable Documentation
gItemHudScripts
IconHudScriptPair gItemHudScripts[] extern
gPauseCurrentDescIconScript
HudScript* gPauseCurrentDescIconScript extern
Referenced by pause_badges_draw_contents(), pause_badges_handle_input(), pause_handle_input(), pause_init(), pause_items_draw_contents(), pause_items_handle_input(), pause_map_handle_input(), pause_partners_handle_input(), pause_spirits_handle_input(), pause_stats_handle_input(), and pause_tabs_handle_input().
gPauseCurrentDescMsg
s32 gPauseCurrentDescMsg extern
Referenced by pause_badges_handle_input(), pause_handle_input(), pause_init(), pause_items_handle_input(), pause_map_handle_input(), pause_partners_handle_input(), pause_spirits_handle_input(), pause_stats_handle_input(), and pause_tabs_handle_input().
gPauseCursorIconID
s32 gPauseCursorIconID extern
Referenced by pause_init().
gPauseHeldButtons
s32 gPauseHeldButtons extern
Referenced by pause_badges_handle_input(), pause_handle_input(), pause_items_handle_input(), pause_partners_handle_input(), pause_spirits_handle_input(), pause_stats_handle_input(), and pause_tabs_handle_input().
gPauseMenuCurrentTab
s8 gPauseMenuCurrentTab extern
Referenced by pause_badges_draw_contents(), pause_badges_handle_input(), pause_handle_input(), pause_init(), pause_items_draw_contents(), pause_items_handle_input(), pause_map_draw_contents(), pause_map_draw_title(), pause_map_handle_input(), pause_partners_draw_contents(), pause_partners_draw_movelist(), pause_partners_handle_input(), pause_spirits_draw_contents(), pause_spirits_draw_title(), pause_spirits_handle_input(), pause_spirits_update(), pause_stats_draw_contents(), pause_stats_handle_input(), pause_tabs_draw_badges(), pause_tabs_draw_items(), pause_tabs_draw_map(), pause_tabs_draw_party(), pause_tabs_draw_spirits(), pause_tabs_draw_stats(), and pause_tabs_handle_input().
gPausePressedButtons
s32 gPausePressedButtons extern
Referenced by pause_badges_handle_input(), pause_handle_input(), pause_items_handle_input(), pause_map_handle_input(), pause_partners_handle_input(), pause_spirits_handle_input(), pause_stats_handle_input(), and pause_tabs_handle_input().
gPauseWS_0
WindowStyleCustom gPauseWS_0 extern
gPauseWS_1
WindowStyleCustom gPauseWS_1 extern
gPauseWS_10
WindowStyleCustom gPauseWS_10 extern
Referenced by pause_stats_draw_contents().
gPauseWS_11
WindowStyleCustom gPauseWS_11 extern
gPauseWS_12
WindowStyleCustom gPauseWS_12 extern
gPauseWS_13
WindowStyleCustom gPauseWS_13 extern
Referenced by pause_badges_draw_contents().
gPauseWS_14
WindowStyleCustom gPauseWS_14 extern
Referenced by pause_badges_draw_contents().
gPauseWS_15
WindowStyleCustom gPauseWS_15 extern
Referenced by pause_badges_draw_contents().
gPauseWS_16
WindowStyleCustom gPauseWS_16 extern
gPauseWS_17
WindowStyleCustom gPauseWS_17 extern
Referenced by pause_items_draw_contents().
gPauseWS_18
WindowStyleCustom gPauseWS_18 extern
Referenced by pause_items_draw_contents().
gPauseWS_19
WindowStyleCustom gPauseWS_19 extern
gPauseWS_2
WindowStyleCustom gPauseWS_2 extern
gPauseWS_20
WindowStyleCustom gPauseWS_20 extern
gPauseWS_21
WindowStyleCustom gPauseWS_21 extern
Referenced by pause_partners_draw_contents().
gPauseWS_22
WindowStyleCustom gPauseWS_22 extern
gPauseWS_23
WindowStyleCustom gPauseWS_23 extern
gPauseWS_24
WindowStyleCustom gPauseWS_24 extern
gPauseWS_25
WindowStyleCustom gPauseWS_25 extern
Referenced by pause_spirits_draw_contents().
gPauseWS_26
WindowStyleCustom gPauseWS_26 extern
gPauseWS_27
WindowStyleCustom gPauseWS_27 extern
Referenced by pause_map_draw_contents().
gPauseWS_28
WindowStyleCustom gPauseWS_28 extern
gPauseWS_3
WindowStyleCustom gPauseWS_3 extern
gPauseWS_4
WindowStyleCustom gPauseWS_4 extern
gPauseWS_5
WindowStyleCustom gPauseWS_5 extern
gPauseWS_6
WindowStyleCustom gPauseWS_6 extern
gPauseWS_7
WindowStyleCustom gPauseWS_7 extern
gPauseWS_8
WindowStyleCustom gPauseWS_8 extern
gPauseWS_9
WindowStyleCustom gPauseWS_9 extern
HES_AnimatedCursorHand
HudScript HES_AnimatedCursorHand extern
HES_Clock
HudScript HES_Clock extern
HES_Dash
HudScript HES_Dash extern
HES_DescMsgNext
HudScript HES_DescMsgNext extern
HES_DescMsgPrev
HudScript HES_DescMsgPrev extern
HES_FPCost
HudScript HES_FPCost extern
HES_HeaderBadges
HudScript HES_HeaderBadges extern
HES_HeaderItems
HudScript HES_HeaderItems extern
HES_HeaderMap
HudScript HES_HeaderMap extern
HES_HeaderParty
HudScript HES_HeaderParty extern
HES_HeaderSpirits
HudScript HES_HeaderSpirits extern
HES_HeaderStats
HudScript HES_HeaderStats extern
HES_LabelBpNeeded
HudScript HES_LabelBpNeeded extern
HES_ListNextPage
HudScript HES_ListNextPage extern
HES_ListPrevPage
HudScript HES_ListPrevPage extern
HES_MapWalk0
HudScript HES_MapWalk0 extern
HES_MarioHeadSmall
HudScript HES_MarioHeadSmall extern
HES_MoveBlueOrb
HudScript HES_MoveBlueOrb extern
HES_MoveDiamond
HudScript HES_MoveDiamond extern
HES_MoveGreenOrb
HudScript HES_MoveGreenOrb extern
HES_MoveRedOrb
HudScript HES_MoveRedOrb extern
HES_PartnerRank
HudScript HES_PartnerRank extern
HES_PressAButton
HudScript HES_PressAButton extern
HES_PressStartButton
HudScript HES_PressStartButton extern
HES_StartButtonText
HudScript HES_StartButtonText extern
HES_StatBoots0
HudScript HES_StatBoots0 extern
HES_StatBoots1
HudScript HES_StatBoots1 extern
HES_StatBoots2
HudScript HES_StatBoots2 extern
HES_StatBoots3
HudScript HES_StatBoots3 extern
HES_StatBp
HudScript HES_StatBp extern
HES_StatFp_1
HudScript HES_StatFp_1 extern
HES_StatHammer0
HudScript HES_StatHammer0 extern
HES_StatHammer1
HudScript HES_StatHammer1 extern
HES_StatHammer2
HudScript HES_StatHammer2 extern
HES_StatHammer3
HudScript HES_StatHammer3 extern
HES_StatStarPiece_1
HudScript HES_StatStarPiece_1 extern
HES_StatTimes
HudScript HES_StatTimes extern
HES_StatusHeart
HudScript HES_StatusHeart extern
HES_StatusSPEmptyIncrement
HudScript HES_StatusSPEmptyIncrement extern
Referenced by pause_stats_draw_contents().
HES_StatusSPIncrement1
HudScript HES_StatusSPIncrement1 extern
HES_StatusSPIncrement2
HudScript HES_StatusSPIncrement2 extern
HES_StatusSPIncrement3
HudScript HES_StatusSPIncrement3 extern
HES_StatusSPIncrement4
HudScript HES_StatusSPIncrement4 extern
HES_StatusSPIncrement5
HudScript HES_StatusSPIncrement5 extern
HES_StatusSPIncrement6
HudScript HES_StatusSPIncrement6 extern
HES_StatusSPIncrement7
HudScript HES_StatusSPIncrement7 extern
HES_StatusStar1
HudScript HES_StatusStar1 extern
HES_StatusStar2
HudScript HES_StatusStar2 extern
HES_StatusStar3
HudScript HES_StatusStar3 extern
HES_StatusStar4
HudScript HES_StatusStar4 extern
HES_StatusStar5
HudScript HES_StatusStar5 extern
HES_StatusStar6
HudScript HES_StatusStar6 extern
HES_StatusStar7
HudScript HES_StatusStar7 extern
HES_StatusStarEmpty
HudScript HES_StatusStarEmpty extern
Referenced by pause_stats_draw_contents().
HES_StatusStarPoint
HudScript HES_StatusStarPoint extern
HES_StickTapRight
HudScript HES_StickTapRight extern
HES_UnusedBadge
HudScript HES_UnusedBadge extern