papermario: src/pause/pause_items.c File Reference
pause_items.c File Reference
Macros
#define ITEM_NONE_STANDIN 0x7FFE
#define ITEM_INVALID 0x7FFF
Functions
void pause_items_draw_contents (MenuPanel *menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
void pause_items_init (MenuPanel *panel)
void pause_items_handle_input (MenuPanel *panel)
void pause_items_update (MenuPanel *panel)
void pause_items_cleanup (MenuPanel *panel)
s32 pause_items_comparator (s16 *a, s16 *b)
s32 pause_items_get_pos_x (s32 page, s32 itemIndex)
s32 pause_items_get_pos_y (s32 page, s32 itemIndex)
s32 pause_items_get_column (s32 page, s32 itemIdx)
s32 pause_items_get_row (s32 page, s32 itemIdx)
s32 pause_items_is_visible (s32 y)
s32 pause_items_scroll_offset_y (s32 beforeY)
s32 pause_items_scroll_offset_x (s32 beforeX)
void pause_items_load_items (s32 invItems)
Variables
HudScript * gPauseItemsElements []
MenuWindowBP gPauseItemsWindowBPs []
MenuPanel gPausePanelItems
Macro Definition Documentation
ITEM_INVALID
#define ITEM_INVALID 0x7FFF
Referenced by pause_items_draw_contents(), pause_items_handle_input(), and pause_items_load_items().
ITEM_NONE_STANDIN
#define ITEM_NONE_STANDIN 0x7FFE
Referenced by pause_items_draw_contents(), pause_items_handle_input(), and pause_items_load_items().
Function Documentation
pause_items_cleanup()
void pause_items_cleanup (MenuPanel * panel)
pause_items_comparator()
s32 pause_items_comparator (s16 * a, s16 * b)
Referenced by pause_items_load_items().
pause_items_draw_contents()
void pause_items_draw_contents (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
pause_items_get_column()
s32 pause_items_get_column (s32 page, s32 itemIdx)
Referenced by pause_items_draw_contents().
pause_items_get_pos_x()
s32 pause_items_get_pos_x (s32 page, s32 itemIndex)
Referenced by pause_items_draw_contents().
pause_items_get_pos_y()
s32 pause_items_get_pos_y (s32 page, s32 itemIndex)
Referenced by pause_items_draw_contents(), pause_items_load_items(), and pause_items_update().
pause_items_get_row()
s32 pause_items_get_row (s32 page, s32 itemIdx)
Referenced by pause_items_draw_contents().
pause_items_handle_input()
void pause_items_handle_input (MenuPanel * panel)
pause_items_init()
void pause_items_init (MenuPanel * panel)
pause_items_is_visible()
s32 pause_items_is_visible (s32 y)
Referenced by pause_items_draw_contents().
pause_items_load_items()
void pause_items_load_items (s32 invItems)
Referenced by pause_items_handle_input(), and pause_items_init().
pause_items_scroll_offset_x()
s32 pause_items_scroll_offset_x (s32 beforeX)
Referenced by pause_items_draw_contents().
pause_items_scroll_offset_y()
s32 pause_items_scroll_offset_y (s32 beforeY)
Referenced by pause_items_draw_contents().
pause_items_update()
void pause_items_update (MenuPanel * panel)
Variable Documentation
gPauseItemsElements
HudScript* gPauseItemsElements[]
Initial value:
= {
    &HES_StatBp, &HES_StatBp, &HES_StatBp, &HES_StatBp, &HES_StatBp,
    &HES_StatBp, &HES_StatBp, &HES_StatBp, &HES_StatBp, &HES_StatBp,
    &HES_StatBp, &HES_StatBp, &HES_StatBp, &HES_StatBp, &HES_StatBp,
    &HES_StatBp, &HES_ListPrevPage, &HES_ListNextPage, &HES_Dash,
    &HES_StatusStar1
}
Referenced by pause_items_init().
gPauseItemsWindowBPs
MenuWindowBP gPauseItemsWindowBPs[]
Initial value:
= {
    {
        .windowID = WINDOW_ID_PAUSE_ITEMS,
        .unk_01 = 0,
        .pos = { .x = 3, .y = 16 },
        .width = 289,
        .height = 154,
        .priority = WINDOW_PRIORITY_1,
        .fpDrawContents = &pause_items_draw_contents,
        .tab = NULL,
        .parentID = WINDOW_ID_PAUSE_MAIN,
        .fpUpdate = { WINDOW_UPDATE_HIDE },
        .extraFlags = 0,
        .style = { .customStyle = &gPauseWS_19 }
    }
}
Referenced by pause_items_init().
gPausePanelItems
MenuPanel gPausePanelItems
Initial value:
= {
    .initialized = FALSE,
    .col = 0,
    .row = 0,
    .selected = 0,
    .page = 0,
    .numCols = 0,
    .numRows = 0,
    .numPages = 0,
    .gridData = NULL,
    .fpInit = &pause_items_init,
    .fpHandleInput = &pause_items_handle_input,
    .fpUpdate = &pause_items_update,
    .fpCleanup = &pause_items_cleanup
}