papermario: src/pause/pause_gfx.c File Reference
pause_gfx.c File Reference
Functions
INCLUDE_IMG ("pause/image_1439F0.png", pause_image_1439F0_png)
INCLUDE_IMG ("pause/image_143BF0.png", pause_image_143BF0_png)
INCLUDE_IMG ("pause/image_143FF0.png", pause_image_143FF0_png)
INCLUDE_IMG ("pause/world_map.png", pause_world_map_png)
INCLUDE_PAL ("pause/world_map.pal", pause_world_map_pal)
INCLUDE_IMG ("pause/spirits_bg.png", pause_spirits_bg_png)
INCLUDE_PAL ("pause/spirits_bg.pal", pause_spirits_bg_pal)
INCLUDE_IMG ("pause/orbs.png", pause_orbs_png)
INCLUDE_IMG ("pause/map_location.png", pause_map_location_png)
INCLUDE_IMG ("pause/map_path_marker.png", pause_map_path_marker_png)
INCLUDE_IMG ("pause/map_arrows.png", pause_arrows_png)
INCLUDE_IMG ("pause/banner_hp.png", pause_banner_hp_png)
INCLUDE_PAL ("pause/banner_hp.pal", pause_banner_hp_pal)
INCLUDE_IMG ("pause/banner_fp.png", pause_banner_fp_png)
INCLUDE_PAL ("pause/banner_fp.pal", pause_banner_fp_pal)
INCLUDE_IMG ("pause/banner_bp.png", pause_banner_bp_png)
INCLUDE_PAL ("pause/banner_bp.pal", pause_banner_bp_pal)
INCLUDE_IMG ("pause/banner_boots.png", pause_banner_boots_png)
INCLUDE_PAL ("pause/banner_boots.pal", pause_banner_boots_pal)
INCLUDE_IMG ("pause/banner_hammer.png", pause_banner_hammer_png)
INCLUDE_PAL ("pause/banner_hammer.pal", pause_banner_hammer_pal)
INCLUDE_IMG ("pause/banner_star_energy.png", pause_banner_star_energy_png)
INCLUDE_PAL ("pause/banner_star_energy.pal", pause_banner_star_energy_pal)
INCLUDE_IMG ("pause/available.png", pause_available_png)
INCLUDE_PAL ("pause/available.pal", pause_available_pal)
INCLUDE_IMG ("pause/prompt_check_abilities.png", pause_prompt_check_abilities_png)
INCLUDE_PAL ("pause/prompt_check_abilities.pal", pause_prompt_check_abilities_pal)
INCLUDE_IMG ("pause/stats_bar.png", pause_stats_bar_png)
INCLUDE_PAL ("pause/stats_bar.pal", pause_stats_bar_pal)
s32 pause_get_menu_msg (s32 index)
void pause_draw_menu_label (s32 index, s32 x, s32 y)
Variables
Gfx PauseGfxBannerHp []
Gfx PauseGfxBannerFp []
Gfx PauseGfxBannerBp []
Gfx PauseGfxBannerBoots []
Gfx PauseGfxBannerHammer []
Gfx PauseGfxBannerStarEnergy []
Gfx PauseGfxStatsBar []
Gfx PauseGfxWorldMap []
Gfx PauseGfxPathPoints []
Gfx PauseGfxArrows []
Gfx PauseGfxOrbs []
Gfx PauseGfxAvailable []
Gfx PauseGfxCheckAbilities []
Gfx PauseGfxSpiritsBg []
s32 gPauseMessages []
Gfx * PauseGfxLabels []
BSS s8 gPauseBufferPal1 [512]
BSS s8 gPauseBufferImg1 [15752]
BSS s8 gPauseBufferPal2 [512]
BSS s8 gPauseBufferImg2 [15752]
Function Documentation
INCLUDE_IMG() [1/18]
INCLUDE_IMG ("pause/available.png" , pause_available_png)
INCLUDE_IMG() [2/18]
INCLUDE_IMG ("pause/banner_boots.png" , pause_banner_boots_png)
INCLUDE_IMG() [3/18]
INCLUDE_IMG ("pause/banner_bp.png" , pause_banner_bp_png)
INCLUDE_IMG() [4/18]
INCLUDE_IMG ("pause/banner_fp.png" , pause_banner_fp_png)
INCLUDE_IMG() [5/18]
INCLUDE_IMG ("pause/banner_hammer.png" , pause_banner_hammer_png)
INCLUDE_IMG() [6/18]
INCLUDE_IMG ("pause/banner_hp.png" , pause_banner_hp_png)
INCLUDE_IMG() [7/18]
INCLUDE_IMG ("pause/banner_star_energy.png" , pause_banner_star_energy_png)
INCLUDE_IMG() [8/18]
INCLUDE_IMG ("pause/image_1439F0.png" , pause_image_1439F0_png)
INCLUDE_IMG() [9/18]
INCLUDE_IMG ("pause/image_143BF0.png" , pause_image_143BF0_png)
INCLUDE_IMG() [10/18]
INCLUDE_IMG ("pause/image_143FF0.png" , pause_image_143FF0_png)
INCLUDE_IMG() [11/18]
INCLUDE_IMG ("pause/map_arrows.png" , pause_arrows_png)
INCLUDE_IMG() [12/18]
INCLUDE_IMG ("pause/map_location.png" , pause_map_location_png)
INCLUDE_IMG() [13/18]
INCLUDE_IMG ("pause/map_path_marker.png" , pause_map_path_marker_png)
INCLUDE_IMG() [14/18]
INCLUDE_IMG ("pause/orbs.png" , pause_orbs_png)
INCLUDE_IMG() [15/18]
INCLUDE_IMG ("pause/prompt_check_abilities.png" , pause_prompt_check_abilities_png)
INCLUDE_IMG() [16/18]
INCLUDE_IMG ("pause/spirits_bg.png" , pause_spirits_bg_png)
INCLUDE_IMG() [17/18]
INCLUDE_IMG ("pause/stats_bar.png" , pause_stats_bar_png)
INCLUDE_IMG() [18/18]
INCLUDE_IMG ("pause/world_map.png" , pause_world_map_png)
INCLUDE_PAL() [1/11]
INCLUDE_PAL ("pause/available.pal" , pause_available_pal)
INCLUDE_PAL() [2/11]
INCLUDE_PAL ("pause/banner_boots.pal" , pause_banner_boots_pal)
INCLUDE_PAL() [3/11]
INCLUDE_PAL ("pause/banner_bp.pal" , pause_banner_bp_pal)
INCLUDE_PAL() [4/11]
INCLUDE_PAL ("pause/banner_fp.pal" , pause_banner_fp_pal)
INCLUDE_PAL() [5/11]
INCLUDE_PAL ("pause/banner_hammer.pal" , pause_banner_hammer_pal)
INCLUDE_PAL() [6/11]
INCLUDE_PAL ("pause/banner_hp.pal" , pause_banner_hp_pal)
INCLUDE_PAL() [7/11]
INCLUDE_PAL ("pause/banner_star_energy.pal" , pause_banner_star_energy_pal)
INCLUDE_PAL() [8/11]
INCLUDE_PAL ("pause/prompt_check_abilities.pal" , pause_prompt_check_abilities_pal)
INCLUDE_PAL() [9/11]
INCLUDE_PAL ("pause/spirits_bg.pal" , pause_spirits_bg_pal)
INCLUDE_PAL() [10/11]
INCLUDE_PAL ("pause/stats_bar.pal" , pause_stats_bar_pal)
INCLUDE_PAL() [11/11]
INCLUDE_PAL ("pause/world_map.pal" , pause_world_map_pal)
pause_draw_menu_label()
void pause_draw_menu_label (s32 index, s32 x, s32 y)
Referenced by pause_badges_draw_contents(), pause_partners_draw_contents(), and pause_stats_draw_contents().
pause_get_menu_msg()
s32 pause_get_menu_msg (s32 index)
Referenced by pause_badges_draw_contents(), pause_badges_handle_input(), pause_items_draw_contents(), pause_items_handle_input(), pause_partners_draw_movelist_title(), pause_spirits_draw_title(), pause_spirits_handle_input(), pause_stats_draw_contents(), pause_stats_handle_input(), pause_tabs_draw_badges(), pause_tabs_draw_stats(), pause_tabs_handle_input(), and pause_tutorial_draw_contents().
Variable Documentation
gPauseBufferImg1
BSS s8 gPauseBufferImg1[15752]
gPauseBufferImg2
BSS s8 gPauseBufferImg2[15752]
gPauseBufferPal1
BSS s8 gPauseBufferPal1[512]
gPauseBufferPal2
BSS s8 gPauseBufferPal2[512]
gPauseMessages
s32 gPauseMessages[]
Referenced by pause_get_menu_msg().
PauseGfxArrows
Gfx PauseGfxArrows[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureTile_4b(pause_arrows_png, G_IM_FMT_IA, pause_arrows_png_width, pause_arrows_png_height, 0, 0, pause_arrows_png_width - 1, pause_arrows_png_height - 1, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 4, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by pause_map_draw_contents().
PauseGfxAvailable
Gfx PauseGfxAvailable[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal16(0, pause_available_pal),
    gsDPLoadTextureTile_4b(pause_available_png, G_IM_FMT_CI, pause_available_png_width, pause_available_png_height, 0, 0, pause_available_png_width - 1, pause_available_png_height - 1, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, 6, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
PauseGfxBannerBoots
Gfx PauseGfxBannerBoots[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal16(0, pause_banner_boots_pal),
    gsDPLoadTextureTile_4b(pause_banner_boots_png, G_IM_FMT_CI, pause_banner_boots_png_width, pause_banner_boots_png_height, 0, 0, pause_banner_boots_png_width - 1, pause_banner_boots_png_height - 1, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, 6, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
PauseGfxBannerBp
Gfx PauseGfxBannerBp[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal16(0, pause_banner_bp_pal),
    gsDPLoadTextureTile_4b(pause_banner_bp_png, G_IM_FMT_CI, pause_banner_bp_png_width, pause_banner_bp_png_height, 0, 0, pause_banner_bp_png_width - 1, pause_banner_bp_png_height - 1, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, 6, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
PauseGfxBannerFp
Gfx PauseGfxBannerFp[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal16(0, pause_banner_fp_pal),
    gsDPLoadTextureTile_4b(pause_banner_fp_png, G_IM_FMT_CI, pause_banner_fp_png_width, pause_banner_fp_png_height, 0, 0, pause_banner_fp_png_width - 1, pause_banner_fp_png_height - 1, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, 6, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
PauseGfxBannerHammer
Gfx PauseGfxBannerHammer[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal16(0, pause_banner_hammer_pal),
    gsDPLoadTextureTile_4b(pause_banner_hammer_png, G_IM_FMT_CI, pause_banner_hammer_png_width, pause_banner_hammer_png_height, 0, 0, pause_banner_hammer_png_width - 1, pause_banner_hammer_png_height - 1, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, 6, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
PauseGfxBannerHp
Gfx PauseGfxBannerHp[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal16(0, pause_banner_hp_pal),
    gsDPLoadTextureTile_4b(pause_banner_hp_png, G_IM_FMT_CI, pause_banner_hp_png_width, pause_banner_hp_png_height, 0, 0, pause_banner_hp_png_width - 1, pause_banner_hp_png_height - 1, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, 6, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
PauseGfxBannerStarEnergy
Gfx PauseGfxBannerStarEnergy[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal16(0, pause_banner_star_energy_pal),
    gsDPLoadTextureTile_4b(pause_banner_star_energy_png, G_IM_FMT_CI, pause_banner_star_energy_png_width, pause_banner_star_energy_png_height, 0, 0, pause_banner_star_energy_png_width - 1, pause_banner_star_energy_png_height - 1, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, 6, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
PauseGfxCheckAbilities
Gfx PauseGfxCheckAbilities[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal16(0, pause_prompt_check_abilities_pal),
    gsDPLoadTextureTile_4b(pause_prompt_check_abilities_png, G_IM_FMT_CI, pause_prompt_check_abilities_png_width, pause_prompt_check_abilities_png_height, 0, 0, pause_prompt_check_abilities_png_width - 1, pause_prompt_check_abilities_png_height - 1, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, 7, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
PauseGfxLabels
Gfx* PauseGfxLabels[]
Initial value:
= {
    [PAUSE_LBL_HP]        PauseGfxBannerHp,
    [PAUSE_LBL_FP]        PauseGfxBannerFp,
    [PAUSE_LBL_BP]        PauseGfxBannerBp,
    [PAUSE_LBL_BOOTS]     PauseGfxBannerBoots,
    [PAUSE_LBL_HAMMER]    PauseGfxBannerHammer,
    [PAUSE_LBL_ENERGY]    PauseGfxBannerStarEnergy,
    [PAUSE_LBL_STATS]     PauseGfxStatsBar,
    [PAUSE_LBL_AVAILABLE] PauseGfxAvailable,
    [PAUSE_LBL_ABILITIES] PauseGfxCheckAbilities,
}
Referenced by pause_draw_menu_label().
PauseGfxOrbs
Gfx PauseGfxOrbs[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureTile(pause_orbs_png, G_IM_FMT_RGBA, G_IM_SIZ_16b, pause_orbs_png_width, pause_orbs_png_height, 0, 0, pause_orbs_png_width - 1, pause_orbs_png_height - 1, 0, G_TX_NOMIRROR | G_TX_WRAP, G_TX_NOMIRROR | G_TX_WRAP, 3, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(PM_CC_01, PM_CC_01),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by pause_badges_draw_contents().
PauseGfxPathPoints
Gfx PauseGfxPathPoints[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetRenderMode(G_RM_CLD_SURF, G_RM_CLD_SURF2),
    gsDPSetCombineMode(PM_CC_2F, PM_CC_2F),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureTile(pause_map_location_png, G_IM_FMT_IA, G_IM_SIZ_8b, 16, 16, 0, 0, 15, 15, 0, G_TX_CLAMP, G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadMultiTile(pause_map_path_marker_png, 0x100, 1, G_IM_FMT_IA, G_IM_SIZ_8b, 16, 16, 0, 0, 15, 15, 0, G_TX_CLAMP, G_TX_CLAMP, 4, 4, G_TX_NOLOD, G_TX_NOLOD),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by pause_map_draw_contents().
PauseGfxSpiritsBg
Gfx PauseGfxSpiritsBg[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetTextureFilter(G_TF_AVERAGE),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPLoadTLUT_pal16(0, pause_spirits_bg_pal),
    gsDPSetRenderMode(G_RM_OPA_SURF, G_RM_OPA_SURF2),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_CULL_BOTH | G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by pause_spirits_draw_contents().
PauseGfxStatsBar
Gfx PauseGfxStatsBar[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPLoadTLUT_pal16(0, pause_stats_bar_pal),
    gsDPLoadTextureTile_4b(pause_stats_bar_png, G_IM_FMT_CI, pause_stats_bar_png_width, pause_stats_bar_png_height, 0, 0, pause_stats_bar_png_width - 1, pause_stats_bar_png_height - 1, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_MIRROR | G_TX_WRAP, 8, 3, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetRenderMode(AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c1(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM), AA_EN | CVG_DST_FULL | ZMODE_OPA | CVG_X_ALPHA | GBL_c2(G_BL_CLR_IN, G_BL_A_IN, G_BL_CLR_MEM, G_BL_A_MEM)),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_CULL_BACK | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
PauseGfxWorldMap
Gfx PauseGfxWorldMap[]
Initial value:
= {
    gsDPPipeSync(),
    gsSPTexture(-1, -1, 0, G_TX_RENDERTILE, G_ON),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureLUT(G_TT_RGBA16),
    gsDPSetTextureFilter(G_TF_POINT),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPLoadTLUT_pal256(pause_world_map_pal),
    gsDPSetRenderMode(G_RM_OPA_SURF, G_RM_OPA_SURF2),
    gsDPSetCombineMode(G_CC_DECALRGBA, G_CC_DECALRGBA),
    gsSPClearGeometryMode(G_CULL_BOTH | G_LIGHTING),
    gsSPSetGeometryMode(G_SHADE | G_SHADING_SMOOTH),
    gsSPEndDisplayList(),
}
Referenced by pause_map_draw_contents().