papermario: src/pause/pause_badges.c File Reference
pause_badges.c File Reference
Macros
#define BADGE_NONE_STANDIN 0x7FFE
#define BADGE_INVALID 0x7FFF
#define OFFSET_1_X 43
#define OFFSET_1_Y 81
#define OFFSET_2_X 16
#define OFFSET_3_X 69
#define OFFSET_3_Y 74
#define X_VAR1 241
#define X_VAR2 235
#define X_VAR3 12
#define X_VAR4 73
#define X_VAR5 10
#define X_VAR6 19
#define X_VAR7 12
#define X_VAR8 21
#define X_VAR9 86
#define X_VAR10 90
#define Y_VAR1 37
#define Y_VAR2 42
#define W_VAR1 91
#define W_VAR2 91
Enumerations
enum BadgeEquipResult { EQUIP_RESULT_ALREADY_EQUIPPED , EQUIP_RESULT_NOT_ENOUGH_BP , EQUIP_RESULT_TOO_MANY_BADGES , EQUIP_RESULT_SUCCESS }
Functions
void pause_badges_draw_contents (MenuPanel *menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
void pause_badges_init (MenuPanel *panel)
void pause_badges_handle_input (MenuPanel *panel)
void pause_badges_update (MenuPanel *panel)
void pause_badges_cleanup (MenuPanel *panel)
s32 pause_badges_comparator (s16 *a, s16 *b)
s32 pause_badges_count_all (void)
s32 pause_badges_count_equipped (void)
s32 pause_badges_get_pos_x (s32 page, s32 itemIndex)
s32 pause_badges_get_pos_y (s32 page, s32 itemIndex)
s32 pause_badges_get_column (s32 page, s32 itemIdx)
s32 pause_badges_get_row (s32 page, s32 itemIdx)
s32 pause_badges_is_visible (s32 y)
s32 pause_badges_scroll_offset_y (s32 offset)
s32 pause_badges_scroll_offset_x (s32 x)
s32 pause_badges_try_remove (s16 badgeID)
s32 pause_badges_try_equip (s16 badgeID)
void pause_badges_draw_bp_orbs (s32 orbState, s32 x, s32 y)
void pause_badges_load_badges (s32 onlyEquipped)
Variables
Gfx PauseGfxOrbs []
HudScript * gPauseBadgesElements [][22]
MenuWindowBP gPauseBadgesWindowBPs []
MenuPanel gPausePanelBadges
Macro Definition Documentation
BADGE_INVALID
#define BADGE_INVALID 0x7FFF
Referenced by pause_badges_comparator(), pause_badges_draw_contents(), pause_badges_handle_input(), pause_badges_load_badges(), pause_badges_try_equip(), and pause_badges_try_remove().
BADGE_NONE_STANDIN
#define BADGE_NONE_STANDIN 0x7FFE
Referenced by pause_badges_draw_contents(), pause_badges_handle_input(), pause_badges_init(), pause_badges_load_badges(), and pause_badges_try_equip().
OFFSET_1_X
#define OFFSET_1_X 43
Referenced by pause_badges_draw_contents().
OFFSET_1_Y
#define OFFSET_1_Y 81
Referenced by pause_badges_draw_contents().
OFFSET_2_X
#define OFFSET_2_X 16
Referenced by pause_badges_draw_contents().
OFFSET_3_X
#define OFFSET_3_X 69
Referenced by pause_badges_draw_contents().
OFFSET_3_Y
#define OFFSET_3_Y 74
Referenced by pause_badges_draw_contents().
W_VAR1
#define W_VAR1 91
Referenced by pause_badges_draw_contents().
W_VAR2
#define W_VAR2 91
Referenced by pause_badges_draw_contents().
X_VAR1
#define X_VAR1 241
Referenced by pause_badges_draw_contents().
X_VAR10
#define X_VAR10 90
Referenced by pause_badges_draw_contents().
X_VAR2
#define X_VAR2 235
Referenced by pause_badges_draw_contents().
X_VAR3
#define X_VAR3 12
Referenced by pause_badges_draw_contents().
X_VAR4
#define X_VAR4 73
Referenced by pause_badges_draw_contents().
X_VAR5
#define X_VAR5 10
Referenced by pause_badges_draw_contents().
X_VAR6
#define X_VAR6 19
Referenced by pause_badges_draw_contents().
X_VAR7
#define X_VAR7 12
Referenced by pause_badges_draw_contents().
X_VAR8
#define X_VAR8 21
Referenced by pause_badges_draw_contents().
X_VAR9
#define X_VAR9 86
Referenced by pause_badges_draw_contents().
Y_VAR1
#define Y_VAR1 37
Referenced by pause_badges_draw_contents().
Y_VAR2
#define Y_VAR2 42
Referenced by pause_badges_draw_contents().
Enumeration Type Documentation
BadgeEquipResult
enum BadgeEquipResult
Enumerator
EQUIP_RESULT_ALREADY_EQUIPPED
EQUIP_RESULT_NOT_ENOUGH_BP
EQUIP_RESULT_TOO_MANY_BADGES
EQUIP_RESULT_SUCCESS
Function Documentation
pause_badges_cleanup()
void pause_badges_cleanup (MenuPanel * panel)
pause_badges_comparator()
s32 pause_badges_comparator (s16 * a, s16 * b)
Referenced by pause_badges_count_all(), and pause_badges_count_equipped().
pause_badges_count_all()
s32 pause_badges_count_all (void)
Referenced by pause_badges_init().
pause_badges_count_equipped()
s32 pause_badges_count_equipped (void)
Referenced by pause_badges_load_badges().
pause_badges_draw_bp_orbs()
void pause_badges_draw_bp_orbs (s32 orbState, s32 x, s32 y)
Referenced by pause_badges_draw_contents().
pause_badges_draw_contents()
void pause_badges_draw_contents (MenuPanel * menu, s32 baseX, s32 baseY, s32 width, s32 height, s32 opacity, s32 darkening)
pause_badges_get_column()
s32 pause_badges_get_column (s32 page, s32 itemIdx)
Referenced by pause_badges_draw_contents().
pause_badges_get_pos_x()
s32 pause_badges_get_pos_x (s32 page, s32 itemIndex)
Referenced by pause_badges_draw_contents().
pause_badges_get_pos_y()
s32 pause_badges_get_pos_y (s32 page, s32 itemIndex)
Referenced by pause_badges_draw_contents(), pause_badges_load_badges(), and pause_badges_update().
pause_badges_get_row()
s32 pause_badges_get_row (s32 page, s32 itemIdx)
Referenced by pause_badges_draw_contents().
pause_badges_handle_input()
void pause_badges_handle_input (MenuPanel * panel)
pause_badges_init()
void pause_badges_init (MenuPanel * panel)
pause_badges_is_visible()
s32 pause_badges_is_visible (s32 y)
Referenced by pause_badges_draw_contents().
pause_badges_load_badges()
void pause_badges_load_badges (s32 onlyEquipped)
Referenced by pause_badges_handle_input(), and pause_badges_init().
pause_badges_scroll_offset_x()
s32 pause_badges_scroll_offset_x (s32 x)
Referenced by pause_badges_draw_contents().
pause_badges_scroll_offset_y()
s32 pause_badges_scroll_offset_y (s32 offset)
Referenced by pause_badges_draw_contents().
pause_badges_try_equip()
s32 pause_badges_try_equip (s16 badgeID)
Referenced by pause_badges_handle_input().
pause_badges_try_remove()
s32 pause_badges_try_remove (s16 badgeID)
Referenced by pause_badges_handle_input().
pause_badges_update()
void pause_badges_update (MenuPanel * panel)
Variable Documentation
gPauseBadgesElements
HudScript* gPauseBadgesElements[][22]
Referenced by pause_badges_init().
gPauseBadgesWindowBPs
MenuWindowBP gPauseBadgesWindowBPs[]
Initial value:
= {
    {
        .windowID = WIN_PAUSE_BADGES,
        .unk_01 = 0,
        .pos = { .x = 3, .y = 16 },
        .width = 289,
        .height = 154,
        .priority = WINDOW_PRIORITY_1,
        .fpDrawContents = &pause_badges_draw_contents,
        .tab = NULL,
        .parentID = WIN_PAUSE_MAIN,
        .fpUpdate = { WINDOW_UPDATE_HIDE },
        .extraFlags = 0,
        .style = { .customStyle = &gPauseWS_16 }
    }
}
Referenced by pause_badges_init().
gPausePanelBadges
MenuPanel gPausePanelBadges
Initial value:
= {
    .initialized = FALSE,
    .col = 0,
    .row = 0,
    .selected = 0,
    .state = 0,
    .numCols = 0,
    .numRows = 0,
    .numPages = 0,
    .gridData = NULL,
    .fpInit = &pause_badges_init,
    .fpHandleInput = &pause_badges_handle_input,
    .fpUpdate = &pause_badges_update,
    .fpCleanup = &pause_badges_cleanup
}
PauseGfxOrbs
Gfx PauseGfxOrbs[] extern
Referenced by pause_badges_draw_contents().