papermario: src/effects/peach_star_beam.c File Reference
peach_star_beam.c File Reference
Functions
void peach_star_beam_init (EffectInstance *effect)
void peach_star_beam_update (EffectInstance *effect)
void peach_star_beam_render (EffectInstance *effect)
void peach_star_beam_appendGfx (void *effect)
EffectInstance * peach_star_beam_main (s32 type, f32 x, f32 y, f32 z, f32 arg4, s32 duration)
Variables
Gfx D_09004FE8_3EAF18 []
Gfx D_09005090_3EAFC0 []
Gfx D_090050F0_3EB020 []
Gfx D_09005168_3EB098 []
Gfx D_090051E0_3EB110 []
Gfx D_09005258_3EB188 []
Gfx D_090052D0_3EB200 []
Gfx D_09005348_3EB278 []
Gfx D_090053C0_3EB2F0 []
Gfx D_09005438_3EB368 []
Gfx D_090054B0_3EB3E0 []
Gfx D_09005570_3EB4A0 []
Gfx D_09005590_3EB4C0 []
Gfx * D_E010CA10 [] = { D_090054B0_3EB3E0 }
Gfx * D_E010CA14 [] = { D_09004FE8_3EAF18 }
Gfx * D_E010CA18 [8]
Gfx * D_E010CA38 [8]
Function Documentation
peach_star_beam_appendGfx()
void peach_star_beam_appendGfx (void * effect)
Referenced by peach_star_beam_render().
peach_star_beam_init()
void peach_star_beam_init (EffectInstance * effect)
Referenced by peach_star_beam_main().
peach_star_beam_main()
EffectInstance * peach_star_beam_main (s32 type, f32 x, f32 y, f32 z, f32 arg4, s32 duration)
peach_star_beam_render()
void peach_star_beam_render (EffectInstance * effect)
Referenced by peach_star_beam_main().
peach_star_beam_update()
void peach_star_beam_update (EffectInstance * effect)
Referenced by peach_star_beam_main().
Variable Documentation
D_09004FE8_3EAF18
Gfx D_09004FE8_3EAF18[] extern
D_09005090_3EAFC0
Gfx D_09005090_3EAFC0[] extern
Referenced by peach_star_beam_appendGfx().
D_090050F0_3EB020
Gfx D_090050F0_3EB020[] extern
D_09005168_3EB098
Gfx D_09005168_3EB098[] extern
D_090051E0_3EB110
Gfx D_090051E0_3EB110[] extern
D_09005258_3EB188
Gfx D_09005258_3EB188[] extern
D_090052D0_3EB200
Gfx D_090052D0_3EB200[] extern
D_09005348_3EB278
Gfx D_09005348_3EB278[] extern
D_090053C0_3EB2F0
Gfx D_090053C0_3EB2F0[] extern
D_09005438_3EB368
Gfx D_09005438_3EB368[] extern
D_090054B0_3EB3E0
Gfx D_090054B0_3EB3E0[] extern
D_09005570_3EB4A0
Gfx D_09005570_3EB4A0[] extern
D_09005590_3EB4C0
Gfx D_09005590_3EB4C0[] extern
D_E010CA10
Gfx* D_E010CA10[] = { D_090054B0_3EB3E0 }
Referenced by peach_star_beam_appendGfx().
D_E010CA14
Gfx* D_E010CA14[] = { D_09004FE8_3EAF18 }
Referenced by peach_star_beam_appendGfx().
D_E010CA18
Gfx* D_E010CA18[8]
Initial value:
= {
    D_09005590_3EB4C0, D_09005570_3EB4A0, D_09005570_3EB4A0, D_09005570_3EB4A0,
    D_09005570_3EB4A0, D_09005570_3EB4A0, D_09005570_3EB4A0, D_09005570_3EB4A0
}
Referenced by peach_star_beam_appendGfx().
D_E010CA38
Gfx* D_E010CA38[8]
Initial value:
= {
    D_090050F0_3EB020, D_09005168_3EB098, D_090051E0_3EB110, D_09005258_3EB188,
    D_090052D0_3EB200, D_09005348_3EB278, D_090053C0_3EB2F0, D_09005438_3EB368
}
Referenced by peach_star_beam_appendGfx().