papermario: src/world/area_obk/obk_07/phonograph.c File Reference
phonograph.c File Reference
Data Structures
struct PhonographData
Enumerations
enum {
PHONOGRAPH_HUD_STATE_DESTROYED = -1 , PHONOGRAPH_HUD_STATE_INIT = 0 , PHONOGRAPH_HUD_STATE_APPEAR = 1 , PHONOGRAPH_HUD_STATE_MASHING = 10 ,
PHONOGRAPH_HUD_STATE_FINAL = 11
}
Functions
PhonographData *N GetPhonographData (void)
void N DrawMashMeter (s32 posX, s32 posY, s32 fillValue)
void N DrawMashMeterWithDivisor (s32 baseX, s32 baseY, s32 fillValue, s32 smoothDivisor)
void N worker_update_phonograph_hud (void)
void N worker_draw_phonograph_hud (void)
Variables
HudScript HES_SlowlyMashAButton
Data Structure Documentation
PhonographData
struct PhonographData
Data Fields
s32 barFillWidth
HudElemID buttonHID
f32 crankRotation
s32 fillValue
s32 hudBaseX
s32 hudBaseY
s32 hudWorker
s32 inputBuffer[90]
s32 inputBufferPos
s32 mashMeterDividers[6]
s32 mashMeterIntervals
s32 mashMeterSmoothDivisor
s32 meterFillAmount
HudElemID meterHID
f32 modelScale
HudElemID okHID
f32 recordRotation
s32 songName
s32 state
f32 timeScale
s32 unk_1D8
s8 unk_1DC
char unk_1DD[0x3]
char unk_48[0x4]
s32 updateCrankScriptID
s32 updateRecordScriptID
s32 updateScaleScriptID
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PHONOGRAPH_HUD_STATE_DESTROYED
PHONOGRAPH_HUD_STATE_INIT
PHONOGRAPH_HUD_STATE_APPEAR
PHONOGRAPH_HUD_STATE_MASHING
PHONOGRAPH_HUD_STATE_FINAL
Function Documentation
DrawMashMeter()
void N DrawMashMeter (s32 posX, s32 posY, s32 fillValue)
Referenced by DrawMashMeterWithDivisor().
DrawMashMeterWithDivisor()
void N DrawMashMeterWithDivisor (s32 baseX, s32 baseY, s32 fillValue, s32 smoothDivisor)
Referenced by worker_draw_phonograph_hud().
GetPhonographData()
PhonographData *N GetPhonographData (void)
Referenced by DrawMashMeter(), DrawMashMeterWithDivisor(), worker_draw_phonograph_hud(), and worker_update_phonograph_hud().
worker_draw_phonograph_hud()
void N worker_draw_phonograph_hud (void)
worker_update_phonograph_hud()
void N worker_update_phonograph_hud (void)
Variable Documentation
HES_SlowlyMashAButton
HudScript HES_SlowlyMashAButton extern
Referenced by worker_update_phonograph_hud().