papermario: src/effects/pink_sparkles.c File Reference
pink_sparkles.c File Reference
Functions
void pink_sparkles_init (EffectInstance *effect)
void pink_sparkles_update (EffectInstance *effect)
void pink_sparkles_render (EffectInstance *effect)
void pink_sparkles_appendGfx (void *effect)
EffectInstance * pink_sparkles_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
Variables
Gfx D_09000F20_338EE0 []
Gfx D_090011C8_339188 []
Gfx D_090011E0_3391A0 []
Gfx D_090011F8_3391B8 []
Gfx D_09001210_3391D0 []
Gfx D_09001228_3391E8 []
Gfx D_09001240_339200 []
Gfx D_09001258_339218 []
Gfx D_09001270_339230 []
Gfx * D_E01248A0 []
s8 D_E01248C0 []
u8 D_E0124BC0 []
u8 D_E0124BE4 []
Function Documentation
pink_sparkles_appendGfx()
void pink_sparkles_appendGfx (void * effect)
Referenced by pink_sparkles_render().
pink_sparkles_init()
void pink_sparkles_init (EffectInstance * effect)
Referenced by pink_sparkles_main().
pink_sparkles_main()
EffectInstance * pink_sparkles_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
pink_sparkles_render()
void pink_sparkles_render (EffectInstance * effect)
Referenced by pink_sparkles_main().
pink_sparkles_update()
void pink_sparkles_update (EffectInstance * effect)
Referenced by pink_sparkles_main().
Variable Documentation
D_09000F20_338EE0
Gfx D_09000F20_338EE0[] extern
Referenced by pink_sparkles_appendGfx().
D_090011C8_339188
Gfx D_090011C8_339188[] extern
D_090011E0_3391A0
Gfx D_090011E0_3391A0[] extern
D_090011F8_3391B8
Gfx D_090011F8_3391B8[] extern
D_09001210_3391D0
Gfx D_09001210_3391D0[] extern
D_09001228_3391E8
Gfx D_09001228_3391E8[] extern
D_09001240_339200
Gfx D_09001240_339200[] extern
D_09001258_339218
Gfx D_09001258_339218[] extern
D_09001270_339230
Gfx D_09001270_339230[] extern
D_E01248A0
Gfx* D_E01248A0[]
Initial value:
= {
    D_09001210_3391D0, D_09001228_3391E8, D_09001240_339200,
    D_09001258_339218, D_09001270_339230, D_090011C8_339188,
    D_090011E0_3391A0, D_090011F8_3391B8
}
Referenced by pink_sparkles_appendGfx().
D_E01248C0
s8 D_E01248C0[]
Referenced by pink_sparkles_main().
D_E0124BC0
u8 D_E0124BC0[]
Initial value:
= {
    0xFE, 0xAC, 0xAC,
    0xFE, 0xAC, 0xD5,
    0xFE, 0xB4, 0x9A,
    0xD5, 0xB4, 0xFE,
    0xB4, 0xB4, 0xFE,
    0xB4, 0xDD, 0xFE,
    0xB4, 0xFE, 0xFE,
    0xB4, 0xFE, 0xD5,
    0xB4, 0xFE, 0xB4,
    0xD5, 0xFE, 0xB4,
    0xFE, 0xFE, 0xB4,
    0xFE, 0xD5, 0xAC
}
Referenced by pink_sparkles_appendGfx().
D_E0124BE4
u8 D_E0124BE4[]
Initial value:
= {
    0x1E, 0x3C, 0x5A, 0x64, 0x68,
    0x6A, 0x6C, 0x6E, 0x70, 0x71,
    0x71, 0x6E, 0x6B, 0x67, 0x64,
    0x68, 0x6A, 0x6C, 0x6E, 0x70,
    0x71, 0x71, 0x6E, 0x6B, 0x67
}
Referenced by pink_sparkles_update().