papermario: src/world/common/enemy/ai/PiranhaPlantAI.inc.c File Reference
PiranhaPlantAI.inc.c File Reference
Functions
void PiranhaPlantAI_00 (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void PiranhaPlantAI_01 (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void PiranhaPlantAI_10 (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void PiranhaPlantAI_11 (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void PiranhaPlantAI_12 (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void PiranhaPlantAI_13 (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
void PiranhaPlantAI_LosePlayer (Evt *script, MobileAISettings *aiSettings, EnemyDetectVolume *territory)
s32 PiranhaPlantAI_Main (Evt *script, s32 isInitialCall)
Function Documentation
PiranhaPlantAI_00()
void PiranhaPlantAI_00 (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by PiranhaPlantAI_Main().
PiranhaPlantAI_01()
void PiranhaPlantAI_01 (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by PiranhaPlantAI_Main().
PiranhaPlantAI_10()
void PiranhaPlantAI_10 (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by PiranhaPlantAI_Main().
PiranhaPlantAI_11()
void PiranhaPlantAI_11 (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by PiranhaPlantAI_Main().
PiranhaPlantAI_12()
void PiranhaPlantAI_12 (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by PiranhaPlantAI_Main().
PiranhaPlantAI_13()
void PiranhaPlantAI_13 (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by PiranhaPlantAI_Main().
PiranhaPlantAI_LosePlayer()
void PiranhaPlantAI_LosePlayer (Evt * script, MobileAISettings * aiSettings, EnemyDetectVolume * territory)
Referenced by PiranhaPlantAI_Main().
PiranhaPlantAI_Main()
s32 PiranhaPlantAI_Main (Evt * script, s32 isInitialCall)