papermario: src/entity/jan_iwa/Plants2.c File Reference
Plants2.c File Reference
Functions
void entity_BellbellPlant_idle (Entity *entity)
void entity_TrumpetPlant_idle (Entity *entity)
void entity_TrumpetPlant_create_effect (Entity *entity)
void entity_TrumpetPlant_spawn_coin (Entity *entity)
void entity_Munchlesia_init (Entity *entity)
void func_802BC050_E2E980 (Entity *entity)
void func_802BC0B8_E2E9E8 (Entity *entity)
void func_802BC0F0_E2EA20 (Entity *entity)
void func_802BC17C_E2EAAC (Entity *entity)
s32 entity_Munchlesia_create_child (Entity *entity, EntityBlueprint *EntityBlueprint)
void func_802BC220_E2EB50 (Entity *entity)
void func_802BC250_E2EB80 (Entity *entity)
void func_802BC274_E2EBA4 (Entity *entity)
void func_802BC2B4_E2EBE4 (Entity *entity)
void func_802BC308_E2EC38 (Entity *entity)
void func_802BC32C_E2EC5C (Entity *entity)
void entity_Munchlesia_create_child_reset1 (Entity *entity)
void entity_Munchlesia_create_child_reset2 (Entity *entity)
void func_802BC3A0_E2ECD0 (void)
void entity_MunchlesiaChewing_init (Entity *entity)
void func_802BC3E4_E2ED14 (Entity *entity)
Variables
EntityBlueprint Entity_MunchlesiaReset
EntityBlueprint Entity_MunchlesiaGrab
EntityBlueprint Entity_MunchlesiaEnvelop
EntityBlueprint Entity_MunchlesiaBeginChew
EntityBlueprint Entity_MunchlesiaChewing
EntityBlueprint Entity_MunchlesiaSpitOut
EntityBlueprint Entity_MunchlesiaReset1
EntityBlueprint Entity_MunchlesiaReset2
EntityModelScript Entity_RenderNone_Script
AnimScript Entity_BellbellPlant_AnimationIdle
AnimScript Entity_BellbellPlant_AnimationUse
StaticAnimatorNode * Entity_BellbellPlant_Mesh []
AnimScript Entity_TrumpetPlant_AnimationIdle
AnimScript Entity_TrumpetPlant_AnimationUse
StaticAnimatorNode * Entity_TrumpetPlant_Mesh []
AnimScript Entity_MunchlesiaReset_AnimationIdle
AnimScript Entity_MunchlesiaReset_AnimationReset
StaticAnimatorNode * Entity_MunchlesiaReset_Mesh []
AnimScript Entity_MunchlesiaGrab_Animation
StaticAnimatorNode * Entity_MunchlesiaGrab_Mesh []
AnimScript Entity_MunchlesiaEnvelop_Animation
StaticAnimatorNode * Entity_MunchlesiaEnvelop_Mesh []
AnimScript Entity_MunchlesiaBeginChew_Animation
StaticAnimatorNode * Entity_MunchlesiaBeginChew_Mesh []
AnimScript Entity_MunchlesiaChewing_Animation
StaticAnimatorNode * Entity_MunchlesiaChewing_Mesh []
AnimScript Entity_MunchlesiaSpitOut_Animation
StaticAnimatorNode * Entity_MunchlesiaSpitOut_Mesh []
AnimScript Entity_MunchlesiaReset1_Animation
StaticAnimatorNode * Entity_MunchlesiaReset1_Mesh []
EntityScript Entity_BellbellPlant_Script
EntityScript Entity_TrumpetPlant_Script
EntityScript Entity_Munchlesia_Script
EntityScript Entity_MunchlesiaReset_Script
EntityScript Entity_MunchlesiaGrab_Script
EntityScript Entity_MunchlesiaEnvelop_Script
EntityScript Entity_MunchlesiaBeginChew_Script
EntityScript Entity_MunchlesiaChewing_Script
EntityScript Entity_MunchlesiaSpitOut_Script
EntityScript Entity_MunchlesiaReset1_Script
EntityScript Entity_MunchlesiaReset2_Script
DmaEntry Entity_MunchlesiaReset_dma [] = { ENTITY_ROM(MunchlesiaReset_gfx), ENTITY_ROM(MunchlesiaReset_anim) }
DmaEntry Entity_MunchlesiaGrab_dma [] = { ENTITY_ROM(MunchlesiaGrab_gfx), ENTITY_ROM(MunchlesiaGrab_anim) }
DmaEntry Entity_MunchlesiaEnvelop_dma [] = { ENTITY_ROM(MunchlesiaEnvelop_gfx), ENTITY_ROM(MunchlesiaEnvelop_anim) }
DmaEntry Entity_MunchlesiaBeginChew_dma [] = { ENTITY_ROM(MunchlesiaBeginChew_gfx), ENTITY_ROM(MunchlesiaBeginChew_anim) }
DmaEntry Entity_MunchlesiaChewing_dma [] = { ENTITY_ROM(MunchlesiaChewing_gfx), ENTITY_ROM(MunchlesiaChewing_anim) }
DmaEntry Entity_MunchlesiaSpitOut_dma [] = { ENTITY_ROM(MunchlesiaSpitOut_gfx), ENTITY_ROM(MunchlesiaSpitOut_anim) }
DmaEntry Entity_MunchlesiaReset1_dma [] = { ENTITY_ROM(MunchlesiaReset1_gfx), ENTITY_ROM(MunchlesiaReset1_anim) }
DmaEntry Entity_BellbellPlant_dma [] = { ENTITY_ROM(BellbellPlant_gfx), ENTITY_ROM(BellbellPlant_anim) }
DmaEntry Entity_TrumpetPlant_dma [] = { ENTITY_ROM(TrumpetPlant_gfx), ENTITY_ROM(TrumpetPlant_anim) }
EntityBlueprint Entity_BellbellPlant
EntityBlueprint Entity_TrumpetPlant
EntityBlueprint Entity_Munchlesia
Function Documentation
entity_BellbellPlant_idle()
void entity_BellbellPlant_idle (Entity * entity)
entity_Munchlesia_create_child()
s32 entity_Munchlesia_create_child (Entity * entity, EntityBlueprint * EntityBlueprint)
Referenced by entity_Munchlesia_create_child_reset1(), entity_Munchlesia_create_child_reset2(), func_802BC220_E2EB50(), func_802BC250_E2EB80(), func_802BC274_E2EBA4(), func_802BC2B4_E2EBE4(), func_802BC308_E2EC38(), and func_802BC32C_E2EC5C().
entity_Munchlesia_create_child_reset1()
void entity_Munchlesia_create_child_reset1 (Entity * entity)
entity_Munchlesia_create_child_reset2()
void entity_Munchlesia_create_child_reset2 (Entity * entity)
entity_Munchlesia_init()
void entity_Munchlesia_init (Entity * entity)
entity_MunchlesiaChewing_init()
void entity_MunchlesiaChewing_init (Entity * entity)
entity_TrumpetPlant_create_effect()
void entity_TrumpetPlant_create_effect (Entity * entity)
Referenced by entity_TrumpetPlant_spawn_coin().
entity_TrumpetPlant_idle()
void entity_TrumpetPlant_idle (Entity * entity)
entity_TrumpetPlant_spawn_coin()
void entity_TrumpetPlant_spawn_coin (Entity * entity)
func_802BC050_E2E980()
void func_802BC050_E2E980 (Entity * entity)
func_802BC0B8_E2E9E8()
void func_802BC0B8_E2E9E8 (Entity * entity)
func_802BC0F0_E2EA20()
void func_802BC0F0_E2EA20 (Entity * entity)
func_802BC17C_E2EAAC()
void func_802BC17C_E2EAAC (Entity * entity)
func_802BC220_E2EB50()
void func_802BC220_E2EB50 (Entity * entity)
func_802BC250_E2EB80()
void func_802BC250_E2EB80 (Entity * entity)
func_802BC274_E2EBA4()
void func_802BC274_E2EBA4 (Entity * entity)
func_802BC2B4_E2EBE4()
void func_802BC2B4_E2EBE4 (Entity * entity)
func_802BC308_E2EC38()
void func_802BC308_E2EC38 (Entity * entity)
func_802BC32C_E2EC5C()
void func_802BC32C_E2EC5C (Entity * entity)
func_802BC3A0_E2ECD0()
void func_802BC3A0_E2ECD0 (void)
func_802BC3E4_E2ED14()
void func_802BC3E4_E2ED14 (Entity * entity)
Variable Documentation
Entity_BellbellPlant
EntityBlueprint Entity_BellbellPlant
Initial value:
= {
    .flags = ENTITY_FLAG_SHOWS_INSPECT_PROMPT | ENTITY_FLAG_CIRCULAR_SHADOW | ENTITY_FLAG_400 | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = 0,
    .renderCommandList = Entity_BellbellPlant_AnimationIdle,
    .modelAnimationNodes = Entity_BellbellPlant_Mesh,
    .fpInit = NULL,
    .updateEntityScript = Entity_BellbellPlant_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_BellbellPlant_dma },
    .entityType = ENTITY_TYPE_BELLBELL_PLANT,
    .aabbSize = { 30, 40, 30 }
}
Entity_BellbellPlant_AnimationIdle
AnimScript Entity_BellbellPlant_AnimationIdle extern
Entity_BellbellPlant_AnimationUse
AnimScript Entity_BellbellPlant_AnimationUse extern
Referenced by entity_BellbellPlant_idle().
Entity_BellbellPlant_dma
DmaEntry Entity_BellbellPlant_dma[] = { ENTITY_ROM(BellbellPlant_gfx), ENTITY_ROM(BellbellPlant_anim) }
Entity_BellbellPlant_Mesh
StaticAnimatorNode* Entity_BellbellPlant_Mesh[] extern
Entity_BellbellPlant_Script
EntityScript Entity_BellbellPlant_Script
Initial value:
= {
    es_SetCallback(entity_BellbellPlant_idle, 0)
    es_ClearFlags(ENTITY_FLAG_SHOWS_INSPECT_PROMPT)
    es_PlaySound(SOUND_PLANTS_BELL)
    es_SetCallback(NULL, 60)
    es_SetFlags(ENTITY_FLAG_SHOWS_INSPECT_PROMPT)
    es_Restart
    es_End
}
Entity_Munchlesia
EntityBlueprint Entity_Munchlesia
Initial value:
= {
    .flags = ENTITY_FLAG_CIRCULAR_SHADOW | ENTITY_FLAG_400 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(MunchlesiaData),
    .renderCommandList = Entity_RenderNone_Script,
    .modelAnimationNodes = 0,
    .fpInit = entity_Munchlesia_init,
    .updateEntityScript = Entity_Munchlesia_Script,
    .fpHandleCollision = NULL,
    { .dmaList = NULL },
    .entityType = ENTITY_TYPE_MUNCHLESIA,
    .aabbSize = { 45, 20, 45 }
}
Entity_Munchlesia_Script
EntityScript Entity_Munchlesia_Script
Initial value:
= {
    es_Call(func_802BC220_E2EB50)
    es_Label(1)
        es_SetCallback(func_802BC050_E2E980, 0)
        es_SetCallback(NULL, 80)
    es_Goto(1)
    es_End
}
Entity_MunchlesiaBeginChew
EntityBlueprint Entity_MunchlesiaBeginChew
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(MunchlesiaData),
    .renderCommandList = Entity_MunchlesiaBeginChew_Animation,
    .modelAnimationNodes = Entity_MunchlesiaBeginChew_Mesh,
    .fpInit = NULL,
    .updateEntityScript = Entity_MunchlesiaBeginChew_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_MunchlesiaBeginChew_dma },
    .entityType = ENTITY_TYPE_MUNCHLESIA_BEGIN_CHEW,
    .aabbSize = { 40, 20, 40 }
}
Referenced by func_802BC2B4_E2EBE4().
Entity_MunchlesiaBeginChew_Animation
AnimScript Entity_MunchlesiaBeginChew_Animation extern
Entity_MunchlesiaBeginChew_dma
DmaEntry Entity_MunchlesiaBeginChew_dma[] = { ENTITY_ROM(MunchlesiaBeginChew_gfx), ENTITY_ROM(MunchlesiaBeginChew_anim) }
Entity_MunchlesiaBeginChew_Mesh
StaticAnimatorNode* Entity_MunchlesiaBeginChew_Mesh[] extern
Entity_MunchlesiaBeginChew_Script
EntityScript Entity_MunchlesiaBeginChew_Script
Initial value:
= {
    es_SetCallback(NULL, 8)
    es_Call(func_802BC308_E2EC38)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 3)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_MunchlesiaChewing
EntityBlueprint Entity_MunchlesiaChewing
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(MunchlesiaData),
    .renderCommandList = Entity_MunchlesiaChewing_Animation,
    .modelAnimationNodes = Entity_MunchlesiaChewing_Mesh,
    .fpInit = entity_MunchlesiaChewing_init,
    .updateEntityScript = Entity_MunchlesiaChewing_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_MunchlesiaChewing_dma },
    .entityType = ENTITY_TYPE_MUNCHLESIA_CHEWING,
    .aabbSize = { 40, 20, 40 }
}
Referenced by func_802BC308_E2EC38().
Entity_MunchlesiaChewing_Animation
AnimScript Entity_MunchlesiaChewing_Animation extern
Entity_MunchlesiaChewing_dma
DmaEntry Entity_MunchlesiaChewing_dma[] = { ENTITY_ROM(MunchlesiaChewing_gfx), ENTITY_ROM(MunchlesiaChewing_anim) }
Entity_MunchlesiaChewing_Mesh
StaticAnimatorNode* Entity_MunchlesiaChewing_Mesh[] extern
Entity_MunchlesiaChewing_Script
EntityScript Entity_MunchlesiaChewing_Script
Initial value:
= {
    es_SetCallback(NULL, 1)
    es_SetCallback(func_802BC3E4_E2ED14, 44)
    es_SetCallback(NULL, 13)
    es_Call(func_802BC32C_E2EC5C)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 3)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_MunchlesiaEnvelop
EntityBlueprint Entity_MunchlesiaEnvelop
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(MunchlesiaData),
    .renderCommandList = Entity_MunchlesiaEnvelop_Animation,
    .modelAnimationNodes = Entity_MunchlesiaEnvelop_Mesh,
    .fpInit = NULL,
    .updateEntityScript = Entity_MunchlesiaEnvelop_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_MunchlesiaEnvelop_dma },
    .entityType = ENTITY_TYPE_MUNCHLESIA_ENVELOP,
    .aabbSize = { 40, 20, 40 }
}
Referenced by func_802BC274_E2EBA4().
Entity_MunchlesiaEnvelop_Animation
AnimScript Entity_MunchlesiaEnvelop_Animation extern
Entity_MunchlesiaEnvelop_dma
DmaEntry Entity_MunchlesiaEnvelop_dma[] = { ENTITY_ROM(MunchlesiaEnvelop_gfx), ENTITY_ROM(MunchlesiaEnvelop_anim) }
Entity_MunchlesiaEnvelop_Mesh
StaticAnimatorNode* Entity_MunchlesiaEnvelop_Mesh[] extern
Entity_MunchlesiaEnvelop_Script
EntityScript Entity_MunchlesiaEnvelop_Script
Initial value:
= {
    es_SetCallback(NULL, 7)
    es_Call(func_802BC2B4_E2EBE4)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 3)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_MunchlesiaGrab
EntityBlueprint Entity_MunchlesiaGrab
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(MunchlesiaData),
    .renderCommandList = Entity_MunchlesiaGrab_Animation,
    .modelAnimationNodes = Entity_MunchlesiaGrab_Mesh,
    .fpInit = NULL,
    .updateEntityScript = Entity_MunchlesiaGrab_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_MunchlesiaGrab_dma },
    .entityType = ENTITY_TYPE_MUNCHLESIA_GRAB,
    .aabbSize = { 40, 20, 40 }
}
Referenced by func_802BC250_E2EB80().
Entity_MunchlesiaGrab_Animation
AnimScript Entity_MunchlesiaGrab_Animation extern
Entity_MunchlesiaGrab_dma
DmaEntry Entity_MunchlesiaGrab_dma[] = { ENTITY_ROM(MunchlesiaGrab_gfx), ENTITY_ROM(MunchlesiaGrab_anim) }
Entity_MunchlesiaGrab_Mesh
StaticAnimatorNode* Entity_MunchlesiaGrab_Mesh[] extern
Entity_MunchlesiaGrab_Script
EntityScript Entity_MunchlesiaGrab_Script
Initial value:
= {
    es_SetCallback(NULL, 3)
    es_Call(func_802BC0F0_E2EA20)
    es_SetCallback(func_802BC17C_E2EAAC, 4)
    es_Call(func_802BC274_E2EBA4)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 3)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_MunchlesiaReset
EntityBlueprint Entity_MunchlesiaReset
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(MunchlesiaData),
    .renderCommandList = Entity_MunchlesiaReset_AnimationIdle,
    .modelAnimationNodes = Entity_MunchlesiaReset_Mesh,
    .fpInit = NULL,
    .updateEntityScript = Entity_MunchlesiaReset_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_MunchlesiaReset_dma },
    .entityType = ENTITY_TYPE_RESET_MUNCHLESIA,
    .aabbSize = { 40, 20, 40 }
}
Referenced by func_802BC220_E2EB50().
Entity_MunchlesiaReset1
EntityBlueprint Entity_MunchlesiaReset1
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(MunchlesiaData),
    .renderCommandList = Entity_MunchlesiaReset1_Animation,
    .modelAnimationNodes = Entity_MunchlesiaReset1_Mesh,
    .fpInit = NULL,
    .updateEntityScript = Entity_MunchlesiaReset1_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_MunchlesiaReset1_dma },
    .entityType = ENTITY_TYPE_MUNCHLESIA_RESET1,
    .aabbSize = { 40, 20, 40 }
}
Referenced by entity_Munchlesia_create_child_reset1().
Entity_MunchlesiaReset1_Animation
AnimScript Entity_MunchlesiaReset1_Animation extern
Entity_MunchlesiaReset1_dma
DmaEntry Entity_MunchlesiaReset1_dma[] = { ENTITY_ROM(MunchlesiaReset1_gfx), ENTITY_ROM(MunchlesiaReset1_anim) }
Entity_MunchlesiaReset1_Mesh
StaticAnimatorNode* Entity_MunchlesiaReset1_Mesh[] extern
Entity_MunchlesiaReset1_Script
EntityScript Entity_MunchlesiaReset1_Script
Initial value:
= {
    es_SetCallback(NULL, 8)
    es_Call(entity_Munchlesia_create_child_reset2)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 3)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_MunchlesiaReset2
EntityBlueprint Entity_MunchlesiaReset2
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(MunchlesiaData),
    .renderCommandList = Entity_MunchlesiaReset_AnimationIdle,
    .modelAnimationNodes = Entity_MunchlesiaReset_Mesh,
    .fpInit = NULL,
    .updateEntityScript = Entity_MunchlesiaReset2_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_MunchlesiaReset_dma },
    .entityType = ENTITY_TYPE_MUNCHLESIA_RESET2,
    .aabbSize = { 40, 20, 40 }
}
Referenced by entity_Munchlesia_create_child_reset2().
Entity_MunchlesiaReset2_Script
EntityScript Entity_MunchlesiaReset2_Script
Initial value:
= {
    es_SetCallback(NULL, 9)
    es_Call(func_802BC220_E2EB50)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 10)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_MunchlesiaReset_AnimationIdle
AnimScript Entity_MunchlesiaReset_AnimationIdle extern
Entity_MunchlesiaReset_AnimationReset
AnimScript Entity_MunchlesiaReset_AnimationReset extern
Referenced by func_802BC0B8_E2E9E8().
Entity_MunchlesiaReset_dma
DmaEntry Entity_MunchlesiaReset_dma[] = { ENTITY_ROM(MunchlesiaReset_gfx), ENTITY_ROM(MunchlesiaReset_anim) }
Entity_MunchlesiaReset_Mesh
StaticAnimatorNode* Entity_MunchlesiaReset_Mesh[] extern
Entity_MunchlesiaReset_Script
EntityScript Entity_MunchlesiaReset_Script
Initial value:
= {
    es_SetCallback(NULL, 0)
    es_Call(func_802BC0B8_E2E9E8)
    es_SetCallback(NULL, 7)
    es_Call(func_802BC250_E2EB80)
    es_PlaySound(SOUND_MUNCHLESIA_SUCTION)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 3)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_MunchlesiaSpitOut
EntityBlueprint Entity_MunchlesiaSpitOut
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(MunchlesiaData),
    .renderCommandList = Entity_MunchlesiaSpitOut_Animation,
    .modelAnimationNodes = Entity_MunchlesiaSpitOut_Mesh,
    .fpInit = NULL,
    .updateEntityScript = Entity_MunchlesiaSpitOut_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_MunchlesiaSpitOut_dma },
    .entityType = ENTITY_TYPE_MUNCHLESIA_SPIT_OUT,
    .aabbSize = { 40, 20, 40 }
}
Referenced by func_802BC32C_E2EC5C().
Entity_MunchlesiaSpitOut_Animation
AnimScript Entity_MunchlesiaSpitOut_Animation extern
Entity_MunchlesiaSpitOut_dma
DmaEntry Entity_MunchlesiaSpitOut_dma[] = { ENTITY_ROM(MunchlesiaSpitOut_gfx), ENTITY_ROM(MunchlesiaSpitOut_anim) }
Entity_MunchlesiaSpitOut_Mesh
StaticAnimatorNode* Entity_MunchlesiaSpitOut_Mesh[] extern
Entity_MunchlesiaSpitOut_Script
EntityScript Entity_MunchlesiaSpitOut_Script
Initial value:
= {
    es_SetCallback(NULL, 4)
    es_Call(func_802BC3A0_E2ECD0)
    es_PlaySound(SOUND_MUNCHLESIA_SPIT)
    es_SetCallback(NULL, 4)
    es_Call(entity_Munchlesia_create_child_reset1)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetCallback(NULL, 3)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_RenderNone_Script
EntityModelScript Entity_RenderNone_Script extern
Entity_TrumpetPlant
EntityBlueprint Entity_TrumpetPlant
Initial value:
= {
    .flags = ENTITY_FLAG_SHOWS_INSPECT_PROMPT | ENTITY_FLAG_HAS_ANIMATED_MODEL,
    .typeDataSize = sizeof(TrumpetPlantData),
    .renderCommandList = Entity_TrumpetPlant_AnimationIdle,
    .modelAnimationNodes = Entity_TrumpetPlant_Mesh,
    .fpInit = NULL,
    .updateEntityScript = Entity_TrumpetPlant_Script,
    .fpHandleCollision = NULL,
    { .dmaList = Entity_TrumpetPlant_dma },
    .entityType = ENTITY_TYPE_TRUMPET_PLANT,
    .aabbSize = { 30, 40, 30 }
}
Entity_TrumpetPlant_AnimationIdle
AnimScript Entity_TrumpetPlant_AnimationIdle extern
Entity_TrumpetPlant_AnimationUse
AnimScript Entity_TrumpetPlant_AnimationUse extern
Referenced by entity_TrumpetPlant_idle().
Entity_TrumpetPlant_dma
DmaEntry Entity_TrumpetPlant_dma[] = { ENTITY_ROM(TrumpetPlant_gfx), ENTITY_ROM(TrumpetPlant_anim) }
Entity_TrumpetPlant_Mesh
StaticAnimatorNode* Entity_TrumpetPlant_Mesh[] extern
Entity_TrumpetPlant_Script
EntityScript Entity_TrumpetPlant_Script
Initial value:
= {
    es_SetCallback(entity_TrumpetPlant_idle, 0)
    es_ClearFlags(ENTITY_FLAG_SHOWS_INSPECT_PROMPT)
    es_PlaySound(SOUND_PLANTS_TRUMPET)
    es_SetCallback(NULL, 15)
    es_Call(entity_TrumpetPlant_create_effect)
    es_SetCallback(NULL, 3)
    es_Call(entity_TrumpetPlant_create_effect)
    es_SetCallback(NULL, 2)
    es_Call(entity_TrumpetPlant_spawn_coin)
    es_SetCallback(NULL, 3)
    es_Call(entity_TrumpetPlant_create_effect)
    es_SetCallback(NULL, 2)
    es_Call(entity_TrumpetPlant_create_effect)
    es_SetCallback(NULL, 3)
    es_Call(entity_TrumpetPlant_create_effect)
    es_SetCallback(NULL, 32)
    es_SetFlags(ENTITY_FLAG_SHOWS_INSPECT_PROMPT)
    es_Restart
    es_End
}