papermario: src/audio/private.h File Reference
private.h File Reference
Functions
void au_amb_manager_init (AmbienceManager *arg0, s8 arg1, s8 reverbType, AuGlobals *arg3)
AuResult au_amb_check_player_index (u32 arg0)
void au_amb_load_tracks_fade (s32 arg0, s32 arg1)
void au_amb_set_disabled (s32 arg0, s32 arg1)
AuResult au_amb_start (s32 arg0, s32 arg1)
void au_amb_fade_setup (AmbiencePlayer *arg0)
void au_amb_pause (s32 arg0, s32 arg1)
void au_amb_resume (s32 arg0, s32 arg1)
void au_amb_stop_quick (s32 arg0)
void au_amb_stop_slow (s32 arg0, s32 arg1)
void au_amb_set_volume (s32 arg0, s32 arg1, s32 arg2)
AuResult au_amb_is_stopped (s32 arg0)
void au_amb_play_sequence (AmbienceManager *arg0, MSEQHeader *mseq, s32 index)
void au_amb_manager_update (AmbienceManager *arg0)
void au_amb_load_track_fade_info (AmbienceManager *manager, AmbiencePlayer *lambda)
void au_amb_player_update (AmbienceManager *manager, AmbiencePlayer *lambda)
u8 au_amb_read_next (AmbiencePlayer *arg0)
void au_amb_player_stop (AmbienceManager *arg0, AmbiencePlayer *arg1)
void au_amb_save_voices (AmbienceManager *arg0, AmbiencePlayer *lambda)
void au_amb_restore_voices (AmbienceManager *manager, AmbiencePlayer *lambda)
void au_update_stopped_voices (AuGlobals *globals)
void au_init_voices (AuGlobals *globals)
void au_update_voices (AuGlobals *globals)
void au_voice_after_volume_change (AuVoice *arg0)
s32 au_voice_get_delta (s32 arg0)
void au_voice_start (AuVoice *voice, EnvelopeData *arg1)
u8 au_voice_step (AuVoice *voice)
void au_voice_set_vol_changed (AuVoice *arg0)
void func_80052E30 (u8 index)
void au_engine_init (s32 outputRate)
void au_update_clients_2 (void)
void au_update_players_main (void)
void au_syn_update (AuGlobals *globals)
void au_reset_nonfree_voice (AuVoice *arg0, u8 arg1)
void au_reset_voice (AuVoice *arg0, u8 arg1)
f32 au_compute_pitch_ratio (s32 arg0)
void au_fade_init (Fade *fade, s32 time, s32 startValue, s32 endValue)
void au_fade_clear (Fade *fade)
void au_fade_update (Fade *fade)
void au_fade_set_volume (u8 arg0, u16 arg1, s32 arg2)
void func_80053AC8 (Fade *fade)
void au_fade_set_vol_scale (Fade *fade, s16 value)
void func_80053B04 (Fade *fade, u32 arg1, s32 target)
void func_80053BA8 (Fade *fade)
Instrument * au_get_instrument (AuGlobals *globals, u32 bank, u32 patch, EnvelopeData *arg3)
void au_get_bgm_player_and_file (u32 playerIndex, BGMHeader **outCurrentTrackData, BGMPlayer **outPlayer)
void au_get_bgm_player (u32 playerIndex, BGMPlayer **outPlayer)
AuResult au_load_song_files (u32 arg0, BGMHeader *arg1, BGMPlayer *arg2)
AuResult func_80053E58 (s32 songID, BGMHeader *arg1)
BGMPlayer * func_80053F64 (s32 arg0)
AuResult au_ambient_load (u32 arg0)
BGMPlayer * func_80054248 (u8 arg0)
void au_load_INIT (AuGlobals *arg0, s32 romAddr, ALHeap *heap)
AuResult au_fetch_SBN_file (u32 fileIdx, AuFileFormat format, SBNFileEntry *arg2)
void au_load_PER (AuGlobals *globals, s32 romAddr)
void au_load_PRG (AuGlobals *arg0, s32 romAddr)
InstrumentGroup * au_get_BK_instruments (s32 bankGroup, u32 bankIndex)
SoundBank * au_load_BK_to_bank (s32 bkFileOffset, SoundBank *bank, s32 bankIndex, s32 bankGroup)
void au_swizzle_BK_instruments (s32 bkFileOffset, SoundBank *bank, InstrumentGroup instruments, u32 instrumentCount, u8 arg4)
s32 * func_80054AA0 (s32 *bkFileOffset, void *vaddr, s32 bankIndex, s32 bankGroup)
s32 snd_load_BK (s32 bkFileOffset, s32 bankIndex)
void func_80054C84 (s32 bankIndex, s32 bankGroup)
void func_80054CE0 (s32 arg0, u32 idx)
s32 func_80054D74 (s32 arg0, s32 arg1)
void func_80054DA8 (u32 arg0)
void au_read_rom (s32 romAddr, void *buffer, u32 size)
void au_memset (void *dst, s32 size, u8 value)
void au_copy_bytes (s8 *src, s8 *dest, s32 size)
void au_copy_words (void *src, void *dst, s32 size)
void create_audio_system (void)
void nuAuMgr (void *arg)
s32 nuAuDmaCallBack (s32 addr, s32 len, void *state, u8 arg3)
void au_load_BK_headers (AuGlobals *arg0, ALHeap *)
void au_sfx_init (SoundManager *manager, u8 arg1, u8 arg2, AuGlobals *arg3, u8 arg4)
void au_sfx_load_groups_from_SEF (SoundManager *sndMgr)
void au_sfx_clear_queue (SoundManager *manager)
void au_sfx_enqueue_event (SoundManager *manager, u32 soundID, s16 volume, s16 pitchShift, u8 pan)
void au_sfx_update_main (SoundManager *manager)
s32 au_sfx_set_reverb_type (SoundManager *manager, s32 arg1)
void au_sfx_set_state (SoundManager *manager, s32 arg1)
void au_sfx_load_sound (SoundManager *manager, SoundSFXEntry *entry, SoundManagerCustomCmdList *)
s16 au_sfx_manager_update (SoundManager *manager)
void au_bgm_update_main (BGMPlayer *player)
BGMPlayer * au_bgm_get_player_with_song_name (s32 songString)
AuResult au_bgm_dispatch_player_event (SongUpdateEvent *event)
AuResult au_bgm_stop_song (s32 songName)
void au_bgm_stop_all (void)
AuResult au_bgm_is_song_playing (s32 songName)
s32 func_8004DB28 (BGMPlayer *player)
AuResult func_8004DB4C (SongUpdateEvent *s)
AuResult func_8004DC80 (s32 songName)
AuResult func_8004DCB8 (SongUpdateEvent *update, s32 clearChanged)
AuResult func_8004DE2C (SongUpdateEvent *update)
void func_8004DFD4 (AuGlobals *globals)
AuResult func_8004E0F4 (SongUpdateEvent *update)
void au_bgm_player_init (BGMPlayer *player, s32 arg1, s32 arg2, AuGlobals *arg3)
void au_bgm_set_effect_indices (BGMPlayer *player, u8 *list)
void au_bgm_update_fade (BGMPlayer *player)
void func_8004E444 (BGMPlayer *arg0)
s32 au_bgm_player_update_main (BGMPlayer *player)
void au_bgm_player_initialize (BGMPlayer *player)
void func_8004E844 (BGMPlayer *player, s32 arg1)
void func_8004E880 (BGMPlayer *player, s32 sampleRate, s32 divisor)
void au_bgm_player_read_segment (BGMPlayer *player)
void au_bgm_end_segment_loop (BGMPlayer *player, u32 cmd)
void au_bgm_load_subsegment (BGMPlayer *player, u32 cmd)
void au_bgm_player_update_stop (BGMPlayer *player)
void au_bgm_player_update_playing (BGMPlayer *player)
void au_BGMCmd_E0_MasterTempo (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E1_MasterVolume (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E2_MasterPitchShift (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E3 (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E6_MasterEffect (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E4_MasterTempoFade (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E5_MasterVolumeFade (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E8_TrackOverridePatch (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_E9_SubTrackVolume (BGMPlayer *arg0, BGMPlayerTrack *track)
void au_BGMCmd_F6_TrackVolumeFade (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EA_SubTrackPan (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EB_SubTrackReverb (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EC_SegTrackVolume (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_ED_SubTrackCoarseTune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EE_SubTrackFineTune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_EF_SegTrackTune (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F0_TrackTremolo (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F1_TrackTremoloSpeed (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F2_TrackTremoloTime (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F3_TrackTremoloStop (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F4 (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F5_TrackVoice (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_F7_SubTrackReverbType (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FD_EventTrigger (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FE_Detour (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FC_Jump (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_FF (BGMPlayer *player, BGMPlayerTrack *track)
void au_BGMCmd_NOP (BGMPlayer *player, BGMPlayerTrack *track)
void au_bgm_set_proximity_mix (s32 songName, u32 mix)
void au_bgm_set_playback_rate (BGMPlayer *player, f32 arg1)
void au_bgm_player_set_detune (BGMPlayer *player, s32 arg1)
void au_bgm_change_track_volume (BGMPlayer *player, s32 trackIdx, s16 arg2, u8 arg3)
void au_bgm_set_track_volumes (BGMPlayer *player, u8 *arg1, s32 arg2)
void func_80050888 (BGMPlayer *player, BGMPlayerTrack *track, s32 target, s32 duration)
void func_80050900 (BGMPlayer *player)
AuResult func_80050970 (SongUpdateEvent *arg0)
void func_80055110 (BGMPlayer *player)
AuResult snd_song_get_playing_info (s32 songName, BGMHeader **outTrackData, BGMPlayer **outPlayer)
void au_register_callback (AuCallback arg0, s32 arg1)
void au_driver_init (AuSynDriver *driver, ALConfig *config)
void au_driver_release (void)
void au_use_global_volume (void)
void au_set_global_volume (s16 arg0)
s16 au_get_global_volume (void)
void func_80056D5C (u8 arg0)
void au_bus_set_volume (u8 arg0, u16 arg1)
u16 au_bus_get_volume (u8 arg0, u16 arg1)
void au_bus_set_effect (u8 arg0, u8 effectID)
void au_bus_set_fx_params (u8 arg0, s16 arg1, s16 arg2, s32 arg3)
void au_pvoice_set_bus (u8 arg0, s8 arg1)
void au_syn_stop_voice (u8 voiceIdx)
void au_syn_start_voice (u8 index)
void au_syn_start_voice_params (u8 index, u8 reverbType, Instrument *table, f32 pitch, s16 vol, u8 pan, u8 fxMix, s32 delta)
void au_syn_set_wavetable (u8 voiceIdx, Instrument *table)
void au_syn_set_pitch (u8 voiceIdx, f32 pitchRatio)
void au_syn_set_mixer_params (u8 voiceIdx, s16 volume, s32 arg2, u8 arg3, u8 arg4)
void au_syn_set_pan_fxmix (u8 voiceIdx, u8 arg1, u8 arg2)
void au_syn_set_volume_delta (u8 voiceIdx, s16 arg1, s32 arg2)
void au_syn_set_pan (u8 voiceIdx, u8 pan)
void au_syn_set_fxmix (u8 voiceIdx, u8 dryAmt)
s32 au_syn_get_playing (u8 voiceIdx)
s32 au_syn_get_bus (u8 voiceIdx)
f32 au_syn_get_pitch (u8 voiceIdx)
u8 au_syn_get_pan (u8 voiceIdx)
s16 au_syn_get_dryamt (u8 voiceIdx)
s16 au_syn_get_wetamt (u8 voiceIdx)
s32 au_syn_get_volume_left (u8 voiceIdx)
s32 au_syn_get_volume_right (u8 voiceIdx)
void au_set_delay_time (s32 arg0)
void au_delay_left_channel (u8 arg0)
void au_delay_right_channel (u8 arg0)
void au_disable_channel_delay (void)
void au_delay_channel (s16 arg0)
void * alHeapAlloc (ALHeap *heap, s32 arg1, s32 size)
Acmd * au_pull_voice (AuPVoice *pvoice, Acmd *cmdBufPos)
void func_80058E84 (AuFX *fx, u8 mode, ALHeap *heap)
void func_80058F88 (AlUnkKappa *kappa, ALHeap *heap)
void func_80059008 (AlUnkKappa *kappa, s16 arg1, s16 arg2, s16 fc)
void func_8005904C (AuFX *fx, u8 effectType)
Acmd * au_pull_fx (AuFX *fx, Acmd *cmdBusPos, s16, s16)
s32 au_fx_param_hdl (AuFX *fx, s16 index, s16 paramID, s32 value)
SoundInstance * sfx_get_env_sound_instance (s32 soundID)
Function Documentation
alHeapAlloc()
void * alHeapAlloc (ALHeap * heap, s32 arg1, s32 size)
Referenced by au_driver_init(), au_engine_init(), au_load_BK_to_bank(), au_load_INIT(), create_audio_system(), func_80054AA0(), func_80058E84(), and func_80058F88().
au_amb_check_player_index()
AuResult au_amb_check_player_index (u32 arg0)
Referenced by snd_ambient_disable(), snd_ambient_enable(), snd_ambient_is_stopped(), snd_ambient_mute(), snd_ambient_pause(), snd_ambient_play(), snd_ambient_resume(), snd_ambient_set_volume(), snd_ambient_stop_quick(), and snd_ambient_stop_slow().
au_amb_fade_setup()
void au_amb_fade_setup (AmbiencePlayer * arg0)
Referenced by au_amb_manager_update(), and au_amb_start().
au_amb_is_stopped()
AuResult au_amb_is_stopped (s32 arg0)
Referenced by snd_ambient_is_stopped().
au_amb_load_track_fade_info()
void au_amb_load_track_fade_info (AmbienceManager * manager, AmbiencePlayer * lambda)
Referenced by au_amb_manager_update().
au_amb_load_tracks_fade()
void au_amb_load_tracks_fade (s32 arg0, s32 arg1)
Referenced by snd_ambient_mute().
au_amb_manager_init()
void au_amb_manager_init (AmbienceManager * arg0, s8 arg1, s8 reverbType, AuGlobals * arg3)
Referenced by au_engine_init().
au_amb_manager_update()
void au_amb_manager_update (AmbienceManager * arg0)
Referenced by au_update_clients_2().
au_amb_pause()
void au_amb_pause (s32 arg0, s32 arg1)
Referenced by snd_ambient_pause().
au_amb_play_sequence()
void au_amb_play_sequence (AmbienceManager * arg0, MSEQHeader * mseq, s32 index)
Referenced by au_amb_start().
au_amb_player_stop()
void au_amb_player_stop (AmbienceManager * arg0, AmbiencePlayer * arg1)
Referenced by au_amb_manager_update(), and au_amb_player_update().
au_amb_player_update()
void au_amb_player_update (AmbienceManager * manager, AmbiencePlayer * lambda)
Referenced by au_amb_manager_update().
au_amb_read_next()
u8 au_amb_read_next (AmbiencePlayer * arg0)
Referenced by au_amb_player_update().
au_amb_restore_voices()
void au_amb_restore_voices (AmbienceManager * manager, AmbiencePlayer * lambda)
Referenced by au_amb_manager_update().
au_amb_resume()
void au_amb_resume (s32 arg0, s32 arg1)
Referenced by snd_ambient_resume().
au_amb_save_voices()
void au_amb_save_voices (AmbienceManager * arg0, AmbiencePlayer * lambda)
Referenced by au_amb_manager_update().
au_amb_set_disabled()
void au_amb_set_disabled (s32 arg0, s32 arg1)
Referenced by snd_ambient_disable(), and snd_ambient_enable().
au_amb_set_volume()
void au_amb_set_volume (s32 arg0, s32 arg1, s32 arg2)
Referenced by snd_ambient_set_volume().
au_amb_start()
AuResult au_amb_start (s32 arg0, s32 arg1)
Referenced by snd_ambient_play().
au_amb_stop_quick()
void au_amb_stop_quick (s32 arg0)
Referenced by snd_ambient_stop_quick().
au_amb_stop_slow()
void au_amb_stop_slow (s32 arg0, s32 arg1)
Referenced by snd_ambient_stop_slow().
au_ambient_load()
AuResult au_ambient_load (u32 arg0)
Referenced by snd_load_ambient().
au_bgm_change_track_volume()
void au_bgm_change_track_volume (BGMPlayer * player, s32 trackIdx, s16 arg2, u8 arg3)
au_bgm_dispatch_player_event()
AuResult au_bgm_dispatch_player_event (SongUpdateEvent * event)
Referenced by au_song_start(), au_song_start_variation(), snd_set_song_fade(), and snd_set_song_variation_fade().
au_bgm_end_segment_loop()
void au_bgm_end_segment_loop (BGMPlayer * player, u32 cmd)
Referenced by au_bgm_player_read_segment().
au_bgm_get_player_with_song_name()
BGMPlayer * au_bgm_get_player_with_song_name (s32 songString)
Referenced by au_bgm_dispatch_player_event(), au_bgm_is_song_playing(), au_bgm_set_proximity_mix(), au_bgm_stop_song(), func_8004DB4C(), func_8004DCB8(), func_8004DE2C(), func_8004E0F4(), and func_80050970().
au_bgm_is_song_playing()
AuResult au_bgm_is_song_playing (s32 songName)
Referenced by au_song_is_playing().
au_bgm_load_subsegment()
void au_bgm_load_subsegment (BGMPlayer * player, u32 cmd)
Referenced by au_bgm_player_read_segment().
au_bgm_player_init()
void au_bgm_player_init (BGMPlayer * player, s32 arg1, s32 arg2, AuGlobals * arg3)
Referenced by au_engine_init().
au_bgm_player_initialize()
void au_bgm_player_initialize (BGMPlayer * player)
Referenced by au_bgm_dispatch_player_event(), and au_bgm_player_update_main().
au_bgm_player_read_segment()
void au_bgm_player_read_segment (BGMPlayer * player)
Referenced by au_bgm_player_update_main().
au_bgm_player_set_detune()
void au_bgm_player_set_detune (BGMPlayer * player, s32 arg1)
Referenced by snd_song_set_detune().
au_bgm_player_update_main()
s32 au_bgm_player_update_main (BGMPlayer * player)
Referenced by au_update_clients_2().
au_bgm_player_update_playing()
void au_bgm_player_update_playing (BGMPlayer * player)
Referenced by au_bgm_player_update_main().
au_bgm_player_update_stop()
void au_bgm_player_update_stop (BGMPlayer * player)
Referenced by au_bgm_player_update_main().
au_bgm_set_effect_indices()
void au_bgm_set_effect_indices (BGMPlayer * player, u8 * list)
Referenced by au_engine_init().
au_bgm_set_playback_rate()
void au_bgm_set_playback_rate (BGMPlayer * player, f32 arg1)
Referenced by snd_song_set_playback_rate().
au_bgm_set_proximity_mix()
void au_bgm_set_proximity_mix (s32 songName, u32 mix)
Referenced by bgm_set_proximity_mix_far(), bgm_set_proximity_mix_full(), and bgm_set_proximity_mix_near().
au_bgm_set_track_volumes()
void au_bgm_set_track_volumes (BGMPlayer * player, u8 * arg1, s32 arg2)
Referenced by snd_song_clear_track_volumes(), and snd_song_set_track_volumes().
au_bgm_stop_all()
void au_bgm_stop_all (void)
Referenced by au_stop_songs().
au_bgm_stop_song()
AuResult au_bgm_stop_song (s32 songName)
Referenced by au_song_stop().
au_bgm_update_fade()
void au_bgm_update_fade (BGMPlayer * player)
Referenced by au_update_clients_2().
au_bgm_update_main()
void au_bgm_update_main (BGMPlayer * player)
Referenced by au_update_players_main().
au_BGMCmd_E0_MasterTempo()
void au_BGMCmd_E0_MasterTempo (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E1_MasterVolume()
void au_BGMCmd_E1_MasterVolume (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E2_MasterPitchShift()
void au_BGMCmd_E2_MasterPitchShift (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E3()
void au_BGMCmd_E3 (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E4_MasterTempoFade()
void au_BGMCmd_E4_MasterTempoFade (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E5_MasterVolumeFade()
void au_BGMCmd_E5_MasterVolumeFade (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E6_MasterEffect()
void au_BGMCmd_E6_MasterEffect (BGMPlayer * player, BGMPlayerTrack * track)
Referenced by func_8004DFD4().
au_BGMCmd_E8_TrackOverridePatch()
void au_BGMCmd_E8_TrackOverridePatch (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_E9_SubTrackVolume()
void au_BGMCmd_E9_SubTrackVolume (BGMPlayer * arg0, BGMPlayerTrack * track)
Referenced by func_80050970().
au_BGMCmd_EA_SubTrackPan()
void au_BGMCmd_EA_SubTrackPan (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EB_SubTrackReverb()
void au_BGMCmd_EB_SubTrackReverb (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EC_SegTrackVolume()
void au_BGMCmd_EC_SegTrackVolume (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_ED_SubTrackCoarseTune()
void au_BGMCmd_ED_SubTrackCoarseTune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EE_SubTrackFineTune()
void au_BGMCmd_EE_SubTrackFineTune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_EF_SegTrackTune()
void au_BGMCmd_EF_SegTrackTune (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F0_TrackTremolo()
void au_BGMCmd_F0_TrackTremolo (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F1_TrackTremoloSpeed()
void au_BGMCmd_F1_TrackTremoloSpeed (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F2_TrackTremoloTime()
void au_BGMCmd_F2_TrackTremoloTime (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F3_TrackTremoloStop()
void au_BGMCmd_F3_TrackTremoloStop (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F4()
void au_BGMCmd_F4 (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F5_TrackVoice()
void au_BGMCmd_F5_TrackVoice (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_F6_TrackVolumeFade()
void au_BGMCmd_F6_TrackVolumeFade (BGMPlayer * player, BGMPlayerTrack * track)
Referenced by au_bgm_change_track_volume(), au_bgm_player_update_playing(), and func_80050970().
au_BGMCmd_F7_SubTrackReverbType()
void au_BGMCmd_F7_SubTrackReverbType (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FC_Jump()
void au_BGMCmd_FC_Jump (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FD_EventTrigger()
void au_BGMCmd_FD_EventTrigger (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FE_Detour()
void au_BGMCmd_FE_Detour (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_FF()
void au_BGMCmd_FF (BGMPlayer * player, BGMPlayerTrack * track)
au_BGMCmd_NOP()
void au_BGMCmd_NOP (BGMPlayer * player, BGMPlayerTrack * track)
au_bus_get_volume()
u16 au_bus_get_volume (u8 arg0, u16 arg1)
au_bus_set_effect()
void au_bus_set_effect (u8 arg0, u8 effectID)
Referenced by au_syn_update().
au_bus_set_fx_params()
void au_bus_set_fx_params (u8 arg0, s16 arg1, s16 arg2, s32 arg3)
au_bus_set_volume()
void au_bus_set_volume (u8 arg0, u16 arg1)
Referenced by au_fade_set_volume().
au_compute_pitch_ratio()
f32 au_compute_pitch_ratio (s32 arg0)
Referenced by au_amb_player_update(), au_amb_restore_voices(), and au_bgm_player_update_playing().
au_copy_bytes()
void au_copy_bytes (s8 * src, s8 * dest, s32 size)
au_copy_words()
void au_copy_words (void * src, void * dst, s32 size)
Referenced by au_load_PER(), au_load_PRG(), func_8004DCB8(), and func_8004DFD4().
au_delay_channel()
void au_delay_channel (s16 arg0)
Referenced by au_engine_init().
au_delay_left_channel()
void au_delay_left_channel (u8 arg0)
Referenced by au_syn_update().
au_delay_right_channel()
void au_delay_right_channel (u8 arg0)
Referenced by au_syn_update().
au_disable_channel_delay()
void au_disable_channel_delay (void)
Referenced by au_syn_update().
au_driver_init()
void au_driver_init (AuSynDriver * driver, ALConfig * config)
Referenced by create_audio_system().
au_driver_release()
void au_driver_release (void)
au_engine_init()
void au_engine_init (s32 outputRate)
Referenced by create_audio_system().
au_fade_clear()
void au_fade_clear (Fade * fade)
au_fade_init()
void au_fade_init (Fade * fade, s32 time, s32 startValue, s32 endValue)
Referenced by au_bgm_dispatch_player_event(), au_sfx_init(), and func_8004DFD4().
au_fade_set_vol_scale()
void au_fade_set_vol_scale (Fade * fade, s16 value)
Referenced by au_bgm_player_init().
au_fade_set_volume()
void au_fade_set_volume (u8 arg0, u16 arg1, s32 arg2)
Referenced by au_sfx_init(), au_update_clients_2(), and func_8004E444().
au_fade_update()
void au_fade_update (Fade * fade)
Referenced by au_update_clients_2().
au_fetch_SBN_file()
AuResult au_fetch_SBN_file (u32 fileIdx, AuFileFormat format, SBNFileEntry * arg2)
Referenced by au_engine_init(), au_load_BK_headers(), au_load_song_files(), and func_80053E58().
au_fx_param_hdl()
s32 au_fx_param_hdl (AuFX * fx, s16 index, s16 paramID, s32 value)
Referenced by au_bus_set_fx_params().
au_get_bgm_player()
void au_get_bgm_player (u32 playerIndex, BGMPlayer ** outPlayer)
au_get_bgm_player_and_file()
void au_get_bgm_player_and_file (u32 playerIndex, BGMHeader ** outCurrentTrackData, BGMPlayer ** outPlayer)
Referenced by au_song_load().
au_get_BK_instruments()
InstrumentGroup * au_get_BK_instruments (s32 bankGroup, u32 bankIndex)
Referenced by au_load_BK_to_bank(), func_80054AA0(), and func_80054C84().
au_get_global_volume()
s16 au_get_global_volume (void)
Referenced by nuAuPreNMIProc().
au_get_instrument()
Instrument * au_get_instrument (AuGlobals * globals, u32 bank, u32 patch, EnvelopeData * arg3)
Referenced by au_amb_player_update(), au_bgm_player_update_playing(), au_BGMCmd_E8_TrackOverridePatch(), and au_BGMCmd_F5_TrackVoice().
au_init_voices()
void au_init_voices (AuGlobals * globals)
Referenced by au_engine_init().
au_load_BK_headers()
void au_load_BK_headers (AuGlobals * arg0, ALHeap * heap)
Referenced by au_engine_init().
au_load_BK_to_bank()
SoundBank * au_load_BK_to_bank (s32 bkFileOffset, SoundBank * bank, s32 bankIndex, s32 bankGroup)
Referenced by au_load_BK_headers(), and snd_load_BK().
au_load_INIT()
void au_load_INIT (AuGlobals * arg0, s32 romAddr, ALHeap * heap)
Referenced by au_engine_init().
au_load_PER()
void au_load_PER (AuGlobals * globals, s32 romAddr)
Referenced by au_engine_init().
au_load_PRG()
void au_load_PRG (AuGlobals * arg0, s32 romAddr)
Referenced by au_engine_init().
au_load_song_files()
AuResult au_load_song_files (u32 arg0, BGMHeader * arg1, BGMPlayer * arg2)
Referenced by au_song_load().
au_memset()
void au_memset (void * dst, s32 size, u8 value)
Referenced by au_amb_manager_init(), and au_amb_play_sequence().
au_pull_fx()
Acmd * au_pull_fx (AuFX * fx, Acmd * cmdBusPos, s16 outputBuf, s16 arg3)
Referenced by alAudioFrame().
au_pull_voice()
Acmd * au_pull_voice (AuPVoice * pvoice, Acmd * cmdBufPos)
Referenced by alAudioFrame().
au_pvoice_set_bus()
void au_pvoice_set_bus (u8 arg0, s8 arg1)
Referenced by au_engine_init().
au_read_rom()
void au_read_rom (s32 romAddr, void * buffer, u32 size)
Referenced by au_ambient_load(), au_engine_init(), au_load_BK_headers(), au_load_BK_to_bank(), au_load_INIT(), au_load_PER(), au_load_PRG(), au_load_song_files(), func_80053E58(), and func_80054AA0().
au_register_callback()
void au_register_callback (AuCallback arg0, s32 arg1)
au_reset_nonfree_voice()
void au_reset_nonfree_voice (AuVoice * arg0, u8 arg1)
au_reset_voice()
void au_reset_voice (AuVoice * arg0, u8 arg1)
Referenced by au_amb_player_stop(), au_amb_player_update(), au_amb_restore_voices(), au_bgm_player_update_playing(), au_BGMCmd_FC_Jump(), and func_80050900().
au_set_delay_time()
void au_set_delay_time (s32 arg0)
Referenced by au_syn_update().
au_set_global_volume()
void au_set_global_volume (s16 arg0)
Referenced by nuAuPreNMIProc().
au_sfx_clear_queue()
void au_sfx_clear_queue (SoundManager * manager)
Referenced by au_sfx_init().
au_sfx_enqueue_event()
void au_sfx_enqueue_event (SoundManager * manager, u32 soundID, s16 volume, s16 pitchShift, u8 pan)
Referenced by snd_adjust_sound(), snd_adjust_sound_with_shift(), snd_start_sound(), snd_start_sound_raw(), snd_start_sound_with_shift(), and snd_stop_sound().
au_sfx_init()
void au_sfx_init (SoundManager * manager, u8 arg1, u8 arg2, AuGlobals * arg3, u8 arg4)
Referenced by au_engine_init().
au_sfx_load_groups_from_SEF()
void au_sfx_load_groups_from_SEF (SoundManager * sndMgr)
Referenced by au_engine_init().
au_sfx_load_sound()
void au_sfx_load_sound (SoundManager * manager, SoundSFXEntry * entry, SoundManagerCustomCmdList * customSEF)
Referenced by au_sfx_update_main().
au_sfx_manager_update()
s16 au_sfx_manager_update (SoundManager * manager)
Referenced by au_update_clients_2().
au_sfx_set_reverb_type()
s32 au_sfx_set_reverb_type (SoundManager * manager, s32 arg1)
Referenced by au_sfx_init(), and func_80054D74().
au_sfx_set_state()
void au_sfx_set_state (SoundManager * manager, s32 arg1)
Referenced by au_sfx_init(), disable_sounds(), and enable_sounds().
au_sfx_update_main()
void au_sfx_update_main (SoundManager * manager)
Referenced by au_update_players_main().
au_swizzle_BK_instruments()
void au_swizzle_BK_instruments (s32 bkFileOffset, SoundBank * bank, InstrumentGroup instruments, u32 instrumentCount, u8 arg4)
Referenced by au_load_BK_to_bank(), and func_80054AA0().
au_syn_get_bus()
s32 au_syn_get_bus (u8 voiceIdx)
au_syn_get_dryamt()
s16 au_syn_get_dryamt (u8 voiceIdx)
au_syn_get_pan()
u8 au_syn_get_pan (u8 voiceIdx)
au_syn_get_pitch()
f32 au_syn_get_pitch (u8 voiceIdx)
au_syn_get_playing()
s32 au_syn_get_playing (u8 voiceIdx)
au_syn_get_volume_left()
s32 au_syn_get_volume_left (u8 voiceIdx)
au_syn_get_volume_right()
s32 au_syn_get_volume_right (u8 voiceIdx)
au_syn_get_wetamt()
s16 au_syn_get_wetamt (u8 voiceIdx)
au_syn_set_fxmix()
void au_syn_set_fxmix (u8 voiceIdx, u8 dryAmt)
au_syn_set_mixer_params()
void au_syn_set_mixer_params (u8 voiceIdx, s16 volume, s32 arg2, u8 arg3, u8 arg4)
Referenced by au_syn_update().
au_syn_set_pan()
void au_syn_set_pan (u8 voiceIdx, u8 pan)
Referenced by alAudioFrame().
au_syn_set_pan_fxmix()
void au_syn_set_pan_fxmix (u8 voiceIdx, u8 arg1, u8 arg2)
Referenced by au_syn_update().
au_syn_set_pitch()
void au_syn_set_pitch (u8 voiceIdx, f32 pitchRatio)
Referenced by au_syn_update().
au_syn_set_volume_delta()
void au_syn_set_volume_delta (u8 voiceIdx, s16 arg1, s32 arg2)
Referenced by au_reset_nonfree_voice(), and au_reset_voice().
au_syn_set_wavetable()
void au_syn_set_wavetable (u8 voiceIdx, Instrument * table)
Referenced by au_engine_init().
au_syn_start_voice()
void au_syn_start_voice (u8 index)
au_syn_start_voice_params()
void au_syn_start_voice_params (u8 index, u8 reverbType, Instrument * table, f32 pitch, s16 vol, u8 pan, u8 fxMix, s32 delta)
Referenced by au_syn_update().
au_syn_stop_voice()
void au_syn_stop_voice (u8 voiceIdx)
Referenced by au_syn_update(), and au_update_stopped_voices().
au_syn_update()
void au_syn_update (AuGlobals * globals)
Referenced by au_update_clients_2().
au_update_clients_2()
void au_update_clients_2 (void)
Referenced by alAudioFrame().
au_update_players_main()
void au_update_players_main (void)
Referenced by alAudioFrame().
au_update_stopped_voices()
void au_update_stopped_voices (AuGlobals * globals)
au_update_voices()
void au_update_voices (AuGlobals * globals)
Referenced by au_update_clients_2().
au_use_global_volume()
void au_use_global_volume (void)
Referenced by nuAuPreNMIProc().
au_voice_after_volume_change()
void au_voice_after_volume_change (AuVoice * arg0)
Referenced by au_update_voices().
au_voice_get_delta()
s32 au_voice_get_delta (s32 arg0)
Referenced by au_update_voices(), au_voice_after_volume_change(), and au_voice_start().
au_voice_set_vol_changed()
void au_voice_set_vol_changed (AuVoice * arg0)
au_voice_start()
void au_voice_start (AuVoice * voice, EnvelopeData * arg1)
Referenced by au_syn_update().
au_voice_step()
u8 au_voice_step (AuVoice * voice)
Referenced by au_update_voices(), and au_voice_start().
create_audio_system()
void create_audio_system (void)
func_8004DB28()
s32 func_8004DB28 (BGMPlayer * player)
Referenced by au_load_song_files(), and func_8004DE2C().
func_8004DB4C()
AuResult func_8004DB4C (SongUpdateEvent * s)
Referenced by func_80055BB8(), and snd_set_song_variation_fade_time().
func_8004DC80()
AuResult func_8004DC80 (s32 songName)
Referenced by au_bgm_update_fade().
func_8004DCB8()
AuResult func_8004DCB8 (SongUpdateEvent * update, s32 clearChanged)
Referenced by func_8004DC80(), func_80055AF0(), func_80055B80(), and func_80055BF0().
func_8004DE2C()
AuResult func_8004DE2C (SongUpdateEvent * update)
Referenced by func_80055B28(), and func_80055C2C().
func_8004DFD4()
void func_8004DFD4 (AuGlobals * globals)
Referenced by au_update_clients_2().
func_8004E0F4()
AuResult func_8004E0F4 (SongUpdateEvent * update)
Referenced by func_80055C64(), and func_80055C94().
func_8004E444()
void func_8004E444 (BGMPlayer * arg0)
Referenced by au_bgm_update_fade(), and au_update_clients_2().
func_8004E844()
void func_8004E844 (BGMPlayer * player, s32 arg1)
Referenced by au_bgm_player_initialize(), and au_BGMCmd_FF().
func_8004E880()
void func_8004E880 (BGMPlayer * player, s32 sampleRate, s32 divisor)
Referenced by au_bgm_dispatch_player_event(), au_bgm_player_init(), and au_bgm_update_main().
func_80050888()
void func_80050888 (BGMPlayer * player, BGMPlayerTrack * track, s32 target, s32 duration)
Referenced by au_BGMCmd_FC_Jump(), and au_BGMCmd_FF().
func_80050900()
void func_80050900 (BGMPlayer * player)
Referenced by au_bgm_player_initialize(), au_bgm_player_update_stop(), and func_8004DCB8().
func_80050970()
AuResult func_80050970 (SongUpdateEvent * arg0)
Referenced by snd_set_song_variation().
func_80052E30()
void func_80052E30 (u8 index)
Referenced by au_pull_voice().
func_80053AC8()
void func_80053AC8 (Fade * fade)
Referenced by func_80054CE0().
func_80053B04()
void func_80053B04 (Fade * fade, u32 arg1, s32 target)
Referenced by func_8004E0F4().
func_80053BA8()
void func_80053BA8 (Fade * fade)
Referenced by au_update_clients_2().
func_80053E58()
AuResult func_80053E58 (s32 songID, BGMHeader * arg1)
Referenced by func_8004DE2C().
func_80053F64()
BGMPlayer * func_80053F64 (s32 arg0)
Referenced by func_8004DCB8(), and func_8004DE2C().
func_80054248()
BGMPlayer * func_80054248 (u8 arg0)
Referenced by func_8004DE2C().
func_80054AA0()
s32 * func_80054AA0 (s32 * bkFileOffset, void * vaddr, s32 bankIndex, s32 bankGroup)
func_80054C84()
void func_80054C84 (s32 bankIndex, s32 bankGroup)
func_80054CE0()
void func_80054CE0 (s32 arg0, u32 idx)
Referenced by func_800561A4(), and func_800561C4().
func_80054D74()
s32 func_80054D74 (s32 arg0, s32 arg1)
Referenced by func_800561E4().
func_80054DA8()
void func_80054DA8 (u32 arg0)
Referenced by audio_set_mono(), and audio_set_stereo().
func_80055110()
void func_80055110 (BGMPlayer * player)
Referenced by au_bgm_player_init().
func_80056D5C()
void func_80056D5C (u8 arg0)
Referenced by audio_set_mono(), and audio_set_stereo().
func_80058E84()
void func_80058E84 (AuFX * fx, u8 effectType, ALHeap * heap)
Parameters
effectType from enum AuEffectType
Referenced by au_driver_init().
func_80058F88()
void func_80058F88 (AlUnkKappa * kappa, ALHeap * heap)
func_80059008()
void func_80059008 (AlUnkKappa * kappa, s16 arg1, s16 arg2, s16 fc)
Referenced by func_80058F88().
func_8005904C()
void func_8005904C (AuFX * fx, u8 effectType)
Referenced by au_bus_set_effect(), and func_80058E84().
nuAuDmaCallBack()
s32 nuAuDmaCallBack (s32 addr, s32 len, void * state, u8 arg3)
Referenced by nuAuDmaNew().
nuAuMgr()
void nuAuMgr (void * arg)
Referenced by create_audio_system().
sfx_get_env_sound_instance()
SoundInstance * sfx_get_env_sound_instance (s32 soundID)
Referenced by sfx_adjust_env_sound_params(), sfx_adjust_env_sound_pos(), and snd_stop_tracking_env_sound_pos().
snd_load_BK()
s32 snd_load_BK (s32 bkFileOffset, s32 bankIndex)
Referenced by au_ambient_load(), au_load_song_files(), func_80053E58(), and snd_load_BGM().
snd_song_get_playing_info()
AuResult snd_song_get_playing_info (s32 songName, BGMHeader ** outTrackData, BGMPlayer ** outPlayer)
Referenced by snd_song_clear_track_volumes(), snd_song_set_detune(), snd_song_set_playback_rate(), and snd_song_set_track_volumes().