papermario: src/audio/public.h File Reference
public.h File Reference
Functions
void snd_notify_engine_ready (ALHeap *heap)
void snd_legacy_sound_dispatch (u32 id)
Unused Seems to be an early function that accepts a command to play any kind of audio asset,.
void snd_bgm_enqueue_legacy_command (u32 cmd)
Unused Part of an unused system for inter-thread communication with a BGM player using commands.
void snd_start_sound (s32 soundID, u8 volume, u8 pan)
void snd_start_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void snd_adjust_sound (s32 soundID, u8 volume, u8 pan)
void snd_adjust_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void snd_stop_sound (s32 soundID)
void snd_reset (void)
void snd_start_sound_raw (s32 soundID, s16 volume, s16 pitchShift, s32 pan)
AuResult snd_load_ambient (s32 arg0)
AuResult snd_ambient_play (s32 arg0, s32 arg1)
AuResult snd_ambient_stop_quick (s32 arg0)
AuResult snd_ambient_stop_slow (s32 arg0, s32 arg1)
AuResult snd_ambient_pause (s32 arg0, s32 arg1)
AuResult snd_ambient_resume (s32 arg0, s32 arg1)
AuResult snd_ambient_is_stopped (s32 arg0)
AuResult snd_ambient_fade_out (s32 arg0, s32 arg1)
AuResult snd_ambient_set_volume (s32 arg0, s32 arg1, s32 arg2)
AuResult snd_ambient_disable (s32 arg0)
AuResult snd_ambient_enable (s32 arg0)
void snd_ambient_radio_setup (s32 arg0)
AuResult snd_ambient_radio_stop (s32 arg0)
AuResult snd_ambient_radio_select (s32 arg0)
AuResult snd_song_load (s32 songID, s32 playerIndex)
return value may be either an AuResult error code OR a valid songName
AuResult snd_song_request_play_default (s32 songName)
Unused – snd_song_request_play but always uses BGM_VARIATION_0.
AuResult snd_song_request_play (s32 songName, s32 variation)
Called from bgm_control to start playing a particular song + variation.
AuResult snd_song_stop (s32 songName)
void snd_song_stop_all (void)
AuResult snd_song_is_playing (s32 songName)
AuResult snd_song_request_fade_in (s32 songName, s32 variation, s32 fadeInTime, s32 startVolume, s32 endVolume)
Called from bgm_control to fade in a particular song + variation.
AuResult snd_song_request_fade_in_default (s32 songName, s32 fadeInTime, s32 startVolume, s32 endVolume)
Unused.
AuResult snd_song_request_fade_out (s32 songName, s32 fadeTime, AuCallback callback)
AuResult snd_song_push_stop (s32 songName)
AuResult snd_song_request_pop (s32 songName)
AuResult snd_song_request_snapshot (s32 songName)
AuResult snd_song_request_push_fade_out (s32 songName, s32 fadeTime)
AuResult snd_song_request_pause (s32 songName)
AuResult snd_song_request_unpause (s32 songName)
AuResult snd_song_set_volume_quiet (s32 songName)
AuResult snd_song_set_volume_full (s32 songName)
AuResult snd_song_set_linked_mode (s32 songName, bool mode)
AuResult snd_song_set_playback_rate (s32 songName, f32 arg1)
void snd_song_poll_music_events (u32 **arg0, s32 *arg1)
void snd_song_flush_music_events (void)
void snd_song_trigger_music_event (s32 playerID, s32 trackIndex, s32 eventInfo)
void snd_song_clear_music_events (void)
void snd_set_stereo (void)
void snd_set_mono (void)
void snd_set_bgm_volume (VolumeLevels volume)
void snd_set_sfx_volume (VolumeLevels volume)
void snd_set_sfx_reverb_type (s32 arg0)
void snd_enable_sfx (void)
void snd_disable_sfx (void)
AuResult bgm_set_track_volumes (s32 playerIndex, s16 trackVolSet)
AuResult bgm_clear_track_volumes (s32 playerIndex, s16 trackVolSet)
AuResult bgm_set_linked_mode (s32 playerIndex, b16 mode)
void bgm_quiet_max_volume (void)
void bgm_reset_max_volume (void)
void bgm_reset_volume (void)
s32 bgm_init_music_players (void)
s32 bgm_set_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
void bgm_set_battle_song (s32, s32)
void bgm_push_battle_song (void)
s32 bgm_adjust_proximity (s32 playerIndex, s32 arg1, s16 arg2)
bool bgm_fade_in_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeInTime, s16 arg4, s16 arg5)
void bgm_update_music_control (void)
bool bgm_is_any_song_playing (void)
void bgm_reset_sequence_players (void)
void bgm_pop_song (void)
void bgm_push_song (s32 songID, s32 variation)
void bgm_pop_battle_song (void)
void sfx_reset_door_sounds (void)
void sfx_clear_sounds (void)
void sfx_clear_env_sounds (s16 playSounds)
void sfx_update_env_sound_params (void)
void sfx_set_reverb_mode (s32 arg0)
s32 sfx_get_reverb_mode (void)
void sfx_stop_env_sounds (void)
void sfx_play_sound_looping (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void sfx_register_looping_sound_at_position (s32 soundID, s32 flags, f32 x, f32 y, f32 z)
s32 sfx_adjust_env_sound_pos (s32 soundID, s32 sourceFlags, f32 x, f32 y, f32 z)
void sfx_stop_tracking_env_sound_pos (s32 soundID, s32 keepPlaying)
void sfx_play_sound_with_params (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void sfx_adjust_env_sound_params (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void sfx_stop_sound (s32 soundID)
void sfx_play_sound (s32 soundID)
void sfx_play_sound_at_player (s32 soundID, s32 arg1)
void sfx_play_sound_at_npc (s32 soundID, s32 arg1, s32 npcID)
void sfx_play_sound_at_position (s32 soundID, s32 flags, f32 posX, f32 posY, f32 posZ)
void sfx_get_spatialized_sound_params (f32 x, f32 y, f32 z, s16 *volume, s16 *pan, s32 flags)
void sfx_compute_spatialized_sound_params_ignore_depth (f32 x, f32 y, f32 z, s16 *volume, s16 *pan)
void sfx_compute_spatialized_sound_params_with_depth (f32 x, f32 y, f32 z, s16 *volume, s16 *pan)
void sfx_compute_spatialized_sound_params_full (f32 x, f32 y, f32 z, s16 *volume, s16 *pan, s32 flags)
Function Documentation
bgm_adjust_proximity()
s32 bgm_adjust_proximity (s32 playerIndex, s32 arg1, s16 arg2)
bgm_clear_track_volumes()
AuResult bgm_clear_track_volumes (s32 playerIndex, s16 trackVolSet)
bgm_fade_in_song()
bool bgm_fade_in_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeInTime, s16 arg4, s16 arg5)
bgm_init_music_players()
s32 bgm_init_music_players (void)
Referenced by state_step_startup().
bgm_is_any_song_playing()
bool bgm_is_any_song_playing (void)
bgm_pop_battle_song()
void bgm_pop_battle_song (void)
Referenced by update_encounters_post_battle().
bgm_pop_song()
void bgm_pop_song (void)
bgm_push_battle_song()
void bgm_push_battle_song (void)
Referenced by update_encounters_pre_battle().
bgm_push_song()
void bgm_push_song (s32 songID, s32 variation)
bgm_quiet_max_volume()
void bgm_quiet_max_volume (void)
Referenced by state_step_pause().
bgm_reset_max_volume()
void bgm_reset_max_volume (void)
Referenced by state_step_unpause().
bgm_reset_sequence_players()
void bgm_reset_sequence_players (void)
Referenced by load_engine_data().
bgm_reset_volume()
void bgm_reset_volume (void)
Referenced by state_step_startup().
bgm_set_battle_song()
void bgm_set_battle_song (s32 songID, s32 variation)
Referenced by update_encounters_pre_battle().
bgm_set_linked_mode()
AuResult bgm_set_linked_mode (s32 playerIndex, b16 mode)
bgm_set_song()
s32 bgm_set_song (s32 playerIndex, s32 songID, s32 variation, s32 fadeOutTime, s16 volume)
Referenced by bgm_init_music_players(), bgm_push_battle_song(), bgm_push_song(), btl_state_update_celebration(), btl_state_update_defeat(), btl_state_update_end_training_battle(), btl_state_update_run_away(), btl_state_update_victory(), state_init_exit_file_select(), state_init_title_screen(), and state_step_title_screen().
bgm_set_track_volumes()
AuResult bgm_set_track_volumes (s32 playerIndex, s16 trackVolSet)
bgm_update_music_control()
void bgm_update_music_control (void)
Bug
this is called even if we are trying to fade in, immediately overriding any fade parameters
Referenced by step_game_loop().
sfx_adjust_env_sound_params()
void sfx_adjust_env_sound_params (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by update().
sfx_adjust_env_sound_pos()
s32 sfx_adjust_env_sound_pos (s32 soundID, s32 sourceFlags, f32 x, f32 y, f32 z)
Referenced by SentinelAI_Descend().
sfx_clear_env_sounds()
void sfx_clear_env_sounds (s16 playSounds)
Referenced by load_map_by_IDs(), state_step_battle(), state_step_end_battle(), state_step_exit_language_select(), state_step_language_select(), state_step_pause(), and state_step_unpause().
sfx_clear_sounds()
void sfx_clear_sounds (void)
Referenced by load_engine_data(), and state_step_startup().
sfx_compute_spatialized_sound_params_full()
void sfx_compute_spatialized_sound_params_full (f32 x, f32 y, f32 z, s16 * volume, s16 * pan, s32 flags)
Referenced by sfx_get_spatialized_sound_params().
sfx_compute_spatialized_sound_params_ignore_depth()
void sfx_compute_spatialized_sound_params_ignore_depth (f32 x, f32 y, f32 z, s16 * volume, s16 * pan)
Referenced by sfx_get_spatialized_sound_params().
sfx_compute_spatialized_sound_params_with_depth()
void sfx_compute_spatialized_sound_params_with_depth (f32 x, f32 y, f32 z, s16 * volume, s16 * pan)
Referenced by sfx_get_spatialized_sound_params().
sfx_get_reverb_mode()
s32 sfx_get_reverb_mode (void)
Referenced by state_step_pause().
sfx_get_spatialized_sound_params()
void sfx_get_spatialized_sound_params (f32 x, f32 y, f32 z, s16 * volume, s16 * pan, s32 flags)
Referenced by sfx_play_sound_at_position(), and sfx_update_env_sound_params().
sfx_play_sound()
void sfx_play_sound (s32 soundID)
Referenced by _use_partner_ability(), btl_main_menu_update(), btl_state_update_begin_player_turn(), btl_state_update_celebration(), btl_state_update_defeat(), btl_state_update_partner_menu(), btl_state_update_partner_move(), btl_state_update_player_menu(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_select_target(), btl_submenu_moves_update(), btl_update_ko_status(), btl_update_strats_menu(), calc_player_damage_enemy(), can_open_world_menu(), card_worker_update(), check_input_open_menus(), check_input_status_bar(), coin_counter_draw_content(), entity_BlueWarpPipe_enter_pipe_init(), entity_Chest_begin_opening(), entity_CymbalPlant_idle(), entity_HeartBlockContent__anim_heal(), entity_HiddenPanel_flip_over(), entity_Padlock_idle(), entity_SaveBlock_show_result_message(), entity_StarBoxLauncher_launch(), entity_WoodenCrate_idle(), filemenu_choose_name_handle_input(), filemenu_main_handle_input(), filemenu_selectlanguage_handle_input(), filemenu_yesno_handle_input(), func_800F16CC(), func_802BB34C_E2DC7C(), func_802BC3E4_E2ED14(), hud_element_update(), inflict_partner_ko(), partner_use_ability(), pause_badges_handle_input(), pause_handle_input(), pause_init(), pause_items_handle_input(), pause_map_handle_input(), pause_partners_handle_input(), pause_spirits_handle_input(), pause_stats_handle_input(), pause_tabs_handle_input(), pause_tutorial_input(), popup_menu_update(), remove_player_buffs(), should_cancel_open_world_menu(), state_step_title_screen(), step_entity_commandlist(), update(), update_encounters_neutral(), update_item_entity_pickup(), and update_status_bar().
sfx_play_sound_at_npc()
void sfx_play_sound_at_npc (s32 soundID, s32 arg1, s32 npcID)
Referenced by update_riding_physics().
sfx_play_sound_at_player()
void sfx_play_sound_at_player (s32 soundID, s32 arg1)
Referenced by action_hammer_end_swing(), action_hammer_play_hit_fx(), action_update_hammer(), action_update_hit_lava(), action_update_jump(), action_update_land(), action_update_parasol(), action_update_peach_land(), action_update_sliding(), action_update_spin(), action_update_spin_jump(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_tweester(), appendGfx_pulse_stone_icon(), ispy_notification_update(), phys_player_land(), player_jump(), and try_player_footstep_sounds().
sfx_play_sound_at_position()
void sfx_play_sound_at_position (s32 soundID, s32 flags, f32 posX, f32 posY, f32 posZ)
sfx_play_sound_looping()
void sfx_play_sound_looping (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by sfx_play_sound_with_params().
sfx_play_sound_with_params()
void sfx_play_sound_with_params (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by _update_message(), appendGfx_score_display(), card_worker_update(), msg_copy_to_print_buffer(), msg_play_speech_sound(), sfx_play_sound(), sfx_play_sound_at_position(), update(), and update_riding_physics().
sfx_register_looping_sound_at_position()
void sfx_register_looping_sound_at_position (s32 soundID, s32 flags, f32 x, f32 y, f32 z)
Referenced by sfx_play_sound_at_position().
sfx_reset_door_sounds()
void sfx_reset_door_sounds (void)
Referenced by load_map_by_IDs(), and sfx_clear_sounds().
sfx_set_reverb_mode()
void sfx_set_reverb_mode (s32 arg0)
Referenced by load_map_by_IDs(), sfx_clear_sounds(), state_init_title_screen(), state_step_pause(), and state_step_unpause().
sfx_stop_env_sounds()
void sfx_stop_env_sounds (void)
Referenced by load_map_by_IDs(), state_step_battle(), state_step_end_battle(), state_step_language_select(), state_step_pause(), and step_game_loop().
sfx_stop_sound()
void sfx_stop_sound (s32 soundID)
Referenced by action_update_spin(), free(), phys_update_action_state(), pre_battle(), pre_battle(), SentinelAI_LosePlayerInit(), set_action_state(), update(), and update_encounters_pre_battle().
sfx_stop_tracking_env_sound_pos()
void sfx_stop_tracking_env_sound_pos (s32 soundID, s32 keepPlaying)
Referenced by func_802BB34C_E2DC7C(), and sfx_stop_sound().
sfx_update_env_sound_params()
void sfx_update_env_sound_params (void)
Referenced by step_game_loop().
snd_adjust_sound()
void snd_adjust_sound (s32 soundID, u8 volume, u8 pan)
snd_adjust_sound_with_shift()
void snd_adjust_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by sfx_adjust_env_sound_params(), and sfx_update_env_sound_params().
snd_ambient_disable()
AuResult snd_ambient_disable (s32 arg0)
Referenced by snd_ambient_radio_select().
snd_ambient_enable()
AuResult snd_ambient_enable (s32 arg0)
Referenced by snd_ambient_radio_select().
snd_ambient_fade_out()
AuResult snd_ambient_fade_out (s32 arg0, s32 arg1)
snd_ambient_is_stopped()
AuResult snd_ambient_is_stopped (s32 arg0)
Referenced by update_ambient_sounds().
snd_ambient_pause()
AuResult snd_ambient_pause (s32 arg0, s32 arg1)
Referenced by bgm_push_battle_song().
snd_ambient_play()
AuResult snd_ambient_play (s32 arg0, s32 arg1)
Referenced by snd_ambient_radio_setup(), and update_ambient_sounds().
snd_ambient_radio_select()
AuResult snd_ambient_radio_select (s32 arg0)
Referenced by snd_ambient_radio_setup().
snd_ambient_radio_setup()
void snd_ambient_radio_setup (s32 arg0)
snd_ambient_radio_stop()
AuResult snd_ambient_radio_stop (s32 arg0)
snd_ambient_resume()
AuResult snd_ambient_resume (s32 arg0, s32 arg1)
Referenced by bgm_pop_battle_song().
snd_ambient_set_volume()
AuResult snd_ambient_set_volume (s32 arg0, s32 arg1, s32 arg2)
snd_ambient_stop_quick()
AuResult snd_ambient_stop_quick (s32 arg0)
Referenced by play_ambient_sounds(), snd_ambient_radio_stop(), and update_ambient_sounds().
snd_ambient_stop_slow()
AuResult snd_ambient_stop_slow (s32 arg0, s32 arg1)
Referenced by snd_ambient_radio_stop(), and update_ambient_sounds().
snd_bgm_enqueue_legacy_command()
void snd_bgm_enqueue_legacy_command (u32 cmd)
Unused Part of an unused system for inter-thread communication with a BGM player using commands.
Use functions in bgm_control to manipualte gMusicControlData instead.
snd_disable_sfx()
void snd_disable_sfx (void)
Referenced by state_init_demo().
snd_enable_sfx()
void snd_enable_sfx (void)
Referenced by state_step_demo().
snd_legacy_sound_dispatch()
void snd_legacy_sound_dispatch (u32 id)
Unused Seems to be an early function that accepts a command to play any kind of audio asset,.
snd_load_ambient()
AuResult snd_load_ambient (s32 arg0)
Referenced by update_ambient_sounds().
snd_notify_engine_ready()
void snd_notify_engine_ready (ALHeap * heap)
Referenced by au_engine_init().
snd_reset()
void snd_reset (void)
snd_set_bgm_volume()
void snd_set_bgm_volume (VolumeLevels volume)
Referenced by bgm_reset_sequence_players(), and bgm_update_volume().
snd_set_mono()
void snd_set_mono (void)
Referenced by filemenu_main_handle_input(), and state_step_startup().
snd_set_sfx_reverb_type()
void snd_set_sfx_reverb_type (s32 arg0)
Referenced by sfx_set_reverb_mode().
snd_set_sfx_volume()
void snd_set_sfx_volume (VolumeLevels volume)
snd_set_stereo()
void snd_set_stereo (void)
Referenced by filemenu_main_handle_input(), and state_step_startup().
snd_song_clear_music_events()
void snd_song_clear_music_events (void)
Referenced by au_engine_init(), and au_update_clients_for_video_frame().
snd_song_flush_music_events()
void snd_song_flush_music_events (void)
snd_song_is_playing()
AuResult snd_song_is_playing (s32 songName)
Referenced by bgm_is_any_song_playing(), and bgm_update_music_control().
snd_song_load()
AuResult snd_song_load (s32 songID, s32 playerIndex)
return value may be either an AuResult error code OR a valid songName
Referenced by bgm_update_music_control(), and snd_legacy_sound_dispatch().
snd_song_poll_music_events()
void snd_song_poll_music_events (u32 ** arg0, s32 * arg1)
snd_song_push_stop()
AuResult snd_song_push_stop (s32 songName)
Referenced by bgm_update_music_control().
snd_song_request_fade_in()
AuResult snd_song_request_fade_in (s32 songName, s32 variation, s32 fadeInTime, s32 startVolume, s32 endVolume)
Called from bgm_control to fade in a particular song + variation.
Referenced by bgm_update_music_control().
snd_song_request_fade_in_default()
AuResult snd_song_request_fade_in_default (s32 songName, s32 fadeInTime, s32 startVolume, s32 endVolume)
Unused.
snd_song_request_fade_out()
AuResult snd_song_request_fade_out (s32 songName, s32 fadeTime, AuCallback callback)
Referenced by bgm_update_music_control().
snd_song_request_pause()
AuResult snd_song_request_pause (s32 songName)
snd_song_request_play()
AuResult snd_song_request_play (s32 songName, s32 variation)
Called from bgm_control to start playing a particular song + variation.
Referenced by bgm_update_music_control(), and snd_legacy_sound_dispatch().
snd_song_request_play_default()
AuResult snd_song_request_play_default (s32 songName)
Unused – snd_song_request_play but always uses BGM_VARIATION_0.
snd_song_request_pop()
AuResult snd_song_request_pop (s32 songName)
Referenced by bgm_update_music_control().
snd_song_request_push_fade_out()
AuResult snd_song_request_push_fade_out (s32 songName, s32 fadeTime)
Referenced by bgm_update_music_control().
snd_song_request_snapshot()
AuResult snd_song_request_snapshot (s32 songName)
Referenced by _bgm_set_song().
snd_song_request_unpause()
AuResult snd_song_request_unpause (s32 songName)
snd_song_set_linked_mode()
AuResult snd_song_set_linked_mode (s32 songName, bool mode)
Referenced by bgm_set_linked_mode().
snd_song_set_playback_rate()
AuResult snd_song_set_playback_rate (s32 songName, f32 arg1)
Referenced by worker_update_phonograph_hud().
snd_song_set_volume_full()
AuResult snd_song_set_volume_full (s32 songName)
snd_song_set_volume_quiet()
AuResult snd_song_set_volume_quiet (s32 songName)
snd_song_stop()
AuResult snd_song_stop (s32 songName)
Referenced by _bgm_set_song(), bgm_fade_in_song(), and bgm_update_music_control().
snd_song_stop_all()
void snd_song_stop_all (void)
snd_song_trigger_music_event()
void snd_song_trigger_music_event (s32 playerID, s32 trackIndex, s32 eventInfo)
Referenced by au_BGMCmd_FD_EventTrigger().
snd_start_sound()
void snd_start_sound (s32 soundID, u8 volume, u8 pan)
Referenced by animate_and_draw_record(), and appendGfx_records().
snd_start_sound_raw()
void snd_start_sound_raw (s32 soundID, s16 volume, s16 pitchShift, s32 pan)
snd_start_sound_with_shift()
void snd_start_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by sfx_clear_env_sounds(), sfx_play_sound_looping(), sfx_play_sound_with_params(), and snd_legacy_sound_dispatch().
snd_stop_sound()
void snd_stop_sound (s32 soundID)
Referenced by action_update_sliding(), sfx_stop_env_sounds(), sfx_stop_sound(), and sfx_stop_tracking_env_sound_pos().