papermario: src/pulse_stone.c File Reference
pulse_stone.c File Reference
Data Structures
struct PulseStoneData
Enumerations
enum { PULSE_STONE_APPEAR = 0 , PULSE_STONE_OVERSHOOT = 1 , PULSE_STONE_HOLD = 2 }
Functions
INCLUDE_IMG ("pulse_stone_icon.png", pulse_stone_icon_img)
INCLUDE_PAL ("pulse_stone_icon.pal", pulse_stone_icon_1_pal)
INCLUDE_PAL ("pulse_stone_icon.flash.pal", pulse_stone_icon_2_pal)
void pulse_stone_notification_update (void)
s32 should_cancel_pulse_stone (void)
s32 should_continue_pulse_stone (void)
void pulse_stone_notification_setup (void)
void appendGfx_pulse_stone_icon (void)
Variables
BSS PulseStoneData PulseStoneNotification
PulseStoneData * PulseStonePtr = &PulseStoneNotification
Data Structure Documentation
PulseStoneData
struct PulseStoneData
Data Fields
s32 appearDelay
s32 pingTime
Vec3f pos
f32 scale
s32 state
char unk_10[0x8]
char unk_1C[0x4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PULSE_STONE_APPEAR
PULSE_STONE_OVERSHOOT
PULSE_STONE_HOLD
Function Documentation
appendGfx_pulse_stone_icon()
void appendGfx_pulse_stone_icon (void)
Referenced by render_pulse_stone_icon().
INCLUDE_IMG()
INCLUDE_IMG ("pulse_stone_icon.png" , pulse_stone_icon_img)
INCLUDE_PAL() [1/2]
INCLUDE_PAL ("pulse_stone_icon.flash.pal" , pulse_stone_icon_2_pal)
INCLUDE_PAL() [2/2]
INCLUDE_PAL ("pulse_stone_icon.pal" , pulse_stone_icon_1_pal)
pulse_stone_notification_setup()
void pulse_stone_notification_setup (void)
Referenced by check_for_pulse_stone().
pulse_stone_notification_update()
void pulse_stone_notification_update (void)
Referenced by pulse_stone_notification_setup().
should_cancel_pulse_stone()
s32 should_cancel_pulse_stone (void)
Referenced by should_continue_pulse_stone().
should_continue_pulse_stone()
s32 should_continue_pulse_stone (void)
Referenced by pulse_stone_notification_update().
Variable Documentation
PulseStoneNotification
BSS PulseStoneData PulseStoneNotification
PulseStonePtr
PulseStoneData* PulseStonePtr = &PulseStoneNotification
Referenced by appendGfx_pulse_stone_icon(), pulse_stone_notification_setup(), and pulse_stone_notification_update().