papermario: src/effects/purple_ring.c File Reference
purple_ring.c File Reference
Functions
void purple_ring_init (EffectInstance *effect)
void purple_ring_update (EffectInstance *effect)
void purple_ring_render (EffectInstance *effect)
void purple_ring_appendGfx (void *effect)
EffectInstance * purple_ring_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7)
Variables
Gfx D_09000200_352EE0 []
Gfx D_090004E8_3531C8 []
Function Documentation
purple_ring_appendGfx()
void purple_ring_appendGfx (void * effect)
Referenced by purple_ring_render().
purple_ring_init()
void purple_ring_init (EffectInstance * effect)
Referenced by purple_ring_main().
purple_ring_main()
EffectInstance * purple_ring_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7)
purple_ring_render()
void purple_ring_render (EffectInstance * effect)
Referenced by purple_ring_main().
purple_ring_update()
void purple_ring_update (EffectInstance * effect)
Referenced by purple_ring_main().
Variable Documentation
D_09000200_352EE0
Gfx D_09000200_352EE0[] extern
Referenced by purple_ring_appendGfx().
D_090004E8_3531C8
Gfx D_090004E8_3531C8[] extern
Referenced by purple_ring_appendGfx().