papermario: src/effects/quizmo_assistant.c File Reference
quizmo_assistant.c File Reference
Functions
void quizmo_assistant_init (EffectInstance *effect)
void quizmo_assistant_update (EffectInstance *effect)
void quizmo_assistant_render (EffectInstance *effect)
void quizmo_assistant_appendGfx (void *effect)
EffectInstance * quizmo_assistant_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09002400_409480 []
Gfx D_09002528_4095A8 []
Gfx D_090025B8_409638 []
Gfx D_09002648_4096C8 []
Gfx D_090026D8_409758 []
Gfx D_090027F0_409870 []
Gfx * D_E011C500 []
Gfx * D_E011C514 [] = { D_09002400_409480 }
s32 D_E011C518 [] = { 1, 1, 2, 2, 2 }
s32 D_E011C52C [] = { 3, 3, 4, 4 }
Function Documentation
quizmo_assistant_appendGfx()
void quizmo_assistant_appendGfx (void * effect)
Referenced by quizmo_assistant_render().
quizmo_assistant_init()
void quizmo_assistant_init (EffectInstance * effect)
Referenced by quizmo_assistant_main().
quizmo_assistant_main()
EffectInstance * quizmo_assistant_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
quizmo_assistant_render()
void quizmo_assistant_render (EffectInstance * effect)
Referenced by quizmo_assistant_main().
quizmo_assistant_update()
void quizmo_assistant_update (EffectInstance * effect)
Referenced by quizmo_assistant_main().
Variable Documentation
D_09002400_409480
Gfx D_09002400_409480[] extern
D_09002528_4095A8
Gfx D_09002528_4095A8[] extern
D_090025B8_409638
Gfx D_090025B8_409638[] extern
D_09002648_4096C8
Gfx D_09002648_4096C8[] extern
D_090026D8_409758
Gfx D_090026D8_409758[] extern
D_090027F0_409870
Gfx D_090027F0_409870[] extern
D_E011C500
Gfx* D_E011C500[]
Initial value:
= {
    D_09002528_4095A8, D_090025B8_409638, D_09002648_4096C8,
    D_090026D8_409758, D_090027F0_409870
}
Referenced by quizmo_assistant_appendGfx().
D_E011C514
Gfx* D_E011C514[] = { D_09002400_409480 }
Referenced by quizmo_assistant_appendGfx().
D_E011C518
s32 D_E011C518[] = { 1, 1, 2, 2, 2 }
Referenced by quizmo_assistant_appendGfx().
D_E011C52C
s32 D_E011C52C[] = { 3, 3, 4, 4 }
Referenced by quizmo_assistant_appendGfx().