papermario: src/effects/quizmo_audience.c File Reference
quizmo_audience.c File Reference
Data Structures
struct QuizmoAudiencePositonOffsets
Functions
void quizmo_audience_appendGfx (void *effect)
void quizmo_audience_init (EffectInstance *effect)
void quizmo_audience_update (EffectInstance *effect)
void quizmo_audience_render (EffectInstance *effect)
EffectInstance * quizmo_audience_main (s32 arg0, f32 posX, f32 posY, f32 posZ)
void func_E00A8318 (void)
Variables
Gfx D_09002EE0_3AA680 []
Gfx D_09002F18_3AA6B8 []
Gfx D_09002F50_3AA6F0 []
Gfx D_09002F88_3AA728 []
Gfx D_09002FC0_3AA760 []
Gfx D_09002FF8_3AA798 []
Gfx D_09003030_3AA7D0 []
Gfx D_09003068_3AA808 []
Gfx D_090030A0_3AA840 []
Gfx D_090030D8_3AA878 []
Gfx D_09003110_3AA8B0 []
Gfx * quizmo_audience_renderAudienceMember []
Vec2b quizmo_audience_horizontalPosOffsets []
Vec2b quizmo_audience_verticalPosOffsets []
QuizmoAudiencePositonOffsets quizmo_audience_positionOffsets []
Data Structure Documentation
QuizmoAudiencePositonOffsets
struct QuizmoAudiencePositonOffsets
Data Fields
u8 count
Vec2b * offsets
Function Documentation
func_E00A8318()
void func_E00A8318 (void)
quizmo_audience_appendGfx()
void quizmo_audience_appendGfx (void * effect)
Referenced by quizmo_audience_render().
quizmo_audience_init()
void quizmo_audience_init (EffectInstance * effect)
Referenced by quizmo_audience_main().
quizmo_audience_main()
EffectInstance * quizmo_audience_main (s32 arg0, f32 posX, f32 posY, f32 posZ)
quizmo_audience_render()
void quizmo_audience_render (EffectInstance * effect)
Referenced by quizmo_audience_main().
quizmo_audience_update()
void quizmo_audience_update (EffectInstance * effect)
Referenced by quizmo_audience_main().
Variable Documentation
D_09002EE0_3AA680
Gfx D_09002EE0_3AA680[] extern
D_09002F18_3AA6B8
Gfx D_09002F18_3AA6B8[] extern
D_09002F50_3AA6F0
Gfx D_09002F50_3AA6F0[] extern
D_09002F88_3AA728
Gfx D_09002F88_3AA728[] extern
D_09002FC0_3AA760
Gfx D_09002FC0_3AA760[] extern
D_09002FF8_3AA798
Gfx D_09002FF8_3AA798[] extern
D_09003030_3AA7D0
Gfx D_09003030_3AA7D0[] extern
D_09003068_3AA808
Gfx D_09003068_3AA808[] extern
D_090030A0_3AA840
Gfx D_090030A0_3AA840[] extern
D_090030D8_3AA878
Gfx D_090030D8_3AA878[] extern
D_09003110_3AA8B0
Gfx D_09003110_3AA8B0[] extern
Referenced by quizmo_audience_appendGfx().
quizmo_audience_horizontalPosOffsets
Vec2b quizmo_audience_horizontalPosOffsets[]
Initial value:
= {
    {0, 0},
    {1, 0},
    {2, 0},
    {2, 0},
    {3, 0},
    {3, 0},
    {3, 0},
    {2, 0},
    {2, 0},
    {1, 0},
    {1, 0},
    {0, 0},
    {0, 0},
    {-1, 0},
    {-2, 0},
    {-2, 0},
    {-3, 0},
    {-3, 0},
    {-3, 0},
    {-2, 0},
    {-2, 0},
    {-1, 0},
    {-1, 0},
    {0, 0},
}
quizmo_audience_positionOffsets
QuizmoAudiencePositonOffsets quizmo_audience_positionOffsets[]
Initial value:
= {
    { quizmo_audience_horizontalPosOffsets, ARRAY_COUNT(quizmo_audience_horizontalPosOffsets) },
    { quizmo_audience_verticalPosOffsets, ARRAY_COUNT(quizmo_audience_verticalPosOffsets) },
}
Referenced by quizmo_audience_update().
quizmo_audience_renderAudienceMember
Gfx* quizmo_audience_renderAudienceMember[]
Initial value:
= {
    D_090030D8_3AA878, D_090030A0_3AA840, D_09003068_3AA808, D_09003030_3AA7D0, D_09002FF8_3AA798,
    D_09002FC0_3AA760, D_09002F88_3AA728, D_09002F50_3AA6F0, D_09002F18_3AA6B8, D_09002EE0_3AA680
}
Referenced by quizmo_audience_appendGfx().
quizmo_audience_verticalPosOffsets
Vec2b quizmo_audience_verticalPosOffsets[]
Initial value:
= {
    {0, 0},
    {0, 1},
    {0, 2},
    {0, 2},
    {0, 3},
    {0, 3},
    {0, 3},
    {0, 2},
    {0, 2},
    {0, 1},
    {0, 1},
    {0, 0},
}