papermario: src/effects/radial_shimmer.c File Reference
radial_shimmer.c File Reference
Functions
void radial_shimmer_init (EffectInstance *effect)
void radial_shimmer_update (EffectInstance *effect)
void radial_shimmer_render (EffectInstance *effect)
void radial_shimmer_appendGfx (void *effect)
EffectInstance * radial_shimmer_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09003428_36A188 []
Gfx D_09003508_36A268 []
Gfx D_090035E8_36A348 []
Gfx D_090036C8_36A428 []
Gfx D_09003830_36A590 []
Gfx D_090038B8_36A618 []
Gfx D_090039A8_36A708 []
Gfx D_09003A88_36A7E8 []
Gfx * D_E0066C50 []
Gfx * D_E0066C8C []
s32 D_E0066CC8 []
Function Documentation
radial_shimmer_appendGfx()
void radial_shimmer_appendGfx (void * effect)
Referenced by radial_shimmer_render().
radial_shimmer_init()
void radial_shimmer_init (EffectInstance * effect)
Referenced by radial_shimmer_main().
radial_shimmer_main()
EffectInstance * radial_shimmer_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
radial_shimmer_render()
void radial_shimmer_render (EffectInstance * effect)
Referenced by radial_shimmer_main().
radial_shimmer_update()
void radial_shimmer_update (EffectInstance * effect)
Referenced by radial_shimmer_main().
Variable Documentation
D_09003428_36A188
Gfx D_09003428_36A188[] extern
D_09003508_36A268
Gfx D_09003508_36A268[] extern
D_090035E8_36A348
Gfx D_090035E8_36A348[] extern
D_090036C8_36A428
Gfx D_090036C8_36A428[] extern
D_09003830_36A590
Gfx D_09003830_36A590[] extern
D_090038B8_36A618
Gfx D_090038B8_36A618[] extern
D_090039A8_36A708
Gfx D_090039A8_36A708[] extern
D_09003A88_36A7E8
Gfx D_09003A88_36A7E8[] extern
D_E0066C50
Gfx* D_E0066C50[]
Initial value:
= {
    D_09003830_36A590, D_09003830_36A590, D_09003830_36A590, D_09003830_36A590, D_09003830_36A590,
    D_09003830_36A590, D_09003830_36A590, D_09003830_36A590, D_09003830_36A590, D_09003830_36A590,
    D_09003830_36A590, D_09003830_36A590, D_09003830_36A590, D_09003830_36A590, D_09003830_36A590
}
Referenced by radial_shimmer_appendGfx().
D_E0066C8C
Gfx* D_E0066C8C[]
Initial value:
= {
    D_09003508_36A268, D_090035E8_36A348, D_09003428_36A188, D_090039A8_36A708, D_09003A88_36A7E8,
    D_09003428_36A188, D_090039A8_36A708, D_09003A88_36A7E8, D_090038B8_36A618, D_09003508_36A268,
    D_090038B8_36A618, D_090038B8_36A618, D_09003428_36A188, D_09003A88_36A7E8, D_090036C8_36A428,
}
Referenced by radial_shimmer_appendGfx().
D_E0066CC8
s32 D_E0066CC8[]
Initial value:
= {
    0xFFC59CFF, 0x9CFFFF73, 0xD6FF9CFF, 0xFFC57BFF, 0xB4FFDE73, 0xFFFF949C
}