papermario: src/effects/radiating_energy_orb.c File Reference
radiating_energy_orb.c File Reference
Functions
void radiating_energy_orb_init (EffectInstance *effect)
void radiating_energy_orb_update (EffectInstance *effect)
void radiating_energy_orb_render (EffectInstance *effect)
void radiating_energy_orb_appendGfx (void *effect)
EffectInstance * radiating_energy_orb_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09001200_3A1F60 []
Gfx D_090012A8_3A2008 []
Gfx D_09001490_3A21F0 []
Gfx D_090014B0_3A2210 []
Gfx D_090014D0_3A2230 []
Gfx D_090014F0_3A2250 []
Gfx D_09001510_3A2270 []
Gfx * D_E009EDF0 [] = { D_09001490_3A21F0 }
Gfx * D_E009EDF4 [] = { D_090014B0_3A2210 }
Gfx * D_E009EDF8 [] = { D_090014D0_3A2230 }
Gfx * D_E009EDFC [] = { D_090014F0_3A2250 }
Function Documentation
radiating_energy_orb_appendGfx()
void radiating_energy_orb_appendGfx (void * effect)
Referenced by radiating_energy_orb_render().
radiating_energy_orb_init()
void radiating_energy_orb_init (EffectInstance * effect)
Referenced by radiating_energy_orb_main().
radiating_energy_orb_main()
EffectInstance * radiating_energy_orb_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
radiating_energy_orb_render()
void radiating_energy_orb_render (EffectInstance * effect)
Referenced by radiating_energy_orb_main().
radiating_energy_orb_update()
void radiating_energy_orb_update (EffectInstance * effect)
Referenced by radiating_energy_orb_main().
Variable Documentation
D_09001200_3A1F60
Gfx D_09001200_3A1F60[] extern
Referenced by radiating_energy_orb_appendGfx().
D_090012A8_3A2008
Gfx D_090012A8_3A2008[] extern
Referenced by radiating_energy_orb_appendGfx().
D_09001490_3A21F0
Gfx D_09001490_3A21F0[] extern
D_090014B0_3A2210
Gfx D_090014B0_3A2210[] extern
D_090014D0_3A2230
Gfx D_090014D0_3A2230[] extern
D_090014F0_3A2250
Gfx D_090014F0_3A2250[] extern
D_09001510_3A2270
Gfx D_09001510_3A2270[] extern
Referenced by radiating_energy_orb_appendGfx().
D_E009EDF0
Gfx* D_E009EDF0[] = { D_09001490_3A21F0 }
Referenced by radiating_energy_orb_appendGfx().
D_E009EDF4
Gfx* D_E009EDF4[] = { D_090014B0_3A2210 }
Referenced by radiating_energy_orb_appendGfx().
D_E009EDF8
Gfx* D_E009EDF8[] = { D_090014D0_3A2230 }
Referenced by radiating_energy_orb_appendGfx().
D_E009EDFC
Gfx* D_E009EDFC[] = { D_090014F0_3A2250 }
Referenced by radiating_energy_orb_appendGfx().