papermario: src/effects/red_impact.c File Reference
red_impact.c File Reference
Functions
void red_impact_init (EffectInstance *effect)
void red_impact_update (EffectInstance *effect)
void red_impact_render (EffectInstance *effect)
void red_impact_appendGfx (void *effect)
EffectInstance * red_impact_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09000940_359CF0 []
Gfx D_090009A0_359D50 []
Gfx * D_E00D0B10 [] = { D_090009A0_359D50, D_090009A0_359D50 }
Function Documentation
red_impact_appendGfx()
void red_impact_appendGfx (void * effect)
Referenced by red_impact_render().
red_impact_init()
void red_impact_init (EffectInstance * effect)
Referenced by red_impact_main().
red_impact_main()
EffectInstance * red_impact_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
red_impact_render()
void red_impact_render (EffectInstance * effect)
Referenced by red_impact_main().
red_impact_update()
void red_impact_update (EffectInstance * effect)
Referenced by red_impact_main().
Variable Documentation
D_09000940_359CF0
Gfx D_09000940_359CF0[] extern
Referenced by red_impact_appendGfx().
D_090009A0_359D50
Gfx D_090009A0_359D50[] extern
D_E00D0B10
Gfx* D_E00D0B10[] = { D_090009A0_359D50, D_090009A0_359D50 }
Referenced by red_impact_appendGfx().