papermario: src/world/area_pra/common/Reflection.inc.c File Reference
Reflection.inc.c File Reference
Enumerations
enum ReflectMode { REFLECTION_FLOOR_WALL = 0 , REFLECTION_FLOOR_ONLY = 1 , REFLECTION_WALL_ONLY = 2 }
This include provides functions and scripts for setting up mirror reflections for the player and partner, used in Crystal Palace (area_pra).
Functions
void N worker_reflect_player_wall (void)
void N worker_reflect_player_floor (void)
void N appendGfx_reflect_player_wall (PlayerStatus *playerStatus)
void N appendGfx_reflect_player_floor_fancy (PlayerStatus *playerStatus)
void N appendGfx_reflect_player_floor_basic (PlayerStatus *playerStatus)
void N worker_reflect_partner_all (void)
void N worker_reflect_partner_floor (void)
void N worker_reflect_partner_wall (void)
s32 N reflection_unk_resolve_anim (s32 playerAnim)
s32 N reflection_unk_change_anim_facing (s32 playerAnim)
Enumeration Type Documentation
ReflectMode
enum ReflectMode
This include provides functions and scripts for setting up mirror reflections for the player and partner, used in Crystal Palace (area_pra).
See also tst_11, which has a more primitive reflection implementation.
Enumerator
REFLECTION_FLOOR_WALL
REFLECTION_FLOOR_ONLY
REFLECTION_WALL_ONLY
Function Documentation
appendGfx_reflect_player_floor_basic()
void N appendGfx_reflect_player_floor_basic (PlayerStatus * playerStatus)
Referenced by worker_reflect_player_floor().
appendGfx_reflect_player_floor_fancy()
void N appendGfx_reflect_player_floor_fancy (PlayerStatus * playerStatus)
Referenced by worker_reflect_player_floor().
appendGfx_reflect_player_wall()
void N appendGfx_reflect_player_wall (PlayerStatus * playerStatus)
Referenced by worker_reflect_player_wall().
reflection_unk_change_anim_facing()
s32 N reflection_unk_change_anim_facing (s32 playerAnim)
Referenced by worker_reflect_player_wall().
reflection_unk_resolve_anim()
s32 N reflection_unk_resolve_anim (s32 playerAnim)
Referenced by worker_reflect_player_wall().
worker_reflect_partner_all()
void N worker_reflect_partner_all (void)
worker_reflect_partner_floor()
void N worker_reflect_partner_floor (void)
worker_reflect_partner_wall()
void N worker_reflect_partner_wall (void)
worker_reflect_player_floor()
void N worker_reflect_player_floor (void)
worker_reflect_player_wall()
void N worker_reflect_player_wall (void)