papermario: src/effects/ring_blast.c File Reference
ring_blast.c File Reference
Functions
void ring_blast_init (EffectInstance *effect)
void ring_blast_update (EffectInstance *effect)
void ring_blast_render (EffectInstance *effect)
void ring_blast_appendGfx (void *effect)
void ring_blast_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 arg5)
Variables
Gfx D_09001040_3583E0 []
Gfx D_090010F8_358498 []
Gfx * D_E0048A00 [] = { D_090010F8_358498, D_090010F8_358498 }
Gfx * D_E0048A08 [] = { D_09001040_3583E0, D_09001040_3583E0 }
Function Documentation
ring_blast_appendGfx()
void ring_blast_appendGfx (void * effect)
Referenced by ring_blast_render().
ring_blast_init()
void ring_blast_init (EffectInstance * effect)
Referenced by ring_blast_main().
ring_blast_main()
void ring_blast_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 arg5)
Referenced by spirit_card_main().
ring_blast_render()
void ring_blast_render (EffectInstance * effect)
Referenced by ring_blast_main().
ring_blast_update()
void ring_blast_update (EffectInstance * effect)
Referenced by ring_blast_main().
Variable Documentation
D_09001040_3583E0
Gfx D_09001040_3583E0[] extern
D_090010F8_358498
Gfx D_090010F8_358498[] extern
D_E0048A00
Gfx* D_E0048A00[] = { D_090010F8_358498, D_090010F8_358498 }
Referenced by ring_blast_appendGfx().
D_E0048A08
Gfx* D_E0048A08[] = { D_09001040_3583E0, D_09001040_3583E0 }
Referenced by ring_blast_appendGfx().