papermario: src/effects/rising_bubble.c File Reference
rising_bubble.c File Reference
Functions
void rising_bubble_init (EffectInstance *effect)
void rising_bubble_update (EffectInstance *effect)
void rising_bubble_render (EffectInstance *effect)
void rising_bubble_appendGfx (void *effect)
void rising_bubble_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4)
Variables
Gfx D_09000200_356730 []
Gfx D_090002E8_356818 []
Gfx D_09000308_356838 []
Gfx D_090003F0_356920 []
Gfx D_09000410_356940 []
Gfx D_09000430_356960 []
Gfx * D_E0046600 [] = { D_090002E8_356818 }
Gfx * D_E0046604 []
Gfx * D_E0046614 [] = { D_09000200_356730 }
Gfx * D_E0046618 [] = { D_09000308_356838 }
Function Documentation
rising_bubble_appendGfx()
void rising_bubble_appendGfx (void * effect)
Referenced by rising_bubble_render().
rising_bubble_init()
void rising_bubble_init (EffectInstance * effect)
Referenced by rising_bubble_main().
rising_bubble_main()
void rising_bubble_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4)
rising_bubble_render()
void rising_bubble_render (EffectInstance * effect)
Referenced by rising_bubble_main().
rising_bubble_update()
void rising_bubble_update (EffectInstance * effect)
Referenced by rising_bubble_main().
Variable Documentation
D_09000200_356730
Gfx D_09000200_356730[] extern
D_090002E8_356818
Gfx D_090002E8_356818[] extern
D_09000308_356838
Gfx D_09000308_356838[] extern
D_090003F0_356920
Gfx D_090003F0_356920[] extern
D_09000410_356940
Gfx D_09000410_356940[] extern
D_09000430_356960
Gfx D_09000430_356960[] extern
D_E0046600
Gfx* D_E0046600[] = { D_090002E8_356818 }
Referenced by rising_bubble_appendGfx().
D_E0046604
Gfx* D_E0046604[]
Initial value:
= {
    D_090003F0_356920, D_09000410_356940, D_090003F0_356920, D_09000430_356960
}
Referenced by rising_bubble_appendGfx().
D_E0046614
Gfx* D_E0046614[] = { D_09000200_356730 }
Referenced by rising_bubble_appendGfx().
D_E0046618
Gfx* D_E0046618[] = { D_09000308_356838 }
Referenced by rising_bubble_appendGfx().