papermario: src/rumble.c File Reference
rumble.c File Reference
Functions
void poll_rumble (void)
void start_rumble (s32 freq, s32 nframes)
void update_max_rumble_duration (void)
void reset_max_rumble_duration (void)
Variables
u16 rumbleMaxDuration = 0
s32 rumbleButtons = 0
Function Documentation
poll_rumble()
void poll_rumble (void)
Referenced by load_engine_data().
reset_max_rumble_duration()
void reset_max_rumble_duration (void)
Referenced by load_map_by_IDs(), and update_max_rumble_duration().
start_rumble()
void start_rumble (s32 freq, s32 nframes)
Referenced by action_hammer_play_hit_fx(), action_update_hit_lava(), action_update_spin_jump(), action_update_tornado_jump(), and entity_CymbalPlant_idle().
update_max_rumble_duration()
void update_max_rumble_duration (void)
Referenced by step_game_loop().
Variable Documentation
rumbleButtons
s32 rumbleButtons = 0
Referenced by update_max_rumble_duration().
rumbleMaxDuration
u16 rumbleMaxDuration = 0
Referenced by reset_max_rumble_duration(), start_rumble(), and update_max_rumble_duration().