papermario: src/entity/sbk_omo/Tweester.c File Reference
Tweester.c File Reference
Functions
void entity_Tweester_render_inner_whirl (s32 entityIndex)
void entity_Tweester_render_outer_whirl (s32 entityIndex)
void entity_Tweester_render_face (s32 entityIndex)
void entity_Tweester_setupGfx (s32 entityIndex)
void entity_Tweester_update_face_anim (Entity *entity)
s32 entity_Tweester_has_reached_target (Entity *entity)
void entity_Tweester_select_target_point (Entity *entity)
void entity_Tweester_move (Entity *entity)
void entity_Tweester_idle (Entity *entity)
void entity_Tweester_anim_scale (Entity *entity)
void entity_Tweester_init (Entity *entity)
Variables
u8 Entity_Tweester_FaceAnimationData []
unsigned char D_0A000BF0_E57A50 []
unsigned char D_0A000FF0_E57E50 []
unsigned char D_0A0018A0_E58700 []
unsigned char D_0A0014A0_E58300 []
Mtx Entity_Tweester_mtxInnerWhirl
Mtx Entity_Tweester_mtxOuterWhirl
Gfx Entity_Tweester_RenderInnerWhirl []
Gfx Entity_Tweester_RenderOuterWhirl []
Gfx Entity_Tweester_Render []
EntityScript Entity_Tweester_Script
EntityModelScript Entity_Tweester_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Tweester_Render, RENDER_MODE_SURFACE_XLU_LAYER1)
EntityBlueprint Entity_Tweester
Function Documentation
entity_Tweester_anim_scale()
void entity_Tweester_anim_scale (Entity * entity)
entity_Tweester_has_reached_target()
s32 entity_Tweester_has_reached_target (Entity * entity)
Referenced by entity_Tweester_move().
entity_Tweester_idle()
void entity_Tweester_idle (Entity * entity)
entity_Tweester_init()
void entity_Tweester_init (Entity * entity)
entity_Tweester_move()
void entity_Tweester_move (Entity * entity)
Referenced by entity_Tweester_idle().
entity_Tweester_render_face()
void entity_Tweester_render_face (s32 entityIndex)
Referenced by entity_Tweester_setupGfx().
entity_Tweester_render_inner_whirl()
void entity_Tweester_render_inner_whirl (s32 entityIndex)
Referenced by entity_Tweester_setupGfx().
entity_Tweester_render_outer_whirl()
void entity_Tweester_render_outer_whirl (s32 entityIndex)
Referenced by entity_Tweester_setupGfx().
entity_Tweester_select_target_point()
void entity_Tweester_select_target_point (Entity * entity)
Referenced by entity_Tweester_init(), and entity_Tweester_move().
entity_Tweester_setupGfx()
void entity_Tweester_setupGfx (s32 entityIndex)
Referenced by entity_Tweester_init().
entity_Tweester_update_face_anim()
void entity_Tweester_update_face_anim (Entity * entity)
Referenced by entity_Tweester_idle().
Variable Documentation
D_0A000BF0_E57A50
unsigned char D_0A000BF0_E57A50[] extern
Referenced by entity_Tweester_setupGfx().
D_0A000FF0_E57E50
unsigned char D_0A000FF0_E57E50[] extern
Referenced by entity_Tweester_setupGfx().
D_0A0014A0_E58300
unsigned char D_0A0014A0_E58300[] extern
Referenced by entity_Tweester_render_face().
D_0A0018A0_E58700
unsigned char D_0A0018A0_E58700[] extern
Referenced by entity_Tweester_render_face().
Entity_Tweester
EntityBlueprint Entity_Tweester
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION,
    .typeDataSize = sizeof(TweesterData),
    .renderCommandList = Entity_Tweester_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_Tweester_init,
    .updateEntityScript = Entity_Tweester_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(Tweester) },
    .entityType = ENTITY_TYPE_TWEESTER,
    .aabbSize = { 50, 70, 50 }
}
Entity_Tweester_FaceAnimationData
u8 Entity_Tweester_FaceAnimationData[]
Initial value:
= {
      0,  2,
     32,  2,
      0,  3,
     32,  2,
      0, 80,
    255,  0
}
Referenced by entity_Tweester_update_face_anim().
Entity_Tweester_mtxInnerWhirl
Mtx Entity_Tweester_mtxInnerWhirl extern
Referenced by entity_Tweester_render_inner_whirl().
Entity_Tweester_mtxOuterWhirl
Mtx Entity_Tweester_mtxOuterWhirl extern
Referenced by entity_Tweester_render_outer_whirl().
Entity_Tweester_Render
Gfx Entity_Tweester_Render[] extern
Entity_Tweester_RenderInnerWhirl
Gfx Entity_Tweester_RenderInnerWhirl[] extern
Referenced by entity_Tweester_render_inner_whirl().
Entity_Tweester_RenderOuterWhirl
Gfx Entity_Tweester_RenderOuterWhirl[] extern
Referenced by entity_Tweester_render_outer_whirl().
Entity_Tweester_RenderScript
EntityModelScript Entity_Tweester_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_Tweester_Render, RENDER_MODE_SURFACE_XLU_LAYER1)
Entity_Tweester_Script
EntityScript Entity_Tweester_Script
Initial value:
={
    es_SetCallback(entity_Tweester_anim_scale, 20)
    es_SetCallback(entity_Tweester_idle, 0)
    es_End
}