papermario: src/screen_overlays.c File Reference
screen_overlays.c File Reference
Enumerations
enum ScreenFadeRates {
VERY_SLOW_FADE_RATE = 2 , SLOW_FADE_RATE = 7 , SLOWER_FADE_RATE = 10 , STANDARD_FADE_RATE = 20 ,
FAST_FADE_RATE = 50
}
Functions
INCLUDE_IMG ("ui/stencil/star.png", ui_stencil_star_png)
INCLUDE_IMG ("ui/stencil/mario.png", ui_stencil_mario_png)
INCLUDE_IMG ("ui/stencil/sharp_circle.png", ui_stencil_sharp_circle_png)
INCLUDE_IMG ("ui/stencil/blurry_circle.png", ui_stencil_blurry_circle_png)
void _render_transition_stencil (u8 stencilType, f32 progress, ScreenOverlay *overlay)
void set_screen_overlay_params_front (u8 type, f32 zoom)
void set_screen_overlay_params_back (u8 type, f32 zoom)
void get_screen_overlay_params (s32 layer, u8 *type, f32 *zoom)
void set_screen_overlay_color (s32 layer, u8 r, u8 g, u8 b)
void set_screen_overlay_center (s32 layer, s32 arg1, s32 screenPosX, s32 screenPosY)
void set_screen_overlay_center_worldpos (s32 layer, s32 posIdx, s32 worldPosX, s32 worldPosY, s32 worldPosZ)
void set_screen_overlay_alpha (s32 layer, f32 alpha)
void clear_screen_overlays (void)
void func_80138188 (void)
void func_80138198 (void)
void render_screen_overlay_frontUI (void)
void render_screen_overlay_backUI (void)
void set_map_transition_effect (ScreenTransition transition)
s16 update_exit_map_screen_overlay (s16 *progress)
s16 update_enter_map_screen_overlay (s16 *progress)
Variables
BSS s32 screen_overlay_frontType
BSS f32 screen_overlay_frontZoom
BSS s32 screen_overlay_backType
BSS f32 screen_overlay_backZoom
BSS s32 D_80156910
ScreenOverlay ScreenOverlays [2]
ScreenTransition CurrentScreenTransition = TRANSITION_END_DEMO_SCENE_BLACK
s32 D_8014C6F4 [] = { 0x00000000, 0x00000000, 0x00000000 }
Gfx Gfx_LoadStencilTex_CommonParams []
Gfx Gfx_LoadStencilTex_SharpCircle []
Gfx Gfx_LoadStencilTex_Mario []
Gfx Gfx_LoadStencilTex_Star []
Gfx Gfx_LoadStencilTex_BlurryCircle []
Gfx D_8014E8F0 []
Gfx D_8014E9A8 []
Gfx D_8014EA48 []
Enumeration Type Documentation
ScreenFadeRates
enum ScreenFadeRates
Enumerator
VERY_SLOW_FADE_RATE
SLOW_FADE_RATE
SLOWER_FADE_RATE
STANDARD_FADE_RATE
FAST_FADE_RATE
Function Documentation
_render_transition_stencil()
void _render_transition_stencil (u8 stencilType, f32 progress, ScreenOverlay * overlay)
Referenced by gfx_draw_frame(), render_screen_overlay_backUI(), and render_screen_overlay_frontUI().
clear_screen_overlays()
void clear_screen_overlays (void)
Referenced by load_engine_data(), state_step_demo(), state_step_intro(), and state_step_startup().
func_80138188()
void func_80138188 (void)
Referenced by load_demo_battle(), and load_map_by_IDs().
func_80138198()
void func_80138198 (void)
Referenced by step_game_loop().
get_screen_overlay_params()
void get_screen_overlay_params (s32 layer, u8 * type, f32 * zoom)
Referenced by appendGfx_image_strips(), btl_update(), create_target_list(), UpdateIntroMessages(), and worker_draw_story_graphics().
INCLUDE_IMG() [1/4]
INCLUDE_IMG ("ui/stencil/blurry_circle.png" , ui_stencil_blurry_circle_png)
INCLUDE_IMG() [2/4]
INCLUDE_IMG ("ui/stencil/mario.png" , ui_stencil_mario_png)
INCLUDE_IMG() [3/4]
INCLUDE_IMG ("ui/stencil/sharp_circle.png" , ui_stencil_sharp_circle_png)
INCLUDE_IMG() [4/4]
INCLUDE_IMG ("ui/stencil/star.png" , ui_stencil_star_png)
render_screen_overlay_backUI()
void render_screen_overlay_backUI (void)
Referenced by gfx_draw_frame().
render_screen_overlay_frontUI()
void render_screen_overlay_frontUI (void)
Referenced by gfx_draw_frame().
set_map_transition_effect()
void set_map_transition_effect (ScreenTransition transition)
Referenced by goto_map(), state_init_demo(), state_init_enter_world(), state_init_exit_file_select(), and state_step_demo().
set_screen_overlay_alpha()
void set_screen_overlay_alpha (s32 layer, f32 alpha)
Referenced by draw_encounters_pre_battle(), and update_exit_map_screen_overlay().
set_screen_overlay_center()
void set_screen_overlay_center (s32 layer, s32 arg1, s32 screenPosX, s32 screenPosY)
Referenced by btl_state_update_end_battle(), draw_encounters_pre_battle(), update_enter_map_screen_overlay(), and update_exit_map_screen_overlay().
set_screen_overlay_center_worldpos()
void set_screen_overlay_center_worldpos (s32 layer, s32 posIdx, s32 worldPosX, s32 worldPosY, s32 worldPosZ)
set_screen_overlay_color()
void set_screen_overlay_color (s32 layer, u8 r, u8 g, u8 b)
Referenced by btl_state_draw_end_demo_battle(), btl_state_draw_normal_start(), btl_state_update_end_battle(), btl_state_update_normal_start(), btl_update(), draw_encounters_post_battle(), draw_encounters_pre_battle(), startup_fade_screen_update(), state_init_intro(), state_step_intro(), update_enter_map_screen_overlay(), and update_exit_map_screen_overlay().
set_screen_overlay_params_back()
void set_screen_overlay_params_back (u8 type, f32 zoom)
Referenced by btl_state_update_normal_start(), btl_update(), draw_encounters_pre_battle(), state_init_intro(), state_step_intro(), and update_exit_map_screen_overlay().
set_screen_overlay_params_front()
void set_screen_overlay_params_front (u8 type, f32 zoom)
Referenced by btl_state_draw_celebration(), btl_state_draw_end_battle(), btl_state_draw_end_demo_battle(), btl_state_draw_enemy_striking_first(), btl_state_draw_first_stike(), btl_state_draw_normal_start(), btl_state_draw_partner_striking_first(), btl_state_update_normal_start(), btl_update(), draw_encounters_post_battle(), draw_encounters_pre_battle(), load_demo_battle(), startup_fade_screen_update(), state_init_demo(), state_init_exit_language_select(), state_init_language_select(), state_step_change_map(), state_step_enter_world(), state_step_exit_language_select(), state_step_game_over(), state_step_intro(), state_step_language_select(), update_encounters_post_battle(), update_encounters_pre_battle(), update_enter_map_screen_overlay(), and update_exit_map_screen_overlay().
update_enter_map_screen_overlay()
s16 update_enter_map_screen_overlay (s16 * progress)
Referenced by state_step_change_map(), and state_step_enter_world().
update_exit_map_screen_overlay()
s16 update_exit_map_screen_overlay (s16 * progress)
Referenced by init_enter_world_shared(), state_step_change_map(), and state_step_exit_file_select().
Variable Documentation
CurrentScreenTransition
ScreenTransition CurrentScreenTransition = TRANSITION_END_DEMO_SCENE_BLACK
Referenced by set_map_transition_effect(), update_enter_map_screen_overlay(), and update_exit_map_screen_overlay().
D_8014C6F4
s32 D_8014C6F4[] = { 0x00000000, 0x00000000, 0x00000000 }
D_8014E8F0
Gfx D_8014E8F0[]
Initial value:
= {
    gsSPTexture(0x8000, 0x8000, 0, G_TX_RENDERTILE, G_OFF),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetDepthSource(G_ZS_PRIM),
    gsDPSetPrimDepth(0, 0),
    gsDPSetRenderMode(Z_UPD | IM_RD | CVG_DST_SAVE | ZMODE_OPA | FORCE_BL | GBL_c1(G_BL_CLR_MEM, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA), Z_UPD | IM_RD | CVG_DST_SAVE | ZMODE_OPA | FORCE_BL | GBL_c2(G_BL_CLR_MEM, G_BL_A_IN, G_BL_CLR_MEM, G_BL_1MA)),
    gsDPSetCombineMode(PM_CC_SCREEN_OVERLAY, PM_CC_SCREEN_OVERLAY),
    gsDPSetTexturePersp(G_TP_PERSP),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPSetTextureConvert(G_TC_FILT),
    gsSPClearGeometryMode(G_CULL_BOTH | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BACK),
    gsSPVertex(&vtx_stencil1, 10, 0),
    gsSP2Triangles(0, 1, 2, 0, 3, 0, 2, 0),
    gsSP2Triangles(0, 4, 1, 0, 3, 5, 0, 0),
    gsSP2Triangles(1, 6, 2, 0, 7, 3, 2, 0),
    gsSP2Triangles(8, 7, 2, 0, 7, 9, 3, 0),
    gsDPPipeSync(),
    gsDPSetDepthSource(G_ZS_PIXEL),
    gsSPEndDisplayList()
}
Referenced by _render_transition_stencil().
D_8014E9A8
Gfx D_8014E9A8[]
Initial value:
= {
    gsDPPipeSync(),
    gsDPSetDepthSource(G_ZS_PRIM),
    gsDPSetPrimDepth(20, 0),
    gsDPSetRenderMode(G_RM_ZB_XLU_SURF, G_RM_ZB_XLU_SURF2),
    gsDPSetCombineMode(PM_CC_SCREEN_OVERLAY, PM_CC_SCREEN_OVERLAY),
    gsSPClearGeometryMode(G_CULL_BOTH | G_LIGHTING | G_SHADING_SMOOTH),
    gsSPSetGeometryMode(G_ZBUFFER | G_SHADE),
    gsDPSetColorDither(G_CD_MAGICSQ),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPFillRectangle(0, 0, 320, 240),
    gsDPSetColorDither(G_CD_DISABLE),
    gsDPPipeSync(),
    gsDPSetDepthSource(G_ZS_PIXEL),
    gsSPEndDisplayList()
}
Referenced by _render_transition_stencil().
D_8014EA48
Gfx D_8014EA48[]
Referenced by _render_transition_stencil().
D_80156910
BSS s32 D_80156910
Gfx_LoadStencilTex_BlurryCircle
Gfx Gfx_LoadStencilTex_BlurryCircle[]
Initial value:
= {
    gsSPDisplayList(Gfx_LoadStencilTex_CommonParams),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPSetTextureImage(G_IM_FMT_I, G_IM_SIZ_8b, 64, ui_stencil_blurry_circle_png),
    gsDPSetTile(G_IM_FMT_I, G_IM_SIZ_8b, 8, 0x0000, G_TX_LOADTILE, 0, G_TX_MIRROR | G_TX_CLAMP, 6, G_TX_NOLOD, G_TX_MIRROR | G_TX_CLAMP, 6, G_TX_NOLOD),
    gsDPLoadSync(),
    gsDPLoadTile(G_TX_LOADTILE, 0, 0, 0x00FC, 0x00FC),
    gsDPPipeSync(),
    gsDPSetTile(G_IM_FMT_I, G_IM_SIZ_8b, 8, 0x0000, G_TX_RENDERTILE, 0, G_TX_MIRROR | G_TX_CLAMP, 6, G_TX_NOLOD, G_TX_MIRROR | G_TX_CLAMP, 6, G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x00FC, 0x00FC),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x01FC, 0x01FC),
    gsSPEndDisplayList()
}
Referenced by _render_transition_stencil().
Gfx_LoadStencilTex_CommonParams
Gfx Gfx_LoadStencilTex_CommonParams[]
Initial value:
= {
    gsSPTexture(0xFFFF, 0xFFFF, 0, G_TX_RENDERTILE, G_ON),
    gsDPPipeSync(),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetTextureDetail(G_TD_CLAMP),
    gsDPSetTextureLOD(G_TL_TILE),
    gsDPSetTextureFilter(G_TF_AVERAGE),
    gsDPSetTextureConvert(G_TC_FILT),
    gsDPSetTexturePersp(G_TP_NONE),
    gsDPSetColorDither(G_CD_MAGICSQ),
    gsDPSetAlphaDither(G_AD_PATTERN),
    gsDPSetCombineMode(PM_CC_3A, PM_CC_3A),
    gsDPSetRenderMode(G_RM_CLD_SURF, G_RM_CLD_SURF2),
    gsSPClearGeometryMode(G_ZBUFFER | G_SHADE | G_CULL_BOTH | G_FOG | G_LIGHTING | G_TEXTURE_GEN | G_TEXTURE_GEN_LINEAR | G_LOD | G_SHADING_SMOOTH | G_CLIPPING | 0x0040F9FA),
    gsSPSetGeometryMode(G_SHADE | G_SHADING_SMOOTH),
    gsSPEndDisplayList()
}
Gfx_LoadStencilTex_Mario
Gfx Gfx_LoadStencilTex_Mario[]
Initial value:
= {
    gsSPDisplayList(Gfx_LoadStencilTex_CommonParams),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureTile_4b(ui_stencil_mario_png, G_IM_FMT_I, 64, 0, 0, 0, 63, 63, 0, G_TX_NOMIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 6, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsSPEndDisplayList()
}
Referenced by _render_transition_stencil().
Gfx_LoadStencilTex_SharpCircle
Gfx Gfx_LoadStencilTex_SharpCircle[]
Initial value:
= {
    gsSPDisplayList(Gfx_LoadStencilTex_CommonParams),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureTile_4b(ui_stencil_sharp_circle_png, G_IM_FMT_I, 32, 0, 0, 0, 31, 31, 0, G_TX_MIRROR | G_TX_CLAMP, G_TX_MIRROR | G_TX_CLAMP, 5, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x00FC, 0x00FC),
    gsSPEndDisplayList()
}
Referenced by _render_transition_stencil().
Gfx_LoadStencilTex_Star
Gfx Gfx_LoadStencilTex_Star[]
Initial value:
= {
    gsSPDisplayList(Gfx_LoadStencilTex_CommonParams),
    gsDPSetTextureLUT(G_TT_NONE),
    gsDPLoadTextureTile_4b(ui_stencil_star_png, G_IM_FMT_I, 32, 0, 0, 0, 31, 63, 0, G_TX_MIRROR | G_TX_CLAMP, G_TX_NOMIRROR | G_TX_CLAMP, 5, 6, G_TX_NOLOD, G_TX_NOLOD),
    gsDPSetTileSize(G_TX_RENDERTILE, 0, 0, 0x00FC, 0x00FC),
    gsSPEndDisplayList(),
}
Referenced by _render_transition_stencil().
screen_overlay_backType
BSS s32 screen_overlay_backType
Referenced by clear_screen_overlays(), get_screen_overlay_params(), render_screen_overlay_backUI(), and set_screen_overlay_params_back().
screen_overlay_backZoom
BSS f32 screen_overlay_backZoom
Referenced by clear_screen_overlays(), func_80138188(), get_screen_overlay_params(), render_screen_overlay_backUI(), and set_screen_overlay_params_back().
screen_overlay_frontType
BSS s32 screen_overlay_frontType
Referenced by clear_screen_overlays(), get_screen_overlay_params(), render_screen_overlay_frontUI(), and set_screen_overlay_params_front().
screen_overlay_frontZoom
BSS f32 screen_overlay_frontZoom
Referenced by clear_screen_overlays(), get_screen_overlay_params(), render_screen_overlay_frontUI(), and set_screen_overlay_params_front().
ScreenOverlays
ScreenOverlay ScreenOverlays[2]
Referenced by clear_screen_overlays(), render_screen_overlay_backUI(), render_screen_overlay_frontUI(), set_screen_overlay_alpha(), set_screen_overlay_center(), set_screen_overlay_center_worldpos(), and set_screen_overlay_color().