papermario: src/screen_render_util.c File Reference
screen_render_util.c File Reference
Functions
void appendGfx_draw_prev_frame_buffer (s32 x1, s32 y1, s32 x2, s32 y2, f32 alpha)
void draw_prev_frame_buffer_at_screen_pos (s32 x1, s32 y1, s32 x2, s32 y2, f32 alpha)
void appendGfx_darkness_stencil (b32 isWorld, s32 posX, s32 posY, f32 alpha, f32 progress)
void appendGfx_screen_transition_stencil (s32 arg0, s32 arg1, f32 progress, s32 primR, s32 primG, s32 primB, s32 primA, s32 camID)
Variables
Gfx D_8014ED90 []
Vp DarknessStencilViewport
Vtx Vtx_DarknessStencil []
Gfx Gfx_DarknessStencilQuad []
Function Documentation
appendGfx_darkness_stencil()
void appendGfx_darkness_stencil (b32 isWorld, s32 posX, s32 posY, f32 alpha, f32 progress)
Referenced by _render_transition_stencil().
appendGfx_draw_prev_frame_buffer()
void appendGfx_draw_prev_frame_buffer (s32 x1, s32 y1, s32 x2, s32 y2, f32 alpha)
Referenced by draw_prev_frame_buffer_at_screen_pos().
appendGfx_screen_transition_stencil()
void appendGfx_screen_transition_stencil (s32 arg0, s32 arg1, f32 progress, s32 primR, s32 primG, s32 primB, s32 primA, s32 camID)
Referenced by _render_transition_stencil().
draw_prev_frame_buffer_at_screen_pos()
void draw_prev_frame_buffer_at_screen_pos (s32 x1, s32 y1, s32 x2, s32 y2, f32 alpha)
Variable Documentation
D_8014ED90
Gfx D_8014ED90[]
Initial value:
= {
    gsSPEndDisplayList(),
}
DarknessStencilViewport
Vp DarknessStencilViewport
Initial value:
= {
    .vp = {
        .vscale = { 128, 128, 511, 0 },
        .vtrans = { 128, 128, 511, 0 }
    }
}
Referenced by appendGfx_darkness_stencil().
Gfx_DarknessStencilQuad
Gfx Gfx_DarknessStencilQuad[]
Initial value:
= {
    gsSPVertex(Vtx_DarknessStencil, 4, 0),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsDPPipeSync(),
    gsSPEndDisplayList(),
}
Referenced by appendGfx_darkness_stencil().
Vtx_DarknessStencil
Vtx Vtx_DarknessStencil[]
Initial value:
= {
    {{{ -16,-16, 0 }, 0, { 0x0000, 0x0000 }, { 0, 0, 0, 255 }}},
    {{{  16,-16, 0 }, 0, { 0x1000, 0x0000 }, { 0, 0, 0, 255 }}},
    {{{  16, 16, 0 }, 0, { 0x1000, 0x1000 }, { 0, 0, 0, 255 }}},
    {{{ -16, 16, 0 }, 0, { 0x0000, 0x1000 }, { 0, 0, 0, 255 }}},
}