papermario: include/script_api/common.h File Reference
common.h File Reference
EVT scripting API functions available at all times.
See also
script_api/battle.h script_api/map.h
Functions
Map
ApiStatus TranslateModel (Evt *script, bool isInitialCall)
ApiStatus RotateModel (Evt *script, bool isInitialCall)
ApiStatus ScaleModel (Evt *script, bool isInitialCall)
ApiStatus GetModelIndex (Evt *script, bool isInitialCall)
ApiStatus InvalidateModelTransform (Evt *script, bool isInitialCall)
ApiStatus CloneModel (Evt *script, bool isInitialCall)
ApiStatus GetModelCenter (Evt *script, bool isInitialCall)
ApiStatus SetTexPanner (Evt *script, bool isInitialCall)
ApiStatus SetCustomGfxEnabled (Evt *script, bool isInitialCall)
ApiStatus SetModelCustomGfx (Evt *script, bool isInitialCall)
ApiStatus SetModelTexVariant (Evt *script, bool isInitialCall)
ApiStatus EnableTexPanning (Evt *script, bool isInitialCall)
ApiStatus EnableModel (Evt *script, bool isInitialCall)
ApiStatus SetGroupVisibility (Evt *script, bool isInitialCall)
ApiStatus SetTexPanOffset (Evt *script, bool isInitialCall)
ApiStatus SetCustomGfx (Evt *script, bool isInitialCall)
ApiStatus SetCustomGfxBuilders (Evt *script, bool isInitialCall)
ApiStatus SetModelFlags (Evt *script, bool isInitialCall)
ApiStatus MakeTransformGroup (Evt *script, bool isInitialCall)
ApiStatus SetTransformGroupEnabled (Evt *script, bool isInitialCall)
ApiStatus TranslateGroup (Evt *script, bool isInitialCall)
ApiStatus RotateGroup (Evt *script, bool isInitialCall)
ApiStatus ScaleGroup (Evt *script, bool isInitialCall)
ApiStatus GetTransformGroup (Evt *script, bool isInitialCall)
ApiStatus EnableGroup (Evt *script, bool isInitialCall)
ApiStatus MakeLocalVertexCopy (Evt *script, bool isInitialCall)
ApiStatus ModifyColliderFlags (Evt *script, bool isInitialCall)
ApiStatus ResetFromLava (Evt *script, bool isInitialCall)
ApiStatus GetColliderCenter (Evt *script, bool isInitialCall)
ApiStatus ParentColliderToModel (Evt *script, bool isInitialCall)
ApiStatus UpdateColliderTransform (Evt *script, bool isInitialCall)
ApiStatus SetZoneEnabled (Evt *script, bool isInitialCall)
ApiStatus GotoMap (Evt *script, bool isInitialCall)
ApiStatus GotoMapSpecial (Evt *script, bool isInitialCall)
ApiStatus GotoMapByID (Evt *script, bool isInitialCall)
ApiStatus GetEntryID (Evt *script, bool isInitialCall)
ApiStatus GetMapID (Evt *script, bool isInitialCall)
ApiStatus GetLoadType (Evt *script, bool isInitialCall)
ApiStatus SetRenderMode (Evt *script, bool isInitialCall)
ApiStatus PlaySoundAtModel (Evt *script, bool isInitialCall)
ApiStatus PlaySoundAtCollider (Evt *script, bool isInitialCall)
Animated Model
ApiStatus InitAnimatedModels (Evt *script, bool isInitialCall)
ApiStatus LoadAnimatedModel (Evt *script, bool isInitialCall)
ApiStatus LoadAnimatedMesh (Evt *script, bool isInitialCall)
ApiStatus PlayModelAnimation (Evt *script, bool isInitialCall)
ApiStatus PlayModelAnimationStartingFrom (Evt *script, bool isInitialCall)
ApiStatus ChangeModelAnimation (Evt *script, bool isInitialCall)
ApiStatus SetAnimatedModelRootPosition (Evt *script, bool isInitialCall)
ApiStatus GetAnimatedModelRootPosition (Evt *script, bool isInitialCall)
ApiStatus AddAnimatedModelRootPosition (Evt *script, bool isInitialCall)
ApiStatus SetAnimatedModelRootRotation (Evt *script, bool isInitialCall)
ApiStatus SetAnimatedModelRootScale (Evt *script, bool isInitialCall)
ApiStatus SetAnimatedModelRenderMode (Evt *script, bool isInitialCall)
ApiStatus DeleteAnimatedModel (Evt *script, bool isInitialCall)
ApiStatus SetAnimatorFlags (Evt *script, bool isInitialCall)
ApiStatus GetAnimatedNodePosition (Evt *script, bool isInitialCall)
ApiStatus GetAnimatedNodeRotation (Evt *script, bool isInitialCall)
ApiStatus GetAnimatedPositionByTreeIndex (Evt *script, bool isInitialCall)
ApiStatus GetAnimatedRotationByTreeIndex (Evt *script, bool isInitialCall)
ApiStatus SetAnimatedNodeFlags (Evt *script, bool isInitialCall)
Camera
ApiStatus SetCamEnabled (Evt *script, bool isInitialCall)
ApiStatus SetCamNoDraw (Evt *script, bool isInitialCall)
ApiStatus SetCamPerspective (Evt *script, bool isInitialCall)
ApiStatus SetCamUpdateMode (Evt *script, bool isInitialCall)
ApiStatus GrabCamera (Evt *script, bool isInitialCall)
ApiStatus SetCamViewport (Evt *script, bool isInitialCall)
ApiStatus SetInterpCamParams (Evt *script, bool isInitialCall)
ApiStatus SetNoInterpCamParams (Evt *script, bool isInitialCall)
ApiStatus SetCamBGColor (Evt *script, bool isInitialCall)
ApiStatus SetCamLookTarget (Evt *script, bool isInitialCall)
ApiStatus SetCamTarget (Evt *script, bool isInitialCall)
ApiStatus InterpCamTargetPos (Evt *script, bool isInitialCall)
ApiStatus ShakeCam (Evt *script, bool isInitialCall)
ApiStatus SetCamLeadPlayer (Evt *script, bool isInitialCall)
ApiStatus func_802CB710 (Evt *script, bool isInitialCall)
ApiStatus PanToTarget (Evt *script, bool isInitialCall)
ApiStatus UseSettingsFrom (Evt *script, bool isInitialCall)
ApiStatus LoadSettings (Evt *script, bool isInitialCall)
ApiStatus SetCamType (Evt *script, bool isInitialCall)
ApiStatus SetCamPitch (Evt *script, bool isInitialCall)
ApiStatus SetCamDistance (Evt *script, bool isInitialCall)
ApiStatus SetCamPosA (Evt *script, bool isInitialCall)
ApiStatus SetCamPosB (Evt *script, bool isInitialCall)
ApiStatus SetCamPosC (Evt *script, bool isInitialCall)
ApiStatus SetPanTarget (Evt *script, bool isInitialCall)
ApiStatus SetCamSpeed (Evt *script, bool isInitialCall)
ApiStatus GetCamType (Evt *script, bool isInitialCall)
ApiStatus GetCamPitch (Evt *script, bool isInitialCall)
ApiStatus GetCamDistance (Evt *script, bool isInitialCall)
ApiStatus GetCamPosA (Evt *script, bool isInitialCall)
ApiStatus GetCamPosB (Evt *script, bool isInitialCall)
ApiStatus GetCamPosC (Evt *script, bool isInitialCall)
ApiStatus GetCamPosition (Evt *script, bool isInitialCall)
ApiStatus WaitForCam (Evt *script, bool isInitialCall)
ApiStatus SetCamProperties (Evt *script, bool isInitialCall)
ApiStatus AdjustCam (Evt *script, bool isInitialCall)
ApiStatus ResetCam (Evt *script, bool isInitialCall)
NPC
ApiStatus CreateNpc (Evt *script, bool isInitialCall)
ApiStatus DeleteNpc (Evt *script, bool isInitialCall)
ApiStatus GetNpcPointer (Evt *script, bool isInitialCall)
ApiStatus SetNpcPos (Evt *script, bool isInitialCall)
ApiStatus SetNpcRotation (Evt *script, bool isInitialCall)
ApiStatus SetNpcRotationPivot (Evt *script, bool isInitialCall)
ApiStatus SetNpcScale (Evt *script, bool isInitialCall)
ApiStatus SetNpcCollisionSize (Evt *script, bool isInitialCall)
ApiStatus SetNpcSpeed (Evt *script, bool isInitialCall)
ApiStatus SetNpcJumpscale (Evt *script, bool isInitialCall)
ApiStatus SetNpcAnimation (Evt *script, bool isInitialCall)
ApiStatus GetNpcAnimation (Evt *script, bool isInitialCall)
ApiStatus SetNpcAnimationSpeed (Evt *script, bool isInitialCall)
ApiStatus NpcMoveTo (Evt *script, bool isInitialCall)
ApiStatus NpcJump0 (Evt *script, bool isInitialCall)
ApiStatus NpcJump1 (Evt *script, bool isInitialCall)
ApiStatus NpcFlyTo (Evt *script, bool isInitialCall)
ApiStatus GetNpcYaw (Evt *script, bool isInitialCall)
ApiStatus SetNpcYaw (Evt *script, bool isInitialCall)
ApiStatus InterpNpcYaw (Evt *script, bool isInitialCall)
ApiStatus NpcFacePlayer (Evt *script, bool isInitialCall)
ApiStatus NpcFaceNpc (Evt *script, bool isInitialCall)
ApiStatus SetNpcFlagBits (Evt *script, bool isInitialCall)
ApiStatus GetNpcPos (Evt *script, bool isInitialCall)
ApiStatus SetNpcCollisionChannel (Evt *script, bool isInitialCall)
ApiStatus SetNpcSprite (Evt *script, bool isInitialCall)
ApiStatus EnableNpcShadow (Evt *script, bool isInitialCall)
ApiStatus EnableNpcBlur (Evt *script, bool isInitialCall)
ApiStatus ClearPartnerMoveHistory (Evt *script, bool isInitialCall)
ApiStatus NpcSetHomePosToCurrent (Evt *script, bool isInitialCall)
ApiStatus GetPartnerPos (Evt *script, bool isInitialCall)
ApiStatus DisablePartnerAI (Evt *script, bool isInitialCall)
ApiStatus EnablePartnerAI (Evt *script, bool isInitialCall)
ApiStatus func_802CF54C (Evt *script, bool isInitialCall)
ApiStatus func_802CF56C (Evt *script, bool isInitialCall)
ApiStatus BringPartnerOut (Evt *script, bool isInitialCall)
ApiStatus PutPartnerAway (Evt *script, bool isInitialCall)
ApiStatus GetCurrentPartnerID (Evt *script, bool isInitialCall)
ApiStatus PartnerCanUseAbility (Evt *script, bool isInitialCall)
ApiStatus PartnerIsFlying (Evt *script, bool isInitialCall)
ApiStatus SetNpcImgFXParams (Evt *script, bool isInitialCall)
ApiStatus SetNpcImgFXFlags (Evt *script, bool isInitialCall)
ApiStatus SetNpcPaletteSwapMode (Evt *script, bool isInitialCall)
ApiStatus SetNpcPaletteSwapLower (Evt *script, bool isInitialCall)
ApiStatus SetNpcPaletteSwapping (Evt *script, bool isInitialCall)
ApiStatus SetNpcDecoration (Evt *script, bool isInitialCall)
ApiStatus PlaySoundAtNpc (Evt *script, bool isInitialCall)
ApiStatus SetNpcRenderMode (Evt *script, bool isInitialCall)
Encounter
ApiStatus SetEncounterStatusFlags (Evt *script, bool isInitialCall)
ApiStatus IsStartingConversation (Evt *script, bool isInitialCall)
ApiStatus func_80044238 (Evt *script, bool isInitialCall)
ApiStatus LoadDemoBattle (Evt *script, bool isInitialCall)
ApiStatus func_80044290 (Evt *script, bool isInitialCall)
ApiStatus MakeNpcs (Evt *script, bool isInitialCall)
ApiStatus RemoveNpc (Evt *script, bool isInitialCall)
ApiStatus RemoveEncounter (Evt *script, bool isInitialCall)
ApiStatus GetBattleOutcome (Evt *script, bool isInitialCall)
ApiStatus func_800445A8 (Evt *script, bool isInitialCall)
ApiStatus func_800445D4 (Evt *script, bool isInitialCall)
ApiStatus GetOwnerEncounterTrigger (Evt *script, bool isInitialCall)
ApiStatus DoNpcDefeat (Evt *script, bool isInitialCall)
ApiStatus StartBattle (Evt *script, bool isInitialCall)
ApiStatus StartBattleWith (Evt *script, bool isInitialCall)
ApiStatus StartBossBattle (Evt *script, bool isInitialCall)
ApiStatus SetBattleMusic (Evt *script, bool isInitialCall)
ApiStatus BindNpcAI (Evt *script, bool isInitialCall)
ApiStatus BindNpcIdle (Evt *script, bool isInitialCall)
ApiStatus RestartNpcAI (Evt *script, bool isInitialCall)
ApiStatus EnableNpcAI (Evt *script, bool isInitialCall)
ApiStatus SetNpcAux (Evt *script, bool isInitialCall)
ApiStatus BindNpcAux (Evt *script, bool isInitialCall)
ApiStatus RestartNpcAux (Evt *script, bool isInitialCall)
ApiStatus EnableNpcAux (Evt *script, bool isInitialCall)
ApiStatus BindNpcInteract (Evt *script, bool isInitialCall)
ApiStatus BindNpcHit (Evt *script, bool isInitialCall)
ApiStatus BindNpcDefeat (Evt *script, bool isInitialCall)
ApiStatus SetSelfVar (Evt *script, bool isInitialCall)
ApiStatus GetSelfVar (Evt *script, bool isInitialCall)
ApiStatus SetNpcVar (Evt *script, bool isInitialCall)
ApiStatus GetNpcVar (Evt *script, bool isInitialCall)
ApiStatus SetSelfRotation (Evt *script, bool isInitialCall)
ApiStatus SetSelfEnemyFlags (Evt *script, bool isInitialCall)
ApiStatus SetSelfEnemyFlagBits (Evt *script, bool isInitialCall)
ApiStatus SelfEnemyOverrideSyncPos (Evt *script, bool isInitialCall)
ApiStatus GetSelfNpcID (Evt *script, bool isInitialCall)
ApiStatus ClearDefeatedEnemies (Evt *script, bool isInitialCall)
ApiStatus SetEnemyFlagBits (Evt *script, bool isInitialCall)
ApiStatus func_8004572C (Evt *script, bool isInitialCall)
ApiStatus GetSelfAnimationFromTable (Evt *script, bool isInitialCall)
ApiStatus func_80045798 (Evt *script, bool isInitialCall)
ApiStatus SetOwnerInstigatorValue (Evt *script, bool isInitialCall)
ApiStatus SetBattleAsScripted (Evt *script, bool isInitialCall)
ApiStatus GetEncounterTriggerHitTier (Evt *script, bool isInitialCall)
ApiStatus func_80045838 (Evt *script, bool isInitialCall)
ApiStatus func_800458CC (Evt *script, bool isInitialCall)
ApiStatus OnPlayerFled (Evt *script, bool isInitialCall)
ApiStatus SetTattleMessage (Evt *script, bool isInitialCall)
ApiStatus ShowMerleeCoinMessage (Evt *script, bool isInitialCall)
ApiStatus ShowMerleeRanOutMessage (Evt *script, bool isInitialCall)
ApiStatus FadeInMerlee (Evt *script, bool isInitialCall)
ApiStatus FadeOutMerlee (Evt *script, bool isInitialCall)
ApiStatus MerleeUpdateFX (Evt *script, bool isInitialCall)
ApiStatus MerleeStopFX (Evt *script, bool isInitialCall)
ApiStatus PlayMerleeGatherFX (Evt *script, bool isInitialCall)
ApiStatus PlayMerleeOrbFX (Evt *script, bool isInitialCall)
ApiStatus FadeBackgroundDarken (Evt *script, bool isInitialCall)
ApiStatus FadeBackgroundLighten (Evt *script, bool isInitialCall)
ApiStatus GetCamLookAtObjVector (Evt *script, bool isInitialCall)
ApiStatus HasMerleeCasts (Evt *script, bool isInitialCall)
ApiStatus OnDefeatEnemy (Evt *script, bool isInitialCall)
ApiStatus OnFleeBattleDrops (Evt *script, bool isInitialCall)
Message
ApiStatus SpeakToPlayer (Evt *script, bool isInitialCall)
ApiStatus EndSpeech (Evt *script, bool isInitialCall)
ApiStatus ContinueSpeech (Evt *script, bool isInitialCall)
ApiStatus SpeakToNpc (Evt *script, bool isInitialCall)
ApiStatus ShowMessageAtScreenPos (Evt *script, bool isInitialCall)
ApiStatus ShowMessageAtWorldPos (Evt *script, bool isInitialCall)
ApiStatus CloseMessage (Evt *script, bool isInitialCall)
ApiStatus SwitchMessage (Evt *script, bool isInitialCall)
ApiStatus ShowChoice (Evt *script, bool isInitialCall)
ApiStatus CloseChoice (Evt *script, bool isInitialCall)
ApiStatus CancelMessage (Evt *script, bool isInitialCall)
ApiStatus SetMessageImages (Evt *script, bool isInitialCall)
ApiStatus func_802D0C94 (Evt *script, bool isInitialCall)
ApiStatus SetMessageText (Evt *script, bool isInitialCall)
ApiStatus SetMessageValue (Evt *script, bool isInitialCall)
Player
ApiStatus HidePlayerShadow (Evt *script, bool isInitialCall)
Hides the player's shadow if hide is true, shows it if false.
ApiStatus DisablePlayerPhysics (Evt *script, bool isInitialCall)
Disables player physics if disable is true, enables it if false.
ApiStatus DisablePlayerInput (Evt *script, bool isInitialCall)
Disables player and partner input, and disables the status menu.
ApiStatus SetPlayerPos (Evt *script, bool isInitialCall)
Sets the player position.
ApiStatus SetPlayerCollisionSize (Evt *script, bool isInitialCall)
Overrides the player collision size.
ApiStatus SetPlayerSpeed (Evt *script, bool isInitialCall)
Sets the move speed of the player for subequent PlayerMoveTo calls.
ApiStatus SetPlayerJumpscale (Evt *script, bool isInitialCall)
ApiStatus SetPlayerAnimation (Evt *script, bool isInitialCall)
ApiStatus SetPlayerActionState (Evt *script, bool isInitialCall)
ApiStatus SetPlayerAnimationSpeed (Evt *script, bool isInitialCall)
ApiStatus PlayerMoveTo (Evt *script, bool isInitialCall)
ApiStatus func_802D1270 (Evt *script, bool isInitialCall)
ApiStatus func_802D1380 (Evt *script, bool isInitialCall)
ApiStatus PlayerJump (Evt *script, bool isInitialCall)
ApiStatus PlayerJump1 (Evt *script, bool isInitialCall)
ApiStatus PlayerJump2 (Evt *script, bool isInitialCall)
ApiStatus InterpPlayerYaw (Evt *script, bool isInitialCall)
ApiStatus PlayerFaceNpc (Evt *script, bool isInitialCall)
ApiStatus GetPlayerTargetYaw (Evt *script, bool isInitialCall)
ApiStatus SetPlayerFlagBits (Evt *script, bool isInitialCall)
ApiStatus GetPlayerActionState (Evt *script, bool isInitialCall)
ApiStatus GetPlayerPos (Evt *script, bool isInitialCall)
ApiStatus GetPlayerAnimation (Evt *script, bool isInitialCall)
ApiStatus FullyRestoreHPandFP (Evt *script, bool isInitialCall)
ApiStatus FullyRestoreSP (Evt *script, bool isInitialCall)
ApiStatus EnablePartner (Evt *script, bool isInitialCall)
Enables switching to the given partner.
ApiStatus DisablePartner (Evt *script, bool isInitialCall)
Disables switching to the given partner.
ApiStatus UseEntryHeading (Evt *script, bool isInitialCall)
ApiStatus func_802D2148 (Evt *script, bool isInitialCall)
ApiStatus UseExitHeading (Evt *script, bool isInitialCall)
ApiStatus WaitForPlayerTouchingFloor (Evt *script, bool isInitialCall)
ApiStatus func_802D2484 (Evt *script, bool isInitialCall)
ApiStatus IsPlayerOnValidFloor (Evt *script, bool isInitialCall)
ApiStatus WaitForPlayerMoveToComplete (Evt *script, bool isInitialCall)
ApiStatus WaitForPlayerInputEnabled (Evt *script, bool isInitialCall)
ApiStatus UpdatePlayerImgFX (Evt *script, bool isInitialCall)
ApiStatus SetPlayerImgFXFlags (Evt *script, bool isInitialCall)
ApiStatus FacePlayerTowardPoint (Evt *script, bool isInitialCall)
ApiStatus DisablePulseStone (Evt *script, bool isInitialCall)
ApiStatus GetPartnerInUse (Evt *script, bool isInitialCall)
ApiStatus ForceUsePartner (Evt *script, bool isInitialCall)
ApiStatus InterruptUsePartner (Evt *script, bool isInitialCall)
ApiStatus Disable8bitMario (Evt *script, bool isInitialCall)
Enables and disables the 8-bit Mario easter egg.
ApiStatus func_802D2C14 (Evt *script, bool isInitialCall)
ApiStatus SetPlayerPushVelocity (Evt *script, bool isInitialCall)
ApiStatus PlaySoundAtPlayer (Evt *script, bool isInitialCall)
Math
ApiStatus MakeLerp (Evt *script, bool isInitialCall)
ApiStatus UpdateLerp (Evt *script, bool isInitialCall)
ApiStatus RandInt (Evt *script, bool isInitialCall)
ApiStatus GetAngleBetweenNPCs (Evt *script, bool isInitialCall)
ApiStatus GetAngleToNPC (Evt *script, bool isInitialCall)
ApiStatus GetAngleToPlayer (Evt *script, bool isInitialCall)
ApiStatus AwaitPlayerApproach (Evt *script, bool isInitialCall)
ApiStatus IsPlayerWithin (Evt *script, bool isInitialCall)
ApiStatus AwaitPlayerLeave (Evt *script, bool isInitialCall)
ApiStatus AddVectorPolar (Evt *script, bool isInitialCall)
ApiStatus func_802D4BDC (Evt *script, bool isInitialCall)
ApiStatus func_802D4C4C (Evt *script, bool isInitialCall)
ApiStatus func_802D4CC4 (Evt *script, bool isInitialCall)
ApiStatus func_802D4D14 (Evt *script, bool isInitialCall)
ApiStatus func_802D4D88 (Evt *script, bool isInitialCall)
ApiStatus LoadPath (Evt *script, bool isInitialCall)
ApiStatus GetNextPathPos (Evt *script, bool isInitialCall)
ApiStatus GetDist2D (Evt *script, bool isInitialCall)
ApiStatus SetTimeFreezeMode (Evt *script, bool isInitialCall)
ApiStatus ModifyGlobalOverrideFlags (Evt *script, bool isInitialCall)
ApiStatus SetValueByRef (Evt *script, bool isInitialCall)
ApiStatus GetValueByRef (Evt *script, bool isInitialCall)
ApiStatus SetGameMode (Evt *script, bool isInitialCall)
ApiStatus ClampAngleInt (Evt *script, bool isInitialCall)
ApiStatus ClampAngleFloat (Evt *script, bool isInitialCall)
UI
ApiStatus EnableWorldStatusBar (Evt *script, bool isInitialCall)
ApiStatus ShowWorldStatusBar (Evt *script, bool isInitialCall)
ApiStatus ShowCoinCounter (Evt *script, bool isInitialCall)
Audio
ApiStatus PollMusicEvents (Evt *script, bool isInitialCall)
ApiStatus RegisterMusicEvents (Evt *script, bool isInitialCall)
ApiStatus FadeOutMusic (Evt *script, bool isInitialCall)
ApiStatus SetMusic (Evt *script, bool isInitialCall)
ApiStatus FadeInMusic (Evt *script, bool isInitialCall)
ApiStatus EnableMusicProximityMix (Evt *script, bool isInitialCall)
ApiStatus AdjustMusicProximityMix (Evt *script, bool isInitialCall)
ApiStatus SetTrackVolumes (Evt *script, bool isInitialCall)
ApiStatus PopSong (Evt *script, bool isInitialCall)
ApiStatus PushSong (Evt *script, bool isInitialCall)
ApiStatus PopBattleSong (Evt *script, bool isInitialCall)
ApiStatus PushBattleSong (Evt *script, bool isInitialCall)
ApiStatus SetBattleSong (Evt *script, bool isInitialCall)
ApiStatus ClearAmbientSounds (Evt *script, bool isInitialCall)
ApiStatus PlayAmbientSounds (Evt *script, bool isInitialCall)
ApiStatus PlaySound (Evt *script, bool isInitialCall)
ApiStatus PlaySoundWithVolume (Evt *script, bool isInitialCall)
ApiStatus PlaySoundAt (Evt *script, bool isInitialCall)
ApiStatus StopSound (Evt *script, bool isInitialCall)
ApiStatus StopTrackingSoundPos (Evt *script, bool isInitialCall)
ApiStatus UseDoorSounds (Evt *script, bool isInitialCall)
ApiStatus UseRoomDoorSounds (Evt *script, bool isInitialCall)
ApiStatus PlaySoundAtF (Evt *script, bool isInitialCall)
Virtual Entity
ApiStatus InitVirtualEntityList (Evt *script, bool isInitialCall)
ApiStatus CreateVirtualEntityAt (Evt *script, bool isInitialCall)
ApiStatus CreateVirtualEntity (Evt *script, bool isInitialCall)
ApiStatus CreateVirtualEntity_ALT (Evt *script, bool isInitialCall)
ApiStatus DeleteVirtualEntity (Evt *script, bool isInitialCall)
ApiStatus SetVirtualEntityRenderCommands (Evt *script, bool isInitialCall)
ApiStatus SetVirtualEntityPosition (Evt *script, bool isInitialCall)
ApiStatus GetVirtualEntityPosition (Evt *script, bool isInitialCall)
ApiStatus SetVirtualEntityRotation (Evt *script, bool isInitialCall)
ApiStatus SetVirtualEntityScale (Evt *script, bool isInitialCall)
ApiStatus SetVirtualEntityMoveSpeed (Evt *script, bool isInitialCall)
ApiStatus SetVirtualEntityJumpGravity (Evt *script, bool isInitialCall)
ApiStatus VirtualEntityMoveTo (Evt *script, bool isInitialCall)
ApiStatus VirtualEntityJumpTo (Evt *script, bool isInitialCall)
ApiStatus VirtualEntityLandJump (Evt *script, bool isInitialCall)
ApiStatus SetVirtualEntityFlags (Evt *script, bool isInitialCall)
ApiStatus SetVirtualEntityFlagBits (Evt *script, bool isInitialCall)
ApiStatus SetVirtualEntityRenderMode (Evt *script, bool isInitialCall)
Item
ApiStatus ShowKeyChoicePopup (Evt *script, bool isInitialCall)
ApiStatus ShowConsumableChoicePopup (Evt *script, bool isInitialCall)
ApiStatus RemoveKeyItemAt (Evt *script, bool isInitialCall)
ApiStatus RemoveItemAt (Evt *script, bool isInitialCall)
ApiStatus AddKeyItem (Evt *script, bool isInitialCall)
ApiStatus CloseChoicePopup (Evt *script, bool isInitialCall)
ApiStatus HasKeyItem (Evt *script, bool isInitialCall)
ApiStatus FindKeyItem (Evt *script, bool isInitialCall)
ApiStatus AddItem (Evt *script, bool isInitialCall)
ApiStatus ClearVariable (Evt *script, bool isInitialCall)
ApiStatus FindItem (Evt *script, bool isInitialCall)
ApiStatus RemoveItem (Evt *script, bool isInitialCall)
ApiStatus CountFortessKeys (Evt *script, bool isInitialCall)
ApiStatus RemoveFortressKeys (Evt *script, bool isInitialCall)
ApiStatus MakeItemEntity (Evt *script, bool isInitialCall)
ApiStatus DropItemEntity (Evt *script, bool isInitialCall)
ApiStatus DropResizableItemEntity (Evt *script, bool isInitialCall)
ApiStatus RemoveItemEntity (Evt *script, bool isInitialCall)
ApiStatus AddBadge (Evt *script, bool isInitialCall)
ApiStatus RemoveBadge (Evt *script, bool isInitialCall)
ApiStatus SetItemPos (Evt *script, bool isInitialCall)
ApiStatus SetItemFlags (Evt *script, bool isInitialCall)
ApiStatus SetItemAlpha (Evt *script, bool isInitialCall)
ApiStatus AddCoin (Evt *script, bool isInitialCall)
ApiStatus AddStarPoints (Evt *script, bool isInitialCall)
ApiStatus AddStarPieces (Evt *script, bool isInitialCall)
ApiStatus GetItemPower (Evt *script, bool isInitialCall)
ApiStatus ShowGotItem (Evt *script, bool isInitialCall)
Effect
ApiStatus ShowStartRecoveryShimmer (Evt *script, bool isInitialCall)
ApiStatus ShowRecoveryShimmer (Evt *script, bool isInitialCall)
ApiStatus func_802D7690 (Evt *script, bool isInitialCall)
ApiStatus ShowEmote (Evt *script, bool isInitialCall)
ApiStatus RemoveEffect (Evt *script, bool isInitialCall)
ApiStatus DismissEffect (Evt *script, bool isInitialCall)
ApiStatus DismissItemOutline (Evt *script, bool isInitialCall)
ApiStatus func_802D7B74 (Evt *script, bool isInitialCall)
ApiStatus InterpMotionBlurParams (Evt *script, bool isInitialCall)
ApiStatus SetMotionBlurParams (Evt *script, bool isInitialCall)
ApiStatus ShowSweat (Evt *script, bool isInitialCall)
ApiStatus ShowSleepBubble (Evt *script, bool isInitialCall)
ApiStatus SetSleepBubbleTimeLeft (Evt *script, bool isInitialCall)
ApiStatus PlayEffect_impl (Evt *script, bool isInitialCall)
Entity
ApiStatus MakeEntity (Evt *script, bool isInitialCall)
Creates an entity.
ApiStatus SetEntityCullMode (Evt *script, bool isInitialCall)
ApiStatus UseDynamicShadow (Evt *script, bool isInitialCall)
ApiStatus AssignScript (Evt *script, bool isInitialCall)
ApiStatus AssignSwitchFlag (Evt *script, bool isInitialCall)
ApiStatus AssignBlockFlag (Evt *script, bool isInitialCall)
ApiStatus AssignChestFlag (Evt *script, bool isInitialCall)
ApiStatus AssignPanelFlag (Evt *script, bool isInitialCall)
ApiStatus AssignCrateFlag (Evt *script, bool isInitialCall)
ApiStatus DeleteTrigger (Evt *script, bool isInitialCall)
Removes a trigger previously bound with BindTrigger.
Sprite shading
ApiStatus SetSpriteShading (Evt *script, bool isInitialCall)
ApiStatus EnableSpriteShading (Evt *script, bool isInitialCall)
Demo
ApiStatus GetDemoState (Evt *script, bool isInitialCall)
ApiStatus DemoPressButton (Evt *script, bool isInitialCall)
ApiStatus DemoReleaseButton (Evt *script, bool isInitialCall)
ApiStatus DemoSetButtons (Evt *script, bool isInitialCall)
ApiStatus DemoJoystickRadial (Evt *script, bool isInitialCall)
ApiStatus DemoJoystickXY (Evt *script, bool isInitialCall)
Variables
EvtScript EnemyNpcHit
EvtScript EnemyNpcDefeat
Function Documentation
AddAnimatedModelRootPosition()
ApiStatus AddAnimatedModelRootPosition (Evt * script, bool isInitialCall)
AddBadge()
ApiStatus AddBadge (Evt * script, bool isInitialCall)
AddCoin()
ApiStatus AddCoin (Evt * script, bool isInitialCall)
AddItem()
ApiStatus AddItem (Evt * script, bool isInitialCall)
AddKeyItem()
ApiStatus AddKeyItem (Evt * script, bool isInitialCall)
AddStarPieces()
ApiStatus AddStarPieces (Evt * script, bool isInitialCall)
AddStarPoints()
ApiStatus AddStarPoints (Evt * script, bool isInitialCall)
AddVectorPolar()
ApiStatus AddVectorPolar (Evt * script, bool isInitialCall)
AdjustCam()
ApiStatus AdjustCam (Evt * script, bool isInitialCall)
AdjustMusicProximityMix()
ApiStatus AdjustMusicProximityMix (Evt * script, bool isInitialCall)
AssignBlockFlag()
ApiStatus AssignBlockFlag (Evt * script, bool isInitialCall)
AssignChestFlag()
ApiStatus AssignChestFlag (Evt * script, bool isInitialCall)
AssignCrateFlag()
ApiStatus AssignCrateFlag (Evt * script, bool isInitialCall)
AssignPanelFlag()
ApiStatus AssignPanelFlag (Evt * script, bool isInitialCall)
AssignScript()
ApiStatus AssignScript (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
AssignSwitchFlag()
ApiStatus AssignSwitchFlag (Evt * script, bool isInitialCall)
AwaitPlayerApproach()
ApiStatus AwaitPlayerApproach (Evt * script, bool isInitialCall)
AwaitPlayerLeave()
ApiStatus AwaitPlayerLeave (Evt * script, bool isInitialCall)
BindNpcAI()
ApiStatus BindNpcAI (Evt * script, bool isInitialCall)
BindNpcAux()
ApiStatus BindNpcAux (Evt * script, bool isInitialCall)
BindNpcDefeat()
ApiStatus BindNpcDefeat (Evt * script, bool isInitialCall)
BindNpcHit()
ApiStatus BindNpcHit (Evt * script, bool isInitialCall)
BindNpcIdle()
ApiStatus BindNpcIdle (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
BindNpcInteract()
ApiStatus BindNpcInteract (Evt * script, bool isInitialCall)
BringPartnerOut()
ApiStatus BringPartnerOut (Evt * script, bool isInitialCall)
CancelMessage()
ApiStatus CancelMessage (Evt * script, bool isInitialCall)
ChangeModelAnimation()
ApiStatus ChangeModelAnimation (Evt * script, bool isInitialCall)
ClampAngleFloat()
ApiStatus ClampAngleFloat (Evt * script, bool isInitialCall)
ClampAngleInt()
ApiStatus ClampAngleInt (Evt * script, bool isInitialCall)
ClearAmbientSounds()
ApiStatus ClearAmbientSounds (Evt * script, bool isInitialCall)
ClearDefeatedEnemies()
ApiStatus ClearDefeatedEnemies (Evt * script, bool isInitialCall)
ClearPartnerMoveHistory()
ApiStatus ClearPartnerMoveHistory (Evt * script, bool isInitialCall)
ClearVariable()
ApiStatus ClearVariable (Evt * script, bool isInitialCall)
CloneModel()
ApiStatus CloneModel (Evt * script, bool isInitialCall)
CloseChoice()
ApiStatus CloseChoice (Evt * script, bool isInitialCall)
CloseChoicePopup()
ApiStatus CloseChoicePopup (Evt * script, bool isInitialCall)
CloseMessage()
ApiStatus CloseMessage (Evt * script, bool isInitialCall)
ContinueSpeech()
ApiStatus ContinueSpeech (Evt * script, bool isInitialCall)
CountFortessKeys()
ApiStatus CountFortessKeys (Evt * script, bool isInitialCall)
CreateNpc()
ApiStatus CreateNpc (Evt * script, bool isInitialCall)
CreateVirtualEntity()
ApiStatus CreateVirtualEntity (Evt * script, bool isInitialCall)
CreateVirtualEntity_ALT()
ApiStatus CreateVirtualEntity_ALT (Evt * script, bool isInitialCall)
CreateVirtualEntityAt()
ApiStatus CreateVirtualEntityAt (Evt * script, bool isInitialCall)
DeleteAnimatedModel()
ApiStatus DeleteAnimatedModel (Evt * script, bool isInitialCall)
DeleteNpc()
ApiStatus DeleteNpc (Evt * script, bool isInitialCall)
DeleteTrigger()
ApiStatus DeleteTrigger (Evt * script, bool isInitialCall)
Removes a trigger previously bound with BindTrigger.
Parameters
triggerPtr
DeleteVirtualEntity()
ApiStatus DeleteVirtualEntity (Evt * script, bool isInitialCall)
DemoJoystickRadial()
ApiStatus DemoJoystickRadial (Evt * script, bool isInitialCall)
DemoJoystickXY()
ApiStatus DemoJoystickXY (Evt * script, bool isInitialCall)
DemoPressButton()
ApiStatus DemoPressButton (Evt * script, bool isInitialCall)
DemoReleaseButton()
ApiStatus DemoReleaseButton (Evt * script, bool isInitialCall)
DemoSetButtons()
ApiStatus DemoSetButtons (Evt * script, bool isInitialCall)
Disable8bitMario()
ApiStatus Disable8bitMario (Evt * script, bool isInitialCall)
Enables and disables the 8-bit Mario easter egg.
Parameters
disable Disable the easter egg if true, enable it if false.
Whilst active, the player uses a retro sprite, and the following actions are disabled:
Spin dash
Hammer
Spin jump and tornado jump
Menus
Partner usage and partner switching
See also
PA_FLAG_8BIT_MARIO
DisablePartner()
ApiStatus DisablePartner (Evt * script, bool isInitialCall)
Disables switching to the given partner.
Parameters
partnerID The partner id to disable.
See also
EnablePartner
DisablePartnerAI()
ApiStatus DisablePartnerAI (Evt * script, bool isInitialCall)
DisablePlayerInput()
ApiStatus DisablePlayerInput (Evt * script, bool isInitialCall)
Disables player and partner input, and disables the status menu.
Parameters
disable Whether to disable player input.
Referenced by MAP_RODATA_PAD().
DisablePlayerPhysics()
ApiStatus DisablePlayerPhysics (Evt * script, bool isInitialCall)
Disables player physics if disable is true, enables it if false.
Parameters
disable Whether to disable player physics.
See also
disable_player_static_collisions, enable_player_static_collisions
Referenced by MAP_RODATA_PAD().
DisablePulseStone()
ApiStatus DisablePulseStone (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
DismissEffect()
ApiStatus DismissEffect (Evt * script, bool isInitialCall)
DismissItemOutline()
ApiStatus DismissItemOutline (Evt * script, bool isInitialCall)
DoNpcDefeat()
ApiStatus DoNpcDefeat (Evt * script, bool isInitialCall)
DropItemEntity()
ApiStatus DropItemEntity (Evt * script, bool isInitialCall)
DropResizableItemEntity()
ApiStatus DropResizableItemEntity (Evt * script, bool isInitialCall)
EnableGroup()
ApiStatus EnableGroup (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
EnableModel()
ApiStatus EnableModel (Evt * script, bool isInitialCall)
EnableMusicProximityMix()
ApiStatus EnableMusicProximityMix (Evt * script, bool isInitialCall)
EnableNpcAI()
ApiStatus EnableNpcAI (Evt * script, bool isInitialCall)
EnableNpcAux()
ApiStatus EnableNpcAux (Evt * script, bool isInitialCall)
EnableNpcBlur()
ApiStatus EnableNpcBlur (Evt * script, bool isInitialCall)
EnableNpcShadow()
ApiStatus EnableNpcShadow (Evt * script, bool isInitialCall)
EnablePartner()
ApiStatus EnablePartner (Evt * script, bool isInitialCall)
Enables switching to the given partner.
Parameters
partnerID The partner id to enable.
See also
DisablePartner
EnablePartnerAI()
ApiStatus EnablePartnerAI (Evt * script, bool isInitialCall)
EnableSpriteShading()
ApiStatus EnableSpriteShading (Evt * script, bool isInitialCall)
EnableTexPanning()
ApiStatus EnableTexPanning (Evt * script, bool isInitialCall)
EnableWorldStatusBar()
ApiStatus EnableWorldStatusBar (Evt * script, bool isInitialCall)
EndSpeech()
ApiStatus EndSpeech (Evt * script, bool isInitialCall)
FacePlayerTowardPoint()
ApiStatus FacePlayerTowardPoint (Evt * script, bool isInitialCall)
FadeBackgroundDarken()
ApiStatus FadeBackgroundDarken (Evt * script, bool isInitialCall)
FadeBackgroundLighten()
ApiStatus FadeBackgroundLighten (Evt * script, bool isInitialCall)
FadeInMerlee()
ApiStatus FadeInMerlee (Evt * script, bool isInitialCall)
FadeInMusic()
ApiStatus FadeInMusic (Evt * script, bool isInitialCall)
FadeOutMerlee()
ApiStatus FadeOutMerlee (Evt * script, bool isInitialCall)
FadeOutMusic()
ApiStatus FadeOutMusic (Evt * script, bool isInitialCall)
FindItem()
ApiStatus FindItem (Evt * script, bool isInitialCall)
FindKeyItem()
ApiStatus FindKeyItem (Evt * script, bool isInitialCall)
ForceUsePartner()
ApiStatus ForceUsePartner (Evt * script, bool isInitialCall)
FullyRestoreHPandFP()
ApiStatus FullyRestoreHPandFP (Evt * script, bool isInitialCall)
FullyRestoreSP()
ApiStatus FullyRestoreSP (Evt * script, bool isInitialCall)
func_80044238()
ApiStatus func_80044238 (Evt * script, bool isInitialCall)
func_80044290()
ApiStatus func_80044290 (Evt * script, bool isInitialCall)
func_800445A8()
ApiStatus func_800445A8 (Evt * script, bool isInitialCall)
func_800445D4()
ApiStatus func_800445D4 (Evt * script, bool isInitialCall)
func_8004572C()
ApiStatus func_8004572C (Evt * script, bool isInitialCall)
func_80045798()
ApiStatus func_80045798 (Evt * script, bool isInitialCall)
func_80045838()
ApiStatus func_80045838 (Evt * script, bool isInitialCall)
func_800458CC()
ApiStatus func_800458CC (Evt * script, bool isInitialCall)
func_802CB710()
ApiStatus func_802CB710 (Evt * script, bool isInitialCall)
func_802CF54C()
ApiStatus func_802CF54C (Evt * script, bool isInitialCall)
func_802CF56C()
ApiStatus func_802CF56C (Evt * script, bool isInitialCall)
func_802D0C94()
ApiStatus func_802D0C94 (Evt * script, bool isInitialCall)
func_802D1270()
ApiStatus func_802D1270 (Evt * script, bool isInitialCall)
func_802D1380()
ApiStatus func_802D1380 (Evt * script, bool isInitialCall)
func_802D2148()
ApiStatus func_802D2148 (Evt * script, bool isInitialCall)
func_802D2484()
ApiStatus func_802D2484 (Evt * script, bool isInitialCall)
func_802D2C14()
ApiStatus func_802D2C14 (Evt * script, bool isInitialCall)
func_802D4BDC()
ApiStatus func_802D4BDC (Evt * script, bool isInitialCall)
func_802D4C4C()
ApiStatus func_802D4C4C (Evt * script, bool isInitialCall)
func_802D4CC4()
ApiStatus func_802D4CC4 (Evt * script, bool isInitialCall)
func_802D4D14()
ApiStatus func_802D4D14 (Evt * script, bool isInitialCall)
func_802D4D88()
ApiStatus func_802D4D88 (Evt * script, bool isInitialCall)
func_802D7690()
ApiStatus func_802D7690 (Evt * script, bool isInitialCall)
func_802D7B74()
ApiStatus func_802D7B74 (Evt * script, bool isInitialCall)
GetAngleBetweenNPCs()
ApiStatus GetAngleBetweenNPCs (Evt * script, bool isInitialCall)
GetAngleToNPC()
ApiStatus GetAngleToNPC (Evt * script, bool isInitialCall)
GetAngleToPlayer()
ApiStatus GetAngleToPlayer (Evt * script, bool isInitialCall)
GetAnimatedModelRootPosition()
ApiStatus GetAnimatedModelRootPosition (Evt * script, bool isInitialCall)
GetAnimatedNodePosition()
ApiStatus GetAnimatedNodePosition (Evt * script, bool isInitialCall)
GetAnimatedNodeRotation()
ApiStatus GetAnimatedNodeRotation (Evt * script, bool isInitialCall)
GetAnimatedPositionByTreeIndex()
ApiStatus GetAnimatedPositionByTreeIndex (Evt * script, bool isInitialCall)
GetAnimatedRotationByTreeIndex()
ApiStatus GetAnimatedRotationByTreeIndex (Evt * script, bool isInitialCall)
GetBattleOutcome()
ApiStatus GetBattleOutcome (Evt * script, bool isInitialCall)
GetCamDistance()
ApiStatus GetCamDistance (Evt * script, bool isInitialCall)
GetCamLookAtObjVector()
ApiStatus GetCamLookAtObjVector (Evt * script, bool isInitialCall)
GetCamPitch()
ApiStatus GetCamPitch (Evt * script, bool isInitialCall)
GetCamPosA()
ApiStatus GetCamPosA (Evt * script, bool isInitialCall)
GetCamPosB()
ApiStatus GetCamPosB (Evt * script, bool isInitialCall)
GetCamPosC()
ApiStatus GetCamPosC (Evt * script, bool isInitialCall)
GetCamPosition()
ApiStatus GetCamPosition (Evt * script, bool isInitialCall)
GetCamType()
ApiStatus GetCamType (Evt * script, bool isInitialCall)
GetColliderCenter()
ApiStatus GetColliderCenter (Evt * script, bool isInitialCall)
GetCurrentPartnerID()
ApiStatus GetCurrentPartnerID (Evt * script, bool isInitialCall)
GetDemoState()
ApiStatus GetDemoState (Evt * script, bool isInitialCall)
GetDist2D()
ApiStatus GetDist2D (Evt * script, bool isInitialCall)
GetEncounterTriggerHitTier()
ApiStatus GetEncounterTriggerHitTier (Evt * script, bool isInitialCall)
GetEntryID()
ApiStatus GetEntryID (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD(), and MAP_RODATA_PAD().
GetItemPower()
ApiStatus GetItemPower (Evt * script, bool isInitialCall)
GetLoadType()
ApiStatus GetLoadType (Evt * script, bool isInitialCall)
GetMapID()
ApiStatus GetMapID (Evt * script, bool isInitialCall)
GetModelCenter()
ApiStatus GetModelCenter (Evt * script, bool isInitialCall)
GetModelIndex()
ApiStatus GetModelIndex (Evt * script, bool isInitialCall)
GetNextPathPos()
ApiStatus GetNextPathPos (Evt * script, bool isInitialCall)
See also
LoadPath
Referenced by make_vine_interpolation().
GetNpcAnimation()
ApiStatus GetNpcAnimation (Evt * script, bool isInitialCall)
GetNpcPointer()
ApiStatus GetNpcPointer (Evt * script, bool isInitialCall)
GetNpcPos()
ApiStatus GetNpcPos (Evt * script, bool isInitialCall)
GetNpcVar()
ApiStatus GetNpcVar (Evt * script, bool isInitialCall)
GetNpcYaw()
ApiStatus GetNpcYaw (Evt * script, bool isInitialCall)
GetOwnerEncounterTrigger()
ApiStatus GetOwnerEncounterTrigger (Evt * script, bool isInitialCall)
GetPartnerInUse()
ApiStatus GetPartnerInUse (Evt * script, bool isInitialCall)
GetPartnerPos()
ApiStatus GetPartnerPos (Evt * script, bool isInitialCall)
GetPlayerActionState()
ApiStatus GetPlayerActionState (Evt * script, bool isInitialCall)
GetPlayerAnimation()
ApiStatus GetPlayerAnimation (Evt * script, bool isInitialCall)
GetPlayerPos()
ApiStatus GetPlayerPos (Evt * script, bool isInitialCall)
GetPlayerTargetYaw()
ApiStatus GetPlayerTargetYaw (Evt * script, bool isInitialCall)
GetSelfAnimationFromTable()
ApiStatus GetSelfAnimationFromTable (Evt * script, bool isInitialCall)
GetSelfNpcID()
ApiStatus GetSelfNpcID (Evt * script, bool isInitialCall)
GetSelfVar()
ApiStatus GetSelfVar (Evt * script, bool isInitialCall)
GetTransformGroup()
ApiStatus GetTransformGroup (Evt * script, bool isInitialCall)
GetValueByRef()
ApiStatus GetValueByRef (Evt * script, bool isInitialCall)
GetVirtualEntityPosition()
ApiStatus GetVirtualEntityPosition (Evt * script, bool isInitialCall)
GotoMap()
ApiStatus GotoMap (Evt * script, bool isInitialCall)
GotoMapByID()
ApiStatus GotoMapByID (Evt * script, bool isInitialCall)
GotoMapSpecial()
ApiStatus GotoMapSpecial (Evt * script, bool isInitialCall)
GrabCamera()
ApiStatus GrabCamera (Evt * script, bool isInitialCall)
HasKeyItem()
ApiStatus HasKeyItem (Evt * script, bool isInitialCall)
HasMerleeCasts()
ApiStatus HasMerleeCasts (Evt * script, bool isInitialCall)
HidePlayerShadow()
ApiStatus HidePlayerShadow (Evt * script, bool isInitialCall)
Hides the player's shadow if hide is true, shows it if false.
Parameters
hide Whether to hide the player's shadow.
See also
disable_player_shadow, enable_player_shadow
InitAnimatedModels()
ApiStatus InitAnimatedModels (Evt * script, bool isInitialCall)
InitVirtualEntityList()
ApiStatus InitVirtualEntityList (Evt * script, bool isInitialCall)
InterpCamTargetPos()
ApiStatus InterpCamTargetPos (Evt * script, bool isInitialCall)
InterpMotionBlurParams()
ApiStatus InterpMotionBlurParams (Evt * script, bool isInitialCall)
InterpNpcYaw()
ApiStatus InterpNpcYaw (Evt * script, bool isInitialCall)
InterpPlayerYaw()
ApiStatus InterpPlayerYaw (Evt * script, bool isInitialCall)
InterruptUsePartner()
ApiStatus InterruptUsePartner (Evt * script, bool isInitialCall)
InvalidateModelTransform()
ApiStatus InvalidateModelTransform (Evt * script, bool isInitialCall)
IsPlayerOnValidFloor()
ApiStatus IsPlayerOnValidFloor (Evt * script, bool isInitialCall)
IsPlayerWithin()
ApiStatus IsPlayerWithin (Evt * script, bool isInitialCall)
IsStartingConversation()
ApiStatus IsStartingConversation (Evt * script, bool isInitialCall)
LoadAnimatedMesh()
ApiStatus LoadAnimatedMesh (Evt * script, bool isInitialCall)
LoadAnimatedModel()
ApiStatus LoadAnimatedModel (Evt * script, bool isInitialCall)
LoadDemoBattle()
ApiStatus LoadDemoBattle (Evt * script, bool isInitialCall)
LoadPath()
ApiStatus LoadPath (Evt * script, bool isInitialCall)
See also
GetNextPathPos
Referenced by make_vine_interpolation().
LoadSettings()
ApiStatus LoadSettings (Evt * script, bool isInitialCall)
MakeEntity()
ApiStatus MakeEntity (Evt * script, bool isInitialCall)
Creates an entity.
Parameters
blueprint Pointer to EntityBlueprint to use.
x
y
z
flags EntityFlags
... Varargs.
MAKE_ENTITY_END Terminates the varargs.
[out ] LVar0 Created entity's ID.
Referenced by MAP_RODATA_PAD().
MakeItemEntity()
ApiStatus MakeItemEntity (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
MakeLerp()
ApiStatus MakeLerp (Evt * script, bool isInitialCall)
MakeLocalVertexCopy()
ApiStatus MakeLocalVertexCopy (Evt * script, bool isInitialCall)
MakeNpcs()
ApiStatus MakeNpcs (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
MakeTransformGroup()
ApiStatus MakeTransformGroup (Evt * script, bool isInitialCall)
MerleeStopFX()
ApiStatus MerleeStopFX (Evt * script, bool isInitialCall)
MerleeUpdateFX()
ApiStatus MerleeUpdateFX (Evt * script, bool isInitialCall)
ModifyColliderFlags()
ApiStatus ModifyColliderFlags (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
ModifyGlobalOverrideFlags()
ApiStatus ModifyGlobalOverrideFlags (Evt * script, bool isInitialCall)
NpcFaceNpc()
ApiStatus NpcFaceNpc (Evt * script, bool isInitialCall)
NpcFacePlayer()
ApiStatus NpcFacePlayer (Evt * script, bool isInitialCall)
NpcFlyTo()
ApiStatus NpcFlyTo (Evt * script, bool isInitialCall)
NpcJump0()
ApiStatus NpcJump0 (Evt * script, bool isInitialCall)
NpcJump1()
ApiStatus NpcJump1 (Evt * script, bool isInitialCall)
NpcMoveTo()
ApiStatus NpcMoveTo (Evt * script, bool isInitialCall)
NpcSetHomePosToCurrent()
ApiStatus NpcSetHomePosToCurrent (Evt * script, bool isInitialCall)
OnDefeatEnemy()
ApiStatus OnDefeatEnemy (Evt * script, bool isInitialCall)
OnFleeBattleDrops()
ApiStatus OnFleeBattleDrops (Evt * script, bool isInitialCall)
OnPlayerFled()
ApiStatus OnPlayerFled (Evt * script, bool isInitialCall)
PanToTarget()
ApiStatus PanToTarget (Evt * script, bool isInitialCall)
ParentColliderToModel()
ApiStatus ParentColliderToModel (Evt * script, bool isInitialCall)
PartnerCanUseAbility()
ApiStatus PartnerCanUseAbility (Evt * script, bool isInitialCall)
PartnerIsFlying()
ApiStatus PartnerIsFlying (Evt * script, bool isInitialCall)
PlayAmbientSounds()
ApiStatus PlayAmbientSounds (Evt * script, bool isInitialCall)
PlayEffect_impl()
ApiStatus PlayEffect_impl (Evt * script, bool isInitialCall)
See also
PlayEffect
PlayerFaceNpc()
ApiStatus PlayerFaceNpc (Evt * script, bool isInitialCall)
PlayerJump()
ApiStatus PlayerJump (Evt * script, bool isInitialCall)
PlayerJump1()
ApiStatus PlayerJump1 (Evt * script, bool isInitialCall)
PlayerJump2()
ApiStatus PlayerJump2 (Evt * script, bool isInitialCall)
PlayerMoveTo()
ApiStatus PlayerMoveTo (Evt * script, bool isInitialCall)
PlayMerleeGatherFX()
ApiStatus PlayMerleeGatherFX (Evt * script, bool isInitialCall)
PlayMerleeOrbFX()
ApiStatus PlayMerleeOrbFX (Evt * script, bool isInitialCall)
PlayModelAnimation()
ApiStatus PlayModelAnimation (Evt * script, bool isInitialCall)
PlayModelAnimationStartingFrom()
ApiStatus PlayModelAnimationStartingFrom (Evt * script, bool isInitialCall)
PlaySound()
ApiStatus PlaySound (Evt * script, bool isInitialCall)
PlaySoundAt()
ApiStatus PlaySoundAt (Evt * script, bool isInitialCall)
PlaySoundAtCollider()
ApiStatus PlaySoundAtCollider (Evt * script, bool isInitialCall)
PlaySoundAtF()
ApiStatus PlaySoundAtF (Evt * script, bool isInitialCall)
PlaySoundAtModel()
ApiStatus PlaySoundAtModel (Evt * script, bool isInitialCall)
PlaySoundAtNpc()
ApiStatus PlaySoundAtNpc (Evt * script, bool isInitialCall)
PlaySoundAtPlayer()
ApiStatus PlaySoundAtPlayer (Evt * script, bool isInitialCall)
PlaySoundWithVolume()
ApiStatus PlaySoundWithVolume (Evt * script, bool isInitialCall)
PollMusicEvents()
ApiStatus PollMusicEvents (Evt * script, bool isInitialCall)
PopBattleSong()
ApiStatus PopBattleSong (Evt * script, bool isInitialCall)
PopSong()
ApiStatus PopSong (Evt * script, bool isInitialCall)
PushBattleSong()
ApiStatus PushBattleSong (Evt * script, bool isInitialCall)
PushSong()
ApiStatus PushSong (Evt * script, bool isInitialCall)
PutPartnerAway()
ApiStatus PutPartnerAway (Evt * script, bool isInitialCall)
RandInt()
ApiStatus RandInt (Evt * script, bool isInitialCall)
RegisterMusicEvents()
ApiStatus RegisterMusicEvents (Evt * script, bool isInitialCall)
RemoveBadge()
ApiStatus RemoveBadge (Evt * script, bool isInitialCall)
RemoveEffect()
ApiStatus RemoveEffect (Evt * script, bool isInitialCall)
RemoveEncounter()
ApiStatus RemoveEncounter (Evt * script, bool isInitialCall)
RemoveFortressKeys()
ApiStatus RemoveFortressKeys (Evt * script, bool isInitialCall)
RemoveItem()
ApiStatus RemoveItem (Evt * script, bool isInitialCall)
RemoveItemAt()
ApiStatus RemoveItemAt (Evt * script, bool isInitialCall)
RemoveItemEntity()
ApiStatus RemoveItemEntity (Evt * script, bool isInitialCall)
RemoveKeyItemAt()
ApiStatus RemoveKeyItemAt (Evt * script, bool isInitialCall)
RemoveNpc()
ApiStatus RemoveNpc (Evt * script, bool isInitialCall)
ResetCam()
ApiStatus ResetCam (Evt * script, bool isInitialCall)
ResetFromLava()
ApiStatus ResetFromLava (Evt * script, bool isInitialCall)
RestartNpcAI()
ApiStatus RestartNpcAI (Evt * script, bool isInitialCall)
RestartNpcAux()
ApiStatus RestartNpcAux (Evt * script, bool isInitialCall)
RotateGroup()
ApiStatus RotateGroup (Evt * script, bool isInitialCall)
RotateModel()
ApiStatus RotateModel (Evt * script, bool isInitialCall)
ScaleGroup()
ApiStatus ScaleGroup (Evt * script, bool isInitialCall)
ScaleModel()
ApiStatus ScaleModel (Evt * script, bool isInitialCall)
SelfEnemyOverrideSyncPos()
ApiStatus SelfEnemyOverrideSyncPos (Evt * script, bool isInitialCall)
SetAnimatedModelRenderMode()
ApiStatus SetAnimatedModelRenderMode (Evt * script, bool isInitialCall)
SetAnimatedModelRootPosition()
ApiStatus SetAnimatedModelRootPosition (Evt * script, bool isInitialCall)
SetAnimatedModelRootRotation()
ApiStatus SetAnimatedModelRootRotation (Evt * script, bool isInitialCall)
SetAnimatedModelRootScale()
ApiStatus SetAnimatedModelRootScale (Evt * script, bool isInitialCall)
SetAnimatedNodeFlags()
ApiStatus SetAnimatedNodeFlags (Evt * script, bool isInitialCall)
SetAnimatorFlags()
ApiStatus SetAnimatorFlags (Evt * script, bool isInitialCall)
SetBattleAsScripted()
ApiStatus SetBattleAsScripted (Evt * script, bool isInitialCall)
SetBattleMusic()
ApiStatus SetBattleMusic (Evt * script, bool isInitialCall)
SetBattleSong()
ApiStatus SetBattleSong (Evt * script, bool isInitialCall)
SetCamBGColor()
ApiStatus SetCamBGColor (Evt * script, bool isInitialCall)
SetCamDistance()
ApiStatus SetCamDistance (Evt * script, bool isInitialCall)
SetCamEnabled()
ApiStatus SetCamEnabled (Evt * script, bool isInitialCall)
SetCamLeadPlayer()
ApiStatus SetCamLeadPlayer (Evt * script, bool isInitialCall)
SetCamLookTarget()
ApiStatus SetCamLookTarget (Evt * script, bool isInitialCall)
SetCamNoDraw()
ApiStatus SetCamNoDraw (Evt * script, bool isInitialCall)
SetCamPerspective()
ApiStatus SetCamPerspective (Evt * script, bool isInitialCall)
SetCamPitch()
ApiStatus SetCamPitch (Evt * script, bool isInitialCall)
SetCamPosA()
ApiStatus SetCamPosA (Evt * script, bool isInitialCall)
SetCamPosB()
ApiStatus SetCamPosB (Evt * script, bool isInitialCall)
SetCamPosC()
ApiStatus SetCamPosC (Evt * script, bool isInitialCall)
SetCamProperties()
ApiStatus SetCamProperties (Evt * script, bool isInitialCall)
SetCamSpeed()
ApiStatus SetCamSpeed (Evt * script, bool isInitialCall)
SetCamTarget()
ApiStatus SetCamTarget (Evt * script, bool isInitialCall)
SetCamType()
ApiStatus SetCamType (Evt * script, bool isInitialCall)
SetCamUpdateMode()
ApiStatus SetCamUpdateMode (Evt * script, bool isInitialCall)
SetCamViewport()
ApiStatus SetCamViewport (Evt * script, bool isInitialCall)
Referenced by A(), A(), A(), A(), and A().
SetCustomGfx()
ApiStatus SetCustomGfx (Evt * script, bool isInitialCall)
SetCustomGfxBuilders()
ApiStatus SetCustomGfxBuilders (Evt * script, bool isInitialCall)
SetCustomGfxEnabled()
ApiStatus SetCustomGfxEnabled (Evt * script, bool isInitialCall)
SetEncounterStatusFlags()
ApiStatus SetEncounterStatusFlags (Evt * script, bool isInitialCall)
SetEnemyFlagBits()
ApiStatus SetEnemyFlagBits (Evt * script, bool isInitialCall)
SetEntityCullMode()
ApiStatus SetEntityCullMode (Evt * script, bool isInitialCall)
SetGameMode()
ApiStatus SetGameMode (Evt * script, bool isInitialCall)
SetGroupVisibility()
ApiStatus SetGroupVisibility (Evt * script, bool isInitialCall)
SetInterpCamParams()
ApiStatus SetInterpCamParams (Evt * script, bool isInitialCall)
SetItemAlpha()
ApiStatus SetItemAlpha (Evt * script, bool isInitialCall)
SetItemFlags()
ApiStatus SetItemFlags (Evt * script, bool isInitialCall)
SetItemPos()
ApiStatus SetItemPos (Evt * script, bool isInitialCall)
SetMessageImages()
ApiStatus SetMessageImages (Evt * script, bool isInitialCall)
SetMessageText()
ApiStatus SetMessageText (Evt * script, bool isInitialCall)
SetMessageValue()
ApiStatus SetMessageValue (Evt * script, bool isInitialCall)
SetModelCustomGfx()
ApiStatus SetModelCustomGfx (Evt * script, bool isInitialCall)
SetModelFlags()
ApiStatus SetModelFlags (Evt * script, bool isInitialCall)
SetModelTexVariant()
ApiStatus SetModelTexVariant (Evt * script, bool isInitialCall)
SetMotionBlurParams()
ApiStatus SetMotionBlurParams (Evt * script, bool isInitialCall)
SetMusic()
ApiStatus SetMusic (Evt * script, bool isInitialCall)
Start playing a song.
Parameters
playerID MusicPlayer to use, should almost always be 0 (MUSIC_PLAYER_MAIN).
song Song from SongIDs.
variation
volumeLevel Perceptual loudness from VOL_LEVEL_MUTE to VOL_LEVEL_FULL.
SetNoInterpCamParams()
ApiStatus SetNoInterpCamParams (Evt * script, bool isInitialCall)
SetNpcAnimation()
ApiStatus SetNpcAnimation (Evt * script, bool isInitialCall)
SetNpcAnimationSpeed()
ApiStatus SetNpcAnimationSpeed (Evt * script, bool isInitialCall)
SetNpcAux()
ApiStatus SetNpcAux (Evt * script, bool isInitialCall)
SetNpcCollisionChannel()
ApiStatus SetNpcCollisionChannel (Evt * script, bool isInitialCall)
SetNpcCollisionSize()
ApiStatus SetNpcCollisionSize (Evt * script, bool isInitialCall)
SetNpcDecoration()
ApiStatus SetNpcDecoration (Evt * script, bool isInitialCall)
SetNpcFlagBits()
ApiStatus SetNpcFlagBits (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
SetNpcImgFXFlags()
ApiStatus SetNpcImgFXFlags (Evt * script, bool isInitialCall)
SetNpcImgFXParams()
ApiStatus SetNpcImgFXParams (Evt * script, bool isInitialCall)
SetNpcJumpscale()
ApiStatus SetNpcJumpscale (Evt * script, bool isInitialCall)
SetNpcPaletteSwapLower()
ApiStatus SetNpcPaletteSwapLower (Evt * script, bool isInitialCall)
SetNpcPaletteSwapMode()
ApiStatus SetNpcPaletteSwapMode (Evt * script, bool isInitialCall)
SetNpcPaletteSwapping()
ApiStatus SetNpcPaletteSwapping (Evt * script, bool isInitialCall)
SetNpcPos()
ApiStatus SetNpcPos (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
SetNpcRenderMode()
ApiStatus SetNpcRenderMode (Evt * script, bool isInitialCall)
SetNpcRotation()
ApiStatus SetNpcRotation (Evt * script, bool isInitialCall)
SetNpcRotationPivot()
ApiStatus SetNpcRotationPivot (Evt * script, bool isInitialCall)
SetNpcScale()
ApiStatus SetNpcScale (Evt * script, bool isInitialCall)
SetNpcSpeed()
ApiStatus SetNpcSpeed (Evt * script, bool isInitialCall)
SetNpcSprite()
ApiStatus SetNpcSprite (Evt * script, bool isInitialCall)
SetNpcVar()
ApiStatus SetNpcVar (Evt * script, bool isInitialCall)
SetNpcYaw()
ApiStatus SetNpcYaw (Evt * script, bool isInitialCall)
SetOwnerInstigatorValue()
ApiStatus SetOwnerInstigatorValue (Evt * script, bool isInitialCall)
SetPanTarget()
ApiStatus SetPanTarget (Evt * script, bool isInitialCall)
SetPlayerActionState()
ApiStatus SetPlayerActionState (Evt * script, bool isInitialCall)
SetPlayerAnimation()
ApiStatus SetPlayerAnimation (Evt * script, bool isInitialCall)
SetPlayerAnimationSpeed()
ApiStatus SetPlayerAnimationSpeed (Evt * script, bool isInitialCall)
SetPlayerCollisionSize()
ApiStatus SetPlayerCollisionSize (Evt * script, bool isInitialCall)
Overrides the player collision size.
Parameters
height
diameter
SetPlayerFlagBits()
ApiStatus SetPlayerFlagBits (Evt * script, bool isInitialCall)
SetPlayerImgFXFlags()
ApiStatus SetPlayerImgFXFlags (Evt * script, bool isInitialCall)
SetPlayerJumpscale()
ApiStatus SetPlayerJumpscale (Evt * script, bool isInitialCall)
SetPlayerPos()
ApiStatus SetPlayerPos (Evt * script, bool isInitialCall)
Sets the player position.
Parameters
x
y -1000 is used for hiding the player.
z
See also
GetPlayerPos
Referenced by MAP_RODATA_PAD().
SetPlayerPushVelocity()
ApiStatus SetPlayerPushVelocity (Evt * script, bool isInitialCall)
SetPlayerSpeed()
ApiStatus SetPlayerSpeed (Evt * script, bool isInitialCall)
Sets the move speed of the player for subequent PlayerMoveTo calls.
Parameters
speed Float multiplier.
See also
SetNpcSpeed
SetRenderMode()
ApiStatus SetRenderMode (Evt * script, bool isInitialCall)
SetSelfEnemyFlagBits()
ApiStatus SetSelfEnemyFlagBits (Evt * script, bool isInitialCall)
SetSelfEnemyFlags()
ApiStatus SetSelfEnemyFlags (Evt * script, bool isInitialCall)
SetSelfRotation()
ApiStatus SetSelfRotation (Evt * script, bool isInitialCall)
SetSelfVar()
ApiStatus SetSelfVar (Evt * script, bool isInitialCall)
SetSleepBubbleTimeLeft()
ApiStatus SetSleepBubbleTimeLeft (Evt * script, bool isInitialCall)
SetSpriteShading()
ApiStatus SetSpriteShading (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
SetTattleMessage()
ApiStatus SetTattleMessage (Evt * script, bool isInitialCall)
SetTexPanner()
ApiStatus SetTexPanner (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD(), and MAP_RODATA_PAD().
SetTexPanOffset()
ApiStatus SetTexPanOffset (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
SetTimeFreezeMode()
ApiStatus SetTimeFreezeMode (Evt * script, bool isInitialCall)
SetTrackVolumes()
ApiStatus SetTrackVolumes (Evt * script, bool isInitialCall)
SetTransformGroupEnabled()
ApiStatus SetTransformGroupEnabled (Evt * script, bool isInitialCall)
SetValueByRef()
ApiStatus SetValueByRef (Evt * script, bool isInitialCall)
SetVirtualEntityFlagBits()
ApiStatus SetVirtualEntityFlagBits (Evt * script, bool isInitialCall)
SetVirtualEntityFlags()
ApiStatus SetVirtualEntityFlags (Evt * script, bool isInitialCall)
SetVirtualEntityJumpGravity()
ApiStatus SetVirtualEntityJumpGravity (Evt * script, bool isInitialCall)
SetVirtualEntityMoveSpeed()
ApiStatus SetVirtualEntityMoveSpeed (Evt * script, bool isInitialCall)
SetVirtualEntityPosition()
ApiStatus SetVirtualEntityPosition (Evt * script, bool isInitialCall)
SetVirtualEntityRenderCommands()
ApiStatus SetVirtualEntityRenderCommands (Evt * script, bool isInitialCall)
SetVirtualEntityRenderMode()
ApiStatus SetVirtualEntityRenderMode (Evt * script, bool isInitialCall)
SetVirtualEntityRotation()
ApiStatus SetVirtualEntityRotation (Evt * script, bool isInitialCall)
SetVirtualEntityScale()
ApiStatus SetVirtualEntityScale (Evt * script, bool isInitialCall)
SetZoneEnabled()
ApiStatus SetZoneEnabled (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
ShakeCam()
ApiStatus ShakeCam (Evt * script, bool isInitialCall)
ShowChoice()
ApiStatus ShowChoice (Evt * script, bool isInitialCall)
ShowCoinCounter()
ApiStatus ShowCoinCounter (Evt * script, bool isInitialCall)
ShowConsumableChoicePopup()
ApiStatus ShowConsumableChoicePopup (Evt * script, bool isInitialCall)
ShowEmote()
ApiStatus ShowEmote (Evt * script, bool isInitialCall)
ShowGotItem()
ApiStatus ShowGotItem (Evt * script, bool isInitialCall)
ShowKeyChoicePopup()
ApiStatus ShowKeyChoicePopup (Evt * script, bool isInitialCall)
ShowMerleeCoinMessage()
ApiStatus ShowMerleeCoinMessage (Evt * script, bool isInitialCall)
ShowMerleeRanOutMessage()
ApiStatus ShowMerleeRanOutMessage (Evt * script, bool isInitialCall)
ShowMessageAtScreenPos()
ApiStatus ShowMessageAtScreenPos (Evt * script, bool isInitialCall)
ShowMessageAtWorldPos()
ApiStatus ShowMessageAtWorldPos (Evt * script, bool isInitialCall)
ShowRecoveryShimmer()
ApiStatus ShowRecoveryShimmer (Evt * script, bool isInitialCall)
ShowSleepBubble()
ApiStatus ShowSleepBubble (Evt * script, bool isInitialCall)
ShowStartRecoveryShimmer()
ApiStatus ShowStartRecoveryShimmer (Evt * script, bool isInitialCall)
ShowSweat()
ApiStatus ShowSweat (Evt * script, bool isInitialCall)
ShowWorldStatusBar()
ApiStatus ShowWorldStatusBar (Evt * script, bool isInitialCall)
SpeakToNpc()
ApiStatus SpeakToNpc (Evt * script, bool isInitialCall)
SpeakToPlayer()
ApiStatus SpeakToPlayer (Evt * script, bool isInitialCall)
StartBattle()
ApiStatus StartBattle (Evt * script, bool isInitialCall)
StartBattleWith()
ApiStatus StartBattleWith (Evt * script, bool isInitialCall)
StartBossBattle()
ApiStatus StartBossBattle (Evt * script, bool isInitialCall)
StopSound()
ApiStatus StopSound (Evt * script, bool isInitialCall)
StopTrackingSoundPos()
ApiStatus StopTrackingSoundPos (Evt * script, bool isInitialCall)
SwitchMessage()
ApiStatus SwitchMessage (Evt * script, bool isInitialCall)
TranslateGroup()
ApiStatus TranslateGroup (Evt * script, bool isInitialCall)
TranslateModel()
ApiStatus TranslateModel (Evt * script, bool isInitialCall)
UpdateColliderTransform()
ApiStatus UpdateColliderTransform (Evt * script, bool isInitialCall)
UpdateLerp()
ApiStatus UpdateLerp (Evt * script, bool isInitialCall)
UpdatePlayerImgFX()
ApiStatus UpdatePlayerImgFX (Evt * script, bool isInitialCall)
UseDoorSounds()
ApiStatus UseDoorSounds (Evt * script, bool isInitialCall)
Referenced by MAP_RODATA_PAD().
UseDynamicShadow()
ApiStatus UseDynamicShadow (Evt * script, bool isInitialCall)
UseEntryHeading()
ApiStatus UseEntryHeading (Evt * script, bool isInitialCall)
UseExitHeading()
ApiStatus UseExitHeading (Evt * script, bool isInitialCall)
UseRoomDoorSounds()
ApiStatus UseRoomDoorSounds (Evt * script, bool isInitialCall)
UseSettingsFrom()
ApiStatus UseSettingsFrom (Evt * script, bool isInitialCall)
VirtualEntityJumpTo()
ApiStatus VirtualEntityJumpTo (Evt * script, bool isInitialCall)
VirtualEntityLandJump()
ApiStatus VirtualEntityLandJump (Evt * script, bool isInitialCall)
VirtualEntityMoveTo()
ApiStatus VirtualEntityMoveTo (Evt * script, bool isInitialCall)
WaitForCam()
ApiStatus WaitForCam (Evt * script, bool isInitialCall)
WaitForPlayerInputEnabled()
ApiStatus WaitForPlayerInputEnabled (Evt * script, bool isInitialCall)
WaitForPlayerMoveToComplete()
ApiStatus WaitForPlayerMoveToComplete (Evt * script, bool isInitialCall)
WaitForPlayerTouchingFloor()
ApiStatus WaitForPlayerTouchingFloor (Evt * script, bool isInitialCall)
Variable Documentation
EnemyNpcDefeat
EvtScript EnemyNpcDefeat extern
EnemyNpcHit
EvtScript EnemyNpcHit extern