papermario: src/evt/script_list.c File Reference
script_list.c File Reference
Functions
s32 evt_execute_next_command (Evt *script)
void sort_scripts (void)
void find_script_labels (Evt *script)
void clear_script_list (void)
void init_script_list (void)
void suspend_frozen_scripts (Evt *script)
Evt * start_script (EvtScript *source, s32 priority, s32 flags)
Evt * start_script_in_group (EvtScript *source, u8 priority, u8 flags, u8 groupFlags)
Evt * start_child_script (Evt *parentScript, EvtScript *source, s32 flags)
Evt * func_802C39F8 (Evt *parentScript, Bytecode *nextLine, s32 newState)
Evt * func_802C3C10 (Evt *script, Bytecode *line, s32 arg2)
Evt * restart_script (Evt *script)
void update_scripts (void)
void func_802C3EE4 (void)
void kill_script (Evt *instanceToKill)
void kill_script_by_ID (s32 id)
void kill_all_scripts (void)
s32 does_script_exist (s32 id)
s32 does_script_exist_by_ref (Evt *script)
void set_script_priority (Evt *script, s32 priority)
void set_script_timescale (Evt *script, f32 timescale)
void set_global_timespace (f32 timeScale)
f32 get_global_timespace (void)
void set_script_group (Evt *script, s32 groupFlags)
Trigger * bind_trigger (EvtScript *script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority, s32 arg6)
Trigger * bind_trigger_1 (EvtScript *script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority)
void suspend_group_script (Evt *script, s32 groupFlags)
void resume_group_script (Evt *script, s32 groupFlags)
s32 suspend_all_script (s32 id)
s32 resume_all_script (s32 id)
void suspend_group_script_index (s32 id, s32 groupFlags)
void resume_group_script_index (s32 id, s32 groupFlags)
void suspend_all_group (s32 groupFlags)
s32 resume_all_group (s32 groupFlags)
void suspend_group_others (Evt *script, s32 groupFlags)
void resume_group_others (Evt *script, s32 groupFlags)
Evt * get_script_by_index (s32 index)
Evt * get_script_by_id (s32 id)
void set_script_flags (Evt *script, s32 flags)
void clear_script_flags (Evt *script, s32 flags)
Variables
s32 UniqueScriptCounter = 1
s32 IsUpdatingScripts = FALSE
f32 GlobalTimeRate = 1.0f
BSS u32 * gMapFlags
BSS s32 * gMapVars
BSS s32 gNumScripts
BSS s32 D_802DA48C
BSS ScriptList gWorldScriptList
BSS ScriptList gBattleScriptList
BSS ScriptList * gCurrentScriptListPtr
BSS s32 D_802DA894
BSS s32 gScriptIndexList [MAX_SCRIPTS]
BSS s32 gScriptIdList [MAX_SCRIPTS]
BSS s32 gScriptListCount
BSS s32 D_802DAC9C
BSS char evtDebugPrintBuffer [0x100]
BSS struct LavaReset * gLavaResetList
BSS s32 LastSafeFloor
BSS s32 D_802DADA8 [2]
BSS AnimatedModelList gBattleMeshAnimationList
BSS AnimatedModelList gWorldMeshAnimationList
BSS AnimatedModelList * gCurrentMeshAnimationListPtr
BSS s32 D_802DAE34 [3]
BSS s32 wExtraPartnerID
BSS s32 wExtraPartnerNpcID
BSS s32 D_802DAE4C [2]
BSS s32 ShowMessageScreenOffsetX
BSS s32 ShowMessageScreenOffsetY
BSS s32 D_802DAE58 [2]
BSS char D_802DAE60 [0x400]
BSS MessagePrintState * gCurrentPrintContext
BSS s32 D_802DB264
BSS MessagePrintState * D_802DB268
BSS s32 D_802DB26C
BSS Npc playerNpcData
BSS u16 PlayerImgFXFlags
BSS s32 D_802DB5B4 [3]
BSS VirtualEntityList bBattleVirtualEntityList
BSS VirtualEntityList wWorldVirtualEntityList
BSS VirtualEntityList * gCurrentVirtualEntityListPtr
BSS s32 D_802DB7C4 [3]
BSS MusicEvent * MusicEventList
BSS s32 D_802DB7D4
BSS Evt * RunningMusicEvents [10]
BSS s32 RunningMusicEventIDs [10]
BSS s32 D_802DB828 [2]
BSS PopupMenu D_802DB830
BSS s32 gSpriteShadingHeader
BSS s32 D_802DBB64
BSS s32 gSpriteShadingData
BSS s32 D_802DB8B6C
BSS char D_802DBB70 [0x100]
BSS u32 gWorldMapFlags [MAX_MAPFLAGS]
BSS s32 DoorModelsSwingCW [3]
BSS PushBlockGrid * wPushBlockGrids [8]
BSS u32 gWorldMapVars [MAX_MAPVARS]
BSS u32 gBattleMapVars [MAX_MAPVARS]
BSS s32 DoorModelsSwingCCW [3]
BSS u32 gBattleMapFlags [MAX_MAPFLAGS]
Function Documentation
bind_trigger()
Trigger * bind_trigger (EvtScript * script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority, s32 arg6)
Referenced by bind_trigger_1().
bind_trigger_1()
Trigger * bind_trigger_1 (EvtScript * script, s32 flags, s32 triggerFlagIndex, s32 triggerVar0, s32 triggerVar1, s32 priority)
clear_script_flags()
void clear_script_flags (Evt * script, s32 flags)
Referenced by clear_script_flags(), and update_encounters_neutral().
clear_script_list()
void clear_script_list (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_demo(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
does_script_exist()
s32 does_script_exist (s32 id)
Referenced by _use_partner_ability(), btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_begin_turn(), btl_state_update_celebration(), btl_state_update_change_partner(), btl_state_update_defeat(), btl_state_update_defend(), btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_end_player_turn(), btl_state_update_end_training_battle(), btl_state_update_end_turn(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_next_enemy(), btl_state_update_normal_start(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_victory(), create_encounters(), evt_handle_does_script_exist(), evt_trigger_on_activate_exec_script(), evt_trigger_on_activate_lock(), partner_handle_after_battle(), partner_handle_before_battle(), partner_kill_ability_script(), partner_resume_ability_script(), partner_suspend_ability_script(), state_step_change_map(), state_step_enter_world(), state_step_game_over(), state_step_intro(), update_encounters_conversation(), update_encounters_post_battle(), update_entities(), and update_item_entity_collectable().
does_script_exist_by_ref()
s32 does_script_exist_by_ref (Evt * script)
evt_execute_next_command()
s32 evt_execute_next_command (Evt * script)
Referenced by update_scripts().
find_script_labels()
void find_script_labels (Evt * script)
Referenced by func_802C39F8(), func_802C3C10(), restart_script(), start_child_script(), start_script(), and start_script_in_group().
func_802C39F8()
Evt * func_802C39F8 (Evt * parentScript, Bytecode * nextLine, s32 newState)
Referenced by evt_handle_child_thread().
func_802C3C10()
Evt * func_802C3C10 (Evt * script, Bytecode * line, s32 arg2)
func_802C3EE4()
void func_802C3EE4 (void)
Referenced by gfx_draw_frame().
get_global_timespace()
f32 get_global_timespace (void)
get_script_by_id()
Evt * get_script_by_id (s32 id)
Referenced by update_encounters_neutral(), and worker_update_phonograph_hud().
get_script_by_index()
Evt * get_script_by_index (s32 index)
Referenced by dispatch_event_actor(), and func_802C73B8().
init_script_list()
void init_script_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
kill_all_scripts()
void kill_all_scripts (void)
Referenced by btl_state_update_end_battle(), and btl_state_update_end_demo_battle().
kill_script()
void kill_script (Evt * instanceToKill)
Referenced by evt_handle_end_child_thread(), evt_handle_end_thread(), evt_handle_return(), func_802C3C10(), kill_all_scripts(), kill_script(), and kill_script_by_ID().
kill_script_by_ID()
void kill_script_by_ID (s32 id)
Referenced by _use_partner_ability(), bind_enemy_ai(), bind_enemy_aux(), bind_enemy_interact(), btl_cam_use_preset_impl(), btl_delete_actor(), btl_delete_player_actor(), btl_state_update_celebration(), dispatch_event_actor(), dispatch_event_partner(), dispatch_event_partner_continue_turn(), dispatch_event_player(), dispatch_event_player_continue_turn(), evt_handle_kill(), func_80048E34(), kill_enemy(), partner_handle_after_battle(), partner_handle_before_battle(), partner_kill_ability_script(), start_rumble_type(), and update_encounters_pre_battle().
restart_script()
Evt * restart_script (Evt * script)
Referenced by btl_cam_move(), and evt_handle_jump().
resume_all_group()
s32 resume_all_group (s32 groupFlags)
Referenced by create_encounters(), evt_handle_resume_all(), set_time_freeze_mode(), start_battle(), update_encounters_conversation(), update_encounters_post_battle(), and update_item_entity_collectable().
resume_all_script()
s32 resume_all_script (s32 id)
Referenced by evt_handle_resume(), partner_resume_ability_script(), update_encounters_conversation(), and update_encounters_post_battle().
resume_group_others()
void resume_group_others (Evt * script, s32 groupFlags)
Referenced by evt_handle_resume_others().
resume_group_script()
void resume_group_script (Evt * script, s32 groupFlags)
Referenced by resume_all_group(), resume_all_script(), resume_group_others(), resume_group_script(), and resume_group_script_index().
resume_group_script_index()
void resume_group_script_index (s32 id, s32 groupFlags)
set_global_timespace()
void set_global_timespace (f32 timeScale)
set_script_flags()
void set_script_flags (Evt * script, s32 flags)
Referenced by set_script_flags(), and update_encounters_neutral().
set_script_group()
void set_script_group (Evt * script, s32 groupFlags)
Referenced by evt_handle_set_group().
set_script_priority()
void set_script_priority (Evt * script, s32 priority)
Referenced by evt_handle_set_priority().
set_script_timescale()
void set_script_timescale (Evt * script, f32 timescale)
Referenced by evt_handle_set_timescale(), and worker_update_phonograph_hud().
sort_scripts()
void sort_scripts (void)
Referenced by update_scripts().
start_child_script()
Evt * start_child_script (Evt * parentScript, EvtScript * source, s32 flags)
Referenced by evt_handle_exec_wait().
start_script()
Evt * start_script (EvtScript * source, s32 priority, s32 flags)
Referenced by _use_partner_ability(), bind_enemy_ai(), bind_enemy_aux(), bind_enemy_interact(), btl_cam_use_preset_impl(), btl_state_update_9(), btl_state_update_begin_partner_turn(), btl_state_update_begin_player_turn(), btl_state_update_begin_turn(), btl_state_update_celebration(), btl_state_update_change_partner(), btl_state_update_defeat(), btl_state_update_defend(), btl_state_update_end_battle(), btl_state_update_end_demo_battle(), btl_state_update_end_player_turn(), btl_state_update_end_training_battle(), btl_state_update_end_turn(), btl_state_update_enemy_move(), btl_state_update_enemy_striking_first(), btl_state_update_first_strike(), btl_state_update_next_enemy(), btl_state_update_normal_start(), btl_state_update_partner_move(), btl_state_update_partner_striking_first(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_victory(), calc_enemy_damage_target(), calc_item_damage_enemy(), calc_partner_damage_enemy(), calc_player_damage_enemy(), create_actor(), create_encounters(), dispatch_event_actor(), dispatch_event_partner(), dispatch_event_partner_continue_turn(), dispatch_event_player(), dispatch_event_player_continue_turn(), entity_Chest_adjust_camera(), entity_Chest_reset_camera(), evt_trigger_on_activate_exec_script(), evt_trigger_on_activate_lock(), FireBarAI_Callback(), func_80048E34(), load_partner_actor(), musical_hill_orbit_listener(), partner_handle_after_battle(), red_tree_orbit_listener(), shake_battle_cam_pitch(), shop_owner_begin_speech(), shop_owner_buy_dialog(), shop_owner_continue_speech(), shop_owner_continue_speech_with_quantity(), shop_owner_end_speech(), shop_owner_reset_speech(), start_battle(), start_rumble_type(), update_encounters_neutral(), update_encounters_post_battle(), update_entities(), and use_consumable().
start_script_in_group()
Evt * start_script_in_group (EvtScript * source, u8 priority, u8 flags, u8 groupFlags)
Referenced by evt_handle_exec1(), evt_handle_exec1_get_id(), evt_handle_thread(), exec_ShakeCam1(), exec_ShakeCamX(), load_map_by_IDs(), and update_encounters_post_battle().
suspend_all_group()
void suspend_all_group (s32 groupFlags)
Referenced by evt_handle_suspend_all(), set_time_freeze_mode(), suspend_frozen_scripts(), update_encounters_neutral(), and update_encounters_pre_battle().
suspend_all_script()
s32 suspend_all_script (s32 id)
Referenced by evt_handle_suspend(), partner_suspend_ability_script(), start_battle(), update_encounters_neutral(), and update_encounters_pre_battle().
suspend_frozen_scripts()
void suspend_frozen_scripts (Evt * script)
Referenced by func_802C39F8(), func_802C3C10(), restart_script(), start_child_script(), start_script(), and start_script_in_group().
suspend_group_others()
void suspend_group_others (Evt * script, s32 groupFlags)
Referenced by evt_handle_suspend_others().
suspend_group_script()
void suspend_group_script (Evt * script, s32 groupFlags)
Referenced by resume_group_script(), suspend_all_group(), suspend_all_script(), suspend_group_others(), suspend_group_script(), and suspend_group_script_index().
suspend_group_script_index()
void suspend_group_script_index (s32 id, s32 groupFlags)
update_scripts()
void update_scripts (void)
Referenced by step_game_loop().
Variable Documentation
bBattleVirtualEntityList
BSS VirtualEntityList bBattleVirtualEntityList
Referenced by clear_virtual_entity_list(), and init_virtual_entity_list().
D_802DA48C
BSS s32 D_802DA48C
D_802DA894
BSS s32 D_802DA894
D_802DAC9C
BSS s32 D_802DAC9C
D_802DADA8
BSS s32 D_802DADA8[2]
D_802DAE34
BSS s32 D_802DAE34[3]
D_802DAE4C
BSS s32 D_802DAE4C[2]
D_802DAE58
BSS s32 D_802DAE58[2]
D_802DAE60
BSS char D_802DAE60[0x400]
D_802DB264
BSS s32 D_802DB264
Referenced by _show_message().
D_802DB268
BSS MessagePrintState* D_802DB268
D_802DB26C
BSS s32 D_802DB26C
D_802DB5B4
BSS s32 D_802DB5B4[3]
D_802DB7C4
BSS s32 D_802DB7C4[3]
D_802DB7D4
BSS s32 D_802DB7D4
D_802DB828
BSS s32 D_802DB828[2]
D_802DB830
BSS PopupMenu D_802DB830
D_802DB8B6C
BSS s32 D_802DB8B6C
D_802DBB64
BSS s32 D_802DBB64
D_802DBB70
BSS char D_802DBB70[0x100]
DoorModelsSwingCCW
BSS s32 DoorModelsSwingCCW[3]
DoorModelsSwingCW
BSS s32 DoorModelsSwingCW[3]
evtDebugPrintBuffer
BSS char evtDebugPrintBuffer[0x100]
Referenced by evt_handle_print_debug_var().
gBattleMapFlags
BSS u32 gBattleMapFlags[MAX_MAPFLAGS]
Referenced by clear_script_list(), and init_script_list().
gBattleMapVars
BSS u32 gBattleMapVars[MAX_MAPVARS]
Referenced by clear_script_list(), and init_script_list().
gBattleMeshAnimationList
BSS AnimatedModelList gBattleMeshAnimationList
Referenced by init_model_animators(), and reset_model_animators().
gBattleScriptList
BSS ScriptList gBattleScriptList
Referenced by clear_script_list(), and init_script_list().
gCurrentMeshAnimationListPtr
BSS AnimatedModelList* gCurrentMeshAnimationListPtr
Referenced by init_model_animators(), and reset_model_animators().
gCurrentPrintContext
BSS MessagePrintState* gCurrentPrintContext
Referenced by _show_message(), and cancel_current_message().
gCurrentScriptListPtr
BSS ScriptList* gCurrentScriptListPtr
Referenced by clear_script_list(), does_script_exist_by_ref(), func_802C39F8(), func_802C3EE4(), get_script_by_id(), get_script_by_index(), init_script_list(), kill_script(), sort_scripts(), start_child_script(), start_script(), and start_script_in_group().
gCurrentVirtualEntityListPtr
BSS VirtualEntityList* gCurrentVirtualEntityListPtr
Referenced by ALT_virtual_entity_create(), clear_virtual_entity_list(), init_virtual_entity_list(), virtual_entity_create(), virtual_entity_create_at_index(), virtual_entity_delete_by_ref(), virtual_entity_get_by_index(), virtual_entity_list_render_UI(), virtual_entity_list_render_world(), and virtual_entity_list_update().
gLavaResetList
BSS struct LavaReset* gLavaResetList
Referenced by get_lava_reset_pos().
GlobalTimeRate
f32 GlobalTimeRate = 1.0f
Referenced by func_802C39F8(), func_802C3C10(), get_global_timespace(), restart_script(), set_global_timespace(), set_script_timescale(), start_child_script(), start_script(), and start_script_in_group().
gMapFlags
BSS u32* gMapFlags
Referenced by clear_script_list(), evt_get_float_variable(), evt_get_variable(), evt_handle_print_debug_var(), evt_set_float_variable(), evt_set_variable(), and init_script_list().
gMapVars
BSS s32* gMapVars
Referenced by clear_script_list(), evt_get_float_variable(), evt_get_variable(), evt_handle_print_debug_var(), evt_set_float_variable(), evt_set_variable(), and init_script_list().
gNumScripts
BSS s32 gNumScripts
Referenced by clear_script_list(), func_802C39F8(), init_script_list(), kill_script(), start_child_script(), start_script(), and start_script_in_group().
gScriptIdList
BSS s32 gScriptIdList[MAX_SCRIPTS]
Referenced by func_802C39F8(), func_802C3EE4(), sort_scripts(), start_child_script(), start_script(), start_script_in_group(), and update_scripts().
gScriptIndexList
BSS s32 gScriptIndexList[MAX_SCRIPTS]
Referenced by func_802C39F8(), func_802C3EE4(), sort_scripts(), start_child_script(), start_script(), start_script_in_group(), and update_scripts().
gScriptListCount
BSS s32 gScriptListCount
Referenced by clear_script_list(), func_802C39F8(), func_802C3EE4(), sort_scripts(), start_child_script(), start_script(), start_script_in_group(), and update_scripts().
gSpriteShadingData
BSS s32 gSpriteShadingData
gSpriteShadingHeader
BSS s32 gSpriteShadingHeader
gWorldMapFlags
BSS u32 gWorldMapFlags[MAX_MAPFLAGS]
Referenced by clear_script_list(), and init_script_list().
gWorldMapVars
BSS u32 gWorldMapVars[MAX_MAPVARS]
Referenced by clear_script_list(), and init_script_list().
gWorldMeshAnimationList
BSS AnimatedModelList gWorldMeshAnimationList
Referenced by init_model_animators(), and reset_model_animators().
gWorldScriptList
BSS ScriptList gWorldScriptList
Referenced by clear_script_list(), and init_script_list().
IsUpdatingScripts
s32 IsUpdatingScripts = FALSE
Referenced by clear_script_list(), func_802C39F8(), init_script_list(), start_child_script(), start_script(), start_script_in_group(), and update_scripts().
LastSafeFloor
BSS s32 LastSafeFloor
Referenced by get_lava_reset_pos().
MusicEventList
BSS MusicEvent* MusicEventList
PlayerImgFXFlags
BSS u16 PlayerImgFXFlags
playerNpcData
BSS Npc playerNpcData
RunningMusicEventIDs
BSS s32 RunningMusicEventIDs[10]
RunningMusicEvents
BSS Evt* RunningMusicEvents[10]
ShowMessageScreenOffsetX
BSS s32 ShowMessageScreenOffsetX
Referenced by _show_message().
ShowMessageScreenOffsetY
BSS s32 ShowMessageScreenOffsetY
Referenced by _show_message().
UniqueScriptCounter
s32 UniqueScriptCounter = 1
Referenced by func_802C39F8(), start_child_script(), start_script(), and start_script_in_group().
wExtraPartnerID
BSS s32 wExtraPartnerID
wExtraPartnerNpcID
BSS s32 wExtraPartnerNpcID
wPushBlockGrids
BSS PushBlockGrid* wPushBlockGrids[8]
wWorldVirtualEntityList
BSS VirtualEntityList wWorldVirtualEntityList
Referenced by clear_virtual_entity_list(), and init_virtual_entity_list().