papermario: src/audio/sfx.c File Reference
sfx.c File Reference
Macros
#define MAX_SOUND_INSTANCES 10
#define SOUND_LOOP_IDX(soundID) (soundID & 0xFFFF)
#define SEQ_SOUND_ENTRY(soundID, sym) [soundID & 0xFFFF] { .sounds = sym, .soundCount = ARRAY_COUNT(sym) }
Functions
void sfx_compute_spatialized_sound_params_full (f32 x, f32 y, f32 z, s16 *volume, s16 *pan, s32 flags)
void sfx_reset_door_sounds (void)
void sfx_clear_sounds (void)
void sfx_clear_env_sounds (s16 playSounds)
void sfx_update_env_sound_params (void)
void sfx_set_reverb_mode (s32 mode)
s32 sfx_get_reverb_mode (void)
void sfx_stop_env_sounds (void)
SoundInstance * sfx_get_env_sound_instance (s32 soundID)
void sfx_play_sound_looping (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void sfx_register_looping_sound_at_position (s32 soundID, s32 flags, f32 x, f32 y, f32 z)
s32 sfx_adjust_env_sound_pos (s32 soundID, s32 sourceFlags, f32 x, f32 y, f32 z)
void snd_stop_tracking_env_sound_pos (s32 soundID, s32 keepPlaying)
void sfx_play_sound_with_params (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void sfx_adjust_env_sound_params (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void sfx_stop_sound (s32 soundID)
void sfx_play_sound (s32 soundID)
void sfx_play_sound_at_player (s32 soundID, s32 flags)
void sfx_play_sound_at_npc (s32 soundID, s32 flags, s32 npcID)
void sfx_play_sound_at_position (s32 soundID, s32 flags, f32 posX, f32 posY, f32 posZ)
void sfx_get_spatialized_sound_params (f32 x, f32 y, f32 z, s16 *volume, s16 *pan, s32 flags)
void sfx_compute_spatialized_sound_params_ignore_depth (f32 x, f32 y, f32 z, s16 *volume, s16 *pan)
void sfx_compute_spatialized_sound_params_with_depth (f32 x, f32 y, f32 z, s16 *volume, s16 *pan)
Variables
u16 gCurrentDoorSounds
u16 gCurrentRoomDoorSounds
s32 LoopingSounds []
s32 FireBar0Sounds [] = { SOUND_FIRE_BAR_0_A, SOUND_FIRE_BAR_0_B }
s32 FireBar1Sounds [] = { SOUND_FIRE_BAR_1_A, SOUND_FIRE_BAR_1_B }
s32 FireBar2Sounds [] = { SOUND_FIRE_BAR_2_A, SOUND_FIRE_BAR_2_B }
s32 FireBar3Sounds [] = { SOUND_FIRE_BAR_3_A, SOUND_FIRE_BAR_3_B }
s32 FireBar4Sounds [] = { SOUND_FIRE_BAR_4_A, SOUND_FIRE_BAR_4_B }
s32 FireBar5Sounds [] = { SOUND_FIRE_BAR_5_A, SOUND_FIRE_BAR_5_B }
s32 FireBar6Sounds [] = { SOUND_FIRE_BAR_6_A, SOUND_FIRE_BAR_6_B }
s32 FireBar7Sounds [] = { SOUND_FIRE_BAR_7_A, SOUND_FIRE_BAR_7_B }
s32 FireBar8Sounds [] = { SOUND_FIRE_BAR_8_A, SOUND_FIRE_BAR_8_B }
s32 FireBar9Sounds [] = { SOUND_FIRE_BAR_9_A, SOUND_FIRE_BAR_9_B }
s32 FireBarDeadSounds [] = { SOUND_FIRE_BAR_DEAD, SOUND_FIRE_BAR_DEAD }
s32 AlertSounds [] = { SOUND_AI_ALERT_A, SOUND_AI_ALERT_B }
s32 SnoreInhaleSounds [] = { SOUND_SNORE_INHALE_A, SOUND_SNORE_INHALE_B }
s32 SnoreExhaleSounds [] = { SOUND_SNORE_EXHALE_A, SOUND_SNORE_EXHALE_B }
s32 SnapAwakeSounds [] = { SOUND_SNAP_AWAKE_A, SOUND_SNAP_AWAKE_B }
s32 BooVanishSounds [] = { SOUND_BOO_VANISH_A, SOUND_BOO_VANISH_B }
s32 BooAppearSounds [] = { SOUND_BOO_APPEAR_A, SOUND_BOO_APPEAR_B }
s32 WindowOpenSounds [] = { SOUND_WINDOW_OPEN_A, SOUND_WINDOW_OPEN_B }
s32 WindowCloseSounds [] = { SOUND_WINDOW_CLOSE_A, SOUND_WINDOW_CLOSE_B }
s32 RavenLeapSounds [] = { SOUND_RAVEN_LEAP_A, SOUND_RAVEN_LEAP_B }
s32 RavenFallSounds [] = { SOUND_RAVEN_FALL_A, SOUND_RAVEN_FALL_B, SOUND_RAVEN_FALL_C }
s32 ShootingStarFallSounds [] = { SOUND_SHOOTING_STAR_FALL_A, SOUND_SHOOTING_STAR_FALL_B }
s32 ShootingStarBounceSounds [] = { SOUND_STAR_BOUNCE_A, SOUND_STAR_BOUNCE_B }
s32 FuzzyHopSounds [] = { SOUND_FUZZY_HOP_A, SOUND_FUZZY_HOP_B, SOUND_FUZZY_HOP_C }
s32 BulletBillExplodeSounds [] = { SOUND_BULLET_BILL_EXPLODE_A, SOUND_BULLET_BILL_EXPLODE_B }
s32 LuigiStepSounds [] = { SOUND_LUIGI_STEP_A, SOUND_LUIGI_STEP_B }
s32 TrainChugSounds [] = { SOUND_TRAIN_CHUG_A, SOUND_TRAIN_CHUG_B }
s32 FinaleBridgeCollapseSounds [] = { SOUND_KPA_BRIDGE_COLLAPSE_A, SOUND_KPA_BRIDGE_COLLAPSE_B }
s32 FinaleExplosionSounds [] = { SOUND_KPA_EXPLOSION_A, SOUND_KPA_EXPLOSION_B }
s32 CardShuffleSounds [] = { SOUND_SHUFFLE_CARD_A, SOUND_SHUFFLE_CARD_B }
s32 StarSpiritAppearSounds [] = { SOUND_STAR_SPIRIT_APPEAR_A, SOUND_STAR_SPIRIT_APPEAR_B }
s32 StarSpiritCastSounds [] = { SOUND_STAR_SPIRIT_CAST_A, SOUND_STAR_SPIRIT_CAST_B }
s32 UnusedExplodeSounds [] = { SOUND_BULLET_BILL_EXPLODE_A, SOUND_BULLET_BILL_EXPLODE_B }
s32 ShyGuyStepSounds [] = { SOUND_SHY_GUY_STEP_A, SOUND_SHY_GUY_STEP_B }
AlternatingSoundSet AlternatingSounds []
s32 OpenCloseSounds [][2]
BSS SoundInstance wEnvSounds [10]
BSS SoundInstance bEnvSounds [10]
BSS SoundInstance * gCurrentEnvSounds
BSS s32 SfxReverbMode
Macro Definition Documentation
MAX_SOUND_INSTANCES
#define MAX_SOUND_INSTANCES 10
Referenced by sfx_clear_env_sounds(), sfx_get_env_sound_instance(), sfx_play_sound_looping(), sfx_register_looping_sound_at_position(), sfx_stop_env_sounds(), and sfx_update_env_sound_params().
SEQ_SOUND_ENTRY
#define SEQ_SOUND_ENTRY (soundID, sym) [soundID & 0xFFFF] { .sounds = sym, .soundCount = ARRAY_COUNT(sym) }
SOUND_LOOP_IDX
#define SOUND_LOOP_IDX (soundID) (soundID & 0xFFFF)
Function Documentation
sfx_adjust_env_sound_params()
void sfx_adjust_env_sound_params (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by update().
sfx_adjust_env_sound_pos()
s32 sfx_adjust_env_sound_pos (s32 soundID, s32 sourceFlags, f32 x, f32 y, f32 z)
Referenced by SentinelAI_Descend().
sfx_clear_env_sounds()
void sfx_clear_env_sounds (s16 playSounds)
Referenced by load_map_by_IDs(), state_step_battle(), state_step_end_battle(), state_step_exit_language_select(), state_step_language_select(), state_step_pause(), and state_step_unpause().
sfx_clear_sounds()
void sfx_clear_sounds (void)
Referenced by load_engine_data(), and state_step_startup().
sfx_compute_spatialized_sound_params_full()
void sfx_compute_spatialized_sound_params_full (f32 x, f32 y, f32 z, s16 * volume, s16 * pan, s32 flags)
Referenced by sfx_get_spatialized_sound_params().
sfx_compute_spatialized_sound_params_ignore_depth()
void sfx_compute_spatialized_sound_params_ignore_depth (f32 x, f32 y, f32 z, s16 * volume, s16 * pan)
Referenced by sfx_get_spatialized_sound_params().
sfx_compute_spatialized_sound_params_with_depth()
void sfx_compute_spatialized_sound_params_with_depth (f32 x, f32 y, f32 z, s16 * volume, s16 * pan)
Referenced by sfx_get_spatialized_sound_params().
sfx_get_env_sound_instance()
SoundInstance * sfx_get_env_sound_instance (s32 soundID)
Referenced by sfx_adjust_env_sound_params(), sfx_adjust_env_sound_pos(), and snd_stop_tracking_env_sound_pos().
sfx_get_reverb_mode()
s32 sfx_get_reverb_mode (void)
Referenced by state_step_pause().
sfx_get_spatialized_sound_params()
void sfx_get_spatialized_sound_params (f32 x, f32 y, f32 z, s16 * volume, s16 * pan, s32 flags)
Referenced by sfx_play_sound_at_position(), and sfx_update_env_sound_params().
sfx_play_sound()
void sfx_play_sound (s32 soundID)
Referenced by _use_partner_ability(), btl_main_menu_update(), btl_state_update_begin_player_turn(), btl_state_update_celebration(), btl_state_update_defeat(), btl_state_update_partner_menu(), btl_state_update_partner_move(), btl_state_update_player_menu(), btl_state_update_player_move(), btl_state_update_run_away(), btl_state_update_select_target(), btl_submenu_moves_update(), btl_update_ko_status(), btl_update_strats_menu(), calc_player_damage_enemy(), can_open_world_menu(), card_worker_update(), check_input_open_menus(), check_input_status_bar(), coin_counter_draw_content(), entity_BlueWarpPipe_enter_pipe_init(), entity_Chest_begin_opening(), entity_CymbalPlant_idle(), entity_HeartBlockContent__anim_heal(), entity_HiddenPanel_flip_over(), entity_Padlock_idle(), entity_SaveBlock_show_result_message(), entity_StarBoxLauncher_launch(), entity_WoodenCrate_idle(), filemenu_choose_name_handle_input(), filemenu_main_handle_input(), filemenu_selectlanguage_handle_input(), filemenu_yesno_handle_input(), func_800F16CC(), func_802BB34C_E2DC7C(), func_802BC3E4_E2ED14(), hud_element_update(), inflict_partner_ko(), partner_use_ability(), pause_badges_handle_input(), pause_handle_input(), pause_init(), pause_items_handle_input(), pause_map_handle_input(), pause_partners_handle_input(), pause_spirits_handle_input(), pause_stats_handle_input(), pause_tabs_handle_input(), pause_tutorial_input(), popup_menu_update(), remove_player_buffs(), should_cancel_open_world_menu(), state_step_title_screen(), step_entity_commandlist(), update(), update_encounters_neutral(), update_item_entity_pickup(), and update_status_bar().
sfx_play_sound_at_npc()
void sfx_play_sound_at_npc (s32 soundID, s32 flags, s32 npcID)
Referenced by update_riding_physics().
sfx_play_sound_at_player()
void sfx_play_sound_at_player (s32 soundID, s32 flags)
Referenced by action_hammer_end_swing(), action_hammer_play_hit_fx(), action_update_hammer(), action_update_hit_lava(), action_update_jump(), action_update_land(), action_update_parasol(), action_update_peach_land(), action_update_sliding(), action_update_spin(), action_update_spin_jump(), action_update_tornado_jump(), action_update_use_munchlesia(), action_update_use_tweester(), appendGfx_pulse_stone_icon(), ispy_notification_update(), phys_player_land(), player_jump(), and try_player_footstep_sounds().
sfx_play_sound_at_position()
void sfx_play_sound_at_position (s32 soundID, s32 flags, f32 posX, f32 posY, f32 posZ)
sfx_play_sound_looping()
void sfx_play_sound_looping (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by sfx_play_sound_with_params().
sfx_play_sound_with_params()
void sfx_play_sound_with_params (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by _update_message(), appendGfx_score_display(), card_worker_update(), msg_copy_to_print_buffer(), msg_play_speech_sound(), sfx_play_sound(), sfx_play_sound_at_position(), update(), and update_riding_physics().
sfx_register_looping_sound_at_position()
void sfx_register_looping_sound_at_position (s32 soundID, s32 flags, f32 x, f32 y, f32 z)
Referenced by sfx_play_sound_at_position().
sfx_reset_door_sounds()
void sfx_reset_door_sounds (void)
Referenced by load_map_by_IDs(), and sfx_clear_sounds().
sfx_set_reverb_mode()
void sfx_set_reverb_mode (s32 mode)
Referenced by load_map_by_IDs(), sfx_clear_sounds(), state_init_title_screen(), state_step_pause(), and state_step_unpause().
sfx_stop_env_sounds()
void sfx_stop_env_sounds (void)
Referenced by load_map_by_IDs(), state_step_battle(), state_step_end_battle(), state_step_language_select(), state_step_pause(), and step_game_loop().
sfx_stop_sound()
void sfx_stop_sound (s32 soundID)
Referenced by action_update_spin(), free(), phys_update_action_state(), pre_battle(), pre_battle(), SentinelAI_LosePlayerInit(), set_action_state(), update(), and update_encounters_pre_battle().
sfx_update_env_sound_params()
void sfx_update_env_sound_params (void)
Referenced by step_game_loop().
snd_stop_tracking_env_sound_pos()
void snd_stop_tracking_env_sound_pos (s32 soundID, s32 keepPlaying)
Referenced by func_802BB34C_E2DC7C(), and sfx_stop_sound().
Variable Documentation
AlertSounds
s32 AlertSounds[] = { SOUND_AI_ALERT_A, SOUND_AI_ALERT_B }
AlternatingSounds
AlternatingSoundSet AlternatingSounds[]
Referenced by sfx_play_sound_with_params().
bEnvSounds
BSS SoundInstance bEnvSounds[10]
Referenced by sfx_clear_env_sounds(), sfx_clear_sounds(), and sfx_stop_env_sounds().
BooAppearSounds
s32 BooAppearSounds[] = { SOUND_BOO_APPEAR_A, SOUND_BOO_APPEAR_B }
BooVanishSounds
s32 BooVanishSounds[] = { SOUND_BOO_VANISH_A, SOUND_BOO_VANISH_B }
BulletBillExplodeSounds
s32 BulletBillExplodeSounds[] = { SOUND_BULLET_BILL_EXPLODE_A, SOUND_BULLET_BILL_EXPLODE_B }
CardShuffleSounds
s32 CardShuffleSounds[] = { SOUND_SHUFFLE_CARD_A, SOUND_SHUFFLE_CARD_B }
FinaleBridgeCollapseSounds
s32 FinaleBridgeCollapseSounds[] = { SOUND_KPA_BRIDGE_COLLAPSE_A, SOUND_KPA_BRIDGE_COLLAPSE_B }
FinaleExplosionSounds
s32 FinaleExplosionSounds[] = { SOUND_KPA_EXPLOSION_A, SOUND_KPA_EXPLOSION_B }
FireBar0Sounds
s32 FireBar0Sounds[] = { SOUND_FIRE_BAR_0_A, SOUND_FIRE_BAR_0_B }
FireBar1Sounds
s32 FireBar1Sounds[] = { SOUND_FIRE_BAR_1_A, SOUND_FIRE_BAR_1_B }
FireBar2Sounds
s32 FireBar2Sounds[] = { SOUND_FIRE_BAR_2_A, SOUND_FIRE_BAR_2_B }
FireBar3Sounds
s32 FireBar3Sounds[] = { SOUND_FIRE_BAR_3_A, SOUND_FIRE_BAR_3_B }
FireBar4Sounds
s32 FireBar4Sounds[] = { SOUND_FIRE_BAR_4_A, SOUND_FIRE_BAR_4_B }
FireBar5Sounds
s32 FireBar5Sounds[] = { SOUND_FIRE_BAR_5_A, SOUND_FIRE_BAR_5_B }
FireBar6Sounds
s32 FireBar6Sounds[] = { SOUND_FIRE_BAR_6_A, SOUND_FIRE_BAR_6_B }
FireBar7Sounds
s32 FireBar7Sounds[] = { SOUND_FIRE_BAR_7_A, SOUND_FIRE_BAR_7_B }
FireBar8Sounds
s32 FireBar8Sounds[] = { SOUND_FIRE_BAR_8_A, SOUND_FIRE_BAR_8_B }
FireBar9Sounds
s32 FireBar9Sounds[] = { SOUND_FIRE_BAR_9_A, SOUND_FIRE_BAR_9_B }
FireBarDeadSounds
s32 FireBarDeadSounds[] = { SOUND_FIRE_BAR_DEAD, SOUND_FIRE_BAR_DEAD }
FuzzyHopSounds
s32 FuzzyHopSounds[] = { SOUND_FUZZY_HOP_A, SOUND_FUZZY_HOP_B, SOUND_FUZZY_HOP_C }
gCurrentDoorSounds
u16 gCurrentDoorSounds
Referenced by sfx_play_sound_with_params(), and sfx_reset_door_sounds().
gCurrentEnvSounds
BSS SoundInstance* gCurrentEnvSounds
Referenced by sfx_clear_env_sounds(), sfx_clear_sounds(), sfx_get_env_sound_instance(), sfx_play_sound_looping(), sfx_register_looping_sound_at_position(), sfx_stop_env_sounds(), and sfx_update_env_sound_params().
gCurrentRoomDoorSounds
u16 gCurrentRoomDoorSounds
Referenced by sfx_play_sound_with_params(), and sfx_reset_door_sounds().
LoopingSounds
s32 LoopingSounds[]
Referenced by sfx_adjust_env_sound_params(), sfx_play_sound_at_position(), sfx_play_sound_with_params(), and sfx_stop_sound().
LuigiStepSounds
s32 LuigiStepSounds[] = { SOUND_LUIGI_STEP_A, SOUND_LUIGI_STEP_B }
OpenCloseSounds
s32 OpenCloseSounds[][2]
Initial value:
= {
    { SOUND_BASIC_DOOR_OPEN, SOUND_BASIC_DOOR_CLOSE },
    { SOUND_METAL_DOOR_OPEN, SOUND_METAL_DOOR_CLOSE },
    { SOUND_LARGE_DOOR_OPEN, SOUND_LARGE_DOOR_CLOSE },
    { SOUND_CREAKY_DOOR_OPEN, SOUND_CREAKY_DOOR_CLOSE },
    { SOUND_METAL_GATE_OPEN, SOUND_METAL_GATE_CLOSE },
    { SOUND_WINDOW_OPEN_A, SOUND_WINDOW_CLOSE_A },
    { SOUND_CREAKY_WINDOW_OPEN, SOUND_CREAKY_WINDOW_CLOSE },
}
Referenced by sfx_play_sound_with_params().
RavenFallSounds
s32 RavenFallSounds[] = { SOUND_RAVEN_FALL_A, SOUND_RAVEN_FALL_B, SOUND_RAVEN_FALL_C }
RavenLeapSounds
s32 RavenLeapSounds[] = { SOUND_RAVEN_LEAP_A, SOUND_RAVEN_LEAP_B }
SfxReverbMode
BSS s32 SfxReverbMode
Referenced by sfx_get_reverb_mode(), and sfx_set_reverb_mode().
ShootingStarBounceSounds
s32 ShootingStarBounceSounds[] = { SOUND_STAR_BOUNCE_A, SOUND_STAR_BOUNCE_B }
ShootingStarFallSounds
s32 ShootingStarFallSounds[] = { SOUND_SHOOTING_STAR_FALL_A, SOUND_SHOOTING_STAR_FALL_B }
ShyGuyStepSounds
s32 ShyGuyStepSounds[] = { SOUND_SHY_GUY_STEP_A, SOUND_SHY_GUY_STEP_B }
SnapAwakeSounds
s32 SnapAwakeSounds[] = { SOUND_SNAP_AWAKE_A, SOUND_SNAP_AWAKE_B }
SnoreExhaleSounds
s32 SnoreExhaleSounds[] = { SOUND_SNORE_EXHALE_A, SOUND_SNORE_EXHALE_B }
SnoreInhaleSounds
s32 SnoreInhaleSounds[] = { SOUND_SNORE_INHALE_A, SOUND_SNORE_INHALE_B }
StarSpiritAppearSounds
s32 StarSpiritAppearSounds[] = { SOUND_STAR_SPIRIT_APPEAR_A, SOUND_STAR_SPIRIT_APPEAR_B }
StarSpiritCastSounds
s32 StarSpiritCastSounds[] = { SOUND_STAR_SPIRIT_CAST_A, SOUND_STAR_SPIRIT_CAST_B }
TrainChugSounds
s32 TrainChugSounds[] = { SOUND_TRAIN_CHUG_A, SOUND_TRAIN_CHUG_B }
UnusedExplodeSounds
s32 UnusedExplodeSounds[] = { SOUND_BULLET_BILL_EXPLODE_A, SOUND_BULLET_BILL_EXPLODE_B }
wEnvSounds
BSS SoundInstance wEnvSounds[10]
Referenced by sfx_clear_env_sounds(), sfx_clear_sounds(), and sfx_stop_env_sounds().
WindowCloseSounds
s32 WindowCloseSounds[] = { SOUND_WINDOW_CLOSE_A, SOUND_WINDOW_CLOSE_B }
WindowOpenSounds
s32 WindowOpenSounds[] = { SOUND_WINDOW_OPEN_A, SOUND_WINDOW_OPEN_B }