papermario: src/effects/shape_spell.c File Reference
shape_spell.c File Reference
Data Structures
struct UnkStruct
Functions
void shape_spell_appendGfx (void *effect)
void shape_spell_init (EffectInstance *effect)
void shape_spell_update (EffectInstance *effect)
void shape_spell_render (EffectInstance *effect)
EffectInstance * shape_spell_main (s32 isChild, f32 x, f32 y, f32 z, f32 arg4, f32 arg5, f32 arg6, s32 arg7)
s32 func_E0024324 (s32 arg0, s32 arg1)
s32 func_E00243BC (s32 arg0, s32 arg1)
Variables
Gfx D_09001080_33AFE0 []
Gfx D_09001128_33B088 []
Gfx D_09001150_33B0B0 []
Gfx D_09001178_33B0D8 []
Gfx D_090011A0_33B100 []
Gfx D_090011C8_33B128 []
Gfx D_090011F0_33B150 []
UnkStruct D_E0024CC0 []
Data Structure Documentation
UnkStruct
struct UnkStruct
Data Fields
Gfx * displayList
s16 height
u8 sizeScale
s32 unk_00
u8 unk_00
s8 unk_00
u8 unk_01
s8 unk_01
u8 unk_02
s16 unk_02
u8 unk_03
s32 unk_04
Gfx * unk_04
s16 unk_04
s16 unk_06
f32 unk_08
Gfx * unk_08
s32 unk_08
char unk_09[1]
f32 unk_0C
s32 unk_10
s32 unk_14
s16 width
s16 x
s16 y
Function Documentation
func_E0024324()
s32 func_E0024324 (s32 arg0, s32 arg1)
Referenced by shape_spell_appendGfx().
func_E00243BC()
s32 func_E00243BC (s32 arg0, s32 arg1)
Referenced by shape_spell_appendGfx().
shape_spell_appendGfx()
void shape_spell_appendGfx (void * effect)
Referenced by shape_spell_render().
shape_spell_init()
void shape_spell_init (EffectInstance * effect)
Referenced by shape_spell_main().
shape_spell_main()
EffectInstance * shape_spell_main (s32 isChild, f32 x, f32 y, f32 z, f32 arg4, f32 arg5, f32 arg6, s32 arg7)
Referenced by shape_spell_update().
shape_spell_render()
void shape_spell_render (EffectInstance * effect)
Referenced by shape_spell_main().
shape_spell_update()
void shape_spell_update (EffectInstance * effect)
Referenced by shape_spell_main().
Variable Documentation
D_09001080_33AFE0
Gfx D_09001080_33AFE0[] extern
Referenced by shape_spell_appendGfx().
D_09001128_33B088
Gfx D_09001128_33B088[] extern
D_09001150_33B0B0
Gfx D_09001150_33B0B0[] extern
D_09001178_33B0D8
Gfx D_09001178_33B0D8[] extern
D_090011A0_33B100
Gfx D_090011A0_33B100[] extern
D_090011C8_33B128
Gfx D_090011C8_33B128[] extern
D_090011F0_33B150
Gfx D_090011F0_33B150[] extern
D_E0024CC0
UnkStruct D_E0024CC0[]
Initial value:
= {
    {   0, 255, 208,  26, D_09001128_33B088, D_090011A0_33B100 },
    { 120,  77, 208, 254, D_09001150_33B0B0, D_090011C8_33B128 },
    { 240, 254,  76, 110, D_09001178_33B0D8, D_090011F0_33B150 }
}
Referenced by shape_spell_appendGfx().