papermario: src/effects/shattering_stones.c File Reference
shattering_stones.c File Reference
Functions
void shattering_stones_init (EffectInstance *effect)
void shattering_stones_update (EffectInstance *effect)
void shattering_stones_render (EffectInstance *effect)
void shattering_stones_appendGfx (void *effect)
void shattering_stones_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
Variables
Gfx D_09000C00_341480 []
Gfx D_09001068_3418E8 []
Gfx D_09001080_341900 []
Gfx D_09001098_341918 []
Gfx D_090010B8_341938 []
Gfx D_090010D0_341950 []
Gfx D_090010E8_341968 []
Gfx D_09001108_341988 []
Gfx D_09001120_3419A0 []
Gfx D_09001138_3419B8 []
Gfx * D_E002C940 []
f32 D_E002C964 []
f32 D_E002C984 [][2]
Function Documentation
shattering_stones_appendGfx()
void shattering_stones_appendGfx (void * effect)
Referenced by shattering_stones_render().
shattering_stones_init()
void shattering_stones_init (EffectInstance * effect)
Referenced by shattering_stones_main().
shattering_stones_main()
void shattering_stones_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
shattering_stones_render()
void shattering_stones_render (EffectInstance * effect)
Referenced by shattering_stones_main().
shattering_stones_update()
void shattering_stones_update (EffectInstance * effect)
Referenced by shattering_stones_main().
Variable Documentation
D_09000C00_341480
Gfx D_09000C00_341480[] extern
Referenced by shattering_stones_appendGfx().
D_09001068_3418E8
Gfx D_09001068_3418E8[] extern
D_09001080_341900
Gfx D_09001080_341900[] extern
D_09001098_341918
Gfx D_09001098_341918[] extern
D_090010B8_341938
Gfx D_090010B8_341938[] extern
D_090010D0_341950
Gfx D_090010D0_341950[] extern
D_090010E8_341968
Gfx D_090010E8_341968[] extern
D_09001108_341988
Gfx D_09001108_341988[] extern
D_09001120_3419A0
Gfx D_09001120_3419A0[] extern
D_09001138_3419B8
Gfx D_09001138_3419B8[] extern
D_E002C940
Gfx* D_E002C940[]
Initial value:
= {
    D_09001138_3419B8, D_09001120_3419A0, D_09001108_341988,
    D_090010E8_341968, D_090010D0_341950, D_090010B8_341938,
    D_09001098_341918, D_09001080_341900, D_09001068_3418E8
}
Referenced by shattering_stones_appendGfx().
D_E002C964
f32 D_E002C964[]
Initial value:
= {
    -1.0f, -0.5f, 0.5f, 1.0f, -1.0f, -0.5f, 0.5f, 1.0f
}
Referenced by shattering_stones_main().
D_E002C984
f32 D_E002C984[][2]
Initial value:
= {
    { -5.0f, -4.0f },
    { -3.0f, -2.0f },
    {  2.0f, -3.0f },
    {  5.0f, -4.0f },
    { -4.0f,  2.0f },
    { -1.0f,  4.0f },
    {  3.0f,  2.0f },
    {  5.0f,  4.0f }
}
Referenced by shattering_stones_main().