papermario: src/effects/shimmer_burst.c File Reference
shimmer_burst.c File Reference
Functions
void shimmer_burst_init (EffectInstance *effect)
void shimmer_burst_update (EffectInstance *effect)
void shimmer_burst_render (EffectInstance *effect)
void shimmer_burst_appendGfx (void *effect)
EffectInstance * shimmer_burst_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E0070738 (void)
Variables
Gfx D_09000F20_338EE0 []
Gfx D_090011C8_339188 []
Gfx D_090011E0_3391A0 []
Gfx D_090011F8_3391B8 []
Gfx D_09001210_3391D0 []
Gfx D_09001228_3391E8 []
Gfx D_09001240_339200 []
Gfx D_09001258_339218 []
Gfx D_09001270_339230 []
Gfx * D_E0070CD0 []
f32 D_E0070CF0 []
s32 D_E0070D70 []
Function Documentation
func_E0070738()
void func_E0070738 (void)
shimmer_burst_appendGfx()
void shimmer_burst_appendGfx (void * effect)
Referenced by shimmer_burst_render().
shimmer_burst_init()
void shimmer_burst_init (EffectInstance * effect)
Referenced by shimmer_burst_main().
shimmer_burst_main()
EffectInstance * shimmer_burst_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
shimmer_burst_render()
void shimmer_burst_render (EffectInstance * effect)
Referenced by shimmer_burst_main().
shimmer_burst_update()
void shimmer_burst_update (EffectInstance * effect)
Referenced by shimmer_burst_main().
Variable Documentation
D_09000F20_338EE0
Gfx D_09000F20_338EE0[] extern
Referenced by shimmer_burst_appendGfx().
D_090011C8_339188
Gfx D_090011C8_339188[] extern
D_090011E0_3391A0
Gfx D_090011E0_3391A0[] extern
D_090011F8_3391B8
Gfx D_090011F8_3391B8[] extern
D_09001210_3391D0
Gfx D_09001210_3391D0[] extern
D_09001228_3391E8
Gfx D_09001228_3391E8[] extern
D_09001240_339200
Gfx D_09001240_339200[] extern
D_09001258_339218
Gfx D_09001258_339218[] extern
D_09001270_339230
Gfx D_09001270_339230[] extern
D_E0070CD0
Gfx* D_E0070CD0[]
Initial value:
= {
    D_09001210_3391D0, D_09001228_3391E8, D_09001240_339200, D_09001258_339218,
    D_09001270_339230, D_090011C8_339188, D_090011E0_3391A0, D_090011F8_3391B8
}
Referenced by shimmer_burst_appendGfx().
D_E0070CF0
f32 D_E0070CF0[]
Initial value:
= {
    0.2f, 0.4f, 0.8f, 1.3f, 1.5f, 1.3f, 0.9f, 0.6f, 0.4f, 0.3f,
    0.2f, 0.4f, 0.8f, 1.3f, 1.5f, 1.3f, 0.9f, 0.6f, 0.4f, 0.3f
}
Referenced by shimmer_burst_update().
D_E0070D70
s32 D_E0070D70[]
Initial value:
= {
    0xC8FAFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFAC8, 0x00000000, 0x00000000, 0x00000000
}