papermario: src/effects/shimmer_wave.c File Reference
shimmer_wave.c File Reference
Functions
void shimmer_wave_init (EffectInstance *effect)
void shimmer_wave_update (EffectInstance *effect)
void shimmer_wave_render (EffectInstance *effect)
void shimmer_wave_appendGfx (void *effect)
EffectInstance * shimmer_wave_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, s32 arg6, s32 arg7)
Variables
Gfx D_09000F20_338EE0 []
Gfx D_090011C8_339188 []
Gfx D_090011E0_3391A0 []
Gfx D_090011F8_3391B8 []
Gfx D_09001210_3391D0 []
Gfx D_09001228_3391E8 []
Gfx D_09001240_339200 []
Gfx D_09001258_339218 []
Gfx D_09001270_339230 []
Gfx * D_E0074B60 []
f32 D_E0074B80 []
s32 D_E0074BD0 []
Function Documentation
shimmer_wave_appendGfx()
void shimmer_wave_appendGfx (void * effect)
Referenced by shimmer_wave_render().
shimmer_wave_init()
void shimmer_wave_init (EffectInstance * effect)
Referenced by shimmer_wave_main().
shimmer_wave_main()
EffectInstance * shimmer_wave_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, s32 arg6, s32 arg7)
Referenced by energy_shockwave_update().
shimmer_wave_render()
void shimmer_wave_render (EffectInstance * effect)
Referenced by shimmer_wave_main().
shimmer_wave_update()
void shimmer_wave_update (EffectInstance * effect)
Referenced by shimmer_wave_main().
Variable Documentation
D_09000F20_338EE0
Gfx D_09000F20_338EE0[] extern
Referenced by shimmer_wave_appendGfx().
D_090011C8_339188
Gfx D_090011C8_339188[] extern
D_090011E0_3391A0
Gfx D_090011E0_3391A0[] extern
D_090011F8_3391B8
Gfx D_090011F8_3391B8[] extern
D_09001210_3391D0
Gfx D_09001210_3391D0[] extern
D_09001228_3391E8
Gfx D_09001228_3391E8[] extern
D_09001240_339200
Gfx D_09001240_339200[] extern
D_09001258_339218
Gfx D_09001258_339218[] extern
D_09001270_339230
Gfx D_09001270_339230[] extern
D_E0074B60
Gfx* D_E0074B60[]
Initial value:
= {
    D_09001210_3391D0, D_09001228_3391E8, D_09001240_339200, D_09001258_339218,
    D_09001270_339230, D_090011C8_339188, D_090011E0_3391A0, D_090011F8_3391B8
}
Referenced by shimmer_wave_appendGfx().
D_E0074B80
f32 D_E0074B80[]
Initial value:
= {
    0.2f, 0.4f, 0.8f, 1.3f, 1.5f, 1.3f, 0.9f, 0.6f, 0.4f, 0.3f,
    0.2f, 0.4f, 0.8f, 1.3f, 1.5f, 1.3f, 0.9f, 0.6f, 0.4f, 0.3f
}
Referenced by shimmer_wave_update().
D_E0074BD0
s32 D_E0074BD0[]
Initial value:
= {
    0xC8FAFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFAC8, 0x00000000, 0x00000000, 0x00000000
}