papermario: src/effects/shiny_flare.c File Reference
shiny_flare.c File Reference
Functions
void shiny_flare_init (EffectInstance *effect)
void shiny_flare_update (EffectInstance *effect)
void shiny_flare_render (EffectInstance *effect)
void shiny_flare_appendGfx (void *effect)
EffectInstance * shiny_flare_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00DA228 (void)
Variables
Gfx D_09000240_3D79B0 []
Gfx D_090002E0_3D7A50 []
u8 D_E00DA500 []
Function Documentation
func_E00DA228()
void func_E00DA228 (void)
shiny_flare_appendGfx()
void shiny_flare_appendGfx (void * effect)
Referenced by shiny_flare_render().
shiny_flare_init()
void shiny_flare_init (EffectInstance * effect)
Referenced by shiny_flare_main().
shiny_flare_main()
EffectInstance * shiny_flare_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
shiny_flare_render()
void shiny_flare_render (EffectInstance * effect)
Referenced by shiny_flare_main().
shiny_flare_update()
void shiny_flare_update (EffectInstance * effect)
Referenced by shiny_flare_main().
Variable Documentation
D_09000240_3D79B0
Gfx D_09000240_3D79B0[] extern
Referenced by shiny_flare_appendGfx().
D_090002E0_3D7A50
Gfx D_090002E0_3D7A50[] extern
Referenced by shiny_flare_appendGfx().
D_E00DA500
u8 D_E00DA500[]
Initial value:
= {
    255, 255,  82,
    255, 255,  82,
    181, 148,   0,
    181, 148,   0,
    255, 255, 214,
    255, 255, 214,
    181, 148,   0,
    181, 148,   0
}
Referenced by shiny_flare_appendGfx().