papermario: src/effects/shockwave.c File Reference
shockwave.c File Reference
Functions
void shockwave_init (EffectInstance *effect)
void shockwave_update (EffectInstance *effect)
void shockwave_render (EffectInstance *effect)
void shockwave_appendGfx (void *effect)
void shockwave_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Variables
Gfx D_09000940_359CF0 []
Gfx D_090009A0_359D50 []
Gfx D_09000A80_359E30 []
Gfx * D_E004AE60 []
Function Documentation
shockwave_appendGfx()
void shockwave_appendGfx (void * effect)
Referenced by shockwave_render().
shockwave_init()
void shockwave_init (EffectInstance * effect)
Referenced by shockwave_main().
shockwave_main()
void shockwave_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
shockwave_render()
void shockwave_render (EffectInstance * effect)
Referenced by shockwave_main().
shockwave_update()
void shockwave_update (EffectInstance * effect)
Referenced by shockwave_main().
Variable Documentation
D_09000940_359CF0
Gfx D_09000940_359CF0[] extern
Referenced by shockwave_appendGfx().
D_090009A0_359D50
Gfx D_090009A0_359D50[] extern
D_09000A80_359E30
Gfx D_09000A80_359E30[] extern
D_E004AE60
Gfx* D_E004AE60[]
Initial value:
= {
    D_090009A0_359D50, D_090009A0_359D50, D_09000A80_359E30,
    D_09000A80_359E30, D_09000A80_359E30, D_09000A80_359E30
}
Referenced by shockwave_appendGfx().