papermario: src/effects/sleep_bubble.c File Reference
sleep_bubble.c File Reference
Functions
void sleep_bubble_appendGfx (void *effect)
void sleep_bubble_init (EffectInstance *effect)
void sleep_bubble_update (EffectInstance *effect)
void sleep_bubble_render (EffectInstance *effect)
void sleep_bubble_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, EffectInstance **arg6)
Variables
f32 D_E00529E0 []
Vtx D_09000180_35D690 []
Gfx D_090002E0_35D7F0 []
Gfx D_09000390_35D8A0 []
Gfx D_09000440_35D950 []
Function Documentation
sleep_bubble_appendGfx()
void sleep_bubble_appendGfx (void * effect)
Referenced by sleep_bubble_render().
sleep_bubble_init()
void sleep_bubble_init (EffectInstance * effect)
Referenced by sleep_bubble_main().
sleep_bubble_main()
void sleep_bubble_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, EffectInstance ** arg6)
sleep_bubble_render()
void sleep_bubble_render (EffectInstance * effect)
Referenced by sleep_bubble_main().
sleep_bubble_update()
void sleep_bubble_update (EffectInstance * effect)
Referenced by sleep_bubble_main().
Variable Documentation
D_09000180_35D690
Vtx D_09000180_35D690[] extern
Referenced by sleep_bubble_appendGfx().
D_090002E0_35D7F0
Gfx D_090002E0_35D7F0[] extern
Referenced by sleep_bubble_appendGfx().
D_09000390_35D8A0
Gfx D_09000390_35D8A0[] extern
Referenced by sleep_bubble_appendGfx().
D_09000440_35D950
Gfx D_09000440_35D950[] extern
Referenced by sleep_bubble_appendGfx().
D_E00529E0
f32 D_E00529E0[]
Initial value:
= {
    4.4f, 3.2f, 5.4f, 2.7f, 6.0f, 4.9f, 5.2f, 3.1f, 2.4f, 4.5f,
    2.6f, 5.7f, 3.8f, 2.9f, 3.1f, 5.2f, 2.3f, 5.4f, 3.5f, 2.6f,
    2.4f, 3.1f, 5.2f, 4.9f, 6.0f, 2.7f, 5.4f, 3.2f, 4.4f, 2.6f,
    3.5f, 5.4f, 2.3f, 5.2f, 3.1f, 2.9f, 3.8f, 5.7f, 2.6f, 4.5f
}