papermario: src/battle/action_cmd/smack.h File Reference
smack.h File Reference
Functions
void action_command_smack_update (void)
void action_command_smack_draw (void)
void action_command_smack_free (void)
Function Documentation
action_command_smack_draw()
void action_command_smack_draw (void)
Referenced by action_command_draw().
action_command_smack_free()
void action_command_smack_free (void)
Referenced by action_command_free().
action_command_smack_update()
void action_command_smack_update (void)
Referenced by action_command_update().