papermario: src/effects/small_gold_sparkle.c File Reference
small_gold_sparkle.c File Reference
Functions
void small_gold_sparkle_init (EffectInstance *effect)
void small_gold_sparkle_update (EffectInstance *effect)
void small_gold_sparkle_render (EffectInstance *effect)
void small_gold_sparkle_appendGfx (void *effect)
EffectInstance * small_gold_sparkle_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
Variables
Gfx D_090002C0_392700 []
Gfx D_09000330_392770 []
Gfx D_09000370_3927B0 []
Gfx D_090003B0_3927F0 []
Gfx D_090003F0_392830 []
Gfx D_09000430_392870 []
Gfx D_09000470_3928B0 []
Function Documentation
small_gold_sparkle_appendGfx()
void small_gold_sparkle_appendGfx (void * effect)
Referenced by small_gold_sparkle_render().
small_gold_sparkle_init()
void small_gold_sparkle_init (EffectInstance * effect)
Referenced by small_gold_sparkle_main().
small_gold_sparkle_main()
EffectInstance * small_gold_sparkle_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
small_gold_sparkle_render()
void small_gold_sparkle_render (EffectInstance * effect)
Referenced by small_gold_sparkle_main().
small_gold_sparkle_update()
void small_gold_sparkle_update (EffectInstance * effect)
Referenced by small_gold_sparkle_main().
Variable Documentation
D_090002C0_392700
Gfx D_090002C0_392700[] extern
Referenced by small_gold_sparkle_appendGfx().
D_09000330_392770
Gfx D_09000330_392770[] extern
D_09000370_3927B0
Gfx D_09000370_3927B0[] extern
D_090003B0_3927F0
Gfx D_090003B0_3927F0[] extern
D_090003F0_392830
Gfx D_090003F0_392830[] extern
D_09000430_392870
Gfx D_09000430_392870[] extern
D_09000470_3928B0
Gfx D_09000470_3928B0[] extern
Referenced by small_gold_sparkle_appendGfx().