papermario: src/effects/smoke_ring.c File Reference
smoke_ring.c File Reference
Functions
void smoke_ring_init (EffectInstance *effect)
void smoke_ring_update (EffectInstance *effect)
void smoke_ring_render (EffectInstance *effect)
void smoke_ring_appendGfx (void *effect)
void smoke_ring_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Variables
Gfx D_09002950_32B7F0 []
Gfx D_09002B40_32B9E0 []
Gfx D_09002B60_32BA00 []
s8 D_E002E740 []
s8 * D_E002E754 [] = { D_E002E740 }
Function Documentation
smoke_ring_appendGfx()
void smoke_ring_appendGfx (void * effect)
Referenced by smoke_ring_render().
smoke_ring_init()
void smoke_ring_init (EffectInstance * effect)
Referenced by smoke_ring_main().
smoke_ring_main()
void smoke_ring_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3)
Referenced by explosion_update().
smoke_ring_render()
void smoke_ring_render (EffectInstance * effect)
Referenced by smoke_ring_main().
smoke_ring_update()
void smoke_ring_update (EffectInstance * effect)
Referenced by smoke_ring_main().
Variable Documentation
D_09002950_32B7F0
Gfx D_09002950_32B7F0[] extern
Referenced by smoke_ring_appendGfx().
D_09002B40_32B9E0
Gfx D_09002B40_32B9E0[] extern
Referenced by smoke_ring_appendGfx().
D_09002B60_32BA00
Gfx D_09002B60_32BA00[] extern
Referenced by smoke_ring_appendGfx().
D_E002E740
s8 D_E002E740[]
Initial value:
= {
    0,  1, 2, 26,  3, 27,  4,  28,
    5, 29, 6, 22, 38, 71, 87, 103, -1
}
D_E002E754
s8* D_E002E754[] = { D_E002E740 }
Referenced by smoke_ring_update().