papermario: src/effects/smoke_burst.c File Reference
smoke_burst.c File Reference
Functions
void smoke_burst_init (EffectInstance *effect)
void smoke_burst_update (EffectInstance *effect)
void smoke_burst_render (EffectInstance *effect)
void smoke_burst_appendGfx (void *effect)
void smoke_burst_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 timeLeft)
Variables
Gfx D_09002950_32B7F0 []
Gfx D_09002B60_32BA00 []
Gfx D_09002C60_32BB00 []
Gfx * D_E004E5E0 []
Gfx * D_E004E5EC []
Function Documentation
smoke_burst_appendGfx()
void smoke_burst_appendGfx (void * effect)
Referenced by smoke_burst_render().
smoke_burst_init()
void smoke_burst_init (EffectInstance * effect)
Referenced by smoke_burst_main().
smoke_burst_main()
void smoke_burst_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 timeLeft)
smoke_burst_render()
void smoke_burst_render (EffectInstance * effect)
Referenced by smoke_burst_main().
smoke_burst_update()
void smoke_burst_update (EffectInstance * effect)
Referenced by smoke_burst_main().
Variable Documentation
D_09002950_32B7F0
Gfx D_09002950_32B7F0[] extern
D_09002B60_32BA00
Gfx D_09002B60_32BA00[] extern
D_09002C60_32BB00
Gfx D_09002C60_32BB00[] extern
D_E004E5E0
Gfx* D_E004E5E0[]
Initial value:
= {
    D_09002B60_32BA00, D_09002C60_32BB00, D_09002B60_32BA00
}
Referenced by smoke_burst_appendGfx().
D_E004E5EC
Gfx* D_E004E5EC[]
Initial value:
= {
    D_09002950_32B7F0, D_09002950_32B7F0, D_09002950_32B7F0
}
Referenced by smoke_burst_appendGfx().