papermario: src/effects/smoke_impact.c File Reference
smoke_impact.c File Reference
Functions
void smoke_impact_init (EffectInstance *effect)
void smoke_impact_update (EffectInstance *effect)
void smoke_impact_render (EffectInstance *effect)
void smoke_impact_appendGfx (void *effect)
void smoke_impact_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5, f32 arg6, s32 arg7)
Variables
Gfx D_09002A38_32B8D8 []
Gfx D_09002B60_32BA00 []
Gfx D_09002B80_32BA20 []
Gfx * D_E003A800 []
Gfx * D_E003A80C []
Function Documentation
smoke_impact_appendGfx()
void smoke_impact_appendGfx (void * effect)
Referenced by smoke_impact_render().
smoke_impact_init()
void smoke_impact_init (EffectInstance * effect)
Referenced by smoke_impact_main().
smoke_impact_main()
void smoke_impact_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5, f32 arg6, s32 arg7)
smoke_impact_render()
void smoke_impact_render (EffectInstance * effect)
Referenced by smoke_impact_main().
smoke_impact_update()
void smoke_impact_update (EffectInstance * effect)
Referenced by smoke_impact_main().
Variable Documentation
D_09002A38_32B8D8
Gfx D_09002A38_32B8D8[] extern
D_09002B60_32BA00
Gfx D_09002B60_32BA00[] extern
D_09002B80_32BA20
Gfx D_09002B80_32BA20[] extern
D_E003A800
Gfx* D_E003A800[]
Initial value:
= {
    D_09002B60_32BA00, D_09002B80_32BA20, D_09002B60_32BA00
}
Referenced by smoke_impact_appendGfx().
D_E003A80C
Gfx* D_E003A80C[]
Initial value:
= {
    D_09002A38_32B8D8, D_09002A38_32B8D8, D_09002A38_32B8D8
}
Referenced by smoke_impact_appendGfx().