papermario: src/effects/snaking_static.c File Reference
snaking_static.c File Reference
Functions
void snaking_static_update (EffectInstance *)
void snaking_static_init (EffectInstance *effect)
void snaking_static_render (EffectInstance *effect)
void snaking_static_appendGfx (void *effect)
EffectInstance * snaking_static_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, s32 timeLeft)
void func_E00AE544 (void)
Variables
Gfx D_09001000_3B3D90 []
Gfx D_090010F8_3B3E88 []
Function Documentation
func_E00AE544()
void func_E00AE544 (void)
snaking_static_appendGfx()
void snaking_static_appendGfx (void * effect)
Referenced by snaking_static_render().
snaking_static_init()
void snaking_static_init (EffectInstance * effect)
Referenced by snaking_static_main().
snaking_static_main()
EffectInstance * snaking_static_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 scale, s32 timeLeft)
Referenced by lightning_main().
snaking_static_render()
void snaking_static_render (EffectInstance * effect)
Referenced by snaking_static_main().
snaking_static_update()
void snaking_static_update (EffectInstance * effect)
Referenced by snaking_static_main().
Variable Documentation
D_09001000_3B3D90
Gfx D_09001000_3B3D90[] extern
Referenced by snaking_static_appendGfx().
D_090010F8_3B3E88
Gfx D_090010F8_3B3E88[] extern
Referenced by snaking_static_appendGfx().