papermario: src/audio/snd_interface.c File Reference
snd_interface.c File Reference
Functions
void snd_notify_engine_ready (ALHeap *heap)
void snd_legacy_sound_dispatch (u32 id)
Unused Seems to be an early function that accepts a command to play any kind of audio asset,.
void snd_bgm_clear_legacy_commands (BGMPlayer *player)
Part of an unused system for inter-thread communication with a BGM player using commands.
void snd_bgm_enqueue_legacy_command (u32 cmd)
Unused Part of an unused system for inter-thread communication with a BGM player using commands.
void snd_start_sound (s32 soundID, u8 volume, u8 pan)
void snd_start_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void snd_adjust_sound (s32 soundID, u8 volume, u8 pan)
void snd_adjust_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
void snd_stop_sound (s32 soundID)
void snd_reset (void)
void snd_start_sound_raw (s32 soundID, s16 volume, s16 pitchShift, s32 pan)
AuResult snd_load_ambient (s32 ambSoundID)
AuResult snd_ambient_play (s32 index, s32 fadeInTime)
AuResult snd_ambient_stop_quick (s32 index)
AuResult snd_ambient_stop_slow (s32 index, s32 fadeOutTime)
AuResult snd_ambient_pause (s32 index, s32 fadeOutTime)
AuResult snd_ambient_resume (s32 index, s32 fadeInTime)
AuResult snd_ambient_is_stopped (s32 index)
AuResult snd_ambient_fade_out (s32 index, s32 arg1)
AuResult snd_ambient_set_volume (s32 index, s32 time, s32 volume)
AuResult snd_ambient_disable (s32 index)
AuResult snd_ambient_enable (s32 index)
void snd_ambient_radio_setup (s32 index)
AuResult snd_ambient_radio_stop (s32 time)
AuResult snd_ambient_radio_select (s32 index)
AuResult snd_song_load (s32 songID, s32 playerIndex)
return value may be either an AuResult error code OR a valid songName
AuResult snd_song_request_play_default (s32 songName)
Unused – snd_song_request_play but always uses BGM_VARIATION_0.
AuResult snd_song_request_play (s32 songName, s32 variation)
Called from bgm_control to start playing a particular song + variation.
AuResult snd_song_stop (s32 songName)
void snd_song_stop_all (void)
AuResult snd_song_is_playing (s32 songName)
AuResult snd_song_request_fade_in (s32 songName, s32 variation, s32 fadeInTime, s32 startVolume, s32 endVolume)
Called from bgm_control to fade in a particular song + variation.
AuResult snd_song_request_fade_in_default (s32 songName, s32 fadeInTime, s32 startVolume, s32 endVolume)
Unused.
AuResult snd_song_request_fade_out (s32 songName, s32 fadeTime, AuCallback callback)
AuResult snd_song_push_stop (s32 songName)
AuResult snd_song_request_pop (s32 songName)
AuResult snd_song_request_snapshot (s32 songName)
AuResult snd_song_request_push_fade_out (s32 songName, s32 fadeTime)
AuResult snd_song_request_pause (s32 songName)
AuResult snd_song_request_unpause (s32 songName)
AuResult snd_song_set_volume_quiet (s32 songName)
AuResult snd_song_set_volume_full (s32 songName)
AuResult snd_song_set_linked_mode (s32 songName, b32 mode)
AuResult snd_song_get_playing_info (s32 songName, BGMHeader **outFile, BGMPlayer **outPlayer)
AuResult snd_song_set_playback_rate (s32 songName, f32 rate)
AuResult snd_song_set_detune (s32 songName, s32 detune)
AuResult snd_song_set_track_volumes (s32 songName, MusicTrackVols trackVolSet)
AuResult snd_song_clear_track_volumes (s32 songName, MusicTrackVols trackVolSet)
AuResult snd_song_set_track_vol_mute (s32 songName, s32 trackIdx)
AuResult snd_song_set_track_vol_quiet (s32 songName, s32 trackIdx)
AuResult snd_song_set_track_vol_full (s32 songName, s32 trackIdx)
void snd_song_set_proximity_mix_far (s32 songName, s32 mix)
void snd_song_set_proximity_mix_near (s32 songName, s32 mix)
void snd_song_set_proximity_mix_full (s32 songName, s32 mix)
void snd_song_poll_music_events (MusicEventTrigger **musicEvents, s32 *count)
void snd_song_flush_music_events (void)
void snd_song_trigger_music_event (s32 playerID, s32 trackIndex, s32 eventInfo)
void snd_song_clear_music_events (void)
void snd_register_callback (AuCallback func, s32 index)
void snd_set_stereo (void)
void snd_set_mono (void)
void snd_set_bgm_volume (VolumeLevels volume)
void snd_set_sfx_volume (VolumeLevels volume)
void snd_set_sfx_reverb_type (s32 reverbType)
void snd_enable_sfx (void)
void snd_disable_sfx (void)
Variables
s32 PreventBGMPlayerUpdate = FALSE
While TRUE, the audio thread skips BGM player updates.
u16 SoundEngineReady = 0
u16 AmbienceRadioChannel = 0
u8 TrackVols_JAN_Full []
u8 TrackVols_Unused1 []
u8 TrackVols_TIK_Shiver []
u8 TrackVols_Unused3 []
u8 TrackVols_KPA_Outside []
u8 TrackVols_KPA_1 []
u8 TrackVols_KPA_2 []
u8 TrackVols_KPA_3 []
Function Documentation
snd_adjust_sound()
void snd_adjust_sound (s32 soundID, u8 volume, u8 pan)
snd_adjust_sound_with_shift()
void snd_adjust_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by sfx_adjust_env_sound_params(), and sfx_update_env_sound_params().
snd_ambient_disable()
AuResult snd_ambient_disable (s32 index)
Referenced by snd_ambient_radio_select().
snd_ambient_enable()
AuResult snd_ambient_enable (s32 index)
Referenced by snd_ambient_radio_select().
snd_ambient_fade_out()
AuResult snd_ambient_fade_out (s32 index, s32 arg1)
snd_ambient_is_stopped()
AuResult snd_ambient_is_stopped (s32 index)
Referenced by update_ambient_sounds().
snd_ambient_pause()
AuResult snd_ambient_pause (s32 index, s32 fadeOutTime)
Referenced by bgm_push_battle_song().
snd_ambient_play()
AuResult snd_ambient_play (s32 index, s32 fadeInTime)
Referenced by snd_ambient_radio_setup(), and update_ambient_sounds().
snd_ambient_radio_select()
AuResult snd_ambient_radio_select (s32 index)
Referenced by snd_ambient_radio_setup().
snd_ambient_radio_setup()
void snd_ambient_radio_setup (s32 index)
snd_ambient_radio_stop()
AuResult snd_ambient_radio_stop (s32 time)
snd_ambient_resume()
AuResult snd_ambient_resume (s32 index, s32 fadeInTime)
Referenced by bgm_pop_battle_song().
snd_ambient_set_volume()
AuResult snd_ambient_set_volume (s32 index, s32 time, s32 volume)
snd_ambient_stop_quick()
AuResult snd_ambient_stop_quick (s32 index)
Referenced by play_ambient_sounds(), snd_ambient_radio_stop(), and update_ambient_sounds().
snd_ambient_stop_slow()
AuResult snd_ambient_stop_slow (s32 index, s32 fadeOutTime)
Referenced by snd_ambient_radio_stop(), and update_ambient_sounds().
snd_bgm_clear_legacy_commands()
void snd_bgm_clear_legacy_commands (BGMPlayer * player)
Part of an unused system for inter-thread communication with a BGM player using commands.
Use functions in bgm_control to manipualte gMusicControlData instead.
Referenced by au_bgm_player_init().
snd_bgm_enqueue_legacy_command()
void snd_bgm_enqueue_legacy_command (u32 cmd)
Unused Part of an unused system for inter-thread communication with a BGM player using commands.
Use functions in bgm_control to manipualte gMusicControlData instead.
snd_disable_sfx()
void snd_disable_sfx (void)
Referenced by state_init_demo().
snd_enable_sfx()
void snd_enable_sfx (void)
Referenced by state_step_demo().
snd_legacy_sound_dispatch()
void snd_legacy_sound_dispatch (u32 id)
Unused Seems to be an early function that accepts a command to play any kind of audio asset,.
snd_load_ambient()
AuResult snd_load_ambient (s32 ambSoundID)
Referenced by update_ambient_sounds().
snd_notify_engine_ready()
void snd_notify_engine_ready (ALHeap * heap)
Referenced by au_engine_init().
snd_register_callback()
void snd_register_callback (AuCallback func, s32 index)
snd_reset()
void snd_reset (void)
snd_set_bgm_volume()
void snd_set_bgm_volume (VolumeLevels volume)
Referenced by bgm_reset_sequence_players(), and bgm_update_volume().
snd_set_mono()
void snd_set_mono (void)
Referenced by filemenu_main_handle_input(), and state_step_startup().
snd_set_sfx_reverb_type()
void snd_set_sfx_reverb_type (s32 reverbType)
Referenced by sfx_set_reverb_mode().
snd_set_sfx_volume()
void snd_set_sfx_volume (VolumeLevels volume)
snd_set_stereo()
void snd_set_stereo (void)
Referenced by filemenu_main_handle_input(), and state_step_startup().
snd_song_clear_music_events()
void snd_song_clear_music_events (void)
Referenced by au_engine_init(), and au_update_clients_for_video_frame().
snd_song_clear_track_volumes()
AuResult snd_song_clear_track_volumes (s32 songName, MusicTrackVols trackVolSet)
Referenced by bgm_clear_track_volumes().
snd_song_flush_music_events()
void snd_song_flush_music_events (void)
snd_song_get_playing_info()
AuResult snd_song_get_playing_info (s32 songName, BGMHeader ** outFile, BGMPlayer ** outPlayer)
Referenced by snd_song_clear_track_volumes(), snd_song_set_detune(), snd_song_set_playback_rate(), and snd_song_set_track_volumes().
snd_song_is_playing()
AuResult snd_song_is_playing (s32 songName)
Referenced by bgm_is_any_song_playing(), and bgm_update_music_control().
snd_song_load()
AuResult snd_song_load (s32 songID, s32 playerIndex)
return value may be either an AuResult error code OR a valid songName
Referenced by bgm_update_music_control(), and snd_legacy_sound_dispatch().
snd_song_poll_music_events()
void snd_song_poll_music_events (MusicEventTrigger ** musicEvents, s32 * count)
snd_song_push_stop()
AuResult snd_song_push_stop (s32 songName)
Referenced by bgm_update_music_control().
snd_song_request_fade_in()
AuResult snd_song_request_fade_in (s32 songName, s32 variation, s32 fadeInTime, s32 startVolume, s32 endVolume)
Called from bgm_control to fade in a particular song + variation.
Referenced by bgm_update_music_control().
snd_song_request_fade_in_default()
AuResult snd_song_request_fade_in_default (s32 songName, s32 fadeInTime, s32 startVolume, s32 endVolume)
Unused.
snd_song_request_fade_out()
AuResult snd_song_request_fade_out (s32 songName, s32 fadeTime, AuCallback callback)
Referenced by bgm_update_music_control().
snd_song_request_pause()
AuResult snd_song_request_pause (s32 songName)
snd_song_request_play()
AuResult snd_song_request_play (s32 songName, s32 variation)
Called from bgm_control to start playing a particular song + variation.
Referenced by bgm_update_music_control(), and snd_legacy_sound_dispatch().
snd_song_request_play_default()
AuResult snd_song_request_play_default (s32 songName)
Unused – snd_song_request_play but always uses BGM_VARIATION_0.
snd_song_request_pop()
AuResult snd_song_request_pop (s32 songName)
Referenced by bgm_update_music_control().
snd_song_request_push_fade_out()
AuResult snd_song_request_push_fade_out (s32 songName, s32 fadeTime)
Referenced by bgm_update_music_control().
snd_song_request_snapshot()
AuResult snd_song_request_snapshot (s32 songName)
Referenced by _bgm_set_song().
snd_song_request_unpause()
AuResult snd_song_request_unpause (s32 songName)
snd_song_set_detune()
AuResult snd_song_set_detune (s32 songName, s32 detune)
snd_song_set_linked_mode()
AuResult snd_song_set_linked_mode (s32 songName, b32 mode)
Referenced by bgm_set_linked_mode().
snd_song_set_playback_rate()
AuResult snd_song_set_playback_rate (s32 songName, f32 rate)
Referenced by worker_update_phonograph_hud().
snd_song_set_proximity_mix_far()
void snd_song_set_proximity_mix_far (s32 songName, s32 mix)
Referenced by bgm_adjust_proximity().
snd_song_set_proximity_mix_full()
void snd_song_set_proximity_mix_full (s32 songName, s32 mix)
Referenced by bgm_adjust_proximity().
snd_song_set_proximity_mix_near()
void snd_song_set_proximity_mix_near (s32 songName, s32 mix)
Referenced by bgm_adjust_proximity().
snd_song_set_track_vol_full()
AuResult snd_song_set_track_vol_full (s32 songName, s32 trackIdx)
snd_song_set_track_vol_mute()
AuResult snd_song_set_track_vol_mute (s32 songName, s32 trackIdx)
snd_song_set_track_vol_quiet()
AuResult snd_song_set_track_vol_quiet (s32 songName, s32 trackIdx)
snd_song_set_track_volumes()
AuResult snd_song_set_track_volumes (s32 songName, MusicTrackVols trackVolSet)
Referenced by bgm_set_track_volumes().
snd_song_set_volume_full()
AuResult snd_song_set_volume_full (s32 songName)
snd_song_set_volume_quiet()
AuResult snd_song_set_volume_quiet (s32 songName)
snd_song_stop()
AuResult snd_song_stop (s32 songName)
Referenced by _bgm_set_song(), bgm_fade_in_song(), and bgm_update_music_control().
snd_song_stop_all()
void snd_song_stop_all (void)
snd_song_trigger_music_event()
void snd_song_trigger_music_event (s32 playerID, s32 trackIndex, s32 eventInfo)
Referenced by au_BGMCmd_FD_EventTrigger().
snd_start_sound()
void snd_start_sound (s32 soundID, u8 volume, u8 pan)
Referenced by animate_and_draw_record(), and appendGfx_records().
snd_start_sound_raw()
void snd_start_sound_raw (s32 soundID, s16 volume, s16 pitchShift, s32 pan)
snd_start_sound_with_shift()
void snd_start_sound_with_shift (s32 soundID, u8 volume, u8 pan, s16 pitchShift)
Referenced by sfx_clear_env_sounds(), sfx_play_sound_looping(), sfx_play_sound_with_params(), and snd_legacy_sound_dispatch().
snd_stop_sound()
void snd_stop_sound (s32 soundID)
Referenced by action_update_sliding(), sfx_stop_env_sounds(), sfx_stop_sound(), and sfx_stop_tracking_env_sound_pos().
Variable Documentation
AmbienceRadioChannel
u16 AmbienceRadioChannel = 0
Referenced by snd_ambient_radio_select(), snd_ambient_radio_setup(), and snd_ambient_radio_stop().
PreventBGMPlayerUpdate
s32 PreventBGMPlayerUpdate = FALSE
While TRUE, the audio thread skips BGM player updates.
Used by the game thread to lock out BGM updates while modifying player state, to prevent race conditions.
Referenced by au_update_clients_for_audio_frame(), snd_notify_engine_ready(), snd_song_request_fade_in(), snd_song_request_fade_in_default(), snd_song_request_play(), snd_song_request_play_default(), and snd_song_request_pop().
SoundEngineReady
u16 SoundEngineReady = 0
Referenced by snd_legacy_sound_dispatch(), and snd_notify_engine_ready().
TrackVols_JAN_Full
u8 TrackVols_JAN_Full[]
Initial value:
= {
    2, 94,
    3, 80,
    4, 100,
    5, 84,
    0
}
TrackVols_KPA_1
u8 TrackVols_KPA_1[]
Initial value:
= {
    5, 100,
    6, 102,
    7, 88,
    8, 110,
    9, 0,
    10, 0,
    11, 0,
    12, 0,
    13, 0,
    14, 0,
    15, 0,
    16, 0,
    0
}
TrackVols_KPA_2
u8 TrackVols_KPA_2[]
Initial value:
= {
    5, 100,
    6, 102,
    7, 88,
    8, 110,
    9, 126,
    10, 88,
    11, 100,
    12, 0,
    13, 0,
    14, 0,
    15, 0,
    16, 0,
    0
}
TrackVols_KPA_3
u8 TrackVols_KPA_3[]
Initial value:
= {
    5, 100,
    6, 102,
    7, 88,
    8, 110,
    9, 126,
    10, 88,
    11, 100,
    12, 100,
    13, 106,
    14, 100,
    15, 100,
    16, 110,
    0
}
TrackVols_KPA_Outside
u8 TrackVols_KPA_Outside[]
Initial value:
= {
    5, 0,
    6, 0,
    7, 0,
    8, 0,
    9, 0,
    10, 0,
    11, 0,
    12, 0,
    13, 0,
    14, 0,
    15, 0,
    16, 0,
    0
}
TrackVols_TIK_Shiver
u8 TrackVols_TIK_Shiver[]
Initial value:
= {
    2, 95,
    0
}
TrackVols_Unused1
u8 TrackVols_Unused1[]
Initial value:
= {
    2, 100,
    3, 110,
    4, 90,
    0
}
TrackVols_Unused3
u8 TrackVols_Unused3[]
Initial value:
= {
    5, 70,
    6, 90,
    7, 90,
    8, 100,
    0
}