papermario: src/world/action/sneaky_parasol.c File Reference
sneaky_parasol.c File Reference
Data Structures
struct TransformationData
Enumerations
enum {
SUBSTATE_DISGUISE_INIT = 0 , SUBSTATE_USE_PARASOL = 1 , SUBSTATE_PUT_AWAY = 2 , SUBSTATE_DISGUISE_BEGIN = 3 ,
SUBSTATE_DISGUISE_WAIT_FOR_ANGLE = 4 , SUBSTATE_DISGUISE_MAKE_NPC = 5 , SUBSTATE_DISGUISE_SPIN_DOWN = 6 , SUBSTATE_DISGUISE_FINISH_SPIN = 7 ,
SUBSTATE_DISGUISE_DONE = 8 , SUBSTATE_REVERT_INIT = 20 , SUBSTATE_REVERT_WAIT_FOR_ANGLE = 21 , SUBSTATE_SPIN_DOWN = 22 ,
SUBSTATE_FINISH_SPIN = 23 , SUBSTATE_REVERT_DONE = 24 , SUBSTATE_ABORT = 26 , SUBSTATE_FAILED = 40 ,
SUBSTATE_BLOCKED = 50
}
Functions
s32 peach_disguise_check_overlaps (void)
void peach_force_disguise_action (s32)
void parasol_update_spin (void)
Npc * parasol_get_npc (void)
void action_update_parasol (void)
Variables
BSS TransformationData ParasolTransformation
TransformationData * D_802B6D80_E2B430 = &ParasolTransformation
Data Structure Documentation
TransformationData
struct TransformationData
Data Fields
s32 disguiseTime
Npc * npc
f32 playerRotationRate
f32 playerYawOffset
Vec3f pos
s32 reverted
s32 revertTime
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SUBSTATE_DISGUISE_INIT
SUBSTATE_USE_PARASOL
SUBSTATE_PUT_AWAY
SUBSTATE_DISGUISE_BEGIN
SUBSTATE_DISGUISE_WAIT_FOR_ANGLE
SUBSTATE_DISGUISE_MAKE_NPC
SUBSTATE_DISGUISE_SPIN_DOWN
SUBSTATE_DISGUISE_FINISH_SPIN
SUBSTATE_DISGUISE_DONE
SUBSTATE_REVERT_INIT
SUBSTATE_REVERT_WAIT_FOR_ANGLE
SUBSTATE_SPIN_DOWN
SUBSTATE_FINISH_SPIN
SUBSTATE_REVERT_DONE
SUBSTATE_ABORT
SUBSTATE_FAILED
SUBSTATE_BLOCKED
Function Documentation
action_update_parasol()
void action_update_parasol (void)
parasol_get_npc()
Npc * parasol_get_npc (void)
Referenced by action_update_parasol().
parasol_update_spin()
void parasol_update_spin (void)
Referenced by action_update_parasol().
peach_disguise_check_overlaps()
s32 peach_disguise_check_overlaps (void)
Referenced by action_update_parasol().
peach_force_disguise_action()
void peach_force_disguise_action (s32 useParasol)
Referenced by action_update_parasol().
Variable Documentation
D_802B6D80_E2B430
TransformationData* D_802B6D80_E2B430 = &ParasolTransformation
ParasolTransformation
BSS TransformationData ParasolTransformation
Referenced by action_update_parasol(), and parasol_update_spin().