papermario: src/effects/snowflake.c File Reference
snowflake.c File Reference
Functions
void snowflake_init (EffectInstance *effect)
void snowflake_update (EffectInstance *effect)
void snowflake_render (EffectInstance *effect)
void snowflake_appendGfx (void *effect)
void snowflake_main (f32 x, f32 y, f32 z, s32 arg3)
Variables
s32 D_E001C5E0 = 0
Gfx D_09000900_331800 []
Gfx D_090009E8_3318E8 []
Function Documentation
snowflake_appendGfx()
void snowflake_appendGfx (void * effect)
Referenced by snowflake_render().
snowflake_init()
void snowflake_init (EffectInstance * effect)
Referenced by snowflake_main().
snowflake_main()
void snowflake_main (f32 x, f32 y, f32 z, s32 arg3)
snowflake_render()
void snowflake_render (EffectInstance * effect)
Referenced by snowflake_main().
snowflake_update()
void snowflake_update (EffectInstance * effect)
Referenced by snowflake_main().
Variable Documentation
D_09000900_331800
Gfx D_09000900_331800[] extern
Referenced by snowflake_appendGfx().
D_090009E8_3318E8
Gfx D_090009E8_3318E8[] extern
Referenced by snowflake_appendGfx().
D_E001C5E0
s32 D_E001C5E0 = 0
Referenced by snowflake_main().