papermario: src/effects/snowfall.c File Reference
snowfall.c File Reference
Functions
void snowfall_init (EffectInstance *effect)
void snowfall_update (EffectInstance *effect)
void snowfall_render (EffectInstance *effect)
void snowfall_appendGfx (void *effect)
void func_E008A000 (SnowfallFXData *data)
EffectInstance * snowfall_main (s32 arg0, s32 arg1)
void func_E008A290 (SnowfallFXData *data, s32 arg1, s32 arg2, s32 arg3)
Variables
Gfx D_09000C00_38DC70 []
Gfx D_09000D50_38DDC0 []
Gfx * D_E008AA50 [] = { D_09000D50_38DDC0, D_09000D50_38DDC0 }
Function Documentation
func_E008A000()
void func_E008A000 (SnowfallFXData * data)
Referenced by snowfall_main().
func_E008A290()
void func_E008A290 (SnowfallFXData * data, s32 arg1, s32 arg2, s32 arg3)
Referenced by snowfall_update().
snowfall_appendGfx()
void snowfall_appendGfx (void * effect)
Referenced by snowfall_render().
snowfall_init()
void snowfall_init (EffectInstance * effect)
Referenced by snowfall_main().
snowfall_main()
EffectInstance * snowfall_main (s32 arg0, s32 arg1)
snowfall_render()
void snowfall_render (EffectInstance * effect)
Referenced by snowfall_main().
snowfall_update()
void snowfall_update (EffectInstance * effect)
Referenced by snowfall_main().
Variable Documentation
D_09000C00_38DC70
Gfx D_09000C00_38DC70[] extern
Referenced by snowfall_appendGfx().
D_09000D50_38DDC0
Gfx D_09000D50_38DDC0[] extern
D_E008AA50
Gfx* D_E008AA50[] = { D_09000D50_38DDC0, D_09000D50_38DDC0 }
Referenced by snowfall_appendGfx().