papermario: src/effects/sparkles.c File Reference
sparkles.c File Reference
Functions
void sparkles_init (EffectInstance *effect)
void sparkles_update (EffectInstance *effect)
void sparkles_render (EffectInstance *effect)
void sparkles_appendGfx (void *effect)
void sparkles_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
Variables
Gfx D_09000F20_338EE0 []
Gfx D_090011C8_339188 []
Gfx D_090011E0_3391A0 []
Gfx D_090011F8_3391B8 []
Gfx D_09001210_3391D0 []
Gfx D_09001228_3391E8 []
Gfx D_09001240_339200 []
Gfx D_09001258_339218 []
Gfx D_09001270_339230 []
Gfx * D_E0022CD0 []
u8 D_E0022CF0 []
u8 D_E0022D14 [] = { 0x1E, 0x3C, 0x50, 0x5F, 0x64, 0x68, 0x6A }
u8 D_E0022D1C [] = { 0x3C, 0x5A, 0x64, 0x68, 0x6A, 0x6C, 0x6D }
Function Documentation
sparkles_appendGfx()
void sparkles_appendGfx (void * effect)
Referenced by sparkles_render().
sparkles_init()
void sparkles_init (EffectInstance * effect)
Referenced by sparkles_main().
sparkles_main()
void sparkles_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4)
sparkles_render()
void sparkles_render (EffectInstance * effect)
Referenced by sparkles_main().
sparkles_update()
void sparkles_update (EffectInstance * effect)
Referenced by sparkles_main().
Variable Documentation
D_09000F20_338EE0
Gfx D_09000F20_338EE0[] extern
Referenced by sparkles_appendGfx().
D_090011C8_339188
Gfx D_090011C8_339188[] extern
D_090011E0_3391A0
Gfx D_090011E0_3391A0[] extern
D_090011F8_3391B8
Gfx D_090011F8_3391B8[] extern
D_09001210_3391D0
Gfx D_09001210_3391D0[] extern
D_09001228_3391E8
Gfx D_09001228_3391E8[] extern
D_09001240_339200
Gfx D_09001240_339200[] extern
D_09001258_339218
Gfx D_09001258_339218[] extern
D_09001270_339230
Gfx D_09001270_339230[] extern
D_E0022CD0
Gfx* D_E0022CD0[]
Initial value:
= {
    D_09001210_3391D0, D_09001228_3391E8, D_09001240_339200,
    D_09001258_339218, D_09001270_339230, D_090011C8_339188,
    D_090011E0_3391A0, D_090011F8_3391B8
}
Referenced by sparkles_appendGfx().
D_E0022CF0
u8 D_E0022CF0[]
Initial value:
= {
    254, 172, 172,
    254, 172, 213,
    254, 180, 154,
    213, 180, 254,
    180, 180, 254,
    180, 221, 254,
    180, 254, 254,
    180, 254, 213,
    180, 254, 180,
    213, 254, 180,
    254, 254, 180,
    254, 213, 172
}
Referenced by sparkles_appendGfx().
D_E0022D14
u8 D_E0022D14[] = { 0x1E, 0x3C, 0x50, 0x5F, 0x64, 0x68, 0x6A }
Referenced by sparkles_update().
D_E0022D1C
u8 D_E0022D1C[] = { 0x3C, 0x5A, 0x64, 0x68, 0x6A, 0x6C, 0x6D }
Referenced by sparkles_update().