papermario: src/speech_bubble.c File Reference
speech_bubble.c File Reference
Macros
#define NAMESPACE speech_bubble
Enumerations
enum { SPEECH_BUBBLE_APPEAR = 0 , SPEECH_BUBBLE_HOLD = 1 , SPEECH_BUBBLE_IDLE = 2 , SPEECH_BUBBLE_VANISH = 3 }
Functions
INCLUDE_IMG ("speech_bubble.png", speech_bubble_img)
INCLUDE_PAL ("speech_bubble.pal", speech_bubble_pal)
void interact_speech_update (void)
void interact_speech_setup (void)
void appendGfx_speech_bubble (void)
Variables
BSS SpeechBubbleData SpeechBubble
SpeechBubbleData * SpeechBubblePtr = &SpeechBubble
Macro Definition Documentation
NAMESPACE
#define NAMESPACE speech_bubble
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPEECH_BUBBLE_APPEAR
SPEECH_BUBBLE_HOLD
SPEECH_BUBBLE_IDLE
SPEECH_BUBBLE_VANISH
Function Documentation
appendGfx_speech_bubble()
void appendGfx_speech_bubble (void)
Referenced by render_conversation_prompt().
INCLUDE_IMG()
INCLUDE_IMG ("speech_bubble.png" , speech_bubble_img)
INCLUDE_PAL()
INCLUDE_PAL ("speech_bubble.pal" , speech_bubble_pal)
interact_speech_setup()
void interact_speech_setup (void)
Referenced by check_for_conversation_prompt().
interact_speech_update()
void interact_speech_update (void)
Referenced by interact_speech_setup().
Variable Documentation
SpeechBubble
BSS SpeechBubbleData SpeechBubble
SpeechBubblePtr
SpeechBubbleData* SpeechBubblePtr = &SpeechBubble
Referenced by appendGfx_speech_bubble(), interact_speech_setup(), and interact_speech_update().