papermario: src/effects/spiky_white_aura.c File Reference
spiky_white_aura.c File Reference
Functions
void spiky_white_aura_init (EffectInstance *effect)
void spiky_white_aura_update (EffectInstance *effect)
void spiky_white_aura_render (EffectInstance *effect)
void spiky_white_aura_appendGfx (void *effect)
void spiky_white_aura_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4)
Variables
Gfx * D_09000440_34EBB0 []
Gfx * D_090004E8_34EC58 []
u8 D_E00389F0 []
Function Documentation
spiky_white_aura_appendGfx()
void spiky_white_aura_appendGfx (void * effect)
Referenced by spiky_white_aura_render().
spiky_white_aura_init()
void spiky_white_aura_init (EffectInstance * effect)
Referenced by spiky_white_aura_main().
spiky_white_aura_main()
void spiky_white_aura_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4)
spiky_white_aura_render()
void spiky_white_aura_render (EffectInstance * effect)
Referenced by spiky_white_aura_main().
spiky_white_aura_update()
void spiky_white_aura_update (EffectInstance * effect)
Referenced by spiky_white_aura_main().
Variable Documentation
D_09000440_34EBB0
Gfx* D_09000440_34EBB0[] extern
Referenced by spiky_white_aura_appendGfx().
D_090004E8_34EC58
Gfx* D_090004E8_34EC58[] extern
Referenced by spiky_white_aura_appendGfx().
D_E00389F0
u8 D_E00389F0[]
Initial value:
= {
    254, 172, 172,
    254, 172, 213,
    254, 180, 154,
    213, 180, 254,
    180, 180, 254,
    180, 221, 254,
    180, 254, 254,
    180, 254, 213,
    180, 254, 180,
    213, 254, 180,
    254, 254, 180,
    254, 213, 172,
}