papermario: src/effects/spirit_card.c File Reference
spirit_card.c File Reference
Functions
void spirit_card_init (EffectInstance *effect)
void spirit_card_update (EffectInstance *effect)
void spirit_card_render (EffectInstance *effect)
void spirit_card_appendGfx (void *effect)
EFFECT_DEF_RING_BLAST (ring_blast_main)
EFFECT_DEF_MISC_PARTICLES (misc_particles_main)
EffectInstance * spirit_card_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E0112330 (s32 arg0, SpiritCardFXData *data)
Variables
Gfx D_09003F98_3FE448 []
Gfx D_09004010_3FE4C0 []
Gfx D_09004088_3FE538 []
Gfx D_09004100_3FE5B0 []
Gfx D_09004178_3FE628 []
Gfx D_090041F0_3FE6A0 []
Gfx D_09004268_3FE718 []
Gfx D_090042E0_3FE790 []
Gfx D_09004360_3FE810 []
Gfx D_09004458_3FE908 []
Gfx D_09004508_3FE9B8 []
Gfx D_09004600_3FEAB0 []
Gfx * D_E0112630 [] = { D_09004458_3FE908, D_09004600_3FEAB0 }
Gfx * D_E0112638 [] = { D_09004360_3FE810, D_09004508_3FE9B8 }
Gfx * D_E0112640 []
Function Documentation
EFFECT_DEF_MISC_PARTICLES()
EFFECT_DEF_MISC_PARTICLES (misc_particles_main)
EFFECT_DEF_RING_BLAST()
EFFECT_DEF_RING_BLAST (ring_blast_main)
func_E0112330()
void func_E0112330 (s32 arg0, SpiritCardFXData * data)
Referenced by spirit_card_appendGfx().
spirit_card_appendGfx()
void spirit_card_appendGfx (void * effect)
Referenced by spirit_card_render().
spirit_card_init()
void spirit_card_init (EffectInstance * effect)
Referenced by spirit_card_main().
spirit_card_main()
EffectInstance * spirit_card_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
spirit_card_render()
void spirit_card_render (EffectInstance * effect)
Referenced by spirit_card_main().
spirit_card_update()
void spirit_card_update (EffectInstance * effect)
Referenced by spirit_card_main().
Variable Documentation
D_09003F98_3FE448
Gfx D_09003F98_3FE448[] extern
D_09004010_3FE4C0
Gfx D_09004010_3FE4C0[] extern
D_09004088_3FE538
Gfx D_09004088_3FE538[] extern
D_09004100_3FE5B0
Gfx D_09004100_3FE5B0[] extern
D_09004178_3FE628
Gfx D_09004178_3FE628[] extern
D_090041F0_3FE6A0
Gfx D_090041F0_3FE6A0[] extern
D_09004268_3FE718
Gfx D_09004268_3FE718[] extern
D_090042E0_3FE790
Gfx D_090042E0_3FE790[] extern
Referenced by spirit_card_appendGfx().
D_09004360_3FE810
Gfx D_09004360_3FE810[] extern
D_09004458_3FE908
Gfx D_09004458_3FE908[] extern
D_09004508_3FE9B8
Gfx D_09004508_3FE9B8[] extern
D_09004600_3FEAB0
Gfx D_09004600_3FEAB0[] extern
D_E0112630
Gfx* D_E0112630[] = { D_09004458_3FE908, D_09004600_3FEAB0 }
Referenced by spirit_card_appendGfx().
D_E0112638
Gfx* D_E0112638[] = { D_09004360_3FE810, D_09004508_3FE9B8 }
Referenced by spirit_card_appendGfx().
D_E0112640
Gfx* D_E0112640[]
Initial value:
= {
    D_09003F98_3FE448, D_09004010_3FE4C0, D_09004088_3FE538, D_09004100_3FE5B0,
    D_09004178_3FE628, D_090041F0_3FE6A0, D_09004268_3FE718
}
Referenced by spirit_card_appendGfx().