papermario: src/sprite.h File Reference
sprite.h File Reference
Data Structures
struct SpriteComponent
struct PlayerCurrentAnimInfo
struct SpriteAnimComponent
struct SpriteRasterCacheEntry
struct SpriteAnimData
Sprite data header.
struct SpriteInstance
struct PlayerRastersHeader
struct PlayerSpriteSet
struct PlayerSpriteCacheEntry
struct Quad
Macros
#define SPR_PLAYER_COLOR_VARIATIONS 6
#define SPR_PEACH_BTL_PAL_STRIDE 4
Enumerations
enum SpriteIDFields {
SPRITE_ID_ANIM_MASK = 0x000000FF , SPRITE_ID_PAL_MASK = 0x0000FF00 , SPRITE_ID_SPR_MASK = 0x00FF0000 , SPRITE_ID_BACK_FACING = 0x01000000 ,
SPRITE_ID_TAIL_ALLOCATE = 0x80000000
}
enum DrawSpriteOptions {
DRAW_SPRITE_USE_PLAYER_RASTERS = 0x08000000 , DRAW_SPRITE_UPSIDE_DOWN = 0x10000000 , DRAW_SPRITE_OVERRIDE_PALETTES = 0x20000000 , DRAW_SPRITE_OVERRIDE_YAW = 0x40000000 ,
DRAW_SPRITE_OVERRIDE_ALPHA = 0x80000000
}
enum { PLAYER_SPRITE_MAIN = 0 , PLAYER_SPRITE_AUX1 = 1 , PLAYER_SPRITE_AUX2 = 2 }
enum { SPRITE_MODE_PLAYER = 0 , SPRITE_MODE_NPC = 1 }
Functions
void imgfx_init (void)
void spr_init_sprites (s32 playerSpriteSet)
void spr_render_init (void)
void spr_update_player_raster_cache (void)
s32 spr_update_player_sprite (s32 arg0, s32 arg1, f32 timescale)
s32 spr_draw_player_sprite (s32 spriteInstanceID, s32 yaw, s32 arg2, PAL_PTR *paletteList, Matrix4f mtx)
s32 func_802DDEC4 (s32 arg0)
void set_player_imgfx_comp (s32, s32, ImgFXType, s32, s32, s32, s32, s32)
void set_player_imgfx_all (s32, ImgFXType, s32, s32, s32, s32, s32)
IMG_PTR spr_get_player_raster (s32 rasterIndex, s32 playerSpriteID)
void spr_get_player_raster_info (SpriteRasterInfo *out, s32 playerSpriteID, s32 rasterIndex)
PAL_PTR * spr_get_player_palettes (s32 spriteIndex)
s32 spr_load_npc_sprite (s32 animID, u32 *extraAnimList)
s32 spr_update_sprite (s32 spriteInstanceID, s32 animID, f32 timeScale)
s32 spr_draw_npc_sprite (s32 spriteInstanceID, s32 yaw, s32 arg2, PAL_PTR *paletteList, Matrix4f mtx)
s32 spr_get_notify_value (s32 arg0)
s32 spr_free_sprite (s32 spriteInstanceID)
s32 get_npc_comp_imgfx_idx (s32, s32)
void set_npc_imgfx_comp (s32, s32, ImgFXType, s32, s32, s32, s32, s32)
void set_npc_imgfx_all (s32 arg0, ImgFXType arg1, s32 arg2, s32 arg3, s32 arg4, s32 arg5, s32 arg6)
s32 spr_get_comp_position (s32 spriteIdx, s32 compListIdx, s32 *outX, s32 *outY, s32 *outZ)
s32 spr_get_npc_raster_info (SpriteRasterInfo *out, s32 npcSpriteID, s32 rasterIndex)
PAL_PTR * spr_get_npc_palettes (s32 npcSpriteID)
s32 spr_get_npc_color_variations (s32 npcSpriteID)
void create_shading_palette (Matrix4f mtx, s32 uls, s32 ult, s32 lrs, s32 lrt, s32 alpha, s32)
SpriteAnimData * spr_load_sprite (s32 idx, s32 arg1, s32 arg2)
Variables
Quad spr_defaultQuad
Vp SprPauseVp
Vp SprPauseVpAlt
Gfx D_802DF3F0 []
Gfx D_802DF428 []
Gfx D_802DF460 []
Gfx D_802DF490 []
f32 spr_animUpdateTimeScale
PlayerSpriteSet spr_playerSpriteSets [7]
Data Structure Documentation
SpriteComponent
struct SpriteComponent
Data Fields
Vec3f compPos
s32 curPalette
s32 curRaster
s32 imgfxIdx
s32 initialized
s32 loopCounter
Vec3f posOffset
s32 properties AABBCCCC : AA = unused?, BB = parent, CCCC = notify value.
s16 * readPos
Vec3i rot
Vec3f scale
f32 waitTime
PlayerCurrentAnimInfo
struct PlayerCurrentAnimInfo
Data Fields
s32 animID
SpriteComponent ** componentList
s32 notifyValue
SpriteAnimComponent
struct SpriteAnimComponent
Data Fields
u16 * cmdList
s16 cmdListSize
Vec3s compOffset
SpriteRasterCacheEntry
struct SpriteRasterCacheEntry
Data Fields
u8 height
IMG_PTR image
s8 palette
s8 quadCacheIndex
u8 width
SpriteAnimData
struct SpriteAnimData
Data Fields
SpriteAnimComponent ** animListStart[VLA]
s32 colorVariations
s32 maxComponents
PAL_PTR * palettesOffset
SpriteRasterCacheEntry ** rastersOffset
SpriteInstance
struct SpriteInstance
Data Fields
SpriteComponent ** componentList
s32 curAnimID
s32 notifyValue
SpriteAnimData * spriteData
s32 spriteIndex
PlayerRastersHeader
struct PlayerRastersHeader
Data Fields
s32 imageData
s32 indexRanges
s32 loadDescriptors
PlayerSpriteSet
struct PlayerSpriteSet
Data Fields
s32 cacheSize Number of cache entries.
s32 initiallyLoaded Flags saying which rasters to load into the cache in spr_init_sprites(), with each bit corresponding to the Nth raster (with LSB = raster 0).
s32 rasterSize Maximum raster size.
PlayerSpriteCacheEntry
struct PlayerSpriteCacheEntry
Data Fields
s32 lazyDeleteTime
IMG_PTR raster
s32 rasterIndex
s32 spriteIndex
Quad
struct Quad
Data Fields
Vtx v[4]
Macro Definition Documentation
SPR_PEACH_BTL_PAL_STRIDE
#define SPR_PEACH_BTL_PAL_STRIDE 4
Referenced by render_with_player_debuff_palettes().
SPR_PLAYER_COLOR_VARIATIONS
#define SPR_PLAYER_COLOR_VARIATIONS 6
Referenced by render_with_player_debuff_palettes(), render_with_poison_palettes(), render_with_static_palettes(), render_with_watt_attack_palettes(), and render_with_watt_idle_palettes().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PLAYER_SPRITE_MAIN
PLAYER_SPRITE_AUX1
PLAYER_SPRITE_AUX2
anonymous enum
anonymous enum
Enumerator
SPRITE_MODE_PLAYER
SPRITE_MODE_NPC
DrawSpriteOptions
enum DrawSpriteOptions
Enumerator
DRAW_SPRITE_USE_PLAYER_RASTERS
DRAW_SPRITE_UPSIDE_DOWN
DRAW_SPRITE_OVERRIDE_PALETTES
DRAW_SPRITE_OVERRIDE_YAW
DRAW_SPRITE_OVERRIDE_ALPHA
SpriteIDFields
enum SpriteIDFields
Enumerator
SPRITE_ID_ANIM_MASK
SPRITE_ID_PAL_MASK
SPRITE_ID_SPR_MASK
SPRITE_ID_BACK_FACING
SPRITE_ID_TAIL_ALLOCATE
Function Documentation
create_shading_palette()
void create_shading_palette (Matrix4f mtx, s32 uls, s32 ult, s32 lrs, s32 lrt, s32 alpha, s32 otherModeLBits)
Referenced by imgfx_appendGfx_mesh_anim(), imgfx_appendGfx_mesh_basic(), imgfx_appendGfx_mesh_grid(), and spr_appendGfx_component_flat().
func_802DDEC4()
s32 func_802DDEC4 (s32 arg0)
Referenced by appendGfx_npc().
get_npc_comp_imgfx_idx()
s32 get_npc_comp_imgfx_idx (s32 spriteIdx, s32 compIdx)
imgfx_init()
void imgfx_init (void)
Referenced by spr_init_sprites().
set_npc_imgfx_all()
void set_npc_imgfx_all (s32 arg0, ImgFXType arg1, s32 arg2, s32 arg3, s32 arg4, s32 arg5, s32 arg6)
Referenced by appendGfx_npc_blur(), btl_delete_actor(), MagikoopaAI_11(), npc_imgfx_update(), npc_update_decoration_charged(), part_glow_off(), part_glow_on(), pause_partners_draw_contents(), pause_spirits_draw_contents(), pause_tutorial_draw_contents(), SentinelAI_Descend(), and SentinelAI_LosePlayerInit().
set_npc_imgfx_comp()
void set_npc_imgfx_comp (s32 spriteIdx, s32 compIdx, ImgFXType imgfx, s32 imgfxArg1, s32 imgfxArg2, s32 imgfxArg3, s32 imgfxArg4, s32 imgfxArg5)
Referenced by set_npc_imgfx_all().
set_player_imgfx_all()
void set_player_imgfx_all (s32 animID, ImgFXType imgfxType, s32 arg2, s32 arg3, s32 arg4, s32 arg5, s32 arg6)
Referenced by appendGfx_player(), appendGfx_player_spin(), appendGfx_test_reflection_floor(), entity_BlueWarpPipe_enter_pipe_init(), entity_BlueWarpPipe_enter_pipe_update(), entity_CymbalPlant_idle(), part_glow_off(), part_glow_on(), and update_riding_physics().
set_player_imgfx_comp()
void set_player_imgfx_comp (s32 spriteIdx, s32 compIdx, ImgFXType imgfx, s32 imgfxArg1, s32 imgfxArg2, s32 imgfxArg3, s32 imgfxArg4, s32 flags)
Referenced by appendGfx_player(), appendGfx_player_spin(), appendGfx_reflect_player_floor_fancy(), entity_CymbalPlant_idle(), render_player_model(), reset_outta_sight_alpha_on_menu_close(), set_player_imgfx_all(), worker_reflect_player_floor(), and worker_reflect_player_wall().
spr_draw_npc_sprite()
s32 spr_draw_npc_sprite (s32 spriteInstanceID, s32 yaw, s32 arg2, PAL_PTR * paletteList, Matrix4f mtx)
Referenced by appendGfx_nonplayer_actor_blur(), appendGfx_npc(), appendGfx_npc_blur(), func_unkA_draw_npc(), func_unkB_draw_npc(), npc_render_with_double_pal_blending(), npc_render_with_single_pal_blending(), npc_render_with_watt_idle_palettes(), npc_render_without_adjusted_palettes(), pause_partners_draw_contents(), pause_spirits_draw_contents(), pause_tutorial_draw_contents(), and render_with_adjusted_palettes().
spr_draw_player_sprite()
s32 spr_draw_player_sprite (s32 spriteInstanceID, s32 yaw, s32 arg2, PAL_PTR * paletteList, Matrix4f mtx)
Referenced by appendGfx_example_player(), appendGfx_fake_player(), appendGfx_npc(), appendGfx_npc_blur(), appendGfx_player(), appendGfx_player_spin(), appendGfx_reflect_player_floor_basic(), appendGfx_reflect_player_floor_fancy(), appendGfx_reflect_player_wall(), appendGfx_shrunk_player(), appendGfx_test_player_reflection(), appendGfx_test_reflection_floor(), appendGfx_test_reflection_wall(), func_unkA_draw_player(), func_unkB_draw_player(), npc_render_without_adjusted_palettes(), and render_with_adjusted_palettes().
spr_free_sprite()
s32 spr_free_sprite (s32 spriteInstanceID)
Referenced by btl_delete_actor(), free_npc(), free_npc_by_index(), pause_cleanup(), pause_partners_cleanup(), pause_spirits_cleanup(), and set_npc_sprite().
spr_get_comp_position()
s32 spr_get_comp_position (s32 spriteIdx, s32 compListIdx, s32 * outX, s32 * outY, s32 * outZ)
spr_get_notify_value()
s32 spr_get_notify_value (s32 arg0)
Referenced by appendGfx_npc(), appendGfx_npc_actor(), set_actor_anim(), set_actor_anim_by_ref(), and update_nonplayer_actor_shadow().
spr_get_npc_color_variations()
s32 spr_get_npc_color_variations (s32 npcSpriteID)
Referenced by npc_reload_all(), npc_render_with_watt_idle_palettes(), render_with_palset_blending(), render_with_player_debuff_palettes(), render_with_poison_palettes(), render_with_static_palettes(), render_with_watt_attack_palettes(), and render_with_watt_idle_palettes().
spr_get_npc_palettes()
PAL_PTR * spr_get_npc_palettes (s32 npcSpriteID)
Referenced by func_unkA_draw_npc(), npc_reload_all(), npc_render_with_double_pal_blending(), npc_render_with_single_pal_blending(), npc_render_with_watt_idle_palettes(), render_with_berserk_palettes(), render_with_fear_palettes(), render_with_pal_blending(), render_with_palset_blending(), render_with_paralyze_palettes(), render_with_player_debuff_palettes(), render_with_poison_palettes(), render_with_sleep_palettes(), render_with_static_palettes(), render_with_watt_attack_palettes(), and render_with_watt_idle_palettes().
spr_get_npc_raster_info()
s32 spr_get_npc_raster_info (SpriteRasterInfo * out, s32 npcSpriteID, s32 rasterIndex)
Referenced by appendGfx_message(), func_80241610_97F0E0(), func_80241610_990DF0(), and func_80241610_993D40().
spr_get_player_palettes()
PAL_PTR * spr_get_player_palettes (s32 spriteIndex)
Referenced by func_unkA_draw_player(), render_with_berserk_palettes(), render_with_fear_palettes(), render_with_pal_blending(), render_with_palset_blending(), render_with_paralyze_palettes(), render_with_player_debuff_palettes(), render_with_poison_palettes(), render_with_sleep_palettes(), render_with_static_palettes(), render_with_watt_attack_palettes(), and render_with_watt_idle_palettes().
spr_get_player_raster()
IMG_PTR spr_get_player_raster (s32 rasterIndex, s32 playerSpriteID)
Referenced by spr_draw_component(), and spr_get_player_raster_info().
spr_get_player_raster_info()
void spr_get_player_raster_info (SpriteRasterInfo * out, s32 playerSpriteID, s32 rasterIndex)
Referenced by appendGfx_FallingSprite(), appendGfx_ritual_card(), and gfx_build_knocked_down_player().
spr_init_sprites()
void spr_init_sprites (s32 playerSpriteSet)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_end_battle(), state_step_exit_language_select(), state_step_intro(), state_step_language_select(), state_step_pause(), state_step_startup(), state_step_title_screen(), and state_step_unpause().
spr_load_npc_sprite()
s32 spr_load_npc_sprite (s32 animID, u32 * extraAnimList)
Parameters
animID - Set MSB for tail allocation (i.e. 0x80XXYYZZ)
Referenced by create_actor(), create_npc_impl(), load_partner_actor(), npc_reload_all(), pause_init(), pause_partners_init(), pause_spirits_init(), set_npc_sprite(), and update_npcs().
spr_load_sprite()
SpriteAnimData * spr_load_sprite (s32 idx, s32 arg1, s32 arg2)
Referenced by spr_load_npc_sprite(), and spr_load_player_sprite().
spr_render_init()
void spr_render_init (void)
Referenced by gfx_draw_frame().
spr_update_player_raster_cache()
void spr_update_player_raster_cache (void)
Referenced by spr_render_init().
spr_update_player_sprite()
s32 spr_update_player_sprite (s32 arg0, s32 arg1, f32 timescale)
Referenced by appendGfx_example_player(), appendGfx_fake_player(), appendGfx_player_actor(), appendGfx_shrunk_player(), appendGfx_test_player_reflection(), appendGfx_test_reflection_wall(), player_update_sprite(), set_actor_anim(), set_actor_anim_by_ref(), update_npcs(), update_player_actor_shadow(), worker_reflect_player_floor(), and worker_reflect_player_wall().
spr_update_sprite()
s32 spr_update_sprite (s32 spriteInstanceID, s32 animID, f32 timeScale)
Referenced by appendGfx_npc_actor(), pause_handle_input(), pause_partners_update(), pause_spirits_update(), set_actor_anim(), set_actor_anim_by_ref(), set_npc_sprite(), update_nonplayer_actor_shadow(), and update_npcs().
Variable Documentation
D_802DF3F0
Gfx D_802DF3F0[] extern
Referenced by spr_appendGfx_component().
D_802DF428
Gfx D_802DF428[] extern
Referenced by spr_appendGfx_component().
D_802DF460
Gfx D_802DF460[] extern
Referenced by spr_appendGfx_component().
D_802DF490
Gfx D_802DF490[] extern
Referenced by spr_appendGfx_component().
spr_animUpdateTimeScale
f32 spr_animUpdateTimeScale extern
Referenced by spr_component_update_commands(), and spr_set_anim_timescale().
spr_defaultQuad
Quad spr_defaultQuad extern
Referenced by spr_make_quad_for_size().
spr_playerSpriteSets
PlayerSpriteSet spr_playerSpriteSets[7] extern
Referenced by spr_init_sprites().
SprPauseVp
Vp SprPauseVp extern
Referenced by spr_appendGfx_component_flat().
SprPauseVpAlt
Vp SprPauseVpAlt extern
Referenced by spr_appendGfx_component_flat().