papermario: src/sprite_shading.c File Reference
sprite_shading.c File Reference
Functions
void appendGfx_shading_palette (Matrix4f mtx, s32 uls, s32 ult, s32 lrs, s32 lrt, s32 alpha, f32 shadowX, f32 shadowY, f32 shadowZ, s32 shadowR, s32 shadowG, s32 shadowB, s32 highlightR, s32 highlightG, s32 highlightB, s32 ambientPower, s32 otherModeLBits)
void clear_sprite_shading_data (void)
void init_sprite_shading_data (void)
void sprite_shading_set_light_source (u32 idx, s8 flags, f32 x, f32 y, f32 z, u8 r, u8 g, u8 b, f32 falloff, s8 arg9)
void create_shading_palette (Matrix4f mtx, s32 uls, s32 ult, s32 lrs, s32 lrt, s32 alpha, s32 otherModeLBits)
void func_801491E4 (Matrix4f mtx, s32 arg1, s32 arg2, s32 arg3, s32 arg4, s32 alpha)
Variables
SpriteShadingProfile * gSpriteShadingProfile
SpriteShadingProfile * gAuxSpriteShadingProfile
BSS SpriteShadingProfile wSpriteShadingProfile
BSS SpriteShadingProfile bSpriteShadingProfile
BSS SpriteShadingProfile wSpriteShadingProfileAux
BSS SpriteShadingProfile bSpriteShadingProfileAux
BSS PAL_BIN SpriteShadingPalette [16]
Function Documentation
appendGfx_shading_palette()
void appendGfx_shading_palette (Matrix4f mtx, s32 uls, s32 ult, s32 lrs, s32 lrt, s32 alpha, f32 shadowX, f32 shadowY, f32 shadowZ, s32 shadowR, s32 shadowG, s32 shadowB, s32 highlightR, s32 highlightG, s32 highlightB, s32 ambientPower, s32 otherModeLBits)
Referenced by create_shading_palette().
clear_sprite_shading_data()
void clear_sprite_shading_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
create_shading_palette()
void create_shading_palette (Matrix4f mtx, s32 uls, s32 ult, s32 lrs, s32 lrt, s32 alpha, s32 otherModeLBits)
Referenced by imgfx_appendGfx_mesh_anim(), imgfx_appendGfx_mesh_basic(), imgfx_appendGfx_mesh_grid(), and spr_appendGfx_component_flat().
func_801491E4()
void func_801491E4 (Matrix4f mtx, s32 arg1, s32 arg2, s32 arg3, s32 arg4, s32 alpha)
Referenced by appendGfx_item_entity(), and render_item_entities().
init_sprite_shading_data()
void init_sprite_shading_data (void)
Referenced by clear_sprite_shading_data(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
sprite_shading_set_light_source()
void sprite_shading_set_light_source (u32 idx, s8 flags, f32 x, f32 y, f32 z, u8 r, u8 g, u8 b, f32 falloff, s8 arg9)
Variable Documentation
bSpriteShadingProfile
BSS SpriteShadingProfile bSpriteShadingProfile
Referenced by init_sprite_shading_data().
bSpriteShadingProfileAux
BSS SpriteShadingProfile bSpriteShadingProfileAux
Referenced by init_sprite_shading_data().
gAuxSpriteShadingProfile
SpriteShadingProfile* gAuxSpriteShadingProfile
Referenced by clear_sprite_shading_data(), and init_sprite_shading_data().
gSpriteShadingProfile
SpriteShadingProfile* gSpriteShadingProfile
Referenced by appendGfx_item_entity(), clear_sprite_shading_data(), create_shading_palette(), imgfx_appendGfx_mesh_anim(), imgfx_appendGfx_mesh_basic(), imgfx_appendGfx_mesh_grid(), init_sprite_shading_data(), render_item_entities(), spr_appendGfx_component(), spr_appendGfx_component_flat(), and sprite_shading_set_light_source().
SpriteShadingPalette
BSS PAL_BIN SpriteShadingPalette[16]
Referenced by appendGfx_shading_palette().
wSpriteShadingProfile
BSS SpriteShadingProfile wSpriteShadingProfile
Referenced by init_sprite_shading_data().
wSpriteShadingProfileAux
BSS SpriteShadingProfile wSpriteShadingProfileAux
Referenced by init_sprite_shading_data().