papermario: src/effects/stars_orbiting.c File Reference
stars_orbiting.c File Reference
Functions
void stars_orbiting_init (EffectInstance *effect)
void stars_orbiting_update (EffectInstance *effect)
void stars_orbiting_render (EffectInstance *effect)
void func_E005E318 (EffectInstance *effect)
void func_E005E334 (EffectInstance *effect)
void stars_orbiting_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 radius, s32 numStars, EffectInstance **outEffect)
Variables
Gfx D_09000440_363090 []
Gfx D_090004F0_363140 []
Gfx * D_E005E670 [] = { D_090004F0_363140 }
Gfx * D_E005E674 [] = { D_09000440_363090 }
Function Documentation
func_E005E318()
void func_E005E318 (EffectInstance * effect)
Referenced by stars_orbiting_main().
func_E005E334()
void func_E005E334 (EffectInstance * effect)
Referenced by func_E005E318().
stars_orbiting_init()
void stars_orbiting_init (EffectInstance * effect)
Referenced by stars_orbiting_main().
stars_orbiting_main()
void stars_orbiting_main (s32 type, f32 posX, f32 posY, f32 posZ, f32 radius, s32 numStars, EffectInstance ** outEffect)
stars_orbiting_render()
void stars_orbiting_render (EffectInstance * effect)
Referenced by stars_orbiting_main().
stars_orbiting_update()
void stars_orbiting_update (EffectInstance * effect)
Referenced by stars_orbiting_main().
Variable Documentation
D_09000440_363090
Gfx D_09000440_363090[] extern
D_090004F0_363140
Gfx D_090004F0_363140[] extern
D_E005E670
Gfx* D_E005E670[] = { D_090004F0_363140 }
Referenced by func_E005E334().
D_E005E674
Gfx* D_E005E674[] = { D_09000440_363090 }
Referenced by func_E005E334().