papermario: src/effects/stars_spread.c File Reference
stars_spread.c File Reference
Functions
void stars_spread_init (EffectInstance *effect)
void stars_spread_update (EffectInstance *effect)
void stars_spread_render (EffectInstance *effect)
void stars_spread_appendGfx (void *effect)
void stars_spread_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4, s32 arg5)
Variables
Gfx D_09000440_360E70 []
Gfx D_090004F0_360F20 []
Function Documentation
stars_spread_appendGfx()
void stars_spread_appendGfx (void * effect)
Referenced by stars_spread_render().
stars_spread_init()
void stars_spread_init (EffectInstance * effect)
Referenced by stars_spread_main().
stars_spread_main()
void stars_spread_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, s32 arg4, s32 arg5)
Referenced by fire_flower_update().
stars_spread_render()
void stars_spread_render (EffectInstance * effect)
Referenced by stars_spread_main().
stars_spread_update()
void stars_spread_update (EffectInstance * effect)
Referenced by stars_spread_main().
Variable Documentation
D_09000440_360E70
Gfx D_09000440_360E70[] extern
Referenced by stars_spread_appendGfx().
D_090004F0_360F20
Gfx D_090004F0_360F20[] extern
Referenced by stars_spread_appendGfx().