papermario: src/effects/stars_burst.c File Reference
stars_burst.c File Reference
Functions
void stars_burst_init (EffectInstance *effect)
void stars_burst_update (EffectInstance *effect)
void stars_burst_render (EffectInstance *effect)
void stars_burst_appendGfx (void *effect)
void stars_burst_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, s32 arg6)
Variables
Gfx D_090004C0_343500 []
Gfx D_090005E0_343620 []
u8 D_E0042780 []
Function Documentation
stars_burst_appendGfx()
void stars_burst_appendGfx (void * effect)
Referenced by stars_burst_render().
stars_burst_init()
void stars_burst_init (EffectInstance * effect)
Referenced by stars_burst_main().
stars_burst_main()
void stars_burst_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, s32 arg6)
stars_burst_render()
void stars_burst_render (EffectInstance * effect)
Referenced by stars_burst_main().
stars_burst_update()
void stars_burst_update (EffectInstance * effect)
Referenced by stars_burst_main().
Variable Documentation
D_090004C0_343500
Gfx D_090004C0_343500[] extern
Referenced by stars_burst_appendGfx().
D_090005E0_343620
Gfx D_090005E0_343620[] extern
Referenced by stars_burst_appendGfx().
D_E0042780
u8 D_E0042780[]
Initial value:
= {
    254, 172, 172,
    254, 172, 213,
    254, 180, 154,
    213, 180, 254,
    180, 180, 254,
    180, 221, 254,
    180, 254, 254,
    180, 254, 213,
    180, 254, 180,
    213, 254, 180,
    254, 254, 180,
    254, 213, 172,
}
Referenced by stars_burst_appendGfx().