papermario: src/effects/star_spirits_energy.c File Reference
star_spirits_energy.c File Reference
Data Structures
struct UnkStarSpiritsEnergy
Functions
void star_spirits_energy_init (EffectInstance *effect)
void star_spirits_energy_update (EffectInstance *effect)
void star_spirits_energy_render (EffectInstance *effect)
void star_spirits_energy_appendGfx (void *effect)
EffectInstance * star_spirits_energy_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09004E00_412090 []
Gfx D_09005168_4123F8 []
Gfx D_090051C8_412458 []
Gfx D_09005370_412600 []
Gfx D_090053D0_412660 []
Gfx D_09005440_4126D0 []
Gfx * D_E0122B90 []
Gfx * D_E0122BA0 [] = { D_09005440_4126D0 }
Gfx * D_E0122BA4 [] = { D_09004E00_412090 }
UnkStarSpiritsEnergy D_E0122BA8 []
UnkStarSpiritsEnergy D_E0122C20 []
Data Structure Documentation
UnkStarSpiritsEnergy
struct UnkStarSpiritsEnergy
Data Fields
u16 unk_00
char unk_02
u8 unk_03
Function Documentation
star_spirits_energy_appendGfx()
void star_spirits_energy_appendGfx (void * effect)
Referenced by star_spirits_energy_render().
star_spirits_energy_init()
void star_spirits_energy_init (EffectInstance * effect)
Referenced by star_spirits_energy_main().
star_spirits_energy_main()
EffectInstance * star_spirits_energy_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
star_spirits_energy_render()
void star_spirits_energy_render (EffectInstance * effect)
Referenced by star_spirits_energy_main().
star_spirits_energy_update()
void star_spirits_energy_update (EffectInstance * effect)
Referenced by star_spirits_energy_main().
Variable Documentation
D_09004E00_412090
Gfx D_09004E00_412090[] extern
D_09005168_4123F8
Gfx D_09005168_4123F8[] extern
D_090051C8_412458
Gfx D_090051C8_412458[] extern
D_09005370_412600
Gfx D_09005370_412600[] extern
D_090053D0_412660
Gfx D_090053D0_412660[] extern
D_09005440_4126D0
Gfx D_09005440_4126D0[] extern
D_E0122B90
Gfx* D_E0122B90[]
Initial value:
= {
    D_09005168_4123F8, D_090051C8_412458, D_09005370_412600, D_090053D0_412660
}
Referenced by star_spirits_energy_appendGfx().
D_E0122BA0
Gfx* D_E0122BA0[] = { D_09005440_4126D0 }
Referenced by star_spirits_energy_appendGfx().
D_E0122BA4
Gfx* D_E0122BA4[] = { D_09004E00_412090 }
Referenced by star_spirits_energy_appendGfx().
D_E0122BA8
UnkStarSpiritsEnergy D_E0122BA8[]
Referenced by star_spirits_energy_update().
D_E0122C20
UnkStarSpiritsEnergy D_E0122C20[]
Referenced by star_spirits_energy_update().