papermario: src/effects/star.c File Reference
star.c File Reference
Functions
void star_init (EffectInstance *effect)
void star_update (EffectInstance *effect)
void star_render (EffectInstance *effect)
void star_appendGfx (void *effect)
EffectInstance * star_main (s32 type, f32 startX, f32 startY, f32 startZ, f32 endX, f32 endY, f32 endZ, f32 speed)
EFFECT_DEF_LANDING_DUST (landing_dust_main)
Variables
Vtx_t D_09001400_333AA0 []
Gfx D_09001530_333BD0 []
Gfx D_09001650_333CF0 []
Gfx D_09001780_333E20 []
Gfx D_090017D0_333E70 []
Function Documentation
EFFECT_DEF_LANDING_DUST()
EFFECT_DEF_LANDING_DUST (landing_dust_main)
star_appendGfx()
void star_appendGfx (void * effect)
Referenced by star_render().
star_init()
void star_init (EffectInstance * effect)
Referenced by star_main().
star_main()
EffectInstance * star_main (s32 type, f32 startX, f32 startY, f32 startZ, f32 endX, f32 endY, f32 endZ, f32 speed)
star_render()
void star_render (EffectInstance * effect)
Referenced by star_main().
star_update()
void star_update (EffectInstance * effect)
Referenced by star_main().
Variable Documentation
D_09001400_333AA0
Vtx_t D_09001400_333AA0[] extern
Referenced by star_appendGfx().
D_09001530_333BD0
Gfx D_09001530_333BD0[] extern
Referenced by star_appendGfx().
D_09001650_333CF0
Gfx D_09001650_333CF0[] extern
Referenced by star_appendGfx().
D_09001780_333E20
Gfx D_09001780_333E20[] extern
Referenced by star_appendGfx().
D_090017D0_333E70
Gfx D_090017D0_333E70[] extern
Referenced by star_appendGfx().