papermario: src/startup_screen_fading.c File Reference
startup_screen_fading.c File Reference
Functions
void startup_set_fade_screen_alpha (s16 alpha)
void startup_set_fade_screen_color (s16 color)
b32 startup_fade_screen_in (s16 subtractAlpha)
b32 startup_fade_screen_out (s16 addAlpha)
void startup_fade_screen_update (void)
Function Documentation
startup_fade_screen_in()
b32 startup_fade_screen_in (s16 subtractAlpha)
Referenced by state_step_logos(), and state_step_title_screen().
startup_fade_screen_out()
b32 startup_fade_screen_out (s16 addAlpha)
Referenced by state_step_intro(), state_step_logos(), and state_step_title_screen().
startup_fade_screen_update()
void startup_fade_screen_update (void)
Referenced by state_init_intro(), state_init_logos(), state_init_title_screen(), state_step_demo(), state_step_intro(), state_step_logos(), and state_step_title_screen().
startup_set_fade_screen_alpha()
void startup_set_fade_screen_alpha (s16 alpha)
Referenced by btl_update(), state_init_intro(), state_init_logos(), state_step_demo(), and state_step_logos().
startup_set_fade_screen_color()
void startup_set_fade_screen_color (s16 color)
Referenced by btl_update(), state_init_intro(), state_init_logos(), state_step_demo(), state_step_logos(), and state_step_title_screen().