papermario: src/effects/stars_shimmer.c File Reference
stars_shimmer.c File Reference
Functions
void stars_shimmer_init (EffectInstance *effect)
void stars_shimmer_update (EffectInstance *effect)
void stars_shimmer_render (EffectInstance *effect)
void stars_shimmer_appendGfx (void *effect)
void stars_shimmer_main (s32 type, f32 x, f32 y, f32 z, f32 arg4, f32 arg5, s32 numParts, s32 arg7)
Variables
Gfx D_09000F20_338EE0 []
Gfx D_090011C8_339188 []
Gfx D_090011E0_3391A0 []
Gfx D_090011F8_3391B8 []
Gfx D_09001210_3391D0 []
Gfx D_09001228_3391E8 []
Gfx D_09001240_339200 []
Gfx D_09001258_339218 []
Gfx D_09001270_339230 []
Gfx * D_E0044DB0 []
u8 D_E0044DD0 []
u8 D_E0044DF4 []
u8 D_E0044E04 []
Function Documentation
stars_shimmer_appendGfx()
void stars_shimmer_appendGfx (void * effect)
Referenced by stars_shimmer_render().
stars_shimmer_init()
void stars_shimmer_init (EffectInstance * effect)
Referenced by stars_shimmer_main().
stars_shimmer_main()
void stars_shimmer_main (s32 type, f32 x, f32 y, f32 z, f32 arg4, f32 arg5, s32 numParts, s32 arg7)
stars_shimmer_render()
void stars_shimmer_render (EffectInstance * effect)
Referenced by stars_shimmer_main().
stars_shimmer_update()
void stars_shimmer_update (EffectInstance * effect)
Referenced by stars_shimmer_main().
Variable Documentation
D_09000F20_338EE0
Gfx D_09000F20_338EE0[] extern
Referenced by stars_shimmer_appendGfx().
D_090011C8_339188
Gfx D_090011C8_339188[] extern
D_090011E0_3391A0
Gfx D_090011E0_3391A0[] extern
D_090011F8_3391B8
Gfx D_090011F8_3391B8[] extern
D_09001210_3391D0
Gfx D_09001210_3391D0[] extern
D_09001228_3391E8
Gfx D_09001228_3391E8[] extern
D_09001240_339200
Gfx D_09001240_339200[] extern
D_09001258_339218
Gfx D_09001258_339218[] extern
D_09001270_339230
Gfx D_09001270_339230[] extern
D_E0044DB0
Gfx* D_E0044DB0[]
Initial value:
= {
    D_09001210_3391D0, D_09001228_3391E8, D_09001240_339200, D_09001258_339218,
    D_09001270_339230, D_090011C8_339188, D_090011E0_3391A0, D_090011F8_3391B8
}
Referenced by stars_shimmer_appendGfx().
D_E0044DD0
u8 D_E0044DD0[]
Initial value:
= {
    254, 172, 172,
    254, 172, 213,
    254, 180, 154,
    213, 180, 254,
    180, 180, 254,
    180, 221, 254,
    180, 254, 254,
    180, 254, 213,
    180, 254, 180,
    213, 254, 180,
    254, 254, 180,
    254, 213, 172,
}
Referenced by stars_shimmer_appendGfx().
D_E0044DF4
u8 D_E0044DF4[]
Initial value:
= {
    30, 60, 90, 100, 104, 106, 108, 110, 112, 113, 113, 110, 107, 103, 0x00, 0x00
}
Referenced by stars_shimmer_update().
D_E0044E04
u8 D_E0044E04[]
Initial value:
= {
    30, 60, 90, 100, 104, 106, 108, 110, 112, 113, 113, 110, 107, 103, 0x00, 0x00
}
Referenced by stars_shimmer_update().