papermario: src/effects/star_outline.c File Reference
star_outline.c File Reference
Functions
void star_outline_init (EffectInstance *effect)
void star_outline_update (EffectInstance *effect)
void star_outline_render (EffectInstance *effect)
void star_outline_appendGfx (void *effect)
EffectInstance * star_outline_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 arg5)
Variables
Gfx D_09000800_4147A0 []
Gfx D_09000B20_414AC0 []
Gfx D_09000B90_414B30 []
Gfx * D_E0126BC0 [] = { D_09000B90_414B30 }
Gfx * D_E0126BC4 [] = { D_09000B20_414AC0 }
Gfx * D_E0126BC8 [] = { D_09000800_4147A0 }
Function Documentation
star_outline_appendGfx()
void star_outline_appendGfx (void * effect)
Referenced by star_outline_render().
star_outline_init()
void star_outline_init (EffectInstance * effect)
Referenced by star_outline_main().
star_outline_main()
EffectInstance * star_outline_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 arg5)
star_outline_render()
void star_outline_render (EffectInstance * effect)
Referenced by star_outline_main().
star_outline_update()
void star_outline_update (EffectInstance * effect)
Referenced by star_outline_main().
Variable Documentation
D_09000800_4147A0
Gfx D_09000800_4147A0[] extern
D_09000B20_414AC0
Gfx D_09000B20_414AC0[] extern
D_09000B90_414B30
Gfx D_09000B90_414B30[] extern
D_E0126BC0
Gfx* D_E0126BC0[] = { D_09000B90_414B30 }
Referenced by star_outline_appendGfx().
D_E0126BC4
Gfx* D_E0126BC4[] = { D_09000B20_414AC0 }
Referenced by star_outline_appendGfx().
D_E0126BC8
Gfx* D_E0126BC8[] = { D_09000800_4147A0 }
Referenced by star_outline_appendGfx().