papermario: src/effects/stat_change.c File Reference
stat_change.c File Reference
Data Structures
struct ExtraArrowDataEntry
struct ArrowDataTableEntry
Enumerations
enum ArrowType { ARROW_TYPE_ATK_UP = 0 , ARROW_TYPE_ATK_DOWN = 1 , ARROW_TYPE_DEF_UP = 2 }
Functions
void func_E00AC288 (EffectInstance *effect)
void func_E00AC2A4 (EffectInstance *effect)
void stat_change_init (EffectInstance *effect)
void stat_change_update (EffectInstance *effect)
void stat_change_render (EffectInstance *effect)
EffectInstance * stat_change_main (s32 arg0, f32 x, f32 y, f32 z, f32 scale, s32 time)
Variables
Gfx D_09002700_3B1E00 []
Gfx D_09002798_3B1E98 []
Gfx D_09002860_3B1F60 []
Gfx D_09002880_3B1F80 []
Gfx D_090028A0_3B1FA0 []
Gfx D_090028C0_3B1FC0 []
Gfx D_090028E0_3B1FE0 []
Gfx D_09002950_3B2050 []
Gfx D_09002990_3B2090 []
Gfx D_090029D0_3B20D0 []
Gfx D_09002A10_3B2110 []
Gfx D_09002A50_3B2150 []
Gfx D_09002A90_3B2190 []
Gfx D_09002AD0_3B21D0 []
Gfx D_09002B10_3B2210 []
Gfx D_09002B50_3B2250 []
Gfx D_09002B90_3B2290 []
Gfx D_09002BD0_3B22D0 []
Gfx D_09002C10_3B2310 []
Gfx * D_E00AC7B0 [] = { D_09002700_3B1E00, D_09002700_3B1E00, D_09002798_3B1E98 }
Gfx * D_E00AC7BC [] = { D_09002860_3B1F60, D_09002880_3B1F80, D_09002860_3B1F60 }
Gfx * D_E00AC7C8 []
ExtraArrowDataEntry D_E00AC7F8 []
ExtraArrowDataEntry D_E00AC83C []
ArrowDataTableEntry D_E00AC880 []
Data Structure Documentation
ExtraArrowDataEntry
struct ExtraArrowDataEntry
Data Fields
u8 unk_00
u8 unk_01
ArrowDataTableEntry
struct ArrowDataTableEntry
Data Fields
s32 type
s32 value
Enumeration Type Documentation
ArrowType
enum ArrowType
Enumerator
ARROW_TYPE_ATK_UP
ARROW_TYPE_ATK_DOWN
ARROW_TYPE_DEF_UP
Function Documentation
func_E00AC288()
void func_E00AC288 (EffectInstance * effect)
Referenced by stat_change_main().
func_E00AC2A4()
void func_E00AC2A4 (EffectInstance * effect)
Referenced by func_E00AC288().
stat_change_init()
void stat_change_init (EffectInstance * effect)
Referenced by stat_change_main().
stat_change_main()
EffectInstance * stat_change_main (s32 arg0, f32 x, f32 y, f32 z, f32 scale, s32 time)
stat_change_render()
void stat_change_render (EffectInstance * effect)
Referenced by stat_change_main().
stat_change_update()
void stat_change_update (EffectInstance * effect)
Referenced by stat_change_main().
Variable Documentation
D_09002700_3B1E00
Gfx D_09002700_3B1E00[] extern
D_09002798_3B1E98
Gfx D_09002798_3B1E98[] extern
D_09002860_3B1F60
Gfx D_09002860_3B1F60[] extern
D_09002880_3B1F80
Gfx D_09002880_3B1F80[] extern
D_090028A0_3B1FA0
Gfx D_090028A0_3B1FA0[] extern
Referenced by func_E00AC2A4().
D_090028C0_3B1FC0
Gfx D_090028C0_3B1FC0[] extern
Referenced by func_E00AC2A4().
D_090028E0_3B1FE0
Gfx D_090028E0_3B1FE0[] extern
Referenced by func_E00AC2A4().
D_09002950_3B2050
Gfx D_09002950_3B2050[] extern
D_09002990_3B2090
Gfx D_09002990_3B2090[] extern
D_090029D0_3B20D0
Gfx D_090029D0_3B20D0[] extern
D_09002A10_3B2110
Gfx D_09002A10_3B2110[] extern
D_09002A50_3B2150
Gfx D_09002A50_3B2150[] extern
D_09002A90_3B2190
Gfx D_09002A90_3B2190[] extern
D_09002AD0_3B21D0
Gfx D_09002AD0_3B21D0[] extern
D_09002B10_3B2210
Gfx D_09002B10_3B2210[] extern
D_09002B50_3B2250
Gfx D_09002B50_3B2250[] extern
D_09002B90_3B2290
Gfx D_09002B90_3B2290[] extern
D_09002BD0_3B22D0
Gfx D_09002BD0_3B22D0[] extern
D_09002C10_3B2310
Gfx D_09002C10_3B2310[] extern
D_E00AC7B0
Gfx* D_E00AC7B0[] = { D_09002700_3B1E00, D_09002700_3B1E00, D_09002798_3B1E98 }
Referenced by func_E00AC2A4().
D_E00AC7BC
Gfx* D_E00AC7BC[] = { D_09002860_3B1F60, D_09002880_3B1F80, D_09002860_3B1F60 }
Referenced by func_E00AC2A4().
D_E00AC7C8
Gfx* D_E00AC7C8[]
Initial value:
= {
    D_09002950_3B2050, D_09002990_3B2090, D_090029D0_3B20D0, D_09002A10_3B2110,
    D_09002A50_3B2150, D_09002A90_3B2190, D_09002AD0_3B21D0, D_09002B10_3B2210,
    D_09002B50_3B2250, D_09002B90_3B2290, D_09002BD0_3B22D0, D_09002C10_3B2310
}
Referenced by func_E00AC2A4().
D_E00AC7F8
ExtraArrowDataEntry D_E00AC7F8[]
Referenced by stat_change_update().
D_E00AC83C
ExtraArrowDataEntry D_E00AC83C[]
Referenced by stat_change_update().
D_E00AC880
ArrowDataTableEntry D_E00AC880[]
Initial value:
= {
    { .type = ARROW_TYPE_ATK_UP, .value = 1 },
    { .type = ARROW_TYPE_ATK_UP, .value = 2 },
    { .type = ARROW_TYPE_ATK_UP, .value = 3 },
    { .type = ARROW_TYPE_ATK_DOWN, .value = -1 },
    { .type = ARROW_TYPE_ATK_DOWN, .value = -2 },
    { .type = ARROW_TYPE_ATK_DOWN, .value = -3 },
    { .type = ARROW_TYPE_DEF_UP, .value = 1 },
    { .type = ARROW_TYPE_DEF_UP, .value = 2 },
    { .type = ARROW_TYPE_DEF_UP, .value = 3 },
    { .type = ARROW_TYPE_ATK_UP, .value = 0 },
}
Referenced by stat_change_main().