papermario: src/effects/static_status.c File Reference
static_status.c File Reference
Functions
void static_status_init (EffectInstance *effect)
void static_status_update (EffectInstance *effect)
void static_status_render (EffectInstance *effect)
void static_status_appendGfx (void *effect)
EffectInstance * static_status_main (s32 type, f32 x, f32 y, f32 z, f32 scale, s32 numBolts, s32 duration)
void func_E00E651C (void)
Variables
Gfx D_09000280_3E1550 []
Gfx D_090003A0_3E1670 []
Gfx * D_E00E6880 [] = { D_090003A0_3E1670, D_090003A0_3E1670 }
Gfx * D_E00E6888 [] = { D_09000280_3E1550, D_09000280_3E1550 }
s32 StaticEffectFrameCount [] = { 24, 12 }
f32 StaticEffectScaleVals0 []
u8 StaticEffectAlphaVals0 []
f32 StaticEffectScaleVals1 []
u8 StaticEffectAlphaVals1 []
Function Documentation
func_E00E651C()
void func_E00E651C (void)
static_status_appendGfx()
void static_status_appendGfx (void * effect)
Referenced by static_status_render().
static_status_init()
void static_status_init (EffectInstance * effect)
Referenced by static_status_main().
static_status_main()
EffectInstance * static_status_main (s32 type, f32 x, f32 y, f32 z, f32 scale, s32 numBolts, s32 duration)
static_status_render()
void static_status_render (EffectInstance * effect)
Referenced by static_status_main().
static_status_update()
void static_status_update (EffectInstance * effect)
Referenced by static_status_main().
Variable Documentation
D_09000280_3E1550
Gfx D_09000280_3E1550[] extern
D_090003A0_3E1670
Gfx D_090003A0_3E1670[] extern
D_E00E6880
Gfx* D_E00E6880[] = { D_090003A0_3E1670, D_090003A0_3E1670 }
Referenced by static_status_appendGfx().
D_E00E6888
Gfx* D_E00E6888[] = { D_09000280_3E1550, D_09000280_3E1550 }
Referenced by static_status_appendGfx().
StaticEffectAlphaVals0
u8 StaticEffectAlphaVals0[]
Initial value:
= {
    0xFA, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
}
Referenced by static_status_update().
StaticEffectAlphaVals1
u8 StaticEffectAlphaVals1[]
Initial value:
= {
    0xFA, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
}
Referenced by static_status_update().
StaticEffectFrameCount
s32 StaticEffectFrameCount[] = { 24, 12 }
Referenced by static_status_main(), and static_status_update().
StaticEffectScaleVals0
f32 StaticEffectScaleVals0[]
Initial value:
= {
     0.9f, 1.0f,  1.0f, 0.9f, 0.85f, 0.8f, 0.75f, 0.7f, 0.65f,  0.6f, 0.55f,  0.5f,
    0.45f, 0.4f, 0.35f, 0.3f, 0.25f, 0.2f, 0.15f, 0.1f, 0.05f, 0.03f, 0.02f, 0.01f
}
Referenced by static_status_update().
StaticEffectScaleVals1
f32 StaticEffectScaleVals1[]
Initial value:
= {
    0.9f, 1.0f, 1.0f, 0.9f, 0.8f, 0.7f, 0.6f, 0.5f, 0.4f, 0.3f, 0.2f, 0.1f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
}
Referenced by static_status_update().