papermario: src/status_star_shimmer.c File Reference
status_star_shimmer.c File Reference
Data Structures
struct ShimmerParticle
struct ShimmerEmitter
Macros
#define NUM_PARTICLES 56
Functions
INCLUDE_IMG ("ui/status/shimmer_particle.png", ui_status_shimmer_particle_png)
void star_power_shimmer_start (s32 emitterIdx, f32 x, f32 y, f32 scale)
void star_power_shimmer_init (void)
void star_power_shimmer_update (void)
void star_power_shimmer_draw (void)
Variables
Vp ShimmerViewport
u8 AnimatedScale []
Vec2b InitialVelocities [56]
BSS ShimmerEmitter ShimmerEmitters [1]
Data Structure Documentation
ShimmerParticle
struct ShimmerParticle
Data Fields
u8 alive
s8 animTime
u8 lifetime
Vec2f pos
Color_RGBA8 rgba
f32 scale
s8 timeLeft
Vec2f vel
ShimmerEmitter
struct ShimmerEmitter
Data Fields
ShimmerParticle particles[1+56]
Macro Definition Documentation
NUM_PARTICLES
#define NUM_PARTICLES 56
Function Documentation
INCLUDE_IMG()
INCLUDE_IMG ("ui/status/shimmer_particle.png" , ui_status_shimmer_particle_png)
star_power_shimmer_draw()
void star_power_shimmer_draw (void)
Referenced by update_status_bar().
star_power_shimmer_init()
void star_power_shimmer_init (void)
Referenced by initialize_status_bar().
star_power_shimmer_start()
void star_power_shimmer_start (s32 emitterIdx, f32 x, f32 y, f32 scale)
Referenced by update_status_bar().
star_power_shimmer_update()
void star_power_shimmer_update (void)
Referenced by update_status_bar().
Variable Documentation
AnimatedScale
u8 AnimatedScale[]
Initial value:
= {
    40, 90, 81, 72, 65, 59, 53, 47, 43, 38, 34, 31, 28, 25, 22, 20, 18, 16, 15, 13, 12, 10, 9, 8, 7, 7, 6, 5, 5, 4
}
Referenced by star_power_shimmer_update().
InitialVelocities
Vec2b InitialVelocities[56]
Initial value:
= {
    { 247, 105 }, { 239, 87 }, { 17, 87 }, { 9, 105 }, { 0, 122 }, { 230, 69 }, { 26, 69 }, { 221, 52 }, { 35, 52 },
    { 202, 49 }, { 186, 255 }, { 200, 241 }, { 0, 200 }, { 56, 241 }, { 70, 255 }, { 54, 49 }, { 196, 222 },
    { 239, 191 }, { 17, 191 }, { 60, 222 }, { 85, 13 }, { 74, 46 }, { 99, 27 }, { 93, 43 }, { 12, 33 }, { 12, 22 },
    { 24, 22 }, { 24, 33 }, { 12, 10 }, { 24, 10 }, { 24, 45 }, { 232, 33 }, { 232, 22 }, { 232, 45 }, { 113, 40 },
    { 193, 203 }, { 190, 183 }, { 182, 46 }, { 163, 43 }, { 35, 182 }, { 52, 173 }, { 12, 45 }, { 244, 22 },
    { 244, 33 }, { 232, 10 }, { 244, 10 }, { 244, 45 }, { 204, 173 }, { 221, 182 }, { 186, 164 }, { 171, 13 },
    { 157, 27 }, { 143, 40 }, { 63, 203 }, { 66, 183 }, { 70, 164 }
}
Referenced by star_power_shimmer_update().
ShimmerEmitters
BSS ShimmerEmitter ShimmerEmitters[1]
Referenced by star_power_shimmer_draw(), star_power_shimmer_init(), star_power_shimmer_start(), and star_power_shimmer_update().
ShimmerViewport
Vp ShimmerViewport
Initial value:
= {
    .vp = {
        .vscale = { 640, 480, 511, 0 },
        .vtrans = { 640, 480, 511, 0 }
    }
}
Referenced by star_power_shimmer_draw().