papermario: src/status_icons.c File Reference
status_icons.c File Reference
Data Structures
struct HudComplexStatusIcon
struct HudSimpleStatusIcon
struct HudStatusIcon
Macros
#define MAX_ICONS (64)
Enumerations
enum StatusIconFlag {
STATUS_ICON_FLAG_USED = 0x001 , STATUS_ICON_FLAG_BATTLE = 0x002 , STATUS_ICON_FLAG_DEBUFF = 0x004 , STATUS_ICON_FLAG_STATIC = 0x008 ,
STATUS_ICON_FLAG_TRANSPARENT = 0x010 , STATUS_ICON_FLAG_STATUS_CHILL_OUT = 0x020 , STATUS_ICON_FLAG_BOOST_JUMP = 0x040 , STATUS_ICON_FLAG_BOOST_HAMMER = 0x080 ,
STATUS_ICON_FLAG_BOOST_PARTNER = 0x100 , STATUS_ICON_FLAG_SURPRISE = 0x200 , STATUS_ICON_FLAG_PERIL = 0x400 , STATUS_ICON_FLAG_DANGER = 0x800
}
enum StatusIconTask { STATUS_ICON_TASK_NONE = 0 , STATUS_ICON_TASK_LOAD = 1 , STATUS_ICON_TASK_DRAW = 2 }
Functions
void update_merlee_message (void *popup)
void draw_merlee_message (void *popup)
void func_80045BC8 (void)
void init_all_status_icons (void)
void update_all_status_icons (void *popup)
void draw_all_status_icons (void *popup)
void func_80045AC0 (void)
void func_80045B10 (void)
void update_merlee_messages (void)
void draw_merlee_messages (void)
PopupMessage * get_current_merlee_message (void)
void dispose_merlee_message (PopupMessage *popup)
void show_merlee_message (s16 messageIndex, s16 duration)
void draw_merlee_message_string (PopupMessage *popup, s32 posX, s32 posY)
s32 is_merlee_message_done (void)
s32 create_status_icon_set (void)
void remove_all_status_icons (s32 iconID)
void set_status_icons_properties (s32 iconID, f32 x, f32 y, f32 z, s32 arg, s32 arg2, s32 radius, s32 offsetY)
void set_status_icons_offset (s32 iconID, s32 offsetY, s32 offsetX)
void create_status_debuff (s32 iconID, s32 statusID)
void remove_status_debuff (s32 iconID)
void enable_status_debuff (s32 iconID)
void create_status_static (s32 iconID, s32 statusID)
void remove_status_static (s32 iconID)
void enable_status_static (s32 iconID)
void create_status_transparent (s32 iconID, s32 statusID)
void remove_status_transparent (s32 iconID)
void enable_status_transparent (s32 iconID)
void create_status_chill_out (s32 iconID)
void remove_status_chill_out (s32 iconID)
void enable_status_chill_out (s32 iconID)
void create_status_icon_boost_jump (s32 iconID)
void remove_status_icon_boost_jump (s32 iconID)
void enable_status_icon_boost_jump (s32 iconID)
void create_status_icon_boost_hammer (s32 iconID)
void remove_status_icon_boost_hammer (s32 iconID)
void enable_status_icon_boost_hammer (s32 iconID)
void create_status_icon_boost_partner (s32 iconID)
void remove_status_icon_boost_partner (s32 iconID)
void enable_status_icon_boost_partner (s32 iconID)
void create_status_icon_surprise (s32 iconID)
void remove_status_icon_surprise (s32 iconID)
void enable_status_icon_surprise (s32 iconID)
void create_status_icon_peril (s32 iconID)
void remove_status_icon_peril (s32 iconID)
void enable_status_icon_peril (s32 iconID)
void create_status_icon_danger (s32 iconID)
void remove_status_icon_danger (s32 iconID)
void enable_status_icon_danger (s32 iconID)
Variables
s16 D_80078160 [] = { 28, 40 }
s16 D_80078164 [] = { 0, -2 }
s32 D_80078168 []
BSS PopupMessage D_800A0BC0 [32]
BSS s32 D_800A0F40
BSS HudStatusIcon * D_800A0F44
HudScript HES_Item_Present
HudScript HES_AsleepBegin
HudScript HES_AsleepEnd
HudScript HES_ElectrifiedBegin
HudScript HES_ElectrifiedEnd
HudScript HES_ParalyzedBegin
HudScript HES_ParalyzedEnd
HudScript HES_DizzyEnd
HudScript HES_PoisonedBegin
HudScript HES_PoisonedEnd
HudScript HES_DizzyBegin
HudScript HES_FrozenBegin
HudScript HES_FrozenEnd
HudScript HES_WeakenedLoop
HudScript HES_WeakenedBegin
HudScript HES_WeakenedEnd
HudScript HES_StoppedBegin
HudScript HES_StoppedEnd
HudScript HES_ShrunkBegin
HudScript HES_ShrunkEnd
HudScript HES_TransparentBegin
HudScript HES_TransparentEnd
HudScript HES_BoostJumpBegin
HudScript HES_BoostJumpEnd
HudScript HES_BoostHammerBegin
HudScript HES_BoostHammerEnd
HudScript HES_BoostPartner
HudScript HES_Surprise
HudScript HES_Peril
HudScript HES_Danger
const f32 status_icons_rodata_alignment = 0.0f
Data Structure Documentation
HudComplexStatusIcon
struct HudComplexStatusIcon
Data Fields
s8 active
s32 activeElementID
s8 activeTask
s8 frameCounter
s8 removing
s32 removingElementID
s8 removingTask
s8 unk_04
HudSimpleStatusIcon
struct HudSimpleStatusIcon
Data Fields
s8 active
s32 activeElementID
s8 removing
HudStatusIcon
struct HudStatusIcon
Data Fields
HudSimpleStatusIcon boostHammer
HudSimpleStatusIcon boostJump
HudSimpleStatusIcon boostPartner
HudSimpleStatusIcon danger
s32 flags
s32 offsetX
s32 offsetY
HudSimpleStatusIcon peril
s32 prevIndexBoostHammer
s32 prevIndexBoostJump
HudComplexStatusIcon status1
s32 status1OffsetY
s32 status1Radius
HudComplexStatusIcon status2
s32 status2OffsetY
s32 status2Radius
HudComplexStatusIcon status3
s32 status3OffsetY
s32 status3Radius
HudComplexStatusIcon status4
s32 status4OffsetY
s32 status4Radius
HudSimpleStatusIcon surprise
Vec3f worldPos
Macro Definition Documentation
MAX_ICONS
#define MAX_ICONS (64)
Referenced by create_status_icon_set(), draw_all_status_icons(), init_all_status_icons(), and update_all_status_icons().
Enumeration Type Documentation
StatusIconFlag
enum StatusIconFlag
Enumerator
STATUS_ICON_FLAG_USED
STATUS_ICON_FLAG_BATTLE
STATUS_ICON_FLAG_DEBUFF
STATUS_ICON_FLAG_STATIC
STATUS_ICON_FLAG_TRANSPARENT
STATUS_ICON_FLAG_STATUS_CHILL_OUT
STATUS_ICON_FLAG_BOOST_JUMP
STATUS_ICON_FLAG_BOOST_HAMMER
STATUS_ICON_FLAG_BOOST_PARTNER
STATUS_ICON_FLAG_SURPRISE
STATUS_ICON_FLAG_PERIL
STATUS_ICON_FLAG_DANGER
StatusIconTask
enum StatusIconTask
Enumerator
STATUS_ICON_TASK_NONE
STATUS_ICON_TASK_LOAD
STATUS_ICON_TASK_DRAW
Function Documentation
create_status_chill_out()
void create_status_chill_out (s32 iconID)
Referenced by appendGfx_npc_actor().
create_status_debuff()
void create_status_debuff (s32 iconID, s32 statusID)
Referenced by appendGfx_npc_actor(), appendGfx_player_actor(), and inflict_status().
create_status_icon_boost_hammer()
void create_status_icon_boost_hammer (s32 iconID)
Referenced by appendGfx_player_actor().
create_status_icon_boost_jump()
void create_status_icon_boost_jump (s32 iconID)
Referenced by appendGfx_player_actor().
create_status_icon_boost_partner()
void create_status_icon_boost_partner (s32 iconID)
create_status_icon_danger()
void create_status_icon_danger (s32 iconID)
Referenced by appendGfx_player_actor().
create_status_icon_peril()
void create_status_icon_peril (s32 iconID)
Referenced by appendGfx_player_actor().
create_status_icon_set()
s32 create_status_icon_set (void)
Referenced by create_actor(), load_partner_actor(), and load_player_actor().
create_status_icon_surprise()
void create_status_icon_surprise (s32 iconID)
create_status_static()
void create_status_static (s32 iconID, s32 statusID)
Referenced by appendGfx_npc_actor(), appendGfx_player_actor(), and inflict_status().
create_status_transparent()
void create_status_transparent (s32 iconID, s32 statusID)
Referenced by appendGfx_npc_actor(), appendGfx_player_actor(), and inflict_status().
dispose_merlee_message()
void dispose_merlee_message (PopupMessage * popup)
Referenced by update_merlee_message().
draw_all_status_icons()
void draw_all_status_icons (void * popup)
Referenced by init_all_status_icons().
draw_merlee_message()
void draw_merlee_message (void * popup)
Referenced by show_merlee_message().
draw_merlee_message_string()
void draw_merlee_message_string (PopupMessage * popup, s32 posX, s32 posY)
Referenced by draw_merlee_message().
draw_merlee_messages()
void draw_merlee_messages (void)
Referenced by draw_encounter_ui().
enable_status_chill_out()
void enable_status_chill_out (s32 iconID)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
enable_status_debuff()
void enable_status_debuff (s32 iconID)
enable_status_icon_boost_hammer()
void enable_status_icon_boost_hammer (s32 iconID)
Referenced by appendGfx_player_actor().
enable_status_icon_boost_jump()
void enable_status_icon_boost_jump (s32 iconID)
Referenced by appendGfx_player_actor().
enable_status_icon_boost_partner()
void enable_status_icon_boost_partner (s32 iconID)
enable_status_icon_danger()
void enable_status_icon_danger (s32 iconID)
enable_status_icon_peril()
void enable_status_icon_peril (s32 iconID)
enable_status_icon_surprise()
void enable_status_icon_surprise (s32 iconID)
enable_status_static()
void enable_status_static (s32 iconID)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
enable_status_transparent()
void enable_status_transparent (s32 iconID)
func_80045AC0()
void func_80045AC0 (void)
Referenced by clear_encounter_status(), and init_encounter_status().
func_80045B10()
void func_80045B10 (void)
func_80045BC8()
void func_80045BC8 (void)
Referenced by func_80045AC0().
get_current_merlee_message()
PopupMessage * get_current_merlee_message (void)
Referenced by init_all_status_icons(), and show_merlee_message().
init_all_status_icons()
void init_all_status_icons (void)
Referenced by func_80045AC0().
is_merlee_message_done()
s32 is_merlee_message_done (void)
remove_all_status_icons()
void remove_all_status_icons (s32 iconID)
Referenced by btl_delete_actor(), and btl_delete_player_actor().
remove_status_chill_out()
void remove_status_chill_out (s32 iconID)
Referenced by btl_state_update_begin_player_turn(), and remove_all_status_icons().
remove_status_debuff()
void remove_status_debuff (s32 iconID)
Referenced by btl_state_update_9(), btl_state_update_begin_player_turn(), btl_state_update_defeat(), create_status_debuff(), and remove_all_status_icons().
remove_status_icon_boost_hammer()
void remove_status_icon_boost_hammer (s32 iconID)
Referenced by appendGfx_player_actor(), and remove_all_status_icons().
remove_status_icon_boost_jump()
void remove_status_icon_boost_jump (s32 iconID)
Referenced by appendGfx_player_actor(), and remove_all_status_icons().
remove_status_icon_boost_partner()
void remove_status_icon_boost_partner (s32 iconID)
Referenced by remove_all_status_icons().
remove_status_icon_danger()
void remove_status_icon_danger (s32 iconID)
Referenced by appendGfx_player_actor(), and remove_all_status_icons().
remove_status_icon_peril()
void remove_status_icon_peril (s32 iconID)
Referenced by appendGfx_player_actor(), and remove_all_status_icons().
remove_status_icon_surprise()
void remove_status_icon_surprise (s32 iconID)
Referenced by remove_all_status_icons().
remove_status_static()
void remove_status_static (s32 iconID)
Referenced by btl_state_update_9(), btl_state_update_begin_player_turn(), calc_item_damage_enemy(), create_status_static(), remove_all_status_icons(), and remove_player_buffs().
remove_status_transparent()
void remove_status_transparent (s32 iconID)
Referenced by btl_state_update_9(), btl_state_update_begin_player_turn(), calc_item_damage_enemy(), create_status_transparent(), remove_all_status_icons(), and remove_player_buffs().
set_status_icons_offset()
void set_status_icons_offset (s32 iconID, s32 offsetY, s32 offsetX)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
set_status_icons_properties()
void set_status_icons_properties (s32 iconID, f32 x, f32 y, f32 z, s32 arg, s32 arg2, s32 radius, s32 offsetY)
Referenced by appendGfx_npc_actor(), and appendGfx_player_actor().
show_merlee_message()
void show_merlee_message (s16 messageIndex, s16 duration)
update_all_status_icons()
void update_all_status_icons (void * popup)
Referenced by init_all_status_icons().
update_merlee_message()
void update_merlee_message (void * popup)
Referenced by show_merlee_message().
update_merlee_messages()
void update_merlee_messages (void)
Referenced by update_encounters().
Variable Documentation
D_80078160
s16 D_80078160[] = { 28, 40 }
Referenced by draw_merlee_message().
D_80078164
s16 D_80078164[] = { 0, -2 }
Referenced by draw_merlee_message_string().
D_80078168
s32 D_80078168[]
Initial value:
= {
    MSG_Menus_Merlee_IncreaseCoins,
    MSG_Menus_Merlee_Exhausted,
}
Referenced by draw_merlee_message(), and draw_merlee_message_string().
D_800A0BC0
BSS PopupMessage D_800A0BC0[32]
Referenced by draw_merlee_messages(), func_80045AC0(), func_80045B10(), func_80045BC8(), get_current_merlee_message(), and update_merlee_messages().
D_800A0F40
BSS s32 D_800A0F40
Referenced by is_merlee_message_done(), show_merlee_message(), and update_merlee_message().
D_800A0F44
BSS HudStatusIcon* D_800A0F44
Referenced by create_status_chill_out(), create_status_debuff(), create_status_icon_boost_hammer(), create_status_icon_boost_jump(), create_status_icon_boost_partner(), create_status_icon_danger(), create_status_icon_peril(), create_status_icon_set(), create_status_icon_surprise(), create_status_static(), create_status_transparent(), draw_all_status_icons(), enable_status_chill_out(), enable_status_debuff(), enable_status_icon_boost_hammer(), enable_status_icon_boost_jump(), enable_status_icon_boost_partner(), enable_status_icon_danger(), enable_status_icon_peril(), enable_status_icon_surprise(), enable_status_static(), enable_status_transparent(), init_all_status_icons(), remove_all_status_icons(), remove_status_chill_out(), remove_status_debuff(), remove_status_icon_boost_hammer(), remove_status_icon_boost_jump(), remove_status_icon_boost_partner(), remove_status_icon_danger(), remove_status_icon_peril(), remove_status_icon_surprise(), remove_status_static(), remove_status_transparent(), set_status_icons_offset(), set_status_icons_properties(), and update_all_status_icons().
HES_AsleepBegin
HudScript HES_AsleepBegin extern
Referenced by update_all_status_icons().
HES_AsleepEnd
HudScript HES_AsleepEnd extern
Referenced by update_all_status_icons().
HES_BoostHammerBegin
HudScript HES_BoostHammerBegin extern
Referenced by create_status_icon_boost_hammer().
HES_BoostHammerEnd
HudScript HES_BoostHammerEnd extern
Referenced by remove_status_icon_boost_hammer().
HES_BoostJumpBegin
HudScript HES_BoostJumpBegin extern
Referenced by create_status_icon_boost_jump().
HES_BoostJumpEnd
HudScript HES_BoostJumpEnd extern
Referenced by remove_status_icon_boost_jump().
HES_BoostPartner
HudScript HES_BoostPartner extern
Referenced by create_status_icon_boost_partner().
HES_Danger
HudScript HES_Danger extern
Referenced by create_status_icon_danger().
HES_DizzyBegin
HudScript HES_DizzyBegin extern
Referenced by update_all_status_icons().
HES_DizzyEnd
HudScript HES_DizzyEnd extern
Referenced by update_all_status_icons().
HES_ElectrifiedBegin
HudScript HES_ElectrifiedBegin extern
Referenced by update_all_status_icons().
HES_ElectrifiedEnd
HudScript HES_ElectrifiedEnd extern
Referenced by update_all_status_icons().
HES_FrozenBegin
HudScript HES_FrozenBegin extern
Referenced by update_all_status_icons().
HES_FrozenEnd
HudScript HES_FrozenEnd extern
Referenced by update_all_status_icons().
HES_Item_Present
HudScript HES_Item_Present extern
Referenced by update_all_status_icons().
HES_ParalyzedBegin
HudScript HES_ParalyzedBegin extern
Referenced by update_all_status_icons().
HES_ParalyzedEnd
HudScript HES_ParalyzedEnd extern
Referenced by update_all_status_icons().
HES_Peril
HudScript HES_Peril extern
Referenced by create_status_icon_peril().
HES_PoisonedBegin
HudScript HES_PoisonedBegin extern
Referenced by update_all_status_icons().
HES_PoisonedEnd
HudScript HES_PoisonedEnd extern
Referenced by update_all_status_icons().
HES_ShrunkBegin
HudScript HES_ShrunkBegin extern
Referenced by update_all_status_icons().
HES_ShrunkEnd
HudScript HES_ShrunkEnd extern
Referenced by update_all_status_icons().
HES_StoppedBegin
HudScript HES_StoppedBegin extern
Referenced by update_all_status_icons().
HES_StoppedEnd
HudScript HES_StoppedEnd extern
Referenced by update_all_status_icons().
HES_Surprise
HudScript HES_Surprise extern
Referenced by create_status_icon_surprise().
HES_TransparentBegin
HudScript HES_TransparentBegin extern
Referenced by update_all_status_icons().
HES_TransparentEnd
HudScript HES_TransparentEnd extern
Referenced by update_all_status_icons().
HES_WeakenedBegin
HudScript HES_WeakenedBegin extern
Referenced by update_all_status_icons().
HES_WeakenedEnd
HudScript HES_WeakenedEnd extern
Referenced by update_all_status_icons().
HES_WeakenedLoop
HudScript HES_WeakenedLoop extern
Referenced by update_all_status_icons().
status_icons_rodata_alignment
const f32 status_icons_rodata_alignment = 0.0f