papermario: src/effects/steam_burst.c File Reference
steam_burst.c File Reference
Functions
void steam_burst_init (EffectInstance *effect)
void steam_burst_update (EffectInstance *effect)
void steam_burst_render (EffectInstance *effect)
void steam_burst_appendGfx (void *effect)
void steam_burst_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Variables
Gfx D_09000E00_362470 []
Gfx D_09000F30_3625A0 []
Gfx * D_E005C700 [] = { D_09000F30_3625A0 }
Gfx * D_E005C704 [] = { D_09000E00_362470 }
Function Documentation
steam_burst_appendGfx()
void steam_burst_appendGfx (void * effect)
Referenced by steam_burst_render().
steam_burst_init()
void steam_burst_init (EffectInstance * effect)
Referenced by steam_burst_main().
steam_burst_main()
void steam_burst_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
steam_burst_render()
void steam_burst_render (EffectInstance * effect)
Referenced by steam_burst_main().
steam_burst_update()
void steam_burst_update (EffectInstance * effect)
Referenced by steam_burst_main().
Variable Documentation
D_09000E00_362470
Gfx D_09000E00_362470[] extern
D_09000F30_3625A0
Gfx D_09000F30_3625A0[] extern
D_E005C700
Gfx* D_E005C700[] = { D_09000F30_3625A0 }
Referenced by steam_burst_appendGfx().
D_E005C704
Gfx* D_E005C704[] = { D_09000E00_362470 }
Referenced by steam_burst_appendGfx().