papermario: GameMode Struct Reference
GameMode Struct Reference
#include <game_modes.h>
Public Member Functions
UNK_FUN_PTR (unusedFunc)
Data Fields
u16 flags
void(* init)(void)
void(* step)(void)
void(* render)(void)
void(* renderAux)(void)
Member Function Documentation
UNK_FUN_PTR()
GameMode::UNK_FUN_PTR (unusedFunc)
Field Documentation
flags
u16 GameMode::flags
Referenced by clear_game_mode_unk_flags(), clear_game_modes(), set_game_mode_flag_10(), set_game_mode_flag_4(), set_game_mode_flag_8(), and step_current_game_mode().
init
void(* GameMode::init) (void)
Referenced by set_game_mode_slot(), and set_next_game_mode().
render
void(* GameMode::render) (void)
Referenced by set_game_mode_slot(), set_next_game_mode(), state_render_backUI(), and state_render_frontUI().
renderAux
void(* GameMode::renderAux) (void)
See also
state_render_frontUI
Referenced by state_render_frontUI().
step
void(* GameMode::step) (void)
Referenced by set_game_mode_slot(), and set_next_game_mode().
The documentation for this struct was generated from the following file:
src/game_modes.h