papermario: EffectBlueprint Struct Reference
EffectBlueprint Struct Reference
#include <effects.h>
Data Fields
s32 unk_00
s32 effectID
void(* init)(EffectInstance *effectInst)
void(* update)(EffectInstance *effectInst)
void(* renderScene)(EffectInstance *effectInst)
void(* renderUI)(EffectInstance *effectInst)
Field Documentation
effectID
s32 EffectBlueprint::effectID
Referenced by attack_result_text_main(), aura_main(), balloon_main(), big_smoke_puff_main(), big_snowflakes_main(), blast_main(), bombette_breaking_main(), breaking_junk_main(), bulb_glow_main(), butterflies_main(), chapter_change_main(), chomp_drop_main(), cloud_puff_main(), cloud_trail_main(), cold_breath_main(), confetti_main(), create_effect_instance(), damage_indicator_main(), damage_stars_main(), debuff_main(), disable_x_main(), drop_leaves_main(), dust_main(), effect_3D_main(), effect_46_main(), effect_63_main(), effect_65_main(), effect_75_main(), effect_86_main(), embers_main(), emote_main(), ending_decals_main(), energy_in_out_main(), energy_orb_wave_main(), energy_shockwave_main(), explosion_main(), falling_leaves_main(), fire_breath_main(), fire_flower_main(), firework_main(), firework_rocket_main(), flame_main(), flashing_box_shockwave_main(), floating_cloud_puff_main(), floating_flower_main(), floating_rock_main(), flower_splash_main(), flower_trail_main(), footprint_main(), fright_jar_main(), gather_energy_pink_main(), gather_magic_main(), got_item_outline_main(), green_impact_main(), hieroglyphs_main(), huff_puff_breath_main(), ice_pillar_main(), ice_shard_main(), landing_dust_main(), lens_flare_main(), light_rays_main(), lightning_bolt_main(), lightning_main(), lil_oink_main(), merlin_house_stars_main(), misc_particles_main(), motion_blur_flame_main(), moving_cloud_main(), music_note_main(), partner_buff_main(), peach_star_beam_main(), pink_sparkles_main(), purple_ring_main(), quizmo_answer_main(), quizmo_assistant_main(), quizmo_audience_main(), quizmo_stage_main(), radial_shimmer_main(), radiating_energy_orb_main(), recover_main(), red_impact_main(), ring_blast_main(), rising_bubble_main(), shape_spell_main(), shattering_stones_main(), shimmer_burst_main(), shimmer_wave_main(), shiny_flare_main(), shockwave_main(), sleep_bubble_main(), small_gold_sparkle_main(), smoke_burst_main(), smoke_impact_main(), smoke_ring_main(), snaking_static_main(), snowfall_main(), snowflake_main(), snowman_doll_main(), something_rotating_main(), sparkles_main(), spiky_white_aura_main(), spirit_card_main(), squirt_main(), star_main(), star_outline_main(), star_spirits_energy_main(), stars_burst_main(), stars_orbiting_main(), stars_shimmer_main(), stars_spread_main(), stat_change_main(), static_status_main(), steam_burst_main(), stop_watch_main(), sun_main(), sweat_main(), tattle_window_main(), throw_spiny_main(), thunderbolt_ring_main(), tubba_heart_attack_main(), underwater_main(), walking_dust_main(), water_block_main(), water_fountain_main(), water_splash_main(), waterfall_main(), whirlwind_main(), and windy_leaves_main().
init
void(* EffectBlueprint::init) (EffectInstance *effectInst)
Referenced by attack_result_text_main(), aura_main(), balloon_main(), big_smoke_puff_main(), big_snowflakes_main(), blast_main(), bombette_breaking_main(), breaking_junk_main(), bulb_glow_main(), butterflies_main(), chapter_change_main(), chomp_drop_main(), cloud_puff_main(), cloud_trail_main(), cold_breath_main(), confetti_main(), create_effect_instance(), damage_indicator_main(), damage_stars_main(), debuff_main(), disable_x_main(), drop_leaves_main(), dust_main(), effect_3D_main(), effect_46_main(), effect_63_main(), effect_65_main(), effect_75_main(), effect_86_main(), embers_main(), emote_main(), ending_decals_main(), energy_in_out_main(), energy_orb_wave_main(), energy_shockwave_main(), explosion_main(), falling_leaves_main(), fire_breath_main(), fire_flower_main(), firework_main(), firework_rocket_main(), flame_main(), flashing_box_shockwave_main(), floating_cloud_puff_main(), floating_flower_main(), floating_rock_main(), flower_splash_main(), flower_trail_main(), footprint_main(), fright_jar_main(), gather_energy_pink_main(), gather_magic_main(), got_item_outline_main(), green_impact_main(), hieroglyphs_main(), huff_puff_breath_main(), ice_pillar_main(), ice_shard_main(), landing_dust_main(), lens_flare_main(), light_rays_main(), lightning_bolt_main(), lightning_main(), lil_oink_main(), merlin_house_stars_main(), misc_particles_main(), motion_blur_flame_main(), moving_cloud_main(), music_note_main(), partner_buff_main(), peach_star_beam_main(), pink_sparkles_main(), purple_ring_main(), quizmo_answer_main(), quizmo_assistant_main(), quizmo_audience_main(), quizmo_stage_main(), radial_shimmer_main(), radiating_energy_orb_main(), recover_main(), red_impact_main(), ring_blast_main(), rising_bubble_main(), shape_spell_main(), shattering_stones_main(), shimmer_burst_main(), shimmer_wave_main(), shiny_flare_main(), shockwave_main(), sleep_bubble_main(), small_gold_sparkle_main(), smoke_burst_main(), smoke_impact_main(), smoke_ring_main(), snaking_static_main(), snowfall_main(), snowflake_main(), snowman_doll_main(), something_rotating_main(), sparkles_main(), spiky_white_aura_main(), spirit_card_main(), squirt_main(), star_main(), star_outline_main(), star_spirits_energy_main(), stars_burst_main(), stars_orbiting_main(), stars_shimmer_main(), stars_spread_main(), stat_change_main(), static_status_main(), steam_burst_main(), stop_watch_main(), sun_main(), sweat_main(), tattle_window_main(), throw_spiny_main(), thunderbolt_ring_main(), tubba_heart_attack_main(), underwater_main(), walking_dust_main(), water_block_main(), water_fountain_main(), water_splash_main(), waterfall_main(), whirlwind_main(), and windy_leaves_main().
renderScene
void(* EffectBlueprint::renderScene) (EffectInstance *effectInst)
Referenced by attack_result_text_main(), aura_main(), balloon_main(), big_smoke_puff_main(), big_snowflakes_main(), blast_main(), bombette_breaking_main(), breaking_junk_main(), bulb_glow_main(), butterflies_main(), chapter_change_main(), chomp_drop_main(), cloud_puff_main(), cloud_trail_main(), cold_breath_main(), confetti_main(), create_effect_instance(), damage_indicator_main(), damage_stars_main(), debuff_main(), disable_x_main(), drop_leaves_main(), dust_main(), effect_3D_main(), effect_46_main(), effect_63_main(), effect_65_main(), effect_75_main(), effect_86_main(), embers_main(), emote_main(), ending_decals_main(), energy_in_out_main(), energy_orb_wave_main(), energy_shockwave_main(), explosion_main(), falling_leaves_main(), fire_breath_main(), fire_flower_main(), firework_main(), firework_rocket_main(), flame_main(), flashing_box_shockwave_main(), floating_cloud_puff_main(), floating_flower_main(), floating_rock_main(), flower_splash_main(), flower_trail_main(), footprint_main(), fright_jar_main(), gather_energy_pink_main(), gather_magic_main(), got_item_outline_main(), green_impact_main(), hieroglyphs_main(), huff_puff_breath_main(), ice_pillar_main(), ice_shard_main(), landing_dust_main(), lens_flare_main(), light_rays_main(), lightning_bolt_main(), lightning_main(), lil_oink_main(), merlin_house_stars_main(), misc_particles_main(), motion_blur_flame_main(), moving_cloud_main(), music_note_main(), partner_buff_main(), peach_star_beam_main(), pink_sparkles_main(), purple_ring_main(), quizmo_answer_main(), quizmo_assistant_main(), quizmo_audience_main(), quizmo_stage_main(), radial_shimmer_main(), radiating_energy_orb_main(), recover_main(), red_impact_main(), ring_blast_main(), rising_bubble_main(), shape_spell_main(), shattering_stones_main(), shimmer_burst_main(), shimmer_wave_main(), shiny_flare_main(), shockwave_main(), sleep_bubble_main(), small_gold_sparkle_main(), smoke_burst_main(), smoke_impact_main(), smoke_ring_main(), snaking_static_main(), snowfall_main(), snowflake_main(), snowman_doll_main(), something_rotating_main(), sparkles_main(), spiky_white_aura_main(), spirit_card_main(), squirt_main(), star_main(), star_outline_main(), star_spirits_energy_main(), stars_burst_main(), stars_orbiting_main(), stars_shimmer_main(), stars_spread_main(), stat_change_main(), static_status_main(), steam_burst_main(), stop_watch_main(), sun_main(), sweat_main(), tattle_window_main(), throw_spiny_main(), thunderbolt_ring_main(), tubba_heart_attack_main(), underwater_main(), walking_dust_main(), water_block_main(), water_fountain_main(), water_splash_main(), waterfall_main(), whirlwind_main(), and windy_leaves_main().
renderUI
void(* EffectBlueprint::renderUI) (EffectInstance *effectInst)
Referenced by attack_result_text_main(), aura_main(), balloon_main(), big_smoke_puff_main(), big_snowflakes_main(), blast_main(), bombette_breaking_main(), breaking_junk_main(), bulb_glow_main(), butterflies_main(), chapter_change_main(), chomp_drop_main(), cloud_puff_main(), cloud_trail_main(), cold_breath_main(), confetti_main(), create_effect_instance(), damage_indicator_main(), damage_stars_main(), debuff_main(), disable_x_main(), drop_leaves_main(), dust_main(), effect_3D_main(), effect_46_main(), effect_63_main(), effect_65_main(), effect_75_main(), effect_86_main(), embers_main(), emote_main(), ending_decals_main(), energy_in_out_main(), energy_orb_wave_main(), energy_shockwave_main(), explosion_main(), falling_leaves_main(), fire_breath_main(), fire_flower_main(), firework_main(), firework_rocket_main(), flame_main(), flashing_box_shockwave_main(), floating_cloud_puff_main(), floating_flower_main(), floating_rock_main(), flower_splash_main(), flower_trail_main(), footprint_main(), fright_jar_main(), gather_energy_pink_main(), gather_magic_main(), got_item_outline_main(), green_impact_main(), hieroglyphs_main(), huff_puff_breath_main(), ice_pillar_main(), ice_shard_main(), landing_dust_main(), lens_flare_main(), light_rays_main(), lightning_bolt_main(), lightning_main(), lil_oink_main(), merlin_house_stars_main(), misc_particles_main(), motion_blur_flame_main(), moving_cloud_main(), music_note_main(), partner_buff_main(), peach_star_beam_main(), pink_sparkles_main(), purple_ring_main(), quizmo_answer_main(), quizmo_assistant_main(), quizmo_audience_main(), quizmo_stage_main(), radial_shimmer_main(), radiating_energy_orb_main(), recover_main(), red_impact_main(), ring_blast_main(), rising_bubble_main(), shape_spell_main(), shattering_stones_main(), shimmer_burst_main(), shimmer_wave_main(), shiny_flare_main(), shockwave_main(), sleep_bubble_main(), small_gold_sparkle_main(), smoke_burst_main(), smoke_impact_main(), smoke_ring_main(), snaking_static_main(), snowfall_main(), snowflake_main(), snowman_doll_main(), something_rotating_main(), sparkles_main(), spiky_white_aura_main(), spirit_card_main(), squirt_main(), star_main(), star_outline_main(), star_spirits_energy_main(), stars_burst_main(), stars_orbiting_main(), stars_shimmer_main(), stars_spread_main(), stat_change_main(), static_status_main(), steam_burst_main(), stop_watch_main(), sun_main(), sweat_main(), tattle_window_main(), throw_spiny_main(), thunderbolt_ring_main(), tubba_heart_attack_main(), underwater_main(), walking_dust_main(), water_block_main(), water_fountain_main(), water_splash_main(), waterfall_main(), whirlwind_main(), and windy_leaves_main().
unk_00
s32 EffectBlueprint::unk_00
Referenced by attack_result_text_main(), aura_main(), balloon_main(), big_smoke_puff_main(), big_snowflakes_main(), blast_main(), bombette_breaking_main(), breaking_junk_main(), bulb_glow_main(), butterflies_main(), chapter_change_main(), chomp_drop_main(), cloud_puff_main(), cloud_trail_main(), cold_breath_main(), confetti_main(), damage_indicator_main(), damage_stars_main(), debuff_main(), disable_x_main(), drop_leaves_main(), dust_main(), effect_3D_main(), effect_46_main(), effect_63_main(), effect_65_main(), effect_75_main(), effect_86_main(), embers_main(), emote_main(), ending_decals_main(), energy_in_out_main(), energy_orb_wave_main(), energy_shockwave_main(), explosion_main(), falling_leaves_main(), fire_breath_main(), fire_flower_main(), firework_main(), firework_rocket_main(), flame_main(), flashing_box_shockwave_main(), floating_cloud_puff_main(), floating_flower_main(), floating_rock_main(), flower_splash_main(), flower_trail_main(), footprint_main(), fright_jar_main(), gather_energy_pink_main(), gather_magic_main(), got_item_outline_main(), green_impact_main(), hieroglyphs_main(), huff_puff_breath_main(), ice_pillar_main(), ice_shard_main(), landing_dust_main(), lens_flare_main(), light_rays_main(), lightning_bolt_main(), lightning_main(), lil_oink_main(), merlin_house_stars_main(), misc_particles_main(), motion_blur_flame_main(), moving_cloud_main(), music_note_main(), partner_buff_main(), peach_star_beam_main(), pink_sparkles_main(), purple_ring_main(), quizmo_answer_main(), quizmo_assistant_main(), quizmo_audience_main(), quizmo_stage_main(), radial_shimmer_main(), radiating_energy_orb_main(), recover_main(), red_impact_main(), ring_blast_main(), rising_bubble_main(), shape_spell_main(), shattering_stones_main(), shimmer_burst_main(), shimmer_wave_main(), shiny_flare_main(), shockwave_main(), sleep_bubble_main(), small_gold_sparkle_main(), smoke_burst_main(), smoke_impact_main(), smoke_ring_main(), snaking_static_main(), snowfall_main(), snowflake_main(), snowman_doll_main(), something_rotating_main(), sparkles_main(), spiky_white_aura_main(), spirit_card_main(), squirt_main(), star_main(), star_outline_main(), star_spirits_energy_main(), stars_burst_main(), stars_orbiting_main(), stars_shimmer_main(), stars_spread_main(), stat_change_main(), static_status_main(), steam_burst_main(), stop_watch_main(), sun_main(), sweat_main(), tattle_window_main(), throw_spiny_main(), thunderbolt_ring_main(), tubba_heart_attack_main(), underwater_main(), walking_dust_main(), water_block_main(), water_fountain_main(), water_splash_main(), waterfall_main(), whirlwind_main(), and windy_leaves_main().
update
void(* EffectBlueprint::update) (EffectInstance *effectInst)
Referenced by attack_result_text_main(), aura_main(), balloon_main(), big_smoke_puff_main(), big_snowflakes_main(), blast_main(), bombette_breaking_main(), breaking_junk_main(), bulb_glow_main(), butterflies_main(), chapter_change_main(), chomp_drop_main(), cloud_puff_main(), cloud_trail_main(), cold_breath_main(), confetti_main(), create_effect_instance(), damage_indicator_main(), damage_stars_main(), debuff_main(), disable_x_main(), drop_leaves_main(), dust_main(), effect_3D_main(), effect_46_main(), effect_63_main(), effect_65_main(), effect_75_main(), effect_86_main(), embers_main(), emote_main(), ending_decals_main(), energy_in_out_main(), energy_orb_wave_main(), energy_shockwave_main(), explosion_main(), falling_leaves_main(), fire_breath_main(), fire_flower_main(), firework_main(), firework_rocket_main(), flame_main(), flashing_box_shockwave_main(), floating_cloud_puff_main(), floating_flower_main(), floating_rock_main(), flower_splash_main(), flower_trail_main(), footprint_main(), fright_jar_main(), gather_energy_pink_main(), gather_magic_main(), got_item_outline_main(), green_impact_main(), hieroglyphs_main(), huff_puff_breath_main(), ice_pillar_main(), ice_shard_main(), landing_dust_main(), lens_flare_main(), light_rays_main(), lightning_bolt_main(), lightning_main(), lil_oink_main(), merlin_house_stars_main(), misc_particles_main(), motion_blur_flame_main(), moving_cloud_main(), music_note_main(), partner_buff_main(), peach_star_beam_main(), pink_sparkles_main(), purple_ring_main(), quizmo_answer_main(), quizmo_assistant_main(), quizmo_audience_main(), quizmo_stage_main(), radial_shimmer_main(), radiating_energy_orb_main(), recover_main(), red_impact_main(), ring_blast_main(), rising_bubble_main(), shape_spell_main(), shattering_stones_main(), shimmer_burst_main(), shimmer_wave_main(), shiny_flare_main(), shockwave_main(), sleep_bubble_main(), small_gold_sparkle_main(), smoke_burst_main(), smoke_impact_main(), smoke_ring_main(), snaking_static_main(), snowfall_main(), snowflake_main(), snowman_doll_main(), something_rotating_main(), sparkles_main(), spiky_white_aura_main(), spirit_card_main(), squirt_main(), star_main(), star_outline_main(), star_spirits_energy_main(), stars_burst_main(), stars_orbiting_main(), stars_shimmer_main(), stars_spread_main(), stat_change_main(), static_status_main(), steam_burst_main(), stop_watch_main(), sun_main(), sweat_main(), tattle_window_main(), throw_spiny_main(), thunderbolt_ring_main(), tubba_heart_attack_main(), underwater_main(), walking_dust_main(), water_block_main(), water_fountain_main(), water_splash_main(), waterfall_main(), whirlwind_main(), and windy_leaves_main().
The documentation for this struct was generated from the following file:
include/effects.h