papermario: NpcBlueprint Struct Reference
NpcBlueprint Struct Reference
#include <npc.h>
Data Fields
s32 flags
s32 initialAnim
void(* onUpdate)(struct Npc *)
void(* onRender)(struct Npc *)
Field Documentation
flags
s32 NpcBlueprint::flags
Referenced by create_npc_impl(), create_partner_npc(), and peach_make_disguise_npc().
initialAnim
s32 NpcBlueprint::initialAnim
Referenced by create_npc_impl(), create_partner_npc(), and peach_make_disguise_npc().
onRender
void(* NpcBlueprint::onRender) (struct Npc *)
Referenced by create_npc_impl(), create_partner_npc(), and peach_make_disguise_npc().
onUpdate
void(* NpcBlueprint::onUpdate) (struct Npc *)
Referenced by create_npc_impl(), create_partner_npc(), and peach_make_disguise_npc().
The documentation for this struct was generated from the following file:
include/npc.h