papermario: src/effects/sun.c File Reference
sun.c File Reference
Functions
void sun_init (EffectInstance *effect)
void sun_update (EffectInstance *effect)
void sun_render (EffectInstance *effect)
void sun_appendGfx (void *effect)
EffectInstance * sun_main (s32 shineFromRight, f32 offsetX, f32 offsetY, f32 offsetZ, f32 arg4, s32 duration)
Variables
Gfx D_09000898_40C438 []
Gfx D_09000980_40C520 []
Gfx D_09000998_40C538 []
Gfx D_090009B0_40C550 []
Gfx D_090009C8_40C568 []
Gfx D_090009E0_40C580 []
Gfx * D_E0120780 []
Gfx * D_E0120794 [] = { D_09000898_40C438 }
Function Documentation
sun_appendGfx()
void sun_appendGfx (void * effect)
Referenced by sun_render().
sun_init()
void sun_init (EffectInstance * effect)
Referenced by sun_main().
sun_main()
EffectInstance * sun_main (s32 shineFromRight, f32 offsetX, f32 offsetY, f32 offsetZ, f32 arg4, s32 duration)
sun_render()
void sun_render (EffectInstance * effect)
Referenced by sun_main().
sun_update()
void sun_update (EffectInstance * effect)
Referenced by sun_main().
Variable Documentation
D_09000898_40C438
Gfx D_09000898_40C438[] extern
D_09000980_40C520
Gfx D_09000980_40C520[] extern
D_09000998_40C538
Gfx D_09000998_40C538[] extern
D_090009B0_40C550
Gfx D_090009B0_40C550[] extern
D_090009C8_40C568
Gfx D_090009C8_40C568[] extern
D_090009E0_40C580
Gfx D_090009E0_40C580[] extern
D_E0120780
Gfx* D_E0120780[]
Initial value:
= {
    D_09000980_40C520, D_09000998_40C538, D_090009B0_40C550,
    D_090009C8_40C568, D_090009E0_40C580
}
Referenced by sun_appendGfx().
D_E0120794
Gfx* D_E0120794[] = { D_09000898_40C438 }
Referenced by sun_appendGfx().