papermario: src/entity/SuperBlock.c File Reference
SuperBlock.c File Reference
Functions
f32 entity_SuperBlockContent_get_previous_yaw (SuperBlockContentData *data, s32 lagTime)
void entity_upgrade_block_hide_content (s32 entityIndex)
s32 entity_upgrade_block_idle (Entity *entity)
void entity_upgrade_block_check_if_inactive (Entity *entity)
void entity_upgrade_block_init (Entity *entity)
void entity_SuperBlock_init (Entity *entity)
void entity_UltraBlock_init (Entity *entity)
void entity_SuperBlockContent_attach_to_parent (Entity *entity)
void entity_SuperBlockContent_setupGfx (s32 entityIndex)
void entity_SuperBlockContent_idle (Entity *entity)
void entity_init_SuperBlockContent (Entity *entity)
void entity_init_UltraBlockContent (Entity *entity)
Variables
EntityBlueprint Entity_SuperBlockContent
Gfx Entity_SuperBlock_Render []
Gfx Entity_UltraBlock_Render []
Gfx Entity_SuperBlockContent_Render []
Gfx Entity_SuperBlockContent_Render2 []
Gfx Entity_UltraBlockContent_Render []
Gfx Entity_UltraBlockContent_Render2 []
unsigned char D_0A000200_E4A8A0 []
unsigned char D_0A000220_E4A8C0 []
unsigned char D_0A000240_E4A8E0 []
unsigned char D_0A000260_E4A900 []
EntityScript Entity_SuperBlock_Script
unsigned char * Entity_SuperBlock_Palettes []
s8 Entity_SuperBlock_PalData []
Gfx Entity_RenderNone []
EntityScript Entity_SuperBlockContent_Script
EntityScript Entity_UltraBlockContent_Script
EntityModelScript Entity_SuperBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_SuperBlock_Render, RENDER_MODE_ALPHATEST)
EntityModelScript Entity_SuperBlockContent_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_XLU_LAYER2)
EntityModelScript Entity_UltraBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_UltraBlock_Render, RENDER_MODE_ALPHATEST)
EntityModelScript Entity_UltraBlockContent_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_XLU_LAYER2)
EntityBlueprint Entity_SuperBlock
EntityBlueprint Entity_UltraBlock
EntityBlueprint Entity_UltraBlockContent
Function Documentation
entity_init_SuperBlockContent()
void entity_init_SuperBlockContent (Entity * entity)
entity_init_UltraBlockContent()
void entity_init_UltraBlockContent (Entity * entity)
entity_SuperBlock_init()
void entity_SuperBlock_init (Entity * entity)
entity_SuperBlockContent_attach_to_parent()
void entity_SuperBlockContent_attach_to_parent (Entity * entity)
Referenced by entity_SuperBlockContent_idle().
entity_SuperBlockContent_get_previous_yaw()
f32 entity_SuperBlockContent_get_previous_yaw (SuperBlockContentData * data, s32 lagTime)
Referenced by entity_SuperBlockContent_setupGfx().
entity_SuperBlockContent_idle()
void entity_SuperBlockContent_idle (Entity * entity)
entity_SuperBlockContent_setupGfx()
void entity_SuperBlockContent_setupGfx (s32 entityIndex)
Referenced by entity_init_SuperBlockContent(), and entity_init_UltraBlockContent().
entity_UltraBlock_init()
void entity_UltraBlock_init (Entity * entity)
entity_upgrade_block_check_if_inactive()
void entity_upgrade_block_check_if_inactive (Entity * entity)
entity_upgrade_block_hide_content()
void entity_upgrade_block_hide_content (s32 entityIndex)
entity_upgrade_block_idle()
s32 entity_upgrade_block_idle (Entity * entity)
entity_upgrade_block_init()
void entity_upgrade_block_init (Entity * entity)
Referenced by entity_SuperBlock_init(), and entity_UltraBlock_init().
Variable Documentation
D_0A000200_E4A8A0
unsigned char D_0A000200_E4A8A0[] extern
D_0A000220_E4A8C0
unsigned char D_0A000220_E4A8C0[] extern
D_0A000240_E4A8E0
unsigned char D_0A000240_E4A8E0[] extern
D_0A000260_E4A900
unsigned char D_0A000260_E4A900[] extern
Entity_RenderNone
Gfx Entity_RenderNone[] extern
Entity_SuperBlock
EntityBlueprint Entity_SuperBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_SuperBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_SuperBlock_init,
    .updateEntityScript = Entity_SuperBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(SuperBlock) },
    .entityType = ENTITY_TYPE_SUPER_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Entity_SuperBlock_PalData
s8 Entity_SuperBlock_PalData[]
Initial value:
= {
    20, 0,
    2,  1,
    2,  2,
    20, 3,
    2,  2,
    1,  2,
    -1, -1,
}
Referenced by entity_SuperBlockContent_setupGfx().
Entity_SuperBlock_Palettes
unsigned char* Entity_SuperBlock_Palettes[]
Initial value:
= {
    D_0A000200_E4A8A0,
    D_0A000220_E4A8C0,
    D_0A000240_E4A8E0,
    D_0A000260_E4A900
}
Referenced by entity_SuperBlockContent_setupGfx().
Entity_SuperBlock_Render
Gfx Entity_SuperBlock_Render[] extern
Entity_SuperBlock_RenderScript
EntityModelScript Entity_SuperBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_SuperBlock_Render, RENDER_MODE_ALPHATEST)
Entity_SuperBlock_Script
EntityScript Entity_SuperBlock_Script
Initial value:
= {
    es_Call(entity_upgrade_block_check_if_inactive)
    es_Label(1)
        es_SetCallback(entity_upgrade_block_idle, 0)
        es_PlaySound(SOUND_HIT_BLOCK)
        es_Call(entity_block_hit_init_scale)
        es_SetCallback(entity_block_hit_animate_scale, 6)
        es_Call(entity_start_script)
    es_Goto(1)
    es_End
    es_End
}
Entity_SuperBlockContent
EntityBlueprint Entity_SuperBlockContent
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION,
    .typeDataSize = sizeof(SuperBlockContentData),
    .renderCommandList = Entity_SuperBlockContent_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_SuperBlockContent,
    .updateEntityScript = Entity_SuperBlockContent_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(SuperBlockContent) },
    .entityType = ENTITY_TYPE_SUPER_BLOCK_HIT_EFFECT,
    .aabbSize = { 18, 6, 18 }
}
Referenced by entity_upgrade_block_check_if_inactive().
Entity_SuperBlockContent_Render
Gfx Entity_SuperBlockContent_Render[] extern
Referenced by entity_init_SuperBlockContent().
Entity_SuperBlockContent_Render2
Gfx Entity_SuperBlockContent_Render2[] extern
Referenced by entity_init_SuperBlockContent().
Entity_SuperBlockContent_RenderScript
EntityModelScript Entity_SuperBlockContent_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_XLU_LAYER2)
Entity_SuperBlockContent_Script
EntityScript Entity_SuperBlockContent_Script
Initial value:
= {
    es_SetCallback(entity_SuperBlockContent_idle, 0)
    es_End
}
Entity_UltraBlock
EntityBlueprint Entity_UltraBlock
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(BlockData),
    .renderCommandList = Entity_UltraBlock_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_UltraBlock_init,
    .updateEntityScript = Entity_SuperBlock_Script,
    .fpHandleCollision = entity_block_handle_collision,
    { .dma = ENTITY_ROM(UltraBlock) },
    .entityType = ENTITY_TYPE_ULTRA_BLOCK,
    .aabbSize = { 25, 25, 25 }
}
Entity_UltraBlock_Render
Gfx Entity_UltraBlock_Render[] extern
Entity_UltraBlock_RenderScript
EntityModelScript Entity_UltraBlock_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_UltraBlock_Render, RENDER_MODE_ALPHATEST)
Entity_UltraBlockContent
EntityBlueprint Entity_UltraBlockContent
Initial value:
= {
    .flags = ENTITY_FLAG_DISABLE_COLLISION,
    .typeDataSize = sizeof(SuperBlockContentData),
    .renderCommandList = Entity_UltraBlockContent_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_init_UltraBlockContent,
    .updateEntityScript = Entity_UltraBlockContent_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(UltraBlockContent) },
    .entityType = ENTITY_TYPE_ULTRA_BLOCK_HIT_EFFECT,
    .aabbSize = { 18, 6, 18 }
}
Entity_UltraBlockContent_Render
Gfx Entity_UltraBlockContent_Render[] extern
Referenced by entity_init_UltraBlockContent().
Entity_UltraBlockContent_Render2
Gfx Entity_UltraBlockContent_Render2[] extern
Referenced by entity_init_UltraBlockContent().
Entity_UltraBlockContent_RenderScript
EntityModelScript Entity_UltraBlockContent_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_XLU_LAYER2)
Entity_UltraBlockContent_Script
EntityScript Entity_UltraBlockContent_Script
Initial value:
= {
    es_SetCallback(entity_SuperBlockContent_idle, 0)
    es_End
}