papermario: src/world/surfaces.c File Reference
surfaces.c File Reference
Functions
void surface_standard_behavior (void)
void surface_flowers_behavior (void)
void surface_cloud_behavior (void)
void surface_snow_behavior (void)
void surface_hedges_behavior (void)
void surface_water_behavior (void)
void func_800EFD00 (void)
void handle_floor_behavior (void)
void func_800F0C9C (void)
Variables
s32 D_80109480 = 0
f32 D_80109484 = 0.0f
s16 D_80109488 = 4
s16 D_8010948A = 0
f32 D_8010948C = 0.0f
s16 D_80109490 = 4
s16 D_80109492 = 5
s32 D_80109494 = 0
f32 D_80109498 = 0.0f
s16 D_8010949C = 4
s16 D_8010949E = 0
f32 D_801094A0 = 0.0f
s16 D_801094A4 = 4
s16 D_801094A6 = 0
s32 D_801094A8 = 0
s16 D_801094AC = 4
s16 D_801094AE = 4
BSS s32 PrevTimeInAir
BSS s32 LandedTimeInAir
Function Documentation
func_800EFD00()
void func_800EFD00 (void)
func_800F0C9C()
void func_800F0C9C (void)
Referenced by render_player_model().
handle_floor_behavior()
void handle_floor_behavior (void)
Referenced by player_jump(), and update_player().
surface_cloud_behavior()
void surface_cloud_behavior (void)
Referenced by handle_floor_behavior().
surface_flowers_behavior()
void surface_flowers_behavior (void)
Referenced by handle_floor_behavior().
surface_hedges_behavior()
void surface_hedges_behavior (void)
Referenced by handle_floor_behavior().
surface_snow_behavior()
void surface_snow_behavior (void)
Referenced by handle_floor_behavior().
surface_standard_behavior()
void surface_standard_behavior (void)
Referenced by handle_floor_behavior().
surface_water_behavior()
void surface_water_behavior (void)
Referenced by handle_floor_behavior().
Variable Documentation
D_80109480
s32 D_80109480 = 0
Referenced by handle_floor_behavior().
D_80109484
f32 D_80109484 = 0.0f
Referenced by surface_standard_behavior().
D_80109488
s16 D_80109488 = 4
Referenced by surface_standard_behavior().
D_8010948A
s16 D_8010948A = 0
D_8010948C
f32 D_8010948C = 0.0f
Referenced by surface_flowers_behavior().
D_80109490
s16 D_80109490 = 4
Referenced by surface_flowers_behavior().
D_80109492
s16 D_80109492 = 5
Referenced by surface_flowers_behavior().
D_80109494
s32 D_80109494 = 0
Referenced by surface_flowers_behavior().
D_80109498
f32 D_80109498 = 0.0f
Referenced by surface_cloud_behavior().
D_8010949C
s16 D_8010949C = 4
Referenced by surface_cloud_behavior().
D_8010949E
s16 D_8010949E = 0
D_801094A0
f32 D_801094A0 = 0.0f
Referenced by surface_cloud_behavior().
D_801094A4
s16 D_801094A4 = 4
Referenced by surface_snow_behavior().
D_801094A6
s16 D_801094A6 = 0
D_801094A8
s32 D_801094A8 = 0
Referenced by surface_snow_behavior().
D_801094AC
s16 D_801094AC = 4
Referenced by surface_hedges_behavior().
D_801094AE
s16 D_801094AE = 4
Referenced by surface_water_behavior().
LandedTimeInAir
BSS s32 LandedTimeInAir
Referenced by handle_floor_behavior(), surface_cloud_behavior(), and surface_standard_behavior().
PrevTimeInAir
BSS s32 PrevTimeInAir
Referenced by handle_floor_behavior().