papermario: src/effects/sweat.c File Reference
sweat.c File Reference
Functions
void sweat_init (EffectInstance *effect)
void sweat_update (EffectInstance *effect)
void sweat_render (EffectInstance *effect)
void sweat_appendGfx (void *effect)
void sweat_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, s32 timeLeft)
Variables
Gfx D_09000200_35C750 []
Gfx D_090002C8_35C818 []
Gfx D_09000390_35C8E0 []
Gfx D_09000460_35C9B0 []
Function Documentation
sweat_appendGfx()
void sweat_appendGfx (void * effect)
Referenced by sweat_render().
sweat_init()
void sweat_init (EffectInstance * effect)
Referenced by sweat_main().
sweat_main()
void sweat_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, s32 timeLeft)
sweat_render()
void sweat_render (EffectInstance * effect)
Referenced by sweat_main().
sweat_update()
void sweat_update (EffectInstance * effect)
Referenced by sweat_main().
Variable Documentation
D_09000200_35C750
Gfx D_09000200_35C750[] extern
Referenced by sweat_appendGfx().
D_090002C8_35C818
Gfx D_090002C8_35C818[] extern
Referenced by sweat_appendGfx().
D_09000390_35C8E0
Gfx D_09000390_35C8E0[] extern
Referenced by sweat_appendGfx().
D_09000460_35C9B0
Gfx D_09000460_35C9B0[] extern
Referenced by sweat_appendGfx().