papermario: src/entity/Switch.c File Reference
Switch.c File Reference
Macros
#define REFLECTED_SWITCH_HIDDEN 1
#define REFLECTED_SWITCH_LINKED 2
Functions
void entity_GreenStompSwitch_idle (Entity *entity)
void entity_GreenStompSwitch_retract (Entity *entity)
void entity_GreenStompSwitch_extend (Entity *entity)
void entity_switch_fall_down (Entity *entity)
void entity_HugeBlueSwitch_idle (Entity *entity)
void entity_small_switch_idle (Entity *entity)
void entity_RedSwitch_wait_and_reset (Entity *entity)
void entity_base_switch_anim_init (Entity *entity)
s32 entity_RedSwitch_animate_scale (Entity *entity)
void entity_base_switch_start_bound_script (Entity *entity)
void entity_base_switch_animate_scale (Entity *entity)
void entity_base_switch_init (Entity *entity)
void entity_BlueSwitch_init (Entity *entity)
void entity_HugeBlueSwitch_init (Entity *entity)
Variables
Gfx Entity_RedSwitch_Render []
Gfx Entity_BlueSwitch_Render []
Gfx Entity_GreenStompSwitch_Render []
BSS Entity * SwitchToLink
EntityScript Entity_RedSwitch_Script
EntityScript Entity_HugeBlueSwitch_Script
EntityScript Entity_BlueSwitch_Script
EntityScript Entity_GreenStompSwitch_Script
EntityModelScript Entity_BlueSwitch_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_BlueSwitch_Render, RENDER_MODE_SURFACE_XLU_LAYER1)
EntityModelScript Entity_HugeBlueSwitch_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_BlueSwitch_Render, RENDER_MODE_SURFACE_XLU_LAYER1)
EntityModelScript Entity_RedSwitch_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RedSwitch_Render, RENDER_MODE_SURFACE_XLU_LAYER1)
EntityModelScript Entity_GreenStompSwitch_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_GreenStompSwitch_Render, RENDER_MODE_SURFACE_OPA)
EntityBlueprint Entity_RedSwitch
EntityBlueprint Entity_BlueSwitch
EntityBlueprint Entity_HugeBlueSwitch
EntityBlueprint Entity_GreenStompSwitch
Macro Definition Documentation
REFLECTED_SWITCH_HIDDEN
#define REFLECTED_SWITCH_HIDDEN 1
Referenced by entity_BlueSwitch_init().
REFLECTED_SWITCH_LINKED
#define REFLECTED_SWITCH_LINKED 2
Referenced by entity_BlueSwitch_init().
Function Documentation
entity_base_switch_anim_init()
void entity_base_switch_anim_init (Entity * entity)
entity_base_switch_animate_scale()
void entity_base_switch_animate_scale (Entity * entity)
entity_base_switch_init()
void entity_base_switch_init (Entity * entity)
Referenced by entity_BlueSwitch_init(), and entity_HugeBlueSwitch_init().
entity_base_switch_start_bound_script()
void entity_base_switch_start_bound_script (Entity * entity)
entity_BlueSwitch_init()
void entity_BlueSwitch_init (Entity * entity)
entity_GreenStompSwitch_extend()
void entity_GreenStompSwitch_extend (Entity * entity)
entity_GreenStompSwitch_idle()
void entity_GreenStompSwitch_idle (Entity * entity)
entity_GreenStompSwitch_retract()
void entity_GreenStompSwitch_retract (Entity * entity)
entity_HugeBlueSwitch_idle()
void entity_HugeBlueSwitch_idle (Entity * entity)
entity_HugeBlueSwitch_init()
void entity_HugeBlueSwitch_init (Entity * entity)
entity_RedSwitch_animate_scale()
s32 entity_RedSwitch_animate_scale (Entity * entity)
entity_RedSwitch_wait_and_reset()
void entity_RedSwitch_wait_and_reset (Entity * entity)
entity_small_switch_idle()
void entity_small_switch_idle (Entity * entity)
entity_switch_fall_down()
void entity_switch_fall_down (Entity * entity)
Referenced by entity_base_switch_animate_scale(), entity_RedSwitch_animate_scale(), and entity_small_switch_idle().
Variable Documentation
Entity_BlueSwitch
EntityBlueprint Entity_BlueSwitch
Initial value:
= {
    .flags = ENTITY_FLAG_8000 | ENTITY_FLAG_ALWAYS_FACE_CAMERA | ENTITY_FLAG_CIRCULAR_SHADOW | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_HAS_DYNAMIC_SHADOW,
    .typeDataSize = sizeof(SwitchData),
    .renderCommandList = Entity_BlueSwitch_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_BlueSwitch_init,
    .updateEntityScript = Entity_BlueSwitch_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(BlueSwitch) },
    .entityType = ENTITY_TYPE_BLUE_SWITCH,
    .aabbSize = {22, 23, 22}
}
Entity_BlueSwitch_Render
Gfx Entity_BlueSwitch_Render[] extern
Entity_BlueSwitch_RenderScript
EntityModelScript Entity_BlueSwitch_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_BlueSwitch_Render, RENDER_MODE_SURFACE_XLU_LAYER1)
Entity_BlueSwitch_Script
EntityScript Entity_BlueSwitch_Script
Initial value:
= {
    es_SetCallback(entity_small_switch_idle, 0)
    es_PlaySound(SOUND_ACTIVATE_SWITCH)
    es_Call(entity_base_switch_start_bound_script)
    es_Call(entity_base_switch_anim_init)
    es_SetCallback(entity_base_switch_animate_scale, 0)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_GreenStompSwitch
EntityBlueprint Entity_GreenStompSwitch
Initial value:
= {
    .flags = ENTITY_FLAG_8000 | ENTITY_FLAG_4000,
    .typeDataSize = sizeof(SwitchData),
    .renderCommandList = Entity_GreenStompSwitch_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_switch_init,
    .updateEntityScript = Entity_GreenStompSwitch_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(GreenStompSwitch) },
    .entityType = ENTITY_TYPE_GREEN_STOMP_SWITCH,
    .aabbSize = {50, 15, 50}
}
Entity_GreenStompSwitch_Render
Gfx Entity_GreenStompSwitch_Render[] extern
Entity_GreenStompSwitch_RenderScript
EntityModelScript Entity_GreenStompSwitch_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_GreenStompSwitch_Render, RENDER_MODE_SURFACE_OPA)
Entity_GreenStompSwitch_Script
EntityScript Entity_GreenStompSwitch_Script
Initial value:
= {
    es_SetCallback(entity_GreenStompSwitch_idle, 0)
    es_SetCallback(entity_GreenStompSwitch_retract, 0)
    es_PlaySound(SOUND_ACTIVATE_SWITCH)
    es_SetCallback(NULL, 128)
    es_SetCallback(entity_GreenStompSwitch_extend, 0)
    es_Restart
}
Entity_HugeBlueSwitch
EntityBlueprint Entity_HugeBlueSwitch
Initial value:
= {
    .flags = ENTITY_FLAG_8000 | ENTITY_FLAG_ALWAYS_FACE_CAMERA | ENTITY_FLAG_CIRCULAR_SHADOW | ENTITY_FLAG_FIXED_SHADOW_SIZE | ENTITY_FLAG_HAS_DYNAMIC_SHADOW,
    .typeDataSize = sizeof(SwitchData),
    .renderCommandList = Entity_HugeBlueSwitch_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_HugeBlueSwitch_init,
    .updateEntityScript = Entity_HugeBlueSwitch_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(BlueSwitch) },
    .entityType = ENTITY_TYPE_HUGE_BLUE_SWITCH,
    .aabbSize = {66, 75, 66}
}
Entity_HugeBlueSwitch_RenderScript
EntityModelScript Entity_HugeBlueSwitch_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_BlueSwitch_Render, RENDER_MODE_SURFACE_XLU_LAYER1)
Entity_HugeBlueSwitch_Script
EntityScript Entity_HugeBlueSwitch_Script
Initial value:
= {
    es_SetCallback(entity_HugeBlueSwitch_idle, 0)
    es_PlaySound(SOUND_ACTIVATE_SWITCH)
    es_Call(entity_base_switch_start_bound_script)
    es_Call(entity_base_switch_anim_init)
    es_SetCallback(entity_base_switch_animate_scale, 0)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}
Entity_RedSwitch
EntityBlueprint Entity_RedSwitch
Initial value:
= {
    .flags = ENTITY_FLAG_8000 | ENTITY_FLAG_ALWAYS_FACE_CAMERA,
    .typeDataSize = sizeof(SwitchData),
    .renderCommandList = Entity_RedSwitch_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_base_switch_init,
    .updateEntityScript = Entity_RedSwitch_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(RedSwitch) },
    .entityType = ENTITY_TYPE_RED_SWITCH,
    .aabbSize = {22, 23, 22}
}
Entity_RedSwitch_Render
Gfx Entity_RedSwitch_Render[] extern
Entity_RedSwitch_RenderScript
EntityModelScript Entity_RedSwitch_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RedSwitch_Render, RENDER_MODE_SURFACE_XLU_LAYER1)
Entity_RedSwitch_Script
EntityScript Entity_RedSwitch_Script
Initial value:
= {
    es_SetCallback(entity_small_switch_idle, 0)
    es_PlaySound(SOUND_ACTIVATE_SWITCH)
    es_Call(entity_base_switch_start_bound_script)
    es_Call(entity_base_switch_anim_init)
    es_SetCallback(entity_RedSwitch_animate_scale, 0)
    es_SetCallback(entity_RedSwitch_wait_and_reset, 0)
    es_Restart
    es_End
}
SwitchToLink
BSS Entity* SwitchToLink
Referenced by entity_BlueSwitch_init().