papermario: src/effects/tattle_window.c File Reference
tattle_window.c File Reference
Data Structures
struct TattleAnimFrame
Functions
void tattle_window_init (EffectInstance *effect)
void tattle_window_update (EffectInstance *effect)
void tattle_window_render (EffectInstance *effect)
void func_E00D8264 (EffectInstance *effect)
void func_E00D8630 (EffectInstance *effect)
EffectInstance * tattle_window_main (s32 type, f32 x, f32 y, f32 z, f32 arg4, s32 duration)
void func_E00D8280 (void)
void tattle_window_fill_clipped_quad (s32 l, s32 t, s32 r, s32 b)
void func_E00D8334 (TattleWindowFXData *data, s32 left, s32 top, s32 right, s32 bottom)
Variables
u8 D_09000000_3D7040 []
WindowStyleCustom TattleWindowStyle
TattleAnimFrame TattleWindowAnimation []
Data Structure Documentation
TattleAnimFrame
struct TattleAnimFrame
Data Fields
u8 closeAmtX
u8 closeAmtY
s16 offsetY
Function Documentation
func_E00D8264()
void func_E00D8264 (EffectInstance * effect)
Referenced by tattle_window_main().
func_E00D8280()
void func_E00D8280 (void)
func_E00D8334()
void func_E00D8334 (TattleWindowFXData * data, s32 left, s32 top, s32 right, s32 bottom)
Referenced by func_E00D8630().
func_E00D8630()
void func_E00D8630 (EffectInstance * effect)
Referenced by func_E00D8264().
tattle_window_fill_clipped_quad()
void tattle_window_fill_clipped_quad (s32 l, s32 t, s32 r, s32 b)
Referenced by func_E00D8334().
tattle_window_init()
void tattle_window_init (EffectInstance * effect)
Referenced by tattle_window_main().
tattle_window_main()
EffectInstance * tattle_window_main (s32 type, f32 x, f32 y, f32 z, f32 arg4, s32 duration)
tattle_window_render()
void tattle_window_render (EffectInstance * effect)
Referenced by tattle_window_main().
tattle_window_update()
void tattle_window_update (EffectInstance * effect)
Referenced by tattle_window_main().
Variable Documentation
D_09000000_3D7040
u8 D_09000000_3D7040[] extern
TattleWindowAnimation
TattleAnimFrame TattleWindowAnimation[]
Initial value:
= {
    { .offsetY = -200, .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -160, .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -120, .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -85,  .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -55,  .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -30,  .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -16,  .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -8,   .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -4,   .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -2,   .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = -1,   .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = 0,    .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = 0,    .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = 0,    .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = 0,    .closeAmtX = 255, .closeAmtY = 255 },
    { .offsetY = 0,    .closeAmtX = 230, .closeAmtY = 250 },
    { .offsetY = 0,    .closeAmtX = 120, .closeAmtY = 245 },
    { .offsetY = 0,    .closeAmtX = 0,   .closeAmtY = 240 },
    { .offsetY = 0,    .closeAmtX = 0,   .closeAmtY = 210 },
    { .offsetY = 0,    .closeAmtX = 0,   .closeAmtY = 170 },
    { .offsetY = 0,    .closeAmtX = 0,   .closeAmtY = 120 },
    { .offsetY = 0,    .closeAmtX = 0,   .closeAmtY = 60 },
    { .offsetY = 0,    .closeAmtX = 0,   .closeAmtY = 0 },
}
Referenced by tattle_window_update().
TattleWindowStyle
WindowStyleCustom TattleWindowStyle
Initial value:
= {
    .background = { 0 },
    .corners = {
        .imgData = D_09000000_3D7040,
        .fmt = G_IM_FMT_IA,
        .bitDepth = G_IM_SIZ_8b,
        .size1 = { 16, 8 },
        .size2 = { 16, 8 },
        .size3 = { 16, 8 },
        .size4 = { 16, 8 },
    },
    .opaqueCombineMode = gsDPSetCombineMode(PM_CC_15, G_CC_PASS2),
    .transparentCombineMode = gsDPSetCombineMode(PM_CC_14, G_CC_PASS2),
    .color1 = { 61, 74, 188, 255 },
    .color2 = { 0, 25, 28, 255},
}
Referenced by func_E00D8630().