papermario: src/effects/throw_spiny.c File Reference
throw_spiny.c File Reference
Functions
void throw_spiny_appendGfx (void *effect)
void throw_spiny_init (EffectInstance *effect)
void throw_spiny_update (EffectInstance *effect)
void throw_spiny_render (EffectInstance *effect)
EffectInstance * throw_spiny_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, s32 time)
void func_E00C844C (void)
Variables
Gfx D_09000800_3D02F0 []
Gfx D_090008D8_3D03C8 []
Gfx D_090009F0_3D04E0 []
Gfx * D_E00C8710 [2] = { D_09000800_3D02F0, D_090008D8_3D03C8 }
u8 D_E00C8718 [8] = { 110, 150, 130, 110, 100, 95, 100, 0 }
u8 D_E00C8720 [8] = { 80, 60, 80, 100, 120, 110, 100, 0 }
Function Documentation
func_E00C844C()
void func_E00C844C (void)
throw_spiny_appendGfx()
void throw_spiny_appendGfx (void * effect)
Referenced by throw_spiny_render().
throw_spiny_init()
void throw_spiny_init (EffectInstance * effect)
Referenced by throw_spiny_main().
throw_spiny_main()
EffectInstance * throw_spiny_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, s32 time)
throw_spiny_render()
void throw_spiny_render (EffectInstance * effect)
Referenced by throw_spiny_main().
throw_spiny_update()
void throw_spiny_update (EffectInstance * effect)
Referenced by throw_spiny_main().
Variable Documentation
D_09000800_3D02F0
Gfx D_09000800_3D02F0[] extern
D_090008D8_3D03C8
Gfx D_090008D8_3D03C8[] extern
D_090009F0_3D04E0
Gfx D_090009F0_3D04E0[] extern
Referenced by throw_spiny_appendGfx().
D_E00C8710
Gfx* D_E00C8710[2] = { D_09000800_3D02F0, D_090008D8_3D03C8 }
Referenced by throw_spiny_appendGfx().
D_E00C8718
u8 D_E00C8718[8] = { 110, 150, 130, 110, 100, 95, 100, 0 }
Referenced by throw_spiny_update().
D_E00C8720
u8 D_E00C8720[8] = { 80, 60, 80, 100, 120, 110, 100, 0 }
Referenced by throw_spiny_update().