papermario: src/effects/thunderbolt_ring.c File Reference
thunderbolt_ring.c File Reference
Functions
void thunderbolt_ring_init (EffectInstance *effect)
void thunderbolt_ring_update (EffectInstance *effect)
void thunderbolt_ring_render (EffectInstance *effect)
void thunderbolt_ring_appendGfx (void *effect)
EffectInstance * thunderbolt_ring_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 lifeTime)
Variables
Gfx D_09000000_3B46A0 []
Gfx D_090000C8_3B4768 []
Function Documentation
thunderbolt_ring_appendGfx()
void thunderbolt_ring_appendGfx (void * effect)
Referenced by thunderbolt_ring_render().
thunderbolt_ring_init()
void thunderbolt_ring_init (EffectInstance * effect)
Referenced by thunderbolt_ring_main().
thunderbolt_ring_main()
EffectInstance * thunderbolt_ring_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 lifeTime)
thunderbolt_ring_render()
void thunderbolt_ring_render (EffectInstance * effect)
Referenced by thunderbolt_ring_main().
thunderbolt_ring_update()
void thunderbolt_ring_update (EffectInstance * effect)
Referenced by thunderbolt_ring_main().
Variable Documentation
D_09000000_3B46A0
Gfx D_09000000_3B46A0[] extern
Referenced by thunderbolt_ring_appendGfx().
D_090000C8_3B4768
Gfx D_090000C8_3B4768[] extern
Referenced by thunderbolt_ring_appendGfx().