papermario: src/trigger.c File Reference
trigger.c File Reference
Functions
void default_trigger_on_activate (Trigger *self)
void clear_trigger_data (void)
void init_trigger_list (void)
Trigger * create_trigger (TriggerBlueprint *bp)
void update_triggers (void)
void delete_trigger (Trigger *toDelete)
s32 is_another_trigger_bound (Trigger *trigger, EvtScript *script)
Trigger * get_trigger_by_id (s32 triggerID)
s32 should_collider_allow_interact (s32 colliderID)
Variables
s16 gTriggerCount
BSS TriggerList wTriggerList
BSS TriggerList bTriggerList
BSS TriggerList * gCurrentTriggerListPtr
Function Documentation
clear_trigger_data()
void clear_trigger_data (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
create_trigger()
Trigger * create_trigger (TriggerBlueprint * bp)
Referenced by bind_trigger(), evt_handle_bind(), and evt_handle_bind_lock().
default_trigger_on_activate()
void default_trigger_on_activate (Trigger * self)
Referenced by create_trigger().
delete_trigger()
void delete_trigger (Trigger * toDelete)
Referenced by evt_handle_unbind().
get_trigger_by_id()
Trigger * get_trigger_by_id (s32 triggerID)
Referenced by get_trigger_tattle().
init_trigger_list()
void init_trigger_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
is_another_trigger_bound()
s32 is_another_trigger_bound (Trigger * trigger, EvtScript * script)
Referenced by evt_trigger_on_activate_exec_script().
should_collider_allow_interact()
s32 should_collider_allow_interact (s32 colliderID)
Returns
TRUE if colliderID is bound to an interaction trigger (press A) and the player can use it.
Referenced by check_for_interactables(), func_800E06D8(), and should_continue_inspect().
update_triggers()
void update_triggers (void)
Referenced by step_game_loop().
Variable Documentation
bTriggerList
BSS TriggerList bTriggerList
Referenced by clear_trigger_data(), and init_trigger_list().
gCurrentTriggerListPtr
BSS TriggerList* gCurrentTriggerListPtr
Referenced by clear_trigger_data(), create_trigger(), delete_trigger(), get_trigger_by_id(), init_trigger_list(), is_another_trigger_bound(), should_collider_allow_interact(), and update_triggers().
gTriggerCount
s16 gTriggerCount
Referenced by clear_trigger_data(), create_trigger(), and init_trigger_list().
wTriggerList
BSS TriggerList wTriggerList
Referenced by clear_trigger_data(), and init_trigger_list().