papermario: src/effects/underwater.c File Reference
underwater.c File Reference
Functions
void underwater_init (EffectInstance *effect)
void underwater_update (EffectInstance *effect)
void underwater_render (EffectInstance *effect)
void underwater_appendGfx (void *effect)
EffectInstance * underwater_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00BA618 (void)
Variables
Vtx D_09000428_3B9E98 []
Gfx D_09000528_3B9F98 []
Gfx D_09000570_3B9FE0 []
Function Documentation
func_E00BA618()
void func_E00BA618 (void)
underwater_appendGfx()
void underwater_appendGfx (void * effect)
Referenced by underwater_render().
underwater_init()
void underwater_init (EffectInstance * effect)
Referenced by underwater_main().
underwater_main()
EffectInstance * underwater_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
underwater_render()
void underwater_render (EffectInstance * effect)
Referenced by underwater_main().
underwater_update()
void underwater_update (EffectInstance * effect)
Referenced by underwater_main().
Variable Documentation
D_09000428_3B9E98
Vtx D_09000428_3B9E98[] extern
Referenced by underwater_appendGfx().
D_09000528_3B9F98
Gfx D_09000528_3B9F98[] extern
Referenced by underwater_appendGfx().
D_09000570_3B9FE0
Gfx D_09000570_3B9FE0[] extern
Referenced by underwater_appendGfx().