papermario: WindowUpdateFunc Union Reference
WindowUpdateFunc Union Reference
#include <common_structs.h>
Data Fields
int i
void(* func)(s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
Field Documentation
func
void(* WindowUpdateFunc::func) (s32 windowIndex, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
Referenced by filemenu_draw_contents_choose_name(), pause_tabs_update(), and render_windows().
i
int WindowUpdateFunc::i
Referenced by pause_tabs_update(), render_windows(), set_window_properties(), set_window_update(), and setup_pause_menu_tab().
The documentation for this union was generated from the following file:
include/common_structs.h