papermario: src/vars_access.c File Reference
vars_access.c File Reference
Functions
void clear_saved_variables (void)
void clear_area_flags (void)
s32 clear_global_flag (s32 index)
s32 set_global_flag (s32 index)
s32 get_global_flag (s32 index)
s8 set_global_byte (s32 index, s32 value)
s32 get_global_byte (s32 index)
s32 clear_area_flag (s32 index)
s32 set_area_flag (s32 index)
s32 get_area_flag (s32 index)
s8 set_area_byte (s32 index, s32 value)
s32 get_area_byte (s32 index)
Function Documentation
clear_area_flag()
s32 clear_area_flag (s32 index)
Referenced by evt_set_variable().
clear_area_flags()
void clear_area_flags (void)
Referenced by load_map_by_IDs().
clear_global_flag()
s32 clear_global_flag (s32 index)
Referenced by evt_set_variable().
clear_saved_variables()
void clear_saved_variables (void)
Referenced by filemenu_yesno_handle_input(), load_engine_data(), state_init_demo(), state_step_demo(), state_step_intro(), and state_step_startup().
get_area_byte()
s32 get_area_byte (s32 index)
Referenced by evt_get_float_variable(), evt_get_variable(), evt_handle_print_debug_var(), and evt_set_variable().
get_area_flag()
s32 get_area_flag (s32 index)
Referenced by evt_get_variable(), evt_handle_print_debug_var(), evt_set_variable(), and update_triggers().
get_global_byte()
s32 get_global_byte (s32 index)
Referenced by evt_get_float_variable(), evt_get_variable(), evt_handle_print_debug_var(), evt_set_variable(), is_actor_health_bar_visible(), is_actortype_health_bar_visible(), load_tattle_flags(), and save_tattle_flags().
get_global_flag()
s32 get_global_flag (s32 index)
Referenced by entity_BlueWarpPipe_check_if_active(), entity_Chest_check_opened(), entity_HeartBlock_show_tutorial_message(), entity_HiddenPanel_set_ispy_notification(), entity_init_BlueWarpPipe(), entity_ItemBlock_check_if_inactive(), entity_MulticoinBlock_check_if_inactive(), entity_SaveBlock_show_tutorial_message(), entity_upgrade_block_check_if_inactive(), entity_WoodenCrate_shatter(), evt_get_variable(), evt_handle_print_debug_var(), evt_set_variable(), make_item_entity(), spawn_drops(), and update_triggers().
set_area_byte()
s8 set_area_byte (s32 index, s32 value)
Referenced by evt_set_variable().
set_area_flag()
s32 set_area_flag (s32 index)
Referenced by entity_base_switch_start_bound_script(), and evt_set_variable().
set_global_byte()
s8 set_global_byte (s32 index, s32 value)
Referenced by evt_set_variable(), and save_tattle_flags().
set_global_flag()
s32 set_global_flag (s32 index)
Referenced by entity_GiantChest_give_equipment(), entity_HeartBlock_show_tutorial_message(), entity_SaveBlock_show_tutorial_message(), evt_set_variable(), spawn_drops(), update_item_entity_collectable(), and update_item_entity_pickup().