papermario: src/evt/virtual_entity.c File Reference
virtual_entity.c File Reference
Functions
s32 create_worker_backUI (void(*updateFunc)(void), void(*drawFunc)(void))
void virtual_entity_appendGfx_quad (u8 r, u8 g, u8 b, u8 a, u16 left, u16 top, u16 right, u16 bottom)
void virtual_entity_render_quad (s32 r, s32 g, s32 b, s32 a, s32 posX, s32 posY, s32 width, s32 height)
void virtual_entity_move_polar (VirtualEntity *virtualEntity, f32 magnitude, f32 angle)
void virtual_entity_list_update (void)
void virtual_entity_list_render_world (void)
void virtual_entity_list_render_UI (void)
VirtualEntity * virtual_entity_get_by_index (s32 index)
VirtualEntity * virtual_entity_create_at_index (s32 index, EntityModelScript *entityModelData)
s32 virtual_entity_create (EntityModelScript *cmdList)
VirtualEntity * ALT_virtual_entity_create (EntityModelScript *cmdList)
void virtual_entity_set_pos (s32 index, s32 posX, s32 posY, s32 posZ)
void virtual_entity_set_scale (s32 index, f32 scaleX, f32 scaleY, f32 scaleZ)
void virtual_entity_set_rotation (s32 index, f32 angleX, f32 angleY, f32 angleZ)
void virtual_entity_delete_by_index (s32 index)
void virtual_entity_delete_by_ref (VirtualEntity *obj)
void clear_virtual_entity_list (void)
void init_virtual_entity_list (void)
Variables
VirtualEntityList bBattleVirtualEntityList
VirtualEntityList wWorldVirtualEntityList
VirtualEntityList * gCurrentVirtualEntityListPtr
Function Documentation
ALT_virtual_entity_create()
VirtualEntity * ALT_virtual_entity_create (EntityModelScript * cmdList)
clear_virtual_entity_list()
void clear_virtual_entity_list (void)
Referenced by clear_script_list().
create_worker_backUI()
s32 create_worker_backUI (void(*)(void) updateFunc, void(*)(void) drawFunc)
Referenced by clear_virtual_entity_list().
init_virtual_entity_list()
void init_virtual_entity_list (void)
Referenced by init_script_list().
virtual_entity_appendGfx_quad()
void virtual_entity_appendGfx_quad (u8 r, u8 g, u8 b, u8 a, u16 left, u16 top, u16 right, u16 bottom)
Referenced by virtual_entity_render_quad().
virtual_entity_create()
s32 virtual_entity_create (EntityModelScript * cmdList)
virtual_entity_create_at_index()
VirtualEntity * virtual_entity_create_at_index (s32 index, EntityModelScript * entityModelData)
virtual_entity_delete_by_index()
void virtual_entity_delete_by_index (s32 index)
Referenced by virtual_entity_delete_by_ref().
virtual_entity_delete_by_ref()
void virtual_entity_delete_by_ref (VirtualEntity * obj)
virtual_entity_get_by_index()
VirtualEntity * virtual_entity_get_by_index (s32 index)
virtual_entity_list_render_UI()
void virtual_entity_list_render_UI (void)
Referenced by clear_virtual_entity_list().
virtual_entity_list_render_world()
void virtual_entity_list_render_world (void)
Referenced by clear_virtual_entity_list().
virtual_entity_list_update()
void virtual_entity_list_update (void)
Referenced by clear_virtual_entity_list().
virtual_entity_move_polar()
void virtual_entity_move_polar (VirtualEntity * virtualEntity, f32 magnitude, f32 angle)
virtual_entity_render_quad()
void virtual_entity_render_quad (s32 r, s32 g, s32 b, s32 a, s32 posX, s32 posY, s32 width, s32 height)
virtual_entity_set_pos()
void virtual_entity_set_pos (s32 index, s32 posX, s32 posY, s32 posZ)
virtual_entity_set_rotation()
void virtual_entity_set_rotation (s32 index, f32 angleX, f32 angleY, f32 angleZ)
virtual_entity_set_scale()
void virtual_entity_set_scale (s32 index, f32 scaleX, f32 scaleY, f32 scaleZ)
Variable Documentation
bBattleVirtualEntityList
VirtualEntityList bBattleVirtualEntityList extern
Referenced by clear_virtual_entity_list(), and init_virtual_entity_list().
gCurrentVirtualEntityListPtr
VirtualEntityList* gCurrentVirtualEntityListPtr extern
Referenced by ALT_virtual_entity_create(), clear_virtual_entity_list(), init_virtual_entity_list(), virtual_entity_create(), virtual_entity_create_at_index(), virtual_entity_delete_by_ref(), virtual_entity_get_by_index(), virtual_entity_list_render_UI(), virtual_entity_list_render_world(), and virtual_entity_list_update().
wWorldVirtualEntityList
VirtualEntityList wWorldVirtualEntityList extern
Referenced by clear_virtual_entity_list(), and init_virtual_entity_list().