papermario: src/effects/walking_dust.c File Reference
walking_dust.c File Reference
Functions
void walking_dust_init (EffectInstance *effect)
void walking_dust_update (EffectInstance *effect)
void walking_dust_render (EffectInstance *effect)
void walking_dust_appendGfx (void *effect)
void walking_dust_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
Variables
s8 D_E000E660 [16] = { 0, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6, -1, 0 }
s8 D_E000E670 [20] = { 0, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, -1, 0, 0, 0 }
s8 * D_E000E684 [2] = { D_E000E660, D_E000E670 }
Gfx D_09002780_32B620 []
Gfx D_09002868_32B708 []
Gfx D_09002950_32B7F0 []
Gfx D_09002B20_32B9C0 []
Gfx D_09002B40_32B9E0 []
Function Documentation
walking_dust_appendGfx()
void walking_dust_appendGfx (void * effect)
Referenced by walking_dust_render().
walking_dust_init()
void walking_dust_init (EffectInstance * effect)
Referenced by walking_dust_main().
walking_dust_main()
void walking_dust_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5)
walking_dust_render()
void walking_dust_render (EffectInstance * effect)
Referenced by walking_dust_main().
walking_dust_update()
void walking_dust_update (EffectInstance * effect)
Referenced by walking_dust_main().
Variable Documentation
D_09002780_32B620
Gfx D_09002780_32B620[] extern
Referenced by walking_dust_appendGfx().
D_09002868_32B708
Gfx D_09002868_32B708[] extern
Referenced by walking_dust_appendGfx().
D_09002950_32B7F0
Gfx D_09002950_32B7F0[] extern
Referenced by walking_dust_appendGfx().
D_09002B20_32B9C0
Gfx D_09002B20_32B9C0[] extern
Referenced by walking_dust_appendGfx().
D_09002B40_32B9E0
Gfx D_09002B40_32B9E0[] extern
Referenced by walking_dust_appendGfx().
D_E000E660
s8 D_E000E660[16] = { 0, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 6, -1, 0 }
D_E000E670
s8 D_E000E670[20] = { 0, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7, -1, 0, 0, 0 }
D_E000E684
s8* D_E000E684[2] = { D_E000E660, D_E000E670 }
Referenced by walking_dust_update().