papermario: src/effects/waterfall.c File Reference
waterfall.c File Reference
Functions
void waterfall_init (EffectInstance *effect)
void waterfall_update (EffectInstance *effect)
void waterfall_render (EffectInstance *effect)
void waterfall_appendGfx (void *effect)
EffectInstance * waterfall_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00B62D8 (void)
Variables
Gfx D_09000200_3B7AD0 []
Function Documentation
func_E00B62D8()
void func_E00B62D8 (void)
waterfall_appendGfx()
void waterfall_appendGfx (void * effect)
Referenced by waterfall_render().
waterfall_init()
void waterfall_init (EffectInstance * effect)
Referenced by waterfall_main().
waterfall_main()
EffectInstance * waterfall_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
waterfall_render()
void waterfall_render (EffectInstance * effect)
Referenced by waterfall_main().
waterfall_update()
void waterfall_update (EffectInstance * effect)
Referenced by waterfall_main().
Variable Documentation
D_09000200_3B7AD0
Gfx D_09000200_3B7AD0[] extern
Referenced by waterfall_appendGfx().