papermario: src/battle/action_cmd/water_block.h File Reference
water_block.h File Reference
Functions
void action_command_water_block_update (void)
void action_command_water_block_draw (void)
void action_command_water_block_free (void)
Function Documentation
action_command_water_block_draw()
void action_command_water_block_draw (void)
Referenced by action_command_draw().
action_command_water_block_free()
void action_command_water_block_free (void)
Referenced by action_command_free().
action_command_water_block_update()
void action_command_water_block_update (void)
Referenced by action_command_update().