papermario: src/effects/water_fountain.c File Reference
water_fountain.c File Reference
Data Structures
struct UnkStruct
Functions
void water_fountain_init (EffectInstance *effect)
void water_fountain_update (EffectInstance *effect)
void water_fountain_render (EffectInstance *effect)
void water_fountain_appendGfx (void *effect)
EffectInstance * water_fountain_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 arg5)
void func_E00B8200 (void)
Variables
Gfx D_09000280_3B8AE0 []
Gfx D_09000328_3B8B88 []
Gfx D_09000348_3B8BA8 []
UnkStruct D_E00B8900 []
UnkStruct D_E00B8B58 []
s32 D_E00B8CA4 [] = { 0, 40, 55, 190, 20, 130, 270, 300 }
Data Structure Documentation
UnkStruct
struct UnkStruct
Data Fields
Gfx * displayList
s16 height
u8 sizeScale
s32 unk_00
u8 unk_00
s8 unk_00
u8 unk_01
s8 unk_01
u8 unk_02
s16 unk_02
u8 unk_03
s32 unk_04
Gfx * unk_04
s16 unk_04
s16 unk_06
f32 unk_08
Gfx * unk_08
s32 unk_08
char unk_09[1]
f32 unk_0C
s32 unk_10
s32 unk_14
s16 width
s16 x
s16 y
Function Documentation
func_E00B8200()
void func_E00B8200 (void)
water_fountain_appendGfx()
void water_fountain_appendGfx (void * effect)
Referenced by water_fountain_render().
water_fountain_init()
void water_fountain_init (EffectInstance * effect)
Referenced by water_fountain_main().
water_fountain_main()
EffectInstance * water_fountain_main (s32 arg0, f32 posX, f32 posY, f32 posZ, f32 arg4, s32 arg5)
water_fountain_render()
void water_fountain_render (EffectInstance * effect)
Referenced by water_fountain_main().
water_fountain_update()
void water_fountain_update (EffectInstance * effect)
Referenced by water_fountain_main().
Variable Documentation
D_09000280_3B8AE0
Gfx D_09000280_3B8AE0[] extern
Referenced by water_fountain_appendGfx().
D_09000328_3B8B88
Gfx D_09000328_3B8B88[] extern
Referenced by water_fountain_appendGfx().
D_09000348_3B8BA8
Gfx D_09000348_3B8BA8[] extern
Referenced by water_fountain_appendGfx().
D_E00B8900
UnkStruct D_E00B8900[]
Referenced by water_fountain_appendGfx().
D_E00B8B58
UnkStruct D_E00B8B58[]
Referenced by water_fountain_appendGfx().
D_E00B8CA4
s32 D_E00B8CA4[] = { 0, 40, 55, 190, 20, 130, 270, 300 }
Referenced by water_fountain_appendGfx().