papermario: src/effects/water_block.c File Reference
water_block.c File Reference
Data Structures
struct WaterBlockVtxData
Functions
void water_block_init (EffectInstance *effect)
void water_block_update (EffectInstance *effect)
void water_block_render (EffectInstance *effect)
void water_block_appendGfx (void *effect)
EffectInstance * water_block_main (s32 type, f32 x, f32 y, f32 z, f32 arg4, s32 duration)
EFFECT_DEF_WATER_SPLASH (water_splash_main)
void func_E00B4574 (void)
Variables
WaterBlockVtxData D_E00B4CF0 []
Gfx D_09000300_3B6EF0 []
Gfx D_090003B0_3B6FA0 []
Gfx D_090004A0_3B7090 []
Gfx D_090004D8_3B70C8 []
Gfx D_09000538_3B7128 []
Data Structure Documentation
WaterBlockVtxData
struct WaterBlockVtxData
Data Fields
Color_RGB8 color
s16 normX
s16 normY
Vec3b pos
Function Documentation
EFFECT_DEF_WATER_SPLASH()
EFFECT_DEF_WATER_SPLASH (water_splash_main)
func_E00B4574()
void func_E00B4574 (void)
water_block_appendGfx()
void water_block_appendGfx (void * effect)
Referenced by water_block_render().
water_block_init()
void water_block_init (EffectInstance * effect)
Referenced by water_block_main().
water_block_main()
EffectInstance * water_block_main (s32 type, f32 x, f32 y, f32 z, f32 arg4, s32 duration)
water_block_render()
void water_block_render (EffectInstance * effect)
Referenced by water_block_main().
water_block_update()
void water_block_update (EffectInstance * effect)
Referenced by water_block_main().
Variable Documentation
D_09000300_3B6EF0
Gfx D_09000300_3B6EF0[] extern
Referenced by water_block_appendGfx().
D_090003B0_3B6FA0
Gfx D_090003B0_3B6FA0[] extern
Referenced by water_block_appendGfx().
D_090004A0_3B7090
Gfx D_090004A0_3B7090[] extern
Referenced by water_block_appendGfx().
D_090004D8_3B70C8
Gfx D_090004D8_3B70C8[] extern
Referenced by water_block_appendGfx().
D_09000538_3B7128
Gfx D_09000538_3B7128[] extern
Referenced by water_block_appendGfx().
D_E00B4CF0
WaterBlockVtxData D_E00B4CF0[]
Referenced by water_block_appendGfx().