papermario: src/effects/water_splash.c File Reference
water_splash.c File Reference
Functions
void water_splash_init (EffectInstance *effect)
void water_splash_render (EffectInstance *effect)
void water_splash_update (EffectInstance *effect)
void water_splash_appendGfx (void *effect)
EffectInstance * water_splash_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
void func_E00BE5B4 (void)
Variables
Gfx D_09000100_3BCB90 []
Gfx D_09000268_3BCCF8 []
Gfx D_09000288_3BCD18 []
Gfx D_090002A8_3BCD38 []
Gfx * D_E00BEAF0 []
Function Documentation
func_E00BE5B4()
void func_E00BE5B4 (void)
water_splash_appendGfx()
void water_splash_appendGfx (void * effect)
Referenced by water_splash_render().
water_splash_init()
void water_splash_init (EffectInstance * effect)
Referenced by water_splash_main().
water_splash_main()
EffectInstance * water_splash_main (s32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, s32 arg5)
Referenced by water_block_update().
water_splash_render()
void water_splash_render (EffectInstance * effect)
Referenced by water_splash_main().
water_splash_update()
void water_splash_update (EffectInstance * effect)
Referenced by water_splash_main().
Variable Documentation
D_09000100_3BCB90
Gfx D_09000100_3BCB90[] extern
Referenced by water_splash_appendGfx().
D_09000268_3BCCF8
Gfx D_09000268_3BCCF8[] extern
D_09000288_3BCD18
Gfx D_09000288_3BCD18[] extern
D_090002A8_3BCD38
Gfx D_090002A8_3BCD38[] extern
D_E00BEAF0
Gfx* D_E00BEAF0[]
Initial value:
= {
    D_09000268_3BCCF8, D_09000288_3BCD18, D_09000268_3BCCF8, D_090002A8_3BCD38
}
Referenced by water_splash_appendGfx().