papermario: src/world/common/atomic/WhaleAnim.inc.c File Reference
WhaleAnim.inc.c File Reference
Functions
Npc * resolve_npc (Evt *script, s32 npcIdOrPtr)
void unkVtxFunc001 (Vtx *firstVertex, Vtx *copiedVertices, s32 numVertices, s32 *wagPhasePtr)
void unkAngleFunc002 (void)
void unkAngleFunc003 (void)
Function Documentation
resolve_npc()
Npc * resolve_npc (Evt * script, s32 npcIdOrPtr)
Referenced by _show_message(), ApproachPlayer100Units(), func_80045838(), GetAngleBetweenNPCs(), GetAngleToNPC(), GetAngleToPlayer(), ShowEmote(), ShowSleepBubble(), and ShowSweat().
unkAngleFunc002()
void unkAngleFunc002 (void)
unkAngleFunc003()
void unkAngleFunc003 (void)
unkVtxFunc001()
void unkVtxFunc001 (Vtx * firstVertex, Vtx * copiedVertices, s32 numVertices, s32 * wagPhasePtr)
Referenced by unkAngleFunc002(), and unkAngleFunc003().