papermario: src/windows.c File Reference
windows.c File Reference
Data Structures
struct SimpleWindowUpdateData
struct WindowGroup
Enumerations
enum SimpleWindowUpdateFlags { SIMPLE_WINDOW_UPDATE_1 = 0x1 , SIMPLE_WINDOW_UPDATE_OPACITY = 0x2 , SIMPLE_WINDOW_UPDATE_DARKENING = 0x4 }
Functions
void clear_windows (void)
void update_windows (void)
void basic_window_update (s32 windowID, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void basic_hidden_window_update (s32 windowID, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void main_menu_window_update (s32 windowID, s32 *flags, s32 *posX, s32 *posY, s32 *posZ, f32 *scaleX, f32 *scaleY, f32 *rotX, f32 *rotY, f32 *rotZ, s32 *darkening, s32 *opacity)
void render_windows (s32 *windowsArray, s32 parent, s32 flags, s32 baseX, s32 baseY, s32 opacity, s32 darkening, f32(*rotScaleMtx)[4])
void render_window_root (void)
void set_window_properties (s32 windowID, s32 posX, s32 posY, s32 width, s32 height, u8 priority, void *fpDrawContents, void *drawContentsArg0, s8 parent)
void update_window_hierarchy (s32 windowID, u8 priority)
void replace_window_update (s32 windowID, s8 priority, WindowUpdateFunc pendingFunc)
void set_window_update (s32 windowID, s32 func)
void set_windows_visible (s32 groupIdx)
void setup_pause_menu_tab (MenuWindowBP *bp, s32 count)
Variables
Window gWindows [64]
WindowStyle gWindowStyles [64]
SimpleWindowUpdateData gSimpleWindowUpdates []
u8 gWindowAppearScales [] = { 50, 80, 100, 105, 100 }
u8 gWindowAppearFlags [] = { DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, 0}
u8 gWindowDisappearScales [] = { 105, 100, 77, 57, 40, 27, 16, 8, 3, 0 }
u8 gWindowDisappearFlags []
WindowGroup gWindowGroups []
Data Structure Documentation
SimpleWindowUpdateData
struct SimpleWindowUpdateData
Data Fields
u8 darkening
u8 flags
u8 opacity
u8 windowFlagsSet
u8 windowFlagsUnset
WindowGroup
struct WindowGroup
Data Fields
u8 max
u8 min
Enumeration Type Documentation
SimpleWindowUpdateFlags
enum SimpleWindowUpdateFlags
Enumerator
SIMPLE_WINDOW_UPDATE_1
SIMPLE_WINDOW_UPDATE_OPACITY
SIMPLE_WINDOW_UPDATE_DARKENING
Function Documentation
basic_hidden_window_update()
void basic_hidden_window_update (s32 windowID, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by draw_shop_items(), hide_popup_menu(), update_coin_counter(), update_item_entity_pickup(), and worker_update_ingredient_windows().
basic_window_update()
void basic_window_update (s32 windowID, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by draw_shop_items(), func_800F16CC(), pause_tabs_update(), popup_menu_update(), show_coin_counter(), update_item_entity_pickup(), and worker_update_ingredient_windows().
clear_windows()
void clear_windows (void)
Referenced by load_engine_data(), state_step_startup(), and state_step_title_screen().
main_menu_window_update()
void main_menu_window_update (s32 windowID, s32 * flags, s32 * posX, s32 * posY, s32 * posZ, f32 * scaleX, f32 * scaleY, f32 * rotX, f32 * rotY, f32 * rotZ, s32 * darkening, s32 * opacity)
Referenced by filemenu_main_handle_input().
render_window_root()
void render_window_root (void)
Referenced by gfx_draw_frame().
render_windows()
void render_windows (s32 * windowsArray, s32 parent, s32 flags, s32 baseX, s32 baseY, s32 opacity, s32 darkening, f32(*) rotScaleMtx[4])
Referenced by render_window_root(), and render_windows().
replace_window_update()
void replace_window_update (s32 windowID, s8 priority, WindowUpdateFunc pendingFunc)
Referenced by pause_tabs_handle_input().
set_window_properties()
void set_window_properties (s32 windowID, s32 posX, s32 posY, s32 width, s32 height, u8 priority, void * fpDrawContents, void * drawContentsArg0, s8 parent)
Referenced by btl_show_message_popup(), btl_state_update_celebration(), btl_submenu_moves_update(), btl_update_strats_menu(), draw_merlee_message(), func_801363A0(), popup_menu_update(), setup_pause_menu_tab(), and show_coin_counter().
set_window_update()
void set_window_update (s32 windowID, s32 func)
Referenced by btl_show_message_popup(), btl_state_update_celebration(), btl_state_update_partner_menu(), btl_state_update_player_menu(), btl_submenu_moves_update(), btl_update_message_popup(), btl_update_strats_menu(), draw_merlee_message(), draw_shop_items(), filemenu_choose_name_handle_input(), filemenu_cleanup(), filemenu_info_handle_input(), filemenu_main_handle_input(), filemenu_main_init(), filemenu_selectlanguage_handle_input(), filemenu_update_change_layout(), filemenu_yesno_handle_input(), func_800F16CC(), func_802A27E4(), func_802A2910(), func_802A2AB8(), func_802A2C58(), func_802A472C(), func_802A47E0(), func_802A48FC(), func_802A4A10(), hide_popup_menu(), pause_cleanup(), pause_init(), pause_partners_handle_input(), pause_partners_init(), pause_tabs_update(), popup_menu_update(), setup_pause_menu_tab(), show_coin_counter(), update_coin_counter(), update_item_entity_pickup(), update_merlee_message(), and worker_update_ingredient_windows().
set_windows_visible()
void set_windows_visible (s32 groupIdx)
Referenced by btl_state_update_end_battle(), btl_state_update_end_demo_battle(), initialize_battle(), state_init_pause(), state_step_exit_file_select(), state_step_exit_language_select(), state_step_file_select(), state_step_language_select(), and state_step_unpause().
setup_pause_menu_tab()
void setup_pause_menu_tab (MenuWindowBP * bp, s32 count)
Referenced by filemenu_choose_name_init(), filemenu_info_init(), filemenu_init(), filemenu_main_init(), filemenu_selectlanguage_init(), filemenu_yesno_init(), pause_badges_init(), pause_init(), pause_items_init(), pause_map_init(), pause_partners_init(), pause_spirits_init(), pause_stats_init(), and pause_tabs_init().
update_window_hierarchy()
void update_window_hierarchy (s32 windowID, u8 priority)
Referenced by filemenu_init(), pause_init(), pause_update_tab_active(), pause_update_tab_inactive(), render_windows(), and set_window_properties().
update_windows()
void update_windows (void)
Referenced by step_game_loop().
Variable Documentation
gSimpleWindowUpdates
SimpleWindowUpdateData gSimpleWindowUpdates[]
Referenced by render_windows().
gWindowAppearFlags
u8 gWindowAppearFlags[] = { DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, 0}
Referenced by basic_window_update().
gWindowAppearScales
u8 gWindowAppearScales[] = { 50, 80, 100, 105, 100 }
Referenced by basic_window_update().
gWindowDisappearFlags
u8 gWindowDisappearFlags[]
Initial value:
= { DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE,
                               DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE,
                               DRAW_FLAG_ROTSCALE, DRAW_FLAG_ROTSCALE, 0 }
Referenced by basic_hidden_window_update().
gWindowDisappearScales
u8 gWindowDisappearScales[] = { 105, 100, 77, 57, 40, 27, 16, 8, 3, 0 }
Referenced by basic_hidden_window_update().
gWindowGroups
WindowGroup gWindowGroups[]
Initial value:
= {
    { WIN_UNUSED_0, WIN_FILES_SLOT4_TITLE },
    { WIN_BTL_DESC_BOX, WIN_BTL_POPUP },
    { WIN_PAUSE_MAIN, WIN_PAUSE_TAB_INVIS },
    { WIN_FILES_MAIN, WIN_FILES_SLOT4_TITLE }
}
Referenced by set_windows_visible().
gWindows
Window gWindows[64]
Referenced by basic_hidden_window_update(), basic_window_update(), btl_update_message_popup(), clear_windows(), filemenu_choose_name_handle_input(), filemenu_choose_name_init(), filemenu_cleanup(), filemenu_draw_contents_choose_name(), filemenu_main_handle_input(), filemenu_main_init(), filemenu_selectlanguage_init(), filemenu_set_cursor_goal_pos(), filemenu_update(), filemenu_update_change_layout(), filemenu_update_cursor(), filemenu_update_deselect_file(), filemenu_update_hidden_name_confirm(), filemenu_update_hidden_name_input(), filemenu_update_hidden_options_bottom(), filemenu_update_hidden_options_left(), filemenu_update_hidden_options_right(), filemenu_update_hidden_title(), filemenu_update_hidden_with_rotation(), filemenu_update_select_file(), filemenu_update_show_name_confirm(), filemenu_update_show_name_input(), filemenu_update_show_options_bottom(), filemenu_update_show_options_left(), filemenu_update_show_options_right(), filemenu_update_show_title(), filemenu_update_show_with_rotation(), filemenu_yesno_handle_input(), func_80242FBC(), func_802430E4(), func_8024313C(), func_8024330C(), func_802435C4(), main_menu_window_update(), pause_init(), pause_partners_handle_input(), pause_partners_init(), pause_set_cursor_pos(), pause_set_cursor_pos_immediate(), pause_tabs_handle_input(), pause_tabs_init(), pause_tabs_update(), pause_update_page_active_1(), pause_update_page_active_2(), pause_update_page_inactive_1(), pause_update_page_inactive_2(), pause_update_tab_active(), pause_update_tab_default(), pause_update_tab_inactive(), render_window_root(), render_windows(), replace_window_update(), set_window_properties(), set_window_update(), set_windows_visible(), setup_pause_menu_tab(), state_step_exit_file_select(), state_step_exit_language_select(), update_item_entity_pickup(), update_window_hierarchy(), and update_windows().
gWindowStyles
WindowStyle gWindowStyles[64]
Initial value:
= {
    { WINDOW_STYLE_3 }, { WINDOW_STYLE_3 }, { WINDOW_STYLE_11 }, { WINDOW_STYLE_12 },
    { WINDOW_STYLE_13 }, { WINDOW_STYLE_14 }, { WINDOW_STYLE_3 }, { WINDOW_STYLE_21 },
    { WINDOW_STYLE_3 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_9 }, { WINDOW_STYLE_3 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_1 }, { WINDOW_STYLE_3 }, { WINDOW_STYLE_9 },
    { WINDOW_STYLE_10 }, { WINDOW_STYLE_7 }, { WINDOW_STYLE_8 }, { WINDOW_STYLE_3 },
    { WINDOW_STYLE_3 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_3 }, { WINDOW_STYLE_11 }, { WINDOW_STYLE_12 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 },
    { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_0 }, { WINDOW_STYLE_1 }
}
Referenced by filemenu_main_update(), filemenu_selectlanguage_update(), render_windows(), and setup_pause_menu_tab().