papermario: src/effects/windy_leaves.c File Reference
windy_leaves.c File Reference
Functions
void windy_leaves_init (EffectInstance *effect)
void windy_leaves_update (EffectInstance *effect)
void windy_leaves_render (EffectInstance *effect)
void windy_leaves_appendGfx (void *effect)
void windy_leaves_main (s32 type, f32 arg1, f32 arg2, f32 arg3)
Variables
Gfx D_09001180_33E790 []
Gfx D_09001258_33E868 []
Gfx D_09001280_33E890 []
Function Documentation
windy_leaves_appendGfx()
void windy_leaves_appendGfx (void * effect)
Referenced by windy_leaves_render().
windy_leaves_init()
void windy_leaves_init (EffectInstance * effect)
Referenced by windy_leaves_main().
windy_leaves_main()
void windy_leaves_main (s32 type, f32 arg1, f32 arg2, f32 arg3)
windy_leaves_render()
void windy_leaves_render (EffectInstance * effect)
Referenced by windy_leaves_main().
windy_leaves_update()
void windy_leaves_update (EffectInstance * effect)
Referenced by windy_leaves_main().
Variable Documentation
D_09001180_33E790
Gfx D_09001180_33E790[] extern
Referenced by windy_leaves_appendGfx().
D_09001258_33E868
Gfx D_09001258_33E868[] extern
Referenced by windy_leaves_appendGfx().
D_09001280_33E890
Gfx D_09001280_33E890[] extern
Referenced by windy_leaves_appendGfx().