papermario: src/entity/WoodenCrate.c File Reference
WoodenCrate.c File Reference
Functions
void entity_WoodenCrate_setupGfx (s32)
void entity_WoodenCrate_init_fragments (Entity *entity, Gfx **dlists, Mtx *matrices)
void entity_WoodenCrate_init (Entity *entity)
void entity_WoodenCrate_reset_fragments (Entity *entity)
void entity_WoodenCrate_update_fragments (Entity *entity)
s32 entity_WoodenCrate_idle (Entity *entity)
f32 player_get_camera_facing_angle (void)
void entity_WoodenCrate_shatter (Entity *entity, f32 arg1)
Variables
Gfx Entity_RenderNone []
Gfx Entity_WoodenCrate_Render []
Gfx * Entity_WoodenCrate_FragmentsRender []
Mtx Entity_WoodenCrate_FragmentsMatrices []
s32 Entity_WoodenCrate_RenderShatteredScript [] = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_XLU_LAYER1)
EntityModelScript Entity_WoodenCrate_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_WoodenCrate_Render, RENDER_MODE_SURFACE_OPA)
EntityScript Entity_WoodenCrate_Script
EntityBlueprint Entity_WoodenCrate
Function Documentation
entity_WoodenCrate_idle()
s32 entity_WoodenCrate_idle (Entity * entity)
entity_WoodenCrate_init()
void entity_WoodenCrate_init (Entity * entity)
entity_WoodenCrate_init_fragments()
void entity_WoodenCrate_init_fragments (Entity * entity, Gfx ** dlists, Mtx * matrices)
Referenced by entity_WoodenCrate_reset_fragments().
entity_WoodenCrate_reset_fragments()
void entity_WoodenCrate_reset_fragments (Entity * entity)
Referenced by entity_WoodenCrate_idle().
entity_WoodenCrate_setupGfx()
void entity_WoodenCrate_setupGfx (s32 entityIndex)
Referenced by entity_WoodenCrate_init_fragments().
entity_WoodenCrate_shatter()
void entity_WoodenCrate_shatter (Entity * entity, f32 arg1)
entity_WoodenCrate_update_fragments()
void entity_WoodenCrate_update_fragments (Entity * entity)
player_get_camera_facing_angle()
f32 player_get_camera_facing_angle (void)
Referenced by entity_WoodenCrate_shatter().
Variable Documentation
Entity_RenderNone
Gfx Entity_RenderNone[] extern
Entity_WoodenCrate
EntityBlueprint Entity_WoodenCrate
Initial value:
= {
    .flags = ENTITY_FLAG_4000 | ENTITY_FLAG_FIXED_SHADOW_SIZE,
    .typeDataSize = sizeof(WoodenCrateData),
    .renderCommandList = Entity_WoodenCrate_RenderScript,
    .modelAnimationNodes = 0,
    .fpInit = entity_WoodenCrate_init,
    .updateEntityScript = Entity_WoodenCrate_Script,
    .fpHandleCollision = NULL,
    { .dma = ENTITY_ROM(WoodenCrate) },
    .entityType = ENTITY_TYPE_WOODEN_CRATE,
    .aabbSize = { 35, 30, 35 }
}
Entity_WoodenCrate_FragmentsMatrices
Mtx Entity_WoodenCrate_FragmentsMatrices[] extern
Referenced by entity_WoodenCrate_reset_fragments().
Entity_WoodenCrate_FragmentsRender
Gfx* Entity_WoodenCrate_FragmentsRender[] extern
Referenced by entity_WoodenCrate_reset_fragments().
Entity_WoodenCrate_Render
Gfx Entity_WoodenCrate_Render[] extern
Entity_WoodenCrate_RenderScript
EntityModelScript Entity_WoodenCrate_RenderScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_WoodenCrate_Render, RENDER_MODE_SURFACE_OPA)
Entity_WoodenCrate_RenderShatteredScript
EntityModelScript Entity_WoodenCrate_RenderShatteredScript = STANDARD_ENTITY_MODEL_SCRIPT(Entity_RenderNone, RENDER_MODE_SURFACE_XLU_LAYER1)
Referenced by entity_WoodenCrate_idle().
Entity_WoodenCrate_Script
EntityScript Entity_WoodenCrate_Script
Initial value:
= {
    es_SetCallback(entity_WoodenCrate_idle, 0)
    es_SetFlags(ENTITY_FLAG_DISABLE_COLLISION)
    es_Call(entity_WoodenCrate_shatter)
    es_SetCallback(entity_WoodenCrate_update_fragments, 0)
    es_SetFlags(ENTITY_FLAG_HIDDEN)
    es_SetFlags(ENTITY_FLAG_PENDING_INSTANCE_DELETE)
    es_End
}