papermario: src/worker.c File Reference
worker.c File Reference
Functions
void worker_delegate_do_nothing (void)
void clear_worker_list (void)
void init_worker_list (void)
s32 create_worker_scene (void(*updateFunc)(void), void(*renderFunc)(void))
s32 create_worker_frontUI (void(*updateFunc)(void), void(*drawFunc)(void))
s32 create_worker_backUI (void(*updateFunc)(void), void(*drawFunc)(void))
void update_workers (void)
void render_workers_scene (void)
void render_workers_frontUI (void)
void render_workers_backUI (void)
void free_worker (s32 idx)
Worker * get_worker (s32 idx)
Variables
BSS WorkerList gWorldWorkerList
BSS WorkerList gBattleWorkerList
BSS WorkerList * gCurrentWorkerListPtr
Function Documentation
clear_worker_list()
void clear_worker_list (void)
Referenced by load_demo_battle(), load_engine_data(), load_map_by_IDs(), state_init_logos(), state_init_title_screen(), state_step_battle(), state_step_demo(), state_step_intro(), state_step_language_select(), state_step_pause(), and state_step_startup().
create_worker_backUI()
s32 create_worker_backUI (void(*)(void) updateFunc, void(*)(void) drawFunc)
Referenced by clear_virtual_entity_list().
create_worker_frontUI()
s32 create_worker_frontUI (void(*)(void) updateFunc, void(*)(void) drawFunc)
Referenced by clear_item_entity_data(), create_action_command_ui_worker(), create_battle_popup_menu(), create_shop_popup_menu(), create_standard_popup_menu(), init_credits(), and partner_reset_data().
create_worker_scene()
s32 create_worker_scene (void(*)(void) updateFunc, void(*)(void) renderFunc)
Referenced by clear_encounter_status(), clear_item_entity_data(), clear_virtual_entity_list(), func_80045AC0(), init_encounter_status(), initialize_battle(), and reset_model_animators().
free_worker()
void free_worker (s32 idx)
Referenced by popup_menu_update().
get_worker()
Worker * get_worker (s32 idx)
Referenced by partner_reset_data().
init_worker_list()
void init_worker_list (void)
Referenced by state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
render_workers_backUI()
void render_workers_backUI (void)
Referenced by gfx_draw_frame().
render_workers_frontUI()
void render_workers_frontUI (void)
Referenced by gfx_draw_frame().
render_workers_scene()
void render_workers_scene (void)
Referenced by render_frame().
update_workers()
void update_workers (void)
Referenced by step_game_loop().
worker_delegate_do_nothing()
void worker_delegate_do_nothing (void)
Referenced by create_worker_backUI(), create_worker_frontUI(), and create_worker_scene().
Variable Documentation
gBattleWorkerList
BSS WorkerList gBattleWorkerList
Referenced by clear_worker_list(), and init_worker_list().
gCurrentWorkerListPtr
BSS WorkerList* gCurrentWorkerListPtr
Referenced by clear_worker_list(), free_worker(), get_worker(), and init_worker_list().
gWorldWorkerList
BSS WorkerList gWorldWorkerList
Referenced by clear_worker_list(), and init_worker_list().