papermario: src/world/area_mgm/mgm_02/npc.c File Reference
npc.c File Reference
Data Structures
struct SmashGameBoxData
struct SmashGameData
Macros
#define SCOREKEEPER_ENEMY_IDX 0
#define SMASH_DATA_VAR_IDX 0
#define PLAY_COST 10
#define PLAY_TIME ((s32)(900 * DT))
#define FRAME_RATE ((s32)(30 * DT))
#define NUM_BOXES 35
#define NUM_PANELS 10
#define SMASH_DATA_VAR_IDX 0
#define SMASH_DATA_VAR_IDX 0
#define FUZZY_NPC_ID_BASE NPC_Fuzzy_01
#define BOBOMB_NPC_ID_BASE NPC_Bobomb_01
#define LUIGI_NPC_ID_BASE NPC_Luigi_01
#define TEXT_POS_Y 28
#define COUNT_POS_Y 43
Enumerations
enum SmashGameBoxCotent { BOX_CONTENT_FUZZY = 0 , BOX_CONTENT_BOMB = 1 , BOX_CONTENT_PEACH = 2 , BOX_CONTENT_EMPTY = 3 }
enum SmashGameStunFlags { STUN_FLAG_STUNNED = 1 , STUN_FLAG_CHANGED = 2 , STUN_FLAG_GRABBED = 4 }
enum SmashGameBoxState {
BOX_STATE_FUZZY_INIT = 10 , BOX_STATE_FUZZY_IDLE = 11 , BOX_STATE_FUZZY_POPUP = 12 , BOX_STATE_FUZZY_HIT = 13 ,
BOX_STATE_FUZZY_ATTACH = 14 , BOX_STATE_FUZZY_GRAB = 15 , BOX_STATE_FUZZY_DETACH = 16 , BOX_STATE_FUZZY_DONE = 17 ,
BOX_STATE_FUZZY_END = 18 , BOX_STATE_BOMB_INIT = 30 , BOX_STATE_BOMB_IDLE = 31 , BOX_STATE_BOMB_POPUP = 32 ,
BOX_STATE_BOMB_HIT = 33 , BOX_STATE_BOMB_ATTACK = 34 , BOX_STATE_BOMB_STUN = 35 , BOX_STATE_BOMB_DONE = 36 ,
BOX_STATE_BOMB_END = 37 , BOX_STATE_EMPTY_INIT = 50 , BOX_STATE_EMPTY_IDLE = 51 , BOX_STATE_EMPTY_HIT = 52 ,
BOX_STATE_PEACH_INIT = 70 , BOX_STATE_PEACH_IDLE = 71 , BOX_STATE_PEACH_POPUP = 72 , BOX_STATE_PEACH_HIT = 73 ,
BOX_STATE_PEACH_EMERGE = 74 , BOX_STATE_PEACH_DONE = 75
}
Functions
void delete_entity (s32)
void partner_enable_input (void)
void N appendGfx_score_display (void *renderData)
void N worker_draw_score (void)
Variables
HudScript HES_BlueMeter
HudScript HES_AButton
HudScript HES_MashAButton
BSS s32 D_80248600 [10]
Data Structure Documentation
SmashGameBoxData
struct SmashGameBoxData
Data Fields
s32 colliderID
s32 content
s32 modelID
s32 npcID
s32 peachPanelModelID
SmashGameBoxState state
s32 stateTimer
SmashGameData
struct SmashGameData
Data Fields
SmashGameBoxData box[35]
HudElemID buttonHID
s32 curScore
s32 found
s32 mashProgress
HudElemID meterHID
s32 signpostEntity
SmashGameStunFlags stunFlags
s32 timeLeft
s32 windowA_posX
s32 windowB_posX
s32 workerID
Macro Definition Documentation
BOBOMB_NPC_ID_BASE
#define BOBOMB_NPC_ID_BASE NPC_Bobomb_01
COUNT_POS_Y
#define COUNT_POS_Y 43
Referenced by appendGfx_score_display().
FRAME_RATE
#define FRAME_RATE ((s32)(30 * DT))
Referenced by appendGfx_score_display().
FUZZY_NPC_ID_BASE
#define FUZZY_NPC_ID_BASE NPC_Fuzzy_01
LUIGI_NPC_ID_BASE
#define LUIGI_NPC_ID_BASE NPC_Luigi_01
NUM_BOXES
#define NUM_BOXES 35
NUM_PANELS
#define NUM_PANELS 10
Referenced by appendGfx_score_display().
PLAY_COST
#define PLAY_COST 10
PLAY_TIME
#define PLAY_TIME ((s32)(900 * DT))
Referenced by appendGfx_score_display().
SCOREKEEPER_ENEMY_IDX
#define SCOREKEEPER_ENEMY_IDX 0
SMASH_DATA_VAR_IDX [1/3]
#define SMASH_DATA_VAR_IDX 0
Referenced by appendGfx_score_display().
SMASH_DATA_VAR_IDX [2/3]
#define SMASH_DATA_VAR_IDX 0
SMASH_DATA_VAR_IDX [3/3]
#define SMASH_DATA_VAR_IDX 0
TEXT_POS_Y
#define TEXT_POS_Y 28
Referenced by appendGfx_score_display().
Enumeration Type Documentation
SmashGameBoxCotent
enum SmashGameBoxCotent
Enumerator
BOX_CONTENT_FUZZY
BOX_CONTENT_BOMB
BOX_CONTENT_PEACH
BOX_CONTENT_EMPTY
SmashGameBoxState
enum SmashGameBoxState
Enumerator
BOX_STATE_FUZZY_INIT
BOX_STATE_FUZZY_IDLE
BOX_STATE_FUZZY_POPUP
BOX_STATE_FUZZY_HIT
BOX_STATE_FUZZY_ATTACH
BOX_STATE_FUZZY_GRAB
BOX_STATE_FUZZY_DETACH
BOX_STATE_FUZZY_DONE
BOX_STATE_FUZZY_END
BOX_STATE_BOMB_INIT
BOX_STATE_BOMB_IDLE
BOX_STATE_BOMB_POPUP
BOX_STATE_BOMB_HIT
BOX_STATE_BOMB_ATTACK
BOX_STATE_BOMB_STUN
BOX_STATE_BOMB_DONE
BOX_STATE_BOMB_END
BOX_STATE_EMPTY_INIT
BOX_STATE_EMPTY_IDLE
BOX_STATE_EMPTY_HIT
BOX_STATE_PEACH_INIT
BOX_STATE_PEACH_IDLE
BOX_STATE_PEACH_POPUP
BOX_STATE_PEACH_HIT
BOX_STATE_PEACH_EMERGE
BOX_STATE_PEACH_DONE
SmashGameStunFlags
enum SmashGameStunFlags
Enumerator
STUN_FLAG_STUNNED
STUN_FLAG_CHANGED
STUN_FLAG_GRABBED
Function Documentation
appendGfx_score_display()
void N appendGfx_score_display (void * renderData)
delete_entity()
void delete_entity (s32 entityIndex)
Referenced by update_entities().
partner_enable_input()
void partner_enable_input (void)
Referenced by check_input_open_menus(), SentinelAI_GrabPlayer(), update_encounters_conversation(), update_encounters_post_battle(), and update_item_entity_pickup().
worker_draw_score()
void N worker_draw_score (void)
Variable Documentation
D_80248600
BSS s32 D_80248600[10]
HES_AButton
HudScript HES_AButton extern
HES_BlueMeter
HudScript HES_BlueMeter extern
HES_MashAButton
HudScript HES_MashAButton extern