papermario: src/world/world.c File Reference
world.c File Reference
Data Structures
struct AssetHeader
Macros
#define ASSET_TABLE_ROM_START 0x1E40000
#define ASSET_TABLE_HEADER_SIZE 0x20
#define ASSET_TABLE_FIRST_ENTRY (ASSET_TABLE_ROM_START + ASSET_TABLE_HEADER_SIZE)
#define AREA(area, jp_name) { ARRAY_COUNT(area##_maps), area##_maps, "area_" #area, jp_name }
#define MAP(map)
#define MAP_WITH_INIT(map)
Functions
void fio_deserialize_state (void)
void load_map_hit_asset (void)
void load_map_script_lib (void)
void load_map_by_IDs (s16 areaID, s16 mapID, s16 loadType)
MapConfig * get_current_map_config (void)
MapSettings * get_current_map_settings (void)
s32 get_map_IDs_by_name (const char *mapName, s16 *areaID, s16 *mapID)
void * load_asset_by_name (const char *assetName, u32 *decompressedSize)
s32 get_asset_offset (char *assetName, s32 *compressedSize)
Variables
s32 WorldReverbModeMapping [] = { 0, 1, 2, 3 }
Vec3s gEntityColliderFaces []
Vec3f gEntityColliderNormals []
s32 pad_map_table [] = { 0, 0 }
BSS MapConfig * gMapConfig
BSS s32 D_800A41E4
BSS MapSettings gMapSettings
char wMapHitName [0x18]
char wMapShapeName [0x18]
char wMapTexName [0x18]
char wMapBgName [0x14]
ShapeFile gMapShapeData
MapConfig mac_maps []
Toad Town.
MapConfig tik_maps []
Toad Town Tunnels.
MapConfig kgr_maps []
Inside the Whale.
MapConfig kmr_maps []
Goomba Region.
MapConfig iwa_maps []
Mt. Rugged.
MapConfig dro_maps []
Dry Dry Outpost.
MapConfig sbk_maps []
Dry Dry Desert.
MapConfig isk_maps []
Dry Dry Ruins.
MapConfig trd_maps []
Koopa Bros. Fortress.
MapConfig nok_maps []
Koopa Region.
MapConfig hos_maps []
Star Region.
MapConfig kpa_maps []
Bowser's Castle.
MapConfig osr_maps []
Peach's Castle Grounds.
MapConfig kkj_maps []
Peach's Castle.
MapConfig jan_maps []
Jade Jungle.
MapConfig mim_maps []
Forever Forest.
MapConfig obk_maps []
Boo's Mansion.
MapConfig arn_maps []
Gusty Gulch.
MapConfig dgb_maps []
Tubba Blubba's Castle.
MapConfig kzn_maps []
Mt. Lavalava.
MapConfig flo_maps []
Flower Fields.
MapConfig sam_maps []
Shiver Region.
MapConfig pra_maps []
Crystal Palace.
MapConfig omo_maps []
Shy Guy's Toy Box.
MapConfig tst_maps []
Debug.
MapConfig end_maps []
Credits.
MapConfig mgm_maps []
Toad Town Playroom.
MapConfig gv_maps []
Game Over.
AreaConfig gAreas []
Zero-terminated.
Data Structure Documentation
AssetHeader
struct AssetHeader
Data Fields
u32 compressedLength
u32 decompressedLength
char name[16]
u32 offset
Macro Definition Documentation
AREA
#define AREA (area, jp_name) { ARRAY_COUNT(area##_maps), area##_maps, "area_" #area, jp_name }
ASSET_TABLE_FIRST_ENTRY
#define ASSET_TABLE_FIRST_ENTRY (ASSET_TABLE_ROM_START + ASSET_TABLE_HEADER_SIZE)
Referenced by get_asset_offset(), and load_asset_by_name().
ASSET_TABLE_HEADER_SIZE
#define ASSET_TABLE_HEADER_SIZE 0x20
ASSET_TABLE_ROM_START
#define ASSET_TABLE_ROM_START 0x1E40000
MAP
#define MAP (map)
Value:
    .id = #map, \
    .settings = &map##_settings, \
    .dmaStart = map##_ROM_START, \
    .dmaEnd = map##_ROM_END, \
    .dmaDest = map##_VRAM \
MAP_WITH_INIT
#define MAP_WITH_INIT (map)
Value:
    MAP(map), \
    .init = &map##_map_init \
Function Documentation
fio_deserialize_state()
void fio_deserialize_state (void)
Referenced by fio_load_game(), and load_map_by_IDs().
get_asset_offset()
s32 get_asset_offset (char * assetName, s32 * compressedSize)
Referenced by btl_state_update_normal_start(), load_map_by_IDs(), and state_step_end_battle().
get_current_map_config()
MapConfig * get_current_map_config (void)
get_current_map_settings()
MapSettings * get_current_map_settings (void)
Referenced by entity_BlueWarpPipe_set_player_move_to_center(), get_lava_reset_pos(), load_battle_hit_asset(), load_hit_data(), load_map_hit_asset(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
get_map_IDs_by_name()
s32 get_map_IDs_by_name (const char * mapName, s16 * areaID, s16 * mapID)
Referenced by btl_state_update_end_battle(), goto_map(), and state_step_demo().
load_asset_by_name()
void * load_asset_by_name (const char * assetName, u32 * decompressedSize)
Referenced by btl_state_update_normal_start(), load_battle_hit_asset(), load_map_bg(), load_map_by_IDs(), load_map_hit_asset(), pause_partners_load_portrait(), state_init_title_screen(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
load_map_by_IDs()
void load_map_by_IDs (s16 areaID, s16 mapID, s16 loadType)
Referenced by state_step_change_map(), state_step_enter_world(), state_step_game_over(), and state_step_intro().
load_map_hit_asset()
void load_map_hit_asset (void)
Referenced by load_map_by_IDs(), and restore_map_collision_data().
load_map_script_lib()
void load_map_script_lib (void)
Referenced by load_map_by_IDs(), state_step_end_battle(), and state_step_unpause().
Variable Documentation
arn_maps
MapConfig arn_maps[]
Initial value:
= {
    { .id = "arn_02",   .settings = & arn_02_settings,   .dmaStart =  arn_02_ROM_START,   .dmaEnd =  arn_02_ROM_END,   .dmaDest =  arn_02_VRAM, .bgName = "arn_bg" },
    { .id = "arn_03",   .settings = & arn_03_settings,   .dmaStart =  arn_03_ROM_START,   .dmaEnd =  arn_03_ROM_END,   .dmaDest =  arn_03_VRAM, .bgName = "arn_bg" },
    { .id = "arn_04",   .settings = & arn_04_settings,   .dmaStart =  arn_04_ROM_START,   .dmaEnd =  arn_04_ROM_END,   .dmaDest =  arn_04_VRAM, .bgName = "arn_bg" },
    { .id = "arn_05",   .settings = & arn_05_settings,   .dmaStart =  arn_05_ROM_START,   .dmaEnd =  arn_05_ROM_END,   .dmaDest =  arn_05_VRAM, .bgName = "arn_bg" },
    { .id = "arn_07",   .settings = & arn_07_settings,   .dmaStart =  arn_07_ROM_START,   .dmaEnd =  arn_07_ROM_END,   .dmaDest =  arn_07_VRAM, .bgName = "arn_bg" },
    { .id = "arn_08",   .settings = & arn_08_settings,   .dmaStart =  arn_08_ROM_START,   .dmaEnd =  arn_08_ROM_END,   .dmaDest =  arn_08_VRAM, .songVariation = 1, .sfxReverb = 1 },
    { .id = "arn_09",   .settings = & arn_09_settings,   .dmaStart =  arn_09_ROM_START,   .dmaEnd =  arn_09_ROM_END,   .dmaDest =  arn_09_VRAM, .songVariation = 1, .sfxReverb = 1 },
    { .id = "arn_10",   .settings = & arn_10_settings,   .dmaStart =  arn_10_ROM_START,   .dmaEnd =  arn_10_ROM_END,   .dmaDest =  arn_10_VRAM, .songVariation = 1, .sfxReverb = 1 },
    { .id = "arn_11",   .settings = & arn_11_settings,   .dmaStart =  arn_11_ROM_START,   .dmaEnd =  arn_11_ROM_END,   .dmaDest =  arn_11_VRAM, .songVariation = 1, .sfxReverb = 1 },
    { .id = "arn_12",   .settings = & arn_12_settings,   .dmaStart =  arn_12_ROM_START,   .dmaEnd =  arn_12_ROM_END,   .dmaDest =  arn_12_VRAM, .songVariation = 1, .sfxReverb = 1 },
    { .id = "arn_13",   .settings = & arn_13_settings,   .dmaStart =  arn_13_ROM_START,   .dmaEnd =  arn_13_ROM_END,   .dmaDest =  arn_13_VRAM, .songVariation = 1, .sfxReverb = 1 },
}
Gusty Gulch.
D_800A41E4
BSS s32 D_800A41E4
dgb_maps
MapConfig dgb_maps[]
Initial value:
= {
    { .id = "dgb_00",   .settings = & dgb_00_settings,   .dmaStart =  dgb_00_ROM_START,   .dmaEnd =  dgb_00_ROM_END,   .dmaDest =  dgb_00_VRAM,   .init = & dgb_00_map_init, .bgName = "arn_bg" },
    { .id = "dgb_01",   .settings = & dgb_01_settings,   .dmaStart =  dgb_01_ROM_START,   .dmaEnd =  dgb_01_ROM_END,   .dmaDest =  dgb_01_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_02",   .settings = & dgb_02_settings,   .dmaStart =  dgb_02_ROM_START,   .dmaEnd =  dgb_02_ROM_END,   .dmaDest =  dgb_02_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_03",   .settings = & dgb_03_settings,   .dmaStart =  dgb_03_ROM_START,   .dmaEnd =  dgb_03_ROM_END,   .dmaDest =  dgb_03_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_04",   .settings = & dgb_04_settings,   .dmaStart =  dgb_04_ROM_START,   .dmaEnd =  dgb_04_ROM_END,   .dmaDest =  dgb_04_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_05",   .settings = & dgb_05_settings,   .dmaStart =  dgb_05_ROM_START,   .dmaEnd =  dgb_05_ROM_END,   .dmaDest =  dgb_05_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_06",   .settings = & dgb_06_settings,   .dmaStart =  dgb_06_ROM_START,   .dmaEnd =  dgb_06_ROM_END,   .dmaDest =  dgb_06_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_07",   .settings = & dgb_07_settings,   .dmaStart =  dgb_07_ROM_START,   .dmaEnd =  dgb_07_ROM_END,   .dmaDest =  dgb_07_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_08",   .settings = & dgb_08_settings,   .dmaStart =  dgb_08_ROM_START,   .dmaEnd =  dgb_08_ROM_END,   .dmaDest =  dgb_08_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_09",   .settings = & dgb_09_settings,   .dmaStart =  dgb_09_ROM_START,   .dmaEnd =  dgb_09_ROM_END,   .dmaDest =  dgb_09_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_10",   .settings = & dgb_10_settings,   .dmaStart =  dgb_10_ROM_START,   .dmaEnd =  dgb_10_ROM_END,   .dmaDest =  dgb_10_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_11",   .settings = & dgb_11_settings,   .dmaStart =  dgb_11_ROM_START,   .dmaEnd =  dgb_11_ROM_END,   .dmaDest =  dgb_11_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_12",   .settings = & dgb_12_settings,   .dmaStart =  dgb_12_ROM_START,   .dmaEnd =  dgb_12_ROM_END,   .dmaDest =  dgb_12_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_13",   .settings = & dgb_13_settings,   .dmaStart =  dgb_13_ROM_START,   .dmaEnd =  dgb_13_ROM_END,   .dmaDest =  dgb_13_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_14",   .settings = & dgb_14_settings,   .dmaStart =  dgb_14_ROM_START,   .dmaEnd =  dgb_14_ROM_END,   .dmaDest =  dgb_14_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_15",   .settings = & dgb_15_settings,   .dmaStart =  dgb_15_ROM_START,   .dmaEnd =  dgb_15_ROM_END,   .dmaDest =  dgb_15_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_16",   .settings = & dgb_16_settings,   .dmaStart =  dgb_16_ROM_START,   .dmaEnd =  dgb_16_ROM_END,   .dmaDest =  dgb_16_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_17",   .settings = & dgb_17_settings,   .dmaStart =  dgb_17_ROM_START,   .dmaEnd =  dgb_17_ROM_END,   .dmaDest =  dgb_17_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "dgb_18",   .settings = & dgb_18_settings,   .dmaStart =  dgb_18_ROM_START,   .dmaEnd =  dgb_18_ROM_END,   .dmaDest =  dgb_18_VRAM, .songVariation = 1, .sfxReverb = 2 },
}
Tubba Blubba's Castle.
dro_maps
MapConfig dro_maps[]
Initial value:
= {
    { .id = "dro_01",   .settings = & dro_01_settings,   .dmaStart =  dro_01_ROM_START,   .dmaEnd =  dro_01_ROM_END,   .dmaDest =  dro_01_VRAM, .bgName = "sbk_bg" },
    { .id = "dro_02",   .settings = & dro_02_settings,   .dmaStart =  dro_02_ROM_START,   .dmaEnd =  dro_02_ROM_END,   .dmaDest =  dro_02_VRAM, .bgName = "sbk_bg" },
}
Dry Dry Outpost.
end_maps
MapConfig end_maps[]
Initial value:
= {
    { .id = "end_00",   .settings = & end_00_settings,   .dmaStart =  end_00_ROM_START,   .dmaEnd =  end_00_ROM_END,   .dmaDest =  end_00_VRAM,   .init = & end_00_map_init },
    { .id = "end_01",   .settings = & end_01_settings,   .dmaStart =  end_01_ROM_START,   .dmaEnd =  end_01_ROM_END,   .dmaDest =  end_01_VRAM,   .init = & end_01_map_init },
}
Credits.
flo_maps
MapConfig flo_maps[]
Initial value:
= {
    { .id = "flo_00",   .settings = & flo_00_settings,   .dmaStart =  flo_00_ROM_START,   .dmaEnd =  flo_00_ROM_END,   .dmaDest =  flo_00_VRAM, .bgName = "fla_bg" },
    { .id = "flo_03",   .settings = & flo_03_settings,   .dmaStart =  flo_03_ROM_START,   .dmaEnd =  flo_03_ROM_END,   .dmaDest =  flo_03_VRAM, .bgName = "fla_bg" },
    { .id = "flo_07",   .settings = & flo_07_settings,   .dmaStart =  flo_07_ROM_START,   .dmaEnd =  flo_07_ROM_END,   .dmaDest =  flo_07_VRAM, .bgName = "fla_bg" },
    { .id = "flo_08",   .settings = & flo_08_settings,   .dmaStart =  flo_08_ROM_START,   .dmaEnd =  flo_08_ROM_END,   .dmaDest =  flo_08_VRAM, .bgName = "fla_bg" },
    { .id = "flo_09",   .settings = & flo_09_settings,   .dmaStart =  flo_09_ROM_START,   .dmaEnd =  flo_09_ROM_END,   .dmaDest =  flo_09_VRAM, .bgName = "fla_bg" },
    { .id = "flo_10",   .settings = & flo_10_settings,   .dmaStart =  flo_10_ROM_START,   .dmaEnd =  flo_10_ROM_END,   .dmaDest =  flo_10_VRAM, .bgName = "fla_bg" },
    { .id = "flo_11",   .settings = & flo_11_settings,   .dmaStart =  flo_11_ROM_START,   .dmaEnd =  flo_11_ROM_END,   .dmaDest =  flo_11_VRAM, .bgName = "fla_bg" },
    { .id = "flo_12",   .settings = & flo_12_settings,   .dmaStart =  flo_12_ROM_START,   .dmaEnd =  flo_12_ROM_END,   .dmaDest =  flo_12_VRAM, .bgName = "fla_bg" },
    { .id = "flo_13",   .settings = & flo_13_settings,   .dmaStart =  flo_13_ROM_START,   .dmaEnd =  flo_13_ROM_END,   .dmaDest =  flo_13_VRAM, .bgName = "fla_bg" },
    { .id = "flo_14",   .settings = & flo_14_settings,   .dmaStart =  flo_14_ROM_START,   .dmaEnd =  flo_14_ROM_END,   .dmaDest =  flo_14_VRAM, .bgName = "fla_bg" },
    { .id = "flo_15",   .settings = & flo_15_settings,   .dmaStart =  flo_15_ROM_START,   .dmaEnd =  flo_15_ROM_END,   .dmaDest =  flo_15_VRAM, .bgName = "fla_bg" },
    { .id = "flo_16",   .settings = & flo_16_settings,   .dmaStart =  flo_16_ROM_START,   .dmaEnd =  flo_16_ROM_END,   .dmaDest =  flo_16_VRAM, .bgName = "fla_bg" },
    { .id = "flo_17",   .settings = & flo_17_settings,   .dmaStart =  flo_17_ROM_START,   .dmaEnd =  flo_17_ROM_END,   .dmaDest =  flo_17_VRAM, .bgName = "fla_bg" },
    { .id = "flo_18",   .settings = & flo_18_settings,   .dmaStart =  flo_18_ROM_START,   .dmaEnd =  flo_18_ROM_END,   .dmaDest =  flo_18_VRAM, .bgName = "fla_bg" },
    { .id = "flo_19",   .settings = & flo_19_settings,   .dmaStart =  flo_19_ROM_START,   .dmaEnd =  flo_19_ROM_END,   .dmaDest =  flo_19_VRAM, .bgName = "sra_bg" },
    { .id = "flo_21",   .settings = & flo_21_settings,   .dmaStart =  flo_21_ROM_START,   .dmaEnd =  flo_21_ROM_END,   .dmaDest =  flo_21_VRAM, .bgName = "sra_bg" },
    { .id = "flo_22",   .settings = & flo_22_settings,   .dmaStart =  flo_22_ROM_START,   .dmaEnd =  flo_22_ROM_END,   .dmaDest =  flo_22_VRAM, .bgName = "fla_bg" },
    { .id = "flo_23",   .settings = & flo_23_settings,   .dmaStart =  flo_23_ROM_START,   .dmaEnd =  flo_23_ROM_END,   .dmaDest =  flo_23_VRAM, .bgName = "fla_bg" },
    { .id = "flo_24",   .settings = & flo_24_settings,   .dmaStart =  flo_24_ROM_START,   .dmaEnd =  flo_24_ROM_END,   .dmaDest =  flo_24_VRAM, .bgName = "fla_bg" },
    { .id = "flo_25",   .settings = & flo_25_settings,   .dmaStart =  flo_25_ROM_START,   .dmaEnd =  flo_25_ROM_END,   .dmaDest =  flo_25_VRAM, .bgName = "fla_bg" },
}
Flower Fields.
gAreas
AreaConfig gAreas[]
Zero-terminated.
Referenced by bgm_get_map_default_variation(), get_map_IDs_by_name(), load_map_by_IDs(), reset_player_status(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
gEntityColliderFaces
Vec3s gEntityColliderFaces[]
Initial value:
= {
    { 4, 6, 5 }, { 4, 7, 6 },
    { 0, 3, 4 }, { 3, 7, 4 },
    { 3, 2, 7 }, { 2, 6, 7 },
    { 2, 1, 6 }, { 1, 5, 6 },
    { 1, 0, 5 }, { 0, 4, 5 },
    { 0, 1, 2 }, { 0, 2, 3 },
}
Referenced by test_ray_entities().
gEntityColliderNormals
Vec3f gEntityColliderNormals[]
Initial value:
= {
    {  0.0f,  1.0f,  0.0f }, {  0.0f,  1.0f,  0.0f },
    {  1.0f,  0.0f,  0.0f }, {  1.0f,  0.0f,  0.0f },
    {  0.0f,  0.0f, -1.0f }, {  0.0f,  0.0f, -1.0f },
    { -1.0f,  0.0f,  0.0f }, { -1.0f,  0.0f,  0.0f },
    {  0.0f,  0.0f,  1.0f }, {  0.0f,  0.0f,  1.0f },
    {  0.0f, -1.0f,  0.0f }, {  0.0f, -1.0f,  0.0f },
}
Referenced by test_ray_entities().
gMapConfig
BSS MapConfig* gMapConfig
Referenced by get_current_map_config(), and load_map_by_IDs().
gMapSettings
BSS MapSettings gMapSettings
Referenced by get_current_map_settings(), and load_map_by_IDs().
gMapShapeData
ShapeFile gMapShapeData extern
Referenced by load_map_by_IDs().
gv_maps
MapConfig gv_maps[]
Initial value:
= {
    { .id = "gv_01",   .settings = & gv_01_settings,   .dmaStart =  gv_01_ROM_START,   .dmaEnd =  gv_01_ROM_END,   .dmaDest =  gv_01_VRAM },
}
Game Over.
hos_maps
MapConfig hos_maps[]
Initial value:
= {
    { .id = "hos_00",   .settings = & hos_00_settings,   .dmaStart =  hos_00_ROM_START,   .dmaEnd =  hos_00_ROM_END,   .dmaDest =  hos_00_VRAM,   .init = & hos_00_map_init, .bgName = "nok_bg" },
    { .id = "hos_01",   .settings = & hos_01_settings,   .dmaStart =  hos_01_ROM_START,   .dmaEnd =  hos_01_ROM_END,   .dmaDest =  hos_01_VRAM, .bgName = "hos_bg" },
    { .id = "hos_02",   .settings = & hos_02_settings,   .dmaStart =  hos_02_ROM_START,   .dmaEnd =  hos_02_ROM_END,   .dmaDest =  hos_02_VRAM, .bgName = "hos_bg" },
    { .id = "hos_03",   .settings = & hos_03_settings,   .dmaStart =  hos_03_ROM_START,   .dmaEnd =  hos_03_ROM_END,   .dmaDest =  hos_03_VRAM, .bgName = "hos_bg" },
    { .id = "hos_04",   .settings = & hos_04_settings,   .dmaStart =  hos_04_ROM_START,   .dmaEnd =  hos_04_ROM_END,   .dmaDest =  hos_04_VRAM, .bgName = "hos_bg" },
    { .id = "hos_05",   .settings = & hos_05_settings,   .dmaStart =  hos_05_ROM_START,   .dmaEnd =  hos_05_ROM_END,   .dmaDest =  hos_05_VRAM, .bgName = "hos_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "hos_06",   .settings = & hos_06_settings,   .dmaStart =  hos_06_ROM_START,   .dmaEnd =  hos_06_ROM_END,   .dmaDest =  hos_06_VRAM, .bgName = "hos_bg" },
    { .id = "hos_10",   .settings = & hos_10_settings,   .dmaStart =  hos_10_ROM_START,   .dmaEnd =  hos_10_ROM_END,   .dmaDest =  hos_10_VRAM,   .init = & hos_10_map_init, .bgName = "hos_bg" },
    { .id = "hos_20",   .settings = & hos_20_settings,   .dmaStart =  hos_20_ROM_START,   .dmaEnd =  hos_20_ROM_END,   .dmaDest =  hos_20_VRAM, .bgName = "hos_bg" },
}
Star Region.
isk_maps
MapConfig isk_maps[]
Initial value:
= {
    { .id = "isk_01",   .settings = & isk_01_settings,   .dmaStart =  isk_01_ROM_START,   .dmaEnd =  isk_01_ROM_END,   .dmaDest =  isk_01_VRAM, .bgName = "sbk3_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_02",   .settings = & isk_02_settings,   .dmaStart =  isk_02_ROM_START,   .dmaEnd =  isk_02_ROM_END,   .dmaDest =  isk_02_VRAM, .bgName = "sbk3_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_03",   .settings = & isk_03_settings,   .dmaStart =  isk_03_ROM_START,   .dmaEnd =  isk_03_ROM_END,   .dmaDest =  isk_03_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_04",   .settings = & isk_04_settings,   .dmaStart =  isk_04_ROM_START,   .dmaEnd =  isk_04_ROM_END,   .dmaDest =  isk_04_VRAM, .bgName = "sbk3_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_05",   .settings = & isk_05_settings,   .dmaStart =  isk_05_ROM_START,   .dmaEnd =  isk_05_ROM_END,   .dmaDest =  isk_05_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_06",   .settings = & isk_06_settings,   .dmaStart =  isk_06_ROM_START,   .dmaEnd =  isk_06_ROM_END,   .dmaDest =  isk_06_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_07",   .settings = & isk_07_settings,   .dmaStart =  isk_07_ROM_START,   .dmaEnd =  isk_07_ROM_END,   .dmaDest =  isk_07_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_08",   .settings = & isk_08_settings,   .dmaStart =  isk_08_ROM_START,   .dmaEnd =  isk_08_ROM_END,   .dmaDest =  isk_08_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_09",   .settings = & isk_09_settings,   .dmaStart =  isk_09_ROM_START,   .dmaEnd =  isk_09_ROM_END,   .dmaDest =  isk_09_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_10",   .settings = & isk_10_settings,   .dmaStart =  isk_10_ROM_START,   .dmaEnd =  isk_10_ROM_END,   .dmaDest =  isk_10_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_11",   .settings = & isk_11_settings,   .dmaStart =  isk_11_ROM_START,   .dmaEnd =  isk_11_ROM_END,   .dmaDest =  isk_11_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_12",   .settings = & isk_12_settings,   .dmaStart =  isk_12_ROM_START,   .dmaEnd =  isk_12_ROM_END,   .dmaDest =  isk_12_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_13",   .settings = & isk_13_settings,   .dmaStart =  isk_13_ROM_START,   .dmaEnd =  isk_13_ROM_END,   .dmaDest =  isk_13_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_14",   .settings = & isk_14_settings,   .dmaStart =  isk_14_ROM_START,   .dmaEnd =  isk_14_ROM_END,   .dmaDest =  isk_14_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_16",   .settings = & isk_16_settings,   .dmaStart =  isk_16_ROM_START,   .dmaEnd =  isk_16_ROM_END,   .dmaDest =  isk_16_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_18",   .settings = & isk_18_settings,   .dmaStart =  isk_18_ROM_START,   .dmaEnd =  isk_18_ROM_END,   .dmaDest =  isk_18_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "isk_19",   .settings = & isk_19_settings,   .dmaStart =  isk_19_ROM_START,   .dmaEnd =  isk_19_ROM_END,   .dmaDest =  isk_19_VRAM, .songVariation = 1, .sfxReverb = 2 },
}
Dry Dry Ruins.
iwa_maps
MapConfig iwa_maps[]
Initial value:
= {
    { .id = "iwa_00",   .settings = & iwa_00_settings,   .dmaStart =  iwa_00_ROM_START,   .dmaEnd =  iwa_00_ROM_END,   .dmaDest =  iwa_00_VRAM, .bgName = "iwa_bg" },
    { .id = "iwa_01",   .settings = & iwa_01_settings,   .dmaStart =  iwa_01_ROM_START,   .dmaEnd =  iwa_01_ROM_END,   .dmaDest =  iwa_01_VRAM, .bgName = "iwa_bg" },
    { .id = "iwa_02",   .settings = & iwa_02_settings,   .dmaStart =  iwa_02_ROM_START,   .dmaEnd =  iwa_02_ROM_END,   .dmaDest =  iwa_02_VRAM, .bgName = "iwa_bg" },
    { .id = "iwa_03",   .settings = & iwa_03_settings,   .dmaStart =  iwa_03_ROM_START,   .dmaEnd =  iwa_03_ROM_END,   .dmaDest =  iwa_03_VRAM, .bgName = "iwa_bg" },
    { .id = "iwa_04",   .settings = & iwa_04_settings,   .dmaStart =  iwa_04_ROM_START,   .dmaEnd =  iwa_04_ROM_END,   .dmaDest =  iwa_04_VRAM, .bgName = "iwa_bg" },
    { .id = "iwa_10",   .settings = & iwa_10_settings,   .dmaStart =  iwa_10_ROM_START,   .dmaEnd =  iwa_10_ROM_END,   .dmaDest =  iwa_10_VRAM, .bgName = "iwa_bg" },
    { .id = "iwa_11",   .settings = & iwa_11_settings,   .dmaStart =  iwa_11_ROM_START,   .dmaEnd =  iwa_11_ROM_END,   .dmaDest =  iwa_11_VRAM, .bgName = "iwa_bg" },
}
Mt. Rugged.
jan_maps
MapConfig jan_maps[]
Initial value:
= {
    { .id = "jan_00",   .settings = & jan_00_settings,   .dmaStart =  jan_00_ROM_START,   .dmaEnd =  jan_00_ROM_END,   .dmaDest =  jan_00_VRAM, .bgName = "yos_bg" },
    { .id = "jan_01",   .settings = & jan_01_settings,   .dmaStart =  jan_01_ROM_START,   .dmaEnd =  jan_01_ROM_END,   .dmaDest =  jan_01_VRAM, .bgName = "yos_bg" },
    { .id = "jan_02",   .settings = & jan_02_settings,   .dmaStart =  jan_02_ROM_START,   .dmaEnd =  jan_02_ROM_END,   .dmaDest =  jan_02_VRAM, .bgName = "yos_bg" },
    { .id = "jan_03",   .settings = & jan_03_settings,   .dmaStart =  jan_03_ROM_START,   .dmaEnd =  jan_03_ROM_END,   .dmaDest =  jan_03_VRAM, .bgName = "yos_bg" },
    { .id = "jan_04",   .settings = & jan_04_settings,   .dmaStart =  jan_04_ROM_START,   .dmaEnd =  jan_04_ROM_END,   .dmaDest =  jan_04_VRAM, .bgName = "yos_bg" },
    { .id = "jan_05",   .settings = & jan_05_settings,   .dmaStart =  jan_05_ROM_START,   .dmaEnd =  jan_05_ROM_END,   .dmaDest =  jan_05_VRAM, .bgName = "yos_bg" },
    { .id = "jan_06",   .settings = & jan_06_settings,   .dmaStart =  jan_06_ROM_START,   .dmaEnd =  jan_06_ROM_END,   .dmaDest =  jan_06_VRAM, .bgName = "jan_bg" },
    { .id = "jan_07",   .settings = & jan_07_settings,   .dmaStart =  jan_07_ROM_START,   .dmaEnd =  jan_07_ROM_END,   .dmaDest =  jan_07_VRAM, .bgName = "yos_bg" },
    { .id = "jan_08",   .settings = & jan_08_settings,   .dmaStart =  jan_08_ROM_START,   .dmaEnd =  jan_08_ROM_END,   .dmaDest =  jan_08_VRAM, .bgName = "yos_bg" },
    { .id = "jan_09",   .settings = & jan_09_settings,   .dmaStart =  jan_09_ROM_START,   .dmaEnd =  jan_09_ROM_END,   .dmaDest =  jan_09_VRAM, .bgName = "yos_bg" },
    { .id = "jan_10",   .settings = & jan_10_settings,   .dmaStart =  jan_10_ROM_START,   .dmaEnd =  jan_10_ROM_END,   .dmaDest =  jan_10_VRAM, .bgName = "yos_bg" },
    { .id = "jan_11",   .settings = & jan_11_settings,   .dmaStart =  jan_11_ROM_START,   .dmaEnd =  jan_11_ROM_END,   .dmaDest =  jan_11_VRAM, .bgName = "jan_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "jan_12",   .settings = & jan_12_settings,   .dmaStart =  jan_12_ROM_START,   .dmaEnd =  jan_12_ROM_END,   .dmaDest =  jan_12_VRAM, .bgName = "jan_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "jan_13",   .settings = & jan_13_settings,   .dmaStart =  jan_13_ROM_START,   .dmaEnd =  jan_13_ROM_END,   .dmaDest =  jan_13_VRAM, .bgName = "jan_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "jan_14",   .settings = & jan_14_settings,   .dmaStart =  jan_14_ROM_START,   .dmaEnd =  jan_14_ROM_END,   .dmaDest =  jan_14_VRAM, .bgName = "jan_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "jan_15",   .settings = & jan_15_settings,   .dmaStart =  jan_15_ROM_START,   .dmaEnd =  jan_15_ROM_END,   .dmaDest =  jan_15_VRAM, .bgName = "jan_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "jan_16",   .settings = & jan_16_settings,   .dmaStart =  jan_16_ROM_START,   .dmaEnd =  jan_16_ROM_END,   .dmaDest =  jan_16_VRAM, .bgName = "jan_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "jan_17",   .settings = & jan_17_settings,   .dmaStart =  jan_17_ROM_START,   .dmaEnd =  jan_17_ROM_END,   .dmaDest =  jan_17_VRAM, .bgName = "jan_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "jan_18",   .settings = & jan_18_settings,   .dmaStart =  jan_18_ROM_START,   .dmaEnd =  jan_18_ROM_END,   .dmaDest =  jan_18_VRAM, .bgName = "yos_bg" },
    { .id = "jan_19",   .settings = & jan_19_settings,   .dmaStart =  jan_19_ROM_START,   .dmaEnd =  jan_19_ROM_END,   .dmaDest =  jan_19_VRAM, .bgName = "jan_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "jan_22",   .settings = & jan_22_settings,   .dmaStart =  jan_22_ROM_START,   .dmaEnd =  jan_22_ROM_END,   .dmaDest =  jan_22_VRAM, .bgName = "jan_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "jan_23",   .settings = & jan_23_settings,   .dmaStart =  jan_23_ROM_START,   .dmaEnd =  jan_23_ROM_END,   .dmaDest =  jan_23_VRAM, .bgName = "yos_bg" },
}
Jade Jungle.
kgr_maps
MapConfig kgr_maps[]
Initial value:
= {
    { .id = "kgr_01",   .settings = & kgr_01_settings,   .dmaStart =  kgr_01_ROM_START,   .dmaEnd =  kgr_01_ROM_END,   .dmaDest =  kgr_01_VRAM, .sfxReverb = 1 },
    { .id = "kgr_02",   .settings = & kgr_02_settings,   .dmaStart =  kgr_02_ROM_START,   .dmaEnd =  kgr_02_ROM_END,   .dmaDest =  kgr_02_VRAM, .sfxReverb = 1 },
}
Inside the Whale.
kkj_maps
MapConfig kkj_maps[]
Initial value:
= {
    { .id = "kkj_00",   .settings = & kkj_00_settings,   .dmaStart =  kkj_00_ROM_START,   .dmaEnd =  kkj_00_ROM_END,   .dmaDest =  kkj_00_VRAM,   .init = & kkj_00_map_init, .bgName = "nok_bg", .songVariation = 1, .sfxReverb = 3 },
    { .id = "kkj_01",   .settings = & kkj_01_settings,   .dmaStart =  kkj_01_ROM_START,   .dmaEnd =  kkj_01_ROM_END,   .dmaDest =  kkj_01_VRAM, .bgName = "nok_bg", .songVariation = 1, .sfxReverb = 3 },
    { .id = "kkj_02",   .settings = & kkj_02_settings,   .dmaStart =  kkj_02_ROM_START,   .dmaEnd =  kkj_02_ROM_END,   .dmaDest =  kkj_02_VRAM, .bgName = "nok_bg", .sfxReverb = 2 },
    { .id = "kkj_03",   .settings = & kkj_03_settings,   .dmaStart =  kkj_03_ROM_START,   .dmaEnd =  kkj_03_ROM_END,   .dmaDest =  kkj_03_VRAM,   .init = & kkj_03_map_init, .bgName = "nok_bg", .sfxReverb = 3 },
    { .id = "kkj_10",   .settings = & kkj_10_settings,   .dmaStart =  kkj_10_ROM_START,   .dmaEnd =  kkj_10_ROM_END,   .dmaDest =  kkj_10_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "kkj_11",   .settings = & kkj_11_settings,   .dmaStart =  kkj_11_ROM_START,   .dmaEnd =  kkj_11_ROM_END,   .dmaDest =  kkj_11_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "kkj_12",   .settings = & kkj_12_settings,   .dmaStart =  kkj_12_ROM_START,   .dmaEnd =  kkj_12_ROM_END,   .dmaDest =  kkj_12_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kkj_13",   .settings = & kkj_13_settings,   .dmaStart =  kkj_13_ROM_START,   .dmaEnd =  kkj_13_ROM_END,   .dmaDest =  kkj_13_VRAM,   .init = & kkj_13_map_init, .bgName = "kpa_bg",  .songVariation = 1, .sfxReverb = 3},
    { .id = "kkj_14",   .settings = & kkj_14_settings,   .dmaStart =  kkj_14_ROM_START,   .dmaEnd =  kkj_14_ROM_END,   .dmaDest =  kkj_14_VRAM,   .init = & kkj_14_map_init, .bgName = "kpa_bg" },
    { .id = "kkj_15",   .settings = & kkj_15_settings,   .dmaStart =  kkj_15_ROM_START,   .dmaEnd =  kkj_15_ROM_END,   .dmaDest =  kkj_15_VRAM },
    { .id = "kkj_16",   .settings = & kkj_16_settings,   .dmaStart =  kkj_16_ROM_START,   .dmaEnd =  kkj_16_ROM_END,   .dmaDest =  kkj_16_VRAM, .sfxReverb = 1 },
    { .id = "kkj_17",   .settings = & kkj_17_settings,   .dmaStart =  kkj_17_ROM_START,   .dmaEnd =  kkj_17_ROM_END,   .dmaDest =  kkj_17_VRAM },
    { .id = "kkj_18",   .settings = & kkj_18_settings,   .dmaStart =  kkj_18_ROM_START,   .dmaEnd =  kkj_18_ROM_END,   .dmaDest =  kkj_18_VRAM, .bgName = "kpa_bg" },
    { .id = "kkj_19",   .settings = & kkj_19_settings,   .dmaStart =  kkj_19_ROM_START,   .dmaEnd =  kkj_19_ROM_END,   .dmaDest =  kkj_19_VRAM },
    { .id = "kkj_20",   .settings = & kkj_20_settings,   .dmaStart =  kkj_20_ROM_START,   .dmaEnd =  kkj_20_ROM_END,   .dmaDest =  kkj_20_VRAM },
    { .id = "kkj_21",   .settings = & kkj_21_settings,   .dmaStart =  kkj_21_ROM_START,   .dmaEnd =  kkj_21_ROM_END,   .dmaDest =  kkj_21_VRAM, .sfxReverb = 1 },
    { .id = "kkj_22",   .settings = & kkj_22_settings,   .dmaStart =  kkj_22_ROM_START,   .dmaEnd =  kkj_22_ROM_END,   .dmaDest =  kkj_22_VRAM, .bgName = "kpa_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "kkj_23",   .settings = & kkj_23_settings,   .dmaStart =  kkj_23_ROM_START,   .dmaEnd =  kkj_23_ROM_END,   .dmaDest =  kkj_23_VRAM,   .init = & kkj_23_map_init, .bgName = "kpa_bg" },
    { .id = "kkj_24",   .settings = & kkj_24_settings,   .dmaStart =  kkj_24_ROM_START,   .dmaEnd =  kkj_24_ROM_END,   .dmaDest =  kkj_24_VRAM, .bgName = "kpa_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "kkj_25",   .settings = & kkj_25_settings,   .dmaStart =  kkj_25_ROM_START,   .dmaEnd =  kkj_25_ROM_END,   .dmaDest =  kkj_25_VRAM,   .init = & kkj_25_map_init, .bgName = "kpa_bg" },
    { .id = "kkj_26",   .settings = & kkj_26_settings,   .dmaStart =  kkj_26_ROM_START,   .dmaEnd =  kkj_26_ROM_END,   .dmaDest =  kkj_26_VRAM, .bgName = "kpa_bg" },
    { .id = "kkj_26",   .settings = & kkj_26_settings,   .dmaStart =  kkj_26_ROM_START,   .dmaEnd =  kkj_26_ROM_END,   .dmaDest =  kkj_26_VRAM, .sfxReverb = 2 },
    { .id = "kkj_27",   .settings = & kkj_27_settings,   .dmaStart =  kkj_27_ROM_START,   .dmaEnd =  kkj_27_ROM_END,   .dmaDest =  kkj_27_VRAM, .sfxReverb = 1 },
    { .id = "kkj_28",   .settings = & kkj_28_settings,   .dmaStart =  kkj_28_ROM_START,   .dmaEnd =  kkj_28_ROM_END,   .dmaDest =  kkj_28_VRAM, .sfxReverb = 1 },
    { .id = "kkj_29",   .settings = & kkj_29_settings,   .dmaStart =  kkj_29_ROM_START,   .dmaEnd =  kkj_29_ROM_END,   .dmaDest =  kkj_29_VRAM, .sfxReverb = 1 },
}
Peach's Castle.
Bug
There are two entries for kkj_26; the latter is unreachable.
kmr_maps
MapConfig kmr_maps[]
Initial value:
= {
    { .id = "kmr_00",   .settings = & kmr_00_settings,   .dmaStart =  kmr_00_ROM_START,   .dmaEnd =  kmr_00_ROM_END,   .dmaDest =  kmr_00_VRAM, .bgName = "kmr_bg", .sfxReverb = 1 },
    { .id = "kmr_02",   .settings = & kmr_02_settings,   .dmaStart =  kmr_02_ROM_START,   .dmaEnd =  kmr_02_ROM_END,   .dmaDest =  kmr_02_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_03",   .settings = & kmr_03_settings,   .dmaStart =  kmr_03_ROM_START,   .dmaEnd =  kmr_03_ROM_END,   .dmaDest =  kmr_03_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_04",   .settings = & kmr_04_settings,   .dmaStart =  kmr_04_ROM_START,   .dmaEnd =  kmr_04_ROM_END,   .dmaDest =  kmr_04_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_05",   .settings = & kmr_05_settings,   .dmaStart =  kmr_05_ROM_START,   .dmaEnd =  kmr_05_ROM_END,   .dmaDest =  kmr_05_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_06",   .settings = & kmr_06_settings,   .dmaStart =  kmr_06_ROM_START,   .dmaEnd =  kmr_06_ROM_END,   .dmaDest =  kmr_06_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_07",   .settings = & kmr_07_settings,   .dmaStart =  kmr_07_ROM_START,   .dmaEnd =  kmr_07_ROM_END,   .dmaDest =  kmr_07_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_09",   .settings = & kmr_09_settings,   .dmaStart =  kmr_09_ROM_START,   .dmaEnd =  kmr_09_ROM_END,   .dmaDest =  kmr_09_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_10",   .settings = & kmr_10_settings,   .dmaStart =  kmr_10_ROM_START,   .dmaEnd =  kmr_10_ROM_END,   .dmaDest =  kmr_10_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_11",   .settings = & kmr_11_settings,   .dmaStart =  kmr_11_ROM_START,   .dmaEnd =  kmr_11_ROM_END,   .dmaDest =  kmr_11_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_12",   .settings = & kmr_12_settings,   .dmaStart =  kmr_12_ROM_START,   .dmaEnd =  kmr_12_ROM_END,   .dmaDest =  kmr_12_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_20",   .settings = & kmr_20_settings,   .dmaStart =  kmr_20_ROM_START,   .dmaEnd =  kmr_20_ROM_END,   .dmaDest =  kmr_20_VRAM, .bgName = "kmr_bg" },
    { .id = "kmr_21",   .settings = & kmr_21_settings,   .dmaStart =  kmr_21_ROM_START,   .dmaEnd =  kmr_21_ROM_END,   .dmaDest =  kmr_21_VRAM,   .init = & kmr_21_map_init },
    { .id = "kmr_22",   .settings = & kmr_22_settings,   .dmaStart =  kmr_22_ROM_START,   .dmaEnd =  kmr_22_ROM_END,   .dmaDest =  kmr_22_VRAM,   .init = & kmr_22_map_init },
    { .id = "kmr_23",   .settings = & kmr_23_settings,   .dmaStart =  kmr_23_ROM_START,   .dmaEnd =  kmr_23_ROM_END,   .dmaDest =  kmr_23_VRAM,   .init = & kmr_23_map_init },
    { .id = "kmr_24",   .settings = & kmr_24_settings,   .dmaStart =  kmr_24_ROM_START,   .dmaEnd =  kmr_24_ROM_END,   .dmaDest =  kmr_24_VRAM,   .init = & kmr_24_map_init },
    { .id = "kmr_30",   .settings = & kmr_30_settings,   .dmaStart =  kmr_30_ROM_START,   .dmaEnd =  kmr_30_ROM_END,   .dmaDest =  kmr_30_VRAM },
}
Goomba Region.
kpa_maps
MapConfig kpa_maps[]
Bowser's Castle.
kzn_maps
MapConfig kzn_maps[]
Initial value:
= {
    { .id = "kzn_01",   .settings = & kzn_01_settings,   .dmaStart =  kzn_01_ROM_START,   .dmaEnd =  kzn_01_ROM_END,   .dmaDest =  kzn_01_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_02",   .settings = & kzn_02_settings,   .dmaStart =  kzn_02_ROM_START,   .dmaEnd =  kzn_02_ROM_END,   .dmaDest =  kzn_02_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_03",   .settings = & kzn_03_settings,   .dmaStart =  kzn_03_ROM_START,   .dmaEnd =  kzn_03_ROM_END,   .dmaDest =  kzn_03_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_04",   .settings = & kzn_04_settings,   .dmaStart =  kzn_04_ROM_START,   .dmaEnd =  kzn_04_ROM_END,   .dmaDest =  kzn_04_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_05",   .settings = & kzn_05_settings,   .dmaStart =  kzn_05_ROM_START,   .dmaEnd =  kzn_05_ROM_END,   .dmaDest =  kzn_05_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_06",   .settings = & kzn_06_settings,   .dmaStart =  kzn_06_ROM_START,   .dmaEnd =  kzn_06_ROM_END,   .dmaDest =  kzn_06_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_07",   .settings = & kzn_07_settings,   .dmaStart =  kzn_07_ROM_START,   .dmaEnd =  kzn_07_ROM_END,   .dmaDest =  kzn_07_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_08",   .settings = & kzn_08_settings,   .dmaStart =  kzn_08_ROM_START,   .dmaEnd =  kzn_08_ROM_END,   .dmaDest =  kzn_08_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_09",   .settings = & kzn_09_settings,   .dmaStart =  kzn_09_ROM_START,   .dmaEnd =  kzn_09_ROM_END,   .dmaDest =  kzn_09_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_10",   .settings = & kzn_10_settings,   .dmaStart =  kzn_10_ROM_START,   .dmaEnd =  kzn_10_ROM_END,   .dmaDest =  kzn_10_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_11",   .settings = & kzn_11_settings,   .dmaStart =  kzn_11_ROM_START,   .dmaEnd =  kzn_11_ROM_END,   .dmaDest =  kzn_11_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_17",   .settings = & kzn_17_settings,   .dmaStart =  kzn_17_ROM_START,   .dmaEnd =  kzn_17_ROM_END,   .dmaDest =  kzn_17_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_18",   .settings = & kzn_18_settings,   .dmaStart =  kzn_18_ROM_START,   .dmaEnd =  kzn_18_ROM_END,   .dmaDest =  kzn_18_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_19",   .settings = & kzn_19_settings,   .dmaStart =  kzn_19_ROM_START,   .dmaEnd =  kzn_19_ROM_END,   .dmaDest =  kzn_19_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_20",   .settings = & kzn_20_settings,   .dmaStart =  kzn_20_ROM_START,   .dmaEnd =  kzn_20_ROM_END,   .dmaDest =  kzn_20_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_22",   .settings = & kzn_22_settings,   .dmaStart =  kzn_22_ROM_START,   .dmaEnd =  kzn_22_ROM_END,   .dmaDest =  kzn_22_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "kzn_23",   .settings = & kzn_23_settings,   .dmaStart =  kzn_23_ROM_START,   .dmaEnd =  kzn_23_ROM_END,   .dmaDest =  kzn_23_VRAM, .bgName = "yos_bg", .songVariation = 1, .sfxReverb = 2 },
}
Mt. Lavalava.
mac_maps
MapConfig mac_maps[]
Initial value:
= {
    { .id = "machi",   .settings = & machi_settings,   .dmaStart =  machi_ROM_START,   .dmaEnd =  machi_ROM_END,   .dmaDest =  machi_VRAM, .bgName = "nok_bg" },
    { .id = "mac_00",   .settings = & mac_00_settings,   .dmaStart =  mac_00_ROM_START,   .dmaEnd =  mac_00_ROM_END,   .dmaDest =  mac_00_VRAM, .bgName = "nok_bg" },
    { .id = "mac_01",   .settings = & mac_01_settings,   .dmaStart =  mac_01_ROM_START,   .dmaEnd =  mac_01_ROM_END,   .dmaDest =  mac_01_VRAM, .bgName = "nok_bg" },
    { .id = "mac_02",   .settings = & mac_02_settings,   .dmaStart =  mac_02_ROM_START,   .dmaEnd =  mac_02_ROM_END,   .dmaDest =  mac_02_VRAM, .bgName = "nok_bg" },
    { .id = "mac_03",   .settings = & mac_03_settings,   .dmaStart =  mac_03_ROM_START,   .dmaEnd =  mac_03_ROM_END,   .dmaDest =  mac_03_VRAM, .bgName = "nok_bg" },
    { .id = "mac_04",   .settings = & mac_04_settings,   .dmaStart =  mac_04_ROM_START,   .dmaEnd =  mac_04_ROM_END,   .dmaDest =  mac_04_VRAM,   .init = & mac_04_map_init, .bgName = "nok_bg" },
    { .id = "mac_05",   .settings = & mac_05_settings,   .dmaStart =  mac_05_ROM_START,   .dmaEnd =  mac_05_ROM_END,   .dmaDest =  mac_05_VRAM, .bgName = "nok_bg" },
    { .id = "mac_06",   .settings = & mac_06_settings,   .dmaStart =  mac_06_ROM_START,   .dmaEnd =  mac_06_ROM_END,   .dmaDest =  mac_06_VRAM, .bgName = "nok_bg" },
}
Toad Town.
mgm_maps
MapConfig mgm_maps[]
Initial value:
= {
    { .id = "mgm_00",   .settings = & mgm_00_settings,   .dmaStart =  mgm_00_ROM_START,   .dmaEnd =  mgm_00_ROM_END,   .dmaDest =  mgm_00_VRAM },
    { .id = "mgm_01",   .settings = & mgm_01_settings,   .dmaStart =  mgm_01_ROM_START,   .dmaEnd =  mgm_01_ROM_END,   .dmaDest =  mgm_01_VRAM },
    { .id = "mgm_02",   .settings = & mgm_02_settings,   .dmaStart =  mgm_02_ROM_START,   .dmaEnd =  mgm_02_ROM_END,   .dmaDest =  mgm_02_VRAM },
    { .id = "mgm_03",   .settings = & mgm_03_settings,   .dmaStart =  mgm_03_ROM_START,   .dmaEnd =  mgm_03_ROM_END,   .dmaDest =  mgm_03_VRAM },
}
Toad Town Playroom.
mim_maps
MapConfig mim_maps[]
Initial value:
= {
    { .id = "mim_01",   .settings = & mim_01_settings,   .dmaStart =  mim_01_ROM_START,   .dmaEnd =  mim_01_ROM_END,   .dmaDest =  mim_01_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_02",   .settings = & mim_02_settings,   .dmaStart =  mim_02_ROM_START,   .dmaEnd =  mim_02_ROM_END,   .dmaDest =  mim_02_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_03",   .settings = & mim_03_settings,   .dmaStart =  mim_03_ROM_START,   .dmaEnd =  mim_03_ROM_END,   .dmaDest =  mim_03_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_04",   .settings = & mim_04_settings,   .dmaStart =  mim_04_ROM_START,   .dmaEnd =  mim_04_ROM_END,   .dmaDest =  mim_04_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_05",   .settings = & mim_05_settings,   .dmaStart =  mim_05_ROM_START,   .dmaEnd =  mim_05_ROM_END,   .dmaDest =  mim_05_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_06",   .settings = & mim_06_settings,   .dmaStart =  mim_06_ROM_START,   .dmaEnd =  mim_06_ROM_END,   .dmaDest =  mim_06_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_07",   .settings = & mim_07_settings,   .dmaStart =  mim_07_ROM_START,   .dmaEnd =  mim_07_ROM_END,   .dmaDest =  mim_07_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_08",   .settings = & mim_08_settings,   .dmaStart =  mim_08_ROM_START,   .dmaEnd =  mim_08_ROM_END,   .dmaDest =  mim_08_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_09",   .settings = & mim_09_settings,   .dmaStart =  mim_09_ROM_START,   .dmaEnd =  mim_09_ROM_END,   .dmaDest =  mim_09_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_10",   .settings = & mim_10_settings,   .dmaStart =  mim_10_ROM_START,   .dmaEnd =  mim_10_ROM_END,   .dmaDest =  mim_10_VRAM, .bgName = "nok_bg" },
    { .id = "mim_11",   .settings = & mim_11_settings,   .dmaStart =  mim_11_ROM_START,   .dmaEnd =  mim_11_ROM_END,   .dmaDest =  mim_11_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "mim_12",   .settings = & mim_12_settings,   .dmaStart =  mim_12_ROM_START,   .dmaEnd =  mim_12_ROM_END,   .dmaDest =  mim_12_VRAM, .bgName = "arn_bg", .songVariation = 1, .sfxReverb = 2 },
}
Forever Forest.
nok_maps
MapConfig nok_maps[]
Initial value:
= {
    { .id = "nok_01",   .settings = & nok_01_settings,   .dmaStart =  nok_01_ROM_START,   .dmaEnd =  nok_01_ROM_END,   .dmaDest =  nok_01_VRAM, .bgName = "nok_bg" },
    { .id = "nok_02",   .settings = & nok_02_settings,   .dmaStart =  nok_02_ROM_START,   .dmaEnd =  nok_02_ROM_END,   .dmaDest =  nok_02_VRAM, .bgName = "nok_bg" },
    { .id = "nok_03",   .settings = & nok_03_settings,   .dmaStart =  nok_03_ROM_START,   .dmaEnd =  nok_03_ROM_END,   .dmaDest =  nok_03_VRAM, .bgName = "nok_bg" },
    { .id = "nok_04",   .settings = & nok_04_settings,   .dmaStart =  nok_04_ROM_START,   .dmaEnd =  nok_04_ROM_END,   .dmaDest =  nok_04_VRAM, .bgName = "nok_bg" },
    { .id = "nok_11",   .settings = & nok_11_settings,   .dmaStart =  nok_11_ROM_START,   .dmaEnd =  nok_11_ROM_END,   .dmaDest =  nok_11_VRAM, .bgName = "nok_bg" },
    { .id = "nok_12",   .settings = & nok_12_settings,   .dmaStart =  nok_12_ROM_START,   .dmaEnd =  nok_12_ROM_END,   .dmaDest =  nok_12_VRAM, .bgName = "nok_bg" },
    { .id = "nok_13",   .settings = & nok_13_settings,   .dmaStart =  nok_13_ROM_START,   .dmaEnd =  nok_13_ROM_END,   .dmaDest =  nok_13_VRAM, .bgName = "nok_bg" },
    { .id = "nok_14",   .settings = & nok_14_settings,   .dmaStart =  nok_14_ROM_START,   .dmaEnd =  nok_14_ROM_END,   .dmaDest =  nok_14_VRAM, .bgName = "nok_bg" },
    { .id = "nok_15",   .settings = & nok_15_settings,   .dmaStart =  nok_15_ROM_START,   .dmaEnd =  nok_15_ROM_END,   .dmaDest =  nok_15_VRAM, .bgName = "nok_bg" },
}
Koopa Region.
obk_maps
MapConfig obk_maps[]
Initial value:
= {
    { .id = "obk_01",   .settings = & obk_01_settings,   .dmaStart =  obk_01_ROM_START,   .dmaEnd =  obk_01_ROM_END,   .dmaDest =  obk_01_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "obk_02",   .settings = & obk_02_settings,   .dmaStart =  obk_02_ROM_START,   .dmaEnd =  obk_02_ROM_END,   .dmaDest =  obk_02_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "obk_03",   .settings = & obk_03_settings,   .dmaStart =  obk_03_ROM_START,   .dmaEnd =  obk_03_ROM_END,   .dmaDest =  obk_03_VRAM, .songVariation = 1, .sfxReverb = 1 },
    { .id = "obk_04",   .settings = & obk_04_settings,   .dmaStart =  obk_04_ROM_START,   .dmaEnd =  obk_04_ROM_END,   .dmaDest =  obk_04_VRAM, .songVariation = 1, .sfxReverb = 1 },
    { .id = "obk_05",   .settings = & obk_05_settings,   .dmaStart =  obk_05_ROM_START,   .dmaEnd =  obk_05_ROM_END,   .dmaDest =  obk_05_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "obk_06",   .settings = & obk_06_settings,   .dmaStart =  obk_06_ROM_START,   .dmaEnd =  obk_06_ROM_END,   .dmaDest =  obk_06_VRAM, .songVariation = 1, .sfxReverb = 1 },
    { .id = "obk_07",   .settings = & obk_07_settings,   .dmaStart =  obk_07_ROM_START,   .dmaEnd =  obk_07_ROM_END,   .dmaDest =  obk_07_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "obk_08",   .settings = & obk_08_settings,   .dmaStart =  obk_08_ROM_START,   .dmaEnd =  obk_08_ROM_END,   .dmaDest =  obk_08_VRAM, .bgName = "obk_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "obk_09",   .settings = & obk_09_settings,   .dmaStart =  obk_09_ROM_START,   .dmaEnd =  obk_09_ROM_END,   .dmaDest =  obk_09_VRAM, .songVariation = 1, .sfxReverb = 2 },
}
Boo's Mansion.
omo_maps
MapConfig omo_maps[]
Initial value:
= {
    { .id = "omo_01",   .settings = & omo_01_settings,   .dmaStart =  omo_01_ROM_START,   .dmaEnd =  omo_01_ROM_END,   .dmaDest =  omo_01_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_02",   .settings = & omo_02_settings,   .dmaStart =  omo_02_ROM_START,   .dmaEnd =  omo_02_ROM_END,   .dmaDest =  omo_02_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_03",   .settings = & omo_03_settings,   .dmaStart =  omo_03_ROM_START,   .dmaEnd =  omo_03_ROM_END,   .dmaDest =  omo_03_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_04",   .settings = & omo_04_settings,   .dmaStart =  omo_04_ROM_START,   .dmaEnd =  omo_04_ROM_END,   .dmaDest =  omo_04_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_05",   .settings = & omo_05_settings,   .dmaStart =  omo_05_ROM_START,   .dmaEnd =  omo_05_ROM_END,   .dmaDest =  omo_05_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_06",   .settings = & omo_06_settings,   .dmaStart =  omo_06_ROM_START,   .dmaEnd =  omo_06_ROM_END,   .dmaDest =  omo_06_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_07",   .settings = & omo_07_settings,   .dmaStart =  omo_07_ROM_START,   .dmaEnd =  omo_07_ROM_END,   .dmaDest =  omo_07_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_08",   .settings = & omo_08_settings,   .dmaStart =  omo_08_ROM_START,   .dmaEnd =  omo_08_ROM_END,   .dmaDest =  omo_08_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_09",   .settings = & omo_09_settings,   .dmaStart =  omo_09_ROM_START,   .dmaEnd =  omo_09_ROM_END,   .dmaDest =  omo_09_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_10",   .settings = & omo_10_settings,   .dmaStart =  omo_10_ROM_START,   .dmaEnd =  omo_10_ROM_END,   .dmaDest =  omo_10_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_11",   .settings = & omo_11_settings,   .dmaStart =  omo_11_ROM_START,   .dmaEnd =  omo_11_ROM_END,   .dmaDest =  omo_11_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_12",   .settings = & omo_12_settings,   .dmaStart =  omo_12_ROM_START,   .dmaEnd =  omo_12_ROM_END,   .dmaDest =  omo_12_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_13",   .settings = & omo_13_settings,   .dmaStart =  omo_13_ROM_START,   .dmaEnd =  omo_13_ROM_END,   .dmaDest =  omo_13_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_14",   .settings = & omo_14_settings,   .dmaStart =  omo_14_ROM_START,   .dmaEnd =  omo_14_ROM_END,   .dmaDest =  omo_14_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_15",   .settings = & omo_15_settings,   .dmaStart =  omo_15_ROM_START,   .dmaEnd =  omo_15_ROM_END,   .dmaDest =  omo_15_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_16",   .settings = & omo_16_settings,   .dmaStart =  omo_16_ROM_START,   .dmaEnd =  omo_16_ROM_END,   .dmaDest =  omo_16_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
    { .id = "omo_17",   .settings = & omo_17_settings,   .dmaStart =  omo_17_ROM_START,   .dmaEnd =  omo_17_ROM_END,   .dmaDest =  omo_17_VRAM, .bgName = "omo_bg", .songVariation = 1, .sfxReverb = 2 },
}
Shy Guy's Toy Box.
osr_maps
MapConfig osr_maps[]
Initial value:
= {
    { .id = "osr_00",   .settings = & osr_00_settings,   .dmaStart =  osr_00_ROM_START,   .dmaEnd =  osr_00_ROM_END,   .dmaDest =  osr_00_VRAM, .bgName = "nok_bg" },
    { .id = "osr_01",   .settings = & osr_01_settings,   .dmaStart =  osr_01_ROM_START,   .dmaEnd =  osr_01_ROM_END,   .dmaDest =  osr_01_VRAM,   .init = & osr_01_map_init, .bgName = "nok_bg" },
    { .id = "osr_02",   .settings = & osr_02_settings,   .dmaStart =  osr_02_ROM_START,   .dmaEnd =  osr_02_ROM_END,   .dmaDest =  osr_02_VRAM,   .init = & osr_02_map_init, .bgName = "kpa_bg" },
    { .id = "osr_03",   .settings = & osr_03_settings,   .dmaStart =  osr_03_ROM_START,   .dmaEnd =  osr_03_ROM_END,   .dmaDest =  osr_03_VRAM,   .init = & osr_03_map_init, .bgName = "kpa_bg" },
    { .id = "osr_04",   .settings = & osr_04_settings,   .dmaStart =  osr_04_ROM_START,   .dmaEnd =  osr_04_ROM_END,   .dmaDest =  osr_04_VRAM,   .init = & osr_04_map_init, .bgName = "nok_bg" },
}
Peach's Castle Grounds.
pad_map_table
s32 pad_map_table[] = { 0, 0 }
pra_maps
MapConfig pra_maps[]
Crystal Palace.
sam_maps
MapConfig sam_maps[]
Initial value:
= {
    { .id = "sam_01",   .settings = & sam_01_settings,   .dmaStart =  sam_01_ROM_START,   .dmaEnd =  sam_01_ROM_END,   .dmaDest =  sam_01_VRAM, .bgName = "yki_bg" },
    { .id = "sam_02",   .settings = & sam_02_settings,   .dmaStart =  sam_02_ROM_START,   .dmaEnd =  sam_02_ROM_END,   .dmaDest =  sam_02_VRAM, .bgName = "yki_bg" },
    { .id = "sam_03",   .settings = & sam_03_settings,   .dmaStart =  sam_03_ROM_START,   .dmaEnd =  sam_03_ROM_END,   .dmaDest =  sam_03_VRAM, .bgName = "yki_bg" },
    { .id = "sam_04",   .settings = & sam_04_settings,   .dmaStart =  sam_04_ROM_START,   .dmaEnd =  sam_04_ROM_END,   .dmaDest =  sam_04_VRAM, .bgName = "yki_bg" },
    { .id = "sam_05",   .settings = & sam_05_settings,   .dmaStart =  sam_05_ROM_START,   .dmaEnd =  sam_05_ROM_END,   .dmaDest =  sam_05_VRAM, .bgName = "sam_bg" },
    { .id = "sam_06",   .settings = & sam_06_settings,   .dmaStart =  sam_06_ROM_START,   .dmaEnd =  sam_06_ROM_END,   .dmaDest =  sam_06_VRAM, .bgName = "sam_bg" },
    { .id = "sam_07",   .settings = & sam_07_settings,   .dmaStart =  sam_07_ROM_START,   .dmaEnd =  sam_07_ROM_END,   .dmaDest =  sam_07_VRAM, .bgName = "yki_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "sam_08",   .settings = & sam_08_settings,   .dmaStart =  sam_08_ROM_START,   .dmaEnd =  sam_08_ROM_END,   .dmaDest =  sam_08_VRAM, .bgName = "yki_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "sam_09",   .settings = & sam_09_settings,   .dmaStart =  sam_09_ROM_START,   .dmaEnd =  sam_09_ROM_END,   .dmaDest =  sam_09_VRAM, .bgName = "yki_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "sam_10",   .settings = & sam_10_settings,   .dmaStart =  sam_10_ROM_START,   .dmaEnd =  sam_10_ROM_END,   .dmaDest =  sam_10_VRAM, .bgName = "yki_bg", .songVariation = 1, .sfxReverb = 1 },
    { .id = "sam_11",   .settings = & sam_11_settings,   .dmaStart =  sam_11_ROM_START,   .dmaEnd =  sam_11_ROM_END,   .dmaDest =  sam_11_VRAM, .bgName = "yki_bg" },
    { .id = "sam_12",   .settings = & sam_12_settings,   .dmaStart =  sam_12_ROM_START,   .dmaEnd =  sam_12_ROM_END,   .dmaDest =  sam_12_VRAM, .bgName = "yki_bg", .songVariation = 1, .sfxReverb = 1 },
}
Shiver Region.
sbk_maps
MapConfig sbk_maps[]
Dry Dry Desert.
tik_maps
MapConfig tik_maps[]
Initial value:
= {
    { .id = "tik_01",   .settings = & tik_01_settings,   .dmaStart =  tik_01_ROM_START,   .dmaEnd =  tik_01_ROM_END,   .dmaDest =  tik_01_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_02",   .settings = & tik_02_settings,   .dmaStart =  tik_02_ROM_START,   .dmaEnd =  tik_02_ROM_END,   .dmaDest =  tik_02_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_03",   .settings = & tik_03_settings,   .dmaStart =  tik_03_ROM_START,   .dmaEnd =  tik_03_ROM_END,   .dmaDest =  tik_03_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_04",   .settings = & tik_04_settings,   .dmaStart =  tik_04_ROM_START,   .dmaEnd =  tik_04_ROM_END,   .dmaDest =  tik_04_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_05",   .settings = & tik_05_settings,   .dmaStart =  tik_05_ROM_START,   .dmaEnd =  tik_05_ROM_END,   .dmaDest =  tik_05_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_06",   .settings = & tik_06_settings,   .dmaStart =  tik_06_ROM_START,   .dmaEnd =  tik_06_ROM_END,   .dmaDest =  tik_06_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_07",   .settings = & tik_07_settings,   .dmaStart =  tik_07_ROM_START,   .dmaEnd =  tik_07_ROM_END,   .dmaDest =  tik_07_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_08",   .settings = & tik_08_settings,   .dmaStart =  tik_08_ROM_START,   .dmaEnd =  tik_08_ROM_END,   .dmaDest =  tik_08_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_09",   .settings = & tik_09_settings,   .dmaStart =  tik_09_ROM_START,   .dmaEnd =  tik_09_ROM_END,   .dmaDest =  tik_09_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_10",   .settings = & tik_10_settings,   .dmaStart =  tik_10_ROM_START,   .dmaEnd =  tik_10_ROM_END,   .dmaDest =  tik_10_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_12",   .settings = & tik_12_settings,   .dmaStart =  tik_12_ROM_START,   .dmaEnd =  tik_12_ROM_END,   .dmaDest =  tik_12_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_14",   .settings = & tik_14_settings,   .dmaStart =  tik_14_ROM_START,   .dmaEnd =  tik_14_ROM_END,   .dmaDest =  tik_14_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_15",   .settings = & tik_15_settings,   .dmaStart =  tik_15_ROM_START,   .dmaEnd =  tik_15_ROM_END,   .dmaDest =  tik_15_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_17",   .settings = & tik_17_settings,   .dmaStart =  tik_17_ROM_START,   .dmaEnd =  tik_17_ROM_END,   .dmaDest =  tik_17_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_18",   .settings = & tik_18_settings,   .dmaStart =  tik_18_ROM_START,   .dmaEnd =  tik_18_ROM_END,   .dmaDest =  tik_18_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_19",   .settings = & tik_19_settings,   .dmaStart =  tik_19_ROM_START,   .dmaEnd =  tik_19_ROM_END,   .dmaDest =  tik_19_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_20",   .settings = & tik_20_settings,   .dmaStart =  tik_20_ROM_START,   .dmaEnd =  tik_20_ROM_END,   .dmaDest =  tik_20_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_21",   .settings = & tik_21_settings,   .dmaStart =  tik_21_ROM_START,   .dmaEnd =  tik_21_ROM_END,   .dmaDest =  tik_21_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_22",   .settings = & tik_22_settings,   .dmaStart =  tik_22_ROM_START,   .dmaEnd =  tik_22_ROM_END,   .dmaDest =  tik_22_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_23",   .settings = & tik_23_settings,   .dmaStart =  tik_23_ROM_START,   .dmaEnd =  tik_23_ROM_END,   .dmaDest =  tik_23_VRAM, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_24",   .settings = & tik_24_settings,   .dmaStart =  tik_24_ROM_START,   .dmaEnd =  tik_24_ROM_END,   .dmaDest =  tik_24_VRAM,   .init = & tik_24_map_init, .songVariation = 1, .sfxReverb = 2 },
    { .id = "tik_25",   .settings = & tik_25_settings,   .dmaStart =  tik_25_ROM_START,   .dmaEnd =  tik_25_ROM_END,   .dmaDest =  tik_25_VRAM, .songVariation = 1, .sfxReverb = 2 },
}
Toad Town Tunnels.
trd_maps
MapConfig trd_maps[]
Initial value:
= {
    { .id = "trd_00",   .settings = & trd_00_settings,   .dmaStart =  trd_00_ROM_START,   .dmaEnd =  trd_00_ROM_END,   .dmaDest =  trd_00_VRAM, .bgName = "nok_bg" },
    { .id = "trd_01",   .settings = & trd_01_settings,   .dmaStart =  trd_01_ROM_START,   .dmaEnd =  trd_01_ROM_END,   .dmaDest =  trd_01_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "trd_02",   .settings = & trd_02_settings,   .dmaStart =  trd_02_ROM_START,   .dmaEnd =  trd_02_ROM_END,   .dmaDest =  trd_02_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "trd_03",   .settings = & trd_03_settings,   .dmaStart =  trd_03_ROM_START,   .dmaEnd =  trd_03_ROM_END,   .dmaDest =  trd_03_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "trd_04",   .settings = & trd_04_settings,   .dmaStart =  trd_04_ROM_START,   .dmaEnd =  trd_04_ROM_END,   .dmaDest =  trd_04_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "trd_05",   .settings = & trd_05_settings,   .dmaStart =  trd_05_ROM_START,   .dmaEnd =  trd_05_ROM_END,   .dmaDest =  trd_05_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "trd_06",   .settings = & trd_06_settings,   .dmaStart =  trd_06_ROM_START,   .dmaEnd =  trd_06_ROM_END,   .dmaDest =  trd_06_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "trd_07",   .settings = & trd_07_settings,   .dmaStart =  trd_07_ROM_START,   .dmaEnd =  trd_07_ROM_END,   .dmaDest =  trd_07_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "trd_08",   .settings = & trd_08_settings,   .dmaStart =  trd_08_ROM_START,   .dmaEnd =  trd_08_ROM_END,   .dmaDest =  trd_08_VRAM, .songVariation = 1, .sfxReverb = 3 },
    { .id = "trd_09",   .settings = & trd_09_settings,   .dmaStart =  trd_09_ROM_START,   .dmaEnd =  trd_09_ROM_END,   .dmaDest =  trd_09_VRAM, .bgName = "nok_bg" },
    { .id = "trd_10",   .settings = & trd_10_settings,   .dmaStart =  trd_10_ROM_START,   .dmaEnd =  trd_10_ROM_END,   .dmaDest =  trd_10_VRAM, .songVariation = 1, .sfxReverb = 3 },
}
Koopa Bros. Fortress.
tst_maps
MapConfig tst_maps[]
Initial value:
= {
    { .id = "tst_01",   .settings = & tst_01_settings,   .dmaStart =  tst_01_ROM_START,   .dmaEnd =  tst_01_ROM_END,   .dmaDest =  tst_01_VRAM, .bgName = "nok_bg" },
    { .id = "tst_02",   .settings = & tst_02_settings,   .dmaStart =  tst_02_ROM_START,   .dmaEnd =  tst_02_ROM_END,   .dmaDest =  tst_02_VRAM, .bgName = "nok_bg" },
    { .id = "tst_03",   .settings = & tst_03_settings,   .dmaStart =  tst_03_ROM_START,   .dmaEnd =  tst_03_ROM_END,   .dmaDest =  tst_03_VRAM, .bgName = "nok_bg" },
    { .id = "tst_04",   .settings = & tst_04_settings,   .dmaStart =  tst_04_ROM_START,   .dmaEnd =  tst_04_ROM_END,   .dmaDest =  tst_04_VRAM, .bgName = "nok_bg" },
    { .id = "tst_10",   .settings = & tst_10_settings,   .dmaStart =  tst_10_ROM_START,   .dmaEnd =  tst_10_ROM_END,   .dmaDest =  tst_10_VRAM, .bgName = "nok_bg" },
    { .id = "tst_11",   .settings = & tst_11_settings,   .dmaStart =  tst_11_ROM_START,   .dmaEnd =  tst_11_ROM_END,   .dmaDest =  tst_11_VRAM, .bgName = "nok_bg" },
    { .id = "tst_12",   .settings = & tst_12_settings,   .dmaStart =  tst_12_ROM_START,   .dmaEnd =  tst_12_ROM_END,   .dmaDest =  tst_12_VRAM, .bgName = "nok_bg" },
    { .id = "tst_13",   .settings = & tst_13_settings,   .dmaStart =  tst_13_ROM_START,   .dmaEnd =  tst_13_ROM_END,   .dmaDest =  tst_13_VRAM, .bgName = "nok_bg" },
    { .id = "tst_20",   .settings = & tst_20_settings,   .dmaStart =  tst_20_ROM_START,   .dmaEnd =  tst_20_ROM_END,   .dmaDest =  tst_20_VRAM, .bgName = "nok_bg" },
}
Debug.
wMapBgName
char wMapBgName[0x14]
Referenced by load_map_by_IDs(), and map_init().
wMapHitName
char wMapHitName[0x18]
Referenced by load_map_by_IDs(), load_map_hit_asset(), and map_init().
wMapShapeName
char wMapShapeName[0x18]
Referenced by load_map_by_IDs(), map_init(), state_step_end_battle(), state_step_exit_language_select(), and state_step_unpause().
wMapTexName
char wMapTexName[0x18]
Referenced by load_map_by_IDs(), map_init(), and state_step_end_battle().
WorldReverbModeMapping
s32 WorldReverbModeMapping[] = { 0, 1, 2, 3 }
Referenced by load_map_by_IDs().