papermario: src/world/partner/kooper.c File Reference
kooper.c File Reference
Macros
#define NAMESPACE world_kooper
#define USE_STATE functionTemp[0]
#define TEST_COLLISION_AT_ANGLE(testAngle)
Enumerations
enum { SHELL_TOSS_HITBOX_DISABLED = 0 , SHELL_TOSS_HITBOX_ENABLED = 1 , SHELL_TOSS_HITBOX_HIT_ENEMY = 2 }
Functions
s32 entity_try_partner_interaction_trigger (s32)
s32 test_item_entity_position (f32, f32, f32, f32)
s32 npc_raycast_up_corner (s32 ignoreFlags, f32 *x, f32 *y, f32 *z, f32 *length)
void fx_damage_stars (s32, f32, f32, f32, f32, f32, f32, s32)
void auto_collect_item_entity (s32)
s32 lateral_hit_interactable_entity (Npc *npc)
void vertical_hit_interactable_entity (Npc *kooper)
s32 check_for_item_collision (Npc *kooper)
void init (Npc *kooper)
void try_cancel_tweester (Npc *kooper)
s32 test_first_strike (Npc *kooper, Npc *enemy)
void pre_battle (Npc *kooper)
void post_battle (Npc *npc)
Variables
BSS s32 ShellTossHoldTime
BSS s32 TriggeredBattle
BSS s32 PlayerWasFacingLeft
BSS s32 D_802BEC5C
BSS s32 ShellTossKickFalling
BSS b32 LockingPlayerInput
BSS s32 HeldItemIdx
BSS s32 HasItem
BSS f32 ShellTossPosX
BSS f32 ShellTossPosY
BSS f32 ShellTossPosZ
BSS s32 D_802BEC7C
s32 ShellTossHitboxState = SHELL_TOSS_HITBOX_DISABLED
EvtScript EVS_WorldKooper_TakeOut
BSS TweesterPhysics TweesterPhysicsData
TweesterPhysics * TweesterPhysicsPtr = & TweesterPhysicsData
EvtScript EVS_WorldKooper_Update
EvtScript EVS_WorldKooper_UseAbility
EvtScript EVS_WorldKooper_PutAway
Macro Definition Documentation
NAMESPACE
#define NAMESPACE world_kooper
TEST_COLLISION_AT_ANGLE
#define TEST_COLLISION_AT_ANGLE (testAngle)
Value:
                ( \
                posX = kooper->pos.x, \
                posY = kooper->pos.y, \
                posZ = kooper->pos.z, \
                npc_test_move_taller_with_slipping(COLLIDER_FLAG_IGNORE_SHELL, \
                    &posX, &posY, &posZ, kooper->moveSpeed, testAngle,  \
                    kooper->collisionHeight, kooper->collisionDiameter / 2) \
                )
USE_STATE
#define USE_STATE functionTemp[0]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SHELL_TOSS_HITBOX_DISABLED
SHELL_TOSS_HITBOX_ENABLED
SHELL_TOSS_HITBOX_HIT_ENEMY
Function Documentation
auto_collect_item_entity()
void auto_collect_item_entity (s32 index)
check_for_item_collision()
s32 check_for_item_collision (Npc * kooper)
entity_try_partner_interaction_trigger()
s32 entity_try_partner_interaction_trigger (s32 entityIdx)
Referenced by lateral_hit_interactable_entity(), and vertical_hit_interactable_entity().
fx_damage_stars()
void fx_damage_stars (s32 , f32 , f32 , f32 , f32 , f32 , f32 , s32)
Referenced by entity_StarBoxLauncher_check_launch(), OnDefeatEnemy(), PlayEffect(), and update_encounters_neutral().
init()
void init (Npc * kooper)
lateral_hit_interactable_entity()
s32 lateral_hit_interactable_entity (Npc * npc)
npc_raycast_up_corner()
s32 npc_raycast_up_corner (s32 ignoreFlags, f32 * x, f32 * y, f32 * z, f32 * length)
Referenced by npc_raycast_up_corners().
post_battle()
void post_battle (Npc * npc)
pre_battle()
void pre_battle (Npc * kooper)
test_first_strike()
s32 test_first_strike (Npc * kooper, Npc * enemy)
test_item_entity_position()
s32 test_item_entity_position (f32 x, f32 y, f32 z, f32 dist)
Referenced by check_for_item_collision().
try_cancel_tweester()
void try_cancel_tweester (Npc * kooper)
vertical_hit_interactable_entity()
void vertical_hit_interactable_entity (Npc * kooper)
Variable Documentation
D_802BEC5C
BSS s32 D_802BEC5C
D_802BEC7C
BSS s32 D_802BEC7C
EVS_WorldKooper_PutAway
EvtScript EVS_WorldKooper_PutAway
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_WorldKooper_TakeOut
EvtScript EVS_WorldKooper_TakeOut
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_WorldKooper_Update
EvtScript EVS_WorldKooper_Update
Initial value:
= {
    EVT_RETURN
    EVT_END
}
EVS_WorldKooper_UseAbility
EvtScript EVS_WorldKooper_UseAbility
Initial value:
= {
    EVT_RETURN
    EVT_END
}
HasItem
BSS s32 HasItem
Referenced by check_for_item_collision().
HeldItemIdx
BSS s32 HeldItemIdx
Referenced by check_for_item_collision().
LockingPlayerInput
BSS b32 LockingPlayerInput
Referenced by pre_battle().
PlayerWasFacingLeft
BSS s32 PlayerWasFacingLeft
ShellTossHitboxState
s32 ShellTossHitboxState = SHELL_TOSS_HITBOX_DISABLED
Referenced by pre_battle(), and test_first_strike().
ShellTossHoldTime
BSS s32 ShellTossHoldTime
ShellTossKickFalling
BSS s32 ShellTossKickFalling
ShellTossPosX
BSS f32 ShellTossPosX
ShellTossPosY
BSS f32 ShellTossPosY
ShellTossPosZ
BSS f32 ShellTossPosZ
TriggeredBattle
BSS s32 TriggeredBattle
Referenced by init(), post_battle(), and pre_battle().
TweesterPhysicsData
BSS TweesterPhysics TweesterPhysicsData
TweesterPhysicsPtr
TweesterPhysics* TweesterPhysicsPtr = & TweesterPhysicsData
Referenced by try_cancel_tweester().