papermario: src/world/action/hammer.c File Reference
hammer.c File Reference
Data Structures
struct HammerHitData
Enumerations
enum { SUBSTATE_HAMMER_0 = 0 , SUBSTATE_HAMMER_1 = 1 , SUBSTATE_HAMMER_2 = 2 }
Functions
void action_hammer_end_swing (void)
s32 action_hammer_is_swinging_away (s32 animID)
void action_hammer_play_hit_fx (s32 hitID)
HitID action_hammer_test_swing_collision (void)
void action_update_hammer (void)
Variables
BSS HammerHitData D_802B6E90
HammerHitData * HammerHit = &D_802B6E90
Data Structure Documentation
HammerHitData
struct HammerHitData
Data Fields
s32 hitID
Vec3f hitPos
s32 timer
s32 unk_0C
s32 unk_14
s32 unk_1C
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SUBSTATE_HAMMER_0
SUBSTATE_HAMMER_1
SUBSTATE_HAMMER_2
Function Documentation
action_hammer_end_swing()
void action_hammer_end_swing (void)
Referenced by action_update_hammer().
action_hammer_is_swinging_away()
s32 action_hammer_is_swinging_away (s32 animID)
Referenced by action_hammer_end_swing(), and action_hammer_test_swing_collision().
action_hammer_play_hit_fx()
void action_hammer_play_hit_fx (s32 hitID)
Referenced by action_hammer_end_swing().
action_hammer_test_swing_collision()
HitID action_hammer_test_swing_collision (void)
Referenced by action_update_hammer().
action_update_hammer()
void action_update_hammer (void)
Variable Documentation
D_802B6E90
BSS HammerHitData D_802B6E90
HammerHit
HammerHitData* HammerHit = &D_802B6E90
Referenced by action_hammer_end_swing(), action_hammer_play_hit_fx(), action_hammer_test_swing_collision(), and action_update_hammer().