papermario: src/world/action/jump.c File Reference
jump.c File Reference
Functions
void initialize_jump (void)
void action_update_peach_step_down (void)
void action_update_peach_falling (void)
void action_update_jump (void)
void action_update_landing_on_switch (void)
void action_update_falling (void)
void action_update_step_down (void)
Variables
f32 JumpedOnSwitchX
f32 JumpedOnSwitchZ
Function Documentation
action_update_falling()
void action_update_falling (void)
action_update_jump()
void action_update_jump (void)
Referenced by action_update_step_down().
action_update_landing_on_switch()
void action_update_landing_on_switch (void)
action_update_peach_falling()
void action_update_peach_falling (void)
Referenced by action_update_falling().
action_update_peach_step_down()
void action_update_peach_step_down (void)
Referenced by action_update_step_down().
action_update_step_down()
void action_update_step_down (void)
initialize_jump()
void initialize_jump (void)
Referenced by action_update_jump(), and action_update_landing_on_switch().
Variable Documentation
JumpedOnSwitchX
f32 JumpedOnSwitchX extern
Referenced by action_update_landing_on_switch(), and handle_jumping_land_on_switch().
JumpedOnSwitchZ
f32 JumpedOnSwitchZ extern
Referenced by action_update_landing_on_switch(), and handle_jumping_land_on_switch().