var searchData=
[
  ['hammerhitdata_0',['HammerHitData',['../world_2action_2hammer_8c.html#structHammerHitData',1,'']]],
  ['heapnode_1',['HeapNode',['../common__structs_8h.html#structHeapNode',1,'']]],
  ['heartblockcontentdata_2',['HeartBlockContentData',['../entity_8h.html#structHeartBlockContentData',1,'']]],
  ['hiddenpaneldata_3',['HiddenPanelData',['../entity_8h.html#structHiddenPanelData',1,'']]],
  ['hiddenpanelsdata_4',['HiddenPanelsData',['../common__structs_8h.html#structHiddenPanelsData',1,'']]],
  ['hieroglyphsfxdata_5',['HieroglyphsFXData',['../effects_8h.html#structHieroglyphsFXData',1,'']]],
  ['hitassetcollider_6',['HitAssetCollider',['../collision_8c.html#structHitAssetCollider',1,'']]],
  ['hitfile_7',['HitFile',['../collision_8c.html#structHitFile',1,'']]],
  ['hitfileheader_8',['HitFileHeader',['../collision_8c.html#structHitFileHeader',1,'']]],
  ['hudcacheentry_9',['HudCacheEntry',['../hud__element_8h.html#structHudCacheEntry',1,'']]],
  ['hudcomplexstatusicon_10',['HudComplexStatusIcon',['../status__icons_8c.html#structHudComplexStatusIcon',1,'']]],
  ['hudelement_11',['HudElement',['../hud__element_8h.html#structHudElement',1,'']]],
  ['hudelementsize_12',['HudElementSize',['../hud__element_8c.html#structHudElementSize',1,'']]],
  ['hudsimplestatusicon_13',['HudSimpleStatusIcon',['../status__icons_8c.html#structHudSimpleStatusIcon',1,'']]],
  ['hudstatusicon_14',['HudStatusIcon',['../status__icons_8c.html#structHudStatusIcon',1,'']]],
  ['hudtransform_15',['HudTransform',['../hud__element_8h.html#structHudTransform',1,'']]],
  ['huffpuffbreathfxdata_16',['HuffPuffBreathFXData',['../effects_8h.html#structHuffPuffBreathFXData',1,'']]],
  ['hurricanestate_17',['HurricaneState',['../battle_2partner_2lakilester_8c.html#structHurricaneState',1,'']]]
];
