var searchData=
[
  ['game_2ec_0',['game.c',['../obk__04_2game_8c.html',1,'(Global Namespace)'],['../obk__08_2game_8c.html',1,'(Global Namespace)']]],
  ['game_5fmodes_2ec_1',['game_modes.c',['../game__modes_8c.html',1,'']]],
  ['game_5fmodes_2eh_2',['game_modes.h',['../game__modes_8h.html',1,'']]],
  ['game_5fstates_2ec_3',['game_states.c',['../game__states_8c.html',1,'']]],
  ['gate_2ec_4',['gate.c',['../mim__01_2gate_8c.html',1,'(Global Namespace)'],['../mim__02_2gate_8c.html',1,'(Global Namespace)'],['../mim__03_2gate_8c.html',1,'(Global Namespace)'],['../mim__04_2gate_8c.html',1,'(Global Namespace)'],['../mim__05_2gate_8c.html',1,'(Global Namespace)'],['../mim__06_2gate_8c.html',1,'(Global Namespace)'],['../mim__07_2gate_8c.html',1,'(Global Namespace)'],['../mim__08_2gate_8c.html',1,'(Global Namespace)'],['../mim__09_2gate_8c.html',1,'(Global Namespace)'],['../mim__11_2gate_8c.html',1,'(Global Namespace)'],['../mim__12_2gate_8c.html',1,'(Global Namespace)']]],
  ['gateflower_2eh_5',['GateFlower.h',['../GateFlower_8h.html',1,'']]],
  ['gateflower_2einc_2ec_6',['GateFlower.inc.c',['../GateFlower_8inc_8c.html',1,'']]],
  ['gather_5fenergy_5fpink_2ec_7',['gather_energy_pink.c',['../gather__energy__pink_8c.html',1,'(Global Namespace)'],['../gfx_2gather__energy__pink_8c.html',1,'(Global Namespace)']]],
  ['gather_5fmagic_2ec_8',['gather_magic.c',['../gather__magic_8c.html',1,'(Global Namespace)'],['../gfx_2gather__magic_8c.html',1,'(Global Namespace)']]],
  ['gbi_5fcustom_2eh_9',['gbi_custom.h',['../gbi__custom_8h.html',1,'']]],
  ['gears_2ec_10',['gears.c',['../gears_8c.html',1,'']]],
  ['general_5fguy_2ec_11',['general_guy.c',['../general__guy_8c.html',1,'']]],
  ['general_5fheap_5fcreate_5fobfuscated_2ec_12',['general_heap_create_obfuscated.c',['../general__heap__create__obfuscated_8c.html',1,'']]],
  ['generichitboxdefeat_2einc_2ec_13',['GenericHitboxDefeat.inc.c',['../GenericHitboxDefeat_8inc_8c.html',1,'']]],
  ['getdefeatedenemycount_2einc_2ec_14',['GetDefeatedEnemyCount.inc.c',['../GetDefeatedEnemyCount_8inc_8c.html',1,'']]],
  ['getencounterenemyisowner_2einc_2ec_15',['GetEncounterEnemyIsOwner.inc.c',['../GetEncounterEnemyIsOwner_8inc_8c.html',1,'']]],
  ['getentityposition_2einc_2ec_16',['GetEntityPosition.inc.c',['../GetEntityPosition_8inc_8c.html',1,'']]],
  ['getfirsttrianglenormal_2einc_2ec_17',['GetFirstTriangleNormal.inc.c',['../GetFirstTriangleNormal_8inc_8c.html',1,'']]],
  ['getfloorcollider_2einc_2ec_18',['GetFloorCollider.inc.c',['../GetFloorCollider_8inc_8c.html',1,'']]],
  ['geticonbrightnessforangle_2einc_2ec_19',['GetIconBrightnessForAngle.inc.c',['../GetIconBrightnessForAngle_8inc_8c.html',1,'']]],
  ['getintoshell_2einc_2ec_20',['GetIntoShell.inc.c',['../GetIntoShell_8inc_8c.html',1,'']]],
  ['getitememptycount_2einc_2ec_21',['GetItemEmptyCount.inc.c',['../GetItemEmptyCount_8inc_8c.html',1,'']]],
  ['getitementityposition_2einc_2ec_22',['GetItemEntityPosition.inc.c',['../GetItemEntityPosition_8inc_8c.html',1,'']]],
  ['getitemname_2einc_2ec_23',['GetItemName.inc.c',['../GetItemName_8inc_8c.html',1,'']]],
  ['getjumphammercharge_2einc_2ec_24',['GetJumpHammerCharge.inc.c',['../GetJumpHammerCharge_8inc_8c.html',1,'']]],
  ['getkammybroomemitterpos_2einc_2ec_25',['GetKammyBroomEmitterPos.inc.c',['../GetKammyBroomEmitterPos_8inc_8c.html',1,'']]],
  ['getlasteventtype_2einc_2ec_26',['GetLastEventType.inc.c',['../GetLastEventType_8inc_8c.html',1,'']]],
  ['getleftrightpoints_2einc_2ec_27',['GetLeftRightPoints.inc.c',['../GetLeftRightPoints_8inc_8c.html',1,'']]],
  ['getnpccollisionheight_2einc_2ec_28',['GetNpcCollisionHeight.inc.c',['../GetNpcCollisionHeight_8inc_8c.html',1,'']]],
  ['getpeachdisguise_2einc_2ec_29',['GetPeachDisguise.inc.c',['../GetPeachDisguise_8inc_8c.html',1,'']]],
  ['getplayercoins_2einc_2ec_30',['GetPlayerCoins.inc.c',['../GetPlayerCoins_8inc_8c.html',1,'']]],
  ['getplayerhppercent_2einc_2ec_31',['GetPlayerHpPercent.inc.c',['../GetPlayerHpPercent_8inc_8c.html',1,'']]],
  ['getselectedmoveid_2einc_2ec_32',['GetSelectedMoveID.inc.c',['../GetSelectedMoveID_8inc_8c.html',1,'']]],
  ['gfx_2ec_33',['gfx.c',['../gfx_8c.html',1,'']]],
  ['ghost_5fbombette_2einc_2ec_34',['ghost_bombette.inc.c',['../ghost__bombette_8inc_8c.html',1,'']]],
  ['ghost_5fbow_2einc_2ec_35',['ghost_bow.inc.c',['../ghost__bow_8inc_8c.html',1,'']]],
  ['ghost_5fgoombario_2einc_2ec_36',['ghost_goombario.inc.c',['../ghost__goombario_8inc_8c.html',1,'']]],
  ['ghost_5fkooper_2einc_2ec_37',['ghost_kooper.inc.c',['../ghost__kooper_8inc_8c.html',1,'']]],
  ['ghost_5flakilester_2einc_2ec_38',['ghost_lakilester.inc.c',['../ghost__lakilester_8inc_8c.html',1,'']]],
  ['ghost_5fparakarry_2einc_2ec_39',['ghost_parakarry.inc.c',['../ghost__parakarry_8inc_8c.html',1,'']]],
  ['ghost_5fsushie_2einc_2ec_40',['ghost_sushie.inc.c',['../ghost__sushie_8inc_8c.html',1,'']]],
  ['ghost_5fwatt_2einc_2ec_41',['ghost_watt.inc.c',['../ghost__watt_8inc_8c.html',1,'']]],
  ['givereward_2einc_2ec_42',['GiveReward.inc.c',['../GiveReward_8inc_8c.html',1,'']]],
  ['gizmos_2ec_43',['gizmos.c',['../omo__01_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__02_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__03_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__04_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__05_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__06_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__07_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__09_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__10_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__11_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__13_2gizmos_8c.html',1,'(Global Namespace)'],['../omo__17_2gizmos_8c.html',1,'(Global Namespace)']]],
  ['glassshimmer_2einc_2ec_44',['GlassShimmer.inc.c',['../GlassShimmer_8inc_8c.html',1,'']]],
  ['global_5fhud_5fscripts_2ec_45',['global_hud_scripts.c',['../global__hud__scripts_8c.html',1,'']]],
  ['gloomba_2ec_46',['gloomba.c',['../gloomba_8c.html',1,'']]],
  ['gloomba_2eh_47',['Gloomba.h',['../Gloomba_8h.html',1,'']]],
  ['gloomba_2einc_2ec_48',['gloomba.inc.c',['../gloomba_8inc_8c.html',1,'']]],
  ['gloomba_5fwander_2einc_2ec_49',['Gloomba_Wander.inc.c',['../Gloomba__Wander_8inc_8c.html',1,'']]],
  ['goomba_2ec_50',['goomba.c',['../kmr__part__1_2actor_2goomba_8c.html',1,'(Global Namespace)'],['../nok_2actor_2goomba_8c.html',1,'(Global Namespace)'],['../omo3_2actor_2goomba_8c.html',1,'(Global Namespace)']]],
  ['goomba_2eh_51',['Goomba.h',['../Goomba_8h.html',1,'']]],
  ['goomba_2einc_2ec_52',['goomba.inc.c',['../goomba_8inc_8c.html',1,'']]],
  ['goomba_2einc_2ec_53',['Goomba.inc.c',['../Goomba_8inc_8c.html',1,'']]],
  ['goomba_5fbros_5fcommon_2eh_54',['goomba_bros_common.h',['../goomba__bros__common_8h.html',1,'']]],
  ['goomba_5fking_2ec_55',['goomba_king.c',['../battle_2area_2kmr__part__2_2actor_2goomba__king_8c.html',1,'(Global Namespace)'],['../world_2area__mac_2machi_2goomba__king_8c.html',1,'(Global Namespace)']]],
  ['goomba_5fking_5fcommon_2eh_56',['goomba_king_common.h',['../goomba__king__common_8h.html',1,'']]],
  ['goomba_5fwander_2einc_2ec_57',['Goomba_Wander.inc.c',['../Goomba__Wander_8inc_8c.html',1,'']]],
  ['goombabros_2eh_58',['GoombaBros.h',['../GoombaBros_8h.html',1,'']]],
  ['goombabros_5fguard_2einc_2ec_59',['GoombaBros_Guard.inc.c',['../GoombaBros__Guard_8inc_8c.html',1,'']]],
  ['goombafamily_2eh_60',['GoombaFamily.h',['../GoombaFamily_8h.html',1,'']]],
  ['goombafamily_2einc_2ec_61',['GoombaFamily.inc.c',['../GoombaFamily_8inc_8c.html',1,'']]],
  ['goombafamily_5fwander_2einc_2ec_62',['GoombaFamily_Wander.inc.c',['../GoombaFamily__Wander_8inc_8c.html',1,'']]],
  ['goombaria_2ec_63',['goombaria.c',['../goombaria_8c.html',1,'']]],
  ['goombaria_2eh_64',['Goombaria.h',['../Goombaria_8h.html',1,'']]],
  ['goombaria_2eh_65',['goombaria.h',['../goombaria_8h.html',1,'']]],
  ['goombaria_5fstationary_2einc_2ec_66',['Goombaria_Stationary.inc.c',['../Goombaria__Stationary_8inc_8c.html',1,'']]],
  ['goombario_2ec_67',['goombario.c',['../battle_2partner_2goombario_8c.html',1,'(Global Namespace)'],['../world_2partner_2goombario_8c.html',1,'(Global Namespace)']]],
  ['goombario_2eh_68',['goombario.h',['../goombario_8h.html',1,'']]],
  ['goombario_5ftutor_2ec_69',['goombario_tutor.c',['../goombario__tutor_8c.html',1,'']]],
  ['goomnut_5ftree_2ec_70',['goomnut_tree.c',['../goomnut__tree_8c.html',1,'']]],
  ['goompa_2ec_71',['goompa.c',['../battle_2partner_2goompa_8c.html',1,'(Global Namespace)'],['../world_2partner_2goompa_8c.html',1,'(Global Namespace)']]],
  ['goompa_2eh_72',['goompa.h',['../goompa_8h.html',1,'']]],
  ['got_5fitem_5foutline_2ec_73',['got_item_outline.c',['../gfx_2got__item__outline_8c.html',1,'(Global Namespace)'],['../got__item__outline_8c.html',1,'(Global Namespace)']]],
  ['gourmet_2ec_74',['gourmet.c',['../gourmet_8c.html',1,'']]],
  ['gourmetguy_2eh_75',['GourmetGuy.h',['../GourmetGuy_8h.html',1,'']]],
  ['gourmetguy_2einc_2ec_76',['GourmetGuy.inc.c',['../GourmetGuy_8inc_8c.html',1,'']]],
  ['gray_5fmagikoopa_2ec_77',['gray_magikoopa.c',['../pra_2actor_2gray__magikoopa_8c.html',1,'(Global Namespace)'],['../pra3_2actor_2gray__magikoopa_8c.html',1,'(Global Namespace)'],['../sam_2actor_2gray__magikoopa_8c.html',1,'(Global Namespace)'],['../sam2_2actor_2gray__magikoopa_8c.html',1,'(Global Namespace)']]],
  ['gray_5fmagikoopa_2einc_2ec_78',['gray_magikoopa.inc.c',['../gray__magikoopa_8inc_8c.html',1,'']]],
  ['green_5fimpact_2ec_79',['green_impact.c',['../gfx_2green__impact_8c.html',1,'(Global Namespace)'],['../green__impact_8c.html',1,'(Global Namespace)']]],
  ['green_5fmagikoopa_2ec_80',['green_magikoopa.c',['../flo_2actor_2green__magikoopa_8c.html',1,'(Global Namespace)'],['../pra_2actor_2green__magikoopa_8c.html',1,'(Global Namespace)']]],
  ['green_5fmagikoopa_2einc_2ec_81',['green_magikoopa.inc.c',['../green__magikoopa_8inc_8c.html',1,'']]],
  ['green_5fshy_5fguy_2ec_82',['green_shy_guy.c',['../green__shy__guy_8c.html',1,'']]],
  ['green_5fshy_5fguy_2einc_2ec_83',['green_shy_guy.inc.c',['../green__shy__guy_8inc_8c.html',1,'']]],
  ['greenstompswitch_2ec_84',['GreenStompSwitch.c',['../GreenStompSwitch_8c.html',1,'']]],
  ['groove_5fguy_2ec_85',['groove_guy.c',['../groove__guy_8c.html',1,'']]],
  ['groove_5fguy_2einc_2ec_86',['groove_guy.inc.c',['../groove__guy_8inc_8c.html',1,'']]],
  ['grooveguy_2eh_87',['GrooveGuy.h',['../GrooveGuy_8h.html',1,'']]],
  ['grooveguy_2einc_2ec_88',['GrooveGuy.inc.c',['../GrooveGuy_8inc_8c.html',1,'']]],
  ['grooveguyai_2einc_2ec_89',['GrooveGuyAI.inc.c',['../GrooveGuyAI_8inc_8c.html',1,'']]],
  ['guardai_2einc_2ec_90',['GuardAI.inc.c',['../GuardAI_8inc_8c.html',1,'']]],
  ['gulpit_2ec_91',['gulpit.c',['../gulpit_8c.html',1,'']]],
  ['gulpit_2eh_92',['Gulpit.h',['../Gulpit_8h.html',1,'']]],
  ['gulpit_2einc_2ec_93',['gulpit.inc.c',['../gulpit_8inc_8c.html',1,'']]],
  ['gulpit_2einc_2ec_94',['Gulpit.inc.c',['../Gulpit_8inc_8c.html',1,'']]],
  ['gulpit_5frocks_2ec_95',['gulpit_rocks.c',['../gulpit__rocks_8c.html',1,'']]],
  ['gulpit_5frocks_2einc_2ec_96',['gulpit_rocks.inc.c',['../gulpit__rocks_8inc_8c.html',1,'']]],
  ['gv_2eh_97',['gv.h',['../gv_8h.html',1,'']]],
  ['gv_5f01_2eh_98',['gv_01.h',['../gv__01_8h.html',1,'']]],
  ['gv_5f01_5fhit_2eh_99',['gv_01_hit.h',['../gv__01__hit_8h.html',1,'']]],
  ['gv_5f01_5fshape_2eh_100',['gv_01_shape.h',['../gv__01__shape_8h.html',1,'']]]
];
