var searchData=
[
  ['radial_5fshimmer_2ec_0',['radial_shimmer.c',['../gfx_2radial__shimmer_8c.html',1,'(Global Namespace)'],['../radial__shimmer_8c.html',1,'(Global Namespace)']]],
  ['radiating_5fenergy_5forb_2ec_1',['radiating_energy_orb.c',['../gfx_2radiating__energy__orb_8c.html',1,'(Global Namespace)'],['../radiating__energy__orb_8c.html',1,'(Global Namespace)']]],
  ['randomflowers_2einc_2ec_2',['RandomFlowers.inc.c',['../RandomFlowers_8inc_8c.html',1,'']]],
  ['rangedattackai_2einc_2ec_3',['RangedAttackAI.inc.c',['../RangedAttackAI_8inc_8c.html',1,'']]],
  ['raphaelraven_2eh_4',['RaphaelRaven.h',['../RaphaelRaven_8h.html',1,'']]],
  ['raphaelraven_2einc_2ec_5',['RaphaelRaven.inc.c',['../RaphaelRaven_8inc_8c.html',1,'']]],
  ['raven_2eh_6',['Raven.h',['../Raven_8h.html',1,'']]],
  ['raven_2einc_2ec_7',['Raven.inc.c',['../Raven_8inc_8c.html',1,'']]],
  ['read_5ffortune_2einc_2ec_8',['read_fortune.inc.c',['../read__fortune_8inc_8c.html',1,'']]],
  ['recover_2ec_9',['recover.c',['../gfx_2recover_8c.html',1,'(Global Namespace)'],['../recover_8c.html',1,'(Global Namespace)']]],
  ['red_5fgoomba_5f1_2ec_10',['red_goomba_1.c',['../red__goomba__1_8c.html',1,'']]],
  ['red_5fgoomba_5f2_2ec_11',['red_goomba_2.c',['../red__goomba__2_8c.html',1,'']]],
  ['red_5fimpact_2ec_12',['red_impact.c',['../red__impact_8c.html',1,'']]],
  ['red_5fmagikoopa_2ec_13',['red_magikoopa.c',['../flo_2actor_2red__magikoopa_8c.html',1,'(Global Namespace)'],['../kzn_2actor_2red__magikoopa_8c.html',1,'(Global Namespace)'],['../pra_2actor_2red__magikoopa_8c.html',1,'(Global Namespace)'],['../pra3_2actor_2red__magikoopa_8c.html',1,'(Global Namespace)']]],
  ['red_5fmagikoopa_2einc_2ec_14',['red_magikoopa.inc.c',['../red__magikoopa_8inc_8c.html',1,'']]],
  ['red_5fshy_5fguy_2ec_15',['red_shy_guy.c',['../dig_2actor_2red__shy__guy_8c.html',1,'(Global Namespace)'],['../omo_2actor_2red__shy__guy_8c.html',1,'(Global Namespace)'],['../omo3_2actor_2red__shy__guy_8c.html',1,'(Global Namespace)']]],
  ['red_5fshy_5fguy_2einc_2ec_16',['red_shy_guy.inc.c',['../red__shy__guy_8inc_8c.html',1,'']]],
  ['redblock_2ec_17',['RedBlock.c',['../RedBlock_8c.html',1,'']]],
  ['redswitch_2ec_18',['RedSwitch.c',['../RedSwitch_8c.html',1,'']]],
  ['reflection_2edata_2einc_2ec_19',['Reflection.data.inc.c',['../Reflection_8data_8inc_8c.html',1,'']]],
  ['reflection_2einc_2ec_20',['Reflection.inc.c',['../Reflection_8inc_8c.html',1,'']]],
  ['refresh_2ec_21',['refresh.c',['../refresh_8c.html',1,'']]],
  ['removechillout_2einc_2ec_22',['RemoveChillOut.inc.c',['../RemoveChillOut_8inc_8c.html',1,'']]],
  ['removepadlock_2einc_2ec_23',['RemovePadlock.inc.c',['../RemovePadlock_8inc_8c.html',1,'']]],
  ['repel_5fgel_2ec_24',['repel_gel.c',['../repel__gel_8c.html',1,'']]],
  ['restorefrompeachstate_2einc_2ec_25',['RestoreFromPeachState.inc.c',['../RestoreFromPeachState_8inc_8c.html',1,'']]],
  ['reverb_2ec_26',['reverb.c',['../reverb_8c.html',1,'']]],
  ['ring_5fblast_2ec_27',['ring_blast.c',['../gfx_2ring__blast_8c.html',1,'(Global Namespace)'],['../ring__blast_8c.html',1,'(Global Namespace)']]],
  ['rising_5fbubble_2ec_28',['rising_bubble.c',['../gfx_2rising__bubble_8c.html',1,'(Global Namespace)'],['../rising__bubble_8c.html',1,'(Global Namespace)']]],
  ['rockingchair_2einc_2ec_29',['RockingChair.inc.c',['../RockingChair_8inc_8c.html',1,'']]],
  ['rockinghorse_2einc_2ec_30',['RockingHorse.inc.c',['../RockingHorse_8inc_8c.html',1,'']]],
  ['rooms_2ec_31',['rooms.c',['../rooms_8c.html',1,'']]],
  ['rosie_2eh_32',['Rosie.h',['../Rosie_8h.html',1,'']]],
  ['rosie_2einc_2ec_33',['Rosie.inc.c',['../Rosie_8inc_8c.html',1,'']]],
  ['rowf_5fand_5frhuff_2einc_2ec_34',['rowf_and_rhuff.inc.c',['../rowf__and__rhuff_8inc_8c.html',1,'']]],
  ['ruff_5fpuff_2ec_35',['ruff_puff.c',['../ruff__puff_8c.html',1,'']]],
  ['ruff_5fpuff_2einc_2ec_36',['ruff_puff.inc.c',['../ruff__puff_8inc_8c.html',1,'']]],
  ['ruffpuff_2eh_37',['RuffPuff.h',['../RuffPuff_8h.html',1,'']]],
  ['ruffpuff_2einc_2ec_38',['RuffPuff.inc.c',['../RuffPuff_8inc_8c.html',1,'']]],
  ['rumble_2ec_39',['rumble.c',['../rumble_8c.html',1,'']]],
  ['rumble_2eh_40',['rumble.h',['../rumble_8h.html',1,'']]],
  ['russ_5fand_5fthief_2einc_2ec_41',['russ_and_thief.inc.c',['../russ__and__thief_8inc_8c.html',1,'']]]
];
